### ISSUE TITLE
Improve the "Introduction" Content

### ISSUE THREAD

**Issue by caseydavenport** [projectcalico/calico#1]
So that users who come to Calico understand the value proposition that Calico offers and the use-cases it tries to solve.

It is important that people who are new to Calico understand _why_ someone would want to use it, as well as how it works.  This probably serves twofold:
- Make more people realize that they actually do want Calico to meet their use-case.
- Filters out users for whom Calico is not actually a good fit for their use-case.

Note that this may be a global document and/or individual documents per-orchestrator, to advertise the features that Calico brings to each environment.

**Comment by djosborne** [comment]
Sounds like what the **Introduction** page is trying to accomplish. But could use more content to **achieve the function** you have described

**Comment by djosborne** [comment]
Related to #25

**Comment by djosborne** [comment]
@matthewdupre suggested:

>We should review the intro slide deck and put any useful diagrams into the docs: this should be pitched at someone about the level of "someone told me Calico was cool: what is it?".

**Comment by caseydavenport** [comment]
This is better now.
