### ISSUE TITLE
Host the Kubernetes Network policy demo from Vimeo instead of YouTube?

### ISSUE THREAD

**Issue by eepyaich** [projectcalico/calico#10]
Tigera have its own Vimeo site where we can get stats, etc. for any of our videos.  We should put a copy of the Network Policy demo from /docs/getting-started/kubernetes/calico-kubernetes-overview there and embed it in the document.

**Comment by caseydavenport** [comment]
I'd like a better introduction (be it a video or not) than what we have now.  I don't think that video is the right thing for that page long term.

**Comment by caseydavenport** [comment]
Video is no more.
