### ISSUE TITLE
Felix crashes if it can't find the conntrack binary

### ISSUE THREAD

**Issue by tomdee** [projectcalico/calico#1004]
See this comment for the offending line and some diags.

https://github.com/projectcalico/calico/commit/bd27bf6f68df8333fc8f0d2a13c6bd10f951966b#commitcomment-16937768

Felix probably shouldn't assume that this binary exists.

**Comment by fasaxc** [comment]
@tomdee conntrack is required by Felix.  There was a bug that meant that we were failing to call conntrack most of the time but that is now fixed so we're now calling it when we should.
