### ISSUE TITLE
docker-compose generated (new docker bridge networks) containers can't reach the internet

### ISSUE THREAD

**Issue by victortrac** [projectcalico/calico#1012]
I'm running calico on kubernetes on AWS, generated by kops 1.7. Everything seems to work fine, but I noticed that some docker-compose generated containers inside of a jenkins job fails to reach the internet. 

## Current Behavior
To test, I SSH'd into a k8s node and created the following docker-compose.yaml:

```
version: '2.1'
services:
  app:
    container_name: app
    image: "debian:jessie"
    command: ["sleep", "99999999"]
  app2:
    container_name: app2
    image: "debian:jessie"
    command: ["sleep", "99999999"]
```
which fails to reach the internet:
```
# docker exec -it app ping 8.8.8.8
PING 8.8.8.8 (8.8.8.8): 56 data bytes
```
On the same host, a docker cli created container works just fine:
```
# docker run -it -d --name app3 debian:jessie sh -c "sleep 99999999"

# docker exec -it app3 ping 8.8.8.8
PING 8.8.8.8 (8.8.8.8): 56 data bytes
64 bytes from 8.8.8.8: icmp_seq=0 ttl=37 time=9.972 ms
```

I found the difference to be that the docker CLI created container uses the default bridge network whereas the docker-compose created containers use a new bridged network.  

To test this further, I manually created a new bridged network and used the CLI to create a container:

```
root@ip-10-20-140-184:~# docker network create --driver=bridge -o "com.docker.network.bridge.enable_ip_masquerade"="true" --subnet=172.16.47.0/24 bridgetest
f52e2582bf3c45a4d2e3f299d4d6c39108b172a51df33dadd4172b0568299def
root@ip-10-20-140-184:~# docker network inspect bridgetest
[
    {
        "Name": "bridgetest",
        "Id": "f52e2582bf3c45a4d2e3f299d4d6c39108b172a51df33dadd4172b0568299def",
        "Scope": "local",
        "Driver": "bridge",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "default",
            "Options": {},
            "Config": [
                {
                    "Subnet": "172.16.47.0/24"
                }
            ]
        },
        "Internal": false,
        "Containers": {},
        "Options": {
            "com.docker.network.bridge.enable_ip_masquerade": "true"
        },
        "Labels": {}
    }
]
root@ip-10-20-140-184:~# docker run --net bridgetest -it debian:jessie /bin/bash                                                                                                                                                                             
root@168ed72dbd12:/# ping google.com
ping: unknown host
```
Some calico logs when docker-compose creates a new bridge interface:
```
2017-08-09 22:59:33.749 [INFO][85] int_dataplane.go 355: Linux interface state changed. ifaceName="br-ee46fc9f4ef3" state="up"
2017-08-09 22:59:33.752 [INFO][85] int_dataplane.go 373: Linux interface addrs changed. addrs=set.mapSet{"172.18.0.1":set.empty{}, "fe80::42:77ff:fe2c:1a10":set.empty{}} ifaceName="br-ee46fc9f4ef3"
2017-08-09 22:59:33.752 [INFO][85] int_dataplane.go 355: Linux interface state changed. ifaceName="vethcd77091" state="down"
2017-08-09 22:59:33.753 [INFO][85] int_dataplane.go 492: Received interface update msg=&intdataplane.ifaceUpdate{Name:"br-ee46fc9f4ef3", State:"up"}
2017-08-09 22:59:33.753 [INFO][85] int_dataplane.go 492: Received interface update msg=&intdataplane.ifaceUpdate{Name:"vethcd77091", State:"down"}
2017-08-09 22:59:33.753 [INFO][85] int_dataplane.go 584: Applying dataplane updates
2017-08-09 22:59:33.753 [INFO][85] int_dataplane.go 599: Finished applying updates to dataplane. msecToApply=0.08815200000000001
2017-08-09 22:59:33.753 [INFO][85] int_dataplane.go 502: Received interface addresses update msg=&intdataplane.ifaceAddrsUpdate{Name:"br-ee46fc9f4ef3", Addrs:set.mapSet{"172.18.0.1":set.empty{}, "fe80::42:77ff:fe2c:1a10":set.empty{}}}
2017-08-09 22:59:33.753 [INFO][85] int_dataplane.go 584: Applying dataplane updates
2017-08-09 22:59:33.753 [INFO][85] int_dataplane.go 599: Finished applying updates to dataplane. msecToApply=0.15532100000000001
```

## Expected Behavior
I would have expected docker containers using new bridged networks to be able to reach the internet.

## Context
The real case is Jenkins running kubernetes-managed workers, and some of the tests are managed by docker-compose. It makes it quite nice that a developer can run the exact docker-compose that Jenkins runs. However, it works fine on a developer machine but the tests are failing external connectivity tests in kubernetes.

## Your Environment
* Calico version: calico/node:v1.2.1, calico/cni:v1.8.3
* Orchestrator version (e.g. kubernetes, mesos, rkt): kubernetes 1.7.3
* Operating System and version: linux 4.4.78-k8s

**Comment by ozdanborne** [comment]
@victortrac thanks for the detailed bug report. Just to make sure I understand correctly, can you clear one piece up:

>some docker-compose generated containers inside of a jenkins job fails to reach the internet

Which piece of this is networked by Calico? My best guess from reading this is that the jenkins job is run as a calico-networked-kubernetes-pod, with docker-compose installed in it?

**Comment by victortrac** [comment]
@ozdanborne 

> Which piece of this is networked by Calico? My best guess from reading this is that the jenkins job is run as a calico-networked-kubernetes-pod, with docker-compose installed in it?

Correct. Jenkins is running using the k8s plugin to create workers running on a calico-networked k8s pod. The worker container has `/var/run/docker.sock` host volume mapped and has docker-compose installed and simply brings up the docker-compose containers.  

But to be clear, I was able to reproduce by just SSH'ing into a k8s node, manually creating a new docker bridged network, and manually creating a new docker container assigned to use that new bridged network.

**Comment by tmjd** [comment]
IIUC, you are not attempting to create the new containers with Calico networking and have identified that docker run works but docker compose does not (for pinging outbound).  Calico does not require any special docker configuration that I am aware of, could you please explain why you believe this is a Calico issue and not a more general kops or docker issue?

**Comment by tmjd** [comment]
The only reason I listed kops as a possible source of the issue because it might do some docker configuration.

Calico only writes rules that apply to traffic to (or from) pods (I am assuming you do not have Host Endpoints setup for your hosts).  So, I think, unless there are IPs being used that are in the Calico IP Pool CIDR then the rules Calico is responsible for should not affect any containers ran with docker run or docker compose (started before or after Calico is started).
@fasaxc Do you agree with the above?

**Comment by fasaxc** [comment]
That's the case, we should only affect the connectivity of the containers that are on the Calico-controlled network.

**Comment by victortrac** [comment]
Thanks everyone. I'll file with Docker, I guess.

**Comment by cs-niraj-nandane** [comment]
I am facing same issue. What is the resolution?

**Comment by ragsonline** [comment]
We are still having this issue, "Calico" is changing the nodeip to bridge ip". in version 3.16.2... Do we need to change the "autodetect" to interface for it not to pick bridge/any nic

**Comment by fasaxc** [comment]
@ragsonline yes
