### ISSUE TITLE
Calico node target name should not be tied to the container name

### ISSUE THREAD

**Issue by AlexeyKasatkin** [projectcalico/calico#1015]
## Expected Behavior
One should be able to provide custom NODE_CONTAINER_NAME while building calico/node.

## Current Behavior
due to https://github.com/projectcalico/calico/blob/61faa05f2ac4de594220af930933eefc8ab5804a/calico_node/Makefile#L115
target name is now tied to container name so NODE_CONTAINER_NAME cannot be changed while building calico/node. Build becomes broken due to differences of target and container name usage.
Current error is: ``Makefile:115: *** target pattern contains no '%'.  Stop.``
But even if we not use symbols that are not permitted for target in NODE_CONTAINER_NAME, there will be a confusion between target name and container name.

## Possible Solution
1. Use "calico/node" target always (as it was earlier).
2. Introduce separate variable for target name, e.g. NODE_TARGET_NAME

## Steps to Reproduce (for bugs)
1. set NODE_CONTAINER_NAME (to e.g. "docker.ourportal.net/mirantis/projectcalico/calico/node:v1.3.x-55-20170810134058")
2. start build

## Context
We need to use custom attributes in node container name.
It was working fine with the previous version of makefile:
https://github.com/projectcalico/calicoctl/blob/d2babb665a4eb26419ccca9d30caeef09d5c68b4/Makefile.calico-node#L57

## Your Environment
* Calico version 2.4.0 (61faa05f2ac4de594220af930933eefc8ab5804a)

**Comment by caseydavenport** [comment]
@AlexeyKasatkin happy to accept a PR which adds a `calico/node` target as well.

**Comment by caseydavenport** [comment]
This has been fixed in the latest round of makefile improvements.
