### ISSUE TITLE
container cannot ping the host ip

### ISSUE THREAD

**Issue by saiwl** [projectcalico/calico#1017]
On host I can ping the container ip, but in container I cannot ping the host ip.

11: cali599cbd1c15b: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP qlen 1000
    link/ether e2:2a:64:70:fd:b4 brd ff:ff:ff:ff:ff:ff
    inet6 fe80::e02a:64ff:fe70:fdb4/64 scope link 
       valid_lft forever preferred_lft forever

the cali interface has no ipv4 address.
In container it shows:

root@e5f4bc06843b:/# ip ro
default via 169.254.1.1 dev eth1 
169.254.1.1 dev eth1  scope link

So no interface will response the arp request to 169.254.1.1. I guess the cali interface should be assigned 169.254.1.1, but it was not, why?

**Comment by saiwl** [comment]
In container cannot ping 169.254.1.1

**Comment by saiwl** [comment]
solved, ignore

**Comment by matthewdupre** [comment]
If your solution was simple, it would be great if you could quickly describe it here @saiwl to help the community.

Thanks :)
