### ISSUE TITLE
On the Releases page the calico/node does not link to the github release page

### ISSUE THREAD

**Issue by tmjd** [projectcalico/calico#1022]
## Expected Behavior
The calico/node version link points to the Releases page.

## Current Behavior
The calico/node version link points to the github.com release page for the correct version where calico/node is built

## Possible Solution
Fix it

## Steps to Reproduce (for bugs)
Go to docs.projectcalico.org/2.4/releases (or RC release docs.projectcalico.org/2.5/releases)

**Comment by bcreane** [comment]
I put a fix into latest _data/versions.yml for v2.5.0. Once that release is published, we can verify + close this issue.

**Comment by bcreane** [comment]
I think I see what happened now ... the 2.4 htmlproofer run likely failed (and blocked the release) since we're pointing releases to a non-existent git tag, e.g.:
```
- /_site/v2.5/releases/index.html
  *  External link https://github.com/projectcalico/calico/releases/tag/v2.5.0 failed: 404 No error
```

**Comment by tmjd** [comment]
I'm not sure if this is because of your fix but I noticed on the v2.5.0 release the calico/routereflector version links to the docs.projectcalico.org/2.5/releases page.

**Comment by bcreane** [comment]
fixed this in 2.5.

**Comment by bcreane** [comment]
ugh, routereflector has been broken since 2.1.

**Comment by bcreane** [comment]
Spoke with @robbrockbank and he points out calico/routereflector does not have a repo, so doesn't require a URL. We could potentially point to the container image in a future release.
