### ISSUE TITLE
Mac field on endpoint in datamodel is required but should be optional

### ISSUE THREAD

**Issue by tomdee** [projectcalico/calico#1025]
See http://docs.projectcalico.org/en/1.3.0/etcd-data-model.html#endpoints

The `mac` is required for calico-dhcp-agent but I can't see why it's needed for containers. We're jumping through hoops to find and set this mac when we (maybe) don't need to.

**Comment by tomdee** [comment]
@matthewdupre Could fix this is @fasaxc approves the change.

**Comment by fasaxc** [comment]
@tomdee I sent you a slack message, I have a work-in-progress that might help here.  One concern is that, right now, we inject an ARP entry on the host for the container's MAC.  I _think_ that's just an optimisation but we might need a tweak to our iptables rules to allow a real ARP to go through.

**Comment by fasaxc** [comment]
Fixed by #1039.  The `mac` field is now optional.  Note: I've only tested that explicitly for host endpoints.
