### ISSUE TITLE
Unable to start calicoctl node --libnetwork - Throws error

### ISSUE THREAD

**Issue by arjunm183** [projectcalico/calico#1028]
Hello Team,

I followed the below page for configuring calico and in the process of configuring it is throwing error.
https://www.projectcalico.org/docker-libnetwork-is-almost-here-and-calico-is-ready/

=========================================================

**Prerequisites:**

**Docker version :**  docker --version
Docker version 1.9.1, build a34a1d5
=========================================================

**ETCD**  
```
systemctl status etcd.service
etcd.service - Etcd Server
   Loaded: loaded (/usr/lib/systemd/system/etcd.service; disabled)
   Active: active (running) since Fri 2016-06-03 09:49:33 CEST; 20min ago
```
=========================================================

Reproducing the issue :  

```
./calicoctl node --libnetwork
APIError: 500 Server Error: Internal Server Error ("No command specified")

Traceback (most recent call last):
  File "<string>", line 145, in <module>
  File "calico_ctl/node.py", line 207, in node
  File "calico_ctl/node.py", line 302, in node_start
  File "calico_ctl/node.py", line 389, in _start_node_container_docker
  File "site-packages/docker/api/container.py", line 119, in create_container
  File "site-packages/docker/api/container.py", line 130, in create_container_from_config
  File "site-packages/docker/client.py", line 150, in _result
  File "site-packages/docker/client.py", line 146, in _raise_for_status
APIError: 500 Server Error: Internal Server Error ("No command specified")
```
=========================================================

Kindly help me in fixing this issue. Am i missing something or do you need further information to figure this issue.

**Comment by fasaxc** [comment]
@arjunm183 what version of calicoctl are you using?  It'd also be helpful to have the diags bundle colleted with `calicoctl diags`.

**Comment by arjunm183** [comment]
@fasaxc I downloaded calicoctl from the following website
https://github.com/projectcalico/calico-containers/releases

**Version:** v0.19.0
./calicoctl version
0.19.0


./calicoctl diags
[diags-030616_102419.tar.gz](https://github.com/projectcalico/calico/files/297203/diags-030616_102419.tar.gz)

**Comment by arjunm183** [comment]
Issue fixed by loading the docker image instead of importing
