### ISSUE TITLE
Running Calico under rktnetes produces errors for /proc/sys read-only file system

### ISSUE THREAD

**Issue by rbjorklin** [projectcalico/calico#1030]
## Expected Behavior
Running rktnetes with calico as a networking solution should work.

## Current Behavior
Deploying the [kubernetes hosted calico](https://docs.projectcalico.org/v2.4/getting-started/kubernetes/installation/hosted/hosted) networking solution with rktnetes doesn't seem to work and produces this error in the calico/node log:

`[WARNING][136] endpoint_mgr.go 492: Failed to configure interface, will retry error=open /proc/sys/net/ipv4/conf/calicde0ec83-9c/rp_filter: read-only file system`

## Possible Solution
* As a work-around it should be possible to run Calico outside of rktnetes but I've yet to test this.
* It should be possible via annotations to use stage1-fly as described [here](https://kubernetes.io/docs/getting-started-guides/rkt/#modular-isolation-with-interchangeable-stage1-images) which according to the issue linked below should avoid the problem with `/proc/sys` being read-only.
Unfortunately that fails with:
`Failed to create rkt container with error: cannot make "calico-node-g8pg5_kube-system(67484e50-8423-11e7-ad37-005056a010da)": running a custom stage1 requires a privileged security context` even though `securityContext: privileged: true` is set.

## Steps to Reproduce (for bugs)

1. Setup rktnetes
2. Try deploying the previously linked yaml file

## Context
[previous discussion regarding rp_filter](https://github.com/projectcalico/calicoctl/issues/1082)
[rkt always mounts /proc/sys read-only](https://github.com/rkt/rkt/issues/3245)

## Your Environment

* Calico version

    $ calicoctl version       
    Client Version:    v1.4.0
    Build date:        2017-07-31T20:45:05+0000
    Git commit:        03574e5
    Cluster Version:   v2.4.1
    Cluster Type:      k8s,bgp

* Orchestrator version (e.g. kubernetes, mesos, rkt): Kubernetes 1.7.3
* Operating System and version: CoreOS Alpha 1506.0.0
* Link to your project (optional):

**Comment by ozdanborne** [comment]
@rbjorklin I'm sorry this hasn't had any attention for 2 weeks but just wanted to say that I will be digging into it starting next week

**Comment by ozdanborne** [comment]
@rbjorklin we have users running calico in rktnetes without issue, so I wouldn't worry about trying to run Calico outside of it.

I would dial into the problem you stated here:
>Failed to create rkt container with error: cannot make "calico-node-g8pg5_kube-system(67484e50-8423-11e7-ad37-005056a010da)": running a custom stage1 requires a privileged security context

It looks like that privileged context can be applied at the container or pod level. Maybe try one, the other, or both? Probably worth asking the `sig-auth` k8s community why the privileged constraint doesn't seem to be applying.

Does this work if you disable SELinux on the host in question?

**Comment by rbjorklin** [comment]
@ozdanborne I'm running CoreOS which has SELinux disabled by default.

**Comment by caseydavenport** [comment]
@rbjorklin did you ever get to the bottom of this?

**Comment by rbjorklin** [comment]
Nope, after fighting with rkt for like two weeks I finally surrendered and went the docker path and was up and running in a day or so. Feel free to close this.
