### ISSUE TITLE
New pods don't get ip on calico interface after kubernetes master/etcd reinstall

### ISSUE THREAD

**Issue by r7vme** [projectcalico/calico#1031]
I have 1 master and X workers kubernetes setups. After master node (etcd) recreation. I'm getting situation where new pods do not have network connectivity.

I see that pod's `cali02b3560ea8e` interface on node do not get IP address. Inside container all seems fine. 169.254 routes and correct ip 192.168/32 on interface.

I also see that new BGP peer (master) did not showed up in one worker node. Table below does not have master peer `172.25.0.234`. 

But it seems that on ALL workers pods don't have ip on calico interface.

Nodes:
```
~|⇒ kubectl get nodes        
NAME           STATUS                     AGE       VERSION
172.25.0.234   Ready,SchedulingDisabled   1h        v1.7.3+coreos.0
172.25.0.90    Ready                      1h        v1.7.3+coreos.0
172.25.1.118   Ready                      1h        v1.7.3+coreos.0
172.25.1.122   Ready                      1h        v1.7.3+coreos.0
```

One of the worker BGP sessions does not contain new peer (new master):
```
+--------------+-------------------+-------+----------+-------------+
| PEER ADDRESS |     PEER TYPE     | STATE |  SINCE   |    INFO     |
+--------------+-------------------+-------+----------+-------------+
| 172.25.1.118 | node-to-node mesh | up    | 17:01:26 | Established |
| 172.25.0.90  | node-to-node mesh | up    | 17:01:25 | Established |
+--------------+-------------------+-------+----------+-------------+
```

Master bgp session:
```
+--------------+-------------------+-------+----------+--------------------------------+
| PEER ADDRESS |     PEER TYPE     | STATE |  SINCE   |              INFO              |
+--------------+-------------------+-------+----------+--------------------------------+
| 172.25.1.122 | node-to-node mesh | start | 17:13:52 | Active Socket: Connection      |
|              |                   |       |          | reset by peer                  |
| 172.25.1.118 | node-to-node mesh | up    | 17:13:52 | Established                    |
| 172.25.0.90  | node-to-node mesh | up    | 17:13:55 | Established                    |
+--------------+-------------------+-------+----------+--------------------------------+
```

## Expected Behavior
New pods created with correctly configured networking

## Current Behavior
Pods created with broken networking.

## Possible Solution
Workaround is to restart calico-node container.

## Steps to Reproduce (for bugs)
I'm not sure it will be easy reproduce, but
1. Create kubernetes cluster with 1 master and any number of worker
2. delete old master from `calicoctl delete node OLD_MASTER`
3. delete master and create new master (new hostname) with same etcd data (e.g. separate volume)
4. Create pod  (e.g. `kubectl run --rm -i -t busybox --image=busybox -- sh`) and try to ping any external ip.

## Your Environment
* Calico version 2.2.1
* Orchestrator version 1.7.3
* Operating System and version: CoreOS 1409.7.0

**Comment by tmjd** [comment]
Can you check on the calico-node logs and calico-policy-controller logs to see if there are errors there?

You said you recreated the master which has etcd.  How did you restore the etcd data, specifically the Calico data?  If you are using a version 3 etcd server you must make sure the data you backup and restore is both the v2 and v3 data.  K8s probably uses v3 (unless specified to use v2) and Calico uses v2.  My understanding is that the backup utility must be ran in v2 and v3 mode as one does not backup both sets of data.

**Comment by tmjd** [comment]
Sorry for the delay in responding, I think I missed the notification of your last response.
The issue may be due to the reuse of the etcd data. You may want to take a look at https://docs.projectcalico.org/v2.6/usage/decommissioning-a-node. By default new calico-nodes will check the datastore to see if a node is already using an IP Address and I'm wondering if you master was using a previously used IP Address.

**Comment by r7vme** [comment]
Looks like this issue is gone, when we switched to 2.5.1 (from 2.3.0).

There were two issues that caused problems:
1) existing nodes had broken confd (stalled etcd connection?), so bird did not get new peer in config. So new node were reset.
2) For some reason after 1 manually resolved i see IPIP tunnels not forwarding traffic. And what is most weird that i need to ping endpoint IP of tunnel from both sides, after that traffic started to forward.
