### ISSUE TITLE
Calico: using ports instead of IPs

### ISSUE THREAD

**Issue by distributorofpain** [projectcalico/calico#1033]
Just a question, please dont shoot.  :smile_cat: 

I have a situation where we have SSL certificates being generated via each host and then trusted by all hosts.  Traefik requires this trust to work in order to send SSL traffic on the back end for an end to end SSL setup.

Would it be possible to setup calico to use ports instead of IP per container?  If not, we would have to include the CA cert in the container and generate the cert per container on start up which of course would require additional components loaded into the docker image, thus making it larger.

**Comment by fasaxc** [comment]
I responded on your other issue so let's continue the discussion there: https://github.com/projectcalico/calico-mesos/issues/69
