### ISSUE TITLE
Config item which enables IP Tables rules to LOG DROPS and ACCEPTS

### ISSUE THREAD

**Issue by mccormd** [projectcalico/calico#1035]
We are running kubernetes in an environment where we are subject to quite a lot of regulations.  One of these requirements is that we be able to log all DROP/ACCEPT on our firewalls.  As we are starting to use Calico to implement kubernetes NetworkPolicy, can we have a switch where it will insert the correct LOG rules into iptables so that we can have our desired log?  For bonus points, could the log be enriched with kubernetes pod names?

## Expected Behavior

By enabling the connection logging feature, additional LOG entries are added into the chains before a DROP and before the default ACCEPT actions.

## Current Behavior

No usage of iptables LOG seems to be made to log connections/packets.

## Possible Solution

The iptables rules seem complex already, so I'm hoping that this would be best implemented in Calico code base rather than try to do this around it.

## Context

Satisfy our infosec team and pass FCA audits.

## Your Environment

* Calico version:  2.4.0
* Orchestrator version (e.g. kubernetes, mesos, rkt): kubernetes 1.6/1.7
* Operating System and version: CoreOS stable

**Comment by ahrkrak** [comment]
@mccormd that's a feature available in our commercial product - Tigera Essentials (https://tigera.io/essentials), along with a bunch of other features that will fit into the "satisfy our infosec team and pass FCA audits" category. Please do email me at andy@tigera.io if you think there's value in exploring this.
