### ISSUE TITLE
Felix config file ignored if section name is DEFAULT

### ISSUE THREAD

**Issue by lwr20** [projectcalico/calico#1036]
This felix config file (`/etc/calico/felix.cfg`) works fine (felix connects to etcd at the IP/port specified):
```
[default]
EtcdAddr=192.168.15.7:2379
```

But this does not:
```
[DEFAULT]
EtcdAddr=192.168.15.7:2379
```

I believe the docs say that the section names are ignored, so its possible someone else might do this.

**Comment by lwr20** [comment]
In my case, OS=scientific linux 6.  I'm running the calico-felix @fasaxc supplied me for testing at 15:18 on 15/June/2016.

**Comment by fasaxc** [comment]
💯  for finding the one string in the universe that triggered that behaviour.
