### ISSUE TITLE
calico_dhcp_agent ignore etcd_host and port

### ISSUE THREAD

**Issue by gmodules** [projectcalico/calico#1038]
in networking_calico/agent/dhcp_agent.py 

it ignore the neutron.conf because the following is hardcoded : 127.0.0.1:4001 

at the moment it's not possible to bind etcd proxy to an ip other than loopback.

**Comment by matthewdupre** [comment]
Agreed - it would be best to read this config like we do for the plugin.

**Comment by fasaxc** [comment]
We normally use a local etcd proxy on each host, which is why 127.0.0.1 is the default.  Agree, it should be configurable, though.

Assigning to @neiljerram, who owns the OpenStack integration.

**Comment by neiljerram** [comment]
This issue is already tracked at https://bugs.launchpad.net/networking-calico/+bug/1534599.

Please note - networking-calico bugs are tracked in Launchpad, not here.
