### ISSUE TITLE
Down state node still exists in cmd `calicoctl node show` output

### ISSUE THREAD

**Issue by gwanii** [projectcalico/calico#1044]
Two-node cluster for calico network test:
If one of them got down, on the other node use cmd `calicoctl node show` still show the down state node, 

```
[root@calico-01 ~]# calicoctl node show
+-----------+--------------+-----------+-------------------+--------------+--------------+
|  Hostname |  Bird IPv4   | Bird IPv6 |       AS Num      | BGP Peers v4 | BGP Peers v6 |
+-----------+--------------+-----------+-------------------+--------------+--------------+
| calico-01 | 192.168.2.10 |           | 64511 (inherited) |              |              |
| calico-02 | 192.168.2.11 |           | 64511 (inherited) |              |              |
+-----------+--------------+-----------+-------------------+--------------+--------------+
```
and endpoints info from down state node still founded in `calicoctl endpoint show` output.

**Comment by fasaxc** [comment]
@gwanii I think that's working as designed; Calico cannot know if the node is gone permanently or is just down for maintenance.  Either you or an orchestrator needs to tell Calico that the node is really gone for good.
