### ISSUE TITLE
Calico/node can get into a CrashLoopBackoff loop during the v2.5.0 upgrade

### ISSUE THREAD

**Issue by 2ffs2nns** [projectcalico/calico#1052]
## Current Behavior
Calico/node can get into a CrashLoopBackoff restart loop when upgrading from `v2.4.x` to `v2.5.0` in KDD/Kubernetes Datastore backend if the migration job hasn’t been applied. The log output looked like this:

```bash
kubectl logs -n kube-system canal-8jbcp calico-node   
Checking datastore connection
Datastore connection verified
ERROR: Unable to set node resource configuration: Failed to ensure datastore has been initialized: "timed out waiting for the condition". Make sure the Custom Resource Definitions have been created and Calico has been authorized to access them.
Terminating
Calico node failed to start
```

## Solution
Follow step 2 in the [Migration process](https://github.com/projectcalico/calico/blob/master/upgrade/v2.5/README.md) README

After I applied the `upgrade-job.yaml` according to the [README](https://github.com/projectcalico/calico/blob/master/upgrade/v2.5/README.md), the issue went away.

## Your Environment
* Calico version: upgrading from `v2.4.x` to `v2.5.0`
* Orchestrator version (e.g. kubernetes, mesos, rkt): kubernetes `v1.7.3`
* KDD / kubernetes datastore backend

**Comment by bcreane** [comment]
As @2ffs2nns mentions, the solution is to apply `upgrade-job.yaml`.
