### ISSUE TITLE
Felix conntrack rules in FORWARD chain RETURN instead of ACCEPTing, causing packet drops with default DENY

### ISSUE THREAD

**Issue by matthewdupre** [projectcalico/calico#1056]
Symptom: containers unable to ping each other when profile allows but the FORWARD policy is DROP.  (First outgoing packet makes it, but all responses and subsequent packets are dropped.)

https://github.com/projectcalico/calico/blob/4e0c52f680b91cfc02ee994263aaae9f0d82ffc3/calico/felix/plugins/fiptgenerator.py#L370 and the line below set RETURN for ctstate RELATED / ESTABLISHED, but first packets instead go through the profile, where they may be ACCEPTed, DROPed or RETURNed (but usually the first two).

Those lines should probably just ACCEPT.  This does potentially introduce a regression if the rest of the FORWARD chain contains more sophisticated rules which would be bypassed.  @fasaxc: you're most familiar with this area - what do you think?  We could make this configurable if we wanted (I'd suggest default ACCEPT)?

**Comment by matthewdupre** [comment]
Workaround suggestions:
- Use a default of ACCEPT in the FORWARD chain.
- Add a more specific ACCEPT rule to the FORWARD chain.  Perhaps something like  `--append FORWARD --in-interface tap+ --match conntrack --ctstate RELATED,ESTABLISHED --jump ACCEPT` and `--append FORWARD --out-interface tap+ --match conntrack --ctstate RELATED,ESTABLISHED --jump ACCEPT` to catch only the packets RETURNed by Felix.

**Comment by fasaxc** [comment]
I think we introduced this bug when we moved the conntrack rules to the felix-FORWARD chain.  they used to be in a leaf chain, so returning to the felix-FORWARD chain would then hit the rules at the bottom of that chain that do an accept.  So, using a more-specific pair of ACCEPT rules is the right fix, I think.

**Comment by themicster** [comment]
So the fix matthewdupre suggested, is that the right fix?

**Comment by fasaxc** [comment]
@themicster Yes.
