### ISSUE TITLE
If Felix doesn't have a CA cert to authenticate against, it keeps going

### ISSUE THREAD

**Issue by fasaxc** [projectcalico/calico#1058]
Customer hit the following:

> Interestingly, if felix can’t authenticate a certificate (because we haven’t given it the CA cert yet), it still pulls its config down from etcd. It warns that there’s an error:

```
/usr/local/calico-felix/urllib3/connectionpool.py:838: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/security.html
```

> Also, that only gets logged to the console, not either of felix.log or felix-etcd.log

I think when we do have the CA certificate configured we do check it but we should probably fail in the above case.

**Comment by Lukasa** [comment]
You have two issues there.

Firstly, that's a warning. You'll need to intercept where Python warnings go.

The second issue is probably in python-etcd, specifically [here](https://github.com/projectcalico/python-etcd/blob/master/src/etcd/client.py#L171-L173): you only set `cert_reqs=CERT_REQUIRED` if you've provided a CA certificate to validate. That means that python-etcd defaults to not checking the TLS certificate.

**Comment by Lukasa** [comment]
For the warnings stuff, [this](https://pymotw.com/2/warnings/#alternate-message-delivery-functions) looks promising.

**Comment by fasaxc** [comment]
@Lukasa  Maybe we should just bail out if we're asked to use HTTPS without a CA cert?

**Comment by Lukasa** [comment]
@fasaxc That's a totally reasonable thing to do. You can still set CERT_REQUIRED without providing a CA file or directory.

**Comment by elfchief** [comment]
@fasaxc: Being asked to do SSL but not being given a CA cert shouldn't bail instantly, because there's still the system trust store (which the python module accesses, but our CA cert isn't there, for various reasons). Since a lot of people _do_ put their CA certs there, you probably shouldn't break that perfectly normal behavior.

Also, if "bail if we can't verify cert" is added, you should probably also add a "don't verify cert" option, just because that's sometimes useful for testing  (or people who just don't care).

**Comment by Lukasa** [comment]
For what it's worth, urllib3 by default does not load the system trust store on Linux.

**Comment by fasaxc** [comment]
@elfchief I'd agree about the trust store in general but I think most of the etcd ecosystem requires the certs and CA to be specified.  Actually, now I say that, I'm not sure what etcdctls default behaviour is; i.e. whether it user your system trust store or not.  I'll check.

Probably does make sense to have a bypass option and/or enable the default trust store if that's straightforward in urllib3.

**Comment by elfchief** [comment]
etcdctl will use the system cert store by default (or so says strace), for whatever that's worth.

**Comment by fasaxc** [comment]
Thanks, #1061 should make that the default (with option to override to "don't both checking").
