### ISSUE TITLE
Patch release process cannot succeed "by the book"

### ISSUE THREAD

**Issue by fasaxc** [projectcalico/calico#1067]
The patch release process says
```
1. Test the changes locally then open a pull request, make sure it passes CI and get it reviewed.
1. Create a git tag, docker images, and release file by running `make -C calico_node release`. Follow the instructions to push the images but DO NOT PUSH THE TAG YET.
1. Now merge the PR - this will cause the live docs site to be updated (after a few minutes).
```
But, the PR build is guaranteed to fail because the `htmlproofer` step tries to retrieve the release tarball, which doesn't exist if you follow the process in-order.

## Expected Behavior

Process should have a consistent order that ensures success at each stage unless there's a real problem.

## Current Behavior

Semaphore build guaranteed to fail.

## Possible Solution

Not sure what we could do here, if we create the release first, that'd publish before we run the CI tests, which isn't ideal either.

Guess we could host the tarball somewhere else so we can make it available before the github release is pushed but that doesn't feel ideal either.

Maybe we could split the html proofer task into its own build job to make it easier to ignore in this case.

At a minimum, we should tweak the doc to explain what errors it's OK to ignore or not.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Calico version
* Orchestrator version (e.g. kubernetes, mesos, rkt):
* Operating System and version:
* Link to your project (optional):

**Comment by bcreane** [comment]
I was going to see if we can skip validation for release notes and the release-specific directory.

**Comment by bcreane** [comment]
Just tried an experiment with htmlproofer: `--url-swap "v2.6:v2.5` which replaces the upcoming (non-existent) github.com urls with the old (extant) one. Unfortunately, the job is still running after 15 minutes, so I'm guessing this sort of substitution is prohibitively expensive.

**Comment by caseydavenport** [comment]
The patch release process has been fixed up so this is no longer the case.
