### ISSUE TITLE
Felix doesn't handle new interface name for endpoint

### ISSUE THREAD

**Issue by caseydavenport** [projectcalico/calico#1075]
I tried updating an endpoint with a new host-side veth name and I see the following log repeated:

```
calico.felix.endpoint 292: Update on interface cali8077ce8b707 that we do not care about
```

We do care about this interface, Felix!

In k8s it is possible for a container to be restarted with the same identifiers, meaning a new veth is created and then the endpoint is updated to reference that veth.  I'm not seeing the route programmed by Felix in this case.

Haven't had a chance to dig into the code in detail yet, but it looks like we're not tracking the change `endpoint_id_by_iface_name` properly.

@fasaxc any thoughts?

**Comment by caseydavenport** [comment]
On second glance, I might have misjudged the logs.  Could be that Felix is receiving the interface update before the endpoint update, so it makes sense to see those logs.

However, I would still expect the route to eventually appear (and it does not).

Diags can be found here include Felix logs: https://transfer.sh/mFwee/diags-090816-011430.tar.gz

Relevant endpoint has iface `cali8077ce8b707`.

So: 
```
core@k8s-node-01 ~ $ etcdctl get /calico/v1/host/k8s-node-01/workload/k8s/kube-system.kube-ui-v4-orbz8/endpoint/eth0
{"state":"active","name":"cali8077ce8b707","mac":"f6:ef:ee:0f:93:6a","profile_ids":["k8s_ns.kube-system"],"ipv4_nets":["192.168.0.2/32"],"ipv6_nets":[],"labels":{"calico/k8s_ns":"kube-system","k8s-app":"kube-ui","kubernetes.io/cluster-service":"true","version":"v4"}}
```


Will have to look into this further tomorrow.

**Comment by fasaxc** [comment]
D'oh, looking at the code, I think we assume the interface name never changes:
```
if self.endpoint is None:
    # This is the first time we have seen the endpoint, so extract
    # the interface name and endpoint ID.
    self._iface_name = pending_endpoint["name"]
```
Fix is not 100% trivial; if we just update that field then we won't remove routes from the old interface.

**Comment by tomdee** [comment]
@fasaxc I think we need this fixed before we can do a Go CNI release. Rob is itching to do a calico-node release and it would be great to get a fix for this issue too, is that going to be possible?

cc @calico-dashboards
