### ISSUE TITLE
can not set docker container dns

### ISSUE THREAD

**Issue by tiny1990** [projectcalico/calico#1078]
When I use calico, I'll post this json to marathon,but  docker container dns not set ,

post json:
`{
  "id": "zookeeper-1",
  "container": {
    "type": "DOCKER",
    "docker": {
      "image": "debezium/zookeeper:0.2",
      "parameters": [
          {"key": "net", "value": "datapipeline"}
      ]
    },
     "privileged": true
  },
  "instances": 1,
  "cpus": 1,
  "mem": 500,
  "constraints": [
    [
      "hostname",
      "UNIQUE"
    ]
  ],
  "env": {
    "LOG_LEVEL": "WARN"
  }
}`
local machine cat /etc/resolv.conf
```
nameserver 172.31.1.128
 # Generated by NetworkManager
search cn-north-1.compute.internal 31.1.128
nameserver 172.31.0.2
```

container /etc/resolv.conf
```
search cn-north-1.compute.internal 31.1.128
nameserver 127.0.0.11
options ndots:0
```

and mesos-dns

```
{
  "masters": ["172.31.6.2:5050"],
  "ZkDetectionTimeout": 0,
  "refreshSeconds": 60,
  "ttl": 60,
  "domain": "mesos",
  "port": 53,
  "resolvers": ["172.31.1.128"],
  "timeout": 5, 
  "httpon": true,
  "dnson": true,
  "httpport": 8123,
  "externalon": true,
  "listener": "0.0.0.0",
  "SOAMname": "ns1.mesos",
  "SOARname": "root.ns1.mesos",
  "SOARefresh": 60,
  "SOARetry":   600,
  "SOAExpire":  86400,
  "SOAMinttl": 60,
  "IPSources": [ "netinfo", "host"]
}
```

when I post docker network type 'BRIDGE',container dns is set from local machine,it's ok,but why i used net datapipeline container dns is not set.

**Comment by fasaxc** [comment]
@djosborne Probably one for you as mesos expert?

**Comment by djosborne** [comment]
@tiny1990 All of the above output looks ok to me: The container's DNS is set to `127.0.0.11` which is Docker's embedded DNS server, which should forward requests to the Host. [More info here](https://docs.docker.com/engine/userguide/networking/configure-dns/).

Can you elaborate on what exactly is the problem here?

**Comment by djosborne** [comment]
@tiny1990 I haven't heard back from you so I am going to close this issue. Reopen or [contact us on slack](https://slack.projectcalico.org/) if you need more assistance.
