### ISSUE TITLE
Automate release process.

### ISSUE THREAD

**Issue by Lukasa** [projectcalico/calico#108]
For this repository we can conceivably almost entirely automate the release process. We should therefore aim to do that!

This issue tracks thoughts on how we plan to do that.

The script needs to do the following:

1. Given a changelog, it should place it in the Debian and RPM build files.
2. It should increment the version number.
3. It should build source packages and upload to the PPA.
4. It should build binary debs.
5. It should build binary RPMs.
6. It should upload debs and RPMs to release.
7. It should email notifying completion.

Some other notes:

1. It should be super defensive: for example, if it sees more than three version numbers in the code it should stop and require manual intervention.
2. It should be version controlled, ideally in this repository.

**Comment by neiljerram** [comment]
Have just completed some improvements here, for the 1.4.2 release.  Improved process is documented at https://docs.google.com/document/d/1YEZLpHsxWEnMxdrYS_8PVENsjTJskDcCH_0Y7EPnmYs/edit#, using some scripts at https://github.com/tigera/process/.

This puts us in a decent state now, so I'm going to close this issue.  Obviously we can still continue to add further increments of automation in the future, as we gain experience.
