### ISSUE TITLE
Add document explaining what kernel bypass/acceleration options work with Calico

### ISSUE THREAD

**Issue by tomdee** [projectcalico/calico#108]
I don't think there's any info in our docs about what acceleration/bypass options work with Calico (if any). 

This image summarizes some of the options
https://lh3.googleusercontent.com/TO1UdUicn1wuF4jIAhskikO6MLaQgUuurORG_l9Zxr_L_XRvwvVhuZmF5vWTGGkauRFVT2daOOM=w1439-h1079-no

**Comment by djosborne** [comment]
@tomdee assigning to you since I'm not up to speed on context and priority here

**Comment by tomdee** [comment]
Not sure I'm the best home for this - I think @fasaxc has looked at some of these technologies in the past?
