### ISSUE TITLE
Wrong repo in calico 1.4 documentation

### ISSUE THREAD

**Issue by apoiget** [projectcalico/calico#1083]
In the Red Hat Enterprise Linux 7 Packaged Install Instructions documentation for 1.4.0 ( file docs/source/redhat-opens-install.rst )
the repository for Calico is not the good one. 
rpm_stable will install 1.3.0 
1.4.0 should have rpm_calico-1.4

[https://gist.github.com/apoiget/1d53bc8bd7ac31c8dbbbedbaa4502a3b](https://gist.github.com/apoiget/1d53bc8bd7ac31c8dbbbedbaa4502a3b)

**Comment by fasaxc** [comment]
@neiljerram Have we pushed the redhat repo update?

**Comment by fasaxc** [comment]
@neiljerram Have we pushed out the 1.4 RPM packages now?

**Comment by neiljerram** [comment]
@fasaxc I'm not sure I understand what you mean by 'the redhat repo update' - but I believe that the content of rpm_calico-1.4 on binaries is good.

**Comment by fasaxc** [comment]
I know we pushed the PPAs first for 1.4, I wasn't 100% sure that we'd pushed the RH version of hte update.

Thanks for putting up the PR.
