### ISSUE TITLE
packets not forwarded to newly added endpoint

### ISSUE THREAD

**Issue by dachulin** [projectcalico/calico#1087]
This issue is created for following up on #1085 since I can't re-open it.

Are the packets being forwarded to another pod in the service? 
No, packets were being dropped. The service only have one pod.

We can't adjust the application to cycle its source port, since they are not under our control.

Wondering if calico creates IP table rules for kubernete services or only pods? If calico only creates ip table rules for pods, then I agree it should be fixed in kube proxy. If calico also handles the ip table rule creation for kube services, then I would think is better for calico to handle it.

**Comment by fasaxc** [comment]
Ah, sorry about that, didn't realise it would lock the issue to comments.

Calico does not program rules for service IPs.  The IPs have been converted to pod IPs before we see them.

**Comment by dachulin** [comment]
Got it, so agree with you that it is better for kube to handle it then, since it is service ip rule.
