### ISSUE TITLE
Incorrect comment in kubeadm manifest

### ISSUE THREAD

**Issue by tmjd** [projectcalico/calico#1097]
The comment at https://github.com/projectcalico/calico/blob/47184e4c441ccd99931675eab43120634b501015/master/getting-started/kubernetes/installation/hosted/kubeadm/1.6/calico.yaml#L70
 is incorrect.

It should be moved to the `nodeSelector` and a new comment added indicating that the toleration allows the pod to run on master.

**Comment by rakrup** [comment]
@tmjd . I have tried to fix the issue  based on your inputs. Can you please review the PR and check if this is the change you were expecting and merge it based on what you think about it.
