### ISSUE TITLE
Allow multiple interface prefixes in config

### ISSUE THREAD

**Issue by cutwater** [projectcalico/calico#1101]
As we discussed with @fasaxc in https://github.com/projectcalico/libcalico/issues/146 it is nice to have multiple interface prefixes support in calico. Currently Calico supports only single `InterfacePrefix` configuration value that brings limitations on mixed workloads (e.g. OpenStack and K8S are using different prefixes, that cannot be configured).

Multiple prefixes support will allow using Calico on mixed workloads.

**Comment by fasaxc** [comment]
@neiljerram I think you have a bit of time in plan to help with this?

**Comment by neiljerram** [comment]
Yes.
