### ISSUE TITLE
Containers hang on starting with calico installed on minikube

### ISSUE THREAD

**Issue by ceridwen** [projectcalico/calico#1102]
## Expected Behavior

Installing Calico shouldn't prevent pods from starting.

## Current Behavior

After starting minikube with Virtualbox as the driver and,
`minikube start --network-plugin=cni --host-only-cidr=192.168.0.0/16`
and installing Calico with,
`kubectl apply -f https://docs.projectcalico.org/v2.5/getting-started/kubernetes/installation/hosted/kubernetes-datastore/calico-networking/1.7/calico.yaml`,
when I try to start a simple container based on Alpine with netcat installed, the containers never come up.  There are no logs in the containers, for obvious reasons.  The events in `kubectl describe` look like:

```
Events:
  FirstSeen	LastSeen	Count	From			SubObjectPath		Type		Reason			Message
  ---------	--------	-----	----			-------------		--------	------			-------
  12m		12m		1	default-scheduler				Normal		Scheduled		Successfully assigned netcat-0 to minikube
  12m		12m		1	kubelet, minikube				Normal		SuccessfulMountVolume	MountVolume.SetUp succeeded for volume "default-token-xl3r5"
  11m		11m		1	kubelet, minikube	spec.containers{netcat}	Warning		Failed			Error: failed to start container "netcat": Error response from daemon: {"message":"cannot join network of a non running container: 4461ece045eb795ef6ec0aa984500268392344ca0bec347e6e2cb75e20daa94d"}
  10m		10m		1	kubelet, minikube	spec.containers{netcat}	Warning		Failed			Error: failed to start container "netcat": Error response from daemon: {"message":"cannot join network of a non running container: ab7a22b9ef9ffc0cabf859831c10e8723215c2e34d4d476e045136c1d86e4b77"}
  10m		10m		1	kubelet, minikube	spec.containers{netcat}	Warning		Failed			Error: failed to start container "netcat": Error response from daemon: {"message":"cannot join network of a non running container: d92e3c84e9f46e1f0701685fa798366f602ab016ecd8423d32fdb2ff558eb322"}
  11m		3m		4	kubelet, minikube	spec.containers{netcat}	Normal		Pulling			pulling image "ceridwen/netcat:v1"
  11m		3m		4	kubelet, minikube	spec.containers{netcat}	Normal		Pulled			Successfully pulled image "ceridwen/netcat:v1"
  11m		3m		4	kubelet, minikube	spec.containers{netcat}	Normal		Created			Created container
  3m		3m		1	kubelet, minikube	spec.containers{netcat}	Warning		Failed			Error: failed to start container "netcat": Error response from daemon: {"message":"cannot join network of a non running container: 0ccadc0c91bb9408279b4956ebff1631b6ebaedf725a712e0cf921f5f81d0304"}
  12m		4s		154	kubelet, minikube				Normal		SandboxChanged		Pod sandbox changed, it will be killed and re-created.
  12m		0s		162	kubelet, minikube				Warning		FailedSync		Error syncing pod
```

From the `calico-node` logs,

```
2017-09-11T22:10:15Z minikube confd[83]: DEBUG map[/calico/v1/ipam/v4/pool/192.168.0.0-16:{"cidr":"192.168.0.0/16","ipip":"tunl0","ipip_mode":"always","masquerade":true,"ipam":true,"disabled":false}]
2017-09-11T22:10:15Z minikube confd[83]: DEBUG Using source template /etc/calico/confd/templates/tunl-ip.template
2017-09-11T22:10:15Z minikube confd[83]: DEBUG Compiling source template /etc/calico/confd/templates/tunl-ip.template
2017-09-11T22:10:15Z minikube confd[83]: DEBUG Comparing candidate config to /tmp/tunl-ip
2017-09-11T22:10:15Z minikube confd[83]: DEBUG Target config /tmp/tunl-ip in sync
bird: Unable to open configuration file /etc/calico/confd/config/bird.cfg: No such file or directory
bird: Unable to open configuration file /etc/calico/confd/config/bird.cfg: No such file or directory
```

This is specific to calico because if I don't have calico installed, this same pod/container will start.

## Steps to Reproduce (for bugs)

1. Install minikube with homebrew (https://github.com/kubernetes/minikube).
2. Install Virtualbox (https://www.virtualbox.org/wiki/Downloads).
3. Start minikube with `minikube start --network-plugin=cni --host-only-cidr=192.168.0.0/16`
4. Install Calico with `kubectl apply -f https://docs.projectcalico.org/v2.5/getting-started/kubernetes/installation/hosted/kubernetes-datastore/calico-networking/1.7/calico.yaml`
5. Attempt to start a container with the above image.

## Context

I'm trying to create a working development environment for testing network policy on my local machine so I don't have to depend on a remote cluster for doing development work.  I know this is beta software, but it *was* working so I suspect that a change in Calico or minikube is responsible.

## Your Environment

Calico: v2.5
minikube: v0.22.0, Kubernetes version 1.7.5
OS: Mac OS X 10.12.6

**Comment by gunjan5** [comment]
@ceridwen can you do `kubectl get node -o yaml | grep podCIDR`? I think ConfD can't generate the BIRD config files because podCIDR label might be missing from the nodes. 
Not sure how that's done in minikube, but with kubeadm you pass `--pod-network-cidr=10.244.0.0/16` to get that label onto the nodes

**Comment by ceridwen** [comment]
The only way I know of involves patching the minikube node:
`kubectl patch node minikube -p '{"spec":{"podCIDR":"192.168.0.0/24"}}'` (which I discovered while trying to get Canal working---it wasn't obvious here that podCIDR was the problem).
After running this command and reinstalling Calico, the containers come up, and isolation at least appears to be working.  Unfortunately, the Kubernetes Python client is now throwing websocket errors, so I can't check more thoroughly than that right now.

**Comment by tmjd** [comment]
@ceridwen Did you try starting minikube with the options suggested in https://github.com/projectcalico/calico/issues/1013#issuecomment-325689943 on your previous issue around calico and minikube?
You may not need to specify the `iso-url` since you are using minikube v0.22 and I was using v0.21.

**Comment by ceridwen** [comment]
I tried that now.  With minikube v0.22, those arguments seem to set the podCIDR field and so they also work.  Unfortunately, though kubectl seems to work, I'm still seeing websockets problems with the Kubernetes Python client, and I'm unsure what's causing that error.  Let me debug a bit more.

**Comment by ceridwen** [comment]
Actually, I take that back: the podCIDR must have been from a previous test, because after I did `minikube delete` and restarted it using the command from [#1013 (comment)](https://github.com/projectcalico/calico/issues/1013#issuecomment-325689943), Calico didn't start properly until I patched podCIDR onto the minikube node again.  Having or not having the additional arguments doesn't seem to matter.  Once I got Calico to start correctly, it's as I said before: I can verify that a pod in a namespace with a default-deny Network Policy is unreachable with kubectl, but not with the Python client.

**Comment by ceridwen** [comment]
Since exec into a pod works normally when Calico isn't installed on Minikube, I suspect Calico is related to this bug, but I don't know if it's the cause.  With Calico installed, the Python client communicates properly with the Minikube API server until I try to use exec to test pod-to-pod networking.   This initiates a websocket call, which fails with the following traceback:

```
Traceback (most recent call last):
  File "/Users/user/Library/Python/3.6/lib/python/site-packages/kubernetes/client/ws_client.py", line 253, in websocket_call
    client = WSClient(configuration, get_websocket_url(url), headers)
  File "/Users/user/Library/Python/3.6/lib/python/site-packages/kubernetes/client/ws_client.py", line 71, in __init__
    self.sock.connect(url, header=header)
  File "/Users/user/Library/Python/3.6/lib/python/site-packages/websocket/_core.py", line 214, in connect
    self.handshake_response = handshake(self.sock, *addrs, **options)
  File "/Users/user/Library/Python/3.6/lib/python/site-packages/websocket/_handshake.py", line 65, in handshake
    status, resp = _get_resp_headers(sock)
  File "/Users/user/Library/Python/3.6/lib/python/site-packages/websocket/_handshake.py", line 122, in _get_resp_headers
    raise WebSocketBadStatusException("Handshake status %d", status)
websocket._exceptions.WebSocketBadStatusException: Handshake status 500
```

I haven't been able to get any more useful information on this error from the Python websocket client side, and I don't see anything obviously related in the calico-node logs.  This is definitely outside my area of expertise when it comes to debugging.  Is there something else I should be looking at?  I also can't explain why @tmjd's configuration works with those command line arguments but without setting podCIDR, or why my configuration seems to care only about podCIDR.

For the original issue I opened this for, I think the best resolution would be adding something to the documentation about podCIDR and minikube.  The websocket issue should probably be tracked separately, I can create another issue if that's apppropriate.

**Comment by tmjd** [comment]
Could you try with the following options, it looks like maybe the config has changed.  These worked for me with minikube v0.22.1

```
minikube start --network-plugin=cni --host-only-cidr 172.17.17.1/24 \
    --extra-config=kubelet.PodCIDR=192.168.0.0/16 \
    --extra-config=proxy.ClusterCIDR=192.168.0.0/16 \
    --extra-config=controller-manager.ClusterCIDR=192.168.0.0/16 \
    --extra-config=controller-manager.CIDRAllocatorType=RangeAllocator \
    --extra-config=controller-manager.AllocateNodeCIDRs=true
```

Also I'm not sure what python client you are referring to.  Could you point us to what you are using and an example command you are using?

**Comment by ceridwen** [comment]
I tried it again with minikube 0.22.1 and the above `minikube start` command.  Same fundamental issue, different manifestation:

```
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.5/site-packages/kubernetes/client/ws_client.py", line 253, in websocket_call
    client = WSClient(configuration, get_websocket_url(url), headers)
  File "/home/user/.local/lib/python3.5/site-packages/kubernetes/client/ws_client.py", line 71, in __init__
    self.sock.connect(url, header=header)
  File "/home/user/.local/lib/python3.5/site-packages/websocket/_core.py", line 211, in connect
    options.pop('socket', None))
  File "/home/user/.local/lib/python3.5/site-packages/websocket/_http.py", line 77, in connect
    sock = _ssl_socket(sock, options.sslopt, hostname)
  File "/home/user/.local/lib/python3.5/site-packages/websocket/_http.py", line 182, in _ssl_socket
    sock = _wrap_sni_socket(sock, sslopt, hostname, check_hostname)
  File "/home/user/.local/lib/python3.5/site-packages/websocket/_http.py", line 160, in _wrap_sni_socket
    server_hostname=hostname,
  File "/usr/lib/python3.5/ssl.py", line 377, in wrap_socket
    _context=self)
  File "/usr/lib/python3.5/ssl.py", line 752, in __init__
    self.do_handshake()
  File "/usr/lib/python3.5/ssl.py", line 988, in do_handshake
    self._sslobj.do_handshake()
  File "/usr/lib/python3.5/ssl.py", line 633, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:645)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/code/test_automation/test_automation/test_policy.py", line 91, in test_network_policy
    utilities.log_info(kube.wait_for_pod_tcp(connected_pod, other_outside_ip))
  File "/home/user/code/test_automation/test_automation/kube.py", line 537, in wait_for_pod_tcp
    times=times)
  File "/home/user/code/test_automation/test_automation/utilities.py", line 173, in wait_for_tcp
    exception_or_condition)
  File "/home/user/code/test_automation/test_automation/utilities.py", line 131, in wait_for_condition
    value = function(*args, **kws)
  File "/home/user/code/test_automation/test_automation/utilities.py", line 153, in f
    return function(*curried_args)
  File "/home/user/code/test_automation/test_automation/resources.py", line 376, in exec_in
    tty=False)
  File "/home/user/.local/lib/python3.5/site-packages/kubernetes/client/apis/core_v1_api.py", line 907, in connect_get_namespaced_pod_exec
    (data) = self.connect_get_namespaced_pod_exec_with_http_info(name, namespace, **kwargs)
  File "/home/user/.local/lib/python3.5/site-packages/kubernetes/client/apis/core_v1_api.py", line 1012, in connect_get_namespaced_pod_exec_with_http_info
    collection_formats=collection_formats)
  File "/home/user/.local/lib/python3.5/site-packages/kubernetes/client/api_client.py", line 335, in call_api
    _preload_content, _request_timeout)
  File "/home/user/.local/lib/python3.5/site-packages/kubernetes/client/api_client.py", line 148, in __call_api
    _request_timeout=_request_timeout)
  File "/home/user/.local/lib/python3.5/site-packages/kubernetes/client/api_client.py", line 365, in request
    headers=headers)
  File "/home/user/.local/lib/python3.5/site-packages/kubernetes/client/ws_client.py", line 259, in websocket_call
    raise ApiException(status=0, reason=str(e))
kubernetes.client.rest.ApiException: (0)
Reason: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:645)
```

The Kubernetes API calls seem to work as long as they don't involve websockets.

This is the official Python Kubernetes client: https://github.com/kubernetes-incubator/client-python .  An example of a call that uses websockets is [exec](https://github.com/kubernetes-incubator/client-python/blob/master/kubernetes/docs/CoreV1Api.md#connect_get_namespaced_pod_exec).  I'm using exec, but I suspect other calls that involve websockets like watch will also fail.

**Comment by tmjd** [comment]
The errors in your last post seem to indicate a problem with the SSL certificates, which makes me think a connection is being allowed.  If you could try a more simple connection perhaps with telnet or netcat and can show it being denied then I would understand a Calico problem, but if the connection is being allowed and traffic is flowing then I don't understand how it is a Calico issue.

I found https://github.com/kubernetes-incubator/client-python#hostname-doesnt-match, you may want to check out as it seems to be in the same area where you're having a problem (SSL error and I see  check_hostname too).

**Comment by tmjd** [comment]
I'm going to close this for now since it seems to be a problem with SSL as I mentioned in my previous comment. If you can provide additional information, particularly on why this is an issue Calico is causing, I'm happy to reopen this issue.
