### ISSUE TITLE
Clarify default Pool creation env vars are only honored for default pool creation

### ISSUE THREAD

**Issue by tmjd** [projectcalico/calico#1106]
Users regularly try to change the Pool CIDR or IPIP enabled by changing the env vars that are only used at the default pool creation time. It needs to be ensured the reference docs make this clear but also comments should be added to our manifests so that it is clear in the manifests that they are only used if a pool needs to be created.

**Comment by caseydavenport** [comment]
This has been fixed in the reference docs and manifests (via comments).
