### ISSUE TITLE
Provide example dashboard for Calico metrics

### ISSUE THREAD

**Issue by zihaoyu** [projectcalico/calico#1113]
Now that Calico exports Prometheus metrics, I'm wondering if Calico team can provide an example dashboard for those metrics, preferably in Grafana's JSON format. 

For example, CoreOS provides a [sample JSON](https://coreos.com/etcd/docs/latest/op-guide/grafana.json) for etcd monitoring.

**Comment by caseydavenport** [comment]
This would be great.

Is there anyone out there who has an example they'd be willing to contribute as a base?

**Comment by zihaoyu** [comment]
@caseydavenport I've created our first version of Calico dashboard. Attached is a screenshot. [Source here](https://gist.github.com/zihaoyu/64684465eb10690e6b0e8289a07c0629). Feedback welcome.

![grafana calico us east 1](https://user-images.githubusercontent.com/464299/30649690-e878015a-9dee-11e7-8c98-4e3c4dbcf0eb.png)

While searching, I also found [another dashboard](https://grafana.com/dashboards/3244) shared on grafana.com.

**Comment by dhananjaysathe** [comment]
What scrape config did you use ? @zihaoyu
