### ISSUE TITLE
Wrong Felix IptablesAllowAction setting in docs

### ISSUE THREAD

**Issue by Dirbaio** [projectcalico/calico#1116]
The Felix docs [here](https://docs.projectcalico.org/v2.5/reference/felix/configuration) document a setting called `IptablesAllowAction`, but Felix actually uses two settings named `IptablesFilterAllowAction` and `IptablesMangleAllowAction`, for the `filter` and `mangle` tables respectively.

**Comment by caseydavenport** [comment]
Fixed in latest docs (at least in v3.0+)
