### ISSUE TITLE
Workload Endpoint (routes, etc) for a pod being deleted a few minutes after pod creation

### ISSUE THREAD

**Issue by bradbehle** [projectcalico/calico#1117]
We have seen a few cases now where a pod is created in Kubernetes, seems to be working, and then a minute or more later, Calico deletes the WEP and route from underneath the pod, leaving the pod up and running but without any networking.  This last time we saw this we collected the /var/log/calico/* logs and /var/log/syslog, which seem to show that the pod and networking were set up correctly, and then about 17 minutes later calico removed the WEP and route (felix log and syslog specifically).  I'll attach the log files once I get them (soon), here is the IP and pod info:
```dashmpp-head-0                1/1       Running   0          23h       172.30.224.36    xxxxxxxx```

## Expected Behavior
Pod shouldn't have networking pulled out from under it

## Current Behavior
Pod stays there, but networking is removed

## Steps to Reproduce (for bugs)
Can't reproduce at will, but have seen this twice in a few days.  The first time it was about 1 minute after pod creation that the networking was deleted from the pod

## Context
Makes the pod unusable

## Your Environment
* Calico version: 2.1.5 (calico-node managed by systemd)
* Orchestrator version: kubernetes 1.5.6
* Operating System and version: Ubuntu 16.04.2

**Comment by bradbehle** [comment]
Here are the logs
[calico.zip](https://github.com/projectcalico/calico/files/1315066/calico.zip)

**Comment by caseydavenport** [comment]
This sounds like it could be related to or a result of https://github.com/projectcalico/libcalico/issues/189.

That issue causes the policy controller to remove the container ID metadata from a given WEP, which means the CNI plugin is unable to determine whether or not the DEL call it has received from the kubelet is or the active container or an older exited container.

Will need to look at the logs to make sure, but I have a strong hunch that's what it happening here.  If so, the fix is in master and will be available in Calico v2.6.0.

**Comment by bradbehle** [comment]
If it is related to https://github.com/projectcalico/libcalico/issues/189  then is the fix to get the newest (master) policy-controller?  or do we need a new felix/calico-node and/or CNI as well?

**Comment by caseydavenport** [comment]
The fix would be to use the master version of the policy controller AND the master version of Felix (in `calico/node:master`).  If that doesn't fix this issue then I suspect it is something other than what I linked above.

I wouldn't recommend running those in production until we release Calico v2.6.0 which will be this month.

**Comment by bradbehle** [comment]
Is there a way you can verify if this is the same problem based on the logs I provided?

**Comment by caseydavenport** [comment]
@bradbehle Just got around to looking through those logs.

It looks to be a similar but different type of bug in the CNI plugin.  I've proposed a fix here: https://github.com/projectcalico/cni-plugin/pull/383

**Comment by bradbehle** [comment]
@caseydavenport Thanks.  Can this fix make it in to Calico 2.6.0?  We are hitting it fairly often and need it ASAP

**Comment by caseydavenport** [comment]
@bradbehle yep this will go into v2.6.0

**Comment by caseydavenport** [comment]
Fix for this was merged in https://github.com/projectcalico/cni-plugin/pull/383.

Cutting v2.6.0-RC2 tonight which will include the fix if you'd like to try it out.  Thanks @bradbehle!
