### ISSUE TITLE
Need to ship confd event index cleared fix

### ISSUE THREAD

**Issue by fasaxc** [projectcalico/calico#1120]
https://github.com/projectcalico/confd/issues/32 in our confd fork is pretty nasty (IIUC); we have a fix on our confd master but we haven't cut a release and revved our pin in calico/node.

## Your Environment

* Calico version: 2.5.1

**Comment by heschlie** [comment]
This fix was included in in confd-v0.12.1-calico-v0.3.0 I believe, which is what we're using in v2.5.0:

https://github.com/projectcalico/confd/compare/v0.12.1-calico-0.3.0...master#diff-f70e0c8bf930016867d4de1766575386R147

@gunjan5 had to cut a new release to rev libcalico-go in confd to get CRD support for calico/node v2.5.0, if we're still hitting this issue then we need to rethink the fix :frowning_face:

**Comment by fasaxc** [comment]
I don't think it was.  Here's that line of code in the `v0.12.1-calico-0.3.0` tag, it's the left-hand-side of the diff you posted:

https://github.com/projectcalico/confd/blob/v0.12.1-calico-0.3.0/backends/etcd/client.go#L147

**Comment by heschlie** [comment]
@bcreane did a confd release today that has this in it, `v0.12.1-calico-0.4.0`.
