### ISSUE TITLE
v2.6.0-rc2: calicoctl get profile -o wide does not have TAGS

### ISSUE THREAD

**Issue by tmjd** [projectcalico/calico#1128]
The K8s Advanced Policy Tutorial 
https://docs.projectcalico.org/v2.6/getting-started/kubernetes/tutorials/advanced-policy#check-using-calicoctl
has the following

```
$ calicoctl get profile -o wide
NAME                          TAGS
k8s_ns.advanced-policy-demo   k8s_ns.advanced-policy-demo
k8s_ns.default                k8s_ns.default
k8s_ns.kube-public            k8s_ns.kube-public
k8s_ns.kube-system            k8s_ns.kube-system
```

When the above command is ran I get the following output

```
$ ./calicoctl get profile -o wide
NAME                          TAGS   
k8s_ns.advanced-policy-demo          
k8s_ns.default                       
k8s_ns.kube-public                   
k8s_ns.kube-system
```

## Expected Behavior
I expect the docs example output to match what I see when running the same commands.

## Current Behavior
The output doesn't match

## Possible Solution
- Update the docs
  - Remove that command (I'm not sure why it is included)
  - or switch to get policy instead of profile
- or Fix whatever is missing

## Your Environment
* Calico version: v2.6.0-rc2
* Orchestrator version (e.g. kubernetes, mesos, rkt): K8s
* Operating System and version: Container Linux 1465.7.0
* Using etcd with TLS

**Comment by tmjd** [comment]
Here is the output from `get policy` at that time if we want to switch it to that.

```
$ ./calicoctl get policy -o wide
NAME                                            ORDER   SELECTOR
knp.default.advanced-policy-demo.default-deny   1000    calico/k8s_ns == 'advanced-policy-demo'
```

**Comment by caseydavenport** [comment]
So this is because we've commonized the KDD and etcd conversion code: https://github.com/projectcalico/libcalico-go/blob/master/lib/backend/k8s/conversion.go#L98

The KDD code never put tags into the profile, whereas the etcd code used to.

Tags are deprecated, so on the one hand we could potentially just update the docs for this.

However, if people are using tags for some reason then this change to the way the policy controller works might break them.

**Comment by caseydavenport** [comment]
The right thing to do here is to add back support for tags into both KDD and etcd by adding them to the conversion code linked above.

That unfortunately means another full release of Felix, Typha, etc, but it should be low-risk and not require any special testing.

CC @bcreane

**Comment by caseydavenport** [comment]
@tmjd I've talked this over and think that we should leave it as-is and update the docs.

Reason being that tags are deprecated and we can just release note the change.

So actions here:
- Update demo to remove the tags
- Make sure we include in a release note that tags are no longer written by the policy controller.
