### ISSUE TITLE
in v2.6.0-rc2 tag, _data/versions.yml doesn't contain RC2 section 

### ISSUE THREAD

**Issue by lwr20** [projectcalico/calico#1130]
## Expected Behavior
Having checked out the v2.6.0-rc2 tag, if I run `make st` in the `calico_node` directory, I get all the versions of components from RC1.

## Current Behavior
Having checked out the v2.6.0-rc2 tag, if I run `make st` in the `calico_node` directory, I get all the versions of components from RC2 instead.

## Possible Solution
https://github.com/projectcalico/calico/blob/v2.6.0-rc2/_data/versions.yml should have an RC2 section.  

## Steps to Reproduce (for bugs)
```
git checkout upstream/v2.6.0-rc2
cd calico_node
make st
```

**Comment by bcreane** [comment]
I confirmed the docker images have the right felix (2.6.0-rc2). I think I probably just cut the tag from the wrong point in the commit log, but all the binaries are correct. @caseydavenport suggests that we keep an eye on the binaries, but that we can avoid fixing this issue (or cutting a new RC) for the time being.

**Comment by caseydavenport** [comment]
Yeah, given this is an RC and we're planning on cutting the release this week then I think we can close this as "wontfix" for now.

If you'd like to build RC2 or run tests you should use:

```
make RELEASE_STREM=v2.6.0-rc2 X
```

from `master`

**Comment by bcreane** [comment]
I'm pretty sure I built the release on my branch and then switched over to master w/o fetching. So the build should be right (along with the release tarball), but the git tag is wrong. I'll stop trying to save time (or at least do it right next time).
