### ISSUE TITLE
Update advanced policy demo for k8s 1.8

### ISSUE THREAD

**Issue by caseydavenport** [projectcalico/calico#1131]
k8s 1.8 introduces CIDR / egress policies.  Our advanced policy demo says that it doesn't support these things.

https://docs.projectcalico.org/v2.5/getting-started/kubernetes/tutorials/advanced-policy

> Kubernetes NetworkPolicy does not provide a way to prevent outgoing connections from pods. However, Calico does. In this section we’ll create a Policy using calicoctl which prevents all outgoing connections from Kubernetes pods in the advanced-policy-demo Namespace.

## Expected Behavior

Perhaps it should be updated to use the k8s API?

## Current Behavior

It's a mix of k8s / Calico APIs

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Calico version
* Orchestrator version (e.g. kubernetes, mesos, rkt):
* Operating System and version:
* Link to your project (optional):

**Comment by dtzar** [comment]
Is Calico 2.6.0 KDD install with K8s 1.8.0 supposed to currently support egress policies?  The policies are present when I apply the [example deny all egress traffic](https://kubernetes.io/docs/concepts/services-networking/network-policies/#default-deny-all-egress-traffic) but the egress traffic from pods still is allowed.

**Comment by ozdanborne** [comment]
@dtzar please open a new issue and share some of the yaml you are using. Thanks!

**Comment by caseydavenport** [comment]
@dtzar yes, that should be supported.  Like @ozdanborne said, I think that should be its own issue. 

Thanks!

**Comment by caseydavenport** [comment]
@dtzar FYI I reproduced your issue and tracked it down to a bug in v2.6.0 not having the correct release artifacts.  I've pushed v2.6.1 and verified that it is performing as expected.  Thanks for notifying us!

**Comment by dtzar** [comment]
Thanks for the quick fix!  The [2.6.1 release page](https://docs.projectcalico.org/v2.6/releases/) says incorrectly that calico-node is still at 2.6.0 vs [2.6.1](https://github.com/projectcalico/calico/releases/tag/v2.6.1).

**Comment by dtzar** [comment]
I went ahead and started on creating this guidance here: https://github.com/dtzar/calico/commit/4b3e1c8ec0b5c8165a33ae5d8953842dd18d817a

The only thing I haven't gotten to work is the allow Nginx and allow egress policies.  Admittedly, I haven't spent much time playing with the policy syntax - but if someone could help with that it would be great.

**Comment by ozdanborne** [comment]
To close the loop here, It looks like you opened https://github.com/dtzar/calico/commit/4b3e1c8ec0b5c8165a33ae5d8953842dd18d817a as a PR (https://github.com/projectcalico/calico/pull/1174) which @caseydavenport forked and submitted/merged here https://github.com/projectcalico/calico/pull/1184.

Are we good to close this issue now?
