### ISSUE TITLE
Update document for host endpoint untracked policy.

### ISSUE THREAD

**Issue by song-jiang** [projectcalico/calico#1134]
Untracked policy is designed to secure traffic going to local process. Packet going to the workload will be dropped if it has been accepted by untracked policy because the default rules for workload regard the packet has an invalid conntrack state. This should be clearly stated in the document.

**Comment by tmjd** [comment]
@song-jiang do you know if this has been addressed or the docs are still lacking?

**Comment by song-jiang** [comment]
@tmjd I think it has been addressed.
