### ISSUE TITLE
calico-ipam config is not compatible with bird/calico-bgp-daemon behavior

### ISSUE THREAD

**Issue by toshiiw** [projectcalico/calico#1138]
calico-ipam is configured with StrictAffinity = false, but the BGP daemons advertises routes based on AffineBlocks. This would cause uncommunicatable Pod when some of the blocks are full.

## Expected Behavior
Enforcing strict affinity would be the simplest solution.

## Current Behavior
bird has bird_aggr.cfg from calico_node that makes the daemon to only look at AffineBlocks for route advertisements.
calico-bgp-daemon works similarly.

## Possible Solution

Set strict_affinity = true in the IPAM config.

## Steps to Reproduce (for bugs)

1. Start a lot of Pods so that there's no free AffineBlocks to allocate. Then start even more so that IPAM allocation happens from other node's AffineBlock.
2. See the above Pod isn't routed correctly.

## Context

Found during reading the code. Not actually tested.

## Your Environment

* Calico version 2.5
* Orchestrator version (e.g. kubernetes, mesos, rkt): k8s v1.7

**Comment by caseydavenport** [comment]
We can't enable strict-affinity across-the-board, but perhaps we can find a way to enable it when using GoBGP?

Does GoBGP not advertise the exceptions? I would expect the affinity blocks to be advertised, but for the "exceptions" we'd advertise individual /32 routes which take precedence. That would be the ideal solution in my mind (and is what BIRD based deployments do today)

**Comment by toshiiw** [comment]
Thanks @caseydavenport , I was not good at reading calico_aggr.cfg etc.
BIRD seems to be okay. calico-bgp-daemon seems to work until it gets killed and restarts.
It needs to list routes at initialization.

**Comment by toshiiw** [comment]
I'm working on a fix for calico-bgp-daemon.
https://github.com/toshiiw/calico-bgp-daemon/tree/watchkernel-fix
