### ISSUE TITLE
calico node error in kubeadm environment

### ISSUE THREAD

**Issue by like-inspur** [projectcalico/calico#1139]
[root@master1 ~]# kubectl get pods -n kube-system -o wide
NAME READY STATUS RESTARTS AGE IP NODE
calico-etcd-2p27t 1/1 Running 0 7m 10.110.17.59 master1.kubeadm
calico-node-6753t 1/2 CrashLoopBackOff 6 7m 10.110.17.59 master1.kubeadm
calico-policy-controller-336633499-dn9dp 1/1 Running 0 7m 10.110.17.59 master1.kubeadm

[root@master1 ~]# kubectl log calico-node-6753t -n kube-system calico-node
W0927 21:51:31.309272 32763 cmd.go:392] log is DEPRECATED and will be removed in a future version. Use logs instead.
Skipping datastore connection test
Using autodetected IPv4 address on interface eth0: 10.110.17.59/24
Calico node 'localhost.localdomain' is already using the IPv4 address 10.110.17.59:

Check the node configuration to remove the IP address conflict
Terminating
Calico node failed to start
CentOS version：7.3.1611
kubernetes version：1.7.6
Docker version：1.12.6
Calico version：2.4.1

**Comment by caseydavenport** [comment]
@like-inspur it looks like you've got a node conflict - `localhost.localdomain` has already claimed that IP address.

You might need to delete that node with calicoctl in order to start the new one.  See here for more info: https://docs.projectcalico.org/v2.5/usage/decommissioning-a-node

**Comment by like-inspur** [comment]
calicoctl get node is null，how can i decommissioning node "localhost.localdomain"

**Comment by like-inspur** [comment]
two host named "localhost.localdomain" add calico failed，so i kubeadm reset，then the first node can't add。calico node information store in etcd，but i already reset etcd environment，so why？

**Comment by tmjd** [comment]
My comments below are assuming you deployed using the manifest from the Calico "Kubeadm Hosted Install" at https://docs.projectcalico.org/v2.5/getting-started/kubernetes/installation/hosted/kubeadm/:

The etcd directory is mounted from the host system at `/var/etcd`.  When you say you reset the etcd environment did you delete that directory (or at least its contents)?

If `calicoctl get node` returns nothing then most likely you are not configured to access the correct etcd datastore (you might be accessing the one k8s is using). One way to check if you are pointed at the datastore calico-node is using is to run `calicoctl version`, if the `Cluster Type` and `Cluster Version` are `unknown` then no calico-node has used that datastore. If you are running `calicoctl` from the k8s master or one of the nodes you should be able to do `export ETCD_ENDPOINTS=http://10.96.232.136:6666` and then you can run `calicoctl get nodes` and should see results.

**Comment by ozdanborne** [comment]
This issue has been open for quite some time. Given @tmjd 's instructions as well as the new doc on decomissioning a node (https://docs.projectcalico.org/v2.6/usage/decommissioning-a-node) , I'm going to close. 

please reopen if you are still having issues.
