### ISSUE TITLE
Test #1104 in AWS across a subnet boundary

### ISSUE THREAD

**Issue by caseydavenport** [projectcalico/calico#1150]
#1104 modifies the BGP attribute used in cross-subnet mode, but hasn't been tested in public cloud.

We should test this in AWS across a VPC subnet boundary to make sure it sill behaves as expected. I don't see why it wouldn't but we don't currently have any CI running in this AWS configuration to be 100% confident.

**Comment by nightmeng** [comment]
The bgp_next_hop isn't defined in some route rules, and the following is log of the bird:

```
bird: filters, line 18: ~ applied on unknown type pair
```

So, before we use bgp_next_hop, we should check if the bgp_next_hop is defined or not:

```
filter calico_ipip {

  if ( net ~ 10.233.64.0/18 ) then {
    if defined(bgp_next_hop) && (bgp_next_hop ~ 192.168.137.0/24 ) then {
      krt_tunnel = "";
    } else {
      krt_tunnel = "tunl0";
    }
    accept;
  }

  accept;
}
```
And I have issue a new pull request: #1218

**Comment by ozdanborne** [comment]
I just finished running a rig on AWS and confirmed that Calico is correctly using the tunl0 only when traffic is crossing subnets (when in CrossSubnet) mode.
