### ISSUE TITLE
Document tolerations requirement in "Kubernetes Datastore Hosted Install"

### ISSUE THREAD

**Issue by tmjd** [projectcalico/calico#1164]
The "Kubernetes Datastore Hosted Install" section does not mention the assumption that the tolerations in the manifests are written for a kubeadm deployed cluster.  We should document that and probably suggest how to check the taints).   

## Expected Behavior
Requirements documented

## Current Behavior
In the "Kubernetes Datastore Hosted Install" the tolerations assume the taints kubeadm configures.

## Possible Solution
Document the tolerations, how to check the taints, and possibly link to how to set the tolerations if there is a good link for that.

## Context
#1153

**Comment by ozdanborne** [comment]
Just want to clarify that our stance on tolerations is that "Calico manifests include tolerations for some of the commonly used taints in Kubernetes, of which the kubeadm master taints is one." Hope that makes sense.

**Comment by caseydavenport** [comment]
This isn't relevant any more - we tolerate all NoSchedule taints now.
