### ISSUE TITLE
calico-node logs show ipsets.go 502: Bad return code from 'ipset list'. error=exit status 1 family="inet" stderr="ipset v6.32: Kernel error received: Operation not permitted\n"

### ISSUE THREAD

**Issue by ylfforme** [projectcalico/calico#1176]
I install calico follow this page https://docs.projectcalico.org/v2.6/getting-started/kubernetes/installation/hosted/calico.yaml and I got this error [ERROR][2348] ipsets.go 502: Bad return code from 'ipset list'. error=exit status 1 family="inet" stderr="ipset v6.32: Kernel error received: Operation not permitted\n"
I don't understand, my host can run ipset just fine. Is there anything I can do to fix this error?
My calico version is v2.6.1
My kubernetes version is 
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.6", GitCommit:"4bc5e7f9a6c25dc4c03d4d656f2cefd21540e28c", GitTreeState:"clean", BuildDate:"2017-09-14T06:55:55Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.6", GitCommit:"4bc5e7f9a6c25dc4c03d4d656f2cefd21540e28c", GitTreeState:"clean", BuildDate:"2017-09-14T06:36:08Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

**Comment by ylfforme** [comment]
I konw what's wrong, I deleted   securityContext: privileged: true this config. I added it back now problem solved

**Comment by caseydavenport** [comment]
@ylfforme thanks for reporting back with the solution!
