### ISSUE TITLE
Can calico deploy on arm64  now？

### ISSUE THREAD

**Issue by y00369814** [projectcalico/calico#1179]
Can calico deploy on arm64  now？
## Expected Behavior

I expect to deploy calico on arm64.

## Current Behavior

I am a newer to calico, and I can not find calicoctl release version for arm64. So I download the source code to build, then I find calico/protoc image cannot run on arm64 because the binary the X86_64. What can I do if I want  to deploy calico on arm64.

**Comment by caseydavenport** [comment]
@y00369814 thanks for raising - right now there are no official Calico builds for arm64.

However, I believe @TrevorTaoARM is working on adding arm64 support. Would love to get those PRs merged and release official arm builds.

**Comment by caseydavenport** [comment]
Quick update here: There are a number of PRs in progress to add the capability to compile Calico for different platforms (including ARM).

While we're interested in accepting the contributions, there aren't any immediate plans to test or host official `calico/*` images, so it will be up to third parties to build and maintain those.

I'm going to close this for now.
