### ISSUE TITLE
Devstack install with Calico appears to use apt even when deploying on rpm-based distro's

### ISSUE THREAD

**Issue by kprabhak** [projectcalico/calico#1182]
Our devstack install appears to not switch over to yum when deploying on rpm-based distro's. Need to dig into this further and do some clean up.

**Comment by kprabhak** [comment]
Looks like it might just be the two "apt-get" lines in https://git.openstack.org/cgit/openstack/networking-calico/tree/devstack/bootstrap.sh
Will maybe submit a patch once I've had a chance to test it out in a few days.

**Comment by caseydavenport** [comment]
That script has the following disclaimer:

>  and is designed for use on a fresh Ubuntu Trusty VM, 

I believe this is working as expected for now.
