### ISSUE TITLE
Assignment of IPIP tunnel address should use handles to close down error windows where IP addresses get leaked

### ISSUE THREAD

**Issue by robbrockbank** [projectcalico/calico#1195]
Viewed from code reading:

The IPIP tunnel assignment first allocates an IP address and then updates the Calico config to reference that IP.

If an error occurs setting that IP address then it may not be possible to unallocate the IP and hence we'll leak an IP address.  If we used a handle to indicate that the IP was assigned for IPIP address for node X then we can use that to look up the current assignment when we next start the node. 

Worse is in deallocation.  If we unallocated the IP and then fail to update the node settings, then next restart we'll deallocate the IP again - which is sad because the IP could be allocated to a container.

**Comment by caseydavenport** [comment]
I think the design here would be to come up with a scheme for calculating a handleID based on a given Node object, and then pass it to the [allocation code here](https://github.com/projectcalico/node/blob/v3.4.0-0.dev/pkg/allocateipip/allocate_ipip_addr.go#L156).

Then, update all instances of `ReleaseIPs` in that file  to use ReleaseByHandle() instead.

@robbrockbank does that sound right?

The tricky part here is then, what do we do about upgrades from old code where we didn't allocate a handle? I think we'd need some sort of fallback in that scenario.

One option:
- Check if the node has an IP 
- If it does, and that IP is allocated but without a handle, release it and reallocate a new IP using the desired handle. 
- If it does not, then allocate a new IP using a handle and carry on as normal.

This has the downside that we're reallocating ipip tunnel IPs on upgrade when we might not need to. This might be OK, but would reset and host->remote pod connections from that node. /shrug.

We could perhaps make that less likely by attempting to reallocate the exact same IP address - there's no guarantee we'd get it, but I bet in most cases we would. If we fail, then we could try to grab some other address.

**Comment by caseydavenport** [comment]
Fixed here: https://github.com/projectcalico/node/pull/443
