### ISSUE TITLE
Project Calico getting freezes while starting with minikube 

### ISSUE THREAD

**Issue by anirban37** [projectcalico/calico#1210]
## Expected Behavior
Trying to install with `minikube `and expected to start containers in the calico-node pod

## Current Behavior
I have `minikube ` version `v0.19.0` installed and configured in Ubuntu 14.04.5, where I am trying to install Calico which is getting frozen or hanged in the middle of installation steps.

## Steps to Reproduce (for bugs)
1. Download `minikube ` version `v0.19.0` from GitHub : `curl -Lo minikube https://storage.googleapis.com/minikube/releases/v0.19.0/minikube-linux-amd64 && chmod +x minikube && sudo mv minikube /usr/local/bin/

2. Downloaded `kubectl `from GitHub : ```
 wget https://storage.googleapis.com/kubernetes-release/release/v1.4.4/bin/linux/amd64/kubectl
chmod +x kubectl
sudo mv kubectl /usr/local/bin/kubectl`

3.  `minikube start --memory 2096 --network-plugin=cni --host-only-cidr=192.168.0.0/16`

4. Downloaded `https://github.com/projectcalico/calico/tree/master/v2.6/getting-started/kubernetes/installation/hosted/kubernetes-datastore/calico-networking/1.7/calico.yaml` into local `/usr/local/bin/`

5. `chmod +x calico.yaml`

6. `kubectl apply -f calico.yaml`

## Context
I'm trying to install calico on my local machine for testing network policy. I am not sure if it is an issue with calico or minikube as it is getting hanged on my local system and I have to abort the operation everytime. I also tried `minikube  delete` and then tried to install again. But results the same
## Your Environment

* Calico version:- v2.6
* Orchestrator version (e.g. kubernetes, mesos, rkt):   minikube  version `v0.19.0
* Operating System and version:  Ubuntu 14.04.5

**Comment by tmjd** [comment]
See my comment here for using calico on minikube https://github.com/projectcalico/calico/issues/1013#issuecomment-325689943
You can try using the v0.21 directions I have there with the version you are using but I'd suggest updating to the latest minikube.

**Comment by tmjd** [comment]
I'm going to close this as I hope my previous comment helped resolved the issue.  If this still is a problem please provide what you've tried based off the link in the previous comment and what problems you still see and I'll reopen this issue..
