### ISSUE TITLE
Missing Documentation for IPIP Configuration in AWS

### ISSUE THREAD

**Issue by Viji-Sarathy-Bose** [projectcalico/calico#1215]
In the documentation for deploying Calico on AWS at https://docs.projectcalico.org/v2.6/reference/public-cloud/aws, the Requirements section states that traffic on all ports should be allowed for IPIP protocol. However, while configuring a Security Group in AWS, IPIP is not listed among the protocols for which you can add a custom rule. I gathered from one of the users that we will have select protocol #4 (IPv4). If this is indeed true, it would be best to add this piece of information to the documentation.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Calico version
* Orchestrator version (e.g. kubernetes, mesos, rkt):
* Operating System and version:
* Link to your project (optional):

**Comment by caseydavenport** [comment]
CC @colhom, who I believe discovered that both protocol 4 and protocol 94 must be allowed.
