### ISSUE TITLE
calicoctl KDD manifest didn't just work with hosted install

### ISSUE THREAD

**Issue by fasaxc** [projectcalico/calico#1276]
I applied these two manifests on a CRC, kubeadm cluster (doing v3.0 alpha testing):

https://docs.projectcalico.org/master/getting-started/kubernetes/installation/hosted/rbac-kdd.yaml

https://docs.projectcalico.org/master/getting-started/kubernetes/installation/hosted/kubernetes-datastore/calico-networking/1.7/calico.yaml

This got calico working without any config tweaks.  Then I tried the calicoctl manifest:

https://docs.projectcalico.org/master/getting-started/kubernetes/installation/hosted/kubernetes-datastore/calicoctl.yaml

I had hoped that it'd pick up the RBAC just like calico/node did but it seems not:

```
$ kubectl exec -n kube-system calicoctl calicoctl get wep
Failed to get resources: connection is unauthorized
command terminated with exit code 1
```

The version command partially works, giving my some hope that I'm actually running calicoctl:

```
$ kubectl exec -n kube-system calicoctl calicoctl version
Client Version:    v2.0.0-alpha1-rc2-13-g2434301a
Build date:        2017-10-27T04:01:42+0000
Git commit:        2434301a
Unable to retrieve Cluster Version or Type:  connection is unauthorized
command terminated with exit code 1
```

calico repo master is currently a742aa6d063bd3951b35e80926d96369bfc6fdc6
## Expected Behavior

It'd be nice if we could make the calicoctl pod just work.  

## Current Behavior

Permission error with default config.

## Possible Solution

- Add RBAC service account for calicoctl?
- Maybe we should pull it into the main set-up guide for hosted so it gets more attention.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Calico version: 3.0 alpha1 rc2
* Orchestrator version (e.g. kubernetes, mesos, rkt): 

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.2", GitCommit:"bdaeafa71f6c7c04636251031f93464384d54963", GitTreeState:"clean", BuildDate:"2017-10-24T19:48:57Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.2", GitCommit:"bdaeafa71f6c7c04636251031f93464384d54963", GitTreeState:"clean", BuildDate:"2017-10-24T19:38:10Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```

* Operating System and version: Linux smc--kubeadm-master 4.10.0-37-generic #41~16.04.1-Ubuntu SMP Fri Oct 6 22:42:59 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

* Link to your project (optional):

**Comment by caseydavenport** [comment]
We probably want to port this back to v2.x as well - should just be a matter of shipping RBAC with the calicoctl manifest.

**Comment by heschlie** [comment]
Yea it looks like it just needs the service account added to the manifest, PR incoming shortly.
