### ISSUE TITLE
Manually reload iptables using calicoctl

### ISSUE THREAD

**Issue by perandersson** [projectcalico/calico#1292]
## Expected Behavior

The company that I'm working for have a special department that reloads iptables from time to time using a remote script. This will remove calico's iptables rules for between 60-90 seconds everytime this happens.

I want calico to either copy it's iptables- and route rules into a separate file that can be used for reloading them; or a CLI command that manually triggers a reload of the rules.

## Current Behavior

iptables rules and routes are gone for up to 90 seconds everytime our firewall department "reloads" the servers iptables rules

## Possible Solution

I found out that I can "manually" reload the iptables rules by doing something like this - but it feels like an ugly hack (I'm not really sure if it's a good or bad idea to do it like this)

```bash
/usr/local/bin/calicoctl get policy -o yaml | /usr/local/bin/calicoctl replace -f -
```

I want a command like "calicoctl reload iptables" or a command like "calicoctl get iptables > file" that I can use iptables-restore on.

## Context

All calico's DROP and ACCEPT rules are gone for 60 seconds after iptables are "reloaded" by our firewall department. They must be able to do this at day-time, while access to the "calico cluster" is available.

This is considered a security risk by us, especially when this happens while we use Kubernetes Network Policies

## Your Environment

Calico installed by kubespray (~master-ish):

```bash
$ calicoctl version
Client Version:    v1.5.0
Build date:        2017-08-29T04:02:07+0000
Git commit:        118b8ae1
Cluster Version:   v2.5.0
Cluster Type:      kubespray,bgp
```
Operating System = CentOS 7.3
Orchestrator version = Kubernetes 1.8.1
Docker version = 1.31.1

**Comment by caseydavenport** [comment]
Your workaround using calicoctl seems like a good way to do this, though it will trigger a refresh across the entire cluster (not just a particular node). Not sure if that matters for you in your case.

Alternatively, I'd suggest writing a script which saves the Calico iptables rules and can restore them master.

You could also change felix's iptables refresh interval to something smaller, but this can potentially have performance impacts depending on the size of your cluster and the number of policies.

**Comment by perandersson** [comment]
> Your workaround using calicoctl seems like a good way to do this, though it will trigger a refresh across the entire cluster (not just a particular node). Not sure if that matters for you in your case.

Okay, that's good to know. Updating all the nodes in the cluster is not optimal, but it's better then nothing. 

Regarding the command above, is there more than `policy` that I have to take into account if we end up using this approach (like profile, node etc.)? and also, do you think that using replace is a feature that will keep working in the long run?

> Alternatively, I'd suggest writing a script which saves the Calico iptables rules and can restore them master.

The script that our firewall deparment uses disregards all rules saved by the `iptables save` command. But doing a `iptables -S | grep calico > iptables-calico` could work. Do you know if there are any good keywords to grep on? Or do you have any other suggestions on how to filter out the rules managed by calico?

> You could also change felix's iptables refresh interval to something smaller, but this can potentially have performance impacts depending on the size of your cluster and the number of policies.

We are looking into all possible ways to keep iptables up-to-date, and this is also something we are discussing. Although a "polling" solution is our least favorite way to solve it. Regarding the performance impact, how much of an impact are we talking about? Is it the increased load on etcd that you are thinking on?

Now when I think about it more - the most optimal solution for us would be if calico wrote down the current iptables "state" into a file everytime it's refreshing the machines state - think of it as a debug-log file. Then I would be able to expose this file outside docker (using -v) and ensure that it's mounted to a place where our firewall department scripts load their own iptables rules from. Then the reload would, essentially, be atomic between our own iptables script and calico's.

**Comment by caseydavenport** [comment]
> Regarding the command above, is there more than policy that I have to take into account if we end up using this approach (like profile, node etc.)

Pulling in @fasaxc who will know for sure, but I think that just replacing policy will be enough. @fasaxc will Felix refresh all iptables upon a policy change, or do the profiles need to be replaced as well? 

> Do you know if there are any good keywords to grep on? Or do you have any other suggestions on how to filter out the rules managed by calico?

I believe the keyword to grep on would be `cali`. [This script](https://github.com/projectcalico/calico/blob/master/hack/remove-calico-policy/remove-calico-policy.sh) might be useful in that it sort of does the opposite of what you're trying to do - it removes all Calico programmed rules.

> Regarding the performance impact, how much of an impact are we talking about?

Afraid I don't have numbers - it's not load on etcd that's impacted here. Increasing the refresh rate will cause Felix to perform more iptables operations, leading to increased CPU usage on the node for example.

**Comment by fasaxc** [comment]
@perandersson We use the prefix `cali-` to all our iptables chains, if you can avoid touching those (and ensure that you leave our rule insertions in the top-level INPUT/OUTPUT/FORWARD/etc chains) then you might be able to avoid needing to prod Calico.

If you do need to trigger a refresh, I suggest restarting calico-felix rather than rewriting the values in the datastore.  If you're using the calico/node container, you could either restart the container or just do `pkill calico-felix` and let calico/node restart it.

**Comment by fasaxc** [comment]
Note: Calico also have host protection capabilities that would let you replace the remote script.

**Comment by perandersson** [comment]
>  This script might be useful in that it sort of does the opposite of what you're trying to do - it removes all Calico programmed rules.

@caseydavenport The script looks quite interesting and it shouldn't be too hard to modify it to collect/store the iptables rules instead of removing them; I'll look into it in more detail in the beginning of the next week. Hopefully If I manage to write something that works then I'll share it if you want it.

> We use the prefix cali- to all our iptables chains, if you can avoid touching those (and ensure that you leave our rule insertions in the top-level INPUT/OUTPUT/FORWARD/etc chains) then you might be able to avoid needing to prod Calico

@fasaxc They are essentially doing a `iptables -F`, so they remove all iptables rules before re-adding their own. I'm trying to get them to change their script slightly, but that takes time, so I'm looking into other potential solutions at the same time

> If you do need to trigger a refresh, I suggest restarting calico-felix rather than rewriting the values in the datastore. If you're using the calico/node container, you could either restart the container or just do pkill calico-felix and let calico/node restart it.

@fasaxc If I restart calico (either by killing the process or destroying the pod managed by Kubernetes), can I assume that the LAN managed by Calico will still be working? Or will traffic be interrupted to that machine during the time Calico is starting up again?

> Note: Calico also have host protection capabilities

@fasaxc When you say "host protection capabilities" - you are talking about replacing our company's firewall script, and letting Calico completely manage the security by itself? For everything controlled by the cluster, then yes this is exactly what I am expecting of Calico. This is actually how it works for us, most of the time. To manage the addresses and ports manually would be a complete nightmare otherwise. Unfortunately I don't have complete control over the machine, which is something that am trying to change at the moment, but it's a slow process for a company as big as the one I'm working for. So preventing them from resetting iptables from time to time is not feasible at the moment.

Question about this though - just for clarification. I can see that a lot of ACCEPT and DROP rules on our machine when using Network Policies together with Kubernetes. Can I assume that this is how Calico isolates pods and namespaces from each other? So when those rules disappear then the namespaces would be open for traffic between closed off sections until those rules have been put back into iptables?

**Comment by fasaxc** [comment]
@perandersson Restarting calico-felix should not drop any packets.  However, flushing iptables may well do! 

> When you say "host protection capabilities" - you are talking about replacing our company's firewall script, and letting Calico completely manage the security by itself?

Yes, Calico supports "host endpoints", which let you secure you "eth0" interface with Calico policy.

> Can I assume that this is how Calico isolates pods and namespaces from each other? 

Yes.  However, flushing iptables may "drop all" or "allow all" during the window, depending on how their script works.
