### ISSUE TITLE
Support installation mechanism using Kubernete's etcd

### ISSUE THREAD

**Issue by tamalsaha** [projectcalico/calico#1301]
We are using Kubeadm to provision cluster. The current installer scripts for Calico creates its own unauthenticated. We would like to use the same etcd used by Kubernetes for Calico. The benfits we see are:

- We have one etcd to deal with. We can backup that, etc.
- If HA setup (coming in Kubeadm 1.9), we don't have to manually manage a separate etcd.
- We provision cluster in DigitalOcean. We need to use authentication with etcd to avoid potential issues. It will get better to just let Kubeadm deal with all that.

My questions are:
- Are there any potential issues with using the same etcd as Kubernetes?
- Can such installer scripts be added to this repo and add to the doc? We are happy to test/contribute in this regard.

**Comment by tamalsaha** [comment]
cc: @sanjid133

**Comment by caseydavenport** [comment]
@tamalsaha I think there are a few things here.

Firstly, Calico certainly supports etcd auth using certificates. See `ETCD_KEY_FILE` and friends [here](https://docs.projectcalico.org/v2.6/reference/node/configuration)

[This manifest](https://docs.projectcalico.org/v2.6/getting-started/kubernetes/installation/hosted/hosted) is more generic, and includes etcd auth as well as the ability to specify your own etcd endpoints.

Now, when deploying on kubeadm, the k8s apiserver's etcd will by default be installed for access on the master only. This means that in the default configuration Calico can't use the etcd created by kubeadm.

However, if you deploy your own etcd cluster and point both Calico and Kubernetes at it, it should work fine. Many users do this. The main thing to be aware of is sizing your cluster appropriately to make sure it meets the performance requirements of your cluster.

Hopefully that helps!

**Comment by ozdanborne** [comment]
@tamalsaha I'm going to close this issue as we have not heard from you for some time. If @caseydavenport 's response does not adequately resolve your issue please reopen.
