### ISSUE TITLE
IPPool page doesn't mention what CIDRs are valid for an IPPool.

### ISSUE THREAD

**Issue by lwr20** [projectcalico/calico#1320]
## Current Behavior
In this doc: https://docs.projectcalico.org/v2.6/reference/calicoctl/resources/ippool
It simply says that you need to specify a valid CIDR for an IPPool.  
But this is false - the IPPool CIDR has restrictions - it needs to be a /25 or bigger.

## Possible Fix
Update the doc to mention that an IPPool CIDR needs to be a /25 or larger.

**Comment by bcreane** [comment]
@lwr20 - back at you :-)
