### ISSUE TITLE
Should be able to gather confd rendered templates from a running calico/node

### ISSUE THREAD

**Issue by robbrockbank** [projectcalico/calico#1328]
[arguably a calicoctl issue since it's related to the `calicoctl node diags`, but I suspect a solution would require a change in calicoctl and in calico/node.]

## Expected Behavior
It would be useful if we had a supported mechanism for gathering the confd-rendered bird templates from a running calico/node.

## Current Behavior
We don't have a way other than exec-ing in to the container.

## Possible Solution
Perhaps have a trigger event that causes each template to be written out to the logs.

## Context
It makes diagnosing anything IPIP/BGP related quite difficult.

## Your Environment
We should be able to do this across most supported orchestrators.

**Comment by caseydavenport** [comment]
I think you can simply do this with a `docker cp` command: https://docs.docker.com/engine/reference/commandline/cp/
