### ISSUE TITLE
IPIP tunnels don't forward traffic until pinged

### ISSUE THREAD

**Issue by fasaxc** [projectcalico/calico#1357]
Moving this issue from #1173, which mixes two problems:

Originally reported by @r7vme:

we are seeing similar behaviour. After nodes reinstall/reboot IPIP tunnels do not forward traffic. All routes are in place and network between VMs is fine (i can ssh between VMs). In tcpdump i see IPIP traffic from node, but don't see anything on destination node.

What is most weird that as workaround, *i need to ping tunl0 IP addresses. From node A ping node B, from node B ping node A*. After i immediately see ICMP traffic.

I'm seeing this constantly on many enviroments and it not related to AWS, we also use IPIP in out KVM environments and see same behavior there after node reboot/reinstall.

I found that Calico allows only IPIP traffic from known hosts, but this is not the case. I see no matches and see all my hosts in `ipset list`
```
r7vme@ip-10-0-5-117 ~ $ sudo iptables -vL | grep ipencap
    0     0 DROP       ipencap--  any    any     anywhere             anywhere             /* cali:p8Wwvr6qydjU36AQ */ /* Drop IPIP packets from non-Calico hosts */ ! match-set cali4-all-hosts src
```

Any suggestions?

### Details:
Calico 2.5.1 (or 2.3.0)
Kubernetes 1.7.5 (or 1.6.4)
CoreOS 1465.8.0

```
- apiVersion: v1
  kind: ipPool
  metadata:
    cidr: 192.168.0.0/16
  spec:
    ipip:
      enabled: true
      mode: always
    nat-outgoing: true
```

### Demonstration
```
r7vme@ip-10-0-5-103 ~ $ ping -c 1 192.168.16.192
PING 192.168.16.192 (192.168.16.192) 56(84) bytes of data.

--- 192.168.16.192 ping statistics ---
1 packets transmitted, 0 received, 100% packet loss, time 0ms

r7vme@ip-10-0-5-103 ~ $ ssh 10.0.5.155 "ping -c 1 192.168.134.64"
PING 192.168.134.64 (192.168.134.64) 56(84) bytes of data.
64 bytes from 192.168.134.64: icmp_seq=1 ttl=64 time=1.13 ms

--- 192.168.134.64 ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 1.135/1.135/1.135/0.000 ms
r7vme@ip-10-0-5-103 ~ $ ping -c 1 192.168.16.192
PING 192.168.16.192 (192.168.16.192) 56(84) bytes of data.
64 bytes from 192.168.16.192: icmp_seq=1 ttl=64 time=1.17 ms

--- 192.168.16.192 ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 1.173/1.173/1.173/0.000 ms

```

**Comment by fasaxc** [comment]
We haven't got to the bottom of this yet but Giantswarm have published a workaround: https://github.com/giantswarm/calico-ipip-pinger

**Comment by fasaxc** [comment]
OK, got to the bottom of one cause of this issue with a user on slack.  In his case, he had enabled host protection but he had not added a rule to allow incoming IPIP traffic.  This meant that no IPIP traffic would be allowed until an outgoing ping, for example, triggered a conntrack entry, which in turn allowed the return traffic.

For current versions of calico, the fix is to add policy to allow IPIP inbound on the relevant interfaces.

**Comment by fasaxc** [comment]
I think this is the right fix: https://github.com/projectcalico/felix/pull/1558

**Comment by namsral** [comment]
I published [another workaround][0], works by sending single ICMP packets to initialising pods.

[0]: https://fuga.cloud/academy/articles/how-to-stabilise-calico-ip-in-ip-tunnels-in-virtual-environments/ "How to stabilise Calico's IP-in-IP tunnels in virtual environments"

**Comment by r7vme** [comment]
@fasaxc thanks for fix. Will this be cherry-picked to 2.6 ?

**Comment by fasaxc** [comment]
@r7vme Yes, I think so.

**Comment by r7vme** [comment]
Unfortunately we are experiencing this bug with Calico 3.0.2. I saw this at least 3 times on two different clusters. As usual both-ends pinging fixes the problem immediately. Problem happens after nodes were rolled out with update.

I've checked iptables rules and ipset `cali4-all-hosts`, which contains all new hosts.
```
ip-10-0-5-123 ~ # iptables -S | grep ipencap
-A cali-INPUT -p ipencap -m comment --comment "cali:kLJdl8-9MpSKcclh" -m comment --comment "Allow IPIP packets from Calico hosts" -m set --match-set cali4-all-hosts src -m addrtype --dst-type LOCAL -j ACCEPT
-A cali-INPUT -p ipencap -m comment --comment "cali:JhfQUFFJ2v0jbipF" -m comment --comment "Drop IPIP packets from non-Calico hosts" -j DROP
-A cali-OUTPUT -p ipencap -m comment --comment "cali:z0oSsuDED75MEj0R" -m comment --comment "Allow IPIP packets to other Calico hosts" -m set --match-set cali4-all-hosts dst -m addrtype --src-type LOCAL -j ACCEPT
```

**Comment by fasaxc** [comment]
@r7vme Please can you share more details of your configuration?

- Are you using host policy?
- Do you have any non-Calico iptables rules present?
- Are you using any non-standard configuration, such as iptables append mode?
- Please can you share a full `iptables-save` dump along with the routing table from an affected node?

**Comment by r7vme** [comment]
@fasaxc 

> Are you using host policy?

No.

> Do you have any non-Calico iptables rules present?

No. Only calico and kube-proxy rules as far as i see.

> Are you using any non-standard configuration, such as iptables append mode?

Noop.

> Please can you share a full iptables-save dump along with the routing table from an affected node?

`iptables-save` and `ip route` from one worker node

https://gist.github.com/r7vme/63cb0d49a10bd1f59625a3839358334b

**Comment by fasaxc** [comment]
@r7vme all looks good to me, what about `ip addr`, is there anything unusual about your local IPs (our iptables rule for IPIP matches on source IP type == LOCAL).

Failing that, the next step would be to try to figure out what rules are dropping the traffic by looking at counters.  Are the counters on the IPIP rules (the ACCEPT or the DROP) going up at all (while it's in the bad state, before you do the ping)?  `iptables-save -c` shows the counters.

**Comment by r7vme** [comment]
Looks like suggestion from slack was right - use protocol 4 and not 94 in security groups.

Issue appeared in two clusters that still had protocol 94. Others looks fine, which have protocol 4.

I think issue can be closed, thanks for your support.

**Comment by 2rs2ts** [comment]
The suggestion to use protocol 4, not 94, does not work for us. We also tried to allow both. We are still on Calico 2.6.5. Do we have to upgrade?

**Comment by 2rs2ts** [comment]
^ never mind the above, we got it working. The fix is available in our version of Calico, we just had other issues.
