### ISSUE TITLE
Typos in master kubeadm Hosted Install page

### ISSUE THREAD

**Issue by neiljerram** [projectcalico/calico#1358]
At https://docs.projectcalico.org/master/getting-started/kubernetes/installation/hosted/kubeadm/, the documentation includes:

"To install this Calico and a single node etcd on a run the following command:"

which I guess should be "To install Calico and a single node etcd on a ? run the following command:"

**Comment by ozdanborne** [comment]
Closing as duplicate of https://github.com/projectcalico/calico/issues/1442
