### ISSUE TITLE
inspect result of getIPIPEnabledPoolCIDRs()

### ISSUE THREAD

**Issue by joewilliams** [projectcalico/calico#1369]
I am observing some unexpected behavior during IP allocation and would like to better understand what [`allocate_ipip_addr`](https://github.com/projectcalico/calico/blob/master/calico_node/allocateipip/allocate_ipip_addr.go) is doing. Specifically, the CIDRs returned by `getIPIPEnabledPoolCIDRs`. Can you recommend a way for me to do that?

**Comment by caseydavenport** [comment]
@joewilliams is there a particular bit of code you'd like help understanding?

I recommend joining `slack.projectcalico.org` and starting a discussion in the #calico-dev channel.

At a high level, `allocate-ipip-addr` finds all IP Pools that have IPIP enabled, and reserves an IP address from one of them for assignment to the tunl0 device.

**Comment by joewilliams** [comment]
Thanks @caseydavenport, this was a part of our investigation that resulted in https://github.com/projectcalico/libcalico-go/issues/689. The [behavior](https://github.com/projectcalico/calico/blob/master/calico_node/allocateipip/allocate_ipip_addr.go#L228) of `ipPool.Spec.Disabled` seems different in this file compared to [ipam.go](https://github.com/projectcalico/libcalico-go/blob/5cabf71a9999834727d83036e986836084e0a13a/lib/client/ipam.go#L158-L287).
