### ISSUE TITLE
Update clusterIP for kubeadm etcd in hosted manifests

### ISSUE THREAD

**Issue by caseydavenport** [projectcalico/calico#137]
See here https://github.com/kubernetes/kubernetes.github.io/pull/1608/files#diff-d815373181beaa60de5c28956e4ba3fcR120

**Comment by djosborne** [comment]
@caseydavenport I'm not sure I fully grasp this issue, so I'm going to assign this to you to fix or elaborate.

Seems like the service cidr address may need to be updated in our own kubeadm guides? Just master? or past ones too?

**Comment by caseydavenport** [comment]
This shouldn't be in v2.0.0-beta though since it needs to happen when a new kubeadm is cut.

**Comment by caseydavenport** [comment]
@gunjan5 similar sort of thing to https://github.com/tigera/canal/issues/16
