### ISSUE TITLE
Can the `CALICO_IPV4POOL_CIDR` be changed to another CIDR instead of `192.168.0.0/16`?

### ISSUE THREAD

**Issue by KeithTt** [projectcalico/calico#1378]
as the title...for example: `10.xxx.xxx.xxx/16`

**Comment by caseydavenport** [comment]
Yep! 

Please see [the documentation](https://docs.projectcalico.org/v2.6/reference/node/configuration): (specifically, `CALICO_IPV4POOL_CIDR`)

**Comment by KeithTt** [comment]
@caseydavenport thanks a lot!!

**Comment by tmjd** [comment]
Just a note on changing that. If you have already brought up your cluster and the pool has been created then updating the env var and restarting calico-node will not change the IP Pool. The setting is only used when creating a default pool and that is only done when there are no existing pools.

**Comment by KeithTt** [comment]
@tmjd I found that, I change this value but it still use the CIDR before........

So how do make this value take effect if I want to  use the new CIDR?

**Comment by KeithTt** [comment]
I found the config file in the pod here:

```
# kubectl exec -it calico-node-hrm5r -n kube-system -- sh
/etc/calico/confd/config/bird_aggr.cfg
```

**Comment by tmjd** [comment]
If you need to modify Calico data you should use the [calicoctl](https://docs.projectcalico.org/v2.6/reference/calicoctl/) command.  You can use the calicoctl command to create the IP Pool you want to use and then delete the previous one.

It is not safe to edit the /var/lib/etcd data on disk. I would suggest not editing the Calico data directly in etcd, if feel you need to edit etcd data directly I would suggest using the etcdctl command.

When bringing up a new cluster you can set the CALICO_IPV4POOL_CIDR variable so that the default created pool is what you want.  (If the cluster is being rebuilt on the same hosts you will need to clear out the etcd data as it is written to disk.)

**Comment by KeithTt** [comment]
It is strange that I have deleted all the data include `/var/lib/etcd` before rebuilding the k8s cluster, I use a independent etcd cluster not in k8s .

**Comment by tmjd** [comment]
To edit the value if you rebuild the cluster (so the correct value is used when you deploy calico):
1. Download the manifest (grab the file used in the command `kubectl apply -f https://docs.projectcalico.org/v2.6/getting-started/kubernetes/installation/hosted/kubeadm/1.6/calico.yaml`, that command simply downloads that file and then applies it)
2. Edit the variable.
3. Apply the edited manifest with `kubectl apply -f calico.yaml`

The above is assuming you deployed Calico with a `kubectl apply -f <manifest>`, if you used some installer then you would need to figure out how to change that value.

Also note that the IP Pool Calico is configured to use needs to match up with the `--cluster-cidr` specified to the kube-controller-manager and kube-proxy and must not overlap with the Service IP or the network that the hosts are using.

**Comment by KeithTt** [comment]
So, you mean edit the yaml file and `kubectl apply -f calico.yaml`, that is what I did, but do not work, and I have deleted all the data before rebuilding.

And I have checked this config in `manifests/kube-controller-manager.yaml` and `kubectl edit cm kubeadm-config -n kube-system`, they are both correct.

**Comment by tmjd** [comment]
The calico-etcd pod has `/var/etcd` mounted into the container so you need to clean that directory too if you are not completely rebuilding your hosts.

**Comment by KeithTt** [comment]
@tmjd find it, thanks a lot!!! 💯
