### ISSUE TITLE
Allow to filter external traffic with kubernetes datastore

### ISSUE THREAD

**Issue by 0xBF** [projectcalico/calico#1379]
Installation:
 - baremetal kubernetes cluster (1.8)
 - calico with kubernetes datastore (2.6)
 - service with two externalIPs (EIP1, EIP2)
 - EIP1 routed to node1
 - EIP2 routed to node2

I want to limit access to this service for only one external (for cluster) IP. 

When pod and externalIP are on same node (client -> EIP1 -> pod-on-node1), all is ok.
When pod and externalIP are on different nodes (client -> EIP1 -> pod-on-node2), policy doesn't work, because kube-proxy on node1 masquerade traffic and node2 already see node1 IP, not client IP.

I think it should be enough to create global network policy with preDNAT = true, but they applied to hostendpoints, which are not available with kubernetes datastore.

some ideas:
- create CRD for configure host endpoints.
- audo add host endpoint for each externalIPs and nodePort on each node.

**Comment by tmjd** [comment]
The plan is to add feature parity to match etcd when using the kubernetes datastore. There is #355 to track that.

**Comment by caseydavenport** [comment]
@0xBF thanks for raising this - I'm going to close for now since I think this is covered by #355 (add host endpoint support to the kubernetes api datastore)

Let me know if that's not correct and I'll re-open.
