### ISSUE TITLE
IPnIP is routing local node/destination traffic through tunnel interface

### ISSUE THREAD

**Issue by jckasper** [projectcalico/calico#1387]
Created the following IP pool resource:

```
- apiVersion: v1
  kind: ipPool
  metadata:
    cidr: 10.91.152.128/26
  spec:
    ipip:
      enabled: true
      mode: cross-subnet
    nat-outgoing: false
```

When `ipip enabled=false`, the route for this CIDR is correct: 

```
/etc/calico/confd/conf.d # ip route 
default via  ----  dev eth1 onlink 
10.0.0.0/8 via 10.171.236.129 dev eth0 
10.91.152.128/26 via 172.30.6.80 dev cali8a4e22773c7 proto bird      <--- Route
10.171.236.128/25 dev eth0 proto kernel scope link src 10.171.236.204 
172.17.0.0/16 dev docker0 proto kernel scope link src 172.17.0.1 
172.30.6.65 dev cali52836d57283 scope link 
172.30.6.66 dev cali80335bff1cc scope link 
172.30.6.78 dev cali00bc9c75a26 scope link 
172.30.6.80 dev cali8a4e22773c7 scope link                    <--- Local pod
172.30.63.192/26 via 10.171.42.46 dev tunl0 proto bird onlink 
172.30.175.128/26 via 10.171.42.17 dev tunl0 proto bird onlink 
172.30.218.192/26 via 10.171.42.29 dev tunl0 proto bird onlink 
172.30.244.0/26 via 10.171.236.201 dev eth0 proto bird 
```

When IPIP is enabled, the route is changed from:
```
10.91.152.128/26 via 172.30.6.80 dev cali8a4e22773c7 proto bird
```
... to ...
```
10.91.152.128/26 via 172.30.6.80 dev tunl0 proto bird
```

## Expected Behavior
If the destination for the route is a local pod on this node, the traffic should be sent directly to that pod via the cali* device instead of the tunl0 device. 

## Current Behavior
When IPIP is currently enabled (with cross-subnet mode), the tunl0 is always used if `bgp_next_hop` is not located on the same subnet as the endpoint.   This logic does not take into account the above scenario in which the `bgp_next_hop` is a pod IP that is located on this node.

## Possible Solution
I think the `/etc/calico/confd/templates/bird_ipam.cfg.template`  could be updated to generate an additional "else if" clause after the current:
```
    if ( bgp_next_hop ~ {{$network}} ) then
      krt_tunnel = "";  
```
.... to take into account those cases in which `bgp_next_hop` could be a local pod on this node.

## Steps to Reproduce (for bugs)
No easy way (outside of current environment) to recreate this issue.

## Context
I am trying to run strongswan IPSec VPN in a Kubernetes pod to provide site-to-site VPN access to the cluster.   Inside of the VPN pod, I am adding the IP Pool resource (shown above) for the remote subnet (that can only be access via this pod), a BGP peer resource, and also running BIRD to advertise the VPN route.   Everything works fine as long as all of the K8s worker nodes are on the same subnet.   When the cluster has K8s workers that span different subnets, then IPIP is needed to get traffic back to the correct worker node (where the VPN pod is running).   Unfortunately, when IPIP is enabled, the route into the VPN pod is set to use `tunl0`  which does not work.   The IP encapsulated packets arrive in the VPN pod, but the VPN pod does not know how to handle them.  Suggestions on how to handle IPIP packet is a pod ? 

## Your Environment
* Calico version:  2.6
* Orchestrator version: Kubernetes 1.8.2
* Operating System and version:  Ubuntu 16.04 
* Link to your project (optional):   https://console.bluemix.net/docs/containers/container_index.html

**Comment by fasaxc** [comment]
@jckasper Am I right in thinking you're trying to peer a calico host with one of its workloads over BGP?  That is not expected to work.  Apart from any other issue, Felix will remove the route that bird adds.

**Comment by jckasper** [comment]
@fasaxc The routes for the remote VPN network are working fine today as long as the k8s worker nodes are on the same  subnet.  Felix appears to be fine with the new routes.

**Comment by fasaxc** [comment]
As discussed on slack, we found that Felix was deleting the routes but bird was re-adding them.

**Comment by jckasper** [comment]
Found the following Felix configuration setting:  

> RouteRefreshInterval (FELIX_ROUTEREFRESHINTERVAL)
> Period, in seconds, at which Felix re-checks the routes in the dataplane to ensure that no other process has accidentally broken Calico’s rules. Set to 0 to disable route refresh. [Default: 90]
 
I could use this property to disable Felix removing the routes, but don't think that would necessarily be a good thing.

**Comment by jckasper** [comment]
Since Felix is deleting the routes that are being added this bug report will be closed. 
Looking into another way to support this use case.
