### ISSUE TITLE
quay.io calicoctl image with tag v1.6.1 overwritten with v2.0.0-beta

### ISSUE THREAD

**Issue by struz** [projectcalico/calico#1391]
## Expected Behavior

```
[~]$ docker run quay.io/calico/ctl:v1.6.1 --version
calicoctl version v1.6.1, build xxx
```

## Current Behavior

```
[~]$ docker run quay.io/calico/ctl:v1.6.1 --version
calicoctl version v2.0.0-beta1, build 4cf4ff5c
```

## Context

It's not the right version and this breaks assumptions and functionality for people expecting the old version.

**Comment by gunjan5** [comment]
@struz thanks for pointing it out. We've fixed it
