### ISSUE TITLE
Update from 2.6.2 to 3.0.0-alpha1 with kubernetes datastore broke outgoing nat

### ISSUE THREAD

**Issue by 0xBF** [projectcalico/calico#1402]
I try update calico 2.6.2 to 3.0.0-alpha1 and outgoing nat stop work.

kubernetes version: 1.7
calico datastore: kubernetes
calico in policy-only mode

It was fixed by updating ippool with calicoctl.

Maybe, there is a result of renaming nat-outgoing parameter to natOutgoing.

**Comment by fasaxc** [comment]
This is expected; there is no upgrade support from v2 to v3.0.0-alpha (or beta).  Our GA release will include upgrade support.
