### ISSUE TITLE
Calico 2.6 Vagrant install uses k8s 1.7.5, but advanced policy demo tutorial assumes 1.8.x

### ISSUE THREAD

**Issue by lwr20** [projectcalico/calico#1417]
## Expected vs Current Behavior
I installed using the Vagrant/CoreOS install guide in the quickstart section.  
I then attempted to follow the advanced policy demo which uses k8s egress policy.  This fails at step 4 - egress traffic is NOT restricted when tutorial says is should be.

## Possible Solution
`kubectl version` shows that the Vagrant setup has installed kubernetes 1.7.5 - which does NOT support k8s egress policy (you need v1.8.x or above).

Perhaps the Vagrant install guide could be updated to install 1.8.x?

## Steps to Reproduce (for bugs)
1.  Install using https://docs.projectcalico.org/v2.6/getting-started/kubernetes/installation/vagrant/
2.  Follow guide from here: https://docs.projectcalico.org/v2.6/getting-started/kubernetes/tutorials/advanced-policy

**Comment by ozdanborne** [comment]
Looks like this was fixed by #1464 
Thanks @tmjd :D
