### ISSUE TITLE
Broken links: k8s v1.6 docs have moved

### ISSUE THREAD

**Issue by fasaxc** [projectcalico/calico#1418]
htmlproofer hit this:

```
- /_site/v2.5/getting-started/kubernetes/upgrade.html
  *  External link http://kubernetes.io/docs/user-guide/kubectl/v1.6/#cordon failed: 404 No error
  *  External link http://kubernetes.io/docs/user-guide/kubectl/v1.6/#uncordon failed: 404 No error
htmlproofer 3.3.1 | Error:  HTML-Proofer found 2 failures!
```

Looks like the v1.6 docs have been archived to https://v1-6.docs.kubernetes.io/

## Expected Behavior

No broken links.

## Current Behavior

htmlproofer fail.

## Possible Solution

Link to new location?

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Calico version:
* Orchestrator version (e.g. kubernetes, mesos, rkt):
* Operating System and version:
* Link to your project (optional):

**Comment by emanic** [comment]
Fixed
