### ISSUE TITLE
Docs workloadendpoint example doesn't work

### ISSUE THREAD

**Issue by lwr20** [projectcalico/calico#1459]
## Expected Behavior
I'd expect examples given in the docs to 'just-work': 
https://docs.projectcalico.org/v2.6/reference/calicoctl/resources/workloadendpoint

## Current Behavior
```
$ cat test.yaml
apiVersion: v1
kind: workloadEndpoint
metadata:
  name: eth0
  workload: default.frontend-5gs43
  orchestrator: k8s
  node: rack1-host1
  labels:
    app: frontend
    calico/k8s_ns: default
spec:
  interfaceName: cali0ef24ba
  mac: ca:fe:1d:52:bb:e9
  ipNetworks:
  - 192.168.0.0/16
  profiles:
  - profile1
$ ETCD_ENDPOINTS=http://172.18.18.101:2379 calicoctl apply -f test.yaml
Failed to execute command: error with field IPNetworks = '[192.168.0.0/16]' (IP network contains multiple addresses)
```

## Possible Solution
Either the docs are wrong or the validation logic is wrong.  Not sure which.

## Steps to Reproduce (for bugs)
See above.

## Your Environment
Used CoreOS k8s Vagrant demo to install. https://docs.projectcalico.org/v2.6/getting-started/kubernetes/installation/vagrant/

```
$ ETCD_ENDPOINTS=http://172.18.18.101:2379 calicoctl version
Client Version:    v1.6.2
Build date:        2017-11-22T22:41:27+0000
Git commit:        855392a8
Cluster Version:   v2.6.3
Cluster Type:      k8s,bgp

```

**Comment by caseydavenport** [comment]
Yeah, it needs to be a `/32`

**Comment by caseydavenport** [comment]
@lwr20 can you fix the docs?

**Comment by caseydavenport** [comment]
Seems to be fixed now.
