### ISSUE TITLE
Master docs are manually pinned most recent CNI plugin release

### ISSUE THREAD

**Issue by ozdanborne** [projectcalico/calico#147]
projectcalico/cni-plugin doesn't produce "latest" builds, so master docs simply point to the last calico-cni release. This means that the release scripts can't grep and replace calico-cni versioning easily.

I'll propose two fixes to this situation:

1. Generate links to master builds of  calico-cni artifacts for our docs to reference. Then release scripts can replace those precise, static links with the latest release at release time.

2. Update docs to explain how to manually pull the artifacts out of `calico/cni:latest`, much like our hosted install does

**Comment by djosborne** [comment]
When producing a Core Calico release, search for and fix links that appear as: `https://github.com/projectcalico/calico-cni/releases/download/`

**Comment by djosborne** [comment]
@caseydavenport Thoughts on this? Another alternative to hosting master builds of calico-cni artifacts would be to update our docs to show how to pull the artifacts out of `calico/cni:latest`. Can

**Comment by caseydavenport** [comment]
We could switch to using the calico/cni container to install the binaries everywhere?

**Comment by caseydavenport** [comment]
Let's add a projectcalico.org/builds target for the CNI plugins like we do for calicoctl.
