### ISSUE TITLE
calico/node IP detection deadlocked

### ISSUE THREAD

**Issue by fasaxc** [projectcalico/calico#1471]
After restarting 3 nodes in a scale test in GCE, they came back up using the same IPs but the IPs were shuffled amongst the nodes.  `calico/node` then refused to start on each node

- node-1 can’t start because node-2 previously used its IP address
- node-2 can’t start because node-3 previously used its IP address
- node-3 can’t start because node-1 previously used its IP address

The terraform scripts I'm using use the hostname of the node as the nodename rather than the IP address

## Expected Behavior

All three nodes should start up, possible after some retries.

## Current Behavior

Deadlock, they get stuck in that state.

## Possible Solution

Perhaps we could remove our own node IP (if it doesn't match any IP on the node) before doing this check, then each node would run once, remove the state, and then succeed on the retry.

## Workaround

Set env var DISABLE_NODE_IP_CHECK="true" in the calico/node manifest.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Calico version d09223634bac97357eee490c7981e10f27ff8cee
* Orchestrator version (e.g. kubernetes, mesos, rkt): k8s
* Operating System and version:
* Link to your project (optional):

**Comment by fasaxc** [comment]
Initially, I saw this error and hit the bug in #1470 :
```
2017-12-06 15:27:31.258 [INFO][9] startup.go 176: Early log level set to info
2017-12-06 15:27:31.258 [INFO][9] startup.go 187: NODENAME environment not specified - check HOSTNAME
2017-12-06 15:27:31.260 [INFO][9] startup.go 96: Skipping datastore connection test
2017-12-06 15:27:31.262 [WARNING][9] startup.go 402: Unable to confirm IPv4 address 10.240.0.128 is assigned to this host
```
So I set IP=autodetect in the manifest but then hit this problem.

**Comment by fasaxc** [comment]
@caseydavenport what's your thinking on making this a P3?  Seemed like a pretty nasty bug to me

**Comment by caseydavenport** [comment]
Yeah, that's just a labeling bug on my part.

**Comment by fasaxc** [comment]
Suggesting for v3.0.1

**Comment by caseydavenport** [comment]
I think the node controller can't deal with this case, because the nodes themselves aren't being deleted from k8s, so it doesn't know anything has changed.

We'll need to handle this another way.

I think the suggestion in the description has promise.

if `IP=autodetect` and an IP conflict is hit, the restarting node could unset its own node's IP address and restart. This should eventually resolve itself, and should only be hit when multiple nodes are restarted at the same time.

If there is _actually_ a conflict (two instances have the same IP) then I think it's OK to do this as well, since it's clearly an invalid scenario.

**Comment by fasaxc** [comment]
Hmm, just thought of another case: if you take a node offline but don't delete it, then a new node could start up with its old IP legitimately.  Should we have the node controller remove IPs from nodes that haven't been seen for a while or something like that?

**Comment by caseydavenport** [comment]
hm, I think that case is a bit more obscure. In a public cloud case, typically you'd have a cloud-provider enabled which would remove that node from k8s automatically when it was taken offline, I think.

In some other scenarios, I suppose it is possible you should shutdown a node and leave it in k8s, but that feels like an odd scenario to be in and I'd expect people would just remove the node from k8s, thus triggering the node controller.

I'll try to think some more... but I do worry a little bit about adding that sort of guessing logic about whether or not a node is still in the cluster.
