### ISSUE TITLE
Cannot start Kube-controller container of Calico v2.6.3  --- cannot find the kube config file

### ISSUE THREAD

**Issue by samding01** [projectcalico/calico#1489]
Kube-controller (v1.0.1) of Calico v2.6.3 does not work with Kube v1.6x/1.7 on both amd64 and s390x  
## Expected Behavior

On Calico v2.3 it was tested by following https://docs.projectcalico.org/v2.6/getting-started/kubernetes/installation/integration#configuring-kubernetes and worked fine.
It seems that the backward comparability was broken.  
## Current Behavior

The container of kube-controller cannot be started, the container logs show:
  
     2017-12-08 19:50:27.051 [INFO][34] main.go 66: Loaded configuration from environment 
     config=&config.Config{LogLevel:"info", ReconcilerPeriod:"5m", 
     EnabledControllers:"policy,profile,workloadendpoint,node", WorkloadEndpointWorkers:1, 
     ProfileWorkers:1, PolicyWorkers:1, NodeWorkers:1, Kubeconfig:""}
     2017-12-08 19:50:27.052 [INFO][34] client.go 202: Loading config from environment
     2017-12-08 19:50:27.054 [FATAL][34] main.go 78: Failed to start error=failed to build kubernetes 
       client config: invalid configuration: no configuration has been provided

It seems that the `kube-controller` cannot find the kube config file.     
## Possible Solution

Please provide a workable `yaml` file in the instruction document.

## Steps to Reproduce (for bugs)

Following  the instruction https://docs.projectcalico.org/v2.6/getting-started/kubernetes/installation/hosted/hosted
1. download `calico.yam` file, update the `etcd endpoints`, then add
       
             - name: KUBECONFIG
              value: /var/run/kubernetes/kubeconfig
            - name: ENABLED_CONTROLLERS
              value: policy,profile,workloadendpoint,node
          volumeMounts:
            # Mount in the etcd TLS secrets.
            - mountPath: /var/run/kubernetes/
              name: test-volume
       volumes:
        # Used by calico/node.
        - name: test-volume
          hostPath:
            path: /var/run/kubernetes/

into the `calico-policy-controller` part.
2. `cp  kubeconfig  /var/run/kubernetes/`
3.  Then `kubectl apply -f calico.yaml`

You will see the container of `kube-controller` exits and logs show the error as the above.

By the way, as the developer suggested to define env variables like:

    export KUBECONFIG=/var/run/kubernetes/kubeconfig
    export ETCD_ENDPOINTS=http://10.0.0.1:2379,http://10.0.0.2:2379

does not work.
## Your Environment

* Calico version v2.6.3, k8s-policy (v1.0.1)
* Orchestrator version (e.g. kubernetes, mesos, rkt):  Kubenetes 1.6.13 (1.17.x) 
* Operating System and version:  amd64 Ubuntu 16:04
* Link to your project (optional):

**Comment by caseydavenport** [comment]
@samding01 why do you need to mount in a kubeconfig file? I'd expect the correct serviceaccount token to be provided by the system for API access, unless you've not enabled the generation of api tokens?

**Comment by samding01** [comment]
@caseydavenport  Originally I followed the instruction without the part in the (1) (mount mounting the kubeconfig file), it did not work,  then the developer suggested to mount the folder. 
What is the workable `calico.yaml`?

**Comment by caseydavenport** [comment]
@samding01 if you're installing this "self-hosted" on Kubernetes as a Pod, I don't think you need to set KUBECONFIG, nor do you need the volume mount.

It should "just work".

**Comment by gzyeah** [comment]
Follow the  [Integration Guide](https://docs.projectcalico.org/v2.6/getting-started/kubernetes/installation/integration) and face same problem with start up calico-kube-controllers..
Any ideas?

**Comment by gzyeah** [comment]
Try @samding01 's workaround with mounting the kubeconfig file and work. So the problem is that calico-kube-controllers wants to read this file and the Guide does not tel this details..

**Comment by samding01** [comment]
There are two `name: calico-kube-controllers` parts, it should put the above (1) to the 1st part, 
which  made me confused.

**Comment by tmjd** [comment]
@samding01 is this still a problem? From your last statement it sounds like you might have figured out the issue.

**Comment by samding01** [comment]
you can close this
