### ISSUE TITLE
dnsmasq writes spurious warnings to syslog when a host has VMs on multiple Neutron networks

### ISSUE THREAD

**Issue by neiljerram** [projectcalico/calico#15]
Calico's version of the Neutron DHCP agent launches Dnsmasq in the default network namespace, and tells it to listen on all TAP interfaces.  We believe there is one instance of Dnsmasq per OpenStack network.

Therefore, if the VMs on a compute host are attached to more than one network, that will start a corresponding number of Dnsmasq instances, which will race with each other to listen on each new TAP interface as it appears.  Possibly the instance that succeeds in binding will not be the one for the network that the associated VM actually wants, and in that case DHCP IP distribution will fail for that VM.

**Comment by alexaltair** [comment]
Neil and I have now seen this happen with a VM on two IPv6 networks. That is, we've seen two dnsmasq processes, one of which was logging errors into syslog about tap interfaces that weren't on its network. 

That said, we don't yet have sufficient evidence to conclude that this was causing our problems.

**Comment by fasaxc** [comment]
Something we still need to dig into?

**Comment by matthewdupre** [comment]
We need to look at this again - at least for documentation, even if we don't actually fix it.  Our docs tell people to create 3 networks (http://docs.projectcalico.org/en/latest/opens-external-conn.html).

**Comment by fasaxc** [comment]
Had a dig into the dnsmasq docs and FAQ.  Sounds like there's no easy fix here.  If you want to run multiple dnsmasq processes, it seems they're not supposed to be binding to the same interfaces.

I'm not sure we can fix this in the docs.  We could recommend setting up IPv6 and IPv4 on a single network but hat wouldn't solve the problem of wanting public and private IPv4 addresses.

Options I can see:

* use a bridge device (but only for DHCP)
* run dnsmasq in a network namespace and use iptables to route packets into the right namespace(s)

I suspect there's a lot of plumbing to get the right information (name of bridge device or list of namespaces and IP ranges that they serve) to felix.

Putting dnsmasq in a namespace has the advantage that the kernel-created connected route that we currently suppress would disappear inside the namespace.

CC @neiljerram @matthewdupre

**Comment by Lukasa** [comment]
I'm strongly +1 on the namespace approach. Doing anything with bridges is going to be a *massive* chore.

**Comment by neiljerram** [comment]
Please let's be sure about whether there's actually any problem here, before we start proposing designs for fixing it.

I believe we have been running an FV test for ages that involves two networks, and I also believe that that test has beeen reliably passing.

If that's correct, I don't understand how, but perhaps Linux and/or dnsmasq are being cleverer than we're allowing for. It would surely be interesting to understand that properly, but there may not be any fix needed, other than understanding. 

Re private IPv4 addresses: those certainly do need namespaces, as described in our 464XLAT doc; but that's a different matter from just supporting multiple (shared) Neutron networks, e.g. so as to allow both externally routable and RFC 1918 addresses for VMs.

**Comment by matthewdupre** [comment]
I can confirm that when you have 2 networks, you do see errors in syslog `2015-06-30T17:23:45.081111+00:00 calico18 dnsmasq[4685]: failed to create listening socket for fe80::261:feff:feed:cafe%tap8b23e0e2-1b: Address already in use`

But, the VMs all DHCP successfully (I tried 8, across 2 networks over 2 hosts), receiving both the correct IP address and the correct default gateway.  That should have less than 1% chance of working if this issue is genuine, so I'm taking this as pretty solid evidence that this is not a functional bug.

I also checked a single VM with two NICs, each on different networks - this operates as expected.

For the sake of curiosity, I tried killing one of the dnsmasqs and then booting VMs - NICs on that network didn't start, so both are definitely doing something.

~~

The logging issue is real, but less important.

**Comment by Lukasa** [comment]
So, *why* are they successfully DHCPing for both networks?

**Comment by matthewdupre** [comment]
@lukasa - Is there something specific you're interested in checking while I have the system up?

**Comment by Lukasa** [comment]
Yeah, lots:

- Are two dnsmasq processes running?
- Are two Neutron DHCP agents running?
    - If so, are they duplicating each other's information about DHCP leases?
        - If not, which dnsmasq is responding to each DHCP request? Random? Always the same?
            - If DHCP is magically going to the "right" dnsmasq, how is that happening? (This might be too big for you to do now).

**Comment by matthewdupre** [comment]
OK, I've added numbers in the natural fashion:

1.  Yes, and it doesn't work if one of them isn't.
2.  No.

**Comment by Lukasa** [comment]
Interesting. What version of OpenStack are you using?

**Comment by matthewdupre** [comment]
Juno.

Here's a little log sample:
::
    2015-06-30T18:03:10.541755+00:00 calico19 dnsmasq-dhcp[32027]: DHCPDISCOVER(ns-c17bdac4-5c) fa:16:3e:29:3e:99 no address available
    2015-06-30T18:03:10.541771+00:00 calico19 dnsmasq-dhcp[32325]: DHCPDISCOVER(ns-88758acf-f5) fa:16:3e:29:3e:99
    2015-06-30T18:03:10.541779+00:00 calico19 dnsmasq-dhcp[32325]: DHCPOFFER(ns-88758acf-f5) 10.233.1.251 fa:16:3e:29:3e:99
    2015-06-30T18:03:10.542457+00:00 calico19 dnsmasq-dhcp[32325]: DHCPREQUEST(ns-88758acf-f5) 10.233.1.251 fa:16:3e:29:3e:99
    2015-06-30T18:03:10.542478+00:00 calico19 dnsmasq-dhcp[32325]: DHCPACK(ns-88758acf-f5) 10.233.1.251 fa:16:3e:29:3e:99 host-10-233-1-251

Looks to me like the discover is going to them both.

**Comment by matthewdupre** [comment]
If I had to jump to a conclusion, I'd say we don't need to listen on the taps at all, and the ns interfaces are enough on their own.

**Comment by Lukasa** [comment]
Right.  I do think we should check this on Icehouse, because that's where we originally spotted the bug.

**Comment by matthewdupre** [comment]
Perhaps, although I'm not clear on whether we've ever really seen it (when something else wasn't broken) - the report above suggests the system might have been broken anyway.

**Comment by matthewdupre** [comment]
I'll think about doing an Icehouse / IPv6 test tomorrow.  That ought to cover all the bases.

**Comment by neiljerram** [comment]
Agree that it looks like DISCOVER is going to both dnsmasqs. I guess what we're seeing here is the effect of SO_REUSEPORT https://lwn.net/Articles/542629/

Disagree that we don't need to listen on the TAPS. What is your thinking there @matthewdupre ?

Testing on Icehouse is of course a good idea, but - once again - I don't believe we've actually ever observed a problem attributable to this tentative issue. I don't know how much more clearly I can say that!

**Comment by matthewdupre** [comment]
What I said wasn't intended to be any indication of what needs to happen - just a (very sketchy) guess at what might explain the logs (bind failures on the taps, and the ns-* interfaces appearing in the logs for the DISCOVERs themselves).  I've checked though, and you do need to pass --interface tap* for it to work, so I guess that's that.

I suppose the binding failures aren't critical then, which brings us back around to the retitled issue.  It doesn't look serious enough to justify a 1.0 milestone, so I'm going to leave it as it stands.

**Comment by fasaxc** [comment]
@neiljerram Might this be fixed by your recent rework of the dhcp agent to use multiple dnsmasq processes again?

**Comment by neiljerram** [comment]
Yes, I believe it will be.

**Comment by neiljerram** [comment]
This is now fixed by https://review.openstack.org/#/c/370888/.  Specifically, we now have an instance of Dnsmasq per Neutron network, which listens only on the TAP interfaces that are attached to that network.
