### ISSUE TITLE
Does calico support kube-proxy ipvs mode?

### ISSUE THREAD

**Issue by woshihaoren** [projectcalico/calico#1525]

**Comment by caseydavenport** [comment]
@woshihaoren Calico v3.0.0 has beta support for network policy in the kube-proxy ipvs mode.

@song-jiang knows the most about that, so might be able to add some context.

**Comment by song-jiang** [comment]
@woshihaoren Calico v3.0.0 support workload ingress policy only for kube-proxy ipvs mode. We are in the process of adding workload egress policy support.
