### ISSUE TITLE
startup.go/versions should log calico repo version/git commit etc

### ISSUE THREAD

**Issue by fasaxc** [projectcalico/calico#1526]
It's super useful when diagnosing build and in-field issues if the components log their versions.  For example felix logs this:
```
2017-12-19 10:18:31.179 [INFO][34] felix.go 144: Felix starting up GOMAXPROCS=4 buildDate="2017-12-19T08:00:34+0000" gitCommit="fa15f1776244d1db9e30fcd99f51b8b99be509c8" version="3.0.0-beta1-69-gfa15f177"
```
Would be great to have that in startup.go and the calico/node versions command too.  Logging the 

- exact commit ID is useful in case someone (e.g. a community member) did a custom retagged build
- buildDate is useful for unpicking issues with rebuilding (e.g. rebuild the same tag but pick up a bug in the base image)
- git describe is useful because it gives context.

Particular case I was debugging was I'd installed from `calico/node:master` and wanted to verify what revision I'd picked up.

## Expected Behavior

- log of build info.
- output in versions command

**Comment by caseydavenport** [comment]
Fixed in master.
