### ISSUE TITLE
[AWS/K8S] Calico Issues Using Nitro based AWS Instances

### ISSUE THREAD

**Issue by Z3r0Sum** [projectcalico/calico#1528]
Background Architecture:

- Development K8S Cluster running on 1.5.7
- Running CoreOS on all nodes in the cluster: 1465.6.0 (slightly adjusted with some bootstrap logic)
-  1 master and ~15 nodes
- Spread across 3 AWS AZs

It should be noted that the cluster was working fine before swapping some of the nodes out for nitro based instance types (c5s and m5s).  The only variable changing in this equation at any given time was the underlying instance types for the nodes.  The master stayed constant and is running on an m4.xlarge.

## Expected Behavior

I would expect the master to still be able to route in all 3 AWS AZs.  What transpired after the nodes were replaced with nitro-based instances was that the master's route table was only being populated by its AZ and the other 2 were unreachable as a result.  

Master routing table **before** leveraging nitro-based instances:

```
Kernel IP routing table
Destination     Gateway         Genmask         Flags   MSS Window  irtt Iface
0.0.0.0         10.110.2.1      0.0.0.0         UG        0 0          0 eth0
10.110.2.0      0.0.0.0         255.255.254.0   U         0 0          0 eth0
10.110.2.1      0.0.0.0         255.255.255.255 UH        0 0          0 eth0
100.66.156.192  10.110.3.211    255.255.255.192 UG        0 0          0 eth0
100.66.246.192  10.110.3.40     255.255.255.192 UG        0 0          0 eth0
100.69.4.0      10.110.2.21     255.255.255.192 UG        0 0          0 eth0
100.70.133.0    10.110.7.162    255.255.255.192 UG        0 0          0 tunl0
100.71.54.192   10.110.5.104    255.255.255.192 UG        0 0          0 tunl0
100.73.238.64   10.110.3.30     255.255.255.192 UG        0 0          0 eth0
100.75.193.0    10.110.2.117    255.255.255.192 UG        0 0          0 eth0
100.77.21.192   10.110.6.52     255.255.255.192 UG        0 0          0 tunl0
100.77.78.192   10.110.3.8      255.255.255.192 UG        0 0          0 eth0
100.82.169.128  10.110.4.45     255.255.255.192 UG        0 0          0 tunl0
100.84.243.128  10.110.5.151    255.255.255.192 UG        0 0          0 tunl0
100.91.6.0      10.110.7.65     255.255.255.192 UG        0 0          0 tunl0
100.91.177.128  10.110.6.192    255.255.255.192 UG        0 0          0 tunl0
100.92.15.192   10.110.6.65     255.255.255.192 UG        0 0          0 tunl0
100.94.77.128   0.0.0.0         255.255.255.192 U         0 0          0 *
100.97.185.128  10.110.7.105    255.255.255.192 UG        0 0          0 tunl0
100.106.114.64  10.110.3.204    255.255.255.192 UG        0 0          0 eth0
100.114.121.0   10.110.7.135    255.255.255.192 UG        0 0          0 tunl0
100.117.22.0    10.110.5.233    255.255.255.192 UG        0 0          0 tunl0
100.118.184.128 10.110.2.144    255.255.255.192 UG        0 0          0 eth0
172.17.0.0      0.0.0.0         255.255.0.0     U         0 0          0 docker0
```

Master routing table **after** leveraging nitro-based instances:

```
Kernel IP routing table
Destination     Gateway         Genmask         Flags   MSS Window  irtt Iface
0.0.0.0         10.110.2.1      0.0.0.0         UG        0 0          0 eth0
10.110.2.0      0.0.0.0         255.255.254.0   U         0 0          0 eth0
10.110.2.1      0.0.0.0         255.255.255.255 UH        0 0          0 eth0
100.73.238.64   10.110.3.30     255.255.255.192 UG        0 0          0 tunl0
100.94.77.128   0.0.0.0         255.255.255.192 U         0 0          0 *
100.106.114.64  10.110.3.204    255.255.255.192 UG        0 0          0 tunl0
172.17.0.0      0.0.0.0         255.255.0.0     U         0 0          0 docker0
```

## Current Behavior
It seems that nodes not on the nitro-based instance type have trouble with calico adding routes into their routing table.  I did not confirm this on any nodes other than the master (as it was the only non-nitro instance at the time), but that's the working theory.

## Steps to Reproduce (for bugs)
Easiest way would be to stand up a similar K8S environment (see environment details)

1. Master or a Node is on a non-nitro instance within AWS
2. Nodes are on nitro or a combination
3. Validate cross AZ routing between nitro and non-nitro instances

Testing within the cluster can happen via a simple hello world Kubernetes application and pinning the pod to specific nodes across varying AZs and then hitting the K8S service; however, it should be fairly clear based on an instance's routing table if there will be a problem.

## Context
It wouldn't be unreasonable in production to be running nitro and non-nitro instances until a wider variety is available.  Also, depending on the cluster replacing everything might not be feasible.

## Your Environment

* Calico version: 

```
Version:            2.4.0
Full git commit ID: b7e630e22783b96c3769cbadf019f656762acc6a
Build date:         2017-07-31T20:42:32+0000
```

* Orchestrator version (e.g. kubernetes, mesos, rkt): K8S 1.5.7, docker 1.12.6
* Operating System and version: CoreOS 1465.6.0

**Comment by fasaxc** [comment]
@Z3r0Sum  Thanks for the bug report.  A few ideas that just occurred to me:

- We made some datastore watching fixes between v2.4.0 and v2.6.3 (current stable); I recommend trying v2.6.3.  Those are particularly relevant to node restarts.
- When replacing the nodes, are you using automatically-assigned IPs?  calico/node will refuse to start if the IP of the node appears to be in use by another node, which can happen if you remove a node with nodename A without deleting it from the calico datastore and then add a new node with nodename B, re-using that IP address.

**Comment by Z3r0Sum** [comment]
@fasaxc The second bullet point is a definite possibility.  We are automatically assigning IPs.  It does seem a little coincidental that upon replacing the nodes in the other direction (non-nitro) there were no issues.  I can try and prove this out a bit more in a test cluster when I get some time.  Upgrading might be tough, since we are using kops; however, I can look into it.  Thanks for your help and advice on this!

**Comment by fasaxc** [comment]
One datapoint: I tried to start a container OS image on an m5 but it said the AMI wasn't supported.  I started an Amazon linux AMI on an m5.large and I was able to add routes manually with `ip route add`.

**Comment by ozdanborne** [comment]
Ping @Z3r0Sum have you made any progress on this?

**Comment by ozdanborne** [comment]
@Z3r0Sum we haven't heard from you in some time so I'm going to close this issue. If you are still having issues and would like to explore further please reopen!
