### ISSUE TITLE
During migration to pre-v3.0, before issuing complete, calico-felix seems to have memory leak

### ISSUE THREAD

**Issue by tmjd** [projectcalico/calico#1531]
I saw this problem when testing out the upgrade/migration from v2.6.4-rc2 to a master (pre v3.0).

## Expected Behavior
calico-felix does not grow in memory consumed

## Current Behavior
It consumes memory until OOM kills it.

## Possible Solution
Fix it

## Steps to Reproduce (for bugs)
1. Install k8s 1.8
2. Install v2.6.4-rc2
3. Run `calico-upgrade start`
4. Install master(pre v3.0) manifests
5. Monitor memory of calico-felix

## Context
I had left the system in this state (pre `calico-upgrade complete`) and my master eventually became unresponsive. When I looked at the console of the master (with VagrantBox) it showed calico-felix being killed by OOMKiller.

## Your Environment
Vagrant with 1 master and 2 nodes with K8s v1.8.2

**Comment by tmjd** [comment]
I have been unable to get a memory dump. I believe this is because the hook for dumping the memory does not get registered until after the datastore is ready.

**Comment by fasaxc** [comment]
Sigh, when we're in that mode, we discard the datastore client after each check of the ready flag.  I guess the datastore client has some internal state that we're not shutting down?

**Comment by fasaxc** [comment]
Only easy option I can think of is to restart felix after each n checks of the ready flag.  That'll cap the leak. Fixing the problem properly would be invasive.

**Comment by tmjd** [comment]
Re-tested with latest `:master`'s and it looks good now.
