### ISSUE TITLE
v2.6.4-rc2 calico-node is restarting and entering CrashLoopBackoff

### ISSUE THREAD

**Issue by tmjd** [projectcalico/calico#1532]
During upgrade the datastore ready flag is set false and it is expected that calico-node will report the liveness flag but not report the ready flag.  This does not seem to be the case for v2.6.4-rc2 because it is being restarted by K8s and entering CrashLoopBackoff.

## Expected Behavior
calico-node sits there patiently waiting for the ready flag and reports liveness so it isn't restarted.

## Current Behavior
Gets restarted

## Possible Solution
eh

## Steps to Reproduce (for bugs)
1. Install K8s 1.8.x
2. Apply Calico v2.6.4-rc2
3. Run `calico-upgrade start`
4. Wait to see calico-node get restarted

## Context
I was trying to check if calico-felix was consuming memory while the Ready flag was false like it does for the v3.0 version.

**Comment by bcreane** [comment]
@heschlie - when you have a PR ready, please add the "Calico v2.6.4" milestone.

**Comment by bcreane** [comment]
@heschlie - please close this issue, maybe after you've had a chance to verify against `v2.6.4-rc3`.

**Comment by heschlie** [comment]
This looks good, paused an upgrade at the start stage, saw readiness go to false, but liveness stay up, and no restarts :fireworks: and everything recovered on an abort test as well.
