### ISSUE TITLE
Link to docker get-started-overlay page broken, page is gone 

### ISSUE THREAD

**Issue by tmjd** [projectcalico/calico#1536]
Looking at htmlproofer output and checking the link myself (https://docs.docker.com/engine/userguide/networking/get-started-overlay/#/overlay-networking-with-an-external-key-value-store) shows that this page is gone/moved.
I attempted to locate a new version but was not able to.  I found https://docs.docker.com/engine/userguide/networking/#overlay-networks-in-swarm-mode and it has a section about using "An overlay network without swarm mode" and even has a link to the guide we were linking to that is of course also broken (seems like they may need htmlproofer).

## Expected Behavior
Link should work

## Current Behavior
Doesn't go to a useful page.

## Possible Solution
- Find a different page to link to
- Get the page re-instated.

## Steps to Reproduce (for bugs)
Try the link

## Context
Semaphore failure

**Comment by caseydavenport** [comment]
Fixed by https://github.com/projectcalico/calico/pull/1537
