### ISSUE TITLE
Running pods that are not registered with calico-ipam

### ISSUE THREAD

**Issue by bradbehle** [projectcalico/calico#1542]
This is possibly the same or a similar problem to: https://github.com/projectcalico/calico/issues/1406 but it isn't clear it is the same, so I wanted to document it in a new issue.

We have a cluster where a few pods have IP addresses that are not known by calico-ipam.  This is causing new pods that get created to attempt to use these IP addresses, and fail to start because the IPs are already being used.

## Expected Behavior
calico-ipam should know about all IPs being used by running pods

## Current Behavior
Here is some output from our cluster:

~~~
$ kubectl get pods --all-namespaces -o wide | grep Running | awk '{print $7}' | grep "172\.30" | wc -l
391

$ for i in $(kubectl get pods --all-namespaces -o wide | grep Running | awk '{print $7}' | grep "172\.30" | sort); do /opt/bin/calicoctl ipam show --ip=${i} --config calicoctl.cfg | grep -v "No attributes defined" | grep -o "172.30.[0-9]*.[0-9]*"; done
172.30.150.21
172.30.66.139
172.30.82.157

$ kubectl get pods --all-namespaces -o wide | egrep "(172.30.150.21 |172.30.66.139 |172.30.82.157 )"
ivannamespace                            ivanzk-ps-0          1/1     Running    0          20m       172.30.66.139    10.93.17.204
jindong-namespace                        jindongzk-ps-0       1/1     Running    0          18m       172.30.150.21    10.93.17.82
streaming-analytics-ussouth-qa-shared-1  streams-ops-node     1/1     Running    0          1h        172.30.82.157    10.93.14.143

$ /opt/bin/calicoctl ipam show --ip=172.30.150.21 --config calicoctl.cfg
IP 172.30.150.21 is not currently assigned in block
$ /opt/bin/calicoctl ipam show --ip=172.30.66.139 --config calicoctl.cfg
IP 172.30.66.139 is not currently assigned in block
$ /opt/bin/calicoctl ipam show --ip=172.30.82.157 --config calicoctl.cfg
IP 172.30.82.157 is not currently assigned in block
~~~

The first two pods are zookeeper pods that are part of a statefulset.  We killed these pods, and they were recreated with new IP addresses, but these new IP addresses were also not known to calico-ipam.  We had hoped to workaround this bug by killing pods that get into this state, but it appears even that doesn't cause the new IP to be registered with calico-ipam.

## Possible Solution
This is possibly the same or a similar problem to: https://github.com/projectcalico/calico/issues/1406

We are on Kubernetes 1.7.4 and calico-node v2.6.3 (so cni-installer v1.11.1).  We recently upgrade this cluster from calico-node v2.6.1 hoping that would fix this, but it did not.

## Steps to Reproduce (for bugs)
Not sure exactly how this occurs, so don't have definitive recreate steps.  It seems to happen more with StatefulSets.  See above for information about how to recreate on the cluster we have

## Context
This causes unpredictable failures when starting new pods, since calico-ipam might try to give out IPs that are already being used by other pods, causing pod creation to fail over and over again

## Your Environment

* Calico version: v2.6.3
* Orchestrator version (e.g. kubernetes, mesos, rkt): kubernetes 1.7.4
* Operating System and version: Ubuntu 16.04
* Link to your project (optional):

**Comment by bradbehle** [comment]
Here are the syslog and calico-node logs from the two nodes that the zookeeper pods were scheduled on after they were killed and restarted.

[calico-node-10.93.17.82.log](https://github.com/projectcalico/calico/files/1577561/calico-node-10.93.17.82.log)
[calico-node-10.93.17.204.log](https://github.com/projectcalico/calico/files/1577562/calico-node-10.93.17.204.log)
[syslog-10.93.17.82.log.zip](https://github.com/projectcalico/calico/files/1577563/syslog-10.93.17.82.log.zip)
[syslog-10.93.17.204.log.zip](https://github.com/projectcalico/calico/files/1577564/syslog-10.93.17.204.log.zip)

**Comment by fasaxc** [comment]
@bradbehle I believe we've fixed the issue that was causing IPs to be incorrectly freed (particularly in the stateful set case) in v2.6.4 (CNI plugin v1.11.2).  The bug ultimately came down to a faulty assumption about the CNI API on our part, which is why it was so pernicious to fix (we were relying on an ID being unique, when it wasn't guaranteed to be in certain cases).

However, upgrading to v1.11.2 doesn't cure existing instances of the problem because the IPAM tracking data was already deleted by the old CNI plugin that did have the bug.  After upgrading to v1.11.2, recreating pods should start to clean up the issue.

**Comment by tmjd** [comment]
@bradbehle Have you been able to confirm that v2.6.4 (CNI plugin v1.11.2) addresses this?

**Comment by bradbehle** [comment]
We will try calico 2.6.5 and cni 1.11.2 in the next week or so, and will post in here what we find

**Comment by ozdanborne** [comment]
@bradbehle did you get a chance to retry this?

**Comment by caseydavenport** [comment]
@bradbehle did you get a chance to repro on a newer release?

**Comment by bradbehle** [comment]
@caseydavenport @ozdanborne Sorry for the delay.  I just ran some scripts on a few of our large clusters, and did not see any pods with IPs that calico-ipam doesn't know about.  I'm considering it fixed.  Thanks!
