### ISSUE TITLE
Documentation should strongly advice against sharing etcd between calico and kubernetes

### ISSUE THREAD

**Issue by mattiasberge** [projectcalico/calico#1559]
calico-node needs client certificates to communicate with etcd (unless no authentication model on etcd). It can either read said certificates from the servers filesystem.  This puts the certificates at risk, as long as a kubernetes user freely can mount the directory the certificates are stored in. The other model would be to have the certificates in a configMap. The malicious user would then be able to mount the kubernetes kubelet certificate path and use those, which has read permissions to ALL configMaps and secrets in the kube cluster, to read and use the etcd certificates intended for calico-node to gain full permissions over etcd, and thereby the kube cluster.
Not validated, but docker runs as root and mounting any kube node directory can be done freely by anyone with access enough to deploy a pod.

The documentation, https://docs.projectcalico.org/v2.6/reference/advanced/etcd-rbac/kubernetes, states:
"When using etcd with RBAC, all components that access etcd must be configured with the proper certificates. This document describes the users and roles needed to segment etcd so that Kubernetes and Calico can only read and write within their respected subtrees/prefixes. To configure more compartmentalized configurations of the Calico components, see this addon guide."

This gives a false impression that with RBACs one achieves full segmentation. Should probably be changed to reflect the risk involved in sharing etcd.

**Comment by tmjd** [comment]
Maybe I'm misunderstanding something but are you suggesting that using the calico-node etcd certificates would allow full access to the Kubernetes etcd data if you have configured etcd RBAC (following the documentation you linked)?  That is specifically the case that the configuration you referenced prevents.

Also if someone does as you've suggested and gains access to the kubelet certificate path and subsequently accesses the calico-nod certificates then I don't think it matters if it is one etcd cluster or 2.

One point that maybe is confusing is that "etcd with RBAC" is not referring to Kubernetes RBAC but etcd RBAC, maybe we just need to drop the `with` from that sentence.

**Comment by ozdanborne** [comment]
I think what @mattiasberge is saying is:

In Kubernetes, only the apiserver needs access to etcd. But with Calico, all nodes need access to etcd. When Calico and Kubernetes share etcd, Kubernetes becomes arguably less secure as its certs must be spread across all nodes in the cluster.

We actually encounter this exact "problem" in openshift deployments and have mitigated it by providing two install paths - shared etcd, and byo etcd, and we explicitly inform users that shared etcd is not recommended for production and less secure.

I'm going to convert this into a docs issue to cover this in more detail.

**Comment by caseydavenport** [comment]
>  to read and use the etcd certificates intended for calico-node to gain full permissions over etcd, and thereby the kube cluster

I'm not sure I follow - the RBAC described in that document is intended to limit the certificates used by Calico such that a malicious users cannot access all off the etcd tree, and thus cannot access the tree owned by Kubernetes. Am I missing something?

> docker runs as root and mounting any kube node directory can be done freely by anyone with access enough to deploy a pod.

This isn't true - see pod security policies, which allow control over what mount paths are allowed to be accessed by k8s users/pods, among other things: https://kubernetes.io/docs/concepts/policy/pod-security-policy/

**Comment by mattiasberge** [comment]
@caseydavenport I admit I wasn't aware of neither etcds rbac nor using pod security policies to restrict filesystem access. I stand corrected, thanks for helping out and clarifying this. Closing this non-issue.
