### ISSUE TITLE
CALICO_ETCD_IP is not replaced with real IP

### ISSUE THREAD

**Issue by mdianjun** [projectcalico/calico#1576]
* Calico version 3.0.1
* Orchestrator version  kubernetes 1.8.4
* Operating System and version: Centos 7.2
This is the log of etcd: 
```
2018-01-01 12:03:49.061223 I | etcdmain: etcd Version: 3.1.10
2018-01-01 12:03:49.061379 I | etcdmain: Git SHA: 0520cb9
2018-01-01 12:03:49.061390 I | etcdmain: Go Version: go1.8.3
2018-01-01 12:03:49.061398 I | etcdmain: Go OS/Arch: linux/amd64
2018-01-01 12:03:49.061407 I | etcdmain: setting maximum number of CPUs to 40, total number of available CPUs is 40
2018-01-01 12:03:49.061429 I | etcdmain: advertising using detected default host "172.18.187.2"
2018-01-01 12:03:49.061485 N | etcdmain: the server is already initialized as member before, starting as etcd member...
2018-01-01 12:03:49.061672 I | embed: listening for peers on http://0.0.0.0:6667
2018-01-01 12:03:49.061812 I | embed: listening for client requests on 0.0.0.0:6666
2018-01-01 12:03:49.234035 I | etcdserver: name = calico
2018-01-01 12:03:49.234076 I | etcdserver: data dir = /var/etcd/calico-data
2018-01-01 12:03:49.234101 I | etcdserver: member dir = /var/etcd/calico-data/member
2018-01-01 12:03:49.234113 I | etcdserver: heartbeat = 100ms
2018-01-01 12:03:49.234129 I | etcdserver: election = 1000ms
2018-01-01 12:03:49.234139 I | etcdserver: snapshot count = 10000
2018-01-01 12:03:49.234160 I | etcdserver: advertise client URLs = http://$CALICO_ETCD_IP:6666
2018-01-01 12:03:49.272665 I | etcdserver: restarting member bbae441ad340c3d1 in cluster 4cdbd1ebc9dc644c at commit index 4088
2018-01-01 12:03:49.314326 I | raft: bbae441ad340c3d1 became follower at term 2
2018-01-01 12:03:49.314363 I | raft: newRaft bbae441ad340c3d1 [peers: [], term: 2, commit: 4088, applied: 0, lastindex: 4088, lastterm: 2]
2018-01-01 12:03:49.448415 I | mvcc: restore compact to 3482
2018-01-01 12:03:49.521818 I | etcdserver: starting server... [version: 3.1.10, cluster version: to_be_decided]
2018-01-01 12:03:49.522918 I | etcdserver/membership: added member bbae441ad340c3d1 [http://172.18.187.2:6667] to cluster 4cdbd1ebc9dc644c
2018-01-01 12:03:49.523090 N | etcdserver/membership: set the initial cluster version to 3.1
2018-01-01 12:03:49.523138 I | etcdserver/api: enabled capabilities for version 3.1
2018-01-01 12:03:49.634626 I | raft: bbae441ad340c3d1 is starting a new election at term 2
2018-01-01 12:03:49.634671 I | raft: bbae441ad340c3d1 became candidate at term 3
2018-01-01 12:03:49.634701 I | raft: bbae441ad340c3d1 received MsgVoteResp from bbae441ad340c3d1 at term 3
2018-01-01 12:03:49.634721 I | raft: bbae441ad340c3d1 became leader at term 3
2018-01-01 12:03:49.634732 I | raft: raft.node: bbae441ad340c3d1 elected leader bbae441ad340c3d1 at term 3
2018-01-01 12:03:49.774993 I | embed: ready to serve client requests
2018-01-01 12:03:49.775102 I | etcdserver: published {Name:calico ClientURLs:[http://$CALICO_ETCD_IP:6666]} to cluster 4cdbd1ebc9dc644c
```
The yaml is :
```
# This manifest installs the Calico etcd on the kubeadm master.  This uses a DaemonSet
# to force it to run on the master even when the master isn't schedulable, and uses
# nodeSelector to ensure it only runs on the master.
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: calico-etcd
  namespace: kube-system
  labels:
    k8s-app: calico-etcd
spec:
  template:
    metadata:
      labels:
        k8s-app: calico-etcd
      annotations:
        # Mark this pod as a critical add-on; when enabled, the critical add-on scheduler
        # reserves resources for critical add-on pods so that they can be rescheduled after
        # a failure.  This annotation works in tandem with the toleration below.
        scheduler.alpha.kubernetes.io/critical-pod: ''
    spec:
      # Only run this pod on the master.
      tolerations:
      # this taint is set by all kubelets running `--cloud-provider=external`
      # so we should tolerate it to schedule the calico pods
      - key: node.cloudprovider.kubernetes.io/uninitialized
        value: "true"
        effect: NoSchedule
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      # Allow this pod to be rescheduled while the node is in "critical add-ons only" mode.
      # This, along with the annotation above marks this pod as a critical add-on.
      - key: CriticalAddonsOnly
        operator: Exists
      nodeSelector:
        node-role.kubernetes.io/master: ""
      hostNetwork: true
      containers:
        - name: calico-etcd
          image: quay.io/coreos/etcd:v3.1.10
          env:
            - name: CALICO_ETCD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          command:
          - /usr/local/bin/etcd
          args:
          - --name=calico
          - --data-dir=/var/etcd/calico-data
          - --advertise-client-urls=http://$CALICO_ETCD_IP:6666
          - --listen-client-urls=http://0.0.0.0:6666
          - --listen-peer-urls=http://0.0.0.0:6667
          - --auto-compaction-retention=1
          volumeMounts:
            - name: var-etcd
              mountPath: /var/etcd
      volumes:
        - name: var-etcd
          hostPath:
            path: /var/etcd
```

If use this form of command and args, the problem will be resolved:
```
command: ["/bin/sh", "-c"]
args: ["/usr/local/bin/etcd --name=calico --data-dir=/var/etcd/calico-data --advertise-client-urls=http://$CALICO_ETCD_IP:6666 --listen-client-urls=http://0.0.0.0:6666 --listen-peer-urls=http://0.0.0.0:6667 --auto-compaction-retention=1"]
```

**Comment by tmjd** [comment]
I used a manifest that deployed etcd like that yesterday (and it worked). Do you perhaps have any special flags set on your kubelet (or any other k8s components) where it would handle those differently?
Or are there any changes you made in that manifest from the original calico one?

**Comment by madianjun** [comment]
@tmjd  I don't set any spectial flags on my kubelet。And , etcd yaml is not changed.

**Comment by itzamnamx** [comment]
same here, using this page as reference https://kubernetes.io/docs/setup/independent/create-cluster-kubeadm/

**Comment by itzamnamx** [comment]
victor@centauro:~$ sudo kubeadm init --ignore-preflight-errors Swap --pod-network-cidr=192.168.0.0/16
[init] Using Kubernetes version: v1.9.3
[init] Using Authorization modes: [Node RBAC]
[preflight] Running pre-flight checks.
	[WARNING SystemVerification]: docker version is greater than the most recently validated version. Docker version: 17.12.1-ce. Max validated version: 17.03
	[WARNING Swap]: running with swap on is not supported. Please disable swap
	[WARNING FileExisting-crictl]: crictl not found in system path
[preflight] Starting the kubelet service
[certificates] Generated ca certificate and key.
[certificates] Generated apiserver certificate and key.
[certificates] apiserver serving cert is signed for DNS names [centauro kubernetes kubernetes.default kubernetes.default.svc kubernetes.default.svc.cluster.local] and IPs [10.96.0.1 192.168.123.145]
[certificates] Generated apiserver-kubelet-client certificate and key.
[certificates] Generated sa key and public key.
[certificates] Generated front-proxy-ca certificate and key.
[certificates] Generated front-proxy-client certificate and key.
[certificates] Valid certificates and keys now exist in "/etc/kubernetes/pki"
[kubeconfig] Wrote KubeConfig file to disk: "admin.conf"
[kubeconfig] Wrote KubeConfig file to disk: "kubelet.conf"
[kubeconfig] Wrote KubeConfig file to disk: "controller-manager.conf"
[kubeconfig] Wrote KubeConfig file to disk: "scheduler.conf"
[controlplane] Wrote Static Pod manifest for component kube-apiserver to "/etc/kubernetes/manifests/kube-apiserver.yaml"
[controlplane] Wrote Static Pod manifest for component kube-controller-manager to "/etc/kubernetes/manifests/kube-controller-manager.yaml"
[controlplane] Wrote Static Pod manifest for component kube-scheduler to "/etc/kubernetes/manifests/kube-scheduler.yaml"
[etcd] Wrote Static Pod manifest for a local etcd instance to "/etc/kubernetes/manifests/etcd.yaml"
[init] Waiting for the kubelet to boot up the control plane as Static Pods from directory "/etc/kubernetes/manifests".
[init] This might take a minute or longer if the control plane images have to be pulled.
[apiclient] All control plane components are healthy after 30.001219 seconds
[uploadconfig] Storing the configuration used in ConfigMap "kubeadm-config" in the "kube-system" Namespace
[markmaster] Will mark node centauro as master by adding a label and a taint
[markmaster] Master centauro tainted and labelled with key/value: node-role.kubernetes.io/master=""
[bootstraptoken] Using token: 1455a5.9ca3aec138481f55
[bootstraptoken] Configured RBAC rules to allow Node Bootstrap tokens to post CSRs in order for nodes to get long term certificate credentials
[bootstraptoken] Configured RBAC rules to allow the csrapprover controller automatically approve CSRs from a Node Bootstrap Token
[bootstraptoken] Configured RBAC rules to allow certificate rotation for all node client certificates in the cluster
[bootstraptoken] Creating the "cluster-info" ConfigMap in the "kube-public" namespace
[addons] Applied essential addon: kube-dns
[addons] Applied essential addon: kube-proxy

Your Kubernetes master has initialized successfully!

To start using your cluster, you need to run the following as a regular user:

  mkdir -p $HOME/.kube
  sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
  sudo chown $(id -u):$(id -g) $HOME/.kube/config

You should now deploy a pod network to the cluster.
Run "kubectl apply -f [podnetwork].yaml" with one of the options listed at:
  https://kubernetes.io/docs/concepts/cluster-administration/addons/

You can now join any number of machines by running the following on each node
as root:

  kubeadm join --token 1455a5.9ca3aec138481f55 192.168.123.145:6443 --discovery-token-ca-cert-hash sha256:dc7af3a17bba2ac7bff998b697eb9a3d970009b1d9e3468c9d8c096e82ba4099

victor@centauro:~$ mkdir -p $HOME/.kube
victor@centauro:~$ sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
cp: ¿sobreescribir '/home/victor/.kube/config'? (s/n) s
victor@centauro:~$ sudo chown $(id -u):$(id -g) $HOME/.kube/config
victor@centauro:~$ kubectl apply -f \
> https://docs.projectcalico.org/v3.0/getting-started/kubernetes/installation/hosted/kubeadm/1.7/calico.yaml
configmap "calico-config" created
daemonset "calico-etcd" created
service "calico-etcd" created
daemonset "calico-node" created
deployment "calico-kube-controllers" created
clusterrolebinding "calico-cni-plugin" created
clusterrole "calico-cni-plugin" created
serviceaccount "calico-cni-plugin" created
clusterrolebinding "calico-kube-controllers" created
clusterrole "calico-kube-controllers" created
serviceaccount "calico-kube-controllers" created
victor@centauro:~$ watch kubectl get pods --all-namespaces
victor@centauro:~$ kubectl taint nodes --all node-role.kubernetes.io/master-
node "centauro" untainted
victor@centauro:~$ kubectl get nodes -o wide
NAME       STATUS    ROLES     AGE       VERSION   EXTERNAL-IP   OS-IMAGE             KERNEL-VERSION     CONTAINER-RUNTIME
centauro   Ready     master    4m        v1.9.3    <none>        Ubuntu 16.04.4 LTS   4.4.0-93-generic   docker://17.12.1-ce
victor@centauro:~$ ps -ef | grep CALICO_ETCD_IP
root     19562 19546  0 20:57 ?        00:00:00 /usr/local/bin/etcd --name=calico --data-dir=/var/etcd/calico-data --advertise-client-urls=http://$CALICO_ETCD_IP:6666 --listen-client-urls=http://0.0.0.0:6666 --listen-peer-urls=http://0.0.0.0:6667 --auto-compaction-retention=1
victor   30104 14041  0 21:00 pts/12   00:00:00 grep --color=auto CALICO_ETCD_IP
victor@centauro:~$

**Comment by tmjd** [comment]
I believe the fact that ps shows CALICO_ETCD_IP in the command is just a red-herring.  I deployed with the kubeadm manifest and see the same thing.  To see the value for CALICO_ETCD_IP if you do `sudo cat /proc/<etcd pid>/environ` you should see CALICO_ETCD_IP in the output and see the value it is set to.

If you could describe the problem that you are seeing perhaps we can identify the root problem.

**Comment by caseydavenport** [comment]
This guy is pretty old, so I'm going to close for now. Please shout if you are still hitting issues.

**Comment by ApsOps** [comment]
@caseydavenport I'm hitting this in the latest version as well. Following [these instructions](https://docs.projectcalico.org/v3.2/getting-started/kubernetes/).

If the entrypoint is not shell, is etcd binary really going to get the env var value for `$CALICO_ETCD_IP`?

**Comment by caseydavenport** [comment]
You're absolutely right, not sure what I missed above! I've got a PR here: https://github.com/projectcalico/calico/pull/2188
