### ISSUE TITLE
Does calico support node-to-node mesh and router reflector in one cluster?

### ISSUE THREAD

**Issue by gyliu513** [projectcalico/calico#1579]
Sorry to post the question here as I did not found a email list where I can post my questions.

The question is that calico support both node-to-node mesh and router reflector, the problem is that during our test, we found that with node-to-node mesh does not work in a 1000 node kubernetes cluster, the calico node will stop starting up after running on 700~ nodes.

After some investigation, we found that calico recommended using router reflector for large scale calico cluster.

The problem is that can I configure both node-to-node mesh and router reflector in one cluster? the process is as following: I can install a small cluster with 500 nodes using node-to-node mesh and then add another 500 nodes with router reflector? With this configuration, can the containers running in node-to-node mesh nodes talk to router reflector nodes?

@caseydavenport hope can get some comments from you, thanks!

**Comment by tmjd** [comment]
node-to-node mesh is a cluster wide setting. So when using route-reflector the node-to-node mesh should be disabled and all nodes should be connecting to the route reflector(s).

I **believe** it is possible to have a cluster with node-to-node mesh, add route reflector(s), and then disable node-to-node mesh without any traffic disruption.

Also we generally recommend to switch over to route reflectors when cluster size reaches about 100 nodes so I believe you should consider using route-reflectors before reaching 500 nodes.

**Comment by gyliu513** [comment]
@tmjd thanks for the detailed explanation!

Does there are any document related to the best practise of calico in a large scale cluster? Such as when to use router reflector, when to enable calico use a dedicated etcd server?

**Comment by tmjd** [comment]
Sorry for the delay on an answer here. I'm not aware of any documentation like you are asking about.

**Comment by gyliu513** [comment]
Thanks @tmjd 

One more question, any best practise for the mapping of router reflector to calico nodes? Such as how many calico nodes should share one router reflector?

**Comment by tmjd** [comment]
Sorry I don't really know what best practice is as far as that mapping.

If you are interested the company I work for, Tigera Inc, does provide professional services that could help design/review your architecture if you're interested, https://tigera.io/professional-services/.

**Comment by gyliu513** [comment]
Got it, thanks @tmjd , then we will try to get some data for this in the test. @caseydavenport

**Comment by tmjd** [comment]
@gyliu513 I'm going to close this issue as I think it is resolved. If you do gather some data that you would like to share I think it would be best to create a new issue.
If you want this issue to remain open just let me know and I can re-open it.

**Comment by gyliu513** [comment]
I'm OK to close this one, thanks @tmjd for the great help!
