### ISSUE TITLE
Running calico node with QoS class guaranteed

### ISSUE THREAD

**Issue by mschurenko** [projectcalico/calico#1582]
I would like to know if it is recommended to run calico node with a QoS class of guaranteed and, if so, what the recommended limits for cpu and memory should be. The reason for this is I would like to make it as unlikely as possible for kublet to evict calico node pods.

## Expected Behavior
Calico node pods should have a QoS class of guaranteed to make it less likely that kublet will evict them

## Current Behavior
calico node pods are only QoS class burstable.

## Possible Solution
Set both cpu and memory request/limits to be the same.
Example:
```yaml
resources:
  limits:
    cpu: 100m
    memory: 100Mi
  requests:
    cpu: 100m
    memory: 100Mi  
```

## Context
We are using kops and calico node is being run in a daemon set. We have had kublet evict calico node pods in the past and are looking for ways to reduce the likelihood of this occurring. 

## Your Environment
* Calico version v2.6.2
* Orchestrator version: kubernetes v1.8.4
* Operating System and version: k8s-1.7-debian-jessie-amd64-hvm-ebs-2017-07-28

**Comment by tmjd** [comment]
Generally we have only found the need to set a CPU request of 250m (and that is to ensure performance under heavy loads). You can see in one of our provided manifests on the docs site https://docs.projectcalico.org/v2.6/getting-started/kubernetes/installation/hosted/kubeadm/1.6/calico.yaml.

You should check the annotations and tolerations in that same manifest for the calico-node Daemonset. Does your deployment have the `critial-pod` annotation and `CriticalAddonsOnly` tolerations? If they are set then it should stop the pod from being evicted.

**Comment by mschurenko** [comment]
We are using CritialPodAnnotation; however that appears to only work with static pods:

https://github.com/kubernetes/kubernetes/blob/v1.8.4/pkg/kubelet/eviction/eviction_manager.go#L377

(We also tested this out with kublet and found the same thing.)

In theory the rescheduler (https://kubernetes.io/docs/tasks/administer-cluster/guaranteed-scheduling-critical-addon-pods/#rescheduler-guaranteed-scheduling-of-critical-add-ons) may help if the calico pod were to get evicted; however we are trying to prevent that from occurring in the first place. 

However all these things are unrelated to calico. What we would like to know is if it would be harmful in any way to set cpu/memory limits on calico node pods?

**Comment by caseydavenport** [comment]
@mschurenko provided you get the limit correct for your cluster, it shouldn't be harmful to set a CPU / mem limit for Calico.

I'd recommend giving substantial headroom though, since Calico is a critical piece of infrastructure and will degrade when CPU or memory constrained. This is why we typically only set requests in our manifests, allowing Calico to burst if needed. Choosing that value is going to depend a lot on your particular environment - for example how many nodes, pods, and policies are in your cluster and how frequently they change.

**Comment by caseydavenport** [comment]
I don't think we can check-in a default here - the value for `limits` is going to vary widely for different users, so what works for one user might be way too much for another, or might be severely under provisioned for another.

**Comment by mschurenko** [comment]
Great. Thanks

**Comment by caseydavenport** [comment]
I think this is all pretty non-obvious, so we should make our documentation better in this area!

I've raised https://github.com/projectcalico/calico/issues/1586 to add better documentation, so I'll close this for now.  Thanks for raising!
