### ISSUE TITLE
Document resource requests / limits for Kubernetes

### ISSUE THREAD

**Issue by caseydavenport** [projectcalico/calico#1586]
It's not obvious what the right values for resource requests / limits are for Kubernetes. 

We can't provide a default for this because it varies based on individual users and use-cases, but we can provide some guidance as to how to select the appropriate values, and what the tradeoffs and implications of setting these fields might be.

Follow on from https://github.com/projectcalico/calico/issues/1582

**Comment by rafaelvanoni** [comment]
I think this might end up doing more harm than good if, for example, a user follows the guidance too closely and ends up shooting him/herself in the foot. Closing this request until we see a stronger need for it.
