### ISSUE TITLE
document the systemd unit leak on (at least) Ubuntu 17.10

### ISSUE THREAD

**Issue by fasaxc** [projectcalico/calico#1590]
With k8s on Ubuntu 17.10, churning pods seems to leak systemd transient units related to caliXXX network interfaces at a ratio of 1:1.

## Expected Behavior

Deleting the pod should remove all its resources, including removing related systemd units.

## Current Behavior

Units of this form get leaked:
```
  sys-devices-virtual-net-calif911ef1679a.device   loaded    active   plugged   /sys/devices/virtual/net/calif911ef1679a ```

## Possible Solution
<!--- Not obligatory, but suggest a fix/reason for the bug, -->
<!--- or ideas how to implement the addition or change -->

Probably needs an upstream fix but reloading systemd works as a workaround:
```
sudo systemctl daemon-reload
```

## Steps to Reproduce (for bugs)
<!--- Provide a link to a live example, or an unambiguous set of steps to -->
<!--- reproduce this bug. Include code to reproduce, if relevant -->
1. Spin up a kubernetes rig on Ubuntu 17.10, for example using calico-ready-clusters
2. Churn some pods
3. watch `systemctl list-units --all | wc -l`, see number of units increase
4.

## Context
<!--- How has this issue affected you? What are you trying to accomplish? -->
<!--- Providing context helps us come up with a solution that is most useful in the real world -->

## Your Environment
<!--- Include as many relevant details about the environment you experienced the bug in -->
* Calico version: v3.0.2
* Orchestrator version (e.g. kubernetes, mesos, rkt): k8s 1.9.1
* Operating System and version: Ubuntu 17.10
```
$ systemd --version
systemd 234
+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD -IDN2 +IDN default-hierarchy=hybrid

$ uname -a
Linux smc-kubeadm-node-0 4.13.0-21-generic #24-Ubuntu SMP Mon Dec 18 17:29:16 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

```

**Comment by fasaxc** [comment]
I was able to reproduce the leak by simply running `ip link add/del` to create/delete a veth.  Reported upstream: https://bugs.launchpad.net/ubuntu/+source/systemd/+bug/1742250

**Comment by ozdanborne** [comment]
Since this bug is already being tracked upstream via launchpad (thanks @fasaxc ), all we can really do on the Calico side is spread awareness and document the workaround. I'm going to convert this into a docs issue.
