### ISSUE TITLE
calicoctl shows "unknown" for ASN.

### ISSUE THREAD

**Issue by caseydavenport** [projectcalico/calico#1591]
On a standard kubeadm install using Calico v3.0

{code}
ubuntu@casey-crc-kubeadm-kubeadm-master:~$ calicoctl get nodes -o wide
NAME                               ASN         IPV4             IPV6   
casey-crc-kubeadm-kubeadm-master   (unknown)   10.128.0.20/32          
casey-crc-kubeadm-kubeadm-node-0   (unknown)   10.128.0.23/32 
{/code}

## Expected Behavior

ASN shows up as "unknown" when it should really show up as the global ASN, or something that indicates it's inherited from the global ASN.

## Current Behavior

Shows up as unknown.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Calico version
* Orchestrator version (e.g. kubernetes, mesos, rkt):
* Operating System and version:
* Link to your project (optional):

**Comment by towolf** [comment]
@caseydavenport is this related to the phenomenon I am seeing on my three clusters?

On the dev cluster I sort of installed Calico manually and it shows this:
```
kvm336:~# calicoctl get bgpconfig 
NAME      LOGSEVERITY   MESHENABLED   ASNUMBER   
default   Info          true          64512      

kvm336:~# calicoctl get nodes -o wide
NAME     ASN       IPV4            IPV6   
kvm335   (64512)   10.109.0.2/24          
kvm336   (64512)   10.109.0.3/24          
kvm337   (64512)   10.109.0.4/24          
kvm338   (64512)   10.109.0.5/24     
```

So, there is a `default` bgpconfig.

But on two other clusters, I just removed the old canal config and applied the pure calico-node config and there is not default bgpconfig and no ASN shown:
```
s239:~# calicoctl get bgpconfig
NAME   LOGSEVERITY   MESHENABLED   ASNUMBER   

s239:~# calicoctl get nodes -o wide
NAME     ASN         IPV4             IPV6   
h1355    (unknown)   10.109.0.17/24          
h504     (unknown)   10.109.0.16/24          
h5345    (unknown)   10.109.0.18/24          
kvm334   (unknown)   10.109.0.51/24          
s234     (unknown)   10.109.0.14/24          
s237     (unknown)   10.109.0.11/24          
s238     (unknown)   10.109.0.10/24          
s239     (unknown)   10.109.0.9/24  
```

Am I "missing" the defautl bgpconfig, or is this only cosmetic?

**Comment by towolf** [comment]
Nevermind, [I found these docs](https://docs.projectcalico.org/v3.1/usage/configuration/bgp#example) and added a default `bgpconfig` manually, and now the display seems correct.

**Comment by caseydavenport** [comment]
@towolf yeah, the problem here is that there is a default written into the code, and a default that can be set clusterwide.

`calicoctl` doesn't display a value when the code default is in use, but will show a value when a BGP config has been explicitly set.

**Comment by caseydavenport** [comment]
Fixed!
