### ISSUE TITLE
[Question]Does calicoctl support delete multiple nodes

### ISSUE THREAD

**Issue by hchenxa** [projectcalico/calico#1598]
I have 500 calico node cluster and I want to delete the calico node by command `calicoctl`, from the help message seems the command still not support to delete multiple node or node like `calicoctl delete node --all ` or `calicoctl delete node node1,node2,node3`, Just want to know if there have some other method can delete the all nodes by command line?

**Comment by caseydavenport** [comment]
@hchenxa you can put all the nodes in a single manifest file and delete by file.

e.g.

```
calicoctl get nodes -o yaml > nodes.yaml
calicoctl delete -f nodes.yaml
```

There are other options I'd _like_ to have in the future:
- `--all` to delete all nodes
- `--labels` to delete by label match
- `calicoctl delete node NodeA NodeB NodeX`

**Comment by caseydavenport** [comment]
There are enhancement issues which track those features:

- Selection: https://github.com/projectcalico/calicoctl/issues/1383
- Multiple names: https://github.com/projectcalico/calicoctl/issues/1796

**Comment by hchenxa** [comment]
Thanks @caseydavenport
