### ISSUE TITLE
Calico 3.0 documentation support

### ISSUE THREAD

**Issue by mritd** [projectcalico/calico#1606]
Hey guys, I just started learning calico, but I found out that the documentation is old and many of the commands are not working.Unfortunately, my cluster has deployed calico 3.0.

**Comment by tmjd** [comment]
If you could elaborate on what is not working for you that would be great. We just released v3.0 at the end of the year, we thought we had made the needed updates but we must have missed some.

Please make sure you are using the v3.0 docs, if you have calico v3.0 deployed as they have changed a bit from the previous release.  You may also want to make sure you are using the appropriate calicoctl version too (`calicoctl version`).

**Comment by mritd** [comment]
@tmjd Most of the commands do not work in the [Usage](https://docs.projectcalico.org/v3.0/reference/calicoctl/resources/bgpconfig) section of the calico 3.0 documentation, such as the `--scope=global` option; There are also some explanations such as [Disabling the full node-to-node BGP mesh](https://docs.projectcalico.org/v3.0/reference/calicoctl/resources/bgpconfig) configuration is also out of date (bgp.yaml does not contain "nodeToNodeMeshEnabled" parameter);

I just learned calico, these do not work options so I do not know how to operate;However, I'm looking at the Reference section, which seems to work for calico 3.0;

Finally, thank you for answering my question. 😀

**Comment by tmjd** [comment]
Thank you for reporting this.

We would gladly accept updates if you feel like you can make them.  I have put this onto our backlog so hopefully we will get to this soon, if you or someone else doesn't beat us to fixing it.  In the meantime if you need help please feel free join our slack at slack.projectcalico.org for any specific help.
