### ISSUE TITLE
Block.affinity is null, in which case it would be?

### ISSUE THREAD

**Issue by mdianjun** [projectcalico/calico#1641]
The block is empty, and its affinity is null, I don't know why it would be.

```
[root@KC-BCC-POD23-10-196-104-196 ~]# etcdctl --endpoints http://10.196.104.195:6666 get --prefix --keys-only=false /calico/ipam/v2/assignment | grep "ty\":null"
{"cidr":"10.163.81.128/28","affinity":null,"strictAffinity":true,"allocations":[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null],"unallocated":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,0],"attributes":[]}
```

**Comment by caseydavenport** [comment]
@mdianjun sounds like you might have encountered a bug.

To start, this check looks like it might be too lenient: https://github.com/projectcalico/libcalico-go/blob/master/lib/ipam/ipam_block.go#L81-L85

That's likely not the cause, but would have at least spotted the error if it was stricter.

I believe this is where new blocks get configured: https://github.com/projectcalico/libcalico-go/blob/master/lib/ipam/ipam_block_reader_writer.go#L173-L183

It looks like the affinity should always be filled in though.

**Comment by mdianjun** [comment]
I think the reason is that I deleted the ip pool ever,  but I forget how to reproduce this.

**Comment by caseydavenport** [comment]
Ah, that would make sense.  Calico will release affinities when a pool is deleted so that nodes don't continue to assign IPs from the old blocks: https://github.com/projectcalico/libcalico-go/blob/master/lib/clientv3/ippool.go#L160-L176

**Comment by tmjd** [comment]
@caseydavenport would this still maybe be a bug or would it be expected if the IP Pool was deleted?
If there is still a possible bug here, would any of the recent IP Pool/IPAM changes possibly help?

**Comment by caseydavenport** [comment]
No, I don't think this is a bug - deleting the IP pool will release the affinities for the block, which is what we're seeing here.

Once the last IP from that block is release it should usually be deleted, but I'm guessing since this is modified code this check isn't working properly: https://github.com/projectcalico/libcalico-go/blob/master/lib/ipam/ipam_block.go#L158-L160
