### ISSUE TITLE
implement support for BGP import filters

### ISSUE THREAD

**Issue by hex2a** [projectcalico/calico#1647]
## Current Behavior
currently, the BGP import policy is hardcoded to `import all` in [bird.cfg.template](https://github.com/projectcalico/calico/blob/4262ca9c8ae71c6741c2aa653337cb71b5ed6440/calico_node/filesystem/etc/calico/confd/templates/bird.cfg.template#L21)

## Expected Behavior
there should be a way to specify import filters, when configuring a (global/node specific) peer

## Possible Solution
perhaps a similar solution to #1604 ?

## Context
Depending on the topology, an external peer might announce workload addresses (maliciously/accidentally), and cause traffic to leak (sent somewhere else, instead of the node running the workload), if the preferred route is learned from this peer.

## Your Environment
* Calico version: 2.6.2
* Orchestrator version (e.g. kubernetes, mesos, rkt): Kubernetes 1.9.1

**Comment by caseydavenport** [comment]
This seems like a reasonable follow-on given #1604

**Comment by fasaxc** [comment]
Fixed by #7271 
https://docs.tigera.io/calico/latest/reference/resources/bgpfilter
