### ISSUE TITLE
Reserved IPPools

### ISSUE THREAD

**Issue by valentin2105** [projectcalico/calico#1655]
PROPOSAL : 

Hello,

It would be great if Calico will be able tag the IPPools as "`Reserved`"  to disable Pod to get scheduled from this IPPool without specify any Annotation that point this IPPool.

It would be great because when dealing with a lot of IPPools, pods get scheduled a lot on unwanted pools and that force me to specify the IPPool I want on EACH deployment.

Thanks !

**Comment by gunjan5** [comment]
@valentin2105 not sure I understand. How is this different from IPPool `Disabled: true` configuration to stop allocating new IPs from a particular IPPool?

**Comment by valentin2105** [comment]
@gunjan5 if I put Disabled an IPPool, can i still use it by choosing this pool with a Deployment annotation ?

**Comment by gunjan5** [comment]
No that won't work, if the pool is disabled, IPs won't be allocated from it until it is enabled again. But I think I understand what you're asking now, so you want to disabled the IPPool for pods to get IP from by default unless a pod/deployment specifically asks for it using an annotation? Is that correct? 

Example:
You have:
pool-1, pool-2 - for all the other pods
pool-3 - not to be used by other pods, but only used by pods with an annotation asking for pool-3 specifically

Is that correct?

**Comment by valentin2105** [comment]
Yes its exactly that !
I looking to get "reserved" IPPool who is used only when I specify on the
Deployment.

You think is a useful feature ?

In my case, I use pool for give a dedicated IP to my DNS and Nginx-Ingress
to expose them on our DNS and reach them directly.

**Comment by fasaxc** [comment]
@gunjan5 Can you still force-allocate from a disabled pool by using the fixed IP annotation?

**Comment by caseydavenport** [comment]
Hm, yeah. We have a concept of "Disabled" IP Pools, which won't be used for IPAM.

However, I think if you specify a disabled IP Pool in an annotation it will throw an error, rather than calling the specific IP Pool.

Would be nice to have a way of setting some pools aside as reserved.

**Comment by caseydavenport** [comment]
@fasaxc you could still force-allocate, but then you need to pick an exact IP address, and it won't get tracked anywhere (so multiple pods could get the same IP because nothing is coordinating).

I think having a reserved class of IP pools probably seems sensible given the CNI plugin's selection features.

**Comment by valentin2105** [comment]
I have disabled one of my IPPool,
Then I tryed to deploy a deployment (1 replicas) with an IP of this Pool ,
It seem doesn't work : 
```
failed: rpc error: code = Unknown desc = NetworkPlugin cni failed to set up pod \"nginx-ingress-01-6b844c5b9-vjkx7_nginx-ingress\" network: error getting IP from IPAM: The provided IP address is not in a configured pool\n"

```

**Comment by fasaxc** [comment]
@caseydavenport don't get me wrong, I think having a reserved class would be good too, was just trying to find a workaround.  I thought there was an option to "force allocate and claim" an IP

**Comment by caseydavenport** [comment]
I don't think we have a "force allocate and claim" option - we have a "force allocate and don't claim" option. @gunjan5 is that right?

If you use `cni.projectcalico.org/ipAddrsNoIpam` but that only lets you specify an exact address, not an IP Pool.

**Comment by valentin2105** [comment]
I got it,

If you create a `Disabled: true` IPPool and then use `cni.projectcalico.org/ipAddrsNoIpam`, my deployment got the IP I want, and not other pod can take an IP from this Pool !!

So maybe, A `reserved` pod is useless if we can explain that in the documentation.

**Comment by gunjan5** [comment]
@caseydavenport yeah. We don't have a "force allocate and claim" option. 
One solution is what @valentin2105 described, with Disabled pool and force allocate IP, but that will require specifying IP manually for each pod/deployment, not a pool

**Comment by caseydavenport** [comment]
FWIW, with `nodeSelector` you can now create an IP pool which doesn't select any nodes, which effectively "reserves" that IP pool unless explicitly asked for.

It's a bit awkward, but works until there is something cleaner.

**Comment by fasaxc** [comment]
Couple of improvements here in v3.21:
* `IPReservations`
* `allowedUses`

**Comment by caseydavenport** [comment]
I think we can probably close this, as it's been relatively inactive and we have several methods to achieve the original intent of the issue now
