### ISSUE TITLE
Unknown datastore type: etcdv3 when setting DATASTORE_TYPE=etcdv3 for Calico Node v3.0.1

### ISSUE THREAD

**Issue by johanot** [projectcalico/calico#1656]
I run calico-node in a docker container using the following run command:

> docker run --rm --net=host --privileged --name=calico-node \
> --log-driver=none \
> -e DATASTORE_TYPE=etcdv3 \
> -e ETCD_ENDPOINTS=http://127.0.0.1:2379 \
> -e NODENAME="calico1" \
> -e IP="192.168.1.2/24" \
> -e NO_DEFAULT_POOLS=false \
> -e CALICO_LIBNETWORK_ENABLED=true \
> -e CALICO_STARTUP_LOGLEVEL=WARNING \
> -e CALICO_DISABLE_FILE_LOGGING=true \
> -e FELIX_LOGSEVERITYSCREEN=Warning \
> -e FELIX_LOGSEVERITYFILE=Fatal \
> -e FELIX_LOGSEVERITYSYS= \
> -e FELIX_LOGFILE= \
> -e FELIX_IPV6SUPPORT=false \
> -e CALICO_NETWORKING_BACKEND=bird \
> -e FELIX_DEFAULTENDPOINTTOHOSTACTION=Drop \
> -v /var/run/calico:/var/run/calico \
> -v /lib/modules:/lib/modules \
> -v /run/docker/plugins:/run/docker/plugins \
> -v /var/run/docker.sock:/var/run/docker.sock \
> 80a64d11695d7d72dc02eb28d06aee79ee8af78ffb8e5575416956cf62d07947

When not setting DATESTORE_TYPE in the environment, everything works fine connecting to etcdv3.

The docker image used is the one bundled in the 3.0.1 release tar:
https://github.com/projectcalico/calico/releases/download/v3.0.1/release-v3.0.1.tgz

## Expected Behavior
Calico node starts up without errors.

## Current Behavior

> calico1# [   25.110622] gzfwml0qna38a5gpp7vi9080y5jbsmzw-calico-node[1067]: time="2018-02-02T11:35:54Z" level=info msg="Loading config from environment"
> calico1# [   25.114888] gzfwml0qna38a5gpp7vi9080y5jbsmzw-calico-node[1067]: panic: Unknown datastore type: etcdv3
> calico1# [   25.116232] gzfwml0qna38a5gpp7vi9080y5jbsmzw-calico-node[1067]: goroutine 1 [running]:
> calico1# [   25.117949] gzfwml0qna38a5gpp7vi9080y5jbsmzw-calico-node[1067]: panic(0x144db00, 0xc420401590)
> calico1# [   25.118902] gzfwml0qna38a5gpp7vi9080y5jbsmzw-calico-node[1067]: 	/usr/local/go/src/runtime/panic.go:500 +0x1a1
> calico1# [   25.119887] gzfwml0qna38a5gpp7vi9080y5jbsmzw-calico-node[1067]: main.initializeClient()
> calico1# [   25.120826] gzfwml0qna38a5gpp7vi9080y5jbsmzw-calico-node[1067]: 	/go/src/github.com/projectcalico/libnetwork-plugin/main.go:41 +0x1ec
> calico1# [   25.121946] gzfwml0qna38a5gpp7vi9080y5jbsmzw-calico-node[1067]: main.main()
> calico1# [   25.123044] gzfwml0qna38a5gpp7vi9080y5jbsmzw-calico-node[1067]: 	/go/src/github.com/projectcalico/libnetwork-plugin/main.go:68 +0x158

## Possible Solution
Is there perhaps some mismatch between the API's for the compiled version of libnetwork vs. other Calico components?

## Steps to Reproduce (for bugs)
1. wget https://github.com/projectcalico/calico/releases/download/v3.0.1/release-v3.0.1.tgz
2. tar -xf release-v3.0.1.tgz
3. docker load -i release-v3.0.1/images/calico-node.tar
4. docker run .... (see above)

## Context
I'm building a custom Nix module for Calico and I want DATASTORE_TYPE to be configurable from the outside.

## Your Environment
* Calico version v3.0.1
* Docker v17.09.1-ce
* NixOS v17.09

**Comment by caseydavenport** [comment]
> Is there perhaps some mismatch between the API's for the compiled version of libnetwork vs. other Calico components?

@johanot Yeah, the libnetwork integration doesn't support etcdv3 yet, which is probably why it's complaining about that.

libnetwork-plugin needs to be updated to the latest libcalico-go in order to make that work, which won't be trivial because of a number of API changes. It's in the roadmap right now for Calico v3.1, which should be end Q1 2018.

**Comment by johanot** [comment]
@caseydavenport Good to know! Thanks.. Until then I will just unset the DATASTORE_TYPE, since Calico seems to startup just fine without it, even though it is backed by etcdv3.
