### ISSUE TITLE
bad error message: TLS-enabled etcdv3 : grpc: timed out when dialing

### ISSUE THREAD

**Issue by johanot** [projectcalico/calico#1659]
I cannot get calico to connect to etcd, when etcd runs on https (with TLS enabled). 

Here is my etcd configuration on a single test host:

> ETCD_ADVERTISE_CLIENT_URLS=https://etcd.my.domain:2379
> ETCD_CERT_FILE=/nix/store/mp1lvz3xxfh82k50m4kc2ly7acs3bgv5-master-keys/etcd.pem
> ETCD_CLIENT_CERT_AUTH=1
> ETCD_DATA_DIR=/var/lib/etcd
> ETCD_DISCOVERY=
> ETCD_INITIAL_ADVERTISE_PEER_URLS=https://192.168.1.1:2380
> ETCD_INITIAL_CLUSTER=machine=https://192.168.1.1:2380
> ETCD_INITIAL_CLUSTER_STATE=new
> ETCD_INITIAL_CLUSTER_TOKEN=test
> ETCD_KEY_FILE=/nix/store/mp1lvz3xxfh82k50m4kc2ly7acs3bgv5-master-keys/etcd-key.pem
> ETCD_LISTEN_CLIENT_URLS=https://192.168.1.1:2379
> ETCD_LISTEN_PEER_URLS=https://192.168.1.1:2380
> ETCD_NAME=machine
> ETCD_PEER_CERT_FILE=/nix/store/mp1lvz3xxfh82k50m4kc2ly7acs3bgv5-master-keys/etcd.pem
> ETCD_PEER_KEY_FILE=/nix/store/mp1lvz3xxfh82k50m4kc2ly7acs3bgv5-master-keys/etcd-key.pem
> ETCD_PEER_TRUSTED_CA_FILE=/nix/store/vv1h95iz6kn02158x33x644pkrwm7h86-worker-keys/ca.pem
> ETCD_TRUSTED_CA_FILE=/nix/store/vv1h95iz6kn02158x33x644pkrwm7h86-worker-keys/ca.pem

Here is my Calico Node configuration:

> docker run --rm --net=host --privileged --name=calico-node 
> --log-driver=none 
> -e ETCD_ENDPOINTS=https://etcd.my.domain:2379 
> -e ETCD_KEY_FILE=/nix/store/vv1h95iz6kn02158x33x644pkrwm7h86-worker-keys/etcd-client-key.pem 
> -e ETCD_CERT_FILE=/nix/store/vv1h95iz6kn02158x33x644pkrwm7h86-worker-keys/etcd-client.pem 
> -e ETCD_CA_CERT_FILE=/nix/store/vv1h95iz6kn02158x33x644pkrwm7h86-worker-keys/ca.pem
> -e NODENAME="calico1" 
> -e NO_DEFAULT_POOLS=false 
> -e CALICO_LIBNETWORK_ENABLED=true 
> -e CALICO_STARTUP_LOGLEVEL=WARNING 
> -e CALICO_DISABLE_FILE_LOGGING=true 
> -e FELIX_LOGSEVERITYSCREEN=Warning 
> -e FELIX_LOGSEVERITYFILE=Fatal 
> -e FELIX_LOGSEVERITYSYS= 
> -e FELIX_LOGFILE= 
> -e FELIX_IPV6SUPPORT=false 
> -e CALICO_NETWORKING_BACKEND=bird 
> -e FELIX_DEFAULTENDPOINTTOHOSTACTION=Accept 
> -v /var/run/calico:/var/run/calico 
> -v /lib/modules:/lib/modules 
> -v /run/docker/plugins:/run/docker/plugins 
> -v /var/run/docker.sock:/var/run/docker.sock 
> 80a64d11695d7d72dc02eb28d06aee79ee8af78ffb8e5575416956cf62d07947

etcdctl uses the same set of certificates and settings, and it connects to the etcd server just fine.
Disabling client-cert auth on etcd makes no difference. "One-way TLS" doesn't work either.

Everything works fine if I disable https all-together, making etcd listen on the http:// scheme.

## Expected Behavior
Calico should be able to TLS-connect to its etcdv3 datastore.

## Current Behavior
ERROR: Error accessing the Calico datastore: grpc: timed out when dialing

## Possible Solution
I suspect that there is an error in the instantiation parameters of the etdv3 client from libcalico. Or perhaps a bug in the etcdv3 client itself? A possible scenario could be that the etcdv3 client always tries to connect to http://127.0.0.1:2379 - ignoring the ETCD_ENDPOINTS env-var that I set for Calico?

Setting loglevels to DEBUG doesn't reveal which endpoint the etcdv3 client actually tries to call. :(

## Steps to Reproduce (for bugs)
1. Start etcd with above configuration
2. wget https://github.com/projectcalico/calico/releases/download/v3.0.1/release-v3.0.1.tgz
3. tar -xf release-v3.0.1.tgz
4. docker load -i release-v3.0.1/images/calico-node.tar
5. docker run .... (see above)

## Context
I'm building a custom Nix module for Calico and I would prefer to be able to connect to a TLS-enabled etcd cluster.

## Your Environment
Calico version v3.0.1
etcd version v3.1.6 as well as v3.2.15
Docker v17.09.1-ce
NixOS v17.09

**Comment by caseydavenport** [comment]
Hm, the libcalico code for that is here: https://github.com/projectcalico/libcalico-go/blob/master/lib/backend/etcdv3/etcdv3.go#L55-L67

It seems correct to me, though we are ignoring a returned error there which isn't great, and could be related.

**Comment by evident-sbellows** [comment]
Also running into this problem. Calico cannot talk to etcd while etcdctl can. 

Environment:
Calico Version: v3.0.0
Etcd Version: 3.2.12
Docker Version: 17.03.2~ce-0~ubuntu-xenial
Ubuntu 16.04 LTS

**Comment by tmjd** [comment]
@johanot It looks like you need to add a volume mount to make those certificates available in the container.  Could you try adding that and see what you get then? If the error still exists could you add a larger log snippet from calico/node (see the note below).

@evident-sbellows Looking at your [slack message here](https://calicousers.slack.com/archives/C0BC91S9F/p1517927353000499) it looks like you've got the certs mounted in. Could you jump into the container and verify that the certs and key are available where you expect? If that still looks good could you add a larger snippet from the logs too (see the node below).

Could you both try setting `CALICO_STARTUP_LOGLEVEL=debug` and see if that provides any additional information?

**Comment by tmjd** [comment]
I was able to run the `make st-ssl` target in calico_node which runs our system tests against an etcd that is configured for TLS so that gives a little confidence that it is not totally broken. @johanot I guess there is the possibility that it is only connecting to localhost.

Could you both take a look at your etcd logs and see if you see calico/node attempting to connect? It might provide some info about what the problem is too.  Thanks

**Comment by bradbehle** [comment]
I just got this same message: "grpc: timed out when dialing" and it turned out my problem was that I had a typo in the path to my etcdKeyFile, etcdCert, and etcdCACertFile entries in my calicoctl.cfg file.  So maybe verify that the path for those entries is correct in your config.

Also, @tmjd, it would be nice if calicoctl would return a more descriptive error when the path to one of the cert or key files was incorrect (i.e. pointed to a file that does not exist).  When I used etcdctl with a bad file path it gave me a nice error `Error:  open /home/sysadmin/etcd.pem: no such file or directory`

**Comment by caseydavenport** [comment]
I've raised #1696, which I think is the real problem here.

@johanot @evident-sbellows could you confirm whether or not you're seeing the same issue as Brad?

**Comment by tmjd** [comment]
With the [v3.0.3 release](https://docs.projectcalico.org/v3.0/releases/) yesterday there is better error reporting when there are issues with the etcd certificates.  @johanot and @evident-sbellows if you could try again and report your results it would be appreciated.

**Comment by johanot** [comment]
@caseydavenport @tmjd Sorry for the late response. I've now tested with v3.0.3 on the same setup. This is the error message I get from the two versions respectively: 

v3.0.3:
> Error accessing the Calico datastore: context deadline exceededCalico node failed to start

v3.0.1:
> Error accessing the Calico datastore: grpc: timed out when dialingCalico node failed to start

I don't see much difference in the error reporting here? .. etcd is running and it is TLS-enabled. I can curl to https://etcd.domain:2379 and get a response.

There is a slight chance that there is a certificate misconfiguration still somehow, but _why_ would that manifest as a timeout?

Anyway.. I switched attention to Kube-router now, and Kubernetes has no problem TLS-connecting to the same etcd instance.

**Comment by tmjd** [comment]
@johanot Thanks trying again and reporting back.  Did you add a volume mount like I suggested in https://github.com/projectcalico/calico/issues/1659#issuecomment-363877333 so that the certificates are available in the calico-node container?

**Comment by johanot** [comment]
@tmjd I finally managed to get time to test again. Sorry (again).
I found out that two things where missing in my setup:

1. The volume-mount for the certs, as you mentioned. (thanks)
2. The CN / SAN of the server cert did not match the test hostname I had setup.

... Fixing either of the two still gave me:

v3.0.3:
> Error accessing the Calico datastore: context deadline exceededCalico node failed to start

v3.0.1:
> Error accessing the Calico datastore: grpc: timed out when dialingCalico node failed to start

... Fixing both 1 *and* 2 made Calico-node start up healthy.

I only found out for sure about both errors by manually curl'ing etcd.
```bash
[root@machine:~]# curl --cacert /nix/store/wz91nni0kpbbm8gmsq9sgxcxj5arnbmp-master-keys/ca.pem https://etcd:2379
curl: (51) SSL: no alternative certificate subject name matches target host name 'etcd'

[root@machine:~]# curl --cacert /file/not/found/wz91nni0kpbbm8gmsq9sgxcxj5arnbmp-master-keys/ca.pem https://etcd:2379
curl: (77) error setting certificate verify locations:
  CAfile: /file/not/found/wz91nni0kpbbm8gmsq9sgxcxj5arnbmp-master-keys/ca.pem
  CApath: none
```

If Calico had given me error messages like curl does, my life would have been easier :-)
Thanks for continuous support and work!
