### ISSUE TITLE
Document how to add external RRC's to Calico route reflector container

### ISSUE THREAD

**Issue by liljenstolpe** [projectcalico/calico#1668]
## Expected Behavior
An increasingly common topology is an 'L2' network (either in some public clouds or private infra with VXLAN/VTEP overlay).  In those cases, we recommend 2 or more route reflectors with all Calico nodes peered with some (subset) of RR's.  However, the egress router(s) also need to be route reflector clients of those route reflectors.  The instructions do not document how to configure this on the RR side.

## Current Behavior
It's an exercise left to the reader.

## Possible Solution
Create a host-endpoint and use that as a peer definition in calicoctl

## Context
Increasing use of this topology

**Comment by caseydavenport** [comment]
The RR container is going away in Calico v3.3, so this will all be covered by the standard Calico BGPPeer resource documentation, which already covers how to set up external peerings.
