### ISSUE TITLE
calico-node enters CrashLoopBackOff after migration to v3

### ISSUE THREAD

**Issue by r0bj** [projectcalico/calico#1692]
Migration was done with documentation from https://docs.projectcalico.org/v3.0/getting-started/kubernetes/upgrade/

1. migrate calico data in etcd
2. update calico self-hosted installation that uses the etcd datastore

Calico yaml manifest:
https://gist.github.com/r0bj/0efa479ddb872230260f3c40c3dc8b0e

(rather standard from https://docs.projectcalico.org/v3.0/getting-started/kubernetes/installation/hosted/calico.yaml)

## Expected Behavior

Upgraded calico pods are in `Running` state.

## Current Behavior

Upgraded calico pods are in `CrashLoopBackOff` state.
Container `install-cni` is exiting with 1 exit code and enters restarting loop.

```
$ kubectl describe pod calico-node-kcvlm -n kube-system
[...]
  install-cni:
    Container ID:  docker://4399d6e89d419f65e0310551da2b5d63a29d0c5c094bde45c4a6d1a28a797f1f
    Image:         quay.io/calico/cni:v2.0.0
    Image ID:      docker-pullable://quay.io/calico/cni@sha256:ddb91b6fb7d8136d75e828e672123fdcfcf941aad61f94a089d10eff8cd95cd0
    Port:          <none>
    Command:
      /install-cni.sh
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Wed, 14 Feb 2018 12:14:59 +0000
      Finished:     Wed, 14 Feb 2018 12:14:59 +0000
    Ready:          False
    Restart Count:  7
```

It causing:
```
Events:
  Type     Reason                 Age                From                        Message
  ----     ------                 ----               ----                        -------
  Normal   Pulling                13m                kubelet, dev-k8s-worker-s2  pulling image "quay.io/calico/node:v3.0.2"
  Normal   SuccessfulMountVolume  13m                kubelet, dev-k8s-worker-s2  MountVolume.SetUp succeeded for volume "cni-bin-dir"
  Normal   SuccessfulMountVolume  13m                kubelet, dev-k8s-worker-s2  MountVolume.SetUp succeeded for volume "var-run-calico"
  Normal   SuccessfulMountVolume  13m                kubelet, dev-k8s-worker-s2  MountVolume.SetUp succeeded for volume "lib-modules"
  Normal   SuccessfulMountVolume  13m                kubelet, dev-k8s-worker-s2  MountVolume.SetUp succeeded for volume "calico-node-token-xvmb2"
  Normal   SuccessfulMountVolume  13m                kubelet, dev-k8s-worker-s2  MountVolume.SetUp succeeded for volume "etcd-certs"
  Normal   SuccessfulMountVolume  13m                kubelet, dev-k8s-worker-s2  MountVolume.SetUp succeeded for volume "cni-net-dir"
  Normal   Pulling                13m                kubelet, dev-k8s-worker-s2  pulling image "quay.io/calico/cni:v2.0.0"
  Normal   Pulled                 13m                kubelet, dev-k8s-worker-s2  Successfully pulled image "quay.io/calico/node:v3.0.2"
  Normal   Started                13m                kubelet, dev-k8s-worker-s2  Started container
  Normal   Created                13m                kubelet, dev-k8s-worker-s2  Created container
  Normal   Pulled                 13m                kubelet, dev-k8s-worker-s2  Successfully pulled image "quay.io/calico/cni:v2.0.0"
  Normal   Created                13m (x3 over 13m)  kubelet, dev-k8s-worker-s2  Created container
  Normal   Started                13m (x3 over 13m)  kubelet, dev-k8s-worker-s2  Started container
  Normal   Pulled                 12m (x3 over 13m)  kubelet, dev-k8s-worker-s2  Container image "quay.io/calico/cni:v2.0.0" already present on machine
  Warning  BackOff                3m (x46 over 13m)  kubelet, dev-k8s-worker-s2  Back-off restarting failed container
```

Full describe pod log:
https://gist.github.com/r0bj/09ab208b2d89555247ba1dd181b25d2b

Log from container `install-cni`:
```
Installing any TLS assets from /calico-secrets
cp: can't stat '/calico-secrets/*': No such file or directory
```

Logs from calico-node container:
https://gist.github.com/r0bj/e3075bf56791266efad0adeff0af19bb

Migration cannot be finished because calico pods cannot be upgraded.
Calico pods cannot be upgraded because rolling upgrade process stops with failed pods.

## Possible Solution

If `install-cni` container would exit with 0 exit code it would probably work.

## Your Environment

* Calico version
Migration from v2.6.5 to v3.0.2
* Orchestrator version (e.g. kubernetes, mesos, rkt):
kubernetes v1.9.3
* Operating System and version:
ubuntu 14.04

**Comment by tmjd** [comment]
I'm not sure what's going on there. Immediately before that `Installing any TLS assets from /calico-secrets` it checks if there are any files in that directory and if there aren't then it shouldn't be attempting the copy.  I just tried some commands in the calico/cni container and the only way I could get it to produce that error was if there was a hidden file.  Maybe something has changed in K8s v1.9.3 where a Secret mounted as a volume has a hidden file.

**Comment by tmjd** [comment]
Ok yeah I just brought up a cluster with K8s v1.9.3 and this is what I see.
```
/ # ls -A /calico-secrets
..2018_02_14_17_24_53.555775789  ..data
```
This is probably due to https://github.com/kubernetes/kubernetes/pull/57422.

I think a fix will be needed to ignore those new files or to only check for non-hidden files (which I think would be the preferred approach).

@r0bj Since you are not using the certs, the simplest work around is to remove the
```
            - mountPath: /calico-secrets
              name: etcd-certs
```
from the `install-cni` container in the `calico-node` DaemonSet.  I just tried that out and it worked for me.

**Comment by tmjd** [comment]
A new release of CNI is available, https://github.com/projectcalico/cni-plugin/releases/tag/v2.0.1.  You should be able to update [line 216](https://gist.github.com/r0bj/0efa479ddb872230260f3c40c3dc8b0e#file-gistfile1-txt-L216) to `image: quay.io/calico/cni:v2.0.1` and pick up the new release.
That should fix this problem.  Please report back if this does not fix the problem for you.

**Comment by tmjd** [comment]
I also wanted to add, thank you for the thorough issue report.

**Comment by gjmzj** [comment]
I have a similar problem when Migrating from v2.6.5 to v3.0.2, 
``` bash
$ kubectl get pod --all-namespaces
NAMESPACE     NAME                                       READY     STATUS             RESTARTS   AGE
kube-system   calico-kube-controllers-5f748b7f66-dkp5b   1/1       Running            0          16m
kube-system   calico-node-5bfbh                          1/2       CrashLoopBackOff   7          16m
kube-system   calico-node-7w65h                          1/2       CrashLoopBackOff   7          16m
kube-system   calico-node-nx8dg                          1/2       CrashLoopBackOff   7          16m
```
I checked container logs, it seemed that container `calico-node` was ready, and the container `install-cni` failed.
and i tried new release `image: quay.io/calico/cni:v2.0.1`, and still it didn't work. 
k8s 1.9.3

**Comment by tmjd** [comment]
@gjmzj Those logs look like a successful execution of install-cni. Could you check the `State` on the containers when doing a `kubectl -n kube-system describe pod calico-node-jpzv7`, the expected value is `Running` for both calico-node and install-cni.

Upon closer inspection of your CNI config, if you are using one of the manifests from the calico docs, I think your etcd_(key/cert/ca_cert)_file paths are incorrect. Those fields should be the commented out values in the manifest (for example `etcd_ca` in the manifest should be `/calico-secrets/etcd-ca`).

**Comment by gjmzj** [comment]
@tmjd OK, please look at #1708

Thanks

**Comment by xianzhengzhou** [comment]
@tmjd I'm still getting this error when using release-v3.3 docker image from docker hub.
* cni container is working fine.
BUT
* node and kube-controller containers are complaining this:
```
2018-12-04 16:09:23.865 [FATAL][1] main.go 87: Failed to start error=failed to build Calico client: could not initialize etcdv3 client: open /calico-secrets/etcd-cert": no such file or directory
```

I've copied the /calico-secrets folder out of the failed folder and the the following structure:
```
[engineer@prime ~]$ cd calico-secrets/
[engineer@prime calico-secrets]$ ls -l
total 0
lrwxrwxrwx 1 engineer engineer 14 Dec  5 14:06 etcd-ca -> ..data/etcd-ca
lrwxrwxrwx 1 engineer engineer 16 Dec  5 14:06 etcd-cert -> ..data/etcd-cert
lrwxrwxrwx 1 engineer engineer 15 Dec  5 14:06 etcd-key -> ..data/etcd-key
[engineer@prime calico-secrets]$ ls -l ..data
lrwxrwxrwx 1 engineer engineer 31 Dec  5 14:06 ..data -> ..2018_12_05_06_06_54.765987479
[engineer@prime calico-secrets]$ ls ..2018_12_05_06_06_54.765987479/
etcd-ca  etcd-cert  etcd-key
```

**Comment by xianzhengzhou** [comment]
Is it fixed for cni but not for node and kube-controller?
