### ISSUE TITLE
Docker basic tutorial doesn't give enough guidance on ETCD_ENDPOINTS

### ISSUE THREAD

**Issue by tomdee** [projectcalico/calico#170]
https://github.com/projectcalico/calico/blob/master/master/getting-started/docker/tutorials/basic.md

It tells people to set ETCD_ENDPOINTS but this value will be different depending on what environment they used to set up their servers. The installation guides should close with a clear statement on what value for ETCD_ENDPOINTS should be used.

**Comment by djosborne** [comment]
Can probably nip this during the Docker documentation overhaul: #285

**Comment by bjwbell** [comment]
Fixed with PR https://github.com/projectcalico/calico/pull/326.

**Comment by tomdee** [comment]
#326 didn't get merged but this issue might still be handled by #285

**Comment by djosborne** [comment]
The guides have been rewritten but I did not address this during #285. 

Now that our docker documentation isn't moving around that much we should decide how we want to address this and go ahead. 

I'm thinking the new [Calico/Docker Installation Guide](http://docs.projectcalico.org/v2.0/getting-started/docker/installation/manual) should link to the [Calicoctl config guide](http://docs.projectcalico.org/v2.0/reference/calicoctl/setup/etcdv2).
