### ISSUE TITLE
calico-node fails to start but doesn't log an error message

### ISSUE THREAD

**Issue by vainu-arto** [projectcalico/calico#1715]
In a Kops generated Kubernetes cluster running v1.8.8 I have recently started seeing nodes that claim to start successfully but have no network connectivity. Tracking the issue down I found a major difference between the calico logs of working and failing nodes, below:

## Expected Behavior
On a successfully starting node calico logs start this way:

Skipping datastore connection test
IPv4 address 172.20.75.115 discovered on interface eth0
No AS number configured on node resource, using global value
Using node name: ip-172-20-75-115
time="2018-03-01T07:27:20Z" level=info msg="Loading config from environment" 
time="2018-03-01T07:27:20Z" level=info msg="IPIP tunnel address is still valid" IP=100.106.253.0 
Calico node started successfully
bird: device1: Initializing
bird: direct1: Initializing
bird: device1: Starting

## Current Behavior

In the failing case calico-node logs these lines, and nothing else:
Skipping datastore connection test
Using autodetected IPv4 address on interface eth0: 172.20.35.209/19

Pods started on a host like this do not have network connectivity.

Does the second line provide a clue? What is the difference between "IPv4 address 172.20.75.115 discovered on interface eth0" and "Using autodetected IPv4 address on interface eth0: 172.20.35.209/19"?

## Your Environment
* Calico version v2.6.5
* Orchestrator version (e.g. kubernetes, mesos, rkt): Kubernetes v1.8.8
* Operating System and version: Debian 9 'Stretch'

**Comment by tmjd** [comment]
The `IPv4 address 172.20.75.115 discovered on interface eth0` means that an IP address was already configured for the node in the datastore.
`Using autodetected IPv4 address on interface eth0: 172.20.35.209/19` means that there was not a node previously configured, so on startup it is necessary to detect the IP and configure a node entry in the datastore.

I wonder if there is a problem connecting to your datastore from the nodes that have a problem.  You should verify connectivity to your datastore from them.  I'm not too confident this is the problem because I would expect more logs if it was a connection problem.

**Comment by vainu-arto** [comment]
Ah, this was useful information indeed.

The failing instances do have general network connectivity (that was the first thing I tested), but I'll look into how I can check for connectivity specifically to the datastore (etcd, I assume?).

This issue started when I increased the size of the Kubernetes cluster, but I haven't seen an indication of load issues on the three masters. I'm not currently seeing the problem, perhaps I'll try to scale up again and see what happens.

**Comment by vainu-arto** [comment]
After digging deeper I can find error messages from etcd. I'm not sure what the root cause of those is, but that is probably the root cause of this issue as well.

**Comment by tmjd** [comment]
@vainu-arto Thank you for reporting back. We're going to leave this issue open because there should be better error reporting on datastore failures.  Do you have any details on the etcd error messages? They may help us understand the error cases we need to handle better.

**Comment by vainu-arto** [comment]
Other components are reporting timeouts when accessing etcd, and occasionally "client: etcd cluster is unavailable or misconfigured; error #0: client: etcd member http://127.0.0.1:4002 has no leader".

The root cause appears to be that I run out of IOPS on the EBS volumes backing etcd. Testing this is somewhat slow since my first guess at a more suitable value wasn't enough and I didn't know that AWS only allows changing this value once every 6 hours...

**Comment by tmjd** [comment]
You've figure out the problem was connectivity to etcd so I'm going to close this.  One possible thing that might help is to update to Calico v3.x, though I realize with kops that is easier said than done.
