### ISSUE TITLE
Example yamls are too complex

### ISSUE THREAD

**Issue by caseydavenport** [projectcalico/calico#173]
The example calicoctl yaml files in the docs are too complicated.  They shouldn't try to be the source of truth, or include _every_ field.

They should essentially be a skeleton that people can copy and paste that would make sense for 90% of users to then tweak for their needs.

**Comment by djosborne** [comment]
@caseydavenport I think we need both. A fully filled out one helps resolve confusion over how to format particular fields. And a minimal, realistic example helps to get started.

**Comment by caseydavenport** [comment]
@djosborne No, I really don't want examples to be the source of truth.  Our documentation should be good enough that you don't need to dig through examples to find out how to compose a yaml.

We have tables which describe the valid fields for each resource in the docs already.   Those should be made expressive enough that you don't need a full example.
