### ISSUE TITLE
Increased number of kubernetes API calls with node to node mesh disabled

### ISSUE THREAD

**Issue by andrestc** [projectcalico/calico#1739]
Disabling node to node mesh while using the Kubernetes backend increases the number of Kubernetes API calls done by confd. This happens because libcalico-go does not support Watching a single node (https://github.com/projectcalico/libcalico-go/blob/16a16d0960511310db4772874de7650ab2967827/lib/backend/k8s/resources/node.go#L164). And that is what confd does when starting with node to node mesh disabled (https://github.com/projectcalico/confd/blob/master/backends/calico/client.go#L111).

I noticed this by seeing several logs like:

```
[INFO][73] watchercache.go 197: Failed to create watcher ListRoot="/calico/resources/v3/projectcalico.org/nodes/xxxx" error=cannot watch specific resource instance: xxxx performFullResync=true
```

## Expected Behavior
The number of Kubernetes API calls should not increase when disabling node to node mesh.

## Current Behavior

The number of Kubernetes API calls increased by 20x (probably linear to the number of nodes in the cluster).

## Possible Solution
Change the Kubernetes backend to enable watching a single node to prevent `calico-node` from performing full resyncs continuously. 

## Steps to Reproduce (for bugs)
1. Configure calico to use Kubernetes as the backend
2. Disable node to node mesh
3. Watch for the logs and API calls to the Kubernetes API

## Context

We want to run calico with node to node mesh disabled as we are running in a custom network topology where access between nodes are limited. We started https://github.com/tsuru/remesher to accomplish this.

## Your Environment

* Calico 3.0.3
* Kubernetes 1.8.x

I would be happy to help by contributing a fix to this (but would like to get some help deciding what would be the best way to fix this).

**Comment by caseydavenport** [comment]
@andrestc thanks for raising this.

It looks like we explicitly prevent this here: https://github.com/projectcalico/libcalico-go/blob/master/lib/backend/k8s/resources/node.go#L163-L165

Though, I don't think we need to. The `watch.Interface` returned by `Nodes().Watch()` doesn't expose a way to watch an individual named node object which is probably why we've got that check there now, but the underlying Request object does support this as seen here: https://github.com/kubernetes/client-go/blob/82aa063804cf055e16e8911250f888bc216e8b61/rest/request.go#L204-L222

I think we just need to go a level down into client-go so we can set the resource name on the request.

I'm happy to help out with design / review if you'd like to work on a fix.

**Comment by caseydavenport** [comment]
Looking again at this now, I believe this should only be hit when node-to-node mesh is _enabled_, not when it's disabled.

confd disables the node watch when disabled.

**Comment by andrestc** [comment]
I was not able to look into this to try and contribute but thats not what I understand when I look at https://github.com/projectcalico/libcalico-go/blob/d8b7e0355c6fc8a27a169425980b69ead7f2e597/lib/backend/syncersv1/bgpsyncer/bgpsyncer.go#L36. I think it always enables the node watch, but when the node-to-node mesh is disabled it only watches the current node (which is not supported on the kubernetes backend, and causes the issue described). (`watchAllNodes` is `nodeMeshEnabled || routeReflector` per https://github.com/projectcalico/confd/blob/master/backends/calico/client.go#L111:50)

**Comment by caseydavenport** [comment]
Ah, right. That checks out!

working on a fix here: https://github.com/projectcalico/libcalico-go/pull/835
