### ISSUE TITLE
What's the use of cni_network_config's portmap?

### ISSUE THREAD

**Issue by woshihaoren** [projectcalico/calico#1743]
```
    {
      "type": "portmap",
      "snat": true,
      "capabilities": {"portMappings": true}
    }

```

**Comment by tmjd** [comment]
The portmap plugin allows using Kubernetes `hostPort`.

**Comment by caseydavenport** [comment]
Here's some reference material: https://github.com/containernetworking/plugins/blob/master/plugins/meta/portmap/README.md
