### ISSUE TITLE
Base docker image upgrade for Calico/test in Dockerfile.calico_test 

### ISSUE THREAD

**Issue by guirish** [projectcalico/calico#1744]
## Context

The base image used to build calico/test in Dockerfile.calico_test  is docker:1.13.0 are there plans to bump the Docker version(Docker 1.17+) in mentioned file?. We have verified ST run with docker 17.12 and all test cases were passing on s390x and x86_64.  Accordingly we will update the base Docker version to be used when pushing PR for s390x support.

## Your Environment

* Calico version :v3.0.3
* Operating System and version: Ubuntu 16.04, 17.10 and RHEL 7.3 and RHEL 7.4

**Comment by ozdanborne** [comment]
Updating the docker daemon sounds fine. Would you mind submitting a PR?

**Comment by guirish** [comment]
sure , I will test with latest docker:18.03.0 and raise a PR accordingly.
