### ISSUE TITLE
Multiple nodes, minikube and calico

### ISSUE THREAD

**Issue by verizonold** [projectcalico/calico#1746]
Is there an example to run calico and minikube in a multiple node setup?

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Calico version
* Orchestrator version (e.g. kubernetes, mesos, rkt):
* Operating System and version:
* Link to your project (optional):

**Comment by caseydavenport** [comment]
@verizonold thanks for asking! I don't think such a guide exists today, but it should follow the standard hosted install procedure: https://docs.projectcalico.org/v3.0/getting-started/kubernetes/installation/hosted/hosted

If you manage to get it working, we'd love to hear about it! If you hit any issues, please open them here and we can help figure it out.
