### ISSUE TITLE
bird routes unreachalbe. kubectl logs not working

### ISSUE THREAD

**Issue by haashah** [projectcalico/calico#1761]
## Expected Behavior
Master and worker nodes able to communicate with eachother. kubectl logs command fetches logs from calico pods.

## Current Behavior
kubectl logs command fails with following error: 

kubectl logs calico-node-4j2bk -n kube-system calico-node
Error from server: Get https://10.1.1.175:10250/containerLogs/kube-system/calico-node-4j2bk/calico-node: dial tcp 10.1.1.175:10250: connect: no route to host

Basically communication between my nodes in the cluster is broken. I have one master and two workers each running in a different subnet in the same VPC on AWS. Upon investigation I found out routes from bird were unreachable:

**ip r**
default via 10.1.2.1 dev eth0 
unreachable 10.1.1.0/24 proto bird 
10.1.2.0/24 dev eth0 proto kernel scope link src 10.1.2.95 
172.17.0.0/16 dev docker0 proto kernel scope link src 172.17.0.1 
blackhole 192.168.219.64/26 proto bird 
192.168.219.65 dev calibb2a89e60cf scope link 
unreachable 192.168.235.128/26 proto bird

**sudo calicoctl node status**
Calico process is running.

IPv4 BGP status
+--------------+-------------------+-------+----------+-------------+
| PEER ADDRESS |     PEER TYPE     | STATE |  SINCE   |    INFO     |
+--------------+-------------------+-------+----------+-------------+
| 10.1.1.175   | node-to-node mesh | up    | 07:00:49 | Established |
| 10.1.3.119   | node-to-node mesh | up    | 06:58:01 | Established |
+--------------+-------------------+-------+----------+-------------+

IPv6 BGP status
No IPv6 peers found.

**kubectl get pods --all-namespaces**
NAMESPACE     NAME                                       READY     STATUS             RESTARTS   AGE
default       pdns-deployment-797c75dbf9-9nwhm           0/7       ImagePullBackOff   0          2h
default       pdns-deployment-797c75dbf9-dq55t           0/7       ImagePullBackOff   0          2h
kube-system   calico-etcd-22cw7                          1/1       Running            0          22h
kube-system   calico-kube-controllers-559b575f97-z5zv8   1/1       Running            0          22h
kube-system   calico-node-4j2bk                          2/2       Running            46         22h
kube-system   calico-node-s9jpk                          2/2       Running            45         22h
kube-system   calico-node-zwrxq                          2/2       Running            0          22h
kube-system   etcd-master                                1/1       Running            0          22h
kube-system   kube-apiserver-master                      1/1       Running            0          22h
kube-system   kube-controller-manager-master             1/1       Running            0          22h
kube-system   kube-dns-6f4fd4bdf-c2q5q                   3/3       Running            0          22h
kube-system   kube-proxy-7n6zb                           1/1       Running            0          22h
kube-system   kube-proxy-s2tgf                           1/1       Running            0          22h
kube-system   kube-proxy-wd9q5                           1/1       Running            0          22h
kube-system   kube-scheduler-master                      1/1       Running            0          22h

 **kubectl get nodes**
NAME      STATUS     ROLES     AGE       VERSION
master    Ready      master    23h       v1.9.4
worker1   NotReady   <none>    22h       v1.9.4
worker2   NotReady   <none>    22h       v1.9.4

## Steps to Reproduce (for bugs)
1.Bring up 3 nodes in a AWS VPC spread across 3 subnets in different availbity zones. Attaching cloudformation template.
2. Allow IPIP and BGP ports. disable src/dest checks on EC2 instances.  Create an IPinIP pool using calicoctl on the calico cidr (192.168.0.0/16) following this (https://docs.projectcalico.org/v3.0/reference/public-cloud/aws)
3. Deploy kubernetes using kubeadm. 1 master. 2 workers following this guide (https://kubernetes.io/docs/setup/independent/create-cluster-kubeadm/)

## Context
My kubernetes deployments are also stuck. Not sure if this networking issue is causing that.

## Your Environment

* calicoctl version (e.g. `calicoctl version`):  v2.0.1
* confd v1.0.2
BIRD version v0.3.2+birdv1.6.3
libnetwork-plugin: v1.1.0
calico-bgp-daemon: v0.2.1

Felix:
Version:            3.0.3
Full git commit ID: 21894138c411bafe8f7fa419fd5a5b9b4163d056
Build date:         2018-02-23T23:25:56+0000

* Orchestrator: Kubernetes v1.9.4
 * Operating System and version: CentOS Linux release 7.4.1708 (Core), Kernel: 3.10.0-693.11.6.el7.x86_64

**Comment by caseydavenport** [comment]
@haashah interesting, I'd expect the "unreachable" route to point to tunl0. Could you check to see if a `tunl0` device exists on the node? What does the output of `ip link` show?

You should be able to check logs on that node using `docker logs` once you find the correct container. There might be something in the BIRD logs which indicates why it's coming in as unreachable.

**Comment by haashah** [comment]
@caseydavenport following is what I found on the node:

 **ifconfig tunl0**
tunl0: flags=193<UP,RUNNING,NOARP>  mtu 1440
        inet 192.168.235.128  netmask 255.255.255.255
        tunnel   txqueuelen 1  (IPIP Tunnel)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

** ip link show **
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN mode DEFAULT qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 9001 qdisc mq state UP mode DEFAULT qlen 1000
    link/ether 02:5a:83:9f:e9:1c brd ff:ff:ff:ff:ff:ff
3: docker0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN mode DEFAULT 
    link/ether 02:42:87:c9:78:93 brd ff:ff:ff:ff:ff:ff
4: tunl0@NONE: <NOARP,UP,LOWER_UP> mtu 1440 qdisc noqueue state UNKNOWN mode DEFAULT qlen 1
    link/ipip 0.0.0.0 brd 0.0.0.0
9: cali70620a858ec@if4: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP mode DEFAULT 
    link/ether ee:ee:ee:ee:ee:ee brd ff:ff:ff:ff:ff:ff link-netnsid 0
10: cali8288b14d440@if4: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc n

** docker logs **

2018-03-17 07:49:41.815 [INFO][64] health.go 150: Overall health summary=&health.HealthReport{Live:true, Ready:true}
2018-03-17 07:49:42.675 [INFO][64] health.go 150: Overall health summary=&health.HealthReport{Live:true, Ready:true}
2018-03-17 07:49:49.844 [INFO][64] int_dataplane.go 690: Applying dataplane updates
2018-03-17 07:49:49.844 [INFO][64] ipsets.go 222: Asked to resync with the dataplane on next update. family="inet"
2018-03-17 07:49:49.844 [INFO][64] ipsets.go 253: Resyncing ipsets with dataplane. family="inet"
2018-03-17 07:49:49.845 [INFO][64] ipsets.go 295: Finished resync family="inet" numInconsistenciesFound=0 resyncDuration=1.002169ms
2018-03-17 07:49:49.845 [INFO][64] int_dataplane.go 704: Finished applying updates to dataplane. msecToApply=1.199621
2018-03-17 07:49:51.824 [INFO][64] health.go 150: Overall health summary=&health.HealthReport{Live:true, Ready:true}
2018-03-17 07:49:52.631 [INFO][64] health.go 150: Overall health summary=&health.HealthReport{Live:true, Ready:true}
bird: Mesh_10_1_2_95: Error: Hold timer expired
bird: Mesh_10_1_2_95: State changed to stop
bird: Next hop address 10.1.3.119 resolvable through recursive route for 10.1.3.0/24
bird: Mesh_10_1_2_95: State changed to down
bird: Mesh_10_1_2_95: Starting
bird: Mesh_10_1_2_95: State changed to start
2018-03-17 07:49:59.751 [INFO][64] int_dataplane.go 573: Received *proto.ActiveProfileUpdate update from calculation graph msg=id:<name:"kns.default" > 
profile:<inbound_rules:<action:"allow" rule_id:"aBMQCbsUMESPKGRp" > outbound_rules:<action:"allow" rule_id:"8iYOzpfn3SU3eATK" > > 
2018-03-17 07:49:59.752 [INFO][64] table.go 398: Queueing update of chain. chainName="cali-pri-kns.default" ipVersion=0x4 table="filter"
2018-03-17 07:49:59.752 [INFO][64] table.go 717: Invalidating dataplane cache ipVersion=0x4 reason="chain update" table="filter"
2018-03-17 07:49:59.752 [INFO][64] table.go 398: Queueing update of chain. chainName="cali-pro-kns.default" ipVersion=0x4 table="filter"
2018-03-17 07:49:59.752 [INFO][64] int_dataplane.go 690: Applying dataplane updates
2018-03-17 07:49:59.763 [INFO][64] table.go 438: Loading current iptables state and checking it is correct. ipVersion=0x4 table="filter"
2018-03-17 07:49:59.800 [INFO][64] int_dataplane.go 704: Finished applying updates to dataplane. msecToApply=47.773943
2018-03-17 07:50:00.425 [INFO][64] int_dataplane.go 690: Applying dataplane updates
2018-03-17 07:50:00.425 [INFO][64] ipsets.go 222: Asked to resync with the dataplane on next update. family="inet"
2018-03-17 07:50:00.425 [INFO][64] ipsets.go 253: Resyncing ipsets with dataplane. family="inet"

**Comment by caseydavenport** [comment]
Sorry for the long delay on this, @haashah did you ever figure out what was going on?

My guess is that this has to do with routing configuration on the node somehow, and a failure to recursively resolve some routes.
