### ISSUE TITLE
calico-node keeps restart as error

### ISSUE THREAD

**Issue by Davidrjx** [projectcalico/calico#1806]
## Expected Behavior

calico-node runs on all nodes normally as well

## Current Behavior

Hi. I'm using kubernetes 1.9.0 and trying to make cluster with calico 2.6.8.
but when I run kubeadm join on other machine, it keeps failing on running calico-node pod with CrashLoopBackOff status.
The first container (install-cni) of pod seems running well, and second container (calico-node) fails with following messages:

$ kubectl logs calico-node-***** -n kube-system
Skipping datastore connection test
ERROR: Unable to access datastore to query node configuration
Terminating
Calico node failed to start
What am I doing wrong?

## Possible Solution

nothing

## Steps to Reproduce (for bugs)

1. kubeadm create a cluster with three nodes (one as master)
2. kubeadm join third node but it keeps failed as calico-node error above

## Your Environment

* Calico version 
2.6.8
* Orchestrator version (e.g. kubernetes, mesos, rkt):
k8s 1.9.0
docker-ce 17.03.2
kubeadm 1.9.0
* Operating System and version:
debian stretch9 amd64
* Link to your project (optional):

**Comment by tmjd** [comment]
Could you please provide a link to the manifest you are using?  Also please let us know what datastore you are using for Calico (etcd or kubernetes datastore).
Is this error happening on either node that is not the master? In your reproduction steps you indicate that the error is happening on your 3rd node, does that mean on your 2nd node that calico was able to start?

My guess from the information you've given is that you are using the "Standard Hosted" manifest (from https://docs.projectcalico.org/v2.6/getting-started/kubernetes/installation/hosted/hosted) which does not start up its own etcd and instead tries to connect to one at 127.0.0.1 by default which I'm guessing will work on your master node since I believe that is where kubeadm starts the etcd for kubernetes but restricts that etcd to only listen for local traffic.  Again this is just a guess based on the information you've given.

To troubleshoot this I'd suggest jumping on the node(s) where calico-node is failing and attempt to connect to the datastore using curl and see if you are able to connect.

**Comment by Davidrjx** [comment]
Hi, @tmjd , thanks for your reply. 
Currently i changed my solution for deploying k8s HA and  mainly referred to https://github.com/cookeem/kubeadm-ha/blob/master/README.md where about **deploy independent etcd cluster** section. and i choosed an etcd cluster as datastore.

Similar to the previous case ,now i already have three masters working normally but once a worker node added , its calico-node creation faild(initially 2/3) as readness/liveness https://work_node_ip:9099/ connection refused in corresponding  events log. Except worker node, master nodes' canal pods were ok.

About your guess, seems right especially for your saying about restricts that etcd to only listen for local traffic but i can not be sure.

**Comment by tmjd** [comment]
In your new setup what do the calico-node logs report?  If readiness/liveness checks are failing I'd expect to see some kind of error in those logs.

**Comment by Davidrjx** [comment]
@tmjd now, through thoughts adaption and changes made, worker nodes and the other two masters were ok but one master's calico-node logged some warnings like 
```
bird: Unable to open configuration file /etc/calico/confd/config/bird.cfg: No such file or directory
2018-04-01 05:27:56.607 [WARNING][44831] syncer.go 257: Failed to get Ready key from etcd error=100: Key not found (/calico/v1/Ready) [12]
```
but the master's calico-node kept running status though (1/2) as ready

**Comment by tmjd** [comment]
Could you share the output of `kubectl -n kube-system describe pod <calico-node>`? Do those warnings continue to be output or were they temporary?

**Comment by caseydavenport** [comment]
I'm going to close this due to inactivity. Please shout if there are still issues!

**Comment by coderdba** [comment]
Hi, This is happening with kube 1.13.1 and calico 3.4.0.

# kubectl describe pod -n kube-system calico-node-j6zg8  
Name:               calico-node-j6zg8
Namespace:          kube-system
Priority:           0
PriorityClassName:  <none>
Node:               kc0/192.168.11.110
Start Time:         Mon, 24 Dec 2018 14:15:39 +0530
Labels:             controller-revision-hash=7fc67c7f96
                    k8s-app=calico-node
                    pod-template-generation=1
Annotations:        scheduler.alpha.kubernetes.io/critical-pod: 
Status:             Running
IP:                 192.168.11.110
Controlled By:      DaemonSet/calico-node
Init Containers:
  install-cni:
    Container ID:  docker://8c875a229caaea072c4574762e8d8c85e17174ade804aeefecccf42917764510
    Image:         quay.io/calico/cni:v3.4.0
    Image ID:      docker-pullable://quay.io/calico/cni@sha256:526f0c585f66fc70d79062463d78a324f053c406b69a600fc282c2aaa74c4428
    Port:          <none>
    Host Port:     <none>
    Command:
      /install-cni.sh
    State:          Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Mon, 24 Dec 2018 14:16:15 +0530
      Finished:     Mon, 24 Dec 2018 14:16:16 +0530
    Ready:          True
    Restart Count:  0
    Environment:
      CNI_CONF_NAME:       10-calico.conflist
      CNI_NETWORK_CONFIG:  <set to the key 'cni_network_config' of config map 'calico-config'>  Optional: false
      ETCD_ENDPOINTS:      <set to the key 'etcd_endpoints' of config map 'calico-config'>      Optional: false
      CNI_MTU:             <set to the key 'veth_mtu' of config map 'calico-config'>            Optional: false
      SLEEP:               false
    Mounts:
      /calico-secrets from etcd-certs (rw)
      /host/etc/cni/net.d from cni-net-dir (rw)
      /host/opt/cni/bin from cni-bin-dir (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from calico-node-token-s8j6t (ro)
Containers:
  calico-node:
    Container ID:   docker://19b953a96b1b83a90e0490c5d6b1d2736621bedb70d1846c859f9aa9d2034470
    Image:          quay.io/calico/node:v3.4.0
    Image ID:       docker-pullable://quay.io/calico/node@sha256:264d7de573a956f8914de93fbade66bdc7fd86f22a8f4e9a99ebdbb9e45b66f7
    Port:           <none>
    Host Port:      <none>
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Mon, 24 Dec 2018 14:33:57 +0530
      Finished:     Mon, 24 Dec 2018 14:35:06 +0530
    Ready:          False
    Restart Count:  8
    Requests:
      cpu:      250m
    Liveness:   http-get http://localhost:9099/liveness delay=10s timeout=1s period=10s #success=1 #failure=6
    Readiness:  exec [/bin/calico-node -bird-ready -felix-ready] delay=0s timeout=1s period=10s #success=1 #failure=3
    Environment:
      ETCD_ENDPOINTS:                     <set to the key 'etcd_endpoints' of config map 'calico-config'>  Optional: false
      ETCD_CA_CERT_FILE:                  <set to the key 'etcd_ca' of config map 'calico-config'>         Optional: false
      ETCD_KEY_FILE:                      <set to the key 'etcd_key' of config map 'calico-config'>        Optional: false
      ETCD_CERT_FILE:                     <set to the key 'etcd_cert' of config map 'calico-config'>       Optional: false
      CALICO_K8S_NODE_REF:                 (v1:spec.nodeName)
      CALICO_NETWORKING_BACKEND:          <set to the key 'calico_backend' of config map 'calico-config'>  Optional: false
      CLUSTER_TYPE:                       k8s,bgp
      IP:                                 autodetect
      CALICO_IPV4POOL_IPIP:               Always
      FELIX_IPINIPMTU:                    <set to the key 'veth_mtu' of config map 'calico-config'>  Optional: false
      CALICO_IPV4POOL_CIDR:               192.168.0.0/16
      CALICO_DISABLE_FILE_LOGGING:        true
      FELIX_DEFAULTENDPOINTTOHOSTACTION:  ACCEPT
      FELIX_IPV6SUPPORT:                  false
      FELIX_LOGSEVERITYSCREEN:            info
      FELIX_HEALTHENABLED:                true
    Mounts:
      /calico-secrets from etcd-certs (rw)
      /lib/modules from lib-modules (ro)
      /run/xtables.lock from xtables-lock (rw)
      /var/lib/calico from var-lib-calico (rw)
      /var/run/calico from var-run-calico (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from calico-node-token-s8j6t (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  lib-modules:
    Type:          HostPath (bare host directory volume)
    Path:          /lib/modules
    HostPathType:  
  var-run-calico:
    Type:          HostPath (bare host directory volume)
    Path:          /var/run/calico
    HostPathType:  
  var-lib-calico:
    Type:          HostPath (bare host directory volume)
    Path:          /var/lib/calico
    HostPathType:  
  xtables-lock:
    Type:          HostPath (bare host directory volume)
    Path:          /run/xtables.lock
    HostPathType:  FileOrCreate
  cni-bin-dir:
    Type:          HostPath (bare host directory volume)
    Path:          /opt/cni/bin
    HostPathType:  
  cni-net-dir:
    Type:          HostPath (bare host directory volume)
    Path:          /etc/cni/net.d
    HostPathType:  
  etcd-certs:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  calico-etcd-secrets
    Optional:    false
  calico-node-token-s8j6t:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  calico-node-token-s8j6t
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  beta.kubernetes.io/os=linux
Tolerations:     :NoSchedule
                 :NoExecute
                 CriticalAddonsOnly
                 node.kubernetes.io/disk-pressure:NoSchedule
                 node.kubernetes.io/memory-pressure:NoSchedule
                 node.kubernetes.io/network-unavailable:NoSchedule
                 node.kubernetes.io/not-ready:NoExecute
                 node.kubernetes.io/unreachable:NoExecute
                 node.kubernetes.io/unschedulable:NoSchedule
Events:
  Type     Reason     Age                  From               Message
  ----     ------     ----                 ----               -------
  Normal   Scheduled  23m                  default-scheduler  Successfully assigned kube-system/calico-node-j6zg8 to kc0
  Normal   Pulling    23m                  kubelet, kc0       pulling image "quay.io/calico/cni:v3.4.0"
  Normal   Pulled     22m                  kubelet, kc0       Successfully pulled image "quay.io/calico/cni:v3.4.0"
  Normal   Created    22m                  kubelet, kc0       Created container
  Normal   Started    22m                  kubelet, kc0       Started container
  Normal   Pulling    22m                  kubelet, kc0       pulling image "quay.io/calico/node:v3.4.0"
  Normal   Pulled     21m                  kubelet, kc0       Successfully pulled image "quay.io/calico/node:v3.4.0"
  Warning  Unhealthy  21m                  kubelet, kc0       Readiness probe errored: rpc error: code = Unknown desc = container not running (f8ef96a6d9389d54e88bc56c669e54a2e7ad426ebd583db00626cb68d5ab9e77)
  Normal   Created    20m (x4 over 21m)    kubelet, kc0       Created container
  Normal   Started    20m (x4 over 21m)    kubelet, kc0       Started container
  Normal   Pulled     20m (x3 over 21m)    kubelet, kc0       Container image "quay.io/calico/node:v3.4.0" already present on machine
  Warning  Unhealthy  13m (x23 over 21m)   kubelet, kc0       Readiness probe failed: calico/node is not ready: felix is not ready: Get http://localhost:9099/readiness: dial tcp [::1]:9099: connect: connection refused
  Warning  BackOff    3m6s (x55 over 21m)  kubelet, kc0       Back-off restarting failed container

Thanks

**Comment by caseydavenport** [comment]
@coderdba I think you probably are seeing something different. Please open another issue if you're having trouble, thanks!
