### ISSUE TITLE
how to modify IPPool name and CIDR

### ISSUE THREAD

**Issue by luzhongming** [projectcalico/calico#1822]
how to modify IPPool name and CIDR ?

**Comment by tmjd** [comment]
If you are trying to set the CIDR at initial deployment and using one of the Kubernetes manifests then the CIDR can be configured by changing CALICO_IPV4POOL_CIDR in the manifest before applying it. (Note: This only works on initial deployment as that variable is only used if no pool exists.)

If you are looking to change it after deployment see the bottom of https://docs.projectcalico.org/v3.0/reference/calicoctl/commands/ and use the [IP Pools Resource](https://docs.projectcalico.org/v3.0/reference/calicoctl/resources/ippool).  Though I think there may be some limitations that you cannot delete all IP Pools or maybe the default one, I'm not sure.

**Comment by caseydavenport** [comment]
There's also this doc in master which might be helpful: https://docs.projectcalico.org/master/usage/changing-ip-pools
