### ISSUE TITLE
Support arbitrary BIRD config extensions

### ISSUE THREAD

**Issue by caseydavenport** [projectcalico/calico#1824]
We've received a number of requests for adding in new BGP configuration options. It is unlikely that we'll be able to expose every BGP feature through Calico configuration, and doing so would likely introduce a lot of complexity for the majority of users who don't need these advanced configs.

As a strawman, it might be that we could expose some extension points in our BIRD templates that allow for users to mount in template files of their own which can be populated with data from the data store.

We may still want to extend the Calico data model to support some of these use-cases, but allowing arbitrary BIRD template extensions seems like it would help fill in the gaps.

Some examples where this would be relevant (I'm sure there are more too):
- https://github.com/projectcalico/calico/issues/1647
- https://github.com/projectcalico/calico/issues/1604
- https://github.com/projectcalico/calico/issues/1745
- https://github.com/projectcalico/routereflector/pull/10

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Calico version
* Orchestrator version (e.g. kubernetes, mesos, rkt):
* Operating System and version:
* Link to your project (optional):

**Comment by jpiper** [comment]
Yup, another example I have is that I disable graceful restart as when we upgrade/bounce a calico-node pod it takes ~30s for BGP to become established with our ToR with this on.

**Comment by caseydavenport** [comment]
I'm going to close this for now - I think it causes some architectural and support issues to open up this level of config.

In general, I'd much prefer to enhance the Calico data model to support appropriate use-cases.

**Comment by barryib** [comment]
@caseydavenport I think that something like this `include "/etc/bird/conf.d/*.conf";` at the bottom of `bird.conf` will help to solve to this issue.

We can have `confv4.d` for ipv4 and `confv6.d` for ipv6.

In that way, anyone could mount file or directory on `/etc/bird/conf.d/`.
