### ISSUE TITLE
Allow configuration of BGP peer source address

### ISSUE THREAD

**Issue by mdianjun** [projectcalico/calico#1829]
One node has two interfaces, eth0 and eth1.  Each interface is used to announced routes to their respective ToR. 
```
eth0: local ip 100.127.128.11, local as 65501   peer1 ip: 100.127.128.1, peer1 as: 65001
eth1: local ip 100.127.129.11, local as 65501   peer2 ip: 100.127.129.1, peer2 as: 65001
```
It's allowed to define two BGPPeers that represent peer1 and peer2. But, how to defined two bgp local ip for one node?

* Calico version 3.0.3
* Orchestrator version (e.g. kubernetes, mesos, rkt): k8s-1.9.3

**Comment by mdianjun** [comment]
Maybe the configuration file should be like this:
```
# eBGP Uplink to ISP1
protocol bgp uplink_isp1 {
        table exterior;
        debug {events, states};
        description "ISP1 Uplink";
        source address 192.168.1.2;   //HERE
        local as 65000;   //HERE
        neighbor 192.168.1.1 as 65001; //HERE
        hold time 180;
        startup hold time 180;
        connect retry time 30;
        keepalive time 60;
        start delay time 5;
        error wait time 60, 300;
        error forget time 300;
        import filter ebgp_in;
        export where proto = "ext_isp1";
}

# eBGP Uplink to ISP2
protocol bgp uplink_isp2 {
        table exterior;
        debug {events, states};
        description "ISP2 Uplink";
        source address 192.168.2.2; //HERE
        local as 65000;  //HERE
        neighbor 192.168.2.1 as 65002;  //HERE
        hold time 180;
        startup hold time 180;
        connect retry time 30;
        keepalive time 60;
        start delay time 5;
        error wait time 60, 300;
        error forget time 300;
        import filter ebgp_in;
        export where proto = "ext_isp2";
}
```

**Comment by caseydavenport** [comment]
Yes, for now this isn't possible without some changes to the templates. I know some users have made adjustments to get this working, but it requires some changes.

I believe the main thing that is missing is the ability to specify the source address for a peer.

**Comment by feellifexp** [comment]
@caseydavenport, we have similar requirements too. Can you give some more details on what kind of template changes are needed in order to get the ability to specify the source address for a peer? Does Calico support to announce routes to multiple peers now?

Thanks!

**Comment by caseydavenport** [comment]
I believe you should be able to simply remove the source address line from the template and BIRD will use the source address closest to the peer address.

**Comment by neiljerram** [comment]
> I believe you should be able to simply remove the source address line from the template and BIRD will use the source address closest to the peer address.

Yes, that is my understanding too.  Given that, I'm wondering if there are actually any cases where it is necessary to specify source address explicitly.  @feellifexp @mdianjun Do you have cases where the source address cannot be inferred from the neighbor address?

**Comment by feellifexp** [comment]
@caseydavenport @neiljerram Thanks to point out that. I think we are not aware of the specific BIRD behavior. I'll try it. Just wondering: is this behavior an implementation detail or documented?

Thanks!

**Comment by caseydavenport** [comment]
trying this out: https://github.com/projectcalico/node/pull/11

**Comment by krisiasty** [comment]
We have the same requirement, and I'm hearing from our customers that **support for dual-homed hosts connected to two different TORs is a must**. 

I suggested relatively easy solution here: https://github.com/projectcalico/confd/issues/328

That would require extending calico node object by adding option to skip rendering "source address" option in the bgp_template section (allowing bird to select source interface automatically), or extending bgppeer object by adding option to provide source ip for specific peer which could be used to override global source address.

If those additional fields are not defined, calico would behave exactly like before, which should guarantee backward compatibility.

Any chance for implementing this in the near future?

**Comment by caseydavenport** [comment]
FYI there is a feature in Calico - sourceAddress - that allows for some configuration of this: https://projectcalico.docs.tigera.io/reference/resources/bgppeer

> Specifies whether and how to configure a source address for the peerings generated by this BGPPeer resource. Default value “UseNodeIP” means to configure the node IP as the source address. “None” means not to configure a source address.

That said, it doesn't allow for using two different IPs on the same node, so think this should stay open.

**Comment by neiljerram** [comment]
> That said, it doesn't allow for using two different IPs on the same node

How not?  It was for a use case just like that (dual homing) that we added `sourceAddress: None`.

**Comment by caseydavenport** [comment]
Sorry, I meant it doesn't allow to exact specification of which IP to use for which peering, which I now see isn't actually what the original post was about! So, I think this can in fact be closed - `sourceAddress: None` allows for the dual homing that this issue is about, and `sourcceAddress: UseNodeIP` ensures a specific address :+1:

**Comment by neiljerram** [comment]
Thanks @caseydavenport
