### ISSUE TITLE
How isolate kubernetes namespaces with network policies at cluster scope  

### ISSUE THREAD

**Issue by anihak** [projectcalico/calico#1835]
Hello, 

I have a kubernetes cluster  with calico plugin for networking and network policies. I want to create network policies to autorize/deny network traffic between namespaces as I want as an  admin at cluster scope  but  prevent the user inside the namespace to list or modifie this policies. 
actually the network policies are namespaced ressources and with rbac we can only create roles that allow  the user inside a specific namespace to edit or not  the network policies  so I dont know how to performe this isolation at cluster scope so that users  inside namespaces can't list/edit the admin network policies    

* Calico version : 3.0
* Orchestrator version :  kubernetes 1.9

Best regards.

**Comment by anihak** [comment]
the problem with RBAC is that we either allow the user to edit all network policies or not . 
This is not really what i want. 
I want to let the user to define the traffic between his pods inside the namespace but don't allow him to authorize ingress traffic from other namespaces to his pods.

we create poth NetPol ( to  define traffic between pods and deny ingress traffic from other namespaces )  **inside the namespace** so if I use RBAC , the user will not be able to block traffic from between 2 pods inside his ns   

calico define also global Network policies at cluster scope. there aren't a lot of doc about them like NP.  I am testing them but I am not sure that they can perform ns isolation.  
 
My question is  :If i block traffic with GlobalNP will the user be able de allow the same traffic with NP ??

**Comment by anihak** [comment]
I have tested the scenario  where I isolate an namespace  with a Global_NP and authorize another ns to communicate with this isolated ns with a NP and i realized that the NP was able open my ns. 

should I conclude that actually with calico , we are not able to isolate an ns  with a an admin conf  at cluster scope ??

**Comment by caseydavenport** [comment]
@anihak yes, you can configure it such that only developers can use the Kubernetes NetworkPolicy API, but admins can use `calicoctl` to configure global policy.

Kubernetes NetworkPolicies have an order of 1000 in Calico. Thus, if you create global network policies using `calicoctl` with a lower order than that (say, 500) then they will take precedence.  However, you will need to explicitly deny the unwanted traffic, otherwise lower ordered policies will still be able to allow it.

**Comment by anihak** [comment]
it's clearer now.  Thank you very much.

**Comment by caseydavenport** [comment]
I've raised https://github.com/projectcalico/calico/issues/1847 for adding a walkthrough on how to do this - I think our docs are lacking in this area right now.

**Comment by pdhung** [comment]
@anihak: were you able to implement your Global_NP with calicoctl? Can you help me on how to do it please?

**Comment by invidian** [comment]
Sorry for digging old issue, but I couldn't find any more relevant issue and I'm not sure if it's worth opening new one. Somehow related to this issue, it would be nice to have an option to define let's say NetworkPolicyTemplate, which would be able to isolate set of namespaces from each other.

Example: I deploy bunch of microservices into a single namespace, which together build single application. I can deploy multiple versions or environments into separate namespaces and those workloads don't need to and should not be able to cross namespace boundary. To solve this, I have to deploy an NP per namespace. Ideally, I could deploy single NetworkPolicyTemplate (or perhaps something like this could be part of GNP), which applies to every namespace matching a given selector, which only allows traffic inside the namespace itself and not to other namespaces matching the same label.

This way, as a cluster admin (namespaces admin), I can ensure that the namespaces are isolated, but users of namespaces are still allowed to deploy their own more strict policies between the microservices.

Should I create a new issue about it?
