### ISSUE TITLE
Calico v3.0.4: The requested subnet must match the CIDR of a configured Calico IP Pool

### ISSUE THREAD

**Issue by xiaolei0125** [projectcalico/calico#1837]
try to create network with:
docker network create --driver=calico --ipam-driver=calico-ipam --subnet=192.168.8.0/24 dc
Error response from daemon: IpamDriver.RequestPool: The requested subnet must match the CIDR of a configured Calico IP Pool.

## Current Behavior
 ./calicoctl get ippool -o wide
NAME                  CIDR                       NAT     IPIPMODE   DISABLED   
default               192.168.8.0/24             false   Never      false      
default-ipv6-ippool   fd80:24e2:f998:72d6::/64   false   Never      false   

try to create network with:
docker network create --driver=calico --ipam-driver=calico-ipam --subnet=192.168.8.0/24 dc
Error response from daemon: IpamDriver.RequestPool: The requested subnet must match the CIDR of a configured Calico IP Pool.

## Steps to Reproduce (for bugs)

1.
2.

## Your Environment

* Calico version: v3.0.4
* Docker:
Client:
 Version:       18.03.0-ce
 API version:   1.37
Server:
 Engine:
  Version:      18.03.0-ce
  API version:  1.37 (minimum version 1.12)
* Operating System and version:  Ubuntu 16.04.1
* etcd version:  v3.3.1

**Comment by xiaolei0125** [comment]
it work fine with calico v2.6.5,  but  fail to create network with calico v3.0.4

**Comment by caseydavenport** [comment]
@xiaolei0125 Right now, the Calico v3.x series doesn't support docker libnetwork, so you'll need to stick with Calico v2.6 since that's the latest release that does.

There are plans to reintroduce support in a future release.

**Comment by zhoutian77** [comment]
When to support？？？
