### ISSUE TITLE
[Question] Routereflector Issues

### ISSUE THREAD

**Issue by gyliu513** [projectcalico/calico#1839]
In the 3.0 document here https://docs.projectcalico.org/v3.0/usage/routereflector/calico-routereflector#setting-up-node-specific-peering , it is said that if you are deploying a cluster of Route Reflectors, with each Calico node peering to a subset of Route Reflectors it will be necessary to set up the peerings on a node-by-node basis.

This would be the typical situation when scaling out to a very large size. For example, you may have:

- a cluster of 100 route reflectors connected in a full mesh
- a network of 100,000 Calico Docker nodes
- each Calico Docker node is connected to two or three different Route Reflectors.

For above item 3), `each Calico Docker node is connected to two or three different Route Reflectors.`, why I need to let each calico node connect to two or three different router reflectors? I suspect it is for HA function, right? This can make sure if one RR is down, another RR can take over. 

Also do I need to set mesh for all of the different router reflectors? I found that in [0.2 document](https://docs.projectcalico.org/v2.6/usage/routereflector/calico-routereflector#additional-information), I need to set full mesh, but in 0.3, there is no such requirement.
![image](https://user-images.githubusercontent.com/4461983/38298732-c3baa40e-382a-11e8-81cb-7dcf294c1bee.png)

**Comment by gyliu513** [comment]
Thanks @caseydavenport , but in 0.3 document, there is no steps for how to set up full mesh between all router reflectors at https://docs.projectcalico.org/v3.0/usage/routereflector/calico-routereflector#setting-up-node-specific-peering , can you help clarify how I can set up the full mesh?

**Comment by caseydavenport** [comment]
@gyliu513 I believe the route reflector clustering isn't yet supported by the `calico/routereflector` image that ships with Calico v3.0, which is likely why that doc changed.

However, one can create a RR cluster with pretty much any off-the-shelf BGP agent (bird, quagga, gobgp, etc) and Calico can use that cluster. It's just that the provided `calico/routereflector` image won't do it automatically.

**Comment by gyliu513** [comment]
@caseydavenport so you mean that I need to set up RR cluster without the docker image of `calico/routereflector` but have to set up the RR cluster by some binaries of latest RR release? If so, does there are any document that I can reference?

One more thing that I'm not clear is Calico 2.6 support RR cluster with docker image at [here](https://docs.projectcalico.org/v2.6/usage/routereflector/calico-routereflector#additional-information), why Calico 3.0 does not support?

**Comment by caseydavenport** [comment]
The main difference is that Calico v3 uses etcdv3, and Calico v2 uses etcdv2, and so the different routerefletor images are not compatible.

> If so, does there are any document that I can reference?

I'm afraid I'm not aware of any.

The etcdv2 RR relied on using etcdctl in order to configure clustering, and we've not carried that forward yet because it's not a supported workflow to write data into etcd directly. 

It's certainly possible to add this back in for the v3.0 RR image, but we'd like to re-think the configuration UX before we do.

I'll raise this with the team to see if we can bump the priority on adding this feature to Calico v3.0.

I've raised https://github.com/projectcalico/calico/issues/1887 to track the enhancement.

**Comment by gyliu513** [comment]
Thanks @caseydavenport , hope it can be add back to V0.3 soon, as this is very important feature for large scale cluster with calico.

We found that one RR can work well with 1000 nodes, and we are trying to enlarge the cluster to 2000+ nodes, but not sure if one RR can support such 2000+ scale well. It would be great if you can share some comments here.

@hchenxa
