### ISSUE TITLE
Document need for `iptables -P FORWARD ACCEPT` for IPVS until K8s fixes are merged

### ISSUE THREAD

**Issue by tmjd** [projectcalico/calico#1840]
Currently, when using kube-proxy in IPVS mode, for NodePorts to work (when workloads are on a host other than the host initially being connected to) it is necessary to run `iptables -P FORWARD ACCEPT` on all nodes.  The issue is raised upstream https://github.com/kubernetes/kubernetes/issues/59656 and the fix is up as this PR https://github.com/kubernetes/kubernetes/pull/62007.

## Expected Behavior
Should document the need for the above at least until the fix is in a K8s release.

## Current Behavior
Not documented.

/cc @song-jiang

**Comment by caseydavenport** [comment]
Looks like the fix was merged quite a while ago.
