### ISSUE TITLE
Document how to use Calico policy in conjunction with k8s Policy

### ISSUE THREAD

**Issue by caseydavenport** [projectcalico/calico#1847]
This is hard to figure out right now.

See here: https://github.com/projectcalico/calico/issues/1835#issuecomment-378897845

## Expected Behavior

Should have a usage guide or tutorials explaining how Calico NetworkPolicy interacts with Kubernetes NetworkPolicy, and the use cases for doing so.

## Current Behavior

No such guide.

## Possible Solution

Write one.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Calico version
* Orchestrator version (e.g. kubernetes, mesos, rkt):
* Operating System and version:
* Link to your project (optional):

**Comment by pdhung** [comment]
Do we have any progress on this?

**Comment by TimBozeman** [comment]
Bump!

**Comment by caseydavenport** [comment]
I think the docs have come a long way here. Some examples:
- https://docs.projectcalico.org/v3.8/security/kubernetes-network-policy 
- https://docs.projectcalico.org/v3.8/security/calico-network-policy
