### ISSUE TITLE
Traffic for HostedEndpoint is not blocked even when there's no GlobalNetworkPolicy allowing for that

### ISSUE THREAD

**Issue by mwieczorek** [projectcalico/calico#1858]
## Expected Behavior

Access to host endpoints will be blocked according to global network policy.

## Current Behavior

I created k8s cluster 1.9.3 (1 master, 2 nodes) on Azure using [acs-engine](https://github.com/Azure/acs-engine).
Then I used calico 3.1.0-rc1 and installed it in policy-only mode, with k8s datastore - release-v3.1.0-rc1/k8s-manifests/hosted/kubernetes-datastore/policy-only/1.7/calico.yaml

On one of k8s nodes I have pod with `hostnetwork:true` and exposed port 8090. I'd like to attach some security policies to that endpoint.

First I check if creating HostEndpoints will block all traffic (except failsafe rules). 
I created [host endpoints](https://gist.github.com/mwieczorek/6cbdc9ac827298336143fa929adf34cf) for all nodes. Everything worked as expected, f.e. traffic to k8s apiserver (port 443) was blocked.

Then I created new cluster from scratch, and first I applied [GlobalNetworkPolicy](https://gist.github.com/mwieczorek/b2605e964eb2b0b58cf90c2ebfbba4b6) which doesn't have port 8090 in ingress destination. Next I created the same host endpoints.
The traffic to port 8090 was not blocked. Even when I deleted the policy I still could access the service on port 8090.

## Steps to Reproduce (for bugs)

described above

## Context

It's my first attempt to use HostEnpoints, so maybe I'm doing something totally wrong at the beginning...
I used slack and asked about such scenario (protecting pods with hostnetwork using calico) and get advice from @ahrkrak that I can use HostEndpoints) - [slack thread](https://calicousers.slack.com/archives/C0BCA117T/p1522967986000126?thread_ts=1522961899.000317&cid=C0BCA117T)

## Your Environment

* Calico version 3.1.0-rc1
* Orchestrator version (e.g. kubernetes, mesos, rkt): kubernetes 1.9.3
* Operating System and version:
* Link to your project (optional):

**Comment by tmjd** [comment]
The only thing I can think of is you said `I created the same host endpoints`, if you used the exact same host endpoint configuration you previously used, that might be the problem because most likely your hostnames changed and therefore the names of the host endpoints would need to change too.

**Comment by mwieczorek** [comment]
I think I've changed the hosts in hostEndpoints, but maybe did some typo or something, because today I cannot recreate that. 
Sorry for bbothering
