### ISSUE TITLE
Cross build docker images

### ISSUE THREAD

**Issue by mkumatag** [projectcalico/calico#1865]
This is an umbrella Issue for cross-building all the calico docker images on host platform(e.g amd64).

- [x] [calico/go-build](https://github.com/projectcalico/go-build) - ~~https://github.com/projectcalico/go-build/pull/32~~
- [x] [calico/felix](https://github.com/projectcalico/felix) - ~~https://github.com/projectcalico/felix/pull/1746~~
- [x] [calico/typha](https://github.com/projectcalico/typha) - ~~projectcalico/typha#156~~
- [x] [calico/calicoctl](https://github.com/projectcalico/calicoctl) - ~~https://github.com/projectcalico/calicoctl/pull/1838~~
- [x] [calico/bird](https://github.com/projectcalico/bird) - ~~https://github.com/projectcalico/bird/pull/62~~
- [x] [calico/kube-controller](https://github.com/projectcalico/kube-controllers) - ~~https://github.com/projectcalico/kube-controllers/pull/251~~
- [x] [calico/gobgpd](https://github.com/projectcalico/calico-bgp-daemon) - ~~https://github.com/projectcalico/calico-bgp-daemon/pull/44~~
- [x] [calico/libnetwork-plugin](https://github.com/projectcalico/libnetwork-plugin) - ~~https://github.com/projectcalico/libnetwork-plugin/pull/176~~
- [x] [calico/confd](https://github.com/projectcalico/confd) - ~~https://github.com/projectcalico/confd/pull/106~~
- [x] [calico/cni](https://github.com/projectcalico/cni-plugin) - ~~https://github.com/projectcalico/cni-plugin/pull/516~~
- [x] [calico/routereflector](https://github.com/projectcalico/routereflector) - ~~projectcalico/routereflector#20~~
- [x] [calico/node](https://github.com/projectcalico/node)
- [x] ~~[calico/test](https://github.com/projectcalico/libcalico/blob/master/Dockerfile.calico_test) - depreceted.~~
- [ ] [calico/upgrade](https://github.com/projectcalico/calico-upgrade) - https://github.com/projectcalico/calico-upgrade/pull/40
- [ ] [docker-protobuf](https://github.com/projectcalico/docker-protobuf)

Created a separate issue to track manifest work - https://github.com/projectcalico/calico/issues/1866

Documentation PR - https://github.com/projectcalico/calico/pull/1961

**Comment by deitch** [comment]
@mkumatag a few requests:

1. Can we separate this into 2 issues with a list each? 1 for cross-build, 1 for multi-arch manifest? @caseydavenport and @fasaxc asked to make them separate PRs in each repo, and we already have several done for the first but not the second. Easier to track.
2. Can we make each item on the list a link to the repo?
3. Can we add after each item that has a PR (merged or not) a link to the PR?

Is there any way I can edit this list? I don't have edit rights on this repo.

To make life easier, here are the PRs:

* [calico/go-build](https://github.com/projectcalico/go-build/pull/26) merged
* [calico/felix](https://github.com/projectcalico/felix/pull/1703) merged
* [calico/typha](https://github.com/projectcalico/typha/pull/127) merged
* [calico/bird](https://github.com/projectcalico/bird/pull/52) merged
* calico/confd [one](https://github.com/projectcalico/confd/pull/101) and [two](https://github.com/projectcalico/confd/pull/106) still open

**Comment by deitch** [comment]
Wow, we have done a lot of work!

**Comment by deitch** [comment]
Here are the PRs for multi-arch manifest, I think all are open:

* [calico/go-build](https://github.com/projectcalico/go-build/pull/32)
* [calico/felix](https://github.com/projectcalico/felix/pull/1746)
* [calico/confd](https://github.com/projectcalico/confd/pull/101)

I would not open any more yet. We have an agreed way of doing cross-builds, which is why they are moving in at a reasonable pace. No one multi-arch has been merged in, we sort of have been using [felix](https://github.com/projectcalico/felix/pull/1746) as a test case. Once @fasaxc or @caseydavenport signs off on a final version of that one others should be quicker and easier.

**Comment by mkumatag** [comment]
> @mkumatag a few requests:
> 
> Can we separate this into 2 issues with a list each? 1 for cross-build, 1 for multi-arch manifest? 

okay, np.. I'll create a seperate issue for that..

> @caseydavenport and @fasaxc asked to make them separate PRs in each repo, and we already have several done for the first but not the second. Easier to track.
> Can we make each item on the list a link to the repo?
> Can we add after each item that has a PR (merged or not) a link to the PR?

I'll do this..
> Is there any way I can edit this list? I don't have edit rights on this repo.

Not really sure how to give you a write permission to edit same issue, I think only maintainers with enough permissions can edit others issue,
> 
> To make life easier, here are the PRs for cross-compile support:
> 
> calico/go-build merged
> calico/felix merged
> calico/typha merged
> calico/bird merged
> calico/confd one and two still open

**Comment by deitch** [comment]
For calicoctl, PR is https://github.com/projectcalico/calicoctl/pull/1838

**Comment by djlwilder** [comment]
If no one else is working on it I can do the multi arch changes for libnetwork plugin?

**Comment by deitch** [comment]
> multi arch changes for libnetwork plugin?

If you mean the cross-compile, then please. Kindly cc me on it?

Can you mark the complete ones in here?

**Comment by djlwilder** [comment]
Add support to cross-compile architectures: https://github.com/projectcalico/libnetwork-plugin/pull/176

**Comment by deitch** [comment]
@mkumatag can you please mark the complete ones as checked, and add the links for `typha` and `bird` and `libnetwork-plugin`?

**Comment by mkumatag** [comment]
> @mkumatag can you please mark the complete ones as checked, and add the links for typha and bird and libnetwork-plugin?

I have updated the links to respective github projects, I'm not checking any checkbox as none of the projects are enabled with cross-building docker images yet, correct me if I'm wrong..

**Comment by deitch** [comment]
> correct me if I'm wrong.

No, you are not. It turns out there are **3** stages to doing this:

1. Enable cross-compile
2. Use cross-compile as a default so CI _always_ builds images for all ARCHs
3. Use multi-arch manifest

**Comment by deitch** [comment]
FYI, @mkumatag based on my discussion with @fasaxc , the plan is **not** to do the following, as they are not supported in 3.x going forward:

* `libnetwork-plugin` - unsupported in favour of CNI
* `gobgpd` - contribution from outside that has not been supported

@fasaxc , did I get that right?

**Comment by fasaxc** [comment]
@deitch They're not supported for now but may be in future

**Comment by mkumatag** [comment]
> FYI, @mkumatag based on my discussion with @fasaxc , the plan is not to do the following, as they are not supported in 3.x going forward:
> 
> libnetwork-plugin - unsupported in favour of CNI
> gobgpd - contribution from outside that has not been supported
> @fasaxc , did I get that right?

@deitch @fasaxc yes they are not supported in 3.x release but these binaries are used in building `calico/node` image which will disturb the current flow of Makefile, so can we build these projects for not to disturb the flow and for future work.?

**Comment by mkumatag** [comment]
> confd and calicoctl are both done.

@deitch @fasaxc @caseydavenport as these projects are done, can we modify samaphore job to push image for all the supported archs?

**Comment by deitch** [comment]
> can we modify samaphore job to push image for all the supported archs?

We will. There are two steps here:

1. Create a PR with `make push` and `make push-all` targets. I am waiting for [this felix PR](https://github.com/projectcalico/felix/pull/1746) to be approved and merged. It is the first test case with `make push` and `make push-all`. I don't want multiple PRs on different projects doing the same thing until we agree that it is done "the right way". Once [the felix PR](https://github.com/projectcalico/felix/pull/1746) is merged in, I will open PRs for `make push` and `make push-all` for all of the other projects.
2. Create a PR with `make ci` which will incorporate all of the Semaphore activities, so that the repo encapsulates everything, rather than needing to manage tests and pushes in the repo and in Semaphore separately. This is at the request of @fasaxc .

Then, it is complete!

**Comment by deitch** [comment]
CNI PR is available [here](https://github.com/projectcalico/cni-plugin/pull/516)

**Comment by deitch** [comment]
calico-bgp-daemon is [here](https://github.com/projectcalico/calico-bgp-daemon/pull/44)

**Comment by deitch** [comment]
kube-controllers is [here](https://github.com/projectcalico/kube-controllers/pull/251)

**Comment by deitch** [comment]
@mkumatag would you please add the PRs to the list at the beginning of this PR?

**Comment by mkumatag** [comment]
@deitch you are showering with so many PRs man.! Welcome back.. :) will update it.

**Comment by deitch** [comment]
@mkumatag felix 1746 was merged. Can mark it off.

**Comment by deitch** [comment]
@mkumatag : 

* kube-controller was merged. Can mark it off.
* cni-plugin was merged, can mark it off.

**Comment by deitch** [comment]
@mkumatag for typha, please add https://github.com/projectcalico/typha/pull/156

**Comment by deitch** [comment]
@mkumatag for routereflector please add https://github.com/projectcalico/routereflector/pull/20

**Comment by deitch** [comment]
When those get merged in, we can hit `node` finally.

**Comment by caseydavenport** [comment]
I believe this is all done now, shout if there's a reason to leave this open.

**Comment by mkumatag** [comment]
I believe some of those tasks are still open:

calico/test
calico/upgrade

**Comment by caseydavenport** [comment]
Right. We can reopen to track those.

I'd suggest at least removing calico/test from that list - it's long since stopped being used AFAIK.

**Comment by jpds** [comment]
Any chance images for arm could be added? Currently only flannel and weavenet are supported CNIs on that.

**Comment by deitch** [comment]
@jpds wrote:

> Any chance images for arm could be added? Currently only flannel and weavenet are supported CNIs on that.

I don't understand. Calico has images for `arm64` for everything, including multi-arch images.

Or did you mean other earlier arm archs?

**Comment by jpds** [comment]
@deitch Yes, armv7/armhf are still a thing, a la Raspberry Pi's.

**Comment by alexcarman** [comment]
Can the arm64 images not run on a Pi 3b+?

**Comment by caseydavenport** [comment]
I think we can close this now? calico-upgrade is not really relevant here either since it is for v2.6, which doesn't have multi-arch :)

I suggest further work be raised in separate issue. Thanks for all of the hard work everyone put into this!

**Comment by mkumatag** [comment]
> I think we can close this now? calico-upgrade is not really relevant here either since it is for v2.6, which doesn't have multi-arch :)
> 
> I suggest further work be raised in separate issue. Thanks for all of the hard work everyone put into this!

Thanks for the whole support @caseydavenport @tomdee @deitch @djlwilder

**Comment by REBELinBLUE** [comment]
@alexcarman Doesn't look like it

```docker run --rm calico/cni:release-v3.7-arm64
standard_init_linux.go:207: exec user process caused "exec format error"```
