### ISSUE TITLE
Push manifest images

### ISSUE THREAD

**Issue by mkumatag** [projectcalico/calico#1866]
This is an umbrella Issue for pushing [fat manifest image](https://docs.docker.com/registry/spec/manifest-v2-2/) which will be linking to all the supported architectures images.

- [ ] calico/go-build
- [x] calico/felix
- [x] calico/typha
- [x] calico/calicoctl
- [ ] calico/bird
- [x] calico/kube-controller
- [ ] [calico/gobgpd](https://github.com/projectcalico/calico-bgp-daemon)
- [ ] calico/libnetwork-plugin
- [x] calico/confd
- [x] calico/cni
- [ ] calico/routereflector
- [x] calico/node

**Supporting PRs:**
Add manifest-tool to go-build - https://github.com/projectcalico/go-build/pull/39

**Comment by caseydavenport** [comment]
Is there anything left to do here? I think we can probably close this!
