### ISSUE TITLE
'namespaceSelector: {}' not matching all namespaces

### ISSUE THREAD

**Issue by juhtie01** [projectcalico/calico#1893]
I've installed Calico 3.1 alongside Flannel 0.10.0 as network policy controller in a K8s 1.8.10 cluster. I'm trying to allow access to `kube-dns` pod running in `kube-system` namespace from all namespaces, but can't get `namespaceSelector: {}` to match all namespaces. Access to `kube-dns` works only within the `kube-system` namespace. No default-deny policies exist in the cluster. In a GKE cluster with K8s 1.8.8 using Calico 2.6(?) as network policy provider, the network policy works as expected.

## Expected Behavior
A simple network policy such as the one below allows access to a pod from all namespaces.

```yaml
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: kube-dns
  namespace: kube-system
  labels:
    k8s-app: kube-dns
spec:
  podSelector:
    matchLabels:
      k8s-app: kube-dns
  ingress:
    - from:
      - namespaceSelector: {}
```

## Current Behavior
`kube-dns` pod can only be accessed from within the `kube-system` namespace. If I explicitly list all the namespaces with `matchLabels`, the policy works as expected, though this requires us to change the policy each time a namespace is created.

## Steps to Reproduce (for bugs)
1. Create a K8s cluster with Flannel 0.10.0 as CNI plugin and Calico-node 3.1 providing network policy controller functions.
2. Install `kube-dns` in `kube-system` namespace.
3. Apply the network policy mentioned above with `kubectl create -f kube-dns-netpol.yml`.
```bash
% kubectl create -f netpols/kube-dns-netpol.yml
networkpolicy "kube-dns" created
```
4. Try to do a DNS lookup from a pod in the `default` namespace
```bash
% kubectl -n default run busybox --rm -ti --image=busybox /bin/sh
If you don't see a command prompt, try pressing enter.
/ # nslookup google.com
Server:    10.3.0.10
Address 1: 10.3.0.10

nslookup: can't resolve 'google.com'
```
5. Try to do a DNS lookup from a pod in the `kube-system` namespace
```bash
% kubectl -n kube-system run busybox --rm -ti --image=busybox /bin/sh
If you don't see a command prompt, try pressing enter.
/ # nslookup google.com
Server:    10.3.0.10
Address 1: 10.3.0.10 kube-dns.kube-system.svc.cluster.local

Name:      google.com
Address 1: 2a00:1450:4009:80a::200e lhr35s02-in-x0e.1e100.net
Address 2: 216.58.210.46 lhr25s11-in-f46.1e100.net
```

## Context
This issue prevents us from creating sensible network policies which don't need to be updated whenever we create a new namespace.

## Your Environment
* Calico version: 3.1
* Orchestrator version (e.g. kubernetes, mesos, rkt): Kubernetes 1.8.10
* Operating System and version: Container Linux by CoreOS stable (1688.5.3)
* Link to your project (optional): n/a

**Comment by caseydavenport** [comment]
@juhtie01 thanks for raising.

I think this is a bug that was introduced in Calico v3. I'm investigating a fix now.

**Comment by juhtie01** [comment]
@caseydavenport Thank you very much!
