### ISSUE TITLE
Consolidate and tidy up troubleshooting information

### ISSUE THREAD

**Issue by lwr20** [projectcalico/calico#19]
A lot of the information in https://github.com/tigera/calico/blob/master/master/using-calico/troubleshooting/index.md is container-centric.  

For example, `calicoctl` isn't used on Openstack, and neither is `confd`.  Should this doc be here at all?  Perhaps the information contained within it would be better placed into the <Orchestrator>-Troubleshooting docs ?

**Comment by djosborne** [comment]
Oops, thought this doc was removed, but it's still there

**Comment by caseydavenport** [comment]
I don't think we want to remove this at all.

**Comment by caseydavenport** [comment]
"Usage" is the right place for troubleshooting.  If we need to make it more clear what bits are k8s vs openstack vs mesos specific, then we should do that.

**Comment by caseydavenport** [comment]
We've got a [number of open issues](https://github.com/projectcalico/calico/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20troubleshooting) tracking troubleshooting information, with a fair bit of overlap, including https://github.com/projectcalico/calico/issues/103 which I'm going to start using as the main troubleshooting issue.

I've added a point to that issue to track the concerns here.
