### ISSUE TITLE
[Question] How to migrate etcd data when migrate from node node mesh to router reflector

### ISSUE THREAD

**Issue by gyliu513** [projectcalico/calico#1903]
Hi,

I was trying to enlarge my Kubernetes cluster from 500 nodes to 1000 nodes with calico node node mesh, I want to disable node node mesh and enable router reflector with another etcd cluster.

![image](https://user-images.githubusercontent.com/4461983/38860354-98f4519c-4262-11e8-88bf-e1ab9d3ab2cd.png)

The above chart is my current status, I was using one etcd named as `etcd1` shared by both Kubernetes and all calico nodes with node node mesh.

Now I want to change the topology as below:

![image](https://user-images.githubusercontent.com/4461983/38860462-d1f3b924-4262-11e8-98b4-aa13cac372ef.png)

From above, you can see I was setting another etcd named as `etcd2` which is dedicated to the router reflector.

The problem here is do I need to migrate data from etcd1 to etcd2 for calico? My thinking is no, as when I change the calico mode from node node mesh to router reflector, I also need to restart all of the pods in the Kubernetes cluster, and after the pods restart, all of the pods network info will goes to etcd2, so there is no need to migrate data from etcd1 to etcd2, but we can just restart all pods to migrate data.

Thoughts? @caseydavenport @tmjd 

@hchenxa for your awareness.

**Comment by tmjd** [comment]
I think you could do something like that but it would not be a 'no downtime' process.  You'd essentially be re-deploying Calico one node at a time and there would be no communication between the 'old' and 'new' Calico clusters.  One thing I am not sure of is if there would be problems with the kubelet tearing down the old pods as they are restarted, I don't think it would be an issue. @caseydavenport WDYT?

I am assuming you have other reasons for wanting to use a new etcd cluster, but want to mention I don't believe it should be necessary to do this migration to switch to using route reflectors.  It should be possible to add them to the current configuration and then turn off the node-to-node mesh.

**Comment by gyliu513** [comment]
@tmjd thanks for your help always!

Regarding to we want a separate etcd, the reason is because we found that calico contributed a lot load to the shared etcd by Kubernetes and calico with node node mesh mode.

After we remove calico deployment from the cluster, we found that the etcd load was back to normal. So here we want to use a separated etcd. 

Your comment does raise another question to me, do you think most of the load of etcd are contributed by calico node to node mesh? If this is the case, I think we can still share one etcd by both Kubernetes and Calico.

**Comment by tmjd** [comment]
I would not expect the load to change much when switching to route reflectors, though TBH I am not the best person to answer a question like that, especially with the scale you are at.
@caseydavenport WDYT?

**Comment by caseydavenport** [comment]
Yeah, the load is likely not due to node-to-node mesh and instead probably due to the number of nodes in the cluster, which results in a lot of reads and a lot of writes.

The _best_ option would be to upgrade to Calico v3.0 and use etcdv3 as part of this :)

Just wanted to confirm that you don't _need_ to switch etcd in order to use route-reflectors, but I think you already know that.

As for migrating the data, it depends what it in etcd. Either way, it's not something we test so I can't guarantee any level of it working. However, if you migrate all of your policy / config to the new etcd, switch Calico to use the new etcd, and then restart all of your pods that would probably do the trick, but like @tmjd said it would involve downtime.

**Comment by gyliu513** [comment]
Thanks @caseydavenport and @tmjd for the great answer, close this now. ;-)
