### ISSUE TITLE
calico 3.1 is not work!

### ISSUE THREAD

**Issue by dahaian** [projectcalico/calico#1905]
I follow [this page](https://docs.projectcalico.org/v3.1/getting-started/kubernetes/installation/calico#installing-with-the-etcd-datastore) Installing Calico.Kubernetes API datastore—50 nodes or less.
![qq 20180417174559](https://user-images.githubusercontent.com/9957813/38862282-183c3952-4267-11e8-97a5-63046476c1e9.png)
The calico node is running.But it is not work.
The calico node pod log is:
felix-startup-1.log:
![qq 20180417175004](https://user-images.githubusercontent.com/9957813/38862534-c597a000-4267-11e8-8f9f-764aa7647106.png)
The kubernetes log is :
![qq 20180417175210](https://user-images.githubusercontent.com/9957813/38862629-fcc2ba42-4267-11e8-9348-ea6cbb76e136.png)
My kubernetes:
![qq 20180417175509](https://user-images.githubusercontent.com/9957813/38862772-65dad014-4268-11e8-901c-239ef9ae0c12.png)

Any help is appreciated.

**Comment by tmjd** [comment]
Have you made any changes to the manifest before applying it? Specifically it may cause this issue if you have set NO_DEFAULT_POOLS.

Could you give some details on what is not working? From the error I'm seeing I would guess that traffic between pods on the same host work but traffic that has to go between nodes would not work.

**Comment by dahaian** [comment]
@tmjd  First,I do not have set  NO_DEFAULT_POOLS.Then, you are right.The traffic between pods on the same host work but traffic that has to go between nodes would not work.

**Comment by tmjd** [comment]
From the manifest you provided your pods should be getting addresses in the 192.168.0.0/16 subnet but I see that your nodes are in that subnet.  I think you need to update the CALICO_IPV4POOL_CIDR in the manifest to match the cluster-cidr you are using, which from the addresses your pods have looks like it should be something like 172.30.0.0/16.

**Comment by dahaian** [comment]
@tmjd I am ensure the cluster-cidr (pod cidr), service-cidr, and the cidr used by my hosts do not overlap.
But it is still got the same error
