### ISSUE TITLE
doc is not consistent with actual behaviour

### ISSUE THREAD

**Issue by ermazi** [projectcalico/calico#1910]
official docs below:
https://docs.projectcalico.org/v3.1/reference/architecture/data-path

## Expected Behavior
as docs say
![image](https://user-images.githubusercontent.com/23275699/38914900-14412bd4-4314-11e8-9c19-7cef14da26bc.png)

## Current Behavior
![image](https://user-images.githubusercontent.com/23275699/38914882-fcd70c3e-4313-11e8-9578-2dc6daf71b3a.png)

## Possible Solution
with tunnel?

i am fresh bird, can anyone tell me the actual ip packets data path?
tks.

## Your Environment
k8s 1.10.1 in ubuntu

**Comment by caseydavenport** [comment]
@ermazi if IPIP tunneling is enabled then the routes will use the `tunl0` interface. 

If you disable IPIP tunneling, you should see the routes switch to eth0.

See here for more info: https://docs.projectcalico.org/v3.1/usage/configuration/ip-in-ip

**Comment by ermazi** [comment]
i see, tks,
