### ISSUE TITLE
calico 2.6 error

### ISSUE THREAD

**Issue by Alanthur** [projectcalico/calico#1911]
## Current Behavior
My calico got error:

`Apr 18 09:56:26 slave2 journal: E0418 16:56:26.487827       1 reflector.go:201] github.com/projectcalico/k8s-policy/pkg/controllers/namespace/namespace_controller.go:151: Failed to list *v1.Namespace: Get https://10.254.0.1:443/api/v1/namespaces?resourceVersion=0: dial tcp 10.254.0.1:443: connect: network is unreachable
Apr 18 09:56:26 slave2 journal: E0418 16:56:26.557948       1 reflector.go:201] github.com/projectcalico/k8s-policy/pkg/controllers/pod/pod_controller.go:203: Failed to list *v1.Pod: Get https://10.254.0.1:443/api/v1/pods?resourceVersion=0: dial tcp 10.254.0.1:443: connect: network is unreachable`

![qq 20180418180146](https://user-images.githubusercontent.com/9957813/38925588-a87a05aa-4332-11e8-93bc-9c4e796abcf2.png)

Any help is appreciate!
!## Your Environment

* Calico version 2.6.0
* Orchestrator version (e.g. kubernetes, mesos, rkt): kubernetes 1.8.8
* Operating System and version: centos 7

**Comment by caseydavenport** [comment]
>E0418 16:56:26.557948 1 reflector.go:201] github.com/projectcalico/k8s-policy/pkg/controllers/pod/pod_controller.go:203: Failed to list *v1.Pod: Get https://10.254.0.1:443/api/v1/pods?resourceVersion=0: dial tcp 10.254.0.1:443: connect: network is unreachable

Are you running the kube-proxy on that node? Looks like Calico is trying to reach the apiserver but that node can't reach it.

**Comment by dahaian** [comment]
@caseydavenport  My node is :
![qq 20180419090747](https://user-images.githubusercontent.com/9957813/38965767-275ebffe-43b1-11e8-90bf-93b4289d57e5.png)
slave1 :
![qq 20180419091004](https://user-images.githubusercontent.com/9957813/38965803-5d712c8a-43b1-11e8-91fa-70229ff8a8ac.png)
slave2 :
![qq 20180419091119](https://user-images.githubusercontent.com/9957813/38965828-846a960a-43b1-11e8-8d2e-5871c43893e6.png)
And pod status:

**Comment by tmjd** [comment]
You have specified 10.254.0.0 as your cluster-cidr to kubeproxy,  but it looks like 10.254.x.x is your service cidr (judging by the attempts to access the k8s-apiserver at a 10.254.0.1 address).  You should ensure the cluster-cidr (pod cidr), service-cidr, and the cidr used by your hosts do not overlap.  And the cluster-cidr should match the CALICO_IPV4POOL_CIDR in the calico manifest.

**Comment by dahaian** [comment]
@tmjd I update the calico.yaml
![qq 20180420142746](https://user-images.githubusercontent.com/9957813/39033920-ee97f3f6-44a6-11e8-98f0-c105e9c55293.png)

**Comment by dahaian** [comment]
@tmjd Hi,I run `iptables-save` and find this:
slave1:
![qq 20180423095707](https://user-images.githubusercontent.com/9957813/39103629-6347fa46-46de-11e8-83f2-9554f17323a4.png)

**Comment by tmjd** [comment]
That looks good, assuming your Kubernetes apiserver is running at 192.168.213.135 on port 6443.  Could you try doing a curl from one of your nodes to that address, it won't succeed but you should be able to tell something is listening there.
The actual line of interest is the one below the ones you've highlighted because the traffic is coming from the 172.30.0.0/16 range which the line you've highlighted is specifically not matching, if you follow the jumps you'll get to the line that does a `-j DNAT --to-destination 192.168.213.135:6443`.
