### ISSUE TITLE
Port calico to a new platform--mips64el

### ISSUE THREAD

**Issue by vans88** [projectcalico/calico#193]
**@djosborne** 
Hi djosborne, I wanna port calico to mips64el platform. But when installing github-pages, I got the following error.

**Build command from README.md file**
# Building Method

The docs require jekyll, a ruby gem. Install the `github-pages` gem which includes
`jekyll` to ensure you are using the exact version of jekyll that github pages
is using to serve the live site.

```
gem install github-pages
jekyll serve -I
```
# Build result
```
[root@dscn2 calico]# jekyll serve -I
Configuration file: /usr/local/calico/_config.yml
Configuration file: /usr/local/calico/_config.yml
            Source: /usr/local/calico
       Destination: /usr/local/calico/_site
 Incremental build: enabled
      Generating...
                    done in 265.943 seconds.
 Auto-regeneration: enabled for '/usr/local/calico'
Configuration file: /usr/local/calico/_config.yml
    Server address: http://127.0.0.1:4000/
  Server running... press ctrl-c to stop.

```

# Platfrom info

```
[root@dscn2 calico]# uname -a
Linux dscn2 4.4.21+ #3 SMP PREEMPT Wed Oct 12 09:14:23 CST 2016 mips64 mips64 mips64 GNU/Linux
[root@dscn2 calico]# cat /etc/issue
Fedora release 21 (Twenty One)
Kernel \r on an \m (\l)

[root@dscn2 calico]# ruby -v
ruby 2.1.4p265 (2014-10-27 revision 48166) [mips64el-linux]
[root@dscn2 calico]# gem -v
2.2.2
[root@dscn2 calico]# gcc -v
......  ...... 
gcc version 4.9.3 20150626 (Red Hat 4.9.3-3) (GCC)
```

# some confusions
I can not find a file named calico whose architecture is mips64el. 

```
[root@dscn2 calico]# pwd
/usr/local/calico
[root@dscn2 calico]# find . -type d -name bin
./v1.5/getting-started/mesos/demos/cni/cni/bin
./v1.6/getting-started/mesos/demos/cni/cni/bin
./_site/v1.5/getting-started/mesos/demos/cni/cni/bin
./_site/v1.6/getting-started/mesos/demos/cni/cni/bin
[root@dscn2 calico]# cd ./_site/v1.5/getting-started/mesos/demos/cni/cni/bin
[root@dscn2 bin]# ls
calico  calico-ipam
[root@dscn2 bin]# file calico-ipam
calico-ipam: ELF 64-bit LSB executable, ### x86-64, version 1 (SYSV), dynamically linked (uses shared libs), for GNU/Linux 2.6.32, BuildID[sha1]=00747fe5bcde089bb4c2f1ba7ab5348bc02ac5bf, stripped
[root@dscn2 bin]# file calico
calico: ELF 64-bit LSB executable, ### x86-64, version 1 (SYSV), dynamically linked (uses shared libs), for GNU/Linux 2.6.32, BuildID[sha1]=00747fe5bcde089bb4c2f1ba7ab5348bc02ac5bf, stripped
```

# Why 
the files calico and calico-ipam  are "x86_64" architecture, but I notice the following content  and see the **docs site** on my PC(mips64el) indeed.
`As the output states, docs should then be viewable at http://localhost:4000/`

# Could
you tell my build for calico  is successful or not, why? My calico source code is from github. https://github.com/projectcalico/calico

**Comment by djosborne** [comment]
Hey @vans88 I think you're in the wrong repository!

This repository is for documentation and demos.

If you are trying to build calico components, you'll need to locate the correct repository.

Our [Repo Structure](http://docs.projectcalico.org/v2.0/reference/repo-structure) Document is not in great shape, so reply here with what you are trying to build and I can assist further.

- If you're looking to build `calicoctl` or `calico/node`, see https://github.com/projectcalico-calico-containers
- If you're looking to build Calico's CNI binaries (called `calico` and `calico-ipam`, see https://github.com/projectcalico/calico-cni

**Comment by vans88** [comment]
yep, **@djosborne**  Many thanks for you reply.  I need to build calico compontens on my mips64el platform. such as calicoctl,calico,calico-ipam. 
Thank you, Have a good day!

**Comment by djosborne** [comment]
The `make binary` step will need a populated `vendor/` directory to build the golang binary. That seems to be failing. As per the output:
>`# To build without Docker just run "glide install -strip-vendor"`

**Comment by djosborne** [comment]
@vans88 Hoping that last message helped you through your build issues. I'm going to close out this issue. If you encounter issues in the future when building each artifact, please do your best to open an issue on the relevant repository, and someone should be able to assist you there further.

**Comment by vans88** [comment]
@djosborne  Many thanks for your reply and very agree with your point.
