### ISSUE TITLE
Kubernetes Service IP unvailable with calico as network plugin

### ISSUE THREAD

**Issue by jfpucheu** [projectcalico/calico#1934]
Kubernetes Dashboard unvailable with calico as network plugin

## Expected Behavior
using :
kubectl proxy and http://localhost:8001/api/v1/namespaces/kube-system/services/https:kubernetes-dashboard:/proxy/#!/login
or 
https://10.171.41.207/api/v1/namespaces/kube-system/services/https:kubernetes-dashboard:/proxy/#!/login

should display dashboard.

## Current Behavior

Impossible to access K8s dashboard using Calico 3.1.1 network plugin getting error
http: proxy error: context canceled

other enpoints like grafana works:

http://localhost:8001/api/v1/namespaces/kube-system/services/monitoring-grafana

## Steps to Reproduce (for bugs)
Deploy K8S cluster in 1.8.* using calico : 
  kubectl apply -f  https://docs.projectcalico.org/v3.1/getting-started/kubernetes/installation/rbac.yaml
  kubectl apply -f  https://docs.projectcalico.org/v3.1/getting-started/kubernetes/installation/hosted/calico.yaml
Deploy K8S dashboard 1.8.3:

kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/master/src/deploy/recommended/kubernetes-dashboard.yaml

try to access to your dashboard:

kubectl proxy
Starting to serve on 127.0.0.1:8001

and go to : 
http://localhost:8001/api/v1/namespaces/kube-system/services/https:kubernetes-dashboard:/proxy/

## Your Environment
* Calico version: 3.1.1
* Kubernetes v1.8.11
* CentOS 7.3 x86_64 (on openstack instance )

logs from Kube-api-server:

```
I0424 13:54:59.198802       1 wrap.go:42] GET /api/v1/namespaces/kube-system/services/https:kubernetes-dashboard:/proxy/: (5m45.131568046s) 503
goroutine 428066 [running]:
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/httplog.(*respLogger).recordStatus(0xc4215640e0, 0x1f7)
	/workspace/anago-v1.8.11-beta.0.61+1df6a8381669a6/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/httplog/httplog.go:207 +0xdd
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/httplog.(*respLogger).WriteHeader(0xc4215640e0, 0x1f7)
	/workspace/anago-v1.8.11-beta.0.61+1df6a8381669a6/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/httplog/httplog.go:186 +0x35
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/metrics.(*ResponseWriterDelegator).WriteHeader(0xc428a979b0, 0x1f7)
	/workspace/anago-v1.8.11-beta.0.61+1df6a8381669a6/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/metrics/metrics.go:204 +0x45
net/http/httputil.(*ReverseProxy).ServeHTTP(0xc429ddc1c0, 0x81a6dc0, 0xc426e0f6f8, 0xc42850fa00)
	/usr/local/go/src/net/http/httputil/reverseproxy.go:246 +0x795
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/proxy.(*UpgradeAwareHandler).ServeHTTP(0xc42b1e2e40, 0x81a6dc0, 0xc426e0f6f8, 0xc42850ef00)
	/workspace/anago-v1.8.11-beta.0.61+1df6a8381669a6/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/proxy/upgradeaware.go:231 +0x838
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/handlers.ConnectResource.func1(0x81a6dc0, 0xc426e0f6f8, 0xc42850ef00)
	/workspace/anago-v1.8.11-beta.0.61+1df6a8381669a6/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/handlers/rest.go:269 +0x5f4
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints.restfulConnectResource.func1(0xc428a97920, 0xc42b1e2840)
	/workspace/anago-v1.8.11-beta.0.61+1df6a8381669a6/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/installer.go:1106 +0xe0
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/metrics.InstrumentRouteFunc.func1(0xc428a97920, 0xc42b1e2840)
	/workspace/anago-v1.8.11-beta.0.61+1df6a8381669a6/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/metrics/metrics.go:176 +0x207
k8s.io/kubernetes/vendor/github.com/emicklei/go-restful.(*Container).dispatch(0xc420cc5b00, 0x81a6e40, 0xc4215640e0, 0xc42850ef00)
	/workspace/anago-v1.8.11-beta.0.61+1df6a8381669a6/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/emicklei/go-restful/container.go:277 +0xb8d
k8s.io/kubernetes/vendor/github.com/emicklei/go-restful.(*Container).Dispatch(0xc420cc5b00, 0x81a6e40, 0xc4215640e0, 0xc42850ef00)
	/workspace/anago-v1.8.11-beta.0.61+1df6a8381669a6/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/emicklei/go-restful/container.go:199 +0x57
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server.director.ServeHTTP(0x38dcd5b, 0xe, 0xc420cc5b00, 0xc4203bf490, 0x81a6e40, 0xc4215640e0, 0xc42850ef00)
	/workspace/anago-v1.8.11-beta.0.61+1df6a8381669a6/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/handler.go:153 +0x6e7
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server.(*director).ServeHTTP(0xc420904920, 0x81a6e40, 0xc4215640e0, 0xc42850ef00)
	<autogenerated>:69 +0x86
k8s.io/kubernetes/vendor/k8s.io/kube-aggregator/pkg/apiserver.(*proxyHandler).ServeHTTP(0xc425459d80, 0x81a6e40, 0xc4215640e0, 0xc42850ef00)
	/workspace/anago-v1.8.11-beta.0.61+1df6a8381669a6/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/kube-aggregator/pkg/apiserver/handler_proxy.go:91 +0x122
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/mux.(*pathHandler).ServeHTTP(0xc422336b00, 0x81a6e40, 0xc4215640e0, 0xc42850ef00)
	/workspace/anago-v1.8.11-beta.0.61+1df6a8381669a6/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/mux/pathrecorder.go:248 +0x3dd
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/mux.(*PathRecorderMux).ServeHTTP(0xc422871dc0, 0x81a6e40, 0xc4215640e0, 0xc42850ef00)
	/workspace/anago-v1.8.11-beta.0.61+1df6a8381669a6/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/mux/pathrecorder.go:234 +0x72
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server.director.ServeHTTP(0x38e041b, 0xf, 0xc424dbe120, 0xc422871dc0, 0x81a6e40, 0xc4215640e0, 0xc42850ef00)
	/workspace/anago-v1.8.11-beta.0.61+1df6a8381669a6/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/handler.go:161 +0x301
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server.(*director).ServeHTTP(0xc424b3ac60, 0x81a6e40, 0xc4215640e0, 0xc42850ef00)
	<autogenerated>:69 +0x86
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters.WithAuthorization.func1(0x81a6e40, 0xc4215640e0, 0xc42850ef00)
	/workspace/anago-v1.8.11-beta.0.61+1df6a8381669a6/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters/authorization.go:51 +0x37a
net/http.HandlerFunc.ServeHTTP(0xc42392b770, 0x81a6e40, 0xc4215640e0, 0xc42850ef00)
	/usr/local/go/src/net/http/server.go:1942 +0x44
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.WithMaxInFlightLimit.func1(0x81a6e40, 0xc4215640e0, 0xc42850ef00)
	/workspace/anago-v1.8.11-beta.0.61+1df6a8381669a6/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/maxinflight.go:133 +0x7b8
net/http.HandlerFunc.ServeHTTP(0xc4254d5ec0, 0x81a6e40, 0xc4215640e0, 0xc42850ef00)
	/usr/local/go/src/net/http/server.go:1942 +0x44
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters.WithImpersonation.func1(0x81a6e40, 0xc4215640e0, 0xc42850ef00)
	/workspace/anago-v1.8.11-beta.0.61+1df6a8381669a6/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters/impersonation.go:49 +0x21b2
net/http.HandlerFunc.ServeHTTP(0xc42392b9a0, 0x81a6e40, 0xc4215640e0, 0xc42850ef00)
	/usr/local/go/src/net/http/server.go:1942 +0x44
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters.WithAuthentication.func1(0x81a6e40, 0xc4215640e0, 0xc42850ef00)
	/workspace/anago-v1.8.11-beta.0.61+1df6a8381669a6/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters/authentication.go:79 +0x2b0
net/http.HandlerFunc.ServeHTTP(0xc42392b9f0, 0x81a6e40, 0xc4215640e0, 0xc42850ef00)
	/usr/local/go/src/net/http/server.go:1942 +0x44
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/request.WithRequestContext.func1(0x81a6e40, 0xc4215640e0, 0xc42850ef00)
	/workspace/anago-v1.8.11-beta.0.61+1df6a8381669a6/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/request/requestcontext.go:110 +0xef
net/http.HandlerFunc.ServeHTTP(0xc424b3ac80, 0x81a6e40, 0xc4215640e0, 0xc42850ef00)
	/usr/local/go/src/net/http/server.go:1942 +0x44
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.(*timeoutHandler).ServeHTTP(0xc424b3ad00, 0x81a6e40, 0xc4215640e0, 0xc42850ef00)
	/workspace/anago-v1.8.11-beta.0.61+1df6a8381669a6/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/timeout.go:99 +0x44c
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters.WithRequestInfo.func1(0x81a6e40, 0xc4215640e0, 0xc42850ef00)
	/workspace/anago-v1.8.11-beta.0.61+1df6a8381669a6/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters/requestinfo.go:45 +0x219
net/http.HandlerFunc.ServeHTTP(0xc4254d5f00, 0x81a6e40, 0xc4215640e0, 0xc42850ef00)
	/usr/local/go/src/net/http/server.go:1942 +0x44
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/request.WithRequestContext.func1(0x81a6e40, 0xc4215640e0, 0xc42850ef00)
	/workspace/anago-v1.8.11-beta.0.61+1df6a8381669a6/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/request/requestcontext.go:110 +0xef
net/http.HandlerFunc.ServeHTTP(0xc424b3ad20, 0x81a6e40, 0xc4215640e0, 0xc42850ef00)
	/usr/local/go/src/net/http/server.go:1942 +0x44
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.WithPanicRecovery.func1(0x81a6e40, 0xc4215640e0, 0xc42850ef00)
	/workspace/anago-v1.8.11-beta.0.61+1df6a8381669a6/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/wrap.go:41 +0x11b
net/http.HandlerFunc.ServeHTTP(0xc424b3ad40, 0x81a7b00, 0xc426e0f6e8, 0xc42850ef00)
	/usr/local/go/src/net/http/server.go:1942 +0x44
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server.(*APIServerHandler).ServeHTTP(0xc425205620, 0x81a7b00, 0xc426e0f6e8, 0xc42850ef00)
	/workspace/anago-v1.8.11-beta.0.61+1df6a8381669a6/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/handler.go:198 +0x51
net/http.serverHandler.ServeHTTP(0xc428974420, 0x81a7b00, 0xc426e0f6e8, 0xc42850ef00)
	/usr/local/go/src/net/http/server.go:2568 +0x92
net/http.initNPNRequest.ServeHTTP(0xc428354000, 0xc428974420, 0x81a7b00, 0xc426e0f6e8, 0xc42850ef00)
	/usr/local/go/src/net/http/server.go:3088 +0x93
net/http.(*initNPNRequest).ServeHTTP(0xc42576f0d0, 0x81a7b00, 0xc426e0f6e8, 0xc42850ef00)
	<autogenerated>:312 +0x74
net/http.(Handler).ServeHTTP-fm(0x81a7b00, 0xc426e0f6e8, 0xc42850ef00)
	/usr/local/go/src/net/http/h2_bundle.go:4331 +0x4d
net/http.(*http2serverConn).runHandler(0xc42a34fc00, 0xc426e0f6e8, 0xc42850ef00, 0xc425093000)
	/usr/local/go/src/net/http/h2_bundle.go:4611 +0x89
created by net/http.(*http2serverConn).processHeaders
	/usr/local/go/src/net/http/h2_bundle.go:4343 +0x4ac

logging error output: "Error: 'context canceled'\nTrying to reach: 'https://172.12.45.196:8443/'"
```
[root@kubemaster1 ~]# kubectl get pods --namespace=kube-system -o wide
NAME                                             READY     STATUS                  RESTARTS   AGE       IP               NODE
calico-kube-controllers-69c4b96854-vpf7q         1/1       Running                 0          6h        192.168.75.12    kubenode1
calico-node-6vs4l                                2/2       Running                 0          6h        192.168.75.7     kubemaster2
calico-node-dfbmj                                2/2       Running                 0          6h        192.168.75.12    kubenode1
calico-node-f26wf                                2/2       Running                 0          6h        192.168.75.10    kubenode3
calico-node-jjnnf                                2/2       Running                 0          6h        192.168.75.4     kubemaster3
calico-node-jvpzq                                2/2       Running                 0          6h        192.168.75.13    kubeingress2
calico-node-nfrxv                                2/2       Running                 0          6h        192.168.75.11    kubenode2
calico-node-v9zpf                                2/2       Running                 0          6h        192.168.75.8     kubemaster1
calico-node-zvkx2                                2/2       Running                 0          6h        192.168.75.9     kubeingress1
heapster-v1.4.2-cd799cd87-zpn2h                  4/4       Running                 0          4d        172.12.45.194    kubenode3
kube-apiserver-kubemaster1                       1/1       Running                 0          4h        192.168.75.8     kubemaster1
kube-apiserver-kubemaster2                       1/1       Running                 0          4d        192.168.75.7     kubemaster2
kube-apiserver-kubemaster3                       1/1       Running                 0          4d        192.168.75.4     kubemaster3
kube-controller-manager-kubemaster1              1/1       Running                 0          4d        192.168.75.8     kubemaster1
kube-controller-manager-kubemaster2              1/1       Running                 0          4d        192.168.75.7     kubemaster2
kube-controller-manager-kubemaster3              1/1       Running                 0          4d        192.168.75.4     kubemaster3
kube-dns-74597b66c-v4j76                         3/3       Running                 0          4d        172.12.35.65     kubenode2
kube-proxy-kubeingress1                          1/1       Running                 0          4d        192.168.75.9     kubeingress1
kube-proxy-kubeingress2                          1/1       Running                 0          4d        192.168.75.13    kubeingress2
kube-proxy-kubemaster1                           1/1       Running                 0          4d        192.168.75.8     kubemaster1
kube-proxy-kubemaster2                           1/1       Running                 0          4d        192.168.75.7     kubemaster2
kube-proxy-kubemaster3                           1/1       Running                 0          4d        192.168.75.4     kubemaster3
kube-proxy-kubenode1                             1/1       Running                 0          4d        192.168.75.12    kubenode1
kube-proxy-kubenode2                             1/1       Running                 0          4d        192.168.75.11    kubenode2
kube-proxy-kubenode3                             1/1       Running                 0          4d        192.168.75.10    kubenode3
kube-scheduler-kubemaster1                       1/1       Running                 0          4d        192.168.75.8     kubemaster1
kube-scheduler-kubemaster2                       1/1       Running                 0          4d        192.168.75.7     kubemaster2
kube-scheduler-kubemaster3                       1/1       Running                 0          4d        192.168.75.4     kubemaster3
kubernetes-dashboard-964ccbbbb-9g8sl             1/1       Running                 0          1h        172.12.45.196    kubenode3
monitoring-influxdb-grafana-v4-fccc8778d-lhd9t   2/2       Running                 0          4d        172.12.35.66     kubenode2

I suspect a bug from calico with new service type for dashboard  ( https:kubernetes-dashboard )or Missing Rbac rules because it works with flannel .

Thanks 

jeff

**Comment by caseydavenport** [comment]
@jfpucheu how did you install k8s? Do you know if you passed the `--cluster-cidr` argument to the kube-proxy?

If not, I'd recommend passing the IP range you're using for pods to that argument - without it you might see symptoms like this.

**Comment by jfpucheu** [comment]
@caseydavenport, I install it manualy, 

my kube proxy have the good cluster cidr:

- kube-proxy --kubeconfig=/etc/kubernetes/kube-proxy-config.yaml --cluster-cidr=172.12.0.0/16 --proxy-mode=iptables 1>>/var/log/kube-proxy.log 2>&1

it works with other service endpoints, the pb is only with dashboard endpoint.

Jeff

**Comment by jfpucheu** [comment]
to update i think the  come from service IP, 
From a Node i can join directly a pod but not from his service IP

```
traceroute to 172.12.1.8 (172.12.1.8), 30 hops max, 60 byte packets
 1  172.12.1.1 (172.12.1.1)  0.507 ms  0.455 ms  0.447 ms
 2  172.12.1.8 (172.12.1.8)  0.592 ms  0.594 ms  0.601 ms
[root@kubemaster1 ~]# Connection to 10.171.41.205 closed by remote host.
```


```
[root@kubemaster1 ~]# traceroute 10.254.52.61
traceroute to 10.254.52.61 (10.254.52.61), 30 hops max, 60 byte packets
 1  192.168.75.1 (192.168.75.1)  0.526 ms  0.493 ms  0.486 ms
 2  169.254.93.9 (169.254.93.9)  0.464 ms  0.459 ms  0.452 ms
 3  10.171.41.252 (10.171.41.252)  1.443 ms  1.510 ms  1.530 ms
 4  10.170.221.252 (10.170.221.252)  2.171 ms  2.163 ms  2.157 ms
 5  10.170.223.252 (10.170.223.252)  0.518 ms  0.513 ms  0.507 ms
 6  10.4.9.85 (10.4.9.85)  0.750 ms  0.519 ms  0.505 ms
 7  10.4.48.41 (10.4.48.41)  6.853 ms 10.4.182.5 (10.4.182.5)  6.858 ms 10.4.107.53 (10.4.107.53)  1.302 ms
 8  * * *
 9  * * *
10  * * *
11  * * *
```


that is the probleme....

**Comment by jfpucheu** [comment]
Hello, 
I finaly solve my issue, the problem was the MTU configuration !  for openstack the value should be 1430. And the installation doesn't indicate to change that.
It will be preferable to tell in the chapter installation to set the value and not document is in usage part !!

https://docs.projectcalico.org/v3.1/usage/configuration/mtu

Thanks all
Jeff

**Comment by tmjd** [comment]
Glad to hear you've solved it. I'm going to close this issue.

I've created #1960 to track the need for some help in getting the configuration correct.
