### ISSUE TITLE
Can not consistently get calico/node to use the right network interface

### ISSUE THREAD

**Issue by MikeSpreitzer** [projectcalico/calico#1941]
## Expected Behavior

I am following the steps in https://kubernetes.io/docs/setup/independent/high-availability/, using a separate kube etcd cluster, keepalived, and calico.  I have three machines serving as kube masters.  I am using machines that have several network interfaces.  Left to their default behavior, kubelet and calico/node choose the network interface `bond1` (whose addresses are in 169.0.0.0/8).  I hacked the kubelet config so that it chooses `bond0` (whose addresses are in 10.171.209.0/26).  I have restarted the kubelets; now `kubectl get Node` reports the proper addresses.  I have uninstalled and reinstalled Calico according to https://docs.projectcalico.org/v3.1/getting-started/kubernetes/ many times.  I tried deleting the environment variable setting `IP=autodetect` from the calico-node container in the calico-node DaemonSet.  According to https://docs.projectcalico.org/v3.1/reference/node/configuration , that should make calico/node pick up the IP address from the Node.  But no, it still used the address from `bond1`.  Then I restored the `IP=autodetect` setting and added `IP_AUTODETECTION_METHOD=can-reach=10.171.209.20`, based on the same reference doc.  Delete and re-create.  That, too, should make calico/node use `bond0`.

## Current Behavior
With no `IP` environment variable setting, calico/node chose the `bond1` address on all three masters.  With `IP=autodetect` and `IP_AUTODETECTION_METHOD=can-reach=10.171.209.20`, calico/node chose the `bond1` address on two masters and the `bond0` address on the third.

```
root@mjs-api-dal10-a:~# calicoctl get node -o wide
NAME              ASN         IPV4               IPV6   
mjs-api-dal10-a   (unknown)   169.47.255.18/28          
mjs-api-dal10-b   (unknown)   169.47.255.25/28          
mjs-api-dal10-c   (unknown)   10.171.209.62/26          

root@mjs-api-dal10-a:~# calicoctl node status
Calico process is running.

IPv4 BGP status
+---------------+-------------------+-------+----------+-------------+
| PEER ADDRESS  |     PEER TYPE     | STATE |  SINCE   |    INFO     |
+---------------+-------------------+-------+----------+-------------+
| 169.47.255.25 | node-to-node mesh | start | 03:21:39 | Connect     |
| 10.171.209.62 | node-to-node mesh | up    | 03:21:43 | Established |
+---------------+-------------------+-------+----------+-------------+

IPv6 BGP status
No IPv6 peers found.
```

I extracted the logs, with commands like
```
kubectl -n kube-system logs calico-node-hwx25 -c calico-node > cn-b.log
```

Here they are:
[cn-c.log](https://github.com/projectcalico/calico/files/1949634/cn-c.log)
[cn-b.log](https://github.com/projectcalico/calico/files/1949635/cn-b.log)
[cn-a.log](https://github.com/projectcalico/calico/files/1949636/cn-a.log)

Here is the modified calico.yaml that I most recently tried (with `.txt` tacked on so that github will take it):
[calico.yaml.txt](https://github.com/projectcalico/calico/files/1949642/calico.yaml.txt)

## Possible Solution
Sorry, I do not understand the implementation well enough to suggest a fix.

## Steps to Reproduce (for bugs)
This is no small thing.  I hope the logs provide enough evidence to diagnose the root cause.

## Context
My first bottom-line problem is that the kube-dns pod can not reach the kube apiserver.  That is, at this point in my cluster bring-up, my first and only example of a non-host-networking pod trying to open a connection to a kube Service.  I fear Service networking in my cluster is totally broken.

## Your Environment

* Calico version
```
root@mjs-api-dal10-a:~# calicoctl version
Client Version:    v3.1.1
Build date:        2018-04-19T23:45:54+0000
Git commit:        86318310
Cluster Version:   v3.1.1
Cluster Type:      kubeadm,bgp,k8s
```

* Orchestrator version (e.g. kubernetes, mesos, rkt):
```
root@mjs-api-dal10-a:~# kubectl version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.1", GitCommit:"d4ab47518836c750f9949b9e0d387f20fb92260b", GitTreeState:"clean", BuildDate:"2018-04-12T14:26:04Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.1", GitCommit:"d4ab47518836c750f9949b9e0d387f20fb92260b", GitTreeState:"clean", BuildDate:"2018-04-12T14:14:26Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

* Operating System and version: Ubuntu 16.04.4 LTS
* Link to your project (optional):

**Comment by MikeSpreitzer** [comment]
The logs show the correct address being picked at first, but later the wrong address seems to be in use.

**Comment by caseydavenport** [comment]
Yes, this is curious. The logs all seem to indicate that the correct IP address is being picked on each node, but clearly the value `calicoctl get nodes` returns doesn't match up.

cn-a has these logs showing Felix getting the right data:
```
2018-04-26 03:21:39.240 [INFO][94] int_dataplane.go 611: Received *proto.HostMetadataUpdate update from calculation graph msg=hostname:"mjs-api-dal10-a" ipv4_addr:"10.171.209.21" 
2018-04-26 03:21:39.240 [INFO][94] int_dataplane.go 611: Received *proto.HostMetadataUpdate update from calculation graph msg=hostname:"mjs-api-dal10-b" ipv4_addr:"10.171.209.30" 
2018-04-26 03:21:39.240 [INFO][94] int_dataplane.go 611: Received *proto.HostMetadataUpdate update from calculation graph msg=hostname:"mjs-api-dal10-c" ipv4_addr:"10.171.209.62"
```

cn-b has these logs showing Felix getting the right data:
```
2018-04-26 03:21:49.588 [INFO][207] int_dataplane.go 611: Received *proto.HostMetadataUpdate update from calculation graph msg=hostname:"mjs-api-dal10-a" ipv4_addr:"10.171.209.21" 
2018-04-26 03:21:49.588 [INFO][207] int_dataplane.go 611: Received *proto.HostMetadataUpdate update from calculation graph msg=hostname:"mjs-api-dal10-b" ipv4_addr:"10.171.209.30" 
2018-04-26 03:21:49.588 [INFO][207] int_dataplane.go 611: Received *proto.HostMetadataUpdate update from calculation graph msg=hostname:"mjs-api-dal10-c" ipv4_addr:"10.171.209.62"
```

cn-c has these logs, with the _wrong_ data:
```
2018-04-26 03:21:39.287 [INFO][91] int_dataplane.go 611: Received *proto.HostMetadataUpdate update from calculation graph msg=hostname:"mjs-api-dal10-b" ipv4_addr:"169.47.255.25" 
2018-04-26 03:21:39.287 [INFO][91] int_dataplane.go 611: Received *proto.HostMetadataUpdate update from calculation graph msg=hostname:"mjs-api-dal10-c" ipv4_addr:"10.171.209.62" 
2018-04-26 03:21:39.287 [INFO][91] int_dataplane.go 611: Received *proto.HostMetadataUpdate update from calculation graph msg=hostname:"mjs-api-dal10-a" ipv4_addr:"169.47.255.18"
```

So, two of the nodes seems to have the correct view of the world, but one of them doesn't. the logs from cn-c are about 10 seconds off from the other two nodes, which is also a little weird. 

Also curious and likely unrelated but maybe could be, I see several IPIP tunnel address updates in the logs. I'd not expect that value to change in normal operation - could there be something else that is modifying Calico Node resources somehow, that's both updating the IPIP tunnel address and the node's IP?

I'll keep digging around to see if there's anything else fishy here..

**Comment by MikeSpreitzer** [comment]
Now that you mention it, I do not remember whether I ran `ntp` on those machines; it is possible that b's clock was simply 10 seconds ahead.

I can not think of what else would be frobbing Calico's Node resources.  The logs recorded here were produced after the last `kubectl delete -f calico.yaml; kubectl create -f calico.yaml`, and I was doing no manual modifications of anything after that `kubectl create`.  I did not have any daemons aside from those normally running in the cluster (at the point in those bring-up instructions where they say to add networking).

**Comment by MikeSpreitzer** [comment]
OTOH, all three record the same start time --- so the later time difference is mysterious.

**Comment by MikeSpreitzer** [comment]
When I originally reported this problem, it was on a system created by an Ansible playbook I wrote based on https://docs.projectcalico.org/v3.1/getting-started/kubernetes/ .  Later I made a new playbook, based on https://docs.projectcalico.org/v3.1/getting-started/kubernetes/installation/calico --- and the problem went away.  Now the problem is back, with the new playbook.  And yes, I am running `ntp` on my machines.

**Comment by MikeSpreitzer** [comment]
```
root@mjs-api-dal10-c:~# kubectl get pod --all-namespaces -o wide
NAMESPACE     NAME                                       READY     STATUS             RESTARTS   AGE       IP               NODE
kube-system   calico-kube-controllers-5b85d756c6-bs5vv   1/1       Running            1          2h        10.171.126.204   mjs-api-dal10-f
kube-system   calico-node-4xsgw                          1/2       CrashLoopBackOff   24         1h        10.171.126.218   mjs-api-dal10-c
kube-system   calico-node-8rb65                          2/2       Running            2          3d        10.171.126.201   mjs-api-dal10-a
kube-system   calico-node-9x7mh                          1/2       CrashLoopBackOff   37         2h        10.171.126.206   mjs-api-dal10-e
kube-system   calico-node-mzfnn                          2/2       Running            2          21h       10.171.126.249   mjs-api-dal10-d
kube-system   calico-node-q4h8f                          2/2       Running            2          2h        10.171.126.204   mjs-api-dal10-f
kube-system   calico-node-zzkmd                          2/2       Running            0          3d        10.171.126.195   mjs-api-dal10-b
...
```
[caliconode-logs.zip](https://github.com/projectcalico/calico/files/1996267/caliconode-logs.zip)

**Comment by MikeSpreitzer** [comment]
```
root@mjs-api-dal10-a:~# ETCD_ENDPOINTS=https://10.171.126.244:2379 ETCD_KEY_FILE=/etc/kubernetes/pki/etcd/client-key.pem ETCD_CERT_FILE=/etc/kubernetes/pki/etcd/client.pem ETCD_CA_CERT_FILE=/etc/kubernetes/pki/etcd/ca.pem calicoctl node status
Calico process is running.

IPv4 BGP status
+---------------+-------------------+-------+----------+--------------------------------+
| PEER ADDRESS  |     PEER TYPE     | STATE |  SINCE   |              INFO              |
+---------------+-------------------+-------+----------+--------------------------------+
| 169.47.194.24 | node-to-node mesh | start | 15:47:04 | Active Socket: Connection      |
|               |                   |       |          | closed                         |
| 169.47.194.25 | node-to-node mesh | start | 15:47:04 | Active Socket: Connection      |
|               |                   |       |          | closed                         |
| 169.47.194.19 | node-to-node mesh | start | 15:47:04 | Active Socket: Connection      |
|               |                   |       |          | closed                         |
+---------------+-------------------+-------+----------+--------------------------------+

IPv6 BGP status
No IPv6 peers found.
```

**Comment by caseydavenport** [comment]
I'm going to close this for now, given its age and the fact that I haven't encountered this anywhere else and I haven't been able to reproduce it myself either...

If anyone else sees this on newer versions of Calico please chime in and we can reopen.

**Comment by MichaelMcCulloch** [comment]
I'm seeing this on the latest version of calico, you can reproduce the issue with this repo: https://github.com/MichaelMcCulloch/ScalableStellarust/tree/1067be3c6ffd2194d354870f26217e8a74f34791

**Comment by caseydavenport** [comment]
@MichaelMcCulloch this issue is quite old - can you raise a new one explaining your particular setup and symptoms?

**Comment by MichaelMcCulloch** [comment]
I'm not sure how or why, but I can no longer reproduce this issue.
