### ISSUE TITLE
calico v3.1.1 etcd v3.3.0 . k8s 1.9

### ISSUE THREAD

**Issue by peiqi-caicloud** [projectcalico/calico#1943]
I deployed calico with bin calico-cni calico-ipam on host and calico/node in a container.

but the behaviour is not as expected, I can't setup pod as indicated etcd is not specified, but I did. I am wondering if this issue is related to etcd version or something else 

<img width="1165" alt="screen shot 2018-04-26 at 4 54 53 pm" src="https://user-images.githubusercontent.com/5621794/39296144-b7699760-4972-11e8-81ad-b261ad9734c8.png">
<img width="720" alt="screen shot 2018-04-26 at 4 54 07 pm" src="https://user-images.githubusercontent.com/5621794/39296148-b92f7ccc-4972-11e8-98af-0a39be417cf8.png">

**Comment by peiqi-caicloud** [comment]
@jose-bigio @SEJeff @tomdee

**Comment by tmjd** [comment]
Can you share your Calico CNI config in `/etc/cni/net.d`? That is where Calico should be getting the etcd endpoint information.

**Comment by peiqi-caicloud** [comment]
thanks for your reply. this was caused by my bad cni config
