### ISSUE TITLE
disabling IPIP in calico ds

### ISSUE THREAD

**Issue by ajcs3** [projectcalico/calico#1976]
How to disable IPIP tunneling in calico

## Current Behavior

In the daemonset I have changed the IPIP mode from Always to off but after doing a rolling update of daemonset, still the config is reflecting the old values.

## Steps to Reproduce (for bugs)

1. Do the rolling update of the daemonset by changing the IPIP mode from Always to off
2.Recheck the daemonset yaml again
## Context

disabling IPIP in calico in k8s

## Your Environment

* Calico version 3.1.0

/kind support

**Comment by tmjd** [comment]
That variable is only for setting IPIP on the default IP Pool that is created if no other IP Pool exists.
The page for [Configuring IP-in-IP](https://docs.projectcalico.org/v3.1/usage/configuration/ip-in-ip) may be of help.
