### ISSUE TITLE
[Question]Do we have plan to package calico router reflector in helm charts

### ISSUE THREAD

**Issue by hchenxa** [projectcalico/calico#1989]
In large scale environment, calico recommend to use router reflector replace the node-to-node mesh, and currently the router reflector can be started within docker containers.

so do we have plan to package the calico router reflector in helm charts?

**Comment by caseydavenport** [comment]
@hchenxa this isn't something that's on the roadmap for the Calico team. Shouldn't stop anyone in the community from doing this if they're interested.

Note that there is an outstanding issue for packaging Calico itself as a helm chart, but it is blocked on a few things: https://github.com/projectcalico/calico/issues/717
