### ISSUE TITLE
calico ping between 2 busybox not running when used as docker plugin

### ISSUE THREAD

**Issue by vikaskedia** [projectcalico/calico#1991]
I followed the instructions at:
https://docs.projectcalico.org/v2.6/getting-started/docker/installation/manual

**Problem:**
After following all steps at the above URL I cannot ping from Busybox A to Busybox E

Since there are many steps involved I recorded a video (90 secs):
https://www.youtube.com/watch?v=wH8g3zbQyqo

Please feel free to ask for any information. If you want me to fill out the template just ask.

**Hints:**
1. It works with Docker version 17.12.1-ce, build 7390fc6
2. It does not work with Docker version 18.05.0-ce

**Comment by tmjd** [comment]
Did you ensure you met the requirements listed on https://docs.projectcalico.org/v2.6/getting-started/docker/installation/requirements, specifically the cluster-store configuration?
Did you follow the Tutorial at https://docs.projectcalico.org/v2.6/getting-started/docker/tutorials/security-using-calico-profiles for creating a network and running your docker containers?

If the answer to the above questions is yes then perhaps you can investigate by looking at the following:
* Look at the logs from the calico/node container, if you see anything suspicious please add them in a comment or provide a link to them (text format please).
* Check out `ip r` and provide that output, you should see the IP for each pod directed to it's cali* interface.

**Comment by vikaskedia** [comment]
> Did you ensure you met the requirements listed on https://docs.projectcalico.org/v2.6/getting-started/docker/installation/requirements, specifically the cluster-store configuration?

Yes

> Did you follow the Tutorial at https://docs.projectcalico.org/v2.6/getting-started/docker/tutorials/security-using-calico-profiles for creating a network and running your docker containers?

Yes

> Check out ip r and provide that output, you should see the IP for each pod directed to it's cali* interface


root@vm /g/g/c/d/calico# ip r
default via 10.0.1.1 dev ens33 proto dhcp src 10.0.1.50 metric 100 
10.0.1.0/24 dev ens33 proto kernel scope link src 10.0.1.50 
10.0.1.1 dev ens33 proto dhcp scope link src 10.0.1.50 metric 100 
172.17.0.0/16 dev docker0 proto kernel scope link src 172.17.0.1 linkdown 
192.168.141.64 dev cali2dba63b89b6 scope link 
blackhole 192.168.141.64/26 proto bird 
192.168.141.65 dev cali7d35353ece5 scope link 

> Look at the logs from the calico/node container, if you see anything suspicious please add them in a comment or provide a link to them (text format please).

Nothing catches eye. There are a lot of files in /var/log/calico. Is there any specific log file I should be looking at?

**/var/log/calico/libnetwork/current seemed important so here is the last 30 lines from that file.**

root@vm /g/g/c/d/calico# tail -n 30 -f /var/log/calico/libnetwork/current 
time="2018-05-30T10:17:29Z" level=info msg=CreateNetwork JSON="{"NetworkID":"b6722c174806880bacfbb380ceb524603d2686ae9ce3e355065b5b255b0a0538","Options":{"com.docker.network.enable_ipv6":false,"com.docker.network.generic":{}},"IPv4Data":[{"AddressSpace":"CalicoGlobalAddressSpace","Pool":"0.0.0.0/0","Gateway":"0.0.0.0/0","AuxAddresses":null}],"IPv6Data":[]}" 
time="2018-05-30T10:17:29Z" level=info msg="CreateNetwork response" JSON="{}" 
time="2018-05-30T10:18:14Z" level=info msg=RequestAddress JSON="{"PoolID":"CalicoPoolIPv4","Address":"","Options":null}" 
time="2018-05-30T10:18:14Z" level=info msg="Auto assigning IP from Calico pools" 
time="2018-05-30T10:18:14Z" level=info msg="Auto-assign 1 ipv4, 0 ipv6 addrs for host 'vm'" 
time="2018-05-30T10:18:14Z" level=info msg="Ran out of existing affine blocks for host 'vm'" 
time="2018-05-30T10:18:14Z" level=info msg="Need to allocate 1 more addresses - allocate another block" 
time="2018-05-30T10:18:14Z" level=info msg="Claiming a new affine block for host 'vm'" 
time="2018-05-30T10:18:14Z" level=info msg="Host vm claiming block affinity for 192.168.141.64/26" 
time="2018-05-30T10:18:14Z" level=info msg="Claimed new block 192.168.141.64/26 - assigning 1 addresses" 
time="2018-05-30T10:18:14Z" level=info msg="New allocation attribute: {AttrPrimary:<nil> AttrSecondary:map[]}" 
time="2018-05-30T10:18:14Z" level=info msg="Auto-assigned 1 out of 1 IPv4s: [192.168.141.64]" 
time="2018-05-30T10:18:14Z" level=info msg="RequestAddress response" JSON="{"Address":"192.168.141.64/32","Data":null}" 
time="2018-05-30T10:18:14Z" level=info msg=CreateEndpoint JSON="{"NetworkID":"b6722c174806880bacfbb380ceb524603d2686ae9ce3e355065b5b255b0a0538","EndpointID":"2dba63b89b6b1fcf2ab5f9da425359971187cc22d371ffb4ceb07498dab9f74b","Interface":{"Address":"192.168.141.64/32","AddressIPv6":"","MacAddress":""},"Options":{"com.docker.network.endpoint.exposedports":[],"com.docker.network.portmap":[]}}" 
time="2018-05-30T10:18:14Z" level=info msg="CreateEndpoint response" JSON="{"Interface":{"Address":"","AddressIPv6":"","MacAddress":"EE:EE:EE:EE:EE:EE"}}" 
time="2018-05-30T10:18:14Z" level=info msg=Join JSON="{"NetworkID":"b6722c174806880bacfbb380ceb524603d2686ae9ce3e355065b5b255b0a0538","EndpointID":"2dba63b89b6b1fcf2ab5f9da425359971187cc22d371ffb4ceb07498dab9f74b","SandboxKey":"/var/run/docker/netns/46ce1de26614","Options":{"com.docker.network.endpoint.exposedports":[],"com.docker.network.portmap":[]}}" 
time="2018-05-30T10:18:14Z" level=info msg="Join response" JSON="{"InterfaceName":{"SrcName":"temp2dba63b89b6","DstPrefix":"cali"},"Gateway":"169.254.1.1","GatewayIPv6":"fe80::f8e7:42ff:fef9:36a0","StaticRoutes":[{"Destination":"169.254.1.1/32","RouteType":1,"NextHop":""},{"Destination":"fe80::f8e7:42ff:fef9:36a0/128","RouteType":1,"NextHop":""}],"DisableGatewayService":false}" 
time="2018-05-30T10:18:14Z" level=info msg=EndpointInfo JSON="{"NetworkID":"b6722c174806880bacfbb380ceb524603d2686ae9ce3e355065b5b255b0a0538","EndpointID":"2dba63b89b6b1fcf2ab5f9da425359971187cc22d371ffb4ceb07498dab9f74b"}" 
time="2018-05-30T10:18:14Z" level=info msg=EndpointInfo JSON="{"NetworkID":"b6722c174806880bacfbb380ceb524603d2686ae9ce3e355065b5b255b0a0538","EndpointID":"2dba63b89b6b1fcf2ab5f9da425359971187cc22d371ffb4ceb07498dab9f74b"}" 
time="2018-05-30T10:18:38Z" level=info msg=RequestAddress JSON="{"PoolID":"CalicoPoolIPv4","Address":"","Options":null}" 
time="2018-05-30T10:18:38Z" level=info msg="Auto assigning IP from Calico pools" 
time="2018-05-30T10:18:38Z" level=info msg="Auto-assign 1 ipv4, 0 ipv6 addrs for host 'vm'" 
time="2018-05-30T10:18:38Z" level=info msg="Auto-assigned 1 out of 1 IPv4s: [192.168.141.65]" 
time="2018-05-30T10:18:38Z" level=info msg="RequestAddress response" JSON="{"Address":"192.168.141.65/32","Data":null}" 
time="2018-05-30T10:18:38Z" level=info msg=CreateEndpoint JSON="{"NetworkID":"b6722c174806880bacfbb380ceb524603d2686ae9ce3e355065b5b255b0a0538","EndpointID":"7d35353ece5087a9b2680739cd90e09cdac87bc9be93948acd7b5c32992ce51f","Interface":{"Address":"192.168.141.65/32","AddressIPv6":"","MacAddress":""},"Options":{"com.docker.network.endpoint.exposedports":[],"com.docker.network.portmap":[]}}" 
time="2018-05-30T10:18:38Z" level=info msg="CreateEndpoint response" JSON="{"Interface":{"Address":"","AddressIPv6":"","MacAddress":"EE:EE:EE:EE:EE:EE"}}" 
time="2018-05-30T10:18:39Z" level=info msg=Join JSON="{"NetworkID":"b6722c174806880bacfbb380ceb524603d2686ae9ce3e355065b5b255b0a0538","EndpointID":"7d35353ece5087a9b2680739cd90e09cdac87bc9be93948acd7b5c32992ce51f","SandboxKey":"/var/run/docker/netns/2fb989080257","Options":{"com.docker.network.endpoint.exposedports":[],"com.docker.network.portmap":[]}}" 
time="2018-05-30T10:18:39Z" level=info msg="Join response" JSON="{"InterfaceName":{"SrcName":"temp7d35353ece5","DstPrefix":"cali"},"Gateway":"169.254.1.1","GatewayIPv6":"fe80::b050:3eff:fe4b:f33b","StaticRoutes":[{"Destination":"169.254.1.1/32","RouteType":1,"NextHop":""},{"Destination":"fe80::b050:3eff:fe4b:f33b/128","RouteType":1,"NextHop":""}],"DisableGatewayService":false}" 
time="2018-05-30T10:18:39Z" level=info msg=EndpointInfo JSON="{"NetworkID":"b6722c174806880bacfbb380ceb524603d2686ae9ce3e355065b5b255b0a0538","EndpointID":"7d35353ece5087a9b2680739cd90e09cdac87bc9be93948acd7b5c32992ce51f"}" 
time="2018-05-30T10:18:39Z" level=info msg=EndpointInfo JSON="{"NetworkID":"b6722c174806880bacfbb380ceb524603d2686ae9ce3e355065b5b255b0a0538","EndpointID":"7d35353ece5087a9b2680739cd90e09cdac87bc9be93948acd7b5c32992ce51f"}"
