### ISSUE TITLE
Add links to blogposts describing "how people are using Calico"

### ISSUE THREAD

**Issue by ozdanborne** [projectcalico/calico#2]
Some contenders:
- http://www.tcpcloud.eu/en/blog/2016/06/27/making-openstack-production-ready-kubernetes-and-openstack-salt-part-2/
- https://clusterhq.com/2016/04/15/resilient-riak-mesos/
- https://att-innovate.github.io/torc/
- http://techblog.yahoo.co.jp/infrastructure/kubernetes_calico_networking/

**Comment by caseydavenport** [comment]
This is pretty old.  I'm also thinking that docs.projectcalico.org isn't necessarily the right place for this. WDYT?

**Comment by caseydavenport** [comment]
Assigning myself so I remember to close if we don't agree otherwise.

**Comment by caseydavenport** [comment]
Fixed by https://github.com/projectcalico/calico/pull/1821
