### ISSUE TITLE
Improve logging documentation

### ISSUE THREAD

**Issue by lwr20** [projectcalico/calico#20]
The stuff in Usage-Logging https://github.com/tigera/calico/blob/master/master/using-calico/troubleshooting/logging.md is container-centric.  

For example, in Openstack: there's no `calico-node` container, bird is not configured using calicoctl, felix log-level is not set using calicoctl, there's no confd and it doesn't use calico ipam.

Perhaps this info should move to an <orchestrator>-Logging document?

**Comment by caseydavenport** [comment]
Yeah, that page needs work.  I think it's fine to keep a "Configuring log levels" type usage page, but it needs to be clear which components are relevant for which types of deployments.

@tmjd do you want to try to tackle this one?

**Comment by tmjd** [comment]
Yeah I'll add that to my list.  I think this is a good thing because we do regularly get questions asking where do I find logs.  That may not specifically go in this page but there should maybe be a couple logging pages (configuring, viewing) and will need some orchestrator specific info too.

**Comment by caseydavenport** [comment]
The usage/logging documentation needs a few things:

- [ ] Review to make sure it's up-to-date
- [ ] Change title from "Logging" to "Configuring logging"
- [ ] Add in any missing configuration dials.

**Comment by lwr20** [comment]
Can I request that we don't lose the original spirit of this Issue and add "makes sense for all orchestrators" to the list of requirements please?
