### ISSUE TITLE
Calico bgp issue

### ISSUE THREAD

**Issue by treemanzhou** [projectcalico/calico#2002]
## Expected Behavior
I want make sure the order of the Components operation

## Current Behavior
It seems the bgp first export the route then write a blackhole route in local table , that cause a short loop in my product enviroment~ 

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Calico version ：v3.0
* Orchestrator version (e.g. kubernetes, mesos, rkt):
* Operating System and version:
* Link to your project (optional):

**Comment by tmjd** [comment]
The blackhole route is not expected to be necessary but a protection added in case there is a loop in a deployment.  Have routes been added (external to the Calico cluster) that are causing the loop?

By default we use bird to setup and distribute the routes and blackhole routes.  It would probably have to be a change to bird to ensure the blackhole is created before the CIDR route is distributed or possibly a configuration change.

**Comment by caseydavenport** [comment]
> It seems the bgp first export the route then write a blackhole route in local table , that cause a short loop in my product enviroment~

I don't understand how the blackhole route causes a routing loop, but perhaps I'm missing some crucial bit of information :)

Are you sure the symptoms you're seeing are a routing loop and not some other outage? What _are_ the symptoms you're seeing?

**Comment by caseydavenport** [comment]
Any more info on this guy?
