### ISSUE TITLE
Calico virtual interface behavior not clear

### ISSUE THREAD

**Issue by hightoxicity** [projectcalico/calico#2003]
Hi guys,

I am trying to make calico work with metallb in a bare metal deployment, currently peering with TOR (L3 level + AS per rack model), but it's not clear in calico documentation what are the type of interface used by calico, both calico and metallb are using the same virtual interface for two distinct ips and it conflicts.

Note: I use metallb with ExternalTrafficPolicy Local, not going through kube-proxy...

Connecting on the k8s node, I do:

ip n
194.187.170.11 dev cali80a929fc019  FAILED
192.168.56.115 dev ens192 lladdr 00:50:56:9f:24:c1 REACHABLE
172.20.0.1 dev ens224 lladdr 00:50:56:db:05:f4 STALE
172.22.89.104 dev cali80a929fc019 lladdr ae:b6:34:97:df:e6 PERMANENT
172.22.89.110 dev cali27acbdcf300 lladdr a6:a7:9b:40:ca:11 PERMANENT
192.168.56.254 dev ens192 lladdr 00:50:56:b7:5e:21 DELAY
172.20.0.2 dev ens224  FAILED

metallb announces 194.187.170.11 on cali80a929fc019, when calico is already announcing an ip in the pod cidr on the same virtual interface: 172.22.89.104

Thanks for your help.

**Comment by caseydavenport** [comment]
@hightoxicity I'm actually not entirely clear on what your question is. The Calico CNI plugin create virtual ethernet devices prefixed with `cali`. Each interface will be assigned an IP address and a /32 route will be created for it.

Calico should then advertise a /26 per node which includes all of the addresses assigned to pods on that node. 

BGP doesn't advertise addresses per-interface. It should be fine for both BGP agents to advertise their own addresses. However, `194.187.170.11` is not the IP address of the pod at that interface, which is probably why it shows the neighbor entry as failed.

**Comment by hightoxicity** [comment]
Thanks for your help, I think I have some issues configuring the network part, I am trying to ping a public prefix from the host in a bare metal context, I think I required support at the wrong place, sorry.

Thank you again.
