### ISSUE TITLE
Nodeport is rejected with icmp-port-unreachable

### ISSUE THREAD

**Issue by megastallman** [projectcalico/calico#2024]
## Expected Behavior
All nodeports for all services should have been open.

That is how it looks like:
```
# iptables-save | grep 31275
-A KUBE-NODEPORTS -p tcp -m comment --comment "srv1:management-port" -m tcp --dport 31275 -j KUBE-MARK-MASQ
-A KUBE-NODEPORTS -p tcp -m comment --comment "srv1:management-port" -m tcp --dport 31275 -j KUBE-SVC-VNWSL462QTZDN2GP
```

## Current Behavior
We've got a 4-node Kubernetes cluster with 2 masters(first 2 nodes). First 3 nodes are working fine, but on the 4-th random nodeports are closed and unreachable. That happens very randomly. I've checked those ports after a deployment removal, they disappear too, so there are no stuck ports on node-4.
That is how it looks like:
```
# iptables-save | grep 31218
-A KUBE-SERVICES -p tcp -m comment --comment "bad-srv:management-port has no endpoints" -m addrtype --dst-type LOCAL -m tcp --dport 31218 -j REJECT --reject-with icmp-port-unreachable
-A KUBE-NODEPORTS -p tcp -m comment --comment "bad-srv:management-port" -m tcp --dport 31218 -j KUBE-MARK-MASQ
-A KUBE-NODEPORTS -p tcp -m comment --comment "bad-srv:management-port" -m tcp --dport 31218 -j KUBE-SVC-GQKCP75KCV7PRX6J
```

## Possible Solution
Could we somehow remove the drop policy for KUBE-SERVICES as a temporary workaround? At the moment I've cordoned node-4 just to continue working without breakages.

## Steps to Reproduce (for bugs)
The service looks like the follows(both ports are broken):
```
    "ports": [
      {
        "name": "server-port",
        "protocol": "TCP",
        "port": 3004,
        "targetPort": 3004,
        "nodePort": 31197
      },
      {
        "name": "management-port",
        "protocol": "TCP",
        "port": 3104,
        "targetPort": 3104,
        "nodePort": 31218
```

## Your Environment

* Calico version v1.1.3
* Orchestrator version (e.g. kubernetes, mesos, rkt): Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.7+coreos.0", GitCommit:"c8c505ee26ac3ab4d1dff506c46bc5538bc66733", GitTreeState:"clean", BuildDate:"2017-07-06T17:38:33Z", GoVersion:"go1.7.6", Compiler:"gc", Platform:"linux/amd64"} - it is actually a kubespray deployment on top of Centos 7
* Operating System and version: CentOS Linux release 7.3.1611 (Core)

**Comment by megastallman** [comment]
And now I just don't have any endpoints. Other services have.
```
$ kubectl get endpoints bad-srv
NAME                   ENDPOINTS   AGE
bad-srv  <none>      19h
```
But why does it happen on a single node of 4?

**Comment by ozdanborne** [comment]
Node port firewalling is a bid out of  scope of Calico, but I've had some experience debugging it in openshift, so maybe I can provide some help.

- Check that kube-proxy is configured correctly on that node
- Check the kube-proxy logs
- check networkmanager

NetworkManager is run by default in CentOS and is usually to blame for most "randomly occuring" network problems, so worth seeing if that has something to do with it.

**Comment by caseydavenport** [comment]
> -A KUBE-SERVICES -p tcp -m comment --comment "bad-srv:management-port has no endpoints" -m addrtype --dst-type LOCAL -m tcp --dport 31218 -j REJECT --reject-with icmp-port-unreachable

I'm not quite following - this rule gets added when the service has no endpoints. Are you saying that there are endpoints but that this rule is still present on one node?

If so, then I don't think this is a Calico issue but probably a kube-proxy issue.

**Comment by megastallman** [comment]
Thanks everyone. Looks like it is really a kube-proxy issue. I'm going to do more investigations with  creating one more issue.
Thus NetworkManager runs at all nodes, any other configuration is the same. I've reinstalled that node, but nothing changed.
