### ISSUE TITLE
Upgrade docs don't document all the flags

### ISSUE THREAD

**Issue by lwr20** [projectcalico/calico#2027]
https://docs.projectcalico.org/v3.1/getting-started/kubernetes/upgrade/test
https://docs.projectcalico.org/v3.1/getting-started/kubernetes/upgrade/migrate

These docs don't mention the `--no-prompts` and `--ignore-v3-data` flags.  

Documenting these flags is really useful for those who are trying to integrate upgrade into an installer (like Kubespray).

**Comment by lwr20** [comment]
If its preferred to leave this "hidden" in the upgrade procedure docs, perhaps the calico-upgrade tool should get its own doc in the "Reference" section explaining in more detail?

**Comment by caseydavenport** [comment]
I think we should just update the `calico-upgrade` help text to include all the commands. We don't need a reference doc.

**Comment by caseydavenport** [comment]
Close as wont fix for now since v2.6->v3.0 upgrade is old.
