### ISSUE TITLE
calico-node > v1.0.2，docker ce 1.18.03. By default, container in a subnet can‘t ping to host and other container 

### ISSUE THREAD

**Issue by chrXiTer** [projectcalico/calico#2028]
calico-node > v1.0.2，docker ce 1.18.03. By default,  container in a subnet can‘t ping to host and other container . Even if containers in a same subnet.

docker.io 1.13 is OK.
docker.io 1.10 alse not OK

**Comment by ozdanborne** [comment]
Can you try with a more recent version of Calico, say https://docs.projectcalico.org/v2.6/releases/

If that does not work, please open a new issue and fill out the issue template.

**Comment by chrXiTer** [comment]
I am using  2.6.9，follow the page—https://docs.projectcalico.org/v2.6/getting-started/docker/installation/manual .
I will to try 2.6.10.
