### ISSUE TITLE
Rebuild calico/routereflector:v0.5.0 to fix the CVE's

### ISSUE THREAD

**Issue by mkumatag** [projectcalico/calico#2031]
Rebuild `calico/routereflector:v0.5.0` to fix the CVE's

calico/routereflector:v0.5.0 does have following high critical CVE's, can you please rebuild the packages to pick latest fixes from base ubuntu:14.04?

```
root@jupiter-vm247:~/routereflector# docker run -ti --entrypoint sh calico/routereflector:v0.5.0
#
# apt list libc6
Listing... Done
libc6/now 2.19-0ubuntu6.13 amd64 [installed,local]
# apt list sensible-utils
Listing... Done
sensible-utils/now 0.0.9 all [installed,local]
#
```

https://usn.ubuntu.com/3584-1/  - fixed in sensible-utils - 0.0.9ubuntu0.14.04.1
https://usn.ubuntu.com/3534-1/ - fixed in libc6 - 2.19-0ubuntu6.14

**Comment by mkumatag** [comment]
@caseydavenport

**Comment by caseydavenport** [comment]
@mkumatag I just built and pushed `calico/routereflector:v0.5.1` which is a rebuild of v0.5.0 and should have the latest 14.04 CVE fixes.
