### ISSUE TITLE
Terraform : created ippool are destroyed automatically

### ISSUE THREAD

**Issue by Youkoulayley** [projectcalico/calico#2033]
## Expected Behavior
I want to create an ippool with terraform (https://github.com/Cdiscount/terraform-provider-calico branch: 0.2), it is well created, but 10sec later, it gets destroyed !

So I have created an ippool with calicoctl and the ippool isn't destroyed.

## Steps to Reproduce (for bugs)
this is the terraform I execute : 
```
resource "calico_ippool" "default" {
  metadata {
    name = "${format("%s-%s-10.%s.%s", var.responsible, var.tenant_name, var.subnet_second_bits, var.subnet_last_bits)}"
  }
  spec {
    cidr = "${format("10.%s.%s/21", var.subnet_second_bits, var.subnet_last_bits)}"
    ipip_mode = "Never"
    nat_outgoing = true
    disabled = false
  }
}
```

And this is the object in the etcd : 
```
/calico/resources/v3/projectcalico.org/ippools/toto-titi-10.200.40.0
{"kind":"IPPool","apiVersion":"projectcalico.org/v3","metadata":{"name":"toto-titi-10.200.40.0","uid"
:"6e25000f-6b2a-11e8-8c1c-8cec4bef6db8","creationTimestamp":"2018-06-08T14:44:21Z"},"spec":{"cidr":"10.2
00.40.0/21","ipipMode":"Never","natOutgoing":true}}

```

I don't know why the ippool is destroyed when created by terraform.

## Your Environment

* Calico version : 3.1
* ETCD version : 3.2.17
* Orchestrator version (e.g. kubernetes, mesos, rkt): kubernetes
* Operating System and version: Debian 9.0

**Comment by tmjd** [comment]
After you create the IPPool with terraform are you able to do a `calicoctl get ippool -o yaml` and see the pool?
I'm not aware of anything that would remove an IP Pool, so I'm not sure what would be responsible for removing it.
I'm assuming you are trying to setup a new cluster, is it possible your etcd cluster is being wiped out during setup and you're losing the pool that way?

**Comment by Youkoulayley** [comment]
Yes : 
```
- apiVersion: projectcalico.org/v3
  kind: IPPool
  metadata:
    creationTimestamp: 2018-06-12T06:55:50Z
    name: archi-java-10.100.0.0
    resourceVersion: "5713592"
    uid: a4374f39-6e0d-11e8-b185-8cec4bef6db8
  spec:
    cidr: 10.100.0.0/21
    ipipMode: Never
    natOutgoing: true
```

No, the ETCD cluster is stable. And when I create the ippool with calicoctl, it works.
With the API, this works for creating an ippool ? 
```
var ctx = context.Background()
var opts = options.SetOptions{30 * time.Second}

// Convert field to string
func dToString(d *schema.ResourceData, field string) string {
	f := d.Get(field).(string)
	return f
}

// Convert field to bool
func dToBool(d *schema.ResourceData, field string) bool {
	f := d.Get(field).(bool)
	return f
}

// Convert field to IPIPMode type
func dToIpIpMode(d *schema.ResourceData, field string) api.IPIPMode {
	f := api.IPIPMode(dToString(d, field))
	return f
}

spec.CIDR = dToString(d, "spec.0.cidr")
spec.NATOutgoing = dToBool(d, "spec.0.nat_outgoing")
spec.Disabled = dToBool(d, "spec.0.disabled")
spec.IPIPMode = dToIpIpMode(d, "spec.0.ipip_mode")

ipPoolInterface.Create(ctx, ipPool, opts)
```

I am not forgetting something ?

**Comment by tmjd** [comment]
I think what you are doing should work.  The fact that using calicoctl retrieves the IP Pool means you are creating it in the datastore.

For reference, here is the code in calico/node that creates the default pool https://github.com/projectcalico/node/blob/master/pkg/startup/startup.go#L758.

The only thing I can think of to figure out what is happening is to enable debug output with etcd (or whatever appropriate log level) hoping to see where the delete for that key is coming from.

**Comment by Youkoulayley** [comment]
It was an error in my code : 
```
var opts = options.SetOptions{30 * time.Second}
```

Rookie mistake, sorry for the issue.
