### ISSUE TITLE
TestSingleRouteReflector.test_bird_single_route_reflector Test case fails on s390x

### ISSUE THREAD

**Issue by guirish** [projectcalico/calico#2037]
## Expected Behavior

Listed TC should pass on s390x , wherein workload1 should be able to ping workload2. The same TC passes on AMD64.

## Current Behavior

Ping fails from workload1 to workload2

## Steps to Reproduce (for bugs)

1.Run single TC
 ST_TO_RUN=tests/st/bgp/test_single_route_reflector.py:TestSingleRouteReflector.test_bird_single_route_reflector   make st  2>&1 | tee  TestSingleRouteReflector.test_bird_single_route_reflector

## Context

Adding TC logs for reference. 
[TestSingleRouteReflector.test_bird_single_route_reflector.log](https://github.com/projectcalico/calico/files/2094680/TestSingleRouteReflector.test_bird_single_route_reflector.log)

Adding Felix log for reference:
[felix_current.txt](https://github.com/projectcalico/calico/files/2094683/felix_current.txt)

## Your Environment

* Calico version  : v2.6.10
* Operating System and version: Ubuntu 18.04
* Architecture: s390x
* Link to your project (optional):

**Comment by fasaxc** [comment]
@guirish thanks for the report; are your team investigating the cause of the issue?

**Comment by guirish** [comment]
@fasaxc Yes, we are investigating currently but are not able to find out the root cause yet.

**Comment by guirish** [comment]
The issue was resolved by using lower version (dind-17) of calico/dind image in ST.
