### ISSUE TITLE
Delete documentation doesn't mention `node` resource

### ISSUE THREAD

**Issue by caseydavenport** [projectcalico/calico#205]
Assuming some other commands probably don't as well.

The resources listed here: http://docs.projectcalico.org/v2.0/reference/calicoctl/commands/delete

```
 Valid resource types are node, bgpPeer, hostEndpoint, workloadEndpoint,
  ipPool, policy, and profile.  The <TYPE> is case insensitive and may be
  pluralized.
```

don't include the `node` resource.

**Comment by robbrockbank** [comment]
Looks like it is already fixed.
