### ISSUE TITLE
Calico build is failing with go-build image built from source.

### ISSUE THREAD

**Issue by chakravarthy392** [projectcalico/calico#2051]
## Expected Behavior
a `yaml` binary should be created in `/go/bin` of go-build image which will be used to parse the different modules versions required to complete the Calico build.
## Current Behavior
`yaml` binary is not created and Calico build is failing as versions are not getting parsed from `calico/_data/versions.yml` file. This kind of behavior has been observed from last week.
May be this is an issue with [CLI tool for working with yaml files](https://github.com/projectcalico/go-build/blob/master/Dockerfile.amd64#L59)

## Steps to Reproduce 
1. wget https://storage.googleapis.com/golang/go1.10.1.linux-amd64.tar.gz
2. tar xf go1.10.1.linux-amd64.tar.gz
3. export GOPATH=$PWD
4. export GOROOT=$PWD/go
5. export PATH=$GOROOT/bin:$PATH
6. git clone https://github.com/projectcalico/go-build $GOPATH/src/github.com/projectcalico/go-build
7. cd $GOPATH/src/github.com/projectcalico/go-build
8. git checkout v0.9
9. make calico/go-build
10. docker tag calico/go-build:latest calico/go-build:v0.9
11. git clone https://github.com/projectcalico/calico $GOPATH/src/github.com/projectcalico/calico
12. cd $GOPATH/src/github.com/projectcalico/calico
13. git checkout v3.0.5
14. go get github.com/mikefarah/yaml
15. export PATH=$PATH:$GOPATH/bin
16. cd $GOPATH/src/github.com/projectcalico/calico/calico_node
17. make dist/calicoctl 
18. make calico/node

## Context
I was building Calico on some non-Intel architecture and observed that Calico build is failing as `yaml` binary do not exists either locally or in go-build image to parse the different modules versions which are required to complete the build.

When I have checked the same on Intel, build is passing as already pushed go-build image:v0.9 which has yaml binary in /go/bin path is getting downloaded while building calico-node.

Even though the yaml is not present locally , yaml from go-build image is being used for Intel. I have built the [go-build](https://github.com/projectcalico/go-build) image and tagged to 0.9 version and used it for Calico build and observed that build is failing on Intel also with below logs.

[Intel_build_failure.txt](https://github.com/projectcalico/calico/files/2123046/Intel_build_failure.txt)
[calicoctl_failure.txt](https://github.com/projectcalico/calico/files/2123047/calicoctl_failure.txt)

This may break Calico build on Intel also in future.
## Environment

* Calico version - v3.0.5
* Operating System and version: Intel - SUSE

**Comment by chakravarthy392** [comment]
Hi @tomdee, We tried using `go get gopkg.in/mikefarah/yq.v1` and later referred to that created *yq.v1* binary to parse components version and it worked on both Intel and non-Intel ARCH's. Any suggestions whether we could use this instead of *yaml* binary across ARCH's?

Query: As per my understanding, the *yaml* binary is used to parse the component version from versions.yml file. Does it have any other functionalities associated during build and system testing?

**Comment by tomdee** [comment]
No, I don't think it has any other purpose

**Comment by caseydavenport** [comment]
I'm going to close this since it's pretty old.
