### ISSUE TITLE
Training link broken

### ISSUE THREAD

**Issue by naveenb29** [projectcalico/calico#2053]
https://docs.projectcalico.org/tigera.io/training
## Current Behavior
404

## Steps to Reproduce (for bugs)

1. https://docs.projectcalico.org/tigera.io/training

## Your Environment

* Calico version
* Orchestrator version (e.g. kubernetes, mesos, rkt):
* Operating System and version:
* Link to your project (optional):

**Comment by caseydavenport** [comment]
I believe this is the correct URL: https://www.tigera.io/training/
