### ISSUE TITLE
No nodes listed for calicoctl & nodes in "start" state

### ISSUE THREAD

**Issue by barsaboowo** [projectcalico/calico#2055]
I have kubernetes 1.8.6 running with calico v3.1 on aws ec2 instances.  The cluster was set up using kubeadm.  Calico was installed following the install steps (etcd connection is verified, all nodes can ping each other):
https://docs.projectcalico.org/v3.1/getting-started/kubernetes/installation/calico#installing-with-the-etcd-datastore

I can deploy applications but kubernetes clusterip services are not working, either at ip level or dns level:

(from within a pod)
 nslookup kubernetes.default
;; connection timed out; no servers could be reached

However the calico pods are running without errors.  
calico-node-6txs7                                      2/2       Running   0          2h
calico-node-blpp7                                      2/2       Running   0          2h
calico-node-hrf5l                                      2/2       Running   0          2h
calico-node-tlk25                                      2/2       Running   0          2h
calico-node-zjffs                                      2/2       Running   0          2h

2018-06-26 08:21:14.658 [INFO][65] int_dataplane.go 733: Applying dataplane updates
2018-06-26 08:21:14.658 [INFO][65] ipsets.go 222: Asked to resync with the dataplane on next update. family="inet"
2018-06-26 08:21:14.658 [INFO][65] ipsets.go 253: Resyncing ipsets with dataplane. family="inet"
2018-06-26 08:21:14.659 [INFO][65] ipsets.go 295: Finished resync family="inet" numInconsistenciesFound=0 resyncDuration=1.023115ms
2018-06-26 08:21:14.659 [INFO][65] int_dataplane.go 747: Finished applying updates to dataplane. msecToApply=1.217657
2018-06-26 08:21:20.992 [INFO][65] health.go 150: Overall health summary=&health.HealthReport{Live:true, Ready:true}

Following the troubleshooting steps i get the following information:

sudo ./calicoctl node status
Calico process is running.

IPv4 BGP status
+--------------+-------------------+-------+----------+---------+
| PEER ADDRESS |     PEER TYPE     | STATE |  SINCE   |  INFO   |
+--------------+-------------------+-------+----------+---------+
| 10.244.1.1   | node-to-node mesh | start | 05:52:42 | Connect |
| 10.244.3.1   | node-to-node mesh | start | 05:52:42 | Connect |
| 10.244.4.1   | node-to-node mesh | start | 05:52:42 | Connect |
| 10.244.2.1   | node-to-node mesh | start | 05:52:42 | Connect |
+--------------+-------------------+-------+----------+---------+

IPv6 BGP status
No IPv6 peers found.

The node list is empty.
sudo ./calicoctl get nodes
NAME   

## Expected Behavior
After installing calico, kubernetes clusterip services  and dns resolution should be working.

## Your Environment

* Calico version 3.1
* Orchestrator version (e.g. kubernetes, mesos, rkt): kubernetes 1.8.6
* Operating System and version: AWS ec2 

Operating System: Red Hat Enterprise Linux Server 7.4 (Maipo)
CPE OS Name: cpe:/o:redhat:enterprise_linux:7.4:GA:server
Kernel: Linux 3.10.0-693.17.1.el7.x86_64
Architecture: x86-64

**Comment by wanghonglei5181** [comment]
have you open port 179？
