### ISSUE TITLE
In k8s, route to other node add by calico bird was deleted

### ISSUE THREAD

**Issue by chrXiTer** [projectcalico/calico#2059]
k8s version is 1.10.4
docker version is 1.13.1
calico version is 3.1.3
linux kernel route to other node add by calico bird was deleted after 1 seconds every times.

I don't know who deleted it.

**Comment by caseydavenport** [comment]
@chrXiTer Nor do I :)

Are there any other agents running on the node that might delete the route? Are the BGP sessions staying Estsablished?

I'm afraid there's not much we can do without any diagnostics.
