### ISSUE TITLE
containner can't ping each other when using bgp rr

### ISSUE THREAD

**Issue by wanghonglei5181** [projectcalico/calico#2060]
1, 4 node,1 k8s master 10.13.1.165/2 k8s node 10.13.1.66 10.13.1.167/ 1 calico bgp rr node 10.13.3.188
2,bgp config 
apiVersion: projectcalico.org/v3
kind: BGPConfiguration
metadata:
  name: default
spec:
  asNumber: 63400
  logSeverityScreen: Info
  nodeToNodeMeshEnabled: false
3,bgppeer.yaml
apiVersion: projectcalico.org/v3
kind: BGPPeer
metadata:
  name: bgppeer-global-10.13.3.188
spec:
  peerIP: 10.13.3.188
  asNumber: 63400
4,on k8s node 10.13.1.166
0> docker exec -it cd292341f8b7 /bin/bash
[root@online5-847fb5d9b4-msc72 /]# ifconfig
eth0      Link encap:Ethernet  HWaddr CE:32:79:89:19:90  
          inet addr:**192.168.2.23**  Bcast:0.0.0.0  Mask:255.255.255.255
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:96 errors:0 dropped:78 overruns:0 frame:0
          TX packets:492 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:11063 (10.8 KiB)  TX bytes:47258 (46.1 KiB)

lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:0 (0.0 b)  TX bytes:0 (0.0 b)

[root@online5-847fb5d9b4-msc72 /]# route -n
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
0.0.0.0         169.254.1.1     0.0.0.0         UG    0      0        0 eth0
169.254.1.1     0.0.0.0         255.255.255.255 UH    0      0        0 eth0
5,on k8s node 10.13.1.167
[root@online5-847fb5d9b4-lzllp /]# ifconfig
eth0      Link encap:Ethernet  HWaddr 8A:04:12:DF:36:CB  
          inet addr:**192.168.3.7**  Bcast:0.0.0.0  Mask:255.255.255.255
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:82 errors:0 dropped:82 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:10742 (10.4 KiB)  TX bytes:0 (0.0 b)

lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:0 (0.0 b)  TX bytes:0 (0.0 b)

[root@online5-847fb5d9b4-lzllp /]# route -n
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
0.0.0.0         169.254.1.1     0.0.0.0         UG    0      0        0 eth0
169.254.1.1     0.0.0.0         255.255.255.255 UH    0      0        0 eth0

6,container 192.168.2.23 can't ping container 192.168.3.7
7,help!!!!!
##  Environment

* calicoctl==3.1.3 
* kubernetes == 1.10.3
* centos==7.3 kernel>=4.10

**Comment by tmjd** [comment]
You should try putting calicoctl on one of the nodes and doing `calicoctl node status`.  That should show you if the calico BGP agent (bird) is connecting to the route reflector.
https://docs.projectcalico.org/v3.1/usage/calicoctl/install
(you don't need to configure the datastore for doing the `calicoctl node status` command.

**Comment by wanghonglei5181** [comment]
@tmjd    calicoctl node status  display Established

**Comment by wanghonglei5181** [comment]
@tmjd  now it looks like my container can't get pakage from  host

**Comment by wanghonglei5181** [comment]
# To enable Typha, set this to "calico-typha" *and* set a non-zero value for Typha replicas
  # below.  We recommend using Typha if you have more than 50 nodes. Above 100 nodes it is
  # essential.
  typha_service_name: "none"

i modify  typha_service_name to calico-typha, now i modify it to none,the cluster work well!!
!!!!!!!!!!!!!!!!!!!!!!
!
!
!
