### ISSUE TITLE
calico 3.1.3 issues bootstrapping

### ISSUE THREAD

**Issue by antoniobeyah** [projectcalico/calico#2061]
## Current Behavior

Unable to bootstrap cluster, seeing errors in the logs

```
Jul 04 17:23:20 ip-10-12-175-71 kubelet-wrapper[5951]: 2018-07-04 17:23:20.607 [INFO][12633] customresource.go 217: Error getting resource Key=ClusterInformation(default) Name="default" Resource="ClusterInformations" Revision="" error=Get https://[10.12.126.1]:443/apis/crd.projectcalico.org/v1/clusterinformations/default: unexpected EOF
```

## Possible Solution

I'm not sure if this is the problem, but there are square brackets around KUBERNETES_SERVICE_HOST which is causing the kubeconfig to be generated like:

```
apiVersion: v1
kind: Config
clusters:
- name: local
  cluster:
    server: https://[10.12.126.1]:443
```

https://github.com/projectcalico/cni-plugin/commit/48325abb1f7dc4c529533352591294964eeab933#diff-282edec51ec64b45bd3e29ddced5e78fR125

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Context

Bootstrapping a new cluster using bootkube and Calico

## Your Environment

* Calico version 3.1.3
* Orchestrator version (e.g. kubernetes, mesos, rkt): kubernetes
* Operating System and version: Container Linux by CoreOS 1745.7.0 (Rhyolite)
* Link to your project (optional):

**Comment by tmjd** [comment]
Please check that calico-node has started and is running without error.  That cluster information should be populated when it starts up.

**Comment by antoniobeyah** [comment]
we have decided to go a different direction, closing
