### ISSUE TITLE
Upgrading calico v2→v3 (Openshift)

### ISSUE THREAD

**Issue by yunithon** [projectcalico/calico#2065]
Hi all.
I would like to upgrade calico v2.5.0→v3.1 on Openshift. 
Because it is recommended by Openshift...
Can I upgrade by specifying the version(v3.1)?
There is no other way to upgrade the current version itself?

## Your Environment

 Client Version: v1.5.0
 Build date: 2017-08-22T18:38:51+0000
 Git commit: 118b8ae1
 Cluster Version: v2.5.0
 Cluster Type: origin,bgp
 Orchestrator version (e.g. kubernetes, mesos, rkt):3.7 / k8s：v1.7.6

**Comment by ozdanborne** [comment]
@yunithon If you're on a systemd-based install, you'll need to upgrade to a self-hosted install first: https://github.com/openshift/openshift-ansible/tree/master/roles/calico_master#upgrading

If you're on self-hosted, you should just need to set `calico_node_image` and the other images to v3 versions, then rerun the standard install playbook: https://github.com/openshift/openshift-ansible/blob/master/roles/calico_master/defaults/main.yaml
