### ISSUE TITLE
Calico v3.1 not applying profile labels

### ISSUE THREAD

**Issue by coandco** [projectcalico/calico#2066]
I'm upgrading from Calico 2.6.x to Calico 3.1.x.  My setup uses profiles to apply labels to HostEndpoints, and uses a selector of "has(labelname)" in various policies to ensure they only apply to HostEndpoints with a particular profile.  However, Calico 3.1.x is failing to apply labels from profiles, so my policies are failing.  They're correctly applied if I add the label directly to the HostEndpoints in question.

## Expected Behavior
When a HostEndpoint includes a profile and that profile defines labels, the labels in question should be applied to the HostEndpoint and be available for use in policy selectors.  This is the behavior specified in https://docs.projectcalico.org/v3.1/reference/calicoctl/resources/profile -- it defines the "label" attribute of the Profile resource as "A set of labels to apply to endpoints using this profile".

## Current Behavior
Given that directly applying the "region" label to a HostEndpoint causes rules with "has(region)" to be applied but relying on indirect profile labeling does not, it appears that profile labels are not applied to endpoints that include the profile.

## Steps to Reproduce (for bugs)

Example HostEndpoint:

    apiVersion: projectcalico.org/v3
    kind: HostEndpoint
    metadata:
      name: example-node
    spec:
      expectedIPs:
      - <IP of a calico-managed hostendpoint>
      node: example-node
      profiles:
      - region

Example profile:

    apiVersion: projectcalico.org/v3
    kind: Profile
    metadata:
      labels:
        region: example-region
      name: region
    spec: {}

Example policy:

    apiVersion: projectcalico.org/v3
    kind: GlobalNetworkPolicy
    metadata:
      name: icmp
    spec:
      egress:
      - action: Allow
        destination: {}
        protocol: ICMP
        source: {}
      ingress:
      - action: Allow
        destination: {}
        protocol: ICMP
        source: {}
      order: 1
      selector: has(region)
      types:
      - Ingress
      - Egress

With these three resources in Calico, a look at `sudo iptables-save` on the HostEndpoint described by "example-node" will show no "icmp" policy being applied.  However, if the HostEndpoint definition is modified to directly have the "region" label, the "icmp" policy will show up in the iptables entries.

## Context
I'm upgrading from Calico 2.6.9 to 3.1.3, and my old workflow relied on indirect labeling of HostEndpoints via profiles.  For now, I should be able to directly apply the labels to HostEndpoints as a stopgap, but unless I'm missing something it seems like a bug for indirect profile labeling not to work.

## Your Environment

* Calico version: 3.1.3
* Orchestrator version (e.g. kubernetes, mesos, rkt): Kubernetes 1.6.8
* Operating System and version: Ubuntu Xenial 16.04

**Comment by caseydavenport** [comment]
@coandco ugh, the docs in v3.1 are wrong.

This is still possible in v3.1, but the field name has changed.

It would actually look like this:

```
apiVersion: projectcalico.org/v3
kind: Profile
metadata:
  name: region
spec:
  labelsToApply:
    region: example-region
```

Can be confirmed in the code: https://github.com/projectcalico/libcalico-go/blob/master/lib/apis/v3/profile.go#L32

I've submitted a docs fix: https://github.com/projectcalico/calico/pull/2067

**Comment by coandco** [comment]
Confirmed, using `labelsToApply` in `spec` correctly applies the labels to HostEndpoints that include the profile.  Thanks for the quick reply!
