### ISSUE TITLE
why is the source udp port changed?

### ISSUE THREAD

**Issue by rainbowfhb** [projectcalico/calico#2075]
I have two nodes in same subnet,both nodes are deployed calico network. one node can be scheduled by kubernetes when deploy an server application, and the other one cannot be scheduled, it is just used to deploy load balance. 
But sometimes the packet from lb is changed, i dont know why.
## Expected Behavior

i think it should keep the same port.

## Current Behavior

192.168.75.21---Load Balance server IP.
192.168.72.52--Host server IP and container IP 172.26.101.94 on this host.

container host bond0 Ethernet gets the packets like this：
```
10:52:50.866695 fa:16:3e:0f:56:27 > fa:16:3e:19:04:4a, ethertype IPv4 (0x0800), length 64: 192.168.72.52.5683 > 192.168.75.21.40087: UDP, length 22
10:52:53.401237 fa:16:3e:0f:56:27 > fa:16:3e:19:04:4a, ethertype IPv4 (0x0800), length 64: 192.168.72.52.5683 > 192.168.75.21.40087: UDP, length 22
10:52:53.546809 fa:16:3e:19:04:4a > fa:16:3e:0f:56:27, ethertype IPv4 (0x0800), length 60: 192.168.75.21.40087 > 172.26.101.94.5683: UDP, length 15
10:52:53.546839 fa:16:3e:19:04:4a > fa:16:3e:0f:56:27, ethertype IPv4 (0x0800), length 60: 192.168.75.21.40087 > 172.26.101.94.5683: UDP, length 15
10:52:54.603780 fa:16:3e:19:04:4a > fa:16:3e:0f:56:27, ethertype IPv4 (0x0800), length 60: 192.168.75.21.40087 > 172.26.101.94.5683: UDP, length 15
10:52:54.603799 fa:16:3e:19:04:4a > fa:16:3e:0f:56:27, ethertype IPv4 (0x0800), length 60: 192.168.75.21.40087 > 172.26.101.94.5683: UDP, length 15
```
but when transport to pod container, the source port 40087 is mapped to 1038. the following packets is from cali** Ethernet.
```
10:52:50.866675 2e:ba:11:f0:d4:47 > ee:ee:ee:ee:ee:ee, ethertype IPv4 (0x0800), length 64: 172.26.101.94.5683 > 192.168.75.21.40087: UDP, length 22
10:52:53.401226 2e:ba:11:f0:d4:47 > ee:ee:ee:ee:ee:ee, ethertype IPv4 (0x0800), length 64: 172.26.101.94.5683 > 192.168.75.21.40087: UDP, length 22
10:52:53.546835 ee:ee:ee:ee:ee:ee > 2e:ba:11:f0:d4:47, ethertype IPv4 (0x0800), length 57: 192.168.75.21.1038 > 172.26.101.94.5683: UDP, length 15
10:52:53.546844 ee:ee:ee:ee:ee:ee > 2e:ba:11:f0:d4:47, ethertype IPv4 (0x0800), length 57: 192.168.75.21.1038 > 172.26.101.94.5683: UDP, length 15
10:52:54.603795 ee:ee:ee:ee:ee:ee > 2e:ba:11:f0:d4:47, ethertype IPv4 (0x0800), length 57: 192.168.75.21.1038 > 172.26.101.94.5683: UDP, length 15
10:52:54.603803 ee:ee:ee:ee:ee:ee > 2e:ba:11:f0:d4:47, ethertype IPv4 (0x0800), length 57: 192.168.75.21.1038 > 172.26.101.94.5683: UDP, length 15
```

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Calico version
calico-node:v3.0.1
* Orchestrator version (e.g. kubernetes, mesos, rkt):
kubenetes 1.8
* Operating System and version:
centos 7.2
* Link to your project (optional):

**Comment by tmjd** [comment]
Calico does not set up any NAT, so it would not be changing any ports.

kube-proxy does do some NAT for load balancers and other services it sets up.

From the capture you pasted it almost looks like the server in the container is responding back with a different source port than what you are expecting.

**Comment by rainbowfhb** [comment]
the packet is from lb to container.  these packets are captured at the node where the container is scheduled.
192.168.75.21.40087 is captured through node physical bond0 network card，at the same time 192.168.75.21.1038 is captured through node cali***  network card. 
why the packer is changed through Linux kernel.
container ip is 172.26.101.94, port is 5683.  192.168.75.21 is lb ip.

**Comment by tmjd** [comment]
Ok I think I understand a little better, though I don't understand what is happening but I would guess it is some iptables rule that kube-proxy sets up for the LB.

**Comment by rainbowfhb** [comment]
Is there any configuration about udp conntrack to keep udp alive. i set the node kernel parameters: nf_conntrack_udp_timeout=86400, but it doesnot work.  after through testing, i find that the port will be changed after about 3 minutes. my app is used for CoAP NB-IOT. the terminal device willnot always send heartbit.

**Comment by fasaxc** [comment]
@rainbowfhb can you attach output from `sudo iptables-save -c`; seems there must be a NAT rule that you're hitting but I don't think calico or kube-proxy should NAT a packet that is going to a local pod IP.

**Comment by rainbowfhb** [comment]
[root@kube-node-0003 ~]# iptables-save -c |grep 5683
[0:0] -A KUBE-SEP-JISZAHD2XOFEYMJD -s 172.26.110.152/32 -m comment --comment "default/myapp:5683" -j KUBE-MARK-MASQ
[0:0] -A KUBE-SEP-JISZAHD2XOFEYMJD -p udp -m comment --comment "default/myapp:5683" -m udp -j DNAT --to-destination 172.26.110.152:5683
[0:0] -A KUBE-SERVICES -d 10.254.180.155/32 -p udp -m comment --comment "default/myapp:5683 cluster IP" -m udp --dport 5683 -j KUBE-SVC-76M55ND723NQX7MC
[0:0] -A KUBE-SVC-76M55ND723NQX7MC -m comment --comment "default/myapp:5683" -j KUBE-SEP-JISZAHD2XOFEYMJD

**Comment by rainbowfhb** [comment]
the following is node route information about cali*** with container.
172.26.110.152  0.0.0.0         255.255.255.255 UH    0      0        0 cali738e34eabf2

**Comment by fasaxc** [comment]
Are you using the `10.254.180.155` IP from your load balancer or are you accessing 172.26.110.152 directly?

**Comment by rainbowfhb** [comment]
we keep the lb node in calico cluster, and access 172.26.110.152 directly through lb server ip.  
dont use k8s service.
