### ISSUE TITLE
calico node can not ping another node's tunl0

### ISSUE THREAD

**Issue by shigy123456** [projectcalico/calico#2080]
## Expected Behavior
i have a kubernetes cluster,i have the calico to manage the pod's ip,calico manage four nodes.
my problem is i can not ping the tunl0 of slave1 from master1,but i can ping the tunl0 of master2 from master1.
how to solve the problem?

**Comment by shigy123456** [comment]
![image](https://user-images.githubusercontent.com/35130894/43033099-72bcaff4-8cf6-11e8-9dc3-ccbe0a783dba.png)

**Comment by tmjd** [comment]
What cloud provider are you running on?
Are your slave and master instances in the same Security Groups and do they allow IPIP between the hosts?

**Comment by shigy123456** [comment]
i have my kubernetes cluster in my own openstack。
my master and slave instances are in the same security groups.but i do not know if they allow ipip between the hosts,how to judge?
i find master1 can not ping tunl0 of slave1，but slave1 can ping tunl0 of master1.
when i ping tunl0 of master1 from slave1,then i can ping tunl0 of slave1 from master1,i do not know why .i want to know the reason.

**Comment by tmjd** [comment]
Are all your calico-node pods running successfully?
If yes, could you install calicoctl and run `calicoctl node status` on one of your slaves and one master and include the results here.
https://docs.projectcalico.org/v3.1/usage/calicoctl/install#installing-calicoctl-as-a-binary-on-a-single-host Note: It will not work to use the containerized versions for this specific command and it is not necessary to configure calicoctl.

With your last comment about the ping seeming to fix things I think you should take a look at, https://github.com/projectcalico/calico/issues/1357.

**Comment by shigy123456** [comment]
thanks all.
i have found the reason about the problem.
the network flow table of master1 was lost,so when slave1 ping master1,master1 have cache the flow table,then master1 can ping slave1.but when cache was invalid,master1 can not ping slave1.
so i will find the reason of network flow table lost.

**Comment by zryfish** [comment]
> so i will find the reason of network flow table lost.

@shigy123456 I encountered the exactly the same problem as you had, may I ask how you solve this ?

**Comment by Ankur7890** [comment]
Facing the same issue, could you confirm the changes?

**Comment by xingxing122** [comment]
In which version is this problem resolved

**Comment by jokerZhou** [comment]
> i have my kubernetes cluster in my own openstack。 my master and slave instances are in the same security groups.but i do not know if they allow ipip between the hosts,how to judge? i find master1 can not ping tunl0 of slave1，but slave1 can ping tunl0 of master1. when i ping tunl0 of master1 from slave1,then i can ping tunl0 of slave1 from master1,i do not know why .i want to know the reason.

我也是这个问题,请问怎么解决的啊?
