### ISSUE TITLE
Memory leak in Calico 3.0.5 with etcd ds

### ISSUE THREAD

**Issue by r7vme** [projectcalico/calico#2085]
For some reason many calico-nodes in different clusters had memory leaks in last few weeks. Affected multiple clusters on-prem and one cluster in aws (independent users, so no way that same app was deployed). Did not affect functionality tho, we only see alerts on CPU/MEM consumption far above requests (default ones CPU 250m and MEM 100Mi)

We noticed CPU spikes and increasing consumption along with memory leak. Memory leak stabilized on around 400MB. I see that it's `calico-felix` process in all the cases. Nothing major in logs and calico behaves fine.

## Expected Behavior
No memory leaks (8x times).

## Current Behavior
Memory leak from ~50MB to ~400MB

## Possible Solution
Similar [bug](https://github.com/projectcalico/calico/issues/1057), but for KDD not etcd. 

## Steps to Reproduce (for bugs)
I have no steps to reproduce unfortunately, open for possible suggestions what to check.

## Context
CPU 
```
sum by(cluster_id, pod_name) (rate(container_cpu_usage_seconds_total{cluster_id=~"[a-z,0-9]{5}",cluster_type="guest",pod_name=~"^calico-node.*$"}[15m])) 
```

AWS installation
![42866508-608c83a0-8a75-11e8-8089-bae58b977269](https://user-images.githubusercontent.com/1277504/43202248-46d1c92e-901b-11e8-98b5-0d91380c3d08.png)

on-prem installation
<img width="2459" alt="42815019-ee8aef24-89bd-11e8-8f13-94243a77f56c" src="https://user-images.githubusercontent.com/1277504/43202249-46ec81ec-901b-11e8-9a08-f2db7b0d3ede.png">

Memory
```
(container_memory_working_set_bytes{container_name="calico-node"} / 1024 / 1024) > scalar(avg(kube_pod_container_resource_requests_memory_bytes{cluster_type="guest",container="calico-node"} / 1024 / 1024)) * 2.5
```
![42866616-b12ff49a-8a75-11e8-828b-91da001dd3e8](https://user-images.githubusercontent.com/1277504/43202391-aec13808-901b-11e8-8376-3ad7734eb943.png)

Current memory consumption on-prem (leak started week ago) (leak happened in two clusters,  both have the same version 1.10.1 + calico 3.0.5)
![2018-07-25-14 43 34-screenshot](https://user-images.githubusercontent.com/1277504/43202554-1cd6a166-901c-11e8-8fa4-d24d2350616a.png)

top from calico-node that consumes 400MB
```
Mem: 39439948K used, 74013232K free, 4394704K shrd, 87388K buff, 10823120K cached
CPU:  17% usr   0% sys   0% nic  81% idle   0% io   0% irq   0% sirq
Load average: 2.20 2.51 1.62 1/2428 14711
  PID  PPID USER     STAT   VSZ %VSZ CPU %CPU COMMAND
  106    99 root     S     340m   0%   4   0% calico-felix
  104   102 root     S    42960   0%  10   0% confd -confdir=/etc/calico/confd
  105   101 root     S    22800   0%   4   0% bird6 -R -s /var/run/calico/bird6.ctl -d -c /etc/calico/confd/config/bird6.cfg
  103   100 root     S    18796   0%   9   0% bird -R -s /var/run/calico/bird.ctl -d -c /etc/calico/confd/config/bird.cfg
14704     0 root     S     1592   0%   4   0% sh
14711 14704 root     R     1520   0%   8   0% top
    1     0 root     S      768   0%   2   0% /sbin/runsvdir -P /etc/service/enabled
  101     1 root     S      748   0%   9   0% runsv bird6
  100     1 root     S      748   0%   1   0% runsv bird
   99     1 root     S      748   0%   2   0% runsv felix
  102     1 root     S      748   0%   7   0% runsv confd
```
```
/ # netstat -nptu | wc -l
394
/ # iptables -t nat -S | wc -l
477
/ # iptables -S | wc -l
983
```

## Your Environment
* Calico version 3.0.5 (etcd datastore with IPIP tunnels)
* Orchestrator version: k8s 1.10.1
* Operating System and version: CoreOS 
* Link to your project (optional):

**Comment by fasaxc** [comment]
At a guess, we're getting disconnected from etcd (or etcd is returning an error) and we're doing a datastore resync so worth digging into whether there was a disruption in the etcd cluster at that time (the time of the CPU spike) or a connectivity problem.

@r7vme In preparation fo the next time you see this, please can you set environment variable `FELIX_ DebugMemoryProfilePath=/tmp/felix-mem-<timestamp>.pprof` on your calico-node containers, then, if you see a leak again, you can trigger felix to dump a memory profile to disk by sending felix a SIGUSR1 `sudo pkill -USR1 calico-felix`.  It might be useful to have a dump from before and after the leak for comparison (or two dumps a few hours apart after it starts leaking).  The dump will be written to the configured directory inside the container so you'll need to grab it from there or mount in a directory to catch it.  Recording a dump is pretty non-invasive, it only takes about a second and setting that config param doesn't noticeably impact performance.

**Comment by r7vme** [comment]
Cool, added `FELIX_DebugMemoryProfilePath` into two clusters. Will see if/when it will be reproduced.

**Comment by r7vme** [comment]
Can this potentially be already fixed in newer releases? 3.0.x or 3.1.x ?

**Comment by fasaxc** [comment]
@r7vme It's possible.  We have revved the etcd client library in the newer releases.  It's always easier for us to diagnose more recent releases too (and it adds weight to the problem if it's confirmed i the latest release).

**Comment by fasaxc** [comment]
@r7vme Worth checking that SIGUSR1 is working after your tweak and that you can extract the pprof file.  It'd be a shame to discover that I typoed the env var name above  for example only after you get a repo!

**Comment by r7vme** [comment]
@fasaxc all good, your instructions were correct. I only was not sure about <timestampt>.

```
/ # pkill -USR1 calico-felix
/ # ls /tmp/
felix-mem.pprof  tunl-ip
/ # 
```

>  We have revved the etcd client library in the newer releases

Probably we will push more priority on moving to 3.1.x .

**Comment by fasaxc** [comment]
If you include `<timestamp>` in the name of the file, felix will replace it with the current date/time so each dump file will get a unique name.

**Comment by fasaxc** [comment]
@r7vme Any update on this?  Did you manage to repro?

**Comment by r7vme** [comment]
We had few more leaks on other clusters. They did not have debug param set unfortunately.

We are now looking forward to upgrade to 3.1.

**Comment by r7vme** [comment]
We finally catched one node with memory leak. Prometheus shows memory consumption 301MB and cpu 0.46. pprof from felix process below

[felix-mem.pprof.gz](https://github.com/projectcalico/calico/files/2314568/felix-mem.pprof.gz)

**Comment by fasaxc** [comment]
@r7vme Felix memory usage tracks back to generating the per-endpoint iptables chains.  

* Any errors in the felix log?  I'm wondering if it's tight looping, reprogramming the chains again and again.
* Another potential option is that this felix believes it has many endpoints so it's rendering a lot more rules than it should.  How many pods on this host?  How many `cali-tw-XXX` iptables chains in the filter table (should be one of those per pod)?
* Do you have prometheus metrics turned on on this felix?  If so, could you grab the metrics data `curl http:/127.0.0.1:9091/metrics` from the host should do it.

**Comment by fasaxc** [comment]
[pprof.pdf](https://github.com/projectcalico/calico/files/2314829/pprof.pdf)

**Comment by r7vme** [comment]
> Any errors in the felix log? I'm wondering if it's tight looping, reprogramming the chains again and again.

No errors as far as i see/saw. Here is the log from neighbor calico-node that consumes now 192MB. 
[calico-node-logs.txt](https://github.com/projectcalico/calico/files/2318352/calico-node-logs.txt)
  

> Another potential option is that this felix believes it has many endpoints so it's rendering a lot more rules than it should. How many pods on this host? How many cali-tw-XXX iptables chains in the filter table (should be one of those per pod)?

for node that consumes now 192MB: 82 pods, 79 iptables chains `cali-tw-*` .

> Do you have prometheus metrics turned on on this felix? If so, could you grab the metrics data curl http:/127.0.0.1:9091/metrics from the host should do it.

Disabled. We use your default manifests with few changes. I can enable if needed.

> Would also be useful to have a baseline pprof from before the leak if you have one.

pprof from restarted calico-node with consumption 44MB and 69 pods on the node. 
[felix-mem-restarted.pprof.gz](https://github.com/projectcalico/calico/files/2318357/felix-mem-restarted.pprof.gz)

**Comment by caseydavenport** [comment]
What's the status on this guy? @r7vme are you still seeing this behavior on newer versions of Calico?

**Comment by caseydavenport** [comment]
What's the status on this guy? @r7vme are you still seeing this behavior on newer versions of Calico?

**Comment by r7vme** [comment]
I think i have no doubt on closing this.

- we use 3.2 (soon 3.4)
- we use hard resource limits now
