### ISSUE TITLE
Calico nod pod is unhealthy

### ISSUE THREAD

**Issue by ackris** [projectcalico/calico#2094]
Hey

I've installed Docker UCP (part of enterprise edition of docker), and i am trying to add a node to the swarm cluster. But i'm getting the following error: `Calico-node pod is unhealthy: %!s(<nil>)`

**Details:**
`OS: RHEL 7.4`

`uname -r: 3.10.0-693.el7.x86_64`

**Docker version**

```
Client: Docker Enterprise Edition (EE) 2.0
 Version:       17.06.2-ee-10
 API version:   1.30
 Go version:    go1.8.7
 Git commit:    66261a0
 Built: Fri Apr 27 00:38:41 2018
 OS/Arch:       linux/amd64

Server: Docker Enterprise Edition (EE) 2.0
 Engine:
  Version:      17.06.2-ee-10
  API version:  1.30 (minimum version 1.12)
  Go version:   go1.8.7
  Git commit:   66261a0
  Built:        Fri Apr 27 00:40:03 2018
  OS/Arch:      linux/amd64
  Experimental: false

```
The desired result must be successful node addition to the swarm cluster. Help needed in resolving this issue. 

Regards
Aditya

**Comment by tmjd** [comment]
You should start with looking at the logs from calico-node.  It should have some information on why it is unhealthy.  If you can grab logs and add them to the issue we can try to help more.

**Comment by smartinovic** [comment]
I'm having the same issue. 
@ackris Have you been able to resolve it?

**Comment by ned-horvath** [comment]
I've got a similar problem, except the calico images (ucp-calico-node and ucp-calico-cni) aren't even getting pulled. This is ucp 3.1.8. _most_ of my nodes are doing fine, just one is misbehaving. Smells like something pre-installed on that node is interfering

Any ideas or remedies? The other suggestions don't apply (rp_filter is 1, plenty of disk).

**Comment by ned-horvath** [comment]
FWIW, docker/ucp-pause isn't being pulled either.
