### ISSUE TITLE
"stable" redirect to latest release page

### ISSUE THREAD

**Issue by caseydavenport** [projectcalico/calico#211]
I want to be able to link to the latest "stable" release for a given page.

e.g 
- http://docs.projectcalico.org/stable/getting-started/kubernetes/installation/hosted/kubeadm/

should redirect to 
- http://docs.projectcalico.org/v1.6/getting-started/kubernetes/installation/hosted/kubeadm/

So I don't have to update links in other repos all the time.

**Comment by djosborne** [comment]
Seems possible with [jekyll-redirect-from](https://github.com/jekyll/jekyll-redirect-from) which luckily is on the list of [jekyll plugins supported by github](https://pages.github.com/versions/)

**Comment by djosborne** [comment]
That gem is quite powerful, but would require adjustments to our release process. Let's walk through a quick example of how this works. Let's use `v2.0/getting-started/kubernetes/index` as an example.

We'd place at the top of that document, in the yaml front matter:
```
---
redirect_from: /stable/getting-started/kubernetes/
---
```
When it renders the site, jekyll will create `_site/stable/getting-started/kubernetes/index.html`, which includes the following:
```
<title>Redirecting…</title>
<link rel="canonical" href="http://docs.projectcalico.org/v1.6/getting-started/kubernetes/">
<meta http-equiv="refresh" content="0; url=http://docs.projectcalico.org/v1.6/getting-started/kubernetes/">
<h1>Redirecting…</h1>
<a href="http://docs.projectcalico.org/v1.6/getting-started/kubernetes/">Click here if you are not redirected.</a>
<script>location="http://docs.projectcalico.org/v1.6/getting-started/kubernetes/"</script>
```

Folks who visit `docs.projectcalico.org/stable/getting-started/kubernetes/` will see this basic web page briefly before the web browser interprets the html and does the redirect.

This leaves two questions:
1. How does this affect SEO? This doesn't appear to issue a 300 or 301 redirect, so not sure how google's web crawlers will take this.
2. How do we work this into our release processes and layouts. Lets say stable changes from v1.6 to v2.0. We now need to remove that from the header of all v1.6 pages, and add it for v2.0 pages. Additionally, any pages that no longer exist or had their URL changed will now 404.

**Comment by djosborne** [comment]
We should look into improving the release scripts (when we tackle #134) so they also remove `/latest` from all frontmatter of the last release, and add it on the new latest release

**Comment by tomdee** [comment]
This is now fixed
