### ISSUE TITLE
test_host_endpoint_combinations test case is failing for Calico-3.1.3

### ISSUE THREAD

**Issue by chakravarthy392** [projectcalico/calico#2115]
executed `make st` on calico-3.1.3 which resulted a test case failure.

## Expected Behavior
All TCs should pass.

## Current Behavior
`test_host_endpoint_combinations` is failing on RHEL 7.5 (both Intel and non-Intel architectures).
`[fail] 11.58% tests.st.policy.test_felix_gateway.TestFelixOnGateway.test_host_endpoint_combinations: 13.1786s`

## Steps to Reproduce (for bugs)
1.#Install GO 1.10
2.git clone http://github.com/projectcalico/calico $GOPATH/src/github.com/projectcalico/calico
3.cd $GOPATH/src/github.com/projectcalico/calico
4.git checkout v3.1.3
5.cd $GOPATH/src/github.com/projectcalico/calico/calico_node
6.RELEASE_STREAM=v3.1 make dist/calicoctl 
7.RELEASE_STREAM=v3.1 make calico/node 
8.RELEASE_STREAM=v3.1 make st 

Output of `RELEASE_STREAM=v3.1 ST_TO_RUN=tests/st/policy/test_felix_gateway.py:TestFelixOnGateway.test_host_endpoint_combinations  make st` :
[felix.log](https://github.com/projectcalico/calico/files/2282057/felix.log)

## Your Environment

* Calico version - 3.1.3
* Operating System and version: Intel , RHEL-7.5

**Comment by caseydavenport** [comment]
Looks like the `release-v3.1` branch is currently passing all STs: https://semaphoreci.com/calico/calico-old-releases/branches/release-v3-1
