### ISSUE TITLE
Is it possible to use GlobalNetworkSet in a network policies?

### ISSUE THREAD

**Issue by tipirk** [projectcalico/calico#2120]
Hello,

According to GlobalNetworkSet definition i can use it in global network policies, is it possible to use them in network policies?

**Comment by caseydavenport** [comment]
Right now, you cannot - GNPs are a global resource, and network policies are intrinsically namespaced so can only select things within the same namespace, or another namespace.

Could you provide some more info as to what you're trying to achieve / use-case is?

**Comment by tipirk** [comment]
For example we have 2 NS prod and pre-prod, pods within them have the same labels and i want to permit access to external DB only for pods in prod NS. Now i use network policies with nets and IPs of external servers. And if i want change or delete one of these IPs i'll have to change all network policies and reapply all of them separately.

**Comment by tipirk** [comment]
@caseydavenport What if i don't want to permit that access for all pods in the prod namespace? Is it possible to select prod namespace and some pod with certain label from it in GlobalNetworkPolicy?

**Comment by caseydavenport** [comment]
> Is it possible to select prod namespace and some pod with certain label from it in GlobalNetworkPolicy?

Yep - see here: https://docs.projectcalico.org/v3.2/reference/calicoctl/resources/globalnetworkpolicy#selector

Selectors can be combined with `&&`
