### ISSUE TITLE
Provide better documenttion for protocols used between kubernetes nodes

### ISSUE THREAD

**Issue by Chandrashekar89** [projectcalico/calico#2128]
I am setting up kubernetes cluster in AWS with security group allowing all tcp ports. Later I got to know to allow protocol 4 (IP-IP) for traffic between nodes. Then to get node port working I have to allow all traffic between nodes. 

Not much information is provided as to what are the protocols used in calico. It would be better if the list is provided of protocols used rather than opening all traffic.

Environment:
AWS in VPC
Kubernetes

**Comment by ozdanborne** [comment]
Thanks for raising. This requirements page covers some of what you're raising: https://docs.projectcalico.org/v3.2/getting-started/kubernetes/requirements

**Comment by Chandrashekar89** [comment]
The following are the current settings of security group.
Outbound all traffic allowed.
Inbound all TCP allowed, custom protocol (4 for IP in IP) allowed
I am not using flannel. Still I enable UDP 4789.

The above setup should cover all the requirements provided in the link. But still the traffic to nodeport will get dropped, if the pods are not available in that particular node. If I allow all the incomming traffic between nodes, it is working as expected. 

I am assuming the connections are being dropped by VPC in between nodes. But couldn't figure out what other traffic needs to be allowed for the nodeport to work correctly other than allowing all traffic. Maybe I am missing some other protocol that is used by calico other than IP-IP(4).

**Comment by caseydavenport** [comment]
This thread has gone stale - please shout if you're still hitting issues.

I think this is likely a misconfig - the docs here show the set of required allows: https://docs.projectcalico.org/v3.3/getting-started/kubernetes/requirements

Things to consider:
- Is a network policy dropping the traffic?
- Do you have TCP 179 allowed between nodes if you're using BGP?
