### ISSUE TITLE
reference/addressing is wrong / out of date

### ISSUE THREAD

**Issue by caseydavenport** [projectcalico/calico#214]
http://docs.projectcalico.org/v2.0/reference/addressing

The diagram has references to "Note 1", "Note 2" etc which aren't in the doc.

This doc also needs reword in a few places to make sense in the context of Kubernetes, Mesos, etc.

e.g The following doesn't mention the name "IP pools", though that is the concept that users will be familiar with.

> In current Calico, the ranges from which IP addresses may be assigned to workloads are all provisioned by the data center operator

There's a bunch of orchestrator specific information that should probably go here.  For example, k8s pod addresses shouldn't overlap with the k8s Service IP range.

**Comment by djosborne** [comment]
Anyone opposed to us removing that doc?

After gleening it over, it seems to be describing the difference between public and private IP ranges, which doesn't seem like incredibly useful information IMO

**Comment by matthewdupre** [comment]
I think it's more valuable than that; but it's very OpenStacky, and the overhaul would be significant.  (Remember we don't generally use --nat-outgoing in OpenStack: it happens quite differently.)

I'm OK with it going.

**Comment by caseydavenport** [comment]
Not convinced we should remove this doc without replacing it with the right stuff, but it's certainly very wrong as it is now.

**Comment by neiljerram** [comment]
In short, I think it's OK to remove this.

I originally added this in the OpenStack context where it isn't common to assign a public IP directly to a VM, and for a VM to be accessible through a public IP without needing some NAT somewhere.  So it was useful for some OpenStack-centred conversations that we were having then.  But container networking mostly doesn't (yet?) have the 'virtual networking' / 'bring your own addressing' baggage, so the content of this page doesn't really need saying for Calico with containers.

It _might_ be useful in the future for me to resurrect some of this content and add under http://docs.openstack.org/developer/networking-calico/, but there's no great urgency for that, and I can get the content out of Git if I need it.

Note that there are also images that can be removed, when the page goes.

**Comment by djosborne** [comment]
Doc was removed by #347
