### ISSUE TITLE
Calico/node image increased by 120MB from 3.1 to 3.2

### ISSUE THREAD

**Issue by ry4nz** [projectcalico/calico#2144]
```
calico/node     v3.2.0              b0e162722eaf        13 days ago         370MB
calico/node     v3.1.3              7eca10056c8e        2 months ago        248MB
```
The image size has increased dramatically.  Are there any optimization can be done here?

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* calicoctl version (e.g. `calicoctl version`):
* calico/node version (e.g. `docker run --rm calico/node versions`)
* Orchestrator type and version (e.g. kubernetes, mesos, rkt):
* Operating System and version:
* Link to your project (optional):

**Comment by caseydavenport** [comment]
@ry4nz yes, the image that was built for v3.2.0 included two copies of some of the binaries accidentally due to a build issue.

v3.2.1 has fixed this, and should actually be _substantially_ smaller.

```
quay.io/calico/node                                   v3.2.1                              986dbf23b28e        19 hours ago        74.5MB
```
