### ISSUE TITLE
pod to pod communication in same node does not follow expected route

### ISSUE THREAD

**Issue by sudhiragarwal** [projectcalico/calico#2160]
When i am pinging a pod from another pod which are in same worker node, then the pods are not passing through the tunl0 interface. The path which a packet takes is source_pod_eth0 interface ---> 
source_pod_caliXXXX interface ---> destination_pod_caliXXXX interface ---> destination_pod_eth0 interface. I cannot see any packets at the tunl0 interface. If it does not passes through tunl0 interface, then how the caliXXX interface of source pod forwards the packet to the caliXXX interface of the destination pod.

## Expected Behavior
The caliXXX interfaces of both the pods should either communicate through some bridge interface or through the tunl0 interface. Since there is no packets flowing from any interface other than the caliXXX interfaces of the pods, then how they are interacting with each other

## Current Behavior
currently the packets pass from one caliXXX interface to other caliXXX interface without any tunl0 or bridge in between. 

## Steps to Reproduce (for bugs)
1. Create a kubernetes cluster with calico network plugin.
2. Create 2 pods in the same node.
3. Go inside one of the pod and curl the ip of the other pod.
4. At the same time, collect the tcpdump data on all the interfaces (pod's eth0, caliXXX interfaces and the tunl0 interface).

## Your Environment

* Calico version 3.1
* Orchestrator version (e.g. kubernetes, mesos, rkt): kubernetes 1.11.2
* Operating System and version: Linux 7.4
* Link to your project (optional):

**Comment by caseydavenport** [comment]
@sudhiragarwal what you're describing is actually the expected packet flow for calico networked pods.

Calico is a routed network, and there is no bridge device in the middle. Packets leave the pod and get routed directly to the next hop, which in your case is another local pod.

tunl0 will only be used for encapsulated traffic to a pod on another host.

**Comment by virtuallearner** [comment]
Hello Casey, I am beginner in this virtualization stuff but would appreciate your guidance on one of the similar issue i am facing regarding monitoring the tnl0 interface with calico plugin.

Use Case: I want to monitor intra (pod to pod) under same node and also between the nodes, which interface will come into picture in both cases. - As of now I am using tnl0 to monitor traffic between the pods but getting nothing and if i change it to management interface i am able to see packets being captured.

I would really appreciate to please guide me which interfaces do what and what needs to be done in my case.

Thanks in advance!

Regards,
Ani
