### ISSUE TITLE
Calico node is fails to start when DHCP option is changed

### ISSUE THREAD

**Issue by nvenky** [projectcalico/calico#2162]
I am running a Kubernetes cluster v1.8.6 in AWS that I created with KOPS. I use Calico for networking. 

I initially had custom domain name in my VPC DHCP option set. 
domain-name = custom.companyname.com which was pointing to our on-prem server.

I recently changed the DHCP option of my VPC to use the default AWS domain-name.
domain-name = ap-southeast-2.compute.internal

## Expected Behavior
Calico nodes should work normally

## Current Behavior
I terminated all the EC2 instances (3 master and 2 nodes) and recreated the instances. But Calico node fails to start and enters CrashLoopBackOff state.

**Error message I see on the stopped container is:**
2018-08-31T23:30:35.735379684Z Skipping datastore connection test
2018-08-31T23:30:35.951155227Z Using autodetected IPv4 address on interface eth0: 10.33.6.184/24
2018-08-31T23:31:09.910155503Z Calico node 'ip-10-33-6-184.custom.companyname.com' is already using the IPv4 address 10.33.6.184:
2018-08-31T23:31:09.910189827Z  -  Check the node configuration to remove the IP address conflict
2018-08-31T23:31:09.910195192Z Terminating
2018-08-31T23:31:09.911495175Z Calico node failed to start

## Steps to Reproduce (for bugs)

1. As mentioned above, I ran into this issue when I changed the AWS VPC DHCP OptionSet.

## Context
Kubernetes cluster has been down and we are unable to use the system.

## Your Environment

* Calico version - quay.io/calico/node - v2.6.2
* Orchestrator version (e.g. kubernetes, mesos, rkt): Kubernetes
* Operating System and version: CoreOS
* Link to your project (optional):

**Comment by nvenky** [comment]
Realised that Calico stores some of the information in ETCD.

I managed to delete the calico dir from etcd through HTTP API.

curl http://etcd-a.internal.<k8s.cluster>:4001/v2/keys/calico?recursive=true -XDELETE

**Comment by caseydavenport** [comment]
@nvenky I believe this is the document that's relevant to this: https://docs.projectcalico.org/v3.2/usage/decommissioning-a-node

**Comment by caseydavenport** [comment]
In general, you shouldn't delete data from etcd directly since it's possible to end up in an inconsistent state.

We recommend using the `calicoctl` tool to manage the Calico data store.
