### ISSUE TITLE
can calico work with infiniband?

### ISSUE THREAD

**Issue by tingweiwu** [projectcalico/calico#2163]
if I have a ib0 and eth0, can I use ib0 for calico node to route?

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Calico version
* Orchestrator version (e.g. kubernetes, mesos, rkt):
* Operating System and version:
* Link to your project (optional):

**Comment by caseydavenport** [comment]
I'm not aware of this having been tested or tried before. I honestly don't know a whole lot about infiniband. If it manifests itself as a linux network interface, you can certainly try to run Calico over it!

If anyone does try it, I'd be really interested to hear how it worked out!
