### ISSUE TITLE
Calico 3.2 + flannel - bad routing table in containers

### ISSUE THREAD

**Issue by emptywee** [projectcalico/calico#2172]
## Expected Behavior
In 3.1.3:
```
$ kubectl -n kube-system exec -ti centos -- bash
bash-4.2# netstat -nr
Kernel IP routing table
Destination     Gateway         Genmask         Flags   MSS Window  irtt Iface
0.0.0.0         169.254.1.1     0.0.0.0         UG        0 0          0 eth0
169.254.1.1     0.0.0.0         255.255.255.255 UH        0 0          0 eth0
```

## Current Behavior
In 3.2.1:
```
$ kubectl -n kube-system exec -ti centos -- bash
bash-4.2# netstat -nr
Kernel IP routing table
Destination     Gateway         Genmask         Flags   MSS Window  irtt Iface
10.158.128.0    169.254.1.1     255.255.128.0   UG        0 0          0 eth0
169.254.1.1     0.0.0.0         255.255.255.255 UH        0 0          0 eth0
```

So routing is set only for pod's subnet.

## Possible Solution
No idea. I believe one of the PRs merged into 3.2 did something with routing. Could not find any documentation on this behavior change and how to retain old behavior.

## Steps to Reproduce (for bugs)
Followed https://docs.projectcalico.org/v3.1/getting-started/kubernetes/installation/flannel and https://docs.projectcalico.org/v3.2/getting-started/kubernetes/installation/flannel. Behavior is shown above.

## Context

The issue is breaking connectivity from pods to any subnet other than pod's subnet, including services created in cluster.

## Your Environment

* Calico version 3.2.1
* Orchestrator version (e.g. kubernetes, mesos, rkt): Kubernetes 1.10.5
* Operating System and version: CoreOS 1800.7.0 (Rhyolite)

**Comment by caseydavenport** [comment]
Hm, I just installed v3.2.1 on a fresh cluster using the link above and it looks like the routes are correct to me:

```
root@bb-67b45b59d6-w76q6:/# ip route
default via 169.254.1.1 dev eth0 
169.254.1.1 dev eth0  scope link 
```

```
root@bb-67b45b59d6-w76q6:/# netstat -nr
Kernel IP routing table
Destination     Gateway         Genmask         Flags   MSS Window  irtt Iface
0.0.0.0         169.254.1.1     0.0.0.0         UG        0 0          0 eth0
169.254.1.1     0.0.0.0         255.255.255.255 UH        0 0          0 eth0
```

I wonder if there is another environmental difference?

**Comment by emptywee** [comment]
@caseydavenport that's odd. What can affect routing table installed in containers? Any parameters/settings set somewhere? And why would behavior differ between calico 3.1 and 3.2?

**Comment by emptywee** [comment]
What I have found so far. Increased log level verbosity in kubelet and set calico cni loglevel to debug.
3.2.1 produces the following line:

https://github.com/projectcalico/cni-plugin/blob/release-v3.2/k8s/k8s.go#L149

```
Sep 06 14:41:35 lvdkbw501 kubelet-wrapper[8633]: 2018-09-06 21:41:35.484 [INFO][10949] k8s.go 149: Using custom routes from CNI configuration. ContainerID="ed4e18eb87782994a4f50cddb16a3b919d414db4a142fc65f45a924969341433" Namespace="kube-system" Pod="centos" WorkloadEndpoint="lvdkbw501-k8s-centos-eth0" routes=[]*net.IPNet{(*net.IPNet)(0xc4203c8480)}
```

Reading the source code suggests that the https://github.com/projectcalico/cni-plugin/blob/release-v3.2/k8s/k8s.go#L71 condition is true. Is it supposed to be true using flannel for networking?

Seeing that the type is set to host-local from the calico perspective:

```
Sep 06 14:41:23 lvdkbw501 kubelet-wrapper[8633]: 2018-09-06 21:41:23.363 [DEBUG][10672] utils.go 135: Looking for IPAM plugin in paths ContainerID="d67ec769f4b2bb1fa1146d476d0f90299e08e8ac9069177384295b97df928c8f" paths="/opt/flannel/bin:/opt/cni/bin" type="host-local"
```

**Comment by caseydavenport** [comment]
Investigated a bit.

I think this is because when using Flannel as a delegate / meta-plugin, it populates the "routes" section of the IPAM config.

See here: https://github.com/containernetworking/plugins/blob/master/plugins/meta/flannel/flannel.go#L236

In earlier versions of Calico, we ignored this. But, v3.2 now respects it. One option is to just now use flannel in delegate mode and to instead just run the Calico plugin + flanneld - this is what the manifest above does (and why I didn't see this in my repro attempts).

**Comment by caseydavenport** [comment]
@fasaxc yeah, the etcd one still uses delegation, whereas kdd does not.

I'm not sure what the right fix is - either in flannel or in the Calico plugin. The same issue was fixed for flannel+bridge in the bridge plugin by adding a field which tells the bridge plugin it is the default gw.

IMO this is really something that should be fixed in flannel, so it can be configured to pass the right set of routes. Otherwise every delegated plugin will need to implement the same logic.

**Comment by caseydavenport** [comment]
A fix for this went in there: https://github.com/projectcalico/cni-plugin/pull/592

It allows enabling a default route to be programmed. Not in a release yet, but I hope to cherry-pick it into the next v3.2 release. Barring that, it will definitely be in Calico v3.3.0.

**Comment by emptywee** [comment]
Thank you!
