### ISSUE TITLE
Add content for the "coming soon" pages, or remove them

### ISSUE THREAD

**Issue by caseydavenport** [projectcalico/calico#219]
Keeping a comprehensive list here:

- [x] /usage/exposing-ports (Not sure what this one is supposed to be? Can we remove this?)
- [x] /getting-started/mesos/upgrade
- [x] /getting-started/mesos/troubleshooting
- [x] /getting-started/docker/upgrade
- [x] /getting-started/docker/troubleshooting
- [x] /getting-started/docker/
- [x] /getting-started/bare-metal/upgrade
- [x] /getting-started/bare-metal/troubleshooting
- [x] /getting-started/bare-metal/tutorials
- [x] /getting-started/kubernetes/upgrade
- [x] /getting-started/rkt/upgrade
- [x] /getting-started/rkt/troubleshooting
- [x] /getting-started/rkt/
- [x] /getting-started/rkt/tutorials
- [x] /reference/public-cloud/overview
- [x] /reference/private-cloud/troubleshooting
- [x] /reference/private-cloud/

**Comment by djosborne** [comment]
@caseydavenport FYI I updated your list

**Comment by djosborne** [comment]
I think we should get all of these resolved for v2.0.

If this information has been "Coming Soon" for two releases, let's remove the landing pages, and add them in once we are ready to create the content.

**Comment by lwr20** [comment]
Can we prioritise upgrade docs please?

**Comment by caseydavenport** [comment]
Let's remove as many of these as we reasonably can.

**Comment by djosborne** [comment]
I'll take care of the Mesos ones.

**Comment by caseydavenport** [comment]
@djosborne assigning to you for the remaining mesos stuff.
