### ISSUE TITLE
Write public cloud docs for major cloud providers

### ISSUE THREAD

**Issue by caseydavenport** [projectcalico/calico#220]
We need docs in this section: http://docs.projectcalico.org/v2.0/reference/public-cloud/overview

This issue covers docs for:

- [x] AWS (#258)
- [x] GCE
- [ ] Azure

We've already got this information floating around in various other guides.  We should be removing it from all of those places and keeping a "Calico on AWS", "Calico on GCE", etc style doc for each provider.

**Comment by djosborne** [comment]
#315 and #321 were closed, but might provide a useful base for resolving this.
