### ISSUE TITLE
Support for /32 floating IPv4s

### ISSUE THREAD

**Issue by teran-mckinney** [projectcalico/calico#2202]
Would like to be able to use Calico with [Vultr's floating IPs](https://www.vultr.com/docs/high-availability-on-vultr-with-floating-ip-and-bgp). They are provided to the node as /32s. It works just fine to add the /32 to a dummy interface and have bird going. I think Vultr is not the only host to do this

## Expected Behavior
When I add a /32 IPPool, I'd like to see it go through. Implementation details may be more troublesome but this "just works" fairly easily. The host just needs to reply to ARPs for the IP with its interface's MAC and should work as hoped.

## Current Behavior
When adding a /32 IPPool, I get an error saying IPAM only supports /26 and larger.

**Comment by caseydavenport** [comment]
This is fixed in master now - you can create IPPools between /20 and /32 (inclusive).

Will be available in Calico v3.3.
