### ISSUE TITLE
pod to pod on different nodes do not ping

### ISSUE THREAD

**Issue by hocks** [projectcalico/calico#2208]
I am looking for the correct configuration in k8s to enable pod-to-pod ping across nodes.

## Expected Behavior

NAME                          READY     STATUS    RESTARTS   AGE       IP                NODE                  NOMINATED NODE
pod/busybox                   1/1       Running   20         20h       192.168.114.159   gordon-dm1.sdsc.edu   <none>
pod/busylisten                1/1       Running   0          20h       192.168.88.100    gordon-dm2.sdsc.edu   <none>

pod busybox should be able to ping busylisten

## Current Behavior
ping works for pods on the same node but not for pod on different nodes (100% packets loos)

I tried to look through the documentation and find a solution but no such luck
resource does not exist: FelixConfiguration(default)
Failed to apply 'IPPool' resource: resource does not exist: FelixConfiguration(default)

We only use 4 nodes for the k8s, do I need flannel or kube-router just to route between the nodes?  

## Your Environment
calicoctl-3.1.0-0 
kubernetes-cni-0.6.0-0.x86_64
kubelet-1.11.2-0.x86_64
kubeadm-1.11.2-0.x86_64
kubectl-1.11.2-0.x86_64
kube-profile-1.10-0.noarc

CentOS Linux release 7.5.1804

**Comment by caseydavenport** [comment]
You shouldn't need flannel / kube-router for routing to work.

Try running `calicoctl node status` on one of the nodes to see if the BGP sessions are established.

You may also need to allow the traffic in your network firewall, if you have one. Where is this cluster running?

**Comment by Nurlan199206** [comment]
i got same issue, pings pod to pod between nodes not working 

i'm playing with kubernetes on VirtualBox.

1) VM Ubuntu 18.10 ( MASTER `kubernetes 1.14.2, calico v3.7`)
1) VM Ubuntu 18.10 (NODE1 `kubernetes 1.14.2, calico v3.7`)

**Comment by tmjd** [comment]
It might be necessary to specify the IP autodetection. https://docs.projectcalico.org/v3.7/reference/node/configuration#ip-autodetection-methods
Most likely your hosts have multiple interfaces and calico is selecting the wrong one. Your status showing a peer address of 172.21.0.1 indicates this since it should be trying to connect to the Host IP you've listed for the other host.
