### ISSUE TITLE
Calico 3.2.2 with K8s 1.11.3: Readiness probe failed 

### ISSUE THREAD

**Issue by mrsherlock88** [projectcalico/calico#2210]
I see calico-node unhealthy, calico-pod READY 1/2, run `descibe pod` show Warning: `Readiness probe failed: calico/node is not ready: felix is not ready: Get http://localhost:9099/readiness: net/http: request canceled while waiting for connection (Client.Timeout exeeced while awaiting headers)`.

## Steps to Reproduce (for bugs)
Installation with latest kubeadm
1. Run `kubeadm init --pod-network-cidr=192.168.0.0/16`.
2. Setup `etcd.yaml`, `rbac.yaml`. For `calico.yaml`, I tried 2 methods:
- The default on calico site.
- Update `IP_AUTODETECTION_METHOD=interface=ens*`.
- When join another node, calico-node in the worker works fine with 2/2 READY, but on master node still 1/2 READY with the same warning.

## Your Environment
* Calico version: 3.2.2
* Kubernertes 1.11.3
* Ubuntu 16.04

I don't know it comes up with latest version, or with my server environment, because I got server from our sysadmin.

**Comment by caseydavenport** [comment]
You might be encountering this issue: https://github.com/projectcalico/calico/issues/2146#issuecomment-425030944

Do you see the same behavior if you use Calico v3.1?

**Comment by mrsherlock88** [comment]
Sorry, maybe it causes by system environment. After request another VM, it went out. Still do not know how to inspect this, I also run root in both machine.

**Comment by 54853315** [comment]
Hi, use `ifconfig` find your network dervice name ,set to calico.yaml  like this :

```
- name: IP_AUTODETECTION_METHOD
              value: "interface=eth0"
```

![image](https://user-images.githubusercontent.com/1081252/70432923-4c53fa80-1abb-11ea-82d3-6fdb0ddbd7ad.png)
