### ISSUE TITLE
Use SNAT instead of MASQUERADE for --nat-outgoing, so it chooses the right source IP

### ISSUE THREAD

**Issue by cstavr** [projectcalico/calico#2222]
Calico provides external connectivity to containers by performing NAT for traffic that's leaving the Calico pool (--nat-outgoing). NAT is performed with the  `MASQUERADE` target, which causes problems when the host has multiple IP addresses. Instead, it can use `SNAT` and choose the right source IP.

## Current Behavior
When `--nat-outgoing` option is used, Calico performs NAT for the outgoing traffic by adding a rule in the `nat` table that uses the `MASQUERADE` target:
   ```
   Chain cali-nat-outgoing (1 references)
    pkts bytes target     prot opt in     out     source               destination
     121  7548 MASQUERADE  all  --  *      *       0.0.0.0/0            0.0.0.0/0            / * cali:Dw4T8UWPnCLxRJiI */ match-set cali40masq-ipam-pools src ! match-set cali40all-ipam-pools dst
   ```
Using the `MASQUERADE` target causes problems when the host has multiple IP addresses on the same interface. For example, when running on AWS with an Elastic IP attached as a secondary IP on the primary interface. In this case, we may want to perform NAT using the secondary IP as the source IP, because this is the only one with public connectivity.

## Possible Solution
Replacing the `MASQUERADE` target with `SNAT` solves the case where a host has multiple IP addresses. SNAT requires a static IP address, but this should not be a problem since the node's IP is already known (either by the autodetect mechanism or because it is specified with the `--ip` option). Finally, using SNAT removes the overhead to determine for each packet the source IP address to use.

## Your Environment

* Calico version: v3.1.3
* Orchestrator version (e.g. kubernetes, mesos, rkt): Kubernetes
* Operating System and version: Debian

**Comment by caseydavenport** [comment]
> but this should not be a problem since the node's IP is already known (either by the autodetect mechanism or because it is specified with the --ip option). 

The IP chosen by the autodetect mechanism is meant for BGP control plan configuration only, not for workload traffic. In a number of cases where there are multiple interfaces on the host it would be wrong to SNAT to that address.

Need to think about this some more to think about what we can reasonably do. Another alternative would be to disable outgoing NAT in Calico and use another mechanism (e.g. NAT at the border) to provide outbound connectivity.

**Comment by normander** [comment]
Hi, I have the same problem. Is that only solution for snap outgoing from pod?

**Comment by steven-sheehy** [comment]
I encountered this same difficulty when trying to add [egress](https://github.com/steven-sheehy/kube-egress) functionality with Calico. It's made more difficult since Calico ensures it's always the first rule in POSTROUTING. I worked around it by setting `nat-outgoing: false` for my ippool and manually adding a SNAT rule, but this is far from ideal:

```shell
sudo iptables -t nat -I POSTROUTING -o eth0 -s ${POD_SUBNET} ! -d ${POD_SUBNET} -j SNAT --to ${VIP}
```

@caseydavenport My proposal to solve this in Calico is to add a new configuration option `outgoing-ip`. When set, and if `nat-outgoing: true` and that IP exists on the main network interface, Calico will add a SNAT rule to `cali-nat-outgoing` with that `outgoing-ip`. If `nat-outgoing: true` but IP doesn't exist it will fall back to the current MASQUERADE functionality. This is similar to @cstavr idea but makes it an opt-in feature and backwards compatible with the current approach. What do you think?

**Comment by caseydavenport** [comment]
Yeah, something like that sounds fairly reasonable. Would just need to decide on the configuration model.

A single IP seems too limited to me, but maybe we could provide an interface name and/or CIDR from which the IP must match? Or some similar kind of autodetection. It feels operationally difficult to have to specify individual IPs for every node in the cluster.

e.g. `SNAT_INTERFACE=eth1` would configure Calico to use the IP on `eth1`. Or `SNAT_CIDR=172.24.0.0/24` would pick an IP on the host in that range?

**Comment by steven-sheehy** [comment]
Yes, probably both interface and CIDR would be necessary. I like `SNAT_INTERFACE` and `SNAT_CIDR`. These would be environment variables consumed by calico-node, correct? Not sure how you could autodetect that though. Perhaps for now just the manual, off by default approach and consider automatic when the use case arises in a different issue?

If `SNAT_CIDR` needs to support non-contiguous IPs or ranges it could also support comma-separated list of CIDRs. Though again that can be considered in a future issue as the need arises.

**Comment by vivekskrishna** [comment]
@steven-sheehy 

Hi. Even when i switched off nat in calico i see following rule installed in postrouting ven though the masquerade rule is no longer present. So i am not able to match the packets to the rule you specified above as workround

-A POSTROUTING -m comment --comment "cali:O3lYWMrLQYEMJtB5" -j cali-POSTROUTING

how did you disable this?

iptables-save -t nat -c |grep cali-POS
:cali-POSTROUTING - [0:0]
[416:26849] -A POSTROUTING -m comment --comment "cali:O3lYWMrLQYEMJtB5" -j cali-POSTROUTING
[8417:562086] -A cali-POSTROUTING -m comment --comment "cali:Z-c7XtVd2Bq7s_hA" -j cali-fip-snat
[8417:562086] -A cali-POSTROUTING -m comment --comment "cali:nYKhEzDlr11Jccal" -j cali-nat-outgoing

iptables-save -t nat -c |grep cali-fip-snat
:cali-fip-snat - [0:0]
[8487:566748] -A cali-POSTROUTING -m comment --comment "cali:Z-c7XtVd2Bq7s_hA" -j cali-fip-snat

**Comment by steven-sheehy** [comment]
@vivekskrishna The cali-POSTROUTING table doesn't go away, only the rule within cali-POSTROUTING that masquerades outgoing traffic. Thus outgoing traffic will exit cali-POSTROUTING and go to the next rule in POSTROUTING where you can NAT it.

**Comment by vivekskrishna** [comment]
@steven-Sheely Yes. Thank you. I also had to add an entry in filter table to handle forwarding from other notes which had to be inserted before the Kube-drop entry.

**Comment by neiljerram** [comment]
@cstavr @normander @steven-sheehy We will probably merge support for the SNAT option shortly anyway, but I don't fully understand the topologies where MASQUERADE doesn't work, and would like to understand those if you don't mind further sharing.

With MASQUERADE, I assume Linux's algorithm for selecting the source IP would be:
- Use routing to work out the outgoing interface and next hop address for the destination.
- Select the IP on the outgoing interface that's in the same subnet as the next hop address.

So, when you say that you have multiple addresses, but only one of those has public connectivity, why wouldn't the routing be set up such that the public connectivity address will be chosen?

For the AWS case specifically, what is the relationship between
- the elastic IP and its subnet
- the primary (non-public) IP and its subnet
- what the instance's routing table says for routing to the destination?

**Comment by steven-sheehy** [comment]
@neiljerram I'm on bare metal, so I'll let the others speak about the AWS case. My use case is with floating/virtual IPs assigned by keepalived. So I have multiple public addresses (the node IP and the VIP) on the same interface on one node but they resolve to the same MAC address. I want to tell Calico to SNAT via the VIP if it's available and fallback to node IP if not. MASQUERADE is always picking the node IP.

**Comment by neiljerram** [comment]
Initial requirement here has been met by https://github.com/projectcalico/libcalico-go/pull/1089, https://github.com/projectcalico/felix/pull/2028 and https://github.com/projectcalico/calico/pull/2649, so I'll close this issue now.

I'm sure there are more enhancements that might be wanted on top of that.  In that case, please open new issues with a link (for context) back to this one.
