### ISSUE TITLE
usage/troubleshooting/faq formatting weirdly 

### ISSUE THREAD

**Issue by caseydavenport** [projectcalico/calico#224]
http://docs.projectcalico.org/v2.0/usage/troubleshooting/faq

Formatting is messed up - content is below the sidebar rather than next to it.

**Comment by caseydavenport** [comment]
@djosborne I think this is the intermittent formatting issue we were talking about.

Going to remove from v2.0, but would love to see this fixed if we have time.

**Comment by djosborne** [comment]
Fixed by #554
