### ISSUE TITLE
etcd rbac guide talks about etcd v2 in calico v3.x docs

### ISSUE THREAD

**Issue by tuminoid** [projectcalico/calico#2243]
## Expected Behavior
Documentation is correct, and up to date.

In this case, Calico 3.x uses etcd v3 API and paths, so documentation shouldn't mislead with etcd v2 notifications.

## Current Behavior
https://docs.projectcalico.org/v3.2/reference/advanced/etcd-rbac/kubernetes

```
Calico
 *   Read and write access to /calico.
 *   Calico uses the etcd v2 API so the user and roles must be created there too.
```

## Possible Solution
Explain that calico uses etcd v3, and correct prefix to allow is `/calico/` as
`etcdctl role grant-permission role --prefix=true readwrite /calico/` includes `/calico` and `/calico/*` as explained in https://coreos.com/etcd/docs/latest/op-guide/authentication.html

```
# Give read access to keys with a prefix /foo/. The prefix is equal to the range [/foo/, /foo0)
$ etcdctl role grant-permission myrolename --prefix=true read /foo/
```

## Context
I'm hardening Kubernetes installations, and came upon Calico's documentation. As documentation about etcd RBAC is rarely discussed, thus Calico documentation is the top link after one or two CoreOS links.

I'm also interested if below statement in the same page is still true, or obsoleted similarly to etcd v2 part?

```
The etcd user needs to be given the root role to perform compaction when using the etcd v3 API (this also means that Kubernetes will have full read and write access to v3 data).
```
where `user` is referring to user created for Kubernetes itself in etcd. Giving `root` role to k8s user doesn't sound like a good idea, if it is unnecessary.

**Comment by caseydavenport** [comment]
@tuminoid thanks for point this out.

> The etcd user needs to be given the root role to perform compaction when using the etcd v3 API (this also means that Kubernetes will have full read and write access to v3 data).

Kubernetes does perform compaction on etcdv3 clusters. In fact, Calico also does by default (though it can be disabled). We should probably point out that when sharing an etcd, Calico should be configured to disable etcd compaction. Kubernetes, it seems, cannot be configured to disable this: https://github.com/kubernetes/kubernetes/issues/46705#issuecomment-313411837

**Comment by tuminoid** [comment]
Thanks for the quick reply!

In which Calico version was COMPACTION_PERIOD setting added?

**Comment by caseydavenport** [comment]
The COMPACTION_PERIOD option was introduced in Calico v3.0 - looks like it defaults to 10m

https://github.com/projectcalico/kube-controllers/blob/release-v3.0/pkg/config/config.go#L29
