### ISSUE TITLE
Calico can't run as I want, under the guidance of official documents.

### ISSUE THREAD

**Issue by xuhui98** [projectcalico/calico#2252]
Calico can't run as I want, under the guidance of official documents.
[Installing with the Kubernetes API datastore—50 nodes or less](https://docs.projectcalico.org/v3.2/getting-started/kubernetes/installation/calico)

## Expected Behavior
Calico can run normally under the guidance of official documents.

## Current Behavior
Executing commands entirely in accordance with official documents causes the container to be unable to communicate with the outside internet, even if the containers are connected.

## Possible Solution
Modify the configuration of CIDR in ippool configuration file.

## Steps to Reproduce (for bugs)

1. Create calico based on this [section](https://docs.projectcalico.org/v3.2/getting-started/kubernetes/installation/calico) of official documents.

*Unless your CIDR is 192.168.0.0/16, this problem may not recur, but I believe most environments have different cidrs, and the documentation should specify this.*

## Context
> How has this issue affected you?

The container in k8s cluster can't communicate with the outside internet.

## Your Environment

* Calico version v3.2.3
* Orchestrator version (e.g. kubernetes, mesos, rkt): kubernetes
* Operating System and version: Centos7.2

**Comment by caseydavenport** [comment]
@xuhui98 when I follow those documents, my pods are able to access the internet.

Have you identified why your pods are unable to? Does the CIDR of your host overlap with Calico's default?

I believe @emanic is working on a docs update to address that scenario.

**Comment by xuhui98** [comment]
> Does the CIDR of your host overlap with Calico's default?
yes

> Have you identified why your pods are unable to? 
Is it because my host cidr overlaps with the cidr in calico that the container network does not have the proper NAT to communicate with the outside internet?

**Comment by emanic** [comment]
We have made some updates in the master directory to clean up some of the content around the CIDR and let people know how to modify the default CIDR. @caseydavenport  https://docs.projectcalico.org/master/getting-started/kubernetes/installation/calico#installing-with-the-kubernetes-api-datastore50-nodes-or-less

In the requirements, we do state that the CIDRs cannot overlap. This has been in place for some time. https://docs.projectcalico.org/master/getting-started/kubernetes/requirements#ip-pool-configuration

**Comment by caseydavenport** [comment]
> Is it because my host cidr overlaps with the cidr in calico that the container network does not have the proper NAT to communicate with the outside internet?

Yeah, I think that's it. 

I think the docs that @emanic linked to show the steps for modifying the CIDR range used by Calico. I don't think we can change the default CIDR in a way that will work for everyone, but we should make it clear that it may need to be changed if it overlaps.

**Comment by xuhui98** [comment]
> I think the docs that @emanic linked to show the steps for modifying the CIDR range used by Calico. I don't think we can change the default CIDR in a way that will work for everyone, but we should make it clear that it may need to be changed if it overlaps.

OK, I can understand. And thank you @caseydavenport @emanic .
