### ISSUE TITLE
calico route incorrect in ipv6 when delete ip on nic

### ISSUE THREAD

**Issue by hangzhouwanjun** [projectcalico/calico#2254]
In ipv6, when delete ip from nic, calico route is incorrect.

before delele ip:
use "ip -6 route show":
8888:8888::6800/122 via 2000:1691::81 dev eth0 proto bird metric 1024 pref medium
8888:8888::8700/122 via 2000:1691::82 dev eth0 proto bird metric 1024 pref medium

after use "ip addr del 2000:1691::90/64 dev eth0":
use "ip -6 route show":
8888:8888::6800/122 via 2000:1691::1 dev eth0 proto bird metric 1024 pref medium
8888:8888::8700/122 via 2000:1691::1 dev eth0 proto bird metric 1024 pref medium

2000:1691::1 is default gateway

## Expected Behavior

The calico routes should be there stably. When delete ip, calico route don't change
and i can ping pod ip successly
## Current Behavior

When delete ip, calico route change
## Steps to Reproduce (for bugs)

1.  ip addr add 2000:1691::90/64 dev eth0
2.  ip -6 route show
3. ip addr del 2000:1691::90/64 dev eth0
4. ip -6 route show

## Your Environment

* Calico version
   etcd:v3.2.18
   calico/node:v3.2.3
   calico/cni:v3.2.3
   calico/kube-controllers:v3.2.3

* Orchestrator version (e.g. kubernetes, mesos, rkt):
   kubernetes v1.11.2
* Operating System and version:
* Link to your project (optional):

**Comment by caseydavenport** [comment]
@hangzhouwanjun what other routes are present in the routing table? Might it have been using the deleted route to resolve the routes learned over BGP?

 Is this using a BGP mesh or have you configured BGP peering to a TOR / Route reflector?

**Comment by hangzhouwanjun** [comment]
if i delete default gw and delete one IPv6 address, two route will change, such as:
unreachable 8888:8888::6800/122 dev lo proto bird metric 1024 error -113 pref medium
unreachable 8888:8888::8700/122 dev lo proto bird metric 1024 error -113 pref medium
but when i add IPv6 address, these two route will recovery.
The whole process, i tcpdump the bgp packets, not UPDATE packets, only KEEPALIVE packets, the bgp not disconnect .
why calico will use lo as dev in route when i delete one IPv6 address even through nic has two IPv6 address.

**Comment by tmjd** [comment]
@hangzhouwanjun do you have any update on this issue?
I'm trying to understand which routes are the "calico" routes in your examples but cannot tell which you believe Calico to own and which are system routes that calico is not responsible for.

Have you tried with a more recent Calico version to see if that resolves the issue.
