### ISSUE TITLE
CoreDNS CrashLoopBackoff with kubeadm on Ubuntu 18.04 

### ISSUE THREAD

**Issue by cvandesande** [projectcalico/calico#2256]
## Expected Behavior
CoreDNS Running

## Current Behavior
CoreDNS CrashLoopBackOff - endless

**Environment**:
- **Calico version**: 3.1, 3.2, 3.3
- **Kubernetes version** : 1.12.1
- **Cloud provider or hardware configuration**: libvirt VM
- **OS** (e.g. from /etc/os-release): Ubuntu 18.04.1 LTS
- **Kernel** (e.g. `uname -a`): 4.15.0-1023-kvm #23-Ubuntu

## Possible Solution
Use a different kubernetes CNI add-on or disable loop detection plugin in CoreDNS or use CentOS 7 as base OS

## Steps to Reproduce (for bugs)
1. Use libvirt qcow2 image: https://cloud-images.ubuntu.com/bionic/current/bionic-server-cloudimg-amd64.img
2. Use [cloud-init.txt](https://github.com/kubernetes/kubeadm/files/2511179/cloud-init.txt) for userdata
3. `kubeadm init --pod-network-cidr=10.244.0.0/16`
4. Follow kubeadm single master cluster guide [here](https://kubernetes.io/docs/setup/independent/create-cluster-kubeadm/). Select and follow the Calico network-addon option, making sure to edit and replace 192.168.0.0/16 with 10.244.0.0/16 in the final calico.yaml. (This is necessary for me as my local libvirt network overlaps with 192.168.0.0/16

## Context
Similar to kubeadm issue [#1162](https://github.com/kubernetes/kubeadm/issues/1162) but reproducible

I'm working on a fully-automated build with Terraform in order to teach myself kubernetes

The CrashLoopBackOff is caused by the CoreDNS loop plugin detecting a DNS loop, however I believe that message is erroneous. I know it's not my DNS arrangement because the same versions of kubeadm/coredns/calico work on CentOS 7. Just not with Ubuntu.  Also, if I replace Calico with Flannel, I cannot reproduce this problem on Ubuntu. So it's possibly a bug with Calico or CoreDNS, but I thought I'd start here since CoreDNS is working with Flannel in the same environment.

Finally, I've tested this without using systemd-resolved (just using a flat /etc/resolv.conf) as I know there have been issues with kubelet/coredns having loop errors in that environment, however it does not solve the problem for me.

**Comment by caseydavenport** [comment]
@cvandesande do you have network manager enabled on your nodes?

**Comment by cvandesande** [comment]
> 
> 
> @cvandesande do you have network manager enabled on your nodes?

Sorry for the delay, had to redeploy to check. Looks like cloud image of Ubuntu uses a combination of systemd-networkd and netplan.  My master instance got its network configuration through cloud-init > netplan > systemd-networkd

root@kube-master:~# cat /etc/netplan/50-cloud-init.yaml
```network:
    version: 2
    ethernets:
        ens3:
            dhcp4: true
            match:
                macaddress: 16:ff:f6:8c:46:02
            set-name: ens3
```

**Comment by caseydavenport** [comment]
I haven't been able to reproduce this, albeit I also haven't set up an exact replication of the described environment.

Anyone else have ideas on what could be going on here?

**Comment by srikiz** [comment]
Yes, I faced the same CoreDNS Loop issue with Ubuntu 18.04. I used a quick fix, removed loop from the configmap in CoreDNS and that did the trick.
However, this git issue talks about it using this

> --extra-config=kubelet.resolv-conf=/var/run/systemd/resolve/resolv.conf

FYI - https://github.com/coredns/coredns/issues/2087
