### ISSUE TITLE
usage/external-connectivity links to orchestrator-connectivity guides that don't exist

### ISSUE THREAD

**Issue by caseydavenport** [projectcalico/calico#226]
http://docs.projectcalico.org/v2.0/usage/external-connectivity

Links to orchestrator specific information that doesn't exist.

This doc should at least include information on options for this in Kubernetes (there are a few), or we should create a new doc which discusses this in a Kubernetes specific section.

**Comment by caseydavenport** [comment]
Also on this page:

- Our get in touch link shouldn't be to an old blog post.

**Comment by robbrockbank** [comment]
@caseydavenport :   Is there someone better placed than me to write the k8s guide on external connectivity?

**Comment by caseydavenport** [comment]
@robbrockbank something we need to decide.  At the moment we've got all the per-orch stuff in getting started, so maybe it needs to go there.

**Comment by caseydavenport** [comment]
Moving this to v2.0.1.

The Kubernetes stuff especially is likely pretty minimal at this point in time - Calico works with all the standard documented k8s approaches.
