### ISSUE TITLE
Document IPv6 use case of Calico with Docker

### ISSUE THREAD

**Issue by robbrockbank** [projectcalico/calico#227]
This will require the libnetwork plugin to support IPv6 (which it currently does not)

**Comment by caseydavenport** [comment]
This depends on https://github.com/projectcalico/libnetwork-plugin/issues/72

**Comment by tomdee** [comment]
IPv6 support won't be in v2.0.0 - let's make that clear in the relevant doc.

**Comment by djosborne** [comment]
IPv6 support was restored by https://github.com/projectcalico/libnetwork-plugin/issues/72

We should revisit documentation and make sure it sufficiently covers how to use this.

**Comment by bjwbell** [comment]
IPv6 usage to include in docs [libnetwork-plugin/README.md#ipv6-usage](https://github.com/projectcalico/libnetwork-plugin/blob/master/README.md#ipv6-usage).

**Comment by caseydavenport** [comment]
Closing this as stale.
