### ISSUE TITLE
Docker in cloud environment guides need updating for new calicoctl

### ISSUE THREAD

**Issue by robbrockbank** [projectcalico/calico#228]
The following guides need updating to replace the `calicoctl profile` commands with the new style calicoctl resources.

- [ ] Docker on GCE
- [ ] Docker on AWS
- [ ] Docker on Digital Ocean

**Comment by djosborne** [comment]
Would like to see #220 resolved first so we don't waste time fixing docs here that are going to get removed anyways

**Comment by djosborne** [comment]
Or address during #285

**Comment by djosborne** [comment]
All three of those guides have been removed by #285 , so closing
