### ISSUE TITLE
Felix should pass round IP addresses as netaddr structures

### ISSUE THREAD

**Issue by plwhite** [projectcalico/calico#229]
There is a lot of code that passes around IP addresses in Felix, and which validates them using netaddr. That's a bit tedious; probably better to just pass round the structures instead.

**Comment by fasaxc** [comment]
Normally, I'd argue strongly for this but I was a bit worried about the occupancy impact that this might have (and that it might generate lots of overhead until we do the "reified tags" enhancement) so I didn't do it in etcd felix:

```
>>> ip = netaddr.IPNetwork("::")
>>> sys.getsizeof(ip.__dict__) + sys.getsizeof(ip)
368
```

If we do start using it, I recommend limiting it to our "active" objects: ProfileRules, Endpoint etc and keeping the indexes in json dict format as we do now.

**Comment by Lukasa** [comment]
@fasaxc Surely that's a bit of a scary premature optimisation.

**Comment by fasaxc** [comment]
@Lukasa maybe, but we had potential customers talking about 10MB of occupancy being an issue :-/  Let's circle back on this as part of cleanup in 0.17?

**Comment by Lukasa** [comment]
Sounds good to me.

**Comment by lxpollitt** [comment]
I agree with @fasaxc that we need to be very conscious of occupancy in Felix.  I had another person approach me at ContainerCamp SF specifically to ask about per-node occupancy.  So we are hearing this from multiple sources.

**Comment by lxpollitt** [comment]
Also, while we are in MVP mode, I would advocate "if it ain't broke, don't fix it" unless we were convinced that making the change would pay for itself in time saved between now and 1.0.

**Comment by fasaxc** [comment]
We definitely do need to canonicalise IP addresses (#357), which we can sidestep if the canonical version is a netaddr object.

**Comment by fasaxc** [comment]
Did some experiments here, IPAddress uses `__slots__` so it's as space efficient as a string.  IPNetwork appears to have a bug that prevents its slots from taking effect: https://github.com/drkjam/netaddr/pull/92

**Comment by fasaxc** [comment]
netaddr accepted my patch so IPNetwork is now more efficient, like IPAddress.

I measure a string representation of an IP network at 64 bytes for an IPv4 address string vs about 103 bytes for an IPNetwork object.  For IPv6, it's 79 vs 126.  (Measured by creating 1m of each and measuring memory usage change of the process.)

**Comment by plwhite** [comment]
I'm honestly struggling to see the benefit of this - feels to me like we should not do this unless it has a significant benefit in code terms.

**Comment by eepyaich** [comment]
@fasaxc Given other recent changes, is this issue still relevant?

**Comment by fasaxc** [comment]
Closing this because it's a WIBNI with slight occupancy hit.
