### ISSUE TITLE
Update rkt guides

### ISSUE THREAD

**Issue by robbrockbank** [projectcalico/calico#229]
To use new calicoctl, update installation procedure, and test

**Comment by robbrockbank** [comment]
- [ ] Update Vagrant Install
- [ ] Update Tutorial (uses vagrant install)
- [ ] Add Installation requirements
- [ ] Add Manual Installation guide
- [ ] Update Tutorial to offer choice of installation options

**Comment by caseydavenport** [comment]
@robbrockbank can this be closed?

**Comment by djosborne** [comment]
@robbrockbank What's the plan for the rkt upgrade guide? It's still "Coming Soon"

**Comment by robbrockbank** [comment]
Upgrade doc is now removed.

Different install options and policy will be for a later version. (policy would need some CNI changes)
