### ISSUE TITLE
calico-node container is unable to connect to calico-etcd

### ISSUE THREAD

**Issue by sd2k** [projectcalico/calico#2297]
I'm trying to add a new node to our fairly old Kubernetes cluster (v1.8.5) using kubeadm. It's always worked fine in the past, but now I'm encountering errors in the calico-node pods which are unable to reach the calico-etcd pod. I'm not familiar enough with this part of the stack to figure out how the pod _should_ be able to connect, though.

## Expected Behavior
calico-node container should be able to communicate with calico-etcd's endpoint.

## Current Behavior
The calico-node container times out when trying to connect to calico-etcd:

```
➜  ~ kubectl logs calico-node-hh694 calico-node
time="2018-11-08T11:00:11Z" level=info msg="NODENAME environment not specified - check HOSTNAME"
time="2018-11-08T11:00:11Z" level=info msg="Loading config from environment"
Skipping datastore connection test
ERROR: Unable to access datastore to query node configuration
Terminating
time="2018-11-08T11:00:41Z" level=info msg="Unhandled error: client: etcd cluster is unavailable or misconfigured; error #0: client: endpoint http://10.96.232.136:6666 exceeded header timeout
"
time="2018-11-08T11:00:41Z" level=info msg="Unable to query node configuration" Name=psu error="client: etcd cluster is unavailable or misconfigured; error #0: client: endpoint http://10.96.232.136:6666 exceeded header timeout
"
Calico node failed to start
```

## Possible Solution
Not sure - I'm not sure at which point these routes are supposed to be created.

## Steps to Reproduce (for bugs)
I can try to provide this if required, but I'm encountering this error when running step 4 of this guide: https://v1-8.docs.kubernetes.io/docs/setup/independent/create-cluster-kubeadm/#44-joining-your-nodes. 

## Your Environment

* Calico version: inside the daemon set, calico/node container is v1.3.0; calico/cni container is v1.9.1
* Orchestrator version (e.g. kubernetes, mesos, rkt): Kubernetes 1.8.5
* Operating System and version: Ubuntu 16.04

I know all of these versions are quite old which may make debugging trivial; we're working on upgrading the cluster separately. Any advice would be hugely appreciated!

**Comment by caseydavenport** [comment]
@sd2k it looks like it's failing to reach the etcd cluster. I think the most likely culprit is kube-proxy - is it up and running properly on that node?

**Comment by sd2k** [comment]
That was exactly it! It looks like we switched from running kube-proxy as a daemonset to a systemd service a while ago and I hadn't got the memo. After setting that up, everything works as expected. Thanks a lot!
