### ISSUE TITLE
Update / write troubleshooting guides with focus on specific orchestrators

### ISSUE THREAD

**Issue by robbrockbank** [projectcalico/calico#230]
Need orchestrator specific troubleshooting guides

- [ ] Mesos
- [ ] Docker
- [ ] rkt
- [ ] k8s

**Comment by gunjan5** [comment]
- [ ] one more thing to add to the t-shooting guide: how to properly delete a node, see below:

human starts a calico-node with a wrong IP (172.17.8.101) by mistake (on host: calico-01), human realizes and deletes the calico-node on calico-01
```
$ docker rm -f 3ab
3ab
```
:) 

human tries to start calico-node on another host with that IP (172.17.8.101) on the correct host (calico-02) now, but he can't: 
```
$ sudo ETCD_ENDPOINTS=http://$MANAGER_IP:2379 calicoctl node run --ip=$NODE_IP
Running command to load modules: modprobe -a xt_set ip6_tables
Enabling IPv4 forwarding
Enabling IPv6 forwarding
Increasing conntrack limit
Removing old calico-node container (if running).
Running the following command to start calico-node:

docker run --net=host --privileged --name=calico-node -d --restart=always -e IP=172.17.8.102 -e ETCD_ENDPOINTS=http://172.17.8.101:2379 -e ETCD_AUTHORITY= -e ETCD_SCHEME= -e NODENAME=calico-02 -e CALICO_NETWORKING_BACKEND=bird -e NO_DEFAULT_POOLS= -e CALICO_LIBNETWORK_ENABLED=true -v /var/run/calico:/var/run/calico -v /lib/modules:/lib/modules -v /var/log/calico:/var/log/calico -v /run/docker/plugins:/run/docker/plugins -v /var/run/docker.sock:/var/run/docker.sock calico/node:latest

Image may take a short time to download if it is not available locally.
Container started, checking progress logs.
Waiting for etcd connection...
Using IPv4 address from IP environment: 172.17.8.102
No IPv6 address configured
Using global AS number
ERROR: IP address 172.17.8.102 is already in use by host calico-01. Calico requires each compute host to have a unique IP. If this is your first time running the Calico node on this host, ensure that another host is not already using the same IP address.
Error executing command: calico/node has terminated, check logs for details
```

human sad :( 

troubleshooting guide should include how to delete a node with calicoctl to properly release the IP:
```
$ sudo ETCD_ENDPOINTS=http://$MANAGER_IP:2379 calicoctl delete node calico-01
Successfully deleted 1 'node' resource(s)
```

**Comment by djosborne** [comment]
Another thing to include in troubleshooting guides: steps to quickly diagnose you've bound to the wrong IP. I just hit this - I checked the routing table and saw /26's and assumed i was good, but those were the blackhole routes. Troubleshooting should explain the real /26's that should be there, and should of course tell users to ensure their bgp sessinos are established

**Comment by caseydavenport** [comment]
@gunjan5 not sure if that belongs in a troubleshooting guide.

Probably belongs in the "usage" section as a guide for cleaning up a node.

**Comment by djosborne** [comment]
I took a first crack at this in #201  but closed it out since it seems some more planning is required before jumping in. Just mentioning it so we don't lose track of that work in case any of it is useful when we try again.
