### ISSUE TITLE
I use calico3.3.1 ,node have some problem!

### ISSUE THREAD

**Issue by liaoqiArno** [projectcalico/calico#2308]
` kubectl -n kube-system describe  pod  calico-node-zsfcj`

-   Type     Reason     Age                From                  Message
  ----     ------     ----               ----                  -------
  Normal   Scheduled  25m                default-scheduler     Successfully assigned kube-system/calico-node-zsfcj to k8s-node131
  Normal   Pulled     25m                kubelet, k8s-node131  Container image "quay.io/calico/cni:v3.3.1" already present on machine
  Normal   Created    25m                kubelet, k8s-node131  Created container
  Normal   Started    25m                kubelet, k8s-node131  Started container
  Warning  Unhealthy  25m                kubelet, k8s-node131  Readiness probe failed: calico/node is not ready: felix is not ready: Get http://localhost:9099/readiness: dial tcp [::1]:9099: connect: connection refused
  Normal   Created    25m (x2 over 25m)  kubelet, k8s-node131  Created container
  Normal   Started    25m (x2 over 25m)  kubelet, k8s-node131  Started container
  Normal   Pulled     25m (x2 over 25m)  kubelet, k8s-node131  Container image "quay.io/calico/node:v3.3.1" already present on machine
  Warning  Unhealthy    25m                kubelet, k8s-node131  Readiness probe failed: calico/node is not ready: BIRD is not ready: Error querying BIRD: unable to connect to BIRDv4 socket: dial unix /var/run/bird/bird.ctl: connect: no such file or directory

**Comment by liaoqiArno** [comment]
kubectl -n kube-system describe pod calico-node-ggnvv
`Events:
  Type     Reason     Age                From                  Message
  ----     ------     ----               ----                  -------
  Normal   Scheduled  27m                default-scheduler     Successfully assigned kube-system/calico-node-ggnvv to k8s-node132
  Normal   Pulled     27m                kubelet, k8s-node132  Container image "quay.io/calico/cni:v3.3.1" already present on machine
  Normal   Created    27m                kubelet, k8s-node132  Created container
  Normal   Started    27m                kubelet, k8s-node132  Started container
  Normal   Pulled     27m (x2 over 27m)  kubelet, k8s-node132  Container image "quay.io/calico/node:v3.3.1" already present on machine
  Normal   Created    27m (x2 over 27m)  kubelet, k8s-node132  Created container
  Normal   Started    27m (x2 over 27m)  kubelet, k8s-node132  Started container
  Warning  Unhealthy  27m (x2 over 27m)  kubelet, k8s-node132  Readiness probe failed: calico/node is not ready: felix is not ready: Get http://localhost:9099/readiness: dial tcp [::1]:9099: connect: connection refused`

I don't know how I resolve it.

**Comment by caseydavenport** [comment]
@liaoqiArno can you do a `kubectl logs` on that pod? It will hopefully show an indication of why Felix isn't ready.
