### ISSUE TITLE
Calico assigning broadcast IP to PODS

### ISSUE THREAD

**Issue by parthibanethiraj** [projectcalico/calico#2329]
Setup details:
[root@clcmapp-target1 ~]$ calicoctl version
Client Version:    v3.1.3
Build date:        2018-05-30T17:15:59+0000
Git commit:        231083c2
Cluster Version:   v3.1.3
Cluster Type:      k8s
[root@clcmapp-target1 ~]$ kubelet --version
Kubernetes v1.11.2
[root@clcmapp-target1 ~]$ calicoctl get  ippool
NAME                 CIDR                 
192-168-1-0-24       192.168.1.0/24       
2001-db8-1234---64   2001:db8:1234::/64   

With this setup, my assumption is calico ipam should not assign 192.168.1.255 Ip to any pod, as this is default broadcast address for the subnet. 

But I can see this IP assigned to a pod
[root@clcmapp-target1 /etc/cni/multus]$ kubectl get pods -n bhuvan-cmserver -o wide | grep kafka
bhuvan-cscf-kafka-1 7/7 Running 1 2h 192.168.1.255 clcmapp-target2 <none>

## Expected Behavior
Default Broadcast IP should not be assigned

## Current Behavior
Broadcast IP is assigned to a pod by calico IPAM

## Possible Solution
NA

## Steps to Reproduce (for bugs)
Sporadic

## Your Environment
[root@clcmapp-target1 ~]$ calicoctl version
Client Version:    v3.1.3
Build date:        2018-05-30T17:15:59+0000
Git commit:        231083c2
Cluster Version:   v3.1.3
Cluster Type:      k8s
[root@clcmapp-target1 ~]$ kubelet --version
Kubernetes v1.11.2

[root@clcmapp-target1 ~]$ cat /etc/redhat-release 
Red Hat Enterprise Linux Server release 7.5 (Maipo)

**Comment by caseydavenport** [comment]
@parthibanethiraj this is OK, since Calico uses "point-to-point" routed network.

See the FAQ https://docs.projectcalico.org/v3.3/usage/troubleshooting/faq

Also, this older issue: https://github.com/projectcalico/calico/issues/1710
