### ISSUE TITLE
K8S quickstart docs need a landing page 

### ISSUE THREAD

**Issue by lwr20** [projectcalico/calico#233]
There are lots of Kubernetes install docs.  But what are they all and why would you choose one over the other? 

The overview page needs to refer to the new Hosted install types, explain the pros and cons of each.

**Comment by caseydavenport** [comment]
Assuming you're referring to this guy: http://docs.projectcalico.org/v2.0/getting-started/kubernetes/installation/

I've got a fix in the works.

**Comment by lwr20** [comment]
I was thinking of here actually: http://docs.projectcalico.org/v2.0/getting-started/kubernetes/

**Comment by caseydavenport** [comment]
See #18 for my WIP

**Comment by djosborne** [comment]
Fixed by #268
