### ISSUE TITLE
how to remove calico from kube-system 

### ISSUE THREAD

**Issue by snehalbiche** [projectcalico/calico#2331]
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Calico version
* Orchestrator version (e.g. kubernetes, mesos, rkt):
* Operating System and version:
* Link to your project (optional):

**Comment by caseydavenport** [comment]
`kubectl delete -f calico.yaml` will do it

**Comment by snehalbiche** [comment]
Thanks :)
