### ISSUE TITLE
calico with k8s container start fail

### ISSUE THREAD

**Issue by theDEADpool** [projectcalico/calico#2336]
I want to deploy calico in k8s, But containers of calico can not startup successfully with this err:
kubectl log calico-kube-controllers-85cf9c8b79-fb9jr -n kube-system
log is DEPRECATED and will be removed in a future version. Use logs instead.
2018-12-07 06:23:46.318 [INFO][1] main.go 75: Loaded configuration from environment config=&config.Config{LogLevel:"info", ReconcilerPeriod:"5m", CompactionPeriod:"10m", EnabledControllers:"policy,namespace,serviceaccount,workloadendpoint,node", WorkloadEndpointWorkers:1, ProfileWorkers:1, PolicyWorkers:1, NodeWorkers:1, Kubeconfig:"", HealthEnabled:true}
2018-12-07 06:23:46.318 [FATAL][1] main.go 87: Failed to start error=failed to build Calico client: could not initialize etcdv3 client: open /calico-secrets/etcd-cert/etcd.pem: no such file or directory

## Operating steps
I start a TLS enabled etcd service with ca.pem\etcd.pem\etcd-key.pem which are generated by cassl and
start a k8s cluster successfully.
[root@k8s-m common-package]# netstat -plnt | grep etcd
tcp        0      0 192.168.206.37:2379        0.0.0.0:*               LISTEN      2979/etcd           
tcp        0      0 127.0.0.1:2379          0.0.0.0:*               LISTEN      2979/etcd           
tcp        0      0 192.168.206.37:2380        0.0.0.0:*               LISTEN      2979/etcd

then deploy Calico following this guide https://docs.projectcalico.org/v3.3/getting-started/kubernetes/installation/calico "Installing with the etcd datastore"

1. Get calico.yaml by run "curl \
https://docs.projectcalico.org/v3.3/getting-started/kubernetes/installation/hosted/calico.yaml \
-O"

2.Modify these configurations in calico.yaml
etcd_endpoints: "https://192.168.206.37:2379"
etcd_ca: "/calico-secrets/etcd-ca/ca.pem"
etcd_cert: "/calico-secrets/etcd-cert/etcd.pem"
etcd_key: "/calico-secrets/etcd-key/etcd-key.pem"

3.Create paths "/calico-secrets/etcd-ca/" "/calico-secrets/etcd-cert/" "/calico-secrets/etcd-key/" in both k8s master machine and node machine, and copy these ca.pem\etcd.pem\etcd-key.pem three files from etcd config file.

4.run "kubectl apply -f \
https://docs.projectcalico.org/v3.3/getting-started/kubernetes/installation/rbac.yaml"

5.kubectl apply -f calico.yaml

## Environment
* Calico version 3.3
* K8s version 1.12.2
* Operating System and version:
centos7
Linux k8s-m 3.10.0-862.14.4.el7.x86_64 #1 SMP Wed Sep 26 15:12:11 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

Also try modify these configuration as
etcd_ca: "/calico-secrets/etcd-ca"
etcd_cert: "/calico-secrets/etcd-cert"
etcd_key: "/calico-secrets/etcd-key"
but still the same issue.

**Comment by caseydavenport** [comment]
> 3.Create paths "/calico-secrets/etcd-ca/" "/calico-secrets/etcd-cert/" "/calico-secrets/etcd-key/" in both k8s master machine and node machine, and copy these ca.pem\etcd.pem\etcd-key.pem three files from etcd config file.

I think this isn't quite right - the manifest expects those to be Kubernetes secrets, not copied onto the host machine.

**Comment by huzhou520** [comment]
How to resolve?
