### ISSUE TITLE
Implement ERROR  as log_level in Calico v3.0

### ISSUE THREAD

**Issue by lunaimaginea** [projectcalico/calico#2337]
## Expected Behavior
Currently the log level can be set by the CNI configuration management file .The supported log_level parameter values are INFO, DEBUG, WARNING.

## Current Behavior
It should also have ERROR as log_evel to be set in production deployments.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment
* Calico version v3.0
* kubernetes

**Comment by caseydavenport** [comment]
@lunaimaginea it should support error as a valid level. Is this missing in the docs perhaps?

**Comment by lunaimaginea** [comment]
The docs is saying that the valid log levels are INFO, DEBUG, WARNING.I think so because the library used is logrus and it is supporting the ERROR.
