### ISSUE TITLE
high load after upgrading from v2.6.5 to v3.3.0

### ISSUE THREAD

**Issue by mattdgsg** [projectcalico/calico#2338]
We're in the midst of upgrading our Kubernetes clusters from Calico v2.6.5 to v3.3.0. The upgrades have gone smoothly, but we're seeing increased load across the board on every upgraded node. More specifically: we're seeing peaks in the vicinity of x2 core capacity every seven hours. (And I'm not sure that the seven hours thing is significant, btw, after [reading this](https://blog.avast.com/investigation-of-regular-high-load-on-unused-machines-every-7-hours).) And it appears to be calico-node driving the load ... I deleted the calico/node image and prevented it from being pulled again on one of the hosts, so that calico-node wasn't running at all, and our load metrics flattened out.

I'm not seeing any correlated disk latency or swapping or memory spikes or CPU activity. I haven't found anything in the logs to suggest connection errors or anything like that. Many of the machines on which we're seeing this problem are basically idle, apart from the usual Kube / Calico stuff.

## Expected Behavior
Resource usage comparable to v2.6.5

## Current Behavior
Higher than expected load on all Kube nodes, even ones that are mostly idle

## Possible Solution
Places I can look to troubleshoot and / or tunable settings I can try

## Steps to Reproduce (for bugs)
Upgrade from v2.6.5 to v3.3.0

## Your Environment
* OS is CentOS 7 (fully patched)
* Orchestrator is Kube v1.11
* BGP mesh is disabled, two global BGP peers
* etcd is a standalone DS (v3.1.10)

**Comment by andrestc** [comment]
I'm facing a similar issue after upgrading from v3.0.5 to v3.3.1.

**Comment by caseydavenport** [comment]
I'm not aware of any known issues that might cause this. 

Are you seeing higher CPU usage in steady state, or just at this 7 hour interval?

**Comment by caseydavenport** [comment]
Potentially related: https://github.com/projectcalico/confd/pull/234

Can you see if the load is coming from confd?

**Comment by mattdgsg** [comment]
I'm not seeing the BGP recompute every 10 seconds when I enable debug logging. I _am_ seeing the dataplane sync kick off every 10 seconds, but AFAICT that's expected behavior.

**Comment by rikatz** [comment]
I'm facing the same issue. The high usage come from Felix and not confd.

Got some CPU pprof from Felix (kill SIGUSR2) and this is the result:

```
top
Showing nodes accounting for 14770ms, 74.18% of 19910ms total
Dropped 269 nodes (cum <= 99.55ms)
Showing top 10 nodes out of 104
      flat  flat%   sum%        cum   cum%
    4680ms 23.51% 23.51%    10030ms 50.38%  runtime.scanobject
    1800ms  9.04% 32.55%    12440ms 62.48%  runtime.gcDrain
    1730ms  8.69% 41.24%     1750ms  8.79%  syscall.Syscall6
    1680ms  8.44% 49.67%     1680ms  8.44%  runtime.markBits.isMarked (inline)
    1660ms  8.34% 58.01%     1800ms  9.04%  runtime.findObject
    1480ms  7.43% 65.44%     3370ms 16.93%  runtime.greyobject
```

```
Showing nodes accounting for 9310ms, 72.96% of 12760ms total
Dropped 229 nodes (cum <= 63.80ms)
Showing top 10 nodes out of 111
      flat  flat%   sum%        cum   cum%
    3050ms 23.90% 23.90%     6450ms 50.55%  runtime.scanobject
    1100ms  8.62% 32.52%     1100ms  8.62%  runtime.markBits.isMarked (inline)
    1030ms  8.07% 40.60%     2240ms 17.55%  runtime.greyobject
    1010ms  7.92% 48.51%     7870ms 61.68%  runtime.gcDrain
```

If necessary I can attach the pprof files somewhere else. I might also run this in all our environment to help investigation

**Comment by fasaxc** [comment]
@rikatz How big is your cluster?  Nodes? Pods?  What datastore driver are you using?  Are you running Typha?

**Comment by fasaxc** [comment]
Also, is this still an issue with the current supported version (v3.6)?

**Comment by fasaxc** [comment]
From the pprof output you shared, looks like a GC issue; try setting the `DebugMemoryProfilePath` config param and then dumping a memory profile by sending Felix a SIGUSR1 after you see the problem.  Note: the profile will be dumped to the path inside Felix's container so you'll need to retrieve it.

**Comment by rikatz** [comment]
@fasaxc It's Calico 3.6.

My environment is pretty big: 8 baremetal nodes with 48 CPUs and 768Gb of RAM + some minor but tainted nodes.

The heavy load is into the baremetal nodes, with 300+ PODs running in each of them. The total is 2800 PODs across the 8 Baremetal Nodes + some Routing HAProxy Pods running in the minor (virtual) nodes.

We're using direct ETCD as datastore driver. We're not using Typha nor KDD.

We've a pure Calico + Kube Router (for services) environment. No Kube-proxy, and Kube-router is configured as IPVS/services only.

Calico is synced with two Calico-RR that are synced with our edge router.

I'll set DebugMemoryProfilePath. This might be set into felix.cfg only, or can be some ENV?

Tks

**Comment by rikatz** [comment]
Got this strange trace:

```
     4.49s   syscall.Syscall6
             github.com/projectcalico/node/vendor/golang.org/x/sys/unix.recvfrom
             github.com/projectcalico/node/vendor/golang.org/x/sys/unix.Recvfrom
             github.com/projectcalico/node/vendor/github.com/vishvananda/netlink/nl.(*NetlinkSocket).Receive
             github.com/projectcalico/node/vendor/github.com/vishvananda/netlink/nl.(*NetlinkRequest).Execute
             github.com/projectcalico/node/vendor/github.com/vishvananda/netlink.(*Handle).AddrList
             github.com/projectcalico/node/vendor/github.com/vishvananda/netlink.AddrList
             github.com/projectcalico/node/vendor/github.com/projectcalico/felix/ifacemonitor.(*netlinkReal).AddrList
             github.com/projectcalico/node/vendor/github.com/projectcalico/felix/ifacemonitor.(*InterfaceMonitor).storeAndNotifyLinkInner
             github.com/projectcalico/node/vendor/github.com/projectcalico/felix/ifacemonitor.(*InterfaceMonitor).storeAndNotifyLink
             github.com/projectcalico/node/vendor/github.com/projectcalico/felix/ifacemonitor.(*InterfaceMonitor).resync
             github.com/projectcalico/node/vendor/github.com/projectcalico/felix/ifacemonitor.(*InterfaceMonitor).MonitorInterfaces
```

**Comment by fasaxc** [comment]
Those are large nodes but the cluster overall is small for Calico.  We don't regularly test to that many pods per node but we have done it in the past with no issues.  

You can set it as an env var in your calico-node manifest, but, as an env var it needs a prefix: `FELIX_DebugMemoryProfilePath`

FWIW, I'm not sure that Calico works with kube-router, we had to do work to support kube-proxy's IPVS mode; there's no guarantee that that will work with kube-router too.  The problems that IPVS can cause tend to be subtle: policy getting bypassed or "seeing" the wrong source IP for a packet.

> 768Gb of RAM

How much RAM is Felix using?  I'd expect it to use <100MB at your scale.

**Comment by rikatz** [comment]
About kube-router, it's working fine. Just need to ignore the interface generated to the load balance. We've replaced kube-proxy to kube-router as the proxy was generating a race condition into the environment, and also not being able to get all the services (5723 of them)

The whole Calico Container is using an average of 300Mb.

```
pmap 69
69: calico-node -felix
0000000000400000   17876K r-xp  /bin/calico-node
0000000001575000   20980K r--p  /bin/calico-node
00000000029f2000     388K rw-p  /bin/calico-node
0000000002a53000     176K rw-p    [ anon ]
000000c000000000    2048K rw-p    [ anon ]
000000c000200000    2048K rw-p    [ anon ]
000000c000400000    2048K rw-p    [ anon ]
000000c000600000    2048K rw-p    [ anon ]
000000c000800000   69632K rw-p    [ anon ]
000000c004c00000    4096K rw-p    [ anon ]
000000c005000000    2048K rw-p    [ anon ]
000000c005200000   12288K rw-p    [ anon ]
000000c005e00000    2048K rw-p    [ anon ]
000000c006000000    4096K rw-p    [ anon ]
000000c006400000    2048K rw-p    [ anon ]
000000c006600000   26624K rw-p    [ anon ]
000000c008000000   65536K rw-p    [ anon ]
00007f697bd7a000    3536K rw-p    [ anon ]
00007f697c106000   51584K rw-p    [ anon ]
00007fff0077a000     132K rw-p  [stack]
00007fff007c6000      12K r--p  [vvar]
00007fff007c9000       8K r-xp  [vdso]
ffffffffff600000       4K r-xp  [vsyscall]
mapped: 291304K
```

I'll change the Calico Manifest to contain the env and will generate it ASAP

**Comment by rikatz** [comment]
[cpu.pdf](https://github.com/projectcalico/calico/files/3112143/cpu.pdf)
[mem.pdf](https://github.com/projectcalico/calico/files/3112144/mem.pdf)

**Comment by fasaxc** [comment]
How many policies (and rules within them) do you have?  Looks like a lot of memory allocs happening in the conversion routines for policies.

**Comment by rikatz** [comment]
As we use this cluster mainly with Kubernetes, I'll dump the number of NetPolicies instead of Calico Rules :)

```
kubectl get netpol --all-namespaces |wc -l
7555
```

**Comment by fasaxc** [comment]
What do your policies look like, are they large with lots of rules?

**Comment by fasaxc** [comment]
Do the policies churn a lot?

**Comment by rikatz** [comment]
We mainly have a default-deny policy, and policies that allow Ingress to talk to the pods:

```
spec:
  ingress:
  - from:
    - ipBlock:
        cidr: 10.X.Y.0/18
    ports:
    - port: 3000
      protocol: TCP
  - from:
    - ipBlock:
        cidr: 10.X.Z.0/21
    ports:
    - port: 3000
      protocol: TCP
  podSelector:
    matchLabels:
      run: rocketchat
  policyTypes:
  - Ingress
```

**Comment by caseydavenport** [comment]
Anyone have an update on this issue? Is this still seen on newer versions of Calico? Does it happen during upgrade only or also on fresh installs?

**Comment by fasaxc** [comment]
Lots of policies, could be the kube-controllers bug we had a while ago that was causing all the policies to be rewritten continuously? https://github.com/projectcalico/kube-controllers/issues/380

**Comment by rikatz** [comment]
@caseydavenport I don’t think we still have this behavior anymore

Only problem now is the high Dataplane Apply times related to Route Apply being non concurrent (will post the issue number here later). 

@mrrandrade do we still have high calico-node cpu load and problems with iptables lock in our cluster?

**Comment by fasaxc** [comment]
Think it makes sense to close this then.  Please can you open a new issue if you're still hitting other problems (if you haven't already).
