### ISSUE TITLE
installing-with-the-etcd-datastore doc doesn't mention setting up etcd

### ISSUE THREAD

**Issue by lwr20** [projectcalico/calico#2353]
In this doc: 
https://docs.projectcalico.org/v3.4/getting-started/kubernetes/installation/calico#installing-with-the-etcd-datastore

## Expected Behavior
I'd expect the doc to talk about:
- the need to have an etcd for this to work, 
- how to customise the manifest with the information needed to connect to it if you have one 
- how to apply the quickstart etcd manifest (https://docs.projectcalico.org/v3.4/getting-started/kubernetes/installation/hosted/etcd.yaml) if you just want a quick and dirty setup to play with

Also - the manifest here:
https://docs.projectcalico.org/v3.4/getting-started/kubernetes/installation/hosted/calico.yaml
shouldn't have `etcd_endpoints: "http://10.96.232.136:6666"`, unless we talk about the quickstart etcd manifest...

**Comment by caseydavenport** [comment]
We've removed etcd.yaml from the docs, and it looks like it does explain how to replace `etcd_endpoints` now. 

I don't think we should document how to install etcd, but it is listed in the requirements section https://docs.projectcalico.org/v3.6/getting-started/kubernetes/requirements

> Calico v3.6 requires a key/value store accessible by all Calico components. On Kubernetes, you can configure Calico to access an etcdv3 cluster directly or to use the Kubernetes API datastore.

> etcd_endpoints: "http://10.96.232.136:6666", unless we talk about the quickstart etcd manifest...

No longer does :+1:
