### ISSUE TITLE
Missing links to various configuration docs

### ISSUE THREAD

**Issue by caseydavenport** [projectcalico/calico#236]
For example:

https://github.com/projectcalico/k8s-policy/blob/master/configuration.md
https://github.com/projectcalico/calico-cni/blob/master/configuration.md

These are hard to find but useful.  They should be easier to find (or moved into the calico repo)

**Comment by djosborne** [comment]
Closing since those docs were moved to docs.projectcalico. 

OK? @caseydavenport
