### ISSUE TITLE
calico-node pods readiness probe failed when any node got killed

### ISSUE THREAD

**Issue by FrostyLeaf** [projectcalico/calico#2370]
I have a k8s cluster with 3 masters and 3 nodes.

And I install calico-node following [Installing with the Kubernetes API datastore—more than 50 nodes](https://docs.projectcalico.org/v3.3/getting-started/kubernetes/installation/calico#installing-with-the-kubernetes-api-datastoremore-than-50-nodes).

```bash
$ kubectl  get node
NAME                  STATUS   ROLES    AGE   VERSION
km12-01               Ready    master   64d   v1.13.1
km12-02               Ready    master   64d   v1.13.1
km12-03               Ready    master   64d   v1.13.1
prod-k8s-node001      Ready    node     32d   v1.13.1
prod-k8s-node002      Ready    node     63d   v1.13.1
prod-k8s-tmpnode005   Ready    node     62d   v1.13.1

$ kubectl -n kube-system get po | grep calico
calico-node-bm6f6                 2/2     Running   0          13m
calico-node-jvxdp                 2/2     Running   0          13m
calico-node-kk4ph                 2/2     Running   0          13m
calico-node-r76kq                 2/2     Running   2          13m
calico-node-vrlpp                 2/2     Running   0          13m
calico-node-w4tdj                 2/2     Running   0          13m
calico-typha-5fc4874c76-qpcrs     1/1     Running   0          13m
calico-typha-5fc4874c76-v54wt     1/1     Running   0          13m
```

Now I just kill any node by stopping its docker and kubelet service to simulate an accident like one server is down, then all calico-node pods readiness probe failed:

```bash
$ kubectl  get node
NAME                  STATUS     ROLES    AGE   VERSION
km12-01               Ready      master   64d   v1.13.1
km12-02               Ready      master   64d   v1.13.1
km12-03               Ready      master   64d   v1.13.1
prod-k8s-node001      NotReady   node     32d   v1.13.1
prod-k8s-node002      Ready      node     63d   v1.13.1
prod-k8s-tmpnode005   Ready      node     62d   v1.13.1

$ kubectl -n kube-system get po -o wide | grep calico
calico-node-bm6f6                 1/2     Running   0          17m     10.42.104.113     km12-02               <none>           <none>
calico-node-jvxdp                 1/2     Running   0          17m     10.42.177.75      prod-k8s-tmpnode005   <none>           <none>
calico-node-kk4ph                 2/2     Running   0          17m     10.42.164.79      prod-k8s-node001      <none>           <none>
calico-node-r76kq                 1/2     Running   2          17m     10.42.140.154     km12-01               <none>           <none>
calico-node-vrlpp                 1/2     Running   0          17m     10.42.78.21       prod-k8s-node002      <none>           <none>
calico-node-w4tdj                 1/2     Running   0          17m     10.42.177.142     km12-03               <none>           <none>
calico-typha-5fc4874c76-qpcrs     1/1     Running   0          17m     10.42.164.79      prod-k8s-node001      <none>           <none>
calico-typha-5fc4874c76-v54wt     1/1     Running   0          17m     10.42.177.75      prod-k8s-tmpnode005   <none>           <none>

$ kubectl -n kube-system describe po calico-node-vrlpp
Name:               calico-node-vrlpp
Namespace:          kube-system
Priority:           0
PriorityClassName:  <none>
Node:               prod-k8s-node002/10.42.78.21
Start Time:         Tue, 15 Jan 2019 18:59:39 +0800
Labels:             controller-revision-hash=578d566cff
                    k8s-app=calico-node
                    pod-template-generation=2
Annotations:        scheduler.alpha.kubernetes.io/critical-pod:
Status:             Running
IP:                 10.42.78.21
Controlled By:      DaemonSet/calico-node
Containers:
  calico-node:
    Container ID:   docker://359e5e39dce70508edc30a10ead709759d546702a4b49c4673b4faefd681e652
    Image:          quay.io/calico/node:v3.3.2
    Image ID:       docker-pullable://quay.io/calico/node@sha256:eda836bf7c56e2aacaa3f5802e653a35069678b408c744866c486df8ca3df98e
    Port:           <none>
    Host Port:      <none>
    State:          Running
      Started:      Tue, 15 Jan 2019 18:59:39 +0800
    Ready:          False
    Restart Count:  0
    Requests:
      cpu:      250m
    Liveness:   http-get http://localhost:9099/liveness delay=10s timeout=1s period=10s #success=1 #failure=6
    Readiness:  exec [/bin/calico-node -bird-ready -felix-ready] delay=0s timeout=1s period=10s #success=1 #failure=3
    Environment:
      DATASTORE_TYPE:                     kubernetes
      FELIX_TYPHAK8SSERVICENAME:          <set to the key 'typha_service_name' of config map 'calico-config'>  Optional: false
      WAIT_FOR_DATASTORE:                 true
      NODENAME:                            (v1:spec.nodeName)
      CALICO_NETWORKING_BACKEND:          <set to the key 'calico_backend' of config map 'calico-config'>  Optional: false
      CLUSTER_TYPE:                       k8s,bgp
      IP:                                 autodetect
      CALICO_IPV4POOL_IPIP:               Off
      FELIX_IPINIPMTU:                    <set to the key 'veth_mtu' of config map 'calico-config'>  Optional: false
      CALICO_IPV4POOL_CIDR:               192.244.0.0/16
      CALICO_DISABLE_FILE_LOGGING:        true
      FELIX_DEFAULTENDPOINTTOHOSTACTION:  ACCEPT
      FELIX_IPV6SUPPORT:                  false
      FELIX_LOGSEVERITYSCREEN:            info
      FELIX_HEALTHENABLED:                true
    Mounts:
      /lib/modules from lib-modules (ro)
      /run/xtables.lock from xtables-lock (rw)
      /var/lib/calico from var-lib-calico (rw)
      /var/run/calico from var-run-calico (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from calico-node-token-dgq9r (ro)
  install-cni:
    Container ID:  docker://5fe86f53c4f2037bdb98e239dbdede3f81ffa1d6ed983b3b7961dd9f65d11f21
    Image:         quay.io/calico/cni:v3.3.2
    Image ID:      docker-pullable://quay.io/calico/cni@sha256:218209f4948d57ae227fb0fba3b597e99334cb39e2abb11555ec359dae177782
    Port:          <none>
    Host Port:     <none>
    Command:
      /install-cni.sh
    State:          Running
      Started:      Tue, 15 Jan 2019 18:59:39 +0800
    Ready:          True
    Restart Count:  0
    Environment:
      CNI_CONF_NAME:         10-calico.conflist
      KUBERNETES_NODE_NAME:   (v1:spec.nodeName)
      CNI_NETWORK_CONFIG:    <set to the key 'cni_network_config' of config map 'calico-config'>  Optional: false
      CNI_MTU:               <set to the key 'veth_mtu' of config map 'calico-config'>            Optional: false
    Mounts:
      /host/etc/cni/net.d from cni-net-dir (rw)
      /host/opt/cni/bin from cni-bin-dir (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from calico-node-token-dgq9r (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  lib-modules:
    Type:          HostPath (bare host directory volume)
    Path:          /lib/modules
    HostPathType:
  var-run-calico:
    Type:          HostPath (bare host directory volume)
    Path:          /var/run/calico
    HostPathType:
  var-lib-calico:
    Type:          HostPath (bare host directory volume)
    Path:          /var/lib/calico
    HostPathType:
  xtables-lock:
    Type:          HostPath (bare host directory volume)
    Path:          /run/xtables.lock
    HostPathType:  FileOrCreate
  cni-bin-dir:
    Type:          HostPath (bare host directory volume)
    Path:          /opt/cni/bin
    HostPathType:
  cni-net-dir:
    Type:          HostPath (bare host directory volume)
    Path:          /etc/cni/net.d
    HostPathType:
  calico-node-token-dgq9r:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  calico-node-token-dgq9r
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  beta.kubernetes.io/os=linux
Tolerations:     :NoSchedule
                 :NoExecute
                 CriticalAddonsOnly
                 node.kubernetes.io/disk-pressure:NoSchedule
                 node.kubernetes.io/memory-pressure:NoSchedule
                 node.kubernetes.io/network-unavailable:NoSchedule
                 node.kubernetes.io/not-ready:NoExecute
                 node.kubernetes.io/unreachable:NoExecute
                 node.kubernetes.io/unschedulable:NoSchedule
Events:
  Type     Reason     Age                 From                       Message
  ----     ------     ----                ----                       -------
  Normal   Scheduled  30m                 default-scheduler          Successfully assigned kube-system/calico-node-vrlpp to prod-k8s-node002
  Normal   Pulled     30m                 kubelet, prod-k8s-node002  Container image "quay.io/calico/node:v3.3.2" already present on machine
  Normal   Created    30m                 kubelet, prod-k8s-node002  Created container
  Normal   Started    30m                 kubelet, prod-k8s-node002  Started container
  Normal   Pulled     30m                 kubelet, prod-k8s-node002  Container image "quay.io/calico/cni:v3.3.2" already present on machine
  Normal   Created    30m                 kubelet, prod-k8s-node002  Created container
  Normal   Started    30m                 kubelet, prod-k8s-node002  Started container
  Warning  Unhealthy  30m                 kubelet, prod-k8s-node002  Readiness probe failed: calico/node is not ready: BIRD is not ready: Error querying BIRD: unable to connect to BIRDv4 socket: dial unix /var/run/bird/bird.ctl: connect: no such file or directory
  Warning  Unhealthy  20m (x42 over 27m)  kubelet, prod-k8s-node002  Readiness probe failed: calico/node is not ready: BIRD is not ready: BGP not established with 10.42.140.154
  Warning  Unhealthy  32s (x82 over 15m)  kubelet, prod-k8s-node002  Readiness probe failed: calico/node is not ready: BIRD is not ready: BGP not established with 10.42.164.79
```

## Expected Behavior

The rest aliving calico-node pods should recover after a few seconds. Or it can be really confused.

## Current Behavior

All aliving calico-node pods readiness probe failed.

## Steps to Reproduce (for bugs)

1. Deploy an HA master kubernetes cluster with ipvs mode by kubeadm.
2. Install calico-node following [Installing with the Kubernetes API datastore—more than 50 nodes](https://docs.projectcalico.org/v3.3/getting-started/kubernetes/installation/calico#installing-with-the-kubernetes-api-datastoremore-than-50-nodes).
3. Kill any node by stopping its docker and kubelet service.
4. Check calico-node pods status.

## Your Environment

* Calico version: v3.3.2
* Orchestrator version (e.g. kubernetes, mesos, rkt): kubernetes v1.13.2
* Operating System and version: Ubuntu 16.04.5 LTS (GNU/Linux 4.17.0-041700-generic x86_64)

**Comment by FrostyLeaf** [comment]
The same issue occurred to v3.4.0

**Comment by FrostyLeaf** [comment]
Does anyone help? @tmjd @fasaxc @song-jiang

**Comment by fasaxc** [comment]
@FrostyLeaf that's working as designed, Calico uses readiness to indicate that it can't contact one of the other nodes.  Once the node is deleted from the datastore, it should be resolved.  The kube-controllers pod should do that automatically once the node is removed from k8s.

We do recognise that it's sub-optimal for all calico-node's to report no ready in this scenario.  The technical reason that we do that is that, during a rolling upgrade, it's important for the BGP connection to be reestablished before the next node is restarted.

If you want to avoid this problem, you can add route reflectors to your BGP topology.  In v3.4 we added support for in-cluster router reflectors to make that easy.  Then nodes will only report unready if one of the RRs is down (which would be a problem that you'd want to know about!).

**Comment by FrostyLeaf** [comment]
Thanks for your explanation. I think I totally understand now.

**Comment by emedina** [comment]
I'm currently facing this issue during my `Disaster Recovery` testing and IMHO this poses more issues than it tries to solve.

In my DR scenario, I'm basically bringing down one node (in a simple cluster of 3 nodes) to see how everything reacts and whether I can guarantee the provision of service. Being a DR, I have absolutely no control over it, so if now Calico basically turns into a `SPoF` if just one node out of many is down, this is definitively a serious issue and unacceptable for my PROD environment, so we will have to switch to another CNI unfortunately.

Will then Calico move forward with this `SPoF` design?

**Comment by fasaxc** [comment]
@emedina I want to emphasise that Calico continues _functioning_ when a node goes down so I don't think you can call this a SPoF.  Reporting not-ready is basically the only symptom of this design choice, we don't start dropping packets and policy updates continue.

If the node is completely gone, you can delete it form the datamodel to restore the other nodes to ready.

**Comment by emedina** [comment]
Did some more research, and it looks like the issue is actually the readiness probe; however, the liveness probe works fine.

**Comment by emedina** [comment]
@fasaxc After some more research, our conclusions based on our testing is that this may be related to an issue with the `readiness probe` that bundles with Calico `v3.2`, that basically fails when one node is down, therefore not showing the overall status of the Pod as `Ready`.

This is the `readiness probe`:

```
readinessProbe:
            exec:
              command:
              - /bin/calico-node
              - -bird-ready
              - -felix-ready
```

And apparently, the test that fails is related to the `-bird-ready` flag.

Changing the `readiness probe` to something else (which we found by googling around), makes it return that the Pod is healthy, even when one node is down:

```
readinessProbe:
          failureThreshold: 3
          httpGet:
            host: localhost
            path: /readiness
            port: 9099
            scheme: HTTP
```

I would like to understand whether changing the `readiness probe` can have any hidden side effect or impact. Any feedback?

**Comment by fasaxc** [comment]
@emedina Yes, there's a hidden downside, it can cause traffic loss during a rolling upgrade.

The best solution is to upgrade to v3.4 and use the in-cluster route reflector feature so that you can disable the full mesh.  No full mesh means you won't see all nodes go non-ready when a single node fails.

**Comment by fasaxc** [comment]
@emedina Are you actually seeing any issues associated with the non-ready state?  Calico should continue functioning just fine while bird is non-ready, but hte key thing is that it's not safe to do a rolling upgrade until the failed node is removed/restored.

**Comment by emedina** [comment]
@fasaxc Can you please elaborate a bit more on the `in-cluster route reflector feature` in `v3.4`? Maybe a link to how to do it? Thanks!

**Comment by emedina** [comment]
@fasaxc Yes, I face issues with the `non-ready` state when one node is down which make my Pods not be able to resolve DNS names, for instance, or connect to other IPs in the cluster.

**Comment by emedina** [comment]
@fasaxc This is an example. See all Calico pods as `1/2`:

```
# kubectl -n kube-system get po
NAME                                       READY   STATUS    RESTARTS   AGE
calico-kube-controllers-6796f77c45-lk5fv   1/1     Running   0          44d
calico-node-2hhqf                          1/2     Running   1          21d
calico-node-4752g                          1/2     Running   1          21d
calico-node-6fc6z                          1/2     Running   1          21d
calico-node-6pcll                          1/2     Running   1          21d
calico-node-894w7                          0/2     Evicted   0          8m48s
calico-node-9jbnp                          1/2     Running   1          21d
calico-node-bvj88                          1/2     Running   1          21d
calico-node-c46sg                          1/2     Running   1          21d
calico-node-c68mg                          1/2     Running   1          21d
calico-node-cbmmw                          1/2     Running   1          21d
calico-node-dkq7b                          1/2     Running   1          21d
calico-node-fb9z8                          1/2     Running   0          21d
calico-node-fz2rz                          1/2     Running   0          46h
calico-node-gg6mc                          1/2     Running   1          21d
calico-node-lnzq2                          1/2     Running   1          21d
calico-node-n4rpb                          1/2     Running   3          21d
calico-node-nb6qg                          1/2     Running   1          21d
calico-node-qdxvp                          1/2     Running   1          21d
calico-node-s6ncs                          1/2     Running   1          21d
calico-node-xxsqc                          1/2     Running   1          21d
calico-node-zkbg6                          1/2     Running   1          21d
```

Notice the `Evicted` one? That one is making all the other ones fail the `readiness probe`.

If I try to lookup by name something, it simply does not work and I have to kill it because it gets stuck:

```
# kubectl exec -ti dnsutils-7d7db697b7-jn9ds -- nslookup kubernetes
Defaulting container name to dnsutils.
Use 'kubectl describe pod/dnsutils-7d7db697b7-jn9ds -n default' to see all of the containers in this pod.
^C
command terminated with exit code 1
```

Also trying to reach some IP doesn't work either and clearly complains about not being able to resolve DNS names:

```
# kubectl exec -ti curl-78cffbb55c-st9l7 -- curl -vvvvv http://174.16.138.170:8889/actuator/health
Defaulting container name to curl.
Use 'kubectl describe pod/curl-78cffbb55c-st9l7 -n default' to see all of the containers in this pod.
* Hostname was NOT found in DNS cache
*   Trying 174.16.138.170...
^Ccommand terminated with exit code 130
```

**Comment by fasaxc** [comment]
@emedina Where are your DNS pods running?  Were they on the node with the evicted calico/node.   If you evict calico/node then that particular node will become unreachable.

**Comment by emedina** [comment]
@fasaxc They are deployed randomly by K8s scheduler, but in this particular test case, they were not impacted by the outage.

**Comment by fasaxc** [comment]
@emedina Please can you create a new issue.  This issue is about the readiness check, which is working correctly.  Let's start a new issue about the connectivity problem you've encountered.  We'll need details of your cluster to diagnose:

- IPs of the DNS pods
- IPs of the pod with no DNS
- does the host running the pod with failing DNS have calico/node running?
- `ip route` from the host with a pod that can't reach DNS
- `iptables-save` for the host with the pod that can't reach DNS
- Why did Calico get evicted?  Calico is an essential service, you shouldn't let it get evicted.

**Comment by javendo** [comment]
Hello @fasaxc, I am testing some failover scenarios and I am facing something weird. After researching a bit I have found this ticket here and it seems almost what I am seeing.

I have a baremetal k8s cluster with 3 master where those masters are also workers. Everything is working okay but when I turn off all those machines and turn up just two of them calico is not becoming ready again because the readiness probe and my cluster stays useless. When I start the last machine the readiness probe could pass and calico becomes ready and the network is okay.

What should I need to do/configure to bypass this behavior? Is it a normal behavior? If so, don't you think it is strange because I won't have a useful cluster when that scenario occurs?

```
Kubernetes: version 1.14.1
Calico: version 3.5.3
Operational System: Centos 7.5
```

**Comment by ecroys** [comment]
> Hello @fasaxc, I am testing some failover scenarios and I am facing something weird. After researching a bit I have found this ticket here and it seems almost what I am seeing.
> 
> I have a baremetal k8s cluster with 3 master where those masters are also workers. Everything is working okay but when I turn off all those machines and turn up just two of them calico is not becoming ready again because the readiness probe and my cluster stays useless. When I start the last machine the readiness probe could pass and calico becomes ready and the network is okay.
> 
> What should I need to do/configure to bypass this behavior? Is it a normal behavior? If so, don't you think it is strange because I won't have a useful cluster when that scenario occurs?
> 
> ```
> Kubernetes: version 1.14.1
> Calico: version 3.5.3
> Operational System: Centos 7.5
> ```

**
With 2 of 3 nodes back online, we can see this in the calico logs:
```
bird: Unable to open configuration file /etc/calico/confd/config/bird.cfg: No such file or directory
bird: Unable to open configuration file /etc/calico/confd/config/bird6.cfg: No such file or directory
```

Turning on the third node, we can see this messages:
```
2019-04-29 13:21:21.916 [INFO][5051] client.go 316: Calico Syncer has indicated it is in sync
2019-04-29 13:21:21.920 [INFO][5051] resource.go 220: Target config /etc/calico/confd/config/bird6_ipam.cfg out of sync
2019-04-29 13:21:21.921 [INFO][5051] resource.go 220: Target config /etc/calico/confd/config/bird_ipam.cfg out of sync
2019-04-29 13:21:21.923 [INFO][5051] resource.go 220: Target config /etc/calico/confd/config/bird_aggr.cfg out of sync
2019-04-29 13:21:21.923 [INFO][5051] resource.go 220: Target config /tmp/tunl-ip out of sync
2019-04-29 13:21:21.924 [INFO][5051] resource.go 220: Target config /etc/calico/confd/config/bird6.cfg out of sync
2019-04-29 13:21:21.925 [INFO][5051] resource.go 220: Target config /etc/calico/confd/config/bird6_aggr.cfg out of sync
2019-04-29 13:21:21.926 [INFO][5051] resource.go 260: Target config /etc/calico/confd/config/bird6_ipam.cfg has been updated
2019-04-29 13:21:21.927 [INFO][5051] resource.go 220: Target config /etc/calico/confd/config/bird.cfg out of sync
2019-04-29 13:21:21.932 [INFO][5051] resource.go 260: Target config /etc/calico/confd/config/bird6_aggr.cfg has been updated
2019-04-29 13:21:21.934 [INFO][5051] resource.go 260: Target config /etc/calico/confd/config/bird_aggr.cfg has been updated
2019-04-29 13:21:21.940 [INFO][5051] resource.go 260: Target config /etc/calico/confd/config/bird_ipam.cfg has been updated
2019-04-29 13:21:21.944 [INFO][5051] resource.go 260: Target config /etc/calico/confd/config/bird6.cfg has been updated
2019-04-29 13:21:21.947 [INFO][5051] resource.go 260: Target config /etc/calico/confd/config/bird.cfg has been updated
bird: device1: Initializing
bird: direct1: Initializing
bird: device1: Starting
```
**

**Comment by javendo** [comment]
Probably it is related to this one https://github.com/projectcalico/calico/issues/2211

**Comment by boogiefromzk** [comment]
Gentlemen, would you please point some documentation helpful in a case, related to this issue:
I have 3 control plane nodes and an endpoint on haproxy and bare metal cluster.
I was replacing one node with a new server and deleted one of control plane nodes with `kubectl delete node`. Yes, I'm stupid and had to make drain first.
Now 2 control plane nodes that are left are non-functional and for any request, for example `kubectl get nodes` return 
`Unable to connect to the server: EOF`.
I suppose this is because calico broke entire the network due to one node is not accessible.
So far I have only option to re-create cluster, but want to understand how to fix my cluster in cases like this.
Thanks in advance!

**Comment by fasaxc** [comment]
@boogiefromzk Please file a fresh issue, this one is long resolved.  Make sure you're running the latest Calico (v3.24.x) at time of writing.
