### ISSUE TITLE
Where is IP-in-IP encapsulation executed?

### ISSUE THREAD

**Issue by WolfyLPDC** [projectcalico/calico#2374]
I have a QUESTION. According to the docs, you can enable IP-in-IP encapsulation in Calico. However there is no specification about where and how is executed and how is decapsulated. 

According to the architecture, there are four main elements in Calico: Felix, the orquestrator plugin, etcd and BIRD. The last three elements jobs are pretty clear, but none of them does the encapsulation, so the last option is Felix and, according to [the official docs](https://docs.projectcalico.org/v3.4/reference/architecture/): _It is responsible for programming routes and ACLs, and anything else required on the host, in order to provide the desired connectivity for the endpoints on that host._

What is "Anything else"? Reading the first half of the reference, I can understand that Felix just modifies the kernel tables, but _anything else_ can be very relative. Is there an official explanation?

My main point is to understand encapsulation, but if I can have a properly explanation about Felix, I would be really grateful.

**Comment by caseydavenport** [comment]
@WolfyLPDC the IP-in-IP encapsulation itself is performed by the linux kernel.

In order to configure this, Felix creates an IP-in-IP tunnel device (typically `tunl0`) and BIRD configures routes within the cluster to use the tunnel device when appropriate.
