### ISSUE TITLE
Step 3 of Configuring in-cluster route reflectors does not work

### ISSUE THREAD

**Issue by emanic** [projectcalico/calico#2385]
https://docs.projectcalico.org/master/usage/configuration/bgp#configuring-in-cluster-route-reflectors

We have received some documentation feedback that step 3 fails. Do we need some quotes due to the exclamation point? See below for comments from the reporter.

```
In \"Configuring in-cluster route reflectors\", item \"3\", the configuration \"BGPpeer\", \"peer-to-rrs\" does not accept \"nodeSelector: !has(i-am-a-route-reflector)\" without Quotes (\").

I supposed that was caused by Exclamation signal (!).
```

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Calico version
* Orchestrator version (e.g. kubernetes, mesos, rkt):
* Operating System and version:
* Link to your project (optional):

**Comment by redbaron** [comment]
`!` needs to be quoted indeed, otherwise it represents local tag in YAML

**Comment by caseydavenport** [comment]
@emanic yes, any selector with a ! needs to be quoted.

We should update to `"!has(i-am-a-route-reflector)"`

**Comment by liuzeyusss** [comment]
@caseydavenport  what the difference between  one bgppeer as below and two bgppeer build by step 3 ,4  ?
`
apiVersion: projectcalico.org/v3
kind: BGPPeer
metadata:
  name: demo-peer
spec:
  nodeSelector: all()
  peerSelector: has(i-am-a-route-reflector)
`
