### ISSUE TITLE
How can an externel router peer with calico node route reflector

### ISSUE THREAD

**Issue by adamswanglin** [projectcalico/calico#2387]
Hey guys, I'm glad to see calico node can be configured to act as a route reflector for other calico nodes in calico 3.3. 
But when I set external router peer with calico node rr, I got error:
bird: BGP: Unexpected connect from unknown address xxxx (port xxxx)
My calico version is v3.3.2.

**Comment by fasaxc** [comment]
@adamswanglin you need to add a [BGPPeer resource](https://docs.projectcalico.org/v3.4/reference/calicoctl/resources/bgppeer) on the Calico side to tell the route reflector to peer with the external router.

**Comment by fasaxc** [comment]
Not sure I've seen anyone else hit this problem.  The hold time is negotiated as part of the handshake so it should be agreed by both sides.

I'd probably use tcpdump to collect a packet capture on the RR and examine the BGP TCP stream to see if the keep alives are been dropped, for example.

**Comment by shenshouer** [comment]
@caseydavenport I met the same problem, How did you resolve?

**Comment by caseydavenport** [comment]
@shenshouer I closed this one due to inactivity and no clear reproduction scenario.

Could you please raise a new issue describing what you are seeing?
