### ISSUE TITLE
Typha expects BGPPeer CRD but missing from policy-only manifest

### ISSUE THREAD

**Issue by fasaxc** [projectcalico/calico#2398]
Typha logs spammy errors about the missing CRD, may prevent typha from reporting ready.

## Expected Behavior

No errors.

## Possible Solution

- Always install the CRD even if it's not to be used in that configuration.
- Enhance typha to be able to disable the watch on that CRD.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Calico version v3.5 policy-only
* Orchestrator version (e.g. kubernetes, mesos, rkt): k8s 1.11.6
* Operating System and version:
* Link to your project (optional):

**Comment by caseydavenport** [comment]
Also tracked here: https://github.com/projectcalico/typha/issues/271

**Comment by spikecurtis** [comment]
I think this is fixed as tracked by https://github.com/projectcalico/typha/issues/271

Plz reopen if anyone disagrees
