### ISSUE TITLE
Visited links are hard to spot

### ISSUE THREAD

**Issue by matthewdupre** [projectcalico/calico#24]
A vlink colour that contrasts more with black would be nice.

Perhaps a bit lighter, although I'm not sure people would want it to be pink?  WDYT?

**Comment by djosborne** [comment]
Will be affected by #81

**Comment by djosborne** [comment]
Fixed by #554 by making visited links keep their color. We can optionally choose a new color for visited links if we desire but I rather like keeping them the same.
