### ISSUE TITLE
IPSEC encryption between PODs not supported

### ISSUE THREAD

**Issue by sourabhdce** [projectcalico/calico#2416]
IPSEC encryption between POD doesn't work right now. It should be supported for IP data security. 

## Expected Behavior

It should be supported to secure the POD-to-POD communication.

## Current Behavior

It's not supported today

## Possible Solution

It shall work only in IP-in-IP configuration. IPSEC tunnel can be established between calico tunnel endpoints. 
Felix running at each calico node, shall config IPSEC on the node may using strongswan or similiar. BIRD can share tunnel endpoint information of each node.

## Steps to Reproduce (for bugs)

1.Simply setup calico. POD-to-POD traffic is not encrypted. 
2.
3.
4.

## Context

We are trying to use calico with k8s and docker. We are creating this k8s platform to bring up our service provider apps.

## Your Environment

* Calico version v3.5.0
* Orchestrator version (e.g. kubernetes, mesos, rkt): K8s: v1.13.2
* Operating System and version: Ubuntu 16.04
* Link to your project (optional): NA

**Comment by caseydavenport** [comment]
Calico doesn't include any native IPSEC features itself.

I do know some users have configured Calico to run on top of their own IPSEC infrastructure just fine, it should be compatible with the right configuration tweaks, though I don't know what they are off the top of my head. 

You can also enable Calico's istio integration to take advantage of - among other things - mTLS between pods, if TLS would meet your requirements.
