### ISSUE TITLE
NetworkPlugin cni failed to set up pod xxxx  network: no podCidr for node yyyy

### ISSUE THREAD

**Issue by mofee** [projectcalico/calico#2418]
i use kubeadm(1.13.3) create a kebernetes cluster(only 2 nodes), 
vm-130 is master(192.168.195.130), 
vm-131 is a node(192.168.195.131). 
and use the following install calico:
[https://docs.projectcalico.org/v3.5/getting-started/kubernetes/installation/calico#installing-with-the-kubernetes-api-datastore50-nodes-or-less](https://docs.projectcalico.org/v3.5/getting-started/kubernetes/installation/calico#installing-with-the-kubernetes-api-datastore50-nodes-or-less)

kubeadm initial command:
`
kubeadm init  
--pod-network-cidr=10.88.99.0/24 
--service-cidr=10.66.0.0/16 
--apiserver-advertise-address=192.168.195.130 
--ignore-preflight-errors=NumCPU
`
`
kubectl taint nodes --all node-role.kubernetes.io/master-
`

after i join the work node to cluster, it seems all work fine:
`# kubectl get pods --all-namespaces`
NAMESPACE     NAME                                 READY   STATUS    RESTARTS   AGE
kube-system   calico-node-gd2bx                    1/1     Running   0          2m40s
kube-system   calico-node-gqtv2                    1/1     Running   0          20s
.......

`# calicoctl node status`
Calico process is running.

IPv4 BGP status
+-----------------+-------------------+-------+----------+-------------+
|  PEER ADDRESS   |     PEER TYPE     | STATE |  SINCE   |    INFO     |
+-----------------+-------------------+-------+----------+-------------+
| 192.168.195.131 | node-to-node mesh | up    | 12:54:28 | Established |
+-----------------+-------------------+-------+----------+-------------+

IPv6 BGP status
No IPv6 peers found.

`# calicoctl get wep --all-namespaces`
NAMESPACE     WORKLOAD                            NODE         NETWORKS        INTERFACE
kube-system   coredns-78d4cf999f-gfx55            vm-130   10.88.99.6/32   cali63ba253f92d
kube-system   coredns-78d4cf999f-pq7bw          vm-130   10.88.99.7/32   cali3f781e7301b

then i deploy a nginx-deployment, nginx-deployment.yaml:
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.7.9
        ports:
        - containerPort: 80

`
kubectl create -f nginx-deployment.yaml
`

## Expected Behavior
master and node both run a nginx pod

## Current Behavior
node can not deploy success (master is ok), the error is report by kubelet is:
> Feb 13 20:56:26 vm-131 kubelet[44686]: E0213 20:56:26.452929   44686 kuberuntime_manager.go:662] createPodSandbox for pod "nginx-deployment-76bf4969df-pp9xk_default(9d6b58e8-2f8e-11e9-a0b7-000c29302567)" failed: rpc error: code = Unknown desc = failed to set up sandbox container "3083ac73807e677a0a885fbaed668021b5534dc01b46c42e0113852ac3eb2e30" network for pod "nginx-deployment-76bf4969df-pp9xk": **NetworkPlugin cni failed to set up pod "nginx-deployment-76bf4969df-pp9xk_default" network: no podCidr for node vm-131**

## Possible Solution
i try to view the calino/node log by the document: 
[https://docs.projectcalico.org/v3.5/usage/troubleshooting/logging](https://docs.projectcalico.org/v3.5/usage/troubleshooting/logging)
but nothing in /var/log/calico dir
`# docker exec b914ebe47ab5 ls /var/log/calico/`
ls: /var/log/calico/: No such file or directory

and view wep, vm-131's ip is empty:
`# calicoctl get wep --all-namespaces`
NAMESPACE     WORKLOAD                            NODE         NETWORKS        INTERFACE
default       nginx-deployment-76bf4969df-k6j8v    vm-130   10.88.99.8/32   cali8111e7f57a7
default       nginx-deployment-76bf4969df-pp9xk   vm-131                           cali0a11a7a893e
kube-system   coredns-78d4cf999f-gfx55               vm-130   10.88.99.6/32   cali63ba253f92d
kube-system   coredns-78d4cf999f-pq7bw             vm-130   10.88.99.7/32   cali3f781e7301b

i try to resolve follow by the document
[https://docs.projectcalico.org/v3.5/usage/troubleshooting/](https://docs.projectcalico.org/v3.5/usage/troubleshooting/)
but the error still there.

i seach this problen in google, can not found resolved solution.

## Steps to Reproduce (for bugs)
up!

## Context
the calico/node container's inspect:

> [
    {
        "Id": "b914ebe47ab5820d734f40f69828dcf870f3cb841e579a8f3a6728ea69361f8e",
        "Created": "2019-02-13T12:54:24.591398899Z",
        "Path": "start_runit",
        "Args": [],
        "State": {
            "Status": "running",
            "Running": true,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 45464,
            "ExitCode": 0,
            "Error": "",
            "StartedAt": "2019-02-13T12:54:24.956748532Z",
            "FinishedAt": "0001-01-01T00:00:00Z"
        },
        "Image": "sha256:f815de40f3605ae092c8044f57b45309c8d5c5feac6d09c493934228b09245c1",
        "ResolvConfPath": "/var/lib/docker/containers/e6616654cb80a48e759794dffcccb1d44395957c71d6534a88a82073220c3ea6/resolv.conf",
        "HostnamePath": "/var/lib/docker/containers/e6616654cb80a48e759794dffcccb1d44395957c71d6534a88a82073220c3ea6/hostname",
        "HostsPath": "/var/lib/kubelet/pods/7c257833-2f8e-11e9-a0b7-000c29302567/etc-hosts",
        "LogPath": "/var/lib/docker/containers/b914ebe47ab5820d734f40f69828dcf870f3cb841e579a8f3a6728ea69361f8e/b914ebe47ab5820d734f40f69828dcf870f3cb841e579a8f3a6728ea69361f8e-json.log",
        "Name": "/k8s_calico-node_calico-node-gqtv2_kube-system_7c257833-2f8e-11e9-a0b7-000c29302567_0",
        "RestartCount": 0,
        "Driver": "overlay2",
        "Platform": "linux",
        "MountLabel": "",
        "ProcessLabel": "",
        "AppArmorProfile": "",
        "ExecIDs": [
            "b2b90310fd253ae6bab71cccb2a57a4aa9c62ffdcf7ae4c18154e0c9720c47ee"
        ],
        "HostConfig": {
            "Binds": [
                "/lib/modules:/lib/modules:ro",
                "/run/xtables.lock:/run/xtables.lock",
                "/var/run/calico:/var/run/calico",
                "/var/lib/calico:/var/lib/calico",
                "/var/lib/kubelet/pods/7c257833-2f8e-11e9-a0b7-000c29302567/volumes/kubernetes.io~secret/calico-node-token-kbh7p:/var/run/secrets/kubernetes.io/serviceaccount:ro,Z",
                "/var/lib/kubelet/pods/7c257833-2f8e-11e9-a0b7-000c29302567/etc-hosts:/etc/hosts:Z",
                "/var/lib/kubelet/pods/7c257833-2f8e-11e9-a0b7-000c29302567/containers/calico-node/45d81962:/dev/termination-log:Z"
            ],
            "ContainerIDFile": "",
            "LogConfig": {
                "Type": "json-file",
                "Config": {}
            },
            "NetworkMode": "container:e6616654cb80a48e759794dffcccb1d44395957c71d6534a88a82073220c3ea6",
            "PortBindings": null,
            "RestartPolicy": {
                "Name": "",
                "MaximumRetryCount": 0
            },
            "AutoRemove": false,
            "VolumeDriver": "",
            "VolumesFrom": null,
            "CapAdd": null,
            "CapDrop": null,
            "Dns": null,
            "DnsOptions": null,
            "DnsSearch": null,
            "ExtraHosts": null,
            "GroupAdd": null,
            "IpcMode": "container:e6616654cb80a48e759794dffcccb1d44395957c71d6534a88a82073220c3ea6",
            "Cgroup": "",
            "Links": null,
            "OomScoreAdj": 999,
            "PidMode": "",
            "Privileged": true,
            "PublishAllPorts": false,
            "ReadonlyRootfs": false,
            "SecurityOpt": [
                "seccomp=unconfined",
                "label=disable"
            ],
            "UTSMode": "host",
            "UsernsMode": "",
            "ShmSize": 67108864,
            "Runtime": "runc",
            "ConsoleSize": [
                0,
                0
            ],
            "Isolation": "",
            "CpuShares": 256,
            "Memory": 0,
            "NanoCpus": 0,
            "CgroupParent": "/kubepods/burstable/pod7c257833-2f8e-11e9-a0b7-000c29302567",
            "BlkioWeight": 0,
            "BlkioWeightDevice": null,
            "BlkioDeviceReadBps": null,
            "BlkioDeviceWriteBps": null,
            "BlkioDeviceReadIOps": null,
            "BlkioDeviceWriteIOps": null,
            "CpuPeriod": 100000,
            "CpuQuota": 0,
            "CpuRealtimePeriod": 0,
            "CpuRealtimeRuntime": 0,
            "CpusetCpus": "",
            "CpusetMems": "",
            "Devices": [],
            "DeviceCgroupRules": null,
            "DiskQuota": 0,
            "KernelMemory": 0,
            "MemoryReservation": 0,
            "MemorySwap": 0,
            "MemorySwappiness": null,
            "OomKillDisable": false,
            "PidsLimit": 0,
            "Ulimits": null,
            "CpuCount": 0,
            "CpuPercent": 0,
            "IOMaximumIOps": 0,
            "IOMaximumBandwidth": 0,
            "MaskedPaths": null,
            "ReadonlyPaths": null
        },
        "GraphDriver": {
            "Data": {
                "LowerDir": "/var/lib/docker/overlay2/22cdd95db4e08f23a2983e399806a6665d14e2b927ec9bea78cea5424f2691d8-init/diff:/var/lib/docker/overlay2/a718ec7ef1ff24b1f24eb34cbd5ba39d6d61b4b4fdf32fed047d03b0ce7c0151/diff:/var/lib/docker/overlay2/2c5fcd3723a6f2aebe5e131e530415266f110761ea5527fcb80792f2e3f95076/diff:/var/lib/docker/overlay2/6802a2b064b99e8cd0821a31f1d1e7bfaeaa0d24b3c9dffce86ab4be095414a2/diff:/var/lib/docker/overlay2/753a7a0c90e2c48f87c67164d44e4fafb62aed953dfbfe39f85635afe025d2d3/diff:/var/lib/docker/overlay2/67181e9e9f7ed3775d721e974c45ca019512d9b86451b5e9c1da216ae1daa8a5/diff:/var/lib/docker/overlay2/cf59af52c48a99483ef7cfc9e3e4933e8f6404a77995a8fbcc5eed7ba1ebef1d/diff",
                "MergedDir": "/var/lib/docker/overlay2/22cdd95db4e08f23a2983e399806a6665d14e2b927ec9bea78cea5424f2691d8/merged",
                "UpperDir": "/var/lib/docker/overlay2/22cdd95db4e08f23a2983e399806a6665d14e2b927ec9bea78cea5424f2691d8/diff",
                "WorkDir": "/var/lib/docker/overlay2/22cdd95db4e08f23a2983e399806a6665d14e2b927ec9bea78cea5424f2691d8/work"
            },
            "Name": "overlay2"
        },
        "Mounts": [
            {
                "Type": "bind",
                "Source": "/var/run/calico",
                "Destination": "/var/run/calico",
                "Mode": "",
                "RW": true,
                "Propagation": "rprivate"
            },
            {
                "Type": "bind",
                "Source": "/var/lib/calico",
                "Destination": "/var/lib/calico",
                "Mode": "",
                "RW": true,
                "Propagation": "rprivate"
            },
            {
                "Type": "bind",
                "Source": "/var/lib/kubelet/pods/7c257833-2f8e-11e9-a0b7-000c29302567/volumes/kubernetes.io~secret/calico-node-token-kbh7p",
                "Destination": "/var/run/secrets/kubernetes.io/serviceaccount",
                "Mode": "ro,Z",
                "RW": false,
                "Propagation": "rprivate"
            },
            {
                "Type": "bind",
                "Source": "/var/lib/kubelet/pods/7c257833-2f8e-11e9-a0b7-000c29302567/etc-hosts",
                "Destination": "/etc/hosts",
                "Mode": "Z",
                "RW": true,
                "Propagation": "rprivate"
            },
            {
                "Type": "bind",
                "Source": "/var/lib/kubelet/pods/7c257833-2f8e-11e9-a0b7-000c29302567/containers/calico-node/45d81962",
                "Destination": "/dev/termination-log",
                "Mode": "Z",
                "RW": true,
                "Propagation": "rprivate"
            },
            {
                "Type": "bind",
                "Source": "/lib/modules",
                "Destination": "/lib/modules",
                "Mode": "ro",
                "RW": false,
                "Propagation": "rprivate"
            },
            {
                "Type": "bind",
                "Source": "/run/xtables.lock",
                "Destination": "/run/xtables.lock",
                "Mode": "",
                "RW": true,
                "Propagation": "rprivate"
            }
        ],
        "Config": {
            "Hostname": "vm-131",
            "Domainname": "",
            "User": "0",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "DATASTORE_TYPE=kubernetes",
                "WAIT_FOR_DATASTORE=true",
                "NODENAME=vm-131",
                "CLUSTER_TYPE=k8s,bgp",
                "FELIX_IPINIPMTU=1440",
                "FELIX_LOGSEVERITYSCREEN=info",
                "IP=autodetect",
                "CALICO_IPV4POOL_IPIP=Always",
                "CALICO_IPV4POOL_CIDR=10.88.99.0/24",
                "CALICO_DISABLE_FILE_LOGGING=true",
                "FELIX_IPV6SUPPORT=false",
                "FELIX_HEALTHENABLED=true",
                "CALICO_NETWORKING_BACKEND=bird",
                "FELIX_DEFAULTENDPOINTTOHOSTACTION=ACCEPT",
                "KUBE_DNS_PORT_53_UDP_PORT=53",
                "KUBE_DNS_PORT_53_UDP_ADDR=10.66.0.10",
                "KUBE_DNS_PORT_53_TCP_ADDR=10.66.0.10",
                "KUBERNETES_SERVICE_HOST=10.66.0.1",
                "KUBERNETES_SERVICE_PORT_HTTPS=443",
                "KUBERNETES_PORT=tcp://10.66.0.1:443",
                "KUBE_DNS_SERVICE_PORT=53",
                "KUBE_DNS_PORT_53_UDP_PROTO=udp",
                "KUBE_DNS_PORT_53_TCP_PROTO=tcp",
                "KUBE_DNS_PORT_53_TCP_PORT=53",
                "KUBERNETES_PORT_443_TCP=tcp://10.66.0.1:443",
                "KUBERNETES_PORT_443_TCP_PORT=443",
                "KUBERNETES_PORT_443_TCP_ADDR=10.66.0.1",
                "KUBE_DNS_SERVICE_HOST=10.66.0.10",
                "KUBE_DNS_SERVICE_PORT_DNS=53",
                "KUBE_DNS_SERVICE_PORT_DNS_TCP=53",
                "KUBERNETES_SERVICE_PORT=443",
                "KUBE_DNS_PORT=udp://10.66.0.10:53",
                "KUBE_DNS_PORT_53_UDP=udp://10.66.0.10:53",
                "KUBE_DNS_PORT_53_TCP=tcp://10.66.0.10:53",
                "KUBERNETES_PORT_443_TCP_PROTO=tcp",
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
            ],
            "Cmd": [
                "start_runit"
            ],
            "Healthcheck": {
                "Test": [
                    "NONE"
                ]
            },
            "ArgsEscaped": true,
            "Image": "sha256:f815de40f3605ae092c8044f57b45309c8d5c5feac6d09c493934228b09245c1",
            "Volumes": null,
            "WorkingDir": "",
            "Entrypoint": null,
            "OnBuild": null,
            "Labels": {
                "annotation.io.kubernetes.container.hash": "90f274ab",
                "annotation.io.kubernetes.container.restartCount": "0",
                "annotation.io.kubernetes.container.terminationMessagePath": "/dev/termination-log",
                "annotation.io.kubernetes.container.terminationMessagePolicy": "File",
                "annotation.io.kubernetes.pod.terminationGracePeriod": "0",
                "io.kubernetes.container.logpath": "/var/log/pods/7c257833-2f8e-11e9-a0b7-000c29302567/calico-node/0.log",
                "io.kubernetes.container.name": "calico-node",
                "io.kubernetes.docker.type": "container",
                "io.kubernetes.pod.name": "calico-node-gqtv2",
                "io.kubernetes.pod.namespace": "kube-system",
                "io.kubernetes.pod.uid": "7c257833-2f8e-11e9-a0b7-000c29302567",
                "io.kubernetes.sandbox.id": "e6616654cb80a48e759794dffcccb1d44395957c71d6534a88a82073220c3ea6"
            }
        },
        "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": {},
            "SandboxKey": "",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "",
            "Gateway": "",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "",
            "IPPrefixLen": 0,
            "IPv6Gateway": "",
            "MacAddress": "",
            "Networks": {}
        }
    }
]

## Your Environment
* Calico version: 3.5
* Orchestrator version (e.g. kubernetes, mesos, rkt):kubenetes, 1.13.3
* Operating System and version: CentOS Linux release 7.6.1810 (Core)

**Comment by mofee** [comment]
i solved it with change  --pod-network-cidr=10.88.99.0/24 to --pod-network-cidr=10.88.0.0/16

**Comment by devopsweb333** [comment]
Running the following resolved my issues:
# kubeadm init --pod-network-cidr=10.244.0.0/16

For flannel as cni the apiserver needs to have the argument --pod-network-cidr=... to be set to the overlay.

**Comment by luis02lopez** [comment]
I fixed it by adding `podCIDR` to the node specs.
