### ISSUE TITLE
How to do the online migration?

### ISSUE THREAD

**Issue by calixwu** [projectcalico/calico#2434]
As calico 3.x.x only supports etcd v3, we have to migrate Calico data from etcd v2 to v3 when we upgrade calico from 2.6.x to 3.x.x. But the etcd datastore upgrade steps here (https://docs.projectcalico.org/v3.0/getting-started/kubernetes/upgrade/) are not a "online" migration way, because after the "Migrating Calico data" step, the etcdv2 data may be modified continuously without being migrated to the new store. Is there a feasible way to do the online migration? Thanks.

**Comment by tmjd** [comment]
The first step by the `calico-upgrade start ....` command is setting a flag in the v2 datastore that will prevent any new endpoints from being created. That means once the migration is started no new endpoints will be created in the v2 datastore, this is mentioned in https://docs.projectcalico.org/v3.0/getting-started/kubernetes/upgrade/migrate ` While existing connectivity will continue as before, you cannot add any new endpoints until the migration and upgrade complete.`
This does mean no new pods will be able to be started during the migration, we do not have a process to migrate and upgrade that allows pods to be created during the migration.

**Comment by caseydavenport** [comment]
Yep - the migration steps in that guide are an "online" migration. Existing workloads will continue to work fine. 

Any new workloads will be rejected during the migration, and will start afterwards.

**Comment by calixwu** [comment]
> Any new workloads will be rejected during the migration...

@caseydavenport It will impact the new pod creation during the migration.

**Comment by caseydavenport** [comment]
Yep, during the migration new pods cannot be started.

**Comment by calixwu** [comment]
> Yep, during the migration new pods cannot be started, and existing pods will continue to work as expected.

@caseydavenport @tmjd 

Actually, we are looking for a solution that:

1. Won't impact the new pod creation, that is, 
during the migration new pods can be started.

2. Can rollback to 2.6.x in case any exception occurs after migrating to 3.0.0. 

We are considering a double-write mechanism which may be quite complicated... Do you have any other suggestion to meet the two requirements above? Thanks a lot.

**Comment by jfoy** [comment]
@caseydavenport With full support for the Kubernetes API datastore in Calico 3.6, would a similar live-migration technique be possible to move an existing cluster off of the etcd datastore?

**Comment by caseydavenport** [comment]
>  to move an existing cluster off of the etcd datastore?

Hmm.. It might be possible - it's not something we've tested or thought about much.
