### ISSUE TITLE
quick howto docs on howto install on mesos running on centos7

### ISSUE THREAD

**Issue by f1-outsourcing** [projectcalico/calico#2440]
I was wondering if there is a basic/minimum installation and configuration guide to get calico working on a existing mesos/marathon installation on centos7, with complete configuration files of eg etcd. 

Or is maybe the complete test environment from this video available? Or the configuration files for the necessary components? Would be nice to try with these probes.
https://www.youtube.com/watch?v=ZQtRdCVCTUk

**Comment by caseydavenport** [comment]
I'm not aware of anything recent in this area. 

The most recent docs are back in v2.6: https://docs.projectcalico.org/v2.6/getting-started/mesos/

**Comment by f1-outsourcing** [comment]
Hmmm, that is not very helpful. I was actually hoping someone from calico to respond with the files shown in the video. I would like to give it a try.

**Comment by caseydavenport** [comment]
Sorry, that video is over three years old now and I'm not sure where all the content is.

I think this is the demo app: https://github.com/mesosphere/star

The link I provided above talks about how to install Calico and gives some policy examples as well.
