### ISSUE TITLE
Canal support for flannel v0.11.0

### ISSUE THREAD

**Issue by eranreshef** [projectcalico/calico#2447]
## Expected Behavior
Canal should support flannel's latest version, which is v0.11.0

## Current Behavior
Canal is tested with flannel v0.9.1, which is over 1 year old and have 2 newer releases.

## Context
I tried to do this upgrade myself and something is not working there as expected (see https://github.com/projectcalico/calico/issues/2400)

Thanks

**Comment by caseydavenport** [comment]
Yep, totally agree.

**Comment by fasaxc** [comment]
Fixed by #2498
