### ISSUE TITLE
Pods in "ContainerCreating" state forever: network: context deadline exceeded

### ISSUE THREAD

**Issue by r0bj** [projectcalico/calico#2463]
## Expected Behavior

Pod is started with status Running.

## Current Behavior

Pod stays forever in `ContainerCreating` state:
```
send-pending-notifications-1551531000-68v6n                      0/1     ContainerCreating   0          7h10m   <none>           k8s-worker-s2    <none>
```

## Steps to Reproduce (for bugs)

It's happening in our infrastructure from time to time on different nodes, not known pattern so far.

## Context

kubelet logs:
```
Mar 02 20:00:36 k8s-worker-s2 kubelet[9914]: E0302 20:00:36.150527    9914 cni.go:330] Error deleting network: context deadline exceeded
Mar 02 20:00:36 k8s-worker-s2 kubelet[9914]: E0302 20:00:36.151289    9914 remote_runtime.go:119] StopPodSandbox "f825c82ba762ad0bb03c614de070e068471fa82a8c7b5547e3879a5f63c0c676" from runtime service failed: rpc error: code = Unknown desc = NetworkPlugin cni failed to teardown pod "send-pending-notifications-1551531000-68v6n_prod" network: context deadline exceeded
Mar 02 20:00:36 k8s-worker-s2 kubelet[9914]: E0302 20:00:36.151330    9914 kuberuntime_manager.go:810] Failed to stop sandbox {"docker" "f825c82ba762ad0bb03c614de070e068471fa82a8c7b5547e3879a5f63c0c676"}
Mar 02 20:00:36 k8s-worker-s2 kubelet[9914]: E0302 20:00:36.151383    9914 kuberuntime_manager.go:605] killPodWithSyncResult failed: failed to "KillPodSandbox" for "b7212daf-3ce9-11e9-b794-525400fd26f0" with KillPodSandboxError: "rpc error: code = Unknown desc = NetworkPlugin cni failed to teardown pod \"send-pending-notifications-1551531000-68v6n_prod\" network: context deadline exceeded"
Mar 02 20:00:36 k8s-worker-s2 kubelet[9914]: E0302 20:00:36.151415    9914 pod_workers.go:186] Error syncing pod b7212daf-3ce9-11e9-b794-525400fd26f0 ("send-pending-notifications-1551531000-68v6n_prod(b7212daf-3ce9-11e9-b794-525400fd26f0)"), skipping: failed to "KillPodSandbox" for "b7212daf-3ce9-11e9-b794-525400fd26f0" with KillPodSandboxError: "rpc error: code = Unknown desc = NetworkPlugin cni failed to teardown pod \"send-pending-notifications-1551531000-68v6n_prod\" network: context deadline exceeded"
```
More kubelet logs:
https://gist.github.com/r0bj/74854b94dedc41c89c2d7b9213f32a1b

Calico-node logs:
https://gist.github.com/r0bj/ff1e943e90a60326e334f27f1e742113

Docker daemon logs:
https://gist.github.com/r0bj/ab9abaf5142f561331697c5fddd9ee3c

Rebooting node fixes the issue.

## Your Environment

* Calico version: v3.5.0
* Orchestrator version (e.g. kubernetes, mesos, rkt): kubernetes v1.12.3
* Docker version: 17.03.3
* Operating System and version: ubuntu 18.04.1

**Comment by caseydavenport** [comment]
@r0bj is this on a cluster with Calico using and etcd datastore or Kubernetes API?

Also, if possible it would be useful if you could increase the verbosity of the kubelet logs (e.g., `--v 10`) so that the Calico CNI plugin logs appear. Otherwise, it's hard to tell the origin of the error message.

**Comment by r0bj** [comment]
@caseydavenport This cluster runs calico with etcd datastore connected via https.

kubelet logs with `--v=10`:
https://gist.github.com/r0bj/9c0cc6b5e5014925f6457aca992ab241

Unfortunately I didn't find more CNI related entries in those logs.

**Comment by r0bj** [comment]
Also restating docker daemon fixes the issue.

**Comment by caseydavenport** [comment]
Hrm, yeah that doens't look like it upped to verbosity. 

I think we need to see the Calico logs to understand what is failing here.

**Comment by r0bj** [comment]
I've enabled debug logs for CNI calico plugin, maybe this would be helpful:
https://gist.github.com/r0bj/339eed269b58648838be330b054a2522

**Comment by liminghua999** [comment]
I also meet this question.
docker: 18.09.6
k8s: 1.15.0
os: centos 7.6.1810
calico: v3.8.1
I install coredns after calico is good
and the coredns pod is stay in ContainerCreating

then I restart the docker daemon  where the coredns pod stay host

then the coredns pod is fast running

**Comment by tmjd** [comment]
I realize this Issue is a bit old now but, @r0bj the messages `context deadline exceeded` make me think that the CNI plugin is having problems reaching the datastore (etcd). Would there have been any reason that reaching etcd might have been problematic?

@liminghua999 Can you reproduce the problem and collect logs from the kubelet on the node where coredns was being deployed?

**Comment by liminghua999** [comment]
`Aug 21 21:46:50 m-etc-3 kubelet[9357]: E0821 21:46:50.534641    9357 kuberuntime_manager.go:636] killPodWithSyncResult failed: failed to "KillPodSandbox" for "0b0c8197-09c7-4a7a-bc74-49140c2b66c3" with KillPodSandboxError: "rpc error: code = Unknown desc = NetworkPlugin cni failed to teardown pod \"coredns-797455887b-s9r8n_kube-system\" network: context deadline exceeded"
Aug 21 21:46:50 m-etc-3 kubelet[9357]: E0821 21:46:50.534684    9357 pod_workers.go:190] Error syncing pod 0b0c8197-09c7-4a7a-bc74-49140c2b66c3 ("coredns-797455887b-s9r8n_kube-system(0b0c8197-09c7-4a7a-bc74-49140c2b66c3)"), skipping: failed to "KillPodSandbox" for "0b0c8197-09c7-4a7a-bc74-49140c2b66c3" with KillPodSandboxError: "rpc error: code = Unknown desc = NetworkPlugin cni failed to teardown pod \"coredns-797455887b-s9r8n_kube-system\" network: context deadline exceeded"
Aug 21 21:47:13 m-etc-3 kubelet[9357]: E0821 21:47:13.515312    9357 cni.go:352] Error deleting kube-system_coredns-797455887b-s9r8n/16661acb98fff81aaa316ac07df43bf7ec76650086d43e4300fed333afcd461b from network calico/k8s-pod-network: context deadline exceeded
Aug 21 21:47:13 m-etc-3 kubelet[9357]: E0821 21:47:13.516820    9357 remote_runtime.go:128] StopPodSandbox "16661acb98fff81aaa316ac07df43bf7ec76650086d43e4300fed333afcd461b" from runtime service failed: rpc error: code = Unknown desc = NetworkPlugin cni failed to teardown pod "coredns-797455887b-s9r8n_kube-system" network: context deadline exceeded
Aug 21 21:47:13 m-etc-3 kubelet[9357]: E0821 21:47:13.516889    9357 kuberuntime_manager.go:841] Failed to stop sandbox {"docker" "16661acb98fff81aaa316ac07df43bf7ec76650086d43e4300fed333afcd461b"}
Aug 21 21:47:13 m-etc-3 kubelet[9357]: E0821 21:47:13.516973    9357 kuberuntime_manager.go:636] killPodWithSyncResult failed: failed to "KillPodSandbox" for "0b0c8197-09c7-4a7a-bc74-49140c2b66c3" with KillPodSandboxError: "rpc error: code = Unknown desc = NetworkPlugin cni failed to teardown pod \"coredns-797455887b-s9r8n_kube-system\" network: context deadline exceeded"
Aug 21 21:47:13 m-etc-3 kubelet[9357]: E0821 21:47:13.517015    9357 pod_workers.go:190] Error syncing pod 0b0c8197-09c7-4a7a-bc74-49140c2b66c3 ("coredns-797455887b-s9r8n_kube-system(0b0c8197-09c7-4a7a-bc74-49140c2b66c3)"), skipping: failed to "KillPodSandbox" for "0b0c8197-09c7-4a7a-bc74-49140c2b66c3" with KillPodSandboxError: "rpc error: code = Unknown desc = NetworkPlugin cni failed to teardown pod \"coredns-797455887b-s9r8n_kube-system\" network: context deadline exceeded"
Aug 21 21:47:19 m-etc-3 kubelet[9357]: E0821 21:47:19.965969    9357 cni.go:352] Error deleting kube-system_coredns-797455887b-hmftf/b96d6ca37cea4d53ef0c897adbe30e1ceb7379952b673b69fbca1b9cedee5ba3 from network calico/k8s-pod-network: context deadline exceeded
Aug 21 21:47:19 m-etc-3 kubelet[9357]: E0821 21:47:19.967130    9357 remote_runtime.go:128] StopPodSandbox "b96d6ca37cea4d53ef0c897adbe30e1ceb7379952b673b69fbca1b9cedee5ba3" from runtime service failed: rpc error: code = Unknown desc = NetworkPlugin cni failed to teardown pod "coredns-797455887b-hmftf_kube-system" network: context deadline exceeded
Aug 21 21:47:19 m-etc-3 kubelet[9357]: E0821 21:47:19.967164    9357 kuberuntime_gc.go:170] Failed to stop sandbox "b96d6ca37cea4d53ef0c897adbe30e1ceb7379952b673b69fbca1b9cedee5ba3" before removing: rpc error: code = Unknown desc = NetworkPlugin cni failed to teardown pod "coredns-797455887b-hmftf_kube-system" network: context deadline exceeded
`

**Comment by liminghua999** [comment]
![2](https://user-images.githubusercontent.com/18185326/63438103-5d222700-c45e-11e9-808b-b0e73f7af0ef.png)

**Comment by tmjd** [comment]
@liminghua999 I updated your comment to make it a bit more readable but unless I made a mistake updating it, it seems that the Secret: calico-etcd-secrets and ConfigMap: calico-config have gotten intermingled.

I also noticed that our comment `You must also populate the Secret below with these files.` is incorrect as the Secret is now actually before the comment.

To enable TLS for etcd you need to edit the secret to be 
```
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: calico-etcd-secrets
  namespace: kube-system
data:
  etcd-key: <base64 encoded contents of key file>
  etcd-cert: <base64 encoded contents of certificate file>
  etcd-ca: <base64 encoded contents of CA file>
```
And then update the ConfigMap to be 
```
kind: ConfigMap
apiVersion: v1
metadata:
  name: calico-config
  namespace: kube-system
data:
  etcd_endpoints: "http://<ETCD_IP>:<ETCD_PORT>"
  etcd_ca: "/calico-secrets/etcd-ca"
  etcd_cert: "/calico-secrets/etcd-cert"
  etcd_key: "/calico-secrets/etcd-key"
<...the rest of the file...>
```
Notice in the config map I literally uncommented those paths. The Secret is volume mounted into the pods so the `etcd_ca`, `etcd_cert`, and `etcd_key` are paths inside the container, not actual paths on the host/node.

**Comment by liminghua999** [comment]
tks a lot
  got it
