### ISSUE TITLE
Rolling back after upgrading  2.6.x to 3.x.x.

### ISSUE THREAD

**Issue by calixwu** [projectcalico/calico#2468]
As calico 3.x.x only supports etcd v3, we have to migrate Calico data from etcd v2 to v3 when we upgrade calico from 2.6.x to 3.x.x. We saw an upgrade guide here: https://docs.projectcalico.org/v3.0/getting-started/kubernetes/upgrade/, which offers a tool for migrating calico data. 

We wonder is there any down-grade tool doing the opposite things (especially the migration part) for rolling back in case any exception occurs after the upgrade.

Thanks a lot.

**Comment by caseydavenport** [comment]
There isn't any special tool for performing a downgrade, but there is documentation on it here: https://docs.projectcalico.org/v3.0/getting-started/kubernetes/upgrade/downgrade

Note that as mentioned in the doc, once the upgrade is complete and `calicoctl-upgrade complete` is executed, downgrading becomes a disruptive operation.
