### ISSUE TITLE
How to preserve the source IP address across k8s nodes using calico

### ISSUE THREAD

**Issue by asudhakarreddy** [projectcalico/calico#2484]
Using Calico in my Kubrnetes cluster.
Use case: I have an agent pod which is running UDP services(69,162) and this service exposed via nginx ingress controller. 
In Nginx controller enabled transparent mode for the backend agent-pods to preserve source IP address of a client and used hostPort to expose UDP ports.
Note: agents are deployed on backend nodes and NGINX controller deployed on frontend nodes.
clients(Network devices) <---> NGINX Proxy <---> Agent-pods

## Expected Behavior
The agent-pods should receive source traffic coming from the clients(source IP address should preserve) 

## Current Behavior
NGINX controller pod receiving traffic from the clients and it sending traffic coming from the source as a client to the agent-pod, but in the calico level the traffic getting dropped.

## Possible Solution
Provide posible configuration wrt network policies/globalnetworkpolicies

## Your Environment

* Calico version: v3.3
* kubernetes version: v1.12.6
* Operating System and version: CentOS 7
* Link to your project (optional):

![image](https://user-images.githubusercontent.com/10269272/54128267-b6a71400-4431-11e9-9d1b-91c9d4710e59.png)
[debug.log](https://github.com/projectcalico/calico/files/2952429/debug.log)

**Comment by caseydavenport** [comment]
I'm not sure I understand the question - are you looking for a set of policies to allow the traffic? Or help with the nginx configuration?

if the traffic is indeed reaching Calico with the original source, then you can use a Calico policy / network set to allow traffic from those specific networks and IPs.

**Comment by asudhakarreddy** [comment]
@caseydavenport Thanks for the reply. looking for what policies need to be applied on which resources.
could you verify below?
calicoctl apply -f - <<EOF
apiVersion: projectcalico.org/v3
kind: GlobalNetworkSet
metadata:
  name: atom-agent-ingress
  labels:
    app: atom-defaultagent
spec:
  nets:
  - 172.16.0.0/16 # device subnet
  - 10.96.0.0/12 #service subnet
  - 10.200.0.0/16 #pod subnet
EOF
	
---


calicoctl apply -f - <<EOF
apiVersion: projectcalico.org/v3
kind: GlobalNetworkPolicy
metadata:
  name: allow-udp
spec:
  selector: app == 'agent'
  types:
  - Ingress
  - Egress
  ingress:
  - action: Allow
    protocol: UDP
    source:
      selector: all()
    destination:
      ports:
      - 2162
      - 2161
      - 2514
      - 69
  egress:
  - action: Allow
EOF

**Comment by caseydavenport** [comment]
Looks reasonable enough to me. Does it work?

**Comment by patelrajen** [comment]
I am facing the same issue. Can you please update what exactly worked for you?

**Comment by MohammedNoureldin** [comment]
@patelrajen @asudhakarreddy did you figure out how to achieve that?

**Comment by Xavierxxc** [comment]
@caseydavenport @asudhakarreddy @patelrajen I’m in the same boat. When NGINX used "transparent" to preserve source ip,(whether NGINX used NodePort 、HostPort or LoadBalancer), the UDP packet that preserved source ip could not come out of the node, maybe it is the reason why GlobalNetworkSet and GlobalNetworkPolicy did not work? Are there any solution?
(BTW, "transparent" worked when NGINX use "hostNetwork: true", but i don't want to bind a real port with a pod for a k8s service. It really confuses me a lot.)
