### ISSUE TITLE
After Kube node restarted, calico network and routes are gone

### ISSUE THREAD

**Issue by deoxen0n2** [projectcalico/calico#2486]
I'ven't found the solution yet. The detail is as follow, please advice.

## Expected Behavior
After 1 of the node restarted, calico network and routes should come back and work like before restart.

## Current Behavior
After 1 of the node restarted, calico network and routes didn't comeback. When typing

```sh
$ calicoctl node status
```
It shows all other nodes as `Active Socket: Host is unreachable`. And when typing

```sh
$ ip r
```
It shows most routes are gone. And

```sh
$ ip a
```
Shows `tunl0@NONE`.

## Possible Solution
Not found yet.

## Steps to Reproduce
1. Restart 1 of the Kubernetes node
2. The node will later show as `Ready` after some time, but it will now can't connect to other nodes

## Your Environment
Installed via Kubespray.

* Calico version: v3.1.3
* Orchestrator version: Kubernetes v1.11.3
* Operating System and version: CentOS Linux release 7.5.1804 (Core)

**Comment by tmjd** [comment]
Did you try connecting or pinging the other nodes from the node that isn't working? It kind of sounds like there might be a connectivity problem to the other nodes.
If general connections or pinging works then you could try connecting to BGP (TCP 179) from the problem node to other nodes, I suggest using netcat with the verbose option, something like `nc -v <working node ip> 179` (or netcat might need to be spelled out).

**Comment by deoxen0n2** [comment]
@tmjd Thanks for suggestion. Nodes can ping each other but doing this from the non-working node
```sh
nc -v <other node> 179
```
resulting in
```
Ncat: Version 7.50 ( https://nmap.org/ncat )
Ncat: No route to host.
```
But using netcat from other working nodes to other nodes with established calico connections resulting in the same.

**Comment by tmjd** [comment]
You'll need to figure out why there is no route to that host. That is something that will need to be resolved before Calico will be able to run successfully.

I doubt that calico caused this problem, unless maybe you have some overlapping CIDRs, like the subnet your nodes are in overlap with the pod CIDR. That being said I've never seen that problem cause and issue like this.

**Comment by deoxen0n2** [comment]
Thanks @tmjd. I will investigate further. Don't know if this information will help:

```sh
$ ip a
...
tunl0@NONE: <NOARP,UP,LOWER_UP> mtu 1440 qdisc noqueue state UNKNOWN group default qlen 1000
    link/ipip 0.0.0.0 brd 0.0.0.0
    inet 10.233.71.0/32 brd 10.233.71.0 scope global tunl0
       valid_lft forever preferred_lft forever
```

```sh
$ calicoctl get ippool
NAME           CIDR             
default-pool   10.233.64.0/18
```

**Comment by deoxen0n2** [comment]
Sorry, just detect that somehow the firewall rules for port 179 are gone. Hence after some time the connections from all nodes are all unreachable.

Thanks @tmjd. Netcat and port 179 suggestion helps so much.
