### ISSUE TITLE
Front page needs to have prominent links to our other repos

### ISSUE THREAD

**Issue by tomdee** [projectcalico/calico#25]
If we're calling this repo "calico" a bunch of people are going to end up here first. They need to be guided to the right place

**Comment by djosborne** [comment]
I agree we need to direct them better from our home page, but I don't know that sending them to sub-repos is the answer. Instead:

- Front page should push users onto getting-started page.
- Getting-started page should be improved to be more welcoming

**Comment by caseydavenport** [comment]
Closing in favor of, that's right, #1
