### ISSUE TITLE
Bare metal policy - ipv6 endpoint selectors don't cause ipv4 rules to be created

### ISSUE THREAD

**Issue by fasaxc** [projectcalico/calico#250]
From @lwr20; moved from https://github.com/projectcalico/felix/issues/1041.

If I configure an endpoint using an `expected_ipv6_addrs` key, (e.g. `/calico/v1/host/calico-st01/endpoint/endpoint1 : {"expected_ipv6_addrs": ["fec0::250:56ff:fe92:365f"], "labels": {"hostname": "calico-st01", "role": "control"}}`) I find that felix does NOT write ipv4 rules for this endpoint.

**Comment by djosborne** [comment]
> this is expected behaviour - docs should probably be updated to explain this.

**Comment by dimm0** [comment]
Can I create the IPV6 policy for V6 node interfaces in IPV4 cluster? The ticket is >2 years old...

**Comment by caseydavenport** [comment]
> Can I create the IPV6 policy for V6 node interfaces in IPV4 cluster? The ticket is >2 years old...

Yep, both IPv4 and IPv6 policy on HostEndpoints is supported. 

I think this issue can be closed - it's old and I don't think there's anything to do for it.
