### ISSUE TITLE
K8s clusterIP advertising doesn't work with externalTrafficPolicy: Cluster 

### ISSUE THREAD

**Issue by tungdam** [projectcalico/calico#2507]
Hi

We have a problem with k8s cluster IP range advertising and kube-proxy. 

## Expected Behavior
After enabling cluster IP advertising to external BGP peers, we can reach k8s internal service from outside the cluster IP no matter what the externalTrafficPolicy is. 

## Current Behavior
Calico and BGP peers route us to the correct node, but can't reach the pod behind cluster IP. 
It works with externalTrafficPolicy=local and replica=1
When externalTrafficPolicy=local and several replicas, the connectivity is very unstably

## Context
We setup our k8s cluster following this guide [https://www.projectcalico.org/kubernetes-service-ip-route-advertisement/](url), hoping that we can publish our k8s services to the outside without using a load balancer. 
We did set: 
`--service-cluster-ip-range=10.198.32.0/19` for api server 

Env for calico-node ( kubernetes daemonset with etcd datastore ) 
```
            - name: CALICO_IPV4POOL_CIDR
              value: "10.198.0.0/15"
            - name: CALICO_ADVERTISE_CLUSTER_IPS
              value: "10.198.32.0/19"
```
`clusterCIDR: "10.198.32.0/19"` for kube-proxy. Tried toggling masqueradeAll on and off. Didn't help. 

The packet traverses well from PREROUTING -> KUBE-SERVICES -> KUBE-MARK-MASQ + KUBE-SVC -> KUBE-SEP ( DNAT )  -> KUBE-POSTROUTING. 
Tcpdump shows us that: the source IP did changed from external host to the nodeIP before reaching pod IP but that's all. There's nothing else for the response to go back to the external host. 

In case of using externalTrafficPolicy=local, there's no address translation and the pod the response well directly to external host as expected. 

If we use externalTrafficPolicy=Cluster ( default ) and:
- Configure our BGP peer to choose the best route only so external requests will always come to 1 calico-node
- Deploy the pod to that node only
Everything's fine. The behaviour is the same as using externalTrafficPolicy=local. 

Maybe I'm doing something wrong or even expecting something wrong. Please, kindly advice 

Thanks in advance

## My Environment
* Calico version: 3.5.1 
* Orchestrator version: kubernetes 1.12.1 
* Operating System and version: Debian 8 & 9

**Comment by briansan** [comment]
Hi @tungdam, I'm having trouble understanding the context around your issue. If I understand correctly, service IP advertisement works properly when service's externalTrafficPolicy=cluster but not when externalTrafficPolicy=local? Could you clarify what you mean by "the connectivity is very unstably"?

You also say towards the end that "Everything's fine. The behaviour is the same as using externalTrafficPolicy=local" which leads me to believe that things are working as you expect them to. Could you clarify a bit here as well? 

Thanks!

**Comment by tungdam** [comment]
hi @briansan 
With externalTrafficPolicy=cluster -> doesn't work
externalTrafficPolicy=local -> works but with 1 replica only. If we have many pod behinds service, sometimes it works, sometimes it doesn't. I think it doesn't work when the backend pod doesn't belong to the same Node host that IP cluster routed to. 

The cluster IP is advertised well in both case.  Traceroute shows me to the next hop properly. By saying doesn't work, i mean i can't reach the service. For example, can't telnet or curl to clusterIP:80 in case my pod is nginx. 

> You also say towards the end that "Everything's fine. The behaviour is the same as using externalTrafficPolicy=local" which leads me to believe that things are working as you expect them to. Could you clarify a bit here as well?

Everything is fine if we configure following the steps that i explained. I can quote here once again

```
 If we use externalTrafficPolicy=Cluster ( default ) and:
   Configure our BGP peer to choose the best route only so external requests will always come to 1 calico-node
    Deploy the pod to that node only
```
Hope that it's clearer. Sorry for my complicated explanation.

**Comment by tungdam** [comment]
Update: It works with userspace proxy mode. We used default mode ( iptables ) for kube-proxy before. 
The question now is: is it possible to use kube-proxy iptables mode + calico service IP advertising to publish k8s service to the outside ?

**Comment by caseydavenport** [comment]
```
            - name: CALICO_IPV4POOL_CIDR
              value: "10.198.0.0/15"
            - name: CALICO_ADVERTISE_CLUSTER_IPS
              value: "10.198.32.0/19"

clusterCIDR: "10.198.32.0/19" for kube-proxy
```

I have a hunch this might be related to the value you're passing here. The value passed to `clusterCIDR` for kube-proxy should probably be `10.198.0.0/15`, since that is your pod IP range. Passing a clusterCIDR which includes the service range might have unintended consequences re: NAT. Haven't thought through the whole thing yet, but I think it's worth changing that.

From [here](https://kubernetes.io/docs/reference/command-line-tools-reference/kube-proxy/)

> The CIDR range of pods in the cluster. When configured, traffic sent to a Service cluster IP from outside this range will be masqueraded and traffic sent from pods to an external LoadBalancer IP will be directed to the respective cluster IP instead

**Comment by caseydavenport** [comment]
> Calico and BGP peers route us to the correct node, but can't reach the pod behind cluster IP.

This again makes me think it has something to do with the kube-proxy side of things, but can't be 100% sure. Have you validated that cross-host networking works in the general case? (e.g., can you ping from one node to a pod on another node?) That would help tell if it's a node->pod networking issue, or something else.

Also, just to double check, do you have any network policies configured?

**Comment by caseydavenport** [comment]
> is it possible to use kube-proxy iptables mode + calico service IP advertising to publish k8s service to the outside

Yep, it's definitely possible. That this works in userspace mode again makes me think it might have to do with the kube-proxy configuration as I mentioned above. But, I can confirm that this feature works in iptables mode as well (and we _strongly_ recommend avoiding userspace mode)

**Comment by tungdam** [comment]
> I have a hunch this might be related to the value you're passing here. The value passed to clusterCIDR for kube-proxy should probably be 10.198.0.0/15, since that is your pod IP range. Passing a clusterCIDR which includes the service range might have unintended consequences re: NAT. Haven't thought through the whole thing yet, but I think it's worth changing that.
Actually our clusterCIDR doesn't include service range. We created several ippools in calico for different networks ( Eg: Prod / dev ) and spend 1 small subnet exclusively for clusterIP. 
For example, in our network, the calico ip range looks like this:
```
 production 10.198.0.0/19
 range 10.198.32.0/19
 dev: 10.199.0.0/21
```
But I also don't really know what should i use for CALICO_IPV4POOL_CIDR so chose the big subnet that cover everything. 

> This again makes me think it has something to do with the kube-proxy side of things, but can't be 100% sure. Have you validated that cross-host networking works in the general case? (e.g., can you ping from one node to a pod on another node?) That would help tell if it's a node->pod networking issue, or something else.
The cross-host networking is ok. I can ping from pod to pod, pod to host, no problem. 

> Also, just to double check, do you have any network policies configured?
The latest update on this issue is: when i change our default policy of FORWARD chain ( filter table) to ACCEPT ( it was DROP ). Everything's ok. From the external network we can connect to "remote pod" via kube-proxy with iptables mode. 
I haven't figured out why yet. Will share more info details here soon. 

Thanks for your support

**Comment by tungdam** [comment]
So, this is what happened what our FORWARD table

**Incoming request direction:**

- Even when the default FORWARD policy is DROP,  the incoming packet still passes because kube-proxy marks it in KUBE-SERVICES and allow such marked packet in KUBE-FORWARD

```
-A KUBE-FORWARD -m comment --comment "kubernetes forwarding rules" -m mark --mark 0x4000/0x4000 -j ACCEPT
-A KUBE-FORWARD -s 10.198.32.0/19 -m comment --comment "kubernetes forwarding conntrack pod source rule" -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A KUBE-FORWARD -d 10.198.32.0/19 -m comment --comment "kubernetes forwarding conntrack pod destination rule" -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
```
- Source / destination IPs are now: k8s-node / pod

**Response direction:** 

- pod backend receives request well and sends response to remote host. Source / destination IPs are now: pod / remote host. It then goes through our k8s-node FORWARD table. 
- If the destination pod exists locally ( which has kube-proxy running ): it matches cali-FORWARD rules ( -i / o cali+ ) and is accepted, thus passed through to remote host ( which is outside k8s cluster ) 
- If the destination is on another k8s node, it doesn't match any cali-FORWARD or KUBE-FORWARD rules, thus will be dropped eventually. ( as default policy ) 

Then if we set the default policy for FORWARD is ACCEPT, or a bit safer to ACCEPT all RELATED/ESTABLISHED connection in FORWARD table , everything will be fine. 

If an iptables tweak like this is required to get the cluster IP advertising feature works properly ( correct me if I'm wrong please ), should we add some rule to FORWARD table by calico to overcome this automatically ? 
Just a wild idea, what do you think if we set this in cali-FORWARD:

```
-A  cali-FORWARD ! -s CALICO_IPV4POOL_CIDR -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A  cali-FORWARD ! -d CALICO_IPV4POOL_CIDR -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
```

**Comment by caseydavenport** [comment]
> But I also don't really know what should i use for CALICO_IPV4POOL_CIDR in this case so chose the big subnet that cover everything

The CALICO_IPV4POOL_CIDR should be the range that you want to use for Pod IP assignments, and should not include the node IP range or the Service IP range. If these ranges overlap, you'll likely see things start to break.

> -A KUBE-FORWARD -s 10.198.32.0/19 -m comment --comment "kubernetes forwarding conntrack pod source rule" -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT

This rule has the Service IP range in it - I think if you change the `clusterCIDR` passed to kube-proxy to match the range used for pods then this will start to work.

**Comment by sylr** [comment]
I've a similar problem, my ingress controllers do not get the public IP of the clients but the IP of a kubernetes node despite `externalTrafficPolicy: Local`.

I'm using Azure CNI and the IP of the pods are in the same subnet as the kubernetes nodes.

Is it corner case which can not work at the moment ?

**Comment by caseydavenport** [comment]
@tungdam did you get a chance to try the suggestion above?

**Comment by tungdam** [comment]
Sorry for late response. I cant try it right away at the moment. Will check and report very soon.

**Comment by tungdam** [comment]
> The CALICO_IPV4POOL_CIDR should be the range that you want to use for Pod IP assignments, and should not include the node IP range or the Service IP range. If these ranges overlap, you'll likely see things start to break.

I strongly believe that is not our case because even when we set CALICO_IPV4POOL_CIDR to that big subnet but our pod IP assigned explicitly to small subnets / ippools. There will be not overlapping with clusterIP in this case.  And I even don't see any iptables rule that match the value of  CALICO_IPV4POOL_CIDR. 

> > -A KUBE-FORWARD -s 10.198.32.0/19 -m comment --comment "kubernetes forwarding conntrack pod source rule" -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
> 
> This rule has the Service IP range in it - I think if you change the `clusterCIDR` passed to kube-proxy to match the range used for pods then this will start to work.

Unfortunately we can't change our clusterIP range in kube-proxy so far, it's quite inconvenient with us. 

But I added 2 rules manually following for suggestion and it works.
( Because by default FORWARD chain drops 2 requests, 1 from pod IP and 1 from external node **to Pod IP** ) 

Btw, I think adding those rules is just for testing purpose, we shouldn't mix clusterIP range with pod IP range, as you suggested above.

**Comment by caseydavenport** [comment]
> Unfortunately we can't change our clusterIP range in kube-proxy so far, it's quite inconvenient with us.

Why not? Passing `--cluster-cidr=<service-range>` is just a fundamental misconfiguration and is likely why you're seeing things not work. 

> Btw, I think adding those rules is just for testing purpose, we shouldn't mix clusterIP range with pod IP range, as you suggested above.

Yep, agreed - I thin k mostly just confirms that changing the `--cluster-cidr` argument of the kube-proxy to match the pod IP range instead of service range should fix the problem.
