### ISSUE TITLE
calico-node in CrashLoopBackOff state on one node of the two nodes

### ISSUE THREAD

**Issue by FlogFr** [projectcalico/calico#2521]
## Expected Behavior
calico-node pod should be running on my 2 nodes.

## Current Behavior
calico-node pod is not running on one of my 2 nodes.

```
2019-04-02 10:59:28.128 [WARNING][8] startup.go 863: Calico node 'k8s-node-1' is already using the IPv4 address 10.32.0.1.
2019-04-02 10:59:28.128 [WARNING][8] startup.go 1042: Terminating
Calico node failed to start
```

## Context
I installed a 3 hosts kubernetes cluster "the hard way", with one master, and 2 nodes.
The etcd runs on the master host. And the 2 nodes are running containerd, kubelet, kube-proxy. I see my 2 nodes from the master:
```
NAME         STATUS   ROLES    AGE   VERSION   INTERNAL-IP   EXTERNAL-IP   OS-IMAGE                       KERNEL-VERSION          CONTAINER-RUNTIME
k8s-node-1   Ready    <none>   21h   v1.14.0   10.6.24.117   <none>        Debian GNU/Linux 9 (stretch)   4.15.11-mainline-rev1   containerd://1.2.5
k8s-node-2   Ready    <none>   21h   v1.14.0   10.6.36.181   <none>        Debian GNU/Linux 9 (stretch)   4.15.11-mainline-rev1   containerd://1.2.5
```
Now, I customize the manifest (https://docs.projectcalico.org/v3.6/getting-started/kubernetes/installation/hosted/calico.yaml) to use the certificates from etcd as described here https://docs.projectcalico.org/v3.6/getting-started/kubernetes/installation/config-options , and also set the pod CIDR to `10.32.0.0/24` then apply the manifest.
I list the pods:
```
NAME                                       READY   STATUS             RESTARTS   AGE   IP            NODE         NOMINATED NODE   READINESS GATES
calico-kube-controllers-75569d87d7-knj86   1/1     Running            0          43m   10.6.24.117   k8s-node-1   <none>           <none>
calico-node-69tb5                          0/1     CrashLoopBackOff   13         43m   10.6.36.181   k8s-node-2   <none>           <none>
calico-node-m6rm5                          1/1     Running            0          43m   10.6.24.117   k8s-node-1   <none>           <none>
```

I notice one of the calico-node is in the state of `CrashLoopBackOff`.
The logs of this node:
```
Threshold time for bird readiness check:  30s
2019-04-02 11:04:38.084 [INFO][8] startup.go 256: Early log level set to info
2019-04-02 11:04:38.084 [INFO][8] startup.go 276: Using HOSTNAME environment (lowercase) for node name
2019-04-02 11:04:38.085 [INFO][8] startup.go 284: Determined node name: k8s-node-2
2019-04-02 11:04:38.112 [INFO][8] startup.go 97: Skipping datastore connection test
2019-04-02 11:04:38.114 [INFO][8] startup.go 367: Building new node resource Name="k8s-node-2"
2019-04-02 11:04:38.114 [INFO][8] startup.go 382: Initialize BGP data
2019-04-02 11:04:38.116 [INFO][8] startup.go 584: Using autodetected IPv4 address on interface cnio0: 10.32.0.1/24
2019-04-02 11:04:38.116 [INFO][8] startup.go 452: Node IPv4 changed, will check for conflicts
2019-04-02 11:04:38.117 [WARNING][8] startup.go 863: Calico node 'k8s-node-1' is already using the IPv4 address 10.32.0.1.
2019-04-02 11:04:38.118 [WARNING][8] startup.go 1042: Terminating
Calico node failed to start
```

Also, from calicoctl:
```
# ./calicoctl get nodes -o wide
NAME         ASN         IPV4           IPV6   
k8s-node-1   (unknown)   10.32.0.1/24
```
No k8s-node-2 is available.

## Your Environment
* Calico version
```
# ./calicoctl version
Client Version:    v3.0.11
Build date:        2019-03-10T02:11:54+0000
Git commit:        c20ea201
Cluster Version:   v3.6.1
Cluster Type:      k8s,bgp
```
* Orchestrator version (e.g. kubernetes, mesos, rkt): Kubernetes version: `v1.14.0`
* Operating System and version: Debian Stretch, kernel 4.15
* Link to your project (optional):

Already read the issues https://github.com/projectcalico/calico/issues/1628 and https://github.com/projectcalico/calico/issues/1867

**Comment by tmjd** [comment]
I think issue #1628 is probably the answer here, I'm guessing autodetection of the interface needs to be adjusted for you.  What interface on k8s-node-2 is `10.6.36.181` address on? You can see in the logs `Using autodetected IPv4 address on interface cnio0: 10.32.0.1/24` which I'm guessing is the incorrect interface.
Have you tried setting IP_AUTODETECTION_METHOD to help guide autodetection?

**Comment by FlogFr** [comment]
The IP_AUTODETECTION_METHOD was already set to `can-reach=#MASTER_IP#`.
I re-installed my k8s cluster, with being more careful on the CNI setup and I don't have the error anymore.
