### ISSUE TITLE
HOSTNAME vs CALICO_HOSTNAME

### ISSUE THREAD

**Issue by MikeSpreitzer** [projectcalico/calico#253]
https://github.com/projectcalico/calico/blob/master/v1.6/usage/configuration/as-service.md is inconsistent.  The "Note" after the display of `calico.env` speaks of CALICO_HOSTNAME, which is indeed defined in the displayed `calico.env`.   But CALICO_HOSTNAME is not used in the displayed `calido-node.service`.  That says `-e HOSTNAME=${HOSTNAME}` (and, no, it is not easy to tell from https://www.freedesktop.org/software/systemd/man/systemd.service.html whether environment variables are inherited from the context).  I wonder it it was intended to say `-e HOSTNAME=${CALICO_HOSTNAME}` instead.

Also, FYI, http://docs.projectcalico.org/v1.6/reference/calicoctl/node does not mention a hostname parameter to the run-a-node command.  This seems oddly inconsistent.  And it makes it difficult to find any more documentation on the meaning and restrictions on that HOSTNAME environment variable.

**Comment by djosborne** [comment]
reference/calicoctl/node has been split out to include node configuration info under: http://docs.projectcalico.org/v2.1/reference/node/configuration

I think that document has adequate information on the hostname and how it is just used as a unique identifer. closing
