### ISSUE TITLE
Use kubernetes.io/arch in kubernetes manifests as a nodeselector

### ISSUE THREAD

**Issue by mkumatag** [projectcalico/calico#2532]
## Expected Behavior

beta.kubernetes.io/arch is deprecated per 1.14 doc, so calico manifests need to start adopting `kubernetes.io/arch` nodeselector to work with k8s 1.14 and later.

ref: https://kubernetes.io/docs/reference/kubernetes-api/labels-annotations-taints/#beta-kubernetes-io-arch-deprecated

calico manifests - https://docs.projectcalico.org/v3.6/getting-started/kubernetes/installation/hosted/kubernetes-datastore/calico-networking/1.7/calico.yaml

/cc @caseydavenport

**Comment by caseydavenport** [comment]
Thanks for the heads up!

**Comment by caseydavenport** [comment]
Turns out we don't use the "arch" label here, but the same probably applies for the "os" label.

I think we don't want to use the arch label though, since we use multi-arch manifest images now.

**Comment by caseydavenport** [comment]
Do we know when Kubernetes started supporting the new label? And, do any releases support both labels at the same time?
