### ISSUE TITLE
Calico profile doesn't work when networkpolicy exist

### ISSUE THREAD

**Issue by gbjuno** [projectcalico/calico#2535]
calico version: 3.0
kubernetes: 1.10.4

I want to define networkpolicy using calico api rather than k8s networkpolicy api, therefore I define the env ENABLED_CONTROLLERS=profile,workloadendpoint,node on calico-policy-controller.
Cailco create a default profile which allows all ingress and egress traffic for every k8s namespace. 
After define a network policy, I find that the rule defined by profile doesn't work. The traffic which is not match the defined network policy will be denied. When I deleted the network policy, the rule of the profile works again, the traffic which is not match the defined network policy is allowed.

## Expected Behavior

calico profile works when network policy exist

## Steps to Reproduce (for bugs)

1. create a network policy (any one is ok as long as some traffic will not match the policy)
2. test by using the traffic will not match the network policy
3. find the traffic that match the profile (all ingress/egress traffic allowed) will be deny.
4. delete the network policy
5. same traffic of 2 will be allowed
## Context

policy
```
    "spec": {
        "order": 9999,
        "ingress": [
            {
                "action": "Deny",
                "source": {
                    "selector": "servicenamespace != 'system'",
                    "namespaceSelector": "all()"
                },
                "destination": {
                    "selector": "all()"
                }
            }
        ],
        "selector": "",
        "types": [
            "Ingress"
        ]
    }
```
profile
```
    "spec": {
        "ingress": [
            {
                "action": "Allow",
                "source": {},
                "destination": {}
            }
        ],
        "egress": [
            {
                "action": "Allow",
                "source": {},
                "destination": {}
            }
        ]
    }
```

## Your Environment

* Calico version  3.0
* Orchestrator version (e.g. kubernetes, mesos, rkt): kubernetes: 1.10.4
* Operating System and version: ubuntu 16.04 
* Calico-policy-controller: ENABLED_CONTROLLERS=profile,workloadendpoint,node

**Comment by caseydavenport** [comment]
This is working as intended - if you use network policy, profiles won't be applied unless you explicitly pass the traffic to them using a rule with `action: Pass`.

I recommend using another, lower order NetworkPolicy to implement what you want, since the interactions between NetworkPolicy and Profiles are... awkward.

**Comment by gbjuno** [comment]
@caseydavenport thanks for your reply.  I just solved it just as you recommended.
