### ISSUE TITLE
Bugfix release for IPv6 ROUTER_ID

### ISSUE THREAD

**Issue by ismacasti** [projectcalico/calico#2539]
The latest Calico version, v3.6.1, was released with a bug that makes IPv6 only unusable. It was quickly fixed here https://github.com/projectcalico/confd/pull/231 and scheduled for v3.7.0.

I would like to ask for a v3.6.2 released with the mentioned fix, so we can use it without having to wait for 3.7.0.

## Expected Behavior
A new version should be released with the IPv4 hash router ID fix.

## Current Behavior
v3.6.1 is not working correctly on IPv6 only nodes. 
v3.7.0 is far away and might have breaking changes.

## Context
I am working on using Calico for a IPv6 only Kubernetes cluster. For that to be stable Calico needs to behave correctly when no IPv4 addresses are available on a node.

## Your Environment
Kubernetes 1.13.5

Thanks!

**Comment by josdotso** [comment]
Agreed!

I'm currently using [this hack](https://github.com/josdotso/k6/blob/master/kubernetes/calico.yaml#L8-L27), which is based on this comment: https://github.com/projectcalico/calico/issues/2229#issuecomment-435430481

**Comment by caseydavenport** [comment]
Yep! This was cherry-picked to v3.6 so will be in v3.6.2: https://github.com/projectcalico/confd/pull/231#issuecomment-483354627

I don't have an exact date for that patch yet, I'm afraid, but hopefully soon.
