### ISSUE TITLE
Recommend starting path for Kubernetes is buried too deep and non-obvious

### ISSUE THREAD

**Issue by lxpollitt** [projectcalico/calico#254]
Kubernetes overview page has "Integration Guide (Recommended) - Discusses adding Calico to an existing cluster" far down the page in the "Bare-metal guides" section.  It's nothing to do with bare metal, and it's the recommend way of installing Calico so should be up front.  The "Quick-start guides" section should make it clear these guides are for creating Kubernetes clusters - not just installing Calico.

Kubernetes installation introduction page should put self-hosted before manual installation.  (i.e. swap the order).

**Comment by caseydavenport** [comment]
@lxpollitt yeah, I'm planning on organizing the k8s docs a bit in the 2.0 timeframe.

Started hacking on changes here: #247

**Comment by djosborne** [comment]
Fixed by #268
