### ISSUE TITLE
watchercache.go spamming log - 'Failed to create watcher'

### ISSUE THREAD

**Issue by stevefaro** [projectcalico/calico#2540]
Having upgraded from Calico v1.0 to v1.3 on an EKS cluster I found the calico-typha node log is filled (5 events per second) with errors from watchercache.go. 

2019-04-09 20:26:14.735 [INFO][6] watchercache.go 242: Failed to create watcher ListRoot="/calico/resources/v3/projectcalico.org/bgppeers" error=resource does not exist: BGPPeer with error: the server could not find the requested resource (get BGPPeers.crd.projectcalico.org) performFullResync=true

I have found that no errors are reported when upgrading to v1.1 and v1.2, but both v1.3 and v1.4 report the same error.

Happens when upgrading calico on an existing cluster and when deploying calico v.13 fresh onto a new cluster.

### Existing cluster
1. Delete calico v1.0
 - kubectl delete daemonset calico-node -n kube-system
 - kubectl delete deployment calico-typha -n kube-system
 - kubectl delete deployment calico-typha-horizontal-autoscaler -n kube-system
2. Install calico (kubectl apply -f https://raw.githubusercontent.com/aws/amazon-vpc-cni-k8s/master/config/v1.3/calico.yaml)
3. View log (kubectl logs -f calico-typha-cc5f6b66f-fwppc -n kube-system)

### Clean Cluster
1. Deploy a EKS K8s cluster
2. Install calico (kubectl apply -f https://raw.githubusercontent.com/aws/amazon-vpc-cni-k8s/master/config/v1.3/calico.yaml)
3. View log (kubectl logs -f calico-typha-cc5f6b66f-fwppc -n kube-system)

## Your Environment

* Calico version 1.3 & 1.4
* Orchestrator version (e.g. kubernetes, mesos, rkt): Kubernetes 1.11 (AWS EKS)
* Operating System and version: Amazon Linux

**Comment by pajel** [comment]
Same happens on Kubernetes 1.12.6 (AWS EKS) for Calico version 1.3 and 1.4.
Does not happen for version 1.2 (https://raw.githubusercontent.com/aws/amazon-vpc-cni-k8s/master/config/v1.2/calico.yaml)

**Comment by caseydavenport** [comment]
> error=resource does not exist: BGPPeer with error: the server could not find the requested resource (get BGPPeers.crd.projectcalico.org) 

Looks like that manifest is missing the BGPPeer CRD, which is causing the log.

In the v1.2 version of Calico (v3.1.3), typha didn't monitor that resource, so the CRD wasn't needed.

I think the correct fix for now is to update the AWS manifest in the link to include the BGP Peer CRD.

**Comment by caseydavenport** [comment]
Addressed in https://github.com/aws/amazon-vpc-cni-k8s/pull/406
