### ISSUE TITLE
How to change the AS number?

### ISSUE THREAD

**Issue by calixwu** [projectcalico/calico#2541]
We use calico router reflector and configure each node with node-specific peers to the calico router reflector. 

For some reason, we have to change the AS number, so here's our steps:
1.  Run ```calicoctl config set asNumber 65523``` to change the AS number.
2. Update all the node-specific peers with the new AS number.

But after we finished the first step, some errors occurred in bird logs and the peer broke. See "## Current Behavior" below. 

We want to know how to change the AS number safely.

## Expected Behavior
Can change the AS number.

## Current Behavior
1. Occurr error in bird log:  Bad peer AS: 65523
2. ```calicoctl node status``` can show the BGP peer has broken with info:  Connection reset by peer.

## Your Environment
* calico v2.6.7
* k8s

**Comment by calixwu** [comment]
Anybody home ~~? 😟

**Comment by caseydavenport** [comment]
Mandatory "Calico v2.6 is _incredibly_ old, and I strongly recommend updating to a modern version of Calico" comment.

That said, I think you're doing the right thing - setting the global AS number should change the AS for all Calico nodes and the RR. I'd check the generated BIRD configs to see if it is taking effect.

**Comment by calixwu** [comment]
@caseydavenport 

The BIRD configs was generated correctly, but the ip routes were deleted for few seconds until the new AS was actually taking effect, which caused the network paralysis.

**Comment by calixwu** [comment]
We are considering upgrade calico to v3, but there are some troubles with the data migration.

**Comment by calixwu** [comment]
@caseydavenport 
By the way, Will (or When will) you give up maintaining the v2.6.x version of calico in the future?

**Comment by caseydavenport** [comment]
>  ip routes were deleted for few seconds until the new AS was actually taking effect, which caused the network paralysi

Ah, so the AS did change correctly just that there was a transient BGP issue? Did the sessions eventually go back to "Established"?

**Comment by calixwu** [comment]
@caseydavenport 

They eventually go back to "Established".

**Comment by caseydavenport** [comment]
I think this is working as expected - changing AS number on a live cluster will result in momentary re-establishment of BGP sessions, and likely a window of dropped traffic.

Generally it is expected that the BGP AS numbers will be configured prior to running workloads on the cluster.
