### ISSUE TITLE
IPv6 issues after upgrading to k8s 1.13.5

### ISSUE THREAD

**Issue by CallMeFoxie** [projectcalico/calico#2553]
## Expected Behavior
Create a pod. 

## Current Behavior
Fails with error `failed to get IPv6 addresses for host side of the veth pair`

## Possible Solution
No idea.

## Steps to Reproduce (for bugs)
1. Set up k8s 1.13.5 with calico 3.3.6
2. Set up IPv6 alongside IPv4
3. Start as many pods as needed to trigger this issue
4. Fail to start another pod

## Context
After upgrading to k8s 1.12.5 -> 1.13.5 pods seem to have a random issue during start up:
```
failed to get IPv6 addresses for host side of the veth pair
```

the whole log (some hostnames are censored):
```
kubelet[1670]: 2019-04-16 12:15:55.885 [INFO][13522] ipam.go 307: Block '2a02:598:64:8012:30::/116' provided addresses: [2a02:598:64:8012:30::3af] handle="calico-k8s-network.d6ae09d022419e0287f0ab5918497e861e9839cd683bdf1ee2bf053da03a6881" host="xyz"
kubelet[1670]: 2019-04-16 12:15:55.890 [INFO][13522] ipam.go 456: Auto-assigned 1 out of 1 IPv6s: [2a02:598:64:8012:30::3af] handle="calico-k8s-network.d6ae09d022419e0287f0ab5918497e861e9839cd683bdf1ee2bf053da03a6881" host="xyz"
 kubelet[1670]: Calico CNI IPAM assigned addresses IPv4=[10.66.165.205] IPv6=[2a02:598:64:8012:30::3af]
kubelet[1670]: 2019-04-16 12:15:55.893 [INFO][13490] network.go 75: Setting the host side veth name to cali12434e02726 ContainerID="d6ae09d022419e0287f0ab5918497e861e9839cd683bdf1ee2bf053da03a6881" Namespace="inzeraty" Pod="inz-proxy-646485c656-s54mx" WorkloadEndpoint="xyz-k8s-inz--proxy--646485c656--s54mx-eth0"
kubelet[1670]: 2019-04-16 12:15:55.894 [ERROR][13490] network.go 240: **Error creating veth: failed to get IPv6 addresses for host side of the veth pair ** ContainerID="d6ae09d022419e0287f0ab5918497e861e9839cd683bdf1ee2bf053da03a6881" Namespace="inzeraty" Pod="inz-proxy-646485c656-s54mx" WorkloadEndpoint="fvirtbase138.ko.seznam.cz-k8s-inz--proxy--646485c656--s54mx-eth0"
kubelet[1670]: 2019-04-16 12:15:55.894 [ERROR][13490] k8s.go 378: Error setting up networking ContainerID="d6ae09d022419e0287f0ab5918497e861e9839cd683bdf1ee2bf053da03a6881" Namespace="inzeraty" Pod="inz-proxy-646485c656-s54mx" WorkloadEndpoint="fvirtbase138.ko.seznam.cz-k8s-inz--proxy--646485c656--s54mx-eth0" error=failed to get IPv6 addresses for host side of the veth pair
kubelet[1670]: 2019-04-16 12:15:55.894 [INFO][13490] k8s.go 370: Releasing IPAM allocation(s) after failure ContainerID="d6ae09d022419e0287f0ab5918497e861e9839cd683bdf1ee2bf053da03a6881" Namespace="inzeraty" Pod="inz-proxy-646485c656-s54mx" WorkloadEndpoint="fvirtbase138.ko.seznam.cz-k8s-inz--proxy--646485c656--s54mx-eth0" endpointIPs=[]string{"10.66.165.205/32", "2a02:598:64:8012:30::3af/128"}
```

my cni conflist:
```
{
  "cniVersion": "0.3.0",
  "name": "calico-k8s-network",
  "plugins": [
    {
      "etcd_ca_cert_file": "/www/adm/calico/cert/etcd-ca.pem",
      "etcd_cert_file": "/www/adm/calico/cert/etcd-cert.pem",
      "etcd_endpoints": "<censored>",
      "etcd_key_file": "/www/adm/calico/cert/etcd-key.pem",
      "ipam": {
        "assign_ipv4": "true",
        "assign_ipv6": "true",
        "ipv4_pools": [
          "10.66.165.0/24"
        ],
        "ipv6_pools": [
          "2a02:598:64:8012:30::/116"
        ],
        "type": "calico-ipam"
      },
      "kubernetes": {
        "kubeconfig": "/www/adm/kubernetes/conf/kubeconfig.kubelet.yaml"
      },
      "log_level": "info",
      "policy": {
        "type": "k8s"
      },
      "type": "calico"
    },
    {
      "capabilities": {
        "portMappings": true
      },
      "snat": true,
      "type": "portmap"
    },
    {
      "capabilities": {
        "bandwidth": true
      },
      "type": "bandwidth"
    }
  ]
}
```
However while this error is happening with one pod sandbox, another pod can come and start up meanwhile just fine. This seems like some weird race condition. Also this has never happened with kubelet 1.12.5 and downgrading to it works just fine.

Rebooting the node makes no difference either. It just will eventually happen (generally around 10th - 15th pod spawned.) - quick and often cronjobs are the best trigger it seems.

Also I have been unable to trigger this issue with `cri-o 1.14.0` and debian buster + kubelet 1.13.5 which handles the CNI on its own instead of kubelet so far.

## Your Environment
* Calico version 3.3.3/3.3.6
* Orchestrator version (e.g. kubernetes, mesos, rkt): k8s, docker 18.09.2/3/4/5 (a mix across several nodes)
* Operating System and version: Debian Stretch, kernel 4.9.144
* Link to your project (optional): ---

I'll be happy to investigate further and report further info if you have any questions. (Sadly I have no idea how to attach dlv remote debugger to this...)

**Comment by CallMeFoxie** [comment]
Testing cri-o as well and the result is:
```
-- all with calico 3.3.6
cri-o 1.14.0 + debian buster + kernel 4.19 + kubelet 1.13.5 ok
cri-o 1.14.0 + debian buster + kernel 4.19 + kubelet 1.12.5 ok
docker 18.9.5 + debian stretch + kernel 4.9 + kubelet 1.13.5 BAD
docker 18.9.5 + debian stretch + kernel 4.9 + kubelet 1.12.5 ok
```

**Comment by caseydavenport** [comment]
In this case, Calico is just trying to query the addresses from the host-side of the veth pair, and failing to find and IPv6 addresses. Specifically this bit of code: https://github.com/projectcalico/cni-plugin/blob/79704ebd41315e77d9ecdd57db52e634e03fd7b1/internal/pkg/utils/network_linux.go#L190-L205

In this case, the v6 LL address should be assigned as part of creating the interface and isn't something that Calico is repsonsible for. If it's not showing up, it sounds like it might be a misconfiguration on the host or something else.. not sure what might cause it to fail for only some interfaces.

**Comment by CallMeFoxie** [comment]
Tried with kubelet 1.14.1, same thing. 

I have no idea what host config could make this happen, more so if kubelet 1.12.5 works fine :|

**Comment by CallMeFoxie** [comment]
Got more testing done, this time testing crio 1.14.0+debian stretch and it seems to be fine:

```
-- all with calico 3.3.6
cri-o 1.14.0 + debian buster + kernel 4.19 + kubelet 1.13.5 ok
cri-o 1.14.0 + debian buster + kernel 4.19 + kubelet 1.12.5 ok
cri-o 1.14.0 + debian stretch + kernel 4.9 + kubelet 1.13.5 ok
docker 18.9.5 + debian stretch + kernel 4.9 + kubelet 1.12.5 ok
docker 18.9.5 + debian stretch + kernel 4.9 + kubelet 1.13.5 BAD
docker 18.9.5 + debian stretch + kernel 4.9 + kubelet 1.14.1 BAD
```

**Comment by CallMeFoxie** [comment]
OK so I've added a 5 second sleep to here: https://github.com/projectcalico/cni-plugin/blob/79704ebd41315e77d9ecdd57db52e634e03fd7b1/internal/pkg/utils/network_linux.go#L189
and so far it has been running ok for 1.5 hours, which is 4 times as long as it normally takes to trigger.
Maybe the ipv6 LL is not set in time due to some change in kubelet? Anybody has any clues what relevant has changed? :)

**Comment by CallMeFoxie** [comment]
Yep, most likely a race condition, the code between

```
create veth
    v
interface up
    v
enable IPv6
    v
LL gets set by kernel
    v
calico CNI tries to read it
```

has shortened and the LL is not there in time. I think that the correct place to fix this is in Calico :) The issue was there always, but kubelet is now faster :D

I will try to make a quick fix by adding a retry to the IPv6 `netlist.AddrList` with a delay inbetween, that should fix it.

**Comment by caseydavenport** [comment]
Fixed in https://github.com/projectcalico/cni-plugin/pull/730 - thanks for the PR!
