### ISSUE TITLE
How to use calico network with docker swarm

### ISSUE THREAD

**Issue by hegphegp** [projectcalico/calico#2576]
**Description**

<b>How to use calico network with docker swarm, I don't want to user overlay network. Could provide some blogs or some examples about calico network with docker swarm?</b>

**software info:**

```
Docker version 18.09.5-ce
Calicoctl Version 3.6.1
```

**Comment by caseydavenport** [comment]
Calico currently does not support Docker in Swarm mode - you could check out the libnetwork plugin for Calico though, which might get you in the right direction: https://github.com/projectcalico/libnetwork-plugin

It's currently a community supported project though, and isn't being actively developed by the core team.
