### ISSUE TITLE
Clean upgrade of Canal from 2.6.11 to 3.7.2 results in no pods on pod network starting

### ISSUE THREAD

**Issue by blurpy** [projectcalico/calico#2607]
We started with Canal 2.6.11, that was installed in a different namespace than default (called network), so during this upgrade we wanted to move everything into kube-system to follow the default path. In order to do so we had to uninstall Canal 2.6.11 completely before installing Canal 3.7.2. After the upgrade, only pods on the host network would start. All other pods were either in status Error or ContainerCreating (never changing from that state).

## Expected Behavior
I expected all pods on the pod network to complete startup and go into Running state.

## Current Behavior
All pods on pod network stuck in Error or ContainerCreating state.
Canal pods start fine, and I found no errors in the logs.

The other pods have events such as these:

```
Normal   SandboxChanged          19m (x2 over 20m)     kubelet, demoworker4test  Pod sandbox changed, it will be killed and re-created.
Normal   Pulled                  19m                   kubelet, demoworker4test  Container image "quay.io/kubernetes-ingress-controller/nginx-ingress-controller:0.15.0" already present on machine
Normal   Created                 19m                   kubelet, demoworker4test  Created container
Normal   Started                 19m                   kubelet, demoworker4test  Started container
Warning  FailedCreatePodSandBox  7m30s                 kubelet, demoworker4test  Failed create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container "2b8b9cbd2e941115a96fbecf62fad632e23480b70d1649429e52b6056b12103d" network for pod "nginx-ingress-controller-m2wlg": NetworkPlugin cni failed to set up pod "nginx-ingress-controller-m2wlg_ingress" network: Unauthorized
```

## Possible Solution

The issue was solved like this, on each node:

1. `# mv /etc/cni/ /etc/cni.bak`
2. `# reboot`

Pods started fine after this. Looks like the new version comes with /etc/cni/net.d/10-canal.conflist while the old version comes with /etc/cni/net.d/10-calico.conflist. Having both in the same folder results in the issue we see.

## Steps to Reproduce (for bugs)

These are the steps we used to try a safe upgrade, without the risk of having old leftover state.

1. Drained all nodes
2. Uninstalled Canal 2.6.11, including rbac, using original manifests
3. Rebooted all nodes to get rid of old iptables rules and cali-interfaces
4. Installed Canal 3.7.2
5. Undrained all nodes

## Your Environment

* Canal version [3.7.2](https://docs.projectcalico.org/v3.7/getting-started/kubernetes/installation/hosted/canal/canal.yaml)
* Orchestrator version: Kubernetes 1.12.7
* Operating System and version: CentOS 7.6 and RedHat 7.6

**Comment by caseydavenport** [comment]
One option would be to set this variable in the new install-cni manifest: https://github.com/projectcalico/cni-plugin/blob/master/k8s-install/scripts/install-cni.sh#L182

Setting `OLD_CNI_CONF_NAME=10-calico.conflist` would clean up the old file while installing the new one.
