### ISSUE TITLE
Pod memory increasing constantly

### ISSUE THREAD

**Issue by mukgupta** [projectcalico/calico#2621]
The memory usage of my calico pod is increasing regularly. I am using quay.io/calico/node:v3.1.3 image deployed on AWS EKS 1.11

See the attached screenshot
![image](https://user-images.githubusercontent.com/4718916/58150033-f46eb700-7c82-11e9-976f-13d14be6da90.png)

## Expected Behavior
The memory shall remain constant or at least get freed at frequent intervals.

## Current Behavior
Memory keeps rising regularly

## Context

Our pods are going to get restarted in few days if memory keeps rising. Currently our monitoring system is flagging high memory usage.

## Your Environment
* Calico version: 3.1.3
* Orchestrator version: AWS EKS v1.11.5
* Operating System (Host): Ubuntu 18

**Comment by lwr20** [comment]
Looks very similar to https://github.com/projectcalico/calico/issues/2194

**Comment by mukgupta** [comment]
@lwr20 : In my case it doesn't look like an accounting issue since `docker stat`, `ps` and `/sys/fs/cgroup/memory/memory.usage_in_bytes` seem to report similar values

```bash
$ docker stats 8611c5ca3ec2 --no-stream
CONTAINER ID        NAME                                                                                   CPU %               MEM USAGE / LIMIT   MEM %               NET I/O             BLOCK I/O           PIDS
8611c5ca3ec2        k8s_calico-node_calico-node-4cnkh_kube-system_5340b8d7-47b0-11e9-8779-0620df6742c4_0   0.80%               187.1MiB / 256MiB   73.08%              0B / 0B             3.64MB / 24.6kB     16
```

```bash
/# ps -o rss,comm
RSS  COMMAND
   4 runsvdir
   4 runsv
186m calico-felix
1032 sh
   4 ps
```

```bash
/# cat /sys/fs/cgroup/memory/memory.usage_in_bytes
198717440
```

```bash
/# cat /sys/fs/cgroup/memory/memory.stat
cache 2330624
rss 193736704
rss_huge 6291456
shmem 0
mapped_file 983040
dirty 4096
writeback 0
pgpgin 35096870
pgpgout 35050535
pgfault 57392991
pgmajfault 65
inactive_anon 0
active_anon 193667072
inactive_file 282624
active_file 2048000
unevictable 0
hierarchical_memory_limit 268435456
total_cache 2330624
total_rss 193736704
total_rss_huge 6291456
total_shmem 0
total_mapped_file 983040
total_dirty 4096
total_writeback 0
total_pgpgin 35096870
total_pgpgout 35050535
total_pgfault 57392991
total_pgmajfault 65
total_inactive_anon 0
total_active_anon 193667072
total_inactive_file 282624
total_active_file 2048000
total_unevictable 0
```

**Comment by lwr20** [comment]
Felix CPU/memory stats might be useful here (though turning them on will cause a calico-node restart): https://docs.projectcalico.org/v3.1/reference/felix/prometheus

Also - 3.1.3 is almost a year old now (30 May 2018) - you might consider upgrading calico either to 3.1.6 or to a more recent minor version (3.7.2 is the very latest).

**Comment by mukgupta** [comment]
@lwr20 : I have those metrics already enabled and it looks they report similar values:

**go_memstats_sys_bytes**
![image](https://user-images.githubusercontent.com/4718916/58170386-ee8fca80-7cb0-11e9-940b-6417c2f58050.png)



**go_memstats_heap_alloc_bytes**

![image](https://user-images.githubusercontent.com/4718916/58170286-9a84e600-7cb0-11e9-88b4-3210cebc308b.png)

I am using AWS EKS and they only updated the supported calico version recently (https://github.com/aws/amazon-vpc-cni-k8s/tree/master/config).  In the latest version of their configuration, they support v3.3.6. I can upgrade to latest version, just want to make sure that the issue will be fixed post upgrade since upgrade involves a cost

**Comment by lwr20** [comment]
> just want to make sure that the issue will be fixed post upgrade
The only way to be *sure* would be to set up a test rig running 3.3.6, drive it in a similar way to your prod system and see if you hit the same issue.

**Comment by lwr20** [comment]
There are probably a bunch of useful diags we could get that would help narrow this down.  @caseydavenport @fasaxc any recommendations?

**Comment by caseydavenport** [comment]
We did also just fix a leak in Felix: https://github.com/projectcalico/felix/pull/2023

**Comment by tmjd** [comment]
Version v3.7.3 was released yesterday which includes the fix Casey mentioned. Please update to that version and see if the memory usage increase is fixed.

**Comment by tmjd** [comment]
I'm going to close this issue as I believe it has been fixed. If you are able to test with v3.7.3 and still see the problem please respond and we can re-open this issue.
