### ISSUE TITLE
cni fails when blockSize: 32 due to blackhole route

### ISSUE THREAD

**Issue by devyx** [projectcalico/calico#2624]
## Expected Behavior
Pod starts with configured ipAddr

## Current Behavior
CNI plugin fails witih:
```k8s.go 374: Error setting up networking ContainerID="xxx" Namespace="default" Pod="test" WorkloadEndpoint="xxx" error=error adding  host side routes for interface: calixxx, error: route (Ifindex: 12, Dst: 10.0.2.1/32, Scope: 253) already exists for an interface other than 'calixxx'```
due to existance of blackhole route:
```blackhole 10.0.2.1 proto bird```

## Possible Solution
Do not set blackhole route for /32 blocksizes

## Steps to Reproduce (for bugs)
1. create ipv4 ippool with blockSize 32
2. create pod with annotation ```cni.projectcalico.org/ipAddrs:``` with address from the pool
3. pod creation fails 

## Context
There may be a simillar issue for IPv6, but I did not tested that.

## Your Environment
* Calico version: 3.7.2 
* Orchestrator version k8s 1.13.5
* Operating System and version: Debian buster

**Comment by spikecurtis** [comment]
@devyx can you tell us a little bit about why you want to set the block size to /32 in the first place?

**Comment by halfcrazy** [comment]
copy from #3635 
One question is the blackhole router necessary or in which scenario we can disable programming blackhole router?

**Comment by caseydavenport** [comment]
The blackhole route is useful only when the blocksize includes more than one address.

It's purpose is to prevent routing loops when pods on the host send traffic to an address that is not actually allocated to a pod, but within the pod's block CIDR. Without the blackhole, this traffic would be sent via the default route into the network, and potentially bounced _back_ to the host that originated it.

That does raise an interesting point now that I think about it, though. Presumably we _should_ blackhole this traffic if there are no pods assigned that address.

e.g., when a pod is assigned the address, and then the pod is removed, we'll end up with a block on a host that has no IP assigned to it. If we do not black hole that traffic, then it will follow the default route, which isn't desirable.

**Comment by caseydavenport** [comment]
Alternatively, maybe we should be writing a blackhole for the entire IP pool CIDR, so that we only ever send traffic for routes that have been explicitly programmed (e.g., via BIRD or the CNI plugin).

**Comment by caseydavenport** [comment]
related: https://github.com/projectcalico/calico/issues/3498#issuecomment-499319183

**Comment by halfcrazy** [comment]
Thanks for explaining. I like the idea of writing blackhole routes for the entire IP pools.

**Comment by lxpollitt** [comment]
I think blackhole route for the entire IP pool would break any BGP topology using "downward default".  i.e. The node has a default route to the ToR and is not receiving any other routes from the ToR.

**Comment by caseydavenport** [comment]
Hm, yes true. That's probably why we didn't do it in the first place!

I'm not sure what the answer here is, then. It sounds like we need some configuration that is aware of whether or not addresses have actually been assigned.

**Comment by fasaxc** [comment]
I believe this is fixed in v3.21 (and a few releases before that).  We no longer write a blackhole route for /32 blocks to avoid conflicts of this type.
