### ISSUE TITLE
Documentation is missing a section for CNI

### ISSUE THREAD

**Issue by lxpollitt** [projectcalico/calico#265]
Probably mean moving much of the docs from github/calico-cni into the main docs reference section.  Then add the standard header about where to find user face docs (see github/felix for example) to the calico-cni repo.

**Comment by caseydavenport** [comment]
#266 and https://github.com/projectcalico/calico-cni/pull/220 and https://github.com/projectcalico/k8s-policy/pull/61 will fix this.
