### ISSUE TITLE
Calico worker nodes moving to CrashLoopBackOff state after tiller installed 

### ISSUE THREAD

**Issue by BalaVijay193** [projectcalico/calico#2656]
## Expected Behavior
Tiller pod to run properly after installation all pods in kube-system to be on Running state

## Current Behavior
Both Worker nodes (Calico Nodes) moved to CrashLoopBackOff state and Tiller pod in ContainerCreating state

```
[sr-master@sr-master tmp]$ kubectl get pods --namespace kube-system
NAME                                       READY   STATUS              RESTARTS   AGE
calico-etcd-4bzt9                          1/1     Running             0          3h20m
calico-kube-controllers-5d67f6b968-jzzf2   1/1     Running             0          3h20m
**calico-node-6pfp4                          0/1     CrashLoopBackOff    26         116m**
calico-node-kc56p                          1/1     Running             2          3h20m
**calico-node-rr9kh                          0/1     CrashLoopBackOff    26         116m**
coredns-fb8b8dccf-9sr8l                    1/1     Running             0          3h57m
coredns-fb8b8dccf-n7glh                    1/1     Running             0          3h57m
etcd-sr-master                             1/1     Running             0          3h56m
kube-apiserver-sr-master                   1/1     Running             0          3h56m
kube-controller-manager-sr-master          1/1     Running             0          3h56m
kube-proxy-b6d9n                           1/1     Running             0          116m
kube-proxy-dpjnt                           1/1     Running             0          3h57m
kube-proxy-xrqlk                           1/1     Running             0          116m
kube-scheduler-sr-master                   1/1     Running             0          3h56m
kubernetes-dashboard-5f7b999d65-vf9xb      1/1     Running             0          3h18m
**tiller-deploy-9bf6fb76d-swghg              0/1     ContainerCreating   0          75s**
```

##Tiller deploy Describe 
Events:
  Type     Reason                  Age                     From               Message
  ----     ------                  ----                    ----               -------
  Normal   Scheduled               2m44s                   default-scheduler  Successfully assigned kube-system/tiller-deploy-9bf6fb76d-swghg to worker1
  **Warning  FailedCreatePodSandBox  2m43s                   kubelet, worker1   Failed create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container** "998f3a7ff8423f4d40fa15ac2cbf4861b7499249ac44731b95de8e79e83aab16" network for pod "tiller-deploy-9bf6fb76d-swghg": NetworkPlugin cni failed to set up pod "tiller-deploy-9bf6fb76d-swghg_kube-system" network: stat /var/lib/calico/nodename: no such file or directory: check that the calico/node container is running and has mounted /var/lib/calico/
 ...............
  Warning  FailedCreatePodSandBox  2m31s (x4 over 2m34s)   kubelet, worker1   (combined from similar events): Failed create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container "a3ac49a4b38f3e046f61ac8e42f6e8437906d014c109e211772db86d48bff92e" network for pod "tiller-deploy-9bf6fb76d-swghg": NetworkPlugin cni failed to set up pod "tiller-deploy-9bf6fb76d-swghg_kube-system" network: stat /var/lib/calico/nodename: no such file or directory: check that the calico/node container is running and has mounted /var/lib/calico/

##Worker nodes description

Tolerations:     :NoSchedule
                 :NoExecute
                 CriticalAddonsOnly
                 node.kubernetes.io/disk-pressure:NoSchedule
                 node.kubernetes.io/memory-pressure:NoSchedule
                 node.kubernetes.io/network-unavailable:NoSchedule
                 node.kubernetes.io/not-ready:NoExecute
                 node.kubernetes.io/pid-pressure:NoSchedule
                 node.kubernetes.io/unreachable:NoExecute
                 node.kubernetes.io/unschedulable:NoSchedule
Events:
  Type     Reason   Age                     From              Message
  ----     ------   ----                    ----              -------
  Warning  BackOff  4m48s (x546 over 123m)  kubelet, worker2  Back-off restarting failed container

##Worker1 Node log
[sr-master@sr-master tmp]$ kubectl logs -n kube-system -p calico-node-rr9kh  -c calico-node
Threshold time for bird readiness check:  30s
2019-06-07 14:53:28.779 [INFO][8] startup.go 256: Early log level set to info
2019-06-07 14:53:28.779 [INFO][8] startup.go 276: Using HOSTNAME environment (lowercase) for node name
2019-06-07 14:53:28.779 [INFO][8] startup.go 284: Determined node name: worker1
Calico node failed to start
ERROR: Error accessing the Calico datastore: dial tcp 10.96.232.136:6666: connect: no route to host

##Worker2 Node log
[sr-master@sr-master tmp]$ kubectl logs -n kube-system -p calico-node-6pfp4 -c calico-node
Threshold time for bird readiness check:  30s
2019-06-07 14:58:55.452 [INFO][8] startup.go 256: Early log level set to info
2019-06-07 14:58:55.452 [INFO][8] startup.go 276: Using HOSTNAME environment (lowercase) for node name
2019-06-07 14:58:55.452 [INFO][8] startup.go 284: Determined node name: worker2
Calico node failed to start
ERROR: Error accessing the Calico datastore: dial tcp 10.96.232.136:6666: connect: no route to host

##Kubectl Cluster-info
 kubectl cluster-info
Kubernetes master is running at https://192.168.43.57:6443
KubeDNS is running at https://192.168.43.57:6443/api/v1/namespaces/kube-system/services/kube-dns:dns/proxy

##Kubectl Version
[sr-master@sr-master tmp]$ kubectl version
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.3", GitCommit:"5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0", GitTreeState:"clean", BuildDate:"2019-06-06T01:44:30Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.3", GitCommit:"5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0", GitTreeState:"clean", BuildDate:"2019-06-06T01:36:19Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}

##Helm Version  (Tiller deployed but Error visible)
[sr-master@sr-master tmp]$ helm version
Client: &version.Version{SemVer:"v2.14.1", GitCommit:"5270352a09c7e8b6e8c9593002a73535276507c0", GitTreeState:"clean"}
**Error: could not find a ready tiller pod**
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Calico version v3.4
* Orchestrator version (e.g. kubernetes, mesos, rkt): kubeadm 
* Operating System and version: Centos7
* Link to your project (optional):

**Comment by rafaelvanoni** [comment]
This message seems to indicate the root problem
```ERROR: Error accessing the Calico datastore: dial tcp 10.96.232.136:6666: connect: no route to host```
Was calico running without problems before installing helm/tiller ?

**Comment by BalaVijay193** [comment]
thanks rafaelvanoni for reply
 but i didn't remember (before installation !), can you tell me how to handle this error message ERROR: Error accessing the Calico data store: dial tcp 10.96.232.136:6666: connect: no route to host (this message is only in worker nodes not on master node (kubeadm).
one thing i remember is i have not applied (kubectl -f apply below datastore yaml file) 
kubectl apply -f https://docs.projectcalico.org/v3.3/getting-started/kubernetes/installation/hosted/kubernetes-datastore/calico-networking/1.7/calico.yaml
is it compulsory

**Comment by rafaelvanoni** [comment]
That message means that calico can't reach etcd, it's likely a connectivity issue with the etcd instance or etcd itself isn't available.

**Comment by BalaVijay193** [comment]
all three vms are on same machine (laptop). Connectivity issues ! Can you brief me on master node only we will be installing calico stuff do we need to install on worker nodes also (Kubeadm)
