### ISSUE TITLE
`calicoctl config` help / doc should better emphasize that it is for *Felix* settings

### ISSUE THREAD

**Issue by lwr20** [projectcalico/calico#267]
http://docs.projectcalico.org/v2.0/reference/calicoctl/commands/config

has a table of settings, and indicates that calicoctl can load its config from a file (defaults to /etc/calico/calicoctl.cfg) which contains config in json or yaml format.  But that information alone is not enough for me to make up a config file.
```
The table below details the valid config options.

 Name            | Scope       | Value                                  |
-----------------+-------------+----------------------------------------+
 logLevel        | global,node | none,debug,info,warning,error,critical |
 nodeToNodeMesh  | global      | on,off                                 |
 asNumber        | global      | 0-4294967295                           |
 ipip            | global      | on,off                                 |
```

With an example, I think that would be much clearer.

**Comment by caseydavenport** [comment]
@lwr20 I think this just needs to be a link to this doc: http://docs.projectcalico.org/v2.0/reference/calicoctl/setup/etcdv2

**Comment by lwr20** [comment]
Yep - agree that a link to that place with the example would be sufficient.

**Comment by caseydavenport** [comment]
@lwr20 I think you're confusing two types of configuration.

There is Calico configuration (e.g Felix log level) which calicoctl can configure, and there is `calicoctl` configuration which tells calicoctl how to connect to the datastore.

**Comment by lwr20** [comment]
You're right.  Now is that going to be a common misunderstanding or am I simply an idiot?...

**Comment by djosborne** [comment]
I'd say common misunderstanding :smiley: The doc should be improved to better explain this.


The doc states:

>The calicoctl config command allows users to view or modify low-level component configurations for Felix and BGP.

We should explicitly state this is not for configuring calicoctl nor other general node settings, and add references to 
- the calicoctl configuration guide: http://docs.projectcalico.org/v2.0/reference/calicoctl/setup/etcdv2
- [the node configuration guide, once it exists](https://github.com/projectcalico/calico/issues/284)

In the help string, we state:

>These commands can be used to manage global system-wide configuration and some
node-specific low level configuration.

Again, we should explicitly state this is for Felix and BGP only.

**Comment by caseydavenport** [comment]
It's not just for Felix settings - it's for general Calico configuration (Felix, BGP).

> The calicoctl config command allows users to view or modify low-level component configurations for Felix and BGP.

I think this is pretty explicit already. I don't think there is anything to do for this issue.

Here's is the usage guide for calicoctl: http://docs.projectcalico.org/v2.2/usage/calicoctl/install-and-configuration

If there are issues with that doc then please open new issues against that page.
