### ISSUE TITLE
Calico keeps making itself as the first rule in iptables chains

### ISSUE THREAD

**Issue by huang195** [projectcalico/calico#2672]
I'm running a recent version of Kubernetes which uses Calico as the network provider. When looking at iptables entries that Calico puts onto the host machine, I noticed that Calico reassert itself to be always the first rule in various iptables chains (I checked PREROUTING and FORWARD only). So even if I put my own iptables rules in these chains as the first ones, after a few seconds, Calico puts its own rule at the head of the chain again. Is this expected behavior? If so, is there a way to turn this "feature" off?

**Comment by lwr20** [comment]
https://docs.projectcalico.org/v3.7/reference/calicoctl/resources/felixconfig
I think you want `chainInsertMode`

**Comment by huang195** [comment]
Thanks @lwr20 ! Default mode is `insert`, no wonder it puts it in the front. Just curious, why does Calico insist on doing this periodically? In case someone inadvertently deleted the rule?

**Comment by lwr20** [comment]
From that doc:
```
Insert is the safe default since it prevents Calico’s rules from being bypassed. If you switch to Append mode, be sure that the other rules in the chains signal acceptance by falling through to the Calico rules, otherwise the Calico policy will be bypassed.
```

Its very easy to add a rule which totally bypasses all the calico rules, leading to a setup which is not secured at all by Calico.  

The default is more secure, and the existence of the flag means that users who know what they are doing can turn it off.

**Comment by huang195** [comment]
So I followed the instructions on the page above and tried to modify these configurations, but got an error that I don't know how to interprete:

```
root@haih-istio1:~# cat felix.yml 
apiVersion: projectcalico.org/v3
kind: FelixConfiguration
metadata:
  name: default
spec:
  ipsetsRefreshInterval: 0
  iptablesRefreshIntervalSecs: 0
  routeRefreshIntervalSecs: 0
root@haih-istio1:~# DATASTORE_TYPE=kubernetes KUBECONFIG=/etc/kubernetes/admin.conf ./calicoctl apply -f felix.yml 
Failed to execute command: Unknown resource type (FelixConfiguration) and/or version (projectcalico.org/v3)
```

**Comment by huang195** [comment]
Well, the way around this seems to be setting environment variables on the calico-node daemonset. That seems to have worked so far. Closing this issue.
