### ISSUE TITLE
calico-node 3.7.3 node ready on master on k8s v1.15- felix readiness failed

### ISSUE THREAD

**Issue by subodhp** [projectcalico/calico#2681]
## Expected Behavior
calico-node running on master node after taint removal, it is working on the worker node as expected.

## Current Behavior
calico-node not running on the master node, but running fine on the worker node.

## Steps to Reproduce (for bugs)

kubeadm init --pod-network-cidr=10.244.0.0/16
Updated the https://docs.projectcalico.org/v3.7/manifests/calico.yaml with above Pod Network CIDR.
```
root:~# kubectl get pods --all-namespaces=true
NAMESPACE     NAME                                       READY   STATUS    RESTARTS   AGE
kube-system   calico-kube-controllers-6fb584dd97-bhzwx   1/1     Running   0          2m52s
kube-system   calico-node-lqvjw                          1/1    Running   0          2m52s
kube-system   calico-node-pq59r                          0/1     Running   0          2m52s
kube-system   coredns-5c98db65d4-q9swg                   1/1     Running   2          58m
kube-system   coredns-5c98db65d4-z9bqw                   1/1     Running   2          58m
kube-system   etcd-ninja-laptop                          1/1     Running   2          57m
kube-system   kube-apiserver                1/1     Running   2          57m
kube-system   kube-controller-manager       1/1     Running   2          57m
kube-system   kube-proxy-sr67l                           1/1     Running   0          28m
kube-system   kube-proxy-vhtsw                           1/1     Running   2          58m
kube-system   kube-scheduler                1/1     Running   2          57m
```

## Your Environment

* Calico version - 3.7.3
* Orchestrator version (e.g. kubernetes, mesos, rkt): v1.15.0
* Operating System and version: 4.18.0-22-generic #23~18.04.1-Ubuntu SMP
* Link to your project (optional):

**Comment by lwr20** [comment]
`kubectl logs` and `kubectl describe` for the non-ready pod would be helpful

**Comment by RotemEmergi** [comment]
kubectl version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-19T16:40:16Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-19T16:32:14Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}

[describe-pod-calico-node-g7nn7.txt](https://github.com/projectcalico/calico/files/3323927/describe-pod-calico-node-g7nn7.txt)
[logs-calico-node-g7nn7.txt](https://github.com/projectcalico/calico/files/3323928/logs-calico-node-g7nn7.txt)

**Comment by lwr20** [comment]
```
Warning  Unhealthy  7m50s                   kubelet, node-worker-1  Readiness probe failed: calico/node is not ready: BIRD is not ready: BGP not established with 192.168.0.1
```
So looks like your calico-nodes are trying to peer with 192.168.0.1.  Given that that isn't one of your node IPs, have you configured that as a BGPPeer or something?  What's the output of `calicoctl get bgppeer` and `calicoctl get nodes`?

https://docs.projectcalico.org/v3.7/getting-started/calicoctl/install has info on how to install calicoctl if you need it.

FWIW, our CI runs calico v3.7 on k8s v1.15 nightly and is not hitting this, so I currently believe its a config issue.

**Comment by flyznex** [comment]
I have same problems with k8s v1.14.
My testing environment include 3 nodes using CentOS 7 in virtualBox. One node have 2 Network interfaces with 2 gateways. The first time setup kubeadm with param ` --pod-network-cidr=10.244.0.0/16`. All node come ready with no error, `calico-pod-xxxx` is running and already in state `ready`. When I reboot all virtual machine, all node ready, but `calico-pod-xxx` still running but state is not ready. 
Here is my output:
- `calicoctl get bgppeers`:
`NAME   PEERIP   NODE   ASN  `

- `calicoctl get ippools`:
`NAME                  CIDR            SELECTOR   `
`default-ipv4-ippool   10.244.0.0/16   all()   `

- `calicoctl get nodes`
`NAME         `
`kubemaster   `
`kubenode1    `
`kubenode2    `

**Comment by caseydavenport** [comment]
Yeah - looks like there are only two nodes in the cluster, but Calico thinks there are three.

Try deleting kubenode2 - `calicoctl delete node kubenode2` (provided it really doesn't exist!)

**Comment by flyznex** [comment]
I have 3 node named: kubemaster, kubenode1 and kubenode2. I think the reason is come from setup 2 network interfaces each one machine. 
- 1 interface with gateway: `192.168.0.1` with DHCP enable and all nodes can access internet over it.
- 1 interface with gateway: `192.168.99.1` with static IP address. I use it to connect 3 node above.
I set `IP_AUTODETECTION_METHOD=can-reach=192.168.99.1` but my problems are not solve

**Comment by tmjd** [comment]
You should check `calicoctl get nodes -o yaml` and see what address is being selected for each node and that it is your 192.168.100.x address, that I believe you expect it to use.
You also need to make sure you have `IP=autodetect` set (I believe this is the default now), or else the previously detected address will be used from the datastore.

If the interfaces with the IP addresses that calico should use are the same on each of your hosts you can use `interface` option with IP_AUTODETECTION_METHOD.

My guess would be that your 192.168.99.1 address can be reached over more than one interface one or more nodes and so using the can-reach is not effective for selecting the correct address.

If none of the above works, I believe you could turn off the autodetection and then manually update the nodes in the datastore to have the correct address.

**Comment by flyznex** [comment]
Thanks for your suggest, I found my problem is about 2 interfaces, all node can be reached over 2 gateway. When I setup to use 1 interface, all things can work properly.
