### ISSUE TITLE
can not open https://docs.projectcalico.org/v3.7/calico-etcd.yaml

### ISSUE THREAD

**Issue by liuchang-icu** [projectcalico/calico#2692]
when i  open this url  ,show . this

<!Doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="docsearch:version" content="master">
    <link rel="shortcut icon" type="image/png" href="/images/favicon.png">
    <link href='https://fonts.googleapis.com/css?family=Roboto:400,100,100italic,300,300italic,400italic,500,500italic,700,700italic,900,900italic' rel='stylesheet' type='text/css'>
    <link href="https://fonts.googleapis.com/css?family=Lato" rel="stylesheet">
    <link rel="stylesheet" href='https://fonts.googleapis.com/css?family=Roboto+Mono' type='text/css'>
    <link rel="stylesheet" href="/css/style.css"/>
    <link rel="stylesheet" href="/css/search.css"/>
    <link rel="stylesheet" href="/css/plugins/offcanvas.css"/>
    <link rel="stylesheet" href="/css/instantsearch/instantsearch.min.css"/>
    <link href="https://www.projectcalico.org/wp-content/themes/dante/css/font-awesome.min.css" rel="stylesheet">
    <script src="/js/jquery-2.2.0.min.js"></script>
    <script src="/js/bootstrap/bootstrap.min.js"></script>
    <script src="/js/instantsearch/instantsearch.min.js"></script>
    <script src="/js/script.js"></script>

    <script src="/js/clipboard.min.js"></script>
    <script src="/js/code-select.js"></script>

    <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-52125893-4', 'auto');
      ga('send', 'pageview');
    </script>
    
    <script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
    new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
    j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
    'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
    })(window,document,'script','dataLayer','GTM-5FQ2QV4');</script>
    
    
<title>404</title>
<meta name="generator" content="Jekyll v3.8.5" />
<meta property="og:title" content="404" />
<meta property="og:locale" content="en_US" />
<meta name="description" content="Uh Oh" />
<meta property="og:description" content="Uh Oh" />
<link rel="canonical" href="https://docs.projectcalico.org/404.html" />
<meta property="og:url" content="https://docs.projectcalico.org/404.html" />
<script type="application/ld+json">
{"description":"Uh Oh","@type":"WebPage","url":"https://docs.projectcalico.org/404.html","headline":"404","@context":"http://schema.org"}</script>

  </head>
  <body>
    
    <noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-5FQ2QV4" height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
    
    <section>
      <nav id="toplevel-nav" class="navbar navbar-default navbar-static-top">
        <div class="container">
          <div class="navbar-header">
            
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#tigera-navbar" aria-expanded="false" aria-controls="tigera-navbar">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            
            <a class="navbar-brand" href="https://projectcalico.org/">
              <img alt="Brand" src="/images/brand.png">
            </a>
          </div>
          <div id="tigera-navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav navbar-right">

              <li class="active"><a href="/v3.6/introduction"><strong>nightly<span class="caret"></span></strong></a>
                <ul>
                    <li><a href="/v3.7/introduction">v3.7 (latest)</a></li>
                    <li><a href="/v3.6/introduction">v3.6</a></li>
                    <li><a href="/v3.5/introduction">v3.5</a></li>
                    <li><a href="/v3.4/introduction">v3.4</a></li>
                    <li><a href="/v3.3/introduction">v3.3</a></li>
                    <li><a href="/v3.2/introduction">v3.2</a></li>
                    <li><a href="/v3.1/introduction">v3.1</a></li>
                    <li><a href="/v3.0/introduction">v3.0</a></li>
                    <li><a href="/v2.6/introduction">v2.6</a></li>
                    <li><a href="/master/introduction">nightly</a></li>
                </ul>
              </li>

              <li><a href="https://projectcalico.org">Home</a></li>

              <li class="active"><a href="https://projectcalico.org/resources"><span>Resources</span></a>
                <ul>
                    <li><a href="/latest/getting-started/"><i class="fa fa-tachometer" aria-hidden="true"></i> &nbsp; Getting Started</a></li>
                    <li><a href=""><i class="fa fa-book" aria-hidden="true"></i> &nbsp; Documentation</a></li>
                    
                    <li><a href="https://www.projectcalico.org/videos"><i class="fa fa-video-camera" aria-hidden="true"></i> &nbsp; Videos &amp; Webinars</a></li>
                    <li><a href="https://www.projectcalico.org/training"><i class="fa fa-mortar-board" aria-hidden="true"></i> &nbsp; Training</a></li>
                    <li><a href="/latest/release-notes/"><i class="fa fa-clock-o" aria-hidden="true"></i> &nbsp; Releases</a></li>
                    <li><a href="https://www.projectcalico.org/blog"><i class="fa fa-bookmark" aria-hidden="true"></i> &nbsp; Blog</a></li>
                </ul>
              </li>
              <li><a href="https://www.projectcalico.org/community">Community</a>
                <ul>
                    <li><a href="https://slack.projectcalico.org/"><i class="fa fa-slack" aria-hidden="true"></i> &nbsp; Slack</a></li>
                    
                    <li><a href="https://www.projectcalico.org/community#events"><i class="fa fa-calendar" aria-hidden="true"></i> &nbsp; Upcoming Events</a></li>
                    <li><a href="https://www.projectcalico.org/newsletters"><i class="fa fa-envelope-o" aria-hidden="true"></i> &nbsp; Newsletter</a></li>
                    <li><a href="https://github.com/projectcalico" target="_blank"><i class="fa fa-github" aria-hidden="true"></i> &nbsp; GitHub</a></li>
                    <li><a href="https://www.projectcalico.org/jobs"><i class="fa fa-briefcase" aria-hidden="true"></i> &nbsp; Jobs</a></li>
                    <li><a href="https://www.projectcalico.org/blog"><i class="fa fa-bookmark" aria-hidden="true"></i> &nbsp; Blog</a></li>
                </ul>
              </li>
              <li><a href="https://www.projectcalico.org/support">Support</a></li>
              <li class="hidden-xs"><a href="https://www.projectcalico.org/support">
                <img class="desktopImage" width="30" align="absmiddle" src="https://www.projectcalico.org/images/tigera_trans_sm.png" alt="Tigera"></a>
              </li>
            </ul>
            <form class="navbar-form visible-xs">
              <ul class="nav navbar-nav navbar-right">
                
                  <li >
                    <a href="/master/introduction">Introduction</a>
                  </li>
                
                  <li >
                    <a href="/master/getting-started">Getting started</a>
                  </li>
                
                  <li >
                    <a href="/master/networking">Networking</a>
                  </li>
                
                  <li >
                    <a href="/master/security">Security</a>
                  </li>
                
                  <li >
                    <a href="/master/maintenance">Maintenance</a>
                  </li>
                
                  <li >
                    <a href="/master/reference">Reference</a>
                  </li>
                
                  <li >
                    <a href="/master/release-notes">Release notes</a>
                  </li>
                
              </ul>
            </form>
          </div>
        </div>
        <div id="navbar" class="navbar-inverse navbar-collapse collapse">
          <div class="container">
            <ul class="nav navbar-nav">
              
                <li>
                  <a href="/master/introduction"><span>Introduction</span></a>
                </li>
              
                <li>
                  <a href="/master/getting-started"><span>Getting started</span></a>
                </li>
              
                <li>
                  <a href="/master/networking"><span>Networking</span></a>
                </li>
              
                <li>
                  <a href="/master/security"><span>Security</span></a>
                </li>
              
                <li>
                  <a href="/master/maintenance"><span>Maintenance</span></a>
                </li>
              
                <li>
                  <a href="/master/reference"><span>Reference</span></a>
                </li>
              
                <li>
                  <a href="/master/release-notes"><span>Release notes</span></a>
                </li>
              
            </ul>
          </div>
          <div class="row">
            <div class="col-sm-0"></div>
          </div>
        </div>
      </nav>
      <div class="container">
        <div class="row row-offcanvas row-offcanvas-left">
          <p class="pull-left visible-xs">
            <button type="button" class="btn btn-primary btn-xs" data-toggle="offcanvas">Toggle nav</button>
          </p>
          <div class="col-xs-6 col-sm-4 col-md-3 sidebar-offcanvas">
            <div class="row">
              <div class="search-input-container" data-toggle="popover" data-placement="bottom"></div>
              <div class="search-container">
                <div class="search-container__results"></div>
                <div class="search-container__pagination"></div>
              </div>
            </div>
            <div id="sidebar">
            	

            </div>
          </div>
          <div class="col-xs-12 col-sm-8 col-md-9">
            <div id="content-main">
              
              <div style="text-align: left; padding: 18px 0 9px 0; min-width: 500px; overflow-x: hidden;">

              <a data-proofer-ignore href="https://github.com/projectcalico/calico/tree/master/404.html" style="color: #999; text-decoration: none; float: right;" target="_blank"><i class="fa fa-github" aria-hidden="true"></i> Edit this page</a></div>
              
              

  <div class="alert alert-warning" role="alert">
    <strong>Warning:</strong>
    
      You're not viewing the <a href="/latest">latest Calico documentation</a>.
    
  </div>

              <h1>404</h1>
              <p>Sorry, this page doesn't exist.</p>

<p>If you are having trouble finding something, <a href='https://slack.projectcalico.org'>contact us on slack!</a></p>

              
              <div style="margin-top: 60px; margin-bottom: 40px; padding-top: 20px; border-top: 1px solid #999; text-align: left; color: #999;">
                <a href="https://www.projectcalico.org/contact?type=docs&file=404.html" style="margin-left: 30px; color: #999; text-decoration: none;" target="_blank"><i class="fa fa-envelope" aria-hidden="true"></i> Provide Feedback</a>
                <a href="https://www.projectcalico.org/community#slack" style="margin-left: 30px; color: #999; text-decoration: none;" target="_blank"><i class="fa fa-slack" aria-hidden="true"></i> Get Help via Slack</a>
                <a href="https://www.projectcalico.org/training" style="margin-left: 30px; color: #999; text-decoration: none;" target="_blank"><i class="fa fa-graduation-cap" aria-hidden="true"></i> Training</a>
              </div>
              
            </div>
          </div>
        </div>
      </div>
    </section>

    <script src="/js/searchConfig.js"></script>

    <script type="text/template" id="search-results-template">
      
      <div class="search-results">
        {{#hits}}

        {{#shouldDisplayTopCategory}}
        {{#hierarchy.lvl0}}
          <a href="{{url}}" class="search-results__group-header">
            {{{_highlightResult.hierarchy.lvl0.value}}}
          </a>
        {{/hierarchy.lvl0}}
        {{/shouldDisplayTopCategory}}

        <div class="search-results__search-result search-result columns-layout">
          <div class="columns-layout__left-column">
            {{#hierarchy.lvl1}}
              <a href="{{url}}" class="search-result__subcategory">
                {{{_highlightResult.hierarchy.lvl1.value}}}
              </a>
            {{/hierarchy.lvl1}}
          </div>

          <div class="columns-layout__right-column">
            {{#hierarchy.lvl2}}
              <a href="{{url}}" class="search-result__subsubcategory">
                {{{_highlightResult.hierarchy.lvl2.value}}}
              </a>
            {{/hierarchy.lvl2}}

            {{#hierarchy.lvl3}}
              <a href="{{url}}" class="search-result__subsubsubcategory">
                {{{_highlightResult.hierarchy.lvl3.value}}}
              </a>
            {{/hierarchy.lvl3}}

            {{#content}}
              <a href="{{url}}" class="search-result__content">
                {{{_snippetResult.content.value}}}
              </a>
            {{/content}}
          </div>
        </div>
        {{/hits}}
      </div>
      
    </script>

    <script>
      $(document).ready(function() {
        window.initializeSearch('master', '.search-input-container', '.search-container', '.search-container__results', '.search-container__pagination');
      });
    </script>
  </body>
</html>

**Comment by liuchang-icu** [comment]
this url   in  https://docs.projectcalico.org/v3.7/maintenance/kubernetes-upgrade less ，，it  should be  https://docs.projectcalico.org/v3.7/manifests/calico-etcd.yaml  ,less manifests

**Comment by caseydavenport** [comment]
This should fix it: https://github.com/projectcalico/calico/pull/2693
