### ISSUE TITLE
dial tcp 10.96.0.1:443 timeout

### ISSUE THREAD

**Issue by Nurlan199206** [projectcalico/calico#2695]
Sometimes when running `kubectl -f apply prometheus-deployment.yml` , receiving error

`Failed create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container "ebde4d5c55680e5db9de25b76ff4f28989be3de81a2a375d90ef62b04b6916b1" network for pod "prometheus-deployment-5766fbb466-vtptc": NetworkPlugin cni failed to set up pod "prometheus-deployment-5766fbb466-vtptc_default" network: error getting ClusterInformation: Get https://[10.96.0.1]:443/apis/crd.projectcalico.org/v1/clusterinformations/default: dial tcp 10.96.0.1:443: i/o timeout`

## Expected Behavior
`
Prometheus pod start`

## Current Behavior

Prometheus pod start

## Steps to Reproduce (for bugs)

1. `git clone https://github.com/Nurlan199206/kubernetes-prometheus`
```
2. kubectl create -f pv-prom.yaml
3. kubectl create -f pv-claim-prom.yaml
4. kubectl apply -f clusterrole.yml
5. kubectl apply -f prometheus-deployment-pv.yml
6. change IP in prometheus-config-map.yaml
7. create prometheus folder  to /mnt
8. copy prometheus.yml to /mnt/prometheus if you wanna use with PV
```

## Context

Prometheus pods must be start, but something it's starting without any problem.

## Your Environment

* Calico version
`3.7.3`
* Orchestrator version (e.g. kubernetes, mesos, rkt):
```
NAME          STATUS     ROLES    AGE     VERSION   INTERNAL-IP     EXTERNAL-IP   OS-IMAGE       KERNEL-VERSION    CONTAINER-RUNTIME
kubernetes1   Ready      master   11d     v1.14.3   10.132.0.2      <none>        Ubuntu 18.10   4.18.0-1015-gcp   docker://18.9.6
```
* Operating System and version:
```
NAME="Ubuntu"
VERSION="18.10 (Cosmic Cuttlefish)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.10"
VERSION_ID="18.10"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=cosmic
UBUNTU_CODENAME=cosmic
```
* Link to your project (optional):

**Comment by tmjd** [comment]
A guess from the error you provided is that kube-proxy isn't functioning correctly as I believe the 10.96.0.1 is the kubernetes api service address which it is responsible for configuring/setting up. You should check kube-proxy logs and see that it is healthy and create the iptables rules for the kubernetes services.

**Comment by satishrao84** [comment]
What caused this issue? I am facing the same thing.

**Comment by Vitorspk** [comment]
I know this ticket is closed but just to help people who find this post i solved the problem when i changed my pod-network-cidr to pod-network-cidr=10.244.0.0/16

**Comment by rahulsharma2020** [comment]
Thanks @Vitorspk. 
Just to add the clarification: the `pod-network-cidr=10.244.0.0/16` worked for **Calico** CNI. (I see some posts saying this is applicable to Flannel).

**Comment by rahulsharma2020** [comment]
In between, do we know how updating the `pod-network-cidr=10.244.0.0/16` fixes the issue?

**Comment by grahamoptibrium** [comment]
@Vitorspk sadly changing the pod network CIDR to `10.244.0.0/16` did not solve the issue for me.

**Comment by erhan-** [comment]
> @Vitorspk sadly changing the pod network CIDR to `10.244.0.0/16` did not solve the issue for me.

I had the same issue and changed the CIDR as well without luck. I found the solution for me.

When I tried to do `modprobe ip_conntrack && modinfo ip_conntrack` it failed on the node but was working on the master. I checked and saw that the files were in `/lib/modules/4.18.0-240.15.1.el8_3.x86_64/` (in that version) . I did something strange and don't even know why I tried it. On the master the modprobe command worked. I then copied the whole folder from /lib/modules/ to the same path on my node and then I was able to to modprobe. After a restart, my nodes worked again. 

This was a pita and I hope you guys are lucky this way, if it also happens to you. I guess it was a broken kernel update or something.

**Comment by mithlajkn** [comment]
After hours of googling, this is how I resolved it.
Its an issue with the default CIDR which is 10.244.0.0/16 during the flannel initialization.
I'm using canal for CNI networking.
I solved this issue by editing configmap canal-config from the dashboard or use this 
kubectl edit cm -n kube-system kube-flannel-cfg

 
   ```
 net-conf.json: |
        {
          "Network": "10.244.0.0/16",
          "Backend": {
            "Type": "vxlan"
          }
        }
```
Use ``kubectl get nodes -o jsonpath='{.items[*].spec.podCIDR}'` `to get pod CIDR.
#change from 10.244.0.0/16 to your own POD networks.
then delete the canal pod.
credits:Jun Chen

**Comment by andrewjensen-codelab** [comment]
I sat for 2 weeks with this problem and finally found the solution (repost):

microk8s stop
# or for workers: sudo snap stop microk8s

sudo vim.tiny /var/snap/microk8s/current/args/kubelet
# Add this to bottom: --node-ip=<this-specific-node-lan-ip>

sudo vim.tiny /var/snap/microk8s/current/args/kube-apiserver
# Add this to bottom: --advertise-address=<this-specific-node-lan-ip>

microk8s start
# or for workers: sudo snap start microk8s

**Comment by emilianobaum** [comment]
I think this solution is beacuse of that:

_

> If you are using pod CIDR 192.168.0.0/16, skip to the next step. If you are using a different pod CIDR with kubeadm, no changes are required - Calico will automatically detect the CIDR based on the running configuration. For other platforms, make sure you uncomment the CALICO_IPV4POOL_CIDR variable in the manifest and set it to the same value as your chosen pod CIDR.
[https://docs.tigera.io/calico/latest/getting-started/kubernetes/self-managed-onprem/onpremises#install-calico-with-etcd-datastore](url)
_

When I ran kubeadm init again with this range of network pods (10.244.0.0/16), Calico started fine. Later I added new nodes and also joined ok
