### ISSUE TITLE
Integration with Kubernetes Native Dual-Stack

### ISSUE THREAD

**Issue by Arvinderpal** [projectcalico/calico#2706]
Dual-stack support in kubernetes is underway ([KEP](https://github.com/kubernetes/enhancements/blob/master/keps/sig-network/20180612-ipv4-ipv6-dual-stack.md)). [Phase-1](https://github.com/kubernetes/kubernetes/pull/73977) alpha recently merged into master and phase-2 is under active development. 

Calico currently supports dual-stack independent of kubernetes; however, tighter integration with kubernetes dual-stack would be highly desirable. 

Also, current dual-stack development efforts rely on simpler CNI plugins -- kubenet/bridge/host-local. Having early dual-stack support within calico would aid in testing dual-stack on: (i) more realistic/diverse deployments and (ii) e2e testing tools like [KinD](https://github.com/kubernetes-sigs/kind) that use calico as their network plugin.

**Comment by lwr20** [comment]
Are you seeing specific problems with Calico in these environments?  Does it not "just work"?

**Comment by Arvinderpal** [comment]
> Are you seeing specific problems with Calico in these environments? Does it not "just work"?

The dual-stack work includes core API changes (e.g. PodSubnet in the Node object is now a slice), I assume these changes will require appropriate changes on the calico end. I'm not familiar with the calico code base, so I may just be wrong here. 

I did manage to bring up a dual-stack cluster using a calico specific approach as [documented here](https://www.projectcalico.org/enable-ipv6-on-kubernetes-with-project-calico/), but this is of course independent of the recent dual-stack changes in k8s. As more of the dual-stack PRs hit k8s master, I will attempt to integrate with calico. I'll add updates here.

**Comment by rafaelvanoni** [comment]
Thanks for reporting this. We're looking at dual stack and IPv6, if there's information you'd like to contribute or PRs you'd like to propose we'd be very thankful.

**Comment by caseydavenport** [comment]
> I did manage to bring up a dual-stack cluster using a calico specific approach as documented here, but this is of course independent of the recent dual-stack changes in k8s. As more of the dual-stack PRs hit k8s master, I will attempt to integrate with calico. I'll add updates here.

Awesome, appreciate this. Someone on the Calico side should also try to review the new dual-stack KEP and add comments here with any work we identify. I think/hope it should be minimal.

**Comment by neiljerram** [comment]
@Arvinderpal I'm happy to say that the Calico integration with dual stack was done for our v3.11 release, as mentioned at https://docs.projectcalico.org/v3.11/release-notes/.

I think that means we can close this issue; please do open new issues if you notice anything missing.
