### ISSUE TITLE
Is it possible to log iptables drops using calico with the kubernetes NetworkPolicy API?

### ISSUE THREAD

**Issue by rosskusler** [projectcalico/calico#2709]
## Expected Behavior
Have some way to log dropped packets that are dropped by NetworkPolicy using the standard Kubernetes NetworkPolicy API

## Current Behavior
Currently packets are dropped silently

## Possible Solution
I saw this https://github.com/projectcalico/calico/issues/1923 but am hoping to do it in a way that doesnt require using calicoctl or the Calico specific API

## Steps to Reproduce (for bugs)
1. Deploy any application to a new namespace
2. Add a networkpolicy to the namespace that denies all packets
3. Verify that nothing can connect to the deployed application
4. Look at logs on worker node to see what traffic was dropped

## Context
Having a way to log dropped packets would make troubleshooting network policy issues much easier.  We could send these logs to our analysis platform or even just review them by hand.

## Your Environment
kubernetes 1.14 using calico v3.7.3

**Comment by caseydavenport** [comment]
@rosskusler no, this isn't supported for Kubernetes NP right now.

Why not just use the Calico APIs?

**Comment by rosskusler** [comment]
Sorry for the late response.  My primary motivation would be portability.  We have some customers running Calico but others running other NPs.  I was hoping to find some generic way of capturing relevant logs without locking things down to a single NP.

**Comment by caseydavenport** [comment]
I think this might be what you're looking for: https://github.com/box/kube-iptables-tailer
