### ISSUE TITLE
Custom routing for a Node

### ISSUE THREAD

**Issue by lipg** [projectcalico/calico#2714]
## Expected Behavior
User `route add -net 100.0.0.0/16 gw 10.1.1.1` add route,Routing can persist。

## Current Behavior
Custom routing quickly disappears，How to persist？

## Steps to Reproduce (for bugs)
`route add -net 100.0.0.0/16 gw 10.1.1.1`
`route -n`

## Context
K8S+Calico

## Your Environment

* Calico version
* Orchestrator version (e.g. kubernetes, mesos, rkt):
* Operating System and version:
* Link to your project (optional):

**Comment by rafaelvanoni** [comment]
Can you clarify which version of Calico are you running and why do you think Calico is over writing the route? If you don't use Calico and add this custom route, does it persist?

**Comment by lipg** [comment]
Calico 3.8.
I want to link three networks , My network looks like this 
![NetWork](https://user-images.githubusercontent.com/7782635/61955877-87fb9580-afee-11e9-8607-b86206212ec0.png)
1. `VPC 172.17.0.0/16`  `Router1 10.100.0.0/16`  `Router2 10.101.0.0/16 `
2. Facade Server has OpenVPN Server，The Router1 and Router2 use OpenVPN  client into the VPC network.
3. Now,all servers are already connected，but the calico network not ready, can't be accessed across regions.

vpc server route 
```
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
0.0.0.0         172.17.223.253  0.0.0.0         UG    0      0        0 eth0
10.1.34.192     172.17.213.60   255.255.255.192 UG    0      0        0 tunl0
10.1.75.64      172.17.4.53     255.255.255.192 UG    0      0        0 tunl0
10.1.79.64      10.100.1.50     255.255.255.192 UG    0      0        0 tunl0
10.1.222.192    0.0.0.0         255.255.255.192 U     0      0        0 *
10.1.222.193    0.0.0.0         255.255.255.255 UH    0      0        0 cali2e4b1a41847
10.1.222.194    0.0.0.0         255.255.255.255 UH    0      0        0 cali4461bd37c1f
10.1.222.195    0.0.0.0         255.255.255.255 UH    0      0        0 calibd9a85a26d6
10.1.222.198    0.0.0.0         255.255.255.255 UH    0      0        0 cali276ee98a6ba
10.1.222.211    0.0.0.0         255.255.255.255 UH    0      0        0 calib8cdf0dccd2
10.1.222.214    0.0.0.0         255.255.255.255 UH    0      0        0 calid93703c4ce3
10.1.222.215    0.0.0.0         255.255.255.255 UH    0      0        0 cali3588bb10707
10.1.222.216    0.0.0.0         255.255.255.255 UH    0      0        0 cali7b20a6caf57
169.254.0.0     0.0.0.0         255.255.0.0     U     1002   0        0 eth0
172.17.208.0    0.0.0.0         255.255.240.0   U     0      0        0 eth0
172.18.0.0      0.0.0.0         255.255.0.0     U     0      0        0 docker0
```

**Comment by tmjd** [comment]
Have you setup networking where all your hosts can reach each other directly?
Is your IP Pool configured with IPIP or some other encapsulation?
Can all your nodes/hosts reach each other's BGP (port 179)? (You can check this by doing `nc -v <othernode> 179`)

**Comment by lipg** [comment]
1. Yes.all hosts can reach each other directly.
2. Use IPIP
3. Yes. nodes/hosts reach each other's BGP (port 179).
<img width="939" alt="image" src="https://user-images.githubusercontent.com/7782635/61962670-9c468f00-affc-11e9-8638-5547d70e009b.png">
<img width="526" alt="image" src="https://user-images.githubusercontent.com/7782635/61962898-30b0f180-affd-11e9-90fe-0ab22b98216c.png">
I think maybe use `10.1.79.64`, not use `10.100.1.50`.But routing table is `10.100.1.50`
<img width="669" alt="image" src="https://user-images.githubusercontent.com/7782635/61963202-aa48df80-affd-11e9-974d-44e0e367f25c.png">

**Comment by lipg** [comment]
I found this
<img width="1277" alt="image" src="https://user-images.githubusercontent.com/7782635/61966867-6908fd80-b006-11e9-8ddd-6809ab4333e2.png">

**Comment by caseydavenport** [comment]
> Calico 3.8. Route persistence has been resolved.Please help solve other problems. 

Please open up new issues for any other problems once one has been solved. It helps others who may come looking for an answer in the future.
