### ISSUE TITLE
'Assigning IP addresses based on topology'

### ISSUE THREAD

**Issue by azalio** [projectcalico/calico#2719]
It is a documentation issue.
I have read doc in the page https://docs.projectcalico.org/v3.8/networking/assigning-ip-addresses-topology and in:
## Prerequisites
I see:
`This feature requires Calico for networking in etcd mode.`
But according to Lance Robson in the slack channel, it is not true since calico 3.6.
Can you please fix documentation?

**Comment by rafaelvanoni** [comment]
Thanks for reporting this, would you like to submit a PR and help us get this fixed?

**Comment by caseydavenport** [comment]
Fixed in newer versions of the doc.
