### ISSUE TITLE
Feature request: Allow IPAM CIDR rescan

### ISSUE THREAD

**Issue by rgarcia89** [projectcalico/calico#2730]
I would like to make a feature request which is in concern of IPAM and using Calico as Kubernetes CNI. 

## Context
In one of our Clusters we have moved from weave-net to Calico using the same CIDR. After that we were facing the following issue sporadically when deploying new pods:

```
Failed create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container "dcf3c3984f35a2841f8bd189bb4223a3901e6902e2cd99f07fa6dbbee8aeb13c" network for pod "runner-6i3trih-project-6468633-concurrent-0v9jzw": NetworkPlugin cni failed to set up pod "runner-6i3trih-project-6468633-concurrent-0v9jzw_escrow" network: error adding host side routes for interface: calib641cf4cd71, error: route (Ifindex: 61, Dst: 10.203.1.82/32, Scope: 253) already exists for an interface other than 'calib641cf4cd71'
```
When listing the pods I can see that this address is assigned to one of them. However, according to IPAM this doesn't seems to be the case:

```
$ calicoctl ipam show --ip=10.203.1.82
IP 10.203.1.82 is not currently assigned in block
```
Redeploying all pods from before the CNI migration to Calico fills the IPAM key value store.

However as redeploying all pods can become a pain in the ass in bigger clusters, I would like to open the following feature request.

## Request
Have Calico scan the defined CIDR during its deployment and add the found IPs to its key value store.
I of course would be also happy with a documentation showing how to fill the key value store manually.

## Your Environment

* Calico version 3.8.0
* Orchestrator version (e.g. kubernetes, mesos, rkt): kubernetes
* Operating System and version: CentOS 7
* Link to your project (optional):

**Comment by tmjd** [comment]
Currently Calico does not support switching from another CNI plugin, without redeploying all pods. weave-net and Calico networking is not compatible so when switching between them you currently have to redeploy all pods. Without doing this the expectation would be that pods that were networked with weave-net would not be able to communicate with pods networked with Calico and vise-versa.

I don't think the solution would be just to scan the defined CIDR as you say and add it to the datastore. The implemented policy, routing, and interfaces are not known to be compatible so it would not be as simple as you have stated.

If I'm misunderstanding your request please elaborate and help me understand this request.
Thank you

**Comment by rgarcia89** [comment]
You are right. I did not think about the policy, routing and interfaces that are created for every pod.
