### ISSUE TITLE
How to shutdown calico route reflector correctly?

### ISSUE THREAD

**Issue by calixwu** [projectcalico/calico#2733]
## Environment
Calico version: 2.6.7 (Docker container)

## Description
We want to know how to shutdown calico route reflector correctly. When we shutdown the calico-rr by stopping the container directly, the key ``/calico/bgp/v1/rr_v4/<calico-rr ip>`` at etcd was still there. Do we have to remove the key from etcd manually? Will this execution causes unexpected problems?

**Comment by tmjd** [comment]
You will need to remove the key manually. You can see here https://docs.projectcalico.org/v2.6/usage/routereflector/calico-routereflector#configuring-a-cluster-of-route-reflectors that it was added manually.
If you are removing the route reflector (and it is the last one) and have not enabled node-to-node mesh this will definitely cause problems. If there are other route reflectors or you do have node-to-node mesh I don't believe there will be any problems.

**Comment by calixwu** [comment]
@tmjd Thanks~
