### ISSUE TITLE
Routes can not be exchanged between calico router reflectors connected in a full mesh

### ISSUE THREAD

**Issue by calixwu** [projectcalico/calico#2735]
The network topology is like this：

![calico-rr-同步问题](https://user-images.githubusercontent.com/3852339/61506771-d7056180-aa15-11e9-8d03-26d1167095bc.png)

All calico nodes and route reflectors are using the same cluster id.

We found that node1 and node2 can learn each others routes, the same between node3 and node4. But node1 and node3 (or node4), which are connected to different route reflectors, can not learn each others routes. 

Is there something wrong here? Because as this [doc](https://docs.projectcalico.org/v2.6/usage/routereflector/calico-routereflector) describes:

> Setting up node-specific peering
> If you are deploying a cluster of Route Reflectors, with each Calico node peering to a subset of Route Reflectors it will be necessary to set up the peerings on a node-by-node basis.
> 
> This would be the typical situation when scaling out to a very large size. For example, you may have:
> 
> a cluster of 100 route reflectors connected in a full mesh
> a network of 100,000 Calico Docker nodes
> each Calico Docker node is connected to two or three different Route Reflectors.
> 

Nodes should learn all the routes from all other nodes even though they connected to different  route reflectors in a full mesh.

And we found the similar topology in that doc too:

![image](https://user-images.githubusercontent.com/3852339/61507090-f9e44580-aa16-11e9-8d61-a05a147efe70.png)
 
But the different part is that they have different cluster ids. 

## Expected Behavior
Routes can be exchanged.

## Current Behavior

Routes were not exchanged.

## Context

All calico nodes and route reflectors are using the same cluster id.

## Your Environment

* Calico version：v2.6.7
* Orchestrator version (e.g. kubernetes, mesos, rkt): kubernetes

**Comment by rafaelvanoni** [comment]
@calixwu Any particular reason why you can't deploy a more recent version of Calico? v2.6.7 is pretty old at this point. There's newer functionality that allow the nodes themselves to be route reflectors.

**Comment by calixwu** [comment]
@rafaelvanoni Yep... I know the recent version allow the nodes themselves to be route reflectors...

So why router reflectors can not exchanged routes in Calico v2.6.7, it's that as expected?

The reason why we don't upgrade to v3.x.x from v2.6.7 is because we are still finding a graceful way to do the online migration, as calico v3.x.x begins to use etcd v3 from v2. We actually posted some issues for that: [How to do the online migration?]https://github.com/projectcalico/calico/issues/2434 and [Rolling back after upgrading 2.6.x to 3.x.x.](https://github.com/projectcalico/calico/issues/2468)

**Comment by tmjd** [comment]
I think the problem is the difference you've identified, in your cluster you are using the same cluster id for all where you should be using a different cluster ID for each RR group. From https://orhanergun.net/2015/02/bgp-route-reflector-clusters/ it looks like it is expected behavior as since your route reflectors (RR) have the same ID they drop the routes learned from other RRs.

**Comment by calixwu** [comment]
@tmjd Thanks~
