### ISSUE TITLE
calico-node config not work

### ISSUE THREAD

**Issue by phantooom** [projectcalico/calico#2740]
## Expected Behavior
the netowrk mode change to bgp, and ipip mode was disabled

## Current Behavior

network traffic via tun0 to other node and logs show  "IpInIpEnabled:true"

## Steps to Reproduce (for bugs)
kubectl apply -f https://docs.projectcalico.org/v3.8/manifests/calico.yaml
change the damonset  
        - name: CALICO_IPV4POOL_IPIP
          value: Always
to
        - name: CALICO_IPV4POOL_IPIP
          value: Never

## Context
no a new k8s cluster

## Your Environment
* Calico version 3.8 
* Operating System and version: Linux 4.15.0-52-generic #56-Ubuntu SMP Tue Jun 4 22:49:08 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

```
kubectl version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.1", GitCommit:"4485c6f18cee9a5d3c3b4e523bd27972b1b53892", GitTreeState:"clean", BuildDate:"2019-07-18T09:18:22Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.1", GitCommit:"4485c6f18cee9a5d3c3b4e523bd27972b1b53892", GitTreeState:"clean", BuildDate:"2019-07-18T09:09:21Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by rafaelvanoni** [comment]
Can you clarify what you mean by "bgp mode". Calico uses bgp with IPIP enabled or not, if that's what you're trying to do.

**Comment by tmjd** [comment]
With the steps you've suggested I would not expect a change in the IPIP mode. That environment value is only used for initial pool creation so updating the daemonset after it is created will not update the IP Pool.
You can update the current IP Pool and disable IPIP.  See https://docs.projectcalico.org/v3.8/networking/vxlan-ipip and https://docs.projectcalico.org/v3.8/getting-started/calicoctl/install to get started doing that.
If you need further help please let us know.
