### ISSUE TITLE
Missing CRDs result in Typha continuously creating watches

### ISSUE THREAD

**Issue by lmm** [projectcalico/calico#2744]
As reported by @erwbgy [here](https://github.com/projectcalico/typha/issues/271#issuecomment-513790388):

> We found that not adding at the additional CRDs resulted in typha continuously creating a large number of watches with a significant impact on apiserver performance in a cluster with lots of nodes.
> 
> Can the canal.yaml manifest be updated with all of the CRDs? The cluster role also needs updating to allow blockaffinities to be listed.

Related [PR](https://github.com/projectcalico/calico/pull/2741) which closed the original issue.
## Expected Behavior

Typha is not continuously creating watches and impacting performance.

## Current Behavior

Watches are continuously created.

## Possible Solution

- Add in missing CRDs and update RBAC to allow those CRDs

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Calico version
* Orchestrator version (e.g. kubernetes, mesos, rkt):
* Operating System and version:
* Link to your project (optional):

**Comment by caseydavenport** [comment]
@rene-dekker is this fixed by your recent PR? I think so.

**Comment by rene-dekker** [comment]
Yes, this has just been merged into master. https://github.com/projectcalico/calico/pull/2741
