### ISSUE TITLE
No documentation for kubernetes upgrades

### ISSUE THREAD

**Issue by staticdev** [projectcalico/calico#2753]
## Expected Behavior

Step 4 of Kubernetes upgrade says CNI plugins should have documentation for upgrades (https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade-1-15/)

## Current Behavior

I saw there is documentation for calico upgrade (https://docs.projectcalico.org/v3.8/maintenance/kubernetes-upgrade) but didn't find anything specific to kubernetes upgrades, just instalation.

## Possible Solution

Put some note or page in the documentation regarding that.

## Steps to Reproduce (for bugs)

No need.

## Your Environment

* Calico version 3.8
* Orchestrator version (e.g. kubernetes, mesos, rkt): kubernetes 1.15.0
* Operating System and version: Ubuntu 18.04
* Link to your project (optional):

**Comment by caseydavenport** [comment]
> Your Container Network Interface (CNI) provider may have its own upgrade instructions to follow. Check the addons page to find your CNI provider and see whether additional upgrade steps are required

There isn't anything that needs to be done on the Calico side for Kubernetes upgrades, so long as the version of Calico you're running supports the version of Kubernetes that you're upgrading to (which, it should. You can see more about that here: https://docs.projectcalico.org/v3.8/getting-started/kubernetes/requirements#kubernetes-requirements)

> Manually upgrade your CNI provider plugin.

The documentation you linked to is the correct documentation for upgrading Calico, if it is needed. Is there something missing from that page?
