### ISSUE TITLE
how to config for limiting the network speed

### ISSUE THREAD

**Issue by timyinshi** [projectcalico/calico#2757]
## Expected Behavior
i use calico in my k8s,i want to know how to config for limiting the network speed,so example ,i want to config how many bytes per seconds.

## Current Behavior
i want to know how to config for limiting the network speed.

## Your Environment
* Calico version:3.4.0
* Orchestrator version (e.g. kubernetes, mesos, rkt):kubernetes
* Operating System and version:ubuntu18.04

**Comment by tmjd** [comment]
I believe there is a tc CNI plugin, have you looking into that?  Calico does not provide any traffic shaping capabilities, we do support plugin chaining which should allow you to use the tc plugin.

**Comment by timyinshi** [comment]
@rmjd thanks,do you know what is the tc cni plugin's github url?

**Comment by tmjd** [comment]
Looks like it is called bandwidth https://github.com/containernetworking/plugins/tree/master/plugins/meta/bandwidth

**Comment by caseydavenport** [comment]
This comment might be useful: https://github.com/projectcalico/calico/issues/797#issuecomment-493210584
