### ISSUE TITLE
Liveness probe support for calico-kube-controller

### ISSUE THREAD

**Issue by gbharanikumar** [projectcalico/calico#2769]
As of now, liveness probe is not added to calico-kube-controller pod's. Is there a reason why it is not having liveness probe on calico-kube-controller?

## Expected Behavior
Can we add liveness probe to call the check-status script (used in readiness probe) to trigger a restart of the pod when check-status fails as part of liveness probe trigger.
## Current Behavior
There is no liveness probe on calico-kube-controller pod.

## Possible Solution
Add liveness probe which triggers the same check-status script that is called in Readiness probe of calico-kube-controller.

## Steps to Reproduce (for bugs)
Below are couple of scenario's which might lead to the liveness probe fail and which needs pod restart to overcome check-status failure:
1. status.json file reading fail's. which might get fixed after pod restart
2. One of the component/controller (wep,policy,namespace,etc) health check fails might lead to check-status failure and a restart might help to overcome this.
3.
4.

## Context
Incase check-status fails as part of readiness probe failure, calico-kube-controller will be stuck in non-operation state. So we need some mechanism (liveness probe) to restart the pod to come out of this situation.

## Your Environment

* Calico version : v3.4.0
* Orchestrator version (e.g. kubernetes, mesos, rkt): Kubernetes v1.11.6
* Operating System and version: Ubuntu kernel 4.15.0-47-generic
* Link to your project (optional):

**Comment by tmjd** [comment]
Are you seeing problems with the kube-controllers where a liveness probe would help?

As best I could tell currently the readiness check is only checking access to the datastore and the kube-apiserver, so monitoring it with the check-status is not going to catch many problems but would probably be safe to do.

I do believe it would be nice if we added in liveness checks into each of the controllers incase one of them has a problem. As for a reason why it does not have liveness checks is probably because no one has added them and there have not been reports of problems with it, so it hasn't been high on the list of priorities.
If you want to add liveness checks we would be happy to discuss and review.

**Comment by gbharanikumar** [comment]
Hi Erik,

Thanks for your response.
As per my understanding, calico-kube-controller's primary job is to sync the kubernetes objects related to namespace, policy, node, service account, and wep with the calico datastore.
I hope if we add the liveness probe with the same trigger (check-status -r) might help to overcome the readiness probes failures (which needs a restart of the pod).
As mentioned readiness failure can occur while checking access for datastore ("Error Verifying datastore" and the access to kube-apiserver Healthcheck ("Error reaching apiserver").
From my netpol, namespace, policy, node and serviceaccount controller code walk through it seems the controller sync's with K8s API before starting resource cache (deals with kube-apiserver) or syncToDataStore to sync the given update to the Calico datastore.
Because "check-status -r" already addresses the healthcheck with k8s-apiserver and calico datastore, we can add "check-status -r" for liveness probe also.

I hope adding the liveness probe with the below params will be ideal way:
Trigger: /usr/bin/check-status -r
If the readiness probe has: 
- initialDelaySeconds: 5 
- periodSeconds: 10 
- failureThreshold: 2
We can configure the liveness probe as below: 
- initialDelaySeconds: 25 
- periodSeconds: 1 
- failureThreshold: 1

With the above Readiness and liveness probe configuration on calico-kube-controller, readiness check fails 2 times ( time lapsed is 25 sec) and immediately liveness probe (check-status -r) is triggered and restart the calico-kube-controller pod.

Please let me know 
Regards,
Bharani..
