### ISSUE TITLE
kube-controller-manager logs Flexvolume error messages

### ISSUE THREAD

**Issue by filip-havlicek** [projectcalico/calico#2771]
Log of kube-controller-manager is full of these messages
```
E0802 08:58:53.534082       1 driver-call.go:267] Failed to unmarshal output for command: init, output: "2019/08/02 08:58:53 Unix syslog delivery error\n", error: invalid character '/' after top-level value
W0802 08:58:53.534100       1 driver-call.go:150] FlexVolume: driver call failed: executable: /usr/libexec/kubernetes/kubelet-plugins/volume/exec/nodeagent~uds/uds, args: [init], error: exit status 1, output: "2019/08/02 08:58:53 Unix syslog delivery error\n"
E0802 08:58:53.534130       1 plugins.go:746] Error dynamically probing plugins: Error creating Flexvolume plugin from directory nodeagent~uds, skipping. Error: invalid character '/' after top-level value
```
It looks harmless, but I don't understand these messages exactly.

## Steps to Reproduce
1. fresh bootstrap cluster with kubeadm
2. kubectl apply -f release-v3.8.1/k8s-manifests/calico.yaml (downloaded from https://github.com/projectcalico/calico/releases/download/v3.8.1/release-v3.8.1.tgz)
3. kubectl -n kube-system logs -f kube-controller-manager-masternode

## Environment

* Calico version - v3.8.1
* Orchestrator version: kubernetes 1.15.1
* Operating System and version: Debian Stretch, kernel 4.4.174

**Comment by filip-havlicek** [comment]
I am sorry, I will close this. I have to investigate it more. Probably this is not a problem of calico.

**Comment by tmjd** [comment]
@filip-havlicek you may want to keep an eye on https://github.com/projectcalico/pod2daemon/issues/20, there isn't a solution yet but sounds like the same problem.

**Comment by simonfuhrer** [comment]
same problem here in our company. 

our kube-controller-manager runs as non root user (nobody). The flexvol.sh entrypoint script chmod to 0550 and runs as root. the nobody user has no permission to execute the plugin. 

i currently see two possible solutions: 
1. Add some uid, gid args to the entrypoint script
2. chmod to 0555

Maybe someone from calico can check it.

**Comment by rafaelvanoni** [comment]
@simonfuhrer That seems like a different issue, could you please open a new ticket for that?
