### ISSUE TITLE
Calico 3.6 releases after 3.6.1 do not include Kubernetes manifests

### ISSUE THREAD

**Issue by tuminoid** [projectcalico/calico#2777]
## Expected Behavior

Kubernetes manifests are included in release package.

Example, 3.6.1 release:
```
~/tmp/calico/release-v3.6.1$ find -name '*.yaml'
./k8s-manifests/hosted/calicoctl.yaml
./k8s-manifests/hosted/calico.yaml
./k8s-manifests/hosted/etcd.yaml
./k8s-manifests/hosted/canal/canal.yaml
./k8s-manifests/hosted/canal/canal-etcd.yaml
./k8s-manifests/hosted/kubernetes-datastore/calicoctl.yaml
./k8s-manifests/hosted/kubernetes-datastore/calico-networking/1.7/calico.yaml
./k8s-manifests/hosted/kubernetes-datastore/calico-networking/typha/calico.yaml
./k8s-manifests/hosted/kubernetes-datastore/policy-only/1.7/calico.yaml
./k8s-manifests/calico-kube-controllers.yaml
```
## Current Behavior

YAMLs besides few RBAC only yamls are missing.
```
~/tmp/calico/release-v3.6.4$ find -name '*.yaml'
./k8s-manifests/rbac-kdd-flannel.yaml
./k8s-manifests/rbac-kdd-calico.yaml
./k8s-manifests/rbac-etcd-flannel.yaml
./k8s-manifests/rbac-etcd-calico.yaml
```

## Possible Solution

Fix the release build to include YAMLs...

## Steps to Reproduce (for bugs)

1.Download release from https://docs.projectcalico.org/v3.6/release-notes/
2.Extract tarball
3.Look for YAML files

Issue first appeared in 3.6.2 release, 3.6.1 is fine. Release notes for 3.6.2 or later builds do not indicate any changes to packaging.

## Context

Trying to upgrade from Calico 3.6.1 to 3.6.4 due https://www.projectcalico.org/security-bulletins/#TTA-2019-002 and need the compatible YAML files as Calico YAMLs are not really stable even in bug releases, and part of the fix might be a configuration change.

## Your Environment

* Calico version: 3.6.1
* Orchestrator version (e.g. kubernetes, mesos, rkt):Kubernetes
* Operating System and version: irrelevant
* Link to your project (optional):

**Comment by caseydavenport** [comment]
> Trying to upgrade from Calico 3.6.1 to 3.6.4 due https://www.projectcalico.org/security-bulletins/#TTA-2019-002 and need the compatible YAML files as Calico YAMLs are not really stable even in bug releases, and part of the fix might be a configuration change.

yes, we should definitely fix the release build process. And, I can confirm that there is not a yaml change in the fix for that CVE.

**Comment by caseydavenport** [comment]
I believe the problem with the build is that we've changed where the manifests are in newer versions of Calico, but haven't updated the scrips to handle that gracefully (i.e, while also handling earlier versions).

I think this is the line: https://github.com/projectcalico/calico/blob/master/Makefile#L348

This should fix future releases: https://github.com/projectcalico/calico/pull/2778

**Comment by tuminoid** [comment]
> yes, we should definitely fix the release build process. And, I can confirm that there is not a yaml change in the fix for that CVE.

Thanks Casey. Furthermore, is there any changes in YAML in 3.6.2 or 3.6.3 releases, since the YAMLs are missing for those releases too, and 3.6.2 has quite a few fixes in it?

**Comment by caseydavenport** [comment]
Looks like this was the only fix that required changes to the manifests: https://github.com/projectcalico/calico/pull/2562

And, that was limited in scope to the Kubernetes API datastore with the Istio integration enabled.

**Comment by tuminoid** [comment]
Gotcha. Thanks again. We've now upgraded to 3.6.4, using the old manifests and new images.
