### ISSUE TITLE
Build error on 'make dev-image'

### ISSUE THREAD

**Issue by dgunjetti** [projectcalico/calico#2804]
Build error on 'make dev-image'

I am trying to build as stated in https://github.com/projectcalico/calico/blob/master/DEVELOPER_GUIDE.md#building-the-code

## Expected Behavior
Build to succeed

## Current Behavior
'make dev-image' aborts with error
*** No rule to make target `vendor'.

**Comment by caseydavenport** [comment]
This is likely a result of the switch to go modules that we just completed. @rafaelvanoni has been working on that.

We probably need to update that Makefile.

**Comment by caseydavenport** [comment]
We can probably just remove the `dev-vendor` target altogether now, right @rafaelvanoni? Or do any repositories still use a `vendor` directory?

**Comment by dgunjetti** [comment]
one more query, i need to build calico-node with changes in felix.. i tried 
'cd node; make calico/node LOCAL_BUILD=true'
../felix does not get copied on to docker container for build as result i am getting below errors,
go: parsing ../libcalico-go/go.mod: open /go/src/github.com/projectcalico/libcalico-go/go.mod: no such file or directory
go: parsing ../felix/go.mod: open /go/src/github.com/projectcalico/felix/go.mod: no such file or directory
How can i solve this?

**Comment by dgunjetti** [comment]
After removing 'dev-vendor' in makefile, build is getting aborted with error
go: error loading module requirements
make[1]: *** [bin/calico-typha-amd64] Error 1
make: *** [typha-dev-image] Error 2

**Comment by jayunit100** [comment]
i have a vagrantfile im working on which works with dev-vendor removed, and it uses the LOCAL option.  i cannot build w/ dev-vendor either, the reason for me is that some subprojects like `calicoctl` dont seem to have it ? ill issue a PR for this.

**Comment by caseydavenport** [comment]
I think this was fixed in this PR: https://github.com/projectcalico/calico/pull/2931

Thanks @jayunit100 :)

**Comment by jayunit100** [comment]
im seeing this problem when building from 3.9.  i susepct its related to go modules but not sure what the fix is.  master is OK...
