### ISSUE TITLE
Switch from extensions API group to apps for deployments, daemonsets

### ISSUE THREAD

**Issue by alexeldeib** [projectcalico/calico#2814]
Switch from extensions API group to apps for deployments, daemonsets. Similar to #2548 

## Expected Behavior

1.16 will disable the extensions API group by default. Calico uses it, so installations will fail once 1.16 is out (i'm testing the beta).

## Current Behavior

Failure to install due to extensions API group usage.

## Possible Solution

apps/v1 has been available for quite a while, but calico does not use it. Pod priority class will also replace the critical scheduling annotation. I'm happy to make the PRs, but I stared at the templated docs for a while and couldn't figure out where the content came from, e.g. https://github.com/projectcalico/calico/blob/master/v3.8/getting-started/kubernetes/installation/hosted/kubernetes-datastore/calico-networking/1.7/calico.yaml

## Steps to Reproduce (for bugs)

1. Build 1.16 cluster
2. Install any calico release

## Context

I'm testing Kubernetes 1.16.0-beta.1. 

## Your Environment

* Calico version: any
* Orchestrator version (e.g. kubernetes, mesos, rkt): Kubernetes 1.16.0-beta.1
* Operating System and version: Ubuntu 16.04
* Link to your project (optional):

**Comment by alexeldeib** [comment]
For completeness: apps/v1 is available from Kubernetes 1.9 and apps/v1beta2 is available from Kubernetes 1.8.

**Comment by caseydavenport** [comment]
@alexeldeib are there particular resources you think should be updated? 

I believe we have updated all Calico resources in v3.8 to use the latest stable APIs as of this PR: https://github.com/projectcalico/calico/pull/2629

Did we miss something?

**Comment by alexeldeib** [comment]
You’re correct, my apologies! I was looking at daemonsets and deployments. I thought I was pulling latest, but was actually one version off. All is well :)
