### ISSUE TITLE
Cluster Calico BGP Update Error-

### ISSUE THREAD

**Issue by qq284418233** [projectcalico/calico#2827]
Calio is running
ClusertIP: 172.18.1.0/16
PodIP: 172.30.0.0/16
1. Cisco switches and Calico have established BGP protocols.
2. The Cisco switch can learn the POD routing address through BGP, and the server outside the K8S cluster can directly access the POD IP.
3.[! ! 】 Here is the problem, I created two SVCs.
SVC1 is all right. You can learn the cluster route of /32 on the Cisco switch. The packet is sent to the node to send BGP UPDATE packets.

SVC2 is successfully created and can be accessed in the K8S cluster. However, the node does not send BGP UPDATE packets through packet capture. As a result, the Cisco switch does not learn BGP routes. The server outside the K8S cannot access the SVC.

## SVC IP and  Cisco router

[root@master101-1/opt/k8s/yaml/tools]# kubectl get svc --all-namespaces  -o wide |grep yfbhost2
tools           yfbhost2               NodePort       172.18.67.0      <none>        80:40668/TCP                                                                                                            58m     tools=yfbhost2
[root@master101-1/opt/k8s/yaml/tools]# kubectl get svc --all-namespaces  -o wide |grep ues-test
tools           ues-bgp-service        NodePort       172.18.174.0     <none>        28080:36226/TCP                                                                                                         58m     app=ues-test

core-3750x#sh ip route bgp | in 172.18
     172.18.0.0/16 is variably subnetted, 3 subnets, 2 masks
B       172.18.0.0/16 [200/0] via 192.168.101.10, 1w2d
B       172.18.67.0/32 [200/0] via 192.168.101.5, 00:59:07
## SVC 1 YMAL

apiVersion: apps/v1
kind: Deployment
metadata:
  name: yfbhost2
  namespace: tools
spec:
  replicas: 1
  selector:
    matchLabels:
      tools: yfbhost2 
  template:
    metadata:
      labels:
        tools: yfbhost2
    spec:
      containers:
      - name: yfbhost2
        image: nginx
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 80
        volumeMounts:
        - name: yfbhost2-html
          mountPath: /usr/share/nginx/html
        - name: nginx-cfg
          mountPath: /etc/nginx
      volumes:
      - name: yfbhost2-html
        hostPath:
          path: /opt/tools/html
      - name: nginx-cfg
        hostPath:
          path: /opt/tools/nginx-cfg
      nodeSelector:
        tools: yfbhost

apiVersion: v1
kind: Service
metadata:
  name: yfbhost2
  namespace: tools
spec:
  type: "NodePort"
  externalTrafficPolicy: "Local"
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    #nodePort: 30080
  selector:
    tools: yfbhost2

## SVC2 YMAL
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ues-test
  namespace: tools
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 20%
      maxUnavailable: 10%
  selector:
    matchLabels:
      app: use-ws
      type: tomcat
  template:
    metadata:
      labels:
        app: use-ws
        type: tomcat
    spec:
      containers:
      - name: ues-test
        image: harbor.kjtpay.local/app/ues-test:20190826-1
        #imagePullPolicy: IfNotPresent
        imagePullPolicy: Always
        resources:
          limits:
            cpu: "1"             #限制pod申请最大的cpu数量为1个cpu
            memory: 2Gi        #申请内存最大值
        ports:
        - protocol: TCP
          containerPort: 8080
        command:
        - "/opt/scm_tools/tcruntime-ctl.sh"
        - "ues-test"
        - "start"
        volumeMounts:
        - name: jdk
          mountPath: /opt/jdk1.8.0_131
          readOnly: yes
        - name: app-logs
          mountPath: /opt/logs
        - name: saturn
          mountPath: /opt/saturn
          readOnly: yes
        - name: cert
          mountPath: /opt/ues
          readOnly: yes
        - name: apollo
          mountPath: /opt/settings/server.properties
          readOnly: yes
          subPath: server.properties
        - name: druid
          mountPath: /opt/settings/druid-pool.properties
          readOnly: yes
          subPath: druid-pool.properties 
      volumes:
      - name: jdk
        persistentVolumeClaim:
          claimName: tools-jdk-pvc
      - name: cert
        persistentVolumeClaim:
          claimName: ues-cert-pvc
      - name: app-logs
        persistentVolumeClaim:
          claimName: log-pvc
      - name: saturn
        persistentVolumeClaim:
          claimName: saturn-pvc
      - name: apollo
        configMap:
          name: apollo-config
      - name: druid
        configMap:
          name: druid-config
          defaultMode: 0400
      nodeSelector:
        tools: yfbhost

apiVersion: v1
kind: Service
metadata:
  name: ues-bgp-service
  namespace: tools
spec:
  type: "NodePort"
  externalTrafficPolicy: "Local"
  ports:
  - port: 28080
    targetPort: 28080
    protocol: TCP
    #nodePort: 30080
  selector:
    app: ues-test

**Comment by lwr20** [comment]
https://docs.projectcalico.org/v3.8/networking/service-advertisement#about-advertising-kubernetes-services-over-bgp might be relevant

**Comment by qq284418233** [comment]
> https://docs.projectcalico.org/v3.8/networking/service-advertisement#about-advertising-kubernetes-services-over-bgp might be relevant

**Comment by qq284418233** [comment]
> Calio is running
> ClusertIP: 172.18.1.0/16
> PodIP: 172.30.0.0/16
> 
> 1. Cisco switches and Calico have established BGP protocols.
> 2. The Cisco switch can learn the POD routing address through BGP, and the server outside the K8S cluster can directly access the POD IP.
>    3.[! ! 】 Here is the problem, I created two SVCs.
>    SVC1 is all right. You can learn the cluster route of /32 on the Cisco switch. The packet is sent to the node to send BGP UPDATE packets.
> 
> SVC2 is successfully created and can be accessed in the K8S cluster. However, the node does not send BGP UPDATE packets through packet capture. As a result, the Cisco switch does not learn BGP routes. The server outside the K8S cannot access the SVC.
> 
> ## SVC IP and Cisco router
> [root@master101-1/opt/k8s/yaml/tools]# kubectl get svc --all-namespaces -o wide |grep yfbhost2
> tools yfbhost2 NodePort 172.18.67.0 80:40668/TCP 58m tools=yfbhost2
> [root@master101-1/opt/k8s/yaml/tools]# kubectl get svc --all-namespaces -o wide |grep ues-test
> tools ues-bgp-service NodePort 172.18.174.0 28080:36226/TCP 58m app=ues-test
> 
> core-3750x#sh ip route bgp | in 172.18
> 172.18.0.0/16 is variably subnetted, 3 subnets, 2 masks
> B 172.18.0.0/16 [200/0] via 192.168.101.10, 1w2d
> B 172.18.67.0/32 [200/0] via 192.168.101.5, 00:59:07
> 
> ## SVC 1 YMAL
> apiVersion: apps/v1
> kind: Deployment
> metadata:
> name: yfbhost2
> namespace: tools
> spec:
> replicas: 1
> selector:
> matchLabels:
> tools: yfbhost2
> template:
> metadata:
> labels:
> tools: yfbhost2
> spec:
> containers:
> - name: yfbhost2
> image: nginx
> imagePullPolicy: IfNotPresent
> ports:
> - name: http
> containerPort: 80
> volumeMounts:
> - name: yfbhost2-html
> mountPath: /usr/share/nginx/html
> - name: nginx-cfg
> mountPath: /etc/nginx
> volumes:
> - name: yfbhost2-html
> hostPath:
> path: /opt/tools/html
> - name: nginx-cfg
> hostPath:
> path: /opt/tools/nginx-cfg
> nodeSelector:
> tools: yfbhost
> 
> apiVersion: v1
> kind: Service
> metadata:
> name: yfbhost2
> namespace: tools
> spec:
> type: "NodePort"
> externalTrafficPolicy: "Local"
> ports:
> 
> * port: 80
>   targetPort: 80
>   protocol: TCP
>   #nodePort: 30080
>   selector:
>   tools: yfbhost2
> 
> ## SVC2 YMAL
> apiVersion: apps/v1
> kind: Deployment
> metadata:
> name: ues-test
> namespace: tools
> spec:
> replicas: 1
> strategy:
> type: RollingUpdate
> rollingUpdate:
> maxSurge: 20%
> maxUnavailable: 10%
> selector:
> matchLabels:
> app: use-ws
> type: tomcat
> template:
> metadata:
> labels:
> app: use-ws
> type: tomcat
> spec:
> containers:
> - name: ues-test
> image: harbor.kjtpay.local/app/ues-test:20190826-1
> #imagePullPolicy: IfNotPresent
> imagePullPolicy: Always
> resources:
> limits:
> cpu: "1" #限制pod申请最大的cpu数量为1个cpu
> memory: 2Gi #申请内存最大值
> ports:
> - protocol: TCP
> containerPort: 8080
> command:
> - "/opt/scm_tools/tcruntime-ctl.sh"
> - "ues-test"
> - "start"
> volumeMounts:
> - name: jdk
> mountPath: /opt/jdk1.8.0_131
> readOnly: yes
> - name: app-logs
> mountPath: /opt/logs
> - name: saturn
> mountPath: /opt/saturn
> readOnly: yes
> - name: cert
> mountPath: /opt/ues
> readOnly: yes
> - name: apollo
> mountPath: /opt/settings/server.properties
> readOnly: yes
> subPath: server.properties
> - name: druid
> mountPath: /opt/settings/druid-pool.properties
> readOnly: yes
> subPath: druid-pool.properties
> volumes:
> - name: jdk
> persistentVolumeClaim:
> claimName: tools-jdk-pvc
> - name: cert
> persistentVolumeClaim:
> claimName: ues-cert-pvc
> - name: app-logs
> persistentVolumeClaim:
> claimName: log-pvc
> - name: saturn
> persistentVolumeClaim:
> claimName: saturn-pvc
> - name: apollo
> configMap:
> name: apollo-config
> - name: druid
> configMap:
> name: druid-config
> defaultMode: 0400
> nodeSelector:
> tools: yfbhost
> 
> apiVersion: v1
> kind: Service
> metadata:
> name: ues-bgp-service
> namespace: tools
> spec:
> type: "NodePort"
> externalTrafficPolicy: "Local"
> ports:
> 
> * port: 28080
>   targetPort: 28080
>   protocol: TCP
>   #nodePort: 30080
>   selector:
>   app: ues-test

**Comment by qq284418233** [comment]
> https://docs.projectcalico.org/v3.8/networking/service-advertisement#about-advertising-kubernetes-services-over-bgp might be relevant

NO.
My problem is that SVC can't be released to Cisco switches through BUG, but two SVCs with the same configuration. One of them can be released and the other one is not released.

**Comment by tmjd** [comment]
@lmm I think this might be the same as a story you're working on this sprint. WDYT?

**Comment by lmm** [comment]
@qq284418233 Sorry for the delayed response. Did you get this sorted out? If not, could you verify that there are Ready endpoints in both services?

**Comment by tmjd** [comment]
What version of Calico are you using?

**Comment by lmm** [comment]
I'll close this for now, please file a new issue if you encounter anything else.
