### ISSUE TITLE
A plenty of pods of the kubernetes readiness got 503, and restart calico restore

### ISSUE THREAD

**Issue by xieyanker** [projectcalico/calico#2829]
## Current Behavior

A plenty of pods of my k8s cluster's status change to 0/1, beacuse of readinessProbe got 503.
Then I restart calico, it restored. I didn't get useful info from the log or calico.

## Possible Solution

I don't konw whether the probelem of calico.

## Your Environment

* Calico version
> Client Version:    v1.6.3
Build date:        2017-12-20T22:32:36+0000
Git commit:        d4cfc95c
Cluster Version:   v2.6.8
Cluster Type:      kubespray,bgp
* Orchestrator version (e.g. kubernetes, mesos, rkt):
> k8s version: v1.10.4
* Operating System and version:
> Ubuntu 16.04.4 LTS

**Comment by caseydavenport** [comment]
@xieyanker v2.6.8 is very old and out of support - I recommend upgrading to a newer version of Calico.

We've made a lot of improvements in this area since then.
