### ISSUE TITLE
Policy controller manifest could use placeholders for TLS config

### ISSUE THREAD

**Issue by lwr20** [projectcalico/calico#283]
http://docs.projectcalico.org/v2.0/getting-started/kubernetes/installation/policy-controller.yaml

@joeblack from our users-slack says that he'd expect most people to want to connect to their etcd using tls to secure it - would be nice if this manifest contained comments that indicated how you would modify the manifest to do that. https://calicousers.slack.com/archives/kubernetes/p1480505063004132

**Comment by caseydavenport** [comment]
FTR we do document that here: http://docs.projectcalico.org/v2.0/reference/policy-controller/configuration

Probably low cost to add comments, even if it's just a link to that doc.
