### ISSUE TITLE
Cannot download v3.9.0 release archive.

### ISSUE THREAD

**Issue by AlexeyKasatkin** [projectcalico/calico#2855]
**Cannot download v3.9.0 release archive.**

## Expected Behavior
https://github.com/projectcalico/calico/releases/download/v3.9.0/release-v3.9.0.tgz
should be accessible (link was taken from https://docs.projectcalico.org/v3.9/release-notes/).

## Current Behavior
"File not found" error. No such release tag can be found on ``Releases`` page.

**Comment by caseydavenport** [comment]
Looks like we forgot to publish this. 

I've just uploaded the artifacts - they should be available now. Thanks for raising this!
