### ISSUE TITLE
Remove Docker Vagrant-Ubuntu  Guide

### ISSUE THREAD

**Issue by djosborne** [projectcalico/calico#286]
I don't think we really need to be maintaining 2 vagrant guides. Let's stick with CoreOS guide to match the k8s guide.

**Comment by robbrockbank** [comment]
personally i like having ubuntu vagrant setup - it's certainly useful from a dev perspective as Ubuntu has more freedom in terms of installation etc.

That said, is it really required as a tutorial - probably not.
