### ISSUE TITLE
Calico is breaking routes after datastore lost

### ISSUE THREAD

**Issue by bartlomiejsawicki** [projectcalico/calico#2873]
I am not sure if this is error in configuration or just default behavior of Calico node but when Calico is not able to connect to datastore (which for me is kubernetes) is changing already available routes to incorrect one (is switching all routes from tunl0 to ens3).

With this behavior all pods are losing possibility to connect each other. According to me all settings shouldn't be changed so at least what is working will still work.  

Calico version  v3.3.0
Kubernetes v1.11.7
Ubuntu Xenial 

Step to reproduce:
- turn off all kubernetes masters

When masters up:
default via 192.168.0.1 dev ens3 
10.5.0.0/24 via 192.168.0.20 dev tunl0  proto bird onlink 
10.5.1.0/24 via 192.168.0.31 dev tunl0  proto bird onlink 
blackhole 10.5.2.0/24  proto bird 
10.5.2.3 dev cali748e9b88830  scope link 
10.5.2.4 dev caliafdf243cde7  scope link 
169.254.169.254 via 192.168.0.1 dev ens3 
172.17.0.0/16 dev docker0  proto kernel  scope link  src 172.17.0.1 linkdown 
192.168.0.0/24 dev ens3  proto kernel  scope link  src 192.168.0.30

When masters down:
default via 192.168.0.1 dev ens3 
10.5.0.0/24 via 192.168.0.20 dev ens3  proto bird 
10.5.1.0/24 via 192.168.0.31 dev ens3  proto bird 
blackhole 10.5.2.0/24  proto bird 
10.5.2.3 dev cali748e9b88830  scope link 
10.5.2.4 dev caliafdf243cde7  scope link 
169.254.169.254 via 192.168.0.1 dev ens3 
172.17.0.0/16 dev docker0  proto kernel  scope link  src 172.17.0.1 linkdown 
192.168.0.0/24 dev ens3  proto kernel  scope link  src 192.168.0.30

**Comment by rafaelvanoni** [comment]
@bartlomiejsawicki Could you clarify if this is what you're seeing after the installation (without any changes to master or any node) or if this only happens when you 'turn off' the master? Are you seeing if any pods are restarting or unhealthy?

I'd expect lots of things to go wrong if the datastore is not reachable, are you trying to test a specific scenario with this test?

**Comment by bartlomiejsawicki** [comment]
This is situation during HA test. One of scenario is to turn off all masters and check if application is still working. It was ok when CALICO_IPV4POOL_IPIP was set to OFF(so without IPIP) test was successful. 
When changed to default which is ALWAYS (IPIP enabled) stopping masters is causing routes to be changed. As soon as masters are back, routes are correct again.

It would be nice to prevent somehow updates of the routes when no datastore. It is better to not touch than break when no information about cluster state.

**Comment by caseydavenport** [comment]
Ah, I think I know this one. I suspect you're hitting an issue that was fixed by this PR: https://github.com/projectcalico/libcalico-go/pull/1057

It seems to have be present in v3.5.5 and later. Could you try a newer release and let us know if that fixes your issue?

**Comment by bartlomiejsawicki** [comment]
Thank you, after upgrading to 3.9.0 there is no problem.
