### ISSUE TITLE
Tunl0 interface shows overruns errors in TX

### ISSUE THREAD

**Issue by ferrandinand** [projectcalico/calico#2878]
We are running calico 3.7.2 with ipip tunnel always in aws but also onpremise , we see that periodically the errors count increases without CPU spikes in TX.

All nodes in the same cluster have a very similar error overrun value and it increases to all at the same time.

We increased the txqueuelen from 1000 to 10000 but seems not related to maximum number of packets queued on the output side.

This is happening in all nodes (with a very similar error number) in a cluster but also in different clusters with different workloads not similar in cpu/mem/network demands.

```
tunl0: flags=193<UP,RUNNING,NOARP>  mtu 1440
        inet 192.168.148.0  netmask 255.255.255.255
        tunnel   txqueuelen 1000  (IPIP Tunnel)
        RX packets 16205656  bytes 5743261616 (5.3 GiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 18243634  bytes 38428771454 (35.7 GiB)
        TX errors 35842  dropped 0 overruns 35842  carrier 0  collisions 0
```

```
sysctl net.core.default_qdisc
net.core.default_qdisc = fq_codel
```
```
cat /proc/softirqs
                    CPU0       CPU1       CPU2       CPU3
          HI:          0          0          0          0
       TIMER:  375507559  374339959  381113632  448485418
      NET_TX:    2594736    2890325    2086349    1709174
      NET_RX:  180789942  191052727  119558818  150713391
       BLOCK:          0          0          0          0
    IRQ_POLL:          0          0          0          0
     TASKLET:     341926      26317      19504      21003
       SCHED:  250080239  235988557  226253826  228469284
     HRTIMER:         93        211        115        400
         RCU:  247773015  247734480  247786044  290760863
```

```
tc -s qdisc ls dev tunl0
qdisc noqueue 0: root refcnt 2
 Sent 0 bytes 0 pkt (dropped 0, overlimits 0 requeues 0)
 backlog 0b 0p requeues 0
```

```
cat /proc/net/sockstat
sockets: used 316
TCP: inuse 20 orphan 0 tw 81 alloc 100 mem 18
UDP: inuse 1 mem 27
UDPLITE: inuse 0
RAW: inuse 0
FRAG: inuse 0 memory 0
```

```
IcmpMsg:
    InType3: 63
    OutType3: 2356
    OutType5: 6337
Tcp:
    10789434 active connection openings
    1703967 passive connection openings
    464141 failed connection attempts
    524 connection resets received
    16 connections established
    72617434 segments received
    76925678 segments sent out
    2598 segments retransmitted
    0 bad segments received
    467298 resets sent
UdpLite:
TcpExt:
    32 packets pruned from receive queue because of socket buffer overrun
    3123337 TCP sockets finished time wait in fast timer
    741680 delayed acks sent
    39 delayed acks further delayed because of locked socket
    Quick ack mode was activated 3144 times
    16543237 packet headers predicted
    22456212 acknowledgments not containing data payload received
    3072144 predicted acknowledgments
    TCPSackRecovery: 28
    Detected reordering 34 times using SACK
    1 congestion windows fully recovered without slow start
    TCPDSACKUndo: 17
    TCPLostRetransmit: 11
    56 fast retransmits
    TCPTimeouts: 41
    TCPLossProbes: 4970
    TCPLossProbeRecovery: 8
    TCPDSACKOldSent: 3144
    TCPDSACKRecv: 2486
    697 connections reset due to unexpected data
    511 connections reset due to early user close
    TCPDSACKIgnoredNoUndo: 2410
    TCPSackShifted: 1
    TCPSackMerged: 34
    TCPSackShiftFallback: 77
    TCPRcvCoalesce: 1527872
    TCPOFOQueue: 4798
    TCPChallengeACK: 11
    TCPSpuriousRtxHostQueues: 34
    TCPAutoCorking: 311677
    TCPFromZeroWindowAdv: 1
    TCPToZeroWindowAdv: 1
    TCPWantZeroWindowAdv: 176
    TCPSynRetrans: 47
    TCPOrigDataSent: 31232162
    TCPHystartTrainDetect: 360
    TCPHystartTrainCwnd: 6328
    TCPKeepAlive: 10808
    TCPDelivered: 41558150
    TCPAckCompressed: 3936
IpExt:
    InNoRoutes: 4
    InMcastPkts: 3
    OutMcastPkts: 6
    InOctets: 399861042774
    OutOctets: 645559698816
    InMcastOctets: 153
    OutMcastOctets: 273
    InNoECTPkts: 600648026
```

## Context
As this is not an important error rate but we need to understand why those errors are appearing when using calico in ipinip with tunl0 and not when using a different cni.

## Your Environment

* Calico version
`Calico 3.7.2` but also with `3.8.2`
* Orchestrator version (e.g. kubernetes, mesos, rkt):
`Kubernetes v1.14.3` but in others like `v1.14.6`
* Operating System and version:
```
NAME="Container Linux by CoreOS"
ID=coreos
VERSION=2023.4.0 but also in other versions as 2135.4.0 
```

**Comment by fasaxc** [comment]
I believe that error means that the tunnel can't send packets as fast as they're being queued.This could be due to the NIC having insufficient capacity underneath the tunnel or some other factor.  Probably OK if it happens once in a while but if it spikes then there might be something going on.

**Comment by ferrandinand** [comment]
I don´t think this is due insufficient capacity, the node is not under any load and even increasing txqueuelen errors remain growing.

After a tcpdump I see that the error increases by one after receiving a DHCP request from 0.0.0.0.

```
12: tunl0@NONE: <NOARP,UP,LOWER_UP> mtu 8981 qdisc noqueue state UNKNOWN group default qlen 1000
    link/ipip 0.0.0.0 brd 0.0.0.0
    inet 192.168.49.64/32 brd 192.168.49.64 scope global tunl0
       valid_lft forever preferred_lft forever
```
```
IP (tos 0xc0, ttl 64, id 0, offset 0, flags [none], proto UDP (17), length 357)
    0.0.0.0.68 > 255.255.255.255.67: [udp sum ok] BOOTP/DHCP, Request from 00:00:00:00:00:00, length 329, xid 0xc2ecf13d, secs 44736, Flags [none] (0x0000)
	  Client-Ethernet-Address 00:00:00:00:00:00
	  Vendor-rfc1048 Extensions
	    Magic Cookie 0x63825363
	    DHCP-Message Option 53, length 1: Discover
	    Client-ID Option 61, length 19: hardware-type 255, 61:88:a9:20:00:02:00:00:ab:11:09:d0:da:17:12:70:26:e8
	    Parameter-Request Option 55, length 9:
	      Subnet-Mask, Default-Gateway, Hostname, Domain-Name
	      Domain-Name-Server, MTU, Static-Route, Classless-Static-Route
	      NTP
	    MSZ Option 57, length 2: 576
	    FQDN Option 81, length 47: [SE] "^Lip-10-1-3-31^Lus-central-1^Gcompute^Hinternal^@"
	    END Option 255, length 0
```
Not any other interface in the node is receiving this packet.

**Comment by fasaxc** [comment]
Are you sure it's receiving a DHCP packet?  More likely to be trying to send one, I'd expect.  We should probably block DHCP on the tunnel, it has no purpose since the tunnel is not a broadcast device.

**Comment by ferrandinand** [comment]
You are totally right but that it makes sense that after blocking this broadcast request there is a new tx overrun error into the interface?

**Comment by fasaxc** [comment]
@ferrandinand If you're still seeing more errors, suggest you tcpdump again to find out what the now-failing sort of packet is.

**Comment by ferrandinand** [comment]
Ok, no new news here after running tcpdump listening on tunl0 interface.
One DHCP request received in tunl0, one more TX error overrun in the tunl0 interface. Enabling all usual traffic in the network does not provide any other additional errors.
No CPU spikes, no network problems as all nodes in the k8s cluster receive the same package and all create the same error at the same time in the node in the tunnel interface.

**Comment by lmm** [comment]
Closing since this has gotten stale

**Comment by yusufgungor** [comment]
Hi, this issue is still valid for us too. We also see that DHCP requests on tunl0 interface which increases the tx erros and overruns.

```
tunl0: flags=193<UP,RUNNING,NOARP>  mtu 1400
        inet 10.253.82.0  netmask 255.255.255.255
        tunnel   txqueuelen 1000  (IPIP Tunnel)
        RX packets 3  bytes 1592 (1.5 KB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 3  bytes 135 (135.0 B)
        TX errors 1483  dropped 0 overruns 1483  carrier 0  collisions 0
```
  

OS: Ubuntu 20.04.3 LTS
OS Kernel: Linux 5.4.0-90-generic #101-Ubuntu SMP Fri Oct 15 20:00:55 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

Calico
Client Version:    v3.20.2
Git commit:        dcb4b76a
Cluster Version:   v3.20.2
Cluster Type:      kubespray,bgp,kubeadm,kdd,k8s
  calico_backend: bird
  cluster_type: kubespray,bgp

ippool spec:
  blockSize: 24
  cidr: 10.253.64.0/18
  ipipMode: Always
  natOutgoing: true
  nodeSelector: all()
  vxlanMode: Never

**Comment by yusufgungor** [comment]
We had to switch to the cilium cni and no more tx errors or overruns.
