### ISSUE TITLE
CNI spec version clarify

### ISSUE THREAD

**Issue by filip-havlicek** [projectcalico/calico#2886]
You mentioned usage of CNI spec version 0.3.1 in Calico v3.9.1 - https://docs.projectcalico.org/v3.9/release-notes/
`Use CNI spec version 0.3.1 calico #2882 (@caseydavenport)`
I just downloaded fresh release archive and all Kubernetes manifests uses `"cniVersion": "0.3.0"`.
```
grep -ri "cniVersion" k8s-manifests
k8s-manifests/flannel-migration/calico.yaml:      "cniVersion": "0.3.0",
k8s-manifests/canal.yaml:      "cniVersion": "0.3.0",
k8s-manifests/calico-policy-only.yaml:      "cniVersion": "0.3.0",
k8s-manifests/calico.yaml:      "cniVersion": "0.3.0",
k8s-manifests/calico-typha.yaml:      "cniVersion": "0.3.0",
k8s-manifests/canal-etcd.yaml:        "cniVersion": "0.3.0",
k8s-manifests/calico-etcd.yaml:      "cniVersion": "0.3.0",
```

Mentioned commit looks like fix for Helm chart, but shouldn't it be consistent with other deployment methods?

**Comment by caseydavenport** [comment]
Interesting. 

The manifests hosted in the docs website have the correct version: https://docs.projectcalico.org/v3.9/manifests/calico.yaml

Looks like perhaps the wrong manifests ended up in the release archive.

**Comment by caseydavenport** [comment]
Looks like v3.9.1 was accidentally tagged from commit 8c0fba3d198f4eed7b31f4d4513120c3de68ca95 which doesn't include the cniVersion updates, so the release tarball didn't include the changes from 108e47678be6b6063e39fbcede1272012aca369a.

**Comment by caseydavenport** [comment]
Closing this - we'll be cutting a new release in the near future. We shouldn't replace the existing tar archive despite the error.
