### ISSUE TITLE
Duplicate IPs detected between tun interfaces and pods

### ISSUE THREAD

**Issue by zanetworker** [projectcalico/calico#2887]
Sometimes we detect pods using an IP similar to an already assigned tunnel interface IP on a node, this leads to connectivity issues. 

## Expected Behavior

Pods should not be assigned an IP which is already taken by the nodes. Calico should somehow be aware of IP assigned by other IPAM plugins (e.g., host-local). 

## Steps to Reproduce (for bugs)
The issue is sporadic, therefore unable to reproduce.

## Your Environment

* Calico version 3.7
* kubernetes 1.15
* Operating System and version: CoreOS 
* host-local is used as an IPAM plugin with "usePodCIDR"
* APIServer is used as the data-store.

**Comment by caseydavenport** [comment]
@zanetworker could you share how you installed Calico? Are you using one of the manifests from docs.projectcalico.org? Are there any modifications?

**Comment by zanetworker** [comment]
@caseydavenport yes, the most prominent modification would be that we use "host-local" IPAM instead of Calico IPAM. Also for your reference, here is the [link](https://github.com/gardener/gardener-extensions/blob/master/controllers/networking-calico/charts/internal/calico/templates/calico.yaml) to our configuration, if you want to have a quick look at the overall config.

**Comment by caseydavenport** [comment]
I think if you're using the host-local IPAM instead of Calico, you need to set the `USE_POD_CIDR` environment variable. Otherwise, some components may still try to use calico-ipam, and that could lead to the same address being assigned twice.

This is the check that's meant to prevent this from happening: https://github.com/projectcalico/node/blob/master/pkg/allocateip/allocateip.go#L44-L47

It gets set based on this line: https://github.com/projectcalico/libcalico-go/blob/HEAD/lib/apiconfig/apiconfig.go#L79

It's documented on this page: https://docs.projectcalico.org/v3.9/reference/node/configuration

> USE_POD_CIDR	Use the Kubernetes Node.Spec.PodCIDR field. This field is required when using the Kubernetes API datastore with host-local IPAM. [Default: false]	boolean

Hopefully it's just a matter of setting that environment variable in your calico/node daemonset and typha deployment.

**Comment by zanetworker** [comment]
@caseydavenport we do set it but in calico cni config instead, my asumption is that when this is set then the apiConfig would be set as well from this value. Here is the config: 
```json
 "plugins": [
        {
          "type": "calico",
          "log_level": "error",
          "datastore_type": "kubernetes",
          "nodename": "__KUBERNETES_NODE_NAME__",
          "mtu": __CNI_MTU__,
          "ipam": {
            "type": "host-local",
            "subnet": "usePodCidr"
          },
          "policy": {
            "type": "k8s"
          },
          "kubernetes": {
            "kubeconfig": "__KUBECONFIG_FILEPATH__"
          }
        },
        {
          "type": "portmap",
          "snat": true,
          "capabilities": {"portMappings": true}
        }
      ]
    }
```
Also did that according to the documetnation: https://docs.projectcalico.org/v3.9/reference/cni-plugin/configuration 

> When using the CNI host-local IPAM plugin, a special value usePodCidr is allowed for the subnet field (either at the top-level, or in a “range”). This tells the plugin to determine the subnet to use from the Kubernetes API based on the Node.podCIDR field. Calico does not use the gateway field of a range so that field is not required and it will be ignored if present.

**Comment by caseydavenport** [comment]
> my asumption is that when this is set then the apiConfig would be set as well from this value. Here is the config:

That's not quite right. The CNI config is just the configuration for the CNI plugins, not other components like calico/node and Typha. They each need to be told about this config separately via their environment.

**Comment by redbaron** [comment]
@caseydavenport , does `USE_POD_CIDR` need to be set for calico-kube-controllers  too?

**Comment by caseydavenport** [comment]
I think right now, the `USE_POD_CIDR` option doesn't do anything in kube-controllers. 

We should probably add support for that option and turn off the relevant controllers if set. 

However, kube-controllers job is actually just to clean up IPAM allocations when using calico IPAM, so _today_ it's not actually needed if using host-local IPAM.

**Comment by tmjd** [comment]
It sounds like this has been resolved so I'm going to close this. If this is wrong please comment and we can re-open this.
