### ISSUE TITLE
Improve calico-node liveness probe to detect bird or confd not running

### ISSUE THREAD

**Issue by bradbehle** [projectcalico/calico#2889]
We recently had a case where calico-node was running and the liveness check was succeeding, but the node was not getting pod routes from any other k8s nodes.  Investigation showed that it was because bird and confd were not running, here was the process list in calico-node:

```
/ # ps -ef
PID   USER     TIME  COMMAND
    1 root      0:04 /sbin/runsvdir -P /etc/service/enabled
   55 root      4:57 runsv confd
   56 root      5:01 runsv bird
   57 root      5:01 runsv bird6
   58 root      0:00 runsv felix
   61 root      2h06 calico-node -felix
13609 root      0:00 sh
20801 root      0:00 ps -ef
79375 root      0:00 sh
/ # 
```

It turns out that this was caused by kubelet not putting any of the k8s service env vars in the container, for instance there was no:

```
KUBERNETES_PORT=tcp://172.21.0.1:443
...
KUBERNETES_SERVICE_HOST=172.21.0.1
KUBERNETES_SERVICE_PORT=443
KUBERNETES_SERVICE_PORT_HTTPS=443
```

I found in the kubelet.log an error indicating that when it first started up (right before it started the calico-node pod), for some reason it failed to get the k8s service list from the apiserver, so I assume it just started calico-node anyway without these env vars. 

When I exec'd into the pod that was like this, and tried to run confd by hand, it said it needed KUBECONFIG or KUBERNETES_PORT (or something similar).  Then I think bird wouldn't start since confd didn't create the bird.cfg files.

## Expected Behavior

Ideally, if calico-node is not in a functioning state, as in this case where bird won't start and it won't get any routes for pods on any other nodes, the liveness probe should detect this and fail, so that k8s can restart the node

## Current Behavior

The liveness probe returned success

## Possible Solution

Have the liveness probe check that bird and confd are up and running

## Steps to Reproduce (for bugs)

I didn't try this, but I think if you delete the default/kubernetes service from your cluster, and then restart one of the calico-node pods, kubelet might start up the calico-node container without the env vars.  otherwise  you could manually muck with the configuration so that confd and bird don't start, and then test out how to get the liveness probe to detect this?

## Context

While this shouldn't happen often (kubelet not setting the env vars), when it does it is very hard to detect and fix.  calico-node shows it is in ready state, but none of the pods on the node will be able to talk to any pods on any other nodes.  We have to somehow figure out that this happened, and reboot the node or restart calico-node

## Your Environment

* Calico version: 3.6.4
* Orchestrator version (e.g. kubernetes, mesos, rkt): k8s 1.13 (but I don't think it is version dependent)
* Operating System and version: Ubuntu 16.04 LTS
* Link to your project (optional):

**Comment by rafaelvanoni** [comment]
@bradbehle Thanks for reporting this. Would you be up for proposing a PR?

**Comment by bradbehle** [comment]
@rafaelvanoni Unfortunately, I don't have time now to work on a PR for this

**Comment by caseydavenport** [comment]
Yeah, this sounds like a bug to me. The liveness probes are meant to tell when Calico is live or not, and it seems like they can pass when Calico isn't alive :) 

@bradbehle just to check, could you share what your `livenessProbe` for the calico/node pods looks like? Does it include the `--bird-ready` option?

**Comment by bradbehle** [comment]
@caseydavenport Sorry for the delay getting back to this.  We use the livenessProbe that is in the default yaml (for the various versions we deploy:

https://docs.projectcalico.org/v3.6/getting-started/kubernetes/installation/hosted/calico.yaml
https://docs.projectcalico.org/v3.8/manifests/calico-etcd.yaml
https://docs.projectcalico.org/v3.9/manifests/calico-etcd.yaml

There isn't a `--bird-ready` option on these liveness probes.  There is a `--bird-ready` option on the readiness probes, and we do remove that before deploying, but I don't think that is applicable to the liveness probe, is it?  If so, let me know and I can explain why we took out the `--bird-ready` flag on the readiness probe.

**Comment by caseydavenport** [comment]
> There isn't a --bird-ready option on these liveness probes. There is a --bird-ready option on the readiness probes, and we do remove that before deploying, but I don't think that is applicable to the liveness probe, is it? If so, let me know and I can explain why we took out the --bird-ready flag on the readiness probe.

That's correct. I think I understand this better now - we intentionally don't include `--bird-ready` in the liveness probe today.

I think we probably want a new option - `--bird-live` that checks the bird and confd processes are running.
