### ISSUE TITLE
Calico IPAM is used when explicitly configured otherwise

### ISSUE THREAD

**Issue by zanetworker** [projectcalico/calico#2895]
Logs of all calico components indicate that Calico IPAM is being used although host-local is configured via calico config. 

For example, in the logs we see:  `[INFO][1] k8s.go 228: Using Calico IPAM`. 

Shouldn't this be Using host-local IPAM?

## Expected Behavior
I shouldn't see any indications that Calico IPAM being utilized if I configure `host-local` ipam. 
For example, I should see `[INFO][1] k8s.go 228: Using host-local IPAM`

## Context
Calico-config: 

```json
      "plugins": [
        {
          "type": "calico",
          "log_level": "error",
          "datastore_type": "kubernetes",
          "nodename": "__KUBERNETES_NODE_NAME__",
          "mtu": __CNI_MTU__,
          "ipam": {
            "type": "host-local",
            "subnet": "usePodCidr"
          },
          "policy": {
            "type": "k8s"
          },
          "kubernetes": {
            "kubeconfig": "__KUBECONFIG_FILEPATH__"
          }
        },
        {
          "type": "portmap",
          "snat": true,
          "capabilities": {"portMappings": true}
        }
      ]
    }
```
## Your Environment

* Calico version 3.7.2
* Orchestrator versio: v1.15.4
* Operating System and version: CoreOS

**Comment by caseydavenport** [comment]
I think that log comes from here: https://github.com/projectcalico/libcalico-go/blob/262b6a92960b20ef18fb166829df3098eae33286/lib/backend/k8s/k8s.go#L217-L228

You should make sure you are setting `USE_POD_CIDR` when using host-local IPAM, as mentioned in the docs: 
- https://docs.projectcalico.org/v3.9/reference/typha/configuration
- https://docs.projectcalico.org/v3.9/reference/node/configuration 

> USE_POD_CIDR | Use the Kubernetes Node.Spec.PodCIDR field. This field is required when using the Kubernetes API datastore with host-local IPAM. [Default: false] | boolean
-- | -- | --

**Comment by zanetworker** [comment]
Hi @caseydavenport, 

did you get a change to look at the config I posted? if not, please take another look:

```json
   "plugins": [
        {
          "type": "calico",
          "log_level": "error",
          "datastore_type": "kubernetes",
          "nodename": "__KUBERNETES_NODE_NAME__",
          "mtu": __CNI_MTU__,
          "ipam": {
            "type": "host-local",
            "subnet": "usePodCidr"
          },
          "policy": {
            "type": "k8s"
          },
          "kubernetes": {
            "kubeconfig": "__KUBECONFIG_FILEPATH__"
          }
        },
        {
          "type": "portmap",
          "snat": true,
          "capabilities": {"portMappings": true}
        }
      ]
    }
```
I am explicitly setting the subnet field to   `"subnet": "usePodCidr"` as stated in the documentation. Why should I reset the environment variable? please correct me if I am wrong.

**Comment by caseydavenport** [comment]
@zanetworker yep, I looked at your configuration. As I mentioned in the other issue (https://github.com/projectcalico/calico/issues/2887) you need to set USE_POD_CIDR in other places. The CNI configuration is only for the CNI plugins.

You need:
- `usePodCidr` in the CNI config (you've done this)
- ` USE_POD_CIDR=true` in the calico/node env (you haven't done this)
- `USE_POD_CIDR=true` in the calico/typha env (if you're using Typha, if not then ignore)
