### ISSUE TITLE
podCIDR allocation is not working as expected

### ISSUE THREAD

**Issue by sohnaeo** [projectcalico/calico#2900]
**Problem:**

**We need to make this work because we cant run BIRD BGP in our internal network due to security issues and have to rely on the static routes**

**pods are not getting the ips from the podCIDR which assigned to the nodes  **

1- Checkout master branch kubespray

2-  Create inventory, changed only 3 variables

a) Change the etcd deployment to host

b) Change the pod subnets and service addresses

kube_service_addresses: 10.242.0.0/21
kube_pods_subnet: 10.242.64.0/21
kube_network_node_prefix: 24

3- Once Cluster is up , check the pods CIDR assigned to each node
/usr/local/bin/kubectl get nodes node1 -ojsonpath='{.spec.podCIDR}'
node1-->10.242.64.0/24
node3-->10.242.65.0/24
node4-->10.242.66.0/24
node5-->10.242.67.0/24

4- kubectl apply -f nginx.yml with replicas of 6

nginx-5754944d6c-8kzhj   1/1     Running   0          66m   10.242.70.2   node5   <none>           <none>
nginx-5754944d6c-b2tvh   1/1     Running   0          66m   10.242.67.3   node4   <none>           <none>
nginx-5754944d6c-dj4qq   1/1     Running   0          66m   10.242.66.1   node3   <none>           <none>
nginx-5754944d6c-wbhdb   1/1     Running   0          66m   10.242.70.3   node5   <none>           <none>
nginx-5754944d6c-x7gdq   1/1     Running   0          66m   10.242.66.2   node3   <none>           <none>
nginx-5754944d6c-z9vcv   1/1     Running   0          66m   10.242.67.2   node4   <none>           <none>

look at above pods are getting the ips from range which not assigned to the hosts. It is working fine in kubernetes 1.9

**Environment**: master branch
- **Cloud provider or hardware configuration:**  AWS

- **OS (`printf "$(uname -srm)\n$(cat /etc/os-release)\n"`):** 
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

- **Version of Ansible** (`ansible --version`): 
ansible 2.7.12
  config file = /home/farhan/workspaces/kubespray-orignal/ansible.cfg
  configured module search path = ['/home/farhan/workspaces/kubespray-orignal/library']
  ansible python module location = /usr/lib/python3.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.7.4 (default, Jul 16 2019, 07:12:58) [GCC 9.1.0]

**Kubespray version (commit) (`git rev-parse --short HEAD`):*86cc703c*

**Network plugin used**: defult

**Copy of your inventory file:**
[all]
node1 ansible_host=13.x.x.x ip=13.211.170.14  # ip=10.3.0.1 etcd_member_name=etcd1
node2 ansible_host=3.x.x.x ip=3.104.120.158 # ip=10.3.0.2 etcd_member_name=etcd2
node3 ansible_host=13.x.x.x ip=13.210.80.241 # ip=10.3.0.3 etcd_member_name=etcd3

[kube-master]
node1

[etcd]
node5

[kube-node]
node2
node3
node4

[calico-rr]

[k8s-cluster:children]
kube-master
kube-node
calico-rr

How can we change the behavior of IPAM behavior?

**Comment by sohnaeo** [comment]
I fixed this issue by hacking the below but it is not clean solution, would love to see better solution of this

kubespray/role/network_plugin/calico/templates/cni-calico.conflist.j2

FROM
{% else %}
"ipam": {
"type": "calico-ipam",
"assign_ipv4": "true",
"ipv4_pools": ["{{ calico_pool_cidr | default(kube_pods_subnet) }}"]
},

TO:

{% else %}
"ipam": {
"type": "host-local",
"subnet": "usePodCidr"
},

**Comment by caseydavenport** [comment]
> I fixed this issue by hacking the below but it is not clean solution, would love to see better solution of this

That's how it is meant to work. If you want to use host-local IPAM, you need to adjust the configuration file as you did. What do you think would make a better solution?

Also note that when you're using host-local IPAM, you need to set `USE_POD_CIDR=true` in the calico/node and Typha environments.

**Comment by caseydavenport** [comment]
I'd also recommend looking at using Calico's VXLAN capabilities, which don't use BGP and would avoid the need to static routes.

**Comment by sohnaeo** [comment]
@caseydavenport 

Thanks for the prompt reply. In the absence of BGP/BIRD , we are using static routes that make this better solution. Nodes must get podCIDR so static routes work in the cluster. Thanks for the suggestion, I will look into calico VXLAN capabilities.
