### ISSUE TITLE
kubelet reporting "container runtime is down", calico CNI call hanging

### ISSUE THREAD

**Issue by bradbehle** [projectcalico/calico#2902]
It appears that occasionally a Calico CNI call to get the IPPools is hanging, which is hanging containerd (which is making the call).  All of a sudden a few nodes in a k8s cluster will start reporting NotReady, and the reason is "container runtime is down". Here is the relevant section of the `kubectl describe node`:

```
Conditions:
Type Status LastHeartbeatTime LastTransitionTime Reason Message
---- ------ ----------------- ------------------ ------ -------
MemoryPressure False Sat, 28 Sep 2019 15:05:43 +0000 Tue, 17 Sep 2019 04:09:30 +0000 KubeletHasSufficientMemory kubelet has sufficient memory available
DiskPressure False Sat, 28 Sep 2019 15:05:43 +0000 Tue, 17 Sep 2019 04:09:30 +0000 KubeletHasNoDiskPressure kubelet has no disk pressure
PIDPressure False Sat, 28 Sep 2019 15:05:43 +0000 Tue, 17 Sep 2019 04:09:30 +0000 KubeletHasSufficientPID kubelet has sufficient PID available
Ready False Sat, 28 Sep 2019 15:05:43 +0000 Sat, 28 Sep 2019 14:58:10 +0000 KubeletNotReady container runtime is down
```
In one case we were able to get the containerd.log file, and the last line that is shown is:

DATE HOSTNAME containerd[10176]: 2019-08-02 09:32:29.142 [INFO][3397] ipam_plugin.go 208: Calico CNI IPAM request count IPv4=1 IPv6=0 ContainerID="XXXX" HandleID="k8s-pod-network.XXXX" Workload="XXXX-eth0"

That would seem to indicate that it is "stuck" in the call here: https://github.com/projectcalico/cni-plugin/blob/v3.8.0/pkg/ipamplugin/ipam_plugin.go#L210. to utils.ResolvePools, which it looks like makes a call to etcd to get the IPPools.

Workers in this state typically stay like this for an hour or more, until we restart our network firewalls, at which point they immediately go back to Ready state. We aren't sure if the restart just ends these stuck connections, or if it is related to the lower latency once these devices are restarted.

## Expected Behavior
Even if there is some issue with etcd latency, I would expect that the Calico CNI would have some kind of timeout and retry that would prevent this apparent hang

## Current Behavior
Containerd seems to hang for an hour or more on this Calico CNI call

## Possible Solution
Calico CNI would have some kind of timeout and retry that would prevent this apparent hang

## Steps to Reproduce (for bugs)
Unfortunately we can not reliably reproduce this.  If there are certain logs we should gather when it happens, let us know.

## Context
Kubernetes clusters get in this state and can not schedule new pods to the workers.  Also, it seems like when a few worker nodes get in this state, then more can quickly follow

## Your Environment

* Calico version: 3.6.4
* Orchestrator version (e.g. kubernetes, mesos, rkt): k8s 1.13.10
* Operating System and version: Ubuntu 16.04.06
* Link to your project (optional):

**Comment by caseydavenport** [comment]
Yeah, we should be protecting network calls with a timeout so that we don't hang forever.

**Comment by caseydavenport** [comment]
Should be fixed by https://github.com/projectcalico/cni-plugin/pull/807
