### ISSUE TITLE
Document use of custom bird filters

### ISSUE THREAD

**Issue by lwr20** [projectcalico/calico#292]
https://github.com/projectcalico/libcalico/pull/150/files

Do we have a doc explaining how to configure and use them?  Ideally with an example :)

**Comment by caseydavenport** [comment]
We do not! However, not required for v2.0.0.

**Comment by caseydavenport** [comment]
I'm not convinced the current implementation is something we want to officially support long-term.  

We don't want users mucking around in etcd, and there are other data stores where this is not supported.  We don't currently have automated tests and I'm not even sure we know this works on the latest Calico.

As such, I don't think documenting this is correct.
