### ISSUE TITLE
Support using kubectl for Calico resources

### ISSUE THREAD

**Issue by caseydavenport** [projectcalico/calico#2923]
Today, you must use calicoctl to install Calico specific resources (for example, IPPools and GlobalNetworkPolicies). 

This is because calicoctl performs important defaulting, validation, and manipulation of these resources. 

On Kubernetes clusters, these are transformed into CRDs which are installed on the cluster. We could theoretically allow the use of those CRDs, but it needs a lot of work. They weren't designed to be used directly.

We should consider enabling the use of those directly, since it means users don't need to use an additional tool (calicoctl). 

Probably need to at least do / consider the following:
- Add schemas, validation, and defaulting to our CRDs.
- Different API group - `crd.projectcalico.org` vs `projectcalico.org`)
- Expectation of the `default.` prefix on policies
- Add short-names to the CRDs for easier commands
- ???

A follow on step would be to update etcd mode to support these CRDs as well, so we have a unified configuration model across both datastores. One option here would be to update kube-controllers to sync data across. 

Here are some examples where folks have wanted to do this:
- https://github.com/projectcalico/calico/issues/2918
- https://github.com/projectcalico/calicoctl/issues/2065
- https://github.com/projectcalico/calico/issues/2784
- https://github.com/projectcalico/calico/issues/2279 (based on description)
- https://github.com/projectcalico/calico/issues/1942#issuecomment-451745429
- https://github.com/projectcalico/calico/issues/2651
- https://github.com/projectcalico/calico/issues/3860

**Comment by prbsparx** [comment]
> you must use calicoctl to install Calico specific resources

I think it’s important to specify that it’s not just Calico specific resources, but calico specific variants of common resources (Example: NetworkPolicy resource that uses Calico specific functionality like rule order)

**Comment by halfcrazy** [comment]
For validating, there will be a webhook, in k8s webhook needs https which means you need a certificate for svc. Usually, we use cert-manager to generate a self-signed certificate. Unfortronly, cert-manager itself need a POD IP. Maybe it's concerned.

**Comment by caseydavenport** [comment]
I think a great first increment here would be to update our CRDs to use the v1 API instead of the v1beta API. This would require that we add schemas to the resources in order to pass validation.

We should do that in the libcalico repository (ideally using auto-generation) and then we'll need to update the ones served in our manfiests which are hosted in the Calico repository.

**Comment by bradbehle** [comment]
@caseydavenport I assume this is only supported for clusters that are using the Kubernetes Datastore Driver?   Clusters using etcd will not have the option of using kubectl to apply GlobalNetworkPolicies?

**Comment by jayunit100** [comment]
h i everyone, im going to be working on this some.  to start... 

Im going to go through what it looks like to do raw config without calicoctl today to see how bad the delta is :)... then ill start to carve this issue up.   if anyone has done this already, please shoot me some hints :)

**Comment by caseydavenport** [comment]
The delta between the `crd.projectcalico.org` and `projectcalico.org` API grouups should be minimal (there are probably some very small differences, but they're like 99% identical and the differences are probably in terms of validation). 

If I were doing this, the first step here is to switch to using the v1 API group instead of v1beta, and seeing what breaks. It will mean we need to add schemas to the resources, which will be a forcing function for identifying differences.

If we start with that, users can continue to use calicoctl but under the covers it will be using validated CRDs using the v1 API + schemas. That will tease out any incompatibilities pretty quickly, I would have thought.

**Comment by teoyaomiqui** [comment]
Was there any progress on this issue?

**Comment by halfcrazy** [comment]
> Was there any progress on this issue?

If you are using calico kubernetes datastore. Calico crd in gv crd.projectcalico.org/v1 
```bash
kubectl get crd|grep calico
bgpconfigurations.crd.projectcalico.org               2021-03-08T07:05:53Z
bgppeers.crd.projectcalico.org                        2021-03-08T07:05:53Z
blockaffinities.crd.projectcalico.org                 2021-03-08T07:05:54Z
clusterinformations.crd.projectcalico.org             2021-03-08T07:05:54Z
felixconfigurations.crd.projectcalico.org             2021-03-08T07:05:54Z
globalnetworkpolicies.crd.projectcalico.org           2021-03-08T07:05:54Z
globalnetworksets.crd.projectcalico.org               2021-03-08T07:05:54Z
hostendpoints.crd.projectcalico.org                   2021-03-08T07:05:54Z
ipamblocks.crd.projectcalico.org                      2021-03-08T07:05:54Z
ipamconfigs.crd.projectcalico.org                     2021-03-08T07:05:54Z
ipamhandles.crd.projectcalico.org                     2021-03-08T07:05:54Z
ippools.crd.projectcalico.org                         2021-03-08T07:05:54Z
kubecontrollersconfigurations.crd.projectcalico.org   2021-03-08T07:05:54Z
networkpolicies.crd.projectcalico.org                 2021-03-08T07:05:54Z
networksets.crd.projectcalico.org                     2021-03-08T07:05:54Z
```

```shell
kubectl get ippools.crd.projectcalico.org
kubectl edit ippools xxxx
```

**Comment by teoyaomiqui** [comment]
@halfcrazy sorry, I did not follow this issue in detail.
Can I use  `kubectl apply -f calico-resources.yaml`  for example?
```
# cat calico-resources.yaml
apiVersion: projectcalico.org/v3
kind: FelixConfiguration
metadata:
  name: default
spec:
...
```
or calicoctl is needed to apply these resources?

**Comment by halfcrazy** [comment]
> @halfcrazy sorry, I did not follow this issue in detail.
> Can I use `kubectl apply -f calico-resources.yaml` for example?
> 
> ```
> # cat calico-resources.yaml
> apiVersion: projectcalico.org/v3
> kind: FelixConfiguration
> metadata:
>   name: default
> spec:
> ...
> ```
> 
> or calicoctl is needed to apply these resources?

calicoctl and kubectl using different resource version in yaml, actually in kubernetes datastore they are the same resource. 

You need to modified apiVersion to using kubectl. 
```yaml
# cat calico-resources.yaml
apiVersion: crd.projectcalico.org/v1
kind: FelixConfiguration
metadata:
  name: default
spec:
...
```

**Comment by caseydavenport** [comment]
> actually in kubernetes datastore they are the same resource.

@halfcrazy @teoyaomiqui This is ALMOST true, but unfortunately not. This is exactly what this issue is about - the `crd.projectcalico.org/v1` API is not suitable for use, and is subtly different than the `projectcalico.org/v3` API that calicoctl exposes. Please do not use the CRD API directly, as you will be bypassing important validation and defaulting, as well as other important logic as hinted at in the OP. 

> Was there any progress on this issue?

In Calico v3.19 we are aiming to have some progress on this issue. The plan is to introduce a supported way to access the projectcalico.org/v3 API group without using calicoctl. I'll report back when there's more to share!

**Comment by caseydavenport** [comment]
Aiming for a tech-preview of this in Calico v3.19. Here's the WIP docs PR: https://github.com/projectcalico/calico/pull/4485

**Comment by jonaz** [comment]
Just started looking into GlobalNetworkPolicy to avoid confict with custom iptables rules on our kubernetes nodes. 

This would be awesome since we use flux to sync kubernetes manifests to all our clusters using the gitops workflow. This is not possible using calicoctl at the moment.

**Comment by caseydavenport** [comment]
Just an update, this has been available for preview since v3.19.  In v3.20 it will be on by default in operator installations, and we'll be aiming to GA this in the near future. Please try it out and let us know if you hit any issues so we can address them!

**Comment by ira-gordin-sap** [comment]
Is it fixed? May I use kubectl instead of calicoctl? What should be done? To replace projectcalico.org/v3 with what?

**Comment by caseydavenport** [comment]
Explained in this doc: https://docs.tigera.io/calico/latest/operations/install-apiserver
