### ISSUE TITLE
Mention support for rkt-netes

### ISSUE THREAD

**Issue by lwr20** [projectcalico/calico#293]
We have vagrant quick start for rkt, and various guides for Kubernetes, but nothing for using RKT in Kubernetes.  We've had a few questions in slack on this.

https://coreos.com/kubernetes/docs/latest/deploy-master.html looks like the closest guide to this, but I suspect its advice may be out of date (its not self hosted)

**Comment by djosborne** [comment]
What are the differences from a Calico perspective for rkt-netes? I would have thought it's up to the user to set up a rkt-netes cluster and then perform a standard hosted install

**Comment by djosborne** [comment]
Maybe a note in the supported platforms page? (which is being reworked in #123)

**Comment by Promaethius** [comment]
Referencing a possible issue with rktnetes and calico in #457

**Comment by caseydavenport** [comment]
As mentioned in this comment, we should document the right release to use for rktnetes: https://github.com/projectcalico/calico/issues/457#issuecomment-274305862

Relies on a Go version of the CNI plugin.

**Comment by caseydavenport** [comment]
We should go with "rktnetes requires Calico v2.0+"
