### ISSUE TITLE
Pod to pod communication through team network only uses one interface at a time instead of all in parallel

### ISSUE THREAD

**Issue by xsaardo** [projectcalico/calico#2930]
Our 3 node k8 cluster uses a bonded network consisting of 4 25Gbps interfaces (setup for loadbalancing) for internal communication and 1Gbps interface for external communication . When we ran parallel iperf3 node-to-node tests we are able to achieve an overall bandwidth much greater than 25Gbps. The iperf3 tests consisted of setting up 4 iperf3 servers on each node and 4 clients on each node and ensured node-to-node communication with the following iperf3 client to server relationship  (node1->node2, node2->node3, node3->node1)

We also ran the above iperf3 test within a pod on each of the 3 nodes 
- pod1 on node1, pod2 on node2, pod3 on node3
- 4 iperf3 server on each pod
- 4 iperf3 clients on each pod
- iperf3 client-to-server relationship: pod1->pod2, pod2->pod3, pod3->pod1

## Expected Behavior
We should be getting > 25Gbps bandwidth for pod to pod communication 

## Current Behavior
We summed up the individual test bandwidths and got ~22Gbps which seems to imply that pod to pod communication only uses one of the 25Gbps interfaces at time 
Also, ethtool on a calico interface gives us `Speed: 10000Mb/s`

## Possible Solution
Not sure how to configure calico to use multiple interfaces in the team network for pod to pod communication

## Context

We want to ensure that we get the network performance between pods that we are expecting

## Your Environment

calico v3.9
kubernetes version: 1.15.4
RHEL 7.6

Calico v3.9 manifest changes
- veth_mtu=9000
- CALICO_IPV4POOL_IPIP=Never
- CALICO_IPV4POOL_CIDR=10.142.0.0/16 (to match kubeadm init value)

**Comment by caseydavenport** [comment]
Did you configure auto-detection to run Calico on the bonded interface? By default, it may not select it depending on how Calico's interface auto-detection selects the interface.

**Comment by xsaardo** [comment]
We verified that calico is using the proper interface by measuring bandwidth for the device and through calicoctl. Further tests seem to indicate that the multiple interfaces in the team network interface are all used for pod to pod communication but the speed is throttled if a calico interface is used by more than one iperf test at a time.  Performing 2 iperf tests between 2 separate pairs of pods allows us to get 50Gbps while 2 iperf tests in parallel from a single pair of pods doesn't.

**Comment by rafaelvanoni** [comment]
@xsaardo I'm not sure I understood your scenario correctly but if you have two iperf sessions sharing the same 50Gb pipe, I'd expect throughput to be around 25Gb/s. Could you please clarify if that's the case?

**Comment by xsaardo** [comment]
@rafaelvanoni We were able to get 50Gbps for host to host communication with 2 parallel iperf tests but only 25Gbps for pod to pod communication. However, we resolved the issue by assigning more cores/memory to those pods and saw 50Gbps as well. Thanks though!
