### ISSUE TITLE
Explicitly warn users not to bind `calicoctl` to systemd

### ISSUE THREAD

**Issue by ozdanborne** [projectcalico/calico#294]
Our [Calico as a service doc](http://docs.projectcalico.org/v2.0/usage/configuration/as-service) could do with a harder nudge warning users not to bind `calicoctl` to a systemd process. 

As per [#1322](https://github.com/projectcalico/calico-containers/issues/1322)

**Comment by caseydavenport** [comment]
I don't really understand this issue.  Could you explain what the problem is here?

Also note that our latest doc here doesn't use calicoctl: http://docs.projectcalico.org/v2.2/usage/configuration/as-service
