### ISSUE TITLE
Application layer policy does not work with Kubernetes 1.16

### ISSUE THREAD

**Issue by lmm** [projectcalico/calico#2943]
## Expected Behavior

The latest application layer policy (ALP) installation docs work on Kubernetes 1.16 clusters.

## Current Behavior

The ALP installation will fail because the Istio 1.1.7 quick install bundle does not support Kubernetes 1.16. The Istio 1.x.x manifests use API resources that are not served out-of-the-box in Kubernetes 1.16. For details, see: https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.16.md#deprecations-and-removals

## Possible Solution

The ideal solution would be to update ALP so that it works with the latest Istio (1.3.2 as of writing).

Here are some workarounds:

1. The "easiest" workaround is to re-enable serving the removed API resources by modifying the `--runtime-config` as described in the Kubernetes 1.16 changelog linked above.

2. Another way is to update the downloaded Istio installation manifests so that they will work with 1.16. For example, all Deployments and DaemonSets would need to be updated to use apiVersion `apps/v1` and have a valid `spec.selector`. Here is an example diff of `install/kubernetes/helm/istio/charts/nodeagent/templates/daemonset.yaml` with those changes needed:

```
@@ -1,4 +1,4 @@
-apiVersion: extensions/v1beta1
+apiVersion: apps/v1
 kind: DaemonSet
 metadata:
   name: istio-nodeagent
@@ -10,6 +10,13 @@ metadata:
     heritage: {{ .Release.Service }}
     istio: nodeagent
 spec:
+  selector:
+    matchLabels:
+      app: {{ template "nodeagent.name" . }}
+      chart: {{ template "nodeagent.chart" . }}
+      release: {{ .Release.Name }}
+      heritage: {{ .Release.Service }}
+      istio: nodeagent
   template:
     metadata:
       labels:
```

So, the ALP installation steps would look like so:

```
curl -L https://git.io/getLatestIstio | ISTIO_VERSION=1.1.7 sh -
cd $(ls -d istio-*)
// Update all Deployment and DaemonSet manifests here before continuing further
kubectl apply -f install/kubernetes/helm/istio-init/files/
kubectl apply -f install/kubernetes/istio-demo-auth.yaml
```

Refer to the Kubernetes 1.16 changelog for a full list of the Istio manifest changes you might need to make.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Calico version: latest
* Orchestrator version (e.g. kubernetes, mesos, rkt): kubernetes 1.16
* Operating System and version:
* Link to your project (optional):

**Comment by mhmxs** [comment]
I have some bad feeling to `re-enable serving the removed API resources` on target cluster. I'm affraid it is not possible on every environment. What is your advice, does it make sense to ask Itsio team about our plan to move from `extensions/v1beta1` to `apps/v1`?

**Comment by lmm** [comment]
@mhmxs I think you are right, I don't think that 1st workaround I suggested will work for everyone.

I think @tmjd might be looking into this soon. He might have some ideas of how to proceed with this.

**Comment by puzzloholic** [comment]
I wonder if you can make ALP for latest Istio version which is 1.4.0 that fixes intermittently high cpu usage bug on the sidecar itself
