### ISSUE TITLE
Jenkins slave with dind has no access to internet

### ISSUE THREAD

**Issue by Woap** [projectcalico/calico#2955]
I have a connectivity problem for my Jenkins slave which mount the docker sock to use the docker daemon on the host. 

Calico is working great on my K8s cluster, I have a "tools" namespace with no NetworkPolicy and Jenkins is running in this namespace. When a job is started, a slave pop on the same namespace and try to build a Dockerfile. The problem is that the docker build started by the job has no access to internet.

## Expected Behavior

Pods has access to internet but I need that my docker daemon could also access internet to build an image.

## Current Behavior

My docker daemon has no internet.

When I run a docker on one of K8S node : 

> docker run busybox ping 172.217.21.195
> --- 172.217.21.195 ping statistics ---
> 7 packets transmitted, 0 packets received, 100% packet loss
> 
> docker run busybox cat /etc/resolv.conf
> search default.svc.paas.local svc.paas.local 
> nameserver 10.233.0.3
> nameserver 127.0.0.53
> options ndots:2 timeout:2 attempts:2

If I run a pod in K8S, it has internet : 

> kubectl exec -it -n tools busybox -- sh
> / # ping 172.217.21.195
> PING 172.217.21.195 (172.217.21.195): 56 data bytes
> 64 bytes from 172.217.21.195: seq=0 ttl=55 time=5.254 ms
> 64 bytes from 172.217.21.195: seq=1 ttl=55 time=5.260 ms
> 64 bytes from 172.217.21.195: seq=2 ttl=55 time=5.472 ms
> ^C
> --- 172.217.21.195 ping statistics ---
> 3 packets transmitted, 3 packets received, 0% packet loss
> round-trip min/avg/max = 5.254/5.328/5.472 ms

> / # ping google.fr
> PING google.fr (172.217.21.195): 56 data bytes
> 64 bytes from 172.217.21.195: seq=0 ttl=55 time=5.076 ms
> 64 bytes from 172.217.21.195: seq=1 ttl=55 time=5.178 ms
> 64 bytes from 172.217.21.195: seq=2 ttl=55 time=5.673 ms
> ^C
> --- google.fr ping statistics ---
> 3 packets transmitted, 3 packets received, 0% packet loss
> round-trip min/avg/max = 5.076/5.309/5.673 ms

## Context
Trying to build an image with Docker.

## Your Environment

* Calico version : v3.7.3
* Orchestrator version (e.g. kubernetes, mesos, rkt): Kubernetes
* Operating System and version: v1.15.0

**Comment by rafaelvanoni** [comment]
@Woap This doesn't seem like a Calico specific problem and more an issue with how you're configuring ssh through docker from your slave environment. You would need to pass something along these lines to your `docker run` command:
`-v $(SSH_AUTH_SOCK):/ssh-agent --env SSH_AUTH_SOCK=/ssh-agent`
