### ISSUE TITLE
core dns 问题

### ISSUE THREAD

**Issue by mrhjx2** [projectcalico/calico#2964]
/ # nslookup kube-dns.kube-system.svc.cluster.local
nslookup: can't resolve '(null)': Name does not resolve

Name:      kube-dns.kube-system.svc.cluster.local
Address 1: 10.68.0.2 kube-dns.kube-system.svc.cluster.local

/ # nslookup kubernetes.default.svc.cluster.local
nslookup: can't resolve '(null)': Name does not resolve

Name:      kubernetes.default.svc.cluster.local
Address 1: 10.68.0.1 kubernetes.default.svc.cluster.local

有点奇怪 ，弄不清楚为什么找不到dns服务，也能解析出来。
大神 可以帮忙看一下吗

**Comment by rafaelvanoni** [comment]
@mrhjx2 Could provide some context on what your deployment looks like, which versions you're using and what configuration change led to this error? We need a bit more data :-)

**Comment by mrhjx2** [comment]
thanks. this is  busybox image version question,
