### ISSUE TITLE
ClusterIP type service addresses advertised when kube-proxy is in ipvs mode

### ISSUE THREAD

**Issue by ffilippopoulos** [projectcalico/calico#2967]
We are running calico `3.10` on a kubernetes `1.15.3` cluster on gcp. We configure `kube-proxy` in `ipvs` mode. We are using 3 route reflectors to talk to all calico nodes and advertise paths. Our exact bgp configuration is:
```
kind: BGPConfiguration
metadata:
  name: default
spec:
  logSeverityScreen: Error
  nodeToNodeMeshEnabled: false
  asNumber: 64513
  serviceClusterIPs:
  - cidr: 10.5.0.0/16
```
where `10.5.0.0/16` is our services cidr. Our pods cidr is `10.4.0.0/16`.
Our issue is that along with the static route `10.5.0.0/16` that is advertised by every node, all the `ClusterIP` typed services are also advertised by all our cluster nodes.

## Expected Behavior
We should only see the static range (in our case `10.5.0.0/16`) advertised by bgp clients

## Current Behavior

for example for a simple clusterIP svc:
```
kubectl --context=exp-1-gcp --namespace=sys-on-prem describe svc matchbox
Name:              matchbox
Namespace:         sys-on-prem
Labels:            <none>
Annotations:       kubectl.kubernetes.io/last-applied-configuration:
                     {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"matchbox","namespace":"sys-on-prem"},"spec":{"ports":[{"name":"ht...
Selector:          name=matchbox-s3
Type:              ClusterIP
IP:                10.5.91.100
Port:              http  8080/TCP
TargetPort:        8080/TCP
Endpoints:         10.4.3.22:8080,10.4.5.12:8080,10.4.5.30:8080
Session Affinity:  None
Events:            <none>
```
we can see on our route reflector all nodes advertising a /32 to this:
```
gobgp neighbor 10.66.23.6 local | grep 10.5.91.100
*> 10.5.91.100/32       10.22.22.30                               19:23:34   [{Origin: i} {LocalPref: 100}]
*  10.5.91.100/32       10.22.22.31                               19:23:34   [{Origin: i} {LocalPref: 100}]
*  10.5.91.100/32       10.22.22.32                               00:17:53   [{Origin: i} {LocalPref: 100}]
*  10.5.91.100/32       10.22.22.111                              19:23:34   [{Origin: i} {LocalPref: 100}]
*  10.5.91.100/32       10.22.22.112                              19:23:34   [{Origin: i} {LocalPref: 100}]
*  10.5.91.100/32       10.22.22.113                              19:23:33   [{Origin: i} {LocalPref: 100}]
```
while still advertising the whole range as a static route:
```
gobgp neighbor 10.66.23.6 local | grep 10.5.0.0   
*> 10.5.0.0/16          10.22.22.30                               19:24:40   [{Origin: i} {LocalPref: 100}]
*  10.5.0.0/16          10.22.22.31                               19:24:40   [{Origin: i} {LocalPref: 100}]
*  10.5.0.0/16          10.22.22.32                               00:18:59   [{Origin: i} {LocalPref: 100}]
*  10.5.0.0/16          10.22.22.111                              19:24:40   [{Origin: i} {LocalPref: 100}]
*  10.5.0.0/16          10.22.22.112                              19:24:40   [{Origin: i} {LocalPref: 100}]
*  10.5.0.0/16          10.22.22.113                              19:24:39   [{Origin: i} {LocalPref: 100}]
```

the expected behaviour (as from here: https://github.com/projectcalico/confd/blob/master/pkg/backends/calico/routes.go#L430) is to  only advertise the static `/16` route as there is no point flooding the rib with `/32` ones that are superseded by the static one.

## Possible Solution

Changing kube-proxy to `iptables` mode gives the expected behaviour.

## Steps to Reproduce (for bugs)
Use kube-proxy on `ipvs` mode and use `serviceClusterIPs` inside bgp config to advertise cluster services.

## Context
This is preventing us from advertising kube svc addresses outside our cluster as it will make our bgp ribs messy and hard to debug/maintain.

slack discussion: https://calicousers.slack.com/archives/C0BCA117T/p1572438043292800

## Your Environment
- Calico 3.10
- Kubernetes 1.15.3
- kube-proxy 1.15.3 - ipvs mode
- `4.19.78-coreos`

**Comment by spikecurtis** [comment]
@ffilippopoulos can you run `ip link` on one of your nodes in a cluster where you are seeing this behavior?  We have a hypothesis that it has to do with the `kube-ipvs0` interface, but I'd like to confirm.  In particular, what is the state of that interface?  In my test cluster it is DOWN, but it looks like under some circumstances it could be set administratively up and be in state UNKNOWN.

**Comment by ffilippopoulos** [comment]
@spikecurtis you are correct, the state on `kube-ipvs0` is UNKNOWN:

```
6: kube-ipvs0: <BROADCAST,NOARP,UP,LOWER_UP> mtu 1500 qdisc noqueue state UNKNOWN mode DEFAULT group default
    link/ether 96:9b:15:5f:0b:72 brd ff:ff:ff:ff:ff:ff
```

do you think that implies faulty config on my kube proxy deployment? I see on their docs that:
> Make sure a dummy interface exists in the node, defaults to kube-ipvs0

but nothing about what configures the state there.

**Comment by spikecurtis** [comment]
@ffilippopoulos thanks for confirming.
