### ISSUE TITLE
calico/node is not ready: BIRD is not ready: BGP not established, on adding new slave to kubernetes cluster

### ISSUE THREAD

**Issue by deekshith-elear** [projectcalico/calico#2969]
Hi,
I have kubernetes setup of one master and one worker node, I want to add one more worker node to cluster. By adding it to cluster caliconode is staying at not ready state. if I do `ifconfig` it is showing tunl0 and no calico connections.  The node which i was trying to add to cluster is previously hosted kubernetes cluster in LXD containers having below network interface in `ifconfig` command
`
veth53f293d6 Link encap:Ethernet  HWaddr ea:1d:44:df:30:11  
          UP BROADCAST MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)
`
Is this `veth*` interfaces causes any issue to setup calico network.

**Comment by rafaelvanoni** [comment]
@deekshith-elear Just to clarify our understanding of your issue, are you asking if having a pre-existing veth on a node would cause problems to Calico? If we got that right, the answer would be no, it shouldn't cause any issues.

**Comment by tmjd** [comment]
Something to do would be to run `calicoctl node status` (you must run on a node), that should show you BGP status for that particular node. https://docs.projectcalico.org/v3.10/reference/calicoctl/node/status
