### ISSUE TITLE
Create checklists for each of our deploy types for validating installations

### ISSUE THREAD

**Issue by tomdee** [projectcalico/calico#297]
It would be great if users can run through a checklist to make sure they've got everything set up properly. 

This sits somewhere between our manual setup guides and troubleshooting docs.

e.g. for kubernetes, it would be great if we can point people to a checklist (e.g. when they're asking questions on slack) that says for example
* Have you got the policy controller running
* Have you got the CNI plugin installed
* Have you got the kubelet using the CNI plugin
* etc...

**Comment by djosborne** [comment]
@caseydavenport adding to v2.0.0. remove if you disagree.
