### ISSUE TITLE
Second prefix on a node cann't do aggregation of routes

### ISSUE THREAD

**Issue by rayroot** [projectcalico/calico#2984]
Because the number of pods on a node is more than 64 or 128, then need allocate a new prefix, but calico cann't do route aggregation for the second prefix, so other node receive some detailed routing（such as  /32）!  

node1 (192.168.100.33):   pod network(first-10.233.125.64/26, second-10.233.125.0/26 )
node2 (192.168.100.34):   pod network(10.233.85.192/26)

on the  node2 ： 
```
10.233.125.0 via 192.168.100.33 dev enp96s0f1 proto bird
10.233.125.22 via 192.168.100.33 dev enp96s0f1 proto bird
10.233.125.60 via 192.168.100.33 dev enp96s0f1 proto bird
10.233.125.63 via 192.168.100.33 dev enp96s0f1 proto bird
10.233.125.64/26 via 192.168.100.33 dev enp96s0f1 proto bird
```
only the first  prefix done route aggregation ,  and  the second prefix is the detail routes !  
 

## Expected Behavior

Maybe the  the second prefix shoud be done route aggregation 
such as on node2  : 
```
10.233.125.0/26 via 192.168.100.33 dev enp96s0f1 proto bird
10.233.125.64/26 via 192.168.100.33 dev enp96s0f1 proto bird
```

## Current Behavior

on the  node2 ： 
```
10.233.125.0 via 192.168.100.33 dev enp96s0f1 proto bird
10.233.125.22 via 192.168.100.33 dev enp96s0f1 proto bird
10.233.125.60 via 192.168.100.33 dev enp96s0f1 proto bird
10.233.125.63 via 192.168.100.33 dev enp96s0f1 proto bird
10.233.125.64/26 via 192.168.100.33 dev enp96s0f1 proto bird
```

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* k8s version: v1.14.1
* calico version:  v3.4.0
* OS：centos 7.6

**Comment by tmjd** [comment]
Is there any possibility that the block that isn't being aggregated is allocated to another node? It is possible for nodes to borrow IPs from other blocks when all the blocks for a cluster have been claimed.

You could try grabbing the calicoctl command from v3.8 and using `calicoctl ipam show --show-blocks` to see the allocated blocks, I'm not 100% sure that it will work with your cluster being v3.4.0 but you could try.

**Comment by rayroot** [comment]
> Is there any possibility that the block that isn't being aggregated is allocated to another node? It is possible for nodes to borrow IPs from other blocks when all the blocks for a cluster have been claimed.
> 
> You could try grabbing the calicoctl command from v3.8 and using `calicoctl ipam show --show-blocks` to see the allocated blocks, I'm not 100% sure that it will work with your cluster being v3.4.0 but you could try.



I  have checkout the output of   `calicoctl ipam show --show-blocks` ,  can't  find the prefix  second-10.233.125.0/26

**Comment by tmjd** [comment]
Can you update your cluster to a more recent version of Calico? There have been several updates in the code that handles route distribution/aggregation and this may have been fixed already.
