### ISSUE TITLE
POD cannot access outside

### ISSUE THREAD

**Issue by rainbowfhb** [projectcalico/calico#2990]
## Expected Behavior

if host machine restart, the pod are sheduled to other hosts, can new pod can access outside.

## Current Behavior

![image](https://user-images.githubusercontent.com/33643321/68741062-9d411200-0627-11ea-94c0-208a8dec076b.png)
Sometimes  the host machine restart，these pods on this machine are evicted and are scheduled to other hosts.  i can use kubectl get pod -o wide to see the new pod ip, but there is no route cali interface for this pod on the host, so it cannot access outside.
After i restart the calico-node use kubectl delete calico-node**** -n kube-system,  i can get the right route for the pod.

## Steps to Reproduce (for bugs)

i cannot reproduce the problem in test environment

## Your Environment

* Calico version
* Orchestrator version (e.g. kubernetes, mesos, rkt):
* Operating System and version:
* Link to your project (optional):
kubernetes 1.8.6
calico: calico-node:v3.0.1 calico-cni:v2.0.0 calico-kube-controllers:v2.0.0

**Comment by tmjd** [comment]
Have you reviewed the logs from calico-node, is there anything in there that suggests problems?
Also could you install calicoctl on a node with the problem and do `calicoctl node status`?

To be clear you are saying that the routes are not showing up on the new node that the pods are being rescheduled to or the original node that was restarted?

**Comment by caseydavenport** [comment]
@rainbowfhb Calico v3.0 is _very_ old. Please upgrade to a modern version of Calico (and Kubernetes - v1.8 is also quite old) and raise a new issue if you continue to see this behavior. Thanks.
