### ISSUE TITLE
Can not ping tunl0 on my openstack vm -----strange question

### ISSUE THREAD

**Issue by J2AZYZ** [projectcalico/calico#2991]
I install k8s on my openstack cloud. The openstack use vxlan and linuxbridge for network. 
Then I setup 3 vm on openstack and deploy single master k8s on it. Emmmm, the 3 vm are on two different physical machine and the k8s use calico which enable IPIP mode for network. Here come the strange question:
**vm ip**
vm3 192.168.1.79
vm2 192.168.1.68
vm1 192.168.1.62
**vm3 and vm1 on the same physical machine openstack-17,vm2 on physical machine openstack-19.**
route on vm3 (the physical machine is openstack-17)
![image](https://user-images.githubusercontent.com/50548655/68822511-11cd8c80-06cc-11ea-982c-601436a26d5d.png)
I can ping tunl0 on vm2
![image](https://user-images.githubusercontent.com/50548655/68822686-886a8a00-06cc-11ea-986c-ccbe3f5a8e63.png)
But I can not ping tunl0 on vm1
![image](https://user-images.githubusercontent.com/50548655/68822755-b3ed7480-06cc-11ea-9c9c-64ea76b4d4a7.png)
vm1 vm2 vm3 are all in the same Security Group on my openstack which allow all traffic.
vm1-3 can ping each other
![image](https://user-images.githubusercontent.com/50548655/68822949-4ee64e80-06cd-11ea-88f9-407f8dc0324e.png)
When I run calicoctl node status, it shows
![image](https://user-images.githubusercontent.com/50548655/68823192-febbbc00-06cd-11ea-8ccd-790d436d7086.png)

Can you tell me how this happen? This cost me two days to debug. Thanks very much.

**Comment by tmjd** [comment]
Are your screenshots from different nodes? Because they all look to have the same hostname. That could possibly be part of the problem. I'm thinking this because I noticed that each of the screen shots show the same tunl0 IP address and I believe those should be unique for each of the hosts.

**Comment by J2AZYZ** [comment]
@tmjd 
Thank you for your reply, i found the issue and solve it. The reason is Openstack Security Group stop the IPIP packet.
