### ISSUE TITLE
Kubernetes pod's service cannot reach via Service IP

### ISSUE THREAD

**Issue by joechan222** [projectcalico/calico#2997]
Hello, I am now encountering the following situation. I have expose the Kubernetes pod's service by using the NodePort, which is mapping the owf-svc port - 8081 to host port 30016. However, there are some problem in getting the repose packet.

**Node port setting
owf-svc                               NodePort    10.233.44.11    <none>        8081:30016/TCP                         6h34m**

# kcp get po owf-deployment-58b7bbdc94-xdfvg -o json | grep IP
        "hostIP": "172.20.84.172",
        "podIP": "10.233.97.137",

**ipvsadm setting
TCP  169.254.25.10:30016 rr
  -> 10.233.97.137:8081           Masq    1      0          0
TCP  172.17.0.1:30016 rr
  -> 10.233.97.137:8081           Masq    1      0          0
TCP  172.20.47.64:30016 rr
  -> 10.233.97.137:8081           Masq    1      0          0
TCP  172.20.57.202:30016 rr
  -> 10.233.97.137:8081           Masq    1      0          0
TCP  172.20.84.168:30016 rr
  -> 10.233.97.137:8081           Masq    1      0          0
TCP  10.233.95.0:30016 rr
  -> 10.233.97.137:8081           Masq    1      0          0
TCP  127.0.0.1:30016 rr
  -> 10.233.97.137:8081           Masq    1      0          0
**

## Expected Behavior

The IP addresses of whole cluster member is able to access to the service end point.

## Current Behavior

Only certain Nodes is able to get the HTTP content of the service end point.
![image](https://user-images.githubusercontent.com/57897390/69047044-42e3ef00-0a35-11ea-87fe-fbe53d961c71.png)

Failed to access 
![image](https://user-images.githubusercontent.com/57897390/69046947-0f08c980-0a35-11ea-818a-ccbc797d0801.png)

## Steps to Reproduce (for bugs)

1. Set the server and client in different nodes
2. Try to access the server via "curl" command
3. client timeout occurred

## Your Environment

* Calico version v3.7.3
* Orchestrator version (e.g. kubernetes, mesos, rkt): Kubernetes v1.15.3
* Docker version (client) 18.09.5
* Docker version (engine) 19.03.1
* Operating System and version: RHEL 7.6
* Link to your project (optional):

routing for all node:
Node1:
Destination     Gateway         Genmask         Flags   MSS Window  irtt Iface
0.0.0.0         172.20.84.10    0.0.0.0         UG        0 0          0 bond0
10.233.95.0     0.0.0.0         255.255.255.0   U         0 0          0 *
10.233.95.56    0.0.0.0         255.255.255.255 UH        0 0          0 cali065d00e8bcb
10.233.95.64    0.0.0.0         255.255.255.255 UH        0 0          0 cali1b80674e142
10.233.95.67    0.0.0.0         255.255.255.255 UH        0 0          0 cali13e26d90820
10.233.95.80    0.0.0.0         255.255.255.255 UH        0 0          0 cali866e25ece32
10.233.95.84    0.0.0.0         255.255.255.255 UH        0 0          0 cali2bac336e025
10.233.95.85    0.0.0.0         255.255.255.255 UH        0 0          0 calibe184722f8f
10.233.95.99    0.0.0.0         255.255.255.255 UH        0 0          0 calie6fb0797634
10.233.95.104   0.0.0.0         255.255.255.255 UH        0 0          0 cali15f6c8e4c2f
10.233.95.108   0.0.0.0         255.255.255.255 UH        0 0          0 cali6db21bed51a
10.233.95.110   0.0.0.0         255.255.255.255 UH        0 0          0 calie470ef228d5
10.233.95.114   0.0.0.0         255.255.255.255 UH        0 0          0 cali21ceae1fd9b
10.233.95.116   0.0.0.0         255.255.255.255 UH        0 0          0 cali805a0c46be7
10.233.95.117   0.0.0.0         255.255.255.255 UH        0 0          0 cali7f838916e9f
10.233.95.120   0.0.0.0         255.255.255.255 UH        0 0          0 cali05b32d07183
10.233.95.124   0.0.0.0         255.255.255.255 UH        0 0          0 cali230c46d86b1
10.233.95.126   0.0.0.0         255.255.255.255 UH        0 0          0 cali02fab63eef6
10.233.95.127   0.0.0.0         255.255.255.255 UH        0 0          0 cali85eee7e75fb
10.233.95.131   0.0.0.0         255.255.255.255 UH        0 0          0 cali09b9817af1e
10.233.95.135   0.0.0.0         255.255.255.255 UH        0 0          0 cali59fe9c6cc6d
10.233.95.140   0.0.0.0         255.255.255.255 UH        0 0          0 calic26a41ba515
10.233.95.146   0.0.0.0         255.255.255.255 UH        0 0          0 cali4de650e18d5
10.233.95.147   0.0.0.0         255.255.255.255 UH        0 0          0 calide5751592d6
10.233.95.149   0.0.0.0         255.255.255.255 UH        0 0          0 cali07c386d087f
10.233.95.151   0.0.0.0         255.255.255.255 UH        0 0          0 cali049d1034d14
10.233.95.153   0.0.0.0         255.255.255.255 UH        0 0          0 cali372ec00a62d
10.233.95.156   0.0.0.0         255.255.255.255 UH        0 0          0 cali8fe369bed3f
10.233.95.157   0.0.0.0         255.255.255.255 UH        0 0          0 cali736d4d24c54
10.233.95.166   0.0.0.0         255.255.255.255 UH        0 0          0 cali22cccf8a592
10.233.95.168   0.0.0.0         255.255.255.255 UH        0 0          0 calib091a19b830
10.233.95.169   0.0.0.0         255.255.255.255 UH        0 0          0 cali7d6e6e5c6e7
10.233.95.186   0.0.0.0         255.255.255.255 UH        0 0          0 cali938e8c9d98c
10.233.95.189   0.0.0.0         255.255.255.255 UH        0 0          0 cali623f95229e7
10.233.95.193   0.0.0.0         255.255.255.255 UH        0 0          0 cali273b84ec30a
10.233.95.198   0.0.0.0         255.255.255.255 UH        0 0          0 calie5bc06c86a4
10.233.95.199   0.0.0.0         255.255.255.255 UH        0 0          0 cali11464447b38
10.233.95.204   0.0.0.0         255.255.255.255 UH        0 0          0 calib4dbb5d8176
10.233.95.207   0.0.0.0         255.255.255.255 UH        0 0          0 califf5cbaed46f
10.233.95.210   0.0.0.0         255.255.255.255 UH        0 0          0 cali10a4908950c
10.233.95.214   0.0.0.0         255.255.255.255 UH        0 0          0 caliefee149fe8b
10.233.97.0     172.20.84.172   255.255.255.0   UG        0 0          0 tunl0
10.233.108.0    172.20.84.170   255.255.255.0   UG        0 0          0 tunl0
169.254.0.0     0.0.0.0         255.255.0.0     U         0 0          0 eno2
169.254.0.0     0.0.0.0         255.255.0.0     U         0 0          0 ens3f1
169.254.0.0     0.0.0.0         255.255.0.0     U         0 0          0 bond0
172.17.0.0      0.0.0.0         255.255.0.0     U         0 0          0 docker0
172.20.21.0     172.20.57.1     255.255.255.0   UG        0 0          0 eno2
172.20.47.0     0.0.0.0         255.255.255.0   U         0 0          0 ens3f1
172.20.57.0     0.0.0.0         255.255.255.0   U         0 0          0 eno2
172.20.84.0     0.0.0.0         255.255.255.0   U         0 0          0 bond0
172.20.171.128  172.20.47.1     255.255.255.192 UG        0 0          0 ens3f1
172.20.171.192  172.20.47.1     255.255.255.192 UG        0 0          0 ens3f1

Node2:
Destination     Gateway         Genmask         Flags   MSS Window  irtt Iface
0.0.0.0         172.20.84.10    0.0.0.0         UG        0 0          0 bond0
10.233.95.0     172.20.84.168   255.255.255.0   UG        0 0          0 tunl0
10.233.97.0     172.20.84.172   255.255.255.0   UG        0 0          0 tunl0
10.233.108.0    0.0.0.0         255.255.255.0   U         0 0          0 *
10.233.108.2    0.0.0.0         255.255.255.255 UH        0 0          0 calibfe35223a7a
10.233.108.13   0.0.0.0         255.255.255.255 UH        0 0          0 calieda1018460a
10.233.108.23   0.0.0.0         255.255.255.255 UH        0 0          0 cali3906d914eb2
10.233.108.26   0.0.0.0         255.255.255.255 UH        0 0          0 cali3048649ca00
10.233.108.27   0.0.0.0         255.255.255.255 UH        0 0          0 calid497009f49b
10.233.108.28   0.0.0.0         255.255.255.255 UH        0 0          0 cali4c29f8cb0e5
10.233.108.32   0.0.0.0         255.255.255.255 UH        0 0          0 cali35b1ae59bd4
10.233.108.37   0.0.0.0         255.255.255.255 UH        0 0          0 calic7ff607c7b0
10.233.108.40   0.0.0.0         255.255.255.255 UH        0 0          0 calie8e1e3e39dc
10.233.108.42   0.0.0.0         255.255.255.255 UH        0 0          0 cali46fe10e6101
10.233.108.46   0.0.0.0         255.255.255.255 UH        0 0          0 cali7211fc879bb
10.233.108.47   0.0.0.0         255.255.255.255 UH        0 0          0 calic1e55f73243
10.233.108.50   0.0.0.0         255.255.255.255 UH        0 0          0 calibaf60aa234e
10.233.108.51   0.0.0.0         255.255.255.255 UH        0 0          0 calib53acedb730
10.233.108.64   0.0.0.0         255.255.255.255 UH        0 0          0 calie12d7aacdee
10.233.108.65   0.0.0.0         255.255.255.255 UH        0 0          0 cali5081e3bf5e8
10.233.108.68   0.0.0.0         255.255.255.255 UH        0 0          0 cali59777d44aec
10.233.108.69   0.0.0.0         255.255.255.255 UH        0 0          0 cali0cbafed62c0
10.233.108.72   0.0.0.0         255.255.255.255 UH        0 0          0 cali323606db407
10.233.108.73   0.0.0.0         255.255.255.255 UH        0 0          0 cali3b4187c1c5a
10.233.108.78   0.0.0.0         255.255.255.255 UH        0 0          0 calib7e5a6805ec
10.233.108.81   0.0.0.0         255.255.255.255 UH        0 0          0 cali179a261396d
10.233.108.82   0.0.0.0         255.255.255.255 UH        0 0          0 cali65bfd11e4b5
10.233.108.85   0.0.0.0         255.255.255.255 UH        0 0          0 cali6f06f6469d4
10.233.108.86   0.0.0.0         255.255.255.255 UH        0 0          0 califacdcbd83b2
10.233.108.87   0.0.0.0         255.255.255.255 UH        0 0          0 cali406eccf6c0d
10.233.108.88   0.0.0.0         255.255.255.255 UH        0 0          0 cali0644b4aeaf0
169.254.0.0     0.0.0.0         255.255.0.0     U         0 0          0 eno2
169.254.0.0     0.0.0.0         255.255.0.0     U         0 0          0 ens3f1
169.254.0.0     0.0.0.0         255.255.0.0     U         0 0          0 bond0
172.17.0.0      0.0.0.0         255.255.0.0     U         0 0          0 docker0
172.20.21.0     172.20.57.1     255.255.255.0   UG        0 0          0 eno2
172.20.47.0     0.0.0.0         255.255.255.0   U         0 0          0 ens3f1
172.20.57.0     0.0.0.0         255.255.255.0   U         0 0          0 eno2
172.20.84.0     0.0.0.0         255.255.255.0   U         0 0          0 bond0
172.20.171.128  172.20.47.1     255.255.255.192 UG        0 0          0 ens3f1
172.20.171.192  172.20.47.1     255.255.255.192 UG        0 0          0 ens3f1

Node3:
0.0.0.0         172.20.84.10    0.0.0.0         UG        0 0          0 bond0
10.233.95.0     172.20.84.168   255.255.255.0   UG        0 0          0 tunl0
10.233.97.0     0.0.0.0         255.255.255.0   U         0 0          0 *
10.233.97.107   0.0.0.0         255.255.255.255 UH        0 0          0 cali03fb109e043
10.233.97.112   0.0.0.0         255.255.255.255 UH        0 0          0 calib34b9e4816e
10.233.97.115   0.0.0.0         255.255.255.255 UH        0 0          0 cali577a5455e4c
10.233.97.120   0.0.0.0         255.255.255.255 UH        0 0          0 calic46422174b9
10.233.97.133   0.0.0.0         255.255.255.255 UH        0 0          0 cali481e03abab1
10.233.97.135   0.0.0.0         255.255.255.255 UH        0 0          0 calif23a9962152
10.233.97.137   0.0.0.0         255.255.255.255 UH        0 0          0 cali6e58db3ca14
10.233.97.141   0.0.0.0         255.255.255.255 UH        0 0          0 calia523e532a8a
10.233.97.146   0.0.0.0         255.255.255.255 UH        0 0          0 calief4881741e0
10.233.108.0    172.20.84.170   255.255.255.0   UG        0 0          0 tunl0
169.254.0.0     0.0.0.0         255.255.0.0     U         0 0          0 eno2
169.254.0.0     0.0.0.0         255.255.0.0     U         0 0          0 ens3f1
169.254.0.0     0.0.0.0         255.255.0.0     U         0 0          0 bond0
172.17.0.0      0.0.0.0         255.255.0.0     U         0 0          0 docker0
172.20.21.0     172.20.57.1     255.255.255.0   UG        0 0          0 eno2
172.20.47.0     0.0.0.0         255.255.255.0   U         0 0          0 ens3f1
172.20.57.0     0.0.0.0         255.255.255.0   U         0 0          0 eno2
172.20.84.0     0.0.0.0         255.255.255.0   U         0 0          0 bond0
172.20.171.128  172.20.47.1     255.255.255.192 UG        0 0          0 ens3f1
172.20.171.192  172.20.47.1     255.255.255.192 UG        0 0          0 ens3f1

##attachment - client and server packet trace
Server side: 
#23 server receives the HTTP get request
#35 server response the HTTP get result

Client side:
#16701 Client side sent out the HTTP get request
#16719 Client side receive the HTTP continuation packet

[client_server.zip](https://github.com/projectcalico/calico/files/3858187/client_server.zip)

**Comment by tmjd** [comment]
I would expect to see your service IP in your ipvsadmin output. That should be handled by kube-proxy. Can you check that kube-proxy is healthy and its logs do not show any problems?

**Comment by joechan222** [comment]
> I would expect to see your service IP in your ipvsadmin output. That should be handled by kube-proxy. Can you check that kube-proxy is healthy and its logs do not show any problems?

I have also suspected that this case is due to the malfunction of kube-proxy, thus, i have manually restart all of kube-proxy pods but still the same result. There is no error log is found even though the kube-proxy is executed with “-v=4” flag.

Besides, i have also change the MTU of calico to 1480 (1500-20) but still no luck.

**Comment by tmjd** [comment]
You listed output from ipvsadmin and I assumed you have IPVS configured for kube-proxy, just to cover the bases you do have kube-proxy configured with IPVS, right?
I don't see how you would have stuff in ipvsadmin output but I'm wondering if we need to be looking at kube-proxy.

**Comment by tmjd** [comment]
Another cover the bases question:
Have you verified that pod-to-pod (between nodes) communication is working?

**Comment by joechan222** [comment]
> You listed output from ipvsadmin and I assumed you have IPVS configured for kube-proxy, just to cover the bases you do have kube-proxy configured with IPVS, right?
> I don't see how you would have stuff in ipvsadmin output but I'm wondering if we need to be looking at kube-proxy.

In this issue, I think it is most likely related to the low level network problem within Calico. It is because I have made the below tests.

**kube-proxy is running**
` kcs get pods
NAME                                       READY   STATUS    RESTARTS   AGE
calico-kube-controllers-759bb57d4c-knb7t   1/1     Running   3          35d
calico-node-4hmks                          1/1     Running   1          37h
calico-node-lj268                          1/1     Running   2          37h
calico-node-vcs5z                          1/1     Running   3          37h
coredns-74c9d4d795-2bxmp                   1/1     Running   6          35d
coredns-74c9d4d795-j95nc                   1/1     Running   3          35d
dns-autoscaler-7d95989447-t6tg4            1/1     Running   4          35d
kube-apiserver-hk2hp060                    1/1     Running   11         62d
kube-apiserver-hk2hp061                    1/1     Running   6          62d
kube-apiserver-hk2hp062                    1/1     Running   24         62d
kube-controller-manager-hk2hp060           1/1     Running   10         40d
kube-controller-manager-hk2hp061           1/1     Running   4          40d
kube-controller-manager-hk2hp062           1/1     Running   8          40d
kube-proxy-7vdzg                           1/1     Running   2          43h
kube-proxy-rkr5t                           1/1     Running   3          43h
kube-proxy-zpw94                           1/1     Running   3          43h
kube-scheduler-hk2hp060                    1/1     Running   13         62d
kube-scheduler-hk2hp061                    1/1     Running   6          62d
kube-scheduler-hk2hp062                    1/1     Running   10         62d
kubernetes-dashboard-7c547b4c64-n4mtl      1/1     Running   4          35d
nodelocaldns-f6qq4                         1/1     Running   13         71d
nodelocaldns-pjckx                         1/1     Running   8          71d
nodelocaldns-rt6wj                         1/1     Running   8          71d
tiller-deploy-8557598fbc-xddz5             1/1     Running   3          19d
`

**K8s cluster seems healthy**
`kc get cs
NAME                 STATUS    MESSAGE             ERROR
scheduler            Healthy   ok
controller-manager   Healthy   ok
etcd-0               Healthy   {"health":"true"}
etcd-1               Healthy   {"health":"true"}
etcd-2               Healthy   {"health":"true"}
`

**No error under kube-proxy log**
`$ kcs logs kube-proxy-7vdzg | grep -i error
$ kcs logs kube-proxy-rkr5t | grep -i error
$ kcs logs kube-proxy-zpw94 | grep -i error
$
`

Pods between different nodes is able to ping through
`bash-4.4# ping 10.233.97.149 -c1
PING 10.233.97.149 (10.233.97.149): 56 data bytes
64 bytes from 10.233.97.149: seq=0 ttl=62 time=0.234 ms

--- 10.233.97.149 ping statistics ---
1 packets transmitted, 1 packets received, 0% packet loss
round-trip min/avg/max = 0.234/0.234/0.234 ms
bash-4.4# traceroute 10.233.97.149
traceroute to 10.233.97.149 (10.233.97.149), 30 hops max, 46 byte packets
 1  172.20.57.202 (172.20.57.202)  0.006 ms  0.007 ms  0.003 ms
 2  10.233.97.0 (10.233.97.0)  0.148 ms  0.109 ms  0.045 ms
 3  10-233-97-149.owf-internal-svc.prod.svc.cluster.local (10.233.97.149)  0.123 ms  0.107 ms  0.069 ms
`

**Cannot access to the HTTP return between nodes even if it is inside pods(different nodes), however the port is open**
`bash-4.4# curl 10.233.97.149:8081/optimus/login -m3
curl: (28) Operation timed out after 3001 milliseconds with 0 bytes received
bash-4.4# nc -v 10.233.97.149 8081
10.233.97.149 (10.233.97.149:8081) open

`

**Comment by tmjd** [comment]
I want to check that your CIDRs are not overlapping as that can cause problems.
What are the different CIDRs you are using in your cluster?
* node CIDR
* pod CIDR
* service CIDR

Also it would be good to check that the IPs that Calico selected are what you would expect to be used for communication between your nodes.
Could you use calicoctl and do `calicoctl get nodes -o yaml` and include that output?
Also on each of the nodes could you collect and include:
* `calicoctl node status`
* `ip a`

Could you also use calicoctl to collect your IPPool configuration and include that?

**Comment by joechan222** [comment]
This issue is fixed by changing the MTU of tunl0 interface - https://www.ibm.com/support/pages/poor-ui-performances-and-many-packets-drop-tunl0-and-calico-interfaces-power-nodes

Thus, I will close this case. Thank you for your support.
