### ISSUE TITLE
calio 3.10.1 After the address pool is created, there is no host route.

### ISSUE THREAD

**Issue by yq513** [projectcalico/calico#3007]
calio 3.10.1 
After the address pool is created, there is no host route.

**Comment by jayunit100** [comment]
im curious wether we can reproduce this somehow w/ a bash script, i.e. the new kind one in the hack/development-environment

**Comment by tmjd** [comment]
@yq513 Could you please give more details about your setup and collect some information from your system?
It would be good to know how you've deployed, what version of k8s, the OS of the nodes, which manifest you used to install calico, any tweaks you've made, if you've created/modified additional IP pools.
It would probably be good to see `ip a` from a host, `ip r` output.
Could you also install calicoctl on a host and collect `calicoctl node status` output.
Also please look at the calico-node logs and possibly include them here.

**Comment by eddebc** [comment]
I had a similar issue but it was due to a conflict between the docker bridge network address (/etc/docker/daemon.json) and physical network one.
