### ISSUE TITLE
missing proper documentation for installing calico-driver directly during new openstack installation

### ISSUE THREAD

**Issue by vasilinamatov** [projectcalico/calico#3015]
Hey,

In the calico official website guide described that you need to install neutron and ML2 networking before implementing calico.
In the Before you begin section
https://docs.projectcalico.org/v3.10/getting-started/openstack/installation/ubuntu

But how you will remove the ML2 plugin without any issues in database?
As described in the Warning: After you configure the ML2 plug-in, removing values in the type_drivers option can lead to database inconsistency.
Here:
https://docs.openstack.org/neutron/train/install/controller-install-option1-ubuntu.html

It means that Calico have kind of limitation, in initial new openstack installation, to start up with core_plugin = calico driver from the beginning instead of core_plugin = ml2?

So the database population is incorrect in case of calico driver:
su -s /bin/sh -c “neutron-db-manage --config-file /etc/neutron/neutron.conf \
  --config-file /etc/neutron/plugins/ml2/ml2_conf.ini upgrade head” neutron

So it required to populate database without ml2?
su -s /bin/sh -c “neutron-db-manage --config-file /etc/neutron/neutron.conf upgrade head” neutron

And one more thing: the neutron-metadata-agent, neutron-dhcp-agent, ml2, linuxbridge installation also can be ignored?

Thanks,
Vasili

**Comment by tmjd** [comment]
@neiljerram could you take a look at this issue? Thanks

**Comment by neiljerram** [comment]
@vasilinamatov It's not clear to me if you're describing a hypothetical issue, or something that you've actually had trouble with.

For reference, and comparison if it's useful, here's what our internal script does when setting up a rig for testing (with Queens on Ubuntu):
```
# Install and configure Neutron - only creating neutron user if no proxy
create_mysql_user neutron
openstack user create --domain default --password ${ADMIN_PASSWORD} neutron
openstack role add --project service --user neutron admin
openstack service create --name neutron  --description "OpenStack Networking" network
openstack endpoint create --region ${REGION}  network public http://controller-${REGION}:9696
openstack endpoint create --region ${REGION}  network internal http://controller-${REGION}:9696
openstack endpoint create --region ${REGION}  network admin http://controller-${REGION}:9696

apt-get install -y neutron-server neutron-plugin-ml2 python-neutronclient neutron-metadata-agent

crudini --set /etc/neutron/neutron.conf DEFAULT debug true
crudini --set /etc/neutron/neutron.conf DEFAULT verbose true
crudini --set /etc/neutron/neutron.conf database connection mysql+pymysql://neutron:${ADMIN_PASSWORD}@controller-${REGION}/neutron

crudini --set /etc/neutron/neutron.conf DEFAULT transport_url rabbit://openstack:${ADMIN_PASSWORD}@controller-${REGION}
crudini --set /etc/neutron/neutron.conf DEFAULT rpc_backend rabbit
crudini --set /etc/neutron/neutron.conf DEFAULT rabbit_host controller-${REGION}
crudini --set /etc/neutron/neutron.conf DEFAULT rabbit_password ${ADMIN_PASSWORD}
crudini --set /etc/neutron/neutron.conf DEFAULT auth_strategy keystone
crudini --set /etc/neutron/neutron.conf keystone_authtoken auth_uri http://controller-${REGION}:5000
crudini --set /etc/neutron/neutron.conf keystone_authtoken auth_url http://controller-${REGION}:5000
crudini --set /etc/neutron/neutron.conf keystone_authtoken identity_uri http://controller-${REGION}:5000
crudini --set /etc/neutron/neutron.conf keystone_authtoken admin_tenant_name service
crudini --set /etc/neutron/neutron.conf keystone_authtoken admin_user neutron
crudini --set /etc/neutron/neutron.conf keystone_authtoken admin_password ${ADMIN_PASSWORD}
crudini --del /etc/neutron/neutron.conf keystone_authtoken auth_host
crudini --del /etc/neutron/neutron.conf keystone_authtoken auth_port
crudini --del /etc/neutron/neutron.conf keystone_authtoken auth_protocol
crudini --set /etc/neutron/neutron.conf keystone_authtoken auth_type password
crudini --set /etc/neutron/neutron.conf keystone_authtoken project_domain_name default
crudini --set /etc/neutron/neutron.conf keystone_authtoken user_domain_name default
crudini --set /etc/neutron/neutron.conf keystone_authtoken project_name service
crudini --set /etc/neutron/neutron.conf keystone_authtoken username neutron
crudini --set /etc/neutron/neutron.conf keystone_authtoken password ${ADMIN_PASSWORD}

crudini --set /etc/neutron/neutron.conf DEFAULT notify_nova_on_port_status_changes True
crudini --set /etc/neutron/neutron.conf DEFAULT notify_nova_on_port_data_changes True
crudini --set /etc/neutron/neutron.conf quotas quota_security_group 10000
crudini --set /etc/neutron/neutron.conf quotas quota_security_group_rule 10000
crudini --set /etc/neutron/neutron.conf quotas quota_network 20
crudini --set /etc/neutron/neutron.conf nova auth_url http://controller-${REGION}:5000
crudini --set /etc/neutron/neutron.conf nova auth_type password
crudini --set /etc/neutron/neutron.conf nova project_domain_name default
crudini --set /etc/neutron/neutron.conf nova user_domain_name default
crudini --set /etc/neutron/neutron.conf nova region_name ${REGION}
crudini --set /etc/neutron/neutron.conf nova project_name service
crudini --set /etc/neutron/neutron.conf nova username nova
crudini --set /etc/neutron/neutron.conf nova password ${ADMIN_PASSWORD}
crudini --set /etc/neutron/neutron.conf oslo_concurrency lock_path /var/lib/neutron/tmp

crudini --set /etc/neutron/plugins/ml2/ml2_conf.ini securitygroup enable_security_group True
crudini --set /etc/neutron/plugins/ml2/ml2_conf.ini securitygroup enable_ipset True
crudini --set /etc/neutron/plugins/ml2/ml2_conf.ini securitygroup firewall_driver neutron.agent.linux.iptables_firewall.OVSHybridIptablesFirewallDriver

crudini --set /etc/neutron/metadata_agent.ini DEFAULT nova_metadata_ip controller-${REGION}
crudini --set /etc/neutron/metadata_agent.ini DEFAULT metadata_proxy_shared_secret ${ADMIN_PASSWORD}

crudini --set /etc/nova/nova.conf DEFAULT network_api_class nova.network.neutronv2.api.API
crudini --set /etc/nova/nova.conf DEFAULT security_group_api neutron
crudini --del /etc/nova/nova.conf DEFAULT linuxnet_interface_driver
crudini --set /etc/nova/nova.conf DEFAULT firewall_driver nova.virt.firewall.NoopFirewallDriver
crudini --set /etc/nova/nova.conf neutron project_name service
crudini --set /etc/nova/nova.conf neutron username neutron
crudini --set /etc/nova/nova.conf neutron password ${ADMIN_PASSWORD}
crudini --del /etc/nova/nova.conf neutron service_metadata_proxy
crudini --del /etc/nova/nova.conf neutron metadata_proxy_shared_secret

crudini --set /etc/nova/nova.conf neutron url http://controller-${REGION}:9696
crudini --set /etc/nova/nova.conf neutron auth_url http://controller-${REGION}:5000
crudini --set /etc/nova/nova.conf neutron auth_type password
crudini --set /etc/nova/nova.conf neutron project_domain_name default
crudini --set /etc/nova/nova.conf neutron user_domain_name default
crudini --set /etc/nova/nova.conf neutron region_name ${REGION}

crudini --set /etc/neutron/neutron.conf DEFAULT core_plugin calico
crudini --del /etc/neutron/neutron.conf DEFAULT service_plugins
crudini --set /etc/neutron/neutron.conf DEFAULT allow_overlapping_ips True
crudini --set /etc/neutron/neutron.conf DEFAULT dhcp_agents_per_network 10000
crudini --set /etc/neutron/plugins/ml2/ml2_conf.ini ml2 type_drivers "local, flat"
crudini --set /etc/neutron/plugins/ml2/ml2_conf.ini ml2 tenant_network_types "local"
crudini --set /etc/neutron/plugins/ml2/ml2_conf.ini ml2 mechanism_drivers calico
crudini --set /etc/neutron/plugins/ml2/ml2_conf.ini ml2_type_flat flat_networks external
crudini --set /etc/neutron/neutron.conf calico etcd_host ${ETCD_IP:-127.0.0.1}

su -s /bin/sh -c "neutron-db-manage --config-file /etc/neutron/neutron.conf --config-file /etc/neutron/plugins/ml2/ml2_conf.ini upgrade head" neutron
```

Most of that is OpenStack install, not Calico, and it's really important to understand that OpenStack install is **hard**, and the Calico team has very deliberately decided **not** to be in the business of teaching people how to install OpenStack!

**Comment by vasilinamatov** [comment]
Neil, it's not about teaching people its about way of calico developer testing its code and if the documentation is correctly written. As an example in documentation said that you don't need to configure ml2 at all if you use core_pluging since liberty release. Thank you anyway for the update.

**Comment by neiljerram** [comment]
@vasilinamatov I'm still unclear what this issue is actually about.  The title says "missing proper documentation".  What is the documentation that you think we should add?

**Comment by vasilinamatov** [comment]
proper documentation means proper guide, maybe it require to add another guide for installing calico-driver directly without linux bridge or ovs pre installed..

let's say the step by step installation you have shared here is much clear then in the site

for example: 
apt-get install -y neutron-server neutron-plugin-ml2 python-neutronclient neutron-metadata-agent

I didn't see it on the guide..

**Comment by neiljerram** [comment]
@vasilinamatov 
> maybe it require to add another guide for installing calico-driver directly without linux bridge or ovs pre installed

That is exactly what the existing guides are for - i.e. without any other driver installed first.  (If you install another driver first, like linux bridge or OVS, the steps needed to clean that up are much harder, especially with OVS.)

> apt-get install -y neutron-server neutron-plugin-ml2 python-neutronclient neutron-metadata-agent
>
> I didn't see it on the guide..

That would be documenting how to install OpenStack, are we are very sure that we don't want to do that.

**Comment by vasilinamatov** [comment]
Why it require to install neutron-ml2 and neutron-metadata-agent if calico and neutron doesn’t use them while calico driver and nova-api-metadata used?

**Comment by neiljerram** [comment]
> Why it require to install neutron-ml2 and neutron-metadata-agent if calico and neutron doesn’t use them while calico driver and nova-api-metadata used?

Good question; in fact these steps may not be necessary.  Our internal OpenStack install scripts have evolved over a few years, and it's quite likely that they now include steps that we don't actually need.  In particular, we used to advise `core_plugin = ml2` and configuring Calico as an ML2 mechanism driver, but now we prefer `core_plugin = calico`.  That said, `neutron-plugin-ml2` may still be needed to install the ML2 plugin code, because the Calico plugin code inherits from that.

**Comment by vasilinamatov** [comment]
Will try to check your comment deeper soon: “may still be needed to install the ML2 plugin code”

**Comment by neiljerram** [comment]
Thanks @vasilinamatov .  If it is needed, perhaps it would be better to make that explicit by adding a dependency on neutron-plugin-ml2 in the Calico packaging.

**Comment by vasilinamatov** [comment]
According to my lab in general installing neutron-server on controller and nova-api-metadata on compute from openstack side is enough.

**Comment by vasilinamatov** [comment]
+ neutron-common on compute
