### ISSUE TITLE
Missing upgrade docs

### ISSUE THREAD

**Issue by lwr20** [projectcalico/calico#302]
- [ ] https://djosborne.github.io/calico/v2.0/getting-started/kubernetes/upgrade
- [ ] https://djosborne.github.io/calico/v2.0/getting-started/mesos/upgrade
- [ ] https://djosborne.github.io/calico/v2.0/getting-started/docker/upgrade
- [ ] https://djosborne.github.io/calico/v2.0/getting-started/rkt/upgrade
- [ ] https://djosborne.github.io/calico/v2.0/getting-started/bare-metal/upgrade

**Comment by djosborne** [comment]
I'm going to close this as a dupe of the broader issue: #219
