### ISSUE TITLE
Docs for hosted install don't explain how to configure pools

### ISSUE THREAD

**Issue by caseydavenport** [projectcalico/calico#303]

**Comment by djosborne** [comment]
+1. I think a Pools guide in the Usage section would be very useful. There's lots of places we could point to that, so keeping it generic is important

**Comment by caseydavenport** [comment]
@djosborne yeah we should have a guide for this and then we can point a bunch of stuff at it.

The hosted doc is a little bit different, because it's included in the manifest, so it needs to say "The manfiest configures a pool for you - you can modify it by editing calico.yaml in this spot"
