### ISSUE TITLE
why istio not working well with calico in openshift 3.11

### ISSUE THREAD

**Issue by zzzhy** [projectcalico/calico#3045]
I use istio to monitor all my services in k8s with calico environment.
The situtation is nothing captured into the prometheus and I got nothing edges displayed in the kiali component. And also the istio grafana dashboard (which grafana dashboard id is 7636)
## Expected Behavior
Display all the traffic diagrams.

## Current Behavior
nothing appears 
It seems istio hijack failed , although injected succeed.
## Your Environment

1. openshift 3.11
2. calico 3.8
3. istio 1.3.2

**Comment by tmjd** [comment]
Have you configured network policy that may be blocking traffic?

@spikecurtis do you have any idea what the issue may be here?

**Comment by spikecurtis** [comment]
@zzzhy can you explain why you think Calico has something to do with Istio not working? For example, was it all working fine before you installed Calico?

You should be able to check if Istio hijack is working by examining iptables within the pods. Are you using the Istio CNI plugin to configure the hijack, or the init container? I have a vague memory of some people hitting issues with CNI config ordering when combining the Istio CNI plugin with the Calico CNI plugin.

**Comment by zzzhy** [comment]
my develop env is on the minikube while production env is kubernetes with calico,  all run well in develop and not as the production.
when using the install option [`global.proxy.privileged` ](https://istio.io/docs/reference/config/installation-options/#global-options), all things become normal , althougn I doubt if it is the right solution .
terribly sorry for not really confirmed whether it involoed with calico.

**Comment by spikecurtis** [comment]
If running the Istio-proxy in privileged mode solves the problem it's very unlikely to have something to do with Calico.

The hijacking works by running the Istio proxy as a specific user (UID 1337 if I recall correctly).  I think that OpenShift by default assigns UIDs from a (per-namespace?) range, which might interfere with the proxy. Running as privileged might override that behavior and get it running as UID 1337.

@zzzhy if you need further help, I suggest you try the Istio forums at https://discuss.istio.io/ . Is it OK if we close this issue?

**Comment by zzzhy** [comment]
@spikecurtis thanks, just close it.
