### ISSUE TITLE
Allow setting BGP community on exported routes

### ISSUE THREAD

**Issue by kevclarx** [projectcalico/calico#3049]
## Expected Behavior
We currently see no way to set bgp communities on the exported routes in bird.  We need these communities for routing decisions upstream.  

## Current Behavior
Bird supports BGP communities in export filters however don't see a place to configure this in calico.

## Possible Solution
Way to configure bird export filters

## Steps to Reproduce (for bugs)
n/a

## Context
We need these routes tagged with bgp communities for routing decisions upstream.  

## Your Environment
rkt, kubernetes

**Comment by Cellebyte** [comment]
when will it be available in the CRD?

**Comment by caseydavenport** [comment]
This will be available in Calico v3.16.0
