### ISSUE TITLE
Reinstate Docker Swarm tutorial

### ISSUE THREAD

**Issue by gunjan5** [projectcalico/calico#305]
it's pretty out of date and doesn't work.
Look at this: `calico/node:v0.4.9 ` <-- from before the dinosaurs roam the 🌍 

http://docs.projectcalico.org/v2.0/getting-started/docker/tutorials/docker-swarm

**Comment by gunjan5** [comment]
Might also be worth adding a vagrant demo for this

**Comment by djosborne** [comment]
The swarm install doc has been removed by #285 .

**Comment by gunjan5** [comment]
@djosborne depends on the v2.0.1 timeline, but I'm hoping it should be a day worth of work (getting it working + updating the docs)

**Comment by caseydavenport** [comment]
This is blocked on actually supporting Docker 1.12.0+ in swarm mode.
