### ISSUE TITLE
Doc page on route tables and  blackholes

### ISSUE THREAD

**Issue by jayunit100** [projectcalico/calico#3055]
## Expected Behavior 

calico blackholes should be searchable on the doc site.

## Current behaviour

looking around for docs on calico blackholes yields several very long github issues which are a little confusing... i suggest making a page similar to https://jayunit100.blogspot.com/2019/12/iproutes-for-devices-and-blackholes-in.html

**Comment by tmjd** [comment]
I'm not sure we would want to add documentation on route tables and blackholes, at least in the user facing documentation, because those are implementation details and not something users should need to consider.
We could maybe add some information to the Felix repo with some info like that.

**Comment by caseydavenport** [comment]
Yeah, I'm not sure if this is right for the Calico docs. Blackhole routes are an implementation detail rather than a feature, if you see what I mean.
