### ISSUE TITLE
Missing iptables.log in AKS

### ISSUE THREAD

**Issue by johnnyhuy** [projectcalico/calico#3074]
I'm having trouble finding IPTables logs that are getting reported by Calico on AKS (Azure Kubernetes Service). I've tried using a [iptables-tailer](https://github.com/box/kube-iptables-tailer) but I realized that the `iptables.log` file is missing on the node that it mounts at `/var/log`.

## Expected Behavior

Be able to view Calico reporting packet messages at `/var/log/iptables.log` on the AKS node.

## Current Behavior

`iptables.log` file is missing on the node.

## Context

I'm currently having trouble identifying network connectivity issues between pods since we don't have a good place to find logs to track packets coming from Calico.

We've managed to get logs from `syslog` and `messages` on the node when we applied a `action: Log` network policy to all traffic. However, we cannot identify where the packets were getting denied or pods affected.

Please correct if I'm wrong or point me to the right place to find good debugging tricks on pod connectivity with Calico. 😅

## Your Environment

Calico version: 3.5 (enabled via Azure Resource Manager)
Azure Kubernetes Service on Kubernetes 1.14.4

**Comment by ivanting95** [comment]
+1 also have the same issue

**Comment by song-jiang** [comment]
Not sure why iptables logs got missing on AKS node. Generally I will take the following steps to identify kubernetes network issues. 
- isolate and reproduce the issue as simple as possible. Pod A can not access pod B via cluster ip for instance.

**Comment by tmjd** [comment]
iptables logs should be present if the host system iptables is configured to write them. So I think this would be a host system configuration issue, not something Calico can control. I think you would need to bring this up with whoever is in control of your host's OS configuration.
