### ISSUE TITLE
There is no pod2daemon-flexvol docker image in elease-v3.10.2.tgz

### ISSUE THREAD

**Issue by dmanbu** [projectcalico/calico#3075]
I tried to import the image required by calico through release-v3.10.2/images, but this error was prompted in K8s:
Back-off pulling image "calico/pod2daemon-flexvol:v3.10.2"

Is it possible to put pod2daemon-flexvol.tar into a release package?
thank you

**Comment by lmm** [comment]
@dmanbu, thank you for reporting this issue. It's been fixed and the upcoming v3.11 release package will include the missing Docker images.
