### ISSUE TITLE
ip conflict in tunl0

### ISSUE THREAD

**Issue by zong400** [projectcalico/calico#3097]
We added two new nodes to k8s cluster,but found that tunl0 ip is the same.

## Expected Behavior
every nodes has one and only ip

## Current Behavior
<img width="582" alt="node1-docker-ip" src="https://user-images.githubusercontent.com/10556584/71609555-797c6000-2bc4-11ea-9033-4b1a158b2390.png">

<img width="587" alt="node8-docker-ip" src="https://user-images.githubusercontent.com/10556584/71609556-7da87d80-2bc4-11ea-8b49-46dd56d80175.png">

## Your Environment

* Calico version  3.1.3
* Orchestrator version (e.g. kubernetes, mesos, rkt):  k8s 1.13.5
* Operating System and version:  ubuntu18.04 have this problem and ubuntu16.04 not

**Comment by halfcrazy** [comment]
Check your node's hostname and `/var/lib/calico/nodename`, you may forget to change your hostname or set a unique node name.

**Comment by zong400** [comment]
@halfcrazy I just found /var/lib/calico/nodename is different from hostname in node8

![image](https://user-images.githubusercontent.com/10556584/71612220-ddf5ea00-2bd9-11ea-989d-b174b15d4e2e.png)

**Comment by halfcrazy** [comment]
Delete `/var/lib/calico/nodename` from your host node8, and recreate calico-node pod on this host.

**Comment by zong400** [comment]
@halfcrazy it work. thanks
