### ISSUE TITLE
how access pod in intranet node by pod in extranet master based on kubernetes ?

### ISSUE THREAD

**Issue by QiusHosens** [projectcalico/calico#3101]
use kubernetes, i want to access pod in intranet node by pod in extranet master. 
for example, master's ip is 192.168.10.239, node2's ip is 192.168.0.12, it's my virtual machine, the node can access to master, how to access node by master ? 
calico support? thanks.

**Comment by tmjd** [comment]
Are your calico-node pods healthy?
Where are your nodes and master running (VirtualBox, GCP, AWS)? If Vagrant/VirtualBox you may need to configure the IP auto detection, see [here](https://docs.projectcalico.org/v3.11/reference/node/configuration#ip-autodetection-methods).
How did you install Calico on your cluster? Did you do any additional configuration to the install?
You might need to configure the default IPPool as the defaults overlap with your master and node IPs which could easily cause problems.
