### ISSUE TITLE
Calico for OpenStack needs Python 3 support in order to run with Stein release and later

### ISSUE THREAD

**Issue by vasilinamatov** [projectcalico/calico#3125]
Calico neutron plugin is missing python3 support.
Since Openstack Stein release (which already moved to python3) calico plugin is unavailable and not supported to work with neutron.

Reference: https://bugs.launchpad.net/pypi/+bug/1856485

Best,
Vasili

**Comment by neiljerram** [comment]
Thanks @vasilinamatov for tracking this here.  I'll move the error log down here:
> ERROR neutron.manager [-] Plugin 'calico' not found

and update the title to reflect the underlying Python 3 issue.

**Comment by vasilinamatov** [comment]
The following error is an issue so I added it under issue subject.
Now you changed the subject to what should be done in order to fix the issue. So not sure that you suggested subject is really convenient. Anyway, its upon you how to track the issues.
Thanks anyway.
Best,
Vasili

**Comment by vasilinamatov** [comment]
For search engines its great to have this error available.

ERROR neutron.manager [-] Plugin 'calico' not found

**Comment by neiljerram** [comment]
@vasilinamatov I believe this issue has now been addressed by https://github.com/projectcalico/networking-calico/pull/25.  Please let me know of any further issues!
