### ISSUE TITLE
Calico Container on CrashLoopBackOff 

### ISSUE THREAD

**Issue by Goeldeepesh** [projectcalico/calico#3138]
I was trying to Setup a Multi-Master Kubernetes setup with external etcd 3 nodes cluster on bare metal REHL 7.2.  Etcd cluster setup got successful. After running the kubeadm init with --pod-cidr 192.168.0.0/16, i had applied calico 3.8 YAML. Containers were very much up and running. But when I'm adding a second master or data node the calico containers which were spun on them are getting in crash back loop. 

**Kube version: 1.17**

Note: I have updated calico.yaml with below, but still the same error.
- name: IP_AUTODETECTION_METHOD
   value: "interface=eth.*"

**Describe POD**

`kubectl describe pod calico-node-hr65k -n kube-system
Name:                 calico-node-hr65k
Namespace:            kube-system
Priority:             2000001000
Priority Class Name:  system-node-critical
Node:                 n4tenl-depa0601/10.5.30.104
Start Time:           Wed, 15 Jan 2020 18:31:12 +0530
Labels:               controller-revision-hash=89867b6d7
                      k8s-app=calico-node
                      pod-template-generation=1
Annotations:          scheduler.alpha.kubernetes.io/critical-pod:
Status:               Running
IP:                   10.5.30.104
IPs:
  IP:           10.5.30.104
Controlled By:  DaemonSet/calico-node
Init Containers:
  upgrade-ipam:
    Container ID:  docker://8252f021ff312541ff939bc744e7233c65e7fbf587920b48448746fb54b1184c
    Image:         calico/cni:v3.8.4
    Image ID:      docker-pullable://calico/cni@sha256:040aafdeef49322a1d79f2ec438852af00df7c04d4354fec1acf3e41abb17d12
    Port:          <none>
    Host Port:     <none>
    Command:
      /opt/cni/bin/calico-ipam
      -upgrade
    State:          Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Wed, 15 Jan 2020 18:31:13 +0530
      Finished:     Wed, 15 Jan 2020 18:31:13 +0530
    Ready:          True
    Restart Count:  0
    Environment:
      KUBERNETES_NODE_NAME:        (v1:spec.nodeName)
      CALICO_NETWORKING_BACKEND:  <set to the key 'calico_backend' of config map 'calico-config'>  Optional: false
    Mounts:
      /host/opt/cni/bin from cni-bin-dir (rw)
      /var/lib/cni/networks from host-local-net-dir (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from calico-node-token-gtp7p (ro)
  install-cni:
    Container ID:  docker://93af302c5ab7a1078347b4b00dfdf793dfd78d028053c55cd0c7a89342e81256
    Image:         calico/cni:v3.8.4
    Image ID:      docker-pullable://calico/cni@sha256:040aafdeef49322a1d79f2ec438852af00df7c04d4354fec1acf3e41abb17d12
    Port:          <none>
    Host Port:     <none>
    Command:
      /install-cni.sh
    State:          Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Wed, 15 Jan 2020 18:31:14 +0530
      Finished:     Wed, 15 Jan 2020 18:31:14 +0530
    Ready:          True
    Restart Count:  0
    Environment:
      CNI_CONF_NAME:         10-calico.conflist
      CNI_NETWORK_CONFIG:    <set to the key 'cni_network_config' of config map 'calico-config'>  Optional: false
      KUBERNETES_NODE_NAME:   (v1:spec.nodeName)
      CNI_MTU:               <set to the key 'veth_mtu' of config map 'calico-config'>  Optional: false
      SLEEP:                 false
    Mounts:
      /host/etc/cni/net.d from cni-net-dir (rw)
      /host/opt/cni/bin from cni-bin-dir (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from calico-node-token-gtp7p (ro)
  flexvol-driver:
    Container ID:   docker://b16b00fa4712f1aee8901484ac2ddd5a31aaae305b988258815b6f731b92ebc7
    Image:          calico/pod2daemon-flexvol:v3.8.4
    Image ID:       docker-pullable://calico/pod2daemon-flexvol@sha256:6dd45f10b54e5d3c9c226504460b12ff3d2a232754c0aa86e8f02d92cf673d94
    Port:           <none>
    Host Port:      <none>
    State:          Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Wed, 15 Jan 2020 18:31:15 +0530
      Finished:     Wed, 15 Jan 2020 18:31:15 +0530
    Ready:          True
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /host/driver from flexvol-driver-host (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from calico-node-token-gtp7p (ro)
Containers:
  calico-node:
    Container ID:   docker://2db21392f6fafae9fe847b91ea29f83e09b9a3eaeb6d48f9b7232f158dd2f50a
    Image:          calico/node:v3.8.4
    Image ID:       docker-pullable://calico/node@sha256:ae2a196f15724fe994e41d8992ed01ad7df871eb5529d55e4e7c55ab0d7ef791
    Port:           <none>
    Host Port:      <none>
    State:          Running
      Started:      Thu, 16 Jan 2020 16:22:23 +0530
    Last State:     Terminated
      Reason:       Error
      Exit Code:    137
      Started:      Thu, 16 Jan 2020 16:16:11 +0530
      Finished:     Thu, 16 Jan 2020 16:17:20 +0530
    Ready:          False
    Restart Count:  358
    Requests:
      cpu:      250m
    Liveness:   http-get http://localhost:9099/liveness delay=10s timeout=1s period=10s #success=1 #failure=6
    Readiness:  exec [/bin/calico-node -bird-ready -felix-ready] delay=0s timeout=1s period=10s #success=1 #failure=3
    Environment:
      DATASTORE_TYPE:                     kubernetes
      WAIT_FOR_DATASTORE:                 true
      NODENAME:                            (v1:spec.nodeName)
      CALICO_NETWORKING_BACKEND:          <set to the key 'calico_backend' of config map 'calico-config'>  Optional: false
      CLUSTER_TYPE:                       k8s,bgp
      IP:                                 autodetect
      IP_AUTODETECTION_METHOD:            interface=ens192
      CALICO_IPV4POOL_IPIP:               Always
      FELIX_IPINIPMTU:                    <set to the key 'veth_mtu' of config map 'calico-config'>  Optional: false
      CALICO_IPV4POOL_CIDR:               192.168.0.0/16
      CALICO_DISABLE_FILE_LOGGING:        true
      FELIX_DEFAULTENDPOINTTOHOSTACTION:  ACCEPT
      FELIX_IPV6SUPPORT:                  false
      FELIX_LOGSEVERITYSCREEN:            info
      FELIX_HEALTHENABLED:                true
    Mounts:
      /lib/modules from lib-modules (ro)
      /run/xtables.lock from xtables-lock (rw)
      /var/lib/calico from var-lib-calico (rw)
      /var/run/calico from var-run-calico (rw)
      /var/run/nodeagent from policysync (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from calico-node-token-gtp7p (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  lib-modules:
    Type:          HostPath (bare host directory volume)
    Path:          /lib/modules
    HostPathType:
  var-run-calico:
    Type:          HostPath (bare host directory volume)
    Path:          /var/run/calico
    HostPathType:
  var-lib-calico:
    Type:          HostPath (bare host directory volume)
    Path:          /var/lib/calico
    HostPathType:
  xtables-lock:
    Type:          HostPath (bare host directory volume)
    Path:          /run/xtables.lock
    HostPathType:  FileOrCreate
  cni-bin-dir:
    Type:          HostPath (bare host directory volume)
    Path:          /opt/cni/bin
    HostPathType:
  cni-net-dir:
    Type:          HostPath (bare host directory volume)
    Path:          /etc/cni/net.d
    HostPathType:
  host-local-net-dir:
    Type:          HostPath (bare host directory volume)
    Path:          /var/lib/cni/networks
    HostPathType:
  policysync:
    Type:          HostPath (bare host directory volume)
    Path:          /var/run/nodeagent
    HostPathType:  DirectoryOrCreate
  flexvol-driver-host:
    Type:          HostPath (bare host directory volume)
    Path:          /usr/libexec/kubernetes/kubelet-plugins/volume/exec/nodeagent~uds
    HostPathType:  DirectoryOrCreate
  calico-node-token-gtp7p:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  calico-node-token-gtp7p
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  beta.kubernetes.io/os=linux
Tolerations:     :NoSchedule
                 :NoExecute
                 CriticalAddonsOnly
                 node.kubernetes.io/disk-pressure:NoSchedule
                 node.kubernetes.io/memory-pressure:NoSchedule
                 node.kubernetes.io/network-unavailable:NoSchedule
                 node.kubernetes.io/not-ready:NoExecute
                 node.kubernetes.io/pid-pressure:NoSchedule
                 node.kubernetes.io/unreachable:NoExecute
                 node.kubernetes.io/unschedulable:NoSchedule
Events:
  Type     Reason     Age                     From                      Message
  ----     ------     ----                    ----                      -------
  Warning  Unhealthy  6m58s (x2430 over 21h)  kubelet, n4tenl-depa0601  Readiness probe failed: calico/node is not ready: felix is not ready: Get http://localhost:9099/readiness: dial tcp 127.0.0.1:9099: connect: connection refused
  Warning  BackOff    118s (x4349 over 21h)   kubelet, n4tenl-depa0601  Back-off restarting failed container`

**Conatiner LOGS**

kubectl logs calico-node-hr65k  -n kube-system -c calico-node
2020-01-16 10:53:31.539 [INFO][8] startup.go 256: Early log level set to info
2020-01-16 10:53:31.540 [INFO][8] startup.go 272: Using NODENAME environment for node name
2020-01-16 10:53:31.540 [INFO][8] startup.go 284: Determined node name: n4tenl-depa0601
2020-01-16 10:53:31.541 [INFO][8] k8s.go 228: Using Calico IPAM
2020-01-16 10:53:31.542 [INFO][8] startup.go 316: Checking datastore connection
2020-01-16 10:54:01.543 [INFO][8] startup.go 331: Hit error connecting to datastore - retry error=Get https://10.96.0.1:443/api/v1/nodes/foo: dial tcp 10.96.0.1:443: i/o timeout
2020-01-16 10:54:32.543 [INFO][8] startup.go 331: Hit error connecting to datastore - retry error=Get https://10.96.0.1:443/api/v1/nodes/foo: dial tcp 10.96.0.1:443: i/o timeout

I have read almost every similar issue raised in GITHUB but still not able to proceed further.

**Comment by Goeldeepesh** [comment]
anyone can please help me out here.

**Comment by zzmg** [comment]
hello i met same issue, did you solve it？
