### ISSUE TITLE
Suggested improvement in documentation

### ISSUE THREAD

**Issue by cexposit** [projectcalico/calico#3143]
I have a bare-metal cluster composed of 3 nodes and Kubernetes:
```
kubectl get nodes -o wide
NAME    STATUS   ROLES    AGE   VERSION   INTERNAL-IP    EXTERNAL-IP   OS-IMAGE             KERNEL-VERSION      CONTAINER-RUNTIME
node0   Ready    master   14m   v1.17.1   10.6.128.7     <none>        Ubuntu 18.04.3 LTS   4.15.0-72-generic   docker://19.3.4
node1   Ready    <none>   12m   v1.17.1   10.6.129.228   <none>        Ubuntu 18.04.3 LTS   4.15.0-72-generic   docker://19.3.4
node2   Ready    <none>   12m   v1.17.1   10.6.129.47    <none>        Ubuntu 18.04.3 LTS   4.15.0-72-generic   docker://19.3.4
```
The master node has 2 network interfaces (one with the public IP and the other with 10.6.128.7). The internal network interface is used to communicate the nodes whereas the public IP is used to provide access from Internet.

And I have installed Calico following the indications of the web:
```
curl https://docs.projectcalico.org/v3.11/manifests/calico.yaml -O
kubectl apply -f calico.yaml
```

## Expected Behavior

The expected behavior is that all the PODs of Calico will be running without problems after workers are joined.

## Current Behavior

The PODs are not working after workers join the cluster: 
```
kubectl get all -n kube-system
NAME                                           READY   STATUS    RESTARTS   AGE
pod/calico-kube-controllers-5b644bc49c-rbxbk   1/1     Running   0          15m
pod/calico-node-btrzp                          0/1     Running   0          14m
pod/calico-node-dmspn                          0/1     Running   0          14m
pod/calico-node-vcvpj                          0/1     Running   0          15m
pod/coredns-6955765f44-4p6hn                   1/1     Running   0          15m
pod/coredns-6955765f44-sf9nw                   1/1     Running   0          15m
pod/etcd-node0                                 1/1     Running   0          15m
pod/kube-apiserver-node0                       1/1     Running   0          15m
pod/kube-controller-manager-node0              1/1     Running   0          15m
pod/kube-proxy-h7t5f                           1/1     Running   0          14m
pod/kube-proxy-k9slf                           1/1     Running   0          15m
pod/kube-proxy-rsw7p                           1/1     Running   0          14m
pod/kube-scheduler-node0                       1/1     Running   0          15m
NAME               TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)                  AGE
service/kube-dns   ClusterIP   10.96.0.10   <none>        53/UDP,53/TCP,9153/TCP   15m
NAME                         DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR                 AGE
daemonset.apps/calico-node   3         3         0       3            0           beta.kubernetes.io/os=linux   15m
```

## Steps to Reproduce (for bugs)

1. Initializing a bare-metal cluster with a master containing 2 network interfaces.
2. `curl https://docs.projectcalico.org/v3.11/manifests/calico.yaml -O`
3. `kubectl apply -f calico.yaml`
4. Join workers
5. `kubectl get pods -n kube-system`

## Context

I suggest to indicate in the documentation in such a way that when several network interfaces are available in the master node, you should
1. identifying the default gateway of your nodes (`ip route | grep default`)
2. modifying `calico.yaml` by including
```
env:
     - name: IP_AUTODETECTION_METHOD
       value: can-reach=<DEFAULT-GATEWAY>
```
before applying `calico.yaml`.

## Your Environment

* Calico version
* Orchestrator version (e.g. kubernetes, mesos, rkt):
* Operating System and version:
* Link to your project (optional):

**Comment by tmjd** [comment]
Thank you for the suggestion. I don't know that we would want to add this as part of the general setup that every user needs to do. Perhaps we could add a note about adding this additional configuration when using multiple interfaces.
I would be happy to review a PR for a change like that if you wanted to submit one.
