### ISSUE TITLE
join a node  to the cluster while it has private ip address and a public ip address mapped to the private

### ISSUE THREAD

**Issue by ehsanrocket** [projectcalico/calico#3163]
I have a machine that has a private ip address , and a public ip address that is mapped to the private address.
when I execute the command : 
```
kubeadm join 1.2.3.4:6443  --token xxx     --discovery-token-ca-cert-hash yyyyy
```
the calico-node's log shows that it tries to connect to the kubelet at https://10.56.128.19:10250/ that is a private ip address. 
how can I configure a calico node to use the public ip address instead of private one. ?

**Comment by rafaelvanoni** [comment]
@ehsanrocket calico-node connects to a service (to connect to the kubernetes API), is that IP the address of a k8s service? calico-node doesn't connect to kubelet directly. Could you give us a little background on what you're trying to do?

**Comment by ehsanrocket** [comment]
Hi @rafaelvanoni  
our nodes are behind NAT, so we can access (ssh) the nodes with a public IP and then it forward the traffic to the private node IP.
so when I run a join command , the outpout of the ```calicoctl nodes status``` command in Master Node, shows that it tries connect to the private IP address of the Nodes that is not routable. 
I used the can-reach:8.8.8.8 method for AUTO DETECTION Discovery.

**Comment by caseydavenport** [comment]
@ehsanrocket you can configure the IP address that Calico uses through the IP_AUTODETECTION_METHOD option. 

See here for more information: https://docs.projectcalico.org/networking/node#understanding-caliconode-ip-autodetection-logic

**Comment by ehsanrocket** [comment]
thank you @caseydavenport

**Comment by ehsanrocket** [comment]
As I understand  we can also run
```kubectl edit node <NodeName> ```
and then change the ```projectcalico.org/IPv4Address: ``` section

**Comment by zz940522** [comment]
Hello @ehsanrocket ,how you solve this issue
