### ISSUE TITLE
BIRD BGP propagates gateway id

### ISSUE THREAD

**Issue by DockToFuture** [projectcalico/calico#3194]
We ran a kubernetes cluster v1.16.6 with calico as cni plugin and bird as backend.
The calico pods run as expected as long as we only have the default docker networking bridge on all nodes.
When we create a new docker network bridge on one of the kubernetes nodes, for example with `docker network create dummy`, bird takes the newly created network gateway id instead of the node ip and distributes it as bgp neighbor. 
As consequence of this will the calico node fail to run.

Our configuration for calico is:

```
  calico_backend: bird
  cni_network_config: |-
    {
      "name": "k8s-pod-network",
      "cniVersion": "0.3.1",
      "plugins": [
        {
          "type": "calico",
          "log_level": "error",
          "datastore_type": "kubernetes",
          "nodename": "__KUBERNETES_NODE_NAME__",
          "mtu": __CNI_MTU__,
          "ipam": {
            "type": "host-local",
            "subnet": "usePodCidr"
          },
          "policy": {
            "type": "k8s"
          },
          "kubernetes": {
            "kubeconfig": "__KUBECONFIG_FILEPATH__"
          }
        },
        {
          "type": "portmap",
          "snat": true,
          "capabilities": {"portMappings": true}
        },
        {
          "type": "bandwidth",
          "capabilities": {"bandwidth": true}
        }
      ]
    }
  typha_service_name: calico-typha
  veth_mtu: "1440"
```

## Expected Behavior
I expect calico/bird to propagate the node ip instead of the gateway id of the newly created docker network as long as I didn't specify it somewhere explicitly.

## Current Behavior
Calico/bird  propagates gateway id of docker dummy network.

## Steps to Reproduce (for bugs)

1. Setup a kubernetes cluster with calico as cni plugin.
2. Exec into a calico node container and create a docker network bridge with `docker network create dummy`
The gateway id can then be seen via `docker network inspect dummy`.
3. The calico node which contains the dummy network will no longer come up.

## Your Environment

* Calico version v3.8.2
* Kubernetes: v1.16.6

/cc @zanetworker

**Comment by lwr20** [comment]
As described here: https://docs.projectcalico.org/reference/node/configuration#ip-autodetection-methods you need to give Calico a hint as to which IP it should be using.
