### ISSUE TITLE
why each host must have a default IPv6 route

### ISSUE THREAD

**Issue by etavene** [projectcalico/calico#3215]
## Summary
 I have an ipv6-only cluster running on a single node. Without default gw the calico-kube-controller is always in container creating state. 

 ## Current Behavior
 sudo kubectl get svc
             kubernetes   ClusterIP   fd20::1      <none>        443/TCP   43m
 sudo kubectl get nodes -o wide 
          ubuntu161   Ready    master   62m   v1.17.2   2001:db8:0:f101::4   <none>        Ubuntu 16.04.2 
         LTS   4.4.0-62-generic   docker://18.9.7

 The communication to my cluster IP from my node is  failing ( connection refused)
   curl -6 https://[fd20::1]:443
  
 But if I add dummy default route in the system as shown below, everything is working as expected 
 
 sudo /sbin/route -A inet6 add default gw 2001:0db8:0:f101::1
 
 The calico document for "enbaling ipv6 support"   says, each host must have a default IPv6 route. Can some one make me understand, why we require default gw ? 
 
 
- ## Your Environment
- <!--- Include as many relevant details about the environment you experienced the bug in 
  Calico version : v3.10.2
  Orchestrator version (e.g. kubernetes, mesos, rkt): v 1.17.2
  Operating System and version: ubuntu 16.04
  Link to your project (optional):

**Comment by rafaelvanoni** [comment]
@etavene Is the dummy gw pointing at an actual route or just "some" IP? I'm not sure this is a calico dependency or a lower level/Linux requirement for IPv6 networking. It may have something to do with the fact that cluster IPs are NAT'ed.

**Comment by etavene** [comment]
@rafaelvanoni  Thanks for your reply. It is just some IP. 

The reason for asking above question is, the calico documentation for ipv6 support (https://docs.projectcalico.org/v3.10/networking/ipv6)  says that each host must have default ipv6 route. Would like to know why calico expects to have default route ?

Each Kubernetes host must have an IPv6 address that is reachable from the other hosts.
Each host must have the sysctl setting net.ipv6.conf.all.forwarding setting it to 1. This ensures both Kubernetes service traffic and Calico traffic is forwarded appropriately.
****Each host must have a default IPv6 route.****

**Comment by caseydavenport** [comment]
@etavene I believe this is because it is a requirement for the host to do neighbor discovery proxying for the pod. If the host doesn't think it can route the traffic, it won't proxy neighbor discovery requests.

**Comment by huxiaoliang** [comment]
I found same issue in my pure ipv6 cluster, but Dualstack don't have such issue, error as below:
```
  Normal   Scheduled               52m                    default-scheduler        Successfully assigned kube-system/calico-kube-controllers-65f8bc95db-gd7lv to vm-0-67-ubuntu
  Warning  FailedCreatePodSandBox  52m                    kubelet, vm-0-67-ubuntu  Failed to create pod sandbox: rpc error: code = Unknown desc = [failed to set up sandbox container "0aa422d50bfd0039862b7888e9ceb2f89a6dc85c7bf020775a4c85ce63bbacc7" network for pod "calico-kube-controllers-65f8bc95db-gd7lv": networkPlugin cni failed to set up pod "calico-kube-controllers-65f8bc95db-gd7lv_kube-system" network: error getting ClusterInformation: Get https://[fd00:2::1:0:0:1]:443/apis/crd.projectcalico.org/v1/clusterinformations/default: dial tcp [fd00:2::1:0:0:1]:443: connect: connection refused, failed to clean up sandbox container "0aa422d50bfd0039862b7888e9ceb2f89a6dc85c7bf020775a4c85ce63bbacc7" network for pod "calico-kube-controllers-65f8bc95db-gd7lv": networkPlugin cni failed to teardown pod "calico-kube-controllers-65f8bc95db-gd7lv_kube-system" network: error getting ClusterInformation: Get https://[fd00:2::1:0:0:1]:443/apis/crd.projectcalico.org/v1/clusterinformations/default: dial tcp [fd00:2::1:0:0:1]:443: connect: connection refused]
  Normal   SandboxChanged   

root@VM-0-67-ubuntu:~# curl -6 https://[fd00:2::1:0:0:1]:443
curl: (7) Failed to connect to fd00:2::1:0:0:1 port 443: Connection refused
root@VM-0-67-ubuntu:~# 

``
