### ISSUE TITLE
Using VXLAN with CrossSubnet, Felix doesn't push all routes to dataplane

### ISSUE THREAD

**Issue by tommasopozzetti** [projectcalico/calico#3231]
I opened this issue on project Felix as projectcalico/felix#2214 but I am reopening here as it seems most discussions happen here.

## Expected Behavior
When a felix instance is restarted and VXLAN is enabled in CrossSubnet mode, all routes to all other nodes within the configured IP pools should be pushed to the dataplane so that they get added to the routing table.

## Current Behavior
When a felix instance is restarted and VXLAN is enabled in CrossSubnet mode, only a subset of routes is pushed to the dataplane based on the arrival order of update messages.

## Possible Solution
From debugging this problem, it seems that the cause is in the order of received update messages. We use Typha, which is periodically pushing out update messages with all information on any given node.
The VXLAN resolver populates its information about all nodes based on the received messages and decides when routes are ready to be pushed to the dataplane. Unfortunately, if CrossSubnet is enabled, a route can be considered ready only when information is available about both destination node and source node (the node running the computation).
This is the case because of the added check to verify whether the source and destination node are in the same subnet.
However, routes are checked and pushed to dataplane only upon receiving updates about the destination node. Therefore the following bug can arise (let's suppose a configuration with two nodes N1 and N2, N1 managing IPs in range C1 and N2 managing IPs in C2):
1. Felix instance is started on N1
2. Felix receives an update about N2
3. VXLAN resolver populates all info about N2
4. VXLAN resolver checks whether route R1-2 with destination C2 and gateway N2 is ready
5. VXLAN resolver fails the check as it does not have any info about N1 and therefore cannot check whether N2 and N1 are in the same subnet
6. VXLAN resolver declares route R1-2 as not ready and keeps it pending
7. Felix receives an update about N1
8. VXLAN resolver populates all info about N1 (**here route R1-2 becomes ready but no tests are done on pending routes towards N2 so it is not pushed to the dataplane**)
9. Felix receives another update about N2
10. VXLAN resolver skips it as all info for N2 are already up to date (and even if pending routes were pushed, R1-2 would result ready and therefore not set among the pending ones)
11. Unless other changes happen to N2 configs that make felix reset all routes towards it, R1-2 will never get pushed

Notice that this bug would not have been present if the update about N1 had been received before the update about N2, so it is non deterministic based on the order of received messages.

As a workaround I added the following code in VXLAN resolver in function OnResourceUpdate after [this line](https://github.com/projectcalico/felix/blob/d51cbfa8c774f090a0b8dff3b31e1d4640f13488/calc/vxlan_resolver.go#L184)
```golang
if _, ok := c.nodeNameToNode[c.hostname]; !ok && nodeName != c.hostname {
   logCxt.Debugf("skipping OnResourceUpdate waiting for %s", c.hostname)
   return
}
```
which forces VXLAN resolver to discard any resource update message until it receives the one about its own host, so that route readiness logic is again sound. This seems to be working fine for now.
The right solution, however, would probably include checking for pending routes also when receiving resource update messages about the running host itself, so that routes that become ready at that point can be pushed to the dataplane.

## Your Environment
* `calico/node` container version: 3.11.1
* Which orchestrator are you using: Kubernetes
* Orchestrator version: 1.16.6

**Comment by caseydavenport** [comment]
@tommasopozzetti thanks for raising this issue with detailed analysis, and also sorry for the delay in response. 

If I understand correctly, I think one way of explaining this problem is that we determine the `pendingSet` of routes [here](https://github.com/projectcalico/felix/blob/d51cbfa8c774f090a0b8dff3b31e1d4640f13488/calc/vxlan_resolver.go#L223) _after_ populating the node update into the map [here](https://github.com/projectcalico/felix/blob/d51cbfa8c774f090a0b8dff3b31e1d4640f13488/calc/vxlan_resolver.go#L185). This results in the desired route showing up in the `sentSet` rather than the `pendingSet`, since the VXLAN resolver thinks that given its current internal state the route should have already been sent. 

If that's right, then one fix might just be calculating the `c.routeSets()` prior to populating the node update into `nodeNameToNode`, so that when we kick pending routes, it includes the correct pending set. Does that match up with your investigation?

**Comment by tommasopozzetti** [comment]
@caseydavenport thank you for taking a look at this.
I agree with your explanation. If pending routes are calculated also before populating info in `nodeNameToNode` and they are kicked after that, it should take care of those routes that become ready during that operation, that is those routes that needed the source node info which can be added when populating `nodeNameToNode`.
Doing that should fix this bug.
