### ISSUE TITLE
release-v3.12.0.tgz does not contain kubernetes manifests

### ISSUE THREAD

**Issue by tghartland** [projectcalico/calico#3234]

**Comment by tmjd** [comment]
@lmm I believe we still expect our artifact to contain the manifests. Do you know why we've lost that?

**Comment by lmm** [comment]
@tmjd we missed this with the docs machinery update. In the past we used to have the site built in dir `vX.Y` in the root of the repo. The make target that copies over manifests from the site dir failed because the path `_site/v3.12` doesn't exist.

Thanks for reporting this @tghartland !

**Comment by lmm** [comment]
@tghartland the release artifact has been updated with the manifests now. I'm going to close this now, thanks again 🙂
