### ISSUE TITLE
unable to ping kuberenetes services are not responding after some time after start

### ISSUE THREAD

**Issue by deekshith-elear** [projectcalico/calico#3243]
Hi,
I was using calico as pod networks in my Kubernetes setup. I'm facing below issues
- I'm unable to ping pod IP from nodes other than it's running node
- when I ping once from the node it is running then it is working from other nodes for a short time period <1min
I'm using Kubernetes 1.17.1 and calico configuration v3.11 and CALICO_IPV4POOL_CIDR = 10.112.0.0/12

Is there any way to resolve this? or it's a known bug.

**Comment by caseydavenport** [comment]
Sounds like this could be an ARP issue or similar. Do your hosts have a default route on them? Without one, that might cause pod ARP requests to fail.
