### ISSUE TITLE
Calico blackhole route and IP from this subnet on the other host.

### ISSUE THREAD

**Issue by azalio** [projectcalico/calico#3246]
We have some ippools.
```
# kubectl get ippools
NAME                     AGE
default-ipv4-ippool      252d
default-ipv4-ippool-10   252d
default-ipv4-ippool-11   252d
default-ipv4-ippool-12   252d
default-ipv4-ippool-13   252d
default-ipv4-ippool-14   252d
default-ipv4-ippool-2    252d
default-ipv4-ippool-3    252d
default-ipv4-ippool-4    252d
default-ipv4-ippool-5    252d
default-ipv4-ippool-6    218d
default-ipv4-ippool-7    252d
default-ipv4-ippool-8    252d
default-ipv4-ippool-9    252d
```

We have added about hundred servers onprem.
IP blocks divided by `/26` was ended, because too much nodes(servers).

And we got result. For example:
node1 had network `10.192.79.128/26`
some IPs from this network was free.
Calico assigns these IPs to node2.

It total:
node1 had route
```
blackhole 10.192.79.128/26 proto bird
```
node2 had not any blackhole route, but had IPs from `10.192.79.128/26`.

Pods from node1 can't communicate with pod on node2, because of blackhole.

## Expected Behavior
If calico can't allocate subnet from IPPools, calico-node will fail.

## Current Behavior
Calico allocates IPs from busy block and pods can't communicate.

## Possible Solution
In our case we have added new IPPool, deleted wrong nodes and start them again.

## Your Environment

* Calico version
`v3.7.2`
* Orchestrator version (e.g. kubernetes, mesos, rkt):
`kubernetes v1.14.8`
* Operating System and version:
`Centos7`

**Comment by caseydavenport** [comment]
I would expect `/32` routes to exist for IPs borrowed on node 2, which would then take precedence over the blackhole route.

@azalio can you confirm whether or not you have /32 routes on node1 for the addresses borrowed by node2?

**Comment by azalio** [comment]
@caseydavenport 
I can't confirm it now because I can't a possibility to break the production cluster again, but in two-four weeks I will set up a new cluster and will try to reproduce it.

**Comment by halfcrazy** [comment]
Have you enabled node-to-node mesh or using a router-reflector? I think the /32 route from other nodes are learnt from other nodes with bgp exchange.

**Comment by vsxen** [comment]
same question.
I think strictaffinity must be false.
https://github.com/projectcalico/libcalico-go/pull/1220
ping @gianlucam76 

@halfcrazy also see there https://www.ichenfu.com/2019/09/21/calico-ip-allocation-problems/   (chinese)

**Comment by halfcrazy** [comment]
@vsxen You may configure an in cluster router reflector. 
If you are using fixed IP ipam annotation, pods assigned to a node without the corresponding block is usually.
https://www.projectcalico.org/how-does-in-cluster-route-reflection-work/

**Comment by gianlucam76** [comment]
@vsxen If you don't want IP addresses to be borrowed from blocks assigned to different node, setting strict affinity will achieve that.
When node needs to assign an ip address to a POD:
1) if any block was previously assigned to that node, the node checks if there is any un-used IP address in such block(s);
2) if there are no un-used IP address in its block(s), node asks for a new IP address block (size == blockSize). If a block can be carved out, it gets assigned to the node. And the node assigns IP address from that block.
3) If such a block cannot be carved out, if strictAffinity is set, then POD remains without IP address. Otherwise node tries to borrow an IP address from another block assigned to a different node (which will lead to /32 routes being advertised).

**Comment by vsxen** [comment]
```
+------------------------------------------------------------------------+
|                                                                        |
|                                                                        |
|                                                                        |
|                                                                        |
|                                                                        |
|    +---------------------------+      +----------------------------+   |
|    |                      +-----------------+borrow 192.168.2.2    |   |
|    |                      v    |      |                            |   |
|    |     192.168.2.0/26 block  |      |    192.168.2.64/26 block   |   |
|    |                           |      |                            |   |
|    |                           |      |                            |   |
|    |                           |      |                            |   |
|    |       10.1.1.1 Host       |      |      10.1.1.2 Host         |   |
|    +---------------------------+      +----------------------------+   |
|                                                                        |
|                                                                        |
+------------------------------------------------------------------------+

```
enable node mesh everything is ok.


But with RR 

| src  | 192.168.2.2 |
| ------------- | ------------- |
| 10.1.1.1  | no |
| 10.1.1.2|ok |
|10.1.1.3 other node|ok|
|other pod in 10.1.1.1   |no|


I know, Thank you. @gianlucam76 @halfcrazy

**Comment by halfcrazy** [comment]
> ```
> +------------------------------------------------------------------------+
> |                                                                        |
> |                                                                        |
> |                                                                        |
> |                                                                        |
> |                                                                        |
> |    +---------------------------+      +----------------------------+   |
> |    |                      +-----------------+borrow 192.168.2.2    |   |
> |    |                      v    |      |                            |   |
> |    |     192.168.2.0/26 block  |      |    192.168.2.64/26 block   |   |
> |    |                           |      |                            |   |
> |    |                           |      |                            |   |
> |    |                           |      |                            |   |
> |    |       10.1.1.1 Host       |      |      10.1.1.2 Host         |   |
> |    +---------------------------+      +----------------------------+   |
> |                                                                        |
> |                                                                        |
> +------------------------------------------------------------------------+
> ```
> 
> enable node mesh everything is ok.
> 
> But with RR
> 
> src	192.168.2.2
> 10.1.1.1	no
> 10.1.1.2	ok
> 10.1.1.3 other node	ok
> other pod in 10.1.1.1	no
> I know, Thank you. @gianlucam76 @halfcrazy

How you set up a rr? If using an in cluster rr you should use ibgp(same as number) i think.

**Comment by vsxen** [comment]
I use gobgp as rr connnect k8s node and core switch.
https://github.com/osrg/gobgp
ex:
```
# calicoctl patch bgpconfiguration default -p '{"spec": {"nodeToNodeMeshEnabled": “false”}}'
apiVersion: projectcalico.org/v3
kind: BGPPeer
metadata:
  name: rr1
spec:
  peerIP: 192.20.30.40
  asNumber: 65001
---
apiVersion: projectcalico.org/v3
kind: BGPPeer
metadata:
  name: rr2
spec:
  peerIP: 192.20.30.41
  asNumber: 65001
```

**Comment by halfcrazy** [comment]
> I use gobgp as rr connnect k8s node and core switch.
> https://github.com/osrg/gobgp
> ex:
> 
> ```
> # calicoctl patch bgpconfiguration default -p '{"spec": {"nodeToNodeMeshEnabled": “false”}}'
> apiVersion: projectcalico.org/v3
> kind: BGPPeer
> metadata:
>   name: rr1
> spec:
>   peerIP: 192.20.30.40
>   asNumber: 65001
> ---
> apiVersion: projectcalico.org/v3
> kind: BGPPeer
> metadata:
>   name: rr2
> spec:
>   peerIP: 192.20.30.41
>   asNumber: 65001
> ```

ref https://docs.projectcalico.org/reference/resources/bgpconfig
default as number is: 64512

**Comment by matthewdupre** [comment]
Strict affinity is definitely needed if you're using downward default BGP routing (or in general any set up where the nodes expect to be able to communicate with pods elsewhere via the default route to a peered switch instead of routes advertised from other nodes).

**Comment by gautvenk** [comment]
Hi @caseydavenport, I ran into this issue on a baremetal setup which follows `downward default` BGP routing model. Is it possible to mention `strict affinity` configuration requirement in the docs especially to avoid IP borrowing in `downward default` deployments?
