### ISSUE TITLE
IPv6 pod connectivity across hosts in different subnets

### ISSUE THREAD

**Issue by svallala** [projectcalico/calico#3254]
In IPv4, pod connectivity works seamlessly even though they are in different subnets because the packets are sent IPinIP.

In IPv6, how does this work? I have a cluster with hosts in different v6 subnets and the Pods can't connect to each other. I could not find much information about the traffic flow in v6 mode. Can someone please help me understand or point me to relevant documentation?

I am using Calico 3.11.1
Kubernetes: 1.16.3

Thanks

**Comment by uablrek** [comment]
AFAIK there is no network-overlay for Calico for ipv6. This is needed if you have multiple subnets unless your routers can route all POD addresses. Example;

* POD A in subnet 1000::/64 with ip fd00::1
* POD B in subnet 1100::/64 with ip fd00::2
* Send packet A -> B src/dst  fd00::1 fd00::2
* Calico will have a route for fd00::2 somewhere in 1100::/64, say 1100::1
* Packet goes to an external router connecting the subnets, still src/dst  fd00::1 fd00::2
* **PROBLEM**; The external roouter has no idea that packets to fd00::2 shall be routed to 1100::1

For ipv4 you have a tunel or vxlan network overlay so packets between the subnets will have node addresses of which the external router is aware. The POD addresses are hidden inside the encapsulated packets.

**Comment by lwr20** [comment]
This issue covers adding an overlay for IPv6: https://github.com/projectcalico/libcalico-go/issues/996

I'm going to close this.
