### ISSUE TITLE
calico in kube-proxy ipvs mode don't access kubernetes svc.

### ISSUE THREAD

**Issue by gitbeyond** [projectcalico/calico#3258]
## Current Behavior

```bash
[root@k8s-1 ~]# kubectl version --short
Client Version: v1.16.6-beta.0
Server Version: v1.16.6-beta.0
[root@k8s-1 ~]# kubectl get svc kubernetes
NAME         TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)   AGE
kubernetes   ClusterIP   10.254.0.1   <none>        443/TCP   274d
[root@k8s-1 ~]# kubectl get endpoints kubernetes
NAME         ENDPOINTS                                                  AGE
kubernetes   10.111.32.239:6443,10.111.32.241:6443,10.111.32.242:6443   274d

[root@k8s-6 kubernetes]# ipvsadm -S -n |grep 10.254.0.1
-A -t 10.254.0.1:443 -s rr
-a -t 10.254.0.1:443 -r 10.111.32.239:6443 -m -w 1
-a -t 10.254.0.1:443 -r 10.111.32.241:6443 -m -w 1
-a -t 10.254.0.1:443 -r 10.111.32.242:6443 -m -w 1

[root@k8s-4 ~]# ipvsadm -Lnc
IPVS connection entries
pro expire state       source             virtual            destination
TCP 00:51  SYN_RECV    10.254.0.1:37954   10.254.0.1:443     10.111.32.241:6443
```

when i set kube-proxy use ipvs mode, i cannot access kubernetes svc on every node。 
 It stays in SYN_RECV  state.

## Possible Solution

when I delete the following route entry, I can access it normally。
```bash
[root@k8s-6 ~]# ip rou del local 10.254.0.1 dev kube-ipvs0 proto kernel scope host src 10.254.0.1
# 10.20.235.60 is ip of tunl0 
[root@k8s-6 ~]# ip rou add local 10.254.0.1 dev kube-ipvs0 proto kernel scope host src 10.20.235.60
```

## Your Environment

* Calico version : 3.12.0 (3.11.1)
* Orchestrator version (e.g. kubernetes, mesos, rkt):  kubernetes-v1.16.5(v1.15.8, v1.14.10)
* Operating System and version: CentOs-7.7
* kube-proxy mode: ipvs

**Comment by caseydavenport** [comment]
> ip rou del local 10.254.0.1 dev kube-ipvs0 proto kernel scope host src 10.254.0.1

Interesting. I'm not sure where that route comes from - I don't think it's something that Calico manages. @song-jiang do you know?

**Comment by song-jiang** [comment]
Calico won't program routes to `kube-ipvs0` interface. This route got `proto kernel` so it could be auto generated by kernel. 

AFAIU, for proto kernel, it is a route added automatically when you assign an address to an interface which is not /32. However, kube-proxy should not program any non /32 routes. 

@gitbeyond Could you show us the log of `ip a`?  Do you know if there is any other process on your system which would monitor and create routes?

**Comment by gitbeyond** [comment]
Thank you for your reply. I recently found that this problem was caused by some other software. After stopping those software, it returned to normal. Thanks twice. It's my own fault.
