### ISSUE TITLE
Packets to external IP marked as martian on a node that is running the service

### ISSUE THREAD

**Issue by benceszikora** [projectcalico/calico#3259]
I have a service with `externalTrafficPolicy: Local` and an `externalIP` defined. I am trying to do a simple http request to the external IP of the service.

## Expected Behavior
The external IP of the service is reachable.

## Current Behavior
Trying to query the external IP of a service hangs if the query is from a node that runs a pod that belongs to the service.
I added tracing in iptables for the externalIP of the service I am testing with:
```
iptables -t raw -I PREROUTING 1   -d 7.129.245.6/32 -j TRACE
```
Then I just try to do `curl 7.129.245.6` on a node that runs the service. This shows that the packet gets to mangle PREROUTING and it seems lost afterwards:
```
Feb 19 04:49:10 kernel: TRACE: raw:PREROUTING:policy:5 IN=enp65s0f0 OUT= MAC=24:8a:07:ab:9e:28:cc:16:7e:fe:ad:01:08:00 SRC=7.129.0.130 DST=7.129.245.6 LEN=60 TOS=0x00 PREC=0x00 TTL=63 ID=47746 DF PROTO=TCP SPT=43670 DPT=80 SEQ=2960830465 ACK=0 WINDOW=29200 RES=0x00 SYN URGP=0 OPT (020405B40402080A040C0A83000000000103030A)
Feb 19 04:49:10 kernel: TRACE: mangle:PREROUTING:rule:1 IN=enp65s0f0 OUT= MAC=24:8a:07:ab:9e:28:cc:16:7e:fe:ad:01:08:00 SRC=7.129.0.130 DST=7.129.245.6 LEN=60 TOS=0x00 PREC=0x00 TTL=63 ID=47746 DF PROTO=TCP SPT=43670 DPT=80 SEQ=2960830465 ACK=0 WINDOW=29200 RES=0x00 SYN URGP=0 OPT (020405B40402080A040C0A83000000000103030A)
Feb 19 04:49:10 kernel: TRACE: mangle:cali-PREROUTING:rule:3 IN=enp65s0f0 OUT= MAC=24:8a:07:ab:9e:28:cc:16:7e:fe:ad:01:08:00 SRC=7.129.0.130 DST=7.129.245.6 LEN=60 TOS=0x00 PREC=0x00 TTL=63 ID=47746 DF PROTO=TCP SPT=43670 DPT=80 SEQ=2960830465 ACK=0 WINDOW=29200 RES=0x00 SYN URGP=0 OPT (020405B40402080A040C0A83000000000103030A)
Feb 19 04:49:10 kernel: TRACE: mangle:cali-from-host-endpoint:return:1 IN=enp65s0f0 OUT= MAC=24:8a:07:ab:9e:28:cc:16:7e:fe:ad:01:08:00 SRC=7.129.0.130 DST=7.129.245.6 LEN=60 TOS=0x00 PREC=0x00 TTL=63 ID=47746 DF PROTO=TCP SPT=43670 DPT=80 SEQ=2960830465 ACK=0 WINDOW=29200 RES=0x00 SYN URGP=0 OPT (020405B40402080A040C0A83000000000103030A)
Feb 19 04:49:10 kernel: TRACE: mangle:cali-PREROUTING:return:5 IN=enp65s0f0 OUT= MAC=24:8a:07:ab:9e:28:cc:16:7e:fe:ad:01:08:00 SRC=7.129.0.130 DST=7.129.245.6 LEN=60 TOS=0x00 PREC=0x00 TTL=63 ID=47746 DF PROTO=TCP SPT=43670 DPT=80 SEQ=2960830465 ACK=0 WINDOW=29200 RES=0x00 SYN URGP=0 OPT (020405B40402080A040C0A83000000000103030A)
Feb 19 04:49:10 kernel: TRACE: mangle:PREROUTING:policy:2 IN=enp65s0f0 OUT= MAC=24:8a:07:ab:9e:28:cc:16:7e:fe:ad:01:08:00 SRC=7.129.0.130 DST=7.129.245.6 LEN=60 TOS=0x00 PREC=0x00 TTL=63 ID=47746 DF PROTO=TCP SPT=43670 DPT=80 SEQ=2960830465 ACK=0 WINDOW=29200 RES=0x00 SYN URGP=0 OPT (020405B40402080A040C0A83000000000103030A)
```
After enabling `sys.net.ipv4.conf.all.log_martians` I found that it gets dropped after the above traces:
```
Feb 19 04:49:10 kernel: IPv4: martian source 7.129.245.6 from 7.129.0.130, on dev enp65s0f0
Feb 19 04:49:10 kernel: ll header: 00000000: 24 8a 07 ab 9e 28 cc 16 7e fe ad 01 08 00        $....(..~.....
```
Any ideas why this might be happening?

## Context
Routes for context
```
$ ip r
default via 7.129.0.129 dev enp65s0f0
7.129.0.128/27 dev enp65s0f0 proto kernel scope link src 7.129.0.130
7.129.4.0/22 dev eno1 proto kernel scope link src 7.129.4.19
blackhole 7.129.17.0/24 proto bird
7.129.17.231 dev calibc56ba63daf scope link
7.129.17.232 dev calib12ccf003ae scope link
7.129.17.233 dev cali0e4b17fc7a3 scope link
7.129.17.234 dev calie2df1318714 scope link
7.129.17.236 dev cali29beaebbaa5 scope link
7.129.17.237 dev calieffebc3fc95 scope link
7.129.17.238 dev cali1034546d288 scope link
7.129.17.242 dev cali6cf8ed3a5ec scope link
```

## Your Environment
* Calico version: `v3.12.0` 
* Orchestrator version (e.g. kubernetes, mesos, rkt): `kubernetes 1.16.2`
* Operating System and version: `RHEL 7.5`

**Comment by spikecurtis** [comment]
Hey, a couple questions for you: what is 7.129.245.6 in your network?

You are trying to reach 7.129.24.29, but it appears from your logs that this is getting DNAT'ed to 7.129.245.6.  However, you don't have a route to 7.129.245.6 via any `cali` interface, so it doesn't appear to be a pod running the service locally.

**Comment by benceszikora** [comment]
@spikecurtis Sorry I have mixed things up while preparing this report. `7.129.245.6` is the `externalIP` of the service. `7.129.24.29` is the `clusterIP`, I was also testing with that, that's why I pasted the wrong this. Apologies for the confusion. I have now updated the issue to reflect that.

**Comment by spikecurtis** [comment]
This is sounding like a kube-proxy issue---what kube-proxy mode are you running? (e.g. iptables, ipvs, etc.)

**Comment by spikecurtis** [comment]
@benceszikora any updates here? Is this still a problem for you?
