### ISSUE TITLE
[Kubernetes] Route management for Pod IPs causes internal cluster packets to leak to the external network

### ISSUE THREAD

**Issue by juliohm1978** [projectcalico/calico#3269]
We're running a standard Kubernetes cluster installed using Kubespray, recently upgraded to k8s 1.17.3 and using Calico 3.7.3 as network plugin.

Our firewall team noticed a strange behavior, and asked us for explanations as to why packets from inside the k8s cluster are reaching the firewall that connects our cluster to the other corporate networks.

Given the nature of how k8s and calico work, I'd expect to never see network packets from inside the cluster to reach out to a firewall at the edge of its network. But we can easily gather reports showing otherwise.

We managed to isolate and correlate the packets captured by the firewall to events in the calico Pod logs. Shortly before packets are sent to the firewall, we can see log messages similar to this one:

```
2020-02-21 03:55:16.191 [INFO][48] route_table.go 561: Syncing routes: removing old route. dest=192.168.218.190/32 ifaceName="calif1bc3ecb0a0" ipVersion=0x4 routeProblems=[]string{"unexpected route"}
```

As far as I can tell, calico is just reacting to Pods being restarted or terminated in the cluster, as expected. It removes the stale Pod IP from the nodes' routing tables.

Safe to say, this is a common every day scenario. Applications deploy randomly throughout the day. New pods are created and the old ones die away.

The unexpected behavior is that, for a very short period of time, until routes are settled and users are redirected to new pods, network packets from clients are still trying to reach the stale pod IPs. At this point, having no specific route to them, the kernel does what it does best. It sends them away to the default gateway on the primary network interface.

Throughout the day, we see small occasional groups of packets from the calico network reaching the edge firewall. Timestamps are always related to those same calico log messages.

I could be wrong, so I'm happy to stand corrected on what I just said.

My question here is: **Should I expect packets to leak from the k8s network at all? Is this normal?** 

At this point, this is a non-issue for us. We are mostly curious to understand and diagnose this with more details. But I can see how this can be a more serious concern in terms of security or privacy for critical environments.

**Comment by spikecurtis** [comment]
Can you tell me whether you are using an overlay encapsulation like VXLAN or IP in IP? I believe kubespray installs IP in IP as default, but would be helpful to know whether you've changed this.

It would also be helpful to know if are using Calico IPAM, or some other IPAM plugin.

In general, I think your analysis is correct, and this is just related to the fact that routing doesn't instantaneously converge across the cluster, causing packets to get sent to the default router. Depending on the configuration, we add summary routes to the kernel to help mitigate misdirected packets, but we definitely don't have a design goal that all such races are eliminated.

**Comment by juliohm1978** [comment]
We are using whatever defaults Kubespray applied for Calico. So yes, IP in IP and calico's IPAM.

This is what a routing table in a k8s node typically looks like for us.

![image](https://user-images.githubusercontent.com/4145456/75550755-54b03780-5a11-11ea-9cd5-eeb5bbbf6772.png)

So, when one of those 10.233.x.x routes gets removed, packets that happen to be in transit before new routes to new pods are picked up might end up in the default gateway (ie: 172.25.134.1 in this case).

Like I said, we are mostly curious. So I'm closing this for now satisfied with this context, leaving it on the record for anyone else. It can be reopened in case it becomes a real issue.

Thank you!
