### ISSUE TITLE
Fix version pins for PPAs

### ISSUE THREAD

**Issue by caseydavenport** [projectcalico/calico#328]
See this comment: https://github.com/projectcalico/calico/pull/325#issuecomment-265287826

**Comment by djosborne** [comment]
To elaborate, there are a few places in openstack installs we reference which Felix ppa version to install. So far, we've manually updated those references when felix is released, i.e. this commit: https://github.com/projectcalico/calico/pull/325/commits/6c981ef9e8b37e9c393d55ee4cfbb8d82c0e63c0

We should automate this through the do_release.py

**Comment by caseydavenport** [comment]
We should automate, but at a minimum we should document in RELEASING.md what needs to be done.
