### ISSUE TITLE
calico-kube-controllers always stays in ContainerCreating state

### ISSUE THREAD

**Issue by Flybro** [projectcalico/calico#3288]
I am installing a multi-node kubernetes cluster in-hard-way on 7 VMs (1 load balancer, 3 master, 3 workers) and everything seems to be working properly except caliko-kube-controllerr where pod stay in ContainerCreating state forever. What could be the reason?

## Expected Behavior

All pods running in watch kubectl get pods -A
## Current Behavior

**# kubectl get pods -A**
```
NAMESPACE     NAME                                      READY   STATUS              RESTARTS   AGE
kube-system   calico-kube-controllers-77c4b7448-ll2mh   0/1     ContainerCreating   0          46h
kube-system   calico-node-47trw                         1/1     Running             0          46h
kube-system   calico-node-fzxvk                         1/1     Running             0          46h
kube-system   calico-node-g6k9l                         1/1     Running             0          46h
kube-system   calico-node-hg6hk                         1/1     Running             0          46h
kube-system   calico-node-pvzbk                         1/1     Running             0          46h
kube-system   calico-node-ql4wf                         1/1     Running             0          46h
```
**# kubectl -n kube-system describe pod calico-kube-controllers-77c4b7448-ll2mh**
```
Warning  FailedCreatePodSandBox  3m54s (x2274 over 46h)  kubelet, is-worker2.softice.io  (combined from similar events): Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "c938ec64e65733df365b33d718fd4bd22695aed43fb2faf7410f18143575140d": error getting ClusterInformation: Get https://[192.168.128.1]:443/apis/crd.projectcalico.org/v1/clusterinformations/default: Service Unavailable
```
**# kubectl -n kube-system logs calico-kube-controllers-77c4b7448-ll2mh**
```
Error from server (BadRequest): container "calico-kube-controllers" in pod "calico-kube-controllers-77c4b7448-ll2mh" is waiting to start: ContainerCreating
```
***# kubectl get svc -A***
```
NAMESPACE   NAME         TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)   AGE
default     kubernetes   ClusterIP   192.168.128.1   <none>        443/TCP   46h
```
***# kubectl describe svc kubernetes***
```
Name:              kubernetes
Namespace:         default
Labels:            component=apiserver
                   provider=kubernetes
Annotations:       <none>
Selector:          <none>
Type:              ClusterIP
IP:                192.168.128.1
Port:              https  443/TCP
TargetPort:        6443/TCP
Endpoints:         10.64.106.143:6443,10.65.134.95:6443,10.68.202.79:6443
Session Affinity:  None
Events:            <none>
```
## Your Environment

Calico version v3.12.0
Kubernetes 1.17.3
Operating System and version: Debian Buster 10

**Comment by tmjd** [comment]
Are you running kube-proxy? I ask because you need something to configure routing to the kubernetes service that Calico components are depending on.
A prerequisite of calico of calico is being able to access the kubernets API server by accessing it's service address from each of your hosts. Can you do this?

**Comment by Flybro** [comment]
All nodes are using external LB (HAproxy) and at least all of them are able to download images from outside. Executing following command from the node where calico-kube-controller supposed to run seems to be OK.

**curl -k https://is-lb:6443/version**
```
{
  "major": "1",
  "minor": "17",
  "gitVersion": "v1.17.3",
  "gitCommit": "06ad960bfd03b39c8310aaf92d1e7c12ce618213",
  "gitTreeState": "clean",
  "buildDate": "2020-02-11T18:07:13Z",
  "goVersion": "go1.13.6",
  "compiler": "gc",
  "platform": "linux/amd64"
}
```

**Comment by rafaelvanoni** [comment]
@Flybro We'd still like to know if the kubernetes apiserver is reachable by its service IP. The calico CNI plugin needs to use that and it seems that's failing (from the first err message in your description).

**Comment by Flybro** [comment]
I have to admin @rafaelvanoni that I don't have much experience with kubernetes, so can I ask you for some hints on how to be sure if CNI have access to apiserver?

**Comment by song-jiang** [comment]
@Flybro Do you still see this issue?

**Comment by Flybro** [comment]
After upgrading to 1.18.* the probleam dissaperd.
