### ISSUE TITLE
Resource requests/limits for self-hosted manfests

### ISSUE THREAD

**Issue by caseydavenport** [projectcalico/calico#329]
We should be setting resource limits in the self-hosted manifests.

Currently blocked by deciding what those limits should be.

EDIT:

I don't think we can reasonably specify values here that will apply apply to all clusters.  I think instead we need a table of some sort with recommended values based on experience.

**Comment by caseydavenport** [comment]
We should also have a table of recommended values for various levels of scale.

**Comment by djosborne** [comment]
Would be useful to know this for the calico-dcos install as well.

**Comment by caseydavenport** [comment]
I believe we set requests now.
