### ISSUE TITLE
Do calico support intranet penetration?

### ISSUE THREAD

**Issue by QiusHosens** [projectcalico/calico#3294]
Do calico support intranet penetration? like ngrok
thanks !

**Comment by rafaelvanoni** [comment]
@QiusHosens We haven't test ngrok with Calico but it should work as long as the right network policies are in place... is there something in particular that you're curious/concerned about?

**Comment by QiusHosens** [comment]
@rafaelvanoni 
thanks.
sorry, I didn't express my meaning clearly.
I mean can Calico support the function of intranet penetration， not whether ngrok will work with calico.
thanks !

**Comment by spikecurtis** [comment]
No, Calico doesn't have any built-in functionality that is similar to ngrok.  It does support all the usual Kubernetes ingress options.
