### ISSUE TITLE
Add alpha network policy tests to sempahore

### ISSUE THREAD

**Issue by jayunit100** [projectcalico/calico#3312]
Now that we have upstreamed our new network policy validation API, I'd be happy to add this to the Calico test suites if possible.  Benefits here:

- Calico gets the all on all testing and validation that we're putting in upstream ahead of time.
- If any issues (we found a latency issue in other CNIs) calico might benefit from the additional coverage
- Better per pull test coverage of any latency or other issues that come up, as the wget with 3 tries gives a quick performance test.

As is calico 3.12 passes on this test suite.

If anyone wants to provide me with instructions im happy to add the necessary YAML etc to run this as an acceptace test. 

References: 

- https://github.com/jayunit100/presentations/blob/master/netpol-sig-network-ongoing/netpol-testing.md
- https://github.com/kubernetes/enhancements/pull/1568

**Comment by caseydavenport** [comment]
> Now that we have upstreamed our new network policy validation API, I'd be happy to add this to the Calico test suites if possible. Benefits here:

@jayunit100 could you provide a link to the tests you're proposing we run? I don't recall seeing the PR for the upstream testing changes.

**Comment by jayunit100** [comment]
Heres an example of them running ... https://github.com/vmware-tanzu/antrea/pull/495/checks?check_run_id=500273143 .  We dont have them in upstream k8s yet .

**Comment by jayunit100** [comment]
per conv w/ @caseydavenport today in the Calico community meeting might be worth waiting til upstream that way its all coming from core k8s, will keep pushing on the 1568 kep to see how soon we can get it approved.

**Comment by caseydavenport** [comment]
I'm going to close this for now. I don't think there is any action to take on the Calico side. We pull in e2e tests from upstream fairly regularly so once merged upstream they will flow through.

**Comment by jayunit100** [comment]
ok... but... do we run them regularly ? I thought we didnt (they were broken upstream for a while) ?  Might want to reopen later.
