### ISSUE TITLE
Add status reporting to felix

### ISSUE THREAD

**Issue by fasaxc** [projectcalico/calico#335]
We'd like felix to report its status back into etcd so that we can figure out how far behind the felices are and whether they're alive.

**Comment by Lukasa** [comment]
This needs an assignee.

**Comment by Lukasa** [comment]
This is languishing, so it's been moved out to 1.0.

**Comment by joe-marshall** [comment]
Miroslav is working on this, so I've assigned it to him.

**Comment by lwr20** [comment]
@fasaxc: you're working on this now, yes?

**Comment by eepyaich** [comment]
@fasaxc Can we close this now?
