### ISSUE TITLE
Allow selectively removing nodes from service advertisement datapath

### ISSUE THREAD

**Issue by grandich** [projectcalico/calico#3365]
## Expected Behavior
k8s service address range should be routed to worker nodes

## Current Behavior
k8s service address range is routed through route reflector nodes

## Context
- BGP full-mesh disabled
- dedicated RR nodes against ToR talking i-BGP
- k8s service CIDR: 10.231.32.0/20
- pods CIDR: 10.231.48.0/20
- workers: 10.184.42.*
- ToR: 10.184.42.254

on RR, we can see blackhole route producing this behaviour:

birdcl -s /run/calico/bird.ctl show route export Node_10_184_42_254
      10.231.50.192/26   via 10.184.42.35 on ens3 [Node_10_184_42_35 19:25:23] * (100/0) [i]
      10.231.63.64/26    via 10.184.42.34 on ens3 [Node_10_184_42_34 19:25:22] * (100/0) [i]
      10.231.61.128/26   via 10.184.42.26 on ens3 [Node_10_184_42_26 19:25:22] * (100/0) [i]
      **10.231.32.0/20     blackhole [static1 19:25:21] * (200)**

## Your Environment
Calico version v3.7.3
Kubernetes v1.15.3
Operating System and version: Ubuntu 18.04.2 LTS

**Comment by spikecurtis** [comment]
Just to clarify, all the nodes and the ToRs are all in the same BGP Autonomous System (AS)?

And, your route reflectors are running `calico-node` to act as a route reflector? Are they also Kubernetes nodes?

**Comment by grandich** [comment]
Yes, each node is in the same AS as the ToR, one AS per rack.

We are using calico-node in all nodes, and all are Kubernetes nodes (although RRs not scheduleable for user workloads).

NAME                                              READY   STATUS    RESTARTS   AGE    IP              NODE                           
calico-node-s4ghz                                 1/1     Running   2          80d    10.184.42.xxx  team-01-k8s-master-nf-1         
calico-node-mrff7                                 1/1     Running   1          80d    10.184.42.xxx  team-01-k8s-node-nf-1           
calico-node-gvcfs                                 1/1     Running   1          80d    10.184.46.xxx  team-01-k8s-node-nf-2           
calico-node-g5mt5                                 1/1     Running   3          61d    10.184.42.xxx  team-01-k8s-node-nf-3           
calico-node-b59gb                                 1/1     Running   3          61d    10.184.46.xxx  team-01-k8s-node-nf-4           
calico-node-8cfcc                                 1/1     Running   0          46h    10.184.42.xxx  team-01-k8s-calico-rr-64942     
calico-node-gxwlp                                 1/1     Running   1          58d    10.184.42.xxx  team-01-k8s-calico-rr-64942-bkp 
calico-node-rxsrj                                 1/1     Running   0          20h    10.184.46.xxx  team-01-k8s-calico-rr-64946     
calico-node-sqph6                                 1/1     Running   0          2d2h   10.184.46.xxx  team-01-k8s-calico-rr-64946-bkp 
kube-proxy-4dwfn                                  1/1     Running   0          28d    10.184.42.xxx  team-01-k8s-calico-rr-64942     
kube-proxy-5vqrl                                  1/1     Running   1          80d    10.184.42.xxx  team-01-k8s-calico-rr-64942-bkp 
kube-proxy-fgcm7                                  1/1     Running   0          27d    10.184.46.xxx  team-01-k8s-calico-rr-64946     
kube-proxy-nxbwd                                  1/1     Running   0          28d    10.184.46.xxx  team-01-k8s-calico-rr-64946-bkp 
nginx-proxy-team-01-k8s-calico-rr-64942           1/1     Running   0          80d    10.184.42.xxx  team-01-k8s-calico-rr-64942     
nginx-proxy-team-01-k8s-calico-rr-64942-bkp       1/1     Running   1          80d    10.184.42.xxx  team-01-k8s-calico-rr-64942-bkp 
nginx-proxy-team-01-k8s-calico-rr-64946           1/1     Running   0          80d    10.184.46.xxx  team-01-k8s-calico-rr-64946     
nginx-proxy-team-01-k8s-calico-rr-64946-bkp       1/1     Running   0          80d    10.184.46.xxx  team-01-k8s-calico-rr-64946-bkp 
nodelocaldns-6lhwc                                1/1     Running   0          20h    10.184.46.xxx  team-01-k8s-calico-rr-64946     
nodelocaldns-pwp7m                                1/1     Running   0          46h    10.184.42.xxx  team-01-k8s-calico-rr-64942     
nodelocaldns-rqfgm                                1/1     Running   1          58d    10.184.42.xxx  team-01-k8s-calico-rr-64942-bkp 
nodelocaldns-swzmw                                1/1     Running   0          2d1h   10.184.46.xxx  team-01-k8s-calico-rr-64946-bkp

**Comment by spikecurtis** [comment]
Are you setting externalTrafficPolicy to `local`? If not, the default is `cluster` which causes each Kubernetes node to advertise the service IPs, regardless of whether they have backends for the service running (which of course your RRs do not).

This doc has some more information
https://docs.projectcalico.org/networking/advertise-service-ips

**Comment by grandich** [comment]
We are using ClusterIP type service, which does not support ExternalTrafficPolicy = Local

> The Service "xxx" is invalid: spec.externalTrafficPolicy: Invalid value: "Local": ExternalTrafficPolicy can only be set on NodePort and LoadBalancer service

Either way, the root problem is we have, say, 100 worker calico-nodes peered with 2 RR calico-nodes, which are peered with the rest of our infrastructure. Both RR advertise the entire service CIDR with next-hop for themselves (blackhole route), making them SpOF and bottlneck.

ref: https://github.com/projectcalico/calico/issues/1008#issuecomment-598931488

**Comment by spikecurtis** [comment]
You can create your services as NodePorts, which then still get a ClusterIP, and Calico can still advertise that IP out over BGP. You don't have to actually use the node port.

With externalTrafficPolicy local, each valid node will advertise a /32, which takes precedence over the service CIDR route due to longest prefix matching.

**Comment by caseydavenport** [comment]
IIUC, in this case the RR nodes are in the datapath for the "cluster" type services, because the nodes themselves are within the cluster. Additionally, the RR nodes shouldn't be SPOF, because hte route will be advertised from _all_ nodes.

I think this is working as expected, and the above suggestion to use Local type services will remove them from the datapath for those services.

We could also consider an enhancement to allow certain nodes to opt-out of being included in service advertisement for the entire range.

**Comment by grandich** [comment]
I've recently found that master nodes (kubernetes control plane) also advertises service ranges, putting them in the datapath. I suppose this issue applies to this case also.

In the meantime, is there any workaround to exclude service CIDR from being advertised in master nodes?

**Comment by caseydavenport** [comment]
We added a way to do this in Calico v3.18: https://docs.projectcalico.org/archive/v3.18/networking/advertise-service-ips#exclude-certain-nodes-from-advertisement
