### ISSUE TITLE
UBER Arachne not working on calico nodes with globalnetworkpolicy

### ISSUE THREAD

**Issue by dimm0** [projectcalico/calico#3374]
## Expected Behavior
With calico global policy in place according to docs, host processes should be able to send SYN TCP packets
## Current Behavior
I have a global policy set up to allow all outgoing traffic from nodes according to `Allow local host egress traffic` https://docs.projectcalico.org/security/kubernetes-node-ports. Trying to set up Uber Arachne (https://github.com/uber/arachne) for monitoring, and for nodes on which HostEndpoint is defined, arachne can't send SYN tcp packets

`{"level":"error","ts":1584673197.87136,"msg":"failed to send out operation not permitted","PID":30994,"hostname":"k8s-bharadia-01.sdsc.optiputer.net","service_name":"arachne","flag":"SYN","src_address":"67.58.50.234","src_port":"31011","dst_address":"67.58.53.156","dst_port":"44111","stacktrace":"github.com/uber/arachne/internal/tcp.send.func1\n\t/Users/dimm/go/src/github.com/uber/arachne/internal/tcp/tcp.go:521"}`

Once I remove the hostendpoint, everything is working fine.

## Steps to Reproduce (for bugs)
1. Set calico policy
2. Copy arachne on 2 nodes, try set up monitoring according to docs

## Context
Trying to monitor all cluster nodes connectivity

## Your Environment
* Calico version 3.11.1
* Orchestrator version (e.g. kubernetes, mesos, rkt): k8s 1.17.4
* Operating System and version: Centos 7

**Comment by dimm0** [comment]
BTW not working on overlay network too... But with a different error, not sure what that means
`{"level":"error","ts":1584681454.333809,"msg":"host exists in resultStore, but not in remoteStore","PID":17539,"hostname":"testpoint-w9pm6","service_name":"arachne","host":"198.17.101.70","stacktrace":"github.com/uber/arachne/collector.resultStore.walkResults\n\t/Users/dimm/go/src/github.com/uber/arachne/collector/collector.go:143\ngithub.com/uber/arachne/collector.resultStore.printResults\n\t/Users/dimm/go/src/github.com/uber/arachne/collector/collector.go:206\ngithub.com/uber/arachne/collector.batchWorker\n\t/Users/dimm/go/src/github.com/uber/arachne/collector/collector.go:349\ngithub.com/uber/arachne/collector.Run.func1\n\t/Users/dimm/go/src/github.com/uber/arachne/collector/collector.go:231"}`

**Comment by spikecurtis** [comment]
hi @dimm0 

Can you paste the full set of Calico policies you have in place?

One curious thing about the error you are seeing is it says "failed to send out operation not permitted" --- this operation not permitted language is usually reserved for when the kernel blocks something at the socket layer, rather than when it drops packets (the calling application doesn't get any notification when packets get dropped).

**Comment by dimm0** [comment]
Hi!

The policies are here: https://gitlab.nautilus.optiputer.net/prp/calico/blob/master/policy.yaml (all other config is in the same repo).

> One curious thing about the error you are seeing is it says "failed to send out operation not permitted"

Yes! I found that interesting too, I never saw something being actively prohibited, and not sure how it's possible. But maybe that's how it works for outgoing packets? I don't have much experience blocking those.

**Comment by spikecurtis** [comment]
One other comment is that Arachne's docs say it's using "raw sockets" and BPF filters. Calico's main mode of operation uses iptables (we have a eBPF dataplane in tech preview), so it's possible that Arachne attaches some of its workings in a different place than "normal" applications, and it's possible this accounts for at least some of the strange behavior.

**Comment by spikecurtis** [comment]
You might want to try the TCP connection just with `nc` ("src_address":"67.58.50.234","src_port":"31011","dst_address":"67.58.53.156","dst_port":"44111") and see whether that's blocked by Calico --- that would help rule out whether Arachne's nonstandard use of sockets is part of the issue.

**Comment by dimm0** [comment]
Raw sockets - yes
BPF - 
> When **receiving** packets, Arachne **attempts** to apply a BPF filter to the raw socket

It tries to send TCP packets without a proper TCP handshake (to measure the response time better). So kernel can't filter those packets properly, since there's no actual TCP connection

I can test that, but I'm prettu sure it will work fine. I have no other issues with a bunch of other software

**Comment by spikecurtis** [comment]
Arachne is running on the host right, not in a pod in its own network namespace, right?

**Comment by dimm0** [comment]
Yes, directly on the host

2nd step will be in a pod, but for now at least on the host

**Comment by spikecurtis** [comment]
Ironically, you might have better luck with it in a Pod, because all the fancy Calico stuff happens in the root network namespace and we generally don't have any stuff in the pod network namespace (except for when using Policy for Istio).

**Comment by dimm0** [comment]
I need it working both ways eventually...
How can I help debugging?

**Comment by spikecurtis** [comment]
I think we're down into kernel spelunking, unfortunately.  Looks like Arachne opens a raw IP socket, then fails on the SendTo syscall. I'm not sure why or how iptables programming would affect permissions on that syscall.

**Comment by dimm0** [comment]
Were you able to reproduce?
Do you have a simple test system to see if it's a specific set of calico rules, or even empty set of rules would cause it?
I'm a bit worried to test stuff on production cluster...

**Comment by dimm0** [comment]
🥺
