### ISSUE TITLE
GlobalNetworkPolicy Deny policy doesn't work

### ISSUE THREAD

**Issue by huangyingting** [projectcalico/calico#3379]
GlobalNetworkPolicy Deny policy doesn't work, when apply below template
apiVersion: projectcalico.org/v3
kind: GlobalNetworkPolicy
metadata:
  name: deny-lb-port-80
spec:
  applyOnForward: true
  preDNAT: true
  ingress:
  - action: Deny
    destination:
      nets:
      - 20.43.149.233/32
      ports:
      - 80
    protocol: TCP
    source: {}
## Expected Behavior

It should block port 80 on destination IP address 20.43.149.233 which is a load balancer's public IP on Azure AKS. 
## Current Behavior

Unfortunately, it doesn't work. When I tried psping devapp.k8s.azcloud.top:80, I still get responses
D:\>psping devapp.k8s.azcloud.top:80

PsPing v2.10 - PsPing - ping, latency, bandwidth measurement utility
Copyright (C) 2012-2016 Mark Russinovich
Sysinternals - www.sysinternals.com

TCP connect to 20.43.149.233:80:
5 iterations (warmup 1) ping test:
Connecting to 20.43.149.233:80 (warmup): from 100.64.80.107:56007: 68.90ms
Connecting to 20.43.149.233:80: from 100.64.80.107:56008: 69.27ms
Connecting to 20.43.149.233:80: from 100.64.80.107:56009: 70.23ms

  Sent = 2, Received = 2, Lost = 0 (0% loss),
  Minimum = 69.27ms, Maximum = 70.23ms, Average = 69.75ms
## Steps to Reproduce (for bugs)

Calico version is below
D:\>calicoctl version
Client Version:    v3.8.7
Git commit:        0991d2fb
Cluster Version:   v3.5.0
Cluster Type:      typha,kdd,k8s

Apply below template
apiVersion: projectcalico.org/v3
kind: GlobalNetworkPolicy
metadata:
  name: deny-lb-port-80
spec:
  applyOnForward: true
  preDNAT: true
  ingress:
  - action: Deny
    destination:
      nets:
      - <YOUR_PUBLIC_IP>/32
      ports:
      - 80
    protocol: TCP
    source: {}

## Your Environment

* Calico version
* Orchestrator version (e.g. kubernetes, mesos, rkt):
* Operating System and version:
* Link to your project (optional):

D:\>calicoctl version
Client Version:    v3.8.7
Git commit:        0991d2fb
Cluster Version:   v3.5.0
Cluster Type:      typha,kdd,k8s

**Comment by rafaelvanoni** [comment]
@huangyingting Couple questions: (a) do you have a host endpoint and (b) where are you trying to block traffic from? Can you elaborate on your setup and what you're trying to achieve so we can help determine the best way of achieving it?

**Comment by huangyingting** [comment]
@rafaelvanoni thank you for your prompt response, the environment is AKS cluster in Azure which is eanbled Calico policy, the AKS cluster only has 1 node (agent node)

Server version is below
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.7", GitCommit:"c83d931fb9bece427bc63a02349755e0f8696d3e", GitTreeState:"clean", BuildDate:"2020-01-31T20:09:49Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}

devapp.k8s.azcloud.top is a simple web application behind nginx ingress controller.

What I want to achieve is, using global network policy block any inbound traffics target to devapp.k8s.azcloud.top's IP 20.43.149.233 and port 80, only allow port 443.

But it seems it won't. I also checked iptables from node itself, the interesting part is I can see below iptables rule get created, but no any "-j" command to it

-A cali-pi-deny-lb-port-80 -d 13.67.39.3/32 -p tcp -m comment --comment "cali:pzo7YUzMGCYxykNB" -m multiport --dports 80 -j DROP

**Comment by spikecurtis** [comment]
@huangyingting how have you set up your ingress controller?  Is it a daemonset, or is it running as a deployment with a Kubernetes service fronting it?

Another way to put this question is, what does the IP 20.43.149.233 represent? Is it the public IP address of your node, or the public IP of some load-balancer outside the AKS cluster?

**Comment by huangyingting** [comment]
@spikecurtis , thanks for your follow-up. 20.43.149.233 is a load balancer which is backed by Nginx ingress controller. Refer to below. Nginx ingress controller runs as a deployment. 
It has setting "externalTrafficPolicy: Cluster", also I changed to Local, it won't work as well. As preDNAT: true, so I feel it doesnt' matter.

kubectl get service -n=dev
NAME                            TYPE           CLUSTER-IP     EXTERNAL-IP     PORT(S)                      AGE
devapp                          ClusterIP      10.0.47.90     <none>          80/TCP                       6d15h
nginx-ingress-controller        LoadBalancer   10.0.206.231   20.43.149.233   80:31812/TCP,443:30067/TCP   6d17h
nginx-ingress-default-backend   ClusterIP      10.0.141.39    <none>          80/TCP                       6d17h

**Comment by spikecurtis** [comment]
@huangyingting I don't think a GlobalNetworkPolicy selecting the external IP is the right solution for your problem.  The IP address 20.43.149.233 is for a load balancer outside of Kubernetes (presumably provided by Azure in your case).  Traffic for that address hits the load balancer, and then gets its address translated to something in your cluster---either a node address or possibly the pod address of the nginx ingress. So, by the time Calico sees the traffic entering the actual Kubernetes cluster, it no longer has the 20.43.149.233 address as the destination, and your GlobalNetworkPolicy rule won't select the traffic.

My recommendation is to use a network policy that selects the nginx pod(s) serving your traffic, and apply the policy there to only allow connections on port 443. This should have the desired effect of preventing connections on port 80.

**Comment by huangyingting** [comment]
@spikecurtis , seriously? I have captured traffics on node, it shows 20.43.149.233 hit my node, this is by default, in any cloud, it uses direct server return (or floating IP) for load balancer IP address. Can you build a simple test environment and prove what you are saying is the truth? 
Also can you help explain what's the appropriate scenario to use GlobalNetworkPolicy?

**Comment by spikecurtis** [comment]
@huangyingting maybe I'm mistaken about Azure cloud load balancers.  I know that in AWS the ELBs do address translation to node ports on Kubernetes nodes, and you wouldn't see the external IP at the Kubernetes node. It's certainly possible that Azure does something different, I was just assuming that they worked similarly.

If you're seeing traffic for 20.43.149.233 at the node, then a GlobalNetworkPolicy is one appropriate solution to control traffic.  In order to use network policy with traffic on the node you have to create a [HostEndpoint](https://docs.projectcalico.org/reference/resources/hostendpoint) for the node interface you want to apply the policy to. Have you done that?

Then, label the host endpoint and use the selector on the GlobalNetworkPolicy to select that label to get your policy to apply to that endpoint.

**Comment by huangyingting** [comment]
@spikecurtis , thank you, I don't have HostEndpoint defined orginally.

But now, even I use below configuration, I still could not make it work, can you help check what's the problem?

As you can see, the node IP is 10.32.32.4 
D:\>kubectl get node -o wide
NAME                              STATUS   ROLES   AGE   VERSION   INTERNAL-IP   EXTERNAL-IP   OS-IMAGE             KERNEL-VERSION      CONTAINER-RUNTIME
aks-default-29099486-vmss000000   Ready    agent   8d    v1.15.7   10.32.32.4    <none>        Ubuntu 16.04.6 LTS   4.15.0-1071-azure   docker://3.0.10+azure

apiVersion: crd.projectcalico.org/v1
kind: HostEndpoint
metadata:
  name: vmss000000
  labels:
    type: production
spec:
  interfaceName: eth0
  node: aks-default-29099486-vmss000000
  expectedIPs:
  - 10.32.32.4
---
apiVersion: crd.projectcalico.org/v1
kind: GlobalNetworkPolicy
metadata:
  name: deny-lb-80
spec:
  selector: type == 'production'
  types:
  - Ingress
  preDNAT: true
  applyOnForward: true  
  ingress:
  - action: Deny
    source: {}
    destination:
      nets:
      - 20.43.149.233/32
      ports:
      - 80

**Comment by spikecurtis** [comment]
One thing to double-check is that the `node` field in your host endpoint matches the hostname of the node you want it to apply to, and to verify that the interface name is correct by doing an `ip addr show` on that node.

Keep in mind that:

> If a host endpoint is added and network policy is not in place, the Calico default is to deny traffic to/from that endpoint (except for traffic allowed by failsafe rules).

(from https://docs.projectcalico.org/reference/resources/hostendpoint)

That means that you will need to explicitly create Global Network Policies that allow all required traffic.  For example, the policy you have now denies port 80, but there are no rules that allow port 443, so you'll need to add them. This includes all traffic in and out of that node that aren't covered by the failsafes (https://docs.projectcalico.org/reference/host-endpoints/failsafe).

The complexity of having to whitelist host traffic is one reason why I suggested that applying regular network policy to the pods backing your service might be a better option for your specific use case.
