### ISSUE TITLE
Diagnostics: would be nice to log why packet is being dropped

### ISSUE THREAD

**Issue by fasaxc** [projectcalico/calico#338]
There are various reasons that our iptables chains may drop a packet apart from a user-configured drop rule.  iptables has a log target that, if enabled, makes a log to the system log when a packet hits that rule.  Combined with a probabilistic match, we could use that to log some fraction of dropped packets.

It'd be nice to log:

* when a packet hits an anti-spoof rule; this bit me today when I had a misconfigured docker container and its MAC didn't match the value in etcd
* when a packet hits the drop rule in a "stub" chain programmed when we're missing the configuration for a chain.

**Comment by Lukasa** [comment]
What's the performance impact of the logging? In general it's easy enough to spot packets hitting certain rules by using a judicious combination of `iptables -Z` and `iptables -L -v`, so if there's any significant performance hit in the logging I don't believe it's worthwhile.

**Comment by fasaxc** [comment]
I think the impact of each log is too much for every packet but that's why they recommend using the log target with one of iptables statistical matches that let you do things like "log the first packet and then one every 10s".

**Comment by fasaxc** [comment]
Fixed under #1067
