### ISSUE TITLE
no matches for kind "NetworkPolicy" in version "projectcalico.org/v3"

### ISSUE THREAD

**Issue by jicowan** [projectcalico/calico#3380]
When creating a network policy with `apiVersion: projectcalico.org/v3` I get the following error: 
```
no matches for kind "NetworkPolicy" in version "projectcalico.org/v3"
```
If I change the value of `apiVersion` to `crd.projectcalico.org/v1` it works.  

I applied the following manifest to install Calico on an EKS cluster at v1.15. 
https://github.com/aws/amazon-vpc-cni-k8s/blob/master/config/v1.5/calico.yaml

**Comment by jicowan** [comment]
I see that you have to use calicoctl.  It's still not prominent enough IMO.

**Comment by sig-piskule** [comment]
I came across this issue, and this doesn't appear to be true (at least not anymore). While I am having the same issue on EKS, this should be possible according to Tigera's own blog:

https://www.tigera.io/blog/getting-started-with-eks-and-calico/

Calico walks you through how to do this, but this appears to be enabled by default:

https://docs.tigera.io/calico/latest/operations/install-apiserver
