### ISSUE TITLE
Unable to use deviceRouteSourceAddress in spec for FelixConfiguration

### ISSUE THREAD

**Issue by acritelli** [projectcalico/calico#3381]
I'm trying to specify the `deviceRouteSourceAddress` parameter in a `FelixConfiguration`. My understanding is that this can be used to indicate the interface that traffic from a pod on one host to a pod on another host should use (currently, my host is using wlan0 and I want it to use eth0).

Attempting to specify this parameter is resulting in an error:

```
fsh$ calicoctl create -f felix.yaml 
Failed to execute command: error parsing document: field in document is not recognized or is in the wrong location: deviceRouteSourceAddress
```

## Expected Behavior

I would expect that the `calicoctl replace -f felix.yaml` command would succeed.

## Current Behavior
I am receiving the following error, as seen above: `Failed to execute command: error parsing document: field in document is not recognized or is in the wrong location: deviceRouteSourceAddress`

Below is the contents of the current Felix configuration:

```
fsh$ calicoctl get felixconfig default -o yaml > felix-current.yaml
fsh$ cat felix-current.yaml -p
apiVersion: projectcalico.org/v3
kind: FelixConfiguration
metadata:
  creationTimestamp: 2020-03-08T01:23:23Z
  name: default
  resourceVersion: "616"
  uid: e0f27800-bd2e-4738-979d-7be7927010c7
spec:
  XDPRefreshInterval: null
  ipipEnabled: true
  logSeverityScreen: Info
  reportingInterval: 0s
```

And below is the config I am attempting to apply (note that I've changed the name to be a node so that it is applied to an individual node. I'm assuming this is needed since the `deviceRouteSourceAddress` would be device specific.)

```
fsh$ cat felix.yaml -p
apiVersion: projectcalico.org/v3
kind: FelixConfiguration
metadata:
  creationTimestamp: 2020-03-08T01:23:23Z
  name: raspi01
  resourceVersion: "616"
  uid: e0f27800-bd2e-4738-979d-7be7927010c7
spec:
  XDPRefreshInterval: null
  deviceRouteSourceAddress: "192.168.200.1"
  ipipEnabled: true
  logSeverityScreen: Info
  reportingInterval: 0s
```

And here is a diff of the files:

```
fsh$ diff felix-current.yaml felix.yaml
5c5
<   name: default
---
>   name: raspi01
9a10
>   deviceRouteSourceAddress: "192.168.200.1"
```

## Possible Solution
N/A

## Steps to Reproduce (for bugs)
1. Set up an environment as described under the environment section
2. Attempt to apply a felix configuration with the `deviceRouteSourceAddress` parameter

## Context
Discussed in the description, but for more context: I have two IP Pools. The default pool, and a separate pool being used by a separate namespace. The default pool uses IPinIP. The traffic for this seems to egress via eth0 just fine.

The other pool is set to **not** use IPinIP. That traffic seems to be going out of the wlan0 interface. I would like it to go out of eth0, and my understanding is that the `deviceRouteSourceAddress` is the way to do this.

## Your Environment
Calico version:
```
fsh$ calicoctl version
Client Version:    v3.8.7
Git commit:        0991d2fb
Cluster Version:   v3.13.0
Cluster Type:      k8s,bgp,kubeadm,kdd,typha
```

K8s version (deployed via kubeadm):
```
fsh$ kubectl version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T11:13:54Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-11T18:07:13Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/arm64"}
```

These are Raspi 4s running Ubuntu 18.04

**Comment by rafaelvanoni** [comment]
@acritelli It looks like you're using an older version of calicoctl, we recommend using the same version as the install you're running.
