### ISSUE TITLE
Can't ping any ip address in hosts network from pod

### ISSUE THREAD

**Issue by MarcusFloeser** [projectcalico/calico#3388]
I installed kubernetes cluster with calico network in my private network.
All pods are running after install, but I cannot ping out of a pod to any host ip in my network.

Host ip config: 10.23.1.111/17, gateway 10.23.0.1, DNS server 10.23.0.87
Calico CIDR=172.20.0.0/16

Routing on host:
![image](https://user-images.githubusercontent.com/62652377/77539146-2ce1b180-6ea1-11ea-86cf-a0f847eba527.png)

![image](https://user-images.githubusercontent.com/62652377/77538695-69f97400-6ea0-11ea-92a6-93dac72ba214.png)

But ping from busybox to a host ip do not work:
![image](https://user-images.githubusercontent.com/62652377/77538891-c2c90c80-6ea0-11ea-8fa0-b3c1c67b50eb.png)

## Your Environment
Calico version: 3.3
kubernetes: 1.11.9
Operating system and version: CentOS 7.7

**Comment by MaagoFleesa** [comment]
Hmm .. found out that after enabling firewall on host it is working. I can now ping to anywhere.
But is it really needed to have a enabled firewall ?

**Comment by spikecurtis** [comment]
Can you elaborate on what you mean by "enabling firewall on host"?  What firewall are you running, how did you enable it, and what is its configuration?

**Comment by MaagoFleesa** [comment]
I started "systemctl start firewalld" and suddenly I can ping outside from my pod.

**Comment by spikecurtis** [comment]
I wonder whether enabling the firewall also enabled iptables.  Can you attach the logs from `calico-node`? --- that might give some insight

**Comment by MaagoFleesa** [comment]
[calicolog.log.zip](https://github.com/projectcalico/calico/files/4413663/calicolog.log.zip)
