### ISSUE TITLE
staticcheck issues on 3.13.1

### ISSUE THREAD

**Issue by smijolovic** [projectcalico/calico#3389]
Staticcheck SCA results from Calico source code:

calicoctl/calicoctl.go:109:10: error strings should not be capitalized (ST1005)
calicoctl/commands/apply.go:87:10: error strings should not be capitalized (ST1005)
calicoctl/commands/apply.go:87:10: error strings should not end with punctuation or a newline (ST1005)
calicoctl/commands/apply.go:97:10: error strings should not be capitalized (ST1005)
calicoctl/commands/apply.go:100:11: error strings should not be capitalized (ST1005)
calicoctl/commands/apply.go:102:11: error strings should not be capitalized (ST1005)
calicoctl/commands/apply.go:104:11: error strings should not be capitalized (ST1005)
calicoctl/commands/apply.go:106:11: error strings should not be capitalized (ST1005)
calicoctl/commands/apply.go:125:10: error strings should not be capitalized (ST1005)
calicoctl/commands/convert.go:62:10: error strings should not be capitalized (ST1005)
calicoctl/commands/convert.go:62:10: error strings should not end with punctuation or a newline (ST1005)
calicoctl/commands/convert.go:86:10: error strings should not be capitalized (ST1005)
calicoctl/commands/convert.go:93:11: error strings should not be capitalized (ST1005)
calicoctl/commands/convert.go:109:12: error strings should not be capitalized (ST1005)
calicoctl/commands/convert.go:109:12: error strings should not end with punctuation or a newline (ST1005)
calicoctl/commands/convert.go:121:10: error strings should not be capitalized (ST1005)
calicoctl/commands/create.go:84:10: error strings should not be capitalized (ST1005)
calicoctl/commands/create.go:84:10: error strings should not end with punctuation or a newline (ST1005)
calicoctl/commands/create.go:94:10: error strings should not be capitalized (ST1005)
calicoctl/commands/create.go:97:11: error strings should not be capitalized (ST1005)
calicoctl/commands/create.go:99:11: error strings should not be capitalized (ST1005)
calicoctl/commands/create.go:101:11: error strings should not be capitalized (ST1005)
calicoctl/commands/create.go:103:11: error strings should not be capitalized (ST1005)
calicoctl/commands/create.go:122:10: error strings should not be capitalized (ST1005)
calicoctl/commands/delete.go:97:10: error strings should not be capitalized (ST1005)
calicoctl/commands/delete.go:97:10: error strings should not end with punctuation or a newline (ST1005)
calicoctl/commands/delete.go:107:10: error strings should not be capitalized (ST1005)
calicoctl/commands/delete.go:109:10: error strings should not be capitalized (ST1005)
calicoctl/commands/delete.go:117:10: error strings should not be capitalized (ST1005)
calicoctl/commands/get.go:116:10: error strings should not be capitalized (ST1005)
calicoctl/commands/get.go:116:10: error strings should not end with punctuation or a newline (ST1005)
calicoctl/commands/get.go:179:10: error strings should not be capitalized (ST1005)
calicoctl/commands/get.go:181:10: error strings should not be capitalized (ST1005)
calicoctl/commands/ipam.go:46:10: error strings should not be capitalized (ST1005)
calicoctl/commands/ipam.go:46:10: error strings should not end with punctuation or a newline (ST1005)
calicoctl/commands/ipam/release.go:53:10: error strings should not be capitalized (ST1005)
calicoctl/commands/ipam/release.go:53:10: error strings should not end with punctuation or a newline (ST1005)
calicoctl/commands/ipam/release.go:78:10: error strings should not be capitalized (ST1005)
calicoctl/commands/ipam/show.go:55:10: error strings should not be capitalized (ST1005)
calicoctl/commands/ipam/show.go:55:10: error strings should not end with punctuation or a newline (ST1005)
calicoctl/commands/label.go:93:10: error strings should not be capitalized (ST1005)
calicoctl/commands/label.go:93:10: error strings should not end with punctuation or a newline (ST1005)
calicoctl/commands/label.go:123:10: error strings should not be capitalized (ST1005)
calicoctl/commands/label.go:158:12: error strings should not end with punctuation or a newline (ST1005)
calicoctl/commands/node/checksystem.go:53:10: error strings should not be capitalized (ST1005)
calicoctl/commands/node/checksystem.go:53:10: error strings should not end with punctuation or a newline (ST1005)
calicoctl/commands/node/checksystem.go:78:10: error strings should not be capitalized (ST1005)
calicoctl/commands/node/checksystem.go:105:10: error strings should not be capitalized (ST1005)
calicoctl/commands/node/checksystem.go:183:10: error strings should not be capitalized (ST1005)
calicoctl/commands/node/checksystem.go:214:11: error strings should not be capitalized (ST1005)
calicoctl/commands/node/diags.go:66:10: error strings should not be capitalized (ST1005)
calicoctl/commands/node/diags.go:66:10: error strings should not end with punctuation or a newline (ST1005)
calicoctl/commands/node/diags.go:104:10: error strings should not be capitalized (ST1005)
calicoctl/commands/node/diags.go:110:10: error strings should not be capitalized (ST1005)
calicoctl/commands/node/diags.go:115:10: error strings should not be capitalized (ST1005)
calicoctl/commands/node/diags.go:115:10: error strings should not end with punctuation or a newline (ST1005)
calicoctl/commands/node/run.go:156:10: error strings should not be capitalized (ST1005)
calicoctl/commands/node/run.go:156:10: error strings should not end with punctuation or a newline (ST1005)
calicoctl/commands/node/run.go:182:11: error strings should not be capitalized (ST1005)
calicoctl/commands/node/run.go:188:11: error strings should not be capitalized (ST1005)
calicoctl/commands/node/run.go:198:10: error strings should not be capitalized (ST1005)
calicoctl/commands/node/run.go:216:11: error strings should not be capitalized (ST1005)
calicoctl/commands/node/run.go:223:10: error strings should not be capitalized (ST1005)
calicoctl/commands/node/run.go:226:10: error strings should not be capitalized (ST1005)
calicoctl/commands/node/run.go:378:10: error strings should not be capitalized (ST1005)
calicoctl/commands/node/run.go:385:10: error strings should not be capitalized (ST1005)
calicoctl/commands/node/run.go:412:10: error strings should not be capitalized (ST1005)
calicoctl/commands/node/run.go:421:10: error strings should not be capitalized (ST1005)
calicoctl/commands/node/run.go:423:10: error strings should not be capitalized (ST1005)
calicoctl/commands/node/run.go:492:11: error strings should not be capitalized (ST1005)
calicoctl/commands/node/run.go:501:10: error strings should not be capitalized (ST1005)
calicoctl/commands/node/run.go:511:12: error strings should not be capitalized (ST1005)
calicoctl/commands/node/run.go:524:12: error strings should not be capitalized (ST1005)
calicoctl/commands/node/run.go:530:9: error strings should not be capitalized (ST1005)
calicoctl/commands/node/status.go:52:10: error strings should not be capitalized (ST1005)
calicoctl/commands/node/status.go:52:10: error strings should not end with punctuation or a newline (ST1005)
calicoctl/commands/node/status.go:70:10: error strings should not be capitalized (ST1005)
calicoctl/commands/node/status.go:70:10: error strings should not end with punctuation or a newline (ST1005)
calicoctl/commands/node/status.go:242:10: error strings should not be capitalized (ST1005)
calicoctl/commands/node/status.go:249:10: error strings should not be capitalized (ST1005)
calicoctl/commands/node/status.go:343:10: error strings should not be capitalized (ST1005)
calicoctl/commands/node/status.go:356:10: error strings should not be capitalized (ST1005)
calicoctl/commands/node_linux.go:48:10: error strings should not be capitalized (ST1005)
calicoctl/commands/node_linux.go:48:10: error strings should not end with punctuation or a newline (ST1005)
calicoctl/commands/patch.go:83:10: error strings should not be capitalized (ST1005)
calicoctl/commands/patch.go:83:10: error strings should not end with punctuation or a newline (ST1005)
calicoctl/commands/patch.go:93:10: error strings should not be capitalized (ST1005)
calicoctl/commands/patch.go:97:10: error strings should not be capitalized (ST1005)
calicoctl/commands/replace.go:84:10: error strings should not be capitalized (ST1005)
calicoctl/commands/replace.go:84:10: error strings should not end with punctuation or a newline (ST1005)
calicoctl/commands/replace.go:94:10: error strings should not be capitalized (ST1005)
calicoctl/commands/replace.go:97:11: error strings should not be capitalized (ST1005)
calicoctl/commands/replace.go:99:11: error strings should not be capitalized (ST1005)
calicoctl/commands/replace.go:101:11: error strings should not be capitalized (ST1005)
calicoctl/commands/replace.go:103:11: error strings should not be capitalized (ST1005)
calicoctl/commands/replace.go:120:10: error strings should not be capitalized (ST1005)
calicoctl/commands/v1resourceloader/v1resourceloader.go:62:15: error strings should not be capitalized (ST1005)
calicoctl/commands/version.go:50:10: error strings should not be capitalized (ST1005)
calicoctl/commands/version.go:50:10: error strings should not end with punctuation or a newline (ST1005)
calicoctl/commands/version.go:68:10: error strings should not be capitalized (ST1005)
calicoctl/resourcemgr/resourcemgr.go:353:9: error strings should not be capitalized (ST1005)
calicoctl/resourcemgr/resourcemgr.go:389:15: error strings should not be capitalized (ST1005)
calicoctl/resourcemgr/resourcemgr.go:569:15: error strings should not be capitalized (ST1005)
tests/fv/utils/calicoctl.go:21:2: should not use dot imports (ST1001)

**Comment by rafaelvanoni** [comment]
@smijolovic Thanks for reporting these. Would you be able to put up a PR to fix those?

**Comment by smijolovic** [comment]
Rafael:

I submitted a new pull request for the results. If there is any other
additional information you need form me, please do not hesitate to reach
out.

Simon

**Comment by rafaelvanoni** [comment]
Ah, I see. You don't need to submit a PR just for the results. I was wondering if you were interested in contributing the fixes for those lint issues. No worries if not tho.

**Comment by smijolovic** [comment]
I wouldn’t mind contributing to them...just need a primer on how I would do that. 

Simon Mijolovic
President     
Defense in Depth Consulting, LLC
+1 315 729 8852
simon.mijolovic@gmail.com

**Comment by rafaelvanoni** [comment]
Sure, please take a look at these two docs for some initial guidance
https://github.com/projectcalico/community
https://github.com/projectcalico/calico/blob/master/CONTRIBUTING_CODE.md

For this issue, you'll be working on the calicoctl repository 
http://github.com/projectcalico/calicoctl/

Are you familiar with how forks, clones, branches work in open source projects?

**Comment by smijolovic** [comment]
I have familiarity with git on private repos.

Simon Mijolovic
President     
Defense in Depth Consulting, LLC
+1 315 729 8852
simon.mijolovic@gmail.com

**Comment by rafaelvanoni** [comment]
Cool. The "Contributing Code" document should have most of the steps you'll need. Feel free to ping me here or anyone on the Calico slack for any help.
