### ISSUE TITLE
Different behaviour of network policies while connecting to a pod and to a service (aka cluster) IP

### ISSUE THREAD

**Issue by edganiukov** [projectcalico/calico#3393]
Recently we discovered very odd behaviour when connectivity is blocked while connecting to a pod IP but allowed  while using a service (aka cluster) IP. 

In our cluster we are defining policies in each namespace to allow egress connectivity within the cluster (we do not use Global policies as we decided to use native Kubernetes NetworkPolicies) and also ingress connectivity from the host network (required for kubelet liveness and readiness probs).

 We have the following setup:
1. `namespace_a` and `namespace_b`
2. host network - `10.0.0.0/16`
3. two IP pools - `10.1.0.0/16` and `10.2.0.0/16`
4. Both IP pools configured without NAT via host network.
5. two NetworkPolicies in each namespace - to allow egress within the cluster (`namespaceSelector: {}`) and ingress from the host network (`cidr: 10.0.0.0/16`).
6. two pods in `namespace_a` - one pod (`pod_a_1`) uses IP from the first IP pool, second (`pod_a_2`) uses IP from the second IP pool.
7. a pod and a service in `namespace_b` - `service_b` 

When I am trying to connect from `pod_a_1` to service `service_b` - I get connection refused.
When I am trying to connect from `pod_a_2` to service `service_b` - I get connection established.

In the same time I can't connect to pod IP in both cases.

## Expected Behavior
In both cases I expect connection refused. 

## Possible Solution
What I find out is that for the connection from `pod_a_1` (tcpdump on the host where pod is running) source IP is the IP of the pod.
But for the connection from `pod_a_2`, source IP is the IP of the host (and connectivity from the host is allowed by the network policy).

## Steps to Reproduce (for bugs)
See in the description.

## Context
For us this is a critical security issue.

## Your Environment

* Calico version - 3.3.6
* Kubernetes - 1.14.5
* Operating System and version: Red Hat 7.5

**Comment by flarno11** [comment]
I believe this behavior is caused by kube-proxy, as it applies NAT to out of cluster traffic.

See `kube-proxy --cluster-cidr` (https://kubernetes.io/docs/reference/command-line-tools-reference/kube-proxy/):

> The  CIDR range of pods in the cluster. When configured, traffic sent to a  Service cluster IP from outside this range will be masqueraded and  traffic sent from pods to an external LoadBalancer IP will be directed  to the respective cluster IP instead

If you don't need this feature, you can specify `kube-proxy --cluster-cidr 0.0.0.0/0`.

**Comment by spikecurtis** [comment]
> and also ingress connectivity from the host network (required for kubelet liveness and readiness probs).

You shouldn't need to explicitly define policy for this. Calico allows kubelet and other processes running in the host network namespace to access local pods without restriction (for precisely this reason).

**Comment by spikecurtis** [comment]
I'm gonna close this one on the grounds that I think @flarno11 has posted the right answer, but feel free to reopen if you are still having trouble.
