### ISSUE TITLE
Different behaviour between v3.3.x and v3.13.1

### ISSUE THREAD

**Issue by openstacker** [projectcalico/calico#3398]
In OpenStack Magnum, we're trying to upgrade the calico from v3.3.6 to v3.13.1, after tweaking the yaml file, everything looks good. But we just found one case failed which worked in v3.3.6.

Test case:
Running a daemon set (see https://gist.githubusercontent.com/strigazi/5e75559e2221d4b9e3f63f7b33c82c9b/raw/3ac84e9416403fd1b9981ff77184c5b8542b6409/debugging-daemonset.yaml) on a 1 master, 2 work nodes k8s cluster. In calico v3.3.6, the pod running on a worker node can access pod running on both master node and worker node without opening a specific port of the firewall (security group). But on v3.13.1, we have to open the particular port (80 here), the pod of the daemon set can access another pod on another worker node, but cannot access the pod running on the master node without opening the 80 port on the master node's firewall.

## Expected Behavior
The pod running on worker node can access the pod running on master node without opening a particular port.

## Current Behavior
The pod running on worker node can NOT access the pod running on master node without opening a particular port.

## Steps to Reproduce (for bugs)
1. Deploy above daemon set
2. Login into the sidecar of one of the pod on worker node
3. Try to access the pod IP address by `curl <IP>:80`

## Your Environment
* Calico version
  v3.13.1
* Orchestrator version (e.g. kubernetes, mesos, rkt):
  Kubernetes
* Operating System and version:
  Fedora CoreOS 31
* Link to your project (optional):
 OpenStack Magnum

**Comment by openstacker** [comment]
Adding @strigazi

**Comment by spikecurtis** [comment]
@neiljerram do you know much about security group integration in OpenStack Magnum?

What might help is a dump of the network policies in both versions so we can see how they are being rendered to Calico policy.  `calicoctl get networkpolicy --all-namespaces -o yaml`

**Comment by openstacker** [comment]
Hi @spikecurtis  Thanks for the reply. Here are the security rules we're setting https://github.com/openstack/magnum/blob/master/magnum/drivers/k8s_fedora_coreos_v1/templates/kubecluster.yaml#L932-L1016 between masters and workers

Here are the output of get networkpolicy on v3.3.6:
<pre>
[fedora@k8s-hlz-1-o2ld4or3vl5w-master-0 ~]$ ./calicoctl get networkpolicy --all-namespaces -o yaml
apiVersion: projectcalico.org/v3
items: []
kind: NetworkPolicyList
metadata:
  resourceVersion: "1399258"
</pre>

Here are the output of get networkpolicy on v3.13.1:
<pre>
[core@k8s-6-ivycyrytldox-master-0 ~]$ ./calicoctl get networkpolicy --all-namespaces -o yaml
apiVersion: projectcalico.org/v3
items: []
kind: NetworkPolicyList
metadata:
  resourceVersion: "8708"
</pre>

**Comment by neiljerram** [comment]
Thanks @openstacker , so those outputs indicate no Calico-level networkpolicy, which I think should be fine.  I'm afraid I can't immediately think of a relevant change between Calico v3.3 and v3.13, so please let's try to debug why this is not working with v3.13.

I'm just ramping up on Magnum, but for the scenario in question I think the data path will be like this:

- source pod on worker node
- Calico routing and iptables on worker node
- OpenStack routing or L2 forwarding between the worker node and the master node
- Calico routing and iptables on master node
- destination pod on master node

Could you check if there is an iptables rule that is dropping the traffic, by running `iptables-save -c | grep DROP` on the worker and master nodes?

Also it might help to know what OpenStack routing or L2 forwarding you are using between the worker node and the master node, and whether those nodes are on the same or different OpenStack hosts.

**Comment by neiljerram** [comment]
Actually, one other stab in the dark...  Does Magnum use kubeadm as its Kubernetes installer?  A change in v3.13 was that Calico tries to auto-detect the correct value for CALICO_IPV4POOL_CIDR by looking at the kubeadm config (https://github.com/projectcalico/node/pull/417).  I wonder if something about that process might be going wrong in a Magnum deployment?

**Comment by caseydavenport** [comment]
> after tweaking the yaml file, everything looks good. But we just found one case failed which worked in v3.3.6.

What process did you use to upgrade? I would _not_ expect Calico to work simply by bumping the `image:` within the v3.3 manfiests, for example. I would expect you would need to apply the new manifests from Calico v3.13 (we don't support mismatched manifest and image versions)
