### ISSUE TITLE
bird: Cannot create control socket /var/run/calico/bird.ctl: Address in use

### ISSUE THREAD

**Issue by sadeghrz** [projectcalico/calico#3399]
hi.
We have a k8s cluster created by RKE.
after restarting each worker server we receive :
`bird: Cannot create control socket /var/run/calico/bird.ctl: Address in use`
from calico node container and we have to remove /var/run/calico/bird.ctl directory to solve this problem.

**Comment by spikecurtis** [comment]
Can you give us more information on the versions of Calico, RKE, your operating system, and how you are installing Calico?  Do you know if SELinux or AppArmor are enabled?

**Comment by sadeghrz** [comment]
versions: 
Kubernetes: v1.17.4, 
Calico: v3.13.0, 
RKE: 1.0.5,
OS: ubuntu 16.4

AppArmor status:
apparmor module is loaded.
15 profiles are loaded.
15 profiles are in enforce mode.
----
0 profiles are in complain mode.
188 processes have profiles defined.
188 processes are in enforce mode.
----
0 processes are in complain mode.
0 processes are unconfined but have a profile defined.

We try to upgrading RKE, Kubernetes and Calico but still have same thing. after reboot the os, /var/run/ directory starts as empty directory.
We had the same error in previous versions.

**Comment by spikecurtis** [comment]
My suspicions lie with AppArmor. To verify, can you disable AppArmor entirely or switch it out of enforcing mode for Calico and see if that resolves the issue?

**Comment by sadeghrz** [comment]
Gracias spiki.
fixed by disabling AppArmor.
i'm searching for the root cause.

**Comment by spikecurtis** [comment]
`/var/run/calico/bird.ctl` is a domain socket that bird creates to allow inspection and control over the bird daemon. When it restarts, it has to delete and recreate the domain socket. AppArmor is presumably not allowing this, and hence the error you're seeing.  You'll need to either disable AppArmor or run calico under a profile that allows these actions to be performed.

**Comment by sadeghrz** [comment]
I found something interesting:
before solving the problem it seems calico-node by default use "unconfined" appArmor profile:

```
$ docker inspect {CALICO_NODE_ID} | grep -i armor
"AppArmorProfile": "unconfined",
```

but after i added `"container.apparmor.security.beta.kubernetes.io/calico-node: unconfined" ` annotation to calico-node DaemonSet the result changed to:

```
$ docker inspect {CALICO_NODE_ID} | grep -i armor
"AppArmorProfile": "unconfined",
"apparmor=unconfined",
```

then problem solved!

**Comment by spikecurtis** [comment]
I'm glad you got things working!
