### ISSUE TITLE
Notes about selector subtlety have been lost

### ISSUE THREAD

**Issue by fasaxc** [projectcalico/calico#341]
We've lost the notes that highlight some of the subtleties of selectors:

`notSelector: a=="b"` is not the same as `selector: a!="b"`.  The former matches all packets (from anywhere, even outside the cluster), excluding those from endpoints labelled with a=b.  The latter matches only traffic from known endpoints that are not labeled with a=b.

If you're implementing complex policy, for example to implement tenant isolation.  It's better to use a rule of this form:
```
action: drop
source:
  notSelector: tenant=="my-tenant"
```
than one of this form:
```
action: drop
source:
  selector: tenant!="my-tenant"
```
because the former renders as a (small) ipset whitelist, where only tenant-specific traffic is allowed whereas the latter renders as a large blacklist with every endpoint IP apart from the ones owned by the tenant.  Rendering a whitelist is generally smaller and it's also safer because there aren't any race conditions where traffic is allowed before the blacklist is updated.

**Comment by caseydavenport** [comment]
@fasaxc Don't think this needs to be done in the v2.0.0 release timeframe but would be good to do soon after.
