### ISSUE TITLE
Liveness probe failed: calico/node is not ready: Felix is not live: Get http://localhost:9099/liveness: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

### ISSUE THREAD

**Issue by cann0nf0dder** [projectcalico/calico#3420]
I've noticed this behavior in my clusters, right now on calico 3.12 but it looks to be going back to earlier versions
## Expected Behavior
No Liveness and Readiness warnings 

## Current Behavior

All calico node pods are running 1/1 (no restarts)

# kubectl describe pod calico-node | grep failed
  Warning  Unhealthy  50m (x789 over 39d)  kubelet, w4r008  Liveness probe failed: calico/node is not ready: Felix is not live: Get http://localhost:9099/liveness: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
  Warning  Unhealthy  25m (x725 over 38d)  kubelet, w4r008  Readiness probe failed: calico/node is not ready: felix is not ready: Get http://localhost:9099/readiness: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
  Warning  Unhealthy  6m17s (x723 over 39d)  kubelet, 0r002  Liveness probe failed: calico/node is not ready: Felix is not live: Get http://localhost:9099/liveness: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
  Warning  Unhealthy  52m (x820 over 39d)  kubelet, 003  Liveness probe failed: calico/node is not ready: Felix is not live: Get http://localhost:9099/liveness: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
  Warning  Unhealthy  47m (x794 over 39d)  kubelet, 003  Readiness probe failed: calico/node is not ready: felix is not ready: Get http://localhost:9099/readiness: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
  Warning  Unhealthy  47m (x778 over 39d)    kubelet, 003  Readiness probe failed: calico/node is not ready: felix is not ready: Get http://localhost:9099/readiness: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
  Warning  Unhealthy  9m16s (x744 over 39d)  kubelet, 003  Liveness probe failed: calico/node is not ready: Felix is not live: Get http://localhost:9099/liveiness: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

When curling the endpoint on the affected node:
$ curl -v http://localhost:9099/readiness
* Uses proxy env variable no_proxy == '127.0.0.1, localhost, kubernetes'
*   Trying 127.0.0.1:9099...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 9099 (#0)
> GET /readiness HTTP/1.1
> Host: localhost:9099
> User-Agent: curl/7.65.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 204 No Content
< Date: Tue, 07 Apr 2020 12:37:39 GMT
< 
* Connection #0 to host localhost left intact

When running calico health check within docker container:
calico-node -bird-ready -bird-live
2020-04-07 12:51:32.464 [INFO][8408] health.go 156: Number of node(s) with BGP peering established = 15
calico-node -felix-ready -felix-live
#(no output) 

## Steps to Reproduce (for bugs)

We are pretty much using the generic yaml from calico repo

## Context
Trying to make sure the probes are working as expected

## Your Environment
* Calico version: 3.12
* Orchestrator version (e.g. kubernetes, mesos, rkt): k8s 1.16.6
* Operating System and version: CoreOS

Any suggestions what to look at? thanks!

**Comment by cann0nf0dder** [comment]
needs more investigation on my end..

**Comment by mjagyo** [comment]
> needs more investigation on my end..

any resolution to this? this might help who encountered the same issue. thanks!

**Comment by oxr463** [comment]
@cann0nf0dder any updates?

**Comment by uweenukr** [comment]
have a new install and have this error.

**Comment by 85117921** [comment]
I encounter the same issue, as i checked the port 9099 was not existing , which process will listen to port 9099 ?

**Comment by tunicashashi** [comment]
I too got this issue. Has anybody found solution for it.

No process is running on port 9099

**Comment by cann0nf0dder** [comment]
are you guys still running CoreOS? When we migrated to FedoraCoreOS it has resolved without making any changes to the calico deployment.

**Comment by tunicashashi** [comment]
No, I am using Ubuntu node  with ACRN VM

Normal   Created    3h4m                    kubelet, acrn1-nuc7i7dnhe  Created container calico-node
  Warning  Unhealthy  3h3m (x7 over 3h4m)     kubelet, acrn1-nuc7i7dnhe  Readiness probe failed: calico/node is not ready: felix is not ready: Get http://localhost:9099/readiness: dial tcp 127.0.0.1:9099: connect: connection refused
  Normal   Killing    129m (x20 over 3h3m)    kubelet, acrn1-nuc7i7dnhe  Container calico-node failed liveness probe, will be restarted
  Normal   Pulled     124m (x21 over 3h4m)    kubelet, acrn1-nuc7i7dnhe  Container image "registry.local:9001/quay.io/calico/node:v3.12.0" already present on machine
  Normal   Started    109m (x25 over 3h4m)    kubelet, acrn1-nuc7i7dnhe  Started container calico-node
  Warning  BackOff    9m25s (x561 over 177m)  kubelet, acrn1-nuc7i7dnhe  Back-off restarting failed container
  Warning  Unhealthy  4m31s (x320 over 3h4m)  kubelet, acrn1-nuc7i7dnhe  Liveness probe failed: calico/node is not ready: Felix is not live: Get http://localhost:9099/liveness: dial tcp 127.0.0.1:9099: connect: connection refused

**Comment by cann0nf0dder** [comment]
if it helps here are my probes, rather standard i think
`
livenessProbe:
--
  | exec:
  | command:
  | - /bin/calico-node
  | - -felix-live
  | - -bird-live
  | periodSeconds: 10
  | initialDelaySeconds: 10
  | failureThreshold: 6
  | readinessProbe:
  | exec:
  | command:
  | - /bin/calico-node
  | - -felix-ready
  | - -bird-ready
  | periodSeconds: 10

`

**Comment by liangsqrt** [comment]
I also encounter the same issue.

**Comment by boogiefromzk** [comment]
Also having this problem.

**Comment by h3mmy** [comment]
[may be related?](https://docs.rke2.io/known_issues/#calico-with-vxlan-encapsulation)

**Comment by rajaie-sg** [comment]
In our case, the issue was that the calico-node pods didn't have any CPU requests/limit set.

When a pod ran with heavy CPU usage ran on the node, calico-node got very little CPU time and wasn't able to respond to the liveness/health checks. This caused it to get stuck in a restart loop until the high CPU pod completed.

Setting a CPU request for calico-node pods resolved the issue.

**Comment by arehmandev** [comment]
In my case there was a few things I attempted:
calico daemonset CPU limits
recycling nodes

And then low and behold i found some usage statistics timeouts in some of the pod logs (when set FelixConfig to INFO).

This fixed it for me - turning off usage statistics:

```
kubectl patch felixconfiguration default --type merge -p '{"spec":{"usageReportingEnabled":false}}'
```

Hope it helps
