### ISSUE TITLE
getting the dial tcp 10.96.0.1:443: i/o timeout issues

### ISSUE THREAD

**Issue by mohit5577** [projectcalico/calico#3422]
Hello All,

I have created kubernetes cluster on centos 7 with one master node and 2 worker nodes.
[causer@master deployments]$ kubectl get nodes
NAME STATUS ROLES AGE VERSION
master Ready master 9d v1.18.0
node1 Ready 7d8h v1.18.0
node2 Ready 7d8h v1.18.0

i am using calico cni for networking. All the pods are running fine except the ingress pods on worker nodes
i.e.
[causer@master deployments]$ kubectl get pods --all-namespaces -o wide
NAMESPACE NAME READY STATUS RESTARTS AGE IP NODE NOMINATED NODE READINESS GATES
kube-system calico-kube-controllers-5fc5dbfc47-ktfzc 1/1 Running 2 9d 192.168.219.72 master
kube-system calico-node-bwhff 1/1 Running 2 9d 192.168.29.85 master
kube-system calico-node-mg7rp 1/1 Running 1 7d7h 192.168.29.161 node2
kube-system calico-node-rn9zg 1/1 Running 1 7d7h 192.168.29.16 node1
kube-system coredns-66bff467f8-vkz47 1/1 Running 2 9d 192.168.219.71 master
kube-system coredns-66bff467f8-w4b45 1/1 Running 2 9d 192.168.219.73 master
kube-system etcd-master 1/1 Running 2 9d 192.168.29.85 master
kube-system kube-apiserver-master 1/1 Running 2 9d 192.168.29.85 master
kube-system kube-controller-manager-master 1/1 Running 2 9d 192.168.29.85 master
kube-system kube-proxy-7b9jd 1/1 Running 1 7d7h 192.168.29.161 node2
kube-system kube-proxy-8bbjc 1/1 Running 1 7d7h 192.168.29.16 node1
kube-system kube-proxy-b96b5 1/1 Running 2 9d 192.168.29.85 master
kube-system kube-scheduler-master 1/1 Running 3 9d 192.168.29.85 master
kube-system tiller-deploy-754f98dbfc-f7ztt 1/1 Running 1 7d7h 192.168.104.2 node2
nginx-ingress nginx-ingress-f2lh6 0/1 CrashLoopBackOff 7 16m 192.168.104.3 node2
nginx-ingress nginx-ingress-htclm 0/1 CrashLoopBackOff 7 16m 192.168.166.129 node1
nginx-ingress nginx-ingress-lssvl 1/1 Running 0 16m 192.168.219.74 master

after looking into the logs for failing ingress pods i am getting the following logs

[causer@master deployments]$ kubectl logs nginx-ingress-htclm -n nginx-ingress
I0407 14:34:18.403254 1 main.go:169] Starting NGINX Ingress controller Version=1.6.3 GitCommit=b9378d56
F0407 14:34:48.409730 1 main.go:275] Error trying to get the default server TLS secret nginx-ingress/default-server-secret: could not get nginx-ingress/default-server-secret: Get https://10.96.0.1:443/api/v1/namespaces/nginx-ingress/secrets/default-server-secret: dial tcp 10.96.0.1:443: i/o timeout

Also in the tiller pod i am getting the following error

[causer@master deployments]$ kubectl logs tiller-deploy-754f98dbfc-f7ztt -n kube-system
[main] 2020/04/07 13:19:03 Starting Tiller v2.16.5 (tls=false)
[main] 2020/04/07 13:19:03 GRPC listening on :44134
[main] 2020/04/07 13:19:03 Probes listening on :44135
[main] 2020/04/07 13:19:03 Storage driver is ConfigMap
[main] 2020/04/07 13:19:03 Max history per release is 0
[storage] 2020/04/07 14:41:53 listing all releases with filter
[storage/driver] 2020/04/07 14:42:23 list: failed to list: Get https://10.96.0.1:443/api/v1/namespaces/kube-system/configmaps?labelSelector=OWNER%3DTILLER: dial tcp 10.96.0.1:443: i/o timeout

Anyone else got this issue ? The ingress pod running on master is able to connect with kube api server but the ingress pods running on worker nodes are not able to connect.
Any hint or suggestions will be very helpful. i was told in one of the forum that this is the issue with the Calico configuration https://github.com/nginxinc/kubernetes-ingress/issues/911#issuecomment-610958605  . Can somebody help me in fixing the issue ??

-Regards
Mohit

## Expected Behavior
The IC pods should be up and running.

**Comment by mohit5577** [comment]
we are using version 3.9 Calico

**Comment by tmjd** [comment]
The 10.96.0.1 error suggests an issue reaching the Kube API server using the kubernetes service that kube-proxy should be setting up.
What is your platform your hosts are running on (or are they baremetal)?
One common problem is when using Vagrant (or other setups) where the hosts have multiple interfaces, the wrong address is attempting to be used for the Kube API server. You might need to ensure that the master is advertising/using the IP adddress that should be used for communication between your hosts.
The fact that your ingress controller works on master but not other nodes suggests that multiple interfaces may be the problem too.

**Comment by tmjd** [comment]
I just realized that calico is reporting ready on all nodes though so that makes me think that reaching the Kube API server is working though.
You should do `kubectl get endpoints kubernetes` (it might be necessary to specify namespace) and see if the address for the endpoint is reachable from each of your nodes.
Another thing to try is `curl https://10.96.0.1:443/version` from each of your nodes, they should each be able to reach the kube API server.

**Comment by mohit5577** [comment]
got the issue fixed. Its the problem with the CIDR.

-Regards
 Mohit

**Comment by rahulsharma2020** [comment]
I am still having this issue. Tried changing CIDR and even tried Flannel CNI but in vain.
@mohit5577: Can you let us know what was the problem with your CIDR and how you rectified it?

**Comment by flavono123** [comment]
> One common problem is when using Vagrant (or other setups) where the hosts have multiple interfaces, the wrong address is attempting to be used for the Kube API server.

It is my case.

> You might need to ensure that the master is advertising/using the IP adddress that should be used for communication between your hosts.

I've set `--advertise-address` for kube-apiserver and `--control-plane-endpoint`, `--apiserver-cert-extra-sans` when the cluster set with kubeadm. Somethingelse needed more?

**Comment by anhadgill23** [comment]
Are there any updates on this?

**Comment by ssmuthukumaran** [comment]
am facing this issue, Any updates?

**Comment by echoface** [comment]
same issue here, any updates?

**Comment by pschichtel** [comment]
my checklist for future reference:

1. [ ] replace the IP in the uplink NIC configuration
2. [ ] replace the IP in any relevant `/etc/hosts` entries
3. [ ] replace the IP in `/etc/k0s/k0s.yaml`
4. [ ] replace the IP in `/var/lib/k0s/kubelet.conf` and `/var/lib/k0s/kubelet-bootstrap.conf`
5. [ ] delete the `default/kubernetes` service (will be recreated)
6. [ ] remove any stale kubernete* EndpointSlices if they exist

The `k0s etcd member-list` still shows the old IP, but in a single node setup that doesn't seem to matter.

**Comment by elkinaguas** [comment]
Same issue here. I used Terraform to deploy my nodes with KVM. I'm using Flannel for my network configuration. 

When running `curl https://10.96.0.1:443/version` as @tmjd suggested, I get: `curl: (60) Peer's Certificate issuer is not recognized`

If I run the curl in insecure mode (`curl -k https://10.96.0.1:443/version`), the node can retrieve the version.

**Comment by elkinaguas** [comment]
I had the same issue when deploying applications with helm. What helped me solved the problem was disabling the firewall in all my nodes (master and workers). I know this is not a permanent solution, but it might help you work your way towards a solution by modifying the firewall rules and see what works for you.

**Comment by jiangxiaoqiang** [comment]
> I had the same issue when deploying applications with helm. What helped me solved the problem was disabling the firewall in all my nodes (master and workers). I know this is not a permanent solution, but it might help you work your way towards a solution by modifying the firewall rules and see what works for you.

I did not enable the firewall but still facing this issue.

**Comment by midnight-wonderer** [comment]
I solved mine, basically, my Kubernetes API server is advertising IP addresses from the wrong network interface.

I used MicroK8s BTW; I followed https://microk8s.io/docs/configure-host-interfaces by setting the `--advertise-address` argument.
To track down this issue, I used `kubectl describe` to inspect the service.

**Comment by ahinsutime** [comment]
I solved my issue too.

I will share my trobleshooting details for anyone were in no luck like me and frustrated due to the error:
```
# On control node, look for network interface starts with "default via ..." 
# Example: default via 10.111.0.1 dev ens5 
ip addr show

# Or using following command:
# Example: ens5
ip route show | awk '/^default/ {print $5}'

# Get your network interface's IP
# Example: inet 10.123.0.34/32 brd 10.123.0.37 scope global dynamic ens5
ip addr show dev ens5 | grep 'inet '

# Or using following command:
# Example: 10.123.0.34
ip addr show dev ens5 | awk '/inet / {print $2}' | cut -d/ -f1

# Then perform control plane node initialization based on the IP:
kubeadm init \
  --apiserver-advertise-address=10.123.0.34 \
  --pod-network-cidr=192.168.0.0/16

# For your worker node, do something like:
kubeadm join 10.123.0.34:6443 --token <token> --discovery-token-ca-cert-hash sha256:<hash>

```
