### ISSUE TITLE
Network and firewalld configuration for local multi-pods/nodes cluster.

### ISSUE THREAD

**Issue by LSmyrnaios** [projectcalico/calico#3425]
## Context
Hi, I am having problems in my kubernetes cluster, I cannot make possible for pods to communicate with each other.
I read lots of documentation and blogs online, but in the end, I am not sure what ports and protocols, as well as other configurations to apply so that pod-to-pod communication can work.

Is there a summary of all the network and firewall configurations somewhere?

Thank you

## Your Environment

* Calico version: 3.13
* Orchestrator version (e.g. kubernetes, mesos, rkt): Kubernetes v1.15.11
* Operating System and version: Ubuntu 18.04

**Comment by tmjd** [comment]
The Network Requirements section https://docs.projectcalico.org/getting-started/kubernetes/requirements#network-requirements should provide that information.

Where are your hosts running? Some environments require certain configurations as they might block some traffic by default or not allow some specific traffic.

**Comment by LSmyrnaios** [comment]
Hi @tmjd , I have already tried the IP-IP configuration, but it seems that it doesn't work for me.
I have the related package "ipip" installed on all hosts, as well as enabled the protocol in "firewalld".

My hosts' configuration is the following:
- master: local machine (desktop)
firewalld configuration: 
`public (active)`
`  target: default`
`  icmp-block-inversion: no`
`  interfaces: enp2s0`
`  sources: `
`  services: ssh dhcpv6-client`
`  ports: 10250/tcp 10255/tcp 6443/tcp 2379-2380/tcp 10248/tcp 10251-10252/tcp 8080/tcp 8001/tcp 8500/tcp 9090/tcp 22/tcp`
`  protocols: `
`  masquerade: no`
`  forward-ports: `
`  source-ports: `
`  icmp-blocks: `
`  rich rules: `
`        rule protocol value="ipip" accept`

- 2 workers: remote VMs
firewalld configuration: 
`public`
`  target: default`
`  icmp-block-inversion: no`
`  interfaces: `
`  sources: `
`  services: ssh dhcpv6-client`
`  ports: 10250/tcp 10255/tcp 30000-32767/tcp 9090/tcp 22/tcp`
`  protocols: `
`  masquerade: no`
`  forward-ports: `
`  source-ports: `
`  icmp-blocks: `
 ` rich rules: `
`	rule protocol value="ipip" accept`

**Comment by tmjd** [comment]
It is typically suggested to disable other firewalls on hosts as they can interfere.
Something to verify on your hosts that the kubernetes service is reachable from all your hosts. Calico depends on that being functional for reaching the kubernetes API.
