### ISSUE TITLE
Pod is running normally, but there is no eth0 network interface in it and can not be accessed.

### ISSUE THREAD

**Issue by fyery-chen** [projectcalico/calico#3439]
## Expected Behavior
I can access this pod successfully and there should be an `eth0` network interface in it.

## Current Behavior
When I troubleshot the cluster network, I found that  I can't access one pod via its IP, so I went into this pod and run the following command `ifconfig`, 
```
/app # ifconfig
lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1 
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)
``` 
What surprised me is that there is no `eth0` network interface in it, but the pod has podIP and is running normally.

## Possible Solution
Check the network of pod whether it is OK.

## Your Environment

* Calico version v3.6.0
* Orchestrator version (e.g. kubernetes, mesos, rkt): kubernetes
* Operating System and version: 
OS: CentOS Linux 7
kernel: 4.9.99
* Link to your project (optional):

**Comment by caseydavenport** [comment]
Do you have a way to reproduce this?

Or, do you have logs from the CNI plugin for when this pod was launched?

Afraid there isn't a lot to go on here without those things.
