### ISSUE TITLE
Support ExternalTrafficPolicy for Service ExternalIP advertisement

### ISSUE THREAD

**Issue by caseydavenport** [projectcalico/calico#3443]
https://github.com/kubernetes/kubernetes/commit/efc4b121862f1a7ba08be397114524b46145a279

Prior to the linked commit, externalIPs didn't not respect the externalTrafficPolicy field on services.

After that commit, they optionally can do so. We should update our service advertisement logic to advertise /32 routes for externalIPs with externalTrafficPolicy=Local so that we similarly respect the field for external IPs. We should do this once the above commit has made it into a release of k8s.

We should also look a bit more at whether we need a toggle for this behavior. In the linked commit there seems to be a feature gate for it - not sure if that is there to stay, or if it will go away and always be enabled at some point in the future.

**Comment by JensErat** [comment]
Exact duplicate of #3408

**Comment by arianvp** [comment]
Are you sure this is not implemented? 
Seems to work fine for me.  I see `/32` (well; in my case `/128` because IPv6) advertised for external IPs just fine...

**Comment by caseydavenport** [comment]
> Exact duplicate of #3408

Well, that's bizarre. I'm not sure how that happened! I'll close the other.

> Seems to work fine for me. I see /32 (well; in my case /128 because IPv6) advertised for external IPs just fine...

Honestly, I'm not 100% sure. I assumed that we would need to do this but its possible we jumped the gun and implemented this in advance of it actually existing in k8s!

**Comment by caseydavenport** [comment]
And you're right. Just checked the code, and it looks like we already do this. Sweet.
