### ISSUE TITLE
Update Calico the hard way tutorial to use the latest Calico version

### ISSUE THREAD

**Issue by lmm** [projectcalico/calico#3446]
The hard way tutorial was written using v3.8.0. It would be nice if the tutorial used a more recent Calico version. (Thanks to @xieyanker for raising this issue!)

I think we just need to bump the versions used in the tutorial and run through it, making sure firstly that everything works, but also that the tutorial text is adjusted to reflect any changes since v3.8.0

**Comment by mhmxs** [comment]
I'm glad to walk through the hard way and verify it with version `v3.13.3`
