### ISSUE TITLE
WAIT_FOR_DATASTORE not respected for k8s datastore driver

### ISSUE THREAD

**Issue by caseydavenport** [projectcalico/calico#345]
This means that if the kube-proxy isn't running (e.g on a master node) calico/node will crash.

**Comment by caseydavenport** [comment]
Assigning to @2blesd2bstresd because this will be fixed by the startup work he's doing.

**Comment by caseydavenport** [comment]
This should be fixed but needs re-testing for v2.1.0.

**Comment by heschlie** [comment]
@caseydavenport seems to have hit this doing something else, looks like it might still be an issue

**Comment by heschlie** [comment]
@caseydavenport reports that this is now working properly in k8s and etcd
