### ISSUE TITLE
Include kubernetes as datastore option in "network policy using Istio tutorial" 

### ISSUE THREAD

**Issue by p-tang** [projectcalico/calico#3450]
In the "Enforce network policy using Istio" tutorial, the demo is currently set up using etcd as the backing datastore. To be consistent with other tutorials, the option of using K8s datastore should also be included.

**Comment by tmjd** [comment]
Could you please provide a link to the document you are referring to?
The document I found https://docs.projectcalico.org/security/enforce-policy-istio does not seem to indicate any specific datastore option, and neither does the "enable application layer policy" as far as I can tell.

**Comment by p-tang** [comment]
Here's the link: https://docs.projectcalico.org/security/tutorials/app-layer-policy/enforce-policy-istio

**Comment by tmjd** [comment]
Are you referring to the following?
> a microservice that serves up account summaries, and an etcd datastore.
That is the demo itself that is using an etcd datastore, it shouldn't matter what database the demo uses.
Please if I'm misunderstanding something please provide a snippet from the doc that you are referring to that shows the text. Thanks
