### ISSUE TITLE
Missing configmap resource when starting etcd-backed calicoctl as pod

### ISSUE THREAD

**Issue by p-tang** [projectcalico/calico#3451]
When starting etcd-backed calicoctl as a Kubernetes pod according to https://docs.projectcalico.org/getting-started/calicoctl/install#installing-calicoctl-as-a-kubernetes-pod, a missing configmap error occurs. It would be helpful if the documentation could provide guidance on how to produce the missing resource.

**Comment by caseydavenport** [comment]
How did you install Calico originally?

**Comment by p-tang** [comment]
I'm following the [Rancher quickstart guide for AWS](https://rancher.com/docs/rancher/v2.x/en/quick-start-guide/deployment/amazon-aws-qs/). Default CNI is Canal. Within the pod, there's a container with `rancher/calico-node:v3.13.0`.

**Comment by caseydavenport** [comment]
The ConfigMap is in our standard manifests, I guess the ones Rancher use have removed it. 

https://docs.projectcalico.org/manifests/calico.yaml
