### ISSUE TITLE
Flannel to Calico migration failed on a one node development cluster

### ISSUE THREAD

**Issue by davesargrad** [projectcalico/calico#3452]
I've followed the calico process for migrating from flannel to calico.

The flannel-migration pod simply pends.

![image](https://user-images.githubusercontent.com/48793689/79996351-5ed93a00-8486-11ea-9cc1-ba8a8d6f54ca.png)

My cluster was healthy prior to this.
The only two commands I ran are seen in the following:
![image](https://user-images.githubusercontent.com/48793689/79996419-7284a080-8486-11ea-9a17-dbcf261239f9.png)

The pods in kube-system
![image](https://user-images.githubusercontent.com/48793689/79996480-83351680-8486-11ea-8c8a-cdc0baa4fed5.png)

![image](https://user-images.githubusercontent.com/48793689/79996636-ab247a00-8486-11ea-8c1e-85ced39f12e1.png)

**Comment by tmjd** [comment]
@song-jiang is this expected to work? I think I remember that there is an issue with running migration on a one node cluster.

**Comment by davesargrad** [comment]
@tmjd Thanks. I didnt see that in the docs.


I just quickly reset my k8s cluster.. it was the right way to go anyways.

So I've got calico installed properly now.

**Comment by song-jiang** [comment]
Flannel migration would not work on one node cluster as the migration controller requires one working node (node not in the process of migration) to run.

**Comment by davesargrad** [comment]
@song-jiang Ty.
