### ISSUE TITLE
Can I block connection between a pod and elasticcache in AWS

### ISSUE THREAD

**Issue by vrathore18** [projectcalico/calico#3456]
I have my K8s setup(Pods A,B and C) and Elastic cache ("xxx.xxxx.xx.cache.amazonaws.com")in AWS. Right now all my pods have access to elastic cache.

I am looking for a solution by which I can restrict the communication. I read about calico but I understand I can block communication between two pods. Is there any way I can allow A to communicate with xxx.xxxx.xx.cache.amazonaws.com but block Pods B and C.

Thanks guy for the great project.

**Comment by tmjd** [comment]
You could try creating a network set and add IPs for it but the IP addresses are probably difficult to collect and they probably change too.
Of course if you can try to restrict all outgoing traffic then only allow A egress in general but that is probably not feasible.

There is an option available with Calico Enterprise to do this type of thing, check out https://docs.projectcalico.org/security/calico-enterprise/egress-access-controls#egress-access-control-to-external-endpoints.
