### ISSUE TITLE
Readiness probe failed, and Liveness Probe Failed

### ISSUE THREAD

**Issue by Juangunner4** [projectcalico/calico#3457]
## Expected Behavior
I installed calico for networking on my CentOS8 cluster using kubernetes and pods should run on each node

## Current Behavior
All the nodes status is Not Ready for Calico pods, and they are doing a CrashLoopBackOff
## Possible Solution
No Idea, what the solution may be

## Steps to Reproduce (for bugs)
https://docs.projectcalico.org/getting-started/kubernetes/quickstart I used this guide for the testing on one node.

## Context
I am trying to deploy applications to my nodes. but the service is not ready

default       nginx-f89759699-btwvz                     1/1     Running            0          24h     192.168.184.65   node4.engr         <none>           <none>
kube-system   calico-kube-controllers-8db7766b4-4l48c   0/1     CrashLoopBackOff   19         80m     10.3.60.115      node14.engr        <none>           <none>
kube-system   calico-node-44cqd                         0/1     CrashLoopBackOff   25         80m     10.3.60.119      node18.engr        <none>           <none>
kube-system   calico-node-4kzf4                         0/1     Running            25         80m     10.3.60.106      node5.engr         <none>           <none>
kube-system   calico-node-88d46                         0/1     CrashLoopBackOff   25         80m     10.3.60.117      node16.engr        <none>           <none>
kube-system   calico-node-8g9cc                         0/1     CrashLoopBackOff   25         80m     10.3.60.107      node6.engr         <none>           <none>
kube-system   calico-node-98k9v                         0/1     CrashLoopBackOff   25         80m     10.3.60.112      mail.node11.engr   <none>           <none>
kube-system   calico-node-b7ndw                         0/1     CrashLoopBackOff   25         80m     10.3.60.114      node13.engr        <none>           <none>
kube-system   calico-node-c6wz5                         0/1     Running            29         80m     10.3.60.196      masternode.engr    <none>           <none>
kube-system   calico-node-gkbt2                         0/1     CrashLoopBackOff   25         80m     10.3.60.104      node3.engr         <none>           <none>
kube-system   calico-node-hpgf9                         0/1     CrashLoopBackOff   25         80m     10.3.60.108      node7.engr         <none>           <none>
kube-system   calico-node-hwlh6                         0/1     Pending            0          80m     <none>           node1.engr         <none>           <none>
kube-system   calico-node-q74jq                         0/1     CrashLoopBackOff   25         80m     10.3.60.195      node9.engr         <none>           <none>
kube-system   calico-node-rk4qm                         0/1     CrashLoopBackOff   25         80m     10.3.60.116      node15.engr        <none>           <none>
kube-system   calico-node-rltdn                         0/1     CrashLoopBackOff   25         80m     10.3.60.113      node12.engr        <none>           <none>
kube-system   calico-node-sxpnm                         0/1     CrashLoopBackOff   25         80m     10.3.60.105      node4.engr         <none>           <none>
kube-system   calico-node-t8q2j                         0/1     CrashLoopBackOff   25         80m     10.3.60.111      node10.engr        <none>           <none>
kube-system   calico-node-tgxtm                         0/1     CrashLoopBackOff   25         80m     10.3.60.115      node14.engr        <none>           <none>
kube-system   calico-node-vbbfh                         0/1     Running            17         80m     10.3.60.109      node8.engr         <none>           <none>
kube-system   calico-node-vggsj                         0/1     CrashLoopBackOff   25         80m     10.3.60.103      node2.engr         <none>           <none>
kube-system   calico-node-wlh9m                         0/1     CrashLoopBackOff   25         80m     10.3.60.118      node17.engr        <none>           <none>
kube-system   etcd-masternode.engr                      1/1     Running            3          4d21h   10.3.60.196      masternode.engr    <none>           <none>
kube-system   kube-apiserver-masternode.engr            1/1     Running            3          4d21h   10.3.60.196      masternode.engr    <none>           <none>
kube-system   kube-controller-manager-masternode.engr   1/1     Running            3          4d21h   10.3.60.196      masternode.engr    <none>           <none>
kube-system   kube-proxy-2fc6z                          1/1     Running            1          4d20h   10.3.60.113      node12.engr        <none>           <none>
kube-system   kube-proxy-4phvl                          1/1     Running            1          4d20h   10.3.60.109      node8.engr         <none>           <none>
kube-system   kube-proxy-5pw46                          1/1     Running            1          4d20h   10.3.60.106      node5.engr         <none>           <none>
kube-system   kube-proxy-6hw2r                          1/1     Running            1          4d20h   10.3.60.104      node3.engr         <none>           <none>
kube-system   kube-proxy-drqpz                          1/1     Running            1          4d20h   10.3.60.119      node18.engr        <none>           <none>
kube-system   kube-proxy-hbtmd                          1/1     Running            1          4d20h   10.3.60.195      node9.engr         <none>           <none>
kube-system   kube-proxy-j4mfw                          1/1     Running            1          4d20h   10.3.60.112      mail.node11.engr   <none>           <none>
kube-system   kube-proxy-m22r5                          1/1     Running            0          4d20h   10.3.60.120      node1.engr         <none>           <none>
kube-system   kube-proxy-mrnjv                          1/1     Running            1          4d20h   10.3.60.116      node15.engr        <none>           <none>
kube-system   kube-proxy-qxwsp                          1/1     Running            1          4d20h   10.3.60.111      node10.engr        <none>           <none>
kube-system   kube-proxy-r25mx                          1/1     Running            1          4d20h   10.3.60.105      node4.engr         <none>           <none>
kube-system   kube-proxy-sx96s                          1/1     Running            1          4d20h   10.3.60.103      node2.engr         <none>           <none>
kube-system   kube-proxy-szrbx                          1/1     Running            1          4d20h   10.3.60.114      node13.engr        <none>           <none>
kube-system   kube-proxy-t6wvd                          1/1     Running            1          4d20h   10.3.60.107      node6.engr         <none>           <none>
kube-system   kube-proxy-vpfrr                          1/1     Running            1          4d20h   10.3.60.108      node7.engr         <none>           <none>
kube-system   kube-proxy-vtqvw                          1/1     Running            3          4d21h   10.3.60.196      masternode.engr    <none>           <none>
kube-system   kube-proxy-wkkb7                          1/1     Running            1          4d20h   10.3.60.117      node16.engr        <none>           <none>
kube-system   kube-proxy-wwk9l                          1/1     Running            1          4d20h   10.3.60.118      node17.engr        <none>           <none>
kube-system   kube-proxy-xfmpl                          1/1     Running            1          4d20h   10.3.60.115      node14.engr        <none>           <none>
kube-system   kube-scheduler-masternode.engr            1/1     Running            3          4d21h   10.3.60.196      masternode.engr    <none>           <none>
sonobuoy      sonobuoy                                  0/1     Terminating        0          24h     <none>           node8.engr         <none>           <none>

## Your Environment

* Calico version Using Kubernetes to install yaml
* Orchestrator version (e.g. kubernetes, mesos, rkt): Kubernetes
* Operating System and version: CentOS8
* Link to your project (optional):

**Comment by fasaxc** [comment]
Try looking at the logs for one of the calico-node pods, that should tell you what's wrong.

**Comment by tmjd** [comment]
It looks like we still haven't set the IptablesBackend configuration to "Auto" by default and I think CentOS 8 is using the nft backend for iptables. So you may need to add an environment variable to the calico-node daemonset of FELIX_IPTABLESBACKEND set to "Auto" (or NFT).
