### ISSUE TITLE
Running a BGP peer in a pod

### ISSUE THREAD

**Issue by ldx** [projectcalico/calico#3466]
## Expected Behavior

Installed calico in an on-prem kubernetes cluster (right now I'm testing this out on my laptop via VMs). Nodes are all in the same subnet: 172.17.0.0/16. The pod CIDR is 10.244.0.0/16. I'm running a VPN client in a pod that establishes a tunnel to an AWS VPN gateway. I added gobgpd to the pod to be able to peer with the VPN gateway. BGP between gobgpd and the VPN gateway works fine.

I also added the pod as a BGP peer to calico (same ASN as the one used by calico, full mesh). BGP sessions established and working fine:

    root@aws-vpn-client-6c7697c5c6-kvxt7:/# gobgp global
    AS:        65220
    Router-ID: 10.244.0.71
    Listening Port: 179, Addresses: 0.0.0.0, ::
    root@aws-vpn-client-6c7697c5c6-kvxt7:/# gobgp n
    Peer             AS  Up/Down State       |#Received  Accepted
    172.17.0.2    65220 00:12:07 Establ      |        6         6
    172.17.0.3    65220 00:12:07 Establ      |        3         3
    172.17.0.4    65220 00:12:07 Establ      |        5         5
    169.254.10.21 64620 00:03:47 Establ      |        1         1
    169.254.30.41 64620 00:03:52 Establ      |        1         1

The VPC CIDR is exported to the calico peers:

        root@aws-vpn-client-6c7697c5c6-kvxt7:/# gobgp n 172.17.0.4 adj-out
       ID  Network              Next Hop             AS_PATH              Attrs
       2   10.10.0.0/16         10.244.0.71          64620                [{Origin: i} {Med: 0} {LocalPref: 100}]

However, the route only works on the node where the pod runs:

    root@minikube-m03 /]# ip route ls 10.10.0.0/16
    10.10.0.0/16 via 10.244.0.71 dev cali81c6636cdbf proto bird

On the other nodes it's unreachable:

    [root@minikube /]# ip route ls 10.10.0.0/16
    unreachable 10.10.0.0/16 proto bird

I understand that this is due to the fact that recursive next hop resolving in bird only works if the corresponding /32 route for the next hop is present. Obviously I don't want to add this manually to every node.

## Current Behavior

Routes to the VPC are unreachable on every node except the node running my BGP agent and tunnel.

## Steps to Reproduce (for bugs)

I can provide a step-by-step guide on how to set up an environment if needed.

## Your Environment

* Calico version calico/node:v3.13.2
* Orchestrator version (e.g. kubernetes, mesos, rkt): kubernetes v1.18.0
* Operating System and version: Ubuntu 19.10
* Link to your project (optional):

**Comment by caseydavenport** [comment]
> I understand that this is due to the fact that recursive next hop resolving in bird only works if the corresponding /32 route for the next hop is present

I'm not 100% sure, but feel a little surprised about this. Shouldn't recursive NH resolution be able to resolve from destination -> pod IP -> host running that pod? Since I'd expect BIRD to have routes similar to this:

- 10.10.0.0/16 via 10.244.0.71
- 10.244.0.0/26 via 172.17.0.1
- 172.17.0.1 dev eth0 

So it should be able to resolve the NH to the node hosting the pod. It's possible that I'm misunderstanding something about the situation, though!

**Comment by ldx** [comment]
> > I understand that this is due to the fact that recursive next hop resolving in bird only works if the corresponding /32 route for the next hop is present
> 
> I'm not 100% sure, but feel a little surprised about this. Shouldn't recursive NH resolution be able to resolve from destination -> pod IP -> host running that pod? Since I'd expect BIRD to have routes similar to this:
> 
>     * 10.10.0.0/16 via 10.244.0.71
> 
>     * 10.244.0.0/26 via 172.17.0.1
> 
>     * 172.17.0.1 dev eth0

The nodes have a 172.17.0.0/16 route, and a default route via 172.17.0.1. They also have the correct pod CIDR route for each other, e.g. 10.244.0.0/26 via the correct node. But it seems BIRD can't do a recursive route resolution when it can't be resolved via a direct hop; i.e. if I add the route "10.244.0.71/32 via 172.17.0.4" to all nodes, BIRD will add the "10.0.0.0/16 via 10.244.0.71" route on all nodes (so it's not in the unreachable state anymore). It's just not something I would like to do, since I'd like to avoid any manual steps.

> 
> 
> So it should be able to resolve the NH to the node hosting the pod. It's possible that I'm misunderstanding something about the situation, though! If that is true, then something else must be going on.

I think your understanding is correct.
