### ISSUE TITLE
Release 3.12.1 lists on website not not available via Github

### ISSUE THREAD

**Issue by mmellin** [projectcalico/calico#3484]
The release notes for v3.12 state that there is a v3.12.1 version with links to downloads but which end in 404 errors.  https://docs.projectcalico.org/archive/v3.12/release-notes/

There are also no releases or tags in the github repo to account for this version.

## Expected Behavior

Existing links in the documentation would provide access to download that version software (v3.12.1).

## Current Behavior

Links end in 404 errors.  No release v3.12.1 exists in Github.

## Possible Solution

N/a

## Steps to Reproduce (for bugs)

Visit release notes page, click on "release archive" for v3.12.1.

## Context

My main question is which version is considered the most stable for basic CNI (no network policy, no BGP usage) with K8s 1.17+?

## Your Environment

N/a

**Comment by tmjd** [comment]
Thank you for bringing that to our attention.
Going to https://docs.projectcalico.org/introduction/ will take you to the latest docs, install options, notes for the latest release. The current version is v3.13.3 and what we would suggest for any new install.
There are no Calico installation options that do not provide network policy but the default is allow all traffic.
'no BGP usage', BGP is the default and typically is not a problem. I would suggest you start with a default install in a test environment and then possibly consider different installation/configuration options.

**Comment by mmellin** [comment]
@tmjd Thank you.
