### ISSUE TITLE
Calico does not create tunl0 interface on ARM64 Ubuntu 16.04

### ISSUE THREAD

**Issue by mewais** [projectcalico/calico#3507]
## Your Environment

We have a hybrid (mixed AMD64/ARM64) High Availability kubernetes cluster consisting of 11 nodes total.

### AMD64
We have 10 VMs, all Ubuntu 18.04 server and AMD64 based, running `uname -a` on any of them yields:
```
Linux worker-01 4.15.0-99-generic #100-Ubuntu SMP Wed Apr 22 20:32:56 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```
and `cat /etc/*-release` is:
```
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.4 LTS"
NAME="Ubuntu"
VERSION="18.04.4 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.4 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```
These VMs serve as follows: 3 HA masters, and 7 workers.

### ARM64
We also have one ARM64 board, with Ubuntu 16.04 installed on it. This board also serves as a worker node, `uname -a` outputs this:
```
Linux mpsoc10 4.14.0-00002-g3f7dc94 #13 SMP Tue Dec 24 12:41:43 EST 2019 aarch64 aarch64 aarch64 GNU/Linux
```
and `cat /etc/*-release` is:
```
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.6 LTS"
NAME="Ubuntu"
VERSION="16.04.6 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.6 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
```

### Kubernetes Version
```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-21T01:25:41Z", GoVersion:"go1.13.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T11:48:36Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```
### Configuration
Calico is deployed to kubernetes directly as follows:
```
https://docs.projectcalico.org/v3.11/manifests/calico.yaml
perl -pi -e 's/192.168.0.0\/16/10.84.32.0\/24/gi;' calico.yaml       # To change to our Pod CIDR
kubectl apply -f calico.yaml
```

## Current Behavior

1. Calico is deployed successfully on all nodes, no events or restarts:
```
NAME                                       READY   STATUS    RESTARTS   AGE   IP            NODE                NOMINATED NODE   READINESS GATES
calico-kube-controllers-75d56dfc47-n55sm   1/1     Running   0          69m   10.84.32.68   storage-worker-02   <none>           <none>
calico-node-9778j                          1/1     Running   0          69m   10.84.31.1    master-01           <none>           <none>
calico-node-j4b62                          1/1     Running   0          69m   10.84.31.11   mpsoc10             <none>           <none>
calico-node-kb8fk                          1/1     Running   0          69m   10.84.31.10   worker-04           <none>           <none>
calico-node-l7mgc                          1/1     Running   0          69m   10.84.31.9    worker-03           <none>           <none>
calico-node-ncz4d                          1/1     Running   0          69m   10.84.31.7    worker-01           <none>           <none>
calico-node-nhb8k                          1/1     Running   0          69m   10.84.31.5    storage-worker-02   <none>           <none>
calico-node-qmqdt                          1/1     Running   0          69m   10.84.31.4    storage-worker-01   <none>           <none>
calico-node-t6jsr                          1/1     Running   0          69m   10.84.31.8    worker-02           <none>           <none>
calico-node-ttvg7                          1/1     Running   0          69m   10.84.31.2    master-02           <none>           <none>
calico-node-x8ngs                          1/1     Running   0          69m   10.84.31.6    storage-worker-03   <none>           <none>
calico-node-z29hh                          1/1     Running   0          69m   10.84.31.3    master-03           <none>           <none>
```
2. I can check that all the AMD64/Ubuntu 18.04 nodes have `tunl0` ports through `ip a`, for example:
```
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: enp0s3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether 00:11:22:33:22:11 brd ff:ff:ff:ff:ff:ff
    inet 10.84.31.7/16 brd 10.84.255.255 scope global enp0s3
       valid_lft forever preferred_lft forever
    inet6 fe80::a00:27ff:feb5:e12c/64 scope link 
       valid_lft forever preferred_lft forever
3: docker0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default 
    link/ether 02:42:c4:80:05:99 brd ff:ff:ff:ff:ff:ff
    inet 172.17.0.1/16 brd 172.17.255.255 scope global docker0
       valid_lft forever preferred_lft forever
6: tunl0@NONE: <NOARP,UP,LOWER_UP> mtu 1440 qdisc noqueue state UNKNOWN group default qlen 1000
    link/ipip 0.0.0.0 brd 0.0.0.0
    inet 10.84.32.65/32 brd 10.84.32.65 scope global tunl0
       valid_lft forever preferred_lft forever
```
3. The ARM64/Ubuntu 16.04 node does not have `tunl0`:
```
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
2: dummy0: <BROADCAST,NOARP> mtu 1500 qdisc noop state DOWN group default qlen 1000
    link/ether 8e:c1:30:f5:ef:1e brd ff:ff:ff:ff:ff:ff
3: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 00:11:22:33:22:11 brd ff:ff:ff:ff:ff:ff
    inet 10.84.31.11/16 brd 10.84.255.255 scope global eth0
       valid_lft forever preferred_lft forever
4: teql0: <NOARP> mtu 1500 qdisc noop state DOWN group default qlen 100
    link/void 
5: sit0@NONE: <NOARP> mtu 1480 qdisc noop state DOWN group default qlen 1000
    link/sit 0.0.0.0 brd 0.0.0.0
6: docker0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default 
    link/ether 02:42:2b:b7:6c:f1 brd ff:ff:ff:ff:ff:ff
    inet 172.17.0.1/16 brd 172.17.255.255 scope global docker0
       valid_lft forever preferred_lft forever
```
4. Anything running on the ARM64 node is unable to communicate to/from any pods or services on the AMD64 nodes, but the AMD64 nodes can communicate together just fine. This was tested by running a simple alpine image `kubectl run -it --rm --restart=Never alpine --image=alpine sh` and pinging all used pod IPs.
5. Running `kubectl logs calico-node-j4b62 -n kube-system` where `calico-node-j4b62` is the pod running on the ARM64 yields the following 
[arm64.log](https://github.com/projectcalico/calico/files/4584133/arm64.log) which includes a lot of errors about `Failed to get IPIP tunnel device` and similar.
6. In the [following page](https://docs.projectcalico.org/getting-started/kubernetes/requirements) it mentions:
**Note:** Many Linux distributions, such as most of the above, include NetworkManager. By default, NetworkManager does not allow Calico to manage interfaces. If your nodes have NetworkManager, complete the steps in [Preventing NetworkManager from controlling Calico interfaces](https://docs.projectcalico.org/maintenance/troubleshooting#configure-networkmanager) before installing Calico.
However, doing so didn't fix/help the problem.

## Expected Behavior

Have tunl0 created on all nodes including the ARM64. Be able to communicate between all nodes.

## Steps to Reproduce (for bugs)

1. [Setup primary master](https://github.com/mewais/KubernetesCluster/blob/master/master-01_setup.sh), includes deploying calico. The IPs and CIDRs are different
2. Setup [second](https://github.com/mewais/KubernetesCluster/blob/master/master-02_setup.sh) and [third](https://github.com/mewais/KubernetesCluster/blob/master/master-03_setup.sh) masters
3. [Setup worker nodes](https://github.com/mewais/KubernetesCluster/blob/master/worker_setup.sh), both ARM64 and AMD64
4. Run `ip a` on the ARM64 and AMD64 nodes to check out that `tunl0` is missing

**Comment by mewais** [comment]
Hours later, I think I found the issue. We use a custom kernel for the ARM64 nodes, which is lacking a lot of the kernel modules required by Calico (e.g. IPIP and others). The full list of kernel modules needed can be found [here](https://docs.projectcalico.org/getting-started/kubernetes/requirements#kernel-dependencies)

I will be building a new kernel with the required modules, and will report back with the results and whether or not this fixed the issue.

**Comment by mewais** [comment]
I can verify that building a kernel with the required modules has indeed fixed my problem.

I'm thus closing this.

**Comment by kdheejb7** [comment]
I'm having the same problem.
Have you installed all of the kernel modules mentioned [here](https://docs.projectcalico.org/getting-started/kubernetes/requirements#kernel-dependencies)? Can you tell me which module you installed?
