### ISSUE TITLE
Default main registry for container images

### ISSUE THREAD

**Issue by bmangoen** [projectcalico/calico#3520]
When installing OpenShift 4 with Calico as CNI plugin, the [tigera-operator](https://docs.projectcalico.org/manifests/ocp/tigera-operator/02-tigera-operator.yaml) manifest uses the images: `quay.io/tigera/operator:v1.3.4` and `calico/ctl:v3.13.3`.

Why do you not use a main registry for these images?

NB: These images are already available on the both registries (`quay.io` or `docker.io`).

## Expected Behavior
The [tigera-operator](https://docs.projectcalico.org/manifests/ocp/tigera-operator/02-tigera-operator.yaml) manifest could use the same registry for the both images: `tigera/operator:v1.3.4` and `calico/ctl:v3.13.3`

## Current Behavior
The [tigera-operator](https://docs.projectcalico.org/manifests/ocp/tigera-operator/02-tigera-operator.yaml) manifest uses different registries for the following images: `tigera/operator:v1.3.4` (quay.io) and `calico/ctl:v3.13.3` (docker.io)

## Possible Solution
Modify the default value of `template "tigera-operator.image" .Values.tigeraOperator` or `.Values.calicoctl.image` by prefixing by the default main registry.

For example, it could be done by modifying the values of `defaults.values.imageNames.calicoctl` by `quay.io/calico/ctl` into the [_config.yaml](https://github.com/projectcalico/calico/blob/master/_config.yml).

## Steps to Reproduce (for bugs)
N/A

## Context
In customer production environment, only images from an unique and main registry (in my case `quay.io`) are allowed to be pulled.

## Your Environment
* Calico version: latest
* Installation on OpenShift 4.4

**Comment by caseydavenport** [comment]
I think the tigera/operator is the outlier here - all of the other manifests use docker hub to pull their images, and that is intentional since DockerHub supports multi-arch manifests. Quay is used as a backup.

To change this, we'd need to start pushing the tigera/operator image to docker hub and then update the documentation to use that image. 

This of course wouldn't help your requirement that all images are pulled from quay. But, you can always pull the image and push it to your own registry.

**Comment by onedr0p** [comment]
@caseydavenport Quay now supports multiarch images and does not rate limit. It would be good to revisit this, build the images and push to Quay and default to them to avoid Docker Hubs rate limits. Thanks.

Related: https://github.com/projectcalico/calico/issues/4833
