### ISSUE TITLE
kubeadm doc needs to explain what it's doing

### ISSUE THREAD

**Issue by gunjan5** [projectcalico/calico#353]
kubeadm doc (http://docs.projectcalico.org/v2.0/getting-started/kubernetes/installation/hosted/kubeadm) just says `kubectl apply -f calico.yaml` but it should also explain what it's doing so users can modify the manifest if they understand what it's doing.

**Comment by caseydavenport** [comment]
This is discussed in the hosted introduction page.

http://docs.projectcalico.org/v2.0/getting-started/kubernetes/installation/hosted/
