### ISSUE TITLE
 error getting ClusterInformation: connection is unauthorized: Unauthorized

### ISSUE THREAD

**Issue by shenchenguo** [projectcalico/calico#3538]
When I setup calico 3.14.0 in Kubernetes（version 1.18.2）,the staus of pod 'calico-kube-controllers' returns error:
networkPlugin cni failed to set up pod "calico-kube-controllers-5d9b9bfc74-nxrlq_kube-system" network: error getting ClusterInformation: connection is unauthorized: Unauthorized, failed to clean up sandbox container "94c018f22b521170b263f954b2eafbc154b317ad16e86d009fd9e3460e1abea1" network for pod "calico-kube-controllers-5d9b9bfc74-nxrlq": networkPlugin cni failed to teardown pod "calico-kube-controllers-5d9b9bfc74-nxrlq_kube-system" network: error getting ClusterInformation: connection is unauthorized: Unauthorized]

CNI Plugin version: 3.14.0
OS version: CentOS 7.6.1810

When I rollback calico version to 3.13.3, the pod 'calico-kube-controllers'  runs successfully.

**Comment by tmjd** [comment]
Could you provide a link to the Calico docs you used to install Calico v3.14.0? Looking at one of the guides it looks like the proper RBAC is configured through ClusterRole and ClusterRoleBinding for accessing ClusterInformation.
Were there any modifications you did to the manifests?
Can you run the following command successfully?
```
kubectl get ClusterRole calico-node
kubectl get ClusterRoleBinding calico-node
```
If either of those fail with v3.14.0 installed then that suggests that there was a problem with the install.

**Comment by shenchenguo** [comment]
The link to the Calico docs I used to install Calico v3.14.0 is:
kubectl apply -f https://docs.projectcalico.org/v3.14.0/manifests/calico-typha.yaml
kubectl apply -f https://docs.projectcalico.org/v3.14.0/manifests/calicoctl.yaml

**Comment by caseydavenport** [comment]
@shenchenguo looks like that manifest has the necessary permissions. Could you try the commands that @tmjd suggested to see if those resources exist in the cluster as expected?
