### ISSUE TITLE
Flannel to Calico Migration works after restarting all the nodes

### ISSUE THREAD

**Issue by tsvet** [projectcalico/calico#3543]
We tried migrating our multi-node Kubernetes cluster from Flannel vxlan to Calico by using the migration controller. Our cluster consists of master nodes and worker nodes. All our migration attempts (after successful completion of the migration job) ended up with issues, which seemed to be solved *after rebooting all the nodes*.

## Expected Behavior
After the migration job has finished, all the pods/nodes are in an expected state and can communicate as before the migration. 

## Current Behavior
The migration job (started with kubectl apply -f https://docs.projectcalico.org/manifests/flannel-migration/migration-job.yaml) finished successfully, but some of the pods were not in the expected state. 
After restarting ALL the nodes, the issues were solved. However, this procedure is rather cumbersome. 

## Steps to Reproduce (for bugs)
We tried a migration from Flannel to Calico according to the steps described in https://docs.projectcalico.org/getting-started/kubernetes/flannel/migration-from-flannel 

## Context
Can you recommend us another way of tackling these issues instead of restarting the nodes?

## Your Environment
Kubernetes-Version: v1.16.0
Calico-Version: v3.13.3
Flannel-Version: v0.11.0-amd64

**Comment by caseydavenport** [comment]
> Can you recommend us another way of tackling these issues instead of restarting the nodes?

@tsvet I think we are going to need some more specific information about what issues you encountered that required restarting the nodes. Could you provide some more information about the symptoms you were seeing prior to restarting the nodes?

Things like logs from the migration controller, kubectl describe and logs output on failing pods, etc, will all be useful to identify the issue.

**Comment by caseydavenport** [comment]
@tsvet any more information on this one?
