### ISSUE TITLE
Calico fails e2e test for service with no endpoints

### ISSUE THREAD

**Issue by csrwng** [projectcalico/calico#3548]
We are testing an OpenShift cluster using Calico as the SDN. It is currently failing the following upstream test:
https://github.com/kubernetes/kubernetes/blob/0024c837bae4945427d790fdcd11176fb32aa056/test/e2e/network/service.go#L2628
Accessing a kubernetes service with no endpoints, should result in a response of 'REFUSED'. Instead, the connection is timing out. 
We are not seeing this when running with the OpenShift SDN.

## Expected Behavior
The kubernetes e2e should pass. Connecting to a service with no endpoints should result in a 'REFUSED' response.

## Current Behavior
Connecting to a service with no endpoints results in a timeout.

## Steps to Reproduce (for bugs)
1. Run the kubernetes network e2e tests against a cluster using Calico as the SDN, particularly the test mentioned above.

## Your Environment
* Calico version v3.12.0
* Orchestrator version: kubernetes v1.16.2 / openshift 4.3.18
* Operating System and version: RHEL 7.8

**Comment by smarterclayton** [comment]
> We are not seeing this when running with the OpenShift SDN.

Which uses the kube-proxy from the specified version of Kube in iptables mode

**Comment by smarterclayton** [comment]
This e2e run should capture the failure: https://deck-ci.apps.ci.l2s4.p1.openshiftapps.com/view/gcs/origin-ci-test/logs/release-openshift-origin-installer-e2e-aws-calico-4.5/5

```
[sig-network] Services should be rejected when no endpoints exist [Skipped:ibmcloud] [Suite:openshift/conformance/parallel] [Suite:k8s] 

fail [k8s.io/kubernetes/test/e2e/network/service.go:2621]: Unexpected error:     <*errors.errorString \| 0xc000204990>: {         s: "timed out waiting for the condition",     }     timed out waiting for the condition occurred
```

**Comment by smarterclayton** [comment]
There is some suspicion that there is an ICMP related rate limit in the kernel, but we have had to make changes in the past for other network plugins to get this test working.

**Comment by caseydavenport** [comment]
Sorry for missing this one - I think this is the same issue as discussed here: https://github.com/kubernetes/kubernetes/issues/78994

And, also here: https://github.com/projectcalico/calico/issues/1055

Basically, it seems the Calico rules are accepting the traffic before it gets to the kube-proxy reject rules.
