### ISSUE TITLE
Docs unclear about default pool

### ISSUE THREAD

**Issue by caseydavenport** [projectcalico/calico#356]
That the docs (well where I looked) did not state that the default calico network is 192.168.0.0/16 which just so happens to be the network I am using on the front end (I am currently trying to make this 10.3.0.0/16)

from https://github.com/projectcalico/calico-containers/issues/1324

CC @javaboyuk

**Comment by djosborne** [comment]
Let's clear this up when we fix #63 [No IPAM Documentation]
