### ISSUE TITLE
Tunnel are not communicating between slaves

### ISSUE THREAD

**Issue by deekshith-elear** [projectcalico/calico#3561]
Hi,
I have found a bug that calico tunnels are not establishing communication between slaves in Kubernetes. The observation described below
1. Kubernetes cluster setup was done 6months back all communication worked properly, after 6 months I have added new slave. it is able to join to cluster and launch pods but not able to communicate between slaves or between pods. If I do manual ping of tunnel ip's then they slaves start communication but it lasts till 5-10 mins.
Is this is bug or Is there any thing wrong in setup?

calico version 3.10 & kubernetes version of 1.16.1

Thanks,

**Comment by caseydavenport** [comment]
> Is this is bug or Is there any thing wrong in setup?

Hard to tell with the information provided. I would expect connectivity to work, and my guess is it is a configuration issue.

How have you installed Calico on the new node? Where is this cluster running? Are there any differences between the new node and the other nodes that are working? 

It sounds like a similar symptom to this issue: https://github.com/projectcalico/calico/issues/1357

The resolution there was to make sure you were allowing protocol 4 in the node's underlying security group / firewall.
