### ISSUE TITLE
ExternalIPs/LoadBalancers services do not honor externalTrafficPolicy

### ISSUE THREAD

**Issue by JensErat** [projectcalico/calico#3564]
The [docs have a general paragraph on `externalTrafficPolicy`](https://docs.projectcalico.org/networking/advertise-service-ips#advertising-service-ips-quick-glance) that explain `Cluster` vs `Local` settings. They do not explain this setting is (seems?) only honored by ClusterIP services (or: the cluster IPs in general), but not by ExternalIPs/Load Balancers. The docs seem to be general on both kinds.

#3408 indicates this is only supported by Kubernetes 1.18+ (and if a feature toggle is set) and missing in Calico entirely yet.

## Expected Behavior

Feature implemented or docs unambiguous.

## Current Behavior

Features seems not implemented, but docs are not explicit about this.

## Possible Solution

Implement feature or make docs explicit.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Calico version 3.14.0
* Orchestrator version (e.g. kubernetes, mesos, rkt): Kubernetes 1.14.1
* Operating System and version: Ubuntu 18.04
* Link to your project (optional):

**Comment by JensErat** [comment]
Looks like I was misleaded by the fact that Calico only honours the `externalIPs` field, not `loadBalancerIP` (and further misconfiguration/test configuration in BGPConfigurations: `serviceExternalIPs` vs `serviceClusterIPs`). Got it working now. #2770 finally explained the situation.

**Comment by JensErat** [comment]
After understanding what was wrong, Kubernetes and Calico behavior seems correct to me (but was not obvious on first hand). Would you mind a minor pull request indicating that Calico only exports the `externalIPs` fields for <https://docs.projectcalico.org/networking/advertise-service-ips#advertising-service-ips-quick-glance>? If you agree on having some note, I'll gladly provide a pull request.

**Comment by caseydavenport** [comment]
Sorry for the delay - I think a docs PR here is fine, although that doc already seems pretty clear to me. 

Advertising LB IPs is a further enhancement we could make to the code as well.
