### ISSUE TITLE
Docs unclear about etcd endpoints

### ISSUE THREAD

**Issue by caseydavenport** [projectcalico/calico#357]
The calicoctl command talks to the etcd back-end directly and so you need to have an env variable ETCD_ENDPOINTS which points to your etcd service before your run calicoctl. The docs assume your on the same node as etcd and calico-node I think so the lookpback would work, but mine were separate (as according to best practice).

from https://github.com/projectcalico/calico-containers/issues/1324

CC @javaboyuk

**Comment by ozdanborne** [comment]
@caseydavenport What work is needed to close this?

**Comment by caseydavenport** [comment]
This page needs to document the default value for ETCD_ENDPOINTS: http://docs.projectcalico.org/v2.2/reference/calicoctl/setup/etcdv2

(And probably other stuff as well)

**Comment by tmjd** [comment]
The section http://docs.projectcalico.org/v2.2/reference/calicoctl/setup/etcdv2#environment-variables has a note about the default value and the next section has the default for etcdEndpoints listed with the description.  Some of the other fields that are listed as optional could use explicit default values.  Perhaps a dedicated default column in the table.

**Comment by caseydavenport** [comment]
Yep - I think a default column in the table is right and will be more discoverable than a note in the text.

**Comment by tmjd** [comment]
I just created #798 around standardizing out tables in the reference section (as much as we can), so if someone addresses this they should take that into consideration.

**Comment by tmjd** [comment]
In the standardization of the tables the addition of a Default column was decided against (due to the table formatting), but there is a default for the ETCD_ENDPOINTS in v2.5.  Check the docs out at https://docs.projectcalico.org/v2.5/reference/calicoctl/setup/etcdv2.  @caseydavenport can this issue be closed?
