### ISSUE TITLE
Configuring Felix via ENV vars could be clearer

### ISSUE THREAD

**Issue by lwr20** [projectcalico/calico#358]
http://docs.projectcalico.org/v2.0/usage/configuration/
This doc talks about various config settings for felix and at the end of the table explains how to figure out the name of the Environment variable if you want to use that instead.  

While the conversion is fairly easy, wouldn't it be simpler to simply have another column in the table with the ENV var name of each setting?

**Comment by djosborne** [comment]
Let's be sure to address whis when we Fix #30
