### ISSUE TITLE
calico-typha can't be run while set  ipv6 config in hosts file

### ISSUE THREAD

**Issue by shalousun** [projectcalico/calico#3590]
Calico version: v3.8.8/3.13.0

I installed a kubernetes cluster with more than 100 nodes, using the default ipv4 protocol, and ipv6 support is not enabled. When I use calico-typha.yaml to deploy the calico network plugin, I find that calico-typha cannot run.  It can run normally when using calico.yaml.
## Expected Behavior
When ipv6 is not enabled in the configuration of calico. I hope calico can run normally without being affected by the configuration of ipv6 in `/etc/hosts`

## Current Behavior
calico-typha can’t run. When the following line is configured in `/etc/hosts`
```
::1    localhost       localhost.localdomain   localhost6      localhost6.localdomain6
```
## Your Environment
* Calico version v3.8.8/3.13.0
* Orchestrator version (e.g. kubernetes, mesos, rkt): kubernetes 1.17.4
* Operating System and version: centos 7.5 
* Kernel Version: 3.10

**Comment by caseydavenport** [comment]
Not 100% sure the /etc/hosts line is relevant here. Can you provide some more details from typha as to why it is not running?

What do the typha logs say? Is the pod crashing? Or just not ready? Or something else?

**Comment by shalousun** [comment]
@caseydavenport The server environment provided by our cloud service currently has some problems. After the environment is ready, I will confirm the problem
