### ISSUE TITLE
Calico rpfilter ip6table rule has a high impact on performance

### ISSUE THREAD

**Issue by gpl** [projectcalico/calico#3591]
Issue made at request of @fasaxc on Slack.

We deployed a simple HTTP echo server, along with the traefik ingress.  The traefik ingress definition was given an externalIP.  

During a benchmark with the `wrk` benchmarking tool (github.com/wg/wrk), we noticed that the kernel cpu usage exceeds 70% of all CPU on each node, with traefik using maybe an eighth of a percent total.  Each node in this case has 32 physical cores.

After some fiddling with `perf`, we determined that rpfilter was the cause of this issue.   Removing the ip6tables rule initially had no effect, but by running `ip6tables-save | grep -v rpfilter | ip6tables-restore` in a loop, we were able to determine that the performance was significantly increased.  Traefik now used 40% of all cpu, with kernel taking 30% or so.  We went from 10k rps to 410k rps, and saw an 85% reduction in p95 latency.

As it stands, I haven't yet done any testing if a similar performance penalty exists with rpfilter on ipv4.

We'd like to be able to disable the rpfilter.

## Context
We were doing some basic smoke-testing of a new kubernetes deployment.  

wrk was run with the following flags:

`wrk -t 10 -c 100 -d 1000 http://2001:DB8::100`

## Your Environment
* Calico version - v3.14.0
* Orchestrator version (e.g. kubernetes, mesos, rkt): kubernetes via kubeadm
* Operating System and version: Ubuntu 20.04, base kernel

**Comment by fasaxc** [comment]
@gpl what was the server you were using and what load balancer/ingress did you have in front of it?

**Comment by gpl** [comment]
The server was a single nginx server with a static file.  

The ingress is the traefik v2 ingress here -- https://github.com/containous/traefik-helm-chart.

**Comment by fasaxc** [comment]
@gpl does the problem repro if you just use a node port instead of traefik?

**Comment by caseydavenport** [comment]
@gpl any update here?
