### ISSUE TITLE
[Calico-cri-o]Worker nodes calico-node-xxxxx CrashLoopbackOff due to already allocated IP

### ISSUE THREAD

**Issue by kubealex** [projectcalico/calico#3616]
## Expected Behavior

I set the --pod-cidr-network variable to 10.217.0.0/16 in kubeadm

Calico pods in RUNNING state

## Current Behavior

I set the --pod-cidr-network variable to 10.217.0.0/16 in kubeadm

Calico pods status:

kube-system     calico-kube-controllers-76d4774d89-wwdsh       1/1     Running            0          11m     10.217.0.4        k8s-master-0.k8s.lab   <none>           <none>
kube-system     calico-node-c9jhb                              0/1     CrashLoopBackOff   6          10m     192.168.200.138   k8s-worker-0.k8s.lab   <none>           <none>
kube-system     calico-node-dk6jm                              0/1     Running            0          10m     192.168.200.50    k8s-master-1.k8s.lab   <none>           <none>
kube-system     calico-node-kjj2c                              0/1     Running            0          11m     192.168.200.243   k8s-master-0.k8s.lab   <none>           <none>
kube-system     calico-node-q7qls                              0/1     CrashLoopBackOff   6          10m     192.168.200.157   k8s-worker-1.k8s.lab   <none>           <none>

Pods logs:

2020-06-01 17:57:03.595 [INFO][8] startup/startup.go 664: Using autodetected IPv4 address on interface cni0: 10.217.0.1/16
2020-06-01 17:57:03.596 [INFO][8] startup/startup.go 495: Node IPv4 changed, will check for conflicts
2020-06-01 17:57:03.702 [WARNING][8] startup/startup.go 1010: Calico node 'k8s-master-0.k8s.lab' is already using the IPv4 address 10.217.0.1.
2020-06-01 17:57:03.702 [INFO][8] startup/startup.go 263: Clearing out-of-date IPv4 address from this node IP="10.217.0.1/16"
2020-06-01 17:57:04.418 [WARNING][8] startup/startup.go 1214: Terminating

## Steps to Reproduce (for bugs)

1. Install cri-o 
2. Edit crio-bridge config file in /etc/cni/net.d to fit the cidr network
3. launch kubeadm with --pod-network-cidr with new net
4.

## Your Environment

* Calico version: latest
* Orchestrator version (e.g. kubernetes, mesos, rkt): kubernetes 1.18
* Operating System and version: Centos7

Care, this happens only with cri-o, tested with docker and containerd, nothing to edit or report.

**Comment by kubealex** [comment]
That's horrific, default 'first-found' method in IP_AUTODETECTION_METHOD collides with cni0 being the first interface on nodes, allocating the first free address on cri-o cidr.

**Comment by kubealex** [comment]
This PR on calico/node solves the problem https://github.com/projectcalico/node/pull/509

**Comment by caseydavenport** [comment]
FWIW you should also be able to configure this explicitly without a code change.

Ultimately, we cannot make our default settings work for every possible node network configuration, so we provide knobs to control how the interface is chosen. 

That PR seems sensible enough, though. Don't think we'll ever want to select an interface beginning with `cni`
