### ISSUE TITLE
iptables backend defaults to legacy, when it should default to auto

### ISSUE THREAD

**Issue by hogepodge** [projectcalico/calico#3634]
## Expected Behavior
iptablesbackend should auto detect if NFT is being used

## Current Behavior
iptablesbackend defaults to legacy

## Possible Solution
iptablesbackend should default to auto

## Steps to Reproduce (for bugs)
install calico on CentOS 8, with NFT.

## Context
Report from CentOS 8 user in K8s Slack

## Your Environment

CentOS 8

**Comment by caseydavenport** [comment]
@hogepodge agree completely.

**Comment by caseydavenport** [comment]
This has been fixed
