### ISSUE TITLE
why kube-controller needs container network not host network?

### ISSUE THREAD

**Issue by halfcrazy** [projectcalico/calico#3636]
kube-controller cannot start until calico cni is ready, because kube-controller needs an IP.
I think it's unnecessary for kube-controller to wait cni ready.
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Calico version 3.14.1
* Orchestrator version (e.g. kubernetes, mesos, rkt): k8s
* Operating System and version:
* Link to your project (optional):

**Comment by caseydavenport** [comment]
kube-controllers doesn't need host network because it is not a critical part of establishing networking for the cluster.

It uses pod networking to prevent issues with conflicts on the host, to enable network policy to be applied to it, and as a general best practice.
