### ISSUE TITLE
calico policy enforcement issue in olcne cluster

### ISSUE THREAD

**Issue by sudheshpn** [projectcalico/calico#3653]
We have a [ Oracle OLCNE kubernetes ](https://docs.oracle.com/en/operating-systems/olcne/start/)
which comes bundled with flannel network which has a pod cidr address of range 10.244. We are using flannel for pod to pod communication. We tried to install calico for network policy however the policy enforcement is not happening.     

## Expected Behavior
Followed the example  https://docs.projectcalico.org/security/tutorials/kubernetes-policy-basic. Calico network policy should blocked the access to nginx url. Instead its giving http 200 status 

## Current Behavior
Applied default-deny policy to policy-demo namespace. We are able to access the nginx url from busybox.

## Steps to Reproduce (for bugs)
Applied default-deny policy to policy-demo namespace. Acess the nginx url from busybox. Gives status 200. Expected output it should be blocked

## Your Environment

* Calico version
* Orchestrator version :
* Operating System and version:

-bash-4.2# kubectl version --short
Client Version: v1.17.4+1.0.1.el7
Server Version: v1.17.4+1.0.1.el7
-bash-4.2# uname -a
Linux 4.14.35-1902.301.1.el7uek.x86_64 #2 SMP Tue Mar 31 16:50:32 PDT 2020 x86_64 x86_64 x86_64 GNU/Linux
-bash-4.2# cat /etc/redhat-release
Red Hat Enterprise Linux Server release 7.8 (Maipo)
-bash-4.2#

calico/cni:v3.11.2

Error: Calico interface missing from the worker node

2020-06-11 21:47:15.077 [INFO][50] route_table.go 500: Failed to get interface; it's down/gone. error=Link not found ifaceName="cali8ea2a28d719" ipVersion=0x4
2020-06-11 21:47:15.077 [INFO][50] route_table.go 358: Interface missing, will retry if it appears. ifaceName="cali8ea2a28d719" ipVersion=0x4

**Comment by caseydavenport** [comment]
> which comes bundled with flannel network which has a pod cidr address of range 10.244. We are using flannel for pod to pod communication. We tried to install calico for network policy however the policy enforcement is not happening.

How did you install Calico in this scenario? What manifest / changes did you use?

**Comment by sudheshpn** [comment]
I tried to install canal on a fresh Kubernetes cluster. I used the manifest https://docs.projectcalico.org/getting-started/kubernetes/flannel/flannel . We are seeing the below error in our coredns log. VM are behind proxy and we have added proxy settings in crio proxy config file. calic interfaces are created on worker and master nodes.
Normal   Started    4m16s                 kubelet, umems758  Started container coredns
  Warning  Unhealthy  40s (x22 over 4m10s)  kubelet, umems758  Readiness probe failed: HTTP probe failed with statuscode: 503





11:08
Liveness:     http-get http://:8080/health delay=60s timeout=5s period=10s #success=1 #failure=5

**Comment by sudheshpn** [comment]
I have done the below changes to my env

Environment="NO_PROXY=127.0.0.1,localhost,.us.example.com,.in.example.com,10.244.0.0/16,10.96.0.0,10.96.0.1,10.96.0.0/12"

cat <<'EOF'>>/etc/NetworkManager/conf.d/calico.conf
[keyfile]
unmanaged-devices=interface-name:cali*;interface-name:tunl*
EOF

for port in 4789/udp 179/tcp 5473/tcp 179/tcp
do
ssh $target sudo firewall-cmd --add-port $port
ssh $target sudo firewall-cmd --add-port $port --permanent
Modifies the plugin_dirs in /etc/crio/crio.conf from /usr/libexec/cni
[crio.network]
 network_dir = "/etc/cni/net.d/"
 plugin_dirs = ["/opt/cni/bin/"]
