### ISSUE TITLE
Blackhole route for service CIDR can prevent host from accessing service cluster IPs

### ISSUE THREAD

**Issue by neiljerram** [projectcalico/calico#3689]
## Expected Behavior
A host-networked pod, or some other process running directly on a Kubernetes host, should be able to connect to a Kubernetes service using that service's cluster IP.

## Current Behavior
Connection to the service cluster IP fails.

(But please note, this is only from the host; connection from normal pods is fine.)

## Explanation
In https://github.com/projectcalico/confd/pull/322, we recently arranged to program a blackhole route into the Linux kernel routing table, for the Kubernetes service CIDR.  The motivation for this was to break accidental routing loops, when we are also advertising service IPs to the Calico nodes' default gateway.

Unfortunately we think this blackhole route may prevent connection to a service IP from the host.  For example, this arose in the older issue at #2457 , when a similar blackhole route was being programmed by accident.  #2457 was focussed on suppressing the blackhole route and does not describe the detailed cause of the connection problem, but we think it is to do with Linux source IP selection.  Linux needs to choose a source IP for the connection from the host, and to do that it looks up the destination IP - which is the cluster IP - in the routing table.  The routing table says "blackhole", so the connection fails at that point.  (If Linux source IP selection happened after the service IP DNAT, there would be no problem, but unfortunately it happens earlier than that.)

Net, we need to revisit this, confirm the detailed explanation for why host connections fail, and update the kernel programming so as to prevent routing loops while still allowing a host to connect to a service IP.

**Comment by caseydavenport** [comment]
Fixed here: https://github.com/projectcalico/calico/pull/3755

**Comment by alxbse** [comment]
@caseydavenport The linked pull request seems to be unrelated to this issue. Does that fix apply to this issue?

**Comment by ravilr** [comment]
perhaps, he meant this https://github.com/projectcalico/confd/pull/337 which reverted the original confd change. v3.15.1 releasenotes mentions the reverted fix.

**Comment by caseydavenport** [comment]
Uhh, yeah I'm not sure why I linked that! Must have grabbed the wrong tab.

The fix was indeed the revert that @ravilr linked to.
