### ISSUE TITLE
Calico autoselects iptables-legacy mode if ip_tables.ko preloaded on CentOS 8

### ISSUE THREAD

**Issue by dmitry-irtegov** [projectcalico/calico#3709]
## Expected Behavior
FELIX_IPTABLESBACKEND=auto detection results are consistent with kube-proxy iptables mode.

## Current Behavior
If ip_tables.ko is preloaded on CentOS 8, Calico with FELIX_IPTABLESBACKEND=auto  selects legacy mode, while kube-proxy selects native mode.  This results in pod->service connectivity issues, most noticeable is that coredns and calico-kube-controllers enter CrashLoopBackoff cycle.
calico-kube-controllers log contains the following:
```
2020-06-19 16:20:20.609 [INFO][1] main.go 88: Loaded configuration from environment config=&config.Config{LogLevel:"info", WorkloadEndpointWorkers:1, ProfileWorkers:1, PolicyWorkers:1, NodeWorkers:1, Kubeconfig:"", DatastoreType:"kubernetes"}
W0619 16:20:20.615416       1 client_config.go:541] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
2020-06-19 16:20:20.616 [INFO][1] main.go 109: Ensuring Calico datastore is initialized
2020-06-19 16:20:30.617 [ERROR][1] client.go 261: Error getting cluster information config ClusterInformation="default" error=Get https://100.64.0.1:443/apis/crd.projectcalico.org/v1/clusterinformations/default: context deadline exceeded
2020-06-19 16:20:30.617 [FATAL][1] main.go 114: Failed to initialize Calico datastore error=Get https://100.64.0.1:443/apis/crd.projectcalico.org/v1/clusterinformations/default: context deadline exceeded
```
Setting `FELIX_IPTABLESBACKEND=nft` **or** running `rmmod ip_tables` and blacklisting legacy iptables modules before starting the kubelet BOTH solve the issue. 

## Steps to Reproduce (for bugs)

1.  Install cluster with Calico 3.13.3. or 3.14.1 and FELIX_IPTABLESBACKEND=auto on AWS using ami-01ca03df4a6012157 image.  According to https://wiki.centos.org/Cloud/AWS this is official CentOS image for AWS, and it definitely has ip_tables preloaded.  Note that the issue is image dependent; on our installations of CentOS 8 we did not observed the issue.
2. Run iptables-save.  Observe the following line at the end of output:
`# Warning: iptables-legacy tables present, use iptables-legacy-save to see them`
3.  Observe kube-proxy rules but no calico rules in the output of iptables-save
4.  Observe nonempty file `/proc/net/ip_tables_names`
5.  CentOS 8 has no iptables-legacy binary. To view actual content of the legacy tables it is necessary to dig in /proc or run a shell in the kube-proxy container, where iptables-legacy is available.  Observe calico rules in legacy tables.
6. Observe no pod->service connectivity when pod and service are on different nodes.

## Context
We are developing Kubernetes installer that should work both on CentOS/RHeL 8 and earlier OS distributives, even in mixed clusters. 

## Your Environment

* Calico version. 3.13.3 and 3.14.1
* Orchestrator version (e.g. kubernetes, mesos, rkt):  Kubernetes 1.18.2
* Operating System and version: CentOS 8 AWS/ami-01ca03df4a6012157 , docker-ce
* Link to your project (optional): https://www.kublr.com

**Comment by dmitry-irtegov** [comment]
We probably found the real culprit: localnodedns 1.15.10, which unconditionally uses legacy iptables.  If it manages to start before calico, it fills legacy tables, and it triggers the condition at https://github.com/projectcalico/felix/blob/954cc9b5cf62e63583d404adc5e04dd0e5ad6be3/iptables/feature_detect.go#L180

We will try to fix localnodedns or just delay its start, but, I think, it outlines the fact that current autodetection logic is rather fragile.

**Comment by caseydavenport** [comment]
> it outlines the fact that current autodetection logic is rather fragile.

@dmitry-irtegov yes, I agree, and this is why Felix supports explicit values as well. Unfortunately I am not aware of a better way to detect which mode is being used.

**Comment by champtar** [comment]
nodelocaldns nftables => https://github.com/kubernetes/dns/pull/367

**Comment by panpan0000** [comment]
Attempt to enhance this detection logic in  https://github.com/kubernetes-sigs/iptables-wrappers/pull/2, hope it helps.

**Comment by panpan0000** [comment]
kubelet, as a service/binary,  will leverage host "iptables utilities" to create some rules.
kubelet is the very first one in k8s node, right before those containers (nodelocaldns, kube-proxy, calico) whoever create rules later.
So those containers without host filesystem access( if they can access host fs, they can easily judge by iptables -v :-) ), can detect the rules which kubelet created and make it the baseline of detection logic.

**Comment by yankay** [comment]
> > it outlines the fact that current autodetection logic is rather fragile.
> 
> @dmitry-irtegov yes, I agree, and this is why Felix supports explicit values as well. Unfortunately I am not aware of a better way to detect which mode is being used.

HI @caseydavenport the "https://github.com/kubernetes-sigs/iptables-wrappers/pull/3" has been updated and solve the issue.  :-)
