### ISSUE TITLE
Star policy demo missing arm64 support

### ISSUE THREAD

**Issue by jayanthvn** [projectcalico/calico#3717]
## Expected Behavior
Should be able to deploy calico on arm64 instances.

## Current Behavior
Customer is trying star policy demo on arm64 instances and seeing the below error -
`
$ kubectl logs -n management-ui management-ui-p2jbw
standard_init_linux.go:211: exec user process caused "exec format error"
`
## Possible Solution
Config change might be needed as suggested by the submitter.

## Context
Customer is unable to try the demo on arm64 instances

## Your Environment
Please refer to https://github.com/aws/amazon-vpc-cni-k8s/issues/1047

**Comment by fasaxc** [comment]
ARM64 is community-supported; not sure if @deitch (the original contributor) has any bandwidth for fixing up the demos.

**Comment by deitch** [comment]
Hi @fasaxc ; always nice to see you online. 😀

I won't have for the next several weeks at least.

**Comment by vielmetti** [comment]
"Exec format error" is a typical error message when a container doesn't have multi-architecture support. Your challenge is to figure out which container is being run, and see if either the container's build process can be fixed to provide a multi-architecture manifest, or if the configuration file can be adjusted to pull from a suitable alternate that has support.  I'll look upstream.

**Comment by frozenprocess** [comment]
I've created a multiarch image for stars project.
It supports both aarch64 and amd64.

```
rezareza/star-collect:v0.1.1
rezareza/star-probe:v0.1.1
```

[star-probe](https://hub.docker.com/repository/docker/rezareza/star-probe)
[star-collect](https://hub.docker.com/repository/docker/rezareza/star-collect)
