### ISSUE TITLE
[Question] Using metadata.name as a namespace selector ?

### ISSUE THREAD

**Issue by emirot** [projectcalico/calico#3722]
Hi there,

I was wondering if we could use the metadata namespace name for the namespace selector.
Otherwise, it looks like I would have to add a label name==metadata.name for each of my namespace.

**Comment by caseydavenport** [comment]
If you use Calico network policies you can use a special label to match:

```
namespaceSelector: projectcalico.org/name == "<namespace name>"
```

See here: https://docs.projectcalico.org/reference/resources/globalnetworkpolicy#spec
