### ISSUE TITLE
iptables locking bug with CentOS 7

### ISSUE THREAD

**Issue by tommasopozzetti** [projectcalico/calico#3727]
## Expected Behavior
Felix auto-discovers features from `iptables`, including the capability of performing and configuring locking through the `-w` flag. The combination of this auto-discovery and felix's capability of manually acquiring the xtables lock with configurable timeouts and retry intervals should ensure that no races or deadlocks can occurr.

## Current Behavior
On CentOS 7, if the `FELIX_IPTABLESLOCKTIMEOUTSECS` and the `FELIX_IPTABLESLOCKPROBEINTERVALMILLIS` environment variables are set, felix tries to acquire the xtables lock and then calls `iptables-restore`, which however also tries to acquire the same lock resulting in a failure which always results in felix restarting.

## Possible Solution
It seems that the bug is due to the fact that felix performs auto-discovery of `iptables-restore` capabilities via version comparison and sets the starting version for the presence of the `-w` flag to version `1.6.2` (as seen [here](https://github.com/projectcalico/felix/blob/master/iptables/feature_detect.go#L104)). However, iptables on CentOS 7 version `1.4.21` has received several backports of new features including the capability of managing the xtables lock and the `-w` flag (as seen [here](https://git.centos.org/rpms/iptables/blob/c7/f/SOURCES)).

Therefore, it seems that felix will try to grab the lock believing that `iptables-restore` is not going to, but `iptables-restore` actually does try to grab it as well which results in the failure.

This bug only presents itself if felix is configured with non-default timeout and retry interval values. By default, it disables locking for versions < `1.6.2`, so it results in only `iptables-restore` trying to grab the lock.

## Your Environment
* Calico version: 3.14.0
* Orchestrator version: Kubernetes 1.18.3
* Operating System and version: CentOS 7

**Comment by fasaxc** [comment]
The version of iptables that felix uses is the one in our calico/node container, which is 1.8.x so it always supports the lock.  The flags you mentioned should never be used with the calico/node container.

**Comment by tommasopozzetti** [comment]
Thank you @fasaxc for your clarification.
We rebuild the images to base them on CentOS, so that is probably why we are experiencing the issue with iptables. I will correct it for our setup.
I don't know whether this could still be a relevant issue for people installing calico on bare-metal via package manager on CentOS 7, but if not I think we can close the issue as it's more related to our own setup than calico.

**Comment by fasaxc** [comment]
What's your reason for wanting to rebuild our images on a different base?  You should know that we do huge amounts of testing on the images, which you'll invalidate by building them on something different (as you found out!).
