### ISSUE TITLE
v2.6 to v3.x upgrade guide links are broken

### ISSUE THREAD

**Issue by fasaxc** [projectcalico/calico#3735]
On this page, for example:
https://docs.projectcalico.org/archive/v3.4/getting-started/kubernetes/upgrade/

## Expected Behavior

The links near the bottom "Install and configure calico-upgrade" etc should land on a v3.4 page; 
## Current Behavior

Instead they get redirected to https://docs.projectcalico.org/maintenance/upgrading.
## Possible Solution

Fix the urls of the links to be relative.
## Steps to Reproduce (for bugs)

1. Go to https://docs.projectcalico.org/archive/v3.4/getting-started/kubernetes/upgrade/
2. Click "Install and configure calico-upgrade"

## Your Environment

* Calico version
* Orchestrator version (e.g. kubernetes, mesos, rkt):
* Operating System and version:
* Link to your project (optional):

**Comment by opskumu** [comment]
+1

**Comment by opskumu** [comment]
I have already upgraded calico from v2.6.12 -> v3.5.8 yesterday with the follow pages: 

![image](https://user-images.githubusercontent.com/5445356/86901579-659b5300-c13f-11ea-932f-a7f92f4a446b.png)

For old versions pages, there are many wrong links to latest，but not affect upgrade.
