### ISSUE TITLE
Unable to curl service using IPv6 address on kubernetes multi-node setup using calico cn

### ISSUE THREAD

**Issue by dsapra30** [projectcalico/calico#3737]
## Expected Behavior

I am trying to create a muli-node kubernetes cluster with dual stack IPv4/IPv6 support using calico cni. I have created fd00:4000::1 interfaces on both machines for node to node communication using IPv6 and 192.168.122.0/24 for node to node communication using IPv4.
Should be able to access the service to pod using IPv6 (nodeport).

## Current Behavior

Before setting ipvs mode in kube-proxy, I was able to curl the service using nodeip:nodeport.
But after setting ipvs mode in kube-proxy, I am not able to curl the service using nodeip:nodeport and get the below error:
curl -6 http://[fd00:4000::147]:32123 -g
curl: (7) Failed connect to fd00:4000::147:32123; Connection refused

## Possible Solution

Suggest some solutions.

## Steps to Reproduce (for bugs)

1.Below are the configurations details:
# cat /etc/hosts
# for IPv4
master-node 192.168.122.163
worker-node 192.168.122.157
# for IPv6
master-node fd00:4000::1cd
worker-node fd00:4000::147

2. Created cluster using below command:
kubeadm init --apiserver-advertise-address=fd00:4000::1cd  --pod-network-cidr=1100::/48,192.168.0.0/16 
--service-cidr=fd00:100::/112,172.20.0.0/16 --feature-gates="IPv6DualStack=true"
3. Configured calico.yaml with the following parameters:

"ipam": {
        "type": "calico-ipam",
        "assign_ipv4": "true",
        "assign_ipv6": "true"
    },
IP6: autodetect
CALICO_IPV6POOL_CIDR: 1100::/48
FELIX_IPV6SUPPORT: true

4. After creating a service with Nodeport type. 
kubectl get svc --all-namespaces
NAMESPACE     NAME           TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)                  AGE
default       kubernetes     ClusterIP   fd00:100::1      <none>        443/TCP                  171m
default       my-nginx-new   NodePort    fd00:100::4611   <none>        8080:32123/TCP           167m
kube-system   kube-dns       ClusterIP   fd00:100::a      <none>        53/UDP,53/TCP,9153/TCP   171m

5. After setting ipvs mode in kube-proxy, I am not able to curl the service using nodeip:nodeport and get the below error:
curl -6 http://[fd00:4000::147]:32123 -g
curl: (7) Failed connect to fd00:4000::147:32123; Connection refused
## Context

Service to pod communication using IPv6 nodeport.

## Your Environment

* Calico version
   calico version 3.15.0
* Orchestrator version (e.g. kubernetes, mesos, rkt):
  kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.5", GitCommit:"e6503f8d8f769ace2f338794c914a96fc335df0f", GitTreeState:"clean", BuildDate:"2020-06-26T03:47:41Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.5", GitCommit:"e6503f8d8f769ace2f338794c914a96fc335df0f", GitTreeState:"clean", BuildDate:"2020-06-26T03:39:24Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}

* Operating System and version:
   Centos 7
* Link to your project (optional):

**Comment by dsapra30** [comment]
@fasaxc @song-jiang  Hi guys, Could you please suggest solution to this problem?

**Comment by timyl** [comment]
@dsapra30 maybe this is the issue about kube-proxy, 
https://github.com/kubernetes/kubeadm/issues/2205

**Comment by uablrek** [comment]
@dsapra30 Please see https://github.com/kubernetes/kubernetes/issues/92412#issuecomment-654028293

It seems to be the same problem and can you also please attach the kube-proxy log?

The kernel in "Centos 7" is extremly old `3.10` and this has caused several problems in combination with recent K8s versions. It is possible for you to test with a never kernel?

**Comment by uablrek** [comment]
Seem likely to be this bug; https://github.com/kubernetes/kubernetes/issues/89520

**Comment by dsapra30** [comment]
@uablrek  Thanks for your suggestion. I updated the kernel version from 3.10 to 5.7.7-1.el7.elrepo.x86_6. After doing this, I am now able to curl service using IPV6. 

Thanks for resolving. I am closing this issue.
