### ISSUE TITLE
unknown blackhole route, unable to access container network

### ISSUE THREAD

**Issue by monkey92t** [projectcalico/calico#3740]
unknown blackhole route, unable to access container network:  `blackhole 192.168.39.0/26 proto bird`,
if deleted: `ip route del 192.168.39.0/26`， it will reappear.  
similar issue:  https://github.com/projectcalico/calico/issues/2457

## Expected Behavior
the blackhole network should not exist, normal access to container network.

## Your Environment

os: centos 7.3<kernel 4.4>
docker versioin: 19.03.12
etcd: quay.io/coreos/etcd:v3.3.22
calicoctl: v3.15.0
calico: quay.io/calico/node:latest
calico-libnetwork-plugin: quay.io/calico/libnetwork-plugin:master

calico ippool:
```
[root@node-1 ~]#calicoctl get ippool -o wide
NAME                  CIDR                  NAT     IPIPMODE   VXLANMODE   DISABLED   SELECTOR   
default-ipv4-ippool   192.168.0.0/16        true    Never      Never       false      all()      
default-ipv6-ippool   fd50:4ddc:c118::/48   false   Never      Never       false      all()
```

docker network:
[root@node-1 ~]#docker network create --driver calico --ipam-driver calico-ipam --subnet=192.168.0.0/16 nginx-net
[root@node-1 ~]#docker network ls
NETWORK ID          NAME                DRIVER              SCOPE
21c2fe7e51e0        bridge              bridge              local
80d252098283        host                host                local
152cc11a0d80        nginx-net           calico              global
eef2ab02e7c7        none                null                local

node-1、node-2、node-3, using nginx-net network to run nginx container, but containers cannot access each other.

I see` ip route`:
```
192.168.39.0 dev cali957dd21ff42 scope link 
blackhole 192.168.39.0/26 proto bird 
192.168.84.128/26 via 10.3.138.23 dev ens32 proto bird 
192.168.205.192/26 via 10.3.138.22 dev ens32 proto bird
```

why `blackhole` exist? does it block access to the container network?

if use `ip route del 192.168.39.0/26` to delete a route,  This blackhole will appear again.

**Comment by monkey92t** [comment]
it seems to be a problem with libnetwork-plugin, close the issue here.

**Comment by SomKen** [comment]
> 
> 
> it seems to be a problem with libnetwork-plugin, close the issue here.

How'd you figure that out? I've been having this issue for a few months and it's driving me NUTS!
