### ISSUE TITLE
How to create a BGP HA with shortest down time

### ISSUE THREAD

**Issue by kaitaklam** [projectcalico/calico#3741]
This is actually a question.

setup:
I have setup Calico to advertise service IP using externalIP to the outside world.
The outside world BGP-peer is connected to two Calico BGP-peers.
The advertised IP service address appears on the outside BGP-peer and the route is via one of the Calico BGP peer IP address.

If the Calico BGP peer IP is down, the outside world BGP-peer detects in 3 seconds the unavailable Calico BGP peer and started to switch to the other to other Calico peer.

So this means that during 3 seconds the route is unavailable. 

The 3 second is the lowest value that can be achieved, as it is configured in bird.conf on the outside world BGP-peer (hold time = 3 x keepalive_time see below).

For my application, I would like to have zero down time. How can I achieve this?

protocol bgp m0{
        description "m0 bird";
        hold time 3;
        keepalive time 1;      # defaults to hold time / 3
        local as 65000;
        neighbor 192.168.21.86 as 64512;
        source address 192.168.21.38;   # What local address we use for the TCP connection
        import all;     # Accept all prefixes from our neighbor
        export none;    # Don't send the neighbor any prefixes
}

protocol bgp w0{
        description "w0 bird";
        hold time 3;
        keepalive time 1;      # defaults to hold time / 3
        local as 65000;
        neighbor 192.168.21.19 as 64512;
        source address 192.168.21.38;   # What local address we use for the TCP connection
        import all;     # Accept all prefixes from our neighbor
        export none;    # Don't send the neighbor any prefixes
}

**Comment by lmm** [comment]
I think this has less to do with Calico and maybe more about BGP networking infra setup. If you have any more questions about this, join our Slack (https://calicousers.slack.com/) - perhaps another Calico user has looked into this area.
