### ISSUE TITLE
Udp packets loss

### ISSUE THREAD

**Issue by hamzakilic** [projectcalico/calico#3748]
a rsyslog service with nodeport, externalpolicy:Cluster configuration in kubernetes,
udp packets loss,
I am sending 1000 syslog packets from my computer to kubernetes cluster for testing
Kubernetes cluster is working on my machine with virtual box( 1 master,2 worker node),
only sending 1000 udp syslog packets 
with bash command like
**for i in {1..1000}; do logger "test100" -n node1 -P 30515 -d ;done**
this, some of packets loss

![kubernetes](https://user-images.githubusercontent.com/11096936/86506821-b62b4d00-bddb-11ea-83bc-76386aae11e3.png)

## Expected Behavior
no packet loss, it is a small amount of packets

## Current Behavior
every time some of the packets is lost, sometimes 10, sometimes 4

## Possible Solution
tried debian 10, but no fix,
install other CNI fixed this error

## Steps to Reproduce (for bugs)

1. create **3** machines, install kubernetes 1.18 and centos 7, one of them will kubernetes master, others will worker node
2. install calico 3.14 or 3.15 
3. create a docker rsyslog image with this docker file or other from internet
[dockerfile](https://github.com/hamzakilic/kubernetesudpproblem/blob/master/rsyslog.dockerfile)

docker build -t mysyslog -f rsyslog.dockerfile .
4. deploy rsyslog images to kubernetes like this configuration
[rsyslog.yaml](https://github.com/hamzakilic/kubernetesudpproblem/blob/master/rsyslog.yaml)
5. deploy at least 4 replicas of rsyslog image
6. at  worker node1 follow packets
**tcpdump -i any -nn port 30515 --number**
**tcpdump -i any -nn port 514 --number**
7. from your machine 
**for i in {1..1000}; do logger "test100" -n node1 -P 30515 -d ;done**
8. **at worker node1** you will see at tcpdump 30515 command screen **1000** packets, but at tcpdump 514 you will not see 1000 packets,
packets arrive to node1 to port 30515 with out loss,but sum of the packets that route to  node1  port 514 and node2 port 514  are not 1000

 

## Your Environment

* Calico version ( 3.14, 3.15,3,9)
* Orchestrator version (e.g. kubernetes, mesos, rkt):kubernetes 1.18, kubernetes 1.17 ( kube-proxy mode must be iptables)
* Operating System and version:centos 7, debian 10
* Link to your project [(github files for testing):](https://github.com/hamzakilic/kubernetesudpproblem)

**Comment by hamzakilic** [comment]
I have fixed this problem by changing kube-proxy working mode iptables to ipvs

**Comment by dostalradim** [comment]
Same thing happend to me with ClusterIP service which`s IP is routed to cluster. And this solution really helped me. On Kubernetes 1.19.4 and with Debian 9 hosts.

Thanks
