### ISSUE TITLE
Setup Calico polices while creating cluster

### ISSUE THREAD

**Issue by prasad-1729** [projectcalico/calico#3750]
Hi 

I want to setup calico polices while creating cluster automatically..is there any way?
like using cli ,we can create a cluster, but how can we setup calico polices?

can you help me on this..?
Thanks!!

**Comment by caseydavenport** [comment]
You can create Kubernetes NetworkPolicies using kubectl (see the Kubernetes documentation).

You can also create Calico policies using calicoctl (see the Calico docs: https://docs.projectcalico.org)
