### ISSUE TITLE
felix/wireguard.go 578: Wireguard is not enabled

### ISSUE THREAD

**Issue by tomdoherty** [projectcalico/calico#3754]
Log spammed with `felix/wireguard.go 578: Wireguard is not enabled`

## Expected Behavior

Less frequent alerting to Wireguard not being enabled

## Current Behavior
Log flooded with `felix/wireguard.go 578: Wireguard is not enabled`

## Steps to Reproduce (for bugs)
1.  run calico v3.15.0 with default configs

## Your Environment

* v3.15.0
* k3s 1.17.7
* RHEL 7.8

**Comment by tomdoherty** [comment]
This is an identical setup to the ones described [here](https://github.com/projectcalico/calico/issues/3756) with the exception of `FELIX_LOGSEVERITYSCREEN` being unmodified

**Comment by caseydavenport** [comment]
Looks like this log has been downgraded to "debug" in master, so future releases won't be so chatty. Thanks for raising.
