### ISSUE TITLE
Outgoing NAT fails when multiple ip-pools are defined

### ISSUE THREAD

**Issue by komal-SkyNET** [projectcalico/calico#3770]
OutgoingNAT fails when there are multiple IP_POOLS in the ip_pool list with the below configs:
```
calicoctl get ippool -o yaml

apiVersion: projectcalico.org/v3
items:
- apiVersion: projectcalico.org/v3
  kind: IPPool
  metadata:
    name: default-ipv4-ippool
  spec:
    cidr: 192.168.0.0/16
    ipipMode: Never
    natOutgoing: true
- apiVersion: projectcalico.org/v3
  kind: IPPool
  metadata:
    name: default-pool
  spec:
    cidr: 10.14.0.0/20
    ipipMode: Always
    natOutgoing: true
kind: IPPoolList
metadata:
  resourceVersion: "sample"
```

## Expected Behavior
Outgoingnat should work properly for 10.14.x.x/20 subnet.

## Current Behavior
Outgoingnat fails with the ippool config mentioned above. But after removing the default-ipv4-pool (192.x) - outgoing nat works for 10.14.x.x subnet. 

## Steps to Reproduce (for bugs)

1. Apply the ippool config from below (mentioned in context section) into the cluster. 'calicoctl apply -f -'
2. Initiate connection from 10.14.x.x/20 subnet to any external system say, 8.8.8.8.  
You can observe that - Outgoing NAT fails and POD IP is not masqueraded to NODE IP as connection is sent out. 
3. If you delete the 'default-ipv4-ippool' and then do the same - outgoing NAT works.  

## Context
There were multiple ipools in the ippool list. And natoutgoing didn't work for our 10.14.0.0/20 subnet (the one we use). The default 192.x subnet is not being used. After 192.x ippool was removed - the natoutgoing started working. 

## Your Environment
/usr/local/bin/calicoctl version
Client Version:    v3.2.0
Cluster Version:   v3.2.0
Cluster Type:      kubespray,bgp,k8s

K8s version: v1.9.3

**Comment by caseydavenport** [comment]
> Cluster Version: v3.2.0

Calico v3.2 is _very_ old and not in support any longer. Could you try reproducing on a modern version of Calico to see if the issue still exists?

**Comment by caseydavenport** [comment]
If you can reproduce on a newer version please report back and I will reopen this issue.
