### ISSUE TITLE
IP Range for PODS

### ISSUE THREAD

**Issue by psaini79** [projectcalico/calico#3773]
Hi,

Is there a way to specify the range of IPs for a pod? for example, I have a calico network configured on following CIDR 192.168.16.0./24 but I want pods to choose IPs for pods from this range only 192.168.168.100-192.168.168.200 during POD creation. However, the rest of the IPs can be up as an IP alias inside the POD.
Eg:

eth1 will have 192.168.16.100 but our application will create an alias of 192.168.16.10 on eth0:1. I just want to make sure that some reserved IPs should not be given to pod during pod creation.

## Current Solution
There is a [solution](https://docs.projectcalico.org/networking/legacy-firewalls) in calico to block a CIDR at pod using IP pools but it blocks the complete CIDR. In our case, we want to block selected IPs in a subnet.

Are there any parameters to do this as few IPs are brought up by our app and we wanna make sure those IPs should not be allocated to other PODs.

**Comment by caseydavenport** [comment]
The document you linked to is the correct way to do this with Calico. You can create multiple distinct pools with the ranges you want.

you're correct, though - there is no way to specify a set of specific IP addresses to use. You need to pick a CIDR from which addresses can be assigned.
