### ISSUE TITLE
status of the calico-kube-controllers pod is pending

### ISSUE THREAD

**Issue by theSxx** [projectcalico/calico#3777]
if my config.yaml not use those keywords, my k8s network will work without normally.
```
"containner_settings" : {
  "allow_ip_forwarding": true
},
"feature_control": {
  "floating_ips": true 
}
```
It looks like Corednspod is not working properly causing the Calico-Kube-Controllers Pod to be pending.
I don't think the two keywords are related, but it is strange that the service would not work if the YAML file did not have these keywords in it. Specifically, the state of coredns pod within k8s will be pending, resulting in the state of not-ready of k8s nodes.

If you add these two keywords to your configuration file, coredns pod will normally be running, and then calico-Kubec-Controllers will be scheduled to the master node.

Here is the official introduction:
Container settings
The following options allow configuration of settings within the container namespace.
allow_ip_forwarding (default is false)

```
{
    "name": "any_name",
    "cniVersion": "0.1.0",
    "type": "calico",
    "ipam": {
        "type": "calico-ipam"
    },
    "container_settings": {
        "allow_ip_forwarding": true
    }
}
```
If anyone has used these two keywords or knows how to use them, please get back to me. thanks.

**Comment by caseydavenport** [comment]
Pods in a "Pending" state is typically not related to networking - the scheduler has decided that there are no nodes that can accept the pods.

This may be a result of various unreadiness conditions on the nodes. However, it doesn't sound like this is a Calico issue, and most likely a cluster setup issue.
