### ISSUE TITLE
Could not set up calico network via CNI

### ISSUE THREAD

**Issue by HongjunNi** [projectcalico/calico#378]
Hey,

I set up a k8s cluster with calico networking by following the link: http://docs.projectcalico.org/v1.5/getting-started/kubernetes/installation/vagrant/. 
As a result, master node and two nodes are set up correctly. 
The following is the output of node-02:
core@k8s-node-02 /opt $ docker ps
CONTAINER ID        IMAGE                        COMMAND               CREATED             STATUS              PORTS              
22390a58c13e        calico/cni:v1.4.2            "/install-cni.sh"     About an hour ago   Up About an hour                        
4fca4ba5c593        calico/node:v0.22.0          "/sbin/start_runit"   About an hour ago   Up About an hour                        
0804cbcb2a54        docker.io/kubernetes/pause   "/pause"              About an hour ago   Up About an hou

When I created calico by following this link: 
http://docs.projectcalico.org/v1.5/reference/without-docker-networking/installation
Both containers in the same PROF could ping each other very well.  It uses calico networking.

But when I created container through:
kubectl create -f /vagrant/cloud-config/busybox.yaml --record
The container still uses the default container bridge, not using the calico networking via CNI.

Did I miss some steps in my setup?  Thanks a lot!

The following is the config of busybox.yaml:
apiVersion: v1
kind: Pod
metadata:
  name: busybox
  namespace: kube-system
spec:
  containers:
  - name: busybox
    image: busybox
    imagePullPolicy: IfNotPresent
  restartPolicy: Always

**Comment by caseydavenport** [comment]
@HongjunNi sounds like the kubelet might not be calling the Calico plugin.

Did you start the kubelet with `--network-plugin=cni`?

**Comment by HongjunNi** [comment]
@caseydavenport Thank you for your quick response.
Yes, I started the kubelet with:
        --network-plugin=cni \
        --network-plugin-dir=/etc/cni/net.d

(1). The following is the list of /opt/cni/bin in node-01:
core@k8s-node-01 /opt/cni/bin $ ls -l
total 79144
-rwxr-xr-x. 1 root root  4903520 Jun  9  2016 bridge
-rwxr-xr-x. 1 root root 24809824 Dec 13 15:24 calico
-rwxr-xr-x. 1 root root  9766528 Dec 13 15:24 calico-ipam
-rwxr-xr-x. 1 root root  3585888 Jun  9  2016 cnitool
-rwxr-xr-x. 1 root root  9212240 Jun  9  2016 dhcp
-rwxr-xr-x. 1 root root  3632688 Jun  9  2016 flannel
-rwxr-xr-x. 1 root root  3856208 Jun  9  2016 host-local
-rwxr-xr-x. 1 root root  4308632 Jun  9  2016 ipvlan
-rwxr-xr-x. 1 root root  3909976 Jun  9  2016 loopback
-rwxr-xr-x. 1 root root  4321560 Jun  9  2016 macvlan
-rwxr-xr-x. 1 root root  4890816 Jun  9  2016 ptp
-rwxr-xr-x. 1 root root  3764296 Jun  9  2016 tuning

(2).The following is the node-01's output for kubelet:  "journalctl -b -u kubelet"

Dec 13 15:24:23 k8s-node-01 systemd[1]: Starting Kubernetes Kubelet...
Dec 13 15:24:23 k8s-node-01 tar[2145]: ./
Dec 13 15:24:23 k8s-node-01 tar[2145]: ./cnitool
Dec 13 15:24:23 k8s-node-01 tar[2145]: ./flannel
Dec 13 15:24:23 k8s-node-01 tar[2145]: ./tuning
Dec 13 15:24:24 k8s-node-01 tar[2145]: ./bridge
Dec 13 15:24:24 k8s-node-01 tar[2145]: ./ipvlan
Dec 13 15:24:24 k8s-node-01 tar[2145]: ./loopback
Dec 13 15:24:24 k8s-node-01 tar[2145]: ./macvlan
Dec 13 15:24:24 k8s-node-01 tar[2145]: ./ptp
Dec 13 15:24:24 k8s-node-01 tar[2145]: ./dhcp
Dec 13 15:24:24 k8s-node-01 tar[2145]: ./host-local
Dec 13 15:24:24 k8s-node-01 systemd[1]: Started Kubernetes Kubelet.
Dec 13 15:24:25 k8s-node-01 kubelet[2203]: Flag --api-servers has been deprecated, Use --kubeconfig instead. Will be removed in a future version.
Dec 13 15:24:25 k8s-node-01 kubelet[2203]: I1213 15:24:25.202822    2203 feature_gate.go:161] feature gates: map[AllAlpha:true DynamicKubeletConfig:true DynamicVolumeProvisioning:true AllowExtTrafficLocalEndpoints:true]
Dec 13 15:24:25 k8s-node-01 kubelet[2203]: W1213 15:24:25.204328    2203 server.go:549] Could not load kubeconfig file /var/lib/kubelet/kubeconfig: stat /var/lib/kubelet/kubeconfig: no such file or directory. Using default client config
Dec 13 15:24:25 k8s-node-01 kubelet[2203]: I1213 15:24:25.213073    2203 server.go:215] Starting Kubelet configuration sync loop
Dec 13 15:24:25 k8s-node-01 kubelet[2203]: W1213 15:24:25.213466    2203 server.go:549] Could not load kubeconfig file /var/lib/kubelet/kubeconfig: stat /var/lib/kubelet/kubeconfig: no such file or directory. Using default client config
Dec 13 15:24:25 k8s-node-01 kubelet[2203]: I1213 15:24:25.656310    2203 docker.go:375] Connecting to docker on unix:///var/run/docker.sock
Dec 13 15:24:25 k8s-node-01 kubelet[2203]: I1213 15:24:25.656659    2203 docker.go:395] Start docker client with request timeout=2m0s
Dec 13 15:24:25 k8s-node-01 kubelet[2203]: I1213 15:24:25.671298    2203 manager.go:140] cAdvisor running in container: "/system.slice/kubelet.service"
Dec 13 15:24:25 k8s-node-01 kubelet[2203]: W1213 15:24:25.676834    2203 manager.go:148] unable to connect to Rkt api service: rkt: cannot tcp Dial rkt api service: dial tcp 127.0.0.1:15441: getsockopt: connection refused
Dec 13 15:24:25 k8s-node-01 kubelet[2203]: I1213 15:24:25.679056    2203 fs.go:116] Filesystem partitions: map[/dev/sda6:{mountpoint:/usr/share/oem major:8 minor:6 fsType:ext4 blockSize:0} /dev/sda9:{mountpoint:/ major:8 minor:9 fsType:e
Dec 13 15:24:25 k8s-node-01 kubelet[2203]: I1213 15:24:25.680280    2203 manager.go:195] Machine: {NumCores:1 CpuFrequency:2294805 MemoryCapacity:2102435840 MachineID:9f001c6d22ab4c62908de000d6757d84 SystemUUID:63648752-B275-45AD-AF01-99
Dec 13 15:24:25 k8s-node-01 kubelet[2203]: I1213 15:24:25.683123    2203 manager.go:201] Version: {KernelVersion:4.7.3-coreos-r2 ContainerOsVersion:CoreOS 1185.3.0 (MoreOS) DockerVersion:1.11.2 CadvisorVersion: CadvisorRevision:}
Dec 13 15:24:25 k8s-node-01 kubelet[2203]: I1213 15:24:25.686582    2203 kubelet.go:255] Adding manifest file: /etc/kubernetes/manifests
Dec 13 15:24:25 k8s-node-01 kubelet[2203]: I1213 15:24:25.686836    2203 kubelet.go:265] Watching apiserver
Dec 13 15:24:25 k8s-node-01 kubelet[2203]: E1213 15:24:25.688226    2203 file.go:53] Unable to read config path "/etc/kubernetes/manifests": path does not exist, ignoring
Dec 13 15:24:25 k8s-node-01 kubelet[2203]: W1213 15:24:25.689109    2203 kubelet_network.go:71] Hairpin mode set to "promiscuous-bridge" but configureCBR0 is false, falling back to "hairpin-veth"
Dec 13 15:24:25 k8s-node-01 kubelet[2203]: I1213 15:24:25.689846    2203 kubelet.go:516] Hairpin mode set to "hairpin-veth"
Dec 13 15:24:25 k8s-node-01 kubelet[2203]: I1213 15:24:25.700677    2203 docker_manager.go:242] Setting dockerRoot to /var/lib/docker
Dec 13 15:24:25 k8s-node-01 kubelet[2203]: I1213 15:24:25.701513    2203 server.go:714] Started kubelet v1.4.0
Dec 13 15:24:25 k8s-node-01 kubelet[2203]: E1213 15:24:25.707701    2203 kubelet.go:1094] Image garbage collection failed: unable to find data for container /
Dec 13 15:24:25 k8s-node-01 kubelet[2203]: I1213 15:24:25.708066    2203 kubelet_node_status.go:194] Setting node annotation to enable volume controller attach/detach
Dec 13 15:24:25 k8s-node-01 kubelet[2203]: I1213 15:24:25.708161    2203 server.go:118] Starting to listen on 0.0.0.0:10250
Dec 13 15:24:25 k8s-node-01 kubelet[2203]: E1213 15:24:25.725980    2203 kubelet.go:2127] Failed to check if disk space is available for the runtime: failed to get fs info for "runtime": unable to find data for container /
Dec 13 15:24:25 k8s-node-01 kubelet[2203]: E1213 15:24:25.726226    2203 kubelet.go:2135] Failed to check if disk space is available on the root partition: failed to get fs info for "root": unable to find data for container /
Dec 13 15:24:25 k8s-node-01 kubelet[2203]: I1213 15:24:25.727426    2203 fs_resource_analyzer.go:66] Starting FS ResourceAnalyzer
Dec 13 15:24:25 k8s-node-01 kubelet[2203]: I1213 15:24:25.727454    2203 status_manager.go:129] Starting to sync pod status with apiserver
Dec 13 15:24:25 k8s-node-01 kubelet[2203]: I1213 15:24:25.727665    2203 kubelet.go:2229] Starting kubelet main sync loop.
Dec 13 15:24:25 k8s-node-01 kubelet[2203]: I1213 15:24:25.727875    2203 kubelet.go:2240] skipping pod synchronization - [network state unknown container runtime is down]
Dec 13 15:24:25 k8s-node-01 kubelet[2203]: I1213 15:24:25.729160    2203 volume_manager.go:234] Starting Kubelet Volume Manager
Dec 13 15:24:25 k8s-node-01 kubelet[2203]: I1213 15:24:25.733845    2203 factory.go:295] Registering Docker factory
Dec 13 15:24:25 k8s-node-01 kubelet[2203]: W1213 15:24:25.735132    2203 manager.go:244] Registration of the rkt container factory failed: unable to communicate with Rkt api service: rkt: cannot tcp Dial rkt api service: dial tcp 127.0.0
Dec 13 15:24:25 k8s-node-01 kubelet[2203]: I1213 15:24:25.735352    2203 factory.go:54] Registering systemd factory
Dec 13 15:24:25 k8s-node-01 kubelet[2203]: I1213 15:24:25.735474    2203 factory.go:86] Registering Raw factory
Dec 13 15:24:25 k8s-node-01 kubelet[2203]: I1213 15:24:25.735475    2203 manager.go:1082] Started watching for new ooms in manager
Dec 13 15:24:25 k8s-node-01 kubelet[2203]: I1213 15:24:25.736708    2203 oomparser.go:185] oomparser using systemd
Dec 13 15:24:25 k8s-node-01 kubelet[2203]: I1213 15:24:25.740789    2203 manager.go:285] Starting recovery of all containers
Dec 13 15:24:25 k8s-node-01 kubelet[2203]: I1213 15:24:25.793098    2203 manager.go:290] Recovery completed
Dec 13 15:24:25 k8s-node-01 kubelet[2203]: I1213 15:24:25.874980    2203 kubelet_node_status.go:194] Setting node annotation to enable volume controller attach/detach
Dec 13 15:24:25 k8s-node-01 kubelet[2203]: I1213 15:24:25.882055    2203 kubelet_node_status.go:64] Attempting to register node 172.18.18.102
Dec 13 15:24:25 k8s-node-01 kubelet[2203]: I1213 15:24:25.901495    2203 kubelet_node_status.go:103] Node 172.18.18.102 was previously registered
Dec 13 15:24:25 k8s-node-01 kubelet[2203]: I1213 15:24:25.902118    2203 kubelet_node_status.go:67] Successfully registered node 172.18.18.102
Dec 13 15:24:30 k8s-node-01 kubelet[2203]: W1213 15:24:30.729283    2203 pod_container_deletor.go:77] Container "b2bec15575212b5fbb59a86349565408b8ce0e7006839b56d917804de1e11148" not found in pod's containers
Dec 13 15:24:30 k8s-node-01 kubelet[2203]: W1213 15:24:30.730988    2203 pod_container_deletor.go:77] Container "f7cd0e581644ed52cc6c9789736feb7be3565c6f07cbb67c1f2a3ddb4bdeed10" not found in pod's containers
Dec 13 15:24:30 k8s-node-01 kubelet[2203]: W1213 15:24:30.731030    2203 pod_container_deletor.go:77] Container "41a9cc6d06ba1c4e78f5ac6fb0a1ba598bbe692d03c4110457ca955bd1fa3755" not found in pod's containers
Dec 13 15:24:30 k8s-node-01 kubelet[2203]: I1213 15:24:30.905196    2203 reconciler.go:225] VerifyControllerAttachedVolume operation started for volume "kubernetes.io/host-path/05d052a8-adae-11e6-b224-080027db44c2-lib-modules" (spec.Name
Dec 13 15:24:30 k8s-node-01 kubelet[2203]: I1213 15:24:30.905632    2203 reconciler.go:225] VerifyControllerAttachedVolume operation started for volume "kubernetes.io/host-path/05d052a8-adae-11e6-b224-080027db44c2-var-run-calico" (spec.N
Dec 13 15:24:30 k8s-node-01 kubelet[2203]: I1213 15:24:30.906223    2203 reconciler.go:225] VerifyControllerAttachedVolume operation started for volume "kubernetes.io/host-path/05d052a8-adae-11e6-b224-080027db44c2-cni-bin-dir" (spec.Name
Dec 13 15:24:30 k8s-node-01 kubelet[2203]: I1213 15:24:30.906808    2203 reconciler.go:225] VerifyControllerAttachedVolume operation started for volume "kubernetes.io/host-path/05d052a8-adae-11e6-b224-080027db44c2-cni-net-dir" (spec.Name
Dec 13 15:24:30 k8s-node-01 kubelet[2203]: I1213 15:24:30.907383    2203 reconciler.go:225] VerifyControllerAttachedVolume operation started for volume "kubernetes.io/secret/05d052a8-adae-11e6-b224-080027db44c2-default-token-ccwdm" (spec
Dec 13 15:24:31 k8s-node-01 kubelet[2203]: I1213 15:24:31.008144    2203 reconciler.go:299] MountVolume operation started for volume "kubernetes.io/host-path/05d052a8-adae-11e6-b224-080027db44c2-cni-net-dir" (spec.Name: "cni-net-dir") to
Dec 13 15:24:31 k8s-node-01 kubelet[2203]: I1213 15:24:31.008215    2203 reconciler.go:299] MountVolume operation started for volume "kubernetes.io/secret/05d052a8-adae-11e6-b224-080027db44c2-default-token-ccwdm" (spec.Name: "default-tok
Dec 13 15:24:31 k8s-node-01 kubelet[2203]: I1213 15:24:31.008238    2203 reconciler.go:299] MountVolume operation started for volume "kubernetes.io/host-path/05d052a8-adae-11e6-b224-080027db44c2-lib-modules" (spec.Name: "lib-modules") to
Dec 13 15:24:31 k8s-node-01 kubelet[2203]: I1213 15:24:31.008283    2203 reconciler.go:299] MountVolume operation started for volume "kubernetes.io/host-path/05d052a8-adae-11e6-b224-080027db44c2-var-run-calico" (spec.Name: "var-run-calic
Dec 13 15:24:31 k8s-node-01 kubelet[2203]: I1213 15:24:31.008325    2203 reconciler.go:299] MountVolume operation started for volume "kubernetes.io/host-path/05d052a8-adae-11e6-b224-080027db44c2-cni-bin-dir" (spec.Name: "cni-bin-dir") to
Dec 13 15:24:31 k8s-node-01 kubelet[2203]: I1213 15:24:31.008401    2203 operation_executor.go:802] MountVolume.SetUp succeeded for volume "kubernetes.io/host-path/05d052a8-adae-11e6-b224-080027db44c2-cni-bin-dir" (spec.Name: "cni-bin-di
Dec 13 15:24:31 k8s-node-01 kubelet[2203]: I1213 15:24:31.008482    2203 operation_executor.go:802] MountVolume.SetUp succeeded for volume "kubernetes.io/host-path/05d052a8-adae-11e6-b224-080027db44c2-cni-net-dir" (spec.Name: "cni-net-di
Dec 13 15:24:31 k8s-node-01 kubelet[2203]: I1213 15:24:31.010532    2203 operation_executor.go:802] MountVolume.SetUp succeeded for volume "kubernetes.io/host-path/05d052a8-adae-11e6-b224-080027db44c2-lib-modules" (spec.Name: "lib-module
Dec 13 15:24:31 k8s-node-01 kubelet[2203]: I1213 15:24:31.010638    2203 operation_executor.go:802] MountVolume.SetUp succeeded for volume "kubernetes.io/host-path/05d052a8-adae-11e6-b224-080027db44c2-var-run-calico" (spec.Name: "var-run
Dec 13 15:24:31 k8s-node-01 kubelet[2203]: I1213 15:24:31.032125    2203 operation_executor.go:802] MountVolume.SetUp succeeded for volume "kubernetes.io/secret/05d052a8-adae-11e6-b224-080027db44c2-default-token-ccwdm" (spec.Name: "defau
Dec 13 15:24:31 k8s-node-01 kubelet[2203]: E1213 15:24:31.056636    2203 docker_manager.go:746] Logging security options: {key:seccomp value:unconfined msg:}
Dec 13 15:24:31 k8s-node-01 kubelet[2203]: E1213 15:24:31.201896    2203 docker_manager.go:746] Logging security options: {key:seccomp value:unconfined msg:}
Dec 13 15:24:40 k8s-node-01 kubelet[2203]: E1213 15:24:40.286511    2203 docker_manager.go:746] Logging security options: {key:seccomp value:unconfined msg:}
Dec 13 15:24:40 k8s-node-01 kubelet[2203]: I1213 15:24:40.993249    2203 reconciler.go:299] MountVolume operation started for volume "kubernetes.io/secret/05d052a8-adae-11e6-b224-080027db44c2-default-token-ccwdm" (spec.Name: "default-tok
Dec 13 15:24:40 k8s-node-01 kubelet[2203]: I1213 15:24:40.997521    2203 operation_executor.go:802] MountVolume.SetUp succeeded for volume "kubernetes.io/secret/05d052a8-adae-11e6-b224-080027db44c2-default-token-ccwdm" (spec.Name: "defau
Dec 13 15:24:42 k8s-node-01 kubelet[2203]: I1213 15:24:42.000650    2203 reconciler.go:299] MountVolume operation started for volume "kubernetes.io/secret/05d052a8-adae-11e6-b224-080027db44c2-default-token-ccwdm" (spec.Name: "default-tok
Dec 13 15:24:42 k8s-node-01 kubelet[2203]: I1213 15:24:42.005725    2203 operation_executor.go:802] MountVolume.SetUp succeeded for volume "kubernetes.io/secret/05d052a8-adae-11e6-b224-080027db44c2-default-token-ccwdm" (spec.Name: "defau
Dec 13 15:24:45 k8s-node-01 kubelet[2203]: E1213 15:24:45.688736    2203 file.go:53] Unable to read config path "/etc/kubernetes/manifests": path does not exist, ignoring
Dec 13 15:24:45 k8s-node-01 kubelet[2203]: W1213 15:24:45.948786    2203 conversion.go:110] Could not get instant cpu stats: different number of cpus
Dec 13 15:24:55 k8s-node-01 kubelet[2203]: I1213 15:24:55.229950    2203 server.go:218] Checking API server for new Kubelet configuration.
Dec 13 15:24:55 k8s-node-01 kubelet[2203]: W1213 15:24:55.230799    2203 server.go:549] Could not load kubeconfig file /var/lib/kubelet/kubeconfig: stat /var/lib/kubelet/kubeconfig: no such file or directory. Using default client config
Dec 13 15:24:55 k8s-node-01 kubelet[2203]: I1213 15:24:55.234638    2203 server.go:227] Did not find a configuration for this Kubelet via API server: cloud provider was nil, and attempt to use hostname to find config resulted in: configm
Dec 13 15:24:56 k8s-node-01 kubelet[2203]: W1213 15:24:56.004268    2203 conversion.go:110] Could not get instant cpu stats: different number of cpus
Dec 13 15:25:05 k8s-node-01 kubelet[2203]: E1213 15:25:05.690517    2203 file.go:53] Unable to read config path "/etc/kubernetes/manifests": path does not exist, ignoring

It seems that kubelet is started without calico and calico-ipam
Is there some thing wrong that I did?  
Thanks a lot.

**Comment by tmjd** [comment]
@HongjunNi Were you ever able to fix the issue you were having?  I have followed the directions at http://docs.projectcalico.org/v1.5/getting-started/kubernetes/installation/vagrant/ and am able to start up pods that get a calico IP address.
The only problem I had was getting the kubernetes services started but I believe my issue was due to slow downloads of the binaries that the services pull down.  I was able to get around this by adding `TimeoutStartSec=infinity` to each of the service definitions in the cloud configs.  I do not believe you were having this issue but just wanted to mention it in case you wanted to try with that modification.

**Comment by caseydavenport** [comment]
@tmjd maybe we should be fixing that timeout in our demos by default? I suspect you're not the only one to have hit that.

**Comment by HongjunNi** [comment]
@tmjd This issue has not yet fixed after some tries. These days, I have been working on other project, and will give it a try next week. Thank you so much.

**Comment by tmjd** [comment]
I'm going to close this issue for the time being.  @HongjunNi if you are able to revisit this issue, preferably using the latest Calico release, and still continue to have the same problem feel free to reopen this issue.  Obviously if you run into other issues please create a new issue.  As always, you can checkout https://calicousers.slack.com for help too.
