### ISSUE TITLE
If an Official Declaration about the Arm64 Support of Calico available

### ISSUE THREAD

**Issue by TrevorTaoARM** [projectcalico/calico#3783]
Now all the Calico images are multi-arched which support both amd64 and arm64, and the major Kubernetes installation file:
https://docs.projectcalico.org/manifests/calico.yaml also supports the installation of Calico on arm64. So I think the Calico can support both amd64 and arm64.

But we still lack of an official declaration about the arm64 support of Calico which may include the following info:
1. The project Calico can support arm64 officially, the installation is available for both x86_64(amd64) and aarch64(arm64);
2. The needed images and installation files for Calico k8s installation are available for both x86_64(amd64) and aarch64(arm64);
3. The images for aarch64 platform are available for v3.15.1 and would be provided in the following releases;
4. The CI for arm64 platform is also ready(optional)
5. Other important things about Calico Arm64 support ...

I think the ProjectCalico community had made great efforts to enable the multi-platform support for arm64 platform and it's very attactive to see the official declaration for the Calico arm64 support which would tag the enrichment of Calico ecosystem. 

Thank you very much;

**Comment by lwr20** [comment]
I believe the official line here is that Calico ARM64 is **community supported.**
The reason for that is that while Calico has automatic ARM builds, it does not have ARM CI and e2e tests.
That said, it has been stably working for a long while now.

**Comment by TrevorTaoARM** [comment]
> I believe the official line here is that Calico ARM64 is **community supported.**
> The reason for that is that while Calico has automatic ARM builds, it does not have ARM CI and e2e tests.
> That said, it has been stably working for a long while now.

@lwr20 It's very nice to hear that. And it would be greatly appreciated if the anoucemount of the official Arm support could be appeared on the next official Calico release notes.
Thank you so much.

**Comment by lwr20** [comment]
It was announced on the Calico blog back when it went in: 
https://www.projectcalico.org/announcing-calico-v3-2/

and it appeared in the release notes for that version: 
https://docs.projectcalico.org/archive/v3.2/releases#multiple-architectures

**Comment by TrevorTaoARM** [comment]
> It was announced on the Calico blog back when it went in:
> https://www.projectcalico.org/announcing-calico-v3-2/
> 
> and it appeared in the release notes for that version:
> https://docs.projectcalico.org/archive/v3.2/releases#multiple-architectures

@lwr20 Thanks. It's great to learn that.
