### ISSUE TITLE
H1 and H2 size look very similar 

### ISSUE THREAD

**Issue by gunjan5** [projectcalico/calico#38]
need to change H2 text size to be smaller in CSS.
Sub-topics are very hard to differentiate with H1 and H2 sizes being very similar.
See this doc for example: https://tigera.github.io/calico/master/reference/architecture/

**Comment by djosborne** [comment]
H1's should not be used more than once (or in documentation at all for that matter), as per https://github.com/projectcalico/calico/issues/39#issuecomment-251835326
