### ISSUE TITLE
Use `quay.io/calico/node`

### ISSUE THREAD

**Issue by caseydavenport** [projectcalico/calico#380]
#We should update master docs to point at quay.io/calico/*

**Comment by djosborne** [comment]
Keeping this as a v2.1 milestone since the default node image launched by calicoctl was changed from `[default: calico/node:%s]` to `[default: quay.io/calico/node:%s]` (https://github.com/projectcalico/calicoctl/commit/9c48a1407f69ecc427a974735840a7819b4e37f1)

Our master docs are now "wrong".

**Comment by cmluciano** [comment]
Are these the areas particularly that need to be updated https://github.com/projectcalico/calico/search?utf8=✓&q=registry

**Comment by djosborne** [comment]
@cmluciano Those, as well as anywhere we run the `calico/node` container. This PR is a half-baked attempt at getting them all: https://github.com/projectcalico/calico/issues/459
