### ISSUE TITLE
Add more rkt guides

### ISSUE THREAD

**Issue by robbrockbank** [projectcalico/calico#381]
The rkt section needs beefing up.  We should add:

- [ ] More installation options (cloud based)
- [ ] More tutorials (advanced policy).  Note this requires CNI changes to expose labels.
- [ ] More troubleshooting docs
- [ ] Upgrade doc

**Comment by djosborne** [comment]
I don't know that some of this is needed. Most folks aren't using rkt as an orchestrator (via commandline), but merely a container engine. That means they're not interested in Upgrade Docs or usage tutorials, as that's usually abstracted into the orchestrator.

**Comment by caseydavenport** [comment]
I don't think it's v2.0.1.  We may want these docs eventually though.
