### ISSUE TITLE
Calico node-to-node mesh nodes advertising all peer node prefixes to global router

### ISSUE THREAD

**Issue by starcraft66** [projectcalico/calico#3810]
## Context
I installed calico in my brand-new IPv6-only kubernetes cluster and I'm experiencing connectivity issues with my pods. Right now, it is setup as a node-to-node mesh with 3 nodes which are peering via bgp. My nodes are also peering with my router running VyOS via bgp. The problem I diagnosed is that when the node-to-node mesh is enabled, all of the calico nodes advertise every single route/prefix in the cluster to my VyOS router. This causes a problem because the router thinks every node prefix is reachable via any node in the cluster and messes up the return path of outgoing packets from my kubernetes pods because the response packets are sometimes routed to the wrong nodes.

If I disable the node-to-node mesh, everything works as expected and every node only advertises its own prefix to the router and everything functions correctly except that the nodes obviously don't peer with each other anymore and this incurs an extra penalty where packets originating from one node to another node must pass through the router instead of being routed to the correct node immediately without an extra hop.

## Expected Behavior
I expect the BGP routing table on my router to look something like this with node-to-node mesh enabled (this is how it looks when I disable the node-to-node mesh):
```
vyos@235-gw# run show ipv6 bgp
BGP table version is 27, local router ID is 172.32.1.1, vrf id 0
Default local pref 100, local AS 64512
Status codes:  s suppressed, d damped, h history, * valid, > best, = multipath,
               i internal, r RIB-failure, S Stale, R Removed
Nexthop codes: @NNN nexthop's vrf id, < announce-nh-self
Origin codes:  i - IGP, e - EGP, ? - incomplete
   Network          Next Hop            Metric LocPrf Weight Path
*> 2607:fa48:6ed8:8a54:1:118d:947a:ebc0/122
                    2607:fa48:6ed8:8a54::100:3
                                                           0 64513 i
*> 2607:fa48:6ed8:8a54:1:1ed1:b573:50c0/122
                    2607:fa48:6ed8:8a54::100:2
                                                           0 64513 i
*> 2607:fa48:6ed8:8a54:1:ad13:6304:2440/122
                    2607:fa48:6ed8:8a54::100:1
                                                           0 64513 i
Displayed  3 routes and 3 total paths
```

## Current Behavior
Currently, with node-to-node mesh enables, my bgp routing table looks like this:
```
vyos@235-gw# run show ipv6 bgp
BGP table version is 27, local router ID is 172.32.1.1, vrf id 0
Default local pref 100, local AS 64512
Status codes:  s suppressed, d damped, h history, * valid, > best, = multipath,
               i internal, r RIB-failure, S Stale, R Removed
Nexthop codes: @NNN nexthop's vrf id, < announce-nh-self
Origin codes:  i - IGP, e - EGP, ? - incomplete
   Network          Next Hop            Metric LocPrf Weight Path
*= 2607:fa48:6ed8:8a54:1:118d:947a:ebc0/122
                    2607:fa48:6ed8:8a54::100:3
                                                           0 64513 i
*=                  2607:fa48:6ed8:8a54::100:2
                                                           0 64513 i
*>                  2607:fa48:6ed8:8a54::100:1
                                                           0 64513 i
*= 2607:fa48:6ed8:8a54:1:1ed1:b573:50c0/122
                    2607:fa48:6ed8:8a54::100:3
                                                           0 64513 i
*=                  2607:fa48:6ed8:8a54::100:1
                                                           0 64513 i
*>                  2607:fa48:6ed8:8a54::100:2
                                                           0 64513 i
*= 2607:fa48:6ed8:8a54:1:ad13:6304:2440/122
                    2607:fa48:6ed8:8a54::100:3
                                                           0 64513 i
*=                  2607:fa48:6ed8:8a54::100:1
                                                           0 64513 i
S                   2607:fa48:6ed8:8a54::100:1
                                                           0 64513 i
*>                  2607:fa48:6ed8:8a54::100:2
                                                           0 64513 i
Displayed  3 routes and 10 total paths
```

## Steps to Reproduce (for bugs)
1. Start a new kubernetes cluster with ipv6 networking
2. Install calico
3. Configure router to peer with nodes using local AS 64512, remote AS 64513
4. Apply the following yaml using `calicoctl` (adjust peer ip) and inspect bgp routing table on router
```
apiVersion: projectcalico.org/v3
kind: BGPConfiguration
metadata:
  name: default
spec:
  logSeverityScreen: Info
  nodeToNodeMeshEnabled: true
  asNumber: 64513
---
apiVersion: projectcalico.org/v3
kind: BGPPeer
metadata:
  name: "235-gw"
spec:
  peerIP: 2607:fa48:6ed8:8a54::1
  asNumber: 64512
```

## Your Environment

* Calico version 3.12.2
* Kubernetes version 1.18.6
* Ubuntu 20.04

**Comment by caseydavenport** [comment]
If I remember correctly, it is expected that routes advertised over an eBGP connection have their original next hop replaced with the next hop of the advertising router (which is the behavior that you're seeing).

This has come up before as well, I think this is more or less the same ask: https://github.com/projectcalico/confd/issues/308

I think we at least need a way to configure this behavior per-peer.

**Comment by caseydavenport** [comment]
That said, I think your only option with the current code is to do as you've said - that is, route traffic through the external router and remove the mesh peerings.

**Comment by elgamal2020** [comment]
I have a similar behaviour , is this issue still valid ??

```
net show route vrf rocket bgp
show ip route vrf rocket bgp
============================
Codes: K - kernel route, C - connected, S - static, R - RIP,
       O - OSPF, I - IS-IS, B - BGP, E - EIGRP, N - NHRP,
       T - Table, v - VNC, V - VNC-Direct, A - Babel, D - SHARP,
       F - PBR, f - OpenFabric,
       > - selected route, * - FIB route, q - queued, r - rejected, b - backup
       t - trapped, o - offload failure

VRF rocket:
B>* 10.233.0.0/18 [20/0] via 10.10.20.6, swp2, weight 1, 1d03h05m
  *                      via 10.10.20.86, swp2, weight 1, 1d03h05m
  *                      via 10.10.20.104, swp2, weight 1, 1d03h05m
  *                      via 10.10.20.180, swp2, weight 1, 1d03h05m
B>* 10.233.19.117/32 [20/0] via 10.10.20.6, swp2, weight 1, 1d03h05m
  *                         via 10.10.20.86, swp2, weight 1, 1d03h05m
  *                         via 10.10.20.104, swp2, weight 1, 1d03h05m
  *                         via 10.10.20.180, swp2, weight 1, 1d03h05m
B>* 10.233.87.128/26 [20/0] via 10.10.20.6, swp2, weight 1, 1d03h05m
  *                         via 10.10.20.86, swp2, weight 1, 1d03h05m
  *                         via 10.10.20.104, swp2, weight 1, 1d03h05m
  *                         via 10.10.20.180, swp2, weight 1, 1d03h05m
B>* 10.233.91.192/26 [20/0] via 10.10.20.6, swp2, weight 1, 1d03h05m
  *                         via 10.10.20.86, swp2, weight 1, 1d03h05m
  *                         via 10.10.20.104, swp2, weight 1, 1d03h05m
  *                         via 10.10.20.180, swp2, weight 1, 1d03h05m
B>* 10.233.98.192/26 [20/0] via 10.10.20.6, swp2, weight 1, 1d03h05m
  *                         via 10.10.20.86, swp2, weight 1, 1d03h05m
  *                         via 10.10.20.104, swp2, weight 1, 1d03h05m
  *                         via 10.10.20.180, swp2, weight 1, 1d03h05m
B>* 10.233.123.64/26 [20/0] via 10.10.20.6, swp2, weight 1, 1d03h05m
  *                         via 10.10.20.86, swp2, weight 1, 1d03h05m
  *                         via 10.10.20.104, swp2, weight 1, 1d03h05m
  *                         via 10.10.20.180, swp2, weight 1, 1d03h05m
B>* 10.240.60.0/24 [20/0] via 10.10.20.6, swp2, weight 1, 1d03h05m
  *                       via 10.10.20.86, swp2, weight 1, 1d03h05m
  *                       via 10.10.20.104, swp2, weight 1, 1d03h05m
  *                       via 10.10.20.180, swp2, weight 1, 1d03h05m
B>* 10.250.0.0/24 [20/0] via 10.10.20.6, swp2, weight 1, 1d03h05m
  *                      via 10.10.20.86, swp2, weight 1, 1d03h05m
  *                      via 10.10.20.104, swp2, weight 1, 1d03h05m
  *                      via 10.10.20.180, swp2, weight 1, 1d03h05m
```


```
calicoctl version
Client Version:    v3.23.3
Git commit:        3a3559be1
Cluster Version:   v3.23.3
Cluster Type:      k8s,bgp,kubeadm,kdd
```

**Comment by starcraft66** [comment]
@elgamal2020 I belive this can now be fixed by setting `keepOriginalNextHop: true` in the `BGPPeer` spec. https://projectcalico.docs.tigera.io/reference/resources/bgppeer

**Comment by elgamal2020** [comment]
Thanks alot @starcraft66  , this solved my issue 

I would think this configuration should be make default , is there any other case , while it is not required ?

**Comment by xoxys** [comment]
> @elgamal2020 I belive this can now be fixed by setting `keepOriginalNextHop: true` in the `BGPPeer` spec. https://projectcalico.docs.tigera.io/reference/resources/bgppeer

Mhm, I still see this behavior even if  `keepOriginalNextHop: true` is set. Am I doing something wrong? I ended up with a `BGPFilter` applied to the `BGPPeer` to only export e.g. the `serviceLoadBalancerIPs` cidr for now, not sure if that's the correct way.

**Comment by caseydavenport** [comment]
> Mhm, I still see this behavior even if keepOriginalNextHop: true is set. Am I doing something wrong? 

I would expect keepOriginalNextHop to maintain the original next hop when advertising routes, although this potentially is influenced by your BGP topology - which links are iBGP vs eBGP, etc.

A BGPFilter to limit exported routes is a perfectly fine way to do this IMO, and is probably a better solution than advertising unnecessary routes anyway.
