### ISSUE TITLE
After upgrading calico-only-policy from 3.14 to 3.15 calico-node Daemonsets are hanging.

### ISSUE THREAD

**Issue by vishahk** [projectcalico/calico#3828]
Sorry.. Updating calico version. its 3.X.X  I am trying to Upgrade from 3.14 to 3.15.1
## Expected Behavior
SHould start calico-node pods in kube-system 

I see the script /bin/startup-calico-node  is calling command "calico-node -allocate-tunnel-addrs" which just seats there like hung. 

## Your Environment

* Calico version   3.15.1
* Orchestrator version (e.g. kubernetes, mesos, rkt):  Kubernetes 1.16.8
* Operating System and version:  OL7
* Link to your project (optional):

**Comment by caseydavenport** [comment]
@vishahk could you share a bit more about how you did the upgrade? 

How did you create your cluster, and have you made any changes to the Calico manifests provided at docs.projectcalico.org?

**Comment by caseydavenport** [comment]
Could you provide the manifest and the logs from a failing calico/node instance?

**Comment by vishahk** [comment]
@caseydavenport 
This is fixed. I am compiling calico binaries from source and then bundling those in docker images before they are deployed. In  "calico-node" command in calico v3.15 start up script requires "-allocate-tunnel-addrs-run-once" or the command just seats there. Here is the diff from v3.14.

 # If possible pre-allocate any tunnel addresses.
-calico-node -allocate-tunnel-addrs || exit 1
+calico-node -allocate-tunnel-addrs -allocate-tunnel-addrs-run-once || exit 1

 echo "Calico node started successfully"
