### ISSUE TITLE
kube-controller-manager excessive logging of Flexvolume 'unexpected end of JSON input'

### ISSUE THREAD

**Issue by IliaGershenzon** [projectcalico/calico#3833]
After upgrading to Calico 3.14.1 on K8S 1.17.9 the kube-controller-manager starts with excessive logging of

```
E0725 15:02:40.955274    2252 driver-call.go:266] Failed to unmarshal output for command: init, output: "", error: unexpected end of JSON input
E0725 15:02:40.955301    2252 plugins.go:734] Error dynamically probing plugins: Error creating Flexvolume plugin from directory nodeagent~uds, skipping. Error: unexpected end of JSON input
```

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Calico version - 3.14.1
* Orchestrator version (e.g. kubernetes, mesos, rkt): Kubernetes
* Operating System and version: CentOS 7 + Ubuntu 18.04
* Link to your project (optional):

**Comment by caseydavenport** [comment]
How did you create your Kubernetes cluster? Is this with kubeadm, kops, some other installer?

I really need a bit more information in order to help with this - could you please fill out the rest of the issue template, including steps to reproduce?
