### ISSUE TITLE
DualStack Floating IPs are ending in a crashloop

### ISSUE THREAD

**Issue by fionera** [projectcalico/calico#3838]
Hi, as already discussed on the Slack, the Calico CNI Plugin currently doesnt support DualStack FloatingIPs because the nat adresses arent getting the correct InternalIP. 

## Expected Behavior
`cni.projectcalico.org/floatingIPs: '["195.160.168.193", "2001:67c:275c:ff::1"]` should work with the floatingIP Annotation.

## Current Behavior
The Pod goes into a crashloop with the error `error with field ExternalIP = 'aabb::abcd' (mismatched IP versions)`

## Possible Solution
https://github.com/projectcalico/cni-plugin/pull/922

## Steps to Reproduce (for bugs)
@neiljerram made a Test to reproduce the Bug: https://github.com/neiljerram/node/commit/32b7242b5d471bc30d19e2f235b326bb2b45b144
1. Create a Pod with a v4 and v6 floatingIP
2. See that it crashes

## Context
I cannot run Pods with a floating v6 address.

## Your Environment
* Calico version: v3.13.4
* Orchestrator version (e.g. kubernetes, mesos, rkt): 1.18.3
* Operating System and version: Ubuntu 20.04

**Comment by neiljerram** [comment]
Fixed by https://github.com/projectcalico/cni-plugin/pull/922 for Calico v3.17.
