### ISSUE TITLE
Docker guides have important steps under 'Requirements'

### ISSUE THREAD

**Issue by matthewdupre** [projectcalico/calico#384]
http://docs.projectcalico.org/v2.0/getting-started/docker/

Setting a --cluster-store is an essential step; but the 'Requirements' section sounds like something people will skip, because it doesn't imply that they need to actually *do* anything.  I think I'd prefer Prerequisites, if we don't move the step into the main guide.

If they do skip it, things will fail in cryptic ways.

WDPT?

**Comment by djosborne** [comment]
@matthewdupre Though this doesn't really change anything - it's named Requirements for consistency with our other orchestrator getting started guides.

But we should take this opportunity to decide what we want to do with `docker/requirements.md`, by picking up on this conversation @robbrockbank and I had earlier: https://github.com/projectcalico/calico/pull/331#pullrequestreview-12287142

Should we just move those requirements into the install guide?
