### ISSUE TITLE
calico 3.15.1 manifest invalid yaml

### ISSUE THREAD

**Issue by marshallford** [projectcalico/calico#3846]
The yaml manifest available here `https://docs.projectcalico.org/manifests/calico.yaml` does not appear to be valid.

```
❯ kubectl apply -f calico.yaml
configmap/calico-config unchanged
customresourcedefinition.apiextensions.k8s.io/bgpconfigurations.crd.projectcalico.org configured
customresourcedefinition.apiextensions.k8s.io/bgppeers.crd.projectcalico.org configured
customresourcedefinition.apiextensions.k8s.io/blockaffinities.crd.projectcalico.org configured
customresourcedefinition.apiextensions.k8s.io/clusterinformations.crd.projectcalico.org configured
error: error parsing calico.yaml: error converting YAML to JSON: yaml: control characters are not allowed
```

From https://codebeautify.org/yaml-validator:
```
Error : Unexpected characters near "'s BPF maps and cannot insert their own".
Line : 402    users cannot access Calico''s BPF maps and cannot insert their own
```

**Comment by caseydavenport** [comment]
@marshallford thanks for raising this, it looks like there are extra quotes in that manifest in the FelixConfiguration CRD. You should be able to workaround this by removing them for now.

I'll make sure we get a fix in the docs ASAP.

**Comment by caseydavenport** [comment]
@marshallford can I ask if you've made any changes to that manifest locally?

When I run the following command on a fresh v1.16.13 Kubernetes cluster, I get a successful apply:

```
kubectl apply -f https://docs.projectcalico.org/manifests/calico.yaml                                                                                                                                                                       
configmap/calico-config created
customresourcedefinition.apiextensions.k8s.io/bgpconfigurations.crd.projectcalico.org created
customresourcedefinition.apiextensions.k8s.io/bgppeers.crd.projectcalico.org created
customresourcedefinition.apiextensions.k8s.io/blockaffinities.crd.projectcalico.org created
customresourcedefinition.apiextensions.k8s.io/clusterinformations.crd.projectcalico.org created
customresourcedefinition.apiextensions.k8s.io/felixconfigurations.crd.projectcalico.org created
customresourcedefinition.apiextensions.k8s.io/globalnetworkpolicies.crd.projectcalico.org created
customresourcedefinition.apiextensions.k8s.io/globalnetworksets.crd.projectcalico.org created
customresourcedefinition.apiextensions.k8s.io/hostendpoints.crd.projectcalico.org created
customresourcedefinition.apiextensions.k8s.io/ipamblocks.crd.projectcalico.org created
customresourcedefinition.apiextensions.k8s.io/ipamconfigs.crd.projectcalico.org created
customresourcedefinition.apiextensions.k8s.io/ipamhandles.crd.projectcalico.org created
customresourcedefinition.apiextensions.k8s.io/ippools.crd.projectcalico.org created
customresourcedefinition.apiextensions.k8s.io/kubecontrollersconfigurations.crd.projectcalico.org created
customresourcedefinition.apiextensions.k8s.io/networkpolicies.crd.projectcalico.org created
customresourcedefinition.apiextensions.k8s.io/networksets.crd.projectcalico.org created
clusterrole.rbac.authorization.k8s.io/calico-kube-controllers created
clusterrolebinding.rbac.authorization.k8s.io/calico-kube-controllers created
clusterrole.rbac.authorization.k8s.io/calico-node created
clusterrolebinding.rbac.authorization.k8s.io/calico-node created
daemonset.apps/calico-node created
serviceaccount/calico-node created
deployment.apps/calico-kube-controllers created
serviceaccount/calico-kube-controllers created
```

**Comment by caseydavenport** [comment]
The only difference I can think of is that mine is a fresh cluster and yours seems to already have Calico installed. What version is the cluster currently running?

**Comment by caseydavenport** [comment]
So, I'm led to believe that both the version of kubectl you're using as well as the linked yaml validator are not correct, which is very surprising, so I might be wrong. What version of kubectl are you using?

**Comment by marshallford** [comment]
Ahhhh I may have cracked it. I'm seeing different behavior between `wget https://docs.projectcalico.org/manifests/calico.yaml -O test.yaml && kubectl apply -f test.yaml` (or just `kubectl apply -f https://docs.projectcalico.org/manifests/calico.yaml`) **and** copy and pasting the yaml in the browser to a local file. The difference lies within the encoding? of the apostrophes. L205 for example on a default install.

```
// direct download L205
remote AS number comes from the remote node’s NodeBGPSpec.ASNumber,

// C&P
remote AS number comes from the remote nodeâ€™s NodeBGPSpec.ASNumber,
```

**Comment by Quentin-M** [comment]
I literally just ran into this myself. Copy-pasting https://docs.projectcalico.org/manifests/calico-typha.yaml into IntelliJ IDEA makes me run into the following:

```
customresourcedefinition.apiextensions.k8s.io/bgpconfigurations.crd.projectcalico.org configured
customresourcedefinition.apiextensions.k8s.io/bgppeers.crd.projectcalico.org configured
customresourcedefinition.apiextensions.k8s.io/blockaffinities.crd.projectcalico.org configured
customresourcedefinition.apiextensions.k8s.io/clusterinformations.crd.projectcalico.org configured
error: error parsing /Users/qmachu/Workspace/bitmex/k8s-configs/modules/kubernetes/spec/resources/k8s_resources/networking/.calico.upstream.yaml: error converting YAML to JSON: yaml: control characters are not allowed
```

The file yielded by wget/curl is quite different than the new I got by copy-pasting into my IDE.  That kind of encoding issues all over the place -->

```
-                    remote AS number comes from the remote nodeâ€™s NodeBGPSpec.ASNumber,
+                    remote AS number comes from the remote node’s NodeBGPSpec.ASNumber,
```


It now works properly. This is some next-level bullshit 😳

**Comment by caseydavenport** [comment]
Yeah ok, this seems to be something about the escaping getting messed up while doing a copy/paste rather than a direct download of the manifest. 

Adding another data point - I copy/pasted from the browser into vim and the original escaping of the apostrophe is left intact and the yaml applies cleanly. So, I think this might be something to do with how the editor you're pasting into handles the escaped characters?

**Comment by caseydavenport** [comment]
This appears to be a problem with the way some editors handle pasted yaml, rather than the Calico manifest themselves being malformed.

**Comment by TheKangaroo** [comment]
Just wanted to mention here, that this is still a problem if you open the yaml in chrome and copy it from there. I'll try to paste it here, the diff is, for example:
```
wget
                  iptables “DROP” action. If you want to allow some or all traffic
copied from chrome
                  iptables â€œDROPâ€ action. If you want to allow some or all traffic
```
is there any reason to use “ over " or ' in the crd descriptions?

**Comment by marshallford** [comment]
> is there any reason to use “ over " or ' in the crd descriptions?

That was my thought as well. I looked at making a PR but couldn't find the true "source" or input that is used to generated the released manifests. Maybe someone else can poke around?

**Comment by caseydavenport** [comment]
There's no reason we need to use those characters.This has been on the back of my mind for a while but I haven't gotten around to fixing it yet (I think there's another issue open tracking it). 

The yaml itself is generated from code comments in this package, if you'd like to look at fixing it!

https://github.com/projectcalico/libcalico-go/tree/master/lib/apis/v3
