### ISSUE TITLE
rr aggregate route

### ISSUE THREAD

**Issue by 3Golds** [projectcalico/calico#3848]
Hello, everybody. When I used Calico bgpPeer, the route I saw for the exchange was:
```
10.16.1.0/24
10.16.2.0/24
10.16.3.0/24
```
Can RR be aggregated to 10.16.0.0/16 and sent out?

**Comment by gunboe** [comment]
I think that is not possible, distribution routes are random on Cluster: a Node can receive 10.16.1.0/24 and other Node can receive 10.16.2.0/24, so aggregating route does not work. Thats could be a border router function, summarizing all of then to an external gateway.

**Comment by caseydavenport** [comment]
Calico will aggregate routes within a particular node, but it cannot control what downstream aggregation occurs at other points in the network.

You can use ip pool `nodeSelectors` to make sure that certain IP ranges are allocated to certain racks, for example, and then use aggregation at the ToR to represent the entire rack as a single route. 

However, I don't think Calico itself can do any further aggregation - you wouldn't want a Calico node advertising a route that included pods that weren't actually running on that node.

**Comment by 3Golds** [comment]
Understand, thank you @gunboe
