### ISSUE TITLE
Unable to connect to the server: dial tcp 54.206.19.82:443: i/o timeout when applying quickstart tigera-operator.yaml

### ISSUE THREAD

**Issue by stevecollett** [projectcalico/calico#3868]
Creating a simple Ubunto 18.04 virtual box based kubernetes cluster and trying to use Calico quickstart following instructions here

https://docs.projectcalico.org/getting-started/kubernetes/quickstart

There is 1 Ubuntu 18.04 virtual box with NAT and Host only network adapter on 192.168.99.200

## Expected Behavior

Kubeadmin init works fine 

sudo kubeadm init --apiserver-advertise-address=192.168.99.200 --pod-network-cidr=192.168.0.0/16

Then running this command should complete - and has done on another VM box running on same Host (currently turned off)

 sudo kubectl create -v=8 -f https://docs.projectcalico.org/manifests/tigera-operator.yaml

## Current Behavior

Get this error 

vagrant@kubecontrol:~$ sudo kubectl create -v=8 -f https://docs.projectcalico.org/manifests/tigera-operator.yaml
I0812 01:22:37.682816    4106 loader.go:375] Config loaded from file:  /home/vagrant/.kube/config
I0812 01:22:37.691990    4106 round_trippers.go:420] GET https://192.168.99.200:6443/openapi/v2?timeout=32s
I0812 01:22:37.692979    4106 round_trippers.go:427] Request Headers:
I0812 01:22:37.693993    4106 round_trippers.go:431]     Accept: application/com.github.proto-openapi.spec.v2@v1.0+protobuf
I0812 01:22:37.694733    4106 round_trippers.go:431]     User-Agent: kubectl/v1.18.6 (linux/amd64) kubernetes/dff82dc
I0812 01:22:37.761495    4106 round_trippers.go:446] Response Status: 200 OK in 66 milliseconds
I0812 01:22:37.761568    4106 round_trippers.go:449] Response Headers:
I0812 01:22:37.761591    4106 round_trippers.go:452]     X-Varied-Accept: application/com.github.proto-openapi.spec.v2@v1.0+protobuf
I0812 01:22:37.761631    4106 round_trippers.go:452]     Content-Type: application/octet-stream
I0812 01:22:37.761821    4106 round_trippers.go:452]     Etag: "B028B5EC8A145F9836906B77B6C9DEAA5A884C03E17C622BD0837F8194C73FB37EFAA92A0D975A93F17FB9A601607263142171639152EC3F5ACA98259639DB70"
I0812 01:22:37.761957    4106 round_trippers.go:452]     Last-Modified: Wed, 12 Aug 2020 01:21:34 GMT
I0812 01:22:37.762143    4106 round_trippers.go:452]     Vary: Accept-Encoding
I0812 01:22:37.762185    4106 round_trippers.go:452]     Vary: Accept
I0812 01:22:37.763141    4106 round_trippers.go:452]     Date: Wed, 12 Aug 2020 01:22:37 GMT
I0812 01:22:37.763307    4106 round_trippers.go:452]     Accept-Ranges: bytes
I0812 01:22:37.763331    4106 round_trippers.go:452]     Cache-Control: no-cache, private
I0812 01:22:38.229913    4106 request.go:1066] Response Body:
00000000  0a 03 32 2e 30 12 15 0a  0a 4b 75 62 65 72 6e 65  |..2.0....Kuberne|
00000010  74 65 73 12 07 76 31 2e  31 38 2e 36 42 89 c0 8b  |tes..v1.18.6B...|
00000020  01 12 f3 25 0a 19 2f 61  70 69 73 2f 61 70 70 73  |...%../apis/apps|
00000030  2f 76 31 2f 64 65 70 6c  6f 79 6d 65 6e 74 73 12  |/v1/deployments.|
00000040  d5 25 12 ce 03 0a 07 61  70 70 73 5f 76 31 1a 28  |.%.....apps_v1.(|
00000050  6c 69 73 74 20 6f 72 20  77 61 74 63 68 20 6f 62  |list or watch ob|
00000060  6a 65 63 74 73 20 6f 66  20 6b 69 6e 64 20 44 65  |jects of kind De|
00000070  70 6c 6f 79 6d 65 6e 74  2a 24 6c 69 73 74 41 70  |ployment*$listAp|
00000080  70 73 56 31 44 65 70 6c  6f 79 6d 65 6e 74 46 6f  |psV1DeploymentFo|
00000090  72 41 6c 6c 4e 61 6d 65  73 70 61 63 65 73 32 10  |rAllNamespaces2.|
000000a0  61 70 70 6c 69 63 61 74  69 6f 6e 2f 6a 73 6f 6e  |application/json|
000000b0  32 10 61 70 70 6c 69 63  61 74 69 6f 6e 2f 79 61  |2.application/ya|
000000c0  6d 6c 32 23 61 70 70 6c  69 63 61 74 69 6f 6e 2f  |ml2#application [truncated 14602907 chars]
I0812 01:24:10.373998    4106 helpers.go:234] Connection error: Get https://docs.projectcalico.org/manifests/tigera-operator.yaml: dial tcp 54.206.19.82:443: i/o timeout
F0812 01:24:10.374105    4106 helpers.go:115] Unable to connect to the server: dial tcp 54.206.19.82:443: i/o timeout

## Possible Solution
It seems kubernetes is running - looking at funny IP when trying to install tigera etc 54.206.19.82

I am behind corporate proxy - but have setup proxy config and trust for SSL rewrite certificates and that works with kubernetes install and others so that should not be the issue.

## Steps to Reproduce (for bugs)

Followed steps here https://kosyfrances.github.io/kubernetes-cluster/

Until applying calico when followed steps here https://docs.projectcalico.org/getting-started/kubernetes/quickstart

## Context
Just trying to get a basic Kubernetes multinode setup on a windows server using virtualbox one master and a number of workers

It did actually work prior to 5/6th August on same windows host different ubuntu guest- just trying to replicate it and now it fails

## Your Environment
* Calico version latest via quickstart https://docs.projectcalico.org/getting-started/kubernetes/quickstart
* Orchestrator version kubernetes v1.18.6
* Operating System and version: Ubuntu 18.04 in Virtualbox 6.1 on Windows 2008 R2
using networkd not network manager

**Comment by caseydavenport** [comment]
I'm able to access that yaml correctly in my setup. I wonder if you have some firewall rules or other local networking issue accessing docs.projectcalico.org from that machine? 

You can try downloading the manifest from another machine and copying it over?

Alternatively, it might have been a transient site error.
