### ISSUE TITLE
Modified Calico CIDR not within configured pod network

### ISSUE THREAD

**Issue by emmerg** [projectcalico/calico#3878]
I'm trying to get Calico stood up and running in a restricted network, specifically with the cluster-cidr having been set to 192.168.1.96/27. Modifying the custom-resources.yaml to have 192.168.1.96/29, and a block size of 30, is causing the tigera-operator pod to hit an error loop with the following error message

> Could not resolve CalicoNetwork IPPool and kubeadm configuration: IPPool 192.168.1.96/29 is not within the platform's configured pod network CIDR(s)

## Expected Behavior
After modifying the custom-resources.yaml such that spec.calicoNetwork.ipPools[0].cidr is e.g. 192.168.1.96/29, the various calico nodes stand up, etc.

## Current Behavior
After modifying the custom-resources yaml such that the spec.calicoNetwork.ipPools[0].cidr is e.g. 192.168.1.96/29, the calico nodes never stand up, and the tigera-operator gives an error indicating an irresoluton between CalicoNetwork IPPool and kubeadm configuration

## Steps to Reproduce (for bugs)

0. Follow the kubeadm installation as indicated in [documentation](https://docs.projectcalico.org/getting-started/kubernetes/quickstart) 

1. Rather than `sudo kubeadm init --pod-network-cidr=192.168.0.0/16`, you need to step through the kubeadm init phases, modifying the `/etc/kubernetes/manifests/kube-controller-manager.yaml` file to have the appropriate value on the `--node-cidr-mask-size` line (by default it will be 24 for an IPv4). Per kubernetes documentation, this will look like 

    ```
    kubeadm init phase preflight
    kubeadm init phase kubelet-start
    kubeadm init phase certs all
    kubeadm init phase kubeconfig all
    kubeadm init phase control-plane all
    kubeadm init phase control-plane controller-manager --pod-network-cidr 192.168.1.96/27 # overwrites the controller manager manifest created in the previous command
    vi /etc/kubernetes/manifests/kube-controller-manager.yaml # or whatever
    kubeadm init phase etcd local
    kubeadm init phase upload-config all
    kubeadm init phase upload-certs
    kubeadm init phase mark-control-plan
    kubeadm init phase bootstrap-token
    kubeadm init phase kubelet-finalize experimental-cert-rotation
    kubeadm init phase addon coredns
    kubeadm init phase addon kube-proxy --pod-network-cidr 192.168.1.96/27
    ```
    
    The only modification made to kube-controller-manager is on the line that starts `--node-cidr-mask-size`, which is set from 24 (default) to 28 (mask slightly more restrictive than the pod-network-cidr)

2. `mkdir -p $HOME/.kube && sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config && sudo chown $(id -u):$(id -g) $HOME/.kube/config`

3. `kubectl create -f https://docs.projectcalico.org/manifests/tigera-operator.yaml`

4. Modifying the custom-resource file and installing it

    ```
    wget https://docs.projectcalico.org/manifests/custom-resources.yaml`
    vi ./custom-resources.yaml # or whatever`
    kubectl create -f ./custom-resources.yaml
    ```

    The modification made to custom-resources.yaml is to set `blockSize` to 30 and `cidr` to 192.168.1.96/29, again more restrictive than the pod-network-cidr or the mask on the pod-network.

## Context
I would like to run on a network that is more restricted than /16. I am unclear if I have misconfigured Calico, if this points to some misconfiguration of Kubernetes, or if I am running into a situation where the environment is too constrained for Calico to function properly.

## Your Environment
* Calico version: 3.15 (taken from the `custom-resources` file)
* Orchestrator version: kubernetes 1.18
* Operating System and version: Ubuntu 16.04.6 LTS

* Nominal kubernetes CIDR (`kubectl get nodes -o jsonpath='{.items[*].spec.podCIDR}'`): 192.168.1.96/28

**Comment by tmjd** [comment]
Could you grab `kubectl get configmap -n kube-system kubeadm-config -o yaml` and include that?
The operator reads that ConfigMap and looks at the podSubnet entry and verifies the IPPool CIDR falls within the podSubnet.

Since you are using Calico IPAM I don't believe the change to `--node-cidr-mask-size` will do anything as Calico does not use that. I believe you should be able to do the `sudo kubeadm init --pod-network-cidr=192.168.0.0/16`

**Comment by emmerg** [comment]
Hmm, this is interesting. The output of `kubectl get configmap` on the setup I described does not have a podSubnet property: networking has dnsDomain and serviceSubnet.

I re-ran using the basic `kubeadm init` (with the pod-network-cidr changed to my mask) and that output _does_ have the podSubnet entry (`podSubnet: 192.168.1.96/27`), but the kube-controller-manager pod is in a crashloop with the error `Controller: Invalid --cluster-cidr, mask size of cluster CIDR must be less than or equal to --node-cidr-mask-size configured for CIDR family` . The crashloop behavior is why I went with the phased initialization, but it would appear that there's more differences between the two initializations than just the --node-cidr-mask-size. Did I misunderstand you, and you are saying that initializing the pod network with 192.168.0.0/16 is appropriate irrespective of what my desired CIDR is?

Configmap output for the setup described in the initial ticket (with IP entries obfuscated) follows:

```
apiVersion: v1
data:
  ClusterConfiguration: |
    apiServer:
      timeoutForControlPlane: 4m0s
    apiVersion: kubeadm.k8s.io/v1beta2
    certificatesDir: /etc/kubernetes/pki
    clusterName: kubernetes
    controllerManager: {}
    dns:
      type: CoreDNS
    etcd:
      local:
        dataDir: /var/lib/etcd
    imageRepository: k8s.gcr.io
    kind: ClusterConfiguration
    kubernetesVersion: v1.18.7
    networking:
      dnsDomain: cluster.local
      serviceSubnet: 10.96.0.0/12
    scheduler: {}
  ClusterStatus: |
    apiEndpoints:
      ip-aaa-bbb-ccc-ddd:
        advertiseAddress: aaa.bbb.ccc.ddd
        bindPort: 6443
    apiVersion: kubeadm.k8s.io/v1beta2
    kind: ClusterStatus
kind: ConfigMap
metadata:
  creationTimestamp: "2020-08-13T13:19:50Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:ClusterConfiguration: {}
        f:ClusterStatus: {}
    manager: kubeadm
    operation: Update
    time: "2020-08-13T13:19:50Z"
  name: kubeadm-config
  namespace: kube-system
  resourceVersion: "250"
  selfLink: /api/v1/namespaces/kube-system/configmaps/kubeadm-config
```

**Comment by caseydavenport** [comment]
The values passed to `--pod-network-cidr` is intended to be the CIDR for the entire cluster, which will be handed out to nodes in chunks based on the size provided to the controller manager.

In this case, the Calico operator is attempting to assert that the provided IP pool is within the `--pod-network-cidr` allocated to the _cluster_, because if it is not then quirky network behavior can arise. However, it's seeing that there is no `--pod-network-cidr` set (which can also arise in somewhat quirky behavior).

It's also worth noting that if you're using Calico networking / Calico IPAM, the CIDRs handed out by the controller manager to nodes are not relevant - Calico ignores them entirely, so you might not need to be setting that field in a phased rollout at all. The thing that Calico _does_ care about, though, it the full CIDR that has been assigned to the entire cluster.

**Comment by emmerg** [comment]
Sorry to have left this ticket unengaged. Indeed, if I run the kubeadm init without a modified CIDR, and just provide the CIDR to Calico, things work. I'm having a little trouble understanding the way that the various CIDRs interact with each other, but I think it's clear now that this is a hole in my understanding, not a hole in functionality. Thanks for the guidance - I'll close this out.
