### ISSUE TITLE
How to create BGP in master node (192.168.50.14) and worker node (192.168.51.200) using calico

### ISSUE THREAD

**Issue by sdnath05** [projectcalico/calico#3884]
Hi I'm trying to run calico on my cluster. Currently I'm having two nodes -
1. master (192.168.50.14)
2. worker (192.168.51.200)

## Current Behavior
What I'm having in error - 

From master - Readiness probe failed: 2020-08-14 07:59:53.966 [INFO][163] confd/health.go 180: Number of node(s) with BGP peering established = 0 calico/node is not ready: BIRD is not ready: BGP not established with 192.168.51.200

From worker-
Readiness probe failed: 2020-08-14 07:56:19.092 [INFO][140] confd/health.go 180: Number of node(s) with BGP peering established = 0 calico/node is not ready: BIRD is not ready: BGP not established with 192.168.50.14

Working fine if -
If my nodes are in 192.168.Y.X/24 then they can create the BGP connection.

## Steps to Reproduce
Not working if -
If my nodes are 192.168.51.200, 192.168.50.14 ...

## Context
But in real scenario I have different IPs in production VMs.
How can I achieve BGP connection with calico with all of the VMs with different IPs. Example - [10.20.1.10, 10.53.14.1, 10.178.14.62].

## My Environment

* Calico version : v3.15.1
* Orchestrator version : Kubernetes-v1.18.6
* Operating System and version: Ubuntu-18.04

**Comment by caseydavenport** [comment]
Sounds like your network might be dropping the BGP traffic that Calico needs. Double check that your network meets these requirements: https://docs.projectcalico.org/getting-started/kubernetes/requirements#network-requirements

**Comment by sdnath05** [comment]
Hi @caseydavenport looks like that is only working only /24 cidr blocks.
But I need /8 and /16 also. Is there anything that I need to configure in calico?

**Comment by caseydavenport** [comment]
I'm not sure what you mean - the size of the network that your hosts are in doesn't matter to Calico.

**Comment by lyyao09** [comment]
> But I need /8 and /16 also. Is there anything that I need to configure in calico?

From your description, I guess you are deploying calico across subnets. So you should choose the appropriate network mode according to the actual scenario, refer to the document: https://docs.projectcalico.org/networking/determine-best-networking

**Comment by lmm** [comment]
Going to close this for now, please open another issue if you're continuing to have issues, thanks!
