### ISSUE TITLE
Why pod Communication is normal when container's veth interface MTU set 1500 and tun interface MTU set default value 1440？

### ISSUE THREAD

**Issue by lklkxcxc** [projectcalico/calico#3895]
## Expected Behavior

Container's veth interface MTU must less than or equal to tun interface MTU when use IPIP mode.

## Current Behavior

Container's veth interface MTU is greater than tun interface MTU ,but pod Communication is normal in the same subnet
## Steps to Reproduce (for bugs)

1.cali34d45bc515f@if4: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP mode DEFAULT
2.tunl0@NONE: <NOARP> mtu 1440 qdisc noop state DOWN group default qlen 1
3.
4.

## Your Environment

* Calico version v3.7.3
* Orchestrator version (e.g. kubernetes, mesos, rkt):kubernetes
* Operating System and version: CentOS 7.6
* Link to your project (optional):

**Comment by caseydavenport** [comment]
@lklkxcxc you should make sure you configure the veth MTU to be the same or less than the primary interface.

Discussed here: https://docs.projectcalico.org/networking/mtu

It might still work if the packets being sent by your pods are small enough.
