### ISSUE TITLE
iptables dropping packets towards $different-node:nodePort

### ISSUE THREAD

**Issue by manuelbuil** [projectcalico/calico#3900]
I have a service called multitool that I am offering through a ingress-nginx-controller. The ingress-nginx-controller service is active:

`ingress-nginx   ingress-nginx-controller             LoadBalancer   10.43.250.13    xxxx.eu-west-1.elb.amazonaws.com   80:31748/TCP,443:31416/TCP   134m`

If I try to access the service through the clusterIP of the ingress controller, it works:
```
user@master0:~> curl -sI http://10.43.250.13/multitool | grep 200
HTTP/1.1 200 OK
```
According to K8s docs, I should also be able to access the ingress service when using the IP of any node in the cluster and the nodePort, which in this case is 31748. Unfortunately, this only works in the node where the ingress pod is running and in the node where I am executing curl. In other words, if I am in master0 and the ingress pod is in worker0:
```
user@master0:~> curl -sI $master0:31748/multitool | grep 200
HTTP/1.1 200 OK
user@master0:~> curl -sI $master1:31748/multitool | grep 200
^C
user@master0:~> curl -sI $master2:31748/multitool | grep 200
^C
user@master0:~> curl -sI $worker0:31748/multitool | grep 200
HTTP/1.1 200 OK
user@master0:~> curl -sI $worker1:31748/multitool | grep 200
^C
```
If I change to master-1:
```
user@master1:~> curl -sI $master0:31748/multitool | grep 200
^C
user@master1:~> curl -sI $master1:31748/multitool | grep 200
HTTP/1.1 200 OK
user@master1:~> curl -sI $master2:31748/multitool | grep 200
^C
user@master1:~> curl -sI $worker0:31748/multitool | grep 200
HTTP/1.1 200 OK
user@master1:~> curl -sI $worker1:31748/multitool | grep 200
^C
```

By checking the iptables in master1, I can see that all packets reach this table under KUBE-NODEPORTS:
`7   420 KUBE-XLB-CG5I4G2RS3ZVWGLK  tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            /* ingress-nginx/ingress-nginx-controller:http */ tcp dpt:31748`

But then, in KUBE-XLB-CG5I4G2RS3ZVWGLK, local packets use this table:
`3   180 KUBE-SVC-CG5I4G2RS3ZVWGLK  all  --  *      *       0.0.0.0/0            0.0.0.0/0            /* route LOCAL traffic for ingress-nginx/ingress-nginx-controller:http LB IP to service chain */ ADDRTYPE match src-type LOCAL`

whereas external packets, as they don't match `src-type LOCAL`, are dropped by this table:
`4   240 KUBE-MARK-DROP  all  --  *      *       0.0.0.0/0            0.0.0.0/0            /* ingress-nginx/ingress-nginx-controller:http has no local endpoints */`

Is this behavior expected?

## Expected Behavior

I expect the ingress service to be accessible by the port 31748 in all nodes of my cluster, not just my local node and the node where the pod is running

## Your Environment

I am using canal with image versions:
    * calico:v3.13.3
    * flannel:v0.11.0
kubernetes v1.18.4

**Comment by caseydavenport** [comment]
I think this is really a Kubernetes issue, since Calico isn't involved in the programming of any of those rules (services are implemented by kube-proxy most of the time).

It sounds like maybe your service has `externalTrafficPolicy: Local` set? If so, you probably want that changed to `Cluster` so that all nodes can perform the load balancing.
