### ISSUE TITLE
Use a CIDR for IP autodetection

### ISSUE THREAD

**Issue by bsctl** [projectcalico/calico#3902]
Feature request: use a network CIDR for IP autodetection to set the node network in Calico. 

## Expected Behavior
Can use the following:

```
IP: "autodetect"
IP_AUTODETECTION_METHOD: "cidr=10.9.5.0/24"
```

## Current Behavior
Current options are: `can-reach`, `interface`, and `skip-interface`.

## Possible Solution
This actually works:

```
IP: "autodetect"
IP_AUTODETECTION_METHOD: "can-reach=10.9.5.0"
```

## Steps to Reproduce (for bugs)
n/a

## Context
We use Calico in a self-service environment where people join their worker nodes to the cluster. They are free to use the workers nodes' NIC they want to join the Calico network, so the option `interface=eth0` or any regex variation `interface=eth0|ens256` is not suitable.

Also the option `can-reach=10.9.5.1` where  `10.9.5.1` is an existing address to reach is not suitable because we do not control which IPs are on that network.

We found that the option `can-reach=10.9.5.0` just works because looks like the code doesn't actually connect to the destination; it just does a routing lookup so it shouldn't matter if the IP actually had a host or router behind it.

It would be nice to document this or, better, introduce the option `cidr=10.9.5.0/24`

## Your Environment
Calico as CNI for kubernetes

**Comment by bsctl** [comment]
@fasaxc thanks for your support on Slack.

**Comment by tmjd** [comment]
I believe we already have this feature being added in Calico v3.16, I believe it is expected out very soon.
See https://github.com/projectcalico/node/pull/518 for the details.
