### ISSUE TITLE
Pod-to-Pod communication scheduled on different worker nodes not working.

### ISSUE THREAD

**Issue by Anil-YadavK8s** [projectcalico/calico#3908]
## Expected Behavior

Pod to Pod communication should work irrespective of where they are scheduled. We don't have any network policy enabled.

## Current Behavior

Scenario: Pod to Pod communication should work irrespective of where they are scheduled. 

Pod A on worker-1 is not able to communicate with POD B on worker-2

## Steps to Reproduce (for bugs)

1.  Calico version v3.12.0 (Routing mode : IPIP -default)
2.  In TCP-Dump: We can see checksum error on source (worker -1) and on packet at destination host (worker 2)

kubeadmin@master-1:~> sudo tcpdump -i eth0 -n '(host 10.217.68.21 and                                                                                                 host 10.217.68.13)' and proto 4 -vvvv
tcpdump: listening on eth0, link-type EN10MB (Ethernet), capture size 262144 bytes
12:41:41.390694 IP (tos 0x0, ttl 64, id 9952, offset 0, flags [DF], proto IPIP (4), lengt                                                                                                h 80)
    10.217.68.21 > 10.217.68.13: IP (tos 0x0, ttl 64, id 59019, offset 0, flags [DF], pro                                                                                                to TCP (6), length 60)
    192.168.255.128.55386 > 192.168.170.223.80: Flags [S], **cksum 0x2be0 (incorrect** -> 0x8                                                                                                119), seq 3778634233, win 28000, options [mss 1400,sackOK,TS val 2807524059 ecr 0,nop,wsc                                                                                                ale 7], length 0
12:41:42.420036 IP (tos 0x0, ttl 64, id 10160, offset 0, flags [DF], proto IPIP (4), leng                                                                                                th 80)
    10.217.68.21 > 10.217.68.13: IP (tos 0x0, ttl 64, id 59020, offset 0, flags [DF], pro                                                                                                to TCP (6), length 60)
    192.168.255.128.55386 > 192.168.170.223.80: Flags [S], cksum 0x2be0 (incorrect -> 0x7                                                                                                d14), seq 3778634233, win 28000, options [mss 1400,sackOK,TS val 2807525088 ecr 0,nop,wsc                                                                                                ale 7], length 0
12:41:44.436032 IP (tos 0x0, ttl 64, id 10542, offset 0, flags [DF], proto IPIP (4), leng                                                                                                th 80)

3. No error in Calico pod logs
4. Kernel version:  4.12.14-197.51-default

## Context
issue got resolved after disabling the TCP segmentation TSO on the worker node:

sudo ethtool -K eth0 tx off sg off tso off
--

 

## Your Environment

* Calico version v3.12.0 (Routing mode : IPIP -default)
* Orchestrator version (e.g. kubernetes, mesos, rkt): v1.17.3
* Operating System and version:  SUSE Linux Enterprise Server 15 SP1
* Link to your project (optional):

Would like to know is any dependency of calico with TCP segementation ?

**Comment by fasaxc** [comment]
That sounds like a kernel bug; we don't interact with TSO directly.  Suse isn't one of the platforms we routinely test on; we haven't hit anything like that on Ubuntu or RHEL.

**Comment by Anil-YadavK8s** [comment]
@fasaxc  Yes seems so. Issue resolved when we downgraded the kernel version from 4.12.14-197.51-default to 4.12.14-195-default.

**Comment by fasaxc** [comment]
Please report the issue to SUSE and drop a link to the upstream issue here.
