### ISSUE TITLE
felix config not set if delay between nodes > 0.25s (RTD 0.5s)

### ISSUE THREAD

**Issue by DaveLangridge** [projectcalico/calico#395]
RTD > 0.5s between controller and compute node.

Nova-compute sets up the VM, but the routes and iptables aren't configured.

felix logs:
2015-04-16 12:41:35,126 [ERROR][3] calico.felix.fetcd 97: Failed to retrieve ready flag from etcd, waiting...
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/calico/felix/fetcd.py", line 92, in wait_for_ready
    timeout=10).value
  File "/usr/lib/python2.7/dist-packages/etcd/client.py", line 344, in read
    self.key_endpoint + key, self._MGET, params=params, timeout=timeout)
  File "/usr/lib/python2.7/dist-packages/etcd/client.py", line 582, in api_execute
    return self._handle_server_response(response)
  File "/usr/lib/python2.7/dist-packages/etcd/client.py", line 598, in _handle_server_response
    etcd.EtcdError.handle(**r)
  File "/usr/lib/python2.7/dist-packages/etcd/__init__.py", line 142, in handle
    raise exc(msg)
EtcdException: Unable to decode server response

and if I query etcd from the command line on the compute node:
ubuntu@calico-vm22:/var/log/calico$ etcdctl ls
Error:  501: All the given peers are not reachable (Tried to connect to each peer twice and failed) [0]

**Comment by Lukasa** [comment]
This problem appears to be in the underlying etcd communication layer. I *suspect* (but do not know) that raft does not like having 500ms latency between communicating nodes.

**Comment by fasaxc** [comment]
Not sure how to triage this, I think we need to be progressing it in the background but I don't think we need to fix it for 0.16 or 0.17.  @Lukasa, any opinion?

**Comment by Lukasa** [comment]
Agreed, I think it's non-urgent.

**Comment by Lukasa** [comment]
I'm extremely confident that this is to do with the leader election timeout, which by default is 1s: exactly twice the latency that causes this problem.

**Comment by bossmc** [comment]
Proxies aren't involved in leadership elections, only true cluster members are, so I don't think that's related.

On the other hand, the code in https://github.com/coreos/etcd/blob/master/Godeps/_workspace/src/github.com/coreos/go-etcd/etcd/requests.go#L157-167 only allows a request to be outstanding for 100ms before cancelling it and it only allows two retries.  I'm not sure if the response from the first request arriving after the second request would be treated as a response to the second request, which would explain how I was able to read/write keys at 100ms latency.  Failing to reach both peers returns an `ErrCodeEtcdNotReachable` which leads to the error message @DaveLangridge reported.

**Comment by bossmc** [comment]
My findings from testing etcd at various latencies:

##### Default Settings

Time between heartbeat messages (equal to “time to wait for votes during election”) = 100ms
Time before starting election = 1000ms

##### Test Architecture

Three etcd nodes, with netem adding latency to the inter-node flows (i.e. all network hops are delayed by the given latency + real latency).  I tested leadership elections by killing the current leader and seeing if a new leader could be elected successfully.

##### Results
 
* 10ms – No issues seen, cluster-health reported healthy, leadership elections were successful
* 20ms – No issues seen, cluster-health reported healthy, leadership elections were successful
* 100ms – No issues seen, cluster-health reported healthy, leadership elections were successful
* 150ms – Elections succeeded, cluster-health reported unhealthy, no explanation why…?  Cluster health didn’t recover when I lowered the latency, I had to force another election to recover the cluster.
* 200ms – Spammy logs, cluster-health reported unhealthy, leadership elections never completed

**Comment by fasaxc** [comment]
We recommend deploying your etcd cluster in a single datacenter, where latency should not be an issue.  In addition, we think etcd have made the timeouts longer/configurable, resolving this issue.
