### ISSUE TITLE
Simple Policy demo needs DNS, but doesn't list it as a pre-req

### ISSUE THREAD

**Issue by lwr20** [projectcalico/calico#395]
http://docs.projectcalico.org/v2.0/getting-started/kubernetes/tutorials/simple-policy

**Comment by caseydavenport** [comment]
We don't generally consider DNS a pre-req in the same way we don't consider running the kubernetes apiserver a pre-req.  It's a core kubernetes component.

**Comment by djosborne** [comment]
>It requires a Kubernetes cluster ...

Is it assumed that DNS is installed in that cluster? Probably worth us nudging folks with that requirement anyways

**Comment by caseydavenport** [comment]
> Is it assumed that DNS is installed in that cluster? Probably worth us nudging folks with that "requirement" anyways

Yeah, as of like v1.3.0 or something DNS is considered a required component.  We can nudge, but it's a little bit silly.

"You must have a working Kubernetes cluster that, by the way, needs to have kubelet running on all of the nodes"

**Comment by lwr20** [comment]
Fair enough.  Closing.
