### ISSUE TITLE
CRD for BGPPeer (from _includes/charts) enforces asNumber and peerIP

### ISSUE THREAD

**Issue by sfudeus** [projectcalico/calico#3950]
## Expected Behavior

`BGPPeer` should allow leaving out at least `peerIP` when using `peerSelector`

## Current Behavior
`BGPPeer` `asNumber` and `peerIP` is set as `required`

## Possible Solution

Do not require asNumber and peerIP

## Context

We want to use BGP RouteReflectors and set the reflectors only as bgp peers for the calico nodes. 
We use the CRD definitions from https://github.com/projectcalico/calico/tree/master/_includes/charts/calico/crds/kdd

## Your Environment

* Calico version 3.14.1/3.15.2 (in master, too)
* Orchestrator version (e.g. kubernetes, mesos, rkt): kubernetes
* Operating System and version: FlatCar 2512.2.1

**Comment by sfudeus** [comment]
It seems when using the v3-manifest with calicoctl, it will reflect in k8s with `asNumber: 0` and `peerIP: ""`. 
Is it safe to assume those will act as "not present"?

We currently do (and prefer doing so), to configure calico solely from rendered k8s manifests (currently via helm). Explicitly doing calicoctl-calls would be cumbersome of required ...

**Comment by sfudeus** [comment]
I suppose this is related to #2923

**Comment by caseydavenport** [comment]
>We currently do (and prefer doing so), to configure calico solely from rendered k8s manifests (currently via helm). Explicitly doing calicoctl-calls would be cumbersome of required ...

Yeah, this is a probably a growing pain related to adding validation to our CRDs. 

I agree that we probably shouldn't be requiring those fields. I guess calicoctl writes in "zero" values for them and gets around this.
