### ISSUE TITLE
command calicoctl get ippools does not show default ip pool information

### ISSUE THREAD

**Issue by khatrig** [projectcalico/calico#3951]
I have kuberentes cluster setup with cluster podcidr 10.233.64.0/18. Using calico to pod networking. All cluster operations seem normal. calico is allocating pod ips from the kubernetes cluster pod CIDR correctly. calicoctl (as a pod or from Linux command line) does not show default IP pool information.

## Expected Behavior
Command **_calicoctl get ippools_** should return the default IP pool currently in use
**Eg.**
NAME                              CIDR             NAT    IPIPMODE   DISABLED
default-ipv4-ippool   192.168.0.0/16    true   Always     true

## Current Behavior
**_calicoctl get ippools_** does not show

_calicoctl get ippools_
NAME   CIDR   SELECTOR

## Steps to Reproduce (for bugs)
kubectl apply -f https://docs.projectcalico.org/manifests/calicoctl.yaml
kubectl exec -ti -n kube-system calicoctl -- calicoctl get ippools

## Your Environment

* Calico version : Tried v3.11.1, v3.15.1
* Orchestrator version (e.g. kubernetes, mesos, rkt): Kubernetes 1.16.3
* Operating System and version: Ubuntu 18.04
* Link to your project (optional):

**Comment by caseydavenport** [comment]
@khatrig which manifest did you use to install Calico originally?

**Comment by khatrig** [comment]
> @khatrig which manifest did you use to install Calico originally?

This is a default installation using kubespray https://github.com/kubernetes-sigs/kubespray/tree/master/roles/network_plugin/calico/

**Comment by caseydavenport** [comment]
One quick thing to check before going deeper - could you check which datastore type your cluster is using? 

I think a command like this should do it:

```
kubectl get configmap calico-config -n kube-system | grep datastore
```

It will either be "etcd" or "kubernetes". The linked `calicoctl` manifest will only work for "kubernetes", there is separate one for "etcd".

**Comment by khatrig** [comment]
> One quick thing to check before going deeper - could you check which datastore type your cluster is using?
> 
> I think a command like this should do it:
> 
> ```
> kubectl get configmap calico-config -n kube-system | grep datastore
> ```
> 
> It will either be "etcd" or "kubernetes". The linked `calicoctl` manifest will only work for "kubernetes", there is separate one for "etcd".

Tried below commands but did not get any output

kubectl get configmap calico-config -n kube-system | grep datastore        
kubectl get configmap calico-config -n kube-system -o yaml | grep datastore

Do you mean kubernetes etcd vs external datastore? I'm using kubernetes etcd as the data store for calico.

One more point. I'm able to use calicoctl to list allocated IPs / WEP assigned from the cluster pod cidr.

**Comment by caseydavenport** [comment]
> Do you mean kubernetes etcd vs external datastore? 

Calico has two ways of storing its data - in etcd directly, or the k8s API via CRDs. There are two calicoctl manifests - one for each mode. Wanted to make sure you were using the right one.

This is pretty strange. Could you try running the calicoctl command with debug logging enabled to see if there's anything useful there?

```
calicoctl -l debug get ippool
```

Might also be worth running this to determine datastore:

```
kubectl get ippool
```

**Comment by khatrig** [comment]
@caseydavenport 

I'm using calicoctl manifest - **https://docs.projectcalico.org/manifests/calicoctl.yaml**

```
calicoctl -l debug get ippool                                                                          

INFO[0000] Log level set to debug
INFO[0000] Executing config command
DEBU[0000] Resource: projectcalico.org/v3, Kind=IPPool
DEBU[0000] Data: - apiVersion: projectcalico.org/v3
  kind: IPPool
  metadata:
    creationTimestamp: null
  spec:
    cidr: ""
INFO[0000] Config file: /etc/calico/calicoctl.cfg cannot be read - reading config from environment
DEBU[0000] Loading config from environment
INFO[0000] Loaded client config: apiconfig.CalicoAPIConfigSpec{DatastoreType:"kubernetes", EtcdConfig:apiconfig.EtcdConfig{EtcdEndpoints:"", EtcdDiscoverySrv:"", EtcdUsername:"", EtcdPassword:"", EtcdKeyFile:"", EtcdCertFile:"", EtcdCACertFile:"", EtcdKey:"", EtcdCert:"", EtcdCACert:""}, KubeConfig:apiconfig.KubeConfig{Kubeconfig:"", K8sAPIEndpoint:"", K8sKeyFile:"", K8sCertFile:"", K8sCAFile:"", K8sAPIToken:"", K8sInsecureSkipTLSVerify:false, K8sDisableNodePoll:false, K8sUsePodCIDR:false, KubeconfigInline:"", K8sClientQPS:0}}
DEBU[0000] Using datastore type 'kubernetes'
DEBU[0000] Calico is configured to use calico-ipam
INFO[0000] Client: {{{CalicoAPIConfig projectcalico.org/v3} {      0 {{0 0 <nil>}} <nil> <nil> map[] map[] [] []  []} {kubernetes {         } {      false false false  0}}} 0xc0001d5180 0xc00034eed0}
DEBU[0000] Performing 'List' for IPPool model.ResourceListOptions
DEBU[0000] List Custom K8s Resource                      ListInterface=IPPool Resource=IPPools
INFO[0000] results: {FileInvalid:false NumResources:1 NumHandled:1 Err:<nil> SingleKind:IPPool Resources:[0xc00079a3f0] ResErrs:[] Client:{config:{TypeMeta:{Kind:CalicoAPIConfig APIVersion:projectcalico.org/v3} ObjectMeta:{Name: GenerateName: Namespace: SelfLink: UID: ResourceVersion: Generation:0 CreationTimestamp:{Time:{wall:0 ext:0 loc:<nil>}} DeletionTimestamp:<nil> DeletionGracePeriodSeconds:<nil> Labels:map[] Annotations:map[] OwnerReferences:[] Finalizers:[] ClusterName: ManagedFields:[]} Spec:{DatastoreType:kubernetes EtcdConfig:{EtcdEndpoints: EtcdDiscoverySrv: EtcdUsername: EtcdPassword: EtcdKeyFile: EtcdCertFile: EtcdCACertFile: EtcdKey: EtcdCert: EtcdCACert:} KubeConfig:{Kubeconfig: K8sAPIEndpoint: K8sKeyFile: K8sCertFile: K8sCAFile: K8sAPIToken: K8sInsecureSkipTLSVerify:false K8sDisableNodePoll:false K8sUsePodCIDR:false KubeconfigInline: K8sClientQPS:0}}} backend:0xc0001d5180 resources:0xc00034eed0}}
INFO[0000] Output in table format (wide=false)
DEBU[0000] Got resource template                         template="NAME\tCIDR\tSELECTOR\t\n{{range .Items}}{{.ObjectMeta.Name}}\t{{.Spec.CIDR}}\t{{.Spec.NodeSelector}}\t\n{{end}}"
NAME   CIDR   SELECTOR
```
```
kubectl get ippool                                                                                                                          
error: the server doesn't have a resource type "ippool"
```

**Comment by caseydavenport** [comment]
```
kubectl get ippool                                                                                                                          
error: the server doesn't have a resource type "ippool"
```

This seems to indicate that either Calico is not properly installed, or calicoctl is pointing at the wrong place.

**Comment by laimison** [comment]
Hi all, I'm having same issue when there is no IP pool printed. Installation method was Kubespray, but version is higher - 1.18.8.

Obviously, I'm having issue with this, for example `StatefulSet` members cannot talk to each other.

```
era@server-master-3:~$ calicoctl -l debug get ippool
INFO[0000] Log level set to debug
INFO[0000] Executing config command
DEBU[0000] Resource: projectcalico.org/v3, Kind=IPPool
DEBU[0000] Data: - apiVersion: projectcalico.org/v3
  kind: IPPool
  metadata:
    creationTimestamp: null
  spec:
    cidr: ""
INFO[0000] Config file: /etc/calico/calicoctl.cfg cannot be read - reading config from environment
DEBU[0000] Loading config from environment
INFO[0000] Loaded client config: apiconfig.CalicoAPIConfigSpec{DatastoreType:"kubernetes", EtcdConfig:apiconfig.EtcdConfig{EtcdEndpoints:"", EtcdDiscoverySrv:"", EtcdUsername:"", EtcdPassword:"", EtcdKeyFile:"", EtcdCertFile:"", EtcdCACertFile:"", EtcdKey:"", EtcdCert:"", EtcdCACert:""}, KubeConfig:apiconfig.KubeConfig{Kubeconfig:"/home/era/.kube/config", K8sAPIEndpoint:"", K8sKeyFile:"", K8sCertFile:"", K8sCAFile:"", K8sAPIToken:"", K8sInsecureSkipTLSVerify:false, K8sDisableNodePoll:false, K8sUsePodCIDR:false, KubeconfigInline:"", K8sClientQPS:0}}
DEBU[0000] Using datastore type 'kubernetes'
DEBU[0000] Calico is configued to use calico-ipam
INFO[0000] Client: {{{CalicoAPIConfig projectcalico.org/v3} {      0 {{0 0 <nil>}} <nil> <nil> map[] map[] [] []  []} {kubernetes {         } {/home/era/.kube/config      false false false  0}}} 0xc000098040 0xc00061a4e0}
DEBU[0000] Performing 'List' for IPPool model.ResourceListOptions
DEBU[0000] List Custom K8s Resource                      ListInterface=IPPool Resource=IPPools
INFO[0000] results: {FileInvalid:false NumResources:1 NumHandled:1 Err:<nil> SingleKind:IPPool Resources:[0xc000539030] ResErrs:[] Client:{config:{TypeMeta:{Kind:CalicoAPIConfig APIVersion:projectcalico.org/v3} ObjectMeta:{Name: GenerateName: Namespace: SelfLink: UID: ResourceVersion: Generation:0 CreationTimestamp:{Time:{wall:0 ext:0 loc:<nil>}} DeletionTimestamp:<nil> DeletionGracePeriodSeconds:<nil> Labels:map[] Annotations:map[] OwnerReferences:[] Finalizers:[] ClusterName: ManagedFields:[]} Spec:{DatastoreType:kubernetes EtcdConfig:{EtcdEndpoints: EtcdDiscoverySrv: EtcdUsername: EtcdPassword: EtcdKeyFile: EtcdCertFile: EtcdCACertFile: EtcdKey: EtcdCert: EtcdCACert:} KubeConfig:{Kubeconfig:/home/era/.kube/config K8sAPIEndpoint: K8sKeyFile: K8sCertFile: K8sCAFile: K8sAPIToken: K8sInsecureSkipTLSVerify:false K8sDisableNodePoll:false K8sUsePodCIDR:false KubeconfigInline: K8sClientQPS:0}}} backend:0xc000098040 resources:0xc00061a4e0}}
INFO[0000] Output in table format (wide=false)
DEBU[0000] Got resource template                         template="NAME\tCIDR\tSELECTOR\t\n{{range .Items}}{{.ObjectMeta.Name}}\t{{.Spec.CIDR}}\t{{.Spec.NodeSelector}}\t\n{{end}}"
NAME   CIDR   SELECTOR

era@server-master-3:~$ kubectl get ippool
error: the server doesn't have a resource type "ippool"
era@server-master-3:~$ calicoctl get ippool -o wide
NAME   CIDR   NAT   IPIPMODE   VXLANMODE   DISABLED   SELECTOR

era@server-master-3:~$ k version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.8", GitCommit:"9f2892aab98fe339f3bd70e3c470144299398ace", GitTreeState:"clean", BuildDate:"2020-08-13T16:12:48Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.8", GitCommit:"9f2892aab98fe339f3bd70e3c470144299398ace", GitTreeState:"clean", BuildDate:"2020-08-13T16:04:18Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
era@server-master-3:~$
```

Any advice on what to check next? How ippool is installed?

**Comment by khatrig** [comment]
> ```
> kubectl get ippool                                                                                                                          
> error: the server doesn't have a resource type "ippool"
> ```
> 
> This seems to indicate that either Calico is not properly installed, or calicoctl is pointing at the wrong place.

I've seen calicoctl get ippools work in some of my previous installations but I've never seen kubectl get ippool work.

Is there anything else I can do to help investigate this further?

**Comment by laimison** [comment]
I have checked several working production clusters built with Kubespray 2.10 and 2.13 and they don't have `ippool` resource
So it should be okay to see `error: the server doesn't have a resource type "ippool"`.

**Comment by laimison** [comment]
@khatrig you can use this command to list pool:

```
# sudo calicoctl.sh get ippool
NAME           CIDR             SELECTOR
default-pool   10.233.64.0/18   all()
```

`calicoctl.sh` is just a wrapper which has only variables, but they are set correctly to use `calicoctl` properly. Can you see the output?

In my setup servers are in different subnets under different gateways, but they can communicate to each other in normal network. Could it be an issue? Do I need to use `calico_ipip_mode=CrossSubnet` or `calico_vxlan_mode=Always`? Are they for other purposes?

```
root@server-master-1:~# sudo calicoctl.sh get nodes -o wide
NAME                       ASN       IPV4                 IPV6
server-master-1.internal   (64512)   192.168.250.111/32
server-master-2.internal   (64512)   192.168.240.111/32
server-master-3.internal   (64512)   192.168.230.111/32
server-node-1.internal     (64512)   192.168.250.112/32
server-node-2.internal     (64512)   192.168.240.112/32
server-node-3.internal     (64512)   192.168.230.112/32

root@server-master-1:~#
```

**Comment by laimison** [comment]
my issue is solved here https://github.com/projectcalico/calico/issues/4160

**Comment by caseydavenport** [comment]
> In my setup servers are in different subnets under different gateways, but they can communicate to each other in normal network. Could it be an issue? Do I need to use calico_ipip_mode=CrossSubnet or calico_vxlan_mode=Always?

It should be OK to have your nodes in different subnets, so long as the router / firewall between those subnets allows the necessary Calico traffic (namely, the BGP port TCP 179). 

You will need one type of encap enabled - either IPIP or VXLAN (in either CrossSubnet or Always) in order for pod traffic to work across subnet boundaries.

**Comment by caseydavenport** [comment]
> All cluster operations seem normal. calico is allocating pod ips from the kubernetes cluster pod CIDR correctly. calicoctl (as a pod or from Linux command line) does not show default IP pool information.

If Calico is allocating IP addresses, then an IP pools _must_ actually exist. Since the CNI plugin needs one in order to allocate addresses.

So, this sounds like a calicoctl issue. Either calicoctl is pointing at the wrong etcd, or maybe there is a bug in calicoctl somehow (although I'd be surprised at that)

> I've seen calicoctl get ippools work in some of my previous installations but I've never seen kubectl get ippool work.

Yes, this makes sense for clusters using etcd directly. `kubectl get ippools` will only work if using Calico w/ the Kubernetes API data store via CRDs.
