### ISSUE TITLE
Adding a node to a kubernetes cluster gives failed to load Kubelet config file /var/lib/kubelet/config.yaml and no networks found in /etc/cni/net.d

### ISSUE THREAD

**Issue by dwschulze** [projectcalico/calico#3952]
I have a two node k8s cluster working. I added another node to the cluster and the `sudo kubeadm join ...` command reported that the node had joined the cluster. The new node is stuck in the NotReady state:

```
kubectl get nodes
NAME               STATUS     ROLES    AGE    VERSION
msi-ubuntu18       NotReady   <none>   29m    v1.19.0
tv                 Ready      master   131d   v1.18.6
ubuntu-18-extssd   Ready      <none>   131d   v1.17.4
```
The `journalctl -u kubelet `shows this error:

```
Started kubelet: The Kubernetes Node Agent.
  22039 server.go:198] failed to load Kubelet config file /var/lib/kubelet/config.yaml, error failed to read kubelet config file "/var/l...
```

But the file `/var/lib/kubelet/config.yaml `exists and looks OK.

The `sudo systemctl status kubelet `shows a different error on the new node:

```
kubelet.go:2103] Container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plu
cni.go:239] Unable to update cni config: no networks found in /etc/cni/net.d
```

And there is no /etc/cni/ directory on the new node. (The existing node has /etc/cni/net.d/ with calico files in it.) If I run

`kubectl apply -f https://docs.projectcalico.org/v3.11/manifests/calico.yaml`

on the master again it doesn't solve the problem. There is still no /etc/cni/ dir on the new node.

At what point does the `/etc/cni/ `directory get created on the new node? It's also puzzling that the `kubeadm join ...` command indicates success when the new node is stuck in NotReady.

**Comment by tmjd** [comment]
What does `kubectl get pods -n kube-system -o wide` show, is there a calico-node pod starting on the new node? What is it's status? The daemonset of calico-node should cause a calico-node pod on the new node and an init container should install a file in /etc/cni/net.d that would cause the node to go Ready.

**Comment by dwschulze** [comment]
```
NAME                                       READY   STATUS    RESTARTS   AGE   IP               NODE               NOMINATED NODE   READINESS GATES
calico-kube-controllers-59877c7fb4-hbkhs   1/1     Running   0          14h   192.168.88.129   tv                 <none>           <none>
calico-node-27k9m                          1/1     Running   0          14h   192.168.0.8      tv                 <none>           <none>
calico-node-5vj8r                          1/1     Running   0          14h   192.168.0.12     ubuntu-18-extssd   <none>           <none>
coredns-66bff467f8-bfmgm                   1/1     Running   0          14h   192.168.88.130   tv                 <none>           <none>
coredns-66bff467f8-td29p                   1/1     Running   0          14h   192.168.88.131   tv                 <none>           <none>
etcd-tv                                    1/1     Running   0          14h   192.168.0.8      tv                 <none>           <none>
kube-apiserver-tv                          1/1     Running   0          14h   192.168.0.8      tv                 <none>           <none>
kube-controller-manager-tv                 1/1     Running   0          14h   192.168.0.8      tv                 <none>           <none>
kube-proxy-4rs5x                           1/1     Running   0          14h   192.168.0.14     msi-ubuntu18       <none>           <none>
kube-proxy-8q98b                           1/1     Running   0          14h   192.168.0.12     ubuntu-18-extssd   <none>           <none>
kube-proxy-cbkgz                           1/1     Running   0          14h   192.168.0.8      tv                 <none>           <none>
kube-scheduler-tv                          1/1     Running   0          14h   192.168.0.8      tv                 <none>           <none>

```

There is no calico node running on the failed node `msi-ubuntu18`.  My master and the nodes are all different versions of kubernetes.  Could that be the problem?

**Comment by tmjd** [comment]
The issue might be that the os label has changed (or they dropped support for the beta label) in K8s v1.19. The manifest version you're using has `beta.kubernetes.io/os: linux` but I believe that has been deprecated in favor of `kubernetes.io/os=linux`.

You should do a `kubectl describe node msi-ubuntu18` and see what labels it has. If it doesn't have that `beta` label, then that is the reason it isn't getting calico-node deployed. Assuming you'll only have linux nodes you can do a `kubectl edit daemonset -n kube-system calico-node` and remove the nodeSelector. Or you could also add the label to your new node by doing a `kubectl edit node msi-ubuntu18`.

If the above isn't the issue then look again at the describe node and see if there is anything there suggesting why calico-node isn't be deployed. Maybe check events if there are any. Check the taints, though I think the tolerations on calico-node should allow it to run anywhere.

**Comment by dwschulze** [comment]
I was finally able to solve this by doing 

`kubectl delete -f https://docs.projectcalico.org/v3.11/manifests/calico.yaml`

followed by

`kubectl apply -f https://docs.projectcalico.org/manifests/calico.yaml`

There must have been some version incompatibility between version 3.11, which I had installed a few months ago and the new node.

**Comment by tmjd** [comment]
I'm glad you were able to solve your issue.

FYI for updates in the future, I wouldn't have suggested doing the delete 1st because that would remove the CRDs and you could have lost some config/data for Calico. One specific example of what could be lost would be Calico Network Policies (policies created using calicoctl, Kubernetes NetworkPolicies should still be present). 
I think it should have worked to just apply the new manifest.

You might want to restart your pods that were running before you did the delete as their IP Addresses may get handed out to new pods so there might be multiple pods with the same IP address which would be problematic. This would be due to the IPPools and pool data being lost when the CRDs were deleted.
