### ISSUE TITLE
Migration from flannel: "Can't separate key from value"

### ISSUE THREAD

**Issue by mephinet** [projectcalico/calico#3956]
Following the steps in https://docs.projectcalico.org/getting-started/kubernetes/flannel/migration-from-flannel, I tried to migrate my flannel 0.11 installation to Calico.

## Expected Behavior

Successful migration to Calico.

## Current Behavior

The flannel-migration Pod fails right away after a few seconds (status: Error).
The log output says:

> 2020-08-30 20:44:51.947 [INFO][1] main.go 88: Loaded configuration from environment config=&config.Config{LogLevel:"info", WorkloadEndpointWorkers:1, ProfileWo
> rkers:1, PolicyWorkers:1, NodeWorkers:1, Kubeconfig:"", DatastoreType:"kubernetes"}                                                                            
> W0830 20:44:51.949680       1 client_config.go:543] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.         
> 2020-08-30 20:44:51.951 [INFO][1] main.go 109: Ensuring Calico datastore is initialized                                                                        
> 2020-08-30 20:44:51.963 [INFO][1] main.go 135: Loaded Flannel configuration from environment flannelConfig=&flannelmigration.Config{FlannelNetwork:"", FlannelD
> aemonsetName:"kube-flannel-ds-amd64", FlannelMTU:0, FlannelIPMasq:true, FlannelSubnetLen:24, FlannelAnnotationPrefix:"flannel.alpha.coreos.com", FlannelVNI:1, 
> FlannelPort:8472, CalicoDaemonsetName:"calico-node", CniConfigDir:"/etc/cni/net.d", PodNodeName:"node-2", FlannelSubnetEnv:"", DebugWaitBeforeExit:0, DebugWait
> BeforeStart:0}                                                                                                                                                 
> 2020-08-30 20:44:51.963 [INFO][1] main.go 169: Starting status report routine                                                                                  
> 2020-08-30 20:44:51.963 [INFO][1] main.go 402: Starting controller ControllerType="FlannelMigration"                                                           
> 2020-08-30 20:44:51.963 [INFO][1] migration_controller.go 154: Starting Migration controller                                                                   
> 2020-08-30 20:44:51.996 [INFO][1] migration_controller.go 258: Trying to read Flannel env config by executing into daemonet pod.                               
> 2020-08-30 20:44:52.498 [INFO][1] k8s_resources.go 500: Kubectl exec kube-flannel-ds-amd64-ml4q8(kube-flannel) completed successfully.                         
>  ---[exec kube-flannel-ds-amd64-ml4q8 --namespace=kube-system -c=kube-flannel cat run/flannel/subnet.env]---                                                   
> kubectl exec [POD] [COMMAND] is DEPRECATED and will be removed in a future version. Use kubectl kubectl exec [POD] -- [COMMAND] instead.                 
> FLANNEL_NETWORK=10.244.0.0/16                                                                                                                                  
> FLANNEL_SUBNET=10.244.2.1/24                                                                                                                                   
> FLANNEL_MTU=1400                                                                                                                                               
> FLANNEL_IPMASQ=true
> 
>  ------
> 2020-08-30 20:44:52.498 [ERROR][1] migration_controller.go 159: Error checking status, Stopping Migration controller. error=Can't separate key from value
> 2020-08-30 20:44:52.498 [FATAL][1] migration_controller.go 138: Migration controller stopped.
> 

## Steps to Reproduce (for bugs)
Set up a 3-node Kubernetes v1.18.5 cluster with flannel 0.11 from https://github.com/coreos/flannel/blob/v0.11.0/Documentation/kube-flannel.yml

## Your Environment

* Calico version: 3.16
* Orchestrator version: Kubernetes 1.18.5
* Operating System and version: Ubuntu 18.04.4 LTS
* Link to your project (optional):

**Comment by mephinet** [comment]
Same issue after updating to flannel 0.12 and then starting the migration. /run/flannel/subnet.env looks exactly as shown in the log, without a final empty line.

**Comment by song-jiang** [comment]
Thanks @mephinet for reporting this issue. I believe it is caused by latest `kubectl` sent out warning message ```kubectl exec [POD] [COMMAND] is DEPRECATED and will be removed in a future version. Use kubectl kubectl exec [POD] -- [COMMAND] instead.``` and confused migration controller.

**Comment by mephinet** [comment]
That's great - in this case it should be easy to fix it, as kubectl exec allowed for the -- syntax for quite a while now...
