### ISSUE TITLE
Clarification around pod/service cidrs and ippool cidrs

### ISSUE THREAD

**Issue by emmetog** [projectcalico/calico#3979]
First off, thanks for a great tool.

I'm spinning up a k8s cluster where all the VM nodes are in 10.0.0.0/8 and am trying to figure out suitable values for the following:
* The `--pod-network-cidr` flag on `kubeadm init`
* The `--service-cidr` flag on `kubeadm init`
* The `cidr` parameter of the ippool definition

In particular, what can/should overlap and what cannot?

The problem I'm running into is that when I follow the instructions in [Calico the hard way](https://docs.projectcalico.org/getting-started/kubernetes/hardway/) to the letter (except for the number and size of nodes, which I don't think affect this issue) and specify the `--pod-network-cidr` on kubeadm to be 192.168.0.0/16 and set the cidr of pool1 to be 192.168.0.0/18 (as suggested in the tutorial) then the cluster looks fine and all networking works, except traffic to the DNS service. I've also tried the quickstart (which I believe does exactly the same thing as calico the hard way, it just achieves this with volume mounts and daemonsets) but had similar symptoms. I suspect this is because the IPs being allocated to services are outside of the cidr parameter of the ippool definition. Note that this tutorial doesn't suggest to set the `--service-cidr` flag on kubeadm, but I believe that understanding it may be part of the way out.

Here's how I'm starting the cluster:
```
kubeadm init --pod-network-cidr=192.168.0.0/16 --control-plane-endpoint=k8s-cluster-endpoint --kubernetes-version=v1.19.0 --ignore-preflight-errors=NumCPU
```
The api servers are balanced using haproxy on two external VMs, all nodes /etc/hosts are configured to point `k8s-cluster-endpoint` to a virtual IP managed by keepalived. From what I can tell this is working perfectly and not related to the problem. 

Here are all resources in my cluster:
```
$ kubectl get all -A -o wide
NAMESPACE     NAME                                               READY   STATUS    RESTARTS   AGE     IP              NODE                   NOMINATED NODE   READINESS GATES
default       pod/pingtest2                                      1/1     Running   0          3h      192.168.8.193   ukcloud.int.k8s.wk01   <none>           <none>
default       pod/pingtest3                                      1/1     Running   0          3h      192.168.8.194   ukcloud.int.k8s.wk01   <none>           <none>
kube-system   pod/calico-node-n8fjd                              1/1     Running   0          3h4m    10.0.0.36       ukcloud.int.k8s.wk01   <none>           <none>
kube-system   pod/calico-node-r78zp                              1/1     Running   0          3h4m    10.0.0.33       ukcloud.int.k8s.ma01   <none>           <none>
kube-system   pod/calico-typha-ffff99464-rh9wb                   0/1     Pending   0          3h10m   <none>          <none>                 <none>           <none>
kube-system   pod/calico-typha-ffff99464-s95h4                   0/1     Pending   0          3h10m   <none>          <none>                 <none>           <none>
kube-system   pod/calico-typha-ffff99464-tkjtp                   1/1     Running   0          3h10m   10.0.0.36       ukcloud.int.k8s.wk01   <none>           <none>
kube-system   pod/coredns-f9fd979d6-5vnfq                        1/1     Running   0          3h56m   192.168.27.64   ukcloud.int.k8s.ma01   <none>           <none>
kube-system   pod/coredns-f9fd979d6-c8dhk                        1/1     Running   0          3h56m   192.168.27.65   ukcloud.int.k8s.ma01   <none>           <none>
kube-system   pod/etcd-ukcloud.int.k8s.ma01                      1/1     Running   0          3h56m   10.0.0.33       ukcloud.int.k8s.ma01   <none>           <none>
kube-system   pod/kube-apiserver-ukcloud.int.k8s.ma01            1/1     Running   0          3h56m   10.0.0.33       ukcloud.int.k8s.ma01   <none>           <none>
kube-system   pod/kube-controller-manager-ukcloud.int.k8s.ma01   1/1     Running   0          3h56m   10.0.0.33       ukcloud.int.k8s.ma01   <none>           <none>
kube-system   pod/kube-proxy-2vwls                               1/1     Running   0          3h56m   10.0.0.36       ukcloud.int.k8s.wk01   <none>           <none>
kube-system   pod/kube-proxy-8b9j7                               1/1     Running   0          3h56m   10.0.0.33       ukcloud.int.k8s.ma01   <none>           <none>
kube-system   pod/kube-scheduler-ukcloud.int.k8s.ma01            1/1     Running   0          3h56m   10.0.0.33       ukcloud.int.k8s.ma01   <none>           <none>

NAMESPACE     NAME                   TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)                  AGE     SELECTOR
default       service/kubernetes     ClusterIP   10.96.0.1       <none>        443/TCP                  3h56m   <none>
kube-system   service/calico-typha   ClusterIP   10.102.84.235   <none>        5473/TCP                 3h6m    k8s-app=calico-typha
kube-system   service/kube-dns       ClusterIP   10.96.0.10      <none>        53/UDP,53/TCP,9153/TCP   3h56m   k8s-app=kube-dns

NAMESPACE     NAME                         DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR            AGE     CONTAINERS    IMAGES                          SELECTOR
kube-system   daemonset.apps/calico-node   2         2         2       2            2           kubernetes.io/os=linux   3h4m    calico-node   calico/node:v3.8.0              k8s-app=calico-node
kube-system   daemonset.apps/kube-proxy    2         2         2       2            2           kubernetes.io/os=linux   3h56m   kube-proxy    k8s.gcr.io/kube-proxy:v1.19.0   k8s-app=kube-proxy

NAMESPACE     NAME                           READY   UP-TO-DATE   AVAILABLE   AGE     CONTAINERS     IMAGES                     SELECTOR
kube-system   deployment.apps/calico-typha   1/3     3            1           3h10m   calico-typha   calico/typha:v3.8.0        k8s-app=calico-typha
kube-system   deployment.apps/coredns        2/2     2            2           3h56m   coredns        k8s.gcr.io/coredns:1.7.0   k8s-app=kube-dns

NAMESPACE     NAME                                     DESIRED   CURRENT   READY   AGE     CONTAINERS     IMAGES                     SELECTOR
kube-system   replicaset.apps/calico-typha-ffff99464   3         3         1       3h10m   calico-typha   calico/typha:v3.8.0        k8s-app=calico-typha,pod-template-hash=ffff99464
kube-system   replicaset.apps/coredns-f9fd979d6        2         2         2       3h56m   coredns        k8s.gcr.io/coredns:1.7.0   k8s-app=kube-dns,pod-template-hash=f9fd979d6
```

Note: typha is not able to start 2 out of it's 3 replicas as I only have 1 worker node, I don't believe this is related to the problem though.

The end result is that pings between container IPs seem to be fine (they are all in `192.168.0.0/18`) but no container can access the DNS service for example.

`/etc/resolv.conf` of each container contains the DNS service IP which is expected, but it's not reachable:
```
$ kubectl exec -it pingtest2 -- cat /etc/resolv.conf
nameserver 10.96.0.10
search default.svc.cluster.local svc.cluster.local cluster.local openstacklocal
options ndots:5
```
Ping to DNS service fails:
```
kubectl exec -it pingtest2 -- ping 10.96.0.10 -c 1
PING 10.96.0.10 (10.96.0.10): 56 data bytes

--- 10.96.0.10 ping statistics ---
1 packets transmitted, 0 packets received, 100% packet loss
command terminated with exit code 1
```
Ping to another container IP succeeds:
```
$ kubectl exec -it pingtest2 -- ping 192.168.8.194 -c 1
PING 192.168.8.194 (192.168.8.194): 56 data bytes
64 bytes from 192.168.8.194: seq=0 ttl=63 time=0.171 ms

--- 192.168.8.194 ping statistics ---
1 packets transmitted, 1 packets received, 0% packet loss
round-trip min/avg/max = 0.171/0.171/0.171 ms
```

## Expected Behavior
Ping to service IPs should work (assuming that the `--service-cidr` is correct, which I suspect mine is not)

## Current Behavior
Ping to service IPs doesn't work

## Possible Solution
If the problem is indeed that I need to specify my `--service-cidr` flag, maybe more documentation or suggestions around suitable values for all three of these cidr values would be beneficial, at the moment I'm reduced to trial and error and unfortunately I don't yet have a solid understanding of how these three relate.

## Steps to Reproduce (for bugs)
Follow [calico the hard way](https://docs.projectcalico.org/getting-started/kubernetes/hardway/) to the letter, on openstack with VMs on a 10.0.0.0/8 network.

## Context
Trying to set up my first k8s cluster on prem.

## Your Environment

* Calico version
Client version: v3.14.0
calico/node version: v3.8.0

* Orchestrator version (e.g. kubernetes, mesos, rkt):
k8s v1.19.0
docker 19.03.12

* Operating System and version:
Ubuntu 18.04.1 LTS

* Link to your project (optional):

**Comment by emmetog** [comment]
After running a few more tests it looks like following the Calico quickstart tutorial **on Ubuntu 16.04** works perfectly, internal DNS resolutions are working fine. However following the same quickstart on Ubuntu 18.04 doesn't, connectivity to the DNS service fails as described above.

Interestingly I've managed to get it working on Ubuntu 18.04 by using an older version of the calico manifest.

Here are the commands: on Ubuntu 18.04 this does not work: 
```bash
# Bootstrap the cluster
$ kubeadm init --pod-network-cidr=192.168.0.0/16 --control-plane-endpoint=k8s-cluster-endpoint  --ignore-preflight-errors=NumCPU
$ kubectl create -f https://docs.projectcalico.org/manifests/tigera-operator.yaml
$ curl -o pool1.yaml https://docs.projectcalico.org/manifests/custom-resources.yaml
# Then I edit pool1.yaml a bit to look like this:
$ cat pool1.yaml 
# This section includes base Calico installation configuration.
# For more information, see: https://docs.projectcalico.org/v3.16/reference/installation/api#operator.tigera.io/v1.Installation
apiVersion: operator.tigera.io/v1
kind: Installation
metadata:
  name: default
spec:
  # Configures Calico networking.
  calicoNetwork:
    # Note: The ipPools section cannot be modified post-install.
    ipPools:
    - blockSize: 26
      cidr: 192.168.0.0/16
      encapsulation: None
      natOutgoing: Enabled
      nodeSelector: all()
$ kubectl apply -f pool1.yaml

$ kubectl apply -f https://k8s.io/examples/admin/dns/dnsutils.yaml
$ kubectl exec -i -t dnsutils -- nslookup google.com
;; connection timed out; no servers could be reached

command terminated with exit code 1
```

However, resetting the cluster and starting again with a different way of installing calico (following instructions [here](https://loves.cloud/setting-up-a-kubernetes-cluster-on-ubuntu-18-04/)) works:
```bash
# Bootstrap the cluster
$ kubeadm init --pod-network-cidr=192.168.0.0/16 --control-plane-endpoint=k8s-cluster-endpoint  --ignore-preflight-errors=NumCPU
$ kubectl apply -f https://docs.projectcalico.org/v3.11/manifests/calico.yaml
$ kubectl apply -f https://k8s.io/examples/admin/dns/dnsutils.yaml
$ kubectl exec -i -t dnsutils -- nslookup google.com
Server:		10.96.0.10
Address:	10.96.0.10#53

Non-authoritative answer:
Name:	google.com
Address: 172.217.20.78
Name:	google.com
Address: 2a00:1450:400e:80a::200e
```

**Comment by emmetog** [comment]
I've managed to get everything working on Ubuntu 18.04 as described above so my original issue is resolved.

> In particular, what can/should overlap and what cannot?

To answer my original question, the `--pod-network-cidr` flag from kubeadm is the same as my calico ippool in my currently working case (although still not entirely sure if it's ok for `--pod-network-cidr` to be a subset of the ippool cidr or vice versa). The `--service-cidr` can be left to defaults and not specified, my setup is running just fine even though `--service-cidr` defaults to 10.96.0.0/12, which overlaps with my VM network (which is 10.0.0.0/8).

I'm happy to close this unless you'd like to dig into why the latest manifests in the Calico quickstart tutorial don't seem to work on Ubuntu 18.04, I can spin up another test cluster if any more info is needed.

**Comment by caseydavenport** [comment]
Sorry for the delay here, but glad you figured out your original issue. Agree with your conclusion.

I am surprised the manifests do not work on 18.04, though. I believe we have regular automated tests in that environment. 

I see that you modified the IP pool to disable encapsulation in your first non-working example, whereas in the second working example I would expect encapsulation to be enabled (because that is the default). 

you might want to try without modifying `custom-resources.yaml` and see if that gives you better results.

**Comment by mercanon** [comment]
I have a variation on the original post that I don't understand.  I have essentially the same config; 3 node cluster the hard way.  My problem is not DNS; it works as expected in the cluster.  I'm trying to test the Typha Service and can't reach the service IP as documented in [Calico the hard way](https://docs.projectcalico.org/getting-started/kubernetes/hardway/install-typha).  However, it's reachable from each node's Internal IP.  Is that expected?  The other Service addresses in the cluster work as expected.  I don't understand yet how the IPs are allocated from the service space (ie. 10.96.0.0/12) but curious why it's so different for Calico.  The kubernetes Service provides a route to kube-dns but I suspect calico-typha isn't reachable since there's no route.  Any ideas?

Thanks.

kubectl get svc  -A
NAMESPACE     NAME           TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)                  AGE
default       kubernetes     ClusterIP   10.96.0.1       <none>        443/TCP                  2d2h
kube-system   calico-typha   ClusterIP   10.102.65.139   <none>        5473/TCP                 140m
kube-system   kube-dns       ClusterIP   10.96.0.10      <none>        53/UDP,53/TCP,9153/TCP   2d2h

**Comment by etesami** [comment]
For those experiencing a similar issue, I found that the calico-node pod running on the same node as CoreDNS was not in a ready state due to an MTU configuration issue. Restarting the calico-node pod resolved the problem, restoring access to the DNS service.
