### ISSUE TITLE
[v3.16.1]helm3 can not parse calico/templates/kdd-crds.yaml

### ISSUE THREAD

**Issue by mozhuli** [projectcalico/calico#3996]
we use helm3 to manage calico, but parse error as below. 
we change to use version 3.10 `apiextensions.k8s.io/v1beta1`, it is work fine!

maybe there is some special character cause it ?

```
I0912 16:04:11.651390    3754 client.go:376] [helm3] preparing upgrade for copaddon-calico
W0912 16:04:11.695923    3754 client.go:220] Failed to create release copaddon-calico for YAML parse error on calico/templates/calico-crd.yaml: error converting YAML to JSON: yaml: control characters are not allowed; Retry again

```
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Calico version
* Orchestrator version (e.g. kubernetes, mesos, rkt):
* Operating System and version:
* Link to your project (optional):

**Comment by ben-turner** [comment]
There seems to be invalid characters in the [manifests](https://docs.projectcalico.org/manifests/calico.yaml). Searching for `_label` is the easiest way to find them. Looks like `â€œmy_labelâ€<9d>`. Possibly some kind of encoding error? It prevents all of the CRDs from being applied

**Comment by lmm** [comment]
We recently got a fix here https://github.com/projectcalico/libcalico-go/pull/1350, we just need to migrate those changes over to the manifests.

**Comment by caseydavenport** [comment]
Master manifests should have those characters removed now!
