### ISSUE TITLE
Fix/remove broken libvirt links in Ubuntu and Red Hat Openstack install docs

### ISSUE THREAD

**Issue by eepyaich** [projectcalico/calico#4]
In the ubuntu and Red Hat openstack install docs, there is a reference to <http://wiki.libvirt.org/page/Guest_won't_start_-_warning:_could_not_open_/dev/net/tun_('generic_ethernet'_interface)> which appears to no longer exist.

**Comment by neiljerram** [comment]
Fixed by https://github.com/projectcalico/calico/pull/75
