### ISSUE TITLE
felix_active_local_endpoints - what is the reasonable maximum per node?

### ISSUE THREAD

**Issue by sagor999** [projectcalico/calico#4006]
Hi,

I am adding grafana dashboard for calico\felix, and default dashboard provided in documents has maximum set to `80` for felix_active_local_endpoints. Implying that if your host has more than 80 local endpoints, that this is bad.
I wanted to confirm if that is indeed a reasonable maximum? 
We have hosts that have over 100 local endpoints, so it shows up as red gauge in grafana. 

Thank you!
![Screenshot from 2020-09-17 09-16-31](https://user-images.githubusercontent.com/18602811/93498479-b6a98f00-f8c6-11ea-905a-dfc4b8177ce8.png)

**Comment by caseydavenport** [comment]
This is really dependent on how your cluster is configured. What is the highest number of workloads / pods that you expect to be running on any given node at a time? That's probably a good approximation for this number.

**Comment by sagor999** [comment]
Got it. Was just making sure that it is not some sort of a limit for calico. 
Thank you!
