### ISSUE TITLE
HostEndpoint objects remain after calico node is deleted

### ISSUE THREAD

**Issue by bradbehle** [projectcalico/calico#4015]
It looks like when a kubernetes worker node is deleted (when etcd datastore is being used), the calico node data, WorkloadEndpoints, etc are all deleted as well for that node.  However the HostEndpoint object(s) associated with that node are not deleted.  Is this a known issue, and any chance it could be changed to also delete the HostEndpoints associated with that node?  It seems like the HostEndpoint objects that were associated with that node are now useless and should be deleted.

## Expected Behavior
All objects, including HostEndpoints, that are associated with a calico node object should be deleted when the calico node object is deleted

## Current Behavior
HostEndpoint objects associated with a given Node object are not deleted when that Node object is deleted (at least not in etcd datastore mode)

## Possible Solution
Delete them

## Steps to Reproduce (for bugs)
1. Create a k8s cluster with calico in etcd datastore mode with a few worker nodes, and HostEndpoints for each of the nodes (doesn't matter if there are policies applied or not)
2. Delete one of the k8s cluster worker nodes
3. Notice that all the data associated with those workers go away, except for the HostEndpoints
4.

## Context
Our IKS cluster workers automatically get a public and private HostEndpoint (to protect the public and private network interfaces on the worker).  We have customers that use a worker autoscaler to regularly create and delete many nodes a day.  The nodes and most associated objects (WEPs, etc) get cleaned up by calico-kube-controllers, but the HostEndpoint objects remain, and there is no good way to clean up the ones that aren't in use.

## Your Environment

* Calico version: Various, we've seen this behavior in 3.13 and below (haven't tried it on newer versions yet)
* Orchestrator version (e.g. kubernetes, mesos, rkt): kubernetes (version doesn't matter)
* Operating System and version: Ubuntu
* Link to your project (optional):

**Comment by caseydavenport** [comment]
I'll try to dig into whether this is intentional or not, but feels like we should be deleting these.

**Comment by bradbehle** [comment]
@caseydavenport Any update on this?

**Comment by caseydavenport** [comment]
Certainly looks like it was just omitted in this code, where we delete all the other per-node resources on deletion: https://github.com/projectcalico/libcalico-go/blob/34d8399da1480a4f47a32d2bb205cc59d7319ec1/lib/clientv3/node.go#L174-L221

**Comment by caseydavenport** [comment]
Sorry for the delay on this guy, but working on a fix here: https://github.com/projectcalico/libcalico-go/pull/1355
