### ISSUE TITLE
Better support to secure kubernetes apiserver endpoint

### ISSUE THREAD

**Issue by skaegi** [projectcalico/calico#4017]
Writing NetworkPolicy to prevent typical application pods from accessing the `kubernetes` service or alternately to allow controller pods access is harder than it needs to be. The `kubernetes` service is unique, in that it doesn't provide a selector as it is not provided by a pod and so is not modelled by a `WorkloadEndpoint` and also not modelled by a `HostEndpoint`.

## Expected Behavior
I'd like to be able to write a NetworkPolicy for the kubernetes service using a label `selector` instead of a `nets` ip block

## Current Behavior
We currently need to write our NetworkPolicy in terms of ip blocks. 

## Possible Solution
One approach / possible workaround is to auto-create create a GlobalNetworkSet with a single entry for the kubernetes service Endpoint and appropriate labels.

## Context
We need cluster specific knowledge in order to secure access to the apiserver because there is no endpoint abstraction.

## Your Environment

Calico Version:   v3.12.2
Cluster Type:      k8s,bgp

**Comment by caseydavenport** [comment]
I would expect the Kubernetes API server to be modeled by a host endpoint, since it is a host-networked process running on cluster. 

That said, we could probably still make this easier by automatically populating network sets. But you should be able to do this today with a host endpoint.
