### ISSUE TITLE
Cannot Get Source IP In Pod Using Microk8s

### ISSUE THREAD

**Issue by sstubbs** [projectcalico/calico#4019]
Microk8s now uses calico by default I have a single node with a NodePort service setup and when there are connections I cannot get the ip.

## Expected Behavior
The actual ip of the client connecting to be visible.

## Current Behavior
All connections seem to show the source ip of 169.254.0.2 

## Possible Solution
If I disable the ha-plugin it removes calico and goes back to flannel. This then works as expected and I can get the ips.

## Steps to Reproduce (for bugs)
```
sudo snap install microk8s --classic --channel=1.19
```
The calico plugin is now enabled by default

## Context
I need to track ips for blacklisting.

## Your Environment

calico v3.13.2
Kubernetes 1.19
OS Ubuntu 20.04

**Comment by sstubbs** [comment]
I think this might be related to this issue https://github.com/projectcalico/calico/issues/3585

**Comment by caseydavenport** [comment]
Sounds like something is doing NAT on your incoming connections. 

I'd check `iptables-save -c | grep SNAT` and `iptables-save -c | grep MASQ` to see if there are any rules getting hit that would be causing this. 

Generally, Calico shouldn't be performing NAT on traffic coming through a NodePort, but Kubernetes _will_ NAT that traffic in some circumstances (unless it is set to externalTrafficPolicy: local)

**Comment by sstubbs** [comment]
Thanks for the suggestion @caseydavenport 

I've just used the microk8s cilium addon for the being. Both cilium and flannel don't seem to have this issue. I should have another server to to test it on it a week or two. Then I can use their default configuration on this which uses calico and try help figure out why this is happening.

**Comment by sstubbs** [comment]
This issue seems to be resolved in the latest version of microk8s
