### ISSUE TITLE
felix  运行报错，和 iptables 有关嘛，急

### ISSUE THREAD

**Issue by xuan200922702** [projectcalico/calico#4020]
这个问题是什么原因呢

felix  运行报错，和 iptables 有关嘛，急
![image](https://user-images.githubusercontent.com/32674956/94000624-00fca580-fdca-11ea-958f-a2fcf16d7c4d.png)

**Comment by song-jiang** [comment]
@xuan200922702 请你提供更多信息。比如calico 版本，Linux版本，BGP 或者 VXLAN...

**Comment by xuan200922702** [comment]
> @xuan200922702 请你提供更多信息。比如calico 版本，Linux版本，BGP 或者 VXLAN...

calico 版本是 3.4.4    linux是 deepin

**Comment by song-jiang** [comment]
Calico和Linux都是比较老的版本，感觉是iptable命令兼容性的问题。

**Comment by song-jiang** [comment]
I am closing this issue. If you have more info, you can open it again.
