### ISSUE TITLE
Dynamically assigned ippools

### ISSUE THREAD

**Issue by janmalecek** [projectcalico/calico#4021]
Hello,
In our environment, for special purposes we use small ippools, which would be nice to be dynamically assigned - not dependent on a single node for a lifetime (how are ippools designed now). IP borrowing causes routing problems (as described in context paragraph).

## Expected Behavior
We would like to have something like "dynamic ippools" - blocks (or single addresses) will be assigned to a particular node just  for a workload lifetime. When a workload is moved/deleted, empty block is immediately released to be used on another node.

## Current Behavior
Block from ippool is assigned to a particular node for a node lifetime

## Possible Solution
- Something like "dynamic" flag in ippool definition, which causes release of assigned block when flag is set & block is empty
- maybe working /32 blockSize assignments would solve our problems (because it will not allow IP address borrowing)

## Context
Our use case:
In addition to a static ippool allocation per node (based on a network structure) we use a few small ippools cluster-wide (every ippool is configured on a NAT gateway to be behind a particular IP address)

When a block from ippool is assigned to a node, it is for a lifetime, as I have been told a few months ago on Slack by @caseydavenport . In our clusters (300+ nodes) for a limited set of deployments (size <16 pods) we need to assign special IP addresses from mentioned small ippools, used for NAT. We use an annotation in Deployment to choose right ippool.

The problem is when this workload is moving around the cluster. These "small" ippool are sized /28 and have blockSize set to 31 (I would set 32, but we are hitting bug #2624 ). This ippool runs out of blocks when a single block is assigned to 8 nodes. This is the point, where IP address borrowing starts. We have a problem with borrowing, because our infrastructure does not distribute /32 routes everywhere (lower layer switches does not have full routing information) and sometimes it causes routing problems (when traffic is routed to /31 block route, because device lacks of /32 route).

## Your Environment
* Calico version 3.10.1
* Orchestrator version (e.g. kubernetes, mesos, rkt): Kubernetes 1.16.10
* Operating System and version: Ubuntu 18.04

I hope my description is understandable; I am also ready to answer any question.

Thank you & best regards,
Jan Malecek

**Comment by caseydavenport** [comment]
Yeah, this seems legit. We made a choice to bind blocks to nodes for the node's life in order to reduce route churn, but obviously that isn't right for everyone.

One option might be to have this configurable on the pool? Then you can decide on a per-pool basis if they should be "sticky" or not. Would that work?

**Comment by janmalecek** [comment]
Yes, it would definitely work.

**Comment by halfcrazy** [comment]
Can't wait to see it.

**Comment by caseydavenport** [comment]
@janmalecek @halfcrazy In Calico v3.20 we added some logic to release blocks given some conditions:

- The block must be empty
- The node must have another block assigned to it with space available

This is enabled by default so upgrading to v3.20 _should_ just do the trick - give it a spin and let me know if it's working for your use-case!

**Comment by janmalecek** [comment]
We have upgraded our clusters to v3.20 a few weeks ago and we are testing block releasing right now. It looks great - blocks are being released. Also #2624 was fixed - we are fine with this setup now. Thanks @caseydavenport !
