### ISSUE TITLE
[3.16.1] Switching IPIP to VXLAN error

### ISSUE THREAD

**Issue by Maellooou** [projectcalico/calico#4022]
On my on-premise cluster kubernetes (1.18), I deployed Calico 3.16.1 with manifest and configuration IPIP. As I want to use windows nodes, I have to switch to VXLAN configuration and it doesn't work.

I follow the documentation here : https://docs.projectcalico.org/getting-started/kubernetes/installation/config-options#switching-from-ip-in-ip-to-vxlan

As the pool has already been created, I used calicoctl to perform the change.

## Expected Behavior
Calico nodes should restart with the good configuration and routes of each nodes should be ok

## Current Behavior
Some nodes didn't take the right routing configuration 

```
[cloud@ingress01 ~]$ netstat -rn
Table de routage IP du noyau
Destination     Passerelle      Genmask         Indic   MSS Fenêtre irtt Iface
0.0.0.0        x.y.72.193   0.0.0.0         UG        0 0          0 eth0
x.y.72.192   0.0.0.0         255.255.255.224 U         0 0          0 eth0
169.254.169.254 x.y.72.193   255.255.255.255 UGH       0 0          0 eth0
172.12.21.193   0.0.0.0         255.255.255.255 UH        0 0          0 cali8504ae9df2a
172.17.0.0      0.0.0.0         255.255.0.0     U         0 0          0 docker0


[cloud@ingress02 ~]$ netstat -rn
Table de routage IP du noyau
Destination     Passerelle      Genmask         Indic   MSS Fenêtre irtt Iface
0.0.0.0         x.y.72.225   0.0.0.0         UG        0 0          0 eth0
x.y.72.224   0.0.0.0         255.255.255.224 U         0 0          0 eth0
169.254.169.254 x.y.72.225   255.255.255.255 UGH       0 0          0 eth0
172.12.15.129   0.0.0.0         255.255.255.255 UH        0 0          0 cali6690c73972e
172.12.21.192   172.12.21.194   255.255.255.192 UG        0 0          0 vxlan.calico
172.12.48.192   172.12.48.193   255.255.255.192 UG        0 0          0 vxlan.calico
172.12.162.64   172.12.162.67   255.255.255.192 UG        0 0          0 vxlan.calico
172.12.163.0    172.12.163.1    255.255.255.192 UG        0 0          0 vxlan.calico
172.12.177.192  172.12.177.193  255.255.255.192 UG        0 0          0 vxlan.calico
172.12.205.192  172.12.205.199  255.255.255.192 UG        0 0          0 vxlan.calico
172.12.219.0    172.12.219.6    255.255.255.192 UG        0 0          0 vxlan.calico
172.12.241.128  172.12.241.129  255.255.255.192 UG        0 0          0 vxlan.calico
172.17.0.0      0.0.0.0         255.255.0.0     U         0 0          0 docker0
```

I also tried to get the calico-vxlan.yaml manifest and apply it. But the issue is still the same.

## Steps to Reproduce (for bugs)
1. Install calico 3.16.1 with IPIP configuration
2. Try to switch to VXLAN with calicoctl

## Your Environment

* Calico version : 3.16.1
* Orchestrator version (e.g. kubernetes, mesos, rkt): On-premier 1.18.3
* Operating System and version: CentOS Linux release 7.5.1804

**Comment by caseydavenport** [comment]
@Maellooou could you share what your IP pools look like on this cluster? 

e.g., `calicoctl get ippools`

**Comment by lmm** [comment]
@Maellooou I'm going to close this for now but if you're still running into this issue please reopen or file a new issue, thanks!
