### ISSUE TITLE
BGP not advertising serviceExternalIPs

### ISSUE THREAD

**Issue by kifeo** [projectcalico/calico#4027]
I configured Calico to use BGP to advertise the range in serviceExternalIPs.
The peering is ok with the Fortigate (router/firewall appliance).
There are the node networks advertised :
```
get router info bgp network
BGP table version is 1, local router ID is 0.0.0.1
Status codes: s suppressed, d damped, h history, * valid, > best, i - internal,
              S Stale
Origin codes: i - IGP, e - EGP, ? - incomplete

   Network          Next Hop            Metric LocPrf Weight RouteTag Path
*>i172.16.4.0/26    10.0.14.15               0    100      0        0 i <-/1>
*>i172.16.35.128/26 10.0.14.12               0    100      0        0 i <-/1>
*>i172.16.66.192/26 10.0.14.14               0    100      0        0 i <-/1>
*>i172.16.67.0/26   10.0.14.14               0    100      0        0 i <-/1>
*>i172.16.97.128/26 10.0.14.13               0    100      0        0 i <-/1>
*>i172.16.97.192/26 10.0.14.13               0    100      0        0 i <-/1>
*>i172.16.113.0/26  10.0.14.11               0    100      0        0 i <-/1>
*>i172.16.113.64/26 10.0.14.11               0    100      0        0 i <-/1>

```

However the serviceExternalIPs is not advertised.
Here is the bgpconfiguration :
```
k describe bgpconfiguration default
Name:         default
Namespace:    
Labels:       fluxcd.io/sync-gc-mark=sha256.Pfm1qGB4XKc27mS8dpH-4xiNgnOlrmIb4nvRFv875go
Annotations:  fluxcd.io/sync-checksum: 9ad19ae74f0dc2376d9fe859054c4242807d2397
API Version:  crd.projectcalico.org/v1
Kind:         BGPConfiguration
Metadata:
  Creation Timestamp:  2020-09-21T14:01:35Z
  Generation:          6
  Resource Version:    48361837
  Self Link:           /apis/crd.projectcalico.org/v1/bgpconfigurations/default
  UID:                 6674c76c-eaee-414a-b998-65a44a2c5d51
Spec:
  Service External I Ps:
    Cidr:  10.0.15.0/24
Events:    <none>
```

## Expected Behavior

The serviceExternalIPs is advertised

## Current Behavior

The serviceExternalIPs is not advertised

## Possible Solution

I did not find anything in my troubleshooting, however some suggestions are welcome on how to look for the issue.

## Context

I moved from Metallb to Calico

## Your Environment

* Calico version
* Orchestrator version (e.g. kubernetes, mesos, rkt): kubernetes v1.19.0
* Operating System and version: Debian
* Link to your project (optional):

**Comment by caseydavenport** [comment]
@kifeo could you check the calico/node logs on one of your nodes to see if there are any indicators of what might be going wrong?

If you could share the log here that would also be helpful.

**Comment by kifeo** [comment]
Thanks for the help, I reuninstalled metallb and put back the calico configuration as above (except using ebgp instead of ibgp to match the metallb config).
I did check but could not find anything, here you go:
for node in `k get pods -n kube-system | grep calico-node | awk '{print $1}'`; do k logs -n kube-system $node | grep "2020-10-03" > $node.log; done

[calico-nodes.log.zip](https://github.com/projectcalico/calico/files/5321584/calico-nodes.log.zip)

**Comment by salanki** [comment]
Please see: https://github.com/projectcalico/confd/pull/385#issuecomment-722664028

**Comment by caseydavenport** [comment]
@kifeo I don't see anything suspicious in the logs, could you share an example of one of the services that you're expecting to be advertised? e.g., `kubectl get service X -o yaml`?
