### ISSUE TITLE
iptables on k8s node do not work

### ISSUE THREAD

**Issue by Iamlovingit** [projectcalico/calico#4029]
Hello everyone. I am a newer to calico. I setup a cluster with k8s and clico, and I deploy grafana on the k8s-node, the grafana use `nodePort` to match the host 30004 port. Now I want to add a rule to forbide the 30004 port. I run the cmd on the k8s-node 
```
iptables -A INPUT -p tcp --dport 30004 -j DROP
```
but it not works, I can open the home page of grafana.
Anyone can help me out?

my k8s version 1.15.3
my calico version 3.9.5

**Comment by caseydavenport** [comment]
Calico makes sure that its own iptables rules take precedence over manually added rules. One of the main use-cases of Calico is to remove the need to manually program iptables, and instead use NetworkPolicy to enforce restrictions.

**Comment by caseydavenport** [comment]
You can use host endpoints and preDNAT policy to enforce policy on node ports: https://docs.projectcalico.org/reference/host-endpoints/overview
