### ISSUE TITLE
[v3.16.1] Calico docs manifests has json control characters and improper encoding

### ISSUE THREAD

**Issue by hjkatz** [projectcalico/calico#4036]
This link: https://docs.projectcalico.org/manifests/calico.yaml

From these docs: https://docs.projectcalico.org/getting-started/kubernetes/self-managed-onprem/onpremises

Includes characters such as: " â€Notâ€"

See most of the CRD descriptions, example:
```yaml
              egress:
                description: The ordered set of egress rules.  Each rule contains
                  a set of packet match criteria and a corresponding action to apply.
                items:
                  description: "A Rule encapsulates a set of match criteria and an
                    action.  Both selector-based security Policy and security Profiles
                    reference rules - separated out as a list of rules for both ingress
                    and egress packet matching. \n Each positive match criteria has
                    a negated version, prefixed with â€Notâ€. All the match criteria
                    within a rule must be satisfied for a packet to match. A single
                    rule can contain the positive and negative version of a match
                    and both must be satisfied for the rule to match."
                  properties:
```

When applying this yaml to the k8s cluster we get this error:

```
error: error parsing calico.yaml: error converting YAML to JSON: yaml: control characters are not allowed
```

I tried looking around for where/how these manifests are generated but I wasn't able to track it down quickly so I'm reporting the issue instead.

The fix for me was replacing all of these encoding errors with quotes like `\"Not\"` as an example for the above CRD description.

**Comment by caseydavenport** [comment]
@hjkatz I'm able to cleanly apply that manifest without any errors, although I agree it renders strangely in a browser or editor window.

How are you downloading the file? I've seen in the past that some editors have had trouble with proper yaml escaping when copy/pasting the contents of the file from a browser. However, downloading the file directly should work, or at least it does in my testing.

**Comment by hjkatz** [comment]
@caseydavenport You know what? I didn't download the yaml directly, instead I opened the raw content in the web browser and then copy/pasted into my editor (Neovim on Mac using Terminal) so likely some encoding got messed up there.

When downloading the file with `wget -O /tmp/calico.yaml https://docs.projectcalico.org/manifests/calico.yaml` the text is encoded properly and I see the following:

```
                  description: "A Rule encapsulates a set of match criteria and an
                    action.  Both selector-based security Policy and security Profiles
                    reference rules - separated out as a list of rules for both ingress
                    and egress packet matching. \n Each positive match criteria has
                    a negated version, prefixed with ”Not”. All the match criteria
                    within a rule must be satisfied for a packet to match. A single
                    rule can contain the positive and negative version of a match
                    and both must be satisfied for the rule to match."
```

These fancy quotes are what caused the encoding issue for me in the first place. This issue can be closed, sorry for the confusion.

**Comment by erihanse** [comment]
I hope it's okay to ask this: Do we need to use these fancy quotes? I wasted quite some time on this as well.

**Comment by caseydavenport** [comment]
We don't need to use them, no. We should probably fix this since it seems like this is impacting a few users. 

The text in those files is automatically generated by some third-party tooling. So, we'll probably need to patch that tool (assuming that's where the fancy quotes are originating and not somewhere further down the tool chain).

**Comment by caseydavenport** [comment]
This PR fixes a bunch of these, but not sure it fixes all of them: https://github.com/projectcalico/libcalico-go/pull/1289

Will be in Calico v3.17.
