### ISSUE TITLE
install-calico-windows.ps1 on EKS fails getting secret value

### ISSUE THREAD

**Issue by dave-meier** [projectcalico/calico#4037]
**Steps to reproduce the issue:** 

Using latest install-calico-windows.ps1 script:
calico-windows-v3.16.1.zip
Windows Node is 1909 Server Core
Cluster created with eksctl, one linux node and one Windows 1909 Server Core node

1. Following instructions on [installing calico on Windows EKS node](https://docs.projectcalico.org/getting-started/windows-calico/quickstart)
2. Running install-calico-windows.ps1
3. I added a statement to write out the KubeConfigPath and SecretName.

**Full output of failed command:** 
```
c:\install-calico-windows.ps1 -ServiceCidr 172.20.0.0/16 -DNSServerIPs 172.20.0.10
...
Setup Calico for Windows for eks, node name ip-10-12-40-185.usw23.saas.int ...
AWSPowerShell module exists, loading C:\Program Files (x86)\AWS Tools\PowerShell\AWSPowerShell\AWSPowerShell.psd1 ...
Error from server (Forbidden): secrets is forbidden: User "system:node:ip-10-12-40-185.us-west-2.compute.internal" cannot list resource "secrets" in API group "" in the namespace "kube-system": No Object name found
KubeConfigPath: C:\ProgramData\kubernetes\kubeconfig, SecretName: calico-node
calico-node service account does not exist.
At C:\install-calico-windows.ps1:119 char:9
+         throw "$SecretName service account does not exist."
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (calico-node ser...does not exist.:String) [], RuntimeException
    + FullyQualifiedErrorId : calico-node service account does not exist.
```

Running the command directly:
```
PS C:\k> c:\k\kubectl.exe --kubeconfig="C:\ProgramData\kubernetes\kubeconfig" get secret -n kube-system
Error from server (Forbidden): secrets is forbidden: User "system:node:ip-10-12-40-185.us-west-2.compute.internal" cannot list resource "secrets" in API group "" in the namespace "kube-system": No Object name found
```
What do I need to do to make this work?

**Comment by dave-meier** [comment]
Looking at [https://kubernetes.io/docs/reference/access-authn-authz/node/](url) I see the following:

RBAC Node Permissions

In 1.6, the system:node cluster role was automatically bound to the system:nodes group when using the RBAC Authorization mode.

In 1.7, the automatic binding of the system:nodes group to the system:node role is deprecated because the node authorizer accomplishes the same purpose with the benefit of **additional restrictions on secret and configmap access**. If the Node and RBAC authorization modes are both enabled, the automatic binding of the system:nodes group to the system:node role is not created in 1.7.

In 1.8, the binding will not be created at all.

When using RBAC, the system:node cluster role will continue to be created, for compatibility with deployment methods that bind other users or groups to that role.

So it appears that by default, the system:node role is **not** bound to the system:nodes group, and they mention that there are restrictions of secret access.

**What is the best way to deal with this?**

I fixed it for now by editing the clusterrolebinding for system:node and adding the system:nodes group as a subject. This needs to be done from your controlling instance where you have full admin rights with kubectl:

kubectl.exe edit clusterrolebinding system:node

**Add the following:**
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: system:nodes

**Save and you will see:**
clusterrolebinding.rbac.authorization.k8s.io/system:node edited

PS U:\cont\customer> kubectl.exe describe clusterrolebinding system:node
Name:         system:node
Labels:       kubernetes.io/bootstrapping=rbac-defaults
Annotations:  rbac.authorization.kubernetes.io/autoupdate: true
Role:
  Kind:  ClusterRole
  Name:  system:node
Subjects:
  Kind   Name          Namespace
  ----   ----          ---------
  Group  system:nodes

**Comment by lmm** [comment]
Thanks for the details @dave-meier ! Glad to hear you got that sorted out.

Yeah, out of the box the IAM instance role in the EKS nodes kubeconfig does not have access to kube-system, which our installation script depends on. There's a note on this requirement in the quickstart under node requirements but I think we can add an external link to that at the very least. (We're also missing this note in the Standard install docs, so I'll fix that.)

Have you seen? https://docs.aws.amazon.com/eks/latest/userguide/add-user-role.html It details how the nodegroups IAM could be linked to Kubernetes groups using the `aws-auth` configmap.

**Comment by dave-meier** [comment]
Thanks @lmm 

I'm having another problem now, with repeated failures in calico-node.log. Do you have any suggestions on how to fix it?

```
2020-09-29 22:21:45.594 [INFO][4396] startup/startup.go 361: Early log level set to info
2020-09-29 22:21:45.662 [INFO][4396] startup/startup.go 377: Using NODENAME environment for node name
2020-09-29 22:21:45.662 [INFO][4396] startup/startup.go 389: Determined node name: ip-10-12-40-83.usw23.saas.int
2020-09-29 22:21:45.666 [INFO][4396] startup/startup.go 111: Skipping datastore connection test
2020-09-29 22:21:45.695 [INFO][4396] startup/startup.go 472: Building new node resource Name="ip-10-12-40-83.usw23.saas.int"
2020-09-29 22:21:45.696 [INFO][4396] startup/startup.go 487: Initialize BGP data
2020-09-29 22:21:45.705 [INFO][4396] startup/startup.go 746: Using autodetected IPv4 address on interface vEthernet (Ethernet 3): 10.12.40.83/25
2020-09-29 22:21:45.705 [INFO][4396] startup/startup.go 563: Node IPv4 changed, will check for conflicts
2020-09-29 22:21:45.727 [WARNING][4396] startup/node.go 66: Operation Create is not supported on Node type
2020-09-29 22:21:45.728 [ERROR][4396] startup/startup.go 197: Unable to set node resource configuration error=operation Create is not supported on Node(ip-10-12-40-83.usw23.saas.int)
2020-09-29 22:21:45.728 [WARNING][4396] startup/startup.go 1310: Terminating
Calico node initialisation failed, will retry...
```

**Comment by lmm** [comment]
Closing as the original issue was resolved
