### ISSUE TITLE
Not able to enable calico-typha after editing cluster config

### ISSUE THREAD

**Issue by vladh91** [projectcalico/calico#4046]
## Expected Behavior

Per the calico documentation calico/typha can be enabled on existing cluster by editing cluster configuration and appending `typhaReplicas: 3` to calico : https://kops.sigs.k8s.io/networking/calico/#configuring-calico-to-use-typha

## Current Behavior

After applying those changes in existing on premise k8s cluster and running `rolling update` we don't see calico-typha pods created, nothing is changed.

## Steps to Reproduce (for bugs)

1. using kops edit cluster configuration:
    `kops edit cluster`
2. update `calico` section and append with `typhaReplicas: 3` to enable calico-typha per kops/calico docs
3. run rolling update of the cluster

## Context

We have on premise kubernetes cluster and we are having cases when we have more than 50 nodes in the cluster. For those cases we are seeing network related issues.

## Your Environment

* Calico version
```v3.9.5```
* Orchestrator version (e.g. kubernetes, mesos, rkt):
``` Kubernetes v1.16.9```
* Operating System and version:
``` PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
NAME="Debian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
VERSION_CODENAME=stretch
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/```

**Comment by lmm** [comment]
Hi @vladh91, sorry for the delay! Which version of kops are you using?

**Comment by caseydavenport** [comment]
Sounds like this is more than likely a kops code or docs bug rather than a Calico bug

**Comment by song-jiang** [comment]
Close this issue. @vladh91 you can reopen if you are certain it is a Calico bug.
