### ISSUE TITLE
Windows EKS - Pod to pod dns and calls to services or other pods all fail when Windows Calico services are running

### ISSUE THREAD

**Issue by dave-meier** [projectcalico/calico#4048]
Steps to reproduce the issue:

Using latest install-calico-windows.ps1 script:
calico-windows-v3.16.1.zip
Windows Node is 1909 Server Core
Cluster created with eksctl, one linux node and one Windows 1909 Server Core node

Implemented config change to solve #4037 and changed NODENAME in config.ps1 to solve #4040 

So now calico services are running on the Windows node, and I don't see any obvious errors. When I run my pods on the Windows node, they cannot reach other services that I am running, which are all in the same k8s namespace. I have 3 pods, all in the same namespace. Resolve-DnsName fails on the services, and curl fails, even when the container IP address is used. These commands are issued from inside of one of my containers. **Before running Calico on the Windows node, these commands all work correctly. Not sure what to check or try next.**

I have not applied any policies yet, so I know it's not being caused by that, as I assume all traffic is allowed by default, when there is no NetworkPolicy applied.

Commands inside container 1:
```
PS C:\> ipconfig /all

Windows IP Configuration

   Host Name . . . . . . . . . . . . : sbm-slm1
   Primary Dns Suffix  . . . . . . . :
   Node Type . . . . . . . . . . . . : Hybrid
   IP Routing Enabled. . . . . . . . : No
   WINS Proxy Enabled. . . . . . . . : No
   DNS Suffix Search List. . . . . . : green.svc.cluster.local
                                       svc.cluster.local
                                       cluster.local

Ethernet adapter vEthernet (cid-52d97690175fc464feef3dd7b8b7978e1f6bf28273f976e8f4826e214b94eac9):

   Connection-specific DNS Suffix  . : green.svc.cluster.local
   Description . . . . . . . . . . . : Hyper-V Virtual Ethernet Adapter #5
   Physical Address. . . . . . . . . : 00-15-5D-7F-0B-CA
   DHCP Enabled. . . . . . . . . . . : No
   Autoconfiguration Enabled . . . . : Yes
   Link-local IPv6 Address . . . . . : fe80::79ae:9461:7c20:c948%34(Preferred)
   IPv4 Address. . . . . . . . . . . : 10.12.40.119(Preferred)
   Subnet Mask . . . . . . . . . . . : 255.255.255.128
   Default Gateway . . . . . . . . . : 10.12.40.1
   DNS Servers . . . . . . . . . . . : 172.20.0.10
   NetBIOS over Tcpip. . . . . . . . : Disabled
   Connection-specific DNS Suffix Search List :
                                       green.svc.cluster.local
                                       svc.cluster.local
                                       cluster.local
PS C:\> Resolve-DnsName nginx.green.svc.cluster.local
Resolve-DnsName : nginx.green.svc.cluster.local : This operation returned because the timeout period expired
At line:1 char:1
+ Resolve-DnsName nginx.green.svc.cluster.local
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationTimeout: (nginx.green.svc.cluster.local:String) [Resolve-DnsName], Win32Exception
    + FullyQualifiedErrorId : ERROR_TIMEOUT,Microsoft.DnsClient.Commands.ResolveDnsName
PS C:\> curl 10.12.40.115 -UseBasicParsing
curl : Unable to connect to the remote server
At line:1 char:1
+ curl 10.12.40.115 -UseBasicParsing
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand
```
Container 2, which is being referenced by Container 1:
```
PS C:\> ipconfig /all

Windows IP Configuration

   Host Name . . . . . . . . . . . . : nginx-58547f579f-t2f2m
   Primary Dns Suffix  . . . . . . . :
   Node Type . . . . . . . . . . . . : Hybrid
   IP Routing Enabled. . . . . . . . : No
   WINS Proxy Enabled. . . . . . . . : No
   DNS Suffix Search List. . . . . . : green.svc.cluster.local
                                       svc.cluster.local
                                       cluster.local

Ethernet adapter vEthernet (cid-8c778496fd086112a7e0cc84c285d49f7c342c6ec5ce5e5f2bd7725c7bb8f22d):

   Connection-specific DNS Suffix  . : green.svc.cluster.local
   Description . . . . . . . . . . . : Hyper-V Virtual Ethernet Adapter #3
   Physical Address. . . . . . . . . : 00-15-5D-7F-01-7E
   DHCP Enabled. . . . . . . . . . . : No
   Autoconfiguration Enabled . . . . : Yes
   Link-local IPv6 Address . . . . . : fe80::290e:e522:63b:563b%26(Preferred)
   IPv4 Address. . . . . . . . . . . : 10.12.40.115(Preferred)
   Subnet Mask . . . . . . . . . . . : 255.255.255.128
   Default Gateway . . . . . . . . . : 10.12.40.1
   DNS Servers . . . . . . . . . . . : 172.20.0.10
   NetBIOS over Tcpip. . . . . . . . : Disabled
   Connection-specific DNS Suffix Search List :
                                       green.svc.cluster.local
                                       svc.cluster.local
                                       cluster.local
```
Services:
```
PS U:\cont\customer> kubectl.exe get svc -n green
NAME        TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)                       AGE
ae-tomcat   ClusterIP   None            <none>        80/TCP,8085/TCP,6009/TCP      2d21h
nginx       NodePort    172.20.95.214   <none>        80:30070/TCP,8085:30071/TCP   2d21h
slm         ClusterIP   None            <none>        27000/TCP                     2d21h
```

All Steps:
```
- Created an EKS cluster using eksctl, using one managed linux node and one unmanaged Windows 1909 Server Core node.
- Deployed Kubernetes Dashboard and some pods for the application I work on.
- Deployed Calico from my controlling EC2 instance and checked that the pods were all running successfully:
           wget https://raw.githubusercontent.com/aws/amazon-vpc-cni-k8s/v1.7.3/config/v1.7/calico.yaml -o calico.yaml
           kubectl.exe apply -f .\calico.yaml
```
- Remoted into the Windows node and ran the following commands in an elevated PowerShell window:
```
mkdir c:\k
cd k
curl -o kubectl.exe https://amazon-eks.s3.us-west-2.amazonaws.com/1.17.9/2020-08-04/bin/windows/amd64/kubectl.exe
Invoke-WebRequest https://docs.projectcalico.org/scripts/install-calico-windows.ps1 -OutFile c:\install-calico-windows.ps1
c:\install-calico-windows.ps1 -ServiceCidr 172.20.0.0/16 -DNSServerIPs 172.20.0.10
Get-Service -Name CalicoNode
Get-Service -Name CalicoFelix
```

**Comment by dave-meier** [comment]
Windows Calico log files and the config.ps1 file: [calico-logs-plus-config-script.zip](https://github.com/projectcalico/calico/files/5318806/calico-logs-plus-config-script.zip)

**Comment by dave-meier** [comment]
Calico-node and Calico-typha linux pod logs: [calico-linux-pod-logs.zip](https://github.com/projectcalico/calico/files/5318859/calico-linux-pod-logs.zip)

**Comment by dave-meier** [comment]
Looking for any ideas of what to check. I'm not sure where to look since I didn't notice an obvious error. If anyone has experience with these kind of problems, please look through the attached logs files. Thanks!

**Comment by lmm** [comment]
Sorry for the delay @dave-meier . I took a quick look in the calico-felix.log and there's a line indicating there might be policy applying to these workloads:

> 2020-10-02 14:45:10.956 [INFO][7140] felix/calc_graph.go 411: Local endpoint updated id=WorkloadEndpoint(node=ip-10-12-40-102.us-west-2.compute.internal, orchestrator=k8s, workload=green/ae-tomcat-6db96d9fc9-glhgd, name=eth0)
> 2020-10-02 14:45:10.956 [INFO][7140] felix/win_dataplane.go 248: Received *proto.WorkloadEndpointUpdate update from calculation graph msg=id:<orchestrator_id:"k8s" workload_id:"green/ae-tomcat-6db96d9fc9-glhgd" endpoint_id:"eth0" > endpoint:<state:"active" name:"calid896d1a7c35" profile_ids:"kns.green" profile_ids:"ksa.green.default" ipv4_nets:"10.12.40.119/32" tiers:<name:"default" ingress_policies:"green/knp.default.default-deny" egress_policies:"green/knp.default.default-deny" > > 
> 2020-10-02 14:45:10.956 [INFO][7140] felix/endpoint_mgr.go 130: Processing WorkloadEndpointUpdate workloadEndpointId=orchestrator_id:"k8s" workload_id:"green/ae-tomcat-6db96d9fc9-glhgd" endpoint_id:"eth0" 

This is the last update to that endpoint in the log. Were your tests done after the policy was removed? If you did the tests after the policy was removed, then for some reason that wasn't processed on the Windows node.

**Comment by dave-meier** [comment]
Thanks @lmm for taking a look! 

I see what you mean. This may have been a faulty assumption on my part that the policy would go away when I restarted calico pods, but the policy would still be there in the cluster. When I had the last issue, and no traffic was denied, I was experimenting with the following policies. I don't see the "access-green" policy in the log, but perhaps I was experimenting just with default-deny by itself at one point. I could have sworn I was listing the policies with kubectl and seeing none, but maybe there was operator error in there!

```
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: default-deny
  namespace: green
spec:
  podSelector:

---

kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: access-green
  namespace: green
spec:
  podSelector:
    matchLabels:
      environment: green
  ingress:
    - from:
      - podSelector:
          matchLabels:
            environment: green
```

I will recreate the test cluster I was using and try it again, and then apply the following policy, which I'm assuming with only deny traffic from other namespaces to the green namespace:
```
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  namespace: green
  name: deny-traffic-other-namespaces
spec:
  podSelector:
    matchLabels:
  ingress:
  - from:
    - podSelector: {}
```

**Comment by dave-meier** [comment]
Not reproducible.
