### ISSUE TITLE
Issue with basic policy allowing ingress traffic from nginx nodes in another namespace.

### ISSUE THREAD

**Issue by JRolfe-Gen** [projectcalico/calico#4049]
## Expected Behavior
Pods in webserver namespace allow traffic in from nginx-ingress namespace

## Current Behavior
The policy works if I just open the ingress port. However, if I restrict the policy to only accept traffic from certain namespace or pods within that namespace, I receive a 504 error when making the request.

## Steps to Reproduce (for bugs)
nginx-ingress namespace has label service=nginx-ingress
webserver pods are in webservers namespace with labels:
  app.kubernetes.io/instance=test
  app.kubernetes.io/name=webserver
If I apply this policy it does not work:
[netpol.txt](https://github.com/projectcalico/calico/files/5320229/netpol.txt)
If I apply this policy it works fine.
[netpol-work.txt](https://github.com/projectcalico/calico/files/5320236/netpol-work.txt)

## Your Environment
Azure AKS - basic install.
* Calico version 3.8
* Orchestrator version (e.g. kubernetes, mesos, rkt): 1.16.13
* Operating System and version: Ubuntu 16.04

I couldn't find anything that said I had to do something specific to configure Calico - basically a base configuration was applied by AKS when you create the instance.

**Comment by mgleung** [comment]
Hi @JRolfe-Gen, I think the issue here is that the value of your `namespaceSelector` uses `matchLabels` which I do not think we currently have support for. Can you try `namespaceSelector: service == 'nginx-ingress'` instead and see if that works?
