### ISSUE TITLE
Connectivity issue with jumbo Frames 

### ISSUE THREAD

**Issue by elgamal2020** [projectcalico/calico#4057]
Hello,
I have seen a strange problem that happens to some of my pods
The K8s cluster is implemented over VMs installed on openstack based IAAS
when the pod scheduled it got ip assinged , but I cant ping it from the node or from anywhere else while itself it can ping others
Note the node has jumpo frame of 9000 while calico is lest to default of 1500

```

sudo calicoctl get workloadendpoints -n brb11
NAMESPACE   WORKLOAD                                               NODE            NETWORKS           INTERFACE
brb11        brb-brb-n11-brb-775dd6b5b-ks4xg                        brb5       10.233.106.33/32   caliacd53cdac51
```
From the pod it self
```
ip a s
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
3: eth0@if1030: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default
    link/ether 2a:a0:f3:48:82:25 brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet 10.233.106.33/32 brd 10.233.106.33 scope global eth0
       valid_lft forever preferred_lft forever
4: eth1@eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 9000 qdisc noqueue state UNKNOWN group default
    link/ether fa:16:3e:1c:26:cf brd ff:ff:ff:ff:ff:ff
    inet 192.168.53.12/28 brd 192.168.53.15 scope global eth1
       valid_lft forever preferred_lft forever
``````

the pod can reach other objects on both interfaces
```
traceroute 10.233.118.18
traceroute to 10.233.118.18 (10.233.118.18), 30 hops max, 60 byte packets
 1  brb-brb-n11-brb-775dd6b5b-ks4xg (10.233.106.33)  3051.982 ms !H  3051.957 ms !H  3051.950 ms !H
```
```
but noway to reach both interfaces of the pod , like a unidirectional communication
No Network policy has been applied , how can I troubleshoot it further ?
A normal system reboot dont solve the problem , while restaritng the Calico pod on the worker or a  hard reset from openstack solves it
Thanks a lot

**Comment by elgamal2020** [comment]
Could you please provide more details to troubleshoot it further ?

**Comment by caseydavenport** [comment]
> ut I cant ping it from the node or from anywhere else while itself it can ping others
Note the node has jumpo frame of 9000 while calico is lest to default of 1500

You can change Calico's MTU setting to match the network using the `veth_mtu` field in the config map and restarting your pods. That might help. I'm not sure it's really MTU related though, especially since ping isn't going to send such a large packet by default. 

if the node itself is having trouble reaching the pod, that usually suggests an ARP issue. does your node have a default route?
