### ISSUE TITLE
namespaceSelector does not work

### ISSUE THREAD

**Issue by imalandu** [projectcalico/calico#4092]
## Expected Behavior
Pod can communicate across namespaces

## Current Behavior
Pod cannot communicate across namespaces

## Steps to Reproduce (for bugs)

I have two namespaces with the label "appGroup=system": gloo-system and kube-system. In these two namespaces, there are pods labeled "appEnv=core". When I apply the following GNP, the pod cannot Cross-namespace communication
```---
apiVersion: projectcalico.org/v3
kind: GlobalNetworkPolicy
metadata:
  name: allow-core-system-host-pod
spec:
  ingress:
  - action: Allow
    source:
      selector: appEnv in {'core'}
      namespaceSelector: appGroup in {'system'}
  order: 80
  namespaceSelector: appGroup in {'system'}
  selector: appEnv in {'core'}
  types:
  - Ingress
```

```---
apiVersion: projectcalico.org/v3
kind: GlobalNetworkPolicy
metadata:
  name: default-deny
spec:
  egress:
  - action: Allow
    destination: {}
    source: {}
  ingress:
  - action: Deny
    destination: {}
    source: {}
  order: 100
  selector: all()
  types:
  - Ingress
  - Egress
```
```
kubectl get ns -l 'appGroup=system' --show-labels
NAME              STATUS   AGE   LABELS
gloo-system       Active   22h   app=gloo,appGroup=system
kube-system       Active   32d   appGroup=system
```
```
kubectl describe  pod -n kube-system coredns-69d9b6c494-84rtf
Name:                 coredns-69d9b6c494-84rtf
Namespace:            kube-system
Priority:             2000000000
Priority Class Name:  system-cluster-critical
Node:                 node3.core.ptcloud.t.home/172.16.42.6
Start Time:           Thu, 15 Oct 2020 03:35:16 +0800
Labels:               appEnv=core
                      k8s-app=kube-dns
                      pod-template-hash=69d9b6c494
Annotations:          kubernetes.io/psp: default
Status:               Running
```
```
kubectl describe pod -n gloo-system gloo-7b5df4bf9b-sbktv
Name:         gloo-7b5df4bf9b-sbktv
Namespace:    gloo-system
Priority:     0
Node:         node3.core.ptcloud.t.home/172.16.42.6
Start Time:   Thu, 15 Oct 2020 03:38:05 +0800
Labels:       appEnv=core
              gloo=gloo
              pod-template-hash=7b5df4bf9b
Annotations:  kubernetes.io/psp: default
              prometheus.io/path: /metrics
              prometheus.io/port: 9091
              prometheus.io/scrape: true
Status:       Running
```

## Context

Is there something wrong with me?
Is there any error in the information in the [official document](https://docs.projectcalico.org/security/namespace-policy#use-kubernetes-rbac-to-control-namespace-label-assignment)?
Please help me.thx

## Your Environment

* Calico version: v3.16.3
* Orchestrator version (e.g. kubernetes, mesos, rkt): kubernetes 1.19
* Operating System and version: CentOS 8
* Link to your project (optional):

**Comment by mgleung** [comment]
Hi @imalandu , I just took a crack at replicating your issue with the policies you've provided in a clean cluster and was able to see connectivity between the pods with namespaces set up similar to yours. Wanted to quickly ask if there were any other policies (`GlobalNetworkPolicy` or `NetworkPolicy`) in your system that might be interfering with these workloads?

**Comment by caseydavenport** [comment]
Going to close as not reproducible.
