### ISSUE TITLE
UDP redirection changes source port when passing packet to pod.

### ISSUE THREAD

**Issue by bkahveci** [projectcalico/calico#4093]
We are using Calico under Canal with Rancher environment. We serve a video through RTSP and we want to serve the video specifically on UDP instead of TCP. We recently updated our Rancher and Calico version bumped from 3.4.0 to 3.13.4. This caused a change in UDP redirection. When NodePort is used, source port is changed in redirection.

## Expected Behavior

Incoming UDP packets should be redirected from same source port. Pseudo tcpdump output:

> client.23020 > host1.30610: UDP, length 12
> host1.23020 > pod.30610: UDP, length 12
> client.23021 > host1.30611: UDP, length 8
> host1.23021 > pod.30611: UDP, length 8

This was the behaviour with 3.4.0.

## Current Behavior

Intermediate redirection uses random ports.

> client.23020 > host1.30610: UDP, length 12
> host1.(any random port) > pod.30610: UDP, length 12
> client.23021 > host1.30611: UDP, length 8
> host1.(any random port-2) > pod.30611: UDP, length 8

This is the new behaviour in version 3.13.4.

## Possible Solution

We think there should be configuration option that changes this behaviour but we were unable to find such option.

## Steps to Reproduce (for bugs)

1. Create a deployment with UDP NodePort under rancher.
2. Publish a udp stream to this port.
3. Run tcpdump on host machine and see output.

## Context

Packets coming into RTCP should come from same port as reported in RTSP request. For example, if client reported they would use ports 23020 and 23021 for RTP and RTCP, packets should come from these ports. If this does not happen, client gives UDP timeout and tries to get the stream through TCP

## Your Environment

* Calico version: **3.13.4**
* Orchestrator version (e.g. kubernetes, mesos, rkt): **Kubernetes 1.18.6**
* Operating System and version: **CentOS 7.6.1810**
* Link to your project (optional):

**Comment by caseydavenport** [comment]
Interesting - I'm not aware of any changes to Calico that would have caused such a change in behavior. My understanding is that the rules Calico programs will attempt to maintain the original source port, but that it is not always possible.

For example, if you have two clients accessing the same pod via the NodePort using the same source port, one of them will _need_ to be modified in order to properly track the connection, otherwise the two connections will appear to be the same after the NAT. Does that makes sense?

I'm not sure if that is what you're seeing here, but I think independent of that there will always be a chance that the source port changes when going through a NodePort. 

you might want to consider using `externalTrafficPolicy: Local` on your services to prevent the SNAT from occurring at all, so that original lP and port can be maintained. 

CC @fasaxc in case he knows something I don't!

**Comment by bkahveci** [comment]
Actually we had only one client accessing to the server at that moment. So, your first guess is not valid in our situation. But changing externalTrafficPolicy: Local gave us a hint. When we did this, we managed to watch the stream but our external incoming traffic started to act like HostPort (only directed to the host the pod is running on), with the same source port. And in the old versions, nodeport was configured as externalTrafficPolicy: Cluster. So, we are going to focus our research on NodePorts specifically. in the meantime I am keeping this issue open because problem is not solved completely.

**Comment by fasaxc** [comment]
Canal is flannel networking + calico policy.  Are you in a position to try Calico networking instead?  With Calico, you can control whether we set the `--random-fully` setting on the SNAT rule, which may help.  Or, you could try our eBPF dataplane, which preserves source IP in all cases.  Hard to help you with flannel, the project lost a lot of momentum after CoreOS was acquired so there aren't many people working on it any more.

**Comment by bkahveci** [comment]
Actually I am working on an old version of both kernal (3.10) and calico(3.13.4) which makes both your suggestions impossible for me. The setting came with 3.16 and eBPF came with kernel 5.x. So, any other suggestion? :) Because I just want to maintain the earlier behaviour

**Comment by fasaxc** [comment]
Did you also upgrade `kube-proxy`, `kube-proxy` has a similar option?

Why not upgrade your OS.  It's fun :-)

**Comment by fasaxc** [comment]
Looks like --random-fully was added in the flannel 0.11 https://github.com/coreos/flannel/commit/0d7b99460b81f98df43da183258edf56c4abf854

**Comment by bkahveci** [comment]
> Did you also upgrade `kube-proxy`, `kube-proxy` has a similar option?

Which option are you referring to?

> Why not upgrade your OS. It's fun :-)

This is a nearly completed project. I will suggest updating but configuration would be less pain of course.

> Looks like --random-fully was added in the flannel 0.11 [coreos/flannel@0d7b994](https://github.com/coreos/flannel/commit/0d7b99460b81f98df43da183258edf56c4abf854)

Yes, that is the problem. It is not configurable. If iptables supports it, flannel just uses random-fully.

**Comment by fasaxc** [comment]
kube-proxy also adds masquerade rules and it also uses random-fully if available.  Traffic from outside the cluster would normally be masqueraded by kube-proxy, not the CNI plugin.

**Comment by fasaxc** [comment]
Why don't you check which rule is masquerading your traffic in iptables? 
```
iptables-save -t nat -c | grep -e SNAT -e MASQ
```
should show the rule counts on the relevant rules.

**Comment by bkahveci** [comment]
> Why don't you check which rule is masquerading your traffic in iptables?
> 
> ```
> iptables-save -t nat -c | grep -e SNAT -e MASQ
> ```
> 
> should show the rule counts on the relevant rules.

I think we are getting closer. It gave extra rule

```
[0:0] -A KUBE-SEP-<hash> -s 10.42.0.70/32 -m comment --comment "<namespace>/<pod name>-nodeport:<portname>" -j KUBE-MASK-MASQ
```

for each nodeport in new configuration. I still have one Rancher cluster with older versions and this is the only difference in iptables output. There are also 

```
[x:y different than 0] -A KUBE-NODEPORTS -p udp -m comment --comment "<namespace>/<pod name>-nodeport:<portname>" -m udp --dport <port> -j KUBE-MARK-MASQ
[0:0] -A KUBE-SERVICES ! -s 10.42.0.0/16 -d <pod ip> -p udp -m comment --comment  "<namespace>/<pod name>-nodeport:<portname> cluster IP" -m udp --dport <port> -j KUBE-MARK-MASQ
```

in both clusters.

**Comment by fasaxc** [comment]
Those rules only mark the packet for masquerade, what about the rule that actually does the masquerading?

**Comment by bkahveci** [comment]
Those were the only rules that the command gave. I traced the packets and also seen another mark **0x10000** rule in chain **cali-pri-kns.default** different than older version. Is this something relative?

**Comment by bkahveci** [comment]
I think I have found the rule.

```
KUBE-POSTROUTING -m comment --comment "kubernetes service traffic requiring SNAT" -j MASQUERADE
```

**Comment by bkahveci** [comment]
And I found a possibly relative issue in stackoverflow. https://stackoverflow.com/questions/48059269/how-to-avoid-snat-when-using-service-type-clusterip-on-kubernetes.  It says:

> The kube-proxy cluster-cidr needs to match the one used on the controller manager, also the one used by calico.

How can I check the relative cidr's?

**Comment by caseydavenport** [comment]
> How can I check the relative cidr's?

These depend on how you have installed those components. They can either be command-line arguments to those components, or set via a configuration file passed to those components.

**Comment by bkahveci** [comment]
After a long day I found another problem. Calico gives warning

> Failed to query VXLAN device error=Link not found

and I found a possible solution but cannot really understand how to do this in calico or flannel. I tried to create the file in worker node but did not work. https://github.com/rancher/rke/issues/2270#issuecomment-710435248

**Comment by fasaxc** [comment]
> Failed to query VXLAN device error=Link not found

Seeing that error once or twice is expected.  It should stop once the device is created.

**Comment by bkahveci** [comment]
> > Failed to query VXLAN device error=Link not found
> 
> Seeing that error once or twice is expected. It should stop once the device is created.

It is persistent on every redeploy.

**Comment by fasaxc** [comment]
How many times do you see that log in one instance of calico-node?

**Comment by bkahveci** [comment]
Thanks for replying so fast. I only see it once but I am using calico over Rancher and kubernetes by the way. But it happens every time. Frankly, my main problem is port redirection as I mentioned. And with iptables TRACE rules today I have seen packets go directly to cali... instead of flannel1, which was the behaviour with older version. So I thought maybe flannel is not working in canal and when I saw this message I thought flannel is somehow not working but I am not sure.

**Comment by fasaxc** [comment]
@bkahveci FYI, the VXLAN warning is suppresed in v3.16.

**Comment by realgaurav** [comment]
Hi @bkahveci -- Can you try using the latest Calico? Calico v3.13 is an older release at this point.
