### ISSUE TITLE
Replace references to  "calico-containers" with "calicoctl"

### ISSUE THREAD

**Issue by caseydavenport** [projectcalico/calico#410]
github.com/projectcalico/calico-containers has been renamed to github.com/projectcalico/calicoctl. We should update references to it in the docs.

**Comment by djosborne** [comment]
Seems the repository rename has already occured, so this is now just a matter of updating the string in the docs.

**Comment by djosborne** [comment]
Why was this closed? Docs still include references to `calico-containers/releases/`:
such as https://github.com/projectcalico/calico/blob/master/v2.0/getting-started/docker/installation/manual.md#using-calicoctl

**Comment by caseydavenport** [comment]
Huh... not sure how that got through.

**Comment by djosborne** [comment]
I think we do want to fix these links on past releases as well...

**Comment by tomdee** [comment]
Ooops, this isn't a 2.1 issue - removing from milestone.

**Comment by djosborne** [comment]
All references to calico-containers have been removed from v2.0, v2.1, and master.
