### ISSUE TITLE
BGP listen port is not changed. (calico v3.16.3)

### ISSUE THREAD

**Issue by suiny** [projectcalico/calico#4103]
This issue is what I asked on slack and is related to #4098 
https://calicousers.slack.com/archives/CPTH1KS00/p1602833003052900

1. Calico has been updated to version 3.16.3
```
[root@master ~]# docker images|grep calico
calico/node                                        v3.16.3             f0d3b0d0e32c        6 days ago          164MB
calico/pod2daemon-flexvol                          v3.16.3             a0b97353aa18        6 days ago          22.9MB
calico/cni                                         v3.16.3             fe49caa20c30        6 days ago          133MB
[root@master ~]# calicoctl version
Client Version:    v3.16.3
Git commit:        7d066703
Cluster Version:   v3.15.2
Cluster Type:      kubespray,bgp,kubeadm,k8s
```
1. And I wanted to apply the BGP port change spec, but it didn't apply even after restarting the callico-node pod.
```
[root@master ~]# calicoctl get BGPConfiguration default -o yaml --export
apiVersion: projectcalico.org/v3
kind: BGPConfiguration
metadata:
  creationTimestamp: "2020-09-09T10:08:42Z"
  name: default
  resourceVersion: "11573515"
  uid: 0ef5e0ef-db19-4afa-a906-1a7c95d7aaab
spec:
  asNumber: 64512
  listenPort: 11178
  logSeverityScreen: Info
  nodeToNodeMeshEnabled: true
[root@master ~]# ps -ef|grep bird
root      53074  53022  0 17:36 ?        00:00:00 runsv bird6
root      53075  53022  0 17:36 ?        00:00:00 runsv bird
root      53214  53074  0 17:36 ?        00:00:00 bird6 -R -s /var/run/calico/bird6.ctl -d -c /etc/calico/confd/config/bird6.cfg
root      53215  53075  0 17:36 ?        00:00:00 bird -R -s /var/run/calico/bird.ctl -d -c /etc/calico/confd/config/bird.cfg
root      60956  55828  0 17:43 pts/0    00:00:00 grep --color=auto bird
[root@master ~]# netstat -nap |grep LISTEN|grep bird
tcp        0      0 0.0.0.0:179             0.0.0.0:*               LISTEN      53215/bird          
unix  2      [ ACC ]     STREAM     LISTENING     228609567 53215/bird           /var/run/calico/bird.ctl
unix  2      [ ACC ]     STREAM     LISTENING     228610782 53214/bird6          /var/run/calico/bird6.ctl
```

So I tried to apply it manually, but it didn't work either.
```
[root@worker /]# echo 'listen bgp port 11179' >> /etc/calico/confd/config/bird.cfg
[root@worker /]# grep 11179 /etc/calico/confd/config/bird.cfg
listen bgp port 11179
[root@worker /]# sv hup bird
[root@worker /]# exit
exit
command terminated with exit code 127
[root@master ~]# netstat -nap|grep LISTEN|grep bird
tcp        0      0 0.0.0.0:179             0.0.0.0:*               LISTEN      121692/bird    
```

## Expected Behavior
Change BGP listen port. (179->11179)

## Current Behavior
BGP listen port is not changed.

**Comment by suiny** [comment]
Anyone can answer? :(

**Comment by song-jiang** [comment]
@neiljerram Could you look into this?

**Comment by neiljerram** [comment]
@song-jiang @suiny Sure, I've started to take a look.  Please be patient though, as I don't see a really obvious cause here!

**Comment by neiljerram** [comment]
@suiny Sorry for such a long hiatus.  Is this issue still live for you?

> So I tried to apply it manually, but it didn't work either.

I think you need a semicolon at the end of `listen bgp port 11179`.

Recommend `birdcl configure`, instead of `sv hup bird`, as `birdcl` will tell you if the new configuration is valid.

> calicoctl get BGPConfiguration default

When you use BGPConfiguration to set the listen port, can you use `cat /etc/calico/confd/config/bird.cfg` to show us the BIRD config that you have?

**Comment by suiny** [comment]
I checked that changes bgpport (179->11179) as the yaml file on the v3.18.4 version.

**Comment by neiljerram** [comment]
@suiny Thanks.  Reviewing this whole issue, I have a guess at the problem.

> [root@master ~]# calicoctl version
> Client Version:    v3.16.3
> Git commit:        7d066703
> Cluster Version:   v3.15.2
> Cluster Type:      kubespray,bgp,kubeadm,k8s

Note `v3.15.2` - It looks like you haven't actually upgraded the running Calico components on each node.  That would explain why the BGP port configuration was not reflected in your bird.cfg (until you added it manually).

**Comment by suiny** [comment]
That's strange.
I upgraded calico to 3.16.3 but it was not reflected.  (follow this [link](https://docs.projectcalico.org/maintenance/kubernetes-upgrade#upgrading-an-installation-that-uses-an-etcd-datastore))
However, the image was used as 3.16.3.
```
[root@master ~]# calicoctl version
Client Version:    v3.16.3
Git commit:        7d066703
Cluster Version:   v3.15.2
Cluster Type:      kubespray,bgp,kubeadm,k8s
[root@master ~]# docker images |grep calico
calico/node                                        v3.16.3             f0d3b0d0e32c        8 months ago        164MB
calico/pod2daemon-flexvol                          v3.16.3             a0b97353aa18        8 months ago        22.9MB
calico/cni                                         v3.16.3             fe49caa20c30        8 months ago        133MB
```

**Comment by neiljerram** [comment]
The docker image might not be same as what the Kubernetes runtime has available, or is actually using.  What do you get for `kubectl get ds calico-node -n calico-system -o yaml | grep image:` ?  (Or you might need `kube-system` instead of `calico-system`.)

**Comment by suiny** [comment]
@neiljerram 

I used same image (v3.16.3)
```
[root@dev-suinyk8s001-ncl ~]# kubectl get pods -n kube-system calico-node-89pm4 -oyaml | grep image:
            f:image: {}
            f:image: {}
            f:image: {}
            f:image: {}
    image: calico/node:v3.16.3
    image: calico/cni:v3.16.3
    image: calico/cni:v3.16.3
  - image: calico/pod2daemon-flexvol:v3.16.3
    image: calico/node:v3.16.3
    image: calico/cni:v3.16.3
    image: calico/cni:v3.16.3
    image: calico/pod2daemon-flexvol:v3.16.3
```

**Comment by neiljerram** [comment]
Looks good, thanks.  Did you change that just now, or has it been like that for a long time?

**Comment by suiny** [comment]
It's been like that for a long time.
The bgport did't change when using v3.16.3 version's image, and I think that it was a bug.
I recently created a new cluster with v3.18.4 , the bgp port changed.
It's goot that the bug is resolved.
