### ISSUE TITLE
Policy-controller // object of type 'NoneType' has no len()

### ISSUE THREAD

**Issue by valentin2105** [projectcalico/calico#411]
Hi,

I trying to deploy Calico in my Kubernetes cluster on v1.5.1.

I create `calico.yaml` after deleting all etcd_certs references (I use a dedicated no-secure ETCD). 

Everything run fine, But The Network Policy doesn't work (no effect) and I go this in the Calico-Policy-Controller logs : 

```
2016-12-19 04:44:49,752 5 INFO Syncing 'NetworkPolicy' objects
2016-12-19 04:44:49,755 5 ERROR Unahandled exception killed NetworkPolicy manager
Traceback (most recent call last):
  File "<string>", line 304, in _manage_resource
  File "<string>", line 409, in _sync_resources
TypeError: object of type 'NoneType' has no len()
2016-12-19 04:44:49,755 5 WARNING Re-starting watch on resource: NetworkPolicy
```

Any idea where I go wrong ? 

I can post my calico.yaml if needed.

**Comment by caseydavenport** [comment]
@valentin2105 thanks for raising.  Just took a look at this and it appears to be benign - it shouldn't be causing any problems.

If policy isn't working can you verify that the Calico CNI plugin is actually being called?  A few things: 

- The kubelet needs to have `--network-plugin=cni` passed to it.
- If you're running the kubelet as a container, it needs to have the correct dirs mounted in as per http://docs.projectcalico.org/v2.0/getting-started/kubernetes/troubleshooting
- Can you see if there are any workload endpoints created.  You can check with `calicoctl get workloadendpoint`

**Comment by valentin2105** [comment]
Hi @caseydavenport 

I finally get it working using calico-node Docker image and calico-policy-controller in Kubernetes. 

Just two small questions :

- The `calicoctl get node` command is for list peered Kubernetes nodes ? 

- How I define the IP ranges for my pods ? 


Thanks for this awesome tool, tired of Kubenet. :p

**Comment by caseydavenport** [comment]
@valentin2105 glad you got it working :)

`calicoctl get node` will return a list of nodes that Calico is running on and the information Calico knows about them.

You can change the IP ranges for your pods by changing Calico IP pools.  See here: http://docs.projectcalico.org/v2.0/reference/calicoctl/resources/ippool
