### ISSUE TITLE
multiple subnet set up bare metal

### ISSUE THREAD

**Issue by mseewooth** [projectcalico/calico#4125]
Hello, 

I need to setup a kubernetes cluster on bare metal with calico as networking. 

For e.g i will have two subnets  192.168.200.xx and 192.168.150.xx . i'm assuming to have many workers nodes for production environment and they'll use BGP.

Do i have to take into consideration the BGP enabled network devices (router, switchs ) that interconnects the two subnets for calico BGP to work properly? 

If i will need to have routers/swtich that supports BGP and enabled. Is there a configuration in the router to be done so that BGP works ? 

Thank you very much for help.

**Comment by fasaxc** [comment]
> Do i have to take into consideration the BGP enabled network devices (router, switchs ) that interconnects the two subnets for calico BGP to work properly?

> If i will need to have routers/swtich that supports BGP and enabled. Is there a configuration in the router to be done so that BGP works ?

You have two choices; either you peer with the fabrid by configuring BGPPeer resources on the Calico side and by configuring your routers.  Or, you use Calico's overlay modes to bridge the two subnets.  The latter is the default but he former gives better performance.

This free training session might be of interest: https://www.tigera.io/event/getting-up-and-running-with-calico-on-your-on-prem-k8s-cluster-2/ along with this general guide: https://docs.projectcalico.org/about/about-networking
