### ISSUE TITLE
Pods connected to Calico IPPool with NAT not connecting from Node IP

### ISSUE THREAD

**Issue by recrudesce** [projectcalico/calico#4138]
I have a Raspberry Pi K8S cluster, 1 master (192.168.86.150) and 2 nodes (192.168.86.152 and 153).  I also have another Pi acting as an NFS server (192.168.86.160). I have Calico configured, and I used `calicoctl` to see if it had NAT enabled, which it does.

However, any outgoing traffic from a pod to my local network appears to come from the Pod IP, not the node IP, which means nothing can route back in.

Bit more info: my local subnet (as in everything on my home network) is 192.168.86.0/24 provided by DHCP on my Google Wifi router.

This is my Calico IPPool config

```
{
  "kind": "IPPoolList",
  "apiVersion": "projectcalico.org/v3",
  "metadata": {
    "resourceVersion": "11027205"
  },
  "items": [
    {
      "kind": "IPPool",
      "apiVersion": "projectcalico.org/v3",
      "metadata": {
        "name": "default-ipv4-ippool",
        "uid": "7f876465-0c94-4087-b567-8b12171421aa",
        "resourceVersion": "2336",
        "creationTimestamp": "2020-09-15T17:13:01Z"
      },
      "spec": {
        "cidr": "192.168.0.0/16",
        "vxlanMode": "Never",
        "ipipMode": "Always",
        "natOutgoing": true,
        "blockSize": 26,
        "nodeSelector": "all()"
      }
    }
  ]
}

```

My nodes have chosen 192.168.185.0/24 and 192.168.244.0/24 for the pod networks.

When I do a connection test from a pod to a server on my local network, this is what I see in tcpdump

`13:29:05.294836 IP 192.168.185.244.32866 > k8snfs.9000: Flags [S], seq 4185311275, win 64400, options [mss 1400,sackOK,TS val 3431307964 ecr 0,nop,wscale 7], length 0`

Note how it's connected from the Pod IP, and not a NAT IP (which I assume would be the node's IP ?) Because the server it connected to doesn't know how to route back to 192.168.185.0/24, it just fails the connection, which makes total sense.

What have I missed ? What can I check ? I'm pretty new to K8S, so a bit of guidance would be greatly appreciated :)

**Comment by recrudesce** [comment]
Update to this: I thought it might be caused by my K8S calico ippool kinda being in the same subnet, so I switched my whole environment to using 172.16.0.0/16 and recreated my test pods, but it still connects as the pod IP and not the NAT IP

`10:55:17.402626 IP 172.16.249.4.37082 > ubuntu-vm.lan.9000: Flags [S], seq 2636212639, win 64400, options [mss 1400,sackOK,TS val 136381942 ecr 0,nop,wscale 7], length 0`

Please help :(

**Comment by lwr20** [comment]
So to get NATed, the packet must be leaving the pod subnet.  I think what's wrong here is that the NFS server has an IP inside the pod-cidr, so Calico thinks that the traffic is pod-pod.

You need pod cidr, host cidr and service cidr to be non-overlapping to avoid issues.

**Comment by recrudesce** [comment]
Hey @lwr20 - thanks.  I experience the same issue even once I've changed the pod CIDR to 172.16.0.0/16 - all connections (as per my update) are being received from the pod IP, not the node IP :(

**Comment by lwr20** [comment]
Can I see the output of `ip r` on the node with the pod please?

BTW - I can also help you with this on slack - http://slack.projectcalico.org/ for an invite, I'm `lrobson` in there
