### ISSUE TITLE
calico-kube-controllers errors

### ISSUE THREAD

**Issue by kombiwagon** [projectcalico/calico#4140]
**Daily recurring errors in calico-kube-controllers: sometimes a few times a day sometimes a dozen or so**
[ERROR][1]main.go 234: Failed to reach apiserver error=<nil>
[ERROR][1]client.go 255: Error getting cluster information config ClusterInformation="default" error=Get https://10.43.0.1:443/apis/crd.projectcalico.org/v1/clusterinformations/default: context deadline exceeded
[ERROR][1] main.go 203: Failed to verify datastore error=Get https://10.43.0.1:443/apis/crd.projectcalico.org/v1/clusterinformations/default: context deadline exceeded

## Current Behavior
I noticed that when these errors show up my kube-scheduler and kube-controller-manager change leadership. 
Generally cluster works fine but this errors in calico pod and kube-scheduler and control-manager behaviour is disturbing
I can reach to apiserver from nodes:
telnet 10.43.0.1 443 succesfull
I dont se any errors in kube-proxy container

## Your Environment

* Calico version 3.13.4
*  RKE,  Kubernetes Version: v1.18.3 
*  centos 7
* Link to your project (optional):

**Comment by kombiwagon** [comment]
anyone can help?

**Comment by song-jiang** [comment]
@kombiwagon I suppose `10.43.0.1 443` is your `kubernetes` service. The error logs shows `calico-kube-controllers` failed to access kube-apiserver and in the mean time kube-scheduler and kube-controller-manager change leadership. To me it indicates somehow kube-apiserver is not accessible.  Could you fetch logs from `kube-scheduler` and `kube-controller-manager` to see if that is the case as well?

**Comment by kombiwagon** [comment]
Thank you for answer!!!, there are my logs:
Tell me if I should send more info, more logs. 

**kube-scheduler:**
I1026 05:25:23.053830       1 leaderelection.go:242] attempting to acquire leader lease  kube-system/kube-scheduler...
I1026 06:56:44.056955       1 leaderelection.go:252] successfully acquired lease kube-system/kube-scheduler
E1026 08:34:37.404893       1 leaderelection.go:320] error retrieving resource lock kube-system/kube-scheduler: Get https://127.0.0.1:6443/api/v1/namespaces/kube-system/endpoints/kube-scheduler?timeout=10s: context deadline exceeded (Client.Timeout exceeded while awaiting headers)
I1026 08:34:37.405205       1 leaderelection.go:277] failed to renew lease kube-system/kube-scheduler: timed out waiting for the condition
F1026 08:34:37.405307       1 server.go:244] leaderelection lost

**kube-controller-manager:**
I1026 08:34:19.396577       1 pv_controller.go:1285] isVolumeReleased[pvc-942c3781-4d64-4400-bef6-17245b952501]: volume is released
I1026 08:34:19.396578       1 pv_controller.go:1285] isVolumeReleased[pvc-ebbf754f-b75d-4db0-a36a-c9a841880978]: volume is released
I1026 08:34:34.395715       1 pv_controller.go:1285] isVolumeReleased[pvc-539338cb-c9d8-4a99-be6a-cd833c0d56ff]: volume is released
I1026 08:34:34.590594       1 pv_controller.go:1285] isVolumeReleased[pvc-942c3781-4d64-4400-bef6-17245b952501]: volume is released
E1026 08:34:38.631183       1 leaderelection.go:320] error retrieving resource lock kube-system/kube-controller-manager: Get https://127.0.0.1:6443/api/v1/namespaces/kube-system/endpoints/kube-controller-manager?timeout=10s: context deadline exceeded
I1026 08:34:38.631339       1 leaderelection.go:277] failed to renew lease kube-system/kube-controller-manager: timed out waiting for the condition
F1026 08:34:38.631871       1 controllermanager.go:279] leaderelection lost

**kube-apiserver: (|grep error)**
W1026 08:28:49.219395       1 watcher.go:199] watch chan error: etcdserver: mvcc: required revision has been compacted
W1026 08:31:03.911361       1 watcher.go:199] watch chan error: etcdserver: mvcc: required revision has been compacted
W1026 08:31:58.675621       1 watcher.go:199] watch chan error: etcdserver: mvcc: required revision has been compacted
E1026 08:34:39.673783       1 status.go:71] apiserver received an error that is not an metav1.Status: &errors.errorString{s:"context canceled"}
W1026 08:45:29.780252       1 watcher.go:199] watch chan error: etcdserver: mvcc: required revision has been compacted
W1026 08:46:51.233510       1 watcher.go:199] watch chan error: etcdserver: mvcc: required revision has been compacted
W1026 08:48:25.266265       1 watcher.go:199] watch chan error: etcdserver: mvcc: required revision has been compacted

**Comment by song-jiang** [comment]
NP. You can see when `kube-apiserver` outputed error log 
```
E1026 08:34:39.673783 1 status.go:71] apiserver received an error that is not an metav1.Status: &errors.errorString{s:"context canceled"}
```
, at the exact same time, there were error logs from `kube-scheduler` and `kube-controller-manager`.
```
E1026 08:34:37.404893 1 leaderelection.go:320] error retrieving resource lock kube-system/kube-scheduler: Get https://127.0.0.1:6443/api/v1/namespaces/kube-system/endpoints/kube-scheduler?timeout=10s: context deadline exceeded 
```

It could be an kube-apiserver/etcd issue ( https://github.com/kubernetes/kubernetes/issues/92460 ). At moment I don't think it is related to Calico.

**Comment by kombiwagon** [comment]
I have a lot of warnings in etcd: "took too long", and i know that my disc latencies are too long, for example fio test output is p99 > 40 ms.
So I guess that this api-server errors can be related with unstable etcd ... ?

**Comment by song-jiang** [comment]
Yeah. I think so. Once etcd problem get resolved, I believe Calico should behave normally. Will you close this issue?
