### ISSUE TITLE
Pod network is unavailable, and mac is not available

### ISSUE THREAD

**Issue by wangdwcsd** [projectcalico/calico#4144]
## Expected Behavior

Pod can access other pod or node，On the node, you can see the mac of the pod corresponding to the network card
![image](https://user-images.githubusercontent.com/28424375/98364514-e45fb880-206b-11eb-892e-82a819ac8382.png)

## Current Behavior

Pod can not  access other pod or node，On the node, you can not  see the mac of the pod corresponding to the network card
![image](https://user-images.githubusercontent.com/28424375/98364641-183ade00-206c-11eb-9460-36c506ce17d8.png)

## Possible Solution

Delete the pod and let the pod recreate

Has this problem been resolved in later versions of calico？

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Calico version   ：3.8.2
* kubernetes version (e.g. kubernetes, mesos, rkt):   1.17.8
* Operating System and version:  centos 7.6
* Link to your project (optional):

**Comment by wangdwcsd** [comment]
@BedivereZero

**Comment by lwr20** [comment]
I'm not sure I understand what the problem you're seeing is.

**Comment by wangdwcsd** [comment]
Pods on the same node can access each other,The pod on different nodes cannot be accessed.Not all pods are like this, only the pods on a node are like this.

I found that the Cali network card corresponding to the pod in question does not have a MAC address



After I upgraded calico to version 3.16.4, the problem disappeared
