### ISSUE TITLE
eBPF nodeport redirect or push to stack

### ISSUE THREAD

**Issue by firemiles** [projectcalico/calico#4157]
Hi guys, I read calico eBPF code have a question need help. 

When a packet visit nodeport arrived in host nic, if the endpoint is in other Node, the ingress TC eBPF program would redirect it to egress tc or push to network stack let kernel do forward? And also where do the packet snat operation, at ingress tc, iptables or egress tc. I could not found the picture to point these question, anyone can help me?

**Comment by mgleung** [comment]
@fasaxc would you know the answer to these questions?

**Comment by fasaxc** [comment]
You can find out more about our eBPF dataplane here: https://docs.projectcalico.org/about/about-ebpf

eBPF doesn't use SNAT, it uses VXLAN to forward node port traffic.  Hope that helps!
