### ISSUE TITLE
looks like keepOriginalNextHop attribute ignored

### ISSUE THREAD

**Issue by serg-ku** [projectcalico/calico#4164]
I have created bgpPeer resource with AS different from calico and "keepOriginalNextHop: true",
but as I can see calico announces all routes from all nodes with "next hop self", also bird.conf on calico nodes has no "next hop keep" in neighbor section for this peer.

## Expected Behavior
"next hop keep" added to this neighbor section in bird.conf

## Current Behavior
bird.conf on calico nodes has no "next hop keep" in neighbor section for this peer

## Possible Solution
/etc/calico/confd/templates/bird.cfg.template on nodes has this lines:
```
{{- if and (ne $data.as_num $node_as_num) ($data.keep_next_hop)}}
  next hop keep;
{{- end}}
```
I can't find out how to fetch data that confd uses to generate config, but I think $data.keep_next_hop is undefined or false.

## Steps to Reproduce (for bugs)
1. deploy latest calico
2. create bgpPeer with different AS and keepOriginalNextHop set to true
3. check bird.conf on nodes
4. check routes on created peer

## Context
I want upstream peer to directly route traffic to correct nodes.

## Your Environment
* Calico version: v3.16.5
* Orchestrator version (e.g. kubernetes, mesos, rkt): kubernetes v1.19.2
* Operating System and version: CentOS Linux release 7.8.2003

**Comment by neiljerram** [comment]
@serg-ku I think this may be addressed by https://github.com/projectcalico/confd/pull/358, in which case it should work in Calico v3.17 when that comes out (soon!).

Can you confirm if your BGPPeer had a `Node` or `NodeSelector` field?  If it didn't, it's what we call a "global" peering, and needs https://github.com/projectcalico/confd/pull/358.  If it did have one of those fields, it's "node-specific", and should have already supported keepOriginalNextHop following https://github.com/projectcalico/confd/pull/339.

**Comment by serg-ku** [comment]
@neiljerram it has no Node or NodeSelector, this is global peer, thank you!
I've somehow missed that issue.

**Comment by neiljerram** [comment]
Thanks @serg-ku !
