### ISSUE TITLE
Guidance needed: Kubernetes API servers in multiple regions

### ISSUE THREAD

**Issue by jlpnetworx** [projectcalico/calico#4177]
We are running a Kubernetes cluster with nodes in multiple "regions" (it doesn't really matter what that means). 
When a pod wants to reach the API server the random selection that is set up in iptables by calico choses any of them in any region. Is there a way to limit these requests to the same region only?

**Comment by caseydavenport** [comment]
@jlpnetworx Calico isn't actually responsible for making that decision - the kube-proxy programs those rules. 

You might want to look into Service Topology in Kubernetes - that might be able to accomplish what you're looking for!

https://kubernetes.io/docs/concepts/services-networking/service-topology/
