### ISSUE TITLE
ping failed to calico gateway for only some of pods

### ISSUE THREAD

**Issue by majorinche** [projectcalico/calico#4186]
calicoctl version
Client Version:    v3.13.2

k8s version: 1.17.9 

our k8s cluster has 6 nodes, two of them has problem that newly created pod can not ping calico gateway success

```
[root@d0506 ~]# ip r
0.0.0.0 via 172.18.163.254 dev bond0.1103 
10.1.11.0/24 dev bond0.112 proto kernel scope link src 10.1.11.70 metric 400 
10.2.11.0/24 dev bond0.212 proto kernel scope link src 10.2.11.70 metric 402 
blackhole 10.233.76.0/24 proto bird 
10.233.76.8 dev caliefb43993113 scope link 
10.233.76.20 dev calia25d96106e9 scope link 
10.233.76.28 dev cali64f4506fe5a scope link 
10.233.76.34 dev cali1c17579d552 scope link 
10.233.76.36 dev cali69deb0fd7bc scope link 
10.233.76.80 dev calib6f659f7b3d scope link 
10.233.76.85 dev cali658b68d3097 scope link 
10.233.76.89 dev calid510769e85f scope link 
```
like above ip address, some of them can ping successfully to gateway like 10.233.76.0, but new one can not

we tried check inside the pod about the route rule, it seems normal
```
[root@d0506 ~]# ip r
default via 169.254.1.1 dev eth0 
169.254.1.1 dev eth0 scope link 
```

it is so strange for us, any idea?
thank you

**Comment by majorinche** [comment]
update for this issue
1, we find the mac address did not learn successfully,like
ip neigh
169.254.1.1 dev eth0  _**FAILED**_

2, and container already sent arp request to cali7b530308a36, but did not receive any echo
13:33:17.060225 ARP, Request who-has 169.254.1.1 tell 10.233.76.201, length 28

3,after manually add mac like:
ip neigh replace 169.254.1.1 lladdr ee:ee:ee:ee:ee:ee dev eth0

4, then mac add success
[root@d0404 ~]# ip n
169.254.1.1 dev eth0 lladdr ee:ee:ee:ee:ee:ee REACHABLE

5, and finally network is ok, can ping success

so i'm curious about what happened about the cali7b530308a36, why it can not response to the arp request

**Comment by halfcrazy** [comment]
Is proxy_arp successful set for this interface? 
`cat /proc/sys/net/ipv4/conf/cali7b530308a36/proxy_arp`

**Comment by majorinche** [comment]
@halfcrazy 
[root@d0506 ~]# cat /proc/sys/net/ipv4/conf/calieabde1eea72/proxy_arp
1

the result is 1, seems successful

**Comment by caseydavenport** [comment]
> 13:33:17.060225 ARP, Request who-has 169.254.1.1 tell 10.233.76.201, length 28

Hm, normally if proxy_arp is enabled but you're not seeing responses, it's because the host doesn't think it can actually proxy ARP for that destination. However, it looks like your host _does_ have a default route, which should be enough to trigger proxy ARP for the pods.

What are you using for the following values in this cluster:

- Pod CIDR?
- Node CIDR?
- Service CIDR?

Another long-shot scenario is if your host has any local addresses that belong to pods. If so, then it might send the ARP reply _to itself_ instead of back to the pod. 

You can check `ip route show table local` to see if it thinks any of the pod addresses are local to the node.

**Comment by majorinche** [comment]
@caseydavenport 
thanks for you feedback.
sadly, my host doesn't have any default route, my route table shows like following
[root@d0506 ~]# ip r
0.0.0.0 via 172.18.163.254 dev bond0.1103 

0.0.0.0 is not a network, but a host address, only 0.0.0.0/0 is the default network, my bad.

**Comment by tungdam** [comment]
Hi
I'm currently facing the same issue. 
Our worker node does have default gw 
```
ip r s | grep default
default via 10.3.0.1 dev enp5s0f0 onlink
```

Our service  CIDR is 10.196.48.0/20
Pod CIDR: 10.198.0.0/15
Node: 10.3.4.0/24

proxy_arp is enabled in our cali interface:
```
cat /proc/sys/net/ipv4/conf/cali7741e48c6c1/proxy_arp
1
```
Same symptoms: inside pod
```
169.254.1.1 dev eth0  FAILED
```
Host doesn't reply to ARP request 

I'm using calico 3.5.2 

It's just happened recently  with newly created pods. 

Could anyone please show me any idea how to check further ? 

Thanks 
```
