### ISSUE TITLE
Daemonset pods IP addresses not released when node restarts

### ISSUE THREAD

**Issue by mbarecki** [projectcalico/calico#4190]
Hello, let me start with saying that Calico is an awesome product and majority of things are working great.  

Some issues were observed though with IP addresses of daemonsets pods not being released when node reboots.  

## Expected Behavior
Rebooting Kubernetes nodes should not increase amount of IP addresses used.

## Current Behavior  
Whenever we restart a node we observe daemonset pods getting assigned new ips  
after the reboot - but no cleanup of old addresses seem to occur.

## Questions:
- Are we doing node reboot incorrectly ?  
- Should IP used by daemonset pod be released from ipam when node is rebooted ?  
- Should new IP be allocated in ipam for daemonset pod after node reboot ?  

## Steps to Reproduce
In every cluster this happens every time when node is restarted.  

In the example below we have ippool called logging with a daemonset running.  
Only pods from one namespace are using that ippool.  

All the outputs have been shortened for readability.  

1. Verify state of ippool and reserved addresses:  
```console
$ calicoctl get ippool
NAME                  CIDR             SELECTOR                                 
logging               10.123.2.0/26     nonExistingLabel == "nonExistingValue"   
```

```console
$ calicoctl ipam show
+----------+----------------+-----------+------------+-----------+
| GROUPING |      CIDR      | IPS TOTAL | IPS IN USE | IPS FREE  |
+----------+----------------+-----------+------------+-----------+
| IP Pool  | 10.123.2.0/26   |        64 | 39 (61%)   | 25 (39%)  |
+----------+----------------+-----------+------------+-----------+
```

2. list pods running within logging ippool (daeamonset)
```console
$ kubectl -n logging get pods -o wide
NAME                      READY   STATUS    RESTARTS   AGE     IP           NODE        NOMINATED NODE   READINESS GATES
logging-logging-nl22b   2/2     Running   0          6d19h   10.123.2.53   kubenode4   <none>           <none>
logging-logging-qq2rp   2/2     Running   0          6d19h   10.123.2.4    kubenode2   <none>           <none>
logging-logging-rbmwl   2/2     Running   0          6d19h   10.123.2.36   kubenode3   <none>           <none>
logging-logging-rqtjw   2/2     Running   0          6d19h   10.123.2.6    kubenode1   <none>           <none>
logging-logging-rztmd   2/2     Running   0          6d19h   10.123.2.40   kubenode6   <none>           <none>
logging-logging-sjmfz   2/2     Running   0          6d19h   10.123.2.21   kubenode5   <none>           <none>
```

3. drain the node to prepare for system reboot (only daemonsets will be running on the node after drain)
```console
$ kubectl drain kubenode4 --ignore-daemonsets --delete-local-data
```

4. verify state of the pool after node is drained
```console
$ calicoctl ipam show
+----------+----------------+-----------+------------+-----------+
| GROUPING |      CIDR      | IPS TOTAL | IPS IN USE | IPS FREE  |
+----------+----------------+-----------+------------+-----------+
| IP Pool  | 10.123.2.0/26   |        64 | 39 (61%)   | 25 (39%)  |
+----------+----------------+-----------+------------+-----------+
```

5. reboot drained node

6. verify pods which are using logging ippool (daemonset pod logging-logging-nl22b on restared node has new IP assigned):
```console
$ kubectl -n logging get pods -o wide
NAME                      READY   STATUS    RESTARTS   AGE     IP           NODE        NOMINATED NODE   READINESS GATES
logging-logging-nl22b   2/2     Running   0          6d19h   10.123.2.52   kubenode4   <none>           <none>
logging-logging-qq2rp   2/2     Running   0          6d19h   10.123.2.4    kubenode2   <none>           <none>
logging-logging-rbmwl   2/2     Running   0          6d19h   10.123.2.36   kubenode3   <none>           <none>
logging-logging-rqtjw   2/2     Running   0          6d19h   10.123.2.6    kubenode1   <none>           <none>
logging-logging-rztmd   2/2     Running   0          6d19h   10.123.2.40   kubenode6   <none>           <none>
logging-logging-sjmfz   2/2     Running   0          6d19h   10.123.2.21   kubenode5   <none>           <none>
```

7. checking state of the pool after reboot shows increased number of IP addresses used
```console
$ calicoctl ipam show
+----------+----------------+-----------+------------+-----------+
| GROUPING |      CIDR      | IPS TOTAL | IPS IN USE | IPS FREE  |
+----------+----------------+-----------+------------+-----------+
| IP Pool  | 10.123.2.0/26   |        64 | 40 (62%)   | 24 (38%)  |
+----------+----------------+-----------+------------+-----------+
```

8. in ipamblock multiple handle_id's are visible for the same pod (metadata and allocations removed from output)
```console
$ kubectl get ipamblocks.crd.projectcalico.org 10-123-2-48-29 -o yaml
apiVersion: crd.projectcalico.org/v1
kind: IPAMBlock
spec:
  affinity: host:kubenode4
  attributes:
  - handle_id: k8s-pod-network.5d44f8e75091593a199b0cbae5300fe16bfb3b88210bc6ae73375ac838dcbfd7
    secondary:
      namespace: logging
      node: kubenode4
      pod: logging-logging-nl22b
  - handle_id: k8s-pod-network.da05436b553802c4807bbe05bb2e0d9e678cd8537ecbbd17aa27b4067f700fc2
    secondary:
      namespace: logging
      node: kubenode4
      pod: logging-logging-nl22b
  - handle_id: k8s-pod-network.e1a86e0005001e5c6ae3e29adacb02f8447482e4b9fff65c3bef1f60f6a350fc
    secondary:
      namespace: logging
      node: kubenode4
      pod: logging-logging-nl22b
  cidr: 10.123.2.48/29
```
9. Summary:     
Before reboot in logging pool 39 IP addresses were listed in column IPS IN USE.  
After reboot in logging pool 40 IP addresses are listed in column IPS IN USE.  

## Your Environment   
We are using Calico 3.16.5 together with Kubernetes 1.19.1.  
Operating system is Ubuntu Focal and Bionic (versions within cluster not mixed).  
The container runtime is cri-o 1.18.1.  
Calico is deployed using release `calico-typha.yaml` manifest.

**Comment by caseydavenport** [comment]
Hm, interesting.

If I had to guess, I'd say that when rebooting the node the kubelet / container runtime isn't getting a chance to call the Calico CNI plugin to release the address. 

However, I'd expect the address to be released "eventually" once the kubelet / container runtime completes its garbage collection routine. Generally it's the responsibility of the container runtime to track which containers have had resources garbage collected, and which have not. 

What container runtime are you using? Are you able to see if the old container IDs are still present on the node (likely in an "exited" or "stopped" state)?

**Comment by mbarecki** [comment]
Hello @caseydavenport, thank you for reply.

When issue was created we were using cri-o 1.18.1.  

Based on your feedback we looked over our configuration of cri-o.  
We found that issue was related to cri-o wiping pods on startup.  
This was deliberately configured to workaround a problem when pods would not start correctly.

We have upgraded now to cri-o 1.18.4.  
In this version wipe is not needed and IP of a daemonset pod is being reused after node reboot.

We have also done test with containerd version 1.3.7.  
With that container runtime IP of a daemonset pod was properly released from ipam and new IP was allocated for pod.  

It is interesting that cri-o reuses the same pod IP, but containerd allocates the new one in tests we did.  

The issue seems to be resolved, but what is expected behavior:
- should daemonset pod get new IP when node is rebooted ?
- could cri-o reusing the same IP be considered as expected ?

**Comment by mgleung** [comment]
Hi @mbarecki, the expected behavior is that the container runtime will eventually always signal the CNI plugin to delete any containers that it has started. This means that the expected behavior depends a little on how the container runtime handles rebooting. If when a node is rebooted, the container runtime stops all of it's containers and starts them again when the node has rebooted, then I would expect a new IP for the pod. If when a node is rebooted, the container runtime suspends its containers and can restart them, then I would expect the pods to keep their old IPs. So reusing the same IP is expected somewhat but it is dependent on how the container runtime handles events outside of itself.

**Comment by caseydavenport** [comment]
Yeah, it's really up to the container runtime in this case. I would say the behavior is not defined, so don't rely on IP addresses persisting or changing across reboot. The one thing you shouldn't see is _leaked_ IP addresses, if the container runtime is doing the correct thing and calling delete on terminated containers.

**Comment by mbarecki** [comment]
@caseydavenport, @mgleung Thank you very much for help and provided explanations.

This case is solved.
