### ISSUE TITLE
calico-node should have dnsPolicy explicitly declared as ClusterFirstWithHostNet

### ISSUE THREAD

**Issue by ark-g** [projectcalico/calico#4192]
## Expected Behavior
The calico-node pod is running in host network namespace (hostNetwork is "true"), so according to k8s [documentation](https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#pod-s-dns-policy) such a pod should explicitly declare _dnsPolicy_ as _ClusterFirstWithHostNet_.

## Current Behavior
The calico-node pod has no explicit declaration for _dnsPolicy_ parameter, so it fall back to _ClusterFirst_ default value.

## Possible Solution
Add _dnsPolicy: ClusterFirstWithHostNet_ declaration in pod specification in all examples.

## Steps to Reproduce (for bugs)
`
kubectl get pod -n kube-system  -lk8s-app=calico-node  -o jsonpath="{.items[0].spec.hostNetwork} <=> {.items[0].spec.dnsPolicy}"
`
## Your Environment

* Calico version v3.16.1
* Orchestrator version (e.g. kubernetes, mesos, rkt): kubernetes v1.19.1.
* Operating System and version: Ubuntu 18.04

**Comment by caseydavenport** [comment]
@ark-g is there a particular issue you've encountered as a result of this? Or was this spotted through code-reading?

**Comment by ark-g** [comment]
I found it just by pod declaration analysis.
No actual issues were observed.

**Comment by caseydavenport** [comment]
The problem using ClusterFirstWithHostNet, is that calico/node is typically launched prior to cluster DNS being available. 

calico/node is required in order for kube-dns to work, so having a dependency on kube-dns would be bad and likely prevent calico/node from starting up. So, I think it's correct the way that it is today. 

Happy to revisit this if we find a scenario that the current behavior has negative consequences.
