### ISSUE TITLE
pods calico-node on worker nodes with 'Running' but not Ready 0/1

### ISSUE THREAD

**Issue by amin224** [projectcalico/calico#4197]
Expected Behavior
Pods calico-node on worker nodes should have status '1/1 Ready'

Current Behavior
Pods calico-node on worker nodes are in state '0/1 Ready'
```
kubectl get pods -o wide --all-namespaces 
NAMESPACE              NAME                                         READY   STATUS    RESTARTS   AGE     IP                NODE            NOMINATED NODE   READINESS GATES
default                postgres-statefulset-0                       1/1     Running   0          3m1s    192.168.238.130   wd1            <none>           <none>
kube-system            calico-kube-controllers-56b44cd6d5-h94rf     1/1     Running   0          7m16s   192.168.238.128   wd1            <none>           <none>
kube-system            calico-node-bllj7                            0/1     Running   2          5m20s   192.168.5.112    worker-node-1   <none>           <none>
kube-system            calico-node-chtrn                            0/1     Running   2          5m20s   192.168.5.161    master-node-1   <none>           <none>
kube-system            calico-node-ws5z4                            0/1     Running   1          5m20s   192.168.5.180    w90             <none>           <none>
kube-system            calico-node-wxp4k                            0/1     Running   1          5m20s   192.168.5.18     wd1             <none>           <none>
kube-system            coredns-f9fd979d6-fm5n9                      1/1     Running   3          24h     192.168.4.14      master-node-1  <none>           <none>
kube-system            coredns-f9fd979d6-zcphr                      1/1     Running   3          24h     192.168.4.15      master-node-1  <none>           <none>
kube-system            etcd-master-node-1                           1/1     Running   3          24h     192.168.5.161    master-node-1   <none>           <none>
kube-system            kube-apiserver-master-node-1                 1/1     Running   15         24h     192.168.5.161    master-node-1   <none>           <none>
kube-system            kube-controller-manager-master-node-1        1/1     Running   10         24h     192.168.5.161    master-node-1   <none>           <none>
kube-system            kube-proxy-6d4cb                             1/1     Running   0          23h     192.168.5.180    w90             <none>           <none>
kube-system            kube-proxy-9l8gp                             1/1     Running   0          23h     192.168.5.66     wd1             <none>           <none>
kube-system            kube-proxy-fjfzq                             1/1     Running   3          24h     192.168.5.161    master-node-1   <none>           <none>
kube-system            kube-proxy-zcmhh                             1/1     Running   0          23h     192.168.5.112    worker-node-1   <none>           <none>
kube-system            kube-scheduler-master-node-1                 1/1     Running   10         24h     192.168.5.161    master-node-1   <none>           <none>
```

Steps to Reproduce (for bugs)
I searched around on github and stackoverflow for possible solutions and I found that I need to change configuration in calico.yml file
While installation I ran the following command on my master node ...
1.`sudo kubeadm init --pod-network-cidr=192.168.5.0/24 --apiserver-advertise-address=(IP address of your master virtual machine)`
2. I edit my calico file: 
3. `kubectl apply -f https://docs.projectcalico.org/v3.9/manifests/calico.yaml`
4.` kubectl edit -f https://docs.projectcalico.org/v3.9/manifests/calico.yaml`
5. 

```
- name: CALICO_IPV4POOL_CIDR
value: 192.168.5.0/24
- name: CALICO_DISABLE_FILE_LOGGING
value: "true"
- name: FELIX_DEFAULTENDPOINTTOHOSTACTION
value: ACCEPT
- name: FELIX_IPV6SUPPORT
value: "false"
- name: FELIX_LOGSEVERITYSCREEN
value: info
- name: FELIX_HEALTHENABLED
value: "true"
- name: IP_AUTODETECTION_METHOD
value: interface=ens.
```

Context
This issue seems to prevent me from getting pods in the same subnet as I cannot access the postgres pod on pgadmin when the IP of the pod is not in the subnet.
I want to get pods IP in the same subnet even when I want to create other pods.
I noticed that after i edit the calico.yml file and then apply I am getting that the changes have been made but when I access the file again this parameter is not changing

```
name: CALICO_IPV4POOL_CIDR
value: 192.168.0.0/16
```

Cluster information:
Kubernetes version: v1.18.6
Cloud being used: bare-metal
Installation method: kubeadm
Host OS: Ubuntu 18.04
CNI and version: calico
CRI and version: Docker 19.03.6

**Comment by halfcrazy** [comment]
The `CALICO_IPV4POOL_CIDR` env will create an ippool with this CIDR if there are no existing ippools otherwise this env will be ignored. 
I think you should do the  following steps:

1.sudo kubeadm init --pod-network-cidr=192.168.5.0/24 --apiserver-advertise-address=(IP address of your master virtual machine)
2. wget https://docs.projectcalico.org/v3.9/manifests/calico.yaml
3. vi calico.yaml // edit cidr
4. kubectl apply-f calico.yaml
5. kubectl get ippools -o yaml // verify

**Comment by amin224** [comment]
Hi,

Thank you for your reply. As mentioned above I did the required steps to change my calico file to my desired outcome. Unfortunately, the `CALICO_IPV4POOL_CIDR` value is not changing because when i re-enter the file the value is still in the default state `192.168.0.0/16` .

After applying your steps here is the outcome for the last step:
**kubectl get ippools -o yaml**

```
apiVersion: v1
items:
- apiVersion: crd.projectcalico.org/v1
  kind: IPPool
  metadata:
    annotations:
      projectcalico.org/metadata: '{"uid":"6ad92913-44p8-4a18-8012-77ef3d75a78a","creationTimestamp":"2020-11-20T10:32:31Z"}'
    creationTimestamp: "2020-11-20T10:32:31Z"
    generation: 1
    managedFields:
    - apiVersion: crd.projectcalico.org/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:projectcalico.org/metadata: {}
        f:spec:
          .: {}
          f:blockSize: {}
          f:cidr: {}
          f:ipipMode: {}
          f:natOutgoing: {}
          f:nodeSelector: {}
          f:vxlanMode: {}
      manager: Go-http-client
      operation: Update
      time: "2020-11-20T10:32:31Z"
    name: default-ipv4-ippool
    resourceVersion: "625"
    selfLink: /apis/crd.projectcalico.org/v1/ippools/default-ipv4-ippool
    uid: 88889dc2-dcy1-41a4-a49a-4f8a3d472a42
  spec:
    blockSize: 26
    cidr: 192.168.0.0/16
    ipipMode: Always
    natOutgoing: true
    nodeSelector: all()
    vxlanMode: Never
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
```

Please note that the pods are still not in the desired IP subnet that I need them to be.

**Comment by halfcrazy** [comment]
Is your environment a fresh k8s cluster? 
Since the `creationTimestamp: "2020-11-20T10:32:31Z"` looks the legacy data. You may need to clean up legacy data.

**Comment by amin224** [comment]
Yes it is a fresh cluster as I created it to work on my calico subnet problem. For the duration, I managed to solve this issue by providing my deployments with parameter `hostNetwork: true` , but as you may know this will expose my pods outside the cluster which is not safe. Can you please elaborate more on what you mean by cleaning up my legacy data. I have searched on other GitHub posts and all I can find is people solving it with this parameter which is not doing the job for my case.

```
- name: IP_AUTODETECTION_METHOD
value: interface=ens.
```

**Comment by halfcrazy** [comment]
`kubectl delete -f https://docs.projectcalico.org/v3.9/manifests/calico.yaml`

**Comment by amin224** [comment]
I deleted my calico.yml file as mentioned above, what can I do to solve my subnet issue,  please be explicit.

**Comment by halfcrazy** [comment]
> I deleted my calico.yml file as mentioned above, what can I do to solve my subnet issue, please be explicit.

If you had install calico in this cluster, you need at least delete all the existing ippools(`kubectl delete ippools --all`), then create your own ippool.

subnet.yaml
```
- apiVersion: crd.projectcalico.org/v1
  kind: IPPool
  metadata:
    name: default-ipv4-ippool
  spec:
    blockSize: 26
    cidr: 192.168.5.0/24
    ipipMode: Always
    natOutgoing: true
    nodeSelector: all()
    vxlanMode: Never
```

`kubectl apply -f subnet.yaml`

**Comment by caseydavenport** [comment]
> Unfortunately, the CALICO_IPV4POOL_CIDR value is not changing because when i re-enter the file the value is still in the default state 192.168.0.0/16 .

Yes, this cannot be changed on a running cluster. It is only modifiable on a first-time install.

To modify your IP pool CIDR on a running cluster, you need to follow this doc: https://docs.projectcalico.org/archive/v3.17/networking/migrate-pools
