### ISSUE TITLE
ipv6 stack is not ready to use immediately after container started to run user command

### ISSUE THREAD

**Issue by zq-david-wang** [projectcalico/calico#4209]
kubernetes 1.18 with calico 3.15
ipv6 enable (ipam/felix/calico-node)
deploy iperf3/iperf2 server, assuming server pod has ipv6 address "2001:db8:dead:beef:fe::1000"
deploy iperf3/iperf2 client, setting pod args; [ "sh", "-c", "iperf3 -c 2001:db8:dead:beef:fe::1000" ]

for iperf2 client/server, client would get connect EINPROGRESS error and
for iperf3 client/server, client would get connect timeout error

but if the client entry args changed to ["sh", "-c", "sleep 3; iperf3 -c 2001:db8:dead:beef:fe::1000"], then the client would make ipv6 connection successfully.

No such issue happened with ipv4 stack

## Expected Behavior

When container starts to run user command, ipv6 stack should be ready to use.

## Steps to Reproduce (for bugs)

1.  enable ipv6 support
2.  deploy a ipv6 server, e.g. iperf3
3.  deploy a ipv6 client which would make ipv6 connection at its entrypoint
4. for iperf2/perf3 client, the first connection would fail

## Your Environment

* Calico version
3.15
* Orchestrator version (e.g. kubernetes, mesos, rkt):
k8s 1.18
* Operating System and version:
centos7  3.10.0-1127
* Link to your project (optional):

**Comment by lwr20** [comment]
A Kubernetes environment is very much an eventually-consistent environment.  Applications **must** retry connections if they don't work immediately.  

Calico starts all pods with a deny-all policy until it can get the correct policy from the k8s APIserver.  The thinking here is that it would be a security risk if a pod could bypass network policy in a window just after startup.  That round-trip to the APIserver takes time, and that can mean that the pod isn't networked by the time the pod starts running. 
This can happen in IPv4 if the k8s-apiserver is heavily loaded for example.  Its not clear to me why the API server would be slower in the IPv6 case however.

You say that the startup time is less than 3 seconds - is there any way to tell how much of that time is the request/response to the k8s apiserver?

**Comment by zq-david-wang** [comment]
@lwr20 thanks for the explanation, that make sense.

The k8s cluster I was testing was running on low end hardware,  sometimes apiserver did report etcd timeout.
During the test, I do observe the problem only with ipv6 pod... maybe it was the case just by chance. 



Close the issue.
Thanks

**Comment by lwr20** [comment]
I agree that its suspicious that ipv6 and ipv4 behave differently.  Next time I have a stress-testing cluster up, I'll have a look into this...
