### ISSUE TITLE
Unable to drain node running Kube Controller because of Pod Disruption Budget

### ISSUE THREAD

**Issue by invidian** [projectcalico/calico#4211]
## Expected Behavior

Draining the Node running `calico-kube-controllers` should work.

## Current Behavior
`kubectl drain` loops infinitely, as only single `calico-kube-controllers` is allowed to run and PodDisruptionBudget prevents it from being evicted.

## Possible Solution

Ideally  `calico-kube-controllers` should support HA with leases, so multiple instances can run simultaneously, so then `PodDisruptionBudget` is satisfied.

## Steps to Reproduce (for bugs)

1. Install Calico using manifests from v3.17.0
2. Find on which Node `calico-kube-controllers` pod got scheduled.
3. Try running `kubectl drain` on found node.

## Context

Found while updating https://github.com/flexkube/calico-helm-chart to latest Calico version.

#4089 added PodDisruptionBudget object to manifests. CC @gdziwoki

## Your Environment

* Calico version `v3.17.0`
* Orchestrator version (e.g. kubernetes, mesos, rkt): Kubernetes `v1.19.4`

**Comment by gdziwoki** [comment]
Hi @invidian .
I have tested this against clusters running k8s 1.15 and 1.18.
Doing `kubectl drain` on node running calico-kube-controller worked just fine for me.
Could you provide more logs on what is happening?

**Comment by invidian** [comment]
Oh, my bad, the PDB has `maxUnavailable: 1`, so draining will work as expected. Sorry for the noise.

**Comment by TheKangaroo** [comment]
Quick question: What does a PDB for a deployment with replica count "1" and maxUnavailable "1" actually do?

**Comment by gdziwoki** [comment]
It prevents [this](https://github.com/projectcalico/calico/pull/4089)

**Comment by TheKangaroo** [comment]
Ah I see, thank you 👍 
We use our custom redeploy mechanism and no autoscaler so we never hit that case :)
