### ISSUE TITLE
"add-apt-repository ppa:project-calico/calico-3.17" fails on focal

### ISSUE THREAD

**Issue by rodrigogansobarbieri** [projectcalico/calico#4216]
Hello,

Following https://docs.projectcalico.org/getting-started/openstack/installation/ubuntu it works on bionic but not focal.

## Expected Behavior

Expected that it would add the repo successfully just as it works on bionic.

## Current Behavior

See error below:

```
$ add-apt-repository ppa:project-calico/calico-3.17
 This PPA contains packages for Calico's 3.17.x release series, mainly to support OpenStack-based systems (although the Felix package can be used stand-alone). It will be updated with patch releases for that series.
 More info: https://launchpad.net/~project-calico/+archive/ubuntu/calico-3.17
Press [ENTER] to continue or Ctrl-c to cancel adding it.

Hit:1 http://nova.clouds.archive.ubuntu.com/ubuntu focal InRelease
Hit:2 http://nova.clouds.archive.ubuntu.com/ubuntu focal-updates InRelease                             
Hit:3 http://nova.clouds.archive.ubuntu.com/ubuntu focal-backports InRelease                           
Hit:4 http://security.ubuntu.com/ubuntu focal-security InRelease                                       
Ign:5 http://ppa.launchpad.net/project-calico/calico-3.17/ubuntu focal InRelease                       
Err:6 http://ppa.launchpad.net/project-calico/calico-3.17/ubuntu focal Release
  404  Not Found [IP: 91.189.95.83 80]
Reading package lists... Done                      
E: The repository 'http://ppa.launchpad.net/project-calico/calico-3.17/ubuntu focal Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

## Steps to Reproduce (for bugs)

1. Boot a focal VM
2. Follow the steps at https://docs.projectcalico.org/getting-started/openstack/installation/ubuntu
3. Try to add repo "ppa:project-calico/calico-3.17"
4. Unable to install calico-control

## Context

I'm trying to SRU (backport) fixes for nova integration with calico: https://bugs.launchpad.net/ubuntu/+source/nova/+bug/1893263

But it needs to go through focal, then to train and stein.

## Your Environment

* Calico version
* Orchestrator version (e.g. kubernetes, mesos, rkt):
* Operating System and version:
* Link to your project (optional):

OpenStack. Ubuntu 20.04. Calico 3.17

**Comment by neiljerram** [comment]
Yes indeed, we currently only build for Trusty, Xenial and Bionic.

If someone would like to take a look at adding the Focal support, the place for that is https://github.com/projectcalico/packaging/ 

If you check out that repo and search for bionic, it should be pretty obvious what's needed to add in support for another Ubuntu distro.

**Comment by rodrigogansobarbieri** [comment]
Indeed, it is easy and obvious to add the recipe for building focal. I have prepared a PR, but it does not work as networking-calico does not build smoothly in focal. I haven't had time to debug the error. See below:

https://paste.ubuntu.com/p/R7nJ6tYn8B/

**Comment by rodrigogansobarbieri** [comment]
After building the package manually (it was missing the dh-python dependency) I was able to test it on Focal. Turns out it doesn't work. When creating VMs, it triggers this error:

https://paste.ubuntu.com/p/jQnJ8CqRMf/

However, that error is due to Python 3.8, which enforces the Runtime error. See https://stackoverflow.com/questions/59216749/runtimeerror-dictionary-keys-changed-during-iteration-when-attempting-to-call

That particular error has an easy fix though, just creating a set() out of the self.cache.get_network_ids() call, as it is being done in other code places.

However, I am not confident about considering the code ready for focal or python3.8 as is with this particular fix and extra dependency. A full test suite and QA should be done to validate whether the rest of the code works on focal and python 3.8.

**Comment by lmm** [comment]
Hi @rodrigogansobarbieri :wave: , thank you for following up on this. I've chatted with @neiljerram about this and we think your proposed changes (the bug fix and the new dependency) sound about right. If you go ahead and submit the PR as suggested, I can review it :)

> A full test suite and QA should be done to validate whether the rest of the code works on focal and python 3.8

We have automated tests that run internally. Once the PR is merged and the tests run, I can paste the screenshots here.

**Comment by rodrigogansobarbieri** [comment]
Pushed:

https://github.com/projectcalico/networking-calico/pull/48
https://github.com/projectcalico/packaging/pull/39

**Comment by rodrigogansobarbieri** [comment]
@neiljerram could PR 48 be backported to 3.17 or 3.18?

 I'd assume the stable code from those branches were never run against focal before during QA. For anyone wanting to use this in focal right now, they would need to have the fix in a stable release.

**Comment by caseydavenport** [comment]
I'm going to close this for now since the above PRs should fix this for new releases.

I'll leave the back-porting decision up to @lmm
