### ISSUE TITLE
trying to use Calico with kubeadm

### ISSUE THREAD

**Issue by latenite4** [projectcalico/calico#4218]
i am trying to install calico with kubeadm kubernetes on google cloud.
there are 3 ubuntu 16 VMs. first one will be k8s master, others will be worker nodes.

## Expected Behavior
i create VMs and run kubeadm and do joins. i try to install calico with:
```
gcloud compute ssh --ssh-key-file=/home/user01/.ssh/id_rsa.pub --zone us-central1-c --command 'kubectl create --kubeconfig=/home/user01/.kube/admin.conf  -f https://docs.projectcalico.org/manifests/tigera-operator.yaml
' computenode-0
namespace/tigera-operator created
podsecuritypolicy.policy/tigera-operator created
serviceaccount/tigera-operator created
customresourcedefinition.apiextensions.k8s.io/bgpconfigurations.crd.projectcalico.org created
customresourcedefinition.apiextensions.k8s.io/bgppeers.crd.projectcalico.org created
customresourcedefinition.apiextensions.k8s.io/blockaffinities.crd.projectcalico.org created
customresourcedefinition.apiextensions.k8s.io/clusterinformations.crd.projectcalico.org created
customresourcedefinition.apiextensions.k8s.io/felixconfigurations.crd.projectcalico.org created
customresourcedefinition.apiextensions.k8s.io/globalnetworkpolicies.crd.projectcalico.org created
customresourcedefinition.apiextensions.k8s.io/globalnetworksets.crd.projectcalico.org created
customresourcedefinition.apiextensions.k8s.io/hostendpoints.crd.projectcalico.org created
customresourcedefinition.apiextensions.k8s.io/ipamblocks.crd.projectcalico.org created
customresourcedefinition.apiextensions.k8s.io/ipamconfigs.crd.projectcalico.org created
customresourcedefinition.apiextensions.k8s.io/ipamhandles.crd.projectcalico.org created
customresourcedefinition.apiextensions.k8s.io/ippools.crd.projectcalico.org created
customresourcedefinition.apiextensions.k8s.io/kubecontrollersconfigurations.crd.projectcalico.org created
customresourcedefinition.apiextensions.k8s.io/networkpolicies.crd.projectcalico.org created
customresourcedefinition.apiextensions.k8s.io/networksets.crd.projectcalico.org created
customresourcedefinition.apiextensions.k8s.io/installations.operator.tigera.io created
customresourcedefinition.apiextensions.k8s.io/tigerastatuses.operator.tigera.io created
clusterrole.rbac.authorization.k8s.io/tigera-operator created
clusterrolebinding.rbac.authorization.k8s.io/tigera-operator created
**deployment.apps/tigera-operator created**
```
```
gcloud compute ssh --ssh-key-file=/home/user01/.ssh/id_rsa.pub --zone us-central1-c --command 'kubectl create --kubeconfig=/home/user01/.kube/admin.conf  -f https://docs.projectcalico.org/manifests/custom-resources.yaml
' computenode-0
**installation.operator.tigera.io/default created**
```

but DNS pods are still in Pending state.

there is no calico-system namespace:

```
gcloud compute ssh --ssh-key-file=/home/user01/.ssh/id_rsa.pub --zone us-central1-c --command 'kubectl create --kubeconfig=/home/user01/.kube/admin.conf  -f https://docs.projectcalico.org/manifests/custom-resources.yaml
' computenode-0
installation.operator.tigera.io/default created
```

## Current Behavior
master node is NotReady, i assume that is because DNS is Pending.

```
kubectl get nodes
NAME            STATUS     ROLES    AGE   VERSION
computenode-0   NotReady   master   68m   v1.19.4
```

## Steps to Reproduce (for bugs)
create 3 ubuntu 16.04 VMs on GCE and run kubeadm.
install calico following https://docs.projectcalico.org/getting-started/kubernetes/quickstart

## Your Environment
installing k8s using kubeadm in ubuntu1604 VMs on GCP

**Comment by caseydavenport** [comment]
@latenite4 can you check the output of the following commands?

```
kubectl get pods -n tigera-operator
```
```
kubectl get tigerastatus -o yaml
```
```
kubectl logs -n tigera-operator -l k8s-app=tigera-operator
```

I am guessing that, for some reason or another, the operator has not launched.

**Comment by softwareartisan-ops** [comment]
Hi, I have exactly the same case and the issue is the same. 
I paste here the results of the commands
Any suggestion? 

NAME                               READY   STATUS                       RESTARTS       AGE
tigera-operator-7d68577dc5-bgcbs   0/1     CreateContainerConfigError   25 (41m ago)   165m


`  status:
    conditions:
    - lastTransitionTime: "2025-01-18T16:49:00Z"
      message: 'waiting for enabled IP pools to be created: '
      observedGeneration: 2
      reason: ResourceNotFound
      status: "True"
      type: Degraded
- apiVersion: operator.tigera.io/v1
  kind: TigeraStatus
  metadata:
    creationTimestamp: "2025-01-18T16:03:40Z"
    generation: 1
    name: ippools
    resourceVersion: "1359"
    uid: 5cf8e357-3558-4aad-a60e-f4889af1ca7f
  spec: {}
  status:
    conditions:
    - lastTransitionTime: "2025-01-18T16:03:45Z"
      message: 'error filling IP pool defaults: Could not resolve CalicoNetwork IPPool
        and kubeadm configuration: IPPool 192.168.0.0/16 is not within the platform''s
        configured pod network CIDR(s) [10.244.0.0/16]'
      observedGeneration: 2
      reason: ResourceReadError
      status: "True"
      type: Degraded`
