### ISSUE TITLE
Support multiple IP addresses for "cni.projectcalico.org/ipAddrs" 

### ISSUE THREAD

**Issue by zionwu** [projectcalico/calico#4219]
Currently, we can use "cni.projectcalico.org/ipAddrs" to specify a fixed IP for a pod. 
In our use case, We would like to have fixed IPs for a deployment with replica more than 1. Could Calico support multiple IP addresses for "cni.projectcalico.org/ipAddrs" in the future?

**Comment by caseydavenport** [comment]
Closing as a duplicate of https://github.com/projectcalico/cni-plugin/issues/771
