### ISSUE TITLE
Traffic to DaemonSet port in another namespace is not allowed while no policies are defined.

### ISSUE THREAD

**Issue by Svisstack** [projectcalico/calico#4223]
# Expected Behavior

Traffic to the DaemonSet port exposed on the Host IP should be allowed from the pod on different namespaces as no Calico or K8S policies are defined.

## Current Behavior

Traffic to the DaemonSet port exposed on the Host IP is denied if the DaemonSet is on a different namespace than the namespace of the pod initiating a connection.

## Context 

Possibly issue could be related to all cross namespace traffic without policies applied.

## Your Environment
* Calico version v3.16.5
* Orchestrator version (e.g. kubernetes, mesos, rkt): kubernetes v1.19.3
* Operating System and version:  Ubuntu 20.04.1 LTS Linux 5.4.0-54

**Comment by Svisstack** [comment]
### Updating with Slack communication

lrobson  6 hours ago
Agree that this is unexpected.
Can you explain what you mean by "DaemonSet port exposed on the Host IP"?  Is this a Nodeport service or is that daemonset host-networked?

Artur Pietrzyk  6 hours ago
Something different.

Artur Pietrzyk  6 hours ago
The DeamonSet can be exposed to NodePort without the Service. It's defined in the DaemonSet Yaml.

Artur Pietrzyk  6 hours ago
https://kubernetes.io/docs/concepts/workloads/controllers/daemonset/.

Artur Pietrzyk  6 hours ago
My actual problem is with https://github.com/hashicorp/consul-helm/blob/master/templates/client-daemonset.yaml ports are exposed starting from 252 line.

**Comment by mgleung** [comment]
Hi @Svisstack , what happens if you apply a policy that explicitly allows the host ports? I'm trying to distinguish if this is an issue with our policies or networking.

**Comment by Svisstack** [comment]
@mgleung I have no longer possibility to check that.

**Comment by caseydavenport** [comment]
@Svisstack it's not clear to me how your pod is running. Is it doing one of the following?

- DaemonSet running with `hostNetwork: true`?
- DaemonSet running with `hostNetwork:false`, but `hostPorts` defined?
- DaemonSet running with `hostNetwork:false`, but using a service NodePort?

Each of those is quite different, and so would be important to know.

**Comment by lmm** [comment]
Going to close this for now since it's stale, if you run into this again with details please reopen, thanks!
