### ISSUE TITLE
Felix mixes up builddate and gitcommit on startup message 

### ISSUE THREAD

**Issue by sfudeus** [projectcalico/calico#4224]
## Current Behavior

When starting (with info logging enabled), felix e.g. logs the following line:
```
Felix starting up GOMAXPROCS=4 builddate="917484d86d19f1c9b77ece5e42ebbd01bb8570d0" gitcommit="2020-11-23T18:48:10+0000" version="v3.17.0"
```

As you can see, builddate and gitcommit are switched :-)

## Your Environment
* Calico version 3.17.0
* Orchestrator version (e.g. kubernetes, mesos, rkt): kubernetes 1.18.12
* Operating System and version: FlatCar ContainerLinux 2605.7.0

**Comment by caseydavenport** [comment]
Lovely

**Comment by caseydavenport** [comment]
This should do it: https://github.com/projectcalico/node/pull/674
