### ISSUE TITLE
Unable to reach non-service network hosts from k8s pod configured with Calico CNI

### ISSUE THREAD

**Issue by munkyshi** [projectcalico/calico#4233]
Looking for support in understanding how to configure / resolve my issue.
I'm a networking noob, so apologies in advance if I'm barking up the wrong tree here.

## Expected Behavior
I should be able to ping a non-service network host from a pod on k8s.

## Current Behavior
Attempts to ping the non-service network host result in 100% packet loss:
```
bash-5.0# ping6 240b::51
PING 240b::51(240b::51) 56 data bytes
^C
--- 240b::51 ping statistics ---
71 packets transmitted, 0 received, 100% packet loss, time 70005ms
```

## Possible Solution

Potential reasons:
- I've screwed up my configuration when installing the Calico CNI
- I've screwed up my configuration when installing k8s
- The underlying server (company provided) for my k8s stack is misconfigured

## Steps to Reproduce (for bugs)

Providing steps starting with k8s installation, in case that's where my error is. I was following instructions from the [quickstart](https://docs.projectcalico.org/getting-started/kubernetes/quickstart).
1. Acquire server configured with IPv6 address (`240b::1` from hereon)
2. Install k8s v1.16.15-0 with the following `kubeadm`:
```
sudo kubeadm init --apiserver-advertise-address 240b::1 --pod-network-cidr=fc00::/112 --service-cidr=fd00::/112
```
3. Set up `kubectl` configuration:
```
     mkdir -p $HOME/.kube
     sudo cp -f /etc/kubernetes/admin.conf $HOME/.kube/config
     sudo chown $(id -u):$(id -g) $HOME/.kube/config
```
4. Untaint the master node
```
 kubectl taint nodes --all node-role.kubernetes.io/master-
```
5. Install the Tigera Calico operator and custom resource definitions.
```
kubectl create -f https://docs.projectcalico.org/manifests/tigera-operator.yaml
```
6. Install [modified custom resources yaml](https://gist.github.com/munkyshi/cd304c831faaa9369cd88e755d5f205e#file-custom-resources-yaml)
```
kubectl create -f custom-resources.yaml
```
7. Create debug namespace
```
kubectl create ns debug
```
8. Create deployment for debugging with [debug-network.yaml](https://gist.github.com/munkyshi/cd304c831faaa9369cd88e755d5f205e#file-debug-network-yaml)
```
kubectl apply -n debug -f debug-network.yaml
```
9. Exec `bash` on the newly created pod
```
kubectl exec -n debug --stdin --tty $(kubectl get pod -n debug -o name | grep debug-network) -- bash
```
10. Attempt to ping the proxy host (or any host outside of the service network)
```
ping6 240b::51
```

## Context

I've been given access to a single workplace dev server with an IPv6 address that is blocked off from the public internet behind an `http_proxy` server hosted on `240b::51`. I am attempting to set up access from k8s pods to the public internet through this `http_proxy`, but when I attempt to ping `240b::51` from my pods I experience 100% packet loss.

My service net seems to be working fine -- I can ping other pods by their IPv6 address and services by their service domain name. I can also ping the IPv6 address of my underlying host without issue.

Please let me know if there are any logs I can provide to help debug what's going on.

## Your Environment

* Calico version: v3.16.4
* Orchestrator version (e.g. kubernetes, mesos, rkt): kubernetes v1.16.15-0
* Operating System and version: CentOS Linux 7

**Comment by caseydavenport** [comment]
It sounds like you have pod-to-pod connections working fine, as well as pod-to-kubernetes-service connections. Is that correct?

If so, then the main issue here is that pods are having trouble initiating outbound connections to things _outside of the Kubernetes cluster_.

Does that sounds like an accurate summary? 

If so, then I suspect that there is something going on outside of the k8s network layer that is at fault. Are your nodes able to access the http proxy? (i.e., without pod networking in the picture). Traffic from pods -> outside the cluster will net SNAT'd and effectively look like originate from the node hosting the pod.

**Comment by munkyshi** [comment]
> If so, then the main issue here is that pods are having trouble initiating outbound connections to things outside of the Kubernetes cluster.

Yep, that's an accurate summary.

> Are your nodes able to access the http proxy? (i.e., without pod networking in the picture).

By node, you mean the underlying host behind the k8s node? Yes, that is able to reach the proxy (and running a pod with `hostNetwork: true` is also able to reach the proxy).

**Comment by caseydavenport** [comment]
Is the proxy within the same IP range as your pod IP pool? Or another Calico IP pool? That would disable outgoing NAT and might cause issues.
