### ISSUE TITLE
get error: Failed to get resources: client: etcd cluster is unavailable or misconfigured; error #0: EOF

### ISSUE THREAD

**Issue by tscswcn** [projectcalico/calico#4243]
can't get calico status by using calicoctl 

## Expected Behavior

show correct calico node status 

always can't 

## Steps to Reproduce (for bugs)

1. please see following:

```
 root@worker1:/usr/bin# ETCD_ENDPOINTS=http://127.0.0.1:2379 calicoctl get bgppeers
Failed to get resources: client: etcd cluster is unavailable or misconfigured; error #0: EOF
```
```
root@worker1:/usr/bin# calicoctl get nodes
Failed to get resources: client: etcd cluster is unavailable or misconfigured; error #0: EOF
```
```
root@worker1:/usr/bin# ETCD_ENDPOINTS=http://127.0.0.1:2379 calicoctl get bgppeers
Failed to get resources: client: etcd cluster is unavailable or misconfigured; error #0: EOF
```
```
root@worker1:/usr/bin# calicoctl get bgppeers
Failed to get resources: client: etcd cluster is unavailable or misconfigured; error #0: EOF
```
```
root@worker1:/usr/bin# calicoctl get workloadendpoints
Failed to get resources: client: etcd cluster is unavailable or misconfigured; error #0: EOF
```
```
root@worker1:/usr/bin# ps aux | grep calico
root      18604  0.0  0.0  14436  1124 pts/0    S+   08:28   0:00 grep --color=auto calico
root      87873  0.0  1.1 1356764 46036 ?       Sl   07:21   0:00 calico-node -confd
root      87874  1.2  1.2 1578216 51472 ?       Sl   07:21   0:51 calico-node -felix
root      87875  0.0  0.9 1135568 40084 ?       Sl   07:21   0:00 calico-node -monitor-addresses
root      87878  0.0  1.1 1135568 46200 ?       Sl   07:21   0:00 calico-node -allocate-tunnel-addrs
root      88129  0.0  0.0    828   660 ?        S    07:21   0:00 bird -R -s /var/run/calico/bird.ctl -d -c /etc/calico/confd/config/bird.cfg
root      88343  0.0  0.0    744     4 ?        S    07:21   0:00 bird6 -R -s /var/run/calico/bird6.ctl -d -c /etc/calico/confd/config/bird6.cfg 
```
and 
```
kubectl exec -it calico-kube-controllers-8586758878-xcspg  -n kube-system -- sh
OCI runtime exec failed: exec failed: container_linux.go:349: starting container process caused "exec: \"sh\": executable file not found in $PATH": unknown
command terminated with exit code 126
root@worker1:/usr/bin# kubectl run tmp-shell  -i --tty --image nicolaka/netshoot -- /bin/bash
If you don't see a command prompt, try pressing enter.
bash-5.0# calicoctl get nodes
Failed to create Calico API client: no etcd endpoints specified
bash-5.0# ETCD_ENDPOINTS=http://10.10.10.120:2379 calicoctl get bgppeers
```                                                             
and hang  and can't get reslut 

2.
3.
4.

## Your Environment

* Calico version 
calico-kube-controllers:
    Container ID:   docker://adfbd8631d6546efa9e22964d3b8920331ba44c7545eed8dd70a1dfc2522ddcf
    Image:          docker.io/calico/kube-controllers:v3.17.0 

calico-node:
    Container ID:   docker://ad644184e4df6f66bec95e4a35081177d5c72fc4098ca995bb9e07649d7d5204
    Image:          docker.io/calico/node:v3.17.0 

* Orchestrator version (e.g. kubernetes, mesos, rkt): 
kubectl get nodes
NAME      STATUS   ROLES    AGE   VERSION
node120   Ready    master   94m   v1.18.1
node121   Ready    <none>   75m   v1.18.1

* Operating System and version: 
ubuntu 18.04
* Link to your project (optional):

**Comment by lwr20** [comment]
The error is saying that the etcd cluster present at the URL you've provided.  

We need to check a couple of things before going further:
- are you actually using etcd as the calico datastore?  Most current kubernetes installs don't use it (which would explain this error!)  Can you link to the calico.yaml that you used to install calico please?  That should tell us which datastore you're using.

If (as I suspect) you're not using the etcd datastore, you could try:
`KUBECONFIG=/path/to/kubeconfig DATASTORE_TYPE=kubernetes calicoctl get nodes`
