### ISSUE TITLE
can't set calico rr 

### ISSUE THREAD

**Issue by tscswcn** [projectcalico/calico#4244]
can't set calico bird rr 
root@node122:~# calicoctl apply -f node121.yaml
Failed to apply 'Node' resource: [update conflict: Node(node121)]

## Expected Behavior

root@node122:~# calicoctl apply -f node121.yaml

reply one successfully  message

## Steps to Reproduce (for bugs)

1.    kubectl label node node121 route-reflector=true
node/node121 labeled
 kubectl label node node120 route-reflector-
node/node120 labeled
 
 kubectl get nodes --show-labels
NAME      STATUS   ROLES    AGE   VERSION   LABELS
node120   Ready    master   12h   v1.18.1   beta.kubernetes.io/arch=amd64,beta.kubernetes.io/os=linux,kubernetes.io/arch=amd64,kubernetes.io/hostname=node120,kubernetes.io/os=linux,node-role.kubernetes.io/master=
node121   Ready    <none>   12h   v1.18.1   beta.kubernetes.io/arch=amd64,beta.kubernetes.io/os=linux,kubernetes.io/arch=amd64,kubernetes.io/hostname=node121,kubernetes.io/os=linux,route-reflector=true
node122   Ready    <none>   9h    v1.18.1   beta.kubernetes.io/arch=amd64,beta.kubernetes.io/os=linux,kubernetes.io/arch=amd64,kubernetes.io/hostname=node122,kubernetes.io/os=linux
 calicoctl apply -f node121.yaml
Failed to apply 'Node' resource: [update conflict: Node(node121)]

  cat node121.yaml
apiVersion: projectcalico.org/v3
kind: Node
metadata:
  annotations:
    projectcalico.org/kube-labels: '{"beta.kubernetes.io/arch":"amd64","beta.kubernetes.io/os":"linux","kubernetes.io/arch":"amd64","kubernetes.io/hostname":"node121","kubernetes.io/os":"linux"}'
  creationTimestamp: "2020-12-06T15:29:03Z"
  labels:
    beta.kubernetes.io/arch: amd64
    beta.kubernetes.io/os: linux
    kubernetes.io/arch: amd64
    kubernetes.io/hostname: node121
    kubernetes.io/os: linux
  name: node121
  resourceVersion: "108399"
  uid: a77e209d-a0f5-44c0-9c71-45e6a9a8d55a
spec:
  addresses:
  - address: 10.10.10.121/24
  - address: 10.10.10.121
  bgp:
    ipv4Address: 10.10.10.121/24
    routeReflectorClusterID: 244.0.0.1
  orchRefs:
  - nodeName: node121
    orchestrator: k8s
status:
  podCIDRs:
  - 192.168.1.0/24 

# calicoctl apply -f node121.yaml
Failed to apply 'Node' resource: [update conflict: Node(node121)]

2.
3.
4.

## Your Environment

Calico version
calico-kube-controllers:
Container ID: docker://adfbd8631d6546efa9e22964d3b8920331ba44c7545eed8dd70a1dfc2522ddcf
Image: docker.io/calico/kube-controllers:v3.17.0
calico-node:
Container ID: docker://ad644184e4df6f66bec95e4a35081177d5c72fc4098ca995bb9e07649d7d5204
Image: docker.io/calico/node:v3.17.0

Orchestrator version (e.g. kubernetes, mesos, rkt):
kubectl get nodes
NAME STATUS ROLES AGE VERSION
node120 Ready master 94m v1.18.1
node121 Ready 75m v1.18.1

Operating System and version:
ubuntu 18.04

**Comment by tscswcn** [comment]
DATASTORE_TYPE=kubernetes KUBECONFIG=~/.kube/config  calicoctl -l info  apply -f node121_new.yaml
INFO[0000] Log level set to info
INFO[0000] Executing config command
INFO[0000] Processing type &{map[apiVersion:projectcalico.org/v3 kind:Node metadata:map[annotations:map[projectcalico.org/kube-labels:{"beta.kubernetes.io/arch":"amd64","beta.kubernetes.io/os":"linux","kubernetes.io/arch":"amd64","kubernetes.io/hostname":"node121","kubernetes.io/os":"linux"}] creationTimestamp:2020-12-06T15:29:03Z labels:map[beta.kubernetes.io/arch:amd64 beta.kubernetes.io/os:linux kubernetes.io/arch:amd64 kubernetes.io/hostname:node121 kubernetes.io/os:linux] name:node121 resourceVersion:113452 uid:a77e209d-a0f5-44c0-9c71-45e6a9a8d55a] spec:map[addresses:[map[address:10.10.10.121/24] map[address:10.10.10.121]] bgp:map[ipv4Address:10.10.10.121/24 routeReflectorClusterID:222.0.0.2] orchRefs:[map[nodeName:node121 orchestrator:k8s]]] status:map[podCIDRs:[192.168.1.0/24]]]}
INFO[0000] Found resource helper: Resource(&TypeMeta{Kind:Node,APIVersion:projectcalico.org/v3,} projectcalico.org/v3, Kind=Node)
INFO[0000] Type of unpacked data: *v3.Node. Unpacked &{TypeMeta:{Kind:Node APIVersion:projectcalico.org/v3} ObjectMeta:{Name:node121 GenerateName: Namespace: SelfLink: UID:a77e209d-a0f5-44c0-9c71-45e6a9a8d55a ResourceVersion:113452 Generation:0 CreationTimestamp:2020-12-06 07:29:03 -0800 PST DeletionTimestamp:<nil> DeletionGracePeriodSeconds:<nil> Labels:map[beta.kubernetes.io/arch:amd64 beta.kubernetes.io/os:linux kubernetes.io/arch:amd64 kubernetes.io/hostname:node121 kubernetes.io/os:linux] Annotations:map[projectcalico.org/kube-labels:{"beta.kubernetes.io/arch":"amd64","beta.kubernetes.io/os":"linux","kubernetes.io/arch":"amd64","kubernetes.io/hostname":"node121","kubernetes.io/os":"linux"}] OwnerReferences:[] Finalizers:[] ClusterName: ManagedFields:[]} Spec:{BGP:0xc000104960 IPv4VXLANTunnelAddr: VXLANTunnelMACAddr: OrchRefs:[{NodeName:node121 Orchestrator:k8s}] Wireguard:<nil> Addresses:[{Address:10.10.10.121/24} {Address:10.10.10.121}]} Status:{WireguardPublicKey: PodCIDRs:[192.168.1.0/24]}}
INFO[0000] Finished parsing                              numResources=1 source=node121_new.yaml
INFO[0000] Converting resource to slice: [0xc0001529c0]
INFO[0000] Converting resource to slice: &{{Node projectcalico.org/v3} {node121    a77e209d-a0f5-44c0-9c71-45e6a9a8d55a 113452 0 2020-12-06 07:29:03 -0800 PST <nil> <nil> map[beta.kubernetes.io/arch:amd64 beta.kubernetes.io/os:linux kubernetes.io/arch:amd64 kubernetes.io/hostname:node121 kubernetes.io/os:linux] map[projectcalico.org/kube-labels:{"beta.kubernetes.io/arch":"amd64","beta.kubernetes.io/os":"linux","kubernetes.io/arch":"amd64","kubernetes.io/hostname":"node121","kubernetes.io/os":"linux"}] [] []  []} {0xc000104960   [{node121 k8s}] <nil> [{10.10.10.121/24} {10.10.10.121}]} { [192.168.1.0/24]}}
INFO[0000] Returning slice: [0xc0001529c0]
INFO[0000] Returning slice: [0xc0001529c0]
INFO[0000] Error loading config
Failed to create Calico API client: syntax error in /etc/calico/calicoctl.cfg: invalid config file: unknown APIVersion 'v1'
root@node122:~# rm -f /etc/calico/calicoctl.cfg
root@node122:~# DATASTORE_TYPE=kubernetes KUBECONFIG=~/.kube/config  calicoctl -l info  apply -f node121_new.yaml
INFO[0000] Log level set to info
INFO[0000] Executing config command
INFO[0000] Processing type &{map[apiVersion:projectcalico.org/v3 kind:Node metadata:map[annotations:map[projectcalico.org/kube-labels:{"beta.kubernetes.io/arch":"amd64","beta.kubernetes.io/os":"linux","kubernetes.io/arch":"amd64","kubernetes.io/hostname":"node121","kubernetes.io/os":"linux"}] creationTimestamp:2020-12-06T15:29:03Z labels:map[beta.kubernetes.io/arch:amd64 beta.kubernetes.io/os:linux kubernetes.io/arch:amd64 kubernetes.io/hostname:node121 kubernetes.io/os:linux] name:node121 resourceVersion:113452 uid:a77e209d-a0f5-44c0-9c71-45e6a9a8d55a] spec:map[addresses:[map[address:10.10.10.121/24] map[address:10.10.10.121]] bgp:map[ipv4Address:10.10.10.121/24 routeReflectorClusterID:222.0.0.2] orchRefs:[map[nodeName:node121 orchestrator:k8s]]] status:map[podCIDRs:[192.168.1.0/24]]]}
INFO[0000] Found resource helper: Resource(&TypeMeta{Kind:Node,APIVersion:projectcalico.org/v3,} projectcalico.org/v3, Kind=Node)
INFO[0000] Type of unpacked data: *v3.Node. Unpacked &{TypeMeta:{Kind:Node APIVersion:projectcalico.org/v3} ObjectMeta:{Name:node121 GenerateName: Namespace: SelfLink: UID:a77e209d-a0f5-44c0-9c71-45e6a9a8d55a ResourceVersion:113452 Generation:0 CreationTimestamp:2020-12-06 07:29:03 -0800 PST DeletionTimestamp:<nil> DeletionGracePeriodSeconds:<nil> Labels:map[beta.kubernetes.io/arch:amd64 beta.kubernetes.io/os:linux kubernetes.io/arch:amd64 kubernetes.io/hostname:node121 kubernetes.io/os:linux] Annotations:map[projectcalico.org/kube-labels:{"beta.kubernetes.io/arch":"amd64","beta.kubernetes.io/os":"linux","kubernetes.io/arch":"amd64","kubernetes.io/hostname":"node121","kubernetes.io/os":"linux"}] OwnerReferences:[] Finalizers:[] ClusterName: ManagedFields:[]} Spec:{BGP:0xc00007fa40 IPv4VXLANTunnelAddr: VXLANTunnelMACAddr: OrchRefs:[{NodeName:node121 Orchestrator:k8s}] Wireguard:<nil> Addresses:[{Address:10.10.10.121/24} {Address:10.10.10.121}]} Status:{WireguardPublicKey: PodCIDRs:[192.168.1.0/24]}}
INFO[0000] Finished parsing                              numResources=1 source=node121_new.yaml
INFO[0000] Converting resource to slice: [0xc00067c1a0]
INFO[0000] Converting resource to slice: &{{Node projectcalico.org/v3} {node121    a77e209d-a0f5-44c0-9c71-45e6a9a8d55a 113452 0 2020-12-06 07:29:03 -0800 PST <nil> <nil> map[beta.kubernetes.io/arch:amd64 beta.kubernetes.io/os:linux kubernetes.io/arch:amd64 kubernetes.io/hostname:node121 kubernetes.io/os:linux] map[projectcalico.org/kube-labels:{"beta.kubernetes.io/arch":"amd64","beta.kubernetes.io/os":"linux","kubernetes.io/arch":"amd64","kubernetes.io/hostname":"node121","kubernetes.io/os":"linux"}] [] []  []} {0xc00007fa40   [{node121 k8s}] <nil> [{10.10.10.121/24} {10.10.10.121}]} { [192.168.1.0/24]}}
INFO[0000] Returning slice: [0xc00067c1a0]
INFO[0000] Returning slice: [0xc00067c1a0]
INFO[0000] Config file: /etc/calico/calicoctl.cfg cannot be read - reading config from environment
INFO[0000] Loaded client config: apiconfig.CalicoAPIConfigSpec{DatastoreType:"kubernetes", EtcdConfig:apiconfig.EtcdConfig{EtcdEndpoints:"", EtcdDiscoverySrv:"", EtcdUsername:"", EtcdPassword:"", EtcdKeyFile:"", EtcdCertFile:"", EtcdCACertFile:"", EtcdKey:"", EtcdCert:"", EtcdCACert:""}, KubeConfig:apiconfig.KubeConfig{Kubeconfig:"/root/.kube/config", K8sAPIEndpoint:"", K8sKeyFile:"", K8sCertFile:"", K8sCAFile:"", K8sAPIToken:"", K8sInsecureSkipTLSVerify:false, K8sDisableNodePoll:false, K8sUsePodCIDR:false, KubeconfigInline:"", K8sClientQPS:0}}
INFO[0000] Client: {{{CalicoAPIConfig projectcalico.org/v3} {      0 {{0 0 <nil>}} <nil> <nil> map[] map[] [] []  []} {kubernetes {         } {/root/.kube/config      false false false  0}}} 0xc0003a6d40 0xc0001fbd50}
WARN[0000] Operation Create is not supported on Node type
INFO[0000] results: {FileInvalid:false NumResources:1 NumHandled:0 Err:<nil> SingleKind:Node Resources:[] ResErrs:[update conflict: Node(node121)] Client:{config:{TypeMeta:{Kind:CalicoAPIConfig APIVersion:projectcalico.org/v3} ObjectMeta:{Name: GenerateName: Namespace: SelfLink: UID: ResourceVersion: Generation:0 CreationTimestamp:{Time:{wall:0 ext:0 loc:<nil>}} DeletionTimestamp:<nil> DeletionGracePeriodSeconds:<nil> Labels:map[] Annotations:map[] OwnerReferences:[] Finalizers:[] ClusterName: ManagedFields:[]} Spec:{DatastoreType:kubernetes EtcdConfig:{EtcdEndpoints: EtcdDiscoverySrv: EtcdUsername: EtcdPassword: EtcdKeyFile: EtcdCertFile: EtcdCACertFile: EtcdKey: EtcdCert: EtcdCACert:} KubeConfig:{Kubeconfig:/root/.kube/config K8sAPIEndpoint: K8sKeyFile: K8sCertFile: K8sCAFile: K8sAPIToken: K8sInsecureSkipTLSVerify:false K8sDisableNodePoll:false K8sUsePodCIDR:false KubeconfigInline: K8sClientQPS:0}}} backend:0xc0003a6d40 resources:0xc0001fbd50}}
Failed to apply 'Node' resource: [update conflict: Node(node121)]

**Comment by song-jiang** [comment]
I think you should follow the yaml format for a node as https://www.tigera.io/blog/configuring-route-reflectors-in-calico/

Your yaml file seems to has extra fields not required.

**Comment by tscswcn** [comment]
I have fixed the issue, thanks!
