### ISSUE TITLE
Error while Installing an OpenShift 4.6 cluster with Calico on GCP

### ISSUE THREAD

**Issue by younus2019** [projectcalico/calico#4247]
I am following the below url for Installing an OpenShift 4.6 cluster with Calico on GCP, 
https://docs.projectcalico.org/getting-started/openshift/installation

after Updating the configuration file to use Calico, then i run below command to Create the cluster
$openshift-install create cluster

while running the create command it will generate below error:

```
$ openshift-install create cluster
INFO Credentials loaded from file "/..../.gcp/osServiceAccount.json"
INFO Consuming OpenShift Install (Manifests) from target directory
INFO Consuming Master Machines from target directory
INFO Consuming Worker Machines from target directory
INFO Consuming Openshift Manifests from target directory
INFO Consuming Common Manifests from target directory
INFO Creating infrastructure resources...
INFO Waiting up to 20m0s for the Kubernetes API at https://api...:6443...
INFO API v1.19.0+9f84db3 up
INFO Waiting up to 30m0s for bootstrapping to complete...
INFO Destroying the bootstrap resources...
INFO Waiting up to 40m0s for the cluster at https://api.....com:6443 to initialize...
ERROR Cluster operator authentication Degraded is True with IngressStateEndpoints_MissingSubsets::OAuthRouteCheckEndpointAccessibleController_SyncError::OAuthServerDeployment_DeploymentAvailableReplicasCheckFailed::OAuthServerRoute_InvalidCanonicalHost::OAuthServiceCheckEndpointAccessibleController_SyncError::OAuthServiceEndpointsCheckEndpointAccessibleController_SyncError::OAuthVersionDeployment_GetFailed::Route_InvalidCanonicalHost::WellKnownReadyController_SyncError: OAuthServiceEndpointsCheckEndpointAccessibleControllerDegraded: oauth service endpoints are not ready
OAuthServiceCheckEndpointAccessibleControllerDegraded: Get "https://.../healthz": dial tcp 172.30.249.3:443: connect: connection refused
IngressStateEndpointsDegraded: No subsets found for the endpoints of oauth-server
OAuthRouteCheckEndpointAccessibleControllerDegraded: route status does not have host address
WellKnownReadyControllerDegraded: failed to get oauth metadata from openshift-config-managed/oauth-openshift ConfigMap: configmap "oauth-openshift" not found (check authentication operator, it is supposed to create this)
RouteDegraded: Route is not available at canonical host oauth-openshift.apps.calico-os-cluster.test-edgeopenshift.com: route status ingress is empty
OAuthServerDeploymentDegraded: deployments.apps "oauth-openshift" not found
OAuthServerRouteDegraded: Route is not available at canonical host oauth-openshift.apps.calico-os-cluster.test-edgeopenshift.com: route status ingress is empty
OAuthVersionDeploymentDegraded: Unable to get OAuth server deployment: deployment.apps "oauth-openshift" not found
INFO Cluster operator authentication Available is False with APIServices_Error::OAuthServiceCheckEndpointAccessibleController_EndpointUnavailable::OAuthServiceEndpointsCheckEndpointAccessibleController_EndpointUnavailable::OAuthVersionDeployment_MissingDeployment::WellKnown_NotReady: APIServicesAvailable: "oauth.openshift.io.v1" is not ready: 503 (the server is currently unable to handle the request)
APIServicesAvailable: "user.openshift.io.v1" is not ready: 503 (the server is currently unable to handle the request)
OAuthServiceEndpointsCheckEndpointAccessibleControllerAvailable: Failed to get oauth-openshift enpoints
OAuthServiceCheckEndpointAccessibleControllerAvailable: Get "https://...:443/healthz": dial tcp 172.30.249.35:443: connect: connection refused
WellKnownAvailable: The well-known endpoint is not yet available: failed to get oauth metadata from openshift-config-managed/oauth-openshift ConfigMap: configmap "oauth-openshift" not found (check authentication operator, it is supposed to create this)
INFO Cluster operator image-registry Available is False with DeploymentNotFound: Available: The deployment does not exist
ImagePrunerAvailable: Pruner CronJob has been created
INFO Cluster operator image-registry Progressing is True with Error: Progressing: Unable to apply resources: unable to sync storage configuration: Get "https://www.googleapi
s.com/storage/v1/b/calico-os-cluster-kdwrp-image-registry-us-east1-etyilnmnjgsull?alt=json&prettyPrint=false&projection=full": oauth2: cannot fetch token: Post "https://oauth2.googleapis.com/token": dial tcp: i/o timeout
INFO Cluster operator ingress Available is False with IngressUnavailable: Not all ingress controllers are available.
INFO Cluster operator ingress Progressing is True with Reconciling: Not all ingress controllers are available.
ERROR Cluster operator ingress Degraded is True with IngressControllersDegraded: Some ingresscontrollers are degraded: default
INFO Cluster operator insights Disabled is False with AsExpected:
INFO Cluster operator insights UploadDegraded is True with UploadFailed: Unable to report: unable to build request to connect to Insights server: Post "https://cloud.redhat.com/api/ingress/v1/upload": dial tcp: i/o timeout
INFO Cluster operator monitoring Progressing is True with RollOutInProgress: Rolling out the stack.
ERROR Cluster operator monitoring Degraded is True with UpdatingTelemeterclientFailed: Failed to rollout the stack. Error: running task Updating Telemeter client failed: reconciling Telemeter client Prometheus Rule failed: updating PrometheusRule object failed: Internal error occurred: failed calling webhook "prometheusrules.openshift.io": Post "https://prometheus-operator.openshift-monitoring.svc:8080/admission-prometheusrules/validate?timeout=5s": context deadline exceeded
INFO Cluster operator monitoring Available is False with :
INFO Cluster operator openshift-apiserver Available is False with APIServices_Error: APIServicesAvailable: "apps.openshift.io.v1" is not ready: 503 (the server is currently unable to handle the request)
APIServicesAvailable: "authorization.openshift.io.v1" is not ready: 503 (the server is currently unable to handle the request)
APIServicesAvailable: "build.openshift.io.v1" is not ready: 503 (the server is currently unable to handle the request)
APIServicesAvailable: "project.openshift.io.v1" is not ready: 503 (the server is currently unable to handle the request)
APIServicesAvailable: "quota.openshift.io.v1" is not ready: 503 (the server is currently unable to handle the request)
APIServicesAvailable: "security.openshift.io.v1" is not ready: 503 (the server is currently unable to handle the request)
INFO Cluster operator openshift-samples Available is False with :
INFO Cluster operator operator-lifecycle-manager-packageserver Available is False with :
INFO Cluster operator operator-lifecycle-manager-packageserver Progressing is True with : Working toward 0.16.1
FATAL failed to initialize the cluster: Multiple errors are preventing progress:
* Could not update oauthclient "console" (379 of 617)
* Could not update prometheusrule "openshift-cloud-credential-operator/cloud-credential-operator-alerts" (525 of 617)
* Could not update prometheusrule "openshift-cluster-machine-approver/machineapprover-rules" (541 of 617)
* Could not update prometheusrule "openshift-cluster-samples-operator/samples-operator-alerts" (340 of 617)
* Could not update prometheusrule "openshift-cluster-version/cluster-version-operator" (9 of 617)
* Could not update prometheusrule "openshift-dns-operator/dns" (561 of 617)
* Could not update prometheusrule "openshift-ingress-operator/ingress-operator" (568 of 617)
* Could not update prometheusrule "openshift-kube-apiserver-operator/kube-apiserver-operator" (572 of 617)
* Could not update prometheusrule "openshift-kube-controller-manager-operator/kube-controller-manager-operator" (583 of 617)
* Could not update prometheusrule "openshift-kube-scheduler-operator/kube-scheduler-operator" (587 of 617)
* Could not update prometheusrule "openshift-machine-api/cluster-autoscaler-operator-rules" (240 of 617)
* Could not update prometheusrule "openshift-machine-api/machine-api-operator-prometheus-rules" (593 of 617)
* Could not update prometheusrule "openshift-machine-config-operator/machine-config-daemon" (595 of 617)
* Could not update prometheusrule "openshift-operator-lifecycle-manager/olm-alert-rules" (600 of 617)
* Could not update role "openshift-console-operator/prometheus-k8s" (555 of 617): resource may have been deleted
```

Please help me to resolve this issue and let me know anything logs needed. Thanks in advance!....

**Comment by lmm** [comment]
@younus2019 the issue you're seeing is an OpenShift-specific issue I think - can you double check by looking at the output of the tigera-operator in the `tigera-operator` namespace. Could you paste the output of its logs?

I've seen the error logs you're seeing on AWS when security group rules are missing.

**Comment by younus2019** [comment]
I have added tigera-operator log. please check
$ ./oc logs  tigera-operator-7fb84fc5ff-9xvc8 -n tigera-operator
2020/12/09 09:20:48 [INFO] Version: v1.13.0
2020/12/09 09:20:48 [INFO] Go Version: go1.14.4
2020/12/09 09:20:48 [INFO] Go OS/Arch: linux/amd64
I1209 09:20:49.265628       1 request.go:645] Throttling request took 1.034674282s, request: GET:https://...:443/apis/rbac.authorization.k8s.io/v1?timeout=32s
{"level":"info","ts":1607505662.0427606,"logger":"setup","msg":"Checking type of cluster","provider":"OpenShift"}
{"level":"info","ts":1607505662.04574,"logger":"setup","msg":"Checking if TSEE controllers are required","required":false}
{"level":"error","ts":1607505662.1747706,"logger":"typha_autoscaler","msg":"Failed to autoscale typha","error":"could not get number of nodes: the cache is not started, can not read objects","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\t/go/pkg/mod/github.com/go-logr/zapr@v0.1.0/zapr.go:128\ngithub.com/tigera/operator/pkg/controller/installation.(*typhaAutoscaler).start.func1\n\t/go/src/github.com/tigera/operator/pkg/controller/installation/typha_autoscaler.go:122"}
{"level":"info","ts":1607505662.1751385,"logger":"setup","msg":"starting manager"}
I1209 09:21:02.175433       1 leaderelection.go:243] attempting to acquire leader lease  tigera-operator/operator-lock...
I1209 09:21:19.410010       1 leaderelection.go:253] successfully acquired lease tigera-operator/operator-lock
{"level":"info","ts":1607505679.410879,"logger":"controller","msg":"Starting EventSource","controller":"tigera-installation-controller","source":"kind source: /, Kind="}
{"level":"info","ts":1607505679.5236266,"logger":"controller","msg":"Starting EventSource","controller":"tigera-installation-controller","source":"kind source: /, Kind="}
{"level":"info","ts":1607505679.6498709,"logger":"controller","msg":"Starting EventSource","controller":"tigera-installation-controller","source":"kind source: /V1, Kind=Secret"}
{"level":"info","ts":1607505680.2509625,"logger":"controller","msg":"Starting EventSource","controller":"tigera-installation-controller","source":"kind source: /V1, Kind=ConfigMap"}
{"level":"info","ts":1607505680.7518907,"logger":"controller","msg":"Starting EventSource","controller":"tigera-installation-controller","source":"kind source: /, Kind="}
{"level":"info","ts":1607505680.8524163,"logger":"controller","msg":"Starting EventSource","controller":"tigera-installation-controller","source":"kind source: /, Kind="}
{"level":"info","ts":1607505680.9532735,"logger":"controller","msg":"Starting EventSource","controller":"tigera-installation-controller","source":"kind source: /, Kind="}
{"level":"info","ts":1607505681.0550041,"logger":"controller","msg":"Starting EventSource","controller":"tigera-installation-controller","source":"kind source: /, Kind="}
{"level":"info","ts":1607505681.1558104,"logger":"controller","msg":"Starting EventSource","controller":"tigera-installation-controller","source":"kind source: /, Kind="}
W1209 09:21:21.159586       1 warnings.go:67] apiregistration.k8s.io/v1beta1 APIService is deprecated in v1.19+, unavailable in v1.22+; use apiregistration.k8s.io/v1 APIService
W1209 09:21:21.164961       1 warnings.go:67] apiregistration.k8s.io/v1beta1 APIService is deprecated in v1.19+, unavailable in v1.22+; use apiregistration.k8s.io/v1 APIService
{"level":"info","ts":1607505681.256315,"logger":"controller","msg":"Starting EventSource","controller":"tigera-installation-controller","source":"kind source: /, Kind="}
{"level":"info","ts":1607505681.3569188,"logger":"controller","msg":"Starting Controller","controller":"tigera-installation-controller"}
{"level":"info","ts":1607505681.3570905,"logger":"controller","msg":"Starting workers","controller":"tigera-installation-controller","worker count":1}
W1209 09:21:21.608788       1 warnings.go:67] scheduling.k8s.io/v1beta1 PriorityClass is deprecated in v1.14+, unavailable in v1.22+; use scheduling.k8s.io/v1 PriorityClass
W1209 09:21:21.611165       1 warnings.go:67] scheduling.k8s.io/v1beta1 PriorityClass is deprecated in v1.14+, unavailable in v1.22+; use scheduling.k8s.io/v1 PriorityClass
W1209 09:21:21.715054       1 warnings.go:67] scheduling.k8s.io/v1beta1 PriorityClass is deprecated in v1.14+, unavailable in v1.22+; use scheduling.k8s.io/v1 PriorityClass
{"level":"info","ts":1607505682.2818322,"logger":"status_manager","msg":"Failed to update tigera status","error":"Operation cannot be fulfilled on tigerastatuses.operator.tigera.io \"calico\": the object has been modified; please apply your changes to the latest version and try again"}
W1209 09:21:22.342263       1 warnings.go:67] scheduling.k8s.io/v1beta1 PriorityClass is deprecated in v1.14+, unavailable in v1.22+; use scheduling.k8s.io/v1 PriorityClass
W1209 09:21:22.486216       1 warnings.go:67] scheduling.k8s.io/v1beta1 PriorityClass is deprecated in v1.14+, unavailable in v1.22+; use scheduling.k8s.io/v1 PriorityClass
W1209 09:21:22.641869       1 warnings.go:67] scheduling.k8s.io/v1beta1 PriorityClass is deprecated in v1.14+, unavailable in v1.22+; use scheduling.k8s.io/v1 PriorityClass
W1209 09:21:22.832559       1 warnings.go:67] scheduling.k8s.io/v1beta1 PriorityClass is deprecated in v1.14+, unavailable in v1.22+; use scheduling.k8s.io/v1 PriorityClass
W1209 09:21:23.051810       1 warnings.go:67] scheduling.k8s.io/v1beta1 PriorityClass is deprecated in v1.14+, unavailable in v1.22+; use scheduling.k8s.io/v1 PriorityClass
W1209 09:21:23.299050       1 warnings.go:67] scheduling.k8s.io/v1beta1 PriorityClass is deprecated in v1.14+, unavailable in v1.22+; use scheduling.k8s.io/v1 PriorityClass
...

**Comment by lmm** [comment]
I think I might know this is. For OpenShift on AWS, the tigera-operator handles adding extra security group rules that Calico requires: https://github.com/tigera/operator/blob/master/pkg/awssgsetup/aws_security_group_setup.go#L92-L121

In order to get this to work in GCE I think you'll need equivalent firewall rules applied to the cluster nodes. @tmjd does that sound right to you?

**Comment by tmjd** [comment]
Yes those ports and protocol will need to be allowed. To summarize you need to allow between all k8s hosts (workers and control plane) the IPIP protocol (4) and tcp ports 179 and 5473.
I think it is hard to tell, especially with OCP, if this is the problem but certainly something that should be configured or verified that the traffic is allowed.
