### ISSUE TITLE
[Help Wanted] ipamhandles is increased and these bloating the data size of etcd

### ISSUE THREAD

**Issue by Bo0km4n** [projectcalico/calico#4259]
## Expected Behavior
ipamhandles will be compressed over a period of time

## Current Behavior

![image](https://user-images.githubusercontent.com/15085723/102318628-fdd61780-3fbc-11eb-98bf-b0adb671014c.png)

ipamhandles objects are increased.
Do you know how to reduce the increase?

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Calico version: 3.14
* Orchestrator version (e.g. kubernetes, mesos, rkt): kubernetes=1.18.5
* Operating System and version: Ubuntu 18.04
* Link to your project (optional):

**Comment by caseydavenport** [comment]
@Bo0km4n it's not uncommon to have lots of IPAM handles - an IPAM handle gets created for every pod that gets assigned an IP address from Calico. 

Are you seeing problems as a result of this? Are you seeing more handles than there are pods in the cluster?

**Comment by Bo0km4n** [comment]
@caseydavenport I got resolved this problem.
The causes is I forgot deploy `calico-kube-controllers` . 
But I'm not sured how calico-kube-controllers to garbage collect ipamhandles resource.
Do you know this logic ?

**Comment by mgleung** [comment]
@Bo0km4n I believe the logic you are looking for is found in the node controller. Or more specifically here: https://github.com/projectcalico/kube-controllers/blob/master/pkg/controllers/node/ipam.go#L181
