### ISSUE TITLE
calico-ipam generates a large number of core files, causing the disk to fill up

### ISSUE THREAD

**Issue by charnet1019** [projectcalico/calico#4270]
os: CentOS Linux release 7.8.2003 (Core)
kernel: 4.18.9-1.el7.elrepo.x86_64
calico-ipam: v3.13.4

![image](https://user-images.githubusercontent.com/18616254/102564513-916f2b80-4116-11eb-8311-8851456b115e.png)

**Comment by lwr20** [comment]
Can you add kubelet logs and an example corefile please?

Also would be great if you could provide enough information for us to attempt to repro this - e.g. what version of k8s, what you used to install k8s, how you installed Calico, what you're doing at the time of hitting this, etc, etc.

**Comment by fasaxc** [comment]
If you can't share the core file then please bear in mind that Calico is written in Golang so you'll probabaly have more luck with the delve debugger rather than gdb.

**Comment by charnet1019** [comment]
By rancher v2.4.5 to manager k8s, k8s version is v1.18.6. 
[core.zip](https://github.com/projectcalico/calico/files/5739732/core.zip)

**Comment by charnet1019** [comment]
@lwr20 @fasaxc   hi, add kubelet log.
First remove the ending .zip, and then unzip all the files.

[kubelet_log.zip.001.zip](https://github.com/projectcalico/calico/files/5741898/kubelet_log.zip.001.zip)

**Comment by charnet1019** [comment]
[kubelet_log.zip.002.zip](https://github.com/projectcalico/calico/files/5741902/kubelet_log.zip.002.zip)

**Comment by charnet1019** [comment]
[kubelet_log.zip.003.zip](https://github.com/projectcalico/calico/files/5741903/kubelet_log.zip.003.zip)

**Comment by charnet1019** [comment]
[kubelet_log.zip.004.zip](https://github.com/projectcalico/calico/files/5741905/kubelet_log.zip.004.zip)

**Comment by charnet1019** [comment]
[kubelet_log.zip.005.zip](https://github.com/projectcalico/calico/files/5741906/kubelet_log.zip.005.zip)

**Comment by charnet1019** [comment]
[kubelet_log.zip.006.zip](https://github.com/projectcalico/calico/files/5741907/kubelet_log.zip.006.zip)

**Comment by fasaxc** [comment]
Unfortunately, looks like our binary is stripped of debug information so I couldn't make much of the corefile.  @charnet1019 are you still hitting this?  Best option is probably to build a debug build of CNI plugin so we can get something from the corefile.

**Comment by charnet1019** [comment]
I can not hitting this now after replace a CNI plugin from other machine. I will close this issue first. Thanks
