### ISSUE TITLE
calico-bpf routes dump failed 

### ISSUE THREAD

**Issue by tscswcn** [projectcalico/calico#4275]
calico-bpf routes dump failed, get error messages:
ERRO[0000] Failed to dump routes map.                    error="failed to open map: stat /sys/fs/bpf/tc/globals/cali_v4_routes: no such file or directory" 

## Expected Behavior

comannd run well, no error report

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Calico version
* Orchestrator version (e.g. kubernetes, mesos, rkt):
* Operating System and version:
* Link to your project (optional):

root@node-10-120-13-236:~# calicoctl  version
Client Version:    v3.17.0
Git commit:        0e7fc7f7
Cluster Version:   v3.16.5
Cluster Type:      k8s,bgp,kubeadm,kdd,typha
root@node-10-120-13-236:~#         

root@node-10-120-13-236:~# cat /etc/os-release
NAME="Ubuntu"
VERSION="18.04.5 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.5 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

root@node-10-120-13-***:~# kubectl get nodes -o wide
NAME                  STATUS   ROLES                 AGE   VERSION    INTERNAL-IP      EXTERNAL-IP   OS-IMAGE             KERNEL-VERSION       CONTAINER-RUNTIME
node-10-120-127-****   Ready    edge,node             4d    v1.18.12   10.120.127.235   <none>        Ubuntu 18.04.5 LTS   4.15.0-112-generic   containerd://1.2.13
node-10-120-127-***   Ready    edge,node             4d    v1.18.12   10.120.127.236   <none>        Ubuntu 18.04.5 LTS   4.15.0-112-generic   containerd://1.2.13
node-10-120-127-***   Ready    node                  4d    v1.18.12   10.120.127.237   <none>        Ubuntu 18.04.5 LTS   4.15.0-112-generic   containerd://1.2.13
node-10-120-1**-238   Ready    node                  4d    v1.18.12   10.120.127.238   <none>        Ubuntu 18.04.5 LTS   4.15.0-112-generic   containerd://1.2.13
node-10-120-**-236    Ready    controlplane,master   4d    v1.18.12   10.120.13.236    <none>        Ubuntu 18.04.5 LTS   4.15.0-112-generic   containerd://1.2.13
node-10-120-13-**7    Ready    controlplane,master   4d    v1.18.12   10.120.13.237    <none>        Ubuntu 18.04.5 LTS   4.15.0-112-generic   containerd://1.2.13
node-10-120-13-**8    Ready    controlplane,master   4d    v1.18.12   10.120.13.238    <none>        Ubuntu 18.04.5 LTS   4.15.0-112-generic   containerd://1.2.13

root@node-10-120-13-236:~#                                                                                                                                          
 calico-bpf routes dump
ERRO[0000] Failed to dump routes map.                    error="failed to open map: stat /sys/fs/bpf/tc/globals/cali_v4_routes: no such file or directory"

**Comment by tomastigera** [comment]
calico-bpf needs to execute in the calico-node pod

**Comment by fasaxc** [comment]
Your kernel is too old to run BPF mode so no maps will be created.

**Comment by tscswcn** [comment]
> calico-bpf needs to execute in the calico-node pod, the host itself does not have the right directories mounted / created

But I have question, because there are few tools within calico node image,how can I do it? is there package can be executed?

**Comment by tscswcn** [comment]
> Your kernel is too old to run BPF mode so no maps will be created.

this time,  it has been 
 uname -sr
Linux 5.10.2-051002-generic

still have this  issue

**Comment by tomastigera** [comment]
what is the distro? We had an issue with eks Bottlerocket because the bpffs is mounted in a wrong place.
