### ISSUE TITLE
Calico pod Intermittently triggers probe failed events

### ISSUE THREAD

**Issue by tanvp112** [projectcalico/calico#4276]
Strange situation here where Calico pod running on worker nodes intermittently fires event:

NAMESPACE     LAST SEEN   TYPE      REASON      OBJECT                  MESSAGE
...
kube-system         0s          Warning   Unhealthy   pod/calico-node-bfmh5   Readiness probe failed:
kube-system         0s          Warning   Unhealthy   pod/calico-node-bfmh5   Liveness probe failed:

kubectl version:
Client Version: v1.20.1
Server Version: v1.20.1

calicoctl version:
Client Version:    v3.17.1
Git commit:        8871aca3
Cluster Version:   v3.17.1
Cluster Type:      k8s,bgp,kubeadm,kdd

Tailing the log does not show any error or warning. Appreciate if anyone can provide a pointer for further root cause investigation.

[calico-node-bfmh5.log](https://github.com/projectcalico/calico/files/5728144/calico-node-bfmh5.log)

**Comment by lmm** [comment]
Hi @tanvp112 . So the calico node pods are only intermittently causing the failed probes events? Do you know if it is the same calico node pods doing this?

**Comment by tanvp112** [comment]
Hi @lmm, yes, but i would like to understand why is it and not let Kubernetes thinks these pods are "in trouble" and restart it unexpectedly. These events happened on **worker** nodes only.  i suspect there is a latency somewhere... unfortunately i can't find any clue in calico nor kubelet logs.

**Comment by eplightning** [comment]
Might be related to https://kubernetes.io/blog/2020/12/08/kubernetes-1-20-release-announcement/#exec-probe-timeout-handling since you're using K8s 1.20 and calico use exec probes without timeout set - so it defaults to 1s which might be enough.

Try changing _timeoutSeconds_ on exec probes to some higher value.

**Comment by tanvp112** [comment]
The cluster is version 1.20.1. The issue you mentioned is before 1.20.0. On top of that, calico 3.17.1 timeoutSeconds is 1. Tested pod to pod 1k pings average is under 12ms.

Normally there is error message following the readiness probe failed event, in this case all were empty.,,
