### ISSUE TITLE
disable Outgoing nat 

### ISSUE THREAD

**Issue by ayoubsmii19** [projectcalico/calico#4277]
Hi , is there any way to disable outgoing nat in calico ? 
i tried with modifying the pool.yaml like bellow 
apiVersion: projectcalico.org/v3
kind: IPPool
metadata:
  creationTimestamp: "2020-12-22T18:50:30Z"
  name: default-ipv4-ippool
  resourceVersion: "9759"
  uid: 625a4417-5c54-44b2-a764-0c4d1aa98a81
spec:
  blockSize: 26
  cidr: 192.168.0.0/16
  ipipMode: Never
  natOutgoing: false
  nodeSelector: all()
  vxlanMode: Never

#calicoctl apply -f pool.yaml 

But the problem is after this configuration i can't reach internet :/

**Comment by caseydavenport** [comment]
Yes, that disables outgoing NAT. As a result, you won't be able to access the internet, because NAT is required for that.
