### ISSUE TITLE
pod internal communication, a large number of tcp restransmission

### ISSUE THREAD

**Issue by NadamHL** [projectcalico/calico#4278]
![image](https://user-images.githubusercontent.com/39847290/102957062-6e78b900-4514-11eb-84a0-8d8adae685fc.png)

![image](https://user-images.githubusercontent.com/39847290/102957080-7c2e3e80-4514-11eb-8951-759aa49b5903.png)

**Comment by NadamHL** [comment]
kernel: 4.4.198
centos: CentOS Linux release 7.6.1810 (Core)

**Comment by caseydavenport** [comment]
Please fill out the issue template when filing issues. There's not enough information in this issue to get started diagnosing or reproducing the issue.

I'd also strongly recommend upgrading. Calico v3.8 is very much out-of-support at this point in time.
