### ISSUE TITLE
calico-bpf routes dump failed, get error messages:

### ISSUE THREAD

**Issue by tscswcn** [projectcalico/calico#4281]
calico-bpf routes dump failed, get error messages:
ERRO[0000] Failed to dump routes map. error="failed to open map: stat /sys/fs/bpf/tc/globals/cali_v4_routes: no such file or directory"

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Calico version
* Orchestrator version (e.g. kubernetes, mesos, rkt):
* Operating System and version:
* Link to your project (optional):
 calicoctl version
Client Version: v3.17.0
Git commit: 0e7fc7f7
Cluster Version: v3.16.5
Cluster Type: k8s,bgp,kubeadm,kdd,typha
root@node-10-120-13-236:#

 cat /etc/os-release
NAME="Ubuntu"
VERSION="18.04.5 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.5 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
root@node-10-120-13-236:~# uname -sr
Linux 5.10.2-051002-generic

root@node-10-120-13-236:~# kubectl get nodes -o wide
NAME                  STATUS   ROLES                 AGE     VERSION    INTERNAL-IP      EXTERNAL-IP   OS-IMAGE             KERNEL-VERSION          CONTAINER-RUNTIME
node-10-120-127-235   Ready    edge,node             5d17h   v1.18.12   10.120.127.235   <none>        Ubuntu 18.04.5 LTS   4.15.0-112-generic      containerd://1.2.13
node-10-120-127-236   Ready    edge,node             5d17h   v1.18.12   10.120.127.236   <none>        Ubuntu 18.04.5 LTS   4.15.0-112-generic      containerd://1.2.13
node-10-120-127-237   Ready    node                  5d17h   v1.18.12   10.120.127.237   <none>        Ubuntu 18.04.5 LTS   4.15.0-112-generic      containerd://1.2.13
node-10-120-127-238   Ready    node                  5d17h   v1.18.12   10.120.127.238   <none>        Ubuntu 18.04.5 LTS   4.15.0-112-generic      containerd://1.2.13
node-10-120-13-236    Ready    controlplane,master   5d17h   v1.18.12   10.120.13.236    <none>        Ubuntu 18.04.5 LTS   5.10.2-051002-generic   containerd://1.2.13
node-10-120-13-237    Ready    controlplane,master   5d17h   v1.18.12   10.120.13.237    <none>        Ubuntu 18.04.5 LTS   4.15.0-112-generic      containerd://1.2.13
node-10-120-13-238    Ready    controlplane,master   5d17h   v1.18.12   10.120.13.238    <none>        Ubuntu 18.04.5 LTS   4.15.0-112-generic      containerd://1.2.13
root@node-10-120-13-236:~#

**Comment by tscswcn** [comment]
sorry  Iwill try in thr pod

**Comment by tscswcn** [comment]
But I have question,  because there are few tools within calico node image,how can I do it? is there package can be executed?

**Comment by caseydavenport** [comment]
We don't ship the debug tools in calico/node in order to keep the deliverable small. Debug tools should be installed separately.
