### ISSUE TITLE
Capybara quest softlock

### ISSUE THREAD

**Issue by BreezyBird** [projectcalico/calico#4282]
There's this quest i got in onsen where i need to find 3 missing capybara scattered in the mountains, it was almost 12am in the game when i found 2 of them and i decided to run back to the cafe and have my character sleep, because at the time i assumed that my character would collapse like in my time at portia or stardew valley.

After i did that i went back up the mountain to find the last capybara but i couldn't find him anywhere, when i went back to onsen he was already there but the game thought he was still missing, no matter what i tried the game kept thinking i only found 2 of them so now im softlocked from all the onsen quests.

**Comment by BreezyBird** [comment]
This is where im supposed to send complaints about video game bugs in the new calico game right?

**Comment by BreezyBird** [comment]
I didn't mean to close it oops

**Comment by tmjd** [comment]
This repository is for the Calico CNI plugin docs.projectcalico.org, not a video game. Check the [README](https://github.com/projectcalico/calico/blob/master/README.md) for more details.
