### ISSUE TITLE
Secret of the witching woods quest glitch

### ISSUE THREAD

**Issue by Clexashipper** [projectcalico/calico#4285]
it  will not let me complete the mission, I have the toy complete but when I equip the toy and walk up to the giant kitty nothing happens. I have tried just about everything to fix it. 

## Expected Behavior

I am assuming when I equip the toy the cat should respond by moving out of the way so I can get to the woods.

## Current Behavior
instead of moving the cat sleeps, he continues to do nothing and sort of ignores me. 

## Possible Solution
He could've glitched because of my horse? he sort of ran through him?

## Steps to Reproduce (for bugs)

1. Mount the horse
2. he will run through the large cat
3. equip the mouse
4. cat will ignore you 

## Context
I am trying to get to the woods so I can find more animals and get to Rosa. I really want to be able to complete this quest.

## Your Environment
* Calico version : i’m not sure where to find this? 
* Operating System and version: Xbox one S

**Comment by toacoco** [comment]
I'm having this same issue on Nintendo Switch. The rest of the game works beautifully, but the large cat slides more and more away from the entrance to the new area while an invisible wall still blocks it. The large cat doesn't respond to the giant mouse toy at all. Closing and reopening the game did not solve this, nor did going back to the cafe and sleeping.

**Comment by bubearchan** [comment]
I was having the same problem on nintendo switch, but figured something out. If you keep holding the toy and walking along the invisible barrier between the cat and the path it wakes up eventually and you can open the area. (hope this helps :) )

**Comment by Clexashipper** [comment]
that does thank you! I got it to work by restarting my xbox. I don’t know why it didn’t work for a bit there

**Comment by Clexashipper** [comment]
> I'm having this same issue on Nintendo Switch. The rest of the game works beautifully, but the large cat slides more and more away from the entrance to the new area while an invisible wall still blocks it. The large cat doesn't respond to the giant mouse toy at all. Closing and reopening the game did not solve this, nor did going back to the cafe and sleeping.


Have you tried turning the console completely off then back on? that solved it for me
