### ISSUE TITLE
Dapper doves do dastardly deeds quest not working

### ISSUE THREAD

**Issue by Clexashipper** [projectcalico/calico#4286]
The quest glitched out, I picked up each bird and it is not letting me have the keys. It says I poked up 7/5 birds and everytime I talk to Maribel she just says “have you had any luck finding my keys?” and then sort of shoo’s me to go back to picking up the birds.

## Expected Behavior
Since I picked up all of the birds I am assuming she should have responded differently. My guess is by saying I have found her keys and thanking me? I cannot find a video anywhere to see how it should properly work or what exactly I am doing wrong here.

## Current Behavior
It says I picked up more birds than there are and there are no keys, even though Maribel insists that one of those birds has them and that I need to keep picking them up until I find said keys. 

## Possible Solution
I am not sure, maybe figure out if it was a mistake of not giving one of the birds the keys on the xbox version? 

## Steps to Reproduce (for bugs)

1. Ask Maribel if she needs help
2. she will tell you the birds have stolen her keys as well as accessories
3. pick up the birds
4. It will go up to 7/5 
5. speak to Maribel
6. she will ask you if you had any luck with finding her keys.

## Context
I am trying to accomplish finishing this mission, I don’t really like having incomplete tasks on my quest log. I like to complete them as soon as possible and I feel bad for completing every other task except hers. 

## Your Environment

* Calico version: no idea where to find this. 
* Orchestrator version (e.g. kubernetes, mesos, rkt): Not sure where to find this. 
* Operating System and version: Xbox one s

**Comment by fasaxc** [comment]
I think you've found the wrong issue tracker.  This one is for the Project Calico networking and security tool; I think you're looking for this discord server: https://discord.com/invite/2RfZQpx
