### ISSUE TITLE
[Question Consultation] How to access pod ip directly from external network?

### ISSUE THREAD

**Issue by W-BC0001** [projectcalico/calico#4296]
## My Environment

name | version
| - | -
| Calico | rancher/calico-node:v3.7.4
| Orchestrator version (e.g. kubernetes, mesos, rkt) | kubernetes v1.15.5
| Operating System and version | CentOS Linux release 7.7.1908 (Core)

## Network information

name | network
| - | -
The office network | 192.168.8.0/24
kubernetes node ip | 192.168.33.0/24
pod ip | 10.42.0.0/16
route reflector | 192.168.33.210(One of the Kubernetes nodes)

## Expected Behavior
`192.168.8.0/24` can be accessed via the route reflector `10.42.0.0/16`

## Current Behavior  

I think I started calico BGP according to the official documentation, and then I configured one of the Kubernetes nodes as a route reflector. `192.168.8.0/24` found `10.42.0.0/16` through the route reflector.

I referred to [Configure BGP peering](https://docs.projectcalico.org/networking/bgp), #2473, [Calico 3.6 forwards external traffic to the cluster Pod](https://mritd.com/2019/06/18/calico-3.6-forward-network-traffic/), but it didn't work for me

## The following is the YAML file that I configured
default-bgpconfig.yaml
```shell
---
apiVersion: projectcalico.org/v3
kind: BGPConfiguration
metadata:
  name: default
spec:
  logSeverityScreen: Info
  nodeToNodeMeshEnabled: false
  asNumber: 63400
```

rr.yaml
```shell
---
kind: BGPPeer
apiVersion: projectcalico.org/v3
metadata:
  name: peer-to-rrs
spec:
  nodeSelector: "!has(route-reflector)"
  peerSelector: has(route-reflector)
---
kind: BGPPeer
apiVersion: projectcalico.org/v3
metadata:
  name: rr-mesh
spec:
  nodeSelector: has(route-reflector)
  peerSelector: has(route-reflector)
```

k8s-mgr-node.yaml
```shell
apiVersion: projectcalico.org/v3
kind: Node
metadata:
  labels:
    beta.kubernetes.io/arch: amd64
    beta.kubernetes.io/os: linux
    kubernetes.io/arch: amd64
    kubernetes.io/hostname: k8s-mgr
    kubernetes.io/os: linux
    node-role.kubernetes.io/controlplane: "true"
    node-role.kubernetes.io/etcd: "true"
    route-reflector: "true"
  name: k8s-mgr
spec:
  addresses:
  - address: 192.168.33.210/24
  - address: 192.168.33.210
  bgp:
    ipv4Address: 192.168.33.210/24
    ipv4IPIPTunnelAddr: 10.42.181.78
    routeReflectorClusterID: 244.0.0.1
  orchRefs:
  - nodeName: k8s-mgr
    orchestrator: k8s
```

ippool.yaml
```shell
apiVersion: projectcalico.org/v3
kind: IPPool
metadata:
  name: default-ipv4-ippool
spec:
  blockSize: 26
  cidr: 10.42.0.0/16
  ipipMode: CrossSubnet
  natOutgoing: true
  nodeSelector: all()
  vxlanMode: Never
```

## calicoctl node status

```shell
# calicoctl node status
Calico process is running.

IPv4 BGP status
+--------------+---------------+-------+----------+-------------+
| PEER ADDRESS |   PEER TYPE   | STATE |  SINCE   |    INFO     |
+--------------+---------------+-------+----------+-------------+
| 192.168.33.7 | node specific | up    | 14:11:23 | Established |
+--------------+---------------+-------+----------+-------------+

IPv6 BGP status
No IPv6 peers found.
```

## Traceroute

The route reflector does forward the external traffic to the pod's corresponding Kubernetes node, but the Kubernetes node doesn't know where to forward.

```shell
# traceroute 10.42.209.252
traceroute to 10.42.209.252 (10.42.209.252), 30 hops max, 60 byte packets
 1  gateway (192.168.8.254)  0.868 ms  1.343 ms  1.751 ms
 2  k8s-mgr (192.168.33.210)  0.390 ms  0.345 ms  0.337 ms
 3  k8s-test04 (192.168.33.7)  0.619 ms  0.582 ms  0.539 ms
 4  * * *
 5  * * *
 6  * * *
 7  * * *
 8  * * *
 9  * * *
10  * * *
11  * * *
12  * * *
13  * * *
14  * * *
15  * * *
16  * * *
17  * * *
18  * * *
19  * * *
20  * * *
21  * * *
22  * * *
23  * * *
24  * * *
25  * * *
26  * * *
27  * * *
28  * * *
29  * * *
30  * * *
```

## The routing table

192.168.33.210
```shell
$ route -n
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
10.42.181.64    0.0.0.0         255.255.255.192 U     0      0        0 *
10.42.181.76    0.0.0.0         255.255.255.255 UH    0      0        0 calicfa5f2c3d88
10.42.181.77    0.0.0.0         255.255.255.255 UH    0      0        0 calide1f926b305
10.42.209.192   192.168.33.7    255.255.255.192 UG    0      0        0 em1
172.17.0.0      0.0.0.0         255.255.0.0     U     0      0        0 docker0
192.168.33.0    0.0.0.0         255.255.255.0   U     104    0        0 em1
```

192.168.33.7
```shell
$ route -n
...
10.42.209.252   0.0.0.0         255.255.255.255 UH    0      0        0 cali7328bc5811c
...
```

**Comment by caseydavenport** [comment]
Have you configured a BGP peer between the route reflector and your office network routers? I don't see any configuration to do that shown. How does your office network know to send traffic to the Kubernetes cluster?

Typically, a route reflector is not intended to be used as a "gateway" of sorts, rather it just re-advertises routing information. In other words, you wouldn't normally have traffic routed through the RR, it should go direct to the relevant Kubernetes node.

**Comment by W-BC0001** [comment]
Thank you for your reply @caseydavenport 

## How does your office network know to send traffic to the Kubernetes cluster?

I set up the route on my office router, which is a three-tier device

Routing rules are as follows:
```
ip route-static 10.42.0.0 16 192.168.33.210
ip route-static 10.43.0.0 16 192.168.33.210
```

## In other words, you wouldn't normally have traffic routed through the RR, it should go direct to the relevant Kubernetes node.

We tried to set up a route on the office router to forward the external traffic directly to a kubernetes node and through the kubernetes node to the pod, but this did not work.

```shell
del: 
ip route-static 10.42.0.0 16 192.168.33.210

add:
ip route-static 10.42.209.192 26 192.168.33.7
```

The rule is the same as above, However, after the traffic arrives, the node will not forward the traffic.

```shell
$ traceroute 10.42.209.252
traceroute to 10.42.209.252 (10.42.209.252), 30 hops max, 60 byte packets
 1  gateway (192.168.8.254)  0.840 ms  1.267 ms  1.690 ms
 2  k8s-test04 (192.168.33.7)  0.334 ms  0.266 ms  0.235 ms
 3  * * *
 4  * * *
 5  * * *
 6  * * *
 7  * * *
 8  * * *
 9  * * *
10  * * *
11  * * *
12  * * *
13  * * *
14  * * *
15  * * *
16  * * *
17  * * *
18  * * *
19  * * *
20  * * *
21  * * *
22  * * *
23  * * *
24  * * *
25  * * *
26  * * *
27  * * *
28  * * *
29  * * *
30  * * *
```

**Comment by lwr20** [comment]
Does k8s-test04 have a route back to the office subnet?

**Comment by W-BC0001** [comment]
Thank you for your reply @lwr20 

## Does k8s-test04 have a route back to the office subnet?

Yes.
`192.168.8.0` and `192.169.33.0` are connected directly via routers on which routing rules are configured.

```shell
k8s-test04 $ traceroute 192.168.8.251

traceroute to 192.168.8.251 (192.168.8.251), 30 hops max, 60 byte packets
 1  gateway (192.168.33.1)  0.875 ms  1.173 ms  1.552 ms
 2  server03 (192.168.8.251)  0.291 ms  0.278 ms  0.333 ms
```

```shell
k8s-test04 $ ping -c 4 192.168.8.251

PING 192.168.8.251 (192.168.8.251) 56(84) bytes of data.
64 bytes from 192.168.8.251: icmp_seq=1 ttl=63 time=0.419 ms
64 bytes from 192.168.8.251: icmp_seq=2 ttl=63 time=0.162 ms
64 bytes from 192.168.8.251: icmp_seq=3 ttl=63 time=0.131 ms
64 bytes from 192.168.8.251: icmp_seq=4 ttl=63 time=0.161 ms

--- 192.168.8.251 ping statistics ---
4 packets transmitted, 4 received, 0% packet loss, time 2999ms
rtt min/avg/max/mdev = 0.131/0.218/0.419/0.117 ms
```

## I want to know
If kubernetes uses calico network and only adds routing rules, will external networks have direct access to pod?
Or do I need to add extra configuration?

**Comment by lwr20** [comment]
If kubernetes uses calico network and only adds routing rules, will external networks have direct access to podhttps://docs.projectcalico.org/networking/determine-best-networking#pod-ip-routability-outside-of-the-cluster

**Comment by lwr20** [comment]
One of the points in that doc is that if you're using an overlay network, the pods will not be routable.  I see that you have `vxlanMode=CrossSubnet` - that's an overlay network and may stop the pods from being routable.  If you're peering Calico into the infrastructure network, you shouldn't need CrossSubnet mode anyway.  Try setting `vxlanMode=Never`.

If you wanted to discuss debugging your config in near real-time, we have a slack channel go to http://slack.projectcalico.org/ to get an invite.
