### ISSUE TITLE
Is it necessery to " Drop IPIP packets from non-Calico hosts "

### ISSUE THREAD

**Issue by hhstu** [projectcalico/calico#4297]
when use ipip, i find a Chain cali-INPUT ,  it will drop IPIP packets from non-Calico hosts.
but i want access  pod  form  non-Calico hosts(such  as develop env).    how du you think  add a switch  about add this  Chain ?

**Comment by hhstu** [comment]
```json
[root@vm1 ~]# iptables -L -n -v   |grep    Drop    -C   2
 pkts bytes target     prot opt in     out     source               destination         
  231 55915 ACCEPT     4    --  *      *       0.0.0.0/0            0.0.0.0/0            /* cali:PajejrV4aFdkZojI */ /* Allow IPIP packets from Calico hosts */ match-set cali40all-hosts-net src ADDRTYPE match dst-type LOCAL
  172 17888 DROP       4    --  *      *       0.0.0.0/0            0.0.0.0/0            /* cali:_wjq-Yrma8Ly1Svo */ /* Drop IPIP packets from non-Calico hosts */
```

**Comment by hhstu** [comment]
i  enen find some IPIP packets  has  been drop which not calcio tunnel

**Comment by hhstu** [comment]
ExternalNodesCIDRList

**Comment by 666zero** [comment]
hi,i have a same question,we need to add the extra node to access the non-Calico hosts.

**Comment by 666zero** [comment]
can you provide the plan of ExternalNodesCIDRList ? thanks

**Comment by 666zero** [comment]
@hhstu

**Comment by hhstu** [comment]
https://projectcalico.docs.tigera.io/reference/felix/configuration  看下这个链接会介绍 ExternalNodesCIDRList   @666zero

**Comment by 666zero** [comment]
你好，我这边在calico的配置文件中加上FELIX_EXTERNALNODESCIDRLIST，iptables中还是出现DROP规则。想请教下您这边的配置。

**Comment by 666zero** [comment]
containers:
        # Runs calico-node container on each Kubernetes node. This
        # container programs network policy and routes on each
        # host.
        - name: calico-node
          image: docker.io/calico/node:v3.20.2
          envFrom:
          - configMapRef:
              # Allow KUBERNETES_SERVICE_HOST and KUBERNETES_SERVICE_PORT to be overridden for eBPF mode.
              name: kubernetes-services-endpoint
              optional: true
          env:
            # Use Kubernetes API as the backing datastore.
            - name: DATASTORE_TYPE
              value: "kubernetes"
            # POD-POD cross cluster connectivity
            - name: FELIX_EXTERNALNODESCIDRLIST
              value: "10.244.126.0/24"

**Comment by hhstu** [comment]
https://www.yuque.com/docs/share/490162eb-453b-4762-bbcf-b1f416914aa1?# 《集群外访问 calico pod》 @666zero 你先参考一下
