### ISSUE TITLE
release note link is redirecting always to the latest release notes

### ISSUE THREAD

**Issue by shashidharatd** [projectcalico/calico#4301]
## Expected Behavior

should be able to get release notes to other calico releases than latest.
3.16.6 release notes link is redirected to 3.17 which is wrong
https://docs.projectcalico.org/v3.16/release-notes/

## Current Behavior

calico release 3.16 should show 3.16 release notes

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Calico version
* Orchestrator version (e.g. kubernetes, mesos, rkt):
* Operating System and version:
* Link to your project (optional):

**Comment by caseydavenport** [comment]
@shashidharatd thanks for raising this. Looks like we're not using the correct permalinks in our releases page;

While we sort it out, you can find release notes for v3.16 here: https://docs.projectcalico.org/archive/v3.16/release-notes/

**Comment by caseydavenport** [comment]
Fixed up the latest few releases as well as the code that generates those links.
