### ISSUE TITLE
Document cpu architecture limitations to eBPF dataplane

### ISSUE THREAD

**Issue by backjo** [projectcalico/calico#4306]
There are a lot of great blog posts and docs out there about enabling eBPF, including a few that call our some major caveats (such as not running in Hybrid mode). Thinking I had addressed these caveats, I got deep down the rabbit hole of enabling the eBPF dataplane - only to realize it only supports AMD64, and not other architectures :( 
## Expected Behavior

Ideally, this would be supported, but docs calling out this limitation would be welcome in the interim. 
## Current Behavior

EBPF dataplane does not work on ARM64 OS', and documentation does not call this out. 
## Possible Solution

I'd expect the documentation at https://docs.projectcalico.org/maintenance/enabling-bpf to address this limitation. 

## Context

I can't enable the eBPF dataplane, since we run both ARM64 and AMD64 OS'
## Your Environment

* Calico version - 3.17.1
* Orchestrator version (e.g. kubernetes, mesos, rkt): k8s 1.18.10
* Operating System and version: AWS BottleRocket 1.0.4 on ARM64
* Link to your project (optional):

**Comment by nagarahalli** [comment]
@backjo In general, eBPF works fine on ARM64. However, we have not tested Calico with eBPF data plane yet. Have you tested this on other distros like Ubuntu?

**Comment by backjo** [comment]
@nagarahalli for non-amd64 systems, the syscalls needed for eBPF data plane are stubbed - see https://github.com/projectcalico/felix/commit/3dafabe1213d838468cade0722a0dea3bc8e8f61 . This prevents eBPF data plane from being enabled.

**Comment by lwr20** [comment]
From current version of https://docs.projectcalico.org/maintenance/enabling-bpf
> eBPF mode only supports x86-64. (The eBPF programs are not currently built for the other platforms.)
