### ISSUE TITLE
Calicoctl doesn't recognise multiple kubeconfig files in envar KUBECONFIG

### ISSUE THREAD

**Issue by axozoid** [projectcalico/calico#4312]
## Expected Behavior
Any `calicoctl` command should work.

## Current Behavior
I've got multiple kube config files set in my `KUBECONFIG` envar.
When I run a command, for e.g.:
```
calicoctl get node -owide
Failed to create Calico API client: stat /Users/user/.kube/config:/Users/user/.kube/kubeconfig_2: no such file or directory
```
essentially any command return this error, as it looks like the binary doesn't understand multiple files in `KUBECONFIG` envar.

## Possible Solution
Leaving just one file set in the `KUBECONFIG` envar solves the issue.

## Steps to Reproduce (for bugs)

1. `export KUBECONFIG=~/.kube/config:~/.kube/kubeconfig_2`
2. try running `calicoctl version` or any other command

 ```
$ calicoctl version
Client Version:    v3.17.1
Git commit:        8871aca3
Cluster Version:   v3.15.1
Cluster Type:      k8s,ecs,kdd,typha

$ kubectl version --short
Client Version: v1.18.5
Server Version: v1.17.12-eks-7684af
```

**Comment by caseydavenport** [comment]
Neat! I didn't know KUBECONFIG supported multiple files. We should definitely do this.
