### ISSUE TITLE
could not initialize etcdv3 client: open /calico-secrets/etcd-cert: permission denied

### ISSUE THREAD

**Issue by JESWINKNINAN** [projectcalico/calico#4313]
When using the calico version 3.17.1 manifest(https://docs.projectcalico.org/manifests/calico-etcd.yaml), the calico-kube-controller is getting started and failed due to the following error:

"could not initialize etcdv3 client: open /calico-secrets/etcd-cert: permission denied"

## Possible Solution

setting the permission with defaultmode : 440 in the volume mount will fix the issue.

is this can be considered as a bug or can we go with the fix.?

**Comment by lwr20** [comment]
I'm not sure I understand what you're saying is a bug here?  Can you expand please?

**Comment by zaldre** [comment]
This error occurs when deploying using the instructions listed here : https://docs.projectcalico.org/getting-started/kubernetes/installation/config-options

If you configure ETCD options, the secret does not get mounted into the calico-kube-controllers pod with the correct permission causing a crashloopbackoff.

Error states: main.go 101: Failed to start error=failed to build Calico client: could not initialize etcdv3 client: open /calico-secrets/etcd-cert: permission denied

Solution: Change accessmode of etcd-secrets to "calico-kube-controllers" deployment from "0400" to "0440"

`apiVersion: apps/v1
kind: Deployment
metadata:
  name: calico-kube-controllers
.......
      volumes:
        # Mount in the etcd TLS secrets with mode 400.
        # See https://kubernetes.io/docs/concepts/configuration/secret/
        - name: etcd-certs
          secret:
            secretName: calico-etcd-secrets
            defaultMode: 0440
 `

**Comment by pksrc** [comment]
FYI, I ran into this as well while bootstrapping a cluster. I was able to solve it using the edit as suggested above.
