### ISSUE TITLE
Kube-dns port 53 unreachable from pods

### ISSUE THREAD

**Issue by prgaly** [projectcalico/calico#4325]
I am testing Calico 3.17.1 with upstream kubernetes 1.19.6 cluster built using kubeadm on RHEL 7.9. Calico is in VXLAN/Always mode. The problem is that the kube-dns service is not reachable from pods. 

## Expected Behavior
Pods must be able to reach kube-dns service on port 53 in order to be able resolve DNS.

## Current Behavior
A test pod deployed with dnsutils image shows that kube-dns endpoints are not reachable from the pod and DNS resolution fails with no servers were reachable error.

## Possible Solution
None

## Steps to Reproduce (for bugs)
1. Deploy k8s 1.19.6 using kubeadm
2. Deploy Calico using on-prem manifests modified to use VXLAN backend
3. Deploy dnsutils pod and try to perform nslookup. 
4. Fails with no servers reachable

## Context
We are trying to upgrade our old k8s cluster with Flannel to use Calico and intend to use Calico network policies.

## Your Environment
* Calico version 3.17.1
* Orchestrator version (e.g. kubernetes, mesos, rkt): kubernetes 1.19.6
* Operating System and version: RHEL 7.9/AMD64
* Link to your project (optional):

I have the problem cluster running - please let me know if more details are needed. I can also use some debugging tips.

**Comment by ayoubsmii19** [comment]
can you run #kubectl logs -n kube-system coredns  ?

**Comment by prgaly** [comment]
Right now only errors are logged in the config so nothing in logs other than below - I did enable log earlier and it logged the queries - however none of them were from the dnsutils pod I deployed or one of the app pods - those pods were not able to get to the CoreDNS 53 port at all. 

```
$ kubectl logs -n kube-system -l k8s-app=kube-dns
.:53
[INFO] plugin/reload: Running configuration MD5 = 95d601495dbbb7101a678bb86c6d9b14
CoreDNS-1.7.0
linux/amd64, go1.14.4, f59c03d
.:53
[INFO] plugin/reload: Running configuration MD5 = 95d601495dbbb7101a678bb86c6d9b14
CoreDNS-1.7.0
linux/amd64, go1.14.4, f59c03d
```

**Comment by prgaly** [comment]
After debugging this turned out to be a misconfigured firewall issue - for anyone that comes across this, make sure UDP 4789 is reachable to and from master<->worker nodes.

**Comment by tanvp112** [comment]
@prgaly , may i ask does your dns works at the host (node) level under vxlan? for instance:

`nslookup kubernetes.default.svc.cluster.local 10.96.0.10`

Does the above lookup return the correct IP?

**Comment by prgaly** [comment]
> 
> 
> @prgaly , may i ask does your dns works at the host (node) level under vxlan? for instance:
> 
> `nslookup kubernetes.default.svc.cluster.local 10.96.0.10`
> 
> Does the above lookup return the correct IP?

If you mean does resolving a kubernetes domain works from the node/host - no, it's not supposed to work. Any cluster domains are only supposed to be resolvable from within the cluster, the host DNS doesn't normally have any idea on the CoreDNS setup inside the cluster.
