### ISSUE TITLE
Change IPIP mode to BGP mode 

### ISSUE THREAD

**Issue by behnm** [projectcalico/calico#4337]
How can I change calico from IPIP mode to BGP mode ?

**Comment by bcreane** [comment]
Hi @behnm - are you asking how to disable IPIP encapsulation and move from full mesh BGP peering to, for example, peering with a BGP top-of-rack router? If so, then checkout https://docs.projectcalico.org/networking/bgp for moving from full mesh to peer with a, for example, a single TOR. In terms of disabling IPIP, I think you just need to adjust your `ippool` resource, ie see https://docs.projectcalico.org/archive/v3.17/reference/faq#how-do-i-enable-ip-in-ip-and-nat-outgoing-on-an-ip-pool (but set `ipipMode: Never`).
