### ISSUE TITLE
Kube Docs misstate x86-64 is required

### ISSUE THREAD

**Issue by ctrahey** [projectcalico/calico#4340]
## Expected Behavior
[This requirements page](https://github.com/projectcalico/calico/blob/master/getting-started/kubernetes/requirements.md) should either accurately reflect supported architectures, or avoid discussing it at all if the project is fully multi-arch.

## Current Behavior
The page linked above currently includes "x86-64 processor" as the first item under "Node requirements"
I have just completed an installation on Raspberry Pi 4 with no changes to [the stock manifests](https://docs.projectcalico.org/manifests/calico.yaml).

I followed the link to "Edit this page" on GH, but [the page linked](https://github.com/projectcalico/calico/blob/master/getting-started/kubernetes/requirements.md) does not include the above architecture statement, so I'm not sure where it comes from. 

## Possible Solution
Find the source of the "Node requirements" section, and either remove the architecture line, or update it.

## Steps to Reproduce (for bugs)
1. Visit [the requirements page](https://docs.projectcalico.org/getting-started/kubernetes/requirements) (I got there via link on [the self-managed on-prem kubernetes docs](https://docs.projectcalico.org/getting-started/kubernetes/self-managed-onprem/onpremises))
2. Observe that "x86-64 processor" is stated as required
3. Install Calico on an ARM cluster
4. Observe that Calico operates successfully

## Context
There are many CNI plugins to choose from. Users who require ARM support may be skipping over Calico on the assumption that it will not work for them.

## Your Environment
* Calico version: 3.17.1
* Orchestrator version (e.g. kubernetes, mesos, rkt): Kubernetes 1.20
* Operating System and version: Ubuntu 20.04 on aarch64
* Link to your project (optional):

**Comment by caseydavenport** [comment]
Yes, that's a docs bug. Strictly speaking, the Calico team only has the test infrastructure to support x86, which is likely why that is worded that way. However, we have community-provided builds for other architectures as well - ppc64le and arm64, s390x.

I'll submit a PR to update.

**Comment by caseydavenport** [comment]
This should do it: https://github.com/projectcalico/calico/pull/4347
