### ISSUE TITLE
networkpolicy is configured with action: Log.  but I can't see any rejected logs

### ISSUE THREAD

**Issue by lixwlixw** [projectcalico/calico#4344]
calico version 3.12.3
kubernetes version 1.12.3

I have configured policies and logs in calico networkpolicy.
The policy has taken effect, but I can’t see any logs about rejection.   

```
[root@calico]# calicoctl get networkpolicy -n hack-a -o yaml 
apiVersion: projectcalico.org/v3
items:
- apiVersion: projectcalico.org/v3
  kind: NetworkPolicy
  metadata:
    creationTimestamp: "2021-01-26T08:29:17Z"
    name: deny-all
    namespace: hack-a
    resourceVersion: 46888598/
    uid: 945580c8-5fb0-11eb-a33e-525400ae723d
  spec:
    ingress:
    - action: Log
      destination: {}
      protocol: TCP
      source: {}
    - action: Deny
      destination: {}
      protocol: TCP
      source: {}
    types:
    - Ingress
    - Egress
kind: NetworkPolicyList
```

**Comment by bcreane** [comment]
Hi @lixwlixw. You can watch a live difference of iptable rule hits with something like `sudo watch -d iptables -v -L` (on the node). If you send traffic you expect to see denied and logged, confirm that you're seeing the relevant iptable rule "hit." If it's not being hit, suggest you confirm your test setup is sending traffic to a pod on the node, and then I'd probably simplify the policy - I don't think you need `source{}` for example.

**Comment by lixwlixw** [comment]
The iptables rules have taken effect. 
The networkpolicy matches my expected configuration.
I want to know where can I see the log of networkpolicy rejecting requests?

**Comment by bcreane** [comment]
As mentioned in https://docs.projectcalico.org/archive/v3.17/security/calico-network-policy#features, the log actions are recorded in the node's syslog output.

**Comment by lixwlixw** [comment]
i see see. thanks~
