### ISSUE TITLE
calicoctl migrate docs page is empty

### ISSUE THREAD

**Issue by fasaxc** [projectcalico/calico#4345]
## Expected Behavior

The migrate commands should be documented
## Current Behavior

https://docs.projectcalico.org/reference/calicoctl/datastore/migrate/ is empty, possible broken.

## Possible Solution

Write the docs :-)
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Calico version: v3.17
* Orchestrator version (e.g. kubernetes, mesos, rkt):
* Operating System and version:
* Link to your project (optional):

**Comment by mgleung** [comment]
This should be fixed by https://github.com/projectcalico/calico/pull/4348 and related PRs.
