### ISSUE TITLE
calico-node should update kubernetes node status

### ISSUE THREAD

**Issue by dwradcliffe** [projectcalico/calico#435]
When new nodes are added to the kubernetes cluster, or in situations when there are bgp peering problems, there is a period of time when the node is not ready for work but kubernetes thinks it is ready. This is because kubernetes doesn't know anything about calico/bgp peering. We need update the node object and tell kubernetes that the node is not ready yet if bgp peering has not been established.

It seems like calico-node should handle this since it already runs on every node. To be complete we should also run a controller to add the initial state to the new node objects in case the calico-node pod never starts.

There are two options of what to update on the node.
1) Add a new NodeCondition similar to what happens in google or aws environments when their routing is not setup yet (https://github.com/kubernetes/kubernetes/blob/f49442d4331052c3141c47a3f9701da7082ebcff/pkg/controller/route/routecontroller.go#L199-L232). From my initial testing I was having trouble with this option.
2) Add a taint to the node (https://github.com/kubernetes/kubernetes/blob/master/docs/design/taint-toleration-dedicated.md). This worked but it's not as nicely organized as the NodeCondition. However somewhere I read that this would replace NodeCondition someday.

As discussed with @lwr20 @gunjan5 @caseydavenport on Slack (https://calicousers.slack.com/archives/kubernetes/p1483632724001584)

I'm going to take a stab at some code to get this started but I'm not sure what I'll end up with.

Related:
https://github.com/kubernetes/kubernetes/pull/33573

**Comment by caseydavenport** [comment]
Would be great if Kubernetes let you specify one or more node readiness endpoints (similar to how it works for Pods).

Kubelet could then be configured to probe Calico for readiness information, using that to report network readiness via a taint on the Node object.

This would also work when there are, e.g. multiple sources of readiness for the network (Calico + GCE route controller, or Calico + flannel, or something else)

I think this is probably an issue that needs to first be solved in upstream Kubernetes though, before there's anything meaningful to do in Calico.

**Comment by caseydavenport** [comment]
calico/node now sets the NetworkUnavailable condition to `false` when it starts up (or, it will in Calico v3.4 - see https://github.com/projectcalico/node/pull/89)

This issue is more around enhancing that behavior so the state is correct even after startup - for example, if BGP peering is down for X seconds, mark the node unavailable. This needs some careful thought before implementing to make sure we only mark the node unavailable when it really is a broken node.

**Comment by caseydavenport** [comment]
Closing in favor of https://github.com/projectcalico/node/issues/519
