### ISSUE TITLE
"https://[100.64.0.1]:443/apis/crd.projectcalico.org/v1/clusterinformations/default": dial tcp 100.64.0.1:443: i/o timeout when creating pods

### ISSUE THREAD

**Issue by ErkkaKorpi** [projectcalico/calico#4361]
Since upgrading kOps managed cluster from version 1.16.14 to 1.17.17 we started seeing this error where pods hang on "ContainerCreating" up to 20minutes. If i describe the pod thats failing to start i can see events:

`Normal   Scheduled               5m46s                default-scheduler  Successfully assigned erkka-test/nginx-deployment-9496f96c-gs7zd to ip-10-168-48-156.eu-west-1.compute.internal
  Warning  FailedCreatePodSandBox  4m45s                kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = [failed to set up sandbox container "1453a2625b080b25014134559de4b6b7f88706ef2bfe733183a58efee8e7047c" network for pod "nginx-deployment-9496f96c-gs7zd": networkPlugin cni failed to set up pod "nginx-deployment-9496f96c-gs7zd_erkka-test" network: error getting ClusterInformation: Get "https://[100.64.0.1]:443/apis/crd.projectcalico.org/v1/clusterinformations/default": dial tcp 100.64.0.1:443: i/o timeout, failed to clean up sandbox container "1453a2625b080b25014134559de4b6b7f88706ef2bfe733183a58efee8e7047c" network for pod "nginx-deployment-9496f96c-gs7zd": networkPlugin cni failed to teardown pod "nginx-deployment-9496f96c-gs7zd_erkka-test" network: error getting ClusterInformation: Get "https://[100.64.0.1]:443/apis/crd.projectcalico.org/v1/clusterinformations/default": dial tcp 100.64.0.1:443: i/o timeout]
  Warning  FailedCreatePodSandBox  3m44s                kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = [failed to set up sandbox container "a219c83cd7c8e3495cedbc482c71944c3882a4add7f9db12c9ca1fab4dd2b8bf" network for pod "nginx-deployment-9496f96c-gs7zd": networkPlugin cni failed to set up pod "nginx-deployment-9496f96c-gs7zd_erkka-test" network: error getting ClusterInformation: Get "https://[100.64.0.1]:443/apis/crd.projectcalico.org/v1/clusterinformations/default": dial tcp 100.64.0.1:443: i/o timeout, failed to clean up sandbox container "a219c83cd7c8e3495cedbc482c71944c3882a4add7f9db12c9ca1fab4dd2b8bf" network for pod "nginx-deployment-9496f96c-gs7zd": networkPlugin cni failed to teardown pod "nginx-deployment-9496f96c-gs7zd_erkka-test" network: error getting ClusterInformation: Get "https://[100.64.0.1]:443/apis/crd.projectcalico.org/v1/clusterinformations/default": dial tcp 100.64.0.1:443: i/o timeout]
  Normal   SandboxChanged          10s (x9 over 4m45s)  kubelet            Pod sandbox changed, it will be killed and re-created.`
  
When viewing logs from calico-node pod assigned to same worker node as where the pod tries to schedule you can see these errors:
`
[WARNING][239] felix/route_table.go 540: Failed to synchronise routes. error=netlink update operation failed ifaceName="cali66f9048c30b" ifaceRegex="^cali.*" ipVersion=0x4
[WARNING][239] felix/route_table.go 655: Failed to add route error=file exists ifaceName="cali48d3c7b403b" ifaceRegex="^cali.*" ipVersion=0x4
[WARNING][239] felix/route_table.go 1086: Failed to access interface but it now appears to be up error=netlink update operation failed ifaceName="cali48d3c7b403b" ifaceRegex="^cali.*" ipVersion=0x4 link=&netlink.Veth{LinkAttrs:netlink.LinkAttrs{Index:716, MTU:1440, TxQLen:0, Name:"cali48d3c7b403b", HardwareAddr:net.HardwareAddr{0xee, 0xee, 0xee, 0xee, 0xee, 0xee}, Flags:0x13, RawFlags:0x11043, ParentIndex:4, MasterIndex:0, Namespace:interface {}(nil), Alias:"", Statistics:(*netlink.LinkStatistics)(0xc000a5e0f0), Promisc:0, Xdp:(*netlink.LinkXdp)(nil), EncapType:"ether", Protinfo:(*netlink.Protinfo)(nil), OperState:0x6, NetNsID:13, NumTxQueues:0, NumRxQueues:0}, PeerName:""}
`  

I have tried to remove and re-install all calico component to the cluster but behaviour remains the same. When calico-node pods are restarted some are experiencing multiple restarts before they transition to ready 1/1 state. While calico-node pods are starting up they log the following before restarting:

`
[FATAL][20] tunnel-ip-allocator/allocateip.go 202: failed to fetch node resource 'ip-10-168-48-156.eu-west-1.compute.internal' error=Get "https://100.64.0.1:443/api/v1/nodes/ip-10-168-48-156.eu-west-1.compute.internal": dial tcp 100.64.0.1:443: i/o timeout
Calico node failed to start
`
and a little later we can see the following in the log if calico-node goes into CrashLoopBackOff:
`
[INFO][9] startup/startup.go 424: Hit error connecting to datastore - retry error=Get "https://100.64.0.1:443/api/v1/nodes/foo": dial tcp 100.64.0.1:443: i/o timeout
`

## Expected Behavior
Pods getting IP address and transition to "Running" state

## Current Behavior
Pods hang on state "ContainerCreating" up to 20minutes

## Steps to Reproduce (for bugs)
1. Use kOps v1.18.2 to upgrade k8s cluster from v1.16.16 to v1.17.17
2. Deploy any new deployment or restart existing one

## Context
Pods should start running within seconds without problems connecting to "https://[100.64.0.1]:443/apis/crd.projectcalico.org/v1/clusterinformations/default"

## Your Environment

* Calico version 3.15.3
* Orchestrator version (e.g. kubernetes, mesos, rkt): Kubernetes v1.17.17
* Operating System and version: 4.9.0-14-amd64 #1 SMP Debian 4.9.240-2 (2020-10-30) x86_64 GNU/Linux

**Comment by BouweCeunen** [comment]
I'm experiencing the same, sometimes pods start without an issue, sometimes they hang with that message for up to 10minutes.

I found some "solutions" online but haven't tried them yet. https://imlc.me/how-to-resolve-no-route-to-host-in-kubernetes

Most things point to the `iptables`.

**Comment by caseydavenport** [comment]
> [INFO][9] startup/startup.go 424: Hit error connecting to datastore - retry error=Get "https://100.64.0.1:443/api/v1/nodes/foo": dial tcp 100.64.0.1:443: i/o timeout

This generally means that Calico isn't able to access the Kubernetes API server, which is done via kube-proxy's Service implementation. If I had to guess, this isn't a problem with Calico per-se, rather it points to something wrong with either the host's networking or kube-proxy on the node.
