### ISSUE TITLE
Calico/OpenStack issues on CentOS 7

### ISSUE THREAD

**Issue by neiljerram** [projectcalico/calico#437]
CentOS 7 (or RHEL 7, which in theory is equivalent) is one of our target platforms for Calico on OpenStack.  An update of this platform - CentOS 7.3 - was recently released, and since then our Calico/OpenStack testing on CentOS 7 has been seeing some problems, which are documented here.

We believe the key change, in that platform update, was that libvirt was updated from version 1.2.7 to version 2.0.0.  libvirt sits in the stack of control of the hypervisor, like this:

                    XML description
    OpenStack Nova -----------------> libvirt ----> KVM or QEMU
                         of VM
                                  
Nova builds an XML description of each wanted VM, and then libvirt makes it happen.

Following the 7.3 update, all non-trivial tests were failing because of new libvirt (2.0.0) not handling part of the XML - specifically `<script path=''>` - in the same way that libvirt 1.2.7 did.  The Nova-generated XML is strictly speaking incorrect and I've submitted a fix for it (https://review.openstack.org/#/c/411936/), but it happened to work anyway with libvirt 1.2.7 - but no longer with 2.0.0.

Assuming that fix goes through soon, it still won't help existing OpenStack releases, such as those that Tigera's own CI tests with.  I've modified our CI to apply that same fix to Nova code post-install, and other Calico/OpenStack users on CentOS 7.3 can do likewise.  (Alternatively we could build and host patched Nova packages for CentOS, but would prefer not to because of the additional maintenance burden.)

With that Nova fix, most Calico/OpenStack tests pass, but we still reliably see failures in a few tests that involve:
- multiple interfaces into a VM
- 'soft' reboot
- non-live migration.

We haven't yet investigated these in any further detail.

These issues have also been raised and discussed:
- on the OpenStack ML: http://lists.openstack.org/pipermail/openstack-dev/2016-December/109080.html and http://lists.openstack.org/pipermail/openstack-operators/2016-December/012345.html
- in a Nova bug report: https://bugs.launchpad.net/nova/+bug/1649527.

In one of the ML threads it was observed that repositories for CentOS 7.2 - and so still with libvirt 1.2.7 - are still available.  So one option is to configure systems to stick on 7.2 and avoid upgrading to 7.3.

**Comment by lxpollitt** [comment]
cc @ahrkrak @kprabhak @liljenstolpe
