### ISSUE TITLE
Hardware offload to PowerConnect 6200 switch

### ISSUE THREAD

**Issue by cjac** [projectcalico/calico#4371]
```
System Description: Dell Ethernet Switch
System Up Time: 0 days, 11h:33m:16s
System Contact: 
System Name: switch01
System Location: 
Burned In MAC Address: 0025.642A.C55F
System Object ID: 1.3.6.1.4.1.674.10895.3011
System Model ID: PCT6248
Machine Type: PowerConnect 6248
```

## Expected Behavior

It may be possible to implement this with SNMP, otherwise ssh + tftp might be a good solution

## Current Behavior

Is there any support for offload to other switches?  Not certain.

## Possible Solution

SNMP
ssh + tftp

## Context

I understand that a great deal of the network configuration happens with a software bridge.  I don't want this to be a bottleneck when I have a piece of hardware with a 20+GE backplane

## Your Environment

* Calico version

```
$ sudo ~/bin/calicoctl version
Client Version:    v3.17.1
Git commit:        8871aca3
invalid configuration: no configuration has been provided
```

```
$ sudo ~/bin/calicoctl node status
Calico process is running.

IPv4 BGP status
+---------------+-------------------+-------+------------+-------------+
| PEER ADDRESS  |     PEER TYPE     | STATE |   SINCE    |    INFO     |
+---------------+-------------------+-------+------------+-------------+
| 100.64.79.133 | node-to-node mesh | up    | 2021-02-04 | Established |
| 100.64.79.135 | node-to-node mesh | up    | 2021-01-31 | Established |
| 100.64.79.134 | node-to-node mesh | up    | 2021-01-31 | Established |
| 100.64.79.132 | node-to-node mesh | up    | 2021-01-31 | Established |
| 100.64.79.131 | node-to-node mesh | up    | 2021-01-31 | Established |
| 100.64.79.136 | node-to-node mesh | up    | 2021-02-01 | Established |
+---------------+-------------------+-------+------------+-------------+

IPv6 BGP status
No IPv6 peers found.
```

* Orchestrator version (e.g. kubernetes, mesos, rkt):
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-13T13:28:09Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-13T13:20:00Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
```

* Operating System and version:

```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.2 LTS
Release:	20.04
Codename:	focal
```

* Link to your project (optional):

https://wp.colliertech.org/cj/?cat=163

**Comment by song-jiang** [comment]
Calico route packet to container directly. There is no software bridge involved. So I guess the answer is no? @neiljerram WDYT?

**Comment by cjac** [comment]
I heard there's experimental VPP work.  Is this true?

**Comment by neiljerram** [comment]
> I heard there's experimental VPP work.  Is this true?

@cjac Indeed there is: https://github.com/projectcalico/vpp-dataplane

In general our architecture allows user-space dataplane implementations to be plugged in, instead of the kernel / iptables / eBPF implementation, but someone needs to write them.

> Calico route packet to container directly. There is no software bridge involved. So I guess the answer is no? @neiljerram WDYT?

Well there is the "swdev" work in the Linux kernel, whose general purpose I believe is to allow kernel networking things to be offloaded to specific switches.  @cjac Do you know if there is any particular "swdev" work for the PowerConnect switch?

**Comment by cjac** [comment]
> Indeed there is: https://github.com/projectcalico/vpp-dataplane

Thank you!  Perhaps I could and should open this issue with that project instead.  

> Do you know if there is any particular "swdev" work for the PowerConnect switch?

I don't, but I'm curious to find out.
