### ISSUE TITLE
Kubernetes network policy is not enabled between different nodes.

### ISSUE THREAD

**Issue by kawamoto-taku-13** [projectcalico/calico#4380]
We are currently creating multiple instances on Oracle Cloud Infrastructure to build a Kubernetes cluster.
We are building it from scratch using kubeadm instead of OKE, assuming that it can be built in any environment such as on-premise.

When I installed Calico as a CNI plugin and configured the network policy for Kubernetes, the network policy setting does not work.
When you install Calico as a CNI plugin and configure the network policy settings for Kubernetes, the network policy settings do not work effectively when communicating between Pods running on different worker nodes, and communication becomes impossible.

I believe I am missing some settings needed to enable network policy settings even across different worker nodes, but I don't know what I am missing. Please help.

## Current Behavior

I have confirmed that the network policy setting is enabled for pods running on the same worker node.
Also, with the network policy setting removed, Pods running on different worker nodes can communicate with each other.
The same applies to Calico's network policy and global network policy.

Even if you build multiple nodes on a single instance using minikube, we have confirmed that the network policy setting is enabled for communication between different nodes.

## Your Environment

* Calico version:  v3.17
* Orchestrator version : Kubernetes
* Operating System and version: CentOS 7

**Comment by caseydavenport** [comment]
@kawamoto-taku-13 could you please give a bit more detail about what you're trying to do and what exactly is not working? 

>  the network policy settings do not work effectively when communicating between Pods running on different worker nodes, and communication becomes impossible.

Basically, a bit more detail about the policies you've created, and what you mean by "do not work effectively"

**Comment by kawamoto-taku-13** [comment]
@caseydavenport
There are three different systems `a`,`b`,`c` and two worker nodes, with one of the three systems located in each worker node.

```
NAME                        READY   STATUS    RESTARTS   AGE    IP               NODE       NOMINATED NODE   READINESS GATES
system-a-66658b869c-572tz   1/1     Running   0          114s   172.18.250.201   worker-1   <none>           <none>
system-a-66658b869c-dzh44   1/1     Running   0          114s   172.18.26.9      worker-2   <none>           <none>
system-b-7c89c67bbb-dj7xf   1/1     Running   0          9s     172.18.250.202   worker-1   <none>           <none>
system-b-7c89c67bbb-2j25m   1/1     Running   0          9s     172.18.26.10     worker-2   <none>           <none>
system-c-6984589967-kv8fj   1/1     Running   0          9s     172.18.250.203   worker-1   <none>           <none>
system-c-6984589967-kl2lx   1/1     Running   0          9s     172.18.26.11     worker-2   <none>           <none>
```

We want `a` and `b` to be able to communicate freely from each system, but `c` to be able to communicate only from `b`.

Before setting the network policy, all systems are able to communicate.

| Connection source<br>System:Worker node | Connection destination<br>System:Worker node | Communication enabled |
|---|---|:---:|
|system-a : worker-1|system-b : worker-1|yes|
|system-a : worker-1|system-b : worker-2|yes|
|system-a : worker-1|system-c : worker-1|yes|
|system-a : worker-1|system-c : worker-2|yes|
|system-a : worker-2|system-b : worker-1|yes|
|system-a : worker-2|system-b : worker-2|yes|
|system-a : worker-2|system-c : worker-1|yes|
|system-a : worker-2|system-c : worker-2|yes|
|system-b : worker-1|system-a : worker-1|yes|
|system-b : worker-1|system-a : worker-2|yes|
|system-b : worker-1|system-c : worker-1|yes|
|system-b : worker-1|system-c : worker-2|yes|
|system-b : worker-2|system-a : worker-1|yes|
|system-b : worker-2|system-a : worker-2|yes|
|system-b : worker-2|system-c : worker-1|yes|
|system-b : worker-2|system-c : worker-2|yes|

When the network policy is set, the following will happen.


```yaml
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: network-policy-ingress
spec:
  podSelector:
    matchLabels:
      app: system-c
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: system-b
```

| Connection source<br>System:Worker node | Connection destination<br>System:Worker node | Communication enabled | Expected results |
|---|---|:---:|:---:|
|system-a : worker-1|system-b : worker-1|yes|yes|
|system-a : worker-1|system-b : worker-2|yes|yes|
|system-a : worker-1|system-c : worker-1|no|no|
|system-a : worker-1|system-c : worker-2|no|no|
|system-a : worker-2|system-b : worker-1|yes|yes|
|system-a : worker-2|system-b : worker-2|yes|yes|
|system-a : worker-2|system-c : worker-1|no|no|
|system-a : worker-2|system-c : worker-2|no|no|
|system-b : worker-1|system-a : worker-1|yes|yes|
|system-b : worker-1|system-a : worker-2|yes|yes|
|system-b : worker-1|system-c : worker-1|yes|yes|
|system-b : worker-1|system-c : worker-2|**no**|**yes**|
|system-b : worker-2|system-a : worker-1|yes|yes|
|system-b : worker-2|system-a : worker-2|yes|yes|
|system-b : worker-2|system-c : worker-1|**no**|**yes**|
|system-b : worker-2|system-c : worker-2|yes|yes|

Communication from system-b:worker-1 to system-c:worker-2 and from system-b:worker-2 to system-c:worker-1 is no longer possible.


The following configuration file works as expected, but since there may be more systems in the future, I would like to solve this problem with an ingress to system-c.

```yaml
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: network-policy-egress
spec:
  podSelector:
    matchLabels:
      app: system-a
  policyTypes:
  - Egress
  egress:
  - to:
    - podSelector:
        matchLabels:
          app: system-b
```

**Comment by caseydavenport** [comment]
Gotcha, thanks - that helps a lot.

The ingress policy should be implemented on the node's hosting system-c pods. Since it seems like this is only happening for cross-node traffic, it seems to suggest that there may be some sort of NAT or other networking issues between the nodes.

Could you check to see that the traffic is not being NAT'd on egress from the originating node, nor on ingress to the destination node? The kube-proxy may perform this NAT if the `--cluster-cidr` argument is not provided, or does not match the IP pool that Calico is using for pod addresses (as an example).

**Comment by kawamoto-taku-13** [comment]
Since I have only been working with Kubernetes for a short time, I did not know how to check.

I have built a Kubernetes cluster using kubeadm, and I have confirmed that the configMap of kube-proxy includes the clusterCIDR setting.

I'm sorry, but can you please tell me how to check the details?

**Comment by lwr20** [comment]
Perhaps join us in slack http://slack.projectcalico.org/ and we can talk you through troubleshooting steps?
