### ISSUE TITLE
Calico 3.16+ and FirewallD CentOS 7 not working well

### ISSUE THREAD

**Issue by romulus-ai** [projectcalico/calico#4382]
Since the 3.16 release, you guys moved to following rule:
ACCEPT     all  --  anywhere             anywhere             /* cali:S93hcgKJrXEqnTfs */ /* Policy explicitly accepted packet. */ mark match 0x10000/0x10000

from some Calico IPTables Chain to the FORWARD Chain and Calico ensures that this rule will be the last rule in this chain.

However this collides with FirewallD which introduces the following REJECT rule into the FORWARD Chain:
REJECT     all  --  anywhere             anywhere             --reject-with icmp-host-prohibited

Because of the behaviour of Calico, the ACCEPT rule of Calico will come after the REJECT rule of Firewalld and this causes routing problem between the nodes.

## Expected Behavior
Routing should just wohl even if firewalld is enabled, i.e. Calico could introduce the ACCEPT rule as the last ACCEPT rule in the FORWARD Chain, but before any REJECT or DROP Rules.

## Current Behavior
Calico injects the so important ACCEPT rule right after the REJECT Rule of Firewalld and setting the Policy to DROP. 

## Possible Solution
Calico could introduce the ACCEPT rule as the last ACCEPT rule in the FORWARD Chain, but before any REJECT or DROP Rules.
Currently I've built a small service, removing the REJECT Rule of Firewalld and setting the Policy of the FORWARD Chain to DROP. But this is absolutly not a clean way, as explained here: https://github.com/firewalld/firewalld/issues/750

## Steps to Reproduce (for bugs)
Simply setup K8S 1.19.x with Calico 3.17 or 3.16 on a few CentOS 7 nodes.

The Check the Logs of i.e. CoreDNS Cluster or try to deploy Istio or Something that need to reach stuff running on different nodes. It will fail with a routing error.

## Context
Currently we found a workaround which is quite OK, however, this should be fixes somehow, since firewalld is a quite common software to configure IPTables or NFTables.

## Your Environment
* Calico version: 3.17 and 3.16
* Orchestrator version: 1.19.x and 1.18.x
* Operating System and version: CentOS 7 and similar Problems on CentOS 8 but in CentOS may with another root cause.

**Comment by lwr20** [comment]
Calico and firewalld both manipulate iptables rules, and there's high likelihood that they're going to clash or fight over rules.  

Calico host protection can be used to implement the rules you currently implement in firewalld - perhaps the solution here is to use that and disable firewalld? https://docs.projectcalico.org/security/protect-hosts

Fundamentally Calico doesn't _support_ running with firewalld (though if it works for you, great).

**Comment by sagarvelankar** [comment]
Hi,

I solved this problem in CentOS 8 by creating a new firewalld zone for kubernetes pods and setting its target to ACCEPT.
So, firewalld will accept packets going into POD SUBNET CIDR (ingress zone) and also packets coming out of POD SUBNET CIDR
(egress zone)

Commands :

```
firewall-cmd --permanent --delete-zone=kubernetes_pods
firewall-cmd --permanent --new-zone=kubernetes_pods
firewall-cmd --permanent --zone=kubernetes_pods --set-target=ACCEPT
firewall-cmd --permanent --zone=kubernetes_pods --add-source=<POD SUBNET CIDR>
firewall-cmd --reload
```

firewall-cmd man :

```
       --permanent [--zone=zone] --set-target=target
           Set the target of a permanent zone.  target is one of: default, ACCEPT, DROP, REJECT

           default is similar to REJECT, but has special meaning in the following scenarios:

            1. ICMP explicitly allowed

               At the end of the zone's ruleset ICMP packets are explicitly allowed.

            2. forwarded packets follow the target of the egress zone

               In the case of forwarded packets, if the ingress zone uses default then whether or not the packet will be
               allowed is determined by the egress zone.

               For a forwarded packet that ingresses zoneA and egresses zoneB:

               ·   if zoneA's target is ACCEPT, DROP, or REJECT then the packet is accepted, dropped, or rejected
                   respectively.

               ·   if zoneA's target is default, then the packet is accepted, dropped, or rejected based on zoneB's target. If
                   zoneB's target is also default, then the packet will be rejected by firewalld's catchall reject.

            3. Zone drifting from source-based zone to interface-based zone

               This only applies if AllowZoneDrifting is enabled. See firewalld.conf(5).

               If a packet ingresses a source-based zone with a target of default, it may still enter an interface-based zone
               (including the default zone).
```

Versions :

```
firewall-cmd --version
0.8.2

uname -r
4.18.0-240.10.1.el8_3.x86_64

cat /etc/redhat-release
CentOS Linux release 8.3.2011

kubectl version
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-13T13:28:09Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-13T13:20:00Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
```

To see what is getting rejected by firewalld, use the below commands

```
firewall-cmd --set-log-denied=all
firewall-cmd --reload
dmesg | grep -i reject
```
