### ISSUE TITLE
IPIP broken in EL 8.3 with multiple drivers

### ISSUE THREAD

**Issue by champtar** [projectcalico/calico#4384]
This is just a heads up to help triage bug report, nothing to fix in calico.
With EL (RHEL/CentOS/Oracle) 8.3, I've seen 2 cases where IPIP is broken

1) using Mellanox network card (mlx5_core driver), 8.3 ask the NIC firmware what offload is supported, but the firmware is buggy
```
OLD FW / DRIVER with Feature
NO iperf traffic
# ethtool -i eth2 | grep firm ; uname -r ; ethtool -k eth2 | grep ipx
firmware-version: 14.26.1040 (MT_2420110034)
4.18.0-240.el8.x86_64
tx-ipxip4-segmentation: on
tx-ipxip6-segmentation: on
```
```
FIXED FW / DRIVER with Feature
iperf traffic works
# ethtool -i eth2 | grep firm ; uname -r ; ethtool -k eth2 | grep ipx
firmware-version: 14.29.0538 (MT_2420110034)
4.18.0-240.el8.x86_64
tx-ipxip4-segmentation: off [fixed]
tx-ipxip6-segmentation: off [fixed]
```
Nothing public, internal RHEL case https://access.redhat.com/support/cases/#/case/02800279

2) using VMWare (vmxnet3 driver) udp tunnel segmentation is enabled since 8.3, but not working
https://github.com/kubernetes-sigs/kubespray/issues/7268#issuecomment-775929387
```
-tx-udp_tnl-segmentation: off [fixed]
-tx-udp_tnl-csum-segmentation: off [fixed]
+tx-udp_tnl-segmentation: on
+tx-udp_tnl-csum-segmentation: on
```

## Possible Solution
Use VXLAN Crosssubnet or VXLAN Always

## Your Environment
* Operating System and version: EL 8.3

**Comment by caseydavenport** [comment]
@champtar thanks for the heads up!

**Comment by champtar** [comment]
Found a new broken driver with IPIP, qede with CentOS 7.8
```
# ethtool -i ens3f6
driver: qede
version: 8.37.0.20
firmware-version: mfw 8.55.5.0 storm 8.37.7.0
```
https://bugzilla.redhat.com/show_bug.cgi?id=1968614
https://lkml.org/lkml/2021/1/11/849
https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1909062

**Comment by janeczku** [comment]
Related: https://github.com/projectcalico/calico/issues/4727
