### ISSUE TITLE
Initiate traffic with floating IP and receive a reply

### ISSUE THREAD

**Issue by kiemlicz** [projectcalico/calico#4400]
## Question
I would like to initiate the traffic to some application POD with `FLOATING_IP` set to be a SRC IP  
I added to the POD with floating IP a following rule:
`iptables -t nat -A POSTROUTING -d APP_IP -j SNAT --to FLOATING_IP` which effectively spoofs the `FLOATING_IP`  
The outgoing traffic has indeed spoofed the IP to be a `FLOATING_IP`, however the reply from the APP is not making it to the POD, application POD is sending the reply, but the POD with `FLOATING_IP` is not seeing it (tcpdump-wise)

If I initiate the traffic from the APP to the POD with `FLOATING_IP` **beforehand**, then the above scenario works (like I need to punch a hole first). However I don't want to do this (I can't)

Is it a bug or unsupported feature? Please explain

## Context
I want to replicate (HA) the NAT entries between PODS (the PODS perform some internal NATting)  
PODs talk to the APP  
PODs will run conntrackd  

## Your Environment
* Calico 3.17.2
* Kubernetes EKS
* Amazon linux worker nodes

**Comment by caseydavenport** [comment]
> Is it a bug or unsupported feature? Please explain

We don't officially support this sort of feature. I'd recommend trying to track down where the response packet is getting lost - does the remote node have a route to the floating IP? You'll need some way of the remote end routing the traffic back.
