### ISSUE TITLE
make autoHostEndpoint detect all IPs on the interfaces

### ISSUE THREAD

**Issue by r3pek** [projectcalico/calico#4408]
Right now, autoHostEndpoint feature just detects the EndPoints the cluster nodes use to communicate with eachother
In the case there's some more interfaces, they aren't detected and populated in the HostEndpoint object.

## Expected Behavior
HostEndpoint should have all IPs available

## Current Behavior
Only the interfaces with IP used for communication between nodes are identified

## Steps to Reproduce (for bugs)

1. Have a cluster with more than one interface
2. Activate autoHostEndpoint
3. check IPs detected with `calicoctl get hep -owide`

## Context

In my case, the communication between nodes are on a private lan, but the access to the resources on the cluster are from a public facing interface (with a public IP). I might want to apply some policies on this

## Your Environment

* Calico version: 3.17.2
* Orchestrator version (e.g. kubernetes, mesos, rkt): kubernetes
* Operating System and version: CentOS 8 Stream
* Link to your project (optional):

**Comment by lwr20** [comment]
From a conversation in Calico Users slack:
https://calicousers.slack.com/archives/CPEPF833L/p1613639469490300

**Comment by caseydavenport** [comment]
Yes, this would be a nice improvement. We need those IPs to show up in the data store, so I think:

- The first step here is to enhance the Calico "Node" API object to be capable of holding an arbitrary number of IPs (perhaps tagged with some metadata). 
- Next step would be to get calico/node to maintain that set of addresses on the node object. 
- Finally, get kube-controllers to write those addresses back into the HEPs that it is maintaining.

**Comment by caseydavenport** [comment]
@coutinhop this one as well should be covered by what you're working on, effectively. Leveraging the Kubernetes Node API to learn more addresses from the node.

**Comment by coutinhop** [comment]
https://github.com/projectcalico/calico/pull/5405 just merged into master, will go in v3.22
