### ISSUE TITLE
Calico ready state is 0/1 when installed in Kubernetes(Ubuntu 20.04)

### ISSUE THREAD

**Issue by sushilkjaiswar** [projectcalico/calico#4420]
I am trying to build on premise k8s cluster using MacMini(Ubunut 20.04 installed) 2 machines with 1 Master + 1 Worker Node installed. Calico doesn't show ready state after completing installation of Kubertnetes  successfully. Exactly same infrastructure was build on VMWare 1 Master + 2 Nodes which worked absolutely fine after installation was done without any hiccups. 

## Expected Behavior

> captain@captain-america:~$ kubectl get pods --all-namespaces
> NAMESPACE     NAME                                       READY   STATUS    RESTARTS   AGE
> kube-system   calico-kube-controllers-66956989f4-blpvk   1/1     Running   0          19m
> kube-system   calico-node-2vzkq                          1/1     Running   0          19m
> kube-system   calico-node-cqmwt                          1/1     Running   0          19m
> kube-system   coredns-74ff55c5b-9cdd7                    1/1     Running   0          10h
> kube-system   coredns-74ff55c5b-knms8                    1/1     Running   0          10h
> kube-system   etcd-captain-america                       1/1     Running   0          10h
> kube-system   kube-apiserver-captain-america             1/1     Running   0          10h
> kube-system   kube-controller-manager-captain-america    1/1     Running   0          10h
> kube-system   kube-proxy-j6hwh                           1/1     Running   0          10h
> kube-system   kube-proxy-qx9r7                           1/1     Running   0          10h
> kube-system   kube-scheduler-captain-america             1/1     Running   0          10h

## Current Behavior

> captain@captain-america:~$ kubectl get pods --all-namespaces
> NAMESPACE     NAME                                       READY   STATUS    RESTARTS   AGE
> kube-system   calico-kube-controllers-66956989f4-blpvk   1/1     Running   0          19m
> kube-system   calico-node-2vzkq                          0/1     Running   0          19m
> kube-system   calico-node-cqmwt                          0/1     Running   0          19m
> kube-system   coredns-74ff55c5b-9cdd7                    1/1     Running   0          10h
> kube-system   coredns-74ff55c5b-knms8                    1/1     Running   0          10h
> kube-system   etcd-captain-america                       1/1     Running   0          10h
> kube-system   kube-apiserver-captain-america             1/1     Running   0          10h
> kube-system   kube-controller-manager-captain-america    1/1     Running   0          10h
> kube-system   kube-proxy-j6hwh                           1/1     Running   0          10h
> kube-system   kube-proxy-qx9r7                           1/1     Running   0          10h
> kube-system   kube-scheduler-captain-america             1/1     Running   0          10h

> captain@captain-america:~$ KUBECONFIG=~/.kube/config sudo calicoctl node status
> Calico process is running.
> 
> IPv4 BGP status
> +---------------+-------------------+-------+----------+---------+
> | PEER ADDRESS  |     PEER TYPE     | STATE |  SINCE   |  INFO   |
> +---------------+-------------------+-------+----------+---------+
> | 192.168.0.123 | node-to-node mesh | start | 18:17:23 | Connect |
> +---------------+-------------------+-------+----------+---------+
> 
> IPv6 BGP status
> No IPv6 peers found.
> 
> 

## Possible Solution

I tired tweaking some Calico Node variables as suggested in various forums including projectcalico but with unsuccessful results. 

## Context

Not critical issue as far as I am concerned but I was trying to get local Kubernetes cluster created using spare machines for my development. Major concern for me is that same setup works exactly on virtual environment on VMWare.

## Your Environment
* Calico version - 3.18
* Orchestrator version (e.g. kubernetes, mesos, rkt): Kubernetes Client: 1.20, Server: Server: 1.20
* Operating System and version: Ubuntu 20.04(All machines)

What could go wrong here when I am trying to setup on physical machines compared to virtual machines? calico-node ready is always 0/1.

**Comment by sushilkjaiswar** [comment]
Calico Nodes  event logs 
[calico-node-2vzkq.log](https://github.com/projectcalico/calico/files/6031349/calico-node-2vzkq.log)

**Comment by lwr20** [comment]
> What could go wrong here when I am trying to setup on physical machines compared to virtual machines?

Wow, that's potentially a long list.  Given that you're talking about Calico, the relevant ones might include: network environment, networking hardware present in the machine, DNS config, etc, etc

Looking at your logs, I see 
```
bird: BGP: Unexpected connect from unknown address 192.168.0.131 (port 51882)
```
That's often a sign that your machines have >1 network interface and Calico has picked the wrong one to use on at least one of them.  You'll need to give Calico a hint as to which interface to use with IP_AUTODETECTION_METHOD.  See https://docs.projectcalico.org/reference/node/configuration#ip-autodetection-methods

**Comment by sushilkjaiswar** [comment]
Thanks @lwr20 for the prompt reply.

I have already tried the resolution mentioned by you. I verified calico detects correct interface without or with IP_AUTODETECTION_METHOD even in case of multiple interface. After debugging in detail it looks like calico is unsuccessfully in creating necessary rules or interface to make BGP working across my cluster machines. If you notice BGP status doesn't change from 'connect' in my case on physical machine. FYI the error you pointed out from log belongs to my VMWare based kubernetes cluster where the IP belongs to Master node of the environment and  I am surprise how is that IP logged in my Physical kubernetes cluster environment where IP configured are completely different range.

Challenge is to make BGP working between nodes and I am unable to pin point exact root cause for this behavior. Do you think software like GlusterFS should impact network configuration of calico because I do have GlusterFS installed on Worker Node.

**Comment by lwr20** [comment]
> Challenge is to make BGP working between nodes

BGP happens over TCP port 179 between nodes.  If its not coming up, then something is blocking it.  firewalld running on the nodes is one possibility?  Some clouds (both public and private) have firewalls in the virtual network itself (e.g. AWS Security Groups).

**Comment by sushilkjaiswar** [comment]
Yes, I did checked all settings regarding firewall which is first most step to debug networking issues. I have the ports enabled and also tried shutting down firewall completely since infrastructure is completely isolated and cannot be reached from outside world. Still no success. I have provided below details of both master and worker node. Do you see any issues?

**Master node settings**,
Interfaces,
> 1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
>     link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
>     inet 127.0.0.1/8 scope host lo
>        valid_lft forever preferred_lft forever
>     inet6 ::1/128 scope host 
>        valid_lft forever preferred_lft forever
> 2: enp3s0f0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
>     link/ether 78:7b:8a:e2:50:14 brd ff:ff:ff:ff:ff:ff
>     inet 192.168.0.124/24 brd 192.168.0.255 scope global noprefixroute enp3s0f0
>        valid_lft forever preferred_lft forever
>     inet6 fe80::7098:3fc3:1d49:28d1/64 scope link noprefixroute 
>        valid_lft forever preferred_lft forever
> 3: wlp2s0: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN group default qlen 1000
>     link/ether 30:d9:d9:eb:23:2e brd ff:ff:ff:ff:ff:ff
> 4: docker0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default 
>     link/ether 02:42:54:ba:72:29 brd ff:ff:ff:ff:ff:ff
>     inet 172.17.0.1/16 brd 172.17.255.255 scope global docker0
>        valid_lft forever preferred_lft forever
> 5: tunl0@NONE: <NOARP,UP,LOWER_UP> mtu 1480 qdisc noqueue state UNKNOWN group default qlen 1000
>     link/ipip 0.0.0.0 brd 0.0.0.0
>     inet 192.168.100.128/32 scope global tunl0
>        valid_lft forever preferred_lft forever
> 8: cali34325993410@if4: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1480 qdisc noqueue state UP group default 
>     link/ether ee:ee:ee:ee:ee:ee brd ff:ff:ff:ff:ff:ff link-netnsid 0
>     inet6 fe80::ecee:eeff:feee:eeee/64 scope link 
>        valid_lft forever preferred_lft forever
> 10: cali4041ab698b4@if4: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1480 qdisc noqueue state UP group default 
>     link/ether ee:ee:ee:ee:ee:ee brd ff:ff:ff:ff:ff:ff link-netnsid 2
>     inet6 fe80::ecee:eeff:feee:eeee/64 scope link 
>        valid_lft forever preferred_lft forever


Firewall rules
captain@captain-america:~$ sudo ufw show added
> Added user rules (see 'ufw status' for running firewall):
> ufw allow 22/tcp
> ufw allow 179
> ufw allow 179/tcp
> ufw allow 1023/tcp
> ufw allow 631/tcp
> ufw allow 10250
> ufw allow 10250/tcp

IPtables rules,

> captain@captain-america:~$ ip r
> default via 192.168.0.1 dev enp3s0f0 proto static metric 100 
> 169.254.0.0/16 dev enp3s0f0 scope link metric 1000 
> 172.17.0.0/16 dev docker0 proto kernel scope link src 172.17.0.1 linkdown 
> 192.168.0.0/24 dev enp3s0f0 proto kernel scope link src 192.168.0.124 metric 100 
> blackhole 192.168.100.128/26 proto bird 
> 192.168.100.129 dev cali34325993410 scope link 
> 192.168.100.131 dev cali4041ab698b4 scope link

 

**Worker Node settings**,

Interfaces,

> 1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
>     link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
>     inet 127.0.0.1/8 scope host lo
>        valid_lft forever preferred_lft forever
>     inet6 ::1/128 scope host 
>        valid_lft forever preferred_lft forever
> 2: enp3s0f0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
>     link/ether 38:c9:86:4e:60:a5 brd ff:ff:ff:ff:ff:ff
>     inet 192.168.0.123/24 brd 192.168.0.255 scope global noprefixroute enp3s0f0
>        valid_lft forever preferred_lft forever
>     inet6 fe80::cfe3:afc6:78d:cf19/64 scope link noprefixroute 
>        valid_lft forever preferred_lft forever
> 3: wlp2s0: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN group default qlen 1000
>     link/ether ac:29:3a:ee:e5:34 brd ff:ff:ff:ff:ff:ff
> 4: docker0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default 
>     link/ether 02:42:91:a9:8b:66 brd ff:ff:ff:ff:ff:ff
>     inet 172.17.0.1/16 brd 172.17.255.255 scope global docker0
>        valid_lft forever preferred_lft forever
> 5: tunl0@NONE: <NOARP,UP,LOWER_UP> mtu 1480 qdisc noqueue state UNKNOWN group default qlen 1000
>     link/ipip 0.0.0.0 brd 0.0.0.0
>     inet 192.168.100.192/32 scope global tunl0
>        valid_lft forever preferred_lft forever
> 37: cali63a708a7d8f@if4: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1480 qdisc noqueue state UP group default 
>     link/ether ee:ee:ee:ee:ee:ee brd ff:ff:ff:ff:ff:ff link-netnsid 0
>     inet6 fe80::ecee:eeff:feee:eeee/64 scope link 
>        valid_lft forever preferred_lft forever

Firewall rules
> nk@nick-fury:~$ sudo ufw show added
> Added user rules (see 'ufw status' for running firewall):
> ufw allow 22/tcp
> ufw allow 179/tcp
> ufw allow 1023/tcp
> ufw allow 10250
> ufw allow 10250/tcp

IPtables rules,

> nk@nick-fury:~$ ip r
> default via 192.168.0.1 dev enp3s0f0 proto static metric 100 
> 169.254.0.0/16 dev enp3s0f0 scope link metric 1000 
> 172.17.0.0/16 dev docker0 proto kernel scope link src 172.17.0.1 linkdown 
> 192.168.0.0/24 dev enp3s0f0 proto kernel scope link src 192.168.0.123 metric 100 
> blackhole 192.168.100.192/26 proto bird 
> 192.168.100.193 dev cali63a708a7d8f scope link

**Comment by sushilkjaiswar** [comment]
Closing this issue since, I have resolved the issue by using calico reflector deployment which worked in my case.
