### ISSUE TITLE
Missing upgrade instructions for installs using Tigera Operator

### ISSUE THREAD

**Issue by r3pek** [projectcalico/calico#4426]
Well, not much more I can say ;) They are missing from the upgrade page.

**Comment by lwr20** [comment]
In the meantime, I believe the upgrade procedure is just:
```
kubectl apply -f https://docs.projectcalico.org/archive/v3.18/manifests/tigera-operator.yaml
```
(or similar, depending on what release you want to upgrade to)

**Comment by mojoa** [comment]
May want to include client upgrade process as well?
``
kubectl exec -ti -n kube-system calicoctl -- calicoctl version
Client Version:    v3.16.4
Git commit:        51418082
Cluster Version:   v3.18.1
Cluster Type:      typha,kdd,k8s,operator,bgp,kubeadm
``

**Comment by lwr20** [comment]
> May want to include client upgrade process as well?

Just delete it and create a new one from the calicoctl install doc in the uplevel version.  Its not really an "upgrade", so much as "throw away the old one and install the new".

**Comment by mojoa** [comment]
Should this work?

<pre>
[ec2-user@k8y ~]$ kubectl exec -ti -n kube-system calicoctl -- calicoctl version
Client Version:    v3.16.4
Git commit:        51418082
Cluster Version:   v3.18.1
Cluster Type:      typha,kdd,k8s,operator,bgp,kubeadm
[ec2-user@k8y ~]$ kubectl get pod -n kube-system calicoctl
NAME        READY   STATUS    RESTARTS   AGE
calicoctl   1/1     Running   17         143d
[ec2-user@k8y ~]$ kubectl delete pod -n kube-system calicoctl
pod "calicoctl" deleted
[ec2-user@k8y ~]$ kubectl get pod -n kube-system calicoctl
Error from server (NotFound): pods "calicoctl" not found
[ec2-user@k8y ~]$ kubectl apply -f https://docs.projectcalico.org/manifests/calicoctl-etcd.yaml
pod/calicoctl created
[ec2-user@k8y ~]$ kubectl get pod -n kube-system calicoctl
NAME        READY   STATUS                       RESTARTS   AGE
calicoctl   0/1     CreateContainerConfigError   0          2m10s
[ec2-user@k8y ~]$

**Comment by lwr20** [comment]
https://docs.projectcalico.org/manifests/calicoctl.yaml is the one to use when your cluster is using the kubernetes api as a datastore.  
This is shown by the `Cluster Type: ...kdd,...` output from calicoctl version.

Yes, it would be a good idea for the docs to mention that.  Do you fancy raising a PR for that?
