### ISSUE TITLE
Calico does not start in K8s built from the master branch

### ISSUE THREAD

**Issue by uablrek** [projectcalico/calico#4443]
When using K8s built from the master branch calico pods does not start;
```
  15:27:30 Server Version: v1.21.0-beta.0.423+60a499839555d7
  15:27:30 Linux 5.11.1 #11 SMP Thu Mar 4 07:28:24 CET 2021
  15:27:30 CNI-plugin; calico/cni:v3.18.0
  15:27:30 Proxy-mode: "ipvs"
$ kubectl get pods -n kube-system
NAME                                       READY   STATUS              RESTARTS   AGE
calico-kube-controllers-6949477b58-hxgtq   0/1     ContainerCreating   0          10m
calico-node-274wj                          0/1     CrashLoopBackOff    6          10m
calico-node-ft9tz                          0/1     CrashLoopBackOff    6          10m
calico-node-hzzdg                          0/1     CrashLoopBackOff    6          10m
calico-node-rkq46                          0/1     CrashLoopBackOff    6          10m
```
This issue has been preceeded with some discussions on slack;
https://calicousers.slack.com/archives/C0BCA117T/p1614864068003000

Calico (and K8s) is configured for dual-stack [calico.yaml.txt](https://github.com/projectcalico/calico/files/6084508/calico.yaml.txt)

## Expected Behavior

Calico shall start even on K8s-master. This is not something that affect normal users yet, but it should be fixed anyway IMO.

## Current Behavior

See the `kubectl get pods` above.

Output from `kubectl describe pod -n kube-system calico-kube-controllers-6949477b58-hxgtq` [calico-kube-controllers.describe.txt](https://github.com/projectcalico/calico/files/6084546/calico-kube-controllers.describe.txt).

Output from `kubectl logs -n kube-system calico-node-hzzdg` [calico-node.log.txt](https://github.com/projectcalico/calico/files/6084550/calico-node.log.txt).

## Steps to Reproduce (for bugs)
1. Build a K8s system built on the K8s master branch
2. Try to start Calico

## Context

Personal CI with K8s bleeding-edge do spot exactly these kind of problems.

## Your Environment

* Calico version: calico/cni:v3.18.0
* Orchestrator version (e.g. kubernetes, mesos, rkt): K8s v1.21.0-beta.0.423+60a499839555d7
* Operating System and version: Local built kvm VMs
* Link to your project (optional):

**Comment by uablrek** [comment]
Is it possible to define `spec.bpfLogLevel` in the configuration as a work-around?
```
2021-03-04 14:38:59.182 [ERROR][8] startup/startup.go 1052: Failed to create default IPv4 IP pool: 11.0.0.0/16 error=FelixConfiguration.crd.projectcalico.org "default" is invalid: spec.bpfLogLevel: Invalid value: "null": spec.bpfLogLevel in body must be of type string: "null"
```

**Comment by caseydavenport** [comment]
Hm, this was supposed to be fixed a long time ago: https://github.com/projectcalico/libcalico-go/pull/1277

It also doesn't seem to be marked required in the latest v3.18 manifests, at least: https://github.com/projectcalico/calico/blob/release-v3.18/_includes/charts/calico/crds/kdd/crd.projectcalico.org_felixconfigurations.yaml

@uablrek can you check the felixconfig on your cluster to see if it has bpfLogLevel marked as required?

**Comment by uablrek** [comment]
> @uablrek can you check the felixconfig on your cluster to see if it has bpfLogLevel marked as required?

My calico config is included the description in this issue. Can it be seen in it?

And also, why does it work fine in `v1.21.0-beta.0` and not in `master`? What in K8s can make a difference?

**Comment by uablrek** [comment]
I do;
```
curl https://docs.projectcalico.org/manifests/calico.yaml -O
```
an modify for dual-stack when I upgrade. So compare my config [calico.yaml.txt](https://github.com/projectcalico/calico/files/6084508/calico.yaml.txt) to see exactly what I have altered.

**Comment by uablrek** [comment]
A difference is that go1.16 is used. An undefined string should be "" right? Not "null". (I am speculating)

**Comment by uablrek** [comment]
I did;
```
git clone --depth 1 --branch v1.21.0-beta.0 https://github.com/kubernetes/kubernetes.git kubernetes-v1.21.0-beta.0
ln -s kubernetes-v1.21.0-beta.0 kubernetes
```
and built with go1.16 and the problem occured!

It seems to be gov1.16 related.

**Comment by uablrek** [comment]
Build the same checkout with go v1.15.7 and Calico works.

**Comment by uablrek** [comment]
More slack discussions;
https://kubernetes.slack.com/archives/C09R23FHP/p1614883890025600

Created an audit file [audit.txt](https://github.com/projectcalico/calico/files/6086256/audit.txt)

**Comment by uablrek** [comment]
For the record (for my own memory);

File /etc/audit.yaml;
```
apiVersion: audit.k8s.io/v1
kind: Policy
rules:
- level: RequestResponse
  resource:
  - group: crd.projectcalico.org
    resources: ["felixconfigurations"]
- level: Metadata
```
Passed to kube-apiserver;
```
--audit-policy-file=/etc/audit.yaml --audit-log-path=/var/audit
```

**Comment by liggitt** [comment]
This was a bug in the openapi validation that was inert until a change in the values produced by go1.16 reflect.Zero() suddenly became comparable. Detailed triage in https://github.com/kubernetes/kubernetes/issues/99804 and fix in https://github.com/kubernetes/kubernetes/pull/99817. Only affects builds on go1.16 and will be fixed well before the next Kubernetes release.

**Comment by uablrek** [comment]
Closing with the comment above.

**Comment by fasaxc** [comment]
Fixed upstream, the best kind of tricky bug! Thanks @uablrek @liggitt
