### ISSUE TITLE
One node can't connect with the others

### ISSUE THREAD

**Issue by jaimehrubiks** [projectcalico/calico#4446]
I have a cluster of around 10 nodes, all of them working properly except one. I ask here because the issue is a bit estrange, as it looks like the issue is on the "good" nodes, as it seems the failing node is replying packets properly.

Let's say we have these nodes and these are their IPs. This is using the ipip module and the interfaces are main and tunl0 for simplification
Node A: A-main-IP, A-tunl0-IP
Node B: B-main-IP, B-tunl0-IP
...
Node Z: Z-main-IP, Z-tunl0-IP (this is the non-working node)

If I send a packet from A to B (or C or D...) using the tunl0 interface, it works as expected. I can see the encapsulated packet travels the main interface using tunl0-IP under main-IP. And this works fine for all nodes except Z, for ICMP, TCP and UDP.

If I send a packet from A to Z using the tunl0 interface, it does not work properly. However there are a few gotchas.
1. Ping does work, and UDP and TCP don't
2. A to Z works fine, I can see the received packets on Z (using netcat on the host, using udp containers...)
3. Replies or messages from Z to A on UDP and TCP are not working properly. However, I can see the properly forged IPIP packet on Z **and on A**, captured on the main interfaces. But the decapsulated packet from Z to A is missing in A's tunl0 interface capture, and it is never received by the application.

That is why it looks like the issue can be explained as: **The rest of the nodes won't decapsulate the IPIP packet when they are received from node Z**

## Context
I tried a few things:

1. I see that calicoctl node status doesn't show any issue
2. Routes look good
3. /etc/hosts looks good
4. I don't see packets dropped at ethernet level (we knew this because the packet reaches the main interface)
5. I don't see any packet drop on iptables looking at the counters. I tried following the chains just in case, and I see that the ipset cali40all-hosts-net is composed of all nodes properly
6. The tunl0 interface looks identical on the nodes using "ip link show" "ip a show" "ip tunnel", except for the actual IP.
7. Firewalld is disabled
8. selinux is disabled
9. There are no network policies in the cluster

## Your Environment
* Calico version: Container calico docker.io/calico/cni:v3.7.3
* Orchestrator version (e.g. kubernetes, mesos, rkt): Kubernetes
* iptables v1.4.21
* Operating System and version: Centos 7.8 and 7.9

Any ideas? Thank you

**Comment by lmm** [comment]
A related issue with Centos/RHEL and IPIP is here: https://github.com/projectcalico/calico/issues/4384

But the OS version is quite a bit newer than yours. Are you able to try this out with a newer Calico version? v3.7 is really old at this point.
