### ISSUE TITLE
The calico-node service fails to start with error "Could not find container for entity id xxx" displayed

### ISSUE THREAD

**Issue by scjane** [projectcalico/calico#445]
I deployed a kubernetes cluster consisting of 1 master node and 2 minion nodes with calico network selected (using the calico-node image of version v0.18.0). Now, the calico-node service on all the 3 nodes fails to start while the docker and etcd services are running properly. I tried to run the "cailcoctl node" command on the master node, and an error message "APIError: 500 Server Error: Internal Server Error ("Could not find container for entity id xxx“ is displayed. However, the calico-node container exists on one of the mininon node and its status is normal as it can be seen in the output of the "docker ps" command on the minion node. Then, after running "docker exec -it [ID of the calico-node's container]” command on the node, the following messages are displayed:
```
runsv bird: fatal: unable to lock supervise/lock: temporary failure
runsv bird6: fatal: unable to lock supervise/lock: temporary failure
runsv confd: fatal: unable to lock supervise/lock: temporary failure
runsv felix: fatal: unable to lock supervise/lock: temporary failure
runsv bird: fatal: unable to lock supervise/lock: temporary failure
runsv bird6: fatal: unable to lock supervise/lock: temporary failure
runsv confd: fatal: unable to lock supervise/lock: temporary failure
runsv felix: fatal: unable to lock supervise/lock: temporary failure
```

What can I do for troubleshooting?

**Comment by fasaxc** [comment]
@scjane 0.18.0 is a very old release, please update to the latest release of Calico and verify that the problem still occurs.  The current versions are listed here: http://docs.projectcalico.org/v2.0/releases/

**Comment by djosborne** [comment]
@scjane Closing since we haven't heard from you for some time. Do reopen / comment if there is a reason you must use 0.18.0, or if updating did not resolve your issue.
