### ISSUE TITLE
WIBNI bare metal install mentioned using docker images

### ISSUE THREAD

**Issue by lwr20** [projectcalico/calico#447]
Bare metal install has lots of scary command line stuff: http://docs.projectcalico.org/v2.0/getting-started/bare-metal/bare-metal

But we should document the alternative: simply run `calico/felix` and `etcd` containers in docker.

**Comment by caseydavenport** [comment]
It does now!

Though, it's pretty minimal: https://docs.projectcalico.org/v3.3/getting-started/bare-metal/installation/container
