### ISSUE TITLE
Calico OpenShift install instructions do not work (01-crd-installation.yaml is missing a CRD)

### ISSUE THREAD

**Issue by smarterclayton** [projectcalico/calico#4476]
## Expected Behavior

OpenShift CI runs the set of steps decribed in https://docs.projectcalico.org/getting-started/openshift/installation and inlines the curl statements for providing manifests to the installer:

```
curl https://docs.projectcalico.org/manifests/ocp/crds/01-crd-installation.yaml -o manifests/01-crd-installation.yaml
...
```

We expect those to install Calico so we can run our e2e suite.

## Current Behavior

However, it looks like sometime after Feb 22nd this started failing: https://testgrid.k8s.io/redhat-openshift-ocp-release-4.8-informing#release-openshift-origin-installer-e2e-aws-calico-4.8

Looking at the bootstrap logs I see:

```
Mar 16 22:40:36 ip-10-0-8-22 bootkube.sh[49069]: Assert creation failed: failed to load some manifests:
Mar 16 22:40:36 ip-10-0-8-22 bootkube.sh[49069]: "01-crd-installation.yaml": unable to decode asset "01-crd-installation.yaml": Object 'Kind' is missing in 'null'
Mar 16 22:40:36 ip-10-0-8-22 bootkube.sh[49069]: Error: error while checking pod status: timed out waiting for the condition
```

If I curl locally I see

```
$ curl https://docs.projectcalico.org/manifests/ocp/crds/01-crd-installation.yaml 
---
# Source: crds/operator.tigera.io_installations_crd.yaml
```

Which looks wrong (I assume that was supposed to inline the CRD - the resulting content is not valid as a Kube yaml object to deploy).

I *assume* the file was renamed or moved and the script broke.  I randomly sampled the other CRDs and most had content, but did not complete a full review.

## Steps to Reproduce (for bugs)

See https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/logs/release-openshift-origin-installer-e2e-aws-calico-4.8/1371949603124940800/artifacts/e2e-aws/installer/ for the bootstrap logs, the installer manifests are curled from: 

https://github.com/openshift/release/blob/master/ci-operator/templates/openshift/installer/cluster-launch-installer-e2e.yaml#L816

which I verified were up to date today.

## Context

Unable to install Calico in an OpenShift CI environment

## Your Environment

* Calico version: latest
* Orchestrator version (e.g. kubernetes, mesos, rkt): OpenShift 4.8 prerelease
* Operating System and version: RHCOS

**Comment by tmjd** [comment]
Thank you for bringing this to our attention. It has been fixed with #4480
