### ISSUE TITLE
calico/node is not ready: BIRD is not ready: BGP not established with 1xx.2xx.3x.196 ....

### ISSUE THREAD

**Issue by trungphungduc** [projectcalico/calico#4479]
K8s cluster on Centos 7: 1 Master (.196) - 1 Slave (.197)
install as follow:
1. Install Containerd: https://kubernetes.io/docs/setup/production-environment/container-runtimes/
2. Install kubeadm: kubeadm init --cri-socket="/run/containerd/containerd.sock" --pod-network-cidr=192.168.0.0/16 
3. Install calisto: https://docs.projectcalico.org/getting-started/kubernetes/quickstart

## Current Behavior
Ready: 0/1
<img width="596" alt="Screen Shot 2021-03-18 at 09 35 16" src="https://user-images.githubusercontent.com/42766976/111611577-33cea600-880f-11eb-9dd6-d7d745656922.png">

## Expected Behavior
Ready: 1/1

## Possible Solution
I have try so many solution: => **NOT OK** 
1. config NetworkManager in /etc/NetworkManager/conf.d/calico.conf
https://docs.projectcalico.org/archive/v3.18/maintenance/troubleshoot/troubleshooting#error-caliconode-is-not-ready-bird-is-not-ready-bgp-not-established-with-10001

2. kubectl set env daemonset/calico-node -n calico-system IP_AUTODETECTION_METHOD=can-reach=8.8.8.8
3. kubectl set env daemonset/calico-node -n calico-system IP_AUTODETECTION_METHOD=interface=eth.*

<img width="811" alt="Screen Shot 2021-03-18 at 17 30 38" src="https://user-images.githubusercontent.com/42766976/111612385-fdddf180-880f-11eb-9a25-85155e7894df.png">

## Your Environment

* Calico version:
- Client Version:    v3.13.2
- Git commit:        eb796e31
- Cluster Version:   v3.17.1
- Cluster Type:      typha,kdd,k8s,operator,bgp,kubeadm
* Orchestrator version: kubernetes
* Operating System and version: Centos 7

**Comment by lwr20** [comment]
> Operating System and version: Centos 7

Is firewalld blocking BGP?  tcp port 179.

**Comment by trungphungduc** [comment]
> > Operating System and version: Centos 7
> 
> Is firewalld blocking BGP? tcp port 179.

Thanks, i fixed the problem by adding PORT 179.
`firewall-cmd --zone=public --add-port=179/tcp --permanent`
then reload firewall to apply changes.
