### ISSUE TITLE
Add support for WireGuard with IPv6

### ISSUE THREAD

**Issue by dseomn** [projectcalico/calico#4492]
https://docs.projectcalico.org/security/encrypt-cluster-pod-traffic#before-you-begin says:
> Note: WireGuard in Calico does not support IPv6 at this time. Also, encryption using WireGuard is not supported if CALICO_NETWORKING_BACKEND=none (e.g. managed Kubernetes platforms EKS, AKS and GKE).

It would be really nice if Calico supported WireGuard with IPv6, so I'm filing a feature request because I didn't see an existing one.

**Comment by lwr20** [comment]
@petercork FYI

**Comment by inistor** [comment]
One more 'vote' for this. We are running an on-prem IPv6 vanilla kubernets so I can assist with testing, if needed.

**Comment by telmich** [comment]
We'd be very much interested in this, as all clusters are IPv6 only in our environment

**Comment by steffann** [comment]
Hey @coutinhop, I see you self-assigned this issue. Anything we can do to help?

**Comment by lwr20** [comment]
I think its very close to being done.   

We have a "hashrelease" (basically a build from the tip of the v3.24 branch, including docs and manifests) here if you wanted to take it for a spin: https://2022-08-03-v3-24-navigator.docs.eng.tigera.net/

Obviously this build is not supported or ready for GA, but its what we're testing on internally on the way to that point.

**Comment by mgleung** [comment]
This feature should be done! See https://projectcalico.docs.tigera.io/release-notes/ for more details

**Comment by steffann** [comment]
Thanks!
