### ISSUE TITLE
About Calico use in Non-cluster host

### ISSUE THREAD

**Issue by Daose1997** [projectcalico/calico#4496]
When I have a k8s cluster, if  there has a non-cluster host, could I use calico-node in non-cluster host, let this host invoko pod in k8s cluster

Now,I have a k8s cluster use Calico,then I install a container of calico-node in a non-cluster host, and use the same etcd as save.But the non-cluster host can't invoke cluster pod IP.

**Comment by lwr20** [comment]
Yes, this should be possible.  What encap are you using (if any) - IPIP or VXLAN?

If IPIP, can you check that your non-cluster hosts have set up BGP peering with the cluster?  

It might be easier to debug this via slack - http://slack.projectcalico.org/
