### ISSUE TITLE
Improve Route Reflector information

### ISSUE THREAD

**Issue by robbrockbank** [projectcalico/calico#45]
We have a Route Reflector container in our bird fork.  We should consider including those docs in here.

https://github.com/projectcalico/calico-bird/tree/feature-ipinip/build_routereflector

**Comment by robbrockbank** [comment]
Also see:  #223 

Looks like we want to restructure our RR docs to include details about our RR container image.

**Comment by ozdanborne** [comment]
Fixed by #567
