### ISSUE TITLE
Support Calico using bidirectional tunnel

### ISSUE THREAD

**Issue by khalid-davis** [projectcalico/calico#4505]
Hello, everyone. Assume that two computers are in different LANs and one has a has a public IP address and the other does not. Is it possible to use a bidirectional tunnel (for example, ws/gRPC) to make the calico work properly and implement the communication between the containers on the two computers?

**Comment by lwr20** [comment]
Calico requires that the nodes are L3 routable.  

So if you were to set up overlay tunnels of some sort between the nodes, you could configure Calico to use the tunnel interfaces, and that would work.  But Calico doesn't have anything to set that overlay up for you.

**Comment by khalid-davis** [comment]
OK, thanks. I'll try to implement this function later and feed back here.

**Comment by lwr20** [comment]
Feel free to join us on http://slack.projectcalico.org/ if it doesn't "just work" - we can give more interactive help there

**Comment by bcreane** [comment]
Hi @khalid-davis, I'll close for now since the original query was answered quite capably by @lwr20 . Please reach out if on http://slack.projectcalico.org with questions while you work on your pull request. cheers
