### ISSUE TITLE
Advertise Kubernetes service IP addresses

### ISSUE THREAD

**Issue by thanhlong9x** [projectcalico/calico#4506]
I am testing Advertise Kubernetes service IP addresses feature. I refer this doc: https://www.projectcalico.org/kubernetes-service-ip-route-advertisement/
But I don't get result as doc

## Expected Behaviors
service IP is routed over BGP protocol 

## Current Behavior
all node BGP are established each other but service IP isn't routed over BGP protocol 

## Steps to Reproduce (for bugs)

1. Create cluster K8s run calico net
2. Config cluster to run eBGP 
3. A independent node run bird
4. Config bird to peer with all node in cluster

## Your Environment
* Calico version: v3.14.1
* Orchestrator version (kubernetes): v1.17.0
* Operating System and version: centos 7

**Comment by song-jiang** [comment]
@neiljerram Could you help?

**Comment by lwr20** [comment]
Take a look at: https://docs.projectcalico.org/networking/advertise-service-ips

**Comment by caseydavenport** [comment]
@thanhlong9x yes, the link you shared is very old. I'd recommend using the link the @lwr20 suggested, which is the supported documentation and much more up to date.

If you're still having issues after that, please report back and I'll reopen this issue.

**Comment by thanhlong9x** [comment]
Yes, I used link of lwr20 . And It doesn't work my expect. Is my link no longer correct? So why is the link @lwr20  sent still has my link ?

**Comment by caseydavenport** [comment]
The blog post is no longer updated, and very old. 

I'd recommend:
- Updating to a more recent version of Calico (v3.14 is fairly old, and we've made impvoements in this area since)
- Follow the steps at docs.projectcalico.org (not the blog post) and see if they work for you.

Barring that, we'll need to see some more details. e.g., what your BGPConfiguration looks like, how you're enabling the feature, and logs from calico/node.

**Comment by thanhlong9x** [comment]
This is my Bgp configuration. I want to advertise cluster IP 10.96.0.0/12 of cluster. 
![image](https://user-images.githubusercontent.com/29721257/117113838-3da76b00-adb5-11eb-8a2d-16cb96b4aab1.png)

However, I just see IP of Pod when show route table
![image](https://user-images.githubusercontent.com/29721257/117114271-d0e0a080-adb5-11eb-9440-fdd270857cc6.png)
