### ISSUE TITLE
Create a repo for the Calico Helm charts

### ISSUE THREAD

**Issue by lwr20** [projectcalico/calico#4514]
## Expected Behavior
As mentioned in https://github.com/projectcalico/calico/issues/717#issuecomment-814633729, wouldn't it be nice if Calico Helm charts were in a repo?

## Current Behavior
Currently its necessary to download the Helm chart and apply it with helm directly:
https://docs.projectcalico.org/master/getting-started/kubernetes/helm

But it would be great if we could have a Helm repo which could be added with `helm repo add`.  This would make for easier upgrading.

## Possible Solution
Create a helm repo, possibly following https://helm.sh/docs/howto/chart_repository_sync_example/

## Steps to Reproduce (for bugs)
n/a

## Context
Please comment on this issue and add your use case so that this can be prioritised!

## Your Environment
n/a

**Comment by viceice** [comment]
A helm repo would allow  terraform helm provider usage 🎉 

https://registry.terraform.io/providers/hashicorp/helm/latest/docs

**Comment by p3lim** [comment]
It would also help with Flux (and other Helm operators):

https://docs.fluxcd.io/projects/helm-operator/en/stable/helmrelease-guide/chart-sources/#helm-repositories

**Comment by gclawes** [comment]
Helm Chart Releaser Action would be useful for this: https://github.com/helm/chart-releaser-action

The chart is already stored as release artifacts, this would provide indexing.

**Comment by vrabbi** [comment]
This would be extremely helpful in automating the installation and upgrades of calico. Once the chart is built having it added to a repo seems to make sense to me and would as mentioned make terraform argo and flux workflows much easier.

**Comment by vrabbi** [comment]
This would also allow management via tools like kubeapps which would make it much easier to managr upgrades from a simple ui.

**Comment by stevehipwell** [comment]
@lwr20 is there a rough timeframe for when v3.20 will be shipping?

**Comment by lwr20** [comment]
From Calico Community meeting notes of 9th June, I see "mid to late July" for v3.20

**Comment by lwr20** [comment]
FWIW, the index is already up at https://calico-public.s3.amazonaws.com/charts/index.yaml if you wanted to try it out, but that will NOT be the official URL once v3.20 ships.

**Comment by caseydavenport** [comment]
@lwr20 is there anything more to do on this one or can we close it with v3.20 pending?

**Comment by lwr20** [comment]
If that's the normal procedure, sure, feel free to close.
