### ISSUE TITLE
New Line is picked up by Calico along with the hostname

### ISSUE THREAD

**Issue by ImadNaily** [projectcalico/calico#4515]
Calico Node v3.17.1 is picking up a \n in the hostname per the below:
 startup/startup.go 187: Unable to set NetworkUnavailable to False error=timed out patching node, last error was: nodes "prodrpxapp\n" not found
2021-04-07 05:30:26.982 [ERROR][8] startup/startup.go 200: Unable to set node resource configuration error=error with field Metadata.Name = 'prodrpxapp
' (name must consist of lower case alphanumeric characters, '-' or '.' (regex: [a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*))
you can see the \n in the nodes not found and also in the Metadata.Name there is a new line after the node name
I have looked at the hostname and i can not see \n
## Expected Behavior

Not sure if it is a bug but could not figure out where is the \n coming from in the hostname

## Steps to Reproduce (for bugs)

1. Not sure how to reproduce. I have many calico nodes running with no issues. this node is failing due to the new line in the hostname during the joining of the node.
2. Tried to export the NODENAME but calico did not pick it up
3. Not sure what else to try, appreciate any pointers
4.

## Your Environment

* Calico version
* Orchestrator version (e.g. kubernetes, mesos, rkt):
* Operating System and version:
* Link to your project (optional):

**Comment by caseydavenport** [comment]
@ImadNaily strange. How have you installed Calico? Is this just using the normal k8s manifests? And modifications?

**Comment by caseydavenport** [comment]
The node name is calculated based on this logic: https://github.com/projectcalico/node/blob/7d4be57215df3eafdbbac391c537b097c6192da5/pkg/startup/startup.go#L398-L410

Do you see any of those logs showing up in the calico/node logs for the failing node?

**Comment by ImadNaily** [comment]
> @ImadNaily strange. How have you installed Calico? Is this just using the normal k8s manifests? And modifications?

Standard Manifests installation with etcd store. No modification. Works on control-plane nodes and three other nodes just fine.

**Comment by ImadNaily** [comment]
it was picking up the name from:
Using stored node name from /var/lib/calico/nodename
once i deleted the file all is up and running thanks for the pointers

**Comment by ImadNaily** [comment]
thanks

**Comment by caseydavenport** [comment]
Glad you got it working! Let me know if you see this again - I'm not sure how the newline got into that file. Perhaps it was hand-edited at some point?
