### ISSUE TITLE
CrashLoopBackOff in calico-node

### ISSUE THREAD

**Issue by dinucatona** [projectcalico/calico#4519]
Getting CrashLoopBackOff when starting a a calico netwrok in kubernetes. Been trying to figure it out for whole day and was unsuccessful. 

I have kubernetes cluster set up with nothing in it as sown below:
NAMESPACE     NAME                                                READY   STATUS              RESTARTS   AGE
kube-system   coredns-5644d7b6d9-7f76q                            0/1     ContainerCreating   0          13h
kube-system   coredns-5644d7b6d9-p8f8h                            0/1     ContainerCreating   0          13h
kube-system   etcd-calico-master.localdomain                      1/1     Running             1          13h
kube-system   kube-apiserver-calico-master.localdomain            1/1     Running             1          13h
kube-system   kube-controller-manager-calico-master.localdomain   1/1     Running             1          13h
kube-system   kube-proxy-r8d5d                                    1/1     Running             1          13h
kube-system   kube-scheduler-calico-master.localdomain            1/1     Running             1          13h

I am using the calico.yam file from here (https://docs.projectcalico.org/manifests/calico.yaml) and changing the pool cidr as follows::
            # The default IPv4 pool to create on startup if none exists. Pod IPs will be
            # chosen from this range. Changing this value after installation will have
            # no effect. This should fall within `--cluster-cidr`.
            - name: CALICO_IPV4POOL_CIDR
              value: "10.245.0.0/16"

## Current Behavior
When the pods start up gettign a status of  CrashLoopBackOff in the calico-node pod.

kubectl logs calico-node-77gqm -n kube-system
2021-04-08 13:10:32.918 [INFO][8] startup/startup.go 383: Early log level set to info
2021-04-08 13:10:32.918 [INFO][8] startup/startup.go 399: Using NODENAME environment for node name calico-master.localdomain
2021-04-08 13:10:32.918 [INFO][8] startup/startup.go 411: Determined node name: calico-master.localdomain
2021-04-08 13:10:32.918 [INFO][8] startup/startup.go 103: Starting node calico-master.localdomain with version v3.18.1
2021-04-08 13:10:32.921 [INFO][8] startup/startup.go 443: Checking datastore connection
2021-04-08 13:10:32.934 [INFO][8] startup/startup.go 467: Datastore connection verified
2021-04-08 13:10:32.935 [INFO][8] startup/startup.go 113: Datastore is ready
2021-04-08 13:10:32.955 [INFO][8] startup/customresource.go 102: Error getting resource Key=GlobalFelixConfig(name=CalicoVersion) Name="calicoversion" Resource="GlobalFelixConfigs" error=the server could not find the requested resource (get GlobalFelixConfigs.crd.projectcalico.org calicoversion)
2021-04-08 13:10:32.996 [INFO][8] startup/startup.go 768: Using autodetected IPv4 address on interface eth0: 10.0.0.66/26
2021-04-08 13:10:32.996 [INFO][8] startup/startup.go 845: No AS number configured on node resource, using global value
2021-04-08 13:10:32.996 [INFO][8] startup/startup.go 188: Setting NetworkUnavailable to False
2021-04-08 13:10:33.037 [INFO][8] startup/startup.go 894: found v6= in the kubeadm config map
2021-04-08 13:10:33.050 [INFO][8] startup/startup.go 706: CALICO_IPV4POOL_NAT_OUTGOING is true (defaulted) through environment variable
2021-04-08 13:10:33.050 [INFO][8] startup/startup.go 1046: Ensure default IPv4 pool is created. IPIP mode: Always, VXLAN mode: Never
2021-04-08 13:10:33.065 [ERROR][8] startup/startup.go 1052: Failed to create default IPv4 IP pool: 10.245.0.0/16 error=Get "https://10.96.0.1:443/apis/crd.projectcalico.org/v1/felixconfigurations/default": stream error: stream ID 25; INTERNAL_ERROR
2021-04-08 13:10:33.065 [WARNING][8] startup/startup.go 1340: Terminating
Calico node failed to start

cluster init's with 
kubeadm init --pod-network-cidr=10.245.0.0/16

kubectl describe pod -n kube-system   kube-controller-manager-calico-master.localdomain
Name:                 kube-controller-manager-calico-master.localdomain
Namespace:            kube-system
Priority:             2000000000
Priority Class Name:  system-cluster-critical
Node:                 calico-master.localdomain/10.0.0.66
Start Time:           Thu, 08 Apr 2021 09:05:26 -0400
Labels:               component=kube-controller-manager
                      tier=control-plane
Annotations:          kubernetes.io/config.hash: f94426809d552f70f3693bd71bffaa39
                      kubernetes.io/config.mirror: f94426809d552f70f3693bd71bffaa39
                      kubernetes.io/config.seen: 2021-04-07T20:23:43.743984-04:00
                      kubernetes.io/config.source: file
Status:               Running
IP:                   10.0.0.66
IPs:
  IP:  10.0.0.66
Containers:
  kube-controller-manager:
    Container ID:  docker://23b821d31f8d89161eca9cb7c1d1efae46f8e1d2e575b233386911b6855ea7c1
    Image:         k8s.gcr.io/kube-controller-manager:v1.16.0
    Image ID:      docker://sha256:06a629a7e51cdcc81a5ed6a3e6650348312f20c954ac52ee489a023628ec9c7d
    Port:          <none>
    Host Port:     <none>
    Command:
      kube-controller-manager
      --allocate-node-cidrs=true
      --authentication-kubeconfig=/etc/kubernetes/controller-manager.conf
      --authorization-kubeconfig=/etc/kubernetes/controller-manager.conf
      --bind-address=127.0.0.1
      --client-ca-file=/etc/kubernetes/pki/ca.crt
      --cluster-cidr=10.245.0.0/16
      --cluster-signing-cert-file=/etc/kubernetes/pki/ca.crt
      --cluster-signing-key-file=/etc/kubernetes/pki/ca.key
      --controllers=*,bootstrapsigner,tokencleaner
      --kubeconfig=/etc/kubernetes/controller-manager.conf
      --leader-elect=true
      --node-cidr-mask-size=24
      --requestheader-client-ca-file=/etc/kubernetes/pki/front-proxy-ca.crt
      --root-ca-file=/etc/kubernetes/pki/ca.crt
      --service-account-private-key-file=/etc/kubernetes/pki/sa.key
      --service-cluster-ip-range=10.96.0.0/12
      --use-service-account-credentials=true
    State:          Running
      Started:      Thu, 08 Apr 2021 09:05:28 -0400
    Last State:     Terminated
      Reason:       Error
      Exit Code:    255
      Started:      Wed, 07 Apr 2021 20:24:06 -0400
      Finished:     Thu, 08 Apr 2021 09:05:03 -0400
    Ready:          True
    Restart Count:  1
    Requests:
      cpu:        200m
    Liveness:     http-get http://127.0.0.1:10252/healthz delay=15s timeout=15s period=10s #success=1 #failure=8
    Environment:  <none>
    Mounts:
      /etc/kubernetes/controller-manager.conf from kubeconfig (ro)
      /etc/kubernetes/pki from k8s-certs (ro)
      /etc/pki from etc-pki (ro)
      /etc/ssl/certs from ca-certs (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             True
  ContainersReady   True
  PodScheduled      True
Volumes:
  ca-certs:
    Type:          HostPath (bare host directory volume)
    Path:          /etc/ssl/certs
    HostPathType:  DirectoryOrCreate
  etc-pki:
    Type:          HostPath (bare host directory volume)
    Path:          /etc/pki
    HostPathType:  DirectoryOrCreate
  k8s-certs:
    Type:          HostPath (bare host directory volume)
    Path:          /etc/kubernetes/pki
    HostPathType:  DirectoryOrCreate
  kubeconfig:
    Type:          HostPath (bare host directory volume)
    Path:          /etc/kubernetes/controller-manager.conf
    HostPathType:  FileOrCreate
QoS Class:         Burstable
Node-Selectors:    <none>
Tolerations:       :NoExecute
Events:
  Type    Reason          Age   From                                Message
  ----    ------          ----  ----                                -------
  Normal  Pulled          13h   kubelet, calico-master.localdomain  Container image "k8s.gcr.io/kube-controller-manager:v1.16.0" already present on machine
  Normal  Created         13h   kubelet, calico-master.localdomain  Created container kube-controller-manager
  Normal  Started         13h   kubelet, calico-master.localdomain  Started container kube-controller-manager
  Normal  SandboxChanged  30m   kubelet, calico-master.localdomain  Pod sandbox changed, it will be killed and re-created.
  Normal  Pulled          30m   kubelet, calico-master.localdomain  Container image "k8s.gcr.io/kube-controller-manager:v1.16.0" already present on machine
  Normal  Created         30m   kubelet, calico-master.localdomain  Created container kube-controller-manager
  Normal  Started         30m   kubelet, calico-master.localdomain  Started container kube-controller-manager

ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 00:15:5d:b8:dc:1e brd ff:ff:ff:ff:ff:ff
    inet 10.0.0.66/26 brd 10.0.0.127 scope global noprefixroute eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::110f:e787:1289:6a40/64 scope link noprefixroute
       valid_lft forever preferred_lft forever
3: docker0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default
    link/ether 02:42:33:91:10:aa brd ff:ff:ff:ff:ff:ff
    inet 172.17.0.1/16 brd 172.17.255.255 scope global docker0
       valid_lft forever preferred_lft forever

## Your Environment

* Calico version: 3.18.1
* Kubernetes: 1.16.0
* Operating System and version: Linux calico-master.localdomain 3.10.0-862.el7.x86_64 #1 SMP Fri Apr 20 16:44:24 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

Any input will be appreciated.

**Comment by ayoubsmii19** [comment]
do you have checked Network Ports requirements ? 


Calico networking (BGP) | All | Bidirectional | TCP 179
Calico networking with IP-in-IP enabled (default) | All | Bidirectional | IP-in-IP, often represented by its protocol number 4
Calico networking with VXLAN enabled | All | Bidirectional | UDP 4789
Calico networking with Typha enabled | Typha agent hosts | Incoming | TCP 5473 (default)
flannel networking (VXLAN) | All | Bidirectional | UDP 4789
All | kube-apiserver host | Incoming | Often TCP 443 or 6443*
etcd datastore | etcd hosts | Incoming | Officially TCP 2379 but can vary

**Comment by dinucatona** [comment]
Thanks for the reply.
Not sure how to check for all that. Any more info you can help with?
I do not use typha in this implementation. Also the store is kubernetes not etcd. No flannel overlay network either.

**Comment by dinucatona** [comment]
@ayoubsmii19 here the describe of the calico-node pod. I think this is what you wanted to look at:
[master@calico-master ~]$ kubectl describe pod -n kube-system   calico-node-77gqm
Name:                 calico-node-77gqm
Namespace:            kube-system
Priority:             2000001000
Priority Class Name:  system-node-critical
Node:                 calico-master.localdomain/10.0.0.66
Start Time:           Thu, 08 Apr 2021 09:07:20 -0400
Labels:               controller-revision-hash=5cd6dd7df8
                      k8s-app=calico-node
                      pod-template-generation=1
Annotations:          <none>
Status:               Running
IP:                   10.0.0.66
IPs:
  IP:           10.0.0.66
Controlled By:  DaemonSet/calico-node
Init Containers:
  upgrade-ipam:
    Container ID:  docker://c88f63b5f1571977983484a1a21bd15fbbbc0212fd60f9659ab268ad356b5374
    Image:         calico/cni:v3.18.1
    Image ID:      docker://sha256:21fdaa2fccee2d6fc362b19234e750744a13d361c9ddd8753a2954f3392603bd
    Port:          <none>
    Host Port:     <none>
    Command:
      /opt/cni/bin/calico-ipam
      -upgrade
    State:          Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Thu, 08 Apr 2021 14:34:16 -0400
      Finished:     Thu, 08 Apr 2021 14:34:16 -0400
    Ready:          True
    Restart Count:  1
    Environment Variables from:
      kubernetes-services-endpoint  ConfigMap  Optional: true
    Environment:
      KUBERNETES_NODE_NAME:        (v1:spec.nodeName)
      CALICO_NETWORKING_BACKEND:  <set to the key 'calico_backend' of config map 'calico-config'>  Optional: false
    Mounts:
      /host/opt/cni/bin from cni-bin-dir (rw)
      /var/lib/cni/networks from host-local-net-dir (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from calico-node-token-42kcs (ro)
  install-cni:
    Container ID:  docker://f4f60d87d9c982f1450eab20dedd551a2ee2c56b26915e554da5bd3ebb30ad74
    Image:         calico/cni:v3.18.1
    Image ID:      docker://sha256:21fdaa2fccee2d6fc362b19234e750744a13d361c9ddd8753a2954f3392603bd
    Port:          <none>
    Host Port:     <none>
    Command:
      /opt/cni/bin/install
    State:          Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Thu, 08 Apr 2021 14:34:18 -0400
      Finished:     Thu, 08 Apr 2021 14:34:18 -0400
    Ready:          True
    Restart Count:  0
    Environment Variables from:
      kubernetes-services-endpoint  ConfigMap  Optional: true
    Environment:
      CNI_CONF_NAME:         10-calico.conflist
      CNI_NETWORK_CONFIG:    <set to the key 'cni_network_config' of config map 'calico-config'>  Optional: false
      KUBERNETES_NODE_NAME:   (v1:spec.nodeName)
      CNI_MTU:               <set to the key 'veth_mtu' of config map 'calico-config'>  Optional: false
      SLEEP:                 false
    Mounts:
      /host/etc/cni/net.d from cni-net-dir (rw)
      /host/opt/cni/bin from cni-bin-dir (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from calico-node-token-42kcs (ro)
  flexvol-driver:
    Container ID:   docker://29197ac3b752ff23283ffe7e6c635967e9513b9ed219327db346c51837562e5f
    Image:          calico/pod2daemon-flexvol:v3.18.1
    Image ID:       docker://sha256:3994c62982cc018ea2fe7c092a4dfdb76cf01bdf83109055e2736b7ee94c0193
    Port:           <none>
    Host Port:      <none>
    State:          Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Thu, 08 Apr 2021 14:34:19 -0400
      Finished:     Thu, 08 Apr 2021 14:34:19 -0400
    Ready:          True
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /host/driver from flexvol-driver-host (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from calico-node-token-42kcs (ro)
Containers:
  calico-node:
    Container ID:   docker://5a9e97e88d7b5254d292f6b7e62a24d0eabc25fc798fd4800ee90523e6f641b1
    Image:          calico/node:v3.18.1
    Image ID:       docker://sha256:50b52cdadbcf0b250adc3151e8462cc794fc3d9a3a2db3d8f86ceadcec67882a
    Port:           <none>
    Host Port:      <none>
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Thu, 08 Apr 2021 14:35:47 -0400
      Finished:     Thu, 08 Apr 2021 14:35:47 -0400
    Ready:          False
    Restart Count:  21
    Requests:
      cpu:      250m
    Liveness:   exec [/bin/calico-node -felix-live -bird-live] delay=10s timeout=1s period=10s #success=1 #failure=6
    Readiness:  exec [/bin/calico-node -felix-ready -bird-ready] delay=0s timeout=1s period=10s #success=1 #failure=3
    Environment Variables from:
      kubernetes-services-endpoint  ConfigMap  Optional: true
    Environment:
      DATASTORE_TYPE:                     kubernetes
      WAIT_FOR_DATASTORE:                 true
      NODENAME:                            (v1:spec.nodeName)
      CALICO_NETWORKING_BACKEND:          <set to the key 'calico_backend' of config map 'calico-config'>  Optional: false
      CLUSTER_TYPE:                       k8s,bgp
      IP:                                 autodetect
      CALICO_IPV4POOL_IPIP:               Always
      CALICO_IPV4POOL_VXLAN:              Never
      FELIX_IPINIPMTU:                    <set to the key 'veth_mtu' of config map 'calico-config'>  Optional: false
      FELIX_VXLANMTU:                     <set to the key 'veth_mtu' of config map 'calico-config'>  Optional: false
      FELIX_WIREGUARDMTU:                 <set to the key 'veth_mtu' of config map 'calico-config'>  Optional: false
      CALICO_IPV4POOL_CIDR:               10.245.0.0/16
      CALICO_DISABLE_FILE_LOGGING:        true
      FELIX_DEFAULTENDPOINTTOHOSTACTION:  ACCEPT
      FELIX_IPV6SUPPORT:                  false
      FELIX_LOGSEVERITYSCREEN:            info
      FELIX_HEALTHENABLED:                true
    Mounts:
      /lib/modules from lib-modules (ro)
      /run/xtables.lock from xtables-lock (rw)
      /sys/fs/ from sysfs (rw)
      /var/lib/calico from var-lib-calico (rw)
      /var/log/calico/cni from cni-log-dir (ro)
      /var/run/calico from var-run-calico (rw)
      /var/run/nodeagent from policysync (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from calico-node-token-42kcs (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  lib-modules:
    Type:          HostPath (bare host directory volume)
    Path:          /lib/modules
    HostPathType:
  var-run-calico:
    Type:          HostPath (bare host directory volume)
    Path:          /var/run/calico
    HostPathType:
  var-lib-calico:
    Type:          HostPath (bare host directory volume)
    Path:          /var/lib/calico
    HostPathType:
  xtables-lock:
    Type:          HostPath (bare host directory volume)
    Path:          /run/xtables.lock
    HostPathType:  FileOrCreate
  sysfs:
    Type:          HostPath (bare host directory volume)
    Path:          /sys/fs/
    HostPathType:  DirectoryOrCreate
  cni-bin-dir:
    Type:          HostPath (bare host directory volume)
    Path:          /opt/cni/bin
    HostPathType:
  cni-net-dir:
    Type:          HostPath (bare host directory volume)
    Path:          /etc/cni/net.d
    HostPathType:
  cni-log-dir:
    Type:          HostPath (bare host directory volume)
    Path:          /var/log/calico/cni
    HostPathType:
  host-local-net-dir:
    Type:          HostPath (bare host directory volume)
    Path:          /var/lib/cni/networks
    HostPathType:
  policysync:
    Type:          HostPath (bare host directory volume)
    Path:          /var/run/nodeagent
    HostPathType:  DirectoryOrCreate
  flexvol-driver-host:
    Type:          HostPath (bare host directory volume)
    Path:          /usr/libexec/kubernetes/kubelet-plugins/volume/exec/nodeagent~uds
    HostPathType:  DirectoryOrCreate
  calico-node-token-42kcs:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  calico-node-token-42kcs
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  kubernetes.io/os=linux
Tolerations:     :NoSchedule
                 :NoExecute
                 CriticalAddonsOnly
                 node.kubernetes.io/disk-pressure:NoSchedule
                 node.kubernetes.io/memory-pressure:NoSchedule
                 node.kubernetes.io/network-unavailable:NoSchedule
                 node.kubernetes.io/not-ready:NoExecute
                 node.kubernetes.io/pid-pressure:NoSchedule
                 node.kubernetes.io/unreachable:NoExecute
                 node.kubernetes.io/unschedulable:NoSchedule
Events:
  Type     Reason          Age                      From                                Message
  ----     ------          ----                     ----                                -------
  Warning  BackOff         4h29m (x289 over 5h29m)  kubelet, calico-master.localdomain  Back-off restarting failed container
  Normal   SandboxChanged  2m21s                    kubelet, calico-master.localdomain  Pod sandbox changed, it will be killed and re-created.
  Normal   Pulled          2m20s                    kubelet, calico-master.localdomain  Container image "calico/cni:v3.18.1" already present on machine
  Normal   Created         2m20s                    kubelet, calico-master.localdomain  Created container upgrade-ipam
  Normal   Started         2m18s                    kubelet, calico-master.localdomain  Started container upgrade-ipam
  Normal   Pulled          2m18s                    kubelet, calico-master.localdomain  Container image "calico/cni:v3.18.1" already present on machine
  Normal   Created         2m18s                    kubelet, calico-master.localdomain  Created container install-cni
  Normal   Started         2m17s                    kubelet, calico-master.localdomain  Started container install-cni
  Normal   Pulled          2m16s                    kubelet, calico-master.localdomain  Container image "calico/pod2daemon-flexvol:v3.18.1" already present on machine
  Normal   Created         2m16s                    kubelet, calico-master.localdomain  Created container flexvol-driver
  Normal   Started         2m16s                    kubelet, calico-master.localdomain  Started container flexvol-driver
  Normal   Pulled          94s (x3 over 2m15s)      kubelet, calico-master.localdomain  Container image "calico/node:v3.18.1" already present on machine
  Normal   Created         94s (x3 over 2m14s)      kubelet, calico-master.localdomain  Created container calico-node
  Normal   Started         93s (x3 over 2m14s)      kubelet, calico-master.localdomain  Started container calico-node
  Warning  BackOff         87s (x6 over 2m10s)      kubelet, calico-master.localdomain  Back-off restarting failed container

**Comment by caseydavenport** [comment]
> 2021-04-08 13:10:33.065 [ERROR][8] startup/startup.go 1052: Failed to create default IPv4 IP pool: 10.245.0.0/16 error=Get "https://10.96.0.1:443/apis/crd.projectcalico.org/v1/felixconfigurations/default": stream error: stream ID 25; INTERNAL_ERROR

and 

> 2021-04-08 13:10:32.955 [INFO][8] startup/customresource.go 102: Error getting resource Key=GlobalFelixConfig(name=CalicoVersion) Name="calicoversion" Resource="GlobalFelixConfigs" error=the server could not find the requested resource (get GlobalFelixConfigs.crd.projectcalico.org calicoversion)


Suggest something might be wrong with your API server. I'd suggest checking the k8s API server logs to see if it's healthy.

**Comment by dinucatona** [comment]
Hi Casey, 
Thanks for looking into this. Here's the status of my api server:

NAMESPACE     NAME                                                READY   STATUS              RESTARTS   AGE
kube-system   kube-apiserver-calico-master.localdomain            1/1     Running             2          18h

[master@calico-master ~]$ kubectl describe pod -n kube-system kube-apiserver-calico-master.localdomain
Name:                 kube-apiserver-calico-master.localdomain
Namespace:            kube-system
Priority:             2000000000
Priority Class Name:  system-cluster-critical
Node:                 calico-master.localdomain/10.0.0.66
Start Time:           Thu, 08 Apr 2021 14:34:02 -0400
Labels:               component=kube-apiserver
                      tier=control-plane
Annotations:          kubernetes.io/config.hash: 189ceef04ba8b00d5c16dff2bd78a1da
                      kubernetes.io/config.mirror: 189ceef04ba8b00d5c16dff2bd78a1da
                      kubernetes.io/config.seen: 2021-04-07T20:23:43.743981-04:00
                      kubernetes.io/config.source: file
Status:               Running
IP:                   10.0.0.66
IPs:
  IP:  10.0.0.66
Containers:
  kube-apiserver:
    Container ID:  docker://77c3447814488d4a5c31ff0acf0c01c4d96a613fc24863ce41380eac9ff68855
    Image:         k8s.gcr.io/kube-apiserver:v1.16.0
    Image ID:      docker://sha256:b305571ca60a5a7818bda47da122683d75e8a1907475681ee8b1efbd06bff12e
    Port:          <none>
    Host Port:     <none>
    Command:
      kube-apiserver
      --advertise-address=10.0.0.66
      --allow-privileged=true
      --authorization-mode=Node,RBAC
      --client-ca-file=/etc/kubernetes/pki/ca.crt
      --enable-admission-plugins=NodeRestriction
      --enable-bootstrap-token-auth=true
      --etcd-cafile=/etc/kubernetes/pki/etcd/ca.crt
      --etcd-certfile=/etc/kubernetes/pki/apiserver-etcd-client.crt
      --etcd-keyfile=/etc/kubernetes/pki/apiserver-etcd-client.key
      --etcd-servers=https://127.0.0.1:2379
      --insecure-port=0
      --kubelet-client-certificate=/etc/kubernetes/pki/apiserver-kubelet-client.crt
      --kubelet-client-key=/etc/kubernetes/pki/apiserver-kubelet-client.key
      --kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname
      --proxy-client-cert-file=/etc/kubernetes/pki/front-proxy-client.crt
      --proxy-client-key-file=/etc/kubernetes/pki/front-proxy-client.key
      --requestheader-allowed-names=front-proxy-client
      --requestheader-client-ca-file=/etc/kubernetes/pki/front-proxy-ca.crt
      --requestheader-extra-headers-prefix=X-Remote-Extra-
      --requestheader-group-headers=X-Remote-Group
      --requestheader-username-headers=X-Remote-User
      --secure-port=6443
      --service-account-key-file=/etc/kubernetes/pki/sa.pub
      --service-cluster-ip-range=10.96.0.0/12
      --tls-cert-file=/etc/kubernetes/pki/apiserver.crt
      --tls-private-key-file=/etc/kubernetes/pki/apiserver.key
    State:          Running
      Started:      Thu, 08 Apr 2021 14:34:04 -0400
    Last State:     Terminated
      Reason:       Error
      Exit Code:    255
      Started:      Thu, 08 Apr 2021 09:05:28 -0400
      Finished:     Thu, 08 Apr 2021 14:33:37 -0400
    Ready:          True
    Restart Count:  2
    Requests:
      cpu:        250m
    Liveness:     http-get https://10.0.0.66:6443/healthz delay=15s timeout=15s period=10s #success=1 #failure=8
    Environment:  <none>
    Mounts:
      /etc/kubernetes/pki from k8s-certs (ro)
      /etc/pki from etc-pki (ro)
      /etc/ssl/certs from ca-certs (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             True
  ContainersReady   True
  PodScheduled      True
Volumes:
  ca-certs:
    Type:          HostPath (bare host directory volume)
    Path:          /etc/ssl/certs
    HostPathType:  DirectoryOrCreate
  etc-pki:
    Type:          HostPath (bare host directory volume)
    Path:          /etc/pki
    HostPathType:  DirectoryOrCreate
  k8s-certs:
    Type:          HostPath (bare host directory volume)
    Path:          /etc/kubernetes/pki
    HostPathType:  DirectoryOrCreate
QoS Class:         Burstable
Node-Selectors:    <none>
Tolerations:       :NoExecute
Events:
  Type    Reason          Age   From                                Message
  ----    ------          ----  ----                                -------
  Normal  SandboxChanged  44m   kubelet, calico-master.localdomain  Pod sandbox changed, it will be killed and re-created.
  Normal  Pulled          44m   kubelet, calico-master.localdomain  Container image "k8s.gcr.io/kube-apiserver:v1.16.0" already present on machine
  Normal  Created         44m   kubelet, calico-master.localdomain  Created container kube-apiserver
  Normal  Started         44m   kubelet, calico-master.localdomain  Started container kube-apiserver

Here's the log from that server. The only error i see is at 19:20:59.879397. It keeps repeating thruout the log at more or less the same interval
[master@calico-master ~]$ kubectl logs -n kube-system kube-apiserver-calico-master.localdomain | more
net/http.HandlerFunc.ServeHTTP(0xc006f115e0, 0x7b04720, 0xc005a53ce8, 0xc013512b00)
        /usr/local/go/src/net/http/server.go:1995 +0x44
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server.(*APIServerHandler).ServeHTTP(0xc006f21380, 0x7b04720, 0xc005a53ce8, 0xc013512b00)
        /workspace/anago-v1.16.0-rc.2.1+2bd9643cee5b3b/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/handler.go:189 +0x51
net/http.serverHandler.ServeHTTP(0xc00a7cc270, 0x7b04720, 0xc005a53ce8, 0xc013512b00)
        /usr/local/go/src/net/http/server.go:2774 +0xa8
net/http.initNPNRequest.ServeHTTP(0xc00af3b500, 0xc00a7cc270, 0x7b04720, 0xc005a53ce8, 0xc013512b00)
        /usr/local/go/src/net/http/server.go:3323 +0x8d
k8s.io/kubernetes/vendor/golang.org/x/net/http2.(*serverConn).runHandler(0xc005dfbb00, 0xc005a53ce8, 0xc013512b00, 0xc00258d9c0)
        /workspace/anago-v1.16.0-rc.2.1+2bd9643cee5b3b/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/golang.org/x/net/http2/server.go:2125 +0x89
created by k8s.io/kubernetes/vendor/golang.org/x/net/http2.(*serverConn).processHeaders
        /workspace/anago-v1.16.0-rc.2.1+2bd9643cee5b3b/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/golang.org/x/net/http2/server.go:1859 +0x4f4
E0408 19:20:59.879283       1 wrap.go:39] apiserver panic'd on GET /apis/crd.projectcalico.org/v1/hostendpoints?limit=500&resourceVersion=0
I0408 19:20:59.879397       1 log.go:172] http2: panic serving 10.0.0.66:50280: runtime error: invalid memory address or nil pointer dereference
goroutine 137987 [running]:
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.(*timeoutHandler).ServeHTTP.func1.1(0xc00da3c7e0)
        /workspace/anago-v1.16.0-rc.2.1+2bd9643cee5b3b/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/timeout.go:107 +0x107
panic(0x3ce83e0, 0xaa83850)
        /usr/local/go/src/runtime/panic.go:522 +0x1b5
k8s.io/kubernetes/vendor/k8s.io/apiextensions-apiserver/pkg/apiserver/schema.(*Structural).Unfold.func1(0xc0136dd4d0, 0xc013769090)
        /workspace/anago-v1.16.0-rc.2.1+2bd9643cee5b3b/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiextensions-apiserver/pkg/apiserver/schema/unfold.go:38 +0xa2
k8s.io/kubernetes/vendor/k8s.io/apiextensions-apiserver/pkg/apiserver/schema.(*Visitor).visitStructural(0xc013769770, 0xc0136dd4d0, 0xc013769208)
        /workspace/anago-v1.16.0-rc.2.1+2bd9643cee5b3b/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiextensions-apiserver/pkg/apiserver/schema/visitor.go:41 +0x48e
k8s.io/kubernetes/vendor/k8s.io/apiextensions-apiserver/pkg/apiserver/schema.(*Visitor).visitStructural(0xc013769770, 0xc013771e60, 0xc013769378)
        /workspace/anago-v1.16.0-rc.2.1+2bd9643cee5b3b/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiextensions-apiserver/pkg/apiserver/schema/visitor.go:48 +0x173
k8s.io/kubernetes/vendor/k8s.io/apiextensions-apiserver/pkg/apiserver/schema.(*Visitor).visitStructural(0xc013769770, 0xc0136dd3b0, 0xc013769400)
        /workspace/anago-v1.16.0-rc.2.1+2bd9643cee5b3b/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiextensions-apiserver/pkg/apiserver/schema/visitor.go:45 +0x478
k8s.io/kubernetes/vendor/k8s.io/apiextensions-apiserver/pkg/apiserver/schema.(*Visitor).visitStructural(0xc013769770, 0xc0136dd170, 0xc013769600)
        /workspace/anago-v1.16.0-rc.2.1+2bd9643cee5b3b/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiextensions-apiserver/pkg/apiserver/schema/visitor.go:48 +0x173

**Comment by caseydavenport** [comment]
> I0408 19:20:59.879397 1 log.go:172] http2: panic serving 10.0.0.66:50280: runtime error: invalid memory address or nil pointer dereference

Yeah, this seems to be the cause if I had to guess. The API server seems to be hitting a panic and that's going to cause a lot of downstream issues. 

Is this with a vanilla k8s apiserver build? Or are there any modifications?

**Comment by fasaxc** [comment]
Just a heads up that Calico v3.18 expects to be run on k8s v1.18+.  We don't know of any concrete reason why it shouldn't work on v1.16 but we only test a Calico release with the most recent 2-3 releases of k8s.

**Comment by dinucatona** [comment]
It's just a regular build. v1.16 tho.
I try see if i can upgrade to 1.18 and maybe that will fix the problem. Cuz i don't really see any glaring issues with the stup itself.
Thanks guys.

**Comment by dinucatona** [comment]
Resolved
Upgraded to Kubernetes v1.21 and stuff's working fine.
Thanks for all the input.
Issue can be closed.

**Comment by dinucatona** [comment]
Resolved
Upgraded to Kubernetes v1.21 and stuff's working fine.
Thanks for all the input.
Issue can be closed.
