### ISSUE TITLE
IP_AUTODETECTION_METHOD setting is unsuccessful

### ISSUE THREAD

**Issue by sunboy1** [projectcalico/calico#4521]
![image](https://user-images.githubusercontent.com/25715404/114338895-9acd4980-9b86-11eb-8107-5ebe256850b4.png)
![image](https://user-images.githubusercontent.com/25715404/114338929-ad478300-9b86-11eb-91f6-29ef5aa59ba8.png)

**Comment by lmm** [comment]
@sunboy1 is this an operator managed cluster? For operator installs of Calico, to change the IP auto detection config you'll need to update the Installation custom resource: https://docs.projectcalico.org/reference/installation/api#operator.tigera.io/v1.NodeAddressAutodetection

**Comment by sunboy1** [comment]
thanks
