### ISSUE TITLE
Failed to auto-detect host MTU

### ISSUE THREAD

**Issue by thanhlong9x** [projectcalico/calico#4522]
logs in my calico-node pod show this **warning**
![WhatsApp Image 2021-04-12 at 18 33 57](https://user-images.githubusercontent.com/29721257/114408081-47351d00-9bd3-11eb-8780-a3abc3539305.jpeg). 

I don't find anything about mtuIfacePattern and I want know how to fix this ?
Thank you.

## Your Environment
* Calico version 3.18.1
* Orchestrator version (e.g. kubernetes, mesos, rkt): 1.17
* Operating System and version: redhat7

**Comment by caseydavenport** [comment]
Looks like a documentation bug! I'll update the docs to include this field.

This is the option that it's referring to: https://github.com/projectcalico/libcalico-go/blob/master/lib/apis/v3/felixconfig.go#L370-L374

Specifically, it's a FelixConfiguration field.

**Comment by caseydavenport** [comment]
Mind if I ask what your host interfaces look like?

**Comment by caseydavenport** [comment]
Docs PR here: https://github.com/projectcalico/calico/pull/4546
