### ISSUE TITLE
calico node is only "ready" when the IP of the node is added to the firewalld on the three master control-planes nodes

### ISSUE THREAD

**Issue by ImadNaily** [projectcalico/calico#4524]
Unless i open port 6443 on all three master nodes from the calico node host ip, the calico node will not go to ready state.
calico node docker container reports the below error:
startup/startup.go 156: failed to query kubeadm's config map error=Get "https://10.95.0.1:443/api/v1/namespaces/kube-system/configmaps/kubeadm-config?timeout=2s": dial tcp 10.95.0.1:443: connect: no route to host

## Expected Behavior
In a three k8s master node configuration the calico node should use the api servers' load balancer IP. Although if i understand right, it should only talk to the load balanced etcd. It should not go directly to any of the master nodes and certainly, I should not have to explicitly open port 6443 on all three master nodes from the worker node IP  where calico node is running

Not sure if it is a bug or a misconfiguration in kubelet/kube-proxy.
Without the port open on all three master nodes, only calico node is not "Ready".
Kubelet no errors.
Kube-proxy no problem and no errors.

No suggestions
## Possible Solution

the fix is to open the firewall port 6443 on all master nodes for that calico node host IP.
once all three master nodes allow traffic from the node ip on port 6443, calico node goes to "Ready" state and all is well.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

Vanilla installation with container images and etcd calico.yaml.
* Calico version
* calico node v3.17.1
* Orchestrator version (e.g. kubernetes, mesos, rkt):
* v1.20.1
* Operating System and version:
* RHEL 7
* Link to your project (optional):

**Comment by lwr20** [comment]
calico-node (when running in kubernetes datastore mode) absolutely requires to be able to access the k8s apiserver.  As do kubelet and kube-proxy which also run on the node in host-network.  How are they accessing the k8s apiserver in your cluster? 

The flow should be that calico-node accesses the k8s-apiserver via its service IP (10.95.0.1 in this case).  Kube-proxy will have set up iptables NAT rules to translate that into the node IPs (or the LB if that's what you configured).  Perhaps you need to check kube-proxy config?

If the LB does SNAT on the traffic, then sure, you would only configure firewalld with the IP of the LB.  But that's not true of all types of LB.

**Comment by ImadNaily** [comment]
My cluster is using etcd and is load balanced. Calico is configure to use that.
I think you are right in that the kube-proxy is not configured to use my LB apiserver and in fact when I open the ports i am actually opening the ports for kube-proxy and not calico.
But I looked at the configuration of kube-proxy and I can not seem to find the LB apiserver anywhere. So now i suspect that kube-proxy is not using the LB address. Not sure what else to do. Thanks for your help.

**Comment by lwr20** [comment]
Its definitely possible to configure kube-proxy to use an LB as the k8s-apiserver address, because Openshift and kops do exactly this.  

If I had to guess, I'd say there was a config flag that can pass the value to kube-proxy, or maybe a configmap or config file?

I realise this isn't much help.

**Comment by caseydavenport** [comment]
calico/node needs to communicate with the API server, as does the Calico CNI plugin, so I think this is working as expected.
