### ISSUE TITLE
kernel soft lockup

### ISSUE THREAD

**Issue by seaurching** [projectcalico/calico#4526]
kernel:NMI watchdog: BUG: soft lockup - CPU#3 stuck for 40s! [calico-node:53787]
## Expected Behavior
No kernel bug

## Current Behavior

Long time running, the master kernel show tips
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Calico version
- 3.18.1
* Orchestrator version (e.g. kubernetes, mesos, rkt):
- kubernetes 1.20.5
* Operating System and version:
- centos 7.9
* Link to your project (optional):

**Comment by song-jiang** [comment]
@qiqisa Calico uses standard Linux user-space utilities  e.g. `iptables` `ipsets` to interact with kernel. If a soft lockup is raised, most likely it is due to some incompatibility issue with the kernel or the utilities involved.

**Comment by song-jiang** [comment]
Close due to lack of activity. Please reopen if needed.
