### ISSUE TITLE
TCP connections are unstable & flaky. Getting java.net.SocketException: Connection reset intermittenly

### ISSUE THREAD

**Issue by vishumindtree** [projectcalico/calico#4540]
##< BUG DESCRIPTION >

All services: java.net.SocketException: Connection reset .

-- > Getting too many RST's on established TCP connections .  This is highly intermittent .
conntrack is making a new connection as established but it was not created as part of TCP connection establishment, no SYN packet was seen. This causes packets on a valid connection to be send to a non existent TCP connection on port 1024. 

## Expected Behavior
TCP connection should not be abruptly dropped.

## Current Behavior
TCP connections are getting dropped intermittently

## Possible Solution
Packets which are marked invalid should get dropped 

## Steps to Reproduce (for bugs)

Execute the below script & observe the CONNTRACK entry on node & also collect the TCP dump
1.#!/bin/bash

i=0

while [ true ]
do
  echo Count: $i
  time curl  --header 'Accept: application/json' 'h{HTTPURL}/v3/resource/test/35'  -H "Authorization: Basic XXXXXXXXXXXXXXXXXXXXXXXXXX" > /dev/null
  i=$((i+1))
done
2.
3.
4.

## Your Environment

* Calico version  -->>    Image:      docker.io/calico/node:v3.15.1
* Orchestrator version - Kubernetes v1.16.3
* Operating System and version: Ubuntu 18.04.5 LTS (GNU/Linux 4.15.0-130-generic x86_64)
* Link to your project (optional):

**Comment by lwr20** [comment]
FWIW, we don't see this in our overnight test runs.  

Can you check MTU (or upgrade to a recent Calico version with automatic MTU configuration)?

**Comment by vishumindtree** [comment]
Hi Matt ,

Sure ! will give a try & revert back .

Is this happening because of packets being marked as Invalid & this creating IP address spoofing scenario & hence connections being dropped ?

**Comment by lwr20** [comment]
We generally recommend the current release of Calico - at the moment that's v3.19.1.  That should choose the MTU correctly itself.

**Comment by caseydavenport** [comment]
@vishumindtree any update on this one?

**Comment by xiaods** [comment]
you can run conntrack -L to track TCP connection.

**Comment by vishumindtree** [comment]
This issue is not reproducible on calico_version: v3.17.4.
