### ISSUE TITLE
[kubernetes 1.21] [calico 3.18] pods cannot route traffic to external services

### ISSUE THREAD

**Issue by jayaddison** [projectcalico/calico#4542]
Hi folks,

I'm operating a Kubernetes cluster that has until recently been using Calico 3.14.  On consumer-facing request paths, the cluster mostly handles incoming user traffic while occassionally making requests out to internet-based services.

After upgrading to Kubernetes 1.21, an [issue report](https://github.com/openculinary/infrastructure/issues/30) has led to discovery of external connectivity issues from pods in the cluster.

After the issue report, I upgraded the cluster to Calico 3.18 in order to catch up-to-date with the latest fixes and support focus.  Despite the Calico 3.18 upgrade, the issue persists.

Documentation for the Kubernetes cluster configuration is [available here](https://github.com/openculinary/infrastructure/tree/4e2499ab9fcdc0e05781fdcb97a977800522f75e#configure-kubernetes-cluster).

Only a single Calico IPPool is in place; it has `natOutgoing` enabled (true) and has a CIDR configuration that covers the pod network CIDR.

The host is an Ubuntu Linux 20.04 machine running kernel 5.4.0-72-generic (x86_64).

I've previously reported some notes about this under a probably-unrelated issue at https://github.com/projectcalico/calico/issues/3467#issuecomment-820767111.

The only routing table entry that appears on the pods is a link-local `169.x` default gateway route, and I understand that this is expected as a way to route traffic to the Calico router.

## Expected Behavior
All four types of IP traffic below should be routable:

- :heavy_check_mark: Pod-to-internet traffic
- :heavy_check_mark: Pod-to-kubernetes-DNS-service traffic
- :heavy_check_mark: Pod-to-kubernetes-service traffic
- :heavy_check_mark: Pod-to-pod traffic

## Current Behavior

Two of the four types of traffic are routable:

- :heavy_multiplication_x: Pod-to-internet traffic (tested by using `wget github.com`)
- :heavy_check_mark: Pod-to-kubernetes-DNS-service traffic (tested by using `nslookup github.com 10.96.0.10` -- IP from `/etc/resolv.conf`)
- :heavy_check_mark: Pod-to-kubernetes-service traffic (tested by using `wget x-service` -- service name from `kubectl describe svc`)
- :heavy_check_mark: Pod-to-pod traffic (tested by using `wget 192.168.75.x` -- pod IP from `kubectl describe pods`)

## Possible Solution
My guess is that this somehow relates to CIDR allocations, iptables entries, or connection tracking; with the allocation of the DNS service on a 10.x subnet as potentially somehow related.

Despite the strikethrough commentary in https://github.com/projectcalico/calico/issues/3467#issuecomment-821885318, I also do still think there may be something going on related to `WorkloadEndpointUpdate` events.

## Steps to Reproduce (for bugs)
1. Configure a Kubernetes cluster following the [instructions here](https://github.com/openculinary/infrastructure/tree/4e2499ab9fcdc0e05781fdcb97a977800522f75e#configure-kubernetes-cluster)
2. Create a deployment in the service ([`make build && make deploy` of a `blog` service](https://github.com/openculinary/blog/blob/73132534160a8858bd5cc4aa7ea469af19c6435f/Makefile) is a quickly-deployable example I've been using)
3. Attempt outbound connectivity from a pod within the deployment (`kubectl exec -it deployments/blog-deployment -- sh` ...)

## Context
One of the workloads within the cluster makes outbound SMTP requests in order to send feedback emails; it is this functionality that is currently broken, and this is what led to the discovery of the connectivity issues.

## Your Environment
* Calico version 3.18
* Orchestrator version (e.g. kubernetes, mesos, rkt): `kubectl` and `kubeadm` managing a CRI-O Kubernetes cluster
* Operating System and version: Ubuntu 20.04

Edit 1: fixup for the working-and-not-working traffic types (intended: DNS and external traffic routing are _not_ working)
Edit 2: update to indicate that routing for DNS _is_ working

**Comment by jayaddison** [comment]
Sorry, I made a mistake in the list of working/not-working traffic types.  Trust me to make the pretty emojified traffic summary first, spend ages on the writeup, and then not notice that the (important) summary itself was incorrect.

**Comment by caseydavenport** [comment]
oh, hey @jayaddison! Fancy seeing you here :) 

A few thoughts based on the symptoms you're describing.

> Pod-to-kubernetes-DNS-service traffic (tested by using wget 10.96.0.10 -- IP from /etc/resolv.conf)

I suspect that connectivity to your kubernetes DNS is in fact working, but that the command you're using to test it isn't correct. I wouldn't expect a `wget` to work here. `wget` is going to send an HTTP request to the server, whereas DNS is its own protocol (typically operating over UDP, but sometimes TCP). 

Try this (assuming you have a pod with `nslookup` installed). It will do a DNS lookup against the specified server. 

```
nslookup github.com 10.96.0.10
```

But like I said, I suspect that connectivity to the DNS pod is working because your next bullet says that accessing a service by it's **name** is working, and that requires that DNS lookups succeed.

That doesn't necessarily discount DNS being a problem, but it will discount "pod's being able to reach the DNS server" as the cause.

> Pod-to-internet traffic (tested by using wget github.com)

So, at this point we either are reaching the DNS server, but it's not able to find an entry for domains outside of the cluster, or it's returning an address and actual connectivity to the outside world is broken. Hopefully the `nslookup` command above will clarify which scenario we're dealing with - if it returns an address, then it's likely a network connectivity problem. If it doesn't, then it's likely a DNS infrastrucutre thing.

**Comment by jayaddison** [comment]
> oh, hey @jayaddison! Fancy seeing you here :)

:wave: hey @caseydavenport :)  Thanks for the help!

> Try this (assuming you have a pod with `nslookup` installed). It will do a DNS lookup against the specified server.
> 
> ```
> nslookup github.com 10.96.0.10
> ```

Yep, a few of the pods have `nslookup` available.  Here's the output from one of those:

```
/ # nslookup github.com 10.96.0.10
Server:		10.96.0.10
Address:	10.96.0.10:53

Non-authoritative answer:
Name:	github.com
Address: 140.82.121.3

Non-authoritative answer:
*** Can't find github.com: No answer
```

So you're right, DNS resolution is working - that's good to know.

> But like I said, I suspect that connectivity to the DNS pod is working because your next bullet says that accessing a service by it's **name** is working, and that requires that DNS lookups succeed.

Also makes sense, thanks - I had wondered if there was some kind of magic involved in the Kubernetes service name resolution that allowed those to succeed - glad to know that that's _not_ the case!

> > Pod-to-internet traffic (tested by using wget github.com)
> 
> My money is on it being a network / packet routing thing rather than DNS, but I could definitely be wrong!

From the findings, it looks like you guessed correctly on this being a routing issue.  Do you have any recommendations on how I could help narrow down the cause?

> It's strange that this seems to have been triggered by a Kubernetes platform upgrade.

Agreed.  Unfortunately I only have two clusters available, and they vary in a few ways (kernel version, distribution, and Kubernetes platform version) - so I'm not completely certain that the platform upgrade was the cause.

The IP-dual-stack default in 1.21 seems significant, but it could be a red herring (and is certainly described -- and no doubt well tested -- as a non-breaking change).

**Comment by jayaddison** [comment]
Peculiar: external connectivity is now working.  The routing tables in the pods don't appear to have changed, and I haven't upgraded or modified any of the network configuration.

**Comment by jayaddison** [comment]
It's worth mentioning that this was a repeatable connectivity failure condition after resetting and reinitializing the cluster 5+ times, with one or two full system reboots for good measure, so it didn't seem like an intermittent or one-off 'stuck cluster' condition; and yet does appear to have subsided.

I'll put some logs aside and will hold this issue open for another few days to see if the problem re-occurs.  Also glad to take a look into any specific post-recovery items if you have ideas, @caseydavenport.

**Comment by jayaddison** [comment]
(actually, feel free to close this if that's the preferred process - I'm good either way; I just have a strange feeling that the root cause isn't yet resolved and may re-appear)

**Comment by caseydavenport** [comment]
Yeah, let's leave this open for a little bit longer. It does seem suspicious that it just "went away".

I wouldn't expect this to be a problem with the routing table within the pods - the network configuration within a pod is pretty unaware of where the traffic is ultimately going and what you've described sounds like business as usual in that area. 

Most likely this is something to do with your nodes, or something else in your network between the nodes and the internet. Where are you running this cluster, by the way?

**Comment by jayaddison** [comment]
@caseydavenport It's a single node cluster running on a self-hosted server in a home network (perhaps an unusual use case for y'all).  Ubuntu 20.04 x86_64, and all fairly vanilla configuration.

I'll likely try reinitializing the cluster over the weekend to see if the problem is reproducible in a fresh cluster.

**Comment by jayaddison** [comment]
This does appear reproducible following a fresh cluster re-initialization.

```
/ # nslookup github.com 10.96.0.10
Server:		10.96.0.10
Address:	10.96.0.10:53

;; connection timed out; no servers could be reached

/ #
```

My best guess currently is that route propagation is somehow extensively delayed.

**Comment by jayaddison** [comment]
Sorry; to adjust my previous message: perhaps not _route_ propagation, but _some_ kind of network configuration propagation.

**Comment by caseydavenport** [comment]
Very curious that it's a single-node cluster (meaning the source pod and the DNS pod are likely co-located).

One other thing to try would be to do an nslookup using the exact IP address of the pod (not the Service IP) to see if there is a difference between accessing the DNS server via the Service or not.

If it can be accessed via pod IP but not via service IP, then that points to something wrong with kube-proxy programming service rules.

Other thing might be if some other agent like NetworkManager or something is trying to take control over the interfaces created by Calico. Given all the pods are on the same node, there's not a ton of network convergence that needs to happen for pods to talk to each other (i.e., no BGP or route sharing across nodes, etc). But, something might be fighting with Calico's local programming.

**Comment by jayaddison** [comment]
> One other thing to try would be to do an nslookup using the exact IP address of the coredns pod (not the Service IP) to see if there is a difference between accessing the DNS server via the Service or not.

My naive way to do this was to `kubectl -n kube-system get pods`, and then `kubectl -n kube-system describe pods/<pod-id>` for one of the (two) CoreDNS pods, and the copy the IP address from the output of that.  Here's what I get as a result of passing that to `nslookup`:

```
/ # nslookup github.com 192.168.75.9
Server:		192.168.75.9
Address:	192.168.75.9:53

;; connection timed out; no servers could be reached

/ #
```

> Other thing might be if some other agent like NetworkManager or something is trying to take control over the interfaces created by Calico. Given all the pods are on the same node, there's not a ton of network convergence that needs to happen for pods to talk to each other (i.e., no BGP or route sharing across nodes, etc). But, something might be fighting with Calico's local programming.

`NetworkManager` is running, yep - so that is plausible.

`journalctl -eu NetworkManager` does show some log messages relating to `cali*` network interfaces, but initially I don't see any indication that it is competing or modifying the configuration of those devices.

**Comment by caseydavenport** [comment]
@jayaddison sorry for the delay!

NetworkManager sounds like a potential culprit... we have some steps you can take to configure it to stand down: https://docs.projectcalico.org/maintenance/troubleshoot/troubleshooting#configure-networkmanager

Essentially:

Create the following configuration file at /etc/NetworkManager/conf.d/calico.conf to prevent NetworkManager from interfering with the interfaces:

```
[keyfile]
unmanaged-devices=interface-name:cali*;interface-name:tunl*;interface-name:vxlan.calico
```

Might be worth a shot if you're still seeing this.

**Comment by jayaddison** [comment]
Thanks @caseydavenport - that's good documentation.  Applying the guidance led me to investigate the situation again, and -- surprise, surprise -- I think we can consider this issue a case of local configuration error.

It looks like DNS requests from the pods are being dropped when `coredns` attempts to forward them to the (host) network's DNS server at `192.168.1.1`.  The following appears in the `coredns` pod logs:

```
$ kubectl logs -n kube-system pods/<coredns-pod-id>
...
[ERROR] plugin/errors: 2 github.com. AAAA: read udp 192.168.x.x:37343->192.168.1.1:53: i/o timeout
[ERROR] plugin/errors: 2 github.com. A: read udp 192.168.x.x:35901->192.168.1.1:53: i/o timeout
```

So I think the next step is that I should figure out why traffic isn't round-tripping to the DNS server, and I expect that it will be due to configuration issues on the DNS host.

Thank you very much again for your time helping to investigate this!  Hope I can return the favour in future :)

**Comment by jayaddison** [comment]
For the record:

- Updating the pod CIDR IP ranges for the cluster seems to have resolved the issue (https://github.com/openculinary/infrastructure/commit/7eea0a20e0f8a5bbb5804856d8de36efccd01792)
- #2962 reads like a closely-related previous issue report - in particular the `coredns` pod logs appear very similar
