### ISSUE TITLE
v1.6 kubeadm calico.yaml asks for non-existent version of calico/ctl

### ISSUE THREAD

**Issue by lwr20** [projectcalico/calico#455]
http://docs.projectcalico.org/v1.6/getting-started/kubernetes/installation/hosted/kubeadm/ asks for `calico/ctl:v0.23.1` but this version does not exist on Dockerhub. https://hub.docker.com/r/calico/ctl/tags/

Reported by `@pcm` in #kubeadm on the Kubernetes slack.

**Comment by lwr20** [comment]
Not clear to me if the fix is to create the missing version in Dockerhub or change the `calico.yaml` file.

**Comment by pmichali** [comment]
There is a link on that page for the manifest and it calls out v0.23.1 for both node and ctl. The former has that tag, latter does not (has v0.23.0, which seems to work).

**Comment by caseydavenport** [comment]
Good spot.

@gunjan5 cut the v1.6.1 release, so I've assigned to him.  I think the fix is just to push the `calico/ctl:v0.23.1` image

**Comment by caseydavenport** [comment]
As a workaround, v0.23.0 will work just as well.

**Comment by pmichali** [comment]
Great, I'm proceeding with v0.23.0 for now. Want to try out IPv6 with kubeadm setup.

**Comment by gunjan5** [comment]
@pmichali the image should be pushed to dockerhub now

**Comment by pmichali** [comment]
Thanks!
