### ISSUE TITLE
can not access node port service after create and delete hostendpoint for particular node .

### ISSUE THREAD

**Issue by ShawnBian** [projectcalico/calico#4556]
## Expected Behavior
it should access the nodePort service successfully via this particular node , Since we have already deleted all the host endpoint and we don't define any deny policy for this host endpoint  

## Current Behavior

we have a service here named experiment1 and it is NodePort type which means we can access it via nodeip:nodeport
[root@master1 phase2]# kubectl get svc
NAME          TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)        AGE
experiment1   NodePort    10.96.242.195   <none>        80:31861/TCP   50m
kubernetes    ClusterIP   10.96.0.1       <none>        443/TCP        93d

when I just try to calicoctl apply -f host-endpoint-for-node1.yaml and calicoctl delete -f host-endpoint-for-node1.yaml
then I can not access nodePort Service through this specific node( it should be node1 here, the rest of the other node just work normally), please see the below:

[root@master1 phase2]# curl --connect-timeout 5 node1:31861
curl: (28) Connection timed out after 5001 milliseconds
[root@master1 phase2]# curl --connect-timeout 5 node2:31861
nginx index page version 4 | <a href="hostname.html">Pod Name</a>
[root@master1 phase2]# ping node1
PING node1 (192.168.1.6) 56(84) bytes of data.
64 bytes from node1 (192.168.1.6): icmp_seq=1 ttl=64 time=0.788 ms
^C
--- node1 ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 0.788/0.788/0.788/0.000 ms
[root@master1 phase2]# ping node2
PING node2 (192.168.1.7) 56(84) bytes of data.
64 bytes from node2 (192.168.1.7): icmp_seq=1 ttl=64 time=1.02 ms
^C
--- node2 ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 1.022/1.022/1.022/0.000 ms
[root@master1 phase2]# calicoctl get hostendpoint
NAME   NODE   

## Possible Solution
Delete all the calico deployment and redeploy the calico. then everything should be work normally 

## Steps to Reproduce (for bugs)
1.[root@master1 phase2]# cat host-endpoint-for-node1.yaml 
- apiVersion: projectcalico.org/v3
  kind: HostEndpoint
  metadata:
    name: node1-eth0
    labels:
      host-endpoint: ingress
      role: k8s-worker 
  spec:
    interfaceName: eth0
    node: node1
[root@master1 phase2]# 
2. calico apply -f host-endpoint-for-node1.yaml 

## Context

NodePort can not be accessed via this particular node 

## Your Environment

* Calico version:3.17.1
* Orchestrator version (e.g. kubernetes, mesos, rkt):1.19.5
* Operating System and version: Centos 7.6.1810
* Link to your project (optional):

Really appreciated if someone who can point out the reason for the above issue. thanks

**Comment by lmm** [comment]
Can you share the host endpoint manifest you used? I believe we have failsafe rules that should prevent calico on the node with the host endpoint from being cut off from policy updates.

**Comment by bcreane** [comment]
hi @ShawnBian - I'll close for now due to inactivity, but please feel free to reopen if this is still an issue and you're able to provide the host endpoint manifest that @lmm requested. cheers
