### ISSUE TITLE
PyInstaller bundle instructions should set PATH

### ISSUE THREAD

**Issue by fasaxc** [projectcalico/calico#456]
The pyinstaller bundle instructions don't mention putting calico-felix and calico-iptables-plugin on the PATH, which is required.

http://docs.projectcalico.org/v2.0/getting-started/bare-metal/pyi-bare-metal-install

**Comment by robbrockbank** [comment]
The latest versions of Felix are shipped as binary or container images - not Pyinstaller based.  Not going to fix this for very old releases, so closing.
