### ISSUE TITLE
Calcicoctl does not print loadbalancerIPs with print bgpconfig

### ISSUE THREAD

**Issue by catblade** [projectcalico/calico#4564]
Calcicoctl does not print loadbalancerIPs with print bgpconfig

## Expected Behavior
Expect the serviceLoadBalancerIPs to be printed to screen when using calico get bgpconfiguration -o yaml

> DATASTORE_TYPE=kubernetes KUBECONFIG=~/.kube/config calicoctl get bgpconfiguration -o yaml
> apiVersion: projectcalico.org/v3
> items:
> - apiVersion: projectcalico.org/v3
>   kind: BGPConfiguration
>   metadata:
>     creationTimestamp: "2021-04-23T23:38:34Z"
>     name: default
>     resourceVersion: "3223"
>     uid: <redacted>
>   spec:
>     asNumber: redacted
>     logSeverityScreen: Info
>     nodeToNodeMeshEnabled: false
>     serviceClusterIPs:
>     - cidr: redacted
>     serviceExternalIPs:
>     - cidr: redacted
>     - cidr: redacted
>     serviceLoadBalancerIPs:
>     - cidr: redacted
>     - cidr: redacted

## Current Behavior
> DATASTORE_TYPE=kubernetes KUBECONFIG=~/.kube/config calicoctl get bgpconfiguration -o yaml
> apiVersion: projectcalico.org/v3
> items:
> - apiVersion: projectcalico.org/v3
>   kind: BGPConfiguration
>   metadata:
>     creationTimestamp: "2021-04-23T23:38:34Z"
>     name: default
>     resourceVersion: "3223"
>     uid: <redacted>
>   spec:
>     asNumber: redacted
>     logSeverityScreen: Info
>     nodeToNodeMeshEnabled: false
>     serviceClusterIPs:
>     - cidr: redacted
>     serviceExternalIPs:
>     - cidr: redacted
>     - cidr: redacted

## Steps to Reproduce (for bugs)

1.  Enter in, either through patch or apply, serviceLoadBalancerIPs
2.  Watch it work
3.  Watch the bgp work all the way up
4.  Try to print.  It tells you about everything but the serviceLoadBalancerIPs.

## Your Environment

* Calico version  3.18.1
* Orchestrator version (e.g. kubernetes, mesos, rkt): kubernetes 1.19.7
* Operating System and version:  Ubuntu 18.04

**Comment by caseydavenport** [comment]
@catblade could you share the output of running `calicoctl version`?

This sounds most likely like the `calicoctl` binary version you're using is out of date.

**Comment by catblade** [comment]
@caseydavenport  3.18.1

**Comment by Elegant996** [comment]
Sounds like you may not have applied the latest manifest which contains the updated CRD. While `calicoctl` will accept the values for the loadbalancerIP, you do not have a CRD applied which supports storing it.

Hope this helps!

**Comment by caseydavenport** [comment]
Yep, that sounds to be the likely culprit to me as well.
