### ISSUE TITLE
policy/v1beta1 PodDisruptionBudget Deprecated in v1.21+, unavailable in v1.25+

### ISSUE THREAD

**Issue by darkhonor** [projectcalico/calico#4570]
When applying the Calico manifest on a native Kubernetes cluster running v1.21.0, the following warning is shown:

Warning: policy/v1beta1 PodDisruptionBudget is deprecated in v1.21+, unavailable in v1.25+; use policy/v1 PodDisruptionBudget

The PodDisruptionBudget is created as expected for the time being.  This is a new warning as of v1.21 and is not displayed on earlier releases of Kubernetes.

## Expected Behavior
The poddisruptionbudget.policy/calico-kube-controllers should be created without a warning.  Ideal would be if you could check Kubernetes version before declaring the Policy.

## Current Behavior
On versions earlier than 1.21.0, no warning is generated.  Versions 1.21+ will generate a warning.  Versions 1.25+ will fail to create the object.

## Possible Solution
Update Installation documentation to have users using version 1.21+ edit calico.yaml line 3850 prior to applying the configuration.  They need to change:

apiVersion: policy/v1beta1

to:

apiVersion: policy/v1

## Steps to Reproduce (for bugs)
N/A.  The system is working as expected given the prevalence of Kubernetes deployments earlier than 1.21.

## Context
This will become an issue as more users upgrade to Kubernetes 1.21 and beyond.  It will need to be corrected once 1.25 is released.

## Your Environment
* Calico version: 3.17.4
* Orchestrator version (e.g. kubernetes, mesos, rkt): Kubernetes 1.21.0
* Operating System and version: Ubuntu 20.04
* Link to your project (optional): N/A

**Comment by caseydavenport** [comment]
@darkhonor yep, we'll definitely need to update those manfiests. 

It will still work fine to use the v1beta1 API for now. We'll want to switch the default in a release or so in order to make sure we're compatible with +/- a Kubernetes release.

**Comment by vzuevsky** [comment]
Any news on this yet?

**Comment by pacoxu** [comment]
See https://github.com/projectcalico/calico/pull/4926 

> We probably want to merge this PR when v1.23 comes out, since then we'll support v1.21, v1.22, and v1.23.

**Comment by Alceatraz** [comment]
Hello, And I'm super new of k8s. I follow the k8s install guide, And I choose calico as network implements, I see this warning

```
Warning: policy/v1beta1 PodSecurityPolicy is deprecated in v1.21+, unavailable in v1.25+
```

This make me little bit anxiety. Then I check my version, I'm using:
- debian 11
- k8s 1.22.3 c92036820499fedefec0f847e2054d824aea6cd1
- docker 20.10.10 b485636
- containerd.io 1.4.11
- calico's website install command "kubectl create -f https://docs.projectcalico.org/manifests/tigera-operator.yaml"

So I found this issue, Can I use this current version calico guide safely?

**Comment by caseydavenport** [comment]
@Alceatraz you can use the guide safely - we'll update to remove the PSP objects from Calico in v3.23, at which point the warning will go away.

**Comment by caseydavenport** [comment]
Update here - PodDisruptionBudgets have been updated to v1 for the upcoming v3.23 release. PodSecurityPolicy removal is still in progress.

**Comment by caseydavenport** [comment]
Made a new issue to track PSPs, PDB will be done in v3.23
