### ISSUE TITLE
Not possible to change the image names when using the helm chart

### ISSUE THREAD

**Issue by manuelbuil** [projectcalico/calico#4585]
When deploying Calico via Helm, we can define the image name for both tigeraOperator and calicoctl. However, this is not possible for the rest of images: calico/node, calico/kube-controller, calico/typha, calico/cni and calico/pod2daemon-flexvol.

This limitation could severely impact organizations that use private registries since they are forced to use the same image name, which is in general quite generic, e.g. node, cni or kube-controllers

## Expected Behavior

I'd expect to be able to change the image-name of all components in the same fashion as it can be done with tigeraOperator and calicoctl. For example:
```
docker.io/calico/node => my.local.registry/prod/rancher-images/calico-node
docker.io/calico/cni => my.local.registry/prod/rancher-images/calico-cni
```
## Current Behavior

Currently it is only possible to modify the registry and the path but not the name of the image

## Your Environment

* Calico version: 3.18
* Orchestrator version (e.g. kubernetes, mesos, rkt): kubernetes

**Comment by tmjd** [comment]
If you can create sub-paths like it looks like your path contains can't you do `my.local.registry/prod/rancher-images/calico/node`? The only way renaming the images would be necessary is if you can't have any 'orgs' or 'paths' in the registry.

This is really a feature request on the operator as the image names are controlled by the operator itself, that is why the operator and calicoctl images could be renamed.

**Comment by manuelbuil** [comment]
> If you can create sub-paths like it looks like your path contains can't you do `my.local.registry/prod/rancher-images/calico/node`? The only way renaming the images would be necessary is if you can't have any 'orgs' or 'paths' in the registry.

Unfortunately, 'orgs' or 'paths' are not always possible. Therefore, being able to change the name would help us a lot 

> 
> This is really a feature request on the operator as the image names are controlled by the operator itself, that is why the operator and calicoctl images could be renamed.

Could you point me to the correct repo where I should create this request please? I am not sure where the operator issues are handled. Thanks!

**Comment by tmjd** [comment]
> Could you point me to the correct repo where I should create this request please? I am not sure where the operator issues are handled. Thanks!

I think this is a fine place for this request. So I don't think there is a need to move it anywhere.

I was thinking about this a bit over the weekend and have a couple ideas. But first I want to give some context on why we would like to avoid generally allowing the specifying of individual image names. In general for the operator we've avoided exposing component settings and implementation details in the API, allowing individual name changes would be exposing those details and from your use case description I do not think it is necessary. Keeping implementation details out of the API also prevent needing to synchronize updates to configuration when upgrading from one version to the next.

My ideas:
1. The operator Installation API could provide a flag that when specified would change all image names from `<imagePath>/<imageName>` to `<imagePath>-<imageName>`.
2. The operator Installation API could provide a way to specify an imagePrefix which could be prepended to all image names? That would allow for ensuring that the image names in a registry that doesn't support orgs/paths could still have unique/specific image names.

I think both could satisfy the use case but we'd probably want to do some thinking to figure out if one would be better or if there are any better options.

**Comment by manuelbuil** [comment]
Thanks for the proposals. Option 2 seems perfect for our use case :)
