### ISSUE TITLE
Enhancement Request: Autoscale Tpyha PODs based on the no. of nodes in the cluster

### ISSUE THREAD

**Issue by khatrig** [projectcalico/calico#4589]
## Suggested Behavior
As no. of nodes scale in the cluster, calico should Identify and scale the no. of typha replicas automatically.

## Current Behavior
Calico suggests running 1 typha replica per 100 nodes in the cluster. Scaling the no. of nodes in the cluster also requires updating typha replicas manually. The alternative is to run high no. typha instances from the start which is not optimal

## Possible Solution
Typha can use a horizontal pod autoscaler for this. Based on the no. of nodes in the cluster, replicas are added.

**Comment by lwr20** [comment]
If you install using tigera-operator, it will take care of this for you.  
See https://docs.projectcalico.org/getting-started/kubernetes/quickstart

**Comment by khatrig** [comment]
> If you install using tigera-operator, it will take care of this for you.
> See https://docs.projectcalico.org/getting-started/kubernetes/quickstart
@lwr20 , I referred [tigera-operator](https://docs.projectcalico.org/manifests/tigera-operator.yaml) but I could not find a reference for typha autoscaling as per no. of nodes. Can you please help me understand how typha autoscaling is done?

Thanks.

**Comment by lwr20** [comment]
https://github.com/tigera/operator/blob/master/pkg/controller/installation/typha_autoscaler.go#L40-L54

**Comment by khatrig** [comment]
I installed calico as part of kubespray cluster setup which doesn't use tigera operator out of the box. 
Are there any plans to support typha autoscaling through calico manifests?

**Comment by lwr20** [comment]
Even if that happened in the Calico manifests, Kubespray has its own built-in Calico manifests (via templates).  e.g.:
https://github.com/kubernetes-sigs/kubespray/blob/master/roles/network_plugin/calico/templates/calico-typha.yml.j2

It sounds like what you actually want is for _Kubespray_ to include a Typha autoscaler?

**Comment by khatrig** [comment]
> Even if that happened in the Calico manifests, Kubespray has its own built-in Calico manifests (via templates). e.g.:
> https://github.com/kubernetes-sigs/kubespray/blob/master/roles/network_plugin/calico/templates/calico-typha.yml.j2
> 
> It sounds like what you actually want is for _Kubespray_ to include a Typha autoscaler?

This is correct. Thanks for the help.

Closing this request.
