### ISSUE TITLE
Feature/Tool Request: Convert K8S NetworkPolicy to Calico NetworkPolicy

### ISSUE THREAD

**Issue by DennisGlindhart** [projectcalico/calico#4594]
Ability/Way/Tool to convert from a "k8s" NetworkPolicy (networking.k8s.io/v1 ) to "Calico" NetworkPolicy (projectcalico.org/v3).

## Use case
Having an bunch existing NetworkPolicies in the standard k8s native format (existing manifests, other sources, packages, external parties etc.) and want to extend/patch it with Calico-only functionality - i.e. replace the "Drop" with "Log"-target/directive for debug purposes etc.

You can, of course, convert it manually to calico-networkpolicy if only rare/small number, but even then it is prone to human error, so for debugging purposes you can't be sure you converted correctly.

Assuming that k8s-NetworkPolicy is a subset of the calico-NetworkPolicy.

## Possible Solution
AFAIK Calico converts to a policy "common"/"normalized" form inside Felix before application. Would it be possible to export that - ideally directly to the Calico-NetworkPolicy format.

**Comment by Slaiyer** [comment]
Are resources defined via `networking.k8s.io/v1` a strict subset of what's possible with `projectcalico.org/v3`?

**Comment by DennisGlindhart** [comment]
> Are resources defined via `networking.k8s.io/v1` a strict subset of what's possible with `projectcalico.org/v3`?

To the best of my knowledge, yes.

**Comment by caseydavenport** [comment]
> Are resources defined via networking.k8s.io/v1 a strict subset of what's possible with projectcalico.org/v3?

Yep, they are.

There is already conversion done internally within Calico do do this conversion, so this is most likely just a matter of exposing the logic that already exists in some way.

Basically, this function: https://github.com/projectcalico/libcalico-go/blob/master/lib/backend/k8s/conversion/conversion.go#L247

**Comment by coutinhop** [comment]
@caseydavenport @DennisGlindhart So I'm starting to work on the design for this feature, and would love to have some feedback.

I'm thinking we should implement this in calicoctl (there currently is a `calicoctl convert` that converts from Calico v1 to v3 API versions). It could be a sub-subcommand of the convert subcommand, or something else entirely (suggestions?).

The MVP clearly is to have this conversion be from k8s json/yaml to calico json/yaml, similar to what the existing `calicoctl convert` functionality does. Would that be sufficient?

Ideally we could make the functionality deal directly with the datastore, removing the k8s policy and adding the converted calico policy, but I believe there are some details that need to be thought carefully. Is this something worth pursuing? (An example off the top of my head, we could pass the same arguments as to `kubectl get networkpolicy`, and convert all policies that are retrieved)

Please let me know your thoughts.

**Comment by caseydavenport** [comment]
I think we could build this in a composable way:

An MVP workflow might look like this:

```
kubectl get networkpolicies -o yaml > k8s-policies.yaml
calicoctl convert policies -f k8s-policies.yaml -o calico-policies.yaml 
kubectl create -f calico-policies.yaml
kubectl delete k8s-policies.yaml
```

Could potentially be neat to have something that sums that all up though by reading from the k8s API, converting, writing back a policy, and deleting the old one. But I can't imagine us writing that without first writing the tool described above.

**Comment by coutinhop** [comment]
Agreed, thanks @caseydavenport !

**Comment by caseydavenport** [comment]
@coutinhop one thing to be aware of for this is that the policy conversion logic in Calico uses a special prefix internally to ensure uniqueness of the k8s policies: 

> 	policyName := fmt.Sprintf(K8sNetworkPolicyNamePrefix + np.Name)

The tool you're writing will want to avoid putting the K8sNetworkPolicyNamePrefix into the resulting Calico policy. I believe we have validation against any Calico policy starting with that prefix.

**Comment by coutinhop** [comment]
I pushed https://github.com/projectcalico/calico/pull/5184 and https://github.com/projectcalico/calico/pull/5307 to master which extend `calicoctl convert` to support converting k8s policies into calico policies. It should go into calico v3.22.

So basically it would work like
```
kubectl get networkpolicies -o yaml > k8s-policies.yaml
calicoctl convert -f k8s-policies.yaml -o yaml > calico-policies.yaml
kubectl create -f calico-policies.yaml
kubectl delete k8s-policies.yaml
```

**Comment by DennisGlindhart** [comment]
@coutinhop Awesome - Thanks. Looking forward to try it :)

**Comment by coutinhop** [comment]
Both the above PRs merged (along with https://github.com/projectcalico/calico/pull/5333 with test improvements) into master
