### ISSUE TITLE
Calico + Kubernetes - Unable to reach external network IP/Network

### ISSUE THREAD

**Issue by codility99** [projectcalico/calico#4604]
Hi, 

I'm having an on premise kubernetes cluster with calico as CNI plugin. 
With natOutgoing set to true, 
- Pod-to-Pod ping is successful with no issue, 
- Pod can reach to internet
- container able to ping host(pod's host)

== IpPool configured ==
apiVersion: projectcalico.org/v3
items:
- apiVersion: projectcalico.org/v3
  kind: IPPool
  metadata:
    name: default-ipv4-ippool
  spec:
    blockSize: 26
    cidr: 10.1.0.0/16
    ipipMode: Always
    natOutgoing: true
    nodeSelector: all()
    vxlanMode: Never
kind: IPPoolList
metadata:

== Cluster CIRD ==
cluster-cidr=10.1.0.0/16

## Expected Behavior
Be able to reach to local host's network(outside cluster) => 10.1.2.55 (Host's network)

## Current Behavior
Unable to reach IP outside cluster with busybox ping

## Steps to Reproduce (for bugs)
1. Setup k8s cluster 
2. Install Calico plugin

## Your Environment
* Calico version v3.18.1
* Orchestrator version (e.g. kubernetes, mesos, rkt): k8s,bgp,kubeadm,kdd
* Operating System and version: Centos 7

**Comment by codility99** [comment]
Resolved, tks

**Comment by discostur** [comment]
@codility99 Problem was that the host network subnet range is within the cluster cidr / calico IPpool range, or?

```bash
cluster-cidr=10.1.0.0/16

10.1.2.55 (Host's network)
```

Regards,
Kilian
