### ISSUE TITLE
VPP dataplane progression to GA

### ISSUE THREAD

**Issue by caseydavenport** [projectcalico/calico#4610]
This is an umbrella issue for tracking progression of the VPP dataplane integration from tech-preview to GA. Checklists here are likely to evolve over time.

### General 

- [x] Operator integration (https://github.com/tigera/operator/pull/1415)
- [x] Include VPP dataplane in more CI suites (e.g., felix, calico/node, cni plugin)
- [x] Comprehensive code review from someone at Tigera
- [x] 2 release cycles for feedback (i.e., v3.21.0)

### Full platform / CNI support

- [x] EKS w/ Calico CNI
- [x] GCP
- [x] AWS

Out of scope:
- [x] EKS w/ Amazon CNI plugin (non-Calico CNI)
- [x] AKS w/ Azure CNI (non-Calico CNI)
- [x] GKE (addon-manager)
- [x] Azure (different NICs, hard for VPP to detect)

### Feature parity

- [x] HostEndpoint support
- [x] IPv6 / Dual-stack support
- [x] HostPort support

### Full platform / CNI support

- [x] OpenShift

### Testing

- [x] Scale / robustness testing (reboots, "chaos monkey", adding/deleting nodes, etc)
- [x] In-repo CI configured (e.g., Semaphore) https://github.com/projectcalico/vpp-dataplane/issues/292

### Release process

- [x] Decide on whether to fully integrate release processes (agreed to keep releases loosely coupled)
- [x] Release note generation tool includes VPP changes

### Additional items

- [x] Review [list of open VPP issues](https://github.com/projectcalico/calico/issues?q=is%3Aopen+is%3Aissue+label%3Aarea%2Fvpp)
 - [ ] All tests reliably green
 - [x] 1-2 release cycles in Beta for feedback + some verification of adoption during that time frame
 - [x] https://github.com/projectcalico/vpp-dataplane/issues/293
 - [ ] Documentation and troubleshooting
 
## Deferred to after GA

- [ ] Security / CVE review
- [ ] Untracked policy
- [ ] Pre-DNAT policy
- [ ] Run Felix FV subset (i.e., https://github.com/projectcalico/vpp-dataplane/issues/292) [this suite](https://github.com/projectcalico/calico/tree/master/felix/fv). Related: https://github.com/projectcalico/calico/pull/7424/

**Comment by fasaxc** [comment]
Issues that I think need to be fixed for the beta:

- https://github.com/projectcalico/vpp-dataplane/issues/294 Watcher API failures not handled

For the GA:

-  https://github.com/projectcalico/vpp-dataplane/issues/292 GA: Add automated testing?
- https://github.com/projectcalico/vpp-dataplane/issues/293 GA: Scale issue: directly watching Calico resources

**Comment by fasaxc** [comment]
Some missing features marked by TODOs in the code; presumably we just mark these as limitations?

- [ ] untracked policy
- [ ] pre-DNAT policy

**Comment by mmazurek-msft** [comment]
Hi @caseydavenport @fasaxc can you let me know whether VPP in Calico is going to be GA-ed with Calico v3.27.0 ? If so are there going to be some missing features compared to non-VPP deployment ?

**Comment by caseydavenport** [comment]
@mmazurek-msft yes the plan is for VPP data plane to be GA with v3.27.0. @mgleung is leading that release. 

The VPP data plane should support most features of other data planes, but we don't enforce strict feature parity here - that allows the different data planes to implement the feature sets that are most important to their particular use-cases. You should expect all major Calico networking and policy features to function, though.

**Comment by caseydavenport** [comment]
Done in v3.27.0!
