### ISSUE TITLE
projectcalico.org/IPv4Address annotation pointing to wrong node's IP CIDR

### ISSUE THREAD

**Issue by mattstam** [projectcalico/calico#4611]
On Kubernetes clusters > 1.20, `calico-node` fails because of this reason. When it occurs, the logs from this `calico-node` (running on node2 in example) looks like:
`startup/startup.go 411: Determined node name: node2`
`startup/startup.go 103: Starting node node2 with version v3.18.1`
`...`
`startup/reachaddr.go 57: Checking CIDR CIDR="10.240.0.4/16"`
`startup/reachaddr.go 59: Found matching interface CIDR CIDR="10.240.0.4/16"`
`startup/startup.go 808: Using autodetected IPv4 address 10.240.0.4/16, detected by connecting to 1.1.1.1`
`startup/startup.go 585: Node IPv4 changed, will check for conflicts`
**`startup/startup.go 1128: Calico node 'node1' is already using the IPv4 address 10.240.0.4.`** **<----- problem**
`startup/startup.go 347: Clearing out-of-date IPv4 address from this node IP="10.240.0.4/16"`
`startup/startup.go 1340: Terminating`

If you look at the annotations on node1, it will show `projectcalico.org/IPv4Address: 10.240.0.4/16`. However, `10.240.0.4` is **not** node1's IP, it is node2's IP. Thus node1's IP annotation is incorrect.

## Expected Behavior
All nodes to receive an annotation that matches up with the node's IP. 
Example: If a the internal IP of a node is `10.240.0.4`, than it's the annotation it receives from `calico-node` should be `projectcalico.org/IPv4Address: 10.240.0.4/16`.

## Current Behavior
A node will receive an annotation that does not match up with it's IP. 
Example: A node's internal IP may be `10.240.0.5`, but the annotation it receives from `calico-node` will be `projectcalico.org/IPv4Address: 10.240.0.4/16`.

## Steps to Reproduce (for bugs)
The issue seems to be intermediate with low reproducibility. However, all the times this has happened has been from clusters coming from an upgrade.

Particularly, clusters upgrading from a Kubernetes version below 1.20 to above 1.20, which introduces the `tigera-operator` for managing the installation of Calico.

## Context
It seems likely that this comes from a race during an upgrade, possibly similar to https://github.com/projectcalico/calico/issues/4525.

## Your Environment

* Calico version: v3.18.1 (from tigera-operator v1.15.1)
* Orchestrator version: Upgraded to 1.20.x from previous version
* Operating System and version: Ubuntu 18

**Comment by mattstam** [comment]
## Mitigation
If anyone comes across this problem in their cluster, here are the mitigation steps:

Identify which node has the incorrect annotation by doing `kubectl log <crashing calico-node pod> -n calico-system` and look for something like:
`startup/startup.go 1128: Calico node 'node1' is already using the IPv4 address <IP of different node>`

Check `node1` and see if it has annotation `projectcalico.org/IPv4Address` that *does not* match up with it's IP. If so, we must the annotation then restart the `calico-node` running on that node so it gets the receives the correct annotation:

1. `kubectl annotate node <node1> projectcalico.org/IPv4Address= --overwrite`
2. `kubectl delete pod <running calico-node on node1> -n calico-system`

At this point when the failed calico-node restarts it will come up correctly, but if your in a hurry you can manually restart it
3. `kubectl delete pod <failed calico-node> -n calico-system`

All the `projectcalico.org/IPv4Address` node annotations should now match up with their respective IPs, which will allow `calico-node`s to run.

**Comment by varleg** [comment]
Thank you for this. Really helpful as we experienced this exact issue upgrading kubernetes on aks from 1.19.3 to 1.20.5. Several of our production nodes had skewed labels and Ip's, while our dev environment was unaffected.

**Comment by lwr20** [comment]
Here's the Calico Users chat between @caseydavenport and @mattstam on this:
https://calicousers.slack.com/archives/CPTH1KS00/p1621288636253300
(in case there's any clues in there)

**Comment by mattstam** [comment]
@neiljerram This problem looks similar to https://github.com/projectcalico/calico/issues/4525 in that all of the times I have seen this it has been when doing a cluster upgrade (specifically going from k8s versions below 1.20 to above). 

node1's history will depend on how long the cluster had been sitting below 1.20 before upgrade, but I've been able to reproduce just creating a cluster at v1.19.9 and immediately upgrading to 1.20.5. so I don't think that matters here.

**Comment by lupusllc** [comment]
We experienced the same issue today upgrading AKS from 1.18.17, to 1.19.11 and directly to 1.20.7 once the cluster pods were all stable. The 1.19.11 calico pods didn't have this issue.

**Comment by DreamRivulet** [comment]
I think the issue may be  caused  by custom annotation copying during the upgrade .

**Comment by paulgmiller** [comment]
@mattstam  DreamRivulet has a verty good guess. We should probably not copy any annotations (or labels) from the calico namespace during upgrade. We already have an exception to not copy zone annotations so this should be an easy fix.

**Comment by lwr20** [comment]
@lmm I believe you were looking into this?

**Comment by lmm** [comment]
@lwr20 yes this issue is on my plate, I'm hoping to start looking at this today or tomorrow.

**Comment by paulgmiller** [comment]
@lmm  there is a good chance this is aks upgrade related. (I can speak for azure/aks). During an aks upgrade for legacy resaons we preserve node labels by copying them between nodes during the upgrade. We have a blacklist of labels/annotations that I'm goign to expand to containe everything under *.projectcalico.org. Should take another 2+ weeks to hit all regions though. If you've seen this on none AKS clusters then what I say probably doesn't apply.

**Comment by paulgmiller** [comment]
Fix is in but will take 2 weeks before it is in all AKS regions.

**Comment by lmm** [comment]
> If you've seen this on none AKS clusters then what I say probably doesn't apply.

@paulgmiller we haven't had reports of this issue elsewhere (there is a Rancher that is similar but has a different cause).

Thanks for the update!

**Comment by insankim** [comment]
@paulgmiller Could you confirm if fix is deployed in all AKS regions now?

**Comment by caseydavenport** [comment]
Sounds like this one is fixed upstream? Going to close for now but please shout if I should re-open.

**Comment by mattstam** [comment]
Yep this is fixed everywhere
