### ISSUE TITLE
calico don't add blackhole route.

### ISSUE THREAD

**Issue by yxxhero** [projectcalico/calico#4613]
## Expected Behavior

calico add blackhole.
## Current Behavior

calico don't add blackhole route.
## Possible Solution

How should I check the problem？ Thanks very much.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Calico version: v3.15.1
* Orchestrator version (e.g. kubernetes, mesos, rkt):
* Operating System and version:
* Link to your project (optional):

**Comment by MinvenX** [comment]
Hello, I also met this problem. Confd didn't add blackhole to bird config, so that bird advertise pod ip to tor. How to check this problem?
