### ISSUE TITLE
set worker node rpfilter off, But cali-PREROUTING drop my packets.

### ISSUE THREAD

**Issue by mbj0528** [projectcalico/calico#4630]
set linux kernel rp_filter=0. but, iptables raw table cali-PREROUTING drop my packets.

## Expected Behavior

set linux rp_filter 0 (all, default, cali interface) (sysctl -w ...)
then, cali-PREROUTING can accept packets

## Current Behavior

drop packets.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Context

Set worker node linux rp_filter 0 (all, default, cali interface).
my packets from cali interface(pod) : srcip A(unknown ip) dstip B(cluster ip = svc ip). 
B's endpoint pod is on the another worker node.
Anyway, my packets drop at iptables raw table cali-PREROUTING.
In this case, I added policy Based Routing from B to A. (ip rule add from B to A ...)
then can accept packet.

Question. Is this normal working ??

## Your Environment

* Calico version : v3.13.4
* Orchestrator version (e.g. kubernetes, mesos, rkt): kubernetes v1.17.6
* Operating System and version: RHEL 7.5
* Link to your project (optional):

**Comment by lwr20** [comment]
As a security measure, Calico does not allow pods to spoof IPs (i.e. send traffic from an IP that isn't one that belongs to the pod).  

What's your use case?  Perhaps there is a different solution?

**Comment by mbj0528** [comment]
@lwr20 Thank you for reply.
Right... my use case is VPN service on pod. 
So packet is comming from outside, decap in pod.
Then, src ip is shown as unkown private ip in worker node.
Is there any other way that accept packet ?

**Comment by lwr20** [comment]
Can you get your VPN pod to do NAT so that the packets appear to come from its own IP?

**Comment by mbj0528** [comment]
@lwr20 looks good idea.
it will be good solution.
thank you very much.

**Comment by lwr20** [comment]
I'm going to close this, since it sounds like you have what you need for now at least.
