### ISSUE TITLE
using calico network-- pods scheduled on different node cannot communicate with each other on kubernetes cluster 

### ISSUE THREAD

**Issue by irfansheikh777** [projectcalico/calico#4638]
I am facing  this issue troubleshooting long time issue is  I have create Kubernetes cluster with calico network in my on premises server the **pods scheduled  on  different node on this Kubernetes cluster not able to communicate to each other **  . please check below scenarios. 
There are two worker node **server9** and **server10**
Two PODS are created on server 9 and  one pod created on server 10 as u can see below.
pods wit same node are bale to communicate with each other but pod on another node is not able to communicate with each other.
Can you please   help me to resolve this   issue  as there is no communication between this pods which is issue for application level cluster

![image](https://user-images.githubusercontent.com/29003677/119668220-0a05b100-be48-11eb-91b2-05d60b8b56ac.png)
![image](https://user-images.githubusercontent.com/29003677/119668838-91ebbb00-be48-11eb-97c7-788b33263809.png)
![image](https://user-images.githubusercontent.com/29003677/119668922-a5972180-be48-11eb-9746-b374186c51ba.png)
**Ethernet interface of master:-**
![image](https://user-images.githubusercontent.com/29003677/119669009-b9db1e80-be48-11eb-8c40-4cace249e96a.png)

**Comment by irfansheikh777** [comment]
Hi @caseydavenport 
Thanks for reply.    please find the below  details  please helm me to resolve this 

Calico installatio process  followed below:-
**curl https://docs.projectcalico.org/manifests/calico.yaml -O
kubectl apply -f calico.yaml**

 Where is this cluster running (AWS? GCP? On-prem?)  **Its on premises servers**
 
How many nodes are in the cluster and what are their IP addresses   
![image](https://user-images.githubusercontent.com/29003677/120529828-e7e2d480-c3ed-11eb-9d89-896983eabe46.png)

===============

**Comment by caseydavenport** [comment]
@irfansheikh777 from that output, it seems like this to me:

> 172.18.0.1 is not an accessible IP of the remote node (e.g., a local bridge address and not the ensXXX device address). If this is the case, you can change the IP auto-detection method used by Calico to select the correct device.


I don't see 172.18.0.1 assigned to any node, so it looks like Calico is trying to peer with an address that doesn't belong to a node. Do you know what that address is?
