### ISSUE TITLE
Question: Does Calico OSS support calico networkpolicy logging, or is Calico Enterprise required?

### ISSUE THREAD

**Issue by QWERTY92009** [projectcalico/calico#4671]
It doesn't seem clear from the documentation whether networkpolicy logs (allow and deny) is supported by Calico OSS.

If it is, then it doesn't seem clear from the documentation how to configure it.

Thanks for your attention!

**Comment by lmm** [comment]
Hi @QWERTY92009 , if you're looking for basic iptables logging using the LOG action, here is an example of that: https://docs.projectcalico.org/archive/v3.19/security/calico-network-policy#generate-logs-for-specific-traffic

(For more detailed logging and other use cases there is our commercial offering.)

**Comment by QWERTY92009** [comment]
Thanks for your help, @lmm!
