### ISSUE TITLE
Simple calico gnp blocks traffic, when autoHEP is enabled

### ISSUE THREAD

**Issue by DavidDarville** [projectcalico/calico#4673]
Adding a simple Global Network Policy to a kubernetes cluster with calico CNI, ends up blocking access to the cluster.
The policy in question is this:

    apiVersion: projectcalico.org/v3
    kind: GlobalNetworkPolicy
    metadata:
      name: test
    spec:
      types:
      - Ingress
      ingress:
      - action: Log
        destination:
          nets:
          - 8.8.8.8/32

## Expected Behavior

I expect that no traffic should be blocked.

## Current Behavior

I am unable to connect to the apiserver, which makes the cluster quite unusable.
I have not tested what else is blocked...

## Possible Solution

I could disable autoHEP, but I need those host endpoints, to be able to create network policies relating to host networked pods.

## Steps to Reproduce (for bugs)

1. Enable AutoHEP `calicoctl patch kubecontrollersconfiguration default --patch='{"spec": {"controllers": {"node": {"hostEndpoint": {"autoCreate": "Enabled"}}}}}'`
2. Add the gnp using calicoctl
3. Wait a moment
4. All connections to the apiserver are blocked

## Context

I am currently adding network policies to all the pods in a cluster. And to test those policies, I want to log the traffic that is not allowed in the policies. And it makes more sense to add the logging rule as a global policy, instead of adding a policy to every namespace.

## Your Environment

* Calico version

    % calicoctl version
    Client Version:    3.19.1
    Git commit:        6fc0db96
    Cluster Version:   v3.19.1
    Cluster Type:      kops,bgp,kdd,k8s

* Operating System and version:
Ubuntu 20.04

**Comment by lmm** [comment]
Hi @DavidDarville , auto host endpoints protect all virtual interfaces on the host as well. When you applied the ingress policy, that would have blocked ingress to localhost (e.g.. 9099 for Calico, whatever port used by typha). You can get an idea of that in this tutorial: https://docs.projectcalico.org/security/kubernetes-nodes (please note that the `127.0.0.1/32` rule should really be `127.0.0.0/8`). I think the docs for auto host endpoints need to be improved.

**Comment by caseydavenport** [comment]
@lmm isn't the issue here that the single GNP selects _everything_ in the cluster (including all the HEPs and Pods) but doesn't allow any traffic?

Basically, that GNP enforces a cluster-wide default-deny, and so other policy rules will need to be written to allow the desired traffic.

**Comment by lmm** [comment]
I missed this issue, yes I missed that there isn't a selector in the rule so everything is selected.
