### ISSUE TITLE
Different Pod bandwidth using  calico kubernetes over aws network

### ISSUE THREAD

**Issue by nikhilagrawal577** [projectcalico/calico#4681]
The cluster environment is kubernetes over aws, and using iperf3 as bandwidth measurement tool. 

We are getting different bandwidth in multiple runs. 

Test 1:  iperf3 -N -i 30 -t 10 -f m -Z -P 8 -M 1440
> Client on 10.250.24.109:  Connecting to host iperf3-server, port 5201
Client on 10.250.24.109:  [  5] local 100.96.0.24 port 47830 connected to 100.70.174.177 port 5201
Client on 10.250.24.109:  [  7] local 100.96.0.24 port 47832 connected to 100.70.174.177 port 5201
Client on 10.250.24.109:  [  9] local 100.96.0.24 port 47834 connected to 100.70.174.177 port 5201
Client on 10.250.24.109:  [ 11] local 100.96.0.24 port 47836 connected to 100.70.174.177 port 5201
Client on 10.250.24.109:  [ 13] local 100.96.0.24 port 47838 connected to 100.70.174.177 port 5201
Client on 10.250.24.109:  [ 15] local 100.96.0.24 port 47840 connected to 100.70.174.177 port 5201
Client on 10.250.24.109:  [ 17] local 100.96.0.24 port 47842 connected to 100.70.174.177 port 5201
Client on 10.250.24.109:  [ 19] local 100.96.0.24 port 47844 connected to 100.70.174.177 port 5201
Client on 10.250.24.109:  [ ID] Interval           Transfer     Bitrate         Retr  Cwnd
Client on 10.250.24.109:  [  5]   0.00-10.00  sec   950 MBytes   797 Mbits/sec  1809    202 KBytes       
Client on 10.250.24.109:  [  7]   0.00-10.00  sec   916 MBytes   769 Mbits/sec  2067    175 KBytes       
Client on 10.250.24.109:  [  9]   0.00-10.00  sec   846 MBytes   710 Mbits/sec  1716    249 KBytes       
Client on 10.250.24.109:  [ 11]   0.00-10.00  sec   890 MBytes   747 Mbits/sec  1383    324 KBytes       
Client on 10.250.24.109:  [ 13]   0.00-10.00  sec  1.13 GBytes   970 Mbits/sec  2040    271 KBytes       
Client on 10.250.24.109:  [ 15]   0.00-10.00  sec  1021 MBytes   857 Mbits/sec  2672    332 KBytes       
Client on 10.250.24.109:  [ 17]   0.00-10.00  sec   914 MBytes   766 Mbits/sec  1606    191 KBytes       
Client on 10.250.24.109:  [ 19]   0.00-10.00  sec  1.00 GBytes   860 Mbits/sec  1756    316 KBytes       
Client on 10.250.24.109:  [SUM]   0.00-10.00  sec  7.54 GBytes  6475 Mbits/sec  15049             
Client on 10.250.24.109:  - - - - - - - - - - - - - - - - - - - - - - - - -
Client on 10.250.24.109:  [ ID] Interval           Transfer     Bitrate         Retr
Client on 10.250.24.109:  [  5]   0.00-10.00  sec   950 MBytes   797 Mbits/sec  1809             sender
Client on 10.250.24.109:  [  5]   0.00-10.00  sec   941 MBytes   790 Mbits/sec                  receiver
Client on 10.250.24.109:  [  7]   0.00-10.00  sec   916 MBytes   769 Mbits/sec  2067             sender
Client on 10.250.24.109:  [  7]   0.00-10.00  sec   907 MBytes   761 Mbits/sec                  receiver
Client on 10.250.24.109:  [  9]   0.00-10.00  sec   846 MBytes   710 Mbits/sec  1716             sender
Client on 10.250.24.109:  [  9]   0.00-10.00  sec   838 MBytes   703 Mbits/sec                  receiver
Client on 10.250.24.109:  [ 11]   0.00-10.00  sec   890 MBytes   747 Mbits/sec  1383             sender
Client on 10.250.24.109:  [ 11]   0.00-10.00  sec   882 MBytes   739 Mbits/sec                  receiver
Client on 10.250.24.109:  [ 13]   0.00-10.00  sec  1.13 GBytes   970 Mbits/sec  2040             sender
Client on 10.250.24.109:  [ 13]   0.00-10.00  sec  1.12 GBytes   963 Mbits/sec                  receiver
Client on 10.250.24.109:  [ 15]   0.00-10.00  sec  1021 MBytes   857 Mbits/sec  2672             sender
Client on 10.250.24.109:  [ 15]   0.00-10.00  sec  1013 MBytes   850 Mbits/sec                  receiver
Client on 10.250.24.109:  [ 17]   0.00-10.00  sec   914 MBytes   766 Mbits/sec  1606             sender
Client on 10.250.24.109:  [ 17]   0.00-10.00  sec   905 MBytes   759 Mbits/sec                  receiver
Client on 10.250.24.109:  [ 19]   0.00-10.00  sec  1.00 GBytes   860 Mbits/sec  1756             sender
Client on 10.250.24.109:  [ 19]   0.00-10.00  sec  1017 MBytes   853 Mbits/sec                  receiver
Client on 10.250.24.109:  [SUM]   0.00-10.00  sec  7.54 GBytes  6475 Mbits/sec  15049             sender
Client on 10.250.24.109:  [SUM]   0.00-10.00  sec  7.47 GBytes  6418 Mbits/sec                  receiver
Client on 10.250.24.109:  
Client on 10.250.24.109:  iperf Done.

Test 2  : iperf3 -N -i 30 -t 10 -f m -Z -P 8 -M 1440

>  iperf3 -N -i 30 -t 10 -f m -Z -P 8 -M 1440 : Executing for Parallel Connection : 8\n
Client on 10.250.29.116:  Connecting to host iperf3-server, port 5201
Client on 10.250.29.116:  [  5] local 100.96.0.22 port 54718 connected to 100.67.118.76 port 5201
Client on 10.250.29.116:  [  7] local 100.96.0.22 port 54720 connected to 100.67.118.76 port 5201
Client on 10.250.29.116:  [  9] local 100.96.0.22 port 54722 connected to 100.67.118.76 port 5201
Client on 10.250.29.116:  [ 11] local 100.96.0.22 port 54724 connected to 100.67.118.76 port 5201
Client on 10.250.29.116:  [ 13] local 100.96.0.22 port 54726 connected to 100.67.118.76 port 5201
Client on 10.250.29.116:  [ 15] local 100.96.0.22 port 54728 connected to 100.67.118.76 port 5201
Client on 10.250.29.116:  [ 17] local 100.96.0.22 port 54730 connected to 100.67.118.76 port 5201
Client on 10.250.29.116:  [ 19] local 100.96.0.22 port 54732 connected to 100.67.118.76 port 5201
Client on 10.250.29.116:  [ ID] Interval           Transfer     Bitrate         Retr  Cwnd
Client on 10.250.29.116:  [  5]   0.00-10.00  sec   705 MBytes   591 Mbits/sec  8342   77.3 KBytes       
Client on 10.250.29.116:  [  7]   0.00-10.00  sec   715 MBytes   600 Mbits/sec  8694   25.8 KBytes       
Client on 10.250.29.116:  [  9]   0.00-10.00  sec   704 MBytes   590 Mbits/sec  8565   47.4 KBytes       
Client on 10.250.29.116:  [ 11]   0.00-10.00  sec   744 MBytes   624 Mbits/sec  9191   6.78 KBytes       
Client on 10.250.29.116:  [ 13]   0.00-10.00  sec   630 MBytes   528 Mbits/sec  7532    122 KBytes       
Client on 10.250.29.116:  [ 15]   0.00-10.00  sec   690 MBytes   579 Mbits/sec  8657   42.0 KBytes       
Client on 10.250.29.116:  [ 17]   0.00-10.00  sec   636 MBytes   534 Mbits/sec  7270    146 KBytes       
Client on 10.250.29.116:  [ 19]   0.00-10.00  sec   651 MBytes   546 Mbits/sec  8156   39.3 KBytes       
Client on 10.250.29.116:  [SUM]   0.00-10.00  sec  5.35 GBytes  4593 Mbits/sec  66407             
Client on 10.250.29.116:  - - - - - - - - - - - - - - - - - - - - - - - - -
Client on 10.250.29.116:  [ ID] Interval           Transfer     Bitrate         Retr
Client on 10.250.29.116:  [  5]   0.00-10.00  sec   705 MBytes   591 Mbits/sec  8342             sender
Client on 10.250.29.116:  [  5]   0.00-10.00  sec   697 MBytes   584 Mbits/sec                  receiver
Client on 10.250.29.116:  [  7]   0.00-10.00  sec   715 MBytes   600 Mbits/sec  8694             sender
Client on 10.250.29.116:  [  7]   0.00-10.00  sec   706 MBytes   593 Mbits/sec                  receiver
Client on 10.250.29.116:  [  9]   0.00-10.00  sec   704 MBytes   590 Mbits/sec  8565             sender
Client on 10.250.29.116:  [  9]   0.00-10.00  sec   695 MBytes   583 Mbits/sec                  receiver
Client on 10.250.29.116:  [ 11]   0.00-10.00  sec   744 MBytes   624 Mbits/sec  9191             sender
Client on 10.250.29.116:  [ 11]   0.00-10.00  sec   736 MBytes   617 Mbits/sec                  receiver
Client on 10.250.29.116:  [ 13]   0.00-10.00  sec   630 MBytes   528 Mbits/sec  7532             sender
Client on 10.250.29.116:  [ 13]   0.00-10.00  sec   622 MBytes   522 Mbits/sec                  receiver
Client on 10.250.29.116:  [ 15]   0.00-10.00  sec   690 MBytes   579 Mbits/sec  8657             sender
Client on 10.250.29.116:  [ 15]   0.00-10.00  sec   682 MBytes   572 Mbits/sec                  receiver
Client on 10.250.29.116:  [ 17]   0.00-10.00  sec   636 MBytes   534 Mbits/sec  7270             sender
Client on 10.250.29.116:  [ 17]   0.00-10.00  sec   628 MBytes   527 Mbits/sec                  receiver
Client on 10.250.29.116:  [ 19]   0.00-10.00  sec   651 MBytes   546 Mbits/sec  8156             sender
Client on 10.250.29.116:  [ 19]   0.00-10.00  sec   642 MBytes   539 Mbits/sec                  receiver
Client on 10.250.29.116:  [SUM]   0.00-10.00  sec  5.35 GBytes  4593 Mbits/sec  66407             sender
Client on 10.250.29.116:  [SUM]   0.00-10.00  sec  5.28 GBytes  4536 Mbits/sec                  receiver
Client on 10.250.29.116:  
Client on 10.250.29.116:  iperf Done.

Here you can see multiple runs of performance test, both the cases we are getting different numbers where as setup and configuration remain the same.

Mss : 1440

Why do we see such a different in bandwidth in multiple runs ?

## Expected Behavior

Bandwidth should be similar across multiple runs.

## Current Behavior

Bandwidth are different runs in different days.

## Possible Solution

Any configuration by which we can get consistent network bandwidth. 

## Steps to Reproduce (for bugs)

1. Take ec2, m5.large VM over kubernetes
2. Use iperf3 tool
3. Use 8 parallel connection
4. Run the network performance test

## Context
Checking the network bandwidth we can get in different VMs in AWS and compare with host-host

## Your Environment

* Calico version : 3.18.2 
* kubernetes : 1.20.6
* Operating System and version:
* Link to your project (optional):

**Comment by nikhilagrawal577** [comment]
/kind/support

**Comment by song-jiang** [comment]
I see you've got different client on different ip with each run. Not sure if it is a Calico issue cause a client can running on a VM with heavier load.

**Comment by nikhilagrawal577** [comment]
@song-jiang  Yes. These are different client as it was ran from 2 different AWS cluster with same VM size and no workload.

When we are running in same AWS cluster, the numbers are consistent. But in another AWS cluster, we are getting different number.

**Comment by lmm** [comment]
It's hard to say what's going on here without more details. As for getting more consistent bandwidth, you could try setting limits as described here: https://docs.projectcalico.org/reference/cni-plugin/configuration#cni-network-configuration-lists

Maybe try removing the bandwidth plugin and see if that changes things?
