### ISSUE TITLE
Static IP allocated is not released at POD termination

### ISSUE THREAD

**Issue by PaulLemay** [projectcalico/calico#4694]
Using the following  annotation for a specific POD: "cni.projectcalico.org/ipAddrs": "[\"192.168.222.201\"]". 
. The address is allocated properly. 
. Terminate the pod
. Restart the POD, POD remains in creation mode waiting for an already allocated IP address.
. Must use calicoctl ipam release --ip=192.168.222.201 to release the IP so that the POD can start

## Expected Behavior
When the POD terminates, the static IP should automatically be released

## Current Behavior
When the POD terminates, the IP is not automatically be released. must be released manually.

## Steps to Reproduce (for bugs)
. allocate a static IP: "cni.projectcalico.org/ipAddrs": "[\"192.168.222.201\"]". 
. Start the POD, the address is allocated properly. 
. Terminate the pod
. Restart the POD, POD remains in creation mode waiting for an already allocated IP address.

## Context
Must implement a script to terminate a pod.

## Your Environment

* Calico version 3.19.0
* Orchestrator version (e.g. kubernetes, mesos, rkt): K8s Version 1.21
* Operating System and version: RHEL-8
* Kernel: Linux kube-master 4.18.0-240.22.1.rt7.77.el8_3.x86_64
* Link to your project (optional):

**Comment by lmm** [comment]
@PaulLemay can you check your pod termination/restart policies? Maybe the new pod is waiting for the assigned IP to be available, but the old pod is waiting for the new pod to be running and ready before terminating.

**Comment by caseydavenport** [comment]
Yeah, this sounds like the new pod is trying to start before tearing down the old.

You'll need to make sure that your rolling update policy allows the old pod to be torn down before launching the new, else you will deadlock waiting for the IP to be released, but k8s won't release the IP until the new pod starts.
