### ISSUE TITLE
Error querying BIRD: unable to connect to BIRDv4 socket: dial unix /var/run/bird/bird.ctl: connect: no such file or directory

### ISSUE THREAD

**Issue by hetian9288** [projectcalico/calico#4698]
## Current Behavior
1. DNS cannot be resolved
2. Nodeport can only be accessed on the running node

```
[root@k8s-node01 ~]#./calicoctl node status
Calico process is running.

IPv4 BGP status
+--------------+-------------------+-------+----------+-------------+
| PEER ADDRESS |     PEER TYPE     | STATE |  SINCE   |    INFO     |
+--------------+-------------------+-------+----------+-------------+
| 172.16.0.5   | node-to-node mesh | up    | 07:58:54 | Established |
+--------------+-------------------+-------+----------+-------------+

IPv6 BGP status
No IPv6 peers found.


[root@k8s-master ~]# ./calicoctl node status
Calico process is running.

IPv4 BGP status
+--------------+-------------------+-------+----------+-------------+
| PEER ADDRESS |     PEER TYPE     | STATE |  SINCE   |    INFO     |
+--------------+-------------------+-------+----------+-------------+
| 172.16.0.4   | node-to-node mesh | up    | 07:58:54 | Established |
+--------------+-------------------+-------+----------+-------------+

IPv6 BGP status
No IPv6 peers found.
```

### event log
After initialization
`Readiness probe failed: calico/node is not ready: BIRD is not ready: Error querying BIRD: unable to connect to BIRDv4 socket: dial unix /var/run/bird/bird.ctl: connect: no such file or directory`

After adding a new node
```Readiness probe failed: 2021-06-24 07:58:51.638 [INFO][2613] confd/health.go 180: Number of node(s) with BGP peering established = 0 calico/node is not ready: BIRD is not ready: BGP not established with 172.16.0.4```

### log
[log.txt](https://github.com/projectcalico/calico/files/6707589/log.txt)

## Solutions that have been tried
Use the installation method here：https://docs.projectcalico.org/archive/v3.18/getting-started/kubernetes/quickstart
`custom-resources.yaml` increase
```
nodeAddressAutodetectionV4:
      interface: eth.*
```

Turn off iptables  or clear iptables

## Your Environment
* Calico version v3.18.4
* kubernetes 1.21.2 + containerd v1.4.6:
* Centos 7.9: Linux k8s-master 5.12.13-1.el7.elrepo.x86_64 #1 SMP Tue Jun 22 16:26:54 EDT 2021 x86_64 x86_64 x86_64 GNU/Linux

**Comment by lmm** [comment]
Looking at the log it sounds like the calico-node eventually became ready and stayed that way. Did you upload the right log, or am I missing something?

**Comment by stepkh** [comment]
Have the same issue with k8s v1.21.3 and calico v3.19.1.
What's additional information will be useful to understand what's going on?

**Comment by caseydavenport** [comment]
Could you share the full logs from the `calico/node` pod that is hitting this error? Is the error persistent or does it happen once and then stop?

It would also be useful to see the output of the following:

- `ls /var/run/bird/` from within the calico/node pod
- `ls /etc/calico/confd/config` from within the calico/node pod

**Comment by stepkh** [comment]
`kubectl -n kube-system logs calico-node-5rjxr > log.txt` [log.txt](https://github.com/projectcalico/calico/files/7136675/log.txt)

`/var/log/calico/cni/` on node is empty.

I don't know why but calico create `/etc/cni/net.d/calico-kubeconfig` on nodes with default address for api server whereas I created cluster with control-plane-endpoint option where actual reachable ip is pointed out.

> Is the error persistent or does it happen once and then stop?

The error is persistent.

For `ls /var/run/bird/` I got

`ls: cannot access '/var/run/bird/': No such file or directory`

For this I believe it should be `/var/run/calico/` because on working node I have that catalog with bird socket and in daemonset also there is a mount of that catalog into the calico-node pod.

For `ls /etc/calico/confd/config` I got empty output.

The very bottom of `kubectl -n kube-system describe pod calico-node-5rjxr`
``` bash
Events:
  Type     Reason     Age                     From     Message
  ----     ------     ----                    ----     -------
  Warning  Unhealthy  93m (x863 over 28h)     kubelet  Liveness probe failed: calico/node is not ready: Felix is not live: Get "http://localhost:9099/liveness": dial tcp [::1]:9099: connect: connection refused
  Normal   Pulled     43m (x458 over 28h)     kubelet  Container image "docker.io/calico/node:v3.19.1" already present on machine
  Warning  Unhealthy  28m (x1875 over 28h)    kubelet  Liveness probe failed: calico/node is not ready: bird/confd is not live: exit status 1
  Warning  Unhealthy  13m (x3724 over 28h)    kubelet  Readiness probe failed: calico/node is not ready: BIRD is not ready: Error querying BIRD: unable to connect to BIRDv4 socket: dial unix /var/run/bird/bird.ctl: connect: no such file or directory
  Warning  BackOff    3m28s (x5673 over 28h)  kubelet  Back-off restarting failed container```

**Comment by stepkh** [comment]
It was my mistake in configuring sysctl option. Had invalid string in /etc/sysctl.d/99-sysctl.conf.
After removing it and rebooting server calico-node pod on this node started correctly.
