### ISSUE TITLE
Jun 22 15:26:02 master kubelet[2178]: 2021-06-22 15:26:02.734 [INFO][27113] dataplane_linux.go 420: Disabling IPv4 forwarding ContainerID

### ISSUE THREAD

**Issue by nks33** [projectcalico/calico#4703]
Hi Team,

I am getting the below msg when i am trying to bring up the pod. We are using helm and statefulset.yaml for enabling the ipv4 forwarding sysctl parameter during bring-up.

Jun 24 11:51:00 master kubelet[2178]: 2021-06-24 11:51:00.023 [INFO][9687] dataplane_linux.go 420: Disabling IPv4 forwarding ContainerID="befbe1a21feb8c3f9edc0eb9ff42fb32f11011c59452c508b43e8b1f95591949" Namespace="ricplt" Pod="mec-cuplane-service-0" WorkloadEndpoint="master-k8s-mec--cuplane--service--0-eth0"

## Expected Behavior
It is not supposed to come.

## Current Behavior
Currently it is showing in my environment. And it is sporadic .

## Possible Solution
I am trying to resolve this issue by putting the 10-bridge.conf  file in /etc/cni/net.d/  directory and re-deploy the calico.
And my  environment is single node cluster.

[root@master ~]# kubectl get nodes
NAME     STATUS   ROLES    AGE    VERSION
master   Ready    master   157d   v1.18.6
[root@master ~]#

cat old/10-bridge.conf
{
"cniversion": "0.3.1",
"name": "mynet",
"type": "bridge",
"bridge": "cbr0",
"isDefaultGateway": true,
"ipMasq": true,
"hairpinMode": true,
"ipam": {
"type": "host-local",
"ranges": [
[
{
"subnet": "172.16.1.0/24",
"gateway": "172.16.1.1"
}
]
]
}
}

Can you please help me to understand why i am seeing this behavior.

## Your Environment

* Calico version :-  docker.io/calico/cni:v3.17.1
* Orchestrator version (kubernetes):  K8 version 1.18 and docker version :-20.10.2
* Operating System and version:   Cent-OS 7.9

**Comment by mgleung** [comment]
Hi @nks33 , I think that the reason that you are hitting the error for disabling IP forwarding on the container interface is that you have not set the `allow_ip_forwarding` field in the container settings of the CNI config (see https://docs.projectcalico.org/reference/cni-plugin/configuration). That being said, I'm not exactly sure if that is your issue or if there are other issues you are trying to solve. It should make the error message go away, but I don't think it should affect the network connectivity to your pod and I would expect that to work regardless of the error message appearing. Is there something else that you are trying to solve by getting rid of this error message?

**Comment by nks33** [comment]
Hi mgleung,

Thanks for your reply i will try this.

Basically our use case is we need the sysctl ipv4 forwarding enable in the container.
net.ipv4.conf.all.forwarding = 1

But due to some config issue it is showing disable in the container. Then after checking the journalctl log i found the above error msg related to ipv4 disable.

I checked the calico code and it seems it is disabling it by writing the below file.

_d.logger.Info("****Disabling IPv4 forwarding****")
            if err := writeProcSys("/proc/sys/net/ipv4/ip_forward", "0"); err != nil {
                return err
            }
        }

I hope the above snippet of code is applying to the container which basically disabling it.

Can you please comment is my understanding is correct.

**Comment by nks33** [comment]
> Hi @nks33 , I think that the reason that you are hitting the error for disabling IP forwarding on the container interface is that you have not set the `allow_ip_forwarding` field in the container settings of the CNI config (see https://docs.projectcalico.org/reference/cni-plugin/configuration). That being said, I'm not exactly sure if that is your issue or if there are other issues you are trying to solve. It should make the error message go away, but I don't think it should affect the network connectivity to your pod and I would expect that to work regardless of the error message appearing. Is there something else that you are trying to solve by getting rid of this error message?

**Comment by mgleung** [comment]
Hi @nks33 ,

>  Basically our use case is we need the sysctl ipv4 forwarding enable in the container.
net.ipv4.conf.all.forwarding = 1

I am not sure on all the sysctl settings but I think that we're referring to the same setting (my google search turned up `net.ipv6.conf.all.forwarding` and `net.ipv4.ip_forward` but there's possibly a `net.ipv4.conf.all.forwarding` as well I didn't find). The code snippit you also found is what I would expect the `allow_ip_forwarding` field in the CNI config to disable. If you set `allow_ip_forwarding` does it still not work?

**Comment by nks33** [comment]
> Hi @nks33 ,
> 
> > Basically our use case is we need the sysctl ipv4 forwarding enable in the container.
> > net.ipv4.conf.all.forwarding = 1
> 
> I am not sure on all the sysctl settings but I think that we're referring to the same setting (my google search turned up `net.ipv6.conf.all.forwarding` and `net.ipv4.ip_forward` but there's possibly a `net.ipv4.conf.all.forwarding` as well I didn't find). I think that `net.ipv4.ip_forward` should be the same setting.
> 
> > I checked the calico code and it seems it is disabling it by writing the below file inside the container.
> > _d.logger.Info("Disabling IPv4 forwarding")
> > if err := writeProcSys("/proc/sys/net/ipv4/ip_forward", "0"); err != nil {
> > return err
> > }
> > }
> > I hope the above snippet of code is applying to the container which basically disabling it.
> 
> Your understanding is correct and that should be the code that we use to disable IP forwarding by unsetting the sysctl setting. The code snippit you found is also what I would expect the `allow_ip_forwarding` field in the CNI config to disable. If you set `allow_ip_forwarding` does it still not work?

**Comment by nks33** [comment]
Hi @mgleung 

After setting the **allow_ip_forwarding** this issue is resolved .
But i am seeing there is a dependency with the below file.

**/etc/cni/net.d/10-bridge.conf**

Content of bridge file can be seen in the above comment.

If this file is present in the host i don't need to set the above parameter.  i  am not able to understand this relation with ipv4 configuration. Can you please let me know the dependency.

**Comment by caseydavenport** [comment]
> /etc/cni/net.d/10-bridge.conf

You are likely using a non-Calico CNI plugin (the bridge plugin) when that file exists.
