### ISSUE TITLE
no tunnels on some nodes

### ISSUE THREAD

**Issue by Azhdar1990** [projectcalico/calico#4706]
Hello
I have a problem with calico deployment.
After deployment on some nodes there no tunnels created by calico and there is some errors in calico pods.
My Envieroment
There are 3 master nodes and 2 worker nodes
Each node has 2 network interface
interfaces name:
Master nodes (ens3,ens4) 
Worker nodes (ens5f0,ensf51)
ens3 and ens5f0 - public interfaces
ens4 and ens5f1 - privet interfaces
I deploying using private interfaces
i use:
IP_AUTODETECTION_METHOD: "interface=ens4,ens5f1" 
To tell  calico which interface use.
When deploy is finish i can't see tunnel interface on worker nodes.
On master nodes everithing is ok.
Errors on calico pods  witch is on worker nodes

 Warning  Unhealthy  41m (x74 over 66m)   kubelet  Readiness probe failed: calico/node is not ready: BIRD is not ready: Failed to stat() nodename file: stat /var/lib/calico/nodename: no such file or directory
  Warning  Unhealthy  11m (x107 over 66m)  kubelet  Liveness probe failed: calico/node is not ready: bird/confd is not live: exit status 1
  Warning  BackOff    83s (x210 over 60m)  kubelet  Back-off restarting failed container

cube-controller pod (running also on worker node) error

Warning  Unhealthy  10s (x7 over 57s)  kubelet            Readiness probe failed: Failed to read status file /status/status.json: unexpected end of JSON input

Nodes are in cloude

Please could you help how to deploy correctly
My cloude provider sayd that:
all nodes are connected via virtual switch
Master nodes are in one country but worker nodes in another country.
Private interface accessible via public interface

##Your Environment

Ubuntu 20.10
Kubernetes 21.0.1
Calico 3.18.3

**Comment by caseydavenport** [comment]
@Azhdar1990 how did you install Calico? 

> Warning Unhealthy 41m (x74 over 66m) kubelet Readiness probe failed: calico/node is not ready: BIRD is not ready: Failed to stat() nodename file: stat /var/lib/calico/nodename: no such file or directory

This error is confusing to me, because this file is written by calico/node prior to launching BIRD, so I would not expect this to happen. 

Could you provide the full calico/node logs on the failing node? Also, have you changed any volume mounts or other configuration on the calico/node daemonset?

**Comment by Azhdar1990** [comment]
I tryed to execute logs by typing
 kubectl -n kube-system logs pod/calico-node-nsz6p
but there is no log on the failing node.
May be there is another way to see them?
I deployed by using kubespray
I did not change any volume mounts.

**Comment by sshiba** [comment]
I am experiencing same issue when deploying calico on a private network.

**Comment by caseydavenport** [comment]
@sshiba could you share the logs from the calico-kube-controllers pod?

**Comment by sshiba** [comment]
@caseydavenport are you referring to `kubectl logs` command for the crashing `calico-kube-controllers` pod?

**Comment by caseydavenport** [comment]
@sshiba yep
