### ISSUE TITLE
About the tunnel about IPV6 address

### ISSUE THREAD

**Issue by mzzgaopeng** [projectcalico/calico#4709]
At present, calico does not support vxlan tunnel of ipv6, but ipv6 already supports vxlan tunnel. Is there any concern that calico does not support vxlan mode of ipv6 separately?

**Comment by caseydavenport** [comment]
Closing as a duplicate of https://github.com/projectcalico/libcalico-go/issues/996

We don't yet support IPv6 in our encap modes. This is a known enhancement.
