### ISSUE TITLE
calico-typha pods not being evicted

### ISSUE THREAD

**Issue by OwenPitts** [projectcalico/calico#4718]
[tigera-operator] calico-typha pods not being evicted when trying to update node AMI.

Expected Behavior
We are using v1.13.2 of tigera-operator in AWS EKS, when we are trying to update the ami to go from one minor version to the other the updates are occasionally timing out. Usually with smaller clusters 4 nodes or less. I notice there is a Pod Disruption Budget with 3 set as the MaxUnavalible. 

level | RequestResponse
-- | --
objectRef.apiVersion | v1
objectRef.name | calico-typha-5fd589f9fb-8q985
objectRef.namespace | calico-system
objectRef.resource | pods
objectRef.subresource | eviction
requestReceivedTimestamp | 2021-07-02T12:03:57.493130Z
requestURI | /api/v1/namespaces/calico-system/pods/calico-typha-5fd589f9fb-8q985/eviction?timeout=19s
responseObject.apiVersion | v1
responseObject.code | 429
responseObject.details.causes.0.message | The disruption budget calico-typha needs 3 healthy pods and has 3 currently
responseObject.details.causes.0.reason | DisruptionBudget
responseObject.kind | Status
responseObject.message | Cannot evict pod as it would violate the pod's disruption budget.
responseObject.reason | TooManyRequests
responseObject.status | Failure
responseStatus.code | 429
responseStatus.reason | TooManyRequests
responseStatus.status | Failure

Current Behavior
Nodes won't always be terminated due to the calico-typha  refusing to be evicted.

Possible Solution
Drop the MaxUnavalible if possible and how ? Or I am missing something and there is a solution for this elsewhere ?

We are using the yaml files from here - https://raw.githubusercontent.com/aws/amazon-vpc-cni-k8s/master/config/master/calico-operator.yaml and https://raw.githubusercontent.com/aws/amazon-vpc-cni-k8s/master/config/master/calico-crs.yaml

**Comment by tmjd** [comment]
The pod disruption budget for typha set by the operator is `maxUnavailable: 1`. So you should always be able to disrupt 1 typha pod if the other pods are healthy. I'm assuming this was with 4 nodes which with v1.13.2 deploys 4 typhas. Do you know if there was one typha that was unhealthy so the cluster was trying to keep the 3 healthy typhas?
There is also the possibility that the cluster was scaled down to 3 nodes but the operator had not yet scaled the typha deployment to 3 (scaling is checked every 2 minutes), so it could have already looked like there was 1 unhealthy typha.

**Comment by OwenPitts** [comment]
It happened when I was changing the AMI the nodes were running on, to update a minor version of EKS. It's a smaller test cluster so it did only have 3or4 nodes at the time, one per AZ and then an extra one scaled out for demand. I add before removal so it should of spun a new node up before eviciting and I would of expected Typha to start running there. 

Where do I control the maxUnavailable, increasing it to 2 or setting a % value would sort me out ? I tried defining my own PDB but it gets overwritten by the operator. Unless I remove its permission in RBAC, but thats a bit of a hack.

**Comment by tmjd** [comment]
We do not expose the ability to change that disruption budget. From what you've described the disruption budget of 1 should suffice, I think you should try to understand why it is not.
If you started with 3 and a new node is spun up before evicting, it is possible the operator sees the now 4th node and deploys a 4th typha but the disruption budget of 1 should allow one of the nodes to be destroyed, but that would mean that the operator would be waiting about 2 minutes to before checking for scaling again.
You could try upgrading the operator you're using, the typha scale has been reduced in that you will only have 3 typhas with 4 nodes and the scaling is updated every 10 seconds now.

**Comment by tmjd** [comment]
To upgrade you should be able to apply the latest operator manifest https://docs.projectcalico.org/manifests/tigera-operator.yaml

**Comment by OwenPitts** [comment]
Right OK, it doesn't always happen. Perhaps the 2 minute delay rather than 10 seconds occasionally causes the problem. I'll have a go at updating and see if it helps.

Thanks for the advice.
