### ISSUE TITLE
Document use of "endpoint labeling" in libnetwork-plugin

### ISSUE THREAD

**Issue by djosborne** [projectcalico/calico#472]
policy through endpoint labeling was merged in this PR: https://github.com/projectcalico/libnetwork-plugin/pull/103

We should provide info on how to use this.

**Comment by tmjd** [comment]
At a minimum the environment variables to configure node should be added to the master/reference/node/configuration section

**Comment by djosborne** [comment]
At a maximum, this may call for a rework of the [advanced policy guide](http://docs.projectcalico.org/v2.0/getting-started/docker/tutorials/advanced-policy), since we no longer have to hack profiles just to assign labels for policies.

**Comment by tmjd** [comment]
Closed via #506
