### ISSUE TITLE
ipset v7.1: Kernel and userspace incompatible

### ISSUE THREAD

**Issue by DennisGlindhart** [projectcalico/calico#4739]
Having a k8s cluster/node running for 60+ days without issues, suddenly the following logs entries begins to appear in a single calico-node

```

2021-07-13 09:49:37.513 [WARNING][4532] felix/ipsets.go 318: Failed to resync with dataplane error=exit status 1 family="inet6"
2021-07-13 09:49:37.513 [ERROR][4532] felix/ipsets.go 570: Bad return code from 'ipset list'. error=exit status 1 family="inet6" stderr="ipset v7.1: Kernel and userspace incompatible: settype hash:ip with revision 5 not supported by userspace.\n"
```

New pods being created on that node after it starts won't have any network connection (they get an IP, but not traffic going)

This has happened on multiple clusters (all running openSUSE Kubic).

Unable to repro without just waiting for potentially many days before it happens. Problem started suddenly in the middle of weekend where no one is messing around.

## Context

FELIX_IPTABLESBACKEND is set to Auto and log from calico-node doesn't indicate it being any other value.

To the best of my knowlegde there is no firewall-alterting applications running on the node except kube-proxy.

From the host:
```
$ ipset version
ipset v7.11, protocol version: 7
```
From calico-node (kubectl exec)
`ipset v7.1, protocol version: 7`

A reboot solves the problem (until next time).

Last log-entries from calico-node before the errors starts

```
[INFO][69] felix/summary.go 100: Summarising 15 dataplane reconciliation loops over 1m3.6s: avg=38ms longest=174ms (resync-filter-v4)
 [INFO][69] felix/watchercache.go 96: Watch channel closed by remote - recreate watcher ListRoot="/calico/resources/v3/projectcalico.org/workloadendpoints"

```

## Your Environment

* Calico 1.19
* Kubernetes 1.21
* Operating System and version: openSuSE Kubic (snapshot 20210430) 5.12.0-1-default #1 SMP Mon Apr 26 04:25:46 UTC 2021 (5d43652) x86_64 x86_64 x86_64 GNU/Linux

**Comment by lwr20** [comment]
As discussed in slack, once you've hit the problem, restarting calico-node is not sufficient to clear it.  The node itself needs to be rebooted.

**Comment by DennisGlindhart** [comment]
Running `ipset list` on affected node gives a lot of entires, but only 2 of them have Revision: 5 - The rest have Revision: 6

```
Name: tallow
Type: hash:ip
Revision: 5
Header: family inet hashsize 1024 maxelem 65536 timeout 3600 bucketsize 12 initval 0x3b8fb55f
Size in memory: 200
References: 1
Number of entries: 0
Members:

Name: tallow6
Type: hash:ip
Revision: 5
Header: family inet6 hashsize 1024 maxelem 65536 timeout 3600 bucketsize 12 initval 0x1bfd1b13
Size in memory: 288
References: 1
Number of entries: 0
Members:
```

If we can find the source for those

**Comment by DennisGlindhart** [comment]
Turns out that Kubic has a service/tool called tallow ( https://github.com/clearlinux/tallow ) running by default blocking ips based on scanning sshd etc. log-files. That must be it for sure.

I'll disable and reboot, then it should be gone for good. Thanks to @lwr20 for helping out.
