### ISSUE TITLE
Make required cloud settings more prominent

### ISSUE THREAD

**Issue by tmjd** [projectcalico/calico#476]
In the Mesos setup section it might help users if the caveats when running on cloud providers was more prominent.  Specifically http://docs.projectcalico.org/v2.0/getting-started/mesos/installation/dc-os/framework has a note to checkout the Calico AWS setup but that is nested 3 levels deep and only under DC/OS but applies to all Calico setups.
I think it would be good to go in each top level overview section where appropriate or in the Installation/Requirements section.

**Comment by caseydavenport** [comment]
I believe this has been fixed by @emanic's latest requirements refactoring.
