### ISSUE TITLE
Pods losing network connectivity when node systemd-networkd is restarted

### ISSUE THREAD

**Issue by choseh** [projectcalico/calico#4779]
Pods losing network connectivity when systemd-networkd is restarted on node

## Expected Behavior

pods should not lose connectivity

## Current Behavior

established connections lose connectivity

## Possible Solution

N/A

## Steps to Reproduce (for bugs)

1. kubectl run --rm -i -t busybox --image=debian:buster-slim --restart=Never -- bash
2. apt update && apt install netcat
3. establish connection to (for example) redis on aws nc redishostname 6379
4. type PING, receive +PONG from server
5. systemctl restart systemd-networkd on host node
6. type PING in debug container from 1., no +PONG is received

## Context

unattended upgrades or whatever updates requiring networkd restarts break connections of existing pods

networkctl states, that calico interfaces are unmanaged, so i don't think networkd fiddled with them

https://discuss.linuxcontainers.org/t/systemd-update-networkd-restart-breaks-routed-containers/9979 looks related

## Your Environment

* Calico version: 3.18.3
* Orchestrator version (e.g. kubernetes, mesos, rkt): k8s 1.20.8 with kOps on AWS
* Operating System and version: ubuntu 20.04 node images

**Comment by tarun-asthana** [comment]
Faced the same issue when Ubuntu updated their new security patch causing networkd to restart.

**Comment by caseydavenport** [comment]
> https://discuss.linuxcontainers.org/t/systemd-update-networkd-restart-breaks-routed-containers/9979 looks related

Yeah, that looks like it is probably what is going on here.

> If you use a static config and not DHCP then systemd/netplan doesn’t appear to wipe out the IP neighbour entries:

This seemed to be the recommended workaround for now - is that feasible for you?

I don't see that there's anything we can do on the Calico side - sounds like `networkd` is just removing some important programming that it shouldn't be.

**Comment by choseh** [comment]
Unfortunately using static configs in a pretty dynamic kops cluster that's constantly scaling up and down is not an option. We'll give another distro a shot and see if this changes anything. Thanks for the update though.

**Comment by lwr20** [comment]
> I don't see that there's anything we can do on the Calico side - sounds like networkd is just removing some important programming that it shouldn't be.

I think this means we should close this, since there's nothing we can do on the calico side.
