### ISSUE TITLE
Cut down build time

### ISSUE THREAD

**Issue by ozdanborne** [projectcalico/calico#479]
The long build times are a result of a few `for` loops which convert the sidebar yamls into the html sidebar.

This amounts to ~5 seconds per versioned directory. 

We could reasonably shave off 10 seconds if we stop rendering the sidebar dynamically for v1.5 and v1.6, which at this point, we're fairly confidant won't change much.

**Comment by djosborne** [comment]
Bumping to p1 since the release of Calico v2.1 has pushed build times up to >30 seconds :frowning_face:

**Comment by djosborne** [comment]
Sidebar isn't the reason for long build times. It's just the high number of files :(
