### ISSUE TITLE
Explain versioning in chart

### ISSUE THREAD

**Issue by danielburrell** [projectcalico/calico#4796]
Can you please explain how the versioning of your tigera operator charts works? Specifically for a release major.minor.revision, you seem to have a `-1` appended to the end. What is this number for? For scripts that want to automatically pull the latest version of the chart, do you promise there will only be one tigera chart artefact?

The docs say 
> The chart will be in the release artifacts and will have a name like: tigera-operator-v3.19.1-2.tgz

but don't explain what that number represents.

**Comment by stevehipwell** [comment]
Adding a `-` to a SemVer 2 version, as `chartVersion` is required to be in the Helm [docs](https://helm.sh/docs/topics/charts/#the-chartyaml-file), signifies that it's a pre-release and will cause tooling to treat it as such.

**Comment by danielburrell** [comment]
So do you ever publish upgraded chart versions to the same 3.20.0 release?

For example is the following sequence of events possible? :

```
Monday: 
- helm pull projectcalico/tigera-operator --version 3.20.0 
- this pulls in a file called tigera-operator-3.20.0-1.tar.gz

Tuesday:
- additional chart version published

Wednesday:
- helm pull projectcalico/tigera-operator --version 3.20.0 
- this pulls in a file called tigera-operator-3.20.0-2.tar.gz
```

When you say pre-release, you mean it's not considered 'stable'? 
If I look at 3.19.x I see a similar pattern though, a hyphen followed by a number. Can you point me to an example of a release that is not a pre-release?
