### ISSUE TITLE
Duplicate key (bpfExtToServiceConnmark) in CRD causes kustomize to fail

### ISSUE THREAD

**Issue by DanWard** [projectcalico/calico#4803]
## Expected Behavior
Running kustomize should work.

## Current Behavior
Running kustomize fails with error:
```
Error: map[string]interface {}(nil): yaml: unmarshal errors:
  line 61: mapping key "bpfExtToServiceConnmark" already defined at line 55
```

## Possible Solution
There's a duplicate key (`bpfExtToServiceConnmark`) in the CustomResourceDefinition properties.

## Steps to Reproduce (for bugs)
1. create file kustomization.yaml:
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://docs.projectcalico.org/v3.20/manifests/calico.yaml
```
2. `kustomize build system/network/calico/`

## Context
Kustomization is currently broken. The published YAML is likely invalid, and Kube could be swallowing the errors.

**Comment by mgleung** [comment]
Hi @DanWard , thanks for bringing this to our attention. This should be fixed with https://github.com/projectcalico/calico/pull/4805. I just checked the `v3.20` manifest and kustomize should work again for it as well. Let us know if you find any other issues.
