### ISSUE TITLE
Unable to create crd: create not allowed while custom resource definition is terminating

### ISSUE THREAD

**Issue by aasraoui** [projectcalico/calico#4809]
CRD creation is not allowed while custom resource definition is terminating
## Expected Behavior

kubectl create -f /tmp/tigera/custom-resources.yaml
should work after deleting crd
## Current Behavior

CRD creation is not allowed
## Steps to Reproduce (for bugs)

1.Delete crd
2.Try to create crd

Is there a workaround to completely delete crd ?

## Your Environment

* Calico version
* v3.13
* Orchestrator version (e.g. kubernetes, mesos, rkt):
19.0.3.09
* Operating System and version:
Centos 7.9
* Link to your project (optional):

**Comment by caseydavenport** [comment]
@aasraoui v3.13 is very old - have you tried this on a newer version of Calico?
