### ISSUE TITLE
Kubernetes stars-policy tutorial not functional

### ISSUE THREAD

**Issue by ottoyiu** [projectcalico/calico#482]
Hi there,

I'm currently running Kubernetes v1.5.1, using calico-node v1.0 and calico-cni v1.5.5 along with kube-policy-controller v0.5.2; running using IPIP mode if that makes a difference.

I first tried out the simple policy example, which worked flawlessly. With the stars-policy example, I'm unable to get access between namespaces functional. The management ui cannot access frontend, backend, client services even after applying the `allow-ui-client.yaml` and `allow-ui.yaml` files:
```
kubectl get networkpolicies --all-namespaces
NAMESPACE   NAME              POD-SELECTOR    AGE
client      allow-ui          <none>          1h
otto        access-nginx      run=nginx       1h
stars       allow-ui          <none>          1h
stars       backend-policy    role=backend    47m
stars       frontend-policy   role=frontend   46m
```

At first I thought it was something wrong with the kube-policy-controller, but looking at the test cases - the output seemed to be proper:
```
/ # etcdctl get /calico/v1/policy/tier/default/policy/stars.backend-policy
{"outbound_rules": [{"action": "allow"}], "order": 1000, "inbound_rules": [{"action": "allow", "src_selector": "role == 'frontend' && calico/k8s_ns == 'stars'", "protocol": "tcp", "dst_ports": [6379]}], "selector": "calico/k8s_ns == 'stars' && role == 'backend'"}
/ # etcdctl get /calico/v1/policy/tier/default/policy/stars.frontend-policy
{"outbound_rules": [{"action": "allow"}], "order": 1000, "inbound_rules": [{"action": "allow", "src_selector": "k8s_ns/label/role == 'client'", "protocol": "tcp", "dst_ports": [80]}], "selector": "calico/k8s_ns == 'stars' && role == 'frontend'"}
```

I narrowed down to the fact that I can not gain access to the necessary services that are across namespaces, since the simple policy example/tutorial with the nginx worked and I can get the frontend to talk to the backend after applying the `backend-policy.yaml`:
https://github.com/projectcalico/calico/blob/master/v2.0/getting-started/kubernetes/tutorials/stars-policy/policies/frontend-policy.yaml#L14

This works:
```
kubectl exec -it frontend-3q0qs --namespace stars bash
root@frontend-3q0qs:/star# python probe.py http://backend.stars:6379/status                                                                                                          
Sending request: http://backend.stars:6379/status
Response: <Response [200]>
```

This doesn't:
```
kubectl exec -it client-lw55l --namespace client bash                                                                                                                 
root@client-lw55l:/star# python probe.py http://frontend.stars/status
Sending request: http://frontend.stars/status
Error: HTTPConnectionPool(host='frontend.stars', port=80): Max retries exceeded with url: /status (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f7da3a5a2d0>, 'Connection to frontend.stars timed out. (connect timeout=2)'))
```

Are across-namespace policies supported in Calico, ie. pod A in namespace A can talk to service foo in namespace B, given the proper NetworkPolicy definition?

P.S. I came across this old blog post; not sure how relevant this is anymore...
https://www.projectcalico.org/calico-network-policy-comes-to-kubernetes/

**Comment by caseydavenport** [comment]
@ottoyiu thanks for raising!

> Are across-namespace policies supported in Calico, ie. pod A in namespace A can talk to service foo in namespace B, given the proper NetworkPolicy definition?

Yes, definitely.

I think you're hitting an issue that was resolved in Calico v2.0.1.  See the latest versions here: http://docs.projectcalico.org/v2.0/releases/

I'd recommend upgrading to the latest patch release - Calico v2.0.2.

> P.S. I came across this old blog post; not sure how relevant this is anymore...
https://www.projectcalico.org/calico-network-policy-comes-to-kubernetes/

That is quite old - we still do Policy, but it's advanced quite a bit since that blog post.
