### ISSUE TITLE
Pods are not able to communicate among itself, if pods are distributed in multi cluster environment and calico network policies are applied

### ISSUE THREAD

**Issue by gvssaikishore** [projectcalico/calico#4835]
Calico policies for two-cluster Kubernetes with DB pods spread across two Kubernetes clusters

Following is our deployment architecture 
[MDC.pptx](https://github.com/projectcalico/calico/files/6975848/MDC.pptx)

1. Two Kubernetes clusters (A & B ) for high availability  in Active-Active mode
2. Separate application instances in each Kubernetes cluster.
3. DB is spread across both the clusters for quick and effective synchronization when one cluster goes down 
   a. 2 DB pods running in  cluster A and 2 DB pods in cluster B
4. We have applied global calico policies for restricting ingress ports.
5.  We have applied calico network policies including to all the microservices  (including database ) to restrict unauthorized access by using labels

## Expected Behavior

With the Calico network policy implemented for DB along with other micro services, the application should work.

## Current Behavior

While the application is coming up, DB pods are unable to connect and remain in another state.
 
Once we remove the calico network policy for DB, the application is coming up and working properly.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Calico version 
Client Version:    v3.18.2
Git commit:        528c5860
Cluster Version:   v3.20.0
Cluster Type:      k8s,bgp,kubeadm,kdd
* Orchestrator version (e.g. kubernetes, mesos, rkt): Kubernetes v1.19.3
* Operating System and version:  CentOS Linux release 7.5
* Link to your project (optional):

**Comment by caseydavenport** [comment]
@gvssaikishore sounds potentially like your policy is cutting off traffic that is required for your app to work.

**Comment by karthik-kolar** [comment]
@caseydavenport  

Yes that what is exactly happening. So we would like to know is there any work around or any pointers do you have on the above.

Currently Network template policy, validate pods using label selectors within the cluster, what every the label which we added in cluster-B will not validate. (Expected behavior: We need to restrict access to (Postgres and Mongodb) DB  from outside, and need to allow access only from cluster-B )

**Comment by caseydavenport** [comment]
It's hard for me to suggest the correct policy when I don't know the application requirements itself and which traffic isn't being allowed that should be - the first step is going to be to identify which app traffic is not allowed by your network policy, and then we'll need to craft an appropriate rule to allow that traffic as restrictively as possible.
