### ISSUE TITLE
[kubernetes 1.21] [calico 3.20] felix/kubeendpointslice.go 101: Unable to list K8s EndpointSlice resources

### ISSUE THREAD

**Issue by jayaddison** [projectcalico/calico#4848]
After bringing up a Kubernetes 1.21.4 cluster with Calico 3.20, one of the `calico-node` pods appeared to be 'Running', but not 'Ready':

```
$ kubectl -n kube-system get pods
...
calico-node-x4nc6                          0/1     Running   0          19h
```

The following info-level messages appeared in the pod logs:

```
2021-08-17 16:45:40.248 [INFO][57] felix/watchercache.go 174: Full resync is required ListRoot="/calico/resources/v3/projectcalico.org/kubernetesendpointslices"
2021-08-17 16:45:40.250 [INFO][57] felix/kubeendpointslice.go 101: Unable to list K8s EndpointSlice resources error=endpointslices.discovery.k8s.io is forbidden: User "system:serviceaccount:kube-system:calico-node" cannot list resource "endpointslices" in API group "discovery.k8s.io" at the cluster scope
2021-08-17 16:45:40.250 [INFO][57] felix/watchercache.go 186: Failed to perform list of current data during resync ListRoot="/calico/resources/v3/projectcalico.org/kubernetesendpointslices" error=connection is unauthorized: endpointslices.discovery.k8s.io is forbidden: User "system:serviceaccount:kube-system:calico-node" cannot list resource "endpointslices" in API group "discovery.k8s.io" at the cluster scope
```

## Expected Behavior
The `calico-node` pod should be counted as  'Ready'.

## Current Behavior
The `calico-node` pod is 'Running', but does not appear as 'Ready'.

## Possible Solution
Workaround: downgraded to Calico 3.19.

Idea: based on the info-level log messages, perhaps this relates to some kind of permissions change / expectation in the Kubernetes?  There is a similar-sounding comment [here](https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/1583#issuecomment-893877678).

## Steps to Reproduce (for bugs)
1. Initialize a Kubernetes 1.21.4 cluster ([ref](https://github.com/openculinary/infrastructure/tree/027fb5e400c1b1567edf2f5ebbd8b49e80c5bc61#initialize-cluster))
2. Deploy Calico 3.20 networking infrastructure (among other Kubernetes configuration scripts) ([ref](https://github.com/openculinary/infrastructure/tree/027fb5e400c1b1567edf2f5ebbd8b49e80c5bc61#deploy-kubernetes-infrastructure-components))
3. Observe that the `calico-node` pod appears 'Running' but does not appear to be 'Ready'

(I think that this repro case may be incomplete / imprecise - there may be additional information required, let me know if I can help with any configuration/system details)

## Context
The fact that the `calico-node` pod was not running was discovered while investigating network connectivity problems within the cluster.  After downgrading to Calico 3.19, the pod did begin running, and network connectivity is functional (not a conclusive resolution, but it seems like it helped).

## Your Environment
* Calico version 3.20
* Orchestrator version (e.g. kubernetes, mesos, rkt): Kubernetes 1.21.4
* Operating System and version: Ubuntu Linux
* Link to your project (optional): https://github.com/openculinary/infrastructure/

**Comment by lmm** [comment]
@jayaddison I think when you upgraded Calico to v3.20, it might have been missing this RBAC fix: https://github.com/projectcalico/calico/pull/4770/files

**Comment by jayaddison** [comment]
That looks highly likely, thank you @lmm!  I'll test that out soon.  I'll re-open this issue if that _doesn't_ fix the problem, but I expect that it will :)

**Comment by jayaddison** [comment]
Yep, thanks again @lmm - including that fixup has resolved the issue.

**Comment by lmm** [comment]
Awesome, glad to hear that @jayaddison and thank you for the update!

**Comment by chendong96** [comment]
请问你的k8s1.21版本环境是通过什么方式部署的？kubeadm还是二进制？我使用二进制部署后，calico的所有组件都无法running，并且报错如下：
Failed to create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container "876a3d4a5e74a3d2aff35fa57c67a9b28966e783fbf464056fb03ed5e2597c5c" network for pod "calico-kube-controllers-58497c65d5-q7l4f": networkPlugin cni failed to set up pod "calico-kube-controllers-58497c65d5-q7l4f_kube-system" network: stat /var/lib/calico/nodename: no such file or directory: check that the calico/node container is running and has mounted /var/lib/calico/
