### ISSUE TITLE
[helm] Remove deprecated crd-hook in CRD apiserver

### ISSUE THREAD

**Issue by haouc** [projectcalico/calico#4854]
Helm 3 deprecates crd-hook in favor of the `crds/` directory. Does Calico have a plan to deprecate `helm.sh/hook: crd-install`

## Expected Behavior

Since Calico already has the `crds` directory, the hook should be deprecated to avoid warning and failure when using helm 3.

## Current Behavior

Currently the CRD is still using `crd-install` as a hook. 

## Possible Solution

Since the CRD apiserver is already in the crds directory, the `crd-install` hook can be removed.
https://github.com/projectcalico/calico/blob/ace21447af231802d33441ea80f37d988dacf2c0/_includes/charts/tigera-operator/crds/operator.tigera.io_apiservers_crd.yaml#L6
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Context

This is a deprecated behavior and can fail `helm install` and `helm template`.

## Your Environment

* Calico version - v3.20.0
* Orchestrator version (e.g. kubernetes, mesos, rkt): - EKS 1.20
* Operating System and version: macOS Catalina 10.15.7
* Link to your project (optional):

**Comment by caseydavenport** [comment]
Sounds like we already have our CRDs in the right place, so this is just a matter of removing the `helm.sh/hook: crd-install` annotation from the objects in the chart? If so, should be simple enough. I believe we'd still need that on a helm v2 chart, though.

**Comment by caseydavenport** [comment]
A quick grep of the code shows this is no longer an issue.
