### ISSUE TITLE
Ipam blocks are not reused or cleaned properly and hitting per host block limit

### ISSUE THREAD

**Issue by martin-ducar-gd** [projectcalico/calico#4861]
## Expected Behavior

We expect ipamblocks to have same allocations size as number of pods in cluster or at least close to that number

## Current Behavior

We see pods in ContainerCreating state with messages of exhausted per host block limit

```
networkPlugin cni failed to set up pod "default1" network: cannot allocate new block due to per host block limit 
```

```sh
% kubectl get pods -A | wc -l 
     801
% kubectl get ipamblocks.crd.projectcalico.org -o=json > ipamblocks.json
% jq '.items[] | .spec.unallocated | length' ipamblocks.json | grep "^0" | wc -l
      55

% kubectl get installations.operator.tigera.io default -o yaml 
apiVersion: operator.tigera.io/v1
kind: Installation
metadata:
  annotations:
  name: default
  ...
spec:
  calicoNetwork:
    bgp: Enabled
    hostPorts: Enabled
    ipPools:
    - blockSize: 24
      cidr: 100.96.0.0/11
      encapsulation: IPIP
      natOutgoing: Enabled
      nodeSelector: all()
    linuxDataplane: Iptables
    mtu: 1440
    multiInterfaceMode: None
    nodeAddressAutodetectionV4:
      firstFound: true
  cni:
    ipam:
      type: Calico
    type: Calico
  flexVolumePath: /host/driver
  imagePullSecrets:
  - name: dockerhub-auth
  kubernetesProvider: ""
  nodeUpdateStrategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
  variant: Calico
status:
  computed:
    calicoNetwork:
      bgp: Enabled
      hostPorts: Enabled
      ipPools:
      - blockSize: 24
        cidr: 100.96.0.0/11
        encapsulation: IPIP
        natOutgoing: Enabled
        nodeSelector: all()
      linuxDataplane: Iptables
      mtu: 1440
      multiInterfaceMode: None
      nodeAddressAutodetectionV4:
        firstFound: true
    cni:
      ipam:
        type: Calico
      type: Calico
    flexVolumePath: /host/driver
    imagePullSecrets:
    - name: dockerhub-auth
    nodeUpdateStrategy:
      rollingUpdate:
        maxUnavailable: 1
      type: RollingUpdate
    variant: Calico
  mtu: 1440
  variant: Calico
```
as you can see block size is `/24` which is 254 addresses meaning 55 full subnets would result in 55*254 = 13970 compared to number of pods 801 means we have a leak somewhere. We would really need help to identify why its happening or if config is wrong. Also I can't find any documentation around `per host block limit`

## Steps to Reproduce (for bugs)

1. Using tigera-operator install calico in version v3.19.0
2. Generate enough workload on cluster - current workload involves mainly jupiterhub and argo workflow executions all job like executions with start and end
3. Watch ipamblock being slowly exhausted with in the end no new jobs being able to start

## Your Environment

* Calico version - 3.19.0
* Orchestrator version (e.g. kubernetes, mesos, rkt): kubeadm on AWS custom built
* Operating System and version: Flatcar Container Linux by Kinvolk 2905.2.1 (Oklo)
* Link to your project (optional): internal

**Comment by martin-ducar-gd** [comment]
Another info is we found one node on the cluster which has exhausted the limit
```sh
jq '.items[] | select(.spec.affinity == "host:ip-**********.ec2.internal") | .spec.unallocated | length' ~/notes/ipamblocks.json
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
```
and number of blocks is 20 which seems to be a limit per host, but host can only run max 110 pods and actually its running only 40 pods. again allocated ips in ipam 20*254 = 5080

```sh
% kubectl describe no ip-************.ec2.internal
...
Non-terminated Pods:          (40 in total)
...
```

**Comment by martin-ducar-gd** [comment]
Only diffs in configuration between our old and new setup, which did not suffer from the issue are:
* block size change from default `/26` to `/24`
* pure calico manifest vs tigera-operator
* version 3.12.0 to 3.19.0

**Comment by caseydavenport** [comment]
@martin-ducar-gd how many nodes are in your cluster? Calico allocates an IPAM block per node (potentially multiple IPAM blocks per-node if needed in order to satisfy the number of pods on that node).

You can run `calicoctl ipam check` to get a general health report on Calico's IPAM state - should give us a better idea of what's going on.

Given you have a node with 20 blocks, it does sound like there is likely an IP address leak occurring in your cluster. Has anything else changed in your cluster? What container runtime are you using (e.g., docker / crio / containerd)? 

Useful diags for this would be:
- kubelet logs
- container runtime logs
- Calico CNI logs (/var/log/calico/cni)
- Output from `calicoctl ipam check -o report.json`

**Comment by caseydavenport** [comment]
>  cannot allocate new block due to per host block limit 

This is a safeguard against a single node stealing all of the cluster's IPAM resources in case of a severe leak / misconfiguration. Are you seeing this on every node? Or just one or two? I suspect it's doing it's job and preventing a subset of nodes from allocating every block.

**Comment by caseydavenport** [comment]
@martin-ducar-gd any update on this?

**Comment by martin-ducar-gd** [comment]
Sorry was on PTO @caseydavenport seems team upgrade of calico to 3.20 fixed the issue, so most probalby its one of https://github.com/projectcalico/kube-controllers/pull/744 https://github.com/projectcalico/kube-controllers/pull/799

**Comment by caseydavenport** [comment]
Great! Glad to hear it.
