### ISSUE TITLE
First scheduled pod on each node is assigned existing IPIP tunnel interface IP

### ISSUE THREAD

**Issue by tfussell** [projectcalico/calico#4863]
## Expected Behavior

Calico should not assign an IP to a pod if it's already being used by the tunnel interface.

## Current Behavior

calico-node logs, tunl0 is assigned IP 172.24.88.64 at 16:44:
```
2021-08-20 16:44:56.479 [INFO][16] tunnel-ip-allocator/ipam.go 534: Block '172.24.88.64/26' has 64 free ips which is more than 1 ips required. host="master-w2g9n-56df9fb85c-769br" subnet=172.24.88.64/26
2021-08-20 16:44:56.479 [INFO][16] tunnel-ip-allocator/ipam.go 1032: Attempting to assign 1 addresses from block block=172.24.88.64/26 handle="ipip-tunnel-addr-master-w2g9n-56df9fb85c-769br" host="master-w2g9n-56df9fb85c-769br"
2021-08-20 16:44:56.481 [INFO][16] tunnel-ip-allocator/ipam.go 1509: Creating new handle: ipip-tunnel-addr-master-w2g9n-56df9fb85c-769br
2021-08-20 16:44:56.483 [INFO][16] tunnel-ip-allocator/ipam.go 1055: Writing block in order to claim IPs block=172.24.88.64/26 handle="ipip-tunnel-addr-master-w2g9n-56df9fb85c-769br" host="master-w2g9n-56df9fb85c-769br"
2021-08-20 16:44:56.485 [INFO][16] tunnel-ip-allocator/ipam.go 1068: Successfully claimed IPs: [172.24.88.64/26] block=172.24.88.64/26 handle="ipip-tunnel-addr-master-w2g9n-56df9fb85c-769br" host="master-w2g9n-56df9fb85c-769br"
2021-08-20 16:44:56.485 [INFO][16] tunnel-ip-allocator/ipam.go 722: Auto-assigned 1 out of 1 IPv4s: [172.24.88.64/26] handle="ipip-tunnel-addr-master-w2g9n-56df9fb85c-769br" host="master-w2g9n-56df9fb85c-769br"
2021-08-20 16:44:56.490 [INFO][16] tunnel-ip-allocator/allocateip.go 440: Assigned tunnel address to node IP="172.24.88.64" type="ipipTunnelAddress"
```

CNI logs, same node as above, pod is assigned IP 172.24.88.64 at 16:49:
```
Aug 20 16:49:26 master-w2g9n-56df9fb85c-769br kubelet[9022]: 2021-08-20 16:49:26.533 [INFO][10391] ipam.go 534: Block '172.24.88.64/26' has 64 free ips which is more than 1 ips required. host="master-w2g9n-56df9fb85c-769br" subnet=172.24.88.64/26
Aug 20 16:49:26 master-w2g9n-56df9fb85c-769br kubelet[9022]: 2021-08-20 16:49:26.533 [INFO][10391] ipam.go 1032: Attempting to assign 1 addresses from block block=172.24.88.64/26 handle="k8s-pod-network.6a13dc1e5bac58806f9a0e8b69f177b3785aab5a9bde2aaca9f923955af85144" host="master-w2g9n-56df9fb85c-769br"
Aug 20 16:49:26 master-w2g9n-56df9fb85c-769br kubelet[9022]: 2021-08-20 16:49:26.535 [INFO][10391] ipam.go 1509: Creating new handle: k8s-pod-network.6a13dc1e5bac58806f9a0e8b69f177b3785aab5a9bde2aaca9f923955af85144
Aug 20 16:49:26 master-w2g9n-56df9fb85c-769br kubelet[9022]: 2021-08-20 16:49:26.538 [INFO][10391] ipam.go 1055: Writing block in order to claim IPs block=172.24.88.64/26 handle="k8s-pod-network.6a13dc1e5bac58806f9a0e8b69f177b3785aab5a9bde2aaca9f923955af85144" host="master-w2g9n-56df9fb85c-769br"
Aug 20 16:49:26 master-w2g9n-56df9fb85c-769br kubelet[9022]: 2021-08-20 16:49:26.543 [INFO][10391] ipam.go 1068: Successfully claimed IPs: [172.24.88.64/26] block=172.24.88.64/26 handle="k8s-pod-network.6a13dc1e5bac58806f9a0e8b69f177b3785aab5a9bde2aaca9f923955af85144" host="master-w2g9n-56df9fb85c-769br"
Aug 20 16:49:26 master-w2g9n-56df9fb85c-769br kubelet[9022]: 2021-08-20 16:49:26.543 [INFO][10391] ipam.go 722: Auto-assigned 1 out of 1 IPv4s: [172.24.88.64/26] handle="k8s-pod-network.6a13dc1e5bac58806f9a0e8b69f177b3785aab5a9bde2aaca9f923955af85144" host="master-w2g9n-56df9fb85c-769br"
```

## Possible Solution

Either the tunnel IP assignment isn't actually stored in the datastore (etcd) or the CNI IPAM doesn't consider the tunnel IP assignment when selecting an available IP for a pod.

## Steps to Reproduce (for bugs)

1. Start a new cluster without CNI.
2. Install Calico 3.19.2 using etcd datastore with IPIP set to "Always".
3. Create a test pod on a node and it will use the IP of the tunnel device and networking will be broken inside the container.
4. Recreate the pod and it will get a different IP and start working.

## Context

I am trying to automatically bootstrap an onprem cluster in VMs. I create the VMs and register the nodes using ignition and systemd units. Then I install an operator which takes care of installing helm charts in the cluster. The networking is broken for the operator when it is first deployed until I manually delete it. Once it's restarted and working, the first pod scheduled on each node then shows the same issue.

I found https://github.com/projectcalico/calico/issues/3589 which sounds similar, but the setup seems quite different.

## Your Environment
* Calico version: 3.19.2
* Orchestrator version (e.g. kubernetes, mesos, rkt): Kubernetes 1.20.10
* Operating System and version: Flatcar Container Linux 2605.12.0 with kernel 5.4.92 and docker 19.03.14
* Link to your project (optional): https://github.com/giantswarm/kvm-operator
* Datastore: etcd 3.4.16

**Comment by caseydavenport** [comment]
@tfussell interesting - have you made any modifications to your calico.yaml manifest? How exactly are you installing Calico in this situation?

I think to dig into this I'll probably need:

- Full logs from a calico/node hitting this issue.
- Logs from the calico kube-controllers pod
- Logs from the CNI plugin on the node hitting this issue that includes creation of the pod which receives the bad IP.

Another really useful output would be from running this command on a broken system (both output to screen as well as the generated report.json file): `calicoctl ipam check -o report.json`

If I had to guess, without looking at those logs, something must be misconfigured such that kube-controllers is garbage collecting your valid tunnel IP, so when the pod comes around to be created it sees the address as available.
