### ISSUE TITLE
[AWS] [EKS] unexpected route, incorrect gateway with Calico version v3.20.0

### ISSUE THREAD

**Issue by julienMichaud** [projectcalico/calico#4866]
Hi,

When using Calico v3.20.0, I see this message appearing randomly in my calico pods
`{"log":"2021-08-22 12:20:06.485 [INFO][58] felix/route_table.go 876: Remove old route dest=192.168.79.64/26 ifaceName=\"eth0\" ifaceRegex=\"\" ipVersion=0x4 routeProblems=[]string{\"unexpected route\", \"incorrect gateway\"}\n","stream":"stdout","time":"2021-08-22T12:20:06.485950174Z"}`

When this error appear, I cant resolve hostnames from pods in my cluster (cant resolve a service inside my cluster, cant resolve google.com, etc). My application load balancer target groups cant access pods exposed via nodePort on my nodes (request time out). 
After a few minutes (5-10) everything goes back to normal and after 10mn the problem reappear. 

I didnt find any solution except downgrading from v3.20.0 to v3.19.1 thanks to Yuri Gelfand on the Calico slack.

Im using EKS 1.21, installed with Terraform. 
I use the Calico CNI instead of the AWS VPC CNI.
I installed Calico using this manifest https://docs.projectcalico.org/manifests/calico-vxlan.yaml

[calico_node_logs.zip](https://github.com/projectcalico/calico/files/7039306/calico_node_logs.zip)
![image](https://user-images.githubusercontent.com/35925031/130620599-ed237b09-17e0-4dd9-8bf1-c0b9eeffbe8b.png)
![image](https://user-images.githubusercontent.com/35925031/130621491-0347f13b-9a83-493f-9305-e4fbf7417737.png)
![image](https://user-images.githubusercontent.com/35925031/130621310-429d24f4-2602-4f20-a41b-f9d4a0a525fb.png)

**Comment by fasaxc** [comment]
Checked for likely candidates:
* The routing table code hasn't changed at all between v3.19.1 and v3.20.0.
* However, there is a change in the vxlan_mgr; we added blackhole route calculation
* No change in the L3 route resolver or vxlan resolver.

**Comment by toshokan** [comment]
This doesn't seem to only affect AWS/EKS. I ran into the same issue with a bare metal on-prem install (kubernetes 1.22 + calico 3.20). As with the others, downgrading to 3.19.1 (which also meant downgrading to kubernetes 1.21) resolved the issue. 

Seems like #4869 is more general

**Comment by almson** [comment]
Running 3.19.1 doesn't solve the issue for me. Looks like it was an AMI upgrade that did it.

**Comment by almson** [comment]
As @jubbynox pointed out, `kubectl patch ippool.crd.projectcalico.org default-ipv4-ippool --type merge -p '{"spec":{"vxlanMode":"Always"}}'` is a good workaround. It's too bad this cannot be specified in tigera `Installation`.

**Comment by LiranBinshtok** [comment]
i can confirm that downgrading the version helped solve this issue. please update when you solve the bug.

**Comment by almson** [comment]
@LiranBinshtok Are you using AWS CNI?

**Comment by LiranBinshtok** [comment]
> @LiranBinshtok Are you using AWS CNI?

no.

**Comment by dylan2intel** [comment]
> Running 3.19.1 doesn't solve the issue for me. I'm on AWS EKS 1.20 w/o the AWS CNI plugin. Looks like same-subnet non-VXLAN routing doesn't work. I have to use VXLAN for all routes.
> 
> As @jubbynox pointed out, `kubectl patch ippool.crd.projectcalico.org default-ipv4-ippool --type merge -p '{"spec":{"vxlanMode":"Always"}}'`.
> 
> Or, if using Tigera operator Helm chart, `values.yaml`:
> 
> ```
> installation:
>   calicoNetwork:
>     ipPools:
>       encapsulation: VXLAN
> ```

if using calico.yaml manifest not tigera operator installed,
  calico_backend: "vxlan"
              value: "Never"
              value: "CrossSubnet"
              value: "CrossSubnet"
change `CrossSubnet` into `Always`
