### ISSUE TITLE
calico seems to remove routes to CIDR of pods that are the same node subnet

### ISSUE THREAD

**Issue by LiranBinshtok** [projectcalico/calico#4869]
we are obeserving a behavior that a route is being added and deleting intermediately log from calico pod: 
`felix/route_table.go 876: Remove old route dest=192.168.22.128/26 ifaceName="eth0"ifaceRegex=""ipVersion=0x4routeProblems=[]string{"unexpec`
 I think this is the relevant log for it. once it does that the pod under this CIDR block is unreachable since the traffic goes through 0.0.0.0 and to the internet.

possible [dup](https://github.com/projectcalico/calico/issues/4866)

when i am looking at the code i think [this](https://github.com/projectcalico/felix/blob/2ac79567b8fdf60e0a34b0bddc81aa8552012bdf/routetable/route_table.go#L843)
where the issue begins but i am unable to understand why the route is unexpected :/ 

## Expected Behavior

Route of the CIDR should stay or replace with no downtime.
## Current Behavior

the route is deleting and all the pods under that CIDR are un reachable 
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Calico version 3.20.0
* Orchestrator version (e.g. kubernetes, mesos, rkt):
* k8s v1.19.13-eks-8df270
* Operating System and version:
* NAME="Amazon Linux"
VERSION="2"
ID="amzn"
ID_LIKE="centos rhel fedora"
VERSION_ID="2"
PRETTY_NAME="Amazon Linux 2"
ANSI_COLOR="0;33"
CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2"
HOME_URL="https://amazonlinux.com/"

**Comment by almson** [comment]
Set vxlanMode to Always

   `kubectl patch ippool.crd.projectcalico.org default-ipv4-ippool --type merge -p '{"spec":{"vxlanMode":"Always"}}'`

The default seems to be `CrossSubnet` which gives the observed behavior.

**Comment by LiranBinshtok** [comment]
will try this. but i would still like to have this bug fixed, since this solution will add hops.

**Comment by LiranBinshtok** [comment]
Update i change calico version like suggested in the possible dup and so far i have 20 minutes without an unhealthy target :).
i believe its a bug in the new version problem is, that it does not reproduce 100 % of the times, some clusters works fine :/

**Comment by LiranBinshtok** [comment]
i am closing this issue since i believe its a duplicate with the issue i mentioned at the description.
