### ISSUE TITLE
eBPF on EKS arm64

### ISSUE THREAD

**Issue by rubroboletus** [projectcalico/calico#4871]
Hello,

on EKS 1.21, provisioned by Terraform, VPN CNI 1.90, I have installed calico 3.20.0 using tigera-operator. Followed setup steps for eBPF mode. With kube-proxy running, arm64 nodes are able to join cluster and operate. When kube-proxy is turned off by the nodeSelector patch, new arm64 nodes are unable to join cluster. calico-node pod normaly starts on this new node, but vpc cni is in loop, trying to check IPAM connectivity.

## Expected Behavior
I expect, that arm64 nodes will be able to join same way, as amd64 nodes.

## Current Behavior
aws-node pod on arm64 node is in crashloop, trying to check IPAM connectivity (in fact, access cluster on 172.20.0.1:443).

## Steps to Reproduce (for bugs)
1. install EKS with amd64 node group
2. follow steps from Calico documentation for switch EKS to eBPF mode
3. add arm64 node group
4. nodes will be able to reach cluster and run calico-node, but aws-node will be in crashloop

## Your Environment
* Calico version 3.20.0
* EKS 1.21
* Amazon Linux 2 standard EKS AMI with bpf filesystem mounted
* AWS VPC CNI 1.7.5, 1.8.0, 1.9.0 (same issue with any version)

**Comment by caseydavenport** [comment]
I believe eBPF mode is not yet supported on alternative architectures besides AMD64

CC @frozenprocess since I think he's looking at this - do we have an issue tracking this already?

**Comment by frozenprocess** [comment]
You are facing this issue since eBPF is not supported for `arm64` in 3.20.x and lower. (As Casey mentioned) 

Try this  `nightly` version of the operator for a multiarch setup. 
```
kubectl create -f https://docs.projectcalico.org/master/manifests/tigera-operator.yaml
```


This is my own cluster
```
$ kubectl get nodes -L kubernetes.io/arch
NAME                                           STATUS   ROLES    AGE   VERSION              ARCH
ip-192-168-11-39.us-west-2.compute.internal    Ready    <none>   30m   v1.20.7-eks-135321   amd64
ip-192-168-89-114.us-west-2.compute.internal   Ready    <none>   36m   v1.20.7-eks-135321   arm64

$ kubectl get pods -A -ocustom-columns=NAME:.metadata.name,NODE:.spec.nodeName
NAME                                       NODE
calico-apiserver-78dbf7c7dc-pfqck          ip-192-168-11-39.us-west-2.compute.internal
calico-kube-controllers-6784cd5c99-xng5c   ip-192-168-11-39.us-west-2.compute.internal
calico-node-hfj4x                          ip-192-168-11-39.us-west-2.compute.internal
calico-node-mzb4s                          ip-192-168-89-114.us-west-2.compute.internal
calico-typha-5599d5f9d8-d5s77              ip-192-168-11-39.us-west-2.compute.internal
calico-typha-5599d5f9d8-nc42p              ip-192-168-89-114.us-west-2.compute.internal
aws-node-kqxbj                             ip-192-168-89-114.us-west-2.compute.internal
aws-node-zflmp                             ip-192-168-11-39.us-west-2.compute.internal
coredns-ff7ff8cb-fqbz2                     ip-192-168-89-114.us-west-2.compute.internal
coredns-ff7ff8cb-qqlcq                     ip-192-168-89-114.us-west-2.compute.internal
tigera-operator-cbd6b8ccc-2mx6h            ip-192-168-11-39.us-west-2.compute.internal

$ kubectl logs calico-node-mzb4s -n calico-system | egrep -i 'bpf enabled'
2021-09-04 01:52:11.058 [INFO][35] felix/int_dataplane.go 357: BPF enabled, configuring iptables layer to clean up kube-proxy's rules.
2021-09-04 01:52:11.067 [INFO][35] felix/int_dataplane.go 554: BPF enabled, starting BPF endpoint manager and map manager.
2021-09-04 01:52:11.166 [INFO][35] felix/int_dataplane.go 1695: BPF enabled, disabling unprivileged BPF usage.

$ kubectl logs calico-node-hfj4x -n calico-system | egrep -i 'bpf enabled'
2021-09-04 01:51:54.319 [INFO][36] felix/int_dataplane.go 357: BPF enabled, configuring iptables layer to clean up kube-proxy's rules.
2021-09-04 01:51:54.330 [INFO][36] felix/int_dataplane.go 554: BPF enabled, starting BPF endpoint manager and map manager.
2021-09-04 01:51:54.478 [INFO][36] felix/int_dataplane.go 1695: BPF enabled, disabling unprivileged BPF usage.
```

**Comment by caseydavenport** [comment]
@frozenprocess I think we can close this as it will work in the next Calico release (v3.21.0). Please correct me if this is wrong!
