### ISSUE TITLE
Document install-cni container

### ISSUE THREAD

**Issue by heschlie** [projectcalico/calico#489]
There should be some documentation, potentially either in the k8s section or in the references/cni-plugins, about what this container does.

**Comment by djosborne** [comment]
We should also add it to the repo structure artifacts page: http://docs.projectcalico.org/v2.0/reference/repo-structure

**Comment by tmjd** [comment]
Need to document https://github.com/projectcalico/cni-plugin/pull/341 (SKIP_CNI_BINARIES) as part of the document.
