### ISSUE TITLE
how can i forward the 443 port traffic from ippool (iot-internet) pods to port 1809 which is a proxy service running in my host on 1809 port

### ISSUE THREAD

**Issue by srinicrick65** [projectcalico/calico#4894]
Hi ,

I have a k3s cluster with calico as CNI plugin . I have a pod "TestPod"  which is running on k3s in "test" namespace . I have created an IPPOOL called "IOT_INTERNET" that has natOutgoing as true and mapped this ippool to the pods which are on namespace "test".  I have a proxy service that is running on 1809 port in my host and not inside k3s cluster 
. Now my requirement is whenever there is a egress calls to 443 port from TestPod it should redirect the calls to 1809 port which is in my host . How can i achieve this with calico  network policy ? If not possible from calico is there any ways that i can achieve this ?

Thanks in Advance

**Comment by caseydavenport** [comment]
Sounds like you might be looking for a Kubenretes service in front of your external proxy service?

https://kubernetes.io/docs/concepts/services-networking/service/#services-without-selectors

**Comment by srinicrick65** [comment]
hi @caseydavenport  In my case I have a proxy service which is running on port 1809 in my host machine (localhost) and I want to route all my  443 port calls from pod "TestPod" to proxy service port 1809 which is running in my local machine outside the k3s cluster.
Will the solution that you provided would work for my use case? 

Example
I will go to the pod "TestPod" shell and do curl https://google.com and this call should route to my  local proxy service which is running on 1809 in the same machine but outside the k3s cluster

**Comment by caseydavenport** [comment]
Ah, I misunderstood. No - what I suggested above isn't going to help you here.

Similarly, this isn't something that Calico is currently capable of doing. You might be able to achieve that with something like Istio, though.

What is the purpose of your proxy?

**Comment by caseydavenport** [comment]
> Is there a way I can redirect all the https calls to a kubernetes service from a pod.

This isn't really within the scope of Calico.
