### ISSUE TITLE
Can not pull docker.io/calico/cni:v3.20.0

### ISSUE THREAD

**Issue by thanos1983** [projectcalico/calico#4918]
Launching kubernetes cluster with calico and image is failing to be pulled sample:

```bash
docker pull docker.io/calico/cni:v3.20.0                                   
Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
```

## Expected Behavior

Expected behavior being able to pull the image.

## Current Behavior

Currently is failing.

## Possible Solution

No solution to my knowledge.

## Steps to Reproduce (for bugs)

1. Simply run docker pull the image. Sample given above.
2.
3.
4.

## Context

I can not launch my kubernetes cluster.

## Your Environment

* Calico version
3.20 downloaded from here [Install Calico networking and network policy for on-premises deployments](https://docs.projectcalico.org/getting-started/kubernetes/self-managed-onprem/onpremises)
* Orchestrator version (e.g. kubernetes, mesos, rkt):
Kubernetes version tested it with (1.20, 1.21 and 1.22) same problem.
* Operating System and version:
Ubuntu 20.04
* Link to your project (optional):
Github Link [kubernetesVagrant](https://github.com/thanos1983/kubernetesVagrant)

**Comment by caseydavenport** [comment]
@thanos1983 DockerHub has pull ratelimits based on the client IP - sounds likely that you have pulled too many images from DockerHub on that IP address, and so DockerHub is ratelimiting you.

Solutions to this are either:
- Pull the images to your own registry so you don't depend on public infrastructure (recommended)
- Use a paid DockerHub account that has no pull limit
- Use Calico images hosted at quay.io which do not (yet) have a ratelimit enforced on them.

We are considering moving our default to quay.io, but that may take some time. Unfortunately DockerHub's ratelimiting is out of our control.
