### ISSUE TITLE
Calico is not is no longer capable of disabling source/destination checks on EKS nodes

### ISSUE THREAD

**Issue by theophileds** [projectcalico/calico#4923]
The version of calico we used was **3.19.1** and the manifest was calico-vxlan.yaml for EKS.
We first observed connectivity issues, like pods incapable of resolving DNS or just communicating with other pods in different nodes.
Also, we noticed that some calico-node had a warning message saying
`felix is not ready: readiness probe reporting 503`

We used to have this issue before and previously reported it and decided to disable the following settings
`FELIX_AWSSRCDSTCHECK`

It somehow mitigated the warning message but we still had connectivity issues.
We tried to upgrade calico to `3.20` which suppose to have fixed the issues regarding awsSrcDstCheck, without success.

## Expected Behavior
Pods should be able to communicate to other pods hosted in a different node or having internet connectivity.

## Possible Solution
We don't have this issue when creating the cluster using eksctl v0.50.0
According to eksctl release note, [version 0.52.0](https://github.com/weaveworks/eksctl/releases/tag/0.52.0-rc.0) no longer add vpc-cni which remove the following policy **AmazonEKS_CNI_Policy** previously attached to nodegroup.
As a result, calico-node is no longer capable of disabling source/destination checks on nodes.

It is possible to activate [vpc-cni](https://eksctl.io/usage/addons/) in eksctl, but it will create a dedicated role associated with aws-node service account.

## Steps to Reproduce (for bugs)
Create an EKS cluster using eksctl > 0.51.0.
Install Calico networking using calico-vxlan manifest (version 3.19.1 to 3.20.0).
Try to make pod communicate to a pod in a different node. 

## Your Environment
* Calico version 3.19.1
* Kubernetes (EKS) version 1.19
* eksctl version 0.63.0

**Comment by lmm** [comment]
Thanks @theophileds, sorry for the late response. Sounds like we will need to update our docs on projectcalico.org and probably on amazon.com and maybe the EKS workshop.

We'll need to add different steps for EKS with Calico CNI installation too.

**Comment by sjtindell** [comment]
So just to confirm, this setting

`kubectl -n kube-system set env daemonset/calico-node FELIX_AWSSRCDSTCHECK=Disable`

no longer works and we should configure it on the AWS Instance side directly?

**Comment by caseydavenport** [comment]
I've just retested this on the latest eksctl - v0.86.0 at the time of writing - and Calico has no trouble configuring source dest checks, so it seems the necessary IAM permissions have been re-added to the nodes and I think this can be closed.
