### ISSUE TITLE
tigera-operator missing RBAC endpointslices

### ISSUE THREAD

**Issue by dropdeadfu** [projectcalico/calico#4932]
Hallo,

I am currently debugging a behavior where windows nodes in an EKS do not properly apply network policies. The desired network policies should reflect a namespace-isolation scenario but whitelisting the namespace the service running on the windows node resides in results in the pod not being able to communicate with any service in that namespace.

During the search I found an issue which may or may not be the cause of this (there are possible multiple causes that cause this behavior in combination). The calico agent on the windows not is flooding the logfile with:
2021-09-14 08:33:41.849 [INFO][6836] felix/kubeendpointslice.go 101: Unable to list K8s EndpointSlice resources error=endpointslices.discovery.k8s.io is forbidden: User "system:serviceaccount:calico-system:calico-node" cannot list resource "endpointslices" in API group "discovery.k8s.io" at the cluster scope
2021-09-14 08:33:41.849 [INFO][6836] felix/watchercache.go 186: Failed to perform list of current data during resync ListRoot="/calico/resources/v3/projectcalico.org/kubernetesendpointslices" error=connection is unauthorized: endpointslices.discovery.k8s.io is forbidden: User "system:serviceaccount:calico-system:calico-node" cannot list resource "endpointslices" in API group "discovery.k8s.io" at the cluster scope
2021-09-14 08:33:42.850 [INFO][6836] felix/watchercache.go 174: Full resync is required ListRoot="/calico/resources/v3/projectcalico.org/kubernetesendpointslices"

To fix this temporarily I added the following to the calico-node RBAC:
- apiGroups:
  - discovery.k8s.io
  resources:
  - endpointslices
  verbs:
  - list
  - watch

This however gets ovewritten by something constantly, my guess is the operator?

I am using calico version 3.20 with the tigera operator but while looking through the repos I found that the manifest (https://docs.projectcalico.org/manifests/tigera-operator.yaml) doesn't contain the policy but the manifest for calico-policy-only does: https://docs.projectcalico.org/manifests/calico-policy-only.yaml

## Expected Behavior
Clarification if this is actually expected behavior or if the operator should also contain the endpointslices policy.

## Current Behavior
tigera-operator supplies RBAC calico-node policy without endpoints-slice permission.

## Possible Solution
Add the endpoint-slice permission to tigera-operator manifests

## Steps to Reproduce (for bugs)

1. EKS cluster with k8s 1.19
2. Add calico with tigera operator but only enable EKS scenario for basically having only policies being managed by calico
3. Add windows node and install calico 3.20
4. Add network policies for namespace isolation (deny-all, allow-self-namespace, allow-ingress, allow-kube-system)

## Context
This issue floods the logfile on the windows node and clearly doesn't seem to be expected behavior even if my underlying issue is not directly caused by this.

## Your Environment
* Calico version 3.20
* Orchestrator version (e.g. kubernetes, mesos, rkt): EKS k8s 1.19
* Operating System and version: linux windows
* Link to your project (optional):

**Comment by tmjd** [comment]
The operator currently bundled with Calico v3.20 is version 1.20.1. Looking at the [source](https://github.com/tigera/operator/blob/v1.20.1/pkg/render/node.go#L252), shows that it includes the same endpoint RBAC for calico-node that you added.
Is there any possibility that you have something else that is modifying that ClusterRole?

If you scale the operator to 0 replicas (disabling it effectively) and make that same update does it persist? I'm suggesting this to make sure there isn't something else modifying that ClusterRole because I don't really have any idea how you would have that ClusterRole with operator v1.20.1 without the endpointslices rule.
Don't forget to scale the operator back to 1 when done testing.

**Comment by dropdeadfu** [comment]
Good idea, gonna try that and let you know what the result is.
And I don't really have an idea either, that is the reason I opened up this issue in the first place :)

**Comment by dropdeadfu** [comment]
Ah, i found something.
At the time of installation (approx 3 month ago) this got used:
https://raw.githubusercontent.com/aws/amazon-vpc-cni-k8s/master/config/master/calico-operator.yaml
It refers to the operator version v1.13.2

**Comment by dropdeadfu** [comment]
I just redeployed the latest version, not everything points to 1.20.1, the policy for the endpointslices exists and no error on the windows agent.

**Comment by caseydavenport** [comment]
Going to close this one - is there an issue specifically tracking the namespace isolation issue?

**Comment by dropdeadfu** [comment]
I am still unsure if kube-proxy or calico is causing the issue, I wanted to be sure before opening and issue.
You can look at the complete stuff I've been through here: https://github.com/kubernetes-sigs/sig-windows-tools/issues/168

**Comment by dropdeadfu** [comment]
It is by the way also basically the same as: https://github.com/projectcalico/calico/issues/4291

**Comment by dropdeadfu** [comment]
fyi, opened the issue for the namespace isolation https://github.com/projectcalico/calico/issues/4936
