### ISSUE TITLE
cleanup calico ippool docs

### ISSUE THREAD

**Issue by jayunit100** [projectcalico/calico#4946]
hi folks, docs issue...

1) https://docs.projectcalico.org/networking/get-started-ip-addresses references an old blog post ...  about the initial ippools introduced in version 3.3 :)  In that blog post, the `crd` values are out of date.

2) https://docs.projectcalico.org/getting-started/kubernetes/hardway/configure-ip-pools suggests using `apiVersion: projectcalico.org/v3` as the CRD for IPPools.  But I think `crd.projectcalico.org/v1 ` is generally what we want to use for ippools.

In general, what's the difference between "projectcalico.org/v3" and "crd.projectcalico.org/v1" ?

**Comment by caseydavenport** [comment]
> But I think crd.projectcalico.org/v1 is generally what we want to use for ippools.

Nope, this is the other way around.

> In general, what's the difference between "projectcalico.org/v3" and "crd.projectcalico.org/v1" ?

This is sadly a vestige from a long time ago `projectcalico.org/v3` is the real, user-facing API that has existed before CustomResourceDefinitions even existed. `crd.projectcalico.org/v1` is an internal representation of Calico's data, which isnt meant to be accessed or modified by end-users.

If you install the Calico API server, you can interact with `projectcalico.org/v3` resources directly using kubectl: https://docs.projectcalico.org/maintenance/install-apiserver

Alternatively, you can use `calicoctl`, which is effectively a client-side implementation of the apiserver, to manage them without that component or if you're talking directly to etcd.

**Comment by caseydavenport** [comment]
Everything in that blog post should still work, however the only difference now is that we'd recommend using `kubectl` via the API server rather than using calicoctl.

**Comment by jayunit100** [comment]
ok should i close this issues then ?
