### ISSUE TITLE
Unable to apply calicoctl patch command in windows node

### ISSUE THREAD

**Issue by vaibhavjpr** [projectcalico/calico#4947]
I am trying to enable metrics reporting for calico in windows nodes.  I am referring the steps mentioned for felix and kube-controllers mentioned in the link [calicoctlpatch](https://docs.projectcalico.org/maintenance/monitor/monitor-component-metrics) The same steps worked fine for linux nodes but its getting failed for windows nodes.

## Expected Behavior
It should patch the calico and enable metrics for felix and kube-controllers.

## Current Behavior
It's getting failed for windows node with error "Invalid JSON document"

<img width="1669" alt="Screenshot 2021-09-20 at 3 47 09 PM" src="https://user-images.githubusercontent.com/13375871/133989472-828a54cf-e9d8-49aa-8a6b-65600e6469c6.png">

## Steps to Reproduce (for bugs)

PS C:\tmp> .\calicoctl.exe patch felixConfiguration default  --patch '{"spec": {"prometheusMetricsEnabled": true}}'
Hit error: permorming strategic merge patch: invalid JSON document
PS C:\tmp> cat .\calico.json
{
        "spec": {
                "prometheusMetricsEnabled": true
        }
}
PS C:\tmp> .\calicoctl.exe patch felixConfiguration default --patch --type=json --config=c:\tmp\calico.json
Failed to create Calico API client: syntax error in c:\tmp\calico.json: failed to parse config as YAML/JSON: error parsing document: field in document is not recognized or is in the wrong location: prometheusMetricsEnabled
PS C:\tmp>

## Your Environment

* Calico version 3.19.0
* Orchestrator version (e.g. kubernetes, mesos, rkt): 1.19
* Operating System and version: Windows server 2019 version 1809 
<img width="455" alt="Screenshot 2021-09-20 at 4 00 57 PM" src="https://user-images.githubusercontent.com/13375871/133988577-5b310f92-293d-4d5b-b170-41bfdab4075e.png">

* Link to your project (optional):

**Comment by lwr20** [comment]
pinging @lmm and @song-jiang

**Comment by lmm** [comment]
@vaibhavjpr what version of calicoctl are you using? If it's not v3.19.x, can you please try using one that matches your calico version from here: https://github.com/projectcalico/calicoctl/releases/tag/v3.19.3

**Comment by hiveliberty** [comment]
I have the same issue with 3.20.0 version.
Cant automate some actions with ansible

```
root@kb1:~# cat .kube/calico_configs/default-kubecontrollersconfiguration.json
{"spec": {"controllers": {"node": {"hostEndpoint": {"autoCreate": "Disabled"}}}}}
root@kb1:~# calicoctl patch kubecontrollersconfiguration default --patch='$(cat .kube/calico_configs/default-kubecontrollersconfiguration.json)'
Hit error: permorming strategic merge patch: invalid JSON document
root@kb1:~# CALICOTEST=$(cat .kube/calico_configs/default-kubecontrollersconfiguration.json)
root@kb1:~# echo $CALICOTEST
{"spec": {"controllers": {"node": {"hostEndpoint": {"autoCreate": "Disabled"}}}}}
root@kb1:~# calicoctl patch kubecontrollersconfiguration default --patch='$CALICOTEST'
Hit error: permorming strategic merge patch: invalid JSON document
root@kb1:~# calicoctl patch kubecontrollersconfiguration default --patch='{"spec": {"controllers": {"node": {"hostEndpoint": {"autoCreate": "Disabled"}}}}}'
Successfully patched 1 'KubeControllersConfiguration' resource
```

Also same result with `--config=.kube/calico_configs/default-kubecontrollersconfiguration.json`

**Comment by lmm** [comment]
@hiveliberty I think it's because you're using single quotes and so your shell isn't interpolating the command substitution (`$(cat ... )`)

Same with your environment variable example, just change ` --patch='$CALICOTEST'` to ` --patch="$CALICOTEST"`

**Comment by hiveliberty** [comment]
@lmm
Yeah, the problem is in single quotes. With double quotes works fine. Lol, I missed this point..
But i found best solution - kubernetes module for ansible. I think, for infrastructute as code this looks better.
