### ISSUE TITLE
On node restart UDP egress traffic from some pods fails to reach destination

### ISSUE THREAD

**Issue by VivekThrivikraman-est** [projectcalico/calico#4955]
UDP egress traffic from few pods in the cluster seems to get blackholed after worker node is restarted. Clearing the conntrack entries for these pods makes the traffic flow out. It seems like the natoutgoing iptable rules could have been programmed after pods were up, and since udp traffic was continuously sent out from pods(as soon as it is up) the conntrack entries kept refreshing and stale entries remained even after the natoutgoing iptable rules were programmed. 

## Expected Behavior

UDP egress traffic should flow successfully even after a node restart without any intervention. 

## Current Behavior

UDP egress traffic from pods are blackholed after node restart.

## Possible Solution

Iptable should have been programmed before pods are up(if current assumption of root cause is correct) or stale conntrack entries should be removed programmatically.

## Steps to Reproduce (for bugs)

1. Start a POD acting as a UDP client sending egress traffic continuously in short intervals(make sure natOutgoing is true).
2. Restart the node having the pod.
3. After restart some times the traffic doesn't reach the destination.

## Your Environment

* Calico version: Calico v3.19.1
* Orchestrator version (e.g. kubernetes, mesos, rkt): Kubernetes 1.21.1
* Operating System and version: SUSE Linux Enterprise Server 15 SP2
* Link to your project (optional):

**Comment by caseydavenport** [comment]
Summary of discussion from slack:

- There's a gap in node reboot where pods might be launched prior to calico/node becoming ready and programming its rules.
- To close this hole, we probably need to make the CNI plugin felix aware (so it can block until felix is ready)
- Would recommend draining nodes before rebooting them, in general
- in v3.20, this is helped by marking of nodes as unschedulable during calico/node termination. Combined with drain, this likely closes the hole as well. 

Other thoughts:
- I wonder if we'd see this when switching from natOutgoing: false to true?

**Comment by caseydavenport** [comment]
calico/node's readiness is tied to felix's readiness (as well as some other factors) so using that as our gate would be a superset of this particular issue, and also handle other potential problems like BGP not being converged, etc.

**Comment by fasaxc** [comment]
Sounds like a reasonable idea; could poll the health endpoint for X seconds too to avoid spamming errors if calico/node is just a few seconds from starting up. Only issue I can think of is that the health endpoint may be bound to a particular IP rather than 127.0.0.1 so I guess the CNI plugin would need to know how calico/node was configured.

**Comment by caseydavenport** [comment]
Thanks guys. I'm thinking we'll want the CNI plugin to have a small internal retry loop for sure to avoid spamming errors.

The main questions remaining are:
- How is this configured / enabled / disabled
- How does the CNI plugin learn which endpoints/ports to hit (BGP and Felix both have status endpoints, and they aren't always on)
