### ISSUE TITLE
Support for multiple host interfaces and traffic segregation

### ISSUE THREAD

**Issue by lsoica** [projectcalico/calico#4957]
Hi,

I am trying to setup two k8s clusters attached on two different networks. One for intra-cluster communication and another one for inter-cluster communication and for accessing the pods from the outside world. Each cluster node has one interface attached on each network.

I only have one IP address available per node per network so I assume the only option I have for making services externally accessible is through NodePort, like in this diagram:

![image](https://user-images.githubusercontent.com/1623282/134465183-0d5ab09b-9b0d-4d6f-a69b-2b710b747b38.png)

Is this something I can achieve with calico?

Thanks!

**Comment by caseydavenport** [comment]
@lsoica If I understand correctly, this is effectively how Kubernetes networking works, so yes.

Calico will create a network - generally VXLAN, IPIP, or routed using BGP - which allows pods to talk to each other. In order for external entities to talk to pods on the cluster, they must be exposed through a Service - e.g., LoadBalancer / NodePort, often fronting a k8s Ingress.

**Comment by lsoica** [comment]
@caseydavenport thanks for your response. To make sure I understand your explanation, as soon as the external entity hits one of the cluster nodes, the traffic is routed to the specific pod/service on the intra-cluster network and not on the inter-cluster one, right ? If that's true, what I want is to rely on the inter-cluster one E2E, from the external entity to the actual pod. As I wrote in the initial description, but it's not that clear from the diagram, I have one interface attached on each network for each cluster node.

**Comment by caseydavenport** [comment]
> If that's true, what I want is to rely on the inter-cluster one E2E, from the external entity to the actual pod

I think what you are looking for is `externalTrafficPolicy` - https://kubernetes.io/docs/concepts/services-networking/service/#external-traffic-policy
