### ISSUE TITLE
when trying to create route reflectors i get error message 

### ISSUE THREAD

**Issue by nir-lal** [projectcalico/calico#4963]
i am trying to configure route reflectors from nodes and i get an error message.
this is the config that i am trying to apply:

cat <<EOF | calicoctl apply -f -
---
apiVersion: projectcalico.org/v3
kind: BGPPeer
metadata:
  name: peer-with-rr
spec:
  nodeSelector: all()
  peerSelector: route-reflector == 'true'
EOF

and this is the error message:
Failed to apply 'BGPPeer' resource: [BGPPeer.crd.projectcalico.org "peer-with-rr" is invalid: [spec.asNumber: Required value, spec.peerIP: Required value]]
command terminated with exit code 1

we are using Rancher as the orchestrator. the same configuration is working perfectly in kubeadm environment with kubernetes version 1.20.5 and calico version 3.18.1.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

i am using Rancher with kubernetes version 1.19.6.
calico version is 3.16.5

> calicoctl version
Client Version:    v3.19.1
Git commit:        6fc0db96
Cluster Version:   v3.16.5
Cluster Type:      k8s,bgp,rancher,kdd

this route reflector configuration should be supported from at least calico version 3.15

* Calico version
* Orchestrator version (e.g. kubernetes, mesos, rkt):
* Operating System and version:
* Link to your project (optional):

**Comment by caseydavenport** [comment]
@nir-lal thanks for the issue. What version of calicoctl are you using for this cluster?

**Comment by nir-lal** [comment]
@caseydavenport the calicoctl version is 3.19.1.
however, we upgraded the Rancher version and it solved the case.
thank
