### ISSUE TITLE
May I release empty calico blocks manually ?

### ISSUE THREAD

**Issue by nyanpassu** [projectcalico/calico#4975]
May I release empty calico blocks by using code from calico-go lib?

## Expected Behavior
We are facing blocks exhaust on some of our subnet, and we found that nearly 1/5 blocks are empty and not released(they have affinity and their nodes are selected by pool), we want to release those blocks so other node can claim them.

## Current Behavior
Empty blocks are not released when all available blocks are claimed by hosts. 

## Possible Solution
I'm trying to release these blocks by IPAM::ReleaseAffinity, will this has other side effect on the network?

## Context
I'm using calico-go to serve as a docker network plugin to provide SDN for our container, but now we are facing blocks exhaust problem

## Your Environment
* Calico version 3.9
* Orchestrator version : our own orchestrator

**Comment by caseydavenport** [comment]
@nyanpassu You will probably need to release them by hand, yes. In Calico v3.20 we introduced automatic cleanup of empty blocks, however this is specific to Kubernetes so likely won't work for your own orchestrator. 

> I'm trying to release these blocks by IPAM::ReleaseAffinity, will this has other side effect on the network?

ReleaseAffinity should be safe to run, especially if the block is empty. You can pass the "require empty" argument (added in later versions) to ensure that the block is empty on release.
