### ISSUE TITLE
Pods running on Windows worker nodes in K8s have no network connectivity

### ISSUE THREAD

**Issue by wtfacoconut** [projectcalico/calico#4978]
Hello, I'm raising an issue that's similar to (if no the same as) issue #4682  . 

## Expected Behavior
Expect that pod to Pod network connectivity should work
Expect that pod to Service connectivity should work
Expect that pod to WAN (internet) connectivity should work
Expect that pod to LAN (local intranet) connectivity should work

## Current Behavior
Almost no network connectivity. I can access the node port service of a pod though if I use the IP address of the host where the pods is running on.

Also I have been able to finally start resolving internet facing domains provided I open a shell in to the pod to manually specify a secondary DNS server (like 8.8.8.8).

## Possible Solution
Unknown.

## Steps to Reproduce (for bugs)
In case it helps, these were the commands I ran to get a windows worker up and running with calico. Everything below was run from an admin powershell prompt:
```
mkdir C:\k\
# I then transferred a copy of my kube config file to c:\k\
Invoke-WebRequest https://docs.projectcalico.org/scripts/install-calico-windows.ps1 -OutFile C:\install-calico-windows.ps1
C:\install-calico-windows.ps1 -DownloadOnly yes -KubeVersion 1.19.3
C:\CalicoWindows\install-calico.ps1
C:\CalicoWindows\kubernetes\install-kube-services.ps1
Start-Service kubelet
Start-Service kube-proxy
```
After doing so, my windows pods are experiencing the same issues as described in #4682  .

## Context
N/A.

## Your Environment

* Calico version
* Orchestrator version (e.g. kubernetes, mesos, rkt):
* Operating System and version:
* Link to your project (optional):

Below is my version information:
- Kubernetes = v1.22.2
- Calico cluster & client = v3.19.1
- microK8s = v2.1.0
- Windows worker node version: Windows Server 2019 [Version: 1809] (OS Build: 17763.1577)

**Comment by mgleung** [comment]
@wtfacoconut I'm going to close this in favor of #4682 since I see you've also commented there and it might be easier to keep all the related info together. If there are other details that might differ from #4682 then please let us know and we can reopen this issue.
