### ISSUE TITLE
Better explain "Policy Only Mode"

### ISSUE THREAD

**Issue by ozdanborne** [projectcalico/calico#500]
[Documentation for using k8s-backend](http://docs.projectcalico.org/v2.0/getting-started/kubernetes/installation/hosted/k8s-backend/) is pretty sparse for details on what policy-only mode is. Could use a better introduction to the concept, possibly as a separate doc.

**Comment by djosborne** [comment]
As mentioned in #565, we should also explain why IP Autodetection is irrelevant when using k8s backend.

**Comment by caseydavenport** [comment]
We need a high level "policy only" mode document that explains what it is, why you use it.  Then go into details on how to configure it, and its limitations
The KDD docs can then reference that doc in the right places.

I think this is quite important.

**Comment by lwr20** [comment]
Given that this covers part of an issue which was a v2.1.0 thing, should this not also be a v2.1.0 thing?

**Comment by caseydavenport** [comment]
Very WIP: https://github.com/projectcalico/calico/compare/master...caseydavenport:more-cloud-providers#diff-86ca2b9b8a26bd58b00be5ff5db78642

**Comment by caseydavenport** [comment]
> We need a high level "policy only" mode document that explains what it is, why you use it.

The above link doesn't really include this part (just a tiny bit of intro at the top).

Throughout our docs, we should be talking about Calico in terms of two pieces:
- Networking
- Policy

At the moment, we often intertwine how we talk about them, which makes it a bit more difficult to explain some of this stuff to new users.

**Comment by caseydavenport** [comment]
We've got some information on this now: https://docs.projectcalico.org/v3.3/getting-started/kubernetes/installation/other

It's not perfect, but I think we can call this closed, and we can address any issues as separate tickets.
