### ISSUE TITLE
Ipam pod IP not released

### ISSUE THREAD

**Issue by guillaumefenollar** [projectcalico/calico#5004]
On our cluster, some nodes are rapidly out of free IP to assign, limit of number of assigned ipamblocks is reached. This cluster is having ~1200 total pods (350 active ones, others are completed jobs).

## Expected Behavior
Jobs and normal pods should be started with new IP each time. Each node on the cluster should have around 50~60 IP allocated at any moment.

## Current Behavior
One node (not the one where every job's pod starts, the cluster is rather evenly balanced), the 4th node in below example, is not releasing IPs. Here the report created by `calicoctl ipam check` command :
```
Datastore locked.
Checking IPAM for inconsistencies...

Loading all IPAM blocks...
Found 33 IPAM blocks.
 IPAM block 192.168.32.0/26 affinity=host:srv-k8s-qual-3:
 IPAM block 192.168.32.64/26 affinity=host:srv-k8s-qual-3:
 IPAM block 192.168.33.0/26 affinity=host:srv-k8s-qual-1:
 IPAM block 192.168.34.0/26 affinity=host:srv-k8s-qual-2:
 IPAM block 192.168.34.64/26 affinity=host:srv-k8s-qual-2:
 IPAM block 192.168.36.0/26 affinity=host:srv-k8s-qual-1:
 IPAM block 192.168.36.128/26 affinity=host:srv-k8s-qual-1:
 IPAM block 192.168.36.192/26 affinity=host:srv-k8s-qual-1:
 IPAM block 192.168.36.64/26 affinity=host:srv-k8s-qual-1:
 IPAM block 192.168.38.64/26 affinity=host:srv-k8s-qual-2:
 IPAM block 192.168.39.128/26 affinity=host:srv-k8s-qual-4:
 IPAM block 192.168.39.192/26 affinity=host:srv-k8s-qual-4:
 IPAM block 192.168.39.64/26 affinity=host:srv-k8s-qual-4:
 IPAM block 192.168.40.0/26 affinity=host:srv-k8s-qual-4:
 IPAM block 192.168.40.128/26 affinity=host:srv-k8s-qual-4:
 IPAM block 192.168.40.192/26 affinity=host:srv-k8s-qual-4:
 IPAM block 192.168.40.64/26 affinity=host:srv-k8s-qual-4:
 IPAM block 192.168.41.0/26 affinity=host:srv-k8s-qual-4:
 IPAM block 192.168.41.128/26 affinity=host:srv-k8s-qual-4:
 IPAM block 192.168.41.192/26 affinity=host:srv-k8s-qual-4:
 IPAM block 192.168.41.64/26 affinity=host:srv-k8s-qual-4:
 IPAM block 192.168.42.0/26 affinity=host:srv-k8s-qual-4:
 IPAM block 192.168.42.128/26 affinity=host:srv-k8s-qual-4:
 IPAM block 192.168.42.192/26 affinity=host:srv-k8s-qual-4:
 IPAM block 192.168.42.64/26 affinity=host:srv-k8s-qual-4:
 IPAM block 192.168.43.0/26 affinity=host:srv-k8s-qual-4:
 IPAM block 192.168.43.128/26 affinity=host:srv-k8s-qual-3:
 IPAM block 192.168.43.192/26 affinity=host:srv-k8s-qual-3:
 IPAM block 192.168.43.64/26 affinity=host:srv-k8s-qual-4:
 IPAM block 192.168.44.0/26 affinity=host:srv-k8s-qual-3:
 IPAM block 192.168.44.128/26 affinity=host:srv-k8s-qual-4:
 IPAM block 192.168.44.192/26 affinity=host:srv-k8s-qual-4:
 IPAM block 192.168.44.64/26 affinity=host:srv-k8s-qual-4:
IPAM blocks record 1442 allocations.

Loading all IPAM pools...
  192.168.32.0/20
Found 1 active IP pools.

Loading all nodes.
Found 4 node tunnel IPs.

Loading all workload endpoints.
Found 223 workload IPs.
Workloads and nodes are using 227 IPs.

Looking for top (up to 20) nodes by allocations...
  srv-k8s-qual-4 has 1280 allocations
  srv-k8s-qual-3 has 59 allocations
  srv-k8s-qual-1 has 55 allocations
  srv-k8s-qual-2 has 48 allocations
Node with most allocations has 1280; median is 55

Scanning for IPs that are allocated but not actually in use...
Found 1215 IPs that are allocated in IPAM but not actually in use.
Scanning for IPs that are in use by a workload or node but not allocated in IPAM...
Found 0 in-use IPs that are not in active IP pools.
Found 0 in-use IPs that are in active IP pools but have no corresponding IPAM allocation.
```
We have to release manually the IPs in order to allow pods to be started on that node. Without that manual step, node can't schedule any pod anymore in a matter of hours. The k8s scheduler will continue scheduling pods on that machine, pods that will stay in ContainerCreating because no IP could be allocated, so those jobs are stuck indefinitely without human action.

To manually release the ipam as a workaround, we use the `calicoctl ipam release` command, after locking the datastore: 
```
Check complete; found 1215 problems.
Releasing 1215 old IPs
Released 1215 IPs successfully
You may now unlock the data store.
Datastore unlocked.
```

## Steps to Reproduce (for bugs)
I'm not sure how to reproduce this bug. We have 3 clusters in the same infrastructure, and this is the only one with that behavior.
I can't see any error in calico-node nor calico-kube-controller's logs, nothing suspicious.

## My Environment
* Calico version : 3.19.3
* Orchestrator version : Kubernetes vanilla 1.19.8. (This cluster is almost 4 years old, not sure what was the first calico version, but calico was used since the begining)
* Operating System and version: Linux 5.10.21

Calico configuration : 
* Datastore type : kubernetes
* cni version : 0.3.1
* ipam type : calico-ipam
* IpinIp : Never
* VXLan : Never
* IPv6Support : false

**Comment by caseydavenport** [comment]
Well, unfortunately there's nothing in those logs that suggests an error is occurring. Might just not have been captured, but it's hard to tell.

> It seems that sometimes, the count of problematic IPs (unreleased) goes up when no new pod is scheduled

This seems to suggest that the CNI plugin is trying to allocate IPs for start the pod, but the container runtime thinks that the pod has failed and so tries to restart it. Calico relies on the container runtime to inform us when we need to release an IP address, so it is possible that this is a result of a bug in the container runtime you're using. I have seen this behavior before in several different runtimes. What container runtime are you using? CRI-O / containerd / something else?

**Comment by guillaumefenollar** [comment]
I'm using containerd 1.4.6.
I just upgraded it to 1.4.11 and after a couple of hours, there's no unreleased IP anymore reported by `calicoctl ipam check` ! Let's wait for a little more but it looks promising

**Comment by guillaumefenollar** [comment]
Problem seems to be fixed. I upgraded kubelet and containerd (+ ctr + crictl),but I guess only containerd had a role in this as you said. I haven't found in the release notes what can be related to my problem, but I'm glad it's fixed now :)
Thanks for your help @caseydavenport !
