### ISSUE TITLE
Manifests directory is 2 years old :)

### ISSUE THREAD

**Issue by jayunit100** [projectcalico/calico#5006]
# Expected behaviour

modulo `ocp`... We probably should add notes to the manifests/ directory to clarify that they're not published anymore ?  or maybe just delete if from head.

**Comment by tmjd** [comment]
Are you judging by the fact that some of the files in the repo under manifests/ocp haven't changed in the last 2 years?
Those files are linked to other files that do get updated and when the docs are published, those file are being generated with updated content.
If I'm misunderstanding please clarify what files you believe aren't being updated.
