### ISSUE TITLE
Can calico use iptables mangle table?

### ISSUE THREAD

**Issue by my1990** [projectcalico/calico#5015]
Can calico use iptables mangle table? If used, which function will it be used in?

Because we have a security control software that needs to modify the mangle table, I wonder if it will cause problems to calico?

**Comment by caseydavenport** [comment]
Calico will use the mangle table for policy that uses preDNAT. 

If you don't use preDNAT, then maybe all will be OK, but it really depends on what your security software does. I'd recommend trying it out and see if it meets your needs. 

Often times, Calico can be used to implement the same rules you might be trying to implement in another firewalling tool, so I'd also recommend seeing if that would be possible. Using a single solution simplifies this a lot.
