### ISSUE TITLE
canal-etcd.yaml linked in docs uses removed config key __KUBECONFIG_FILENAME__

### ISSUE THREAD

**Issue by markus1978** [projectcalico/calico#5029]
## Expected Behavior
The [Install Calico for policy and flannel (aka Canal) for networking](https://docs.projectcalico.org/getting-started/kubernetes/flannel/flannel#installing-with-the-etcd-datastore) documentation asks you to download
https://docs.projectcalico.org/manifests/canal-etcd.yaml and apply it to your cluster with kubectl. 

This should install necessary `calico-kube-controller` and `canal-node`  replica/daemon sets. The pods should be able to run. 

## Current Behavior
Everything gets installed in the cluster, but the mentioned pods crash or the readiness/liveness probes fail.

## Possible Solution
The `cni_network_config` template defined in https://docs.projectcalico.org/manifests/canal-etcd.yaml lines 55 ff. uses the removed config key `__KUBECONFIG_FILENAME__`. See also #4024.

If I replace `"/etc/cni/net.d/__KUBECONFIG_FILENAME__"` with `"__KUBECONFIG_FILEPATH__"`, everything works as expected.

I am sorry that the information isn't more detailed. I was doing this a couple days ago; don't have the details anymore; and just wanted to post this and the solution to you. Should be a very straightforward affair.

**Comment by caseydavenport** [comment]
Thanks for the heads up! I've raised a PR to fix.
