### ISSUE TITLE
Can Flannel to Calico migration can happen on single node cluster (On prem)?

### ISSUE THREAD

**Issue by codelang1** [projectcalico/calico#5045]
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Calico version
* Orchestrator version (e.g. kubernetes, mesos, rkt):
* Operating System and version:
* Link to your project (optional):

**Comment by caseydavenport** [comment]
I don't see why it can't. That said, flannel isn't doing much on a single node cluster because there is no cross-node communication which is really what flannel is meant to provide. I suppose it still provides outgoing NAT, but that's likely it.
