### ISSUE TITLE
Pod loopback connection via service does not work for certain application in eBPF mode

### ISSUE THREAD

**Issue by vrf888** [projectcalico/calico#5060]
I’m trying eBPF mode on AWS EKS. In this mode i experience weird networking issue: 
.NET 5 application can not connect to itself (from that pod) via service IP (172.20.x.x), but can connect via pod IP (192.168.x.x). What adds to confusion is that i can connect that way with utils like curl, nc or telnet from that pod, also application can connect to other services IPs, also that issue does not occur in non eBPF mode.

## Expected Behavior
Connection shouldn't timeout while connecting application running on the same pod via service IP.

## Current Behavior
Getting connection timeout while connecting application running on the same pod via service IP.

## Possible Solution
On Calico slack was suggested that issue is with connect time load balancer.
"Sounds like the connect time load balancer is not firing for the .NET application.  It must use some unusual pattern of socket operations to set up its socket.  We rely on the connect time load balancer for loop back to the same pod to work."

## Steps to Reproduce (for bugs)

1. Run .NET 5 application listening on HTTP in Alpine Linux pod/deployment.
primary-proxy-api-6df5f77599-97mz8                                1/1     Running     0          45h   192.168.198.4    ip-10-31-82-143.ec2.internal    <none>           <none>

2. Create ClusterIP service for that deployment 
primary-proxy-api                                    ClusterIP   172.20.30.116    <none>        80/TCP     45h

3. Use standard HttpClient class (https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httpclient?view=net-5.0)

4. Try to GET it's own service local URL (http://primary-proxy-api or it's address http://172.20.30.116 )

Also i’ve been able to reproduce the same behavior with nmap: it works fine with Connect method (-sT), but times out with all other methods (like -sS) which use raw sockets.

## Your Environment
* Calico version was running on 3.16.x, now running on 3.20.2
* AWS EKS 1.18
* Container OS: Alpine Linux 3.11.6
* Node OS: Ubuntu 20.04
* .NET 5 SDK 5.0.300

**Comment by tomastigera** [comment]
Based on the discussion [here](https://calicousers.slack.com/archives/CUKP5S64R/p1636069341035800) it is likely a bypass of the connect time load balancer without a proper turn around of the packets back. Pod usually reject packets with their own source IP unless `accept_local` is set. However, that would not be enough as the NATing is done outside and of the pod and response packets would not hit it.
