### ISSUE TITLE
Unable to update default BGP configuration with serviceLoadBalancerIPs CIDR

### ISSUE THREAD

**Issue by TheFutonEng** [projectcalico/calico#5063]
## Expected Behavior
BGPconfiguration spec is successfully updated with a CIDR for serviceLoadBalancerIPs

## Current Behavior
Attempting to patch the current BGPconfiguration results in an error:

```
$ calicoctl patch BGPConfig default --patch '{"spec": {"serviceLoadBalancerIPs": [{"cidr": "198.18.0.0/15"}]}}'
Hit error: creating resource from patched data: error parsing document: field in document is not recognized or is in the wrong location: serviceLoadBalancerIPs
command terminated with exit code 1
```

## Possible Solution
Based on the [Calico BGP Configuration documentation](https://docs.projectcalico.org/reference/resources/bgpconfig#spec), serviceLoadBalancerIPs is part of the configuration spec so the location seems to be correct.  Not sure if a more recent version of Calico is required but 3.17.2 was released in 2/21.

## Steps to Reproduce (for bugs)

1. Deploy a K8s cluster running 1.20.4 using Calico as the CNI
2. Deploy a calicoctl container in the cluster to interact with calico
3. Deploy/Update a BGP configuration whereby the serviceLoadBalancerIPs parameter is set

## Context
I am attempting to follow [this Calico article](https://docs.projectcalico.org/networking/advertise-service-ips) to advertise service load balancer addresses to the underlay network.  Attempting to execute this in a lab so it is not production impacting.  

## Your Environment
* Calico version: 3.17.2
* Orchestrator version (e.g. kubernetes, mesos, rkt): K8s 1.20.4
* Operating System and version: CentOS 7.9.2009

**Comment by caseydavenport** [comment]
Hmm. Looks like we might have a bug in `calicoctl patch`. There are some other issues similar to this as well:

- https://github.com/projectcalico/calico/issues/4724
- https://github.com/projectcalico/calico/issues/4947

**Comment by caseydavenport** [comment]
>Deploy a calicoctl container in the cluster to interact with calico

One thought - have you tried this using calicoctl installed locally? Running as a container within the cluster has some quirks - especially around passing input.

**Comment by TheFutonEng** [comment]
@caseydavenport, I have not tried via a local calicoctl install but I have tried applying a BGP configuration with serviceLoadBalancerIPs in the spec of the BGPConfiguration object and received a similar error:

```
$ calicoctl apply -f - < bgpconfiguration.yaml 
Failed to execute command: error parsing document: field in document is not recognized or is in the wrong location: serviceLoadBalancerIPs
command terminated with exit code 1
```
Would this still point towards a calicoctl bug?  Is it still worth trying via a local install?

**Comment by TheFutonEng** [comment]
@caseydavenport , apologies for the delay.  I got around to testing with a local calicoctl and the results are the same:

```
$ ./calicoctl apply -f ../bgpconfiguration.yaml 
Failed to execute command: error parsing document: field in document is not recognized or is in the wrong location: serviceLoadBalancerIPs
```

Just to be sure is wasn't an issue with the 'apply,' I deleted the BGP configuration object and attempted to create the object fresh, same error:

```
$ ./calicoctl delete -f ../bgpconfiguration.yaml 
Successfully deleted 1 'BGPConfiguration' resource(s)

# Updated bgpconfiguration.yaml to enable {spec.serviceLoadBalancerIPs}

$ ./calicoctl create -f ../bgpconfiguration.yaml 
Failed to execute command: error parsing document: field in document is not recognized or is in the wrong location: serviceLoadBalancerIPs
```

**Comment by caseydavenport** [comment]
@TheFutonEng What version of calicoctl are you using? e.g., `calicoctl version`

**Comment by TheFutonEng** [comment]
@caseydavenport , 3.17.2 for both the instance in the container and the local one.

Container:
```
$ which calicoctl 
alias calicoctl='kubectl exec -i -n kube-system calicoctl -- /calicoctl'
	/usr/local/bin/kubectl
$ calicoctl version
Client Version:    v3.17.2
Git commit:        5eb50600
Cluster Version:   v3.17.2
Cluster Type:      k8s,bgp,rancher,kdd
```

Local:
```
$ ./calicoctl version
Client Version:    v3.17.2
Git commit:        5eb50600
Cluster Version:   v3.17.2
Cluster Type:      k8s,bgp,rancher,kdd
```

**Comment by caseydavenport** [comment]
@TheFutonEng The feature you're trying to use wasn't added until Calico v3.18.0: https://docs.projectcalico.org/archive/v3.18/release-notes/#v3180

So, you need to upgrade before you can advertise LB IPs.

**Comment by TheFutonEng** [comment]
@caseydavenport, I obviously need to improve my google-fu!  I appreciate your assistance, I will upgrade to 3.18.0.
