### ISSUE TITLE
Flannel to Calico migration on a single node cluster is not happening

### ISSUE THREAD

**Issue by codelang1** [projectcalico/calico#5074]
## Expected Behavior
Flannel network should be replaced with Calico

## Current Behavior
Flannel pod is removed
Flannel to Calico migration controller is stuck in pending state
Calico network is not installed

## Possible Solution
Not known yet

## Steps to Reproduce (for bugs)
1. Bought up a single node cluster with kubeadm on ubuntu 18.0.
2. Then deployed flannel : kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml
3. Then removed taint to deploy two nginx pods: kubectl taint nodes --all node-role.kubernetes.io/master-

Everything fine until now.

4. Now I tried to migrate from flannel to calico using : 
helm install cnf ./flannel-to-calico.tgz --set flannelToCalicoMgr=true
https://docs.projectcalico.org/getting-started/kubernetes/flannel/migration-from-flannel
helm chart flannel-to-calico.zip is attached.

5. migration controller is in pending state.
root@qa-cl-26:~# **kubectl get pods -A**
NAMESPACE        NAME                                       READY   STATUS    RESTARTS   AGE
kube-system      calico-kube-controllers-75f8f6cc59-7kz7l   0/1     Pending   0          9m47s
kube-system      coredns-78fcd69978-9j7pj                   0/1     Pending   0          9m47s
kube-system      coredns-78fcd69978-vh8ph                   0/1     Pending   0          9m47s
kube-system      etcd-qa-cl-26                              1/1     Running   0          93m
kube-system      flannel-migration--1-6c2jt                 0/1     Pending   0          9m47s
kube-system      kube-apiserver-qa-cl-26                    1/1     Running   0          93m
kube-system      kube-controller-manager-qa-cl-26           1/1     Running   0          93m
kube-system      kube-proxy-q857m                           1/1     Running   0          93m
kube-system      kube-scheduler-qa-cl-26                    1/1     Running   0          93m
server-space-1   nginx-deploy-1-65999cc47f-m4lgj            0/1     Pending   0          9m47s
server-space-2   nginx-deploy-2-6b56559d58-b8j2j            0/1     Pending   0          9m47s

root@qa-cl-26:~# **kubectl describe pod flannel-migration--1-6c2jt -n kube-system** 
Name:                 flannel-migration--1-6c2jt
Namespace:            kube-system
Priority:             2000000000
Priority Class Name:  system-cluster-critical
Node:                 <none>
Labels:               controller-uid=32ecb890-dfa7-4558-b014-cdec25621f7a
                      job-name=flannel-migration
                      k8s-app=flannel-migration-controller
Annotations:          <none>
Status:               Pending
IP:                   
IPs:                  <none>
Controlled By:        Job/flannel-migration
Containers:
  flannel-migration-controller:
    Image:      calico/flannel-migration-controller:v3.20.2
    Port:       <none>
    Host Port:  <none>
    Readiness:  exec [/usr/bin/check-status -r] delay=0s timeout=1s period=10s #success=1 #failure=3
    Environment:
      ENABLED_CONTROLLERS:        flannelmigration
      DATASTORE_TYPE:             kubernetes
      FLANNEL_DAEMONSET_NAME:     kube-flannel-ds
      FLANNEL_SUBNET_LEN:         24
      FLANNEL_ANNOTATION_PREFIX:  flannel.alpha.coreos.com
      FLANNEL_VNI:                1
      FLANNEL_PORT:               8472
      CALICO_DAEMONSET_NAME:      calico-node
      CNI_CONFIG_DIR:             /etc/cni/net.d
      FLANNEL_SUBNET_ENV:         <set to the key 'flannel_subnet_env' of config map 'flannel-migration-config'>  Optional: false
      POD_NODE_NAME:               (v1:spec.nodeName)
    Mounts:
      /host/run/flannel/subnet.env from flannel-env-file (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-ns244 (ro)
Conditions:
  Type           Status
  PodScheduled   False 
Volumes:
  flannel-env-file:
    Type:          HostPath (bare host directory volume)
    Path:          /run/flannel/subnet.env
    HostPathType:  
  kube-api-access-ns244:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   BestEffort
Node-Selectors:              kubernetes.io/os=linux
Tolerations:                 CriticalAddonsOnly op=Exists
                             node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason            Age                  From               Message
  ----     ------            ----                 ----               -------
  Warning  FailedScheduling  56s (x9 over 9m30s)  default-scheduler  0/1 nodes are available: 1 node(s) were unschedulable.
## Context
The same helm chart is working for 3 node cluster, migration from flannel to calico is happening successfully. 
No changes made to the manifests provided by Calico, only encapsulated them to create a helm chart.
[flannel-to-calico.zip](https://github.com/projectcalico/calico/files/7502203/flannel-to-calico.zip)

## Your Environment

* Calico version
* Orchestrator version (e.g. kubernetes, mesos, rkt):
* Operating System and version:
* Link to your project (optional):

**Comment by caseydavenport** [comment]
@song-jiang sounds like perhaps the flannel migration controller is marking the node as unschedualble, and then not toleration that itself so it gets booted and can't start back up? Do you know if this is expected to work on a 1 node cluster?

**Comment by song-jiang** [comment]
@caseydavenport @codelang1 Flannel migration controller would need to run on a node which is not currently migrating. It won't work on a single node cluster.

**Comment by caseydavenport** [comment]
@codelang1 one thing you might be able to try is to launch a second node for the duration of the upgrade, and then scale back down to 1. However, for a single node, you might just want to repave the cluster anyway. Would be a fair bit simpler.

**Comment by codelang1** [comment]
Looks like Flannel to Calico migration on single node is not possible.
Closing the issue.
