### ISSUE TITLE
Helm repo is missing latest versions

### ISSUE THREAD

**Issue by tim-ings-vgw** [projectcalico/calico#5082]
It seems that the projectcalico helm repo is not automatically updated with the latest version by the release scripts.

Missing versions include:
- v3.20.1
- v3.20.2
- v3.21.0 (since manually fixed, thanks @lwr20)

## Expected Behavior
Helm repo is updated with new version on release

## Current Behavior
Helm repo does not get updated with the new version

## Steps to Reproduce (for bugs)
1. Attempt to helm install the latest version soon after it has been released

## Context
Attempting to upgrade tigera-operator from `v3.20.0` to `v3.21.0` from the `https://docs.projectcalico.org/charts` repository
Slack thread with additional discussion https://calicousers.slack.com/archives/CPTH1KS00/p1636602953098000

## Your Environment
* Helm version: v3.6.2
* Calico version: v3.20.0, v3.21.0
* Orchestrator version (e.g. kubernetes, mesos, rkt): v1.19.7, running locally under kind
* Operating System and version: macOS 11.3.1

**Comment by lwr20** [comment]
Note to self: 
I think these lines of Makefile must be broken:
https://github.com/projectcalico/calico/blob/master/Makefile#L384-L392

**Comment by caseydavenport** [comment]
Yeah, we need to fix those lines. I think they've hit a couple issues over the last few releases. I tried to fix manually this time around but guess I did it wrong somehow :crying_cat_face:

**Comment by lwr20** [comment]
Fixed by https://github.com/projectcalico/calico/pull/5134 (I think)
