### ISSUE TITLE
Expand the inbound external connectivity documentation

### ISSUE THREAD

**Issue by tmjd** [projectcalico/calico#509]
The docs section talking about accessing containers from outside of the calico managed nodes is pretty high level and it would be nice to document some of the other options available and have an example or 2.

Here are some of the options that have came up for inbound external connectivity:
* Configuring calico to peer with the networking fabric so that the other hosts' L3 hop already knows how to route to the containers. This is philiosphically the "best" solution but not always one people can implement if they're not running in private cloud and realistically not unless they're building production infrastructure.
* Run a virtual bgp service on the host directly (such as BIRD). The cheating way to do this is just run calico/node on that host too, even if it's not going to run containers.
* Set up a loadbalancer / proxy service to forward requests to the Calico IP. This is often orchestrator dependent. For Mesos, use Marathon-LoadBalancer. For Kubernetes, there's service ports that can be used
* BGP peer to the next router up, and ensure that the non-Calico host's route to the calico IPs goes via that router.
* Enable proxy arp on the eth0 interfaces of the compute hosts, so they will claim that the Calico pods are directly on the network, and use IPs for the Calico containers that are on subnet.
* Add a static route to the entire Calico IP range via one of the Calico hosts (but this is a suboptimal traffic path).
Thanks @matthewdupre and @djosborne for these options

**Comment by cbluth** [comment]
Is there any documentation for adding a static route to the calico ClusterIP range?

**Comment by halfcrazy** [comment]
Any updates?
Interesting in the cheating way to run calico/node on nodes out of calico cluster.

**Comment by smekkley** [comment]
@cbluth 
What is calico cluster ip range? Pod ip range or kube-proxy cluster ip range?
Could this be what you want?
https://docs.projectcalico.org/v3.4/usage/service-advertisement
Probably this feature is also not meant for production though. Using some Loadbalancer is the only way to export the service.

But yeah, clear documentation of what's recommended for exporting the k8s ip range would be helpful. For example, even though calico exports pod ip when bgp peering is enabled, it's never meant to accessed from outside other than testing purpose. I believe this service-advertisement falls into the same category as well.

**Comment by caseydavenport** [comment]
Yeah, the cluster IP advertisement is definitely a part of this, as would be something like MetalLB integration.
