### ISSUE TITLE
Operator does not support IPv6 and it's not documented

### ISSUE THREAD

**Issue by bjencks** [projectcalico/calico#5091]
It appears that the operator does not support IPv6: "since the operator itself does not support IPv6, we verify that IPv6 is disabled." (https://github.com/tigera/operator/blob/v1.23.1/pkg/controller/migration/convert/network.go#L150)

That's a pretty major limitation, and there's no mention of it on the operator migration page (https://docs.projectcalico.org/archive/v3.21/maintenance/operator-migration). I started the migration and only discovered this when it reported an error about `FELIX_IPV6SUPPORT`. I have a single-stack IPv6 network, so there is no workaround until it's supported normally.

Ideally IPv6 would be supported, but if it's not, please at least mention it on the migration page. I suspect there are other missing features, so a full list would be useful to make sure people don't attempt it when their configuration isn't supported.

**Comment by svallala** [comment]
@bjencks I migrated my IPv6 cluster from 3.12.3 to 3.21 using operator migration steps, but it was not smooth. Please look at the ticket https://github.com/projectcalico/calico/issues/5086 that I opened with a list of issues that I faced. I do have the cluster running now with 3.21, but a lot of options are missing.

[root@cscale-82-57 root]# kubectl get pods -n calico-system
NAME                                       READY   STATUS    RESTARTS   AGE
calico-kube-controllers-7fd885dfcc-b2nv2   1/1     Running   0          4d11h
calico-node-7bjjb                          1/1     Running   0          4d11h
calico-node-dgqwn                          1/1     Running   0          4d11h
calico-typha-5fbfc7b5-ztsx5                1/1     Running   0          4d11h

[root@cscale-82-57 root]# docker images | grep calico
calico/node                                        v3.21.0             f2ff8e948456        11 days ago         189MB
calico/pod2daemon-flexvol                          v3.21.0             21bd0499378c        11 days ago         21.4MB
calico/cni                                         v3.21.0             19c5757ec6bb        11 days ago         239MB
calico/typha                                       v3.21.0             364b090cfcbf        11 days ago         128MB
calico/kube-controllers                            v3.21.0             5235846386af        11 days ago         132MB

**Comment by song-jiang** [comment]
@tmjd @caseydavenport Any comments?

**Comment by caseydavenport** [comment]
Yeah, as mentioned above I think we have some work to do to make this seamless for IPv6. My understanding is that the operator does now support IPv6 (or at least dual-stack) but that the migration code does not yet support all the necessary options, and we are likely missing tests.

**Comment by keliansb** [comment]
The PR tigera/operator#1877 seems to add IPv6 support to the operator.
