### ISSUE TITLE
Calico CNI v3.20.2 intermittently become non-responsive on kubernetes v1.21.5 

### ISSUE THREAD

**Issue by ssshcl** [projectcalico/calico#5097]
Hello,

We are running kubernetes cluster version v1.21.5 without any problem.

Calico CNI v3.20.2
Docker Version v20.10.2
RHEL 7.9

From few day I am facing an issue that CALICO CNI become non-responsive intermittently and all the calico-node daemonset pods showing 0/1 state.
Even calico-controller pods also showing 0/1 and 1/1.

We are unable to identify the issue for CNI or Kubernetes.

We have to restart all the master and worker nodes of the cluster and then only the calico-node pod become in ready state (1/1).

Need your help to know why the calico-node pods become not ready intermittently, Is there any bug on this version.

**Comment by lmm** [comment]
@ssshcl could you please provide more details on the issues you are seeing?

- `kubectl describe` of the failing pods
- `kubectl logs` of the failing pods

How did you install Calico?
