### ISSUE TITLE
calico-vxlan.yaml assumes AWS

### ISSUE THREAD

**Issue by fasaxc** [projectcalico/calico#5101]
It looks like calico-vxlan.yaml turns on the AWS source/dest check feature.  That, of course, fails if you're not running on AWS:

@fasaxc For me it seems to be the same issue. I do not use EKS at all in my case.

Steps to reproduce:

- I created a new Kubernetes cluster without any CNI installed (on Exoscale but I guess any provider can be used).
- I applied `calico-vxlan.yaml` from the latest Calico release (v3.21.0). The manifest contains:

```
            # Disable AWS source-destination check on nodes.
            - name: FELIX_AWSSRCDSTCHECK
              value: Disable
```

`calico-node` pods fail to start:

```
2021-11-18 10:06:28.555 [WARNING][87] felix/health.go 188: Reporter is not ready. name="aws-source-destination-check"
2021-11-18 10:06:28.566 [WARNING][87] felix/health.go 188: Reporter is not ready. name="aws-source-destination-check"
2021-11-18 10:06:28.566 [WARNING][87] felix/health.go 154: Health: not ready
```

I then removed the `FELIX_AWSSRCDSTCHECK` configuration from the manifest and reapplied it: `calico-node` pods are now running and ready.

_Originally posted by @mcorbin in https://github.com/projectcalico/calico/issues/4154#issuecomment-972721208_

**Comment by caseydavenport** [comment]
Seems to have been added here: https://github.com/projectcalico/calico/pull/3812

Not sure why it's setting that for all VXLAN.

**Comment by caseydavenport** [comment]
Looks like that flag used to be called "eks" instead of "vxlan": https://github.com/realgaurav/calico/commit/76e7800dbe61c1b45ad28e3a2c6ead77729a5ca1

**Comment by caseydavenport** [comment]
Probably because it's used in this doc: https://docs.projectcalico.org/getting-started/kubernetes/managed-public-cloud/eks#install-eks-with-calico-networking

Seems to conflate VXLAN with EKS, which isn't the case.

**Comment by caseydavenport** [comment]
This PR should do it: https://github.com/projectcalico/calico/pull/5107
