### ISSUE TITLE
ERROR: Could not set accept_ra

### ISSUE THREAD

**Issue by YuriBucci2** [projectcalico/calico#5106]
Hello All,

Has anyone seen this error/warning in calico ?

> 2021-11-19 18:40:21.262 [WARNING][79] felix/endpoint_mgr.go 1141: Could not set accept_ra: <nil> ifaceName="calic8ba59a1725"
> 2021-11-19 18:41:09.830 [WARNING][79] felix/endpoint_mgr.go 1141: Could not set accept_ra: <nil> ifaceName="calic8ba59a1725"
> 2021-11-19 18:52:53.293 [WARNING][79] felix/endpoint_mgr.go 1141: Could not set accept_ra: <nil> ifaceName="caliabd5a65c320"
> 2021-11-19 18:52:53.293 [WARNING][79] felix/endpoint_mgr.go 1141: Could not set accept_ra: <nil> ifaceName="cali0ceec5f8700"
> 2021-11-19 18:52:53.293 [WARNING][79] felix/endpoint_mgr.go 1141: Could not set accept_ra: <nil> ifaceName="calidf01c2cb530"
> 2021-11-19 18:52:53.294 [WARNING][79] felix/endpoint_mgr.go 1141: Could not set accept_ra: <nil> ifaceName="cali66112969844"
> 2021-11-19 18:52:53.294 [WARNING][79] felix/endpoint_mgr.go 1141: Could not set accept_ra: <nil> ifaceName="cali0adc48f3b5b"
> 2021-11-19 18:52:53.294 [WARNING][79] felix/endpoint_mgr.go 1141: Could not set accept_ra: <nil> ifaceName="cali3b63e95e2c6"
> 2021-11-19 18:52:53.294 [WARNING][79] felix/endpoint_mgr.go 1141: Could not set accept_ra: <nil> ifaceName="calie6d700ff8e3"
> 2021-11-19 18:52:53.294 [WARNING][79] felix/endpoint_mgr.go 1141: Could not set accept_ra: <nil> ifaceName="calie67b9bbf76e"
> 2021-11-19 18:52:53.294 [WARNING][79] felix/endpoint_mgr.go 1141: Could not set accept_ra: <nil> ifaceName="calif712201e5a7"
> 2021-11-19 18:52:53.294 [WARNING][79] felix/endpoint_mgr.go 1141: Could not set accept_ra: <nil> ifaceName="cali46706cbf1b6"
> 2021-11-19 18:52:53.604 [WARNING][79] felix/ipsets.go 914: Failed to delete IP set, may be out-of-sync. error=exit status 1 family="inet" output="ipset v7.1: Set cannot be destroyed: it is in use by a kernel component\n" setName="cali40s:R-gWeczSbcWmY7chlhQZs4E"
> 2021-11-19 18:52:53.604 [WARNING][79] felix/ipsets.go 874: Failed to delete IP set. Will retry on next resync. error=exit status 1 family="inet" setName="cali40s:R-gWeczSbcWmY7chlhQZs4E"
> 2021-11-19 18:52:55.690 [WARNING][79] felix/endpoint_mgr.go 1141: Could not set accept_ra: <nil> ifaceName="cali3b63e95e2c6"
> 2021-11-19 18:52:55.897 [WARNING][79] felix/endpoint_mgr.go 1141: Could not set accept_ra: <nil> ifaceName="calie6d700ff8e3"
> 2021-11-19 18:52:56.199 [WARNING][79] felix/endpoint_mgr.go 1141: Could not set accept_ra: <nil> ifaceName="cali0ceec5f8700"
> 2021-11-19 18:52:56.199 [WARNING][79] felix/endpoint_mgr.go 1141: Could not set accept_ra: <nil> ifaceName="calidf01c2cb530"
> 2021-11-19 18:52:56.199 [WARNING][79] felix/endpoint_mgr.go 1141: Could not set accept_ra: <nil> ifaceName="cali0adc48f3b5b"
> 2021-11-19 18:52:56.199 [WARNING][79] felix/endpoint_mgr.go 1141: Could not set accept_ra: <nil> ifaceName="calif712201e5a7"
> 2021-11-19 18:52:56.493 [WARNING][79] felix/endpoint_mgr.go 1141: Could not set accept_ra: <nil> ifaceName="calie67b9bbf76e"
> 2021-11-19 18:52:56.493 [WARNING][79] felix/endpoint_mgr.go 1141: Could not set accept_ra: <nil> ifaceName="cali46706cbf1b6"
> 2021-11-19 18:52:56.493 [WARNING][79] felix/endpoint_mgr.go 1141: Could not set accept_ra: <nil> ifaceName="caliabd5a65c320"
> 2021-11-19 18:52:57.096 [WARNING][79] felix/endpoint_mgr.go 1141: Could not set accept_ra: <nil> ifaceName="cali66112969844"
> 2021-11-19 18:53:23.271 [WARNING][79] felix/endpoint_mgr.go 1141: Could not set accept_ra: <nil> ifaceName="calie67b9bbf76e"
> 2021-11-19 18:53:25.938 [WARNING][79] felix/endpoint_mgr.go 1141: Could not set accept_ra: <nil> ifaceName="cali0ceec5f8700"
> 2021-11-19 18:53:26.191 [WARNING][79] felix/endpoint_mgr.go 1141: Could not set accept_ra: <nil> ifaceName="calif712201e5a7"
>

**Comment by caseydavenport** [comment]
@YuriBucci2 how did you install Calico? Please fill in the issue template when creating new issues. The information it requests is important.

**Comment by YuriBucci2** [comment]
I installed with Kubespray

Sorry for the bad template

**Comment by caseydavenport** [comment]
This sounds potentially like Calico is missing permissions it needs to set sysctls, or something similar. Have you checked with the kubespray maintainers?

Can you check if your calico/node container is run as privileged / root? 

CC @mgleung
