### ISSUE TITLE
IPAM config doesn't have an example

### ISSUE THREAD

**Issue by lwr20** [projectcalico/calico#511]
http://docs.projectcalico.org/master/reference/cni-plugin/configuration
The IPAM section of this doc talks about various keys (including `ipv6_pools`, `assign_ipv4`), but it isn't clear (to me) where in the config those keys go.  As it turns out, I think they go inside the `ipam:` section of the config, but the doc isn't clear enough (to me).

A lot of the other areas in this doc give an example - it would be great if this section had an example too.

**Comment by lwr20** [comment]
LOL - also - this doc has 2 IPAM sections...  Suspect the second one ought to be "host-local IPAM plugin".

**Comment by caseydavenport** [comment]
@lwr20 the second one is meant to be a sub-section of `Kubernetes specific`.  i.e Kubernetes specific IPAM configuration options.

**Comment by djosborne** [comment]
Related: #430

**Comment by gunjan5** [comment]
addressed in #524
