### ISSUE TITLE
help：I want close cilico networkpolicy function,only use the network function，what should i do？

### ISSUE THREAD

**Issue by xiake468** [projectcalico/calico#5114]
I want close cilico networkpolicy function,only use the network function，what should i do？

**Comment by Akasurde** [comment]
I suggest using the [Slack channel](https://slack.projectcalico.org/) to ask questions like this. The community is much wider and faster there.

**Comment by xiake468** [comment]
> 

thank you,i have asked this in slack,for this issue i will close
