### ISSUE TITLE
Stars tutorial frontend not rendering nodes

### ISSUE THREAD

**Issue by AlejoAsd** [projectcalico/calico#5116]
The stars application used in the network policy tutorial is not working. Specifically, the frontend is not rendering any nodes.

## Expected Behavior
I expected to see three nodes representing the different components.

![image](https://user-images.githubusercontent.com/483619/143292822-82e62dfd-df3b-4fb3-81a9-14df1f89a6c5.png)

## Current Behavior

The frontend is loading but no nodes show up.

![image](https://user-images.githubusercontent.com/483619/143292927-b70caf23-6c78-4026-9009-04ccf6152eb4.png)

No errors show up in the browser console.

![image](https://user-images.githubusercontent.com/483619/143293076-5ff278f4-c13b-45bf-8bd2-83d51f5e6532.png)

This was tried in Chrome 93 and Firefox 94.

## Steps to Reproduce (for bugs)

1. Follow the AWS Guide.
2. Deploy `stars` application on cluster.
3. Port forward frontend service.
4. Load frontend in browser.

## Context
I'm following the [EKS Calico installation guide](https://docs.aws.amazon.com/eks/latest/userguide/calico.html) to install Calico on my EKS cluster for network policies using the AWS CNI. 

After following the EKS guide and installing Calico, I launched the stars application to check that network policies were being enforced.

## Your Environment

* Calico version 3.13.4 (This version was installed for cluster compatibility reasons)
* Orchestrator version (e.g. kubernetes, mesos, rkt): EKS 1.17
* Operating System and version: Ubuntu 18.04
* Link to your project (optional):

**Comment by song-jiang** [comment]
@AlejoAsd Any reason why you can't upgrade? Could you try the same tutorial on latest Calico version v3.21?
 Please raise another issue if it's still not working. I doubt if we would fix this and deliver a patch release for v3.13.

**Comment by AlejoAsd** [comment]
Mostly due to current version freezes in the project. I will see if we can update Calico to 3.17 as it is the latest that my cluster version supports and get back to you.
