### ISSUE TITLE
operator/configuration: pin the `image-tag`

### ISSUE THREAD

**Issue by tormath1** [projectcalico/calico#5121]
## Expected Behavior

Hi,

in the configuration of operator, we can override the following default value for the image specs:
* `registry`
* `imagePath`
* `imagePrefix`
* `imagePullSecrets`

It would be nice to be able to override `imageTag`, it can also been considered as a good practice to pin image tag in order to ensure reliability.

## Current Behavior

I guess it has historical reason, but if we check images pulled by the operator:
* calico/typha
* calico/pod2daemon-flexvol
* calico/cni
* calico/node
* calico/kube-controllers

They both target the same tag.

Looking at the code, there is [this](https://github.com/tigera/operator/blob/efa33b25fd97eb765f727eb1a2770ee4e075b553/pkg/components/references.go#L67-L75):
```go
	if is == nil {
		return fmt.Sprintf("%s%s:%s", registry, image, c.Version), nil
	}


	for _, img := range is.Spec.Images {
		if img.Image == c.Image {
			return fmt.Sprintf("%s%s@%s", registry, image, img.Digest), nil
		}
	}
```

Which use the `c.Version` (hardcoded to `master`) or `img.Digest`.

## Possible Solution

Provide a `imageTag` field into spec and use it in case it's provided.

## Context

Calico is used in [Flatcar](http://flatcar-linux.org/) automated [CI](https://github.com/flatcar-linux/mantle/blob/3b3496bf2ab5f3bbc36225d3edb63a43f648f58b/kola/tests/kubeadm/templates.go#L319-L341) and we noticed that we were always pulling a "latest" version because we're mirroring image from Docker Hub to GHCR.

**Comment by song-jiang** [comment]
@tmjd WDYT?

**Comment by caseydavenport** [comment]
We don't want to expose using arbitrary image tags, as each operator release is intended for use with only one version of Calico - trying to use any other version "voids the warranty", so to speak. 

You can, however, already specify images by their precise digest if you like: https://projectcalico.docs.tigera.io/reference/installation/api#operator.tigera.io/v1.ImageSetSpec

Just make sure you're using the correct version of Calico for the given operator.
