### ISSUE TITLE
HINFO: read udp 10.1.81.29:58070->10.1.162.250:53: i/o timeout

### ISSUE THREAD

**Issue by Sam-Sundar-Apty** [projectcalico/calico#5123]
Hi Calico Team,

We have an offline environment where Microk8s is deployed with Calico node and CoreDNS as DNS.

We could see DNS is not resolving endpoints and are getting i/o timeout. We have followed [this article](https://github.com/ubuntu/microk8s/files/7587411/redhat.txt) to remove NFTABLE and use iptable instead, and also added below env in caliconode daemonset
```yaml
- name: FELIX_IPTABLESBACKEND
  value: "NFT"
  ```
When i check iptables, below is the output with no rule even though we run `iptables -P FORWARD ACCEPT && iptables -P INPUT ACCEPT && iptables -P OUTPUT ACCEPT`

![image](https://user-images.githubusercontent.com/83000807/143888899-8a331724-1e57-4e49-be1c-e6a8edecf8d2.png)
![image](https://user-images.githubusercontent.com/83000807/143888963-3fef30f6-5044-4261-b069-4511c2d14521.png)

We get this error in coredns logs
![image](https://user-images.githubusercontent.com/83000807/143889680-9d808ddf-aae5-4092-9a20-f57082d44cfc.png)

Also when we nslookup a service from another pod, we get this below error
![image](https://user-images.githubusercontent.com/83000807/143890919-e82a5b9d-7c7a-423c-b815-838f2d7309a2.png)

Also `firewalld` is not running and we followed [this](https://github.com/coredns/coredns/issues/4666#issuecomment-856153464) too and removed all the hardening restrictions.
Can you please let us know if we are missing something and how to solve this issue.

**Environment**: 

- the version of Calico : coredns/coredns:1.8.0, quay.io/calico/node:v3.13.2
- Corefile: `forward . /etc/resolv.conf`
- logs, if applicable: 
- [coredns_NFT.log](https://github.com/coredns/coredns/files/7618875/coredns_NFT.log)
- [calico_NFT.log](https://github.com/coredns/coredns/files/7618880/calico_NFT.log)
- OS (e.g: `cat /etc/os-release`) - RHEL 8.4

- Others:

**Comment by coutinhop** [comment]
Hi @Sam-Sundar-Apty! Am I wrong in my understanding that you stopped+disabled nftables and started+enabled iptables? In that case, it seems weird that you set FELIX_IPTABLESBACKEND to "NFT", could you try leaving it at "Auto" or using "Legacy"?

Also, calico 3.13 is pretty outdated, would it be possible to use a more recent version?

**Comment by Sam-Sundar-Apty** [comment]
Hi @coutinhop ,

Sure I'll set `FELIX_IPTABLESBACKEND` to auto, and would nothing break if I update calico to latest version ? 

Also iptabels-legacy binaries are not present in the server. :(

**Comment by Sam-Sundar-Apty** [comment]
Hi @coutinhop,

I tried to set `FELIX_IPTABLESBACKEND` to Auto, and no luck. So i disabled iptables, enabled nftables and firewalld again. And then stopped and started the cluster, and i'm getting below errors in coredns and it's not starting. 
```bash
Trace[544474078]: [30.000360344s] [30.000360344s] END
E1202 10:45:03.506949       1 reflector.go:127] pkg/mod/k8s.io/client-go@v0.19.2/tools/cache/reflector.go:156: Failed to watch *v1.Endpoints: failed to list *v1.Endpoints: Get "https://10.152.183.1:443/api/v1/endpoints?limit=500&resourceVersion=0": dial tcp 10.152.183.1:443: i/o timeout
I1202 10:45:03.506967       1 trace.go:205] Trace[605764324]: "Reflector ListAndWatch" name:pkg/mod/k8s.io/client-go@v0.19.2/tools/cache/reflector.go:156 (02-Dec-2021 10:44:33.506) (total time: 30000ms):
Trace[605764324]: [30.000463645s] [30.000463645s] END
E1202 10:45:03.506991       1 reflector.go:127] pkg/mod/k8s.io/client-go@v0.19.2/tools/cache/reflector.go:156: Failed to watch *v1.Service: failed to list *v1.Service: Get "https://10.152.183.1:443/api/v1/services?limit=500&resourceVersion=0": dial tcp 10.152.183.1:443: i/o timeout
I1202 10:45:03.507010       1 trace.go:205] Trace[1693516159]: "Reflector ListAndWatch" name:pkg/mod/k8s.io/client-go@v0.19.2/tools/cache/reflector.go:156 (02-Dec-2021 10:44:33.506) (total time: 30000ms):
Trace[1693516159]: [30.000517668s] [30.000517668s] END
E1202 10:45:03.507018       1 reflector.go:127] pkg/mod/k8s.io/client-go@v0.19.2/tools/cache/reflector.go:156: Failed to watch *v1.Namespace: failed to list *v1.Namespace: Get "https://10.152.183.1:443/api/v1/namespaces?limit=500&resourceVersion=0": dial tcp 10.152.183.1:443: i/o timeout
[INFO] 127.0.0.1:60530 - 59298 "HINFO IN 6867612701957088673.9206676843128618410. udp 57 false 512" NOERROR - 0 2.00031837s
[ERROR] plugin/errors: 2 6867612701957088673.9206676843128618410. HINFO: read udp 10.1.81.31:45292->8.8.8.8:53: i/o timeout
[INFO] 127.0.0.1:36161 - 30607 "HINFO IN 6867612701957088673.9206676843128618410. udp 57 false 512" NOERROR - 0 2.000285312s
[ERROR] plugin/errors: 2 6867612701957088673.9206676843128618410. HINFO: read udp 10.1.81.31:40489->8.8.8.8:53: i/o timeout
I1202 10:45:34.547562       1 trace.go:205] Trace[392828266]: "Reflector ListAndWatch" name:pkg/mod/k8s.io/client-go@v0.19.2/tools/cache/reflector.go:156 (02-Dec-2021 10:45:04.547) (total time: 30000ms):
Trace[392828266]: [30.000512978s] [30.000512978s] END
E1202 10:45:34.547598       1 reflector.go:127] pkg/mod/k8s.io/client-go@v0.19.2/tools/cache/reflector.go:156: Failed to watch *v1.Namespace: failed to list *v1.Namespace: Get "https://10.152.183.1:443/api/v1/namespaces?limit=500&resourceVersion=0": dial tcp 10.152.183.1:443: i/o timeout
I1202 10:45:34.597056       1 trace.go:205] Trace[1926275561]: "Reflector ListAndWatch" name:pkg/mod/k8s.io/client-go@v0.19.2/tools/cache/reflector.go:156 (02-Dec-2021 10:45:04.596) (total time: 30000ms):
Trace[1926275561]: [30.000477288s] [30.000477288s] END
E1202 10:45:34.597084       1 reflector.go:127] pkg/mod/k8s.io/client-go@v0.19.2/tools/cache/reflector.go:156: Failed to watch *v1.Endpoints: failed to list *v1.Endpoints: Get "https://10.152.183.1:443/api/v1/endpoints?limit=500&resourceVersion=0": dial tcp 10.152.183.1:443: i/o timeout
I1202 10:45:35.013419       1 trace.go:205] Trace[2102234783]: "Reflector ListAndWatch" name:pkg/mod/k8s.io/client-go@v0.19.2/tools/cache/reflector.go:156 (02-Dec-2021 10:45:05.012) (total time: 30000ms):
Trace[2102234783]: [30.000758651s] [30.000758651s] END
E1202 10:45:35.013442       1 reflector.go:127] pkg/mod/k8s.io/client-go@v0.19.2/tools/cache/reflector.go:156: Failed to watch *v1.Service: failed to list *v1.Service: Get "https://10.152.183.1:443/api/v1/services?limit=500&resourceVersion=0": dial tcp 10.152.183.1:443: i/o timeout
I1202 10:46:06.839084       1 trace.go:205] Trace[195071563]: "Reflector ListAndWatch" name:pkg/mod/k8s.io/client-go@v0.19.2/tools/cache/reflector.go:156 (02-Dec-2021 10:45:36.833) (total time: 30000ms):
Trace[195071563]: [30.000649324s] [30.000649324s] END
E1202 10:46:06.839124       1 reflector.go:127] pkg/mod/k8s.io/client-go@v0.19.2/tools/cache/reflector.go:156: Failed to watch *v1.Namespace: failed to list *v1.Namespace: Get "https://10.152.183.1:443/api/v1/namespaces?limit=500&resourceVersion=0": dial tcp 10.152.183.1:443: i/o timeout
I1202 10:46:07.290206       1 trace.go:205] Trace[1990689002]: "Reflector ListAndWatch" name:pkg/mod/k8s.io/client-go@v0.19.2/tools/cache/reflector.go:156 (02-Dec-2021 10:45:37.289) (total time: 30000ms):
Trace[1990689002]: [30.000696553s] [30.000696553s] END
E1202 10:46:07.290242       1 reflector.go:127] pkg/mod/k8s.io/client-go@v0.19.2/tools/cache/reflector.go:156: Failed to watch *v1.Endpoints: failed to list *v1.Endpoints: Get "https://10.152.183.1:443/api/v1/endpoints?limit=500&resourceVersion=0": dial tcp 10.152.183.1:443: i/o timeout
I1202 10:46:08.090341       1 trace.go:205] Trace[747225447]: "Reflector ListAndWatch" name:pkg/mod/k8s.io/client-go@v0.19.2/tools/cache/reflector.go:156 (02-Dec-2021 10:45:38.089) (total time: 30001ms):
Trace[747225447]: [30.001172622s] [30.001172622s] END
E1202 10:46:08.090380       1 reflector.go:127] pkg/mod/k8s.io/client-go@v0.19.2/tools/cache/reflector.go:156: Failed to watch
[nft_list_2021-12-02.log](https://github.com/projectcalico/calico/files/7655572/nft_list_2021-12-02.log)
 *v1.Service: failed to list *v1.Service: Get "https://10.152.183.1:443/api/v1/services?limit=500&resourceVersion=0": dial tcp 10.152.183.1:443: i/o timeout
```

Attaching both `iptables` and `NFT` backend logs below also the `iptables` and `nftables` rules.
PS: The one with NFT in filename is `NFT` backend, and others are `iptables` backend. 
[iptables_2021-12-02.txt](https://github.com/projectcalico/calico/files/7655573/iptables_2021-12-02.txt)
[calico_2021-12-02.log](https://github.com/projectcalico/calico/files/7655578/calico_2021-12-02.log)
[calico_NFT.log](https://github.com/projectcalico/calico/files/7655577/calico_NFT.log)
[coredns_2021-12-02.log](https://github.com/projectcalico/calico/files/7655574/coredns_2021-12-02.log)
[coredns_NFT.log](https://github.com/projectcalico/calico/files/7655575/coredns_NFT.log)
[calico-NFT-2021-12-02.log](https://github.com/projectcalico/calico/files/7655576/calico-NFT-2021-12-02.log)

**Comment by dimm0** [comment]
I've also hit the issue with coredns being unable to access DNS after the calico upgrade

**Comment by caseydavenport** [comment]
@Sam-Sundar-Apty did you get a chance to try this on a newer version of Calico? v3.13 is well out of the support timeframe.

@dimm0 what version were you on? Do you believe it to be the same issue as this one?

> E1202 10:46:07.290242       1 reflector.go:127] pkg/mod/k8s.io/client-go@v0.19.2/tools/cache/reflector.go:156: Failed to watch *v1.Endpoints: failed to list *v1.Endpoints: Get "https://10.152.183.1:443/api/v1/endpoints?limit=500&resourceVersion=0": dial tcp 10.152.183.1:443: i/o timeout

Essentially, the API server isn't reachable. This could be due to any number of reasons. You'll need to check a few things:

- Are nodes able to talk to each other OK?
- Are nodes able to talk to the API server OK (directly, using the API server's REAL address)?
- Are nodes able to talk to the API server OK via it's virtual ClusterIP? 
- Are pods _on the same node_ able to talk to each other?
- Are pods on different nodes able to talk to each other?
- Are pods able to reach the API server using its ClusterIP? 

Running those checks should help narrow the issue down. 

Like mentioned above, setting `FELIX_IPTABLESBACKEND` to the correct value is important. Using iptables-legacy and `FELIX_IPTABLESBACKEND=NFT` is a surefire way to break your cluster.

**Comment by dimm0** [comment]
Mine is in https://github.com/projectcalico/calico/issues/5309 which is a dup of https://github.com/projectcalico/calico/issues/5173 and been fixed already :) Please ignore.
