### ISSUE TITLE
calico custom-resources.yaml enable TYPHA_PROMETHEUSMETRICSENABLED=true

### ISSUE THREAD

**Issue by tanmx** [projectcalico/calico#5124]
I use quickstart install the calico , But soon after I enable TYPHA_PROMETHEUSMETRICSENABLED=true in 
calico-typha daemonset，the pod of calico-typha will rebuild and remove the TYPHA_PROMETHEUSMETRICSENABLED option

how can i enable the enable TYPHA_PROMETHEUSMETRICSENABLED=true in  custom-resources.yaml?

## Your Environment

* Calico version : 3.21.1
* Orchestrator version (e.g. kubernetes, mesos, rkt): k8s 1.19.15
* Operating System and version: centos7
* Link to your project (optional):

**Comment by lwr20** [comment]
In a system installed by tigera-operator, you should be configuring this sort of thing in the Installation resource.  https://docs.projectcalico.org/reference/installation/api

I think you need to set `spec.typhaMetricsPort=9091` in the Installation.  That will cause operator to set  TYPHA_PROMETHEUSMETRICSENABLED=true in the calico-typha daemonset

**Comment by tanmx** [comment]
> https://docs.projectcalico.org/reference/installation/api

thank you
