### ISSUE TITLE
calico-node not ready after node reboot with WireGuard enabled

### ISSUE THREAD

**Issue by Cloud5000** [projectcalico/calico#5125]
With **WireGuard** enabled **calico-node** pod fails to start after node reboot. Readiness probe fails with the following message: **calico/node is not ready: felix is not ready: readiness probe reporting 503**.

## Expected Behavior
Calico-node pod should start normally after node reboot even with Wireguard enabled.

## Current Behavior
Calico-node pod fails to start after node reboot. After deactivating Wireguard again pod gets ready immediately. This only happens when there is no **calico-typha** pod running on the same node. Otherwise pod starts normally even with Wireguard enabled.

## Steps to Reproduce (for bugs)
- Activate Wireguard as described here: https://docs.projectcalico.org/security/encrypt-cluster-pod-traffic
- Reboot node

## Context
Trying to encrypt in-cluster pod traffic

## Your Environment
Azure AKS
Kubernetes version: v1.21.2
Node image: AKSUbuntu-1804gen2containerd-2021.11.06
Calico version: v3.20.0

**Comment by caseydavenport** [comment]
This sounds like it might be a problem with calico/node being able to access Typha in some way - perhaps due to the way wireguard is configured.

@mikestephen could you help diagnose this one? What sort of diagnostics should we look for?

**Comment by mikestephen** [comment]
Hi @Cloud5000 , do you see anything suspicious in the calico-node logs?

I'll try and reproduce this issue in the next day or two.

**Comment by Cloud5000** [comment]
```
[INFO][471] tunnel-ip-allocator/discovery.go 163: Found ready Typha addresses. addrs=[]string{"xx.xx.xx.xx:5473", "xx.xx.xx.35:5473", "xx.xx.xx.82:5473"}
[INFO][471] tunnel-ip-allocator/discovery.go 166: Chose Typha to connect to. choice="xx.xx.xx.82:5473"
[INFO][471] tunnel-ip-allocator/startsyncerclient.go 56: Connecting to Typha. addr="xx.xx.xx.82:5473"
[INFO][471] tunnel-ip-allocator/sync_client.go 71:  requiringTLS=true
[INFO][471] tunnel-ip-allocator/sync_client.go 200: Starting Typha client
[INFO][471] tunnel-ip-allocator/sync_client.go 71:  requiringTLS=true
...
[INFO][471] tunnel-ip-allocator/sync_client.go 252: Connecting to Typha. address="xx.xx.xx.82:5473" connID=0x0 type="tunnel-ip-allocation"
[WARNING][441] felix/health.go 188: Reporter is not ready. name="int_dataplane"
[INFO][441] felix/health.go 196: Overall health status changed newStatus=&health.HealthReport{Live:true, Ready:false}
[WARNING][441] felix/health.go 154: Health: not ready
[WARNING][441] felix/health.go 188: Reporter is not ready. name="int_dataplane"
[ERROR][441] felix/daemon.go 488: Failed to connect to Typha. Retrying... error=dial tcp xx.xx.xx.35:5473: i/o timeout
[INFO][441] felix/health.go 133: Health of component changed lastReport=health.HealthReport{Live:true, Ready:true} name="felix-startup" newReport=&health.HealthReport{Live:true, Ready:false}
[INFO][441] felix/sync_client.go 200: Starting Typha client
[INFO][441] felix/sync_client.go 71:  requiringTLS=true
...
[INFO][441] felix/sync_client.go 252: Connecting to Typha. address="xx.xx.xx.35:5473" connID=0x0 type=""
[FATAL][471] tunnel-ip-allocator/startsyncerclient.go 73: Failed to connect to Typha error=dial tcp xx.xx.xx.82:5473: i/o timeout
```

We don't use **wireguardHostEncryptionEnabled**.

Thanks!

**Comment by aaaaaaaalex** [comment]
Hey @Cloud5000 , do you use the [tigera-operator](https://docs.projectcalico.org/reference/installation/api) or are you configuring Calico manually?

**Comment by Cloud5000** [comment]
Hi @aaaaaaaalex,

we are using managed kubernetes from Azure. We only selected Calico as **network policy** and did not configure anything manually except for enabling wireguard. But **tiger-opeator** pod is deployed automatically (by Azure) and running.

**Comment by aaaaaaaalex** [comment]
Thanks @Cloud5000 

With this in mind, it seems likely that Felix cannot communicate with Typha on another node due to the two nodes' WireGuard configurations being out-of-sync with one-another. It's possible that a Felix restart could cause this. We're attempting to reproduce this now and verify that is the cause

**Comment by artificiosus** [comment]
I can confirm the exact same behavior with the following configuration:
AWS EKS
Kubernetes v1.20.7-eks-d88609
Node AMI ubuntu-eks/k8s_1.20/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20211110
Tigera Operator v1.20.1 / Calico v3.20.0

wireguardEnabled: true but wireguardHostEncryptionEnabled not set

restarting the typha instances after a node reboot seems to correct the issue without having to disable wireguard, otherwise calico-node pods will remain in not ready state indefinitely.

**Comment by Bananenbieger1234** [comment]
@aaaaaaaalex Are there any news on this topic? I am facing the same behavior.

Thx.

---

Azure AKS
Kubernetes version: v1.21.2
Node image: AKSUbuntu-1804gen2containerd-2021.11.06
Calico version: v3.20.0

**Comment by aaaaaaaalex** [comment]
Hi all, thanks for your patience!
I've managed to reproduce this issue on both AKS and EKS clusters with calico version `v3.20.0`, operator version `v1.20.1`.

From what I can tell, updating the operator patch number resolves the issue.
The latest patch of tigera-operator for calico `v3.20.x` can be found [here](https://docs.projectcalico.org/v3.20/manifests/tigera-operator.yaml). Applying this upgrades calico to version `v3.20.3`, as-of the time of writing.

Would someone who is experiencing this issue be able to validate that this works?
Thanks

**Comment by Cloud5000** [comment]
Hi @aaaaaaaalex,

thanks for analyzing. Does anyone know how to force an update of tigera-operator in Azure AKS. Otherwise we have to wait until Azure provides the new version.

**Comment by artificiosus** [comment]
Tried on a new cluster with:
AWS EKS
Kubernetes v1.20.7-eks-d88609
Node AMI ubuntu-eks/k8s_1.20/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20211110
Tigera Operator v1.20.5 / Calico v3.20.3

Still experiencing the same issue when rebooting a node that is not hosting a calico-typha instance.
After reboot, calico-node on rebooted node has event:
```
Readiness probe failed: calico/node is not ready: felix is not ready: readiness probe reporting 503
```
And logs show:

```
2021-12-08 16:32:50.941 [INFO][97] tunnel-ip-allocator/discovery.go 166: Chose Typha to connect to. choice="xxx.xxx.xxx.37:5473"
2021-12-08 16:32:50.941 [INFO][97] tunnel-ip-allocator/startsyncerclient.go 56: Connecting to Typha. addr="xxx.xxx.xxx.37:5473"
...
2021-12-08 16:32:50.941 [INFO][97] tunnel-ip-allocator/sync_client.go 252: Connecting to Typha. address="xxx.xxx.xxx.37:5473" connID=0x0 type="tunnel-ip-allocation"
2021-12-08 16:32:51.082 [ERROR][43] felix/daemon.go 488: Failed to connect to Typha. Retrying... error=dial tcp xxx.xxx.xxx.37:5473: i/o timeout
...
2021-12-08 16:32:57.173 [WARNING][43] felix/health.go 188: Reporter is not ready. name="felix-startup"
2021-12-08 16:32:57.173 [WARNING][43] felix/health.go 188: Reporter is not ready. name="int_dataplane"
2021-12-08 16:32:57.173 [WARNING][43] felix/health.go 154: Health: not ready
2021-12-08 16:33:00.248 [WARNING][43] felix/health.go 188: Reporter is not ready. name="felix-startup"
2021-12-08 16:33:00.248 [WARNING][43] felix/health.go 188: Reporter is not ready. name="int_dataplane"
2021-12-08 16:33:00.941 [FATAL][97] tunnel-ip-allocator/startsyncerclient.go 73: Failed to connect to Typha error=dial tcp xxx.xxx.xxx.37:5473: i/o timeout
```

Additionally, with Calico v3.20.3 I had to configure with
```
  wireguardEnabled: true
  wireguardHostEncryptionEnabled: true
```
as running with
```
  wireguardEnabled: true
  wireguardHostEncryptionEnabled: false
```
caused lots of networking issues even before attempting a reboot. (pod to pod communication failed when pods where on different nodes).

**Comment by aaaaaaaalex** [comment]
:cry: thanks for trying that @artificiosus, not sure why the issue seemed to disappear when I tried it... I'll dig into this some more.
