### ISSUE TITLE
NodePort service fails to function for ingress when targeted by a network policy

### ISSUE THREAD

**Issue by QWERTY92009** [projectcalico/calico#5126]
## Expected Behavior

The rabbitmq pod exposed externally as a NodePort service should allow ingress from IP addresses matching the networkpolicy ingress ipBlock configuration.

When this service is exposed externally as a LoadBalancer service, the behavior is as expected: the ingress flow matching the ipBlock of the network policy targeting this pod is allowed.

## Current Behavior

Bitnami rabbitmq pod deployed, exposed externally as a NodePort service 'ramq'.

Set of network policies controlling flows between pods within namespace using podSelectors, forbidding all flows to / from other namespaces except kube-system, and controlling all flows external to the cluster using ipBlocks.

The network policy targeting the rabbitmq pod allows ingress flows from authorized external interfaces using ipBlock.

```
-   ingress:
  - from:
    - ipBlock:
        cidr: 10.0.0.0/8
```

All internal flows validated (those allowed by network policy are allowed, those not allowed by network policy are not allowed) by scanning IPs / ports from each pod.

Observed rabbitmq pod crashing repeatedly.

Unfortunately the rabbitmq logs are not helpful in isolating the issue.

Removed the network policy targeting the rabbitmq pod.

Observed the rabbitmq pod operating normally.

## Possible Solution

It appears that related issues have been raised, but for example required ipipMode to be set to never. There are no ippools configured for this cluster, per "./calicoctl get ippool -o yaml", so I'm at a loss.

## Steps to Reproduce (for bugs)

Unfortunately the various deployments involve a significant amount of automation. However, this same or a similar behavior has been documented elsewhere:
https://oteemo.com/think-nodeport-kubernetes/

Namely: "NetworkPolicy resources can currently only control [pods exposed as] NodePorts by allowing or disallowing all traffic on them."

## Your Environment

* Calico version 
Calico v3.13.2

* Orchestrator version (e.g. kubernetes, mesos, rkt):
* 
kubectl version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"clean", BuildDate:"2021-04-08T16:31:21Z", GoVersion:"go1.16.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.4", GitCommit:"c96aede7b5205121079932896c4ad89bb93260af", GitTreeState:"clean", BuildDate:"2020-06-17T11:33:59Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.21) and server (1.18) exceeds the supported minor version skew of +/-1* Link to your project (optional):

* CRI:
docker://18.6.1

* OS:
Ubuntu 18.04.5 LTS 4.15.0-136-generic

**Comment by song-jiang** [comment]
> The network policy targeting the rabbitmq pod allows ingress flows from authorized external interfaces using ipBlock.

The network policy would allow flows from external source and it will block rabbitmq pod from getting any in-cluster traffic (if 10.0.0.0/8 is not overlapping with pod cidr). Maybe rabbitmq also needs to be able to receive in-cluster traffic?

**Comment by QWERTY92009** [comment]
That's a good question. The rabbitmq networkpolicy was originally allowing flows to/from only those pods in its namespaces with which it was supposed to be communicating, but for troubleshooting we backed this off to allow ingress from / egress to all other pods in all other namespaces. 

  ingress:
  - from:
    - ipBlock:
        cidr: 10.0.0.0/8
    - namespaceSelector:
        matchLabels: {}
      podSelector:
        matchLabels: {}
  egress:
  - to:
    - ipBlock:
        cidr: 10.0.0.0/8
    - namespaceSelector:
        matchLabels: {}
      podSelector:
        matchLabels: {}

**Comment by song-jiang** [comment]
You would need to find out which traffic flow affected rabbitmq, maybe by a comparison of tcpdumps on the pod ip w/o network policy?

**Comment by mgleung** [comment]
Since it looks like there hasn't been much activity on this issue I'm going to close it. If anyone still finds this affecting them, feel free to shout and I'll reopen it.
