### ISSUE TITLE
Waiting for interface matching management IP... error=no index found for interface

### ISSUE THREAD

**Issue by chj9** [projectcalico/calico#5145]
## Current Behavior
   It is still the same after restarting many times, no error is reported during the installation process, and the window service is running normally
![image](https://user-images.githubusercontent.com/16426260/144691693-204a451e-0696-414f-a4ab-9953fba78df5.png)

## Your Environment

* Calico version 
3.20.1
`calicoctl get node`
![image](https://user-images.githubusercontent.com/16426260/144691861-1af291c6-1485-4c74-9e2c-bad957b109ea.png)

* Orchestrator version (e.g. kubernetes, mesos, rkt):
1.21.6
* Operating System and version:
![image](https://user-images.githubusercontent.com/16426260/144691787-494e3b3c-4e72-4174-8552-cb0a0e922fa7.png)
` (Get-HnsNetwork | ? Name -EQ external).ManagementIP`
![image](https://user-images.githubusercontent.com/16426260/144691900-2e1ea039-265d-4332-b1be-160fa597f9c1.png)

* Link to your project (optional):

**Comment by caseydavenport** [comment]
@lmm @song-jiang could one of you guys take a look?

**Comment by lmm** [comment]
I haven't seen this before. Usually if there's an issue with the management IP, the install fails and we resolve the issue there. In this case, the management IP is there but it looks like the management interface isn't found for the IP (for some reason).
@chj9 could you please run on the failing Windows node in cmd and share the output:
```
netsh interface ipv4 show interfaces
netsh interface ipv4 show config
```

I wonder if there a change in formatting of the output that the code isn't handling properly

**Comment by chj9** [comment]
Sorry, I have given up installing k8s node on windows, I close this question, thank you for your reply

**Comment by glzjin** [comment]
I have solved this problem with https://github.com/kubernetes-sigs/sig-windows-tools/issues/68#issuecomment-696139451 mentioned.
