### ISSUE TITLE
docker.io/calico/apiserver:v3.21.1,no matching manifest for linux/arm64/v8 in the manifest list entries

### ISSUE THREAD

**Issue by Codeprh** [projectcalico/calico#5148]
## Expected Behavior
apiserver:v3.21.1,for linux/arm64/v8

## Current Behavior
docker.io/calico/apiserver:v3.21.1,no matching manifest for linux/arm64/v8 in the manifest list entries

## Possible Solution
m1 pro max

**Comment by caseydavenport** [comment]
Looks like the apiserver is only built for amd64: https://github.com/projectcalico/apiserver/tree/master/docker-image

@frozenprocess was this one on your roadmap?

**Comment by frozenprocess** [comment]
This should fix the problem after merge.

https://github.com/projectcalico/apiserver/pull/63

**Comment by zhangguanzhang** [comment]
patch https://github.com/projectcalico/calico/pull/5386 and
```
make image BUILDARCH=arm64
```
image:
```
zhangguanzhang/calico-apiserver:v3.21.6-arm64
```
