### ISSUE TITLE
Provide an environment variable to control `nat-outgoing`

### ISSUE THREAD

**Issue by leodotcloud** [projectcalico/calico#516]
Currently in v1.0.2, the default value for `nat-outgoing` is false. To enable out going connection for the containers, I have to follow these steps: http://docs.projectcalico.org/master/usage/external-connectivity. Also I was informed that with the next release the default value for `nat-outgoing` would be false. This is great but it would be really useful if this option was configurable via an environment variable. (Something similar to CALICO_IPIP_ENABLED, say CALICO_NAT_OUTGOING?)

**Comment by VincentS** [comment]
Added documentation pull request #775 for pull request introducing CALICO_NAT_OUTGOING
