### ISSUE TITLE
Allow enabling PersistentKeepalive for wireguard enabled setup

### ISSUE THREAD

**Issue by kskalski** [projectcalico/calico#5167]
I'm observing an issue with connectivity (on internal wireguard IPs ``192.168.x.x``) from nodes on public network to node, which is inside private cloud / behind cloud provider firewall. The issue disappears immediately after I ping those nodes from the affected node inside private cloud (pings in the other direction get unstuck). The connectivity works as long as there is some traffic sent in that direction from time to time.

From what I managed to find about wireguard, this seems to be the issue of some firewall / networking gear blocking up inactive routes and could be solved by using ``PersistentKeepalive`` feature.

## Expected Behavior
Connectivity between nodes and pods persists even after periods of no traffic between given pair of nodes and direction.

## Current Behavior
After a few hours of no traffic from ``node1`` to ``node2`` the packets from ``node2`` to ``node1`` stop being routable. The problem is fixed immediately after any packet is sent from ``node1`` to ``node2``.

Note that the first ping from ``node1`` to ``node2`` has higher latency:
```
ING 192.168.96.193 (192.168.96.193) 56(84) bytes of data.
64 bytes from 192.168.96.193: icmp_seq=1 ttl=64 time=41.1 ms
64 bytes from 192.168.96.193: icmp_seq=2 ttl=64 time=19.8 ms
64 bytes from 192.168.96.193: icmp_seq=3 ttl=64 time=20.0 ms
```

as I suppose it is triggering the firewall to evaluate and re-open the route.

## Possible Solution
I suspect wireguard's _persistent keepalives_ might solve the issue. According to documentation this feature may be specified by adding the ``PersistentKeepalive =`` field to a peer in the configuration file, or setting ``persistent-keepalive`` at the command line.
I would like my calico setup to have this setting, I suppose it needs a new config flag to be added.

## Steps to Reproduce (for bugs)
1. create node1 on public vps
2. create node2 on private cloud vps (in my case oracle cloud)
3. connect them into calico node-to-node mesh, but without any workload that would send traffic from node2 to node1
4. after few hours observe that you can't send traffic from pods on node1 to pods in node2 (or even ping the node wireguard internal ip)

## Context
Right now pinging internal ips of other nodes fixes the issue and keeping e.g. webpage open that uses node2->node1 route keeps it going, after I close the page the problem will appear soon. 

## Your Environment
* Calico version ``calico/node:v3.21.1``
* Orchestrator version (e.g. kubernetes, mesos, rkt): ``k3s`` 
* Operating System and version: ``5.13.0-22-generic`` ``Ubuntu 21.10`` ``kubelet version v1.22.2+k3s2``

**Comment by kskalski** [comment]
The problem I had seems to be caused by my firewall rules that rejected ``NEW`` connections on ``UDP port 51820`` (while accepting packets for connections in ``state RELATED,ESTABLISHED``). While keep alive might paper over this problem, updating firewall works for me.

As for the feature itself I suppose it might still be useful in some settings, so I'm not closing this issue so it could be used to track it.

**Comment by lwr20** [comment]
pinging @petercork re. this wireguard feature request

**Comment by soider** [comment]
@petercork are there any updates available on this?
