### ISSUE TITLE
Log prefix not documented in calicoctl policy reference

### ISSUE THREAD

**Issue by fasaxc** [projectcalico/calico#518]
Rules can have a logPrefix that causes them to be logged as well as the normal action, that seems to be missing from the doc here: http://docs.projectcalico.org/v2.0/reference/calicoctl/resources/policy

**Comment by fasaxc** [comment]
Think we've removed that field in a clean-up exercise

**Comment by mmueen** [comment]
If we dont have log prefix, How do we distinguish between logs of packets which were DENIED or ACCEPTED?

**Comment by ramsateesh** [comment]
@fasaxc can we put this back in as a configurable ability so that it can be turned on and off?

**Comment by lucasyvas** [comment]
We are having trouble without the log rule prefix being configurable from profile/policy. We have a multi-tenant environment and it would be great to be able to specify a prefix for the log rule in profile/policy, as these tenants create their own calico profiles and, along with no way to specify denied or accepted traffic, this is kind of a nightmare for firewall reporting.

Was this abandoned as a feature for any particular reason or was it just not officially planned? From looking at the code I see that Felix can accept a log prefix, but I believe this is a global setting via environment variable right now, which doesn't help us unfortunately.
