### ISSUE TITLE
Support custom blockSize during flannel -> calico migration

### ISSUE THREAD

**Issue by sooheng** [projectcalico/calico#5186]
**Expected Behavior**
I want ippool blocksize is 24

**Current Behavior**
ippool blocksize is 26

**Steps to Reproduce (for bugs)**
a k8s cluster with flannel(vxlan).
migrate flannel to calico,
kubectl apply -f https://docs.projectcalico.org/manifests/flannel-migration/calico.yaml
kubectl apply -f https://docs.projectcalico.org/manifests/flannel-migration/migration-job.yaml

Client Version: v3.21.2
Cluster Version: v3.21.2
Cluster Type: k8s

**Comment by sooheng** [comment]
it is not a bug.
I can find the relevant code, but I can't understand why this is done.

	// Based on FlannelSubnetLen, work out the size of ippool.
	blockSize := defaultIppoolSize
	if m.config.FlannelSubnetLen > defaultIppoolSize {
		// Flannel subnet is smaller than one Calico IPAM block with default size of /26.
		blockSize = m.config.FlannelSubnetLen
	}

Why is defaultIppoolSize 26, can I change it to 24？

**Comment by caseydavenport** [comment]
You can migrate your workloads to another IP pool with a different block size per the instructions here: https://projectcalico.docs.tigera.io/networking/change-block-size

Calico's default block size is /26, but Calico will allocate additional blocks and clean them up as needed, so you are not actually limited to 64 addresses (if a node needs more, then more will be allocated to the node on-demand)

**Comment by caseydavenport** [comment]
I think it would be OK to PR a change that makes `defaultBlockSize` configurable via an environment variable.

**Comment by caseydavenport** [comment]
One thing to note is that the block size must be smaller than or equal to the flannel block size so that we don't accidentally take a CIDR that already belongs to another node.

**Comment by squ94wk** [comment]
We're actually running into issues that a pod IP on a (still) flannel node isn't reachable from a (already) calico node.

The pod's IP is 10.244.2.242, so falls into the 10.244.2.192/26 block.
Calico nodes only have a route for the 10.244.2.0/26 block.

I assume the reason for the latter is that Calico itself hasn't assigned any IPs from the ...192/26 block yet (it was assigned by Flannel) so doesn't provide the routes for it?

@caseydavenport can you confirm this?

In that case it would be a bug that during the migration part of the inter-pod communication is disrupted.

**Comment by caseydavenport** [comment]
> We're actually running into issues that a pod IP on a (still) flannel node isn't reachable from a (already) calico node.

@squ94wk could you raise another issue for that? That sounds like a different issue than this one.

**Comment by squ94wk** [comment]
@caseydavenport Roght. I have raised https://github.com/projectcalico/calico/issues/5349.

This here would still provide a workaround for my issue.
