### ISSUE TITLE
`calico` CNI plugin is linked dynamically

### ISSUE THREAD

**Issue by smira** [projectcalico/calico#5187]
## Expected Behavior

CNI plugin should be linked statically to avoid dependencies on the host.

## Current Behavior

Binary provided with `docker.io/calico/cni:v3.21.0` is linked dynamically:

```
$ ldd calico                                                                    
	linux-vdso.so.1 (0x00007ffc20dfe000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f759ce47000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f759cc1f000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f759ce62000)
```

Reverting init container to use `v3.18.6` immediately fixed the issue. I haven't tried other versions, but it is some relatively recent regression.

## Possible Solution

Build CNI plugins as static binaries.

## Your Environment

* CNI plugin version (e.g. `/opt/cni/bin/calico --version`): 3.21.0
* Orchestrator version (e.g. kubernetes, mesos, rkt):
* CNI config:
* Operating System and version: Talos
* Link to your project (optional): https://github.com/talos-systems/talos

**Comment by jnummelin** [comment]
k0s is hitting this too: https://github.com/k0sproject/k0s/issues/1397

**Comment by s0j** [comment]
> Even adding those linker options, I get the following:

Building with the Go build tags `osusergo` and `netgo` should make those warnings disappear.

**Comment by caseydavenport** [comment]
@s0j thanks for the tip. Those tags get rid of most, but not all, of those warnings.

Specifically this one remains:

> /tmp/go-build/cgo-gcc-prolog:58: warning: Using 'getaddrinfo' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking

I'll see if I can find any other tag that resolves this.

**Comment by lwr20** [comment]
@caseydavenport any update here?

**Comment by soider** [comment]
@caseydavenport any new info?

**Comment by caseydavenport** [comment]
No new info. I think the only option I know of at the moment is to produce two builds - one statically compiled, and one dynamically compiled. 

Alternatively we could maybe ship the libraries within the container and do some funky linux magic a la chroot, etc to get the dynamic binary to work, but that needs some more thought / prototyping and I'm not confident will work.

**Comment by peterhoneder** [comment]
> No new info. I think the only option I know of at the moment is to produce two builds - one statically compiled, and one dynamically compiled.
> 
> Alternatively we could maybe ship the libraries within the container and do some funky linux magic a la chroot, etc to get the dynamic binary to work, but that needs some more thought / prototyping and I'm not confident will work.

I would be happy to see that, switching to another image is trivial and also trivial for debugging and understanding what happens.

**Comment by ecrousseau** [comment]
This issue (I believe) forced me to roll back to v3.20. The calico-node pod log is attached below,

[log.txt](https://github.com/projectcalico/calico/files/8327107/log.txt)

Other details that might be relevant:
Calico version v3.22
Calico config was straight out of the box from https://projectcalico.docs.tigera.io/manifests/calico.yaml, aside from changing `CALICO_IPV4POOL_CIDR` to match my cluster's pod network CIDR.
Kubernetes v1.23.0
Cluster bootstrapped using kubeadm
OS is Ubuntu 20.04.4

Calico v3.20 is working just fine.

**Comment by caseydavenport** [comment]
PR in progress to produce two builds - one static and one dynamic: https://github.com/projectcalico/calico/pull/5826
