### ISSUE TITLE
Support dual-stack when `"subnet": "usePodCidr",`

### ISSUE THREAD

**Issue by manuelbuil** [projectcalico/calico#5188]
## Expected Behavior

When using a dual-stack pod-cidr, pods should have two ips in the network interface, one ipv4 and one ipv6

## Current Behavior

When using a dual-stack pod-cidr, pods have only one ipv4 address

## Possible Solution

Fetch node.Spec.PodCIDRs instead of node.Spec.PodCIDR in https://github.com/projectcalico/cni-plugin/blob/v3.19.2/pkg/k8s/k8s.go#L894-L909 and then adapt the code https://github.com/projectcalico/cni-plugin/blob/v3.19.2/internal/pkg/utils/utils.go#L332-L340 to process a slice instead of a string 

## Steps to Reproduce (for bugs)

1. Deploy k8s with a dual-stack pod-cidr (e.g. cluster-cidr: 10.42.0.0/16,2001:cafe:42:0::/56)
2. Use canal with the ipam config:
              "type": "host-local",
              "subnet": "usePodCidr"

## Your Environment

* CNI plugin version: 3.19.2
* Orchestrator version: Kubernetes 1.21.5
* Operating System and version: Ubuntu
* Link to your project (optional): https://github.com/rancher/rke2/issues/1883

**Comment by caseydavenport** [comment]
PR for this has been merged, will be available in v3.22
