### ISSUE TITLE
Allow configuration of MAC address per-pod

### ISSUE THREAD

**Issue by lelvisl** [projectcalico/calico#5196]
I have some legacy, that wants a permanent Mac address. How I can set MAC address for specific container/pod?

**Comment by caseydavenport** [comment]
I think we could resolve this by introducing a new annotation that can be set for a pod.

```
cni.projectcalico.org/hwAdddress
```

It might get complicated when thinking about multi-network support, but we have other annotations to consider there as well so we'll need to figure that out anyway. I assume you want this MAC to be the veth within the container, yeah?

**Comment by lelvisl** [comment]
Yes)

**Comment by KlavsKlavsen** [comment]
We would love this as well - as we too have dockerized license crap software that checks interface mac before it wants to run (which works fine in docker - but we need to be able to move to kubernetes :)
