### ISSUE TITLE
Use pagination when listing pods

### ISSUE THREAD

**Issue by guoshimin** [projectcalico/calico#5205]
## Expected Behavior
When using the kubernetes backend, confd should be able to come up even when there is a large number of pods.

## Current Behavior
As part of initialization, confd lists all pods. When there is a large number of pods, it is observed on EKS that the kubernetes master may close the connection before the listing is complete. Got the following repeatedly in calico-node log:
```
2020-07-31 23:24:26.131 [INFO][163] watchercache.go 188: Failed to perform list of current data during resync ListRoot="/calico/resources/v3/projectcalico.org/workloadendpoints" error=Stream error http2.StreamError{StreamID:0x9, Code:0x2, Cause:error(nil)} when reading response body, may be caused by closed connection. Please retry.
```

## Possible Solution
Use pagination when listing pods. client-go provides a pager: https://github.com/kubernetes/client-go/blob/203d909765c952c466d36786ec7adf13d40f2281/tools/pager/pager.go, and here's how it's used:
https://github.com/kubernetes/client-go/blob/5f4e5d88ae20e638d5ef85d7239d19d21305cf7e/tools/cache/reflector.go#L264

## Steps to Reproduce (for bugs)
Not guaranteed to reproduce. We are on EKS, and saw this when we had about 2300 pods in a cluster. 

## Your Environment

* libcalico-go version: 3.1
* Operating System and version: Ubuntu 18.04
* Link to your project (optional):

**Comment by caseydavenport** [comment]
We implemented this in v3.21
