### ISSUE TITLE
calico/typha is reconnecting without any back-off mechanism

### ISSUE THREAD

**Issue by istvanballok** [projectcalico/calico#5215]
We observed that when the kubernetes api server is not available,
`calico/typha` is trying to reconnect to the kubernetes server
without any back-off mechanism and it can easily reach 1k connection attempts/s.

Would it be possible to throttle the retries to about 100/s or 10/s?

We are concerned about a possible overload issue on our reverse proxy
in the network path, which is shared by several kubernetes api servers.

## Expected Behavior

The reconnect attempts are throttled.

## Current Behavior

<img width="1198" alt="image" src="https://user-images.githubusercontent.com/23032437/109503299-613ef400-7a9a-11eb-9d60-bff95698270d.png">

Calico/typha maintains a high reconnect rate indefinitely.

## Possible Solution

Throttle the reconnect attempts.

## Steps to Reproduce (for bugs)

1. Monitor the connection establishment attempts by the `calico/typha` pod
2. Stop the kubernetes api server

## Context

We are introducing a feature where the network path to the hosted api servers
share a load balancer and a few reverse proxies,
and we are concerned that this thundering herd behavior might lead to a DDoS attack.

Related issue: https://github.com/projectcalico/felix/issues/324#issuecomment-111108710

## Your Environment

* And/Or, `calico/typha` container version (if running Typha in a container): `v3.13.5`
* Which orchestrator are you using (e.g. Kubernetes, OpenStack, Docker, Mesos): Kubernetes
* Orchestrator version (if used): `1.20.2`

**Comment by fasaxc** [comment]
This should be fixed in the upcoming Calico v3.23.0 release.  I added a throttle that prevents us from looping more often than 500ms.  Avoids a 100ms delay in the happy case but should do the trick if we're hitting the bad case described in this issue.
