### ISSUE TITLE
Request to build multiarch docker images 

### ISSUE THREAD

**Issue by jonstevecg** [projectcalico/calico#5222]
When attempting to use Calico with operator install and enable the apiserver the api pod fails to deploy as no arm64 image is available

```
Events:
  Type     Reason     Age                 From               Message
  ----     ------     ----                ----               -------
  Normal   Scheduled  110s                default-scheduler  Successfully assigned calico-apiserver/calico-apiserver-6ccdbf984d-jz568 to k8s-controller
  Normal   BackOff    21s (x5 over 104s)  kubelet            Back-off pulling image "docker.io/calico/apiserver:master"
  Warning  Failed     21s (x5 over 104s)  kubelet            Error: ImagePullBackOff
  Normal   Pulling    6s (x4 over 107s)   kubelet            Pulling image "docker.io/calico/apiserver:master"
  Warning  Failed     4s (x4 over 105s)   kubelet            Failed to pull image "docker.io/calico/apiserver:master": rpc error: code = Unknown desc = no matching manifest for linux/arm64/v8 in the manifest list entries
  Warning  Failed     4s (x4 over 105s)   kubelet            Error: ErrImagePull
```

**Comment by frozenprocess** [comment]
Merged https://github.com/projectcalico/calico/pull/5386

**Comment by caseydavenport** [comment]
apiserver is still missing some other arch, but this issue can be closed for now.

**Comment by jonstevecg** [comment]
That's great thanks very much... however, I see the following currently:

`Events:
  Type     Reason     Age                    From               Message
  ----     ------     ----                   ----               -------
  Normal   Scheduled  3m49s                  default-scheduler  Successfully assigned calico-apiserver/calico-apiserver-6fdddbdc9c-gr5xg to k8s-worker03
  Normal   Pulling    2m11s (x4 over 3m46s)  kubelet            Pulling image "docker.io/calico/apiserver:v3.21.4"
  Warning  Failed     2m9s (x4 over 3m45s)   kubelet            Failed to pull image "docker.io/calico/apiserver:v3.21.4": rpc error: code = Unknown desc = no matching manifest for linux/arm64/v8 in the manifest list entries
  Warning  Failed     2m9s (x4 over 3m45s)   kubelet            Error: ErrImagePull
  Warning  Failed     117s (x6 over 3m44s)   kubelet            Error: ImagePullBackOff
  Normal   BackOff    105s (x7 over 3m44s)   kubelet            Back-off pulling image "docker.io/calico/apiserver:v3.21.4"
`
