### ISSUE TITLE
Using dikastes sidecar in kubernetes jobs

### ISSUE THREAD

**Issue by nohajc** [projectcalico/calico#5227]
I'm trying out Calico application policy and I've come across an issue with kubernetes jobs.

Basically, I need a way to stop the dikastes sidecar container after the job in primary pod container is finished. Until every pod container is stopped, the job is stuck in NotReady state and never reaches Completed state.
This is already handled in istio-proxy sidecar by exposing an HTTP endpoint /quitquitquit which can be used for exactly this purpose.

Kubernetes support is still lacking (https://github.com/kubernetes/kubernetes/issues/25908) so any workaround would be nice.

**Comment by zander312** [comment]
This is a big deal for us. None of our jobs can complete. @nohajc Any way around this?

**Comment by nohajc** [comment]
@zander312 Actually yes. I have a hacky workaround where I set up shared process namespace for all containers running inside a pod:
https://kubernetes.io/docs/tasks/configure-pod-container/share-process-namespace/

Then I can send SIGTERM directly to dikastes process. The above documentation suggests you should add the `SYS_PTRACE` capability to security context but that's actually only needed if you want to signal processes created by a different user. Instead, I just set UID and GID to 999 which is the user configured in dikastes Dockerfile.

There's just one tiny issue with this approach. The gRPC server running inside the sidecar doesn't exit cleanly but I already submitted a patch which should be included in calico 3.22 release.

**Comment by FischlerA** [comment]
This issue still exists, any idea if or when this will get fixed?

**Comment by caseydavenport** [comment]
Would love to review a PR for this

**Comment by amehta-mstr** [comment]
Thank you @zander312 , you can implement the fix here that you did for EO
