### ISSUE TITLE
Document interactions with firewalld

### ISSUE THREAD

**Issue by readerx** [projectcalico/calico#5232]
## Expected Behavior

between the pod

```
/ # wget 10.254.219.68:80
Connecting to 10.254.219.68:80 (10.254.219.68:80)
wget: can't connect to remote host (10.254.219.68): No route to host
```

## Current Behavior

Communication between pods is normal

## Possible Solution

```
nft add rule inet firewalld filter_FWDO_public_allow ct state state new,untracked accept
```

## Steps to Reproduce (for bugs)

install kubernetes in redhat 8.

```
# install kubelet、kubeadm、kubectl
yum install -y kubelet kubeadm kubectl --disableexcludes=kubernetes
systemctl enable kubelet
systemctl start kubelet

# set firewall
firewall-cmd --zone=public --permanent --add-port={6443,2379,2380,10250,10251,10252}/tcp

# install cluster
kubeadm init   --pod-network-cidr=10.254.0.0/16 --image-repository registry.aliyuncs.com/google_containers

# to start using cluster
mkdir -p $HOME/.kube
sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
sudo chown $(id -u):$(id -g) $HOME/.kube/config

# install calico
kubectl apply -f https://docs.projectcalico.org/manifests/calico.yaml

# with env
- name: FELIX_IPTABLESBACKEND
  value: "NFT"

# use master node
kubectl taint nodes --all node-role.kubernetes.io/master-
```

podA (busybox): 10.254.219.69
podB (nginx): 10.254.219.68，listen 80 tcp port

```
kubectl exec -it podA -- sh

/ # wget 10.254.219.68:80
Connecting to 10.254.219.68:80 (10.254.219.68:80)
wget: can't connect to remote host (10.254.219.68): No route to host
````

## Your Environment

* calico/node version:  v3.17.1
* Operating System and version: Red Hat Enterprise Linux release 8.2 (Ootpa)
* Link to your project (optional):

[https://github.com/kubernetes/kubernetes/issues/97283](https://github.com/kubernetes/kubernetes/issues/97283)

**Comment by caseydavenport** [comment]
We actually do call this out in our docs already. 

> If your Linux distribution comes with installed Firewalld or another iptables manager it should be disabled. These may interfere with rules added by Calico and result in unexpected behavior.

https://projectcalico.docs.tigera.io/getting-started/kubernetes/requirements

**Comment by kainzilla** [comment]
Unfortunately, `firewalld` is the default firewall for RHEL, and since it's so nicely integrated with the rest of RHELs setup including Cockpit controls, it's not something I (and I suspect others) would want to disable in favor of managing the whole-system firewall at the calico level.

I'm hoping that future support to play-nice or workarounds would be available for calico

**Comment by kainzilla** [comment]
* The issue appears to arise from the `firewalld` configuration passed to `nft` preventing fowarding from network interfaces if a fowarding-accept rule doesn't exist for that network interface. Interfaces managed by NetworkManager are placed into zones by default, creating these rules.
* When the Calico network interfaces are removed from NetworkManager control per the Calico instructions [here](https://docs.tigera.io/calico/latest/operations/troubleshoot/troubleshooting#configure-networkmanager), the interfaces no longer exist-by-default in any `firewalld` zones, and the default forwarding-accept rules don't exist as a result.
* With only forwarding denied, pod-to-pod and possibly other types of communication to fail, but most other communication still works such as pod-to-service or pod-to-internet.
* Even though the Calico network interfaces are "Unmanaged" by NetworkManager, they can be explicitly added to the `firewalld` [default zone "trusted"](https://firewalld.org/documentation/man-pages/firewalld.zones.html) to add the missing forward-allow entries. Adding the Calico network interfaces to the trusted zone also means `firewalld` generally shouldn't apply any other rules to them, which should allow Calico to co-exist with `firewalld`.
​
The "cali+" and "tunl+" entries below are wildcard-like entries similar to "cali*" and "tunl*", and this list of interfaces was drawn from the Calico instructions linked above. These rules should catch all present and future randomly-generated Calico network interface names, and keep them in the trusted zone:
​
`firewall-cmd --permanent --zone=trusted --add-interface="cali+"`
`firewall-cmd --permanent --zone=trusted --add-interface="tunl+"`
`firewall-cmd --permanent --zone=trusted --add-interface="vxlan-v6.calico"`
`firewall-cmd --permanent --zone=trusted --add-interface="vxlan.calico"`
`firewall-cmd --permanent --zone=trusted --add-interface="wg-v6.cali"`
`firewall-cmd --permanent --zone=trusted --add-interface="wireguard.cali"`
​
Once added, the changes can be reloaded in place without a restart:
​
`firewall-cmd --reload`
​
If you'd like to check if the interfaces had rules successfully passed through to `nft`, run the following:
​
`nft list chain inet firewalld filter_FWD_trusted_allow`
​
Sample output:
```
table inet firewalld {
	chain filter_FWD_trusted_allow {
		oifname "cali*" accept
		oifname "tunl*" accept
		oifname "vxlan-v6.calico" accept
		oifname "vxlan.calico" accept
		oifname "wg-v6.cali" accept
		oifname "wireguard.cali" accept
	}
}
```

For me, this resolves this issue.
