### ISSUE TITLE
Feature: Allow calico-node to be kubernetes aware

### ISSUE THREAD

**Issue by bradbeam** [projectcalico/calico#5236]
It would be awesome if calico-node had the additional hooks into Kubernetes to integrate with pod probes ( readiness/liveness ). Something to the effect of waiting for a pod to become healthy before advertising the route and removing the route when the pod becomes unhealthy. 

I'm not sure what the common implementation of calico on prem is, but in our implementation we utilize headless services nearly exclusively. The dns provider ( coredns/kubedns ) provides some of the above abstraction where dns queries will not return the container IPs until the service is healthy. However in situations where you're utilizing a static IP ( via ipAddrs/ipAddrsNoIpam or floating ips wink wink ), you can run into situations where the pod is not ready yet however the route gets propagated and begins to receive traffic.

**Comment by caseydavenport** [comment]
Thinking about this more now, I don't think this is the right approach nor really within the scope of Calico.

Pod readiness often relies on routing being set up, so in many cases we'd deadlock waiting for a pod to be ready and the pod waiting for network access before marking itself as ready. 

Services handle unready endpoints natively within Kubernetes, and any alternative Service solution really needs to do the same (by excluding unready endpoints from load balancing).
