### ISSUE TITLE
Support eBPF dataplane on ARM64

### ISSUE THREAD

**Issue by backjo** [projectcalico/calico#5246]
## Expected Behavior

Calico currently provides images for multiple architectures, including ARM64. However, the eBPF dataplane today only works on the AMD64 architecture. It's unclear if this is intended, or just an oversight. See https://github.com/projectcalico/calico/issues/4306
## Current Behavior

eBPF Dataplane is not supported on non-AMD64. Binaries for all non-AMD64 platforms appear to be cross-compiled today with CGO_ENABLED=0, which will cause the BPF syscalls to be stubbed, using the bpf_syscall_stub.go file. This causes the eBPF dataplane to be unusable, since the stub will return False for SyscallSupport(), which prevents enabling of the dataplane.

## Possible Solution

Build non-AMD64 binaries using BuildKit, which will allow compilation to happen in an environment where CGO can be enabled for architectures other than the host operating system. 

## Steps to Reproduce (for bugs)

1. Try to enable Calico eBPF DataPlane on ARM64
2. See error in logs about being unable to enable eBPF due to 'unsupported kernel'

## Your Environment

* Felix version (if using Felix binary directly `calico-felix --version`): 3.17.2
* And/Or, `calico/node` container version (if running Felix in a container):
* Which orchestrator are you using (e.g. Kubernetes, OpenStack, Docker, Mesos): Kubernetes(EKS)
* Orchestrator version (if used): 1.19
* Etcd version (if using etcd datastore driver):
* Operating System and version: BottleRocket OS 1.0.5, Linux Kernel 5.4.80
* Link to your project (optional):

**Comment by caseydavenport** [comment]
@frozenprocess @fasaxc what's left to support this?

I thought @frozenprocess did some work a while back to make this possible but by the sounds of it this might still need something else?

**Comment by frozenprocess** [comment]
This PR https://github.com/projectcalico/node/pull/1044 added required changes for arm64 eBPF support.

Tutorial available here : https://github.com/frozenprocess/Tigera-Presentations/tree/master/2021-10-15.Utah.Meetup.Multiarch.clusters.networking

**Comment by caseydavenport** [comment]
So from the sounds of that document, ARM64 eBPF installs should work more or less the same as AMD64 installs do, in Calico v3.21+
