### ISSUE TITLE
Improve WireGuard configuration logging

### ISSUE THREAD

**Issue by hogepodge** [projectcalico/calico#5253]
## Expected Behavior
The WireGuard configuration code path can safely fail at many different points. While configuration failure is logged and handled gracefully, the cause for failures is not necessarily reported. To aid operators in setting up Wireguard, the cause of a failure should be reported as soon as it is detected.

## Current Behavior
For example, in running the tech preview on an Ubuntu node, WireGuard configuration failed. It took sleuthing though the logs and code to find where the configuration failed (on configuring a new netlink), reproducing the failure in the command line, and determining that the kernel module was not loaded. More informative logging would have shortened this process.

## Possible Solution

More descriptive log statements.

## Context
See current behavior section

## Your Environment

* Felix version 3.14.0
* Kubernetes 1.18
* Ubuntu 18.04

**Comment by lwr20** [comment]
@aaaaaaaalex Do you know if this Issue is still valid?  I know we've done a lot of work in this area
