### ISSUE TITLE
Long dataplane apply times in route table apply

### ISSUE THREAD

**Issue by rikatz** [projectcalico/calico#5255]
## Expected Behavior

We've been investigating some high Dataplane Apply times to see what's going on.

Our environment have an average of 600 PODs per node. We've being trying to improve performance and make this possible, even it not being recommended ;)

The Dataplane apply time takes an average of 0.5s, but in some very specific times it takes more than 15s.

Making some digging and brakepointing into the code, we've faced that while applying the dataplane the routine that takes more time is [this](https://github.com/projectcalico/felix/blob/master/dataplane/linux/int_dataplane.go#L1124)

When digging more into this function, we've faced that the [following](https://github.com/projectcalico/felix/blob/master/routetable/route_table.go#L318-L367) part of the code, WHEN CALLED takes that huge amount of time.

What we mean by WHEN? Because this seems an interaction. Sometimes there's no Item to interact and then this piece of code is not called.

But when it's called, the whole array of the iteration calls the ``r.syncRoutesForLink(ifaceName)`` (and all of them with success).

While each call per interface of syncRoutesForLink takes an average of 26ms and a maximum of 113ms, the sum of the times for 400 interfaces is something like 15000ms (15s!).

The question/suggestion of improvement here is:

1) Couldn't those syncRoutesForLink be not serial, but instead run concurrently to drop those requests from 15s to a maximum of 115ms?

2) I couldn't figure out why all interfaces got a syncRoutesForLink instead of only the changed interface (I may be missing something, sorry :( )

It seems, btw that this routes WG does not block IPTables (https://github.com/projectcalico/felix/blob/release-v3.6/dataplane/linux/int_dataplane.go#L936,L949) or anything like that, so it doesn't impact into the rest of dataplane update. 

So may this represent a performance issue or this can be treated just as an improvement?

## Your Environment
* And/Or, `calico/node` container version (if running Felix in a container): 3.6.4
* Which orchestrator are you using (e.g. Kubernetes, OpenStack, Docker, Mesos): Kubernetes
* Orchestrator version (if used): 1.13.4
* Etcd version (if using etcd datastore driver): 3.3
* Operating System and version: CoreOS 2079.6.0

**Comment by fasaxc** [comment]
@rikatz Are you still working with Calico and nodes with many pods?  Think we might finally have a fix for this one: https://github.com/projectcalico/calico/pull/7364.  The kernel API and the netlink library now have support for kernel-side filtering, which is what we need to make our queries fast.

**Comment by rikatz** [comment]
Hey @fasaxc I have changed company almost 2y ago and don't have access to cluster anymore :/ 

@gunboe  do you still have this access and the problem?

**Comment by jcmoraisjr** [comment]
@moacirsouza

**Comment by moacirsouza** [comment]
Hey there @fasaxc. We still have this Cluster running, but it is now in a "frozen" state regarding updates and patches. We've been trying to modify our Clusters infrastructure in favour of smaller, more controlled ones and the upper management don't really want to risk possible disruptive changes until the migration of the major clients end.

I guess we could still try this in our staging environment, which is considerably smaller but still able to work with 400 to 600 pods per node.

@gunboe: We could schedule some testing sessions next week, perhaps?

And thanks for the heads up @jcmoraisjr and @rikatz. Miss you guys 😞

**Comment by fasaxc** [comment]
@moacirsouza Here's the nightly build with the fix: https://2023-02-23-master-sudoku.docs.eng.tigera.net/  (Just grab a manifest with the name that you'd usually use from the manifests directory instead of from the docs.)
