### ISSUE TITLE
Can't run `calicoctl version` without a config

### ISSUE THREAD

**Issue by 06kellyjac** [projectcalico/calico#5260]
## Expected Behavior

```
$ calicoctl version
Client Version:    v3.19.1
Git commit:
(maybe a warning)
```

## Current Behavior

```
$ calicoctl version
Client Version:    v3.19.1
Git commit:
invalid configuration: no configuration has been provided, try setting KUBERNETES_MASTER environment variable
```
(exit code 1)

## Possible Solution

Add some logic to catch the "Invalid configuration" error and just show a warning

## Steps to Reproduce (for bugs)

1. Have no config/Dont provide any config
2. `calicoctl version`

## Context

I'm packaging `calicoctl` for nixpkgs and I like to add a version check by running the command's version flag/argument, in the build sandbox there is no calico config.

I could add a temporary one but I'd rather not

## Your Environment

* calicoctl version (e.g. `calicoctl version`): 3.19.1
* calico/node version (e.g. `docker run --rm calico/node versions`): N/A
* Orchestrator type and version (e.g. kubernetes, mesos, rkt): N/A
* Operating System and version: NixOS
* Link to your project (optional):

**Comment by Akasurde** [comment]
@caseydavenport Can we close this issue since #5455 is merged?

**Comment by caseydavenport** [comment]
Yep good spot
