### ISSUE TITLE
Random failures in bird

### ISSUE THREAD

**Issue by sigxcpu76** [projectcalico/calico#5262]
After a series of various node restarts, sometimes bird fails to move peers to `up` state. sitting in `wait`.
I've noticed that there was a (closed?) ticket for this issue: https://github.com/projectcalico/calicoctl/issues/900

The behaviour described there is identical with what is described there. If a node is down and kept down, other nodes randomly fail to establish the mesh upon restart.
 
## Expected Behavior

BGP mesh to be synchronized upon reboot/restart.

## Current Behavior

Mesh establishing fails randomly.

## Steps to Reproduce (for bugs)

Create a Kubernetes cluster with Calico enabled (default latest `calico.yaml` is fine).
Kill a node and keep it down. Randomly reboot the other nodes (or restart `calico-node` process).
At some point, one of the nodes will fail to push and receive routes to/from the other nodes, seeing them in `wait` state. The connection is `Established` but not routes are exchanged.
Logs on the `calico-node` pods on restart or simply killing `bird` process show that the nodes to in fact see each other going down and up but that's all. No routes are pushed&pulled.

## Context

Pods on the affected nodes are not reachable when this happens.
If the "always down" node is removed from the nodes list, everything works as expected, other nodes not being affected by restarts anymore.

## Your Environment
* calicoctl version (e.g. `calicoctl version`):
```
Client Version:    v3.18.0
Git commit:        5d65da3d
Cluster Version:   v3.17.3
Cluster Type:      k8s,bgp,kubeadm,kdd
```
* calico/node version (e.g. `docker run --rm calico/node versions`)

* Orchestrator type and version (e.g. kubernetes, mesos, rkt):
Kubernetes
* Operating System and version:
Debian 10 (buster)
* Link to your project (optional):

**Comment by caseydavenport** [comment]
I believe that this is BGP behaving as expected per the RFC. I would suggest either switching to VXLAN CrossSubnet, or adjusting your BGP peering topology (i.e., via a ToR) to avoid this scenario altogether.
