### ISSUE TITLE
Significant memory increase in calico typha after update from 3.19 to 3.21

### ISSUE THREAD

**Issue by ScheererJ** [projectcalico/calico#5289]
After upgrading from calico 3.19.x to 3.21.x, we saw a significant increase in the memory usage of calico typha. For most of our kubernetes clusters the increase was above factor 2. While this was not a big issue for smaller clusters, we actually ran into memory limits on bigger clusters as we did not expect the memory increase and memory use of calico typha seems to scale with the number of nodes/pods.

## Expected Behavior

The memory usage of the calico components should stay more or less the same unless described otherwise in the release notes.

## Current Behavior

Between calico 3.19.x and calico 3.21.x, there seem to be changes that cause a quite significant (> 2x) memory increase in the usage of calico typha.

## Possible Solution

Investigate the memory increase or at least document the increased memory requirements.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Context

We operate quite a few kubernetes clusters with a variety in terms of workload and cluster size.

## Your Environment

* Calico version 3.21.1
* Orchestrator version (e.g. kubernetes, mesos, rkt): kubernetes 1.18.x - 1.22.x
* Operating System and version:
* Link to your project (optional):

**Comment by PhilipMay** [comment]
I also notice a significant memory usage with 3.21.2

I have a "bare metal" kubeadm install on Debian 11. 

```text
$ k top pods -A
NAMESPACE         NAME                                       CPU(cores)   MEMORY(bytes)   
calico-system     calico-kube-controllers-59c45ff85c-g4n7s   5m           17Mi            
calico-system     calico-node-hpz6l                          25m          133Mi           
calico-system     calico-node-pxxzr                          44m          120Mi           
calico-system     calico-node-v6j7g                          22m          121Mi           
calico-system     calico-typha-85667c79d-8ltn9               3m           29Mi            
calico-system     calico-typha-85667c79d-gkrqp               2m           29Mi            
kube-system       coredns-64897985d-7zg9f                    2m           20Mi            
kube-system       coredns-64897985d-r5rwl                    2m           17Mi            
kube-system       etcd-master1                               49m          88Mi            
kube-system       etcd-master2                               55m          92Mi            
kube-system       etcd-master3                               46m          85Mi            
kube-system       kube-apiserver-master1                     126m         430Mi           
kube-system       kube-apiserver-master2                     54m          370Mi           
kube-system       kube-apiserver-master3                     56m          316Mi           
kube-system       kube-controller-manager-master1            24m          77Mi            
kube-system       kube-controller-manager-master2            3m           47Mi            
kube-system       kube-controller-manager-master3            3m           44Mi            
kube-system       kube-proxy-7zmvq                           1m           36Mi            
kube-system       kube-proxy-hdvv5                           1m           30Mi            
kube-system       kube-proxy-zzkzx                           1m           34Mi            
kube-system       kube-scheduler-master1                     4m           35Mi            
kube-system       kube-scheduler-master2                     4m           43Mi            
kube-system       kube-scheduler-master3                     3m           38Mi            
metrics-server    metrics-server-5847bdf876-2c2jx            4m           19Mi            
tigera-operator   tigera-operator-59d6fdcd79-5ppgf           20m          37Mi       
```

**Comment by caseydavenport** [comment]
If I had to guess, I would say this is likely a result of sending kubernetes EndpointSlices through Typha, which was introduced in v3.21. EndpointSlices grow with the number of pods selected by Services in the cluster, so for larger clusters with lots of services and pods this may use a fair bit more.

**Comment by PhilipMay** [comment]
> If I had to guess, I would say this is likely a result of sending kubernetes EndpointSlices through Typha, which was introduced in v3.21. EndpointSlices grow with the number of pods selected by Services in the cluster, so for larger clusters with lots of services and pods this may use a fair bit more.

Well. In my case the cluster is new and has no services at all.

**Comment by caseydavenport** [comment]
@PhilipMay even a fresh install will have services on it - kube-dns and a number of Calico services, for one - increase shouldn't be much but there will be some. Looks like typha pods are sitting at 29Mi, which seems roughly correct looking at usage of other components running on the cluster.

**Comment by lwr20** [comment]
I wonder if this could be a consequence of https://github.com/projectcalico/calico/issues/5173.  
That'll be in v3.21.3 (which is due out very shortly)

**Comment by ScheererJ** [comment]
@lwr20 At least for us, we saw the memory increase (factor 2-3) always directly, but only some (around 1%) of the clusters showed the symptoms of #5173, i.e. stale typha causing removal of route table entries.

**Comment by fasaxc** [comment]
Closing as stale, either fixed or it's the "new normal" with endpoint slices so we'd need to do extra work to compress/reduce it.
