### ISSUE TITLE
Windows direct pod connectivity  from linux->windows (or maybe windows->windows) pods on 3.19.2 hangs...

### ISSUE THREAD

**Issue by jayunit100** [projectcalico/calico#5299]
## Expected Behavior

Horizontal pod networking between linux -> windows would work for pods... 

INTERESTINGLY 
- Traffic through the service proxy works fine...
```
vagrant@controlplane:~$ kubectl get svc -o wide
NAME             TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)   AGE     SELECTOR
headless-svc     ClusterIP   None             <none>        80/TCP    5m45s   app=nginx
kubernetes       ClusterIP   10.96.0.1        <none>        443/TCP   20m     <none>
nginx            ClusterIP   10.102.202.69    <none>        80/TCP    19m     app=nginx
whoami-windows   ClusterIP   10.109.226.159   <none>        80/TCP    19m     app=whoami-windows
```
like so
```
/ # wget  10.109.226.159
Connecting to 10.109.226.159 (10.109.226.159:80)
index.html           100% |****************************************************************************|  2238   0:00:00 ETA
```

- but traffic to pod to pod fails

```
/ # wget 100.244.206.69
Connecting to 100.244.206.69 (100.244.206.69:80)
```

# QUESTION 

*whats different about the path through the kube proxy compared to the raw pod<->pod networking path???* 

## Steps to Reproduce (for bugs)

- grab the dev tools `git clone https://github.com/kubernetes-sigs/sig-windows-dev-tools`

- patch the YAML
```
+++ b/forked/calico.yaml
@@ -3544,7 +3544,7 @@ spec:

-          image: docker.io/calico/cni:v3.19.1
+          image: docker.io/calico/cni:v3.19.2

-          image: docker.io/calico/cni:v3.19.1
+          image: docker.io/calico/cni:v3.19.2

-          image: docker.io/calico/pod2daemon-flexvol:v3.19.1
+          image: docker.io/calico/pod2daemon-flexvol:v3.19.2

-          image: docker.io/calico/node:v3.19.1
+          image: docker.io/calico/node:v3.19.2

-          image: docker.io/calico/kube-controllers:v3.19.1
+          image: docker.io/calico/kube-controllers:v3.19.2
```

- then try to curl down the default windows pods from a busybox pod, youll see it isnt reachable 

.... IRONICALLY you CAN curl through the service proxy though!!!!!!!!!!!!!

## Your Environment
* Calico version
* Orchestrator version (e.g. kubernetes, mesos, rkt):
* Operating System and version:
* Link to your project (optional):

**Comment by caseydavenport** [comment]
@jayunit100 thanks for raising! 

CC @song-jiang @lmm 

Our main Windows devs are on PTO for the holidays but we can look into this when they're back :)

**Comment by jayunit100** [comment]
np ! we're a/b testing on 3.19..... will keep you posted

**Comment by jayunit100** [comment]
Update, from jamie, just showed me this is interesting,

```
          "Source": "{\"cniVersion\":\"0.3.1\",\"name\":\"Calico\",\"plugins\":[{\"DNS\":{\"Nameservers\":[\"10.96.0.10\"],\"Search\":[\"sv
c.cluster.local\"]},\"capabilities\":{\"dns\":true},\"cniVersion\":\"0.3.1\",\"datastore_type\":\"kubernetes\",\"etcd_ca_cert_file\":\"\\u0
03cyour etcd ca cert\\u003e\",\"etcd_cert_file\":\"\\u003cyour etcd cert\\u003e\",\"etcd_endpoints\":\"\\u003cyour etcd endpoints\\u003e\",
\"etcd_key_file\":\"\\u003cyour etcd key\\u003e\",\"ipam\":{\"subnet\":\"usePodCidr\",\"type\":\"calico-ipam\"},\"kubernetes\":{\"kubeconfi
g\":\"C:/etc/kubernetes/kubelet.conf\"},\"log_level\":\"info\",\"mode\":\"vxlan\",\"name\":\"Calico\",\"nodename_file\":\"C:\\\\CalicoWindo
ws\\\\libs\\\\calico\\\\..\\\\..\\\\nodename\",\"policies\":[{\"Name\":\"EndpointPolicy\",\"Value\":{\"ExceptionList\":[\"10.96.0.0/12\"],\
"Type\":\"OutBoundNAT\"}},{\"Name\":\"EndpointPolicy\",\"Value\":{\"DestinationPrefix\":\"10.96.0.0/12\",\"NeedEncap\":true,\"Type\":\"SDNR
OUTE\"}}],\"policy\":{\"type\":\"k8s\"},\"type\":\"calico\",\"vxlan_mac_prefix\":\"0E-2A\",\"vxlan_vni\":4096,\"windows_use_single_network\
":true}]}"
        },
        "IFName": "eth0"
      }

```

We have an eth0 being stuck into the windows nodes, to see this on the above setup, you can run 

```
.\crictl config --set runtime-endpoint=npipe:////./pipe/containerd-containerd
```

**Comment by song-jiang** [comment]
@jayunit100 Hmm... if `Linux pod -> Windows Service` works then `Linux pod -> Windows Pod` should work by default. Kube-proxy service IP DNAT is done on Linux node and Windows node/pod should see no difference. 

In your setup, would `Linux pod -> Linux pod` work?

**Comment by phillipsj** [comment]
Yes, works Linux pod to Linux pod.

**Comment by song-jiang** [comment]
I suggest to tcpdump on the Linux node on the main network interface (`eth0`) for `service IP access` and `pod IP access`. With kube-proxy DNAT, we should see both outgoing traffic has the same tuple (src: Linux pod, dest:Windows pod). If we failed to see outgoing packet for `pod IP access`, the issue is on the Linux side, otherwise we can look into Windows node.

**Comment by jayunit100** [comment]
ill bump sig-windows-dev-tools to 1.20.2, per @lmonson and @phillipsj this is a non issue in other versions, will let folks know if that is confirmed on our end.

agree song it seems like generally it should work the same wether DNAT via proxy or direct
