### ISSUE TITLE
Can any one explain how would i use Project Calico for CNI in my nomad cluster

### ISSUE THREAD

**Issue by codesiddhant** [projectcalico/calico#5335]
Reference -> [https://www.hashicorp.com/blog/multi-interface-networking-and-cni-plugins-in-nomad-0-12](https://www.hashicorp.com/blog/multi-interface-networking-and-cni-plugins-in-nomad-0-12)

![image](https://user-images.githubusercontent.com/54833015/147346151-b093ca8e-7e7f-40e9-bcd6-3b189fa0d773.png)

**My Problem** -> I want to connect all My containers across multiple clients(Nodes) in the nomad cluster. In my current Kubernetes cluster, all pods can communicate to each other based on IP address no matter they are deployed in different machines (worker) using CNI (Calico / Cilium / Funnel, etc).

The same thing I want to achieve in Nomad Cluster not only for docker containers but other plugins also including firecracker, qemu, etc.

**What I want** ->  All Resources (Container, MicroVm, Vms) should be able to communicate with each other based on IP Addresses under the same subnet across the entire cluster| Simply speaking I want SDN Solution in my cluster. 

**What I am trying to do** actually I trying to make my own private cloud that can support multiple types of technology including docker, microVM, LXC/LXD container, and KVM as like [Opennebula](https://opennebula.io/discover/). with the help of the Nomad cluster. 

**how will I be able to access instances (VMs)**  for accessing VMS through (SSH/VNC/RDP) with the help of open-source tool [Apache Guacamole](https://guacamole.apache.org/) but the condition is that every VM should be able to communicate with each other to make **Guacd proxy**  work possible.  

**What is my expectation** I am wondering how will one can use Calico as CNI in the nomad cluster. I searched the entire internet but still didn't find any conclusive. 

There is mention of Calico in nomad official documentation ([Blog](https://www.hashicorp.com/blog/multi-interface-networking-and-cni-plugins-in-nomad-0-12)) but I want a more detailed explanation about that. 

Please someone help me out with this including all alternative possibilities.
Billion thanks in advance :innocent:

**Comment by caseydavenport** [comment]
I don't think anyone on the Calico core team have deployed with Nomad before, although I know I have seen other users doing so in the past. 

I would expect that at a very high level you would need to do something like the following:

- Run an etcd instance for Calico to store its configuration and state in.
- Install the CNI plugin binaries and a suitable CNI plugin config file pointing it at etcd, in the place that nomad expects.
- Run calico/node as a container on each node in your nomad cluster, pointing it at etcd.
