### ISSUE TITLE
calico-node   CrashLoopBackOff

### ISSUE THREAD

**Issue by xiaobinggan-zmh** [projectcalico/calico#5343]
**k8s-mec@k8smec:~/a-ZMH-mano$ sudo kubectl get pods -n kube-system**
```
NAME                                       READY   STATUS             RESTARTS   AGE
calico-kube-controllers-85dbf657bb-ncvtv   0/1     CrashLoopBackOff   9          19m
calico-node-2r7cc                          0/1     CrashLoopBackOff   8          17m
calico-node-p69zn                          1/1     Running            0          25m
calico-node-swhnp                          1/1     Running            0          25m
calico-node-wb2h6                          0/1     CrashLoopBackOff   9          25m
coredns-f9fd979d6-8tx89                    1/1     Running            0          18m
coredns-f9fd979d6-tqgkf                    0/1     Running            0          54m
etcd-k8smec                                1/1     Running            1          2d
kube-apiserver-k8smec                      1/1     Running            1          39h
kube-controller-manager-k8smec             1/1     Running            2          2d
kube-proxy-2sn24                           1/1     Running            3          25h
kube-proxy-67x2t                           1/1     Running            1          2d
kube-proxy-j972m                           1/1     Running            1          14h
kube-proxy-zc2bw                           1/1     Running            1          2d
kube-scheduler-k8smec                      1/1     Running            2          2d
```

**k8s-mec@k8smec:~/a-ZMH-mano$ sudo kubectl logs -f calico-node-2r7cc -n kube-system**
```
2021-12-29 04:20:10.839 [INFO][9] startup/startup.go 379: Early log level set to info
2021-12-29 04:20:10.839 [INFO][9] startup/startup.go 395: Using NODENAME environment for node name
2021-12-29 04:20:10.839 [INFO][9] startup/startup.go 407: Determined node name: node3
2021-12-29 04:20:10.842 [INFO][9] startup/startup.go 439: Checking datastore connection
2021-12-29 04:20:10.856 [INFO][9] startup/startup.go 463: Datastore connection verified
2021-12-29 04:20:10.856 [INFO][9] startup/startup.go 112: Datastore is ready
2021-12-29 04:20:10.876 [INFO][9] startup/startup.go 505: Initialize BGP data
2021-12-29 04:20:10.877 [WARNING][9] startup/startup.go 769: Unable to auto-detect an IPv4 address using interface regexes [enp2s0]: no valid host interfaces found
2021-12-29 04:20:10.878 [WARNING][9] startup/startup.go 527: Couldn't autodetect an IPv4 address. If auto-detecting, choose a different autodetection method. Otherwise provide an explicit address.
2021-12-29 04:20:10.878 [INFO][9] startup/startup.go 343: Clearing out-of-date IPv4 address from this node IP=""
2021-12-29 04:20:10.890 [WARNING][9] startup/startup.go 1331: Terminating
Calico node failed to start

```

**k8s-mec@k8smec:~/a-ZMH-mano$ sudo kubectl describe pods calico-node-2r7cc -n kube-system**
```
Events:
  Type     Reason     Age                   From               Message
  ----     ------     ----                  ----               -------
  Normal   Scheduled  22m                   default-scheduler  Successfully assigned kube-system/calico-node-2r7cc to node3
  Normal   Pulled     22m                   kubelet            Container image "docker.io/calico/cni:v3.17.1" already present on machine
  Normal   Created    22m                   kubelet            Created container upgrade-ipam
  Normal   Started    22m                   kubelet            Started container upgrade-ipam
  Normal   Pulled     22m                   kubelet            Container image "docker.io/calico/cni:v3.17.1" already present on machine
  Normal   Created    22m                   kubelet            Created container install-cni
  Normal   Started    22m                   kubelet            Started container install-cni
  Normal   Pulled     22m                   kubelet            Container image "docker.io/calico/pod2daemon-flexvol:v3.17.1" already present on machine
  Normal   Created    22m                   kubelet            Created container flexvol-driver
  Normal   Started    22m                   kubelet            Started container flexvol-driver
  Normal   Created    22m (x3 over 22m)     kubelet            Created container calico-node
  Normal   Started    22m (x3 over 22m)     kubelet            Started container calico-node
  Normal   Pulled     21m (x4 over 22m)     kubelet            Container image "docker.io/calico/node:v3.17.1" already present on machine
  Warning  BackOff    2m14s (x99 over 22m)  kubelet            Back-off restarting failed container
```

**k8s-mec@k8smec:~/a-ZMH-mano$ sudo kubectl version**
```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:50:19Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:41:49Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by xiaobinggan-zmh** [comment]
> **k8s-mec@k8smec:~/a-ZMH-mano$ sudo kubectl get pods -n kube-system** NAME READY STATUS RESTARTS AGE calico-kube-controllers-85dbf657bb-ncvtv 0/1 CrashLoopBackOff 9 19m calico-node-2r7cc 0/1 CrashLoopBackOff 8 17m calico-node-p69zn 1/1 Running 0 25m calico-node-swhnp 1/1 Running 0 25m calico-node-wb2h6 0/1 CrashLoopBackOff 9 25m coredns-f9fd979d6-8tx89 1/1 Running 0 18m coredns-f9fd979d6-tqgkf 0/1 Running 0 54m etcd-k8smec 1/1 Running 1 2d kube-apiserver-k8smec 1/1 Running 1 39h kube-controller-manager-k8smec 1/1 Running 2 2d kube-proxy-2sn24 1/1 Running 3 25h kube-proxy-67x2t 1/1 Running 1 2d kube-proxy-j972m 1/1 Running 1 14h kube-proxy-zc2bw 1/1 Running 1 2d kube-scheduler-k8smec 1/1 Running 2 2d
> 
> **k8s-mec@k8smec:~/a-ZMH-mano$ sudo kubectl logs -f calico-node-2r7cc -n kube-system** 2021-12-29 04:20:10.839 [INFO][9] startup/startup.go 379: Early log level set to info 2021-12-29 04:20:10.839 [INFO][9] startup/startup.go 395: Using NODENAME environment for node name 2021-12-29 04:20:10.839 [INFO][9] startup/startup.go 407: Determined node name: node3 2021-12-29 04:20:10.842 [INFO][9] startup/startup.go 439: Checking datastore connection 2021-12-29 04:20:10.856 [INFO][9] startup/startup.go 463: Datastore connection verified 2021-12-29 04:20:10.856 [INFO][9] startup/startup.go 112: Datastore is ready 2021-12-29 04:20:10.876 [INFO][9] startup/startup.go 505: Initialize BGP data 2021-12-29 04:20:10.877 [WARNING][9] startup/startup.go 769: Unable to auto-detect an IPv4 address using interface regexes [enp2s0]: no valid host interfaces found 2021-12-29 04:20:10.878 [WARNING][9] startup/startup.go 527: Couldn't autodetect an IPv4 address. If auto-detecting, choose a different autodetection method. Otherwise provide an explicit address. 2021-12-29 04:20:10.878 [INFO][9] startup/startup.go 343: Clearing out-of-date IPv4 address from this node IP="" 2021-12-29 04:20:10.890 [WARNING][9] startup/startup.go 1331: Terminating Calico node failed to start
> 
> **k8s-mec@k8smec:~/a-ZMH-mano$ sudo kubectl describe pods calico-node-2r7cc -n kube-system** Events: Type Reason Age From Message
> 
> Normal Scheduled 22m default-scheduler Successfully assigned kube-system/calico-node-2r7cc to node3 Normal Pulled 22m kubelet Container image "docker.io/calico/cni:v3.17.1" already present on machine Normal Created 22m kubelet Created container upgrade-ipam Normal Started 22m kubelet Started container upgrade-ipam Normal Pulled 22m kubelet Container image "docker.io/calico/cni:v3.17.1" already present on machine Normal Created 22m kubelet Created container install-cni Normal Started 22m kubelet Started container install-cni Normal Pulled 22m kubelet Container image "docker.io/calico/pod2daemon-flexvol:v3.17.1" already present on machine Normal Created 22m kubelet Created container flexvol-driver Normal Started 22m kubelet Started container flexvol-driver Normal Created 22m (x3 over 22m) kubelet Created container calico-node Normal Started 22m (x3 over 22m) kubelet Started container calico-node Normal Pulled 21m (x4 over 22m) kubelet Container image "docker.io/calico/node:v3.17.1" already present on machine Warning BackOff 2m14s (x99 over 22m) kubelet Back-off restarting failed container
> 
> **k8s-mec@k8smec:~/a-ZMH-mano$ sudo kubectl version** Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:50:19Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"} Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:41:49Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}

**Comment by caseydavenport** [comment]
> 2021-12-29 04:20:10.877 [WARNING][9] startup/startup.go 769: Unable to auto-detect an IPv4 address using interface regexes [enp2s0]: no valid host interfaces found

Calico is attempting to detect an IP address from an interface that doesn't exist - you should update Calico's IP autodetection method to use an interface that does exist on the node, or another method.

**Comment by jeanflorentine** [comment]
Hi ,

I get the error although the eth1 interface doesd exist.
What is the syntaxe to provide a master explicit IP address.

2022-12-29 10:44:25.000 [INFO][9] startup/customresource.go 102: Error getting resource Key=GlobalFelixConfig(name=CalicoVersion) Name="calicoversion" Resource="GlobalFelixConfigs" error=the server could not find the requested resource (get GlobalFelixConfigs.crd.projectcalico.org calicoversion)
2022-12-29 10:44:25.004 [INFO][9] startup/startup.go 485: Initialize BGP data
2022-12-29 10:44:25.004 [WARNING][9] startup/autodetection_methods.go 113: Unable to auto-detect an IPv4 address using interface regexes [eth1]: no valid IPv4 addresses found on the host interfaces
2022-12-29 10:44:25.004 [WARNING][9] startup/startup.go 507: Couldn't autodetect an IPv4 address. If auto-detecting, choose a different autodetection method. Otherwise provide an explicit address.
