### ISSUE TITLE
Blocks get wrongfully cleaned up in Flannel to Calico migration

### ISSUE THREAD

**Issue by squ94wk** [projectcalico/calico#5349]
We're trying the Flannel to Calico migration on a ~17 node dev cluster running Flannel 0.11 and K8s 1.21.5.
I observed the following problem:
"In the middle of the migration", some inter-pod communication breaks.

I nailed it down to this:
Pod-subnet is 10.244.0.0/16.
There are two nodes, one migrated one, one still running flannel.
On the latter, flannel allocates from the 10.244.2.0/24 block. It has a running Pod with the IP 10.244.2.242.
That would fall in the 10.244.2.192/26 block in Calico's world.

When the migration starts, IPAMBlocks get created for all the /26 blocks within the "old" /24 blocks flannel used for all nodes. I can see that in the logs of the migration-job and also running `kubectl get blockaffinities -w`.

But shorty after, most of the blocks get removed again. There are only 10.244.x.0/26 blocks left.
This means that on migrated nodes there are no routes (`ip r`) to the pod with IP 10.244.2.242. The only route to that node is for 10.244.2.0/26.
This breaks communication from migrated nodes to 3/4 of pods on nodes that haven't been migrated yet (migrated nodes are unaffected, since Calico would only allocate from affined blocks).

## Expected Behavior
Blocks should remain for all Pod IPs in use, whether assigned through Calico or "any other" CNI.

## Current Behavior
Only 10.244.x.0/26 blocks remain.

## Possible Solution
I'm not familiar with the Calico codebase nor were I familiar how Calico handles IPAM before today.
But I can imagine that this could be a regression from some improvement of unused block clean up.

## Steps to Reproduce (for bugs)
See description. I can also provide more detailed information if needed.

## Context
We need to migrate away from Flannel because we need to use NetworkPolicies to improve security.
A migration with downtime was currently not an option, but we might consider it given the migration would break critical HA setups, because peers can't communicate with each other.

## Your Environment

* Calico version = not sure which one the migration is actually using
* Orchestrator version (e.g. kubernetes, mesos, rkt): stock Kubernetes 1.21.5
* Operating System and version: Ubuntu 20.04
* Link to your project (optional): n.a.

**Comment by squ94wk** [comment]
I found a dirty hack to get it to work.
I just removed the `delete` verb from the permissions in the `calico-kube-controllers` ClusterRole.
This way the controller can't clean up the IPAMBlocks and the routes are preserved.

@caseydavenport It seems to work fine. Can you think of any issues that this might introduce?
I'm obviously planning to put the permission back into place once Calico manages all Pod's IPs.

In the controllers' log I find these errors:
```
2022-01-07 11:37:50.602 [INFO][1] ipam.go 572: Releasing affinity for empty block (node has 4 total blocks) blockCIDR="10.244.19.128/26" node="worker4-dev"                                                                                                                                   2022-01-07 11:37:51.803 [WARNING][1] ipam_block_reader_writer.go 316: Error getting block error=connection is unauthorized: ipamblocks.crd.proj
ectcalico.org "10-244-19-128-26" is forbidden: User "system:serviceaccount:kube-system:calico-kube-controllers" cannot delete resource "ipamblocks" in API group "crd.projectcalico.org" at the cluster scope host="worker4-dev" subnet="10.244.19.128/26"
2022-01-07 11:37:51.803 [ERROR][1] ipam.go 1311: Error releasing affinity cidr=10.244.19.128/26 error=connection is unauthorized: ipamblocks.crd.projectcalico.org "10-244-19-128-26" is forbidden: User "system:serviceaccount:kube-system:calico-kube-controllers" cannot delete resource "ipamblocks" in API group "crd.projectcalico.org" at the cluster scope                                                                           
2022-01-07 11:37:51.803 [WARNING][1] ipam.go 579: unable or unwilling to release affinity for block blockCIDR="10.244.19.128/26" error=connecti
on is unauthorized: ipamblocks.crd.projectcalico.org "10-244-19-128-26" is forbidden: User "system:serviceaccount:kube-system:calico-kube-contr
ollers" cannot delete resource "ipamblocks" in API group "crd.projectcalico.org" at the cluster scope node="worker4-dev"
```
So I assume, Calico by default cleans up blocks without any IPs in use.

I might be able to create a patch that disables this during a migration.

**Comment by caseydavenport** [comment]
> 2022-01-07 11:37:50.602 [INFO][1] ipam.go 572: Releasing affinity for empty block (node has 4 total blocks) blockCIDR="10.244.19.128/26" node="worker4-dev"                                                                                                                                   2022-01-07 11:37:51.803 [WARNING][1] ipam_block_reader_writer.go 316: Error getting block error=connection is unauthorized: ipamblocks.crd.proj

Yep, I think that's what is going on here. Good sleuthing! 

Calico v3.21 introduced a feature that cleans up old blocks that are no longer in use. It looks like the GC code is detecting these newly migrated blocks and treating them as redundant. 

Correct fix is probably to disable the GC until after the migration is complete (effectively like what you have done).
