### ISSUE TITLE
kube-controller-manager shows error - FlexVolume: driver call failed: executable: /usr/libexec/kubernetes/kubelet-plugins/volume/exec/nodeagent~uds/uds - no such file or directory

### ISSUE THREAD

**Issue by jitheshktv** [projectcalico/calico#5356]
Setting up a new Kubernetes Cluster using K8s version 1.22.4, and using Calico version v3.21.2. Calico pods are up and running, however kube-controller-manager shows the below error

E0104 20:48:40.127685       1 driver-call.go:262] Failed to unmarshal output for command: init, output: "", error: unexpected end of JSON input
W0104 20:48:40.127706       1 driver-call.go:149] FlexVolume: driver call failed: executable: /usr/libexec/kubernetes/kubelet-plugins/volume/exec/nodeagent\~uds/uds, args: [init], error: fork/exec /usr/libexec/kubernetes/kubelet-plugins/volume/exec/nodeagent\~uds/uds: no such file or directory, output: ""
E0104 20:48:40.127748       1 plugins.go:750] "Error dynamically probing plugins" err="error creating Flexvolume plugin from directory nodeagent~uds, skipping. Error: unexpected end of JSON input"

## Expected Behavior
Kube-controller-manager should be able to access the file. This file exists on the host machine.

[root@ip-10-240-140-165 manifests]# ls -l /usr/libexec/kubernetes/kubelet-plugins/volume/exec/nodeagent\~uds/uds
-rwxrwxrwx. 1 root root 4987070 Dec 27 14:08 /usr/libexec/kubernetes/kubelet-plugins/volume/exec/nodeagent\~uds/uds
[root@ip-10-240-140-165 manifests]#

[root@ip-10-240-140-165 manifests]# /usr/libexec/kubernetes/kubelet-plugins/volume/exec/nodeagent\~uds/uds init
{"status":"Success","message":"Init ok.","capabilities":{"attach":false}}
[root@ip-10-240-140-165 manifests]#

This file is mounted on the "kube-controller-manager" pod using hostPath volume, and the container should be able to find it and execute it.

## Current Behavior
kube-controller-manager shows the below error

E0104 20:48:40.127685       1 driver-call.go:262] Failed to unmarshal output for command: init, output: "", error: unexpected end of JSON input
W0104 20:48:40.127706       1 driver-call.go:149] FlexVolume: driver call failed: executable: /usr/libexec/kubernetes/kubelet-plugins/volume/exec/nodeagent\~uds/uds, args: [init], error: fork/exec /usr/libexec/kubernetes/kubelet-plugins/volume/exec/nodeagent\~uds/uds: no such file or directory, output: ""
E0104 20:48:40.127748       1 plugins.go:750] "Error dynamically probing plugins" err="error creating Flexvolume plugin from directory nodeagent~uds, skipping. Error: unexpected end of JSON input"

## Steps to Reproduce (for bugs)
I have created a busybox pod to reproduce the same error. 

~ (k8s: jithu@kube_cluster) $ k exec -it -n kube-system busybox-test-ip-10-240-140-165.external.citizensbank.com -- sh
/ #

/ # ls -l /usr/libexec/kubernetes/kubelet-plugins/volume/exec/nodeagent\~uds/uds
-rwxrwxrwx    1 root     root       4987070 Dec 27 19:08 /usr/libexec/kubernetes/kubelet-plugins/volume/exec/nodeagent\~uds/uds
/ #

/ # /usr/libexec/kubernetes/kubelet-plugins/volume/exec/nodeagent\~uds/uds init
sh: /usr/libexec/kubernetes/kubelet-plugins/volume/exec/nodeagent\~uds/uds: not found
/ #

## Your Environment

* Calico version : 3.21.2
* Orchestrator version (e.g. kubernetes, mesos, rkt): k8s 1.22.4
* Operating System and version: RHEL 7.9

**Comment by ChengyangDu** [comment]
same issue. Any updates?

**Comment by caseydavenport** [comment]
Might be SELinux releated or something to do with filesystem permissions?

**Comment by jitheshktv** [comment]
Fixed it! Issue seems to be with the "uds" file being dynamically linked.

```
[root@controlplane ~]# file /usr/libexec/kubernetes/kubelet-plugins/volume/exec/nodeagent~uds/uds
/usr/libexec/kubernetes/kubelet-plugins/volume/exec/nodeagent~uds/uds: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked (uses shared libs), not stripped
[root@controlplane~]#
```

I was able to execute the _uds_ binary on the controlplane/worker nodes because the shared libraries are available in these hosts.

```
[root@controlplane ~]# ldd /usr/libexec/kubernetes/kubelet-plugins/volume/exec/nodeagent~uds/uds
	linux-vdso.so.1 =>  (0x00007ffe8fded000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007ff68d38f000)
	libc.so.6 => /lib64/libc.so.6 (0x00007ff68cfc1000)
	/lib64/ld-linux-x86-64.so.2 (0x00007ff68d5ab000)
[root@controlplane ~]#
```

However on the _kube-controller-manager_ container, these shared libs are not present, and hence it's unable to execute the _uds_ binary.

```
[root@controlplane ~]# docker exec -it ca5f96e0be40 /usr/libexec/kubernetes/kubelet-plugins/volume/exec/nodeagent~uds/uds init
OCI runtime exec failed: exec failed: container_linux.go:380: starting container process caused: no such file or directory: unknown
[root@controlplane ~]#
```

What I ended up doing is recompiling the flexvolume binary (flexvol-amd64 in my case) following the instructions here https://github.com/projectcalico/calico/tree/release-v3.21/pod2daemon#how-to-build. But I made sure to build this as statically linked this time. (Note: the _flexvol_ binary is copied as _uds_ to the nodes by the flexvol.sh script when the _flexvol-driver/pod2daemon_ init container is run, so _flexvol_ binary, and _uds_ binary are the same file)

```
🚀  file flexvol-amd64
flexvol-amd64: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, Go BuildID=hDZt0I8vDjLVbEulKErP/wqmhQT9IbDQ7hPgTQCCG/3LjoE_To15f30ydYtGZv/h8olT3sL6LZXgTCGioT8, not stripped
🚀
```
 and rebuilt the "pod2daemon" image to include this file instead of the dynamically linked version. Used this image in my calico deployment instead of the original one from docker hub.

Now in the nodes, as you can see below, the file is statically linked.

```
[root@controlplane ~]# file /usr/libexec/kubernetes/kubelet-plugins/volume/exec/nodeagent~uds/uds
/usr/libexec/kubernetes/kubelet-plugins/volume/exec/nodeagent~uds/uds: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, not stripped
[root@controlplane ~]#
```

restarted _kube-controller-manager_ and as you can see, now the _uds_ binary can be executed.

```
[root@controlplane ~]# docker ps | grep -i k8s_kube-controller-manager_kube-controller-manager
7685cd324e92   0ce02f92d3e4                                                                             "kube-controller-man…"   30 minutes ago   Up 30 minutes             k8s_kube-controller-manager_kube-controller-manager
[root@controlplane ~]#
```

```
[root@controlplane ~]# docker exec -it 7685cd324e92  /usr/libexec/kubernetes/kubelet-plugins/volume/exec/nodeagent~uds/uds init
{"status":"Success","message":"Init ok.","capabilities":{"attach":false}}
[root@controlplane ~]#
```

Also the previous error messages complaining about "no such file or directory" and "unexpected end of JSON" have disappeared from the _kube-controller-manager_ and _kubelet log files._

**Comment by jitheshktv** [comment]
Closing this issue as I was able to resolve it. Thanks to everyone who commented on this issue.

**Comment by caseydavenport** [comment]
@jitheshktv thanks for the awesome write-up, and great sleuthing. I think I am going to leave this open for now, as this probably impacts others and we'll need to find a way to resolve this (maybe by shipping a statically compiled version in our official releases).

**Comment by invidian** [comment]
I just started investigating this and indeed it seems to me linking the binary statically would be the best solution.

**Comment by fredleb** [comment]
> What I ended up doing is recompiling the flexvolume binary (flexvol-amd64 in my case) following the instructions here https://github.com/projectcalico/calico/tree/release-v3.21/pod2daemon#how-to-build. But I made sure to build this as statically linked this time.

Hi, how did you do that ?

I'm banging my head on problem after problem to build a vagrant k8s cluster...

Thanks.

**Comment by invidian** [comment]
@fredleb make sure `go build` runs with `CGO_ENABLED=0` and `-ldflags "-extldflags '-static'"`, it should produce statically linked binary. You can verify by running `ldd` against the built binary.

**Comment by jitheshktv** [comment]
@fredleb - What @invidian mentioned above is exactly what I did for my "make build" command to work. In addition, since I had to spin up a new Linux VM instance to do the build, I ran into issues because I had "selinux" enabled on this VM by default. Make sure to disable it, if that's the case for you.

Also, I didn't do a "make image", instead I created the new image by adding this statically linked "flexvol" binary to the official image from Calico and did the docker build, so essentially added another layer.

**Comment by caseydavenport** [comment]
This PR should fix this: https://github.com/projectcalico/calico/pull/5515

It keeps CGO_ENABLED but passes options to go and the linker to compile statically, since none of the C code included requires dynamic linking.

**Comment by xinbinhuang** [comment]
I have a similar problem for the `calico-node`, and have resolved them by rebuilding statically linked binaries. But I also need to rebuild the CNI plugins with statically linked for my amd64 node (running in proxmox VM), and my arm64 nodes are fine.

My setup is 2 pis + 1 amd64 VM all running with k3os. I've pushed the patched images ([cni](https://hub.docker.com/repository/docker/xinbinhuang/cni) & [pod2daemon-flexvol](https://hub.docker.com/repository/docker/xinbinhuang/pod2daemon-flexvol) ), so anyone can test them out or just use them as temporary workaround.
