### ISSUE TITLE
BIRD is not ready, BGP peering not working. 

### ISSUE THREAD

**Issue by stephenjdawson** [projectcalico/calico#5363]
May someone please help me? 3/4 node pods are running for me, and I can't figure out why the last one won't work. 
```(combined from similar events): Readiness probe failed: 2022-01-05 02:05:38.483 [INFO][883] confd/health.go 180: Number of node(s) with BGP peering established = 0 calico/node is not ready: BIRD is not ready: BGP not established with 10.0.0.12,10.0.0.13,10.0.0.11```

Pod logs states:
```[WARNING][67] felix/table.go 652: Detected out-of-sync inserts, marking for resync actualRuleIDs=[]string{"", "xxxxxxx", "", "", "", " ......}```
My IP tables look the same on the nodes that are successfully running pods. Succesful pods are Arm though, and the erroneous one is x86. Also on the Arm systems, the interface is eth instead of eno (or vice versa) if that matters. I am new to Calico and have not been able to figure this part out yet. I have IP forwarding set to true, and I even changed from IPIP to VXLAN. I also have all required ports open. 

These are my helm custom values for installation: 
```installation:
  enabled: true
  calicoNetwork:
    bgp: Enabled
    hostPorts: Enabled
    ipPools:
      - blockSize: 26
        cidr: 10.50.0.0/16
        encapsulation: VXLAN
        natOutgoing: Enabled
        nodeSelector: all()
    linuxDataplane: Iptables
    multiInterfaceMode: None
    nodeAddressAutodetectionV4:
      cidrs: [10.0.0.0/24]
    containerIPForwarding: Enabled
  controlPlaneTolerations:
  - effect: NoSchedule
    key: kubernetes.io/arch
    operator: Equal
    value: amd64
  - effect: NoSchedule
    key: kubernetes.io/arch
    operator: Equal
    value: arm
  controlPlaneNodeSelector:
    kubernetes.io/arch: amd64 
```
My server args starting k3s are:
```--disable metrics-server --disable local-storage --disable coredns --flannel-backend=none --disable network-policy --disable traefik --disable servicelb --disable-cloud-controller --node-taint kubernetes.io/arch=amd64:NoSchedule```

I found this  but I don't know if it's helpful,  don't think felix is fighting  to update IPTable: https://github.com/projectcalico/calico/issues/3756

Do I need to configure BGP Peering on install or something?

**Comment by caseydavenport** [comment]
> BIRD is not ready: BGP not established with 10.0.0.12,10.0.0.13,10.0.0.11

Does the amd64 instance have IP connectivity with your ARM instances? Are they all in the same subnet? Might just be a matter of ensuring they can talk.

Also - what IP address did your AMD64 calico/node instance select?

**Comment by stephenjdawson** [comment]
Yes, they could all communicate with each other and were on the same subnet could even ssh to each other. I discovered afterward that in my /etc/hosts file I had set every node to : 
```127.0.0.1 localhost

# truncated ipv6 defaults

# Cluster Hosts
10.0.0.10 control
10.0.0.11 worker01
10.0.0.12 worker02
10.0.0.13 worker03```

Should I have defined each node as 127.0.0.1 {node name}? 
This config worked for the arm nodes, but I am not sure what else it could have been. 
The pod was 10.0.0.10 for the control. 

I have since started to implement at talos and sidero cluster where I plan to use Calico, so if this doesn't have a simple explanation I can close the ticket and create a new one if I have issues there.

**Comment by caseydavenport** [comment]
Yeah, given that your cluster isn't around any more lets close this. I suspect it was a configuration issue of some sort. Please shout if you encounter this again and we can reopen.
