### ISSUE TITLE
Path not correct for downloading source files in K8s

### ISSUE THREAD

**Issue by tmjd** [projectcalico/calico#538]
At http://docs.projectcalico.org/v2.1/getting-started/kubernetes/installation/vagrant/
the download urls used for the master-config.yaml and node-config.yaml are not correct, the directory in the Vagrant file is incorrect too.  Either the files need to be moved out of the cloud-config folder or the urls and paths updated.

**Comment by djosborne** [comment]
@tomdee Did you have one of those options in mind when you merged your docs versioning PR?
