### ISSUE TITLE
Impoved IPAM metrics

### ISSUE THREAD

**Issue by gilgameshfreedom** [projectcalico/calico#5430]
We actively use calico in our kubernetes cluster and we'd like to monitor the following unwanted scenarios:

1. If number of free IPs in a ippool is close to zero.
2. If number of "leaked" IPs (leaked IP means that calico allocated this IP but it's actually not in use) grows.

We have encountered these two situations a few times.

Currently for monitoring these we have to parse output of calicoctl ipam show and  calicoctl ipam check. Although, there is an IPAM metric ipam_allocations_per_node, it's useless for monitoring number of free IPs for two reasons:
1. The metrics doesn't has label contains ipppol name or cidr. In some kubernetes clusters we use more than one ippool so we don't know from ipam_allocations_per_node info about the ippool.
2. There is no metric contains information about the number of total available IP address in a ippools.
 
## Possible Solution

I suggest to do the following:
1. Modifing the ipam_allocations_per_node metric by adding labels "ipppol_name" and "ippool_cidr".
2. Adding two new metrics:
* ipam_allocations_total - the total number of IP address per ipppol. The metric should contains labels "ipppol_name" and "ippool_cidr" too.
* ipam_leaked_allocations_per_node - the number of leaked IP address per node per pool. The metric should contains labels "ipppol_name" and "ippool_cidr" and "node".

For example, let's imagine I have two ippools:

```
# calicoctl get ippool
NAME      CIDR            SELECTOR
test1   10.192.0.0/16   all()
test2   10.200.0.0/24   !all()
```

So, the ipam_max_allocations will contains the following:

```
ipam_allocations_total{ippool_name="test1",ippool_cidr="10.192.0.0/16"} 65536
ipam_allocations_total{ippool_name="test2",ippool_cidr="10.200.0.0/24"} 256
```

If I w'd like to know the percent of used IP addresses in pool test1 I could do the following:

`sum(ipam_allocations_per_node{ippool_name="test1"}) / ipam_allocations_total{ippool_name="test1"}`

Further If w'd like to know the percent of "leaked" IP addresses in the allocated IP addresses in  pool test2  I could do the following:

`sum(ipam_leaked_allocations_per_node{ippool_name="test1"}) / ipam_allocations_per_node{ippool_name="test1"}`

## Current Behavior
Currently the only way for monitoring percent of leaked and free IP addresses is to parse output of calicoctl ipam show and  calicoctl ipam check.

**Comment by caseydavenport** [comment]
This seems like a good improvement to make.

**Comment by cdtomkins** [comment]
Thanks, I'll take this one.

**Comment by cdtomkins** [comment]
@caseydavenport @gilgameshfreedom I'm working on point (1) first. In order to make sure I am aiming for the right thing, can I confirm that in this **current scenario**:
```
chris @ chris-work ~/repos/cdtomkins_calico [5430_improved_ipam_metrics !?]
└─512─▶ calicoctl ipam show
+----------+----------------+-----------+------------+--------------+
| GROUPING |      CIDR      | IPS TOTAL | IPS IN USE |   IPS FREE   |
+----------+----------------+-----------+------------+--------------+
| IP Pool  | 192.168.0.0/16 |     65536 | 7 (0%)     | 65529 (100%) |
| IP Pool  | 10.0.0.0/16    |     65536 | 1 (0%)     | 65535 (100%) |
+----------+----------------+-----------+------------+--------------+
chris @ chris-work ~/repos/cdtomkins_calico [5430_improved_ipam_metrics !?]
└─513─▶ calicoctl get ippool
NAME                  CIDR             SELECTOR   
default-ipv4-ippool   192.168.0.0/16   all()      
second-ipv4-ippool    10.0.0.0/16      all()      

chris @ chris-work ~/repos/cdtomkins_calico [5430_improved_ipam_metrics !?]
└─514─▶ minikube ssh
Last login: Fri Jan 21 15:41:34 2022 from 192.168.49.1
docker@minikube:~$ curl -s http://192.168.120.65:9094/metrics | grep -i ipam_allocations_per_node
# HELP ipam_allocations_per_node Number of IPs allocated
# TYPE ipam_allocations_per_node gauge
ipam_allocations_per_node{node="minikube"} 6
ipam_allocations_per_node{node="minikube-m02"} 1
ipam_allocations_per_node{node="minikube-m03"} 1
```

You would **want to see this**:
```
# HELP ipam_allocations_per_node Number of IPs allocated
# TYPE ipam_allocations_per_node gauge
ipam_allocations_per_node{node="minikube",ippool_name="default-ipv4-ippool",ippool_cidr="192.168.0.0/16"} 5
ipam_allocations_per_node{node="minikube-m02",ippool_name="default-ipv4-ippool",ippool_cidr="192.168.0.0/16"} 1
ipam_allocations_per_node{node="minikube-m03",ippool_name="default-ipv4-ippool",ippool_cidr="192.168.0.0/16"} 1
ipam_allocations_per_node{node="minikube",ippool_name="second-ipv4-ippool",ippool_cidr="10.0.0.0/16"} 1
ipam_allocations_per_node{node="minikube-m02",ippool_name="second-ipv4-ippool",ippool_cidr="10.0.0.0/16"} 0
ipam_allocations_per_node{node="minikube-m03",ippool_name="second-ipv4-ippool",ippool_cidr="10.0.0.0/16"} 0
```

**Comment by caseydavenport** [comment]
@cdtomkins that's my understanding of the item 1 :+1:

**Comment by gilgameshfreedom** [comment]
@cdtomkins this's exaclty what I meant on point 1 (modifing the ipam_allocations_per_node metric).

**Comment by pasanw** [comment]
Hey @gilgameshfreedom :wave: I've been developing this feature and should hopefully have it ready shortly. 

I had something I wanted to clarify: you mentioned that the metrics should be labelled with their pool CIDR (in addition to the pool name). Do you mind elaborating a bit on the use-case of having the CIDR label?

**Comment by gilgameshfreedom** [comment]
Hello @pasanw. Sorry for long reply.

> I had something I wanted to clarify: you mentioned that the metrics should be labelled with their pool CIDR (in addition to the pool name). Do you mind elaborating a bit on the use-case of having the CIDR label?

I've re-read my initial text and I've realized that ippool_cidr label is dispensable. The presence of ippool_name label for all kinds of metrics (ipam_allocations_per_node, ipam_allocations_total, ipam_leaked_allocations_per_node) will be sufficient.
