### ISSUE TITLE
Rack affinity doc

### ISSUE THREAD

**Issue by gunjan5** [projectcalico/calico#547]
Pulling this section out from #493 
---------------

Add a "Usage" doc on Rack affinity. At a minimum, just explains the concept of editing each host's configuration to use a different pool. Stretch goal would be to start to explain how to better aggregate those routes by configuring a BGP TOR for each rack. (cc: @kprabhak ?)

cc @djosborne

**Comment by caseydavenport** [comment]
@briansan we should address this as part of the work we're doing in v3.5

**Comment by caseydavenport** [comment]
Covered here: https://docs.projectcalico.org/v3.6/networking/assigning-ip-addresses-topology
