### ISSUE TITLE
Debian/Ubuntu 3.21.4 repo has outdated (3.21.2) `calico-common` & `calico-felix` packages

### ISSUE THREAD

**Issue by comay** [projectcalico/calico#5476]
It appears that http://ppa.launchpad.net/project-calico/calico-3.21/ubuntu/pool/main/f/felix/ wasn't updated with 3.21.4 versions of `calico-common` & `calico-felix` although http://ppa.launchpad.net/project-calico/calico-3.21/ubuntu/pool/main/n/networking-calico/ has been updated. This is holding back our moving to the latest version.

**Comment by caseydavenport** [comment]
This is a known issue and is called out here: https://github.com/projectcalico/calico/releases/tag/v3.21.4

v3.21.4 ppa fails to build but it should be resolved in v3.21.5 - fix has already been made in the scripts, but we have no mechanism to replace the existing release at the moment.
