### ISSUE TITLE
projectcalico.org/IPv4Address suddenly changed.

### ISSUE THREAD

**Issue by b23r0** [projectcalico/calico#5492]
## Current Behavior

Occasionally, a node's projectcalico.org/IPv4Address parameter will suddenly change to its previous configuration.
At this time, the network of the pod will be interrupted.

## Possible Solution

When I reconfigured the projectcalico.org/IPv4Address parameter for that node, the network went back to normal.

## Steps to Reproduce (for bugs)

modify large of `deployment` at the same time and restart pod

## Context

This problem causes business interruptions from time to time, requiring frequent manual maintenance

## Your Environment

* Calico version: 3.20.1
* Orchestrator version (e.g. kubernetes, mesos, rkt): Kubernets 1.22 .
* Operating System and version: CentOS 8.5 4.18.0-305.19.1.el8_4.x86_64
* Link to your project (optional): ###

**Comment by lwr20** [comment]
Is the address being changed to another IP on this node?  Does the node have multiple interfaces? If so, perhaps you need to configure ip autodetection?  https://projectcalico.docs.tigera.io/reference/node/configuration#ip-autodetection-methods

**Comment by caseydavenport** [comment]
Yep, most likely calico/node autodetection is picking a different address and overwriting your manually specified one. You'll need to turn auto-detection off to assign them manually, or pick an autodetection method that correctly picks the address you want.

**Comment by b23r0** [comment]
> Is the address being changed to another IP on this node? Does the node have multiple interfaces? If so, perhaps you need to configure ip autodetection? https://projectcalico.docs.tigera.io/reference/node/configuration#ip-autodetection-methods The method defaults to first-found and is used at startup to determine the correct node IP.

not any IP on the node. It seems to be an IP that has been configured on the node.

**Comment by b23r0** [comment]
> @b23r0 Can you please give us more details
> 
> * Is this an operator or manifest based install?
> * How are you configuring the `projectcalico.org/IPv4Address`?
> * Do you see any logs from the calico-node pod on the affected node indicating the IPv4 address has changed?

I configured projectcalico.org/IPv4Address via `kubectl edit node` command.
Just abruptly changed and there are some error logs due to IP change.

**Comment by b23r0** [comment]
> Yep, most likely calico/node autodetection is picking a different address and overwriting your manually specified one. You'll need to turn auto-detection off to assign them manually, or pick an autodetection method that correctly picks the address you want.

The changed ip is not any IP on the node. It appears to be an IP that was configured once.

I found an article describing a similar problem, maybe enlightening.

https://vadosware.io/post/new-node-who-dis-dns-issues-and-calico-failures-on-a-resurrected-node/

**Comment by lmm** [comment]
@b23r0 what's the IP autodetection you have configured?

Do you see any differences in IPs in `kubectl get node` vs `calicoctl get node`? If so, can you check the kube-controller pod logs?

**Comment by caseydavenport** [comment]
> I configured projectcalico.org/IPv4Address 

this field isn't intended to be hand-edited. It might work to hand edit it, but there is Calico code that fills this field in with the value it believes is correct for the node. If you have autodetection enabled, **calico will overwrite whatever value you put in this field no matter what**

**Comment by b23r0** [comment]
Thanx for everyone. Today I checked the problem and found that it was a configuration error caused by the engineer's negligence. I will close this issue.
