### ISSUE TITLE
Calico node ARM64 compilation time

### ISSUE THREAD

**Issue by frozenprocess** [projectcalico/calico#5516]
compiling arm64 image of calico node on an amd64 machine takes a bit of time right now, this is due to the fact that we have to use qemu and use bin_fmt misc to emulate an arm64 environment. 
## Expected Behavior

Semaphore seems to have added [a1 instance](https://docs.semaphoreci.com/ci-cd-environment/machine-types/#apple-machine-type) to compile macosx code. I think there might be a way to use such an instance to compile arm images faster.
 
## Current Behavior

Makefile uses [regsiter](https://github.com/projectcalico/calico/blob/82c9b752a38f53440d1f7f492b2ecb14bbb539ed/node/Makefile#L265) function and add `arm64` magic headers and copies [qemu binaries](https://github.com/projectcalico/calico/blob/82c9b752a38f53440d1f7f492b2ecb14bbb539ed/node/Dockerfile.arm64#L32) to run the arm64 instruction set in the container environemnt.

> This is only a case for `arm64` atm since it has cgo and ebpf enabled.

## Possible Solution

By adding a new ci pipeline with `a1-standard-4` we could 
compile arm image in less than 10 minutes.
## Steps to Reproduce (for bugs)

1. git clone calico on an amd64 instance
2. run `make -C node image ARCH=arm64

## Context
@lwr20 mentioned waiting 2 hours for calico build to finish might not be the best way to pass time. :)

## Your Environment
N/A

CC: @caseydavenport

**Comment by TrevorTaoARM** [comment]
Hi maintainers:
I would like to ask if there's any consideration for Calico Arm CI, I think it will greatly benefit our Calico environment on arm.

**Comment by caseydavenport** [comment]
I think it's something we'd like to do, but is pretty low on our priority list in terms of CI improvements at the moment.

**Comment by hjiawei** [comment]
Semaphore [R1 machines](https://docs.semaphoreci.com/ci-cd-environment/machine-types/#r1-generation) are now in tech preview.

**Comment by hjiawei** [comment]
We have enabled native ARM64 builds for calico/node in https://github.com/projectcalico/calico/pull/8558. The calico/node image build time is around 16-18 minutes (comparable to native amd64). @frozenprocess Can we close this issue?
