### ISSUE TITLE
calico_backend and helm chart

### ISSUE THREAD

**Issue by malikumaliku** [projectcalico/calico#5534]
I have a hybrid linux+windows workload,

On linux nodes I set up calico_backend to vxlan following 
https://docs.projectcalico.org/getting-started/kubernetes/installation/config-options

And on windows nodes I tune the ps1 script to set up
CALICO_NETWORKING_BACKEND
https://projectcalico.docs.tigera.io/reference/node/configuration

Is there a way to do a helm deployment with vxlan instead of ipip?
I have not found this documentation any way to do it
https://projectcalico.docs.tigera.io/reference/installation/api#operator.tigera.io/v1.Provider
having an ippool with encapsulation type to VXLAN does not seems to be enough

**Comment by caseydavenport** [comment]
Are you using the Calico official helm chart?  That helm chart doesn't have a `calico_backend` config option, so suspect you might not be. 

Using the official helm chart, creating a VXLAN IP pool and setting `bgp: Disabled` should do the trick.

**Comment by malikumaliku** [comment]
I have was trying an helm install with these options, but it never work

--set installation.BGPOption="Disabled"
--set installation.calicoNetwork.ipPools[0].encapsulation="VXLAN"
--set installation.calicoNetwork.ipPools[0].cidr="192.168.123.0/24"

**Comment by caseydavenport** [comment]
> but it never work

I'm afraid you're going to need to give me a bit more to go on than this! What are the symptoms that you are experiencing?

Can you share the generated Installation resource? e.g., `kubectl get installations -o yaml`
