### ISSUE TITLE
Canal manifests are using old Flannel version

### ISSUE THREAD

**Issue by rastislavs** [projectcalico/calico#5563]
Canal manifests for Calico `v3.22` release (https://projectcalico.docs.tigera.io/v3.22/manifests/canal.yaml) are using quite old version of Flannel - `v0.13.0`.

The latest Flannel version at the time of Calico `v3.22` release was `v0.16.3`: https://github.com/flannel-io/flannel/releases/tag/v0.16.3

Since Flannel `v0.13.0`, there were some important bugfixes merged in, e.g. https://github.com/flannel-io/flannel/issues/1408

**Comment by caseydavenport** [comment]
Should be as easy as updating this value: https://github.com/projectcalico/calico/blob/master/calico/_data/versions.yml#L27

And then running tests.

**Comment by frozenprocess** [comment]
@caseydavenport quay seems to be behind as well, [latest version over there is 15](https://quay.io/repository/coreos/flannel?tab=tags&tag=v0.16.3).
```
docker pull quay.io/coreos/flannel:v0.16.3
Error response from daemon: manifest for quay.io/coreos/flannel:v0.16.3 not found: manifest unknown: manifest unknown
```

I think we might need to change this to `rancher/mirrored-flannelcni-flannel` as well. 
https://github.com/projectcalico/calico/blob/632f46ffd41d2441f6fabb84d7854f95ed42b1ed/calico/_config.yml#L38

**Comment by caseydavenport** [comment]
https://github.com/projectcalico/calico/pull/5640
