### ISSUE TITLE
doc search broken

### ISSUE THREAD

**Issue by yelhouti** [projectcalico/calico#5569]
## Expected Behavior

Be able to search in docs

## Current Behavior

not working

## Steps to Reproduce (for bugs)

1. open webiste
2. try to use the searchbar

**Comment by lmm** [comment]
Sorry about that @yelhouti - it's a known issue with our search provider. If it helps, you can try using an older version of our docs for search: https://projectcalico.docs.tigera.io/archive/v3.21/about/about-calico

**Comment by yelhouti** [comment]
@lmm thanks for the quick response

**Comment by lmm** [comment]
@yelhouti the site search for the docs site looks like it's fixed now
