### ISSUE TITLE
Vagrant rkt demo has multiple private IPs assigned and uses etcd proxy

### ISSUE THREAD

**Issue by robbrockbank** [projectcalico/calico#557]
Running the rkt vagrant demo and eth1 has both a 172 and a 192 address assigned:

```
core@calico-01 ~ $ ip addr show
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 08:00:27:db:fa:4a brd ff:ff:ff:ff:ff:ff
    inet 10.0.2.15/24 brd 10.0.2.255 scope global dynamic eth0
       valid_lft 86256sec preferred_lft 86256sec
    inet6 fe80::a00:27ff:fedb:fa4a/64 scope link 
       valid_lft forever preferred_lft forever
3: eth1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 08:00:27:41:41:1a brd ff:ff:ff:ff:ff:ff
    inet 192.168.56.119/24 brd 192.168.56.255 scope global dynamic eth1
       valid_lft 1049sec preferred_lft 1049sec
    inet 172.18.18.101/24 brd 172.18.18.255 scope global eth1
       valid_lft forever preferred_lft forever
    inet6 fe80::a00:27ff:fe41:411a/64 scope link 
       valid_lft forever preferred_lft forever
```

When starting the calico/node without a selection algorithm it chooses the 192. address.

This is fine initially, but after 10 mins or so, the 192 address disappears (presumably due to DHCP lease expiration), at this point things stop working.

**Comment by robbrockbank** [comment]
A few things we need to do:
-  Use a can-reach autodetection method to ensure we select the correct interface.  (Set to can-reach etcd address is good)
-  Update the Vagrantfile and cloud configs to be in line with the other demos (file names and removal of etcd proxy)

**Comment by robbrockbank** [comment]
The v2.1 portion has been fixed by #558

**Comment by djosborne** [comment]
I found that I just needed to turn off DHCP on the VBox managed interface:
```
vboxmanage dhcpserver modify --netname HostInterfaceNetworking-vboxnet0 --disable
```

**Comment by robbrockbank** [comment]
^ @djosborne I was aware of this, but I don't think we should be suggesting to people that they do that since it changes their entire settings for VirtualBox.  Probably better if we can work around it more generically - which we can by using one of the IP auto-detection mechanisms.  Probably need to update all of our vagrant demos with this though.

**Comment by djosborne** [comment]
I think each vagrant setup gets its own hostonlyif. I had 9 on my box. So it isn't "their entire settings". It's the settings for the interface created special for this demo.

**Comment by caseydavenport** [comment]
@robbrockbank I think we can close this if things are working now.

**Comment by robbrockbank** [comment]
Yup I think we worked around this using a different auto detection method or similar, so I'm happy to close.
