### ISSUE TITLE
Topology spread or antiAffinity rules for calico controllers and typha

### ISSUE THREAD

**Issue by nuriel77** [projectcalico/calico#5577]
Have so far I have only found [nodeAffinity ](https://projectcalico.docs.tigera.io/reference/installation/api#operator.tigera.io/v1.TyphaAffinity) for Typha but found no other option to configure custom affinity (or antiAffinity) rules for either Typha or calico kubernetes controllers.

## Expected Behavior

Have an option to supply custom affinity rules. 
This is important for high availability, e.g.:
1. In order to make use of multiple availability zones or racks, 
2. host antiAffinity.

## Current Behavior

No possibility to configure custom affinity or [pod topology spread constraints.](https://kubernetes.io/docs/concepts/workloads/pods/pod-topology-spread-constraints/)

## Possible Solution

Add configuration fields to be able to configure k8s spec affinity rules and/or  [pod topology spread constraints.](https://kubernetes.io/docs/concepts/workloads/pods/pod-topology-spread-constraints/)

## Steps to Reproduce (for bugs)

N/A

## Context

Running on a public cloud, e.g. AWS (EKS) having multiple availability zones. In order to make sure that replicas larger than 1 have the pods spread across the zones for better availability.

## Your Environment

* Calico v3.22.0
* Orchestrator Kubernetes 1.20
* Operating System and version: Linux AWS AMI v1.20.11-eks-f17b81

**Comment by tmjd** [comment]
Yeah you're right, I'm not sure what I was thinking could be done to spread the pods using typhaAffinity.
Thanks for clarifying things for me.

Probably the hardest part of adding this will be figuring out what we want the API for this would be.
My 1st thought is adding this as a field under typhaAffinity. But I think I'd want to consider this addition for other components like the APIServer and how we might want to use a common pattern for both.
@caseydavenport @Brian-McM  WDYT?

**Comment by caseydavenport** [comment]
Cross referencing this because I think they are (just barely) related: https://github.com/tigera/operator/issues/1653#issuecomment-1011385697


> In order to make use of multiple availability zones or racks,

Yep this one sounds _very_ legit. 

As for API, @tmjd maybe I'm missing something but wouldn't it be a straightforward extension to https://github.com/tigera/operator/blob/master/api/v1/installation_types.go#L151-L156

e.g.

```go
type TyphaAffinity struct {
	// NodeAffinity describes node affinity scheduling rules for typha.
	// +optional
	NodeAffinity *NodeAffinity `json:"nodeAffinity,omitempty"`
	
	// Used to ensuring Typha is reasonably spread throughout the cluster
        PodAntiAffinity *PodAffinity `json:"podAffinity,omitempty"`
}

**Comment by tmjd** [comment]
If we added TopologyConstraints would there be a need for PodAntiAffinity?

**Comment by nuriel77** [comment]
@tmjd one reason that comes to mind, afaik, is that Pod Topology Spread Constraints is available since [K8S version 1.19](https://kubernetes.io/docs/concepts/workloads/pods/pod-topology-spread-constraints/) and clusters older than that should still have a way of achieving a similar topology via `podAntiAffinity`. In addition, most users are probably used to the podAffinity/antiAffinity syntax (if its kept in the original k8s spec format).

In any case, I wanted to ask: why is it needed to abstract default K8S Pod configurations (e.g. `TyphaAffinity`) vs. letting users customize k8s pod specs in native k8s format should they choose to do so? That would probably mean less code and less maintenance.
Why not allow configuration of the entire pod.spec.affinity? (`kubectl explain pod.spec.affinity`)
Same for topology constraints etc.

Just as an example, taking a project such as Confluent: they define their own CRDs for "kafka", the pod spec is generated by the CRD. Nevertheless, the CRD allows to configure/override additional specs, for example:
`tolerations`, `topologySpreadConstraints`, `priorityClassName`, `affinity`.

See the CRD spec example: the `podTemplate` allows configuration of pod settings in native k8s spec format (in this case its pod spec of statefulSet, but the idea should be the same for a deployment)
```
kubectl explain kafka.spec.podTemplate
KIND:     Kafka
VERSION:  platform.confluent.io/v1beta1

RESOURCE: podTemplate <Object>

DESCRIPTION:
     podTemplate specifies the statefulset pod template configuration.

FIELDS:
   affinity     <Object>
     affinity specifies a group of affinity scheduling rules. More info:
     https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#affinity-and-anti-affinity.

   annotations  <map[string]string>
     annotations are unstructured key value maps stored with the resource and
     may be set by external tools to store and retrieve arbitrary metadata. They
     are not queryable and should be preserved when modifying objects. More
     info: http://kubernetes.io/docs/user-guide/annotations.

   envVars      <[]Object>
     envVars contain environment variables to be injected into containers. More
     info:
     https://kubernetes.io/docs/tasks/inject-data-application/define-environment-variable-container.

   labels       <map[string]string>
     labels are maps of string keys and values that can be used to organize and
     categorize (scope and select) objects. More info:
     http://kubernetes.io/docs/user-guide/labels.

   podSecurityContext   <Object>
     PodSecurityContext holds pod-level security attributes and common container
     settings. Some fields are also present in container.securityContext. Field
     values of container.securityContext take precedence over field values of
     PodSecurityContext.

   priorityClassName    <string>
     priorityClassName specifies the priority class for the pod (if any).

   probe        <Object>
     probe contains the fields for standard Kubernetes readiness/liveness probe
     configuration.

   resources    <Object>
     resources describe the compute resource requirements.

   serviceAccountName   <string>
     ServiceAccountName is the name of the service account used to run this pod.
     More info:
     https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account.

   terminationGracePeriodSeconds        <integer>
     terminationGracePeriodSeconds is the grace period before the pod is
     deleted.

   tolerations  <[]Object>
     tolerations specify the pods to schedule onto the nodes with matching
     taints, using the triple `<key,value,effect>` and the matching operator
     `<operator>`.

   topologySpreadConstraints    <[]Object>
     topologySpreadConstraints describe how a group of pods ought to spread
     across topology domains. Scheduler will schedule pods based on the
     constraints. All topologySpreadConstraints are ANDed.
```

**Comment by bcbrockway** [comment]
> I think I'd want to consider this addition for other components like the APIServer and how we might want to use a common pattern for both.

This would be a must for us as we have alerting set up to tell us when _anything_ on the cluster is not properly balanced across nodes/zones!

**Comment by lmm** [comment]
Hey @nuriel77 @bcbrockway 

We've put up an outline of proposed changes to operator component configuration. Among other things, this will include allow overriding node affinity/selectors for the core Calico components. Please take a look. We'd appreciate your input on the proposed changes: https://github.com/tigera/operator/issues/1990

**Comment by lmm** [comment]
With #2063 merged it is now possible to add a custom nodeSelector/affinity to the core Calico components.
