### ISSUE TITLE
How to set preference to use local network interface for routing?

### ISSUE THREAD

**Issue by R-omk** [projectcalico/calico#5588]
How can be configured the calico bgp with k8s in such a way that traffic **between pods** located on hosts within one data center passes through the local network (eth1), and in the case of another data center, the public interface (eth0) is used?

Something like this (`IP_AUTODETECTION_METHOD=interface=eth1`) is currently being used when install calico node to use a local network within the same data center. But I have absolutely no idea how to achieve the configuration shown in the figure.

![image](https://user-images.githubusercontent.com/1633879/153034389-7fc82992-8682-441f-bf19-70153a7e33a9.png)

**Comment by lmm** [comment]
If you can setup the BGP peers without using the default full-mesh, then I believe you can use [`sourceAddress: None`](https://projectcalico.docs.tigera.io/reference/resources/bgppeer) in your BGP peers (provided `eth1` is the only interface that can reach the other dc).

(@caseydavenport @neiljerram please correct me if I'm wrong here.)

**Comment by caseydavenport** [comment]
Routing to entities outside of Calico's network (e.g., another cluster) isn't handled by Calico generally, rather your host network would use a default route to send traffic via eth0.

You can configure Calico to use a specific node interface using autodetection to configure the BGP source address and then configure `sourceAddress: UseNodeIP`. Note that this relies on your host properly routing traffic via eth1 for any next hop within your local cluster.

**Comment by R-omk** [comment]
I have the following idea, what if you configure calico on the eth0 interface, but on those hosts where there is a local network, explicitly set static routes to all neighboring hosts through the internal interface?

example:

```
node1-dc1     eth0: 8.8.8.8/32      eth1:192.168.0.101/24
node2-dc1     eth0: 8.8.4.4/32      eth1:192.168.0.102/24

--

node1-dc1$  ip r 
default via 8.8.8.1 dev eth0 proto static onlink 
8.8.4.4 via 192.168.0.102 dev eth1 proto static onlink 
192.168.0.0/24 dev eth1 proto kernel scope link src 192.168.0.101 

--

node2-dc1$  ip r 
default via 8.8.4.1 dev eth0 proto static onlink 
8.8.8.8 via 192.168.0.101 dev eth1 proto static onlink 
192.168.0.0/24 dev eth1 proto kernel scope link src 192.168.0.102 

```


In this example, routes to external IP addresses are explicitly configured through the local network, will such a scheme work with calico and solve the problem described in this issue?

**Comment by caseydavenport** [comment]
I don't think IPIP between clusters is going to work, since Calico installs rules to prevent unknown IPIP packets (and the remote cluster's Calico instances won't know about the other cluster's node IPs)

For routing, I believe the main thing it so make sure that your next hop addresses are preferred over certain interfaces.

e.g., for internal traffic, your next hop should be routed via eth1, and for external traffic, your next hop router should be send via eth0.
