### ISSUE TITLE
kube-iptables-tailer install fails with error "server cannot find the resource projectcalico.org/v3/GlobalNetworkPolicy"

### ISSUE THREAD

**Issue by Leke-Ariyo** [projectcalico/calico#5599]
I found your object that mentions v3 https://projectcalico.docs.tigera.io/reference/resources/globalnetworkpolicy but it doesn't work with calico v3.22

we have calico 3.22 - installed by tigera-operator - and can only see CRDs with v1 - so how come docs say v3 ?

It seems some have working v3 GlobalNetworkPolicy https://github.com/honestica/lifen-charts/
but this does not work with our latest calico currently.

Am I missing some part of calico ?

### My Environment
* Calico version: v3.22
* kubernetes: 1.22
* Operating System and version: Ubuntu 20.04.3 LTS

**Comment by H4R0** [comment]
v3 namespace is only available using calicoctl

if you use kubectl, you need to use crd.projectcalico.org/v1 instead

they are the same afaik

**Comment by caseydavenport** [comment]
A bit more on this here: https://projectcalico.docs.tigera.io/maintenance/install-apiserver

Make sure the Calico API server is installed.

`projectcalico.org/v3` is the officially supported API, served by the API server. `crd.projectcalico.org/v1` is an internal API and shouldn't be used directly.
