### ISSUE TITLE
should-install-windows-upgrade/should_upgrade.go 42: Failed to build Kubernetes client config error=invalid configuration: no configuration has been provided, try setting KUBERNETES_MASTER environment variable

### ISSUE THREAD

**Issue by malikumaliku** [projectcalico/calico#5604]
should-install-windows-upgrade/should_upgrade.go 

only uses harcoded values for checking the kube config file, and is not evaluatig the KUBECONFIG environment variable

**Comment by caseydavenport** [comment]
Please fill out the issue template when creating new issues.

I'll let @song-jiang decide if this is a bug or not, but my inclination is that this is working as intended.

**Comment by song-jiang** [comment]
@malikumaliku Calico for Windows does not use KUBECONFIG environment variable. It uses a file in the fixed location for upgrade service. This is working as expected.
