### ISSUE TITLE
Typha incorrectly disconnecting clients in very large clusters

### ISSUE THREAD

**Issue by gavol** [projectcalico/calico#5629]
I am running a large k8s cluster (2k nodes) and using Typha with the proportional auto-scaler. I have configured the auto-scaler to not start more than 20 Typha replicas (as suggested by the documentation).

At the same time, Typha started to drop clients continuously issuing warnings like that:

`[WARNING][7] sync_server.go 479: Currently have too many connections, terminating one at random. connID=0x30fb current=412 max=408 thread="numConnsGov"`

I have actually increased the number of Typha replicas and the situation went back to normal.

I would like to ask:
- Is there really a maximum number of Typha instances that should be executed?
- Is there a way to increase the number of connection limits?
- Is it possible to have a smarter auto-scaler based on the number of Typha connections?
- Is increasing the number of Typha replicas the right solution to an issue like that?

Thanks in advance for your help.

## Expected Behavior

I would expect a limit in the number of connections to be properly documented with clear rules to follow when that limit is reached.

## Current Behavior

I think there is nothing really broken in the current behavior.

## Possible Solution

I have found that increasing the number of Typha replicas fixes the problem. At the same time, I am not sure whether that is a correct and viable strategy because, I guess, a higher number of Typha replicas will cause additional load to the API server(s).

## Steps to Reproduce (for bugs)

It happened to me when my cluster reached the size of about 2k nodes with 20 Typha instances.

## Your Environment

* Calico version: v3.22.0
* Orchestrator version (e.g. kubernetes, mesos, rkt): Kubernetes v1.21.2 (installed with kubeadm)
* Operating System and version: Linux, CC7

**Comment by caseydavenport** [comment]
> Is there really a maximum number of Typha instances that should be executed?

The main things to be aware of is that the more typhas that exist, the higher the load on the API server. The hard upper limit is when numberTyphas == numNodes, at which point there is no value in running Typha any more.  Running more than 20 won't be an issue.

> Is there a way to increase the number of connection limits?

I believe Typha does support a config option to adjust the connection limits: https://github.com/projectcalico/calico/blob/master/typha/pkg/config/config_params.go#L141-L142

> Is it possible to have a smarter auto-scaler based on the number of Typha connections?

Yes, this would be fantastic. The [operator](github.com/tigera/operator) is the path forward here. It already includes a purpose build autoscaler for typha and any future autoscaling optimizations will go there. I'd recommend looking at switching to a Calico cluster managed by the operator. 

> Is increasing the number of Typha replicas the right solution to an issue like that?

Yep, I think increasing the replicas is the right way to go. You can also look at adjusting the number of connections.

**Comment by caseydavenport** [comment]
> I would expect a limit in the number of connections to be properly documented with clear rules to follow when that limit is reached.

Yeah, we need to update the documentation on this for sure.

**Comment by gavol** [comment]
Thanks a lot for the provided information.

> Yep, I think increasing the replicas is the right way to go. You can also look at adjusting the number of connections.

OK, I will keep experimenting with the number of replicas, trying to have the number of connections for each replica lower than the limit.

Do you have any rationale or strategy to suggest when playing with the number of connections? Is there any strong reason behind the current limit of 400?

> The [operator](https://github.com/projectcalico/calico/issues/github.com/tigera/operator) is the path forward here. It already includes a purpose build autoscaler for typha and any future autoscaling optimizations will go there. I'd recommend looking at switching to a Calico cluster managed by the operator.

Indeed, the operator is on my path.

Last general question: is there any additional performance optimization that can be applied to calico/typha in large clusters? We have very specific and large workloads, where the ability to bring them up and down as fast as possible is very important. We are currently performing POD start-up throughput measurements and we are observing that calico is a kind of limitation in this area. We are actually wondering to just use host networking (it is private cluster and we have full control of what is running there) because of the higher throughput we get; at the same time it would be nice to keep the calico door open.

Maybe I should open a different issue about that :-)

Thanks again for the help.

**Comment by caseydavenport** [comment]
> We are currently performing POD start-up throughput measurements and we are observing that calico is a kind of limitation in this area

It's possible that Calico is limiting here, although we test Calico's impact on this in periodic scale testing and generally Calico's impact is low. This is a fairly tricky thing to measure - how are you measuring this and how confident are you that it's Calico that is introducing the delay?

**Comment by caseydavenport** [comment]
> Do you have any rationale or strategy to suggest when playing with the number of connections? Is there any strong reason behind the current limit of 400?

There's not a fundamental limit, but just remember that the more connections each typha services the more resources that typha will need. You can probably bump that up so long as you're not resource starving individual typha instance.s

**Comment by gavol** [comment]
> It's possible that Calico is limiting here, although we test Calico's impact on this in periodic scale testing and generally Calico's impact is low. This is a fairly tricky thing to measure - how are you measuring this and how confident are you that it's Calico that is introducing the delay?

We start N PODs per host in a single deployment, just running the pause container pre-loaded on all the hosts (no affinities or any other rule to locate the PODs on the worker nodes). We actually run the ClusterLoader2 "density" benchmark.

We perform the tests with and without the HostNetwork flag. 

We scaled the cluster up to 2000 hosts so far, and the control plane is made up of 4 masters with an external ETCD instance.
Just to give you an idea, with the HostNetwork we are able to start 3 PODs per host in about 35 seconds; if we do not use the HostNetwork, with Calico as CNI, that time goes up to about 130 seconds (with all the other conditions being the same). And without Typha the time was much much higher.

Additionally, we really see a huge difference in the API server(s) load when the HostNetwork is not used, with the blockaffinities API call (that, I think, is a Calico call) showing up as one of the most expensive call (without Typha that call was really killing the API servers).

If we go down to 1 POD per node, the difference in time is lower but still important: ~15 seconds (HostNetwork) against ~45 seconds (Calico CNI). In that situation the load on the API servers is modest.

Let me also add that in order to achieve those results, we increase the QPS values of both the scheduler and the controller manager.

**Comment by caseydavenport** [comment]
Interesting. I know that I personally have run similar load tests with Calico in policy-only mode (i.e., not Calico IPAM) on 3k node clusters running 60 pods per node and saw a 99 percentile time to first networking access of less than 2 seconds. That said, running clusters at that scale does require a fair bit of tuning, and calico IPAM as you discovered does change that equations as there are many more API requests required, so that might be the difference maker here.

**Comment by fasaxc** [comment]
@gavol The warning you're seeing in Typha's log about disconnecting a client may just be Typha rebalancing connections.  Typha checks how many typha instances there are and how many nodes and, if it finds that it has more than its fair share, it starts disconnecting clients in a rate-limited fashion.  Those clients then reconnect and hopefully land on another Typha.  It's similar to how the k8s API server terminates any watches after 90 minutes so that clients reconnect and rebalance the load.

The only reason the warning would indicate a real problem is if *all* your Typha instances are disconnecting clients at the same time, in which case we may have got a bug in the "should I disconnect a client" logic.  Even if that's the case, the disconnections are still rate limited so that every client should stay connected to Typha for a long time on average.  (I.e. even if there's a  bug there, we just do what k8s API server does.)

IPAM doesn't go through Typha at all since Typha is a read-only proxy and Typha requires reading and writing in real time.

@caseydavenport given that we now have more typha clients per calico/node, maybe we need to increase Typha's default limit.  I think only Felix is the heavy Typha user and the other clients in calico/node are negligible.

**Comment by gavol** [comment]
Thanks for the detailed description, that is really appreciated.

> The only reason the warning would indicate a real problem is if all your Typha instances are disconnecting clients at the same time, in which case we may have got a bug in the "should I disconnect a client" logic.

I do not think that was the case. I can only say that all the Typha instances reached the connection limit (it was evident in the Grafana dashboard too) and with 2000 workers the disconnection messaged were quite frequent.

**Comment by fasaxc** [comment]
Aha, I think I spot a bug, there are now 4 connections per Typha but looks like the "budget" is for 3 connections per typha. That means, at 2000+ nodes we'll miscalculate the expected number of connections.

2000 nodes * 4 connections = 8000 connections
20 typhas * 400 minimum connections = 8000 connections

**Comment by fasaxc** [comment]
I put up a fix and adjusted the title of the issue.  Please can you file a new issue for the high CPU usage from using Calico IPAM?

**Comment by gavol** [comment]
>  Please can you file a new issue for the high CPU usage from using Calico IPAM?

Done: #5664. Thanks again.
