### ISSUE TITLE
All components support config file

### ISSUE THREAD

**Issue by caseydavenport** [projectcalico/calico#563]
calicoctl supports configuration through a Calico config file, which provides information about how to connect to the Calico datastore.

For example: http://docs.projectcalico.org/v2.0/reference/calicoctl/setup/etcdv2#configuration-file

Would be really great if _all_ components which access the datastore supported this.  It would make installing Calico a lot easier - just write your config file and point all the components at it (rather than configuring each individually)

Namely:

- [x] calicoctl
- [ ] Felix
- [ ] calico/node
- [ ] CNI plugins
- [ ] Libnetwork plugin
- [ ] Policy controller

**Comment by caseydavenport** [comment]
CC @djosborne

**Comment by djosborne** [comment]
What are you thoughts on flag precedence here?

1. configuration file file
2. flag (e.g. cni conf, calicoctl flags)
3. environment variable 

Maybe swap 1 with 2? Might need to have a quick design sesh on this to figure it out.

**Comment by caseydavenport** [comment]
This probably fixes https://github.com/projectcalico/cni-plugin/issues/216 as well

**Comment by tmjd** [comment]
Right now libcalico-go has the priority right now that if a config file is passed then that is used otherwise environment variables are used.  I'm a bit surprised about that precedence order. I typically expect:

1. flag  (Highest)
2. environment variable
3. config file

**Comment by tmjd** [comment]
I created https://gist.github.com/tmjd/49cbc2aba636ceafa939705db89c329f with my notes on the components current configuration methods and user stories for the components also.

**Comment by tmjd** [comment]
There is a proposal + needed changes in the internal Engineering/Designs folder documenting the decisions that have been made.
