### ISSUE TITLE
Communication broken from kube pods executed on master nodes to cluster IP using Calico BPF

### ISSUE THREAD

**Issue by hightoxicity** [projectcalico/calico#5632]
## Global context:

- Spine-leaf virtual routers setup (vqfx10k) with vagrant
- Ebgp between spines and leaves
- Ibgp between leaf and servers under this leaf with rr on virtual leaf
- Kube pod net cidr 10.233.64.0/18
- Kube service cidr 10.233.0.0/18
- Only one master node with scheduling OK for pods
- CALICO 3.20.4

## Server context:
- A cluster with 2 NICs per server, enp0s3 (a vagrant/vbox bridged interface) and enp0s8 (ip under subnets of 172.16.0.0/1, first subnet is 172.16.1.0/24 for servers under first leaf, 172.16.2.0/24 under second one, …)
- Ubuntu 20.04 with kernel 5.14, asserted that bpf volume is mounted by the system and calico is happy with ebpf

## Calico parameters:
- Peer with router
- Node to node mesh turn off
- Calico version v3.20.4
- No global as num
- ipip mode Never
- Advertise cluster IP : Enabled
- calico_ipv4pool_ipip Off
- Important one: calico_ip_auto_method: interface=enp0s8 and ip autodetect on
- calico_endpoint_to_host_action: RETURN
- calico_bpf_enabled
- calico_bpf_service_mode DSR (tested with the two possibilities)
- kube_proxy_strict_arp false
- Nat outgoing false
- One BGPPeer declared for each server to peer with the switch leaf
- calico_advertise_service_loadbalancer_ips 10.108.0.0/22

A collocating metallb with only metallb controller (no bgp/arp speakers):
                "metallb_version": "v0.11.0",
                "metallb_protocol": "bgp",
                "metallb_ip_range": “[10.108.0.0/22]“,
                "metallb_enabled": "True",
                "metallb_speaker_enabled": "False",
                "matallb_auto_assign": "False",

## What is currently working/not working:
- Node to node communication OK
- Worker node to apiserver pod communication OK
- Between pod communication (master node and/or worker nodes) OK
- From master node to apiserver pod communication OK
- Worker nodes pod to pod communication OK
- From pod on any worker node to apiserver (targeting the cluster IP of the Kubernetes api server (10.233.0.1/18)) OK
- From a pod scheduled on master node to the apiserver living on the same node (targeting the cluster IP of the Kubernetes api server (10.233.0.1/18)) NOK

## Diagnostic:
- Ebpf running OK
- Launch a net tool pod on master node and try to mtr the cluster IP (10.233.0.1), this is where it is currently a bad behaviour since, next hop is the IP of the enp0s3 interface (in my case 10.0.2.15/24) and not the interface I set for ip auto discovery

## Expected behaviour:
- In bpf mode turned on
- With several net interfaces
- Having interface discovery fetching a X interface
- We expect: pod scheduled on any node (particularly on master in our case) being able to fetch the cluster ips routing to proper X interface (targeted previously in config) as a hop to find properly the pod at end, today it takes in this particular case the bad interface and it does not know what is the route to the apiserver

## Workaround:
- My current workaround is to use ipvs because kernel knows directly how to go through the real server on node
- I could have done very hacky stuff routing packets between interfaces but it is not acceptable and it could lead to other misbehaving stuff.

We would like to use bpf instead of ipvs, it promises better performance but we know that in the target bare metal servers we will have dedicated to storage interfaces, we would like to be sure calico try to route packet consistently and using specified in configuration interface.

Thanks for any help you could bring me on this subject, I can try to add any useful information with some guidance

**Comment by hightoxicity** [comment]
In fact it does not happen only on master, it is happening fully randomly from any pod running on any node.
Other stuff, mtr is not accurate here since even when it is working (fetching 10.233.0.1), mtr is ever showing first hop on first interface with IP 10.0.2.15.

**Comment by lmm** [comment]
@tomastigera is this something you could please take a look at?

**Comment by hightoxicity** [comment]
I have found that I can lead felix route generation to use my specific IP as the source IP on my node, it is a felix config called FELIX_DEVICEROUTESOURCEADDRESS, that is better in the way I am able to see next hop as my node IP but it never go further, not able to talk to SVC ips

**Comment by fasaxc** [comment]
> From a pod scheduled on master node to the apiserver living on the same node NOK

I'm assuming that NOK means "not OK"?  OK, let's start there.  
* Is the pod on the master node host-networked or is it on the pod network?  
* What do you get for `kubectl get endpoints kubernetes`?  That will show the IP(s) that Calico is DNATting the traffic to.  Do those IPs correspond to IPs on the master node or something else?
