### ISSUE TITLE
'IP Autodetection methods' doesn't explain why you'd want to do this

### ISSUE THREAD

**Issue by lwr20** [projectcalico/calico#565]
http://docs.projectcalico.org/v2.1/reference/node/configuration

The IP Autodetection Methods section doesn't explain why you'd want to do this, or why this isn't useful when using the kubernetes datastore driver (at present). 

That doc feels like a good place to do so.

**Comment by djosborne** [comment]
Mostly fixed by #570 but we still don't mention why this isn't necessary for when using Kubernetes datastore driver. 

I'm going to close this issue and move that aspect over it to #500
