### ISSUE TITLE
Readiness Probe failing for Pods

### ISSUE THREAD

**Issue by nmathew** [projectcalico/calico#5650]
Readiness Probe fails for certain pods, when we have some multus related routes installed on pod.

local ping to pod's primary interface fails, ICMP packets are reaching eth0 interface with first-found IP as the source address.

First found interface with IP is an IP in the multus IP range, so return ICMP gets routed through another multus interface, hence ping and readiness probe fails.

## Your Environment
Calico version v3.19.1
Multus version: v3.7.2
Kubernetes version v1.21.1
runtime: containerd://1.4.4
Host: SLES 15 sp2 kernel 5.3.18

**Comment by caseydavenport** [comment]
> when we have some multus related routes installed on pod.

What are your multus routes like?

We nominally don't support multi-interfaces within Calico pods, so there could be something going on here. 

I suggest you dig into why the pings aren't working - are routes in place on the host? Is ARP successful? etc.
