### ISSUE TITLE
Make binary downloading in unit files more robust

### ISSUE THREAD

**Issue by tmjd** [projectcalico/calico#566]
At one point I brought up a kubernetes cluster and I believe either due to very slow download, resulting in a timeout of the service start, or perhaps an interrupted download produced a half downloaded binary.  In my case this was the kubelet binary.  On the next attempt to start the service the partially downloaded binary is ran causing an immediate failure.  This is because we use the -N (Turn on time-stamping) flag with wget, so even though the file is only partially there the timestamp looks fine so wget does not attempt to re-download it.

I think my problem was due to a slow download so I added `TimeoutStartSec=infinity` to the unit definitions in the cloud config files, we could possibly add this too but I feel like a more robust approach to make sure the binaries are correct would be a better route.

**Comment by caseydavenport** [comment]
The Vagrant demo has been removed now.
