### ISSUE TITLE
Calico node plugins and controllers go into CLBF/Error state after all node restarts on Arm64 platform

### ISSUE THREAD

**Issue by abhilashshetty04** [projectcalico/calico#5669]
Calico node plugins and controllers go into CLBF/Error state after all node restarts

Context:
I am sure this is highly matured product. However, My context is little different.

I have multiple K8s clusters on amd64 arch. Currently i am installing K8s on Macbook pro M1 chip model hence its Arm64 architecture. I am using VMware fusion tech preview for Apple silicon and relevant Arm64 image for ubuntu for K8s platform.

## Cluster setup
I follow standard kubernetes documentation to install Docker, kubeadm and all related package. I have not found any other variants for Arm64 platform. Please correct me if i am wrong.  All machines have static IPs, are in same L2. Always have internet access.

I have used following guide to install calico cni.

https://projectcalico.docs.tigera.io/getting-started/kubernetes/quickstart 

In VMware fusion since machines are getting 192.168.0.0/24 subnets for VMs through my wifi, I have used pod-cidr to use 10.0.0.0/16 in kubeadm init and modified Installation object's cidr accordingly.

Right after i apply tigera-operator.yaml and custom-resource.yaml. I see that all pods in calico-system and kube-system are in Running state. Since this in my laptop i do make sure K8s system is stable after multiple all node restarts.

After the first restart cycle only all or some calico pods go in error/crashLoopBackOff state. I am attaching before and after restart kubectl outputs and logging for all calico pods. 

[calico after deply.txt](https://github.com/projectcalico/calico/files/8146462/calico.after.deply.txt)
[calico after all node restart.txt](https://github.com/projectcalico/calico/files/8146463/calico.after.all.node.restart.txt)

## Steps to Reproduce (for bugs)
What i noticed is its not reproducible in Intel chip machines. I have tried to install multiple times in Macbook M1 (Arm64). Its reproducible all the time.

##My observation:

abhilash@lvm-master:~$ kubectl get pods -n calico-system -owide
NAME                                       READY   STATUS             RESTARTS            AGE    IP              NODE         NOMINATED NODE   READINESS GATES
calico-kube-controllers-77c48f5f64-6qf4b   0/1     Error              0                   106m   <none>          lvm-node-1   <none>           <none>
calico-node-nlkzx                          0/1     Error              2 (8s ago)          106m   192.168.0.150   lvm-node-1   <none>           <none>
calico-node-wntp5                          0/1     CrashLoopBackOff   20 (2m ago)         106m   192.168.0.100   lvm-master   <none>           <none>
calico-node-xccrb                          0/1     Running            1 (<invalid> ago)   106m   192.168.0.200   lvm-node-2   <none>           <none>
calico-typha-6d86dfdfcd-4plbq              1/1     Running            1 (96m ago)         106m   192.168.0.200   lvm-node-2   <none>           <none>
calico-typha-6d86dfdfcd-kjvcw              0/1     Running            2 (<invalid> ago)   106m   192.168.0.150   lvm-node-1   <none>           <none>

I see some of the network interface missing on the master and lvm-node-1 post restart. I dont see anything mission on lvm-node-2 but i forgot to take interface output before restart for that node. I am attaching "ip a" for nodes.

[network interface before after restart.txt](https://github.com/projectcalico/calico/files/8146519/network.interface.before.after.restart.txt)
 

## Context
I work with Mayadata/Datacore . We work mainly on storage Engines. I would use this cluster to dev/test K8s storage specific platforms.

## Your Environment

* Calico version
* Orchestrator version: Kubernetes 1.23
* Operating System and version: 
* abhilash@lvm-master:~$ hostnamectl
   Static hostname: lvm-master
         Icon name: computer-vm
           Chassis: vm
        Machine ID: 81b2486b2a3d4f17b669067757aacdf4
           Boot ID: 5b4844f02a034e9397287fdda530daf7
    Virtualization: vmware
  Operating System: Ubuntu 20.04.3 LTS
            Kernel: Linux 5.4.0-100-generic
      Architecture: arm64
* Link to your project (optional):
* 
Any help would be really appreciated. I have takes snapshot of all VMs before kubeadm and calico installation. Please let me know if any one wants to try something different i can revert and do again.

**Comment by caseydavenport** [comment]
Based on your logs, I don't see anything indicating that this is an architecture related issue - rather it looks like there may be routing / RBAC issues with your underlying Kubernetes cluster and node infrastructure. 

What makes you believe that this is related to the M1 chip specifically?

**Comment by abhilashshetty04** [comment]
Hi Casey, As i said i have multiple clusters on Intel based processors. During installation as well i apply cusom-resource and tiger-operator yaml which installs all objects in separate ns. I dont see any erros in the installation. 

With respect to connectivity . All ips on kube nodes are static . Upon reboot they are same i dont see any networking changes with respect to ens160 interface. However, i said i do see calico/flannel interface going missing intermittently .

I have tried flannel as well on different set of clusters in Same Macbook. i see same issues after reboot

I have attached calico after deploy.txt and calico after node restart.txt . As you can see most of the kube-system containers are not running after restart. Before restart everything was okay.

Do you want me to check anything in specific .

**Comment by caseydavenport** [comment]
> As i said i have multiple clusters on Intel based processors

My point was that the architecture is likely to not be the only difference between these clusters, and the logs suggest that this is a networking issue of some sort rather than say, running a binary built for a different architecture, further suggesting that it's not necessarily the fact that they are running on different archtiectures, but perhaps that the network is setup differently in VMWare fusion than it is in your other clusters (for example)

> 2022-02-26 10:23:34.324 [INFO][1] watchercache.go 245: Failed to create watcher ListRoot="/calico/resources/v3/projectcalico.org/nodes" error=Get "https://10.96.0.1:443/api/v1/nodes?resourceVersion=2836&watch=true": dial tcp 10.96.0.1:443: connect: connection refused performFullResync=false

> However, i said i do see calico/flannel interface going missing intermittently .

Could you explain what you mean by this? Which Calico interface is going missing?

> Do you want me to check anything in specific .

The main issue appears to be that the nodes cannot reach 10.96.0.1 due to a connection refused. This suggests to me that one of the following might be the case:

- kube proxy is not healthy, or programming the wrong rules to reach the API server.
- The apiserver is not healthy and is rejecting connections.
- there is another routing issue between the nodes and the control plane node hosting the API server.

I'd look into all of those, and also confirm whether or not you are able to manually reach the API server on one of your nodes (e.g., via curl) both to the service IP and also try via the node IP itself to see if the behavior is different.

**Comment by abhilashshetty04** [comment]
1. Could you explain what you mean by this? Which Calico interface is going missing?
Ans: I see all the interface created by calico are getting removed once the node restarts. I created 1 more cluster from the scratch yesterday to record all the behavior again.

I am attaching output from all 3 nodes highlighting configs at each stage of cluster deployment.

Please see the attached files.

[node1.txt](https://github.com/projectcalico/calico/files/8197974/node1.txt)
[node2.txt](https://github.com/projectcalico/calico/files/8197975/node2.txt)
[node3.txt](https://github.com/projectcalico/calico/files/8197977/node3.txt)


If you see everything is as expected. All pods and Containers in kube-system and calico are Running. We see multiple interfaces which are created in each node.

I made sure i take snapshot of all 3 vms in VMware fusion before i shutdown and start them again. As soon as node boots up, I see lo, ens160 and docker0 interface only in all the nodes. All interfaces which were from calico are missing.

Right at that time all pods in calico-system and kube-system went into Error/CLBF state. At this state control plane is not functional.

abhilash@kube-node-1:~$ kubectl get pods -n kube-system
NAME                                  READY   STATUS      RESTARTS        AGE
coredns-64897985d-4r2gf               0/1     Completed   0               19m
coredns-64897985d-hqv5w               0/1     Completed   0               19m
etcd-kube-node-1                      0/1     Running     1 (3m2s ago)    20m
kube-apiserver-kube-node-1            0/1     Running     1 (2m52s ago)   20m
kube-controller-manager-kube-node-1   0/1     Running     1 (3m1s ago)    20m
kube-proxy-g8rvs                      1/1     Running     1 (2m51s ago)   18m
kube-proxy-hjb97                      1/1     Running     1 (2m39s ago)   18m
kube-proxy-zp2wv                      1/1     Running     1 (3m2s ago)    19m
kube-scheduler-kube-node-1            0/1     Running     1 (3m2s ago)    20m

kube proxy containers were up. Core dns were down . ETCD and api servers were also down. I reverted snapshot and everything came back to original state. 

I tried restart once again i see following :

All calico created interface are missing as seen in previous logs. each vms had only 3 interfaces. Now i see following cluster state.

abhilash@kube-node-1:~$ kubectl get pods -n kube-system
NAME                                  READY   STATUS      RESTARTS        AGE
coredns-64897985d-4r2gf               0/1     Completed   0               2d3h
coredns-64897985d-hqv5w               0/1     Completed   0               2d3h
etcd-kube-node-1                      1/1     Running     1 (3m26s ago)   2d3h
kube-apiserver-kube-node-1            1/1     Running     2 (3m16s ago)   2d3h
kube-controller-manager-kube-node-1   1/1     Running     3 (3m26s ago)   2d3h
kube-proxy-g8rvs                      1/1     Running     1 (3m7s ago)    2d3h
kube-proxy-hjb97                      1/1     Running     1 (3m16s ago)   2d3h
kube-proxy-zp2wv                      1/1     Running     1 (3m26s ago)   2d3h
kube-scheduler-kube-node-1            1/1     Running     2 (3m26s ago)   2d3h
abhilash@kube-node-1:~$ kubectl get pods -n calico-system
NAME                                       READY   STATUS    RESTARTS        AGE
calico-kube-controllers-67f85d7449-gb7g7   0/1     Error     7               2d3h
calico-node-cxlsz                          0/1     Running   1 (3m20s ago)   2d3h
calico-node-gxtb6                          0/1     Running   1 (3m39s ago)   2d3h
calico-node-q6nvq                          0/1     Running   1 (3m29s ago)   2d3h
calico-typha-54ddf65ccd-j9rrp              0/1     Running   1 (3m20s ago)   2d3h
calico-typha-54ddf65ccd-vpqk5              1/1     Running   1 (3m29s ago)   2d3h

Logs from calico controller which is in Error state.
[new controller log.txt](https://github.com/projectcalico/calico/files/8198131/new.controller.log.txt)

I am able to do curl from node 2 and 3 to API server. I guess thats because api server, etcd all are up except coredns in kube-system ns. This is random last time if you check after restart more pods were not running in kube-system.

abhilash@kube-node-3:~$ curl https://10.96.0.1
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
abhilash@kube-node-3:~$ 

abhilash@kube-node-2:~$ curl https://10.96.0.1
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
abhilash@kube-node-2:~$ 


I have given 1 "Share with Mac" interface to all vms. In linux they are discovered as ens160. I have not seen any changes to that interfaces since the deployment. Connectivity to that interface is fine.

I think VMware fusion is only responsible for ens160 as vmware knows only that interface as part of VM inventory. All virtual interface created by calico has to be provisioned and managed by Ubuntu/calico. Please correct me if i am wrong.

I can reproduce this easily as i have snapshotted all vms. Let me know if you need any logs. If you wish we can setup meeting as well if you want to check things yourself.

**Comment by abhilashshetty04** [comment]
Sorry for the delayed response. I guess this can be closed i am not going forward with k8s installation on VMware fusion on macbook m1. Thanks
