### ISSUE TITLE
NetworkPlugin cni failed to set up pod

### ISSUE THREAD

**Issue by edenbuaa** [projectcalico/calico#5674]
I use the calico cni in k8s cluster,  this error was reported for daemonset pod:

`NetworkPlugin cni failed to set up pod "xxx" network: the given pool (10.233.64.0/18) does not exist, or is not enabled.`

Can anyone help?  thanks.

**Comment by caseydavenport** [comment]
Sounds like you have requested a specific IP pool in your request to launch a pod and that pool doesn't exist. You should either create that IP pool, or remove the explicit IP pool request from your pod. I think the error message is pretty clear.

For future issues, please fill out the issue template as requested.
