### ISSUE TITLE
is any wat to change networkpolicy action log output ?

### ISSUE THREAD

**Issue by jeffwu0624** [projectcalico/calico#5677]
calico version 3.18.1
kubernetes 1.19.7

I have configured policies and logs in calico networkpolicy, it work fine, but  is any wat to change action log to record in the node's syslog?

[Generate logs for specific traffic](https://projectcalico.docs.tigera.io/archive/v3.17/security/calico-network-policy#generate-logs-for-specific-traffic)

**Comment by caseydavenport** [comment]
> but is any wat to change action log to record in the node's syslog?

yes, as per the docs that you linked to this is already where the log action records to.

> In the following example, incoming TCP traffic to an application is denied, and each connection attempt is logged to syslog.



Also, please fill out the issue template when opening issues.
