### ISSUE TITLE
General content improvements (style, consistency etc.)

### ISSUE THREAD

**Issue by robbrockbank** [projectcalico/calico#568]
A lot of our docs are authored in subtly different ways.  Would be good to go through the entire docs and provide a more common use of MD directives.

For example:

- [ ] Consistent use of numbered headings when describing a set of instructions
- [x] Remove the clickable links and replace with inline bold links at the start of the line (e.g. see k8s AWS install instructions)
- [x] calico/node environment table has extra column
- [ ] Index for the calico integrations page has a bulleted list that duplicates the LHS menu - seems like a maintenance nightmare.
- [ ] usage and reference index pages need beefing up with some decent text
- [x] mesos demo is actually an installation option (vagrant) and numbering is off: 1, 1.2, 3
- [ ] intro page is text heavy
- [ ] Calico over ethernet fabrics page talks about the document being a tech note.
- [x] docker overview duplicates the side bar menu.  should simplify 
- [ ] Open stack guide uses Part 0, Part 1 etc... just use normal section numbering
- [ ] big headings in usage: external connectivity

**Comment by caseydavenport** [comment]
@robbrockbank this feels like a whole bunch of issues crammed into one.  I think we should do a bunch of these, but it seems like it will be easier to split this work out and give the right bits the right priority if they were separate issues.

**Comment by robbrockbank** [comment]
I'm closing this as these are stylistic issues that will hopefully be resolved through our docs expert.
