### ISSUE TITLE
Using Calico Network Policy in Operator

### ISSUE THREAD

**Issue by dtrouillet** [projectcalico/calico#5686]
Hi, I would like to use Calico Network Policy in my Operator (using Go Operator SDK).

I know that Calico use a custom kube client with calicoctl.
But how can use crd.projectcalico.org v1 in my operator ?

Today I was trying to use projectcalico.org v3 (with go package "github.com/projectcalico/api/pkg/apis/projectcalico/v3") but this is not a CRD in Kubernetes.

Do you have any idea to help me?

## Your Environment

* Calico version : Canal 3.13.3
* Orchestrator version (e.g. kubernetes, mesos, rkt): Kubernetes RKE2 1.21.5
* Operating System and version: Redhat 8

**Comment by caseydavenport** [comment]
> But how can use crd.projectcalico.org v1 in my operator ?

Don't use this - it's not supported, not validated, not deafulted, and is likely to break your cluster if you are not careful.

You want to use the projectcalico.org/v3 API, which is implemented by the Calico API server described here: https://projectcalico.docs.tigera.io/maintenance/install-apiserver

**Comment by caseydavenport** [comment]
API clients and structures are here: https://github.com/projectcalico/api

**Comment by dtrouillet** [comment]
Thanks @caseydavenport for your answer and advice !
