### ISSUE TITLE
Every 40-60 minutes packets dropped on VXLAN network interface 

### ISSUE THREAD

**Issue by gvych** [projectcalico/calico#5696]
## Expected Behavior
No dropped packets on vxlan network interface during normal operation.

## Current Behavior
Each host experience short period packet drop of transmit packet on vxlan network interface every 40-60 minutes. 

## Possible Reason
- Some kind of hourly internal Calico job, like configuration rebuild, creates pause in vxlan interface functioning?
- Configuration in my calico-vxlan.yaml file produces Calico miss-configuration? 

## Steps to Reproduce
1. clone https://github.com/gvych/calico-packet-drop-problem repository `git clone https://github.com/gvych/calico-packet-drop-problem.git; cd calico-packet-drop-problem`
2. create AWS EKS cluster `eksctl create cluster -f eksclt.yaml`
3. install Calico `kubectl apply -f calico-vxlan.yaml`
4. install prometheus-operator using Helm `helm repo add prometheus-community https://prometheus-community.github.io/helm-charts; helm repo update; helm install prometheus prometheus-community/kube-prometheus-stack`
5. establish connection to Grafana `kubectl port-forward -n default  svc/prometheus-grafana 8080:80`
6. login to Grafana using credentials User:admin Pass:prom-operator on http://localhost:8080
7. each hour you will see metric instance:node_network_transmit_drop_excluding_lo:rate5m{} increases (independently for each server) [Grafana Request Example](http://localhost:8080/explore?orgId=1&left=%5B%22now-3h%22,%22now%22,%22Prometheus%22,%7B%22refId%22:%22A%22,%22instant%22:true,%22range%22:true,%22exemplar%22:true,%22expr%22:%22instance:node_network_transmit_drop_excluding_lo:rate5m%7B%7D%22%7D%5D)
![image](https://user-images.githubusercontent.com/11071790/156511206-2ec238f7-12e6-43ec-8a2b-6c046ed18fdc.png)

Using request `rate(node_network_transmit_drop_total [10m] ) > 0 ` you can see, that all packet drop events occur on vxlan.calico network interfaces
![image](https://user-images.githubusercontent.com/11071790/156511062-cd9cd845-d630-4466-83df-2ad4d90a65ea.png)
 

## Context
Our system experiencing sporadic TCP connection resets from Pods to other Pods or public internet (error messages we get: "read: connection reset by peer reset by peer").  

## Your Environment

* Calico version:
  "cniVersion": "0.3.1"
          image: docker.io/calico/cni:v3.22.0
          image: docker.io/calico/pod2daemon-flexvol:v3.22.0
          image: docker.io/calico/node:v3.22.0
          image: docker.io/calico/kube-controllers:v3.22.0
* Orchestrator version:
     AWS EKS version.Info{Major:"1", Minor:"20+",
* Operating System and version:
      Default AWS nodes used by eksctl (us-east-2 region)
      t3a.small	ami-0e0c65ae692674f99
* Link to your project (optional):
     https://github.com/gvych/calico-packet-drop-problem

**Comment by caseydavenport** [comment]
Are there any logs coming from calico/node at the time of the packet loss that might suggest it's performing some work? I'm not aware of any cyclic background task like this but perhaps there's something going on (e.g., a resync with the datastore or something)

**Comment by lwr20** [comment]
Is there any chance this is DHCP renewal on the nodes?  Calico doesn't have any timers that trigger hourly.

**Comment by gvych** [comment]
> Are there any logs coming from calico/node at the time of the packet loss that might suggest it's performing some work? I'm not aware of any cyclic background task like this but perhaps there's something going on (e.g., a resync with the datastore or something)

Nope, background "noise" logs did not differ in any way from logs around packet drops.

**Comment by gvych** [comment]
> Is there any chance this is DHCP renewal on the nodes? Calico doesn't have any timers that trigger hourly.

Very interesting idea. Will check!

**Comment by gvych** [comment]
Yeap, default lease time from AWS VPC is 1 hour
`[root@ip-192-168-108-88 dhcp]# cat /var/lib/dhclient/dhclient--eth0.lease
...
  option dhcp-lease-time 3600;
`

Will look deeper into AWS EC2 side. 
Thanks for the great hint!
