### ISSUE TITLE
Identify if Calico CNI was used inside AWS

### ISSUE THREAD

**Issue by bongaquino** [projectcalico/calico#5702]
Good day. We're currently experiencing concerns related to Calico inside AWS. We are not aware that this was implemented. We're planning to downgrade the pod, but before doing that, we would like to seek your advice before taking action. We will wait for your reply. 

Have a productive day ahead. Thanks.

**Comment by caseydavenport** [comment]
Please fill out the issue template when raising issues. 

There's not enough information here for us to provide any sort of help or insight here, or even begin to guess at what symptoms you're experiencing.

I'm going to close this - please reopen another and fill out the issue template if you're still seeing issues.
