### ISSUE TITLE
Containers cannot communicate when hosted on separate hypervisors

### ISSUE THREAD

**Issue by jeanluclariviere** [projectcalico/calico#5704]
We have deployed a Rancher RKE1 Kubernetes cluster on VMWare with Calico and found that the containers running on one hypervisor cannot communicate with containers running on another hypervisor.

Network flow:
container1 ---> VM1(RHEL) --> ESX host1 --> physical switch --> ESX host2 --> VM2(RHEL) --> container 2

So far, we've determined that neither ICMP or TCP packets (ping, http) are working from one container to another.

## Expected Behavior
I can ping and/or connect via TCP containers running from one hypervisor (ESX) to another.

## Current Behavior
Pinging containers on the same hypervisor are 100% successfull
Pinging containers on different hypervisors results in 100% packet loss

## Possible Solution
Unknown

## Your Environment
Rancher RKE1 1.21.9 w/calico
RHEL 8.3

**Comment by jeanluclariviere** [comment]
Further troubleshooting of this issue has led me to the IP in IP encapsulation calico uses. After editing the default IPPool configured by Calico and setting the "**ipipMode**" from "**Always**" to "**CrossSubnet**", communication began working again between pods.

I suspect that some device in the network path is having issues decapsulating the traffic? Would love to get more context on this.

```
apiVersion: crd.projectcalico.org/v1
kind: IPPool
metadata:
  annotations:
    projectcalico.org/metadata: '{"uid":"6dca6b31-1601-4205-b642-4552df28b603","creationTimestamp":"2022-02-24T21:59:28Z"}'
  creationTimestamp: "2022-02-24T21:59:28Z"
  generation: 6
  name: default-ipv4-ippool
  resourceVersion: "3060678"
  uid: 87a21d8e-24c9-48f7-b511-9a3134ed6c04
spec:
  blockSize: 26
  cidr: 10.245.0.0/16
  ipipMode: CrossSubnet
  natOutgoing: true
  nodeSelector: all()
  vxlanMode: Never
```

**Comment by lwr20** [comment]
If you want faster support, consider the calico users slack: http://slack.projectcalico.org/

**Comment by jeanluclariviere** [comment]
@lwr20 thanks for the info. We have a few support cases open with some of our vendors, we'll look into it and I will update this issue accordingly.

**Comment by jeanluclariviere** [comment]
> Alternatively, you might consider switching from IPIP to VXLAN encap (which is usually allowed by these sorts of things)

@lwr20, just ran a quick test. Disabling IPIP mode and using VXLan fails, using _always_ or _crosssubnet_ causes traffic to fail from pods running on 1 ESXi host to another.

**Comment by lwr20** [comment]
FWIW, if you want to be certain what's going on, `tcpdump` is they way to go.  

If, as I suspect, the packets are being dropped by something in VMWare, you'll see the encapped packets leaving one host VM and failing to arrive at the destination host VM.  

If you see no packets leaving the source host, that would suggest a Calico problem.  Or arriving at the destination VM and not making it to the pod.

**Comment by jeanluclariviere** [comment]
We've done a few packet captures. On the VM from which the traffic is originating, it does appear as though traffic is leaving the VM, but the capture is full TCP errors, specifically TCP [RST] (connection reset), followed by a flood of TCP retransmissions and out-of-order.

On the receiving VM, we see far few entries, but do see some TCP retransmission errors warnings.

What's strange is we have other Kubernetes environments running on these same ESXi hosts using Canal (vxlan) and these aren't experiencing any issues; those working clusters are running kubeadm vanilla clusters though, compared to these RKE1 clusters.

**Comment by lwr20** [comment]
> using Canal (vxlan) and these aren't experiencing any issues

That's extremely odd.  Calico's VXLAN implementation is almost identical to Flannel's.  

@caseydavenport any ideas about TCP errors?

**Comment by jeanluclariviere** [comment]
> That's extremely odd. Calico's VXLAN implementation is almost identical to Flannel's.

To be fair, this isn't a like-for-like comparison. The VMs where canal is being used are running RHEL 8.5, whereas these VMs are running 8.3 as that is what is supported for RKE1.

Not going to lie though, was very surprised when VXLAN didn't work. I used the following config:

```
apiVersion: crd.projectcalico.org/v1
kind: IPPool
metadata:
  annotations:
    projectcalico.org/metadata: '{"uid":"6dca6b31-1601-4205-b642-4552df28b603","creationTimestamp":"2022-02-24T21:59:28Z"}'
  creationTimestamp: "2022-02-24T21:59:28Z"
  generation: 6
  name: default-ipv4-ippool
  resourceVersion: "3060678"
  uid: 87a21d8e-24c9-48f7-b511-9a3134ed6c04
spec:
  blockSize: 26
  cidr: 10.245.0.0/16
  ipipMode: Never
  natOutgoing: true
  nodeSelector: all()
  vxlanMode: Always
```

**Comment by lwr20** [comment]
I wonder if its something to do with VXLAN checksum offloading in RHEL?  ISTR seeing something like that a while back.  @fasaxc or @tomastigera might know about that?

**Comment by jeanluclariviere** [comment]
@lwr20 it's possible. We initially thought we ran into this issue: https://access.redhat.com/solutions/5881451. We tried disabling offloading for the different interfaces and that didn't seem to help. Later, it was confirmed that if that was the case, ICMP packets wouldn't be effected, but since our overlay tests reveal that both ICMP (ping) and TCP (http) packets are failing, this is not likely the case.

Hoping to run some packet captures at the ESXi level this week, will keep you posted.

**Comment by dtrouillet** [comment]
Hi,

We experienced the same behaviors.
Redhat 8.5, rke2, calico 3.19.2.

When the 3vms are one same ESXI it works but no when on 2 separates ESXI.

We try to reproduce with 3 others VM and we do not success. 

Before using Calico with VXLAN we are using Canal with VXLAN without any problems. 

Regards

**Comment by dtrouillet** [comment]
Hi,

For your information. We use Wireshark, and the behaviour not the good one.
The trafic is on a bad interface (we have several ethXXXX (xxx are a string).

So we edit the Installation CRD to set IP_AUTODETECTION_METHOD with the good interface (interface=ethMYXX.*) and it works !!!

Thanks for the help

**Comment by jeanluclariviere** [comment]
Not convinced @dtrouillet's issue is the same as ours. Just as a follow up, working with VMWare we recently identified that VLAN tags are being stripped from one ESXi host to the other. So traffic appears to leave ESXi host 1 with VLAN tag "1234", but when traffic arrives on ESXi host 2, the VLAN tag has been stripped, therefor traffic gets lost.

They've confirmed the issue could be on the NIC Drivers or even some device on the physical network doing this - we still don't know. In either case, we aren't using encapsulation now so not as much of an issue for us.
