### ISSUE TITLE
Calico Finding wrong IP address from ???

### ISSUE THREAD

**Issue by koehn** [projectcalico/calico#5705]
## Expected Behavior
My canal configuration specifies using `ens10` as the canal interface. IP address 10.0.0.2 is the only IP address bound to that interface. Calicoctl should show 10.0.0.2 as the proper IP address for that node.

## Current Behavior
Calicoctl shows 10.200.0.1 as the IP address. Nodes are able to communicate with one another, unless I turn on Wireguard, in which case nodes with 10.200.0.x addresses cannot communicate with 10.0.0.x machines.

## Possible Solution
No idea.

## Steps to Reproduce (for bugs)
I'm trying to determine where it's getting this address from. Copious logs and output below. 

## Context
My nodes are on a 10.0.0.0/16 CIDR network. So this looked strange:

```
calicoctl get nodes -o wide
NAME            ASN       IPV4            IPV6   
k3s-worker-03   (64512)   10.200.0.4/32          
k3s-worker-01   (64512)   10.0.0.4/32            
k3s-worker-02   (64512)   10.0.0.5/32            
k3s-master      (64512)   10.200.0.1/32 
```
I confirmed with `ip addr` and `ifconfig` that no 10.200.0.1 address is bound to any interface on the machine.

Further digging through logs turned up this in `k3s-master`'s `calico-node` logs:
```
2022-03-04 15:24:14.386 [INFO][9] startup/startup.go 425: Early log level set to info
2022-03-04 15:24:14.390 [INFO][9] startup/utils.go 127: Using NODENAME environment for node name k3s-master
2022-03-04 15:24:14.392 [INFO][9] startup/utils.go 139: Determined node name: k3s-master
2022-03-04 15:24:14.392 [INFO][9] startup/startup.go 94: Starting node k3s-master with version v3.22.1
2022-03-04 15:24:14.406 [INFO][9] startup/startup.go 430: Checking datastore connection
2022-03-04 15:24:14.430 [INFO][9] startup/startup.go 454: Datastore connection verified
2022-03-04 15:24:14.430 [INFO][9] startup/startup.go 104: Datastore is ready
2022-03-04 15:24:14.525 [WARNING][9] startup/startup.go 621: Unable to confirm IPv4 address 10.200.0.1 is assigned to this host
2022-03-04 15:24:14.574 [INFO][9] startup/startup.go 674: FELIX_IPV6SUPPORT is false through environment variable
2022-03-04 15:24:14.587 [INFO][9] startup/startup.go 218: Using node name: k3s-master
CALICO_NETWORKING_BACKEND is none - no BGP daemon running
Calico node started successfully
```
To me it seems like calico is getting the 10.200.0.1 IP address from some configuration somewhere, not that it's configured on the OS. 

Places I've looked:
* Every ConfigMap in `kube-system`
* Every place in the k3s datastore (by dumping the database to a text file)
* [`k3s.service`](https://pastebin.com/CGrQ0jL6)
* `k3s.yaml`
* [`canal.yaml`](https://pastebin.com/T2tRYaZm)
* `/etc/cni/net.d`
* The entire `/etc` and `/var` directory of the host machine using recursive `grep`
* The environment variables of the calico container

FWIW, Felix seems to know about it:
```
2022-03-04 15:25:02.749 [INFO][49] felix/int_dataplane.go 1520: Received *proto.HostMetadataUpdate update from calculation graph msg=hostname:"k3s-worker-01" ipv4_addr:"10.0.0.4" 
2022-03-04 15:25:02.749 [INFO][49] felix/int_dataplane.go 1520: Received *proto.HostMetadataUpdate update from calculation graph msg=hostname:"k3s-worker-03" ipv4_addr:"10.200.0.4" 
2022-03-04 15:25:02.749 [INFO][49] felix/int_dataplane.go 1520: Received *proto.HostMetadataUpdate update from calculation graph msg=hostname:"k3s-worker-02" ipv4_addr:"10.0.0.5" 
2022-03-04 15:25:02.749 [INFO][49] felix/int_dataplane.go 1520: Received *proto.HostMetadataUpdate update from calculation graph msg=hostname:"k3s-master" ipv4_addr:"10.200.0.1" 
```

I've been working my way through the source to try to find out how the configuration is getting loaded, since the 10.200.0.1 address seems like it's configured via either k3s or canal somehow. At least, if it's configured to the OS I cannot find it. 

## Your Environment
* Calico version 3.22.1
* Orchestrator version (e.g. kubernetes, mesos, rkt): Kubernetes (native datastore; not etcd)
* Operating System and version: Ubuntu 20.04

**Comment by caseydavenport** [comment]
Hm, I believe those addresses come from Calico's IP auto-detection capability (if enabled) - how did you install Calico and did you configure an IP autodetection method? It's discussed a bit here: https://projectcalico.docs.tigera.io/networking/ip-autodetection

**Comment by koehn** [comment]
I configured it using this [`canal.yaml`](https://pastebin.com/T2tRYaZm) file. I don't think any auto detection is enabled; when I try to apply the "Internal IP" auto detection from the page you linked I get an error:
```
error: unable to recognize "auto-detection.yaml": no matches for kind "Installation" in version "operator.tigera.io/v1"
```

I'm not sure where those CRDs are supposed to come from, but I don't have them. I suppose that means I'm using first-found?

**Comment by koehn** [comment]
Here's the `calicoctl` yaml for the `k3s-master` node:
```
kind: Node
metadata:
  annotations:
    projectcalico.org/kube-labels: '{"beta.kubernetes.io/arch":"amd64","beta.kubernetes.io/instance-type":"k3s","beta.kubernetes.io/os":"linux","csi.hetzner.cloud/location":"nbg1","kubernetes.io/arch":"amd64","kubernetes.io/hostname":"k3s-master","kubernetes.io/os":"linux","node-role.kubernetes.io/control-plane":"true","node-role.kubernetes.io/master":"true","node.kubernetes.io/instance-type":"k3s"}'
  creationTimestamp: "2022-03-01T03:20:12Z"
  labels:
    beta.kubernetes.io/arch: amd64
    beta.kubernetes.io/instance-type: k3s
    beta.kubernetes.io/os: linux
    csi.hetzner.cloud/location: nbg1
    kubernetes.io/arch: amd64
    kubernetes.io/hostname: k3s-master
    kubernetes.io/os: linux
    node-role.kubernetes.io/control-plane: "true"
    node-role.kubernetes.io/master: "true"
    node.kubernetes.io/instance-type: k3s
  name: k3s-master
  resourceVersion: "454542"
  uid: 65218460-a98b-4185-8be8-5c009169cbb9
spec:
  addresses:
  - address: 10.200.0.1/32
    type: CalicoNodeIP
  - address: 10.0.0.2
    type: InternalIP
  - address: 10.0.0.2
    type: ExternalIP
  bgp:
    ipv4Address: 10.200.0.1/32
    ipv4IPIPTunnelAddr: 10.42.0.1
  orchRefs:
  - nodeName: k3s-master
    orchestrator: k8s
  wireguard:
    interfaceIPv4Address: 10.42.0.1
status:
  podCIDRs:
  - 10.42.0.0/24
```

**Comment by koehn** [comment]
Also this happened:
```
calicoctl node run --ip=autodetect --ip-autodetection-method=interface=ens.\*
Error executing command: 'calicoctl node' commands are not available on this OS
```

(I have MacOS/arm64 where I'm running calicoctl).

**Comment by koehn** [comment]
Adding this to the `canal` DaemonSet didn't change anything:
```
        - name: IP_AUTODETECTION_METHOD
          value: interface=ens.*
```

**Comment by caseydavenport** [comment]
Your manifest has this set:

```
            # No IP address needed.
            - name: IP
              value: ""
```

which suggests autodetection is disabled. So then, where could those IPs be coming from?

Do your Kubernetes nodes have the `projectcalico.org/IPv4Address` annotation set? (i.e., `kubectl get nodes -o yaml | grep projectcalico.org`) Did you previously have a different version of Calico installed on this cluster somehow? 

> error: unable to recognize "auto-detection.yaml": no matches for kind "Installation" in version "operator.tigera.io/v1"

Yep, this is expected since you're not using an operator-based install. You need to look at the "Manifest" tab in the doc I linked.

**Comment by caseydavenport** [comment]
Hm, it does make me think though - for canal Calico shouldn't need or be using an IP address at all. Similarly, I don't think that wireguard encapsulation is supported with `canal` and is a feature of Calico networking (not flannel networking) and so that is likely why Wireguard isn't working. 

The presence of the IP - while a bit strange - might just be a red herring.

**Comment by koehn** [comment]
The Nodes did have that annotation set. Removing them fixed the problem; thanks!
