### ISSUE TITLE
considerations of changing pod ip cidr

### ISSUE THREAD

**Issue by tirelibirefe** [projectcalico/calico#5711]
Hello,
I've Calico v3.22.1 enabled EKS cluster v1.21.

my node cidr is 10.60.0.0/16 and pod cidr is 192.168.0.0/16.

```
$ calicoctl get ippool -o wide
NAME                  CIDR             NAT    IPIPMODE   VXLANMODE     DISABLED   DISABLEBGPEXPORT   SELECTOR
default-ipv4-ippool   192.168.0.0/16   true   Never      CrossSubnet   false      false              all()
```

I need to change default pod cidr (192.168.0.0) with something like 10.61.0.0/16 . 

I would like to follow instructions [here](https://projectcalico.docs.tigera.io/networking/migrate-pools) but  there is an expression on the page: 

> Note: The new IP pool must be within the same cluster CIDR.

...but my existing pod cidr is not in the same cluster cidr and it works.  

Here my questions:

Can I define 10.61.0.0/16 as pod cidr which is not in the same cluster CIDR?

If I define 10.60.0.0/16 as pod cidr, is it possible pod ips overlap with node ips?

I've watched the [video](https://www.youtube.com/watch?v=7LRtytR6ZbA). There will be only 1 subnet. Can I define` ipipMode: Never` ? Does it work?

My pods will access to on-prem servers through vpn. If I set `ipipMode: Never` , Will servers in on-prem network see node-ip of the pod or the pod-ip?

Thanks & Regards

**Comment by lwr20** [comment]
> ...but my existing pod cidr is not in the same cluster cidr and it works.

This is to do with the settings on kube-proxy.  If your pod-cidr isn't in the range that's configured on kube-proxy, kube-proxy will NAT pod-pod traffic between different nodes, which will break network policy (though connectivity will appear to work)
Typically you have to re-create the cluster with the correct pod-cidr defined.

Fundamentally:
- kube-proxy and calico pod-cidr settings must agree (calico pod-cidr must be wholly within the kube-proxy cluster-cidr)
- host-cidr, pod-cidr and service-cidrs to be disjoint (i.e. separate and non-overlapping)

**Comment by lwr20** [comment]
I think we discussed this in the Calico Users slack, and you got it working?  In which case I'm going to close this.  Please reopen if needed.

**Comment by tirelibirefe** [comment]
yes, correct, it worked, thank you. The ticket can be closed.
