### ISSUE TITLE
Debian10: Failed to initialize Calico datastore on kube_proxy_mode=ipvs in IPV6 environment

### ISSUE THREAD

**Issue by cpsrujana** [projectcalico/calico#5741]
### Calico-kube-controller logs

```
sudo kubectl logs -f calico-kube-controllers-694d4cdc46-7fsb9 -nkube-system
2022-03-11 13:34:47.034 [INFO][1] main.go 92: Loaded configuration from environment config=&config.Config{LogLevel:"info", WorkloadEndpointWorkers:1, ProfileWorkers:1, PolicyWorkers:1, NodeWorkers:1, Kubeconfig:"", DatastoreType:"kubernetes"}
W0311 13:34:47.038340       1 client_config.go:615] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
2022-03-11 13:34:47.040 [INFO][1] main.go 113: Ensuring Calico datastore is initialized
2022-03-11 13:34:57.041 [ERROR][1] client.go 261: Error getting cluster information config ClusterInformation="default" error=Get "https://[fd20::1]:443/apis/crd.projectcalico.org/v1/clusterinformations/default": context deadline exceeded
2022-03-11 13:34:57.041 [FATAL][1] main.go 118: Failed to initialize Calico datastore error=Get "https://[fd20::1]:443/apis/crd.projectcalico.org/v1/clusterinformations/default": context deadline exceeded
```

### More details
```
sudo curl https://[fd20::1]:443
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above
```

- fd20::1 is kubernetes service IP.

- We are able to bringup the same on Ubuntu 18.04 IPV6 environment using ipvs mode.

Please guide us, if there is a possibility on missing anything specific to kernel or the environment  ? 

$ sudo lsmod | grep ipvs
$ sudo lsmod | grep ip_vs
ip_vs_sh               16384  0
ip_vs_wrr              16384  0
ip_vs_rr               16384  19

## Your Environment

* Calico version: v3.19.2
* Orchestrator version (e.g. kubernetes, mesos, rkt) : K8s 1.21.5
* Operating System and version: Debian 10, 4.19.81-OpenNetworkLinux
* Link to your project (optional): Deployed using Kubespray 2.17.0

**Comment by caseydavenport** [comment]
Sounds like either a node networking or service / kube-proxy issue - did you run that curl command from the same node as calico/node?

**Comment by wangzhao123456** [comment]
> ## Expected Behavior
> ### Calico-kube-controller logs
> ```
> sudo kubectl logs -f calico-kube-controllers-694d4cdc46-7fsb9 -nkube-system
> 2022-03-11 13:34:47.034 [INFO][1] main.go 92: Loaded configuration from environment config=&config.Config{LogLevel:"info", WorkloadEndpointWorkers:1, ProfileWorkers:1, PolicyWorkers:1, NodeWorkers:1, Kubeconfig:"", DatastoreType:"kubernetes"}
> W0311 13:34:47.038340       1 client_config.go:615] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
> 2022-03-11 13:34:47.040 [INFO][1] main.go 113: Ensuring Calico datastore is initialized
> 2022-03-11 13:34:57.041 [ERROR][1] client.go 261: Error getting cluster information config ClusterInformation="default" error=Get "https://[fd20::1]:443/apis/crd.projectcalico.org/v1/clusterinformations/default": context deadline exceeded
> 2022-03-11 13:34:57.041 [FATAL][1] main.go 118: Failed to initialize Calico datastore error=Get "https://[fd20::1]:443/apis/crd.projectcalico.org/v1/clusterinformations/default": context deadline exceeded
> ```
> 
> ### More details
> ```
> sudo curl https://[fd20::1]:443
> curl: (60) SSL certificate problem: unable to get local issuer certificate
> More details here: https://curl.haxx.se/docs/sslcerts.html
> 
> curl failed to verify the legitimacy of the server and therefore could not
> establish a secure connection to it. To learn more about this situation and
> how to fix it, please visit the web page mentioned above
> ```
> 
> * fd20::1 is kubernetes service IP.
> * We are able to bringup the same on Ubuntu 18.04 IPV6 environment using ipvs mode.
> 
> Please guide us, if there is a possibility on missing anything specific to kernel or the environment ?
> 
> $ sudo lsmod | grep ipvs $ sudo lsmod | grep ip_vs ip_vs_sh 16384 0 ip_vs_wrr 16384 0 ip_vs_rr 16384 19
> 
> ## Your Environment
> * Calico version: v3.19.2
> * Orchestrator version (e.g. kubernetes, mesos, rkt) : K8s 1.21.5
> * Operating System and version: Debian 10, 4.19.81-OpenNetworkLinux
> * Link to your project (optional): Deployed using Kubespray 2.17.0

Hello, do you have any solutions now? I run into the same problem. 
Thanks in advance!
