### ISSUE TITLE
Felix debug logs turned on in calico.yaml

### ISSUE THREAD

**Issue by lwr20** [projectcalico/calico#575]
http://docs.projectcalico.org/master/getting-started/kubernetes/installation/hosted/k8s-backend/calico.yaml
has
```
            - name: FELIX_LOGSEVERITYSCREEN
              value: "debug"
```
in the calico-node section.  Should this be set in a production system?

**Comment by caseydavenport** [comment]
This appears to be fixed in the latest release, but the CNI plugin is still set to debug level.

**Comment by robbrockbank** [comment]
We will soon be introducing k8s 1.7 manifests, so let's at least fix this up in those manifests.
