### ISSUE TITLE
fail when cni plugins cannot be written

### ISSUE THREAD

**Issue by juliantaylor** [projectcalico/calico#5763]
When calicos install-cni container cannot install the cni plugins it just continues ignoring the error.

We occasionally see some issues in the filesystem or mounting of the host paths which causes the path to not be writable, while this is an issue elsewhere calico should not ignore this case and startup as usual as pods on this node cannot be started without the plugins.

It would be good if calico would at least optionally fail in this case.

## Expected Behavior
calico install-cni container crashes when plugins cannot be written

## Current Behavior
time="2022-03-16T11:24:21Z" level=info msg="Running as a Kubernetes pod" source="install.go:141"
time="2022-03-16T11:24:22Z" level=info msg="/host/opt/cni/bin is not writeable, skipping"
time="2022-03-16T11:24:22Z" level=info msg="/host/secondary-bin-dir is not writeable, skipping"
time="2022-03-16T11:24:22Z" level=info msg="Using CNI config template from CNI_NETWORK_CONFIG environment variable." source="install.go:322"
time="2022-03-16T11:24:22Z" level=info msg="Created /host/etc/cni/net.d/10-calico.conflist"
time="2022-03-16T11:24:22Z" level=info msg="Done configuring CNI.  Sleep= false"
-> init container completes, calico-node starts and gets ready

## Your Environment
* Calico version: v3.21.4
* kubernetes 1.21.9

**Comment by caseydavenport** [comment]
Yep, this is a bug
