### ISSUE TITLE
Documentation requires impossible prerequisite

### ISSUE THREAD

**Issue by kkeane** [projectcalico/calico#5764]
Calicoctl produces a version mismatch error when the version of calicoctl does not exactly match the version of calico running on the cluster. This is documented behavior, for instance at https://projectcalico.docs.tigera.io/maintenance/clis/calicoctl/install

However, for many calico versions, there is no matching calicoctl available. For instance, in my cluster:

```
$ calicoctl get nodes
Failed to get resources: Version mismatch.
Client Version:   v3.21.4
Cluster Version:  v3.21.1
Use --allow-version-mismatch to override.
```

An additional problem is that this strict versioning requirement can prevent managing multiple clusters with different versions of calico running.

Note: using the --allow-version-mismatch flag is a workaround, but requiring it seems to defeat the whole purpose of the versioning scheme.

## Expected Behavior

```
curl -L https://github.com/projectcalico/calico/releases/download/v3.21.1/calicoctl-linux-amd64
<downloading valid calicoctl binary>
```

## Current Behavior

```
curl -L https://github.com/projectcalico/calico/releases/download/v3.21.1/calicoctl-linux-amd64
Not Found
```

## Possible Solution
There probably are two ways to address this:
- Provide the missing versions of calicoctl
- The calicoctl binary should officially support all older versions of calico.

The second option is preferred since it also covers the use case of managing multiple clusters with different calico versions.

## Steps to Reproduce (for bugs)
Simply try to download calicoctl for 3.21.1 (or a number of other missing calicoctl versions).

## Context
This particular k8s cluster was set up with Rancher rke 1.3.7 with all default settings.

## Your Environment

* Calico version

3.21.1

* Orchestrator version (e.g. kubernetes, mesos, rkt):

kubernetes, installed by rke

* Operating System and version:

Mix of RHEL 7.9 and 8.5

**Comment by kkeane** [comment]
Thank you! In that case, can you make this a feature request?

There are two separate items:
- Documentation: Improve the documentation to list the old location (thanks for sharing it here!)
- Feature request: support multiple versions from calicoctl so multiple clouds can be supported.

**Comment by caseydavenport** [comment]
> Feature request: support multiple versions from calicoctl so multiple clouds can be supported.

For this, I would recommend checking out the API server: https://projectcalico.docs.tigera.io/maintenance/install-apiserver

What we would like to do is remove the need for calicoctl in mainline operation and have all user interaction go through `kubectl`. This is really the only feasible way to remove the version mismatch requirements and is something that is already in progress / available today.

> Documentation: Improve the documentation to list the old location (thanks for sharing it here!)

Older releases do use the old location (and newer releases use the new location) - it's really just the v3.21 release which was a transitional release and ended up in both places, unfortunately.

I'll add a note to the v3.21 docs to indicate this.

**Comment by caseydavenport** [comment]
Actually, I think it's best to just have v3.21 docs reference the "legacy" location (since all v3.21 releases are present there, but not in the new location) and then starting in v3.22 the docs will point to the new location. That should be the least confusing.
