### ISSUE TITLE
Documentation typo

### ISSUE THREAD

**Issue by xlb0479** [projectcalico/calico#5767]
As [Kernel dependencies](https://github.com/projectcalico/calico/blob/master/calico/_includes/content/reqs-kernel.md#kernel-dependencies)
`rpfilter` occurs multiple times in the describe of match criteria.

**Comment by caseydavenport** [comment]
`rpfilter` isn't a typo - https://manpages.debian.org/jessie/iptables/iptables-extensions.8.en.html#rpfilter

**Comment by xlb0479** [comment]
According to

> At least the following match criteria: `set`, `rpfilter`, `addrtype`, `comment`, `conntrack`, `icmp`, `tcp`, `udp`, `ipvs`, `icmpv6` (if IPv6 is enabled in your kernel), `mark`, `multiport`, `rpfilter`, `sctp`, `ipvs` (if using `kube-proxy` in IPVS mode).

The word `rpfilter` occurs multiple times in this sentence.
