### ISSUE TITLE
After deploying the caliconode (v3.21.3) the core dns went down. 

### ISSUE THREAD

**Issue by bphaneendra** [projectcalico/calico#5769]
## Steps to Reproduce (for bugs)

1. we built the calico from source on linux 8 
2. The image build successfully. calico-node version shows v3.21.3
3.  After deployed this image the coredns crashed, the error log shows coredns [ERROR] plugin/errors: 2 
4.

## Your Environment

* Calico version : 
* Orchestrator version (e.g. kubernetes, mesos, rkt):
* Operating System and version:
* Link to your project (optional):

**Comment by caseydavenport** [comment]
Please update the issue with more information. We need to know how you're installing Calico, what environment you're running in, what logs Calico is producing, **at a minimum** as is called out in the issue template. 

Without any more information I'm afraid there's nothing we can do to help.
