### ISSUE TITLE
calico pods can't start.

### ISSUE THREAD

**Issue by csbertran** [projectcalico/calico#5807]
calico pods can't start. Error message: calico/node is not ready: BIRD is not ready: Error querying BIRD: unable to connect to BIRDv4 socket: dial unix /var/run/bird/bird.ctl: connect: no such file or directory

## Expected Behavior
Calico pods should be up and running. 

## Current Behavior
Calico nodes stuck on restarting because BIRD is not ready. 

## Possible Solution
I've tried multiple things I saw in previous opened issues. I tried different IP_AUTODETECTION_METHOD values and I think I managed to force calico to communicate via private network instead of the public. But It seems they can't communicate either.

## Steps to Reproduce (for bugs)
1. kubeadm init --control-plane-endpoint "IP:PORT" --upload-certs
2. kubeadm join (4 other nodes)
3. kubectl apply -f calico.yaml (official one from https://projectcalico.docs.tigera.io/manifests/calico.yaml)
4. Check status of pods (kubectl get pods -n kube-system) 

## Context
I'm trying to create a Kubernetes cluster on 5 nodes (3 masters, 2 workers). I'm using Debian 10 for each server. Each server has 2 interfaces. One for public network and another one for the private network that is common between all servers (192.168.6.0/24). 
All servers can communicate with each other through this private network.
I would like all communication between nodes to be done through the private network. That is why in the "calico.yaml" configuration I specify "IP_AUTODETECTION_METHOD: interface=ens224" (which is the private network interface for all servers). Still, it seems that if I don't enable firewall rules so that nodes can see each other over the public network, the calico pods don't get up correctly.

It seems that, somehow, BIRD or Calico, use this public address to communicate the nodes with each other, and if the nodes are not seen by the public network, the calico pods cannot be created.

## Your Environment
* Calico version: 3.22.1
* Kubernetes version: 1.23.5
* Operating System and version: Debian 10

**Comment by lwr20** [comment]
Do you need BGP to work in this cluster?  If not, you might try https://projectcalico.docs.tigera.io/manifests/calico-vxlan.yaml

**Comment by lwr20** [comment]
If you look in the calico-node logs, one of the earliest logs should output the config that Calico thinks it has.  Can you check that the IP_AUTODETECTION_METHOD is correct in that config log?

**Comment by csbertran** [comment]
> If you look in the calico-node logs, one of the earliest logs should output the config that Calico thinks it has. Can you check that the IP_AUTODETECTION_METHOD is correct in that config log?

Hii! I tried with vxlan mode and same errors.
I send you the exact error I'm getting during the creation of calico-nodes:

```
root@prok8sm01:~# kubectl logs calico-node-7h4vh -n kube-system
2022-04-06 09:18:31.741 [INFO][11] startup/startup.go 425: Early log level set to info
2022-04-06 09:18:31.741 [INFO][11] startup/utils.go 127: Using NODENAME environment for node name prok8sw01
2022-04-06 09:18:31.742 [INFO][11] startup/utils.go 139: Determined node name: prok8sw01
2022-04-06 09:18:31.742 [INFO][11] startup/startup.go 94: Starting node prok8sw01 with version v3.22.1
2022-04-06 09:18:31.744 [INFO][11] startup/startup.go 430: Checking datastore connection
2022-04-06 09:19:01.745 [INFO][11] startup/startup.go 445: Hit error connecting to datastore - retry error=Get "[https://10.96.0.1:443/api/v1/nodes/foo":](https://10.96.0.1/api/v1/nodes/foo%22:) dial tcp 10.96.0.1:443: i/o timeout
2022-04-06 09:19:32.746 [INFO][11] startup/startup.go 445: Hit error connecting to datastore - retry error=Get "[https://10.96.0.1:443/api/v1/nodes/foo":](https://10.96.0.1/api/v1/nodes/foo%22:) dial tcp 10.96.0.1:443: i/o timeout
```
The error is when it tries to connect with datastore via kubernetes service. This is the config of the kubernetes services, as you can see, the endpoints are the public IP:
```
root@prok8sm01:~# kubectl describe svc
Name: kubernetes
Namespace: default
Labels: component=apiserver
provider=kubernetes
Annotations: <none>
Selector: <none>
Type: ClusterIP
IP Family Policy: SingleStack
IP Families: IPv4
IP: 10.96.0.1
IPs: 10.96.0.1
Port: https 443/TCP
TargetPort: 6443/TCP
Endpoints: <obfuscated_public_ip_master1>:6443,<obfuscated_public_ip_master2>:6443,<obfuscated_public_ip_master3>:6443
Session Affinity: None
Events: <none>
```
If I describe the calico-node pods, I can see that they get assigned an IP from the private net and the environ IP_AUTODETECTION_METHOD is correctly set.

The only solutions I come up with are:
- Open full visibility between all servers
- Is it possible to also add the private IP's of the master nodes as endpoint of the kubernetes service?

**Comment by lwr20** [comment]
So this error from calico-node: `dial tcp 10.96.0.1:443: i/o timeout` indicates that it can't talk to the kubernetes api service.  That service is set up by kube-proxy.  Has kube-proxy on that node started correctly and create the NAT rule that converts 10.96.0.1 to the IP of one of the control plane nodes?

**Comment by zzmg** [comment]
@csbertran  hello did you solve this problem？I met the same issue

**Comment by caseydavenport** [comment]
> Is it possible to also add the private IP's of the master nodes as endpoint of the kubernetes service?

I believe it is possible to do this via configuration passed to the kube-apiserver.

Fundamentally though, all of your nodes need access to the apiserver via the service endpoint, so ensuring that the service endpoint has properly routable IP addresses present is a must.
