### ISSUE TITLE
Move upgrade out of AWS reference

### ISSUE THREAD

**Issue by caseydavenport** [projectcalico/calico#582]
The upgrading section of this doc should not be there: http://docs.projectcalico.org/v2.1/reference/public-cloud/aws

It should be moved to the feature (in this case, cross-subnet IPIP) documentation.

**Comment by robbrockbank** [comment]
actually i think there are a number of changes required:
-  the feature content needs to be removed from the AWS and put in it's own feature documentation (AWS would ref this)
-  the upgrade section needs to be it's own guide ... but the documentation about setting up ip autodetection should probably also be it's own guide.
