### ISSUE TITLE
Pods can't be killed normally after Node restart

### ISSUE THREAD

**Issue by vitaliy-leschenko** [projectcalico/calico#5828]
**Describe the bug**
Command `kubectl delete pods/%podname%` stucks on deleting pods.
When I try to describe the pods, I see the message:
```
Events:
  Type     Reason          Age               From               Message
  ----     ------          ----              ----               -------
  Normal   Scheduled       17m               default-scheduler  Successfully assigned default/demo-85d57c4449-f5wgk to k8s-windows-2
  Normal   Pulling         17m               kubelet            Pulling image "mcr.microsoft.com/windows/nanoserver:ltsc2022"
  Normal   Pulled          15m               kubelet            Successfully pulled image "mcr.microsoft.com/windows/nanoserver:ltsc2022" in 1m30.8318989s
  Normal   Created         15m               kubelet            Created container demo-server
  Normal   Started         15m               kubelet            Started container demo-server
  Normal   SandboxChanged  3m36s             kubelet            Pod sandbox changed, it will be killed and re-created.
  Normal   Pulled          3m32s             kubelet            Container image "mcr.microsoft.com/windows/nanoserver:ltsc2022" already present on machine
  Normal   Created         3m32s             kubelet            Created container demo-server
  Normal   Started         3m30s             kubelet            Started container demo-server
  Normal   Killing         68s               kubelet            Stopping container demo-server
  Warning  FailedKillPod   3s (x8 over 68s)  kubelet            error killing pod: failed to "KillPodSandbox" for "4723efd3-cb10-4c0c-8b45-c8f7ab981155" with KillPodSandboxError: "rpc error: code = Unknown desc = failed to remove network namespace for sandbox \"d8be8cd9b8acfb344ddd598358e8464fc9580121c576af2410235594d4210d89\": hcnDeleteNamespace failed in Win32: The specified request is unsupported. (0x803b0015) {\"Success\":false,\"Error\":\"The specified request is unsupported. \",\"ErrorCode\":2151350293}"
```

**To Reproduce**
1. Deploy new k8s cluster with CRI contaierD and CNI Calico
2. Deploy any pod on windows node
3. Restart windows node
4. Try to delete the pod on windows node

**Expected behavior**
Pods delete without any events.

**Kubernetes (please complete the following information):**
 - Windows Server version: 2022
 - Kubernetes Version: 1.22.2
 - CNI: Calico
 - CRI: containerD 1.6.0

[linked sig-windows-tools issue #184](https://github.com/kubernetes-sigs/sig-windows-tools/issues/184)

**Comment by vitaliy-leschenko** [comment]
After node restart all windows pods lose their IP addresses.

**Comment by lmm** [comment]
Thanks for reporting this @vitaliy-leschenko. Looking at the linked sig-windows issue, I wonder if we need to enforce a service dependency order on the Calico services and try to have those run before kubelet.

**Comment by inklit** [comment]
I have the same issue. have you been able to mitigate the problem?

**Comment by inklit** [comment]
Small update, this problem can be mitigated by setting kubelet and kube-proxy as delayed-start, so that calico will always start before it.

**Comment by vitaliy-leschenko** [comment]
@inklit I tried to startup `kube*` services after CalicoNode is ready. It solve the issue on my on-premise clusters.
