### ISSUE TITLE
calico datastore migrate problem

### ISSUE THREAD

**Issue by Icarus9913** [projectcalico/calico#5837]
Env:
```shell
Client Version:    v3.16.10
Git commit:        cd75341d
Cluster Version:   v3.16.10
Cluster Type:      k8s,bgp
```

Guide: https://projectcalico.docs.tigera.io/archive/v3.16/maintenance/datastore-migration

Description:
Migrate calico database from etcdv3 to kubernetes. I followed the official doc guide but got issue like :
```shell
[root@]# calicoctl datastore migrate import -f etcd-data
Invalid datastore type: etcdv3 to import to for datastore migration. Datastore type must be kubernetes
```
1. I locked the datastore
2. export with exec 'calicoctl datastore migrate export > etcd-data'
3. set up the k8s datastore env with 'export DATASTORE_TYPE=kubernetes'.
4. import but get bad response. And I noticed '/etc/calico/calicoctl.cfg' shows 'datastoreType: etcdv3'

**Comment by Icarus9913** [comment]
I checked the source code, the error means that 'calicoctl.cfg' config file should be set into k8s? 
Is there any mechanism help us change it? Or in another words, the step 3 I set the env but not work good?

**Comment by lwr20** [comment]
Maybe try:
```
DATASTORE_TYPE=kubernetes calicoctl datastore migrate import -f etcd-data
```

**Comment by lwr20** [comment]
The other option is to edit `calicoctl.cfg` as step 3.  i.e. set `datastoreType: kubernetes` in `/etc/calico/calicoctl.cfg`
