### ISSUE TITLE
Improve BGP (& RR) Documentation

### ISSUE THREAD

**Issue by robbrockbank** [projectcalico/calico#584]
Issues:

- [ ]  how does calico use BGP
- [ ] peering with your border router
- [ ] using a route reflectors
- [ ] configuring Calico BGP config using calicoctl.

**Comment by kprabhak** [comment]
Reckon we ought to provide docs for running the calico/routereflector as a container (something like https://github.com/projectcalico/calicoctl/issues/1113#issuecomment-295890857 ) in addition to a Bird route reflector on a dedicated host instance.

**Comment by kprabhak** [comment]
Also, we should update docs for RHEL to just point directly to the bird/bird6 rpms instead of adding an epel repo.

**Comment by caseydavenport** [comment]
This should all be addressed in Calico v3.3 with the work @neiljerram has been doing.
