### ISSUE TITLE
Calico BGP use iptables or  IPVS ?    How can I choose ？

### ISSUE THREAD

**Issue by liuchaowhu** [projectcalico/calico#5849]
My K8S cluster is calico BGP, there are iptables and ipvs modes to choose from, how can I test their performance, can anyone provide a method?

**Comment by lwr20** [comment]
> there are iptables and ipvs modes to choose from
Minor point, but _kube-proxy_ supports these modes, not Calico.  

> how can I test their performance, can anyone provide a method?
Well it all depends what you're trying to test?

Performance dimensions you might want to test include: 
- throughput
- latency

For latency, this blog post may be of interest: https://www.tigera.io/blog/comparing-kube-proxy-modes-iptables-or-ipvs/.  For that blog we tested using `vegeta`, but you could use any web load testing framework that reports latency.

For throughput, you might be interested in this blog post: https://medium.com/itnext/benchmark-results-of-kubernetes-network-plugins-cni-over-10gbit-s-network-updated-august-2020-6e1b757b9e49
https://github.com/InfraBuilder/k8s-bench-suite

**Comment by lwr20** [comment]
You didn't ask about this, but for completeness, I'd like to note that Calico supports other _dataplanes_ too - iptables, ebpf and vpp. 

This blog post compares calico iptables to calico ebpf: https://www.tigera.io/blog/introducing-the-calico-ebpf-dataplane/

And this compares iptables to vpp: https://www.tigera.io/blog/lightning-fast-kubernetes-networking-with-calico-vpp/
