### ISSUE TITLE
host-networked pods cannot access clusterIP services in clusters running on cgroups v2 defaults

### ISSUE THREAD

**Issue by ffilippopoulos** [projectcalico/calico#5852]
We have a self managed Kubernetes cluster running on gcp and we recently deployed calico v3.22.1 on bpf mode with wireguard enabled. We noticed an odd behaviour, where host-networked pods are not able to access kube services (times out), while pods with a cluster IP assigned can access services fine. Moreover, all direct pod to pod communication seems feasible, regardless of network interface used by the pods.
This is already identified by calico and is related to using private cgroup isolation after migrating to cgroups v2, slack discussion: https://calicousers.slack.com/archives/C0BCA117T/p1649247958021389
Related Kubernetes GH issue: https://github.com/kubernetes/kubernetes/issues/103363

## Expected Behavior
Should be able to access clusterIP service addresses from host-networked pods.

## Current Behavior
Access from host-networked pods to clusterIP services times out

## Possible Workaround

Switch back to cgroupv1 or use docker "host" cgroups namespace instead of "private" (

## Your Environment

* Calico version: v3.22.1 
* Orchestrator version (e.g. kubernetes, mesos, rkt): Kubernetes v1.22.5
* Operating System and version: Flatcar Container Linux by Kinvolk 3033.2.4 (Oklo), kernel: 5.10.107-flatcar

**Comment by xabinapal** [comment]
I'm having a similar problem, but I'm not sure if issue is related. I have an EKS cluster with Calico in eBPF mode (but in my scenario, without Wireguard).

Until now, host-networked pods could access ClusterIP services without no problems. We were using a beta version of Calico, `v3.21.0-0.dev-89-g14e7d23e3101`. I've just upgraded to `v3.22.0` (no changes to any node operating system or `cgroups` configuration) and the timeouts started to happen. Rollback to the previous version, and everything works again as expected.

I'm going to perform some tests in a dev environment to check how the suggested workaround behaves in both versions, but maybe this helps to debug the issue.

**Comment by mazdakn** [comment]
@xabinapal this issue should show itself if something, like `cgroups` version, beside Calico in nodes changes. If Calico upgrade is the only variable in your environment, it's probably something else. I would suggest to open another issue, and add the details of your cluster so we can analyse it.

**Comment by xabinapal** [comment]
Thanks for the suggestion @mazdakn. I've been testing my issue and found that this has stopped working after I updated to 3.22 but after updating all pods to latest 3.23 beta version (`release-v3.23` tag in every image), it has started to work again. Should I create an issue anyway, as it's not an stable version?

**Comment by mazdakn** [comment]
@xabinapal I am not sure if you already created a GH issue yet, but this one should be similar to what you are experiencing:
https://github.com/projectcalico/calico/issues/5957 . If you feel it's the same thing, please add your setup information to that.
