### ISSUE TITLE
coredns i/o timeout when trying to resolve external domains

### ISSUE THREAD

**Issue by joey100** [projectcalico/calico#5855]
calico version: v3.22.0
kubernetes version: 1.22.2
Use kubeadm to install kubernetes in AWS EC2, with security group and nacl inside/outside rules all open to 0.0.0.0/0.

kubernetes pods try to resolve external domains but get "can't resolve xxx" error, coredns log shows i/o timeout.
kubernetes pods can communicate with each services inside the kubernetes cluster.
Run a docker container in the kubernetes node, using default docker0 bridge network, can resolve external domains.
kubernetes node can resolve external domains.

## Expected Behavior
kubernetes pods can resolve external domains without error if the kubernetes nodes can resolve external domains.

## Current Behavior
1. kubernetes pods try to resolve external domains but get "can't resolve xxx" error, coredns shows i/o timeout. The pods uses coredns service ip as the nameserver, the coredns pod uses the kubernetes node dns config to get the nameserver, but finally the resolution is timeout.
pods -- > coredns pod -- > node dns config -- > node nameserver -- > timeout.
2. But if the pods don't use node dns nameserver, instead use like 8.8.8.8 as the nameserver, the pods can resolve external domains. 
3. kubernetes pods can communicate with each services inside the kubernetes cluster.
4. Run a docker container in the kubernetes node, using default docker0 bridge network, can resolve external domains. 
docker container -- > docker0 -- > node dns config -- > node nameserver --> works.
5. kubernetes node can resolve external domains using its default dns configuration.

## Steps to Reproduce (for bugs)
1. create AWS EC2, with sg and nacl all open to 0.0.0.0/0
2. use kubeadm to install kubernetes cluster
3. install calico: 
curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | sudo bash
helm repo add projectcalico https://projectcalico.docs.tigera.io/charts
helm install calico projectcalico/tigera-operator --version v3.22.0
4. test dns resolution:
kubectl run curl-test --image=radial/busyboxplus:curl -i --tty --rm
$nslookup baidu.com
$nslookup baidu.com "node-nameserver"
$nslookup baidu.com 8.8.8.8

## Context
This issue impacts HIGH!

1. coredns error log:

```
[INFO] 172.31.128.203:44185 - 10955 "AAAA IN httpserver.svc.cluster.local. udp 46 false 512" NXDOMAIN qr,aa,rd 139 0.000062327s
[INFO] 172.31.128.203:44185 - 59317 "AAAA IN httpserver.cluster.local. udp 42 false 512" NXDOMAIN qr,aa,rd 135 0.000056139s
[INFO] 172.31.128.236:40570 - 2 "PTR IN 10.0.96.10.in-addr.arpa. udp 41 false 512" NOERROR qr,aa,rd 116 0.002475463s
[INFO] 172.31.128.203:44185 - 50020 "AAAA IN httpserver.ap-southeast-1.compute.internal. udp 60 false 512" NOERROR - 0 2.00082523s
[ERROR] plugin/errors: 2 httpserver.ap-southeast-1.compute.internal. AAAA: read udp 172.31.128.234:51264->172.31.0.2:53: i/o timeout
[INFO] 172.31.128.236:46864 - 3 "AAAA IN baidu.com. udp 27 false 512" NOERROR - 0 2.001410723s
[ERROR] plugin/errors: 2 baidu.com. AAAA: read udp 172.31.128.234:49738->172.31.0.2:53: i/o timeout
[INFO] 172.31.128.236:49431 - 4 "AAAA IN baidu.com.default.svc.cluster.local. udp 53 false 512" NXDOMAIN qr,aa,rd 146 0.000208201s
[INFO] 172.31.128.236:48382 - 5 "AAAA IN baidu.com.svc.cluster.local. udp 45 false 512" NXDOMAIN qr,aa,rd 138 0.000154973s
[INFO] 172.31.128.236:57282 - 6 "AAAA IN baidu.com.cluster.local. udp 41 false 512" NXDOMAIN qr,aa,rd 134 0.000150974s
[INFO] 172.31.128.203:44185 - 50020 "AAAA IN httpserver.ap-southeast-1.compute.internal. udp 60 false 512" NOERROR - 0 2.00071224s
[ERROR] plugin/errors: 2 httpserver.ap-southeast-1.compute.internal. AAAA: read udp 172.31.128.234:35267->172.31.0.2:53: i/o timeout
[INFO] 172.31.128.236:47112 - 7 "A IN baidu.com. udp 27 false 512" NOERROR - 0 2.00110745s
[ERROR] plugin/errors: 2 baidu.com. A: read udp 172.31.128.234:45351->172.31.0.2:53: i/o timeout
[INFO] 172.31.128.236:42355 - 8 "A IN baidu.com.default.svc.cluster.local. udp 53 false 512" NXDOMAIN qr,aa,rd 146 0.000218318s
[INFO] 172.31.128.236:39396 - 9 "A IN baidu.com.svc.cluster.local. udp 45 false 512" NXDOMAIN qr,aa,rd 138 0.000184862s
[INFO] 172.31.128.236:37103 - 10 "A IN baidu.com.cluster.local. udp 41 false 512" NXDOMAIN qr,aa,rd 134 0.000125729s
[INFO] 172.31.128.203:44185 - 50020 "AAAA IN httpserver.ap-southeast-1.compute.internal. udp 60 false 512" NOERROR - 0 2.001197674s
[ERROR] plugin/errors: 2 httpserver.ap-southeast-1.compute.internal. AAAA: read udp 172.31.128.234:40759->172.31.0.2:53: i/o timeout
[INFO] 172.31.128.203:44185 - 50020 "AAAA IN httpserver.ap-southeast-1.compute.internal. udp 60 false 512" NOERROR - 0 2.0011854s
```

2. node route:
ubuntu@ip-172-31-12-21:~$ route -n
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
0.0.0.0         172.31.0.1      0.0.0.0         UG    100    0        0 eth0
172.17.0.0      0.0.0.0         255.255.0.0     U     0      0        0 docker0
172.31.0.0      0.0.0.0         255.255.240.0   U     0      0        0 eth0
172.31.0.1      0.0.0.0         255.255.255.255 UH    100    0        0 eth0
172.31.128.192  0.0.0.0         255.255.255.192 U     0      0        0 *
172.31.128.195  0.0.0.0         255.255.255.255 UH    0      0        0 cali2fe3c8f1779
172.31.128.196  0.0.0.0         255.255.255.255 UH    0      0        0 cali63b6fa08c42
172.31.128.197  0.0.0.0         255.255.255.255 UH    0      0        0 cali926fbfa8d7a
172.31.128.201  0.0.0.0         255.255.255.255 UH    0      0        0 calif4edfcf1c05
172.31.128.202  0.0.0.0         255.255.255.255 UH    0      0        0 cali99d62c2e2b8
172.31.128.203  0.0.0.0         255.255.255.255 UH    0      0        0 cali086bcc7bc4c
172.31.128.205  0.0.0.0         255.255.255.255 UH    0      0        0 cali7c41c623fc3
172.31.128.207  0.0.0.0         255.255.255.255 UH    0      0        0 cali6824057f06e
172.31.128.208  0.0.0.0         255.255.255.255 UH    0      0        0 cali1c91169ad84
172.31.128.210  0.0.0.0         255.255.255.255 UH    0      0        0 calid6138c660eb
172.31.128.211  0.0.0.0         255.255.255.255 UH    0      0        0 cali3e848fced8b
172.31.128.213  0.0.0.0         255.255.255.255 UH    0      0        0 cali76dcc1efb81
172.31.128.214  0.0.0.0         255.255.255.255 UH    0      0        0 cali3de9f68d0e6
172.31.128.215  0.0.0.0         255.255.255.255 UH    0      0        0 cali3dfb8c5c0c1
172.31.128.216  0.0.0.0         255.255.255.255 UH    0      0        0 cali9294a9914ea
172.31.128.217  0.0.0.0         255.255.255.255 UH    0      0        0 cali3acbb817c63
172.31.128.218  0.0.0.0         255.255.255.255 UH    0      0        0 calia0104fab6ae
172.31.128.219  0.0.0.0         255.255.255.255 UH    0      0        0 cali61a9554ce92
172.31.128.228  0.0.0.0         255.255.255.255 UH    0      0        0 calif9db393c59c
172.31.128.234  0.0.0.0         255.255.255.255 UH    0      0        0 cali3adad0dd86c
172.31.128.236  0.0.0.0         255.255.255.255 UH    0      0        0 calib31f8768006

3. node dns config:
Link 2 (eth0)
      Current Scopes: DNS
DefaultRoute setting: yes
       LLMNR setting: yes
MulticastDNS setting: no
  DNSOverTLS setting: no
      DNSSEC setting: no
    DNSSEC supported: no
  Current DNS Server: 172.31.0.2
         DNS Servers: 172.31.0.2
          DNS Domain: ap-southeast-1.compute.internal

## Your Environment

* Calico version v3.22.0
* Orchestrator version (e.g. kubernetes, mesos, rkt): kubernetes 1.22.2, containerd as the cri
* Operating System and version: ubuntu 20.04
* Link to your project (optional):

**Comment by lmm** [comment]
Hi @joey100 , sorry for the delay. It seems like this issue is related to DNS rather than Calico. I found this issue that looks related: https://github.com/coredns/coredns/issues/3982

**Comment by joey100** [comment]
Hi @lmm thanks for your help! Actually my kubelet and coredns config are the same with the solution from link you shared. This means my env has been already the same with the solution, but only if I change my node's dns to use external dns resolver like 8.8.8.8 then the pods can resolve external domains successfully.
But one more thing is: after I change the dns config back to original(don't introduce external resolver) for the node, the restart the node, the pods can resolve external domains now! Strange! I will watch the situation for some days and update you again. Thanks.

**Comment by caseydavenport** [comment]
Any update on this? I agree with @lmm that this sounds more like a node config issue than a Calico issue.

**Comment by danpe** [comment]
> Hi @lmm thanks for your help! Actually my kubelet and coredns config are the same with the solution from the link you shared. The solution is to change kubelet config and coredns forward address. This means my env has been already the same with the solution, but only if I change my node's dns to use external dns resolver like 8.8.8.8 then the pods can resolve external domains successfully. But one more thing is: after I change the dns config back to original(don't introduce external resolver) for the node, then restart the node, the pods can resolve external domains now! Strange! I will watch the situation for some days and update you again. Thanks.

What is the "original"? I'm still getting it with Kubernetes 1.28.8 and Calico

**Comment by investlab** [comment]
This issue seems to be caused by failing to resolve DNS. However, after checking various configurations and restarting, it still didn't work. Finally, it was discovered that the forwarding rule configuration was the problem. Just execute the following command:
```
iptables -P INPUT ACCEPT
iptables -P FORWARD ACCEPT
iptables -P OUTPUT ACCEPT
iptables -F
```

**Comment by maze88** [comment]
Partially related, for specific cases:
I had similar errors in my CoreDNS logs too, when running with KinD.
What solved it for me was to pre-create its Docker network (`docker network create kind`).
