### ISSUE TITLE
Vagrant "verify environment" should be automated / moved into the Vagrantfile

### ISSUE THREAD

**Issue by ozdanborne** [projectcalico/calico#586]
http://docs.projectcalico.org/v2.0/getting-started/kubernetes/installation/vagrant#14-verify-environment

This entire "verify environment section" could be done directly in the Vagrantfile, allowing us to error the provisioning if those addresses aren't working.

**Comment by tmjd** [comment]
@ozdanborne What were you thinking for this?
All configuration for a host is done before configuring the next host.  Meaning if I add a section that applied to the master (it is always first), even as a separate `(1..num_instances).each do |i|` it will be done before the nodes are brought up.

I think what could be done is:
- Each node could check docker ps.
- A section that is only applied to the last VM brought up could do the ping checks against the other hosts and curl the etcd version

How does that sound?

**Comment by ozdanborne** [comment]
True, I didn't consider that environment verification can only happen in the order hosts are brought up.

We could pretty easily implement a subset of these checks (master can curl its own etcd, each node can ping master), but any checks beyond that would be much more complicated.

I'm fine with keeping the complexity out of the Vagrantfiles and keeping just those few small instructions for the user to run through.
