### ISSUE TITLE
Allow setting resource limits to tigera-operator via Helm Chart

### ISSUE THREAD

**Issue by michelzanini** [projectcalico/calico#5877]
Hi,

I see the Helm chart tigera-operator at the moment does not support customisation of Kubernetes resource limits.
The Kubernetes Deployment has a pod with no limits set (cpu and memory). 

Is it possible to support this via Helm chart values.yaml?

There's a decent helm chart here https://artifacthub.io/packages/helm/stevehipwell/tigera-operator
that supports most of this settings, but it's not the official chart, which we would prefer to use.

Thanks.

**Comment by caseydavenport** [comment]
Yeah, should be easy to add this for the operator itself, and definitely should do so.

**Comment by sriramy** [comment]
I would like to contribute this simple addition to operator helm chart.
