### ISSUE TITLE
Pod to pod connectivity in between nodes (microk8s)

### ISSUE THREAD

**Issue by maximehyh** [projectcalico/calico#5884]
Hello, 

I am trying to build a k8s cluster of two nodes using microk8s where a MQTT broker is located on one node (exposing a service for a TCP connection on port 1883) and another pod on another node that is supposed to connect to this broker. Everything is working fine when the 2 pods are on the same node but I cannot manage to make the TCP connection when the 2 pods are on 2 different nodes (see screenshots below).

After a few back and forth I realized that the issue was the pod connectivity in between nodes. For example if I `shell exec` inside pod-74b4db7697-4znf5 (on node reamtlrnd03 - 10.99.111.103)  I can: 
- PING the host (10.99.111.103)
- PING the other node (10.99.111.104)
- PING another pod on the same node

```bash
container-registry             registry-5f697bb7df-s76r4                                ●             1/1                                  1 Running              10.1.72.74                 reamtlrnd04              37m
kube-system                    calico-kube-controllers-7959b65c6-4c8jc                  ●             1/1                                  1 Running              10.1.72.76                 reamtlrnd04              18m                 
kube-system                    calico-node-qnlcg                                        ●             1/1                                  1 Running              10.99.111.103              reamtlrnd03              18m                 
kube-system                    calico-node-x2kwn                                        ●             1/1                                  1 Running              10.99.111.104              reamtlrnd04              18m                 
kube-system                    coredns-64c6478b6c-swqmx                                 ●             1/1                                  0 Running              10.1.72.78                 reamtlrnd04              6m36s               
kube-system                    hostpath-provisioner-7764447d7c-p6tn4                    ●             1/1                                  2 Running              10.1.72.77                 reamtlrnd04              37m                 
production                     pod-controller-68fcbbfff-qxsdc                           ●             1/1                                  1 Running              10.1.72.75                 reamtlrnd04              26m                 
production                     pod-74b4db7697-4znf5                                     ●             1/1                                  1 Running              10.1.78.197                reamtlrnd03              26m  
```

So the issue is that one pod on one node cannot connect to a pod on another node. 

I started fiving in Calico's documentation and I tried to run `calicoctl node status`, which gives me: 
```bash
Calico process is running.

The BGP backend process (BIRD) is not running.   
```

So there is indeed an issue. According to the doc I checked that I could make TCP connection on port 179 using `iperf` and configured `NetworkManager` but the BGP backend process is still not running. 

I also tried to specify the network interface using `IP_AUTODETECTION_METHOD=eno1`. But still no luck. 

I also disabled the firewall but something is still wrong. Would you mind checking up the logs of `calicoctl node diags` for my two nodes? 

Thanks. 

[diag-03.tar.gz](https://github.com/projectcalico/calico/files/8460810/diag-03.tar.gz)
[diag-04.tar.gz](https://github.com/projectcalico/calico/files/8460811/diag-04.tar.gz)

**Comment by maximehyh** [comment]
The issue was actually coming from some microk8s misconfiguration on my side. Closing.

**Comment by nc-kab** [comment]
> The issue was actually coming from some microk8s misconfiguration on my side. Closing.

@maximehyh I seem to have the exact same problem. What was your solution?

**Comment by maximehyh** [comment]
@nc-kab some things that were unrelated to Calico, see https://github.com/canonical/microk8s/issues/3043

I basically had to purge my installation and rename my hosts to some proper Linux hostnames .

**Comment by nc-kab** [comment]
> 

That's interesting.
What is a "proper" linux hostname?
I think my hostnames complies with this https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#dns-subdomain-names
My nodes are called k8s-master-1, k8s-node-1, k8s-node-2 etc.
