### ISSUE TITLE
Configure cni_network_config 'tuning' parameters

### ISSUE THREAD

**Issue by amith-basavaraj** [projectcalico/calico#5886]
Hi Team,

I need to configure some sysctl parameters. Can someone provide information on how to configure cni_network_config sysctl 'tuning' parameters from tigera operator?

**Comment by caseydavenport** [comment]
This isn't currently possible, but I think is on our backlog to implement. We need a way to expose more CNI config options via the operator.

**Comment by amith-basavaraj** [comment]
> This isn't currently possible, but I think is on our backlog to implement. We need a way to expose more CNI config options via the operator.

Thanks Casey for the prompt reply. Would like to know by when can we expect this enhancement? This would help us plan our activity.

**Comment by caseydavenport** [comment]
The earliest it will be is Calico v3.24, which is targeted for sometime next quarter - likely 2-3 months out.

**Comment by diranged** [comment]
@caseydavenport Any update on the progress here?
