### ISSUE TITLE
AdminNetworkPolicy support

### ISSUE THREAD

**Issue by caseydavenport** [projectcalico/calico#5891]
## Expected Behavior

Implement the upstream Kubernetes AdminNetworkPolicy API.

## Context

Currently, this is a pre-alpha API that is being implemented as a CRD. This issue is to track the status of Calico's implementation of the new API as is progresses through to GA.  

Enhancement link: https://github.com/kubernetes/enhancements/issues/2091

**Comment by remram44** [comment]
I believe this was fixed by #9206
