### ISSUE TITLE
Policy doc does not list pass as an action

### ISSUE THREAD

**Issue by tmjd** [projectcalico/calico#590]
Pass is an allowed action so the reference should list it.
http://docs.projectcalico.org/master/reference/calicoctl/resources/policy

Side topic: I think pass is too similar to allow and should be renamed.

**Comment by djosborne** [comment]
https://github.com/projectcalico/libcalico-go/pull/234 added the pass action.

Looks like this was in libcalico-go:
```
$ git tag --contains e5a0c16a3f1ccf72ef91ec6407930cb8d3b793f4
v1.0.0
v1.0.0-beta
v1.0.0-beta-rc1
v1.0.0-beta-rc2
v1.0.0-beta-rc3
v1.0.0-beta.1
v1.0.0-rc1
v1.0.0-rc2
v1.0.0-rc3
v1.0.0-rc4
v1.0.0-rc5
v1.0.0-rc6
v1.0.1
v1.0.2
v1.0.3
v1.1.0
v1.1.0-rc1
v1.1.1
v1.1.2
v1.1.3
```

So should be backported to v2.0 and v2.1
