### ISSUE TITLE
Kubernetes master doesnt get external ip of my new node

### ISSUE THREAD

**Issue by Pseudow** [projectcalico/calico#5911]
Hi, Ive recently added a new node in my cluster. The problem is that my vps where the node is has a different internal and external ip. The internal ip is used to acces from outside to my node and the internal is used by the vps itself.

The problem is that when kubeadm join the cluster it sends the internal ip not the external ip, which makes it wrong. Ive tried to change it my modifying --node-ip flag like this:

```
KUBELET_EXTRA_ARGS=--cgroup-driver=cgroupfs --network-plugin=cni --register-node=true --node-ip=MY_EXTERNAL_IP
```

But the problem is that it still dont work
![image](https://user-images.githubusercontent.com/64150196/163419330-dfe369c6-2af9-4a4f-b674-a4c06169ab33.png)

When I look at the logs generated by my calico-node pod it says:
```
Error from server: no preferred addresses found; known addresses: []
```

My external ip is also a cloud one

**Comment by Pseudow** [comment]
My external ip is a cloud one

**Comment by caseydavenport** [comment]
This doesn't sound like a Calico issue - Calico isn't involved in the selection of Kubernetes node IPs.

Why do you want to use the external IP for your node? Calico wants to use the internal IP. What address autodetection mode are you using? 

Kubernetes nodes can have both internal and external IPs set, might want to do that.

**Comment by Pseudow** [comment]
Actually I my kubeadm doesn’t detect any ip so I passed one through the node-ip flag but still don’t work

**Comment by lwr20** [comment]
> Actually I my kubeadm doesn’t detect any ip so I passed one through the node-ip flag but still don’t work
I think perhaps you'll get better assistance from the kubeadm folks?  https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md
