### ISSUE TITLE
Calicoctl pod goes to Error state during graceful node shutdown

### ISSUE THREAD

**Issue by amshankaran** [projectcalico/calico#5925]
During graceful node shutdown calicoctl pod moves to Error state and throws the code 137 instead of gracefully Terminating 
## Expected Behavior
This pod should be gracefully terminated or shutdown during Node shutdown like other pods.

## Current Behavior
Calicoctl pod is moving to Error State with exit code 137.

## Steps to Reproduce (for bugs)

1.Kubeadm Flags configured for Graceful shutdown:
 shutdownGracePeriod:30s, shutdownGracePeriodCriticalPods:10s, --terminated-pod-gc-threshold: 1
2.Shutdown the worker node gracefully (with systemctl poweroff) 
3. Verify the calicoctl pod status in that worker. 

## Context
Graceful node shutdown feature should not see any pods in Error state during graceful shutdown of the node.

## Your Environment

* Calico version
calicoctl version
Client Version:    v3.19.3
Git commit:        6f3d4900
Cluster Version:   v3.19.2-dirty
Cluster Type:      k8s,bgp,kubeadm

* Orchestrator version (e.g. kubernetes, mesos, rkt):
[calicoctl_describe.txt](https://github.com/projectcalico/calico/files/8505492/calicoctl_describe.txt)
director-0-stack1:~> kubectl version
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.3", GitCommit:"a9dda44d3f9da886364993e5cbb0f2afbbeae113", GitTreeState:"clean", BuildDate:"2022-02-10T11:38:28Z", GoVersion:"go1.17.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.3", GitCommit:"a9dda44d3f9da886364993e5cbb0f2afbbeae113", GitTreeState:"clean", BuildDate:"2022-02-10T11:27:59Z", GoVersion:"go1.17.6", Compiler:"gc", Platform:"linux/amd64"}

* Operating System and version:
director-0-stack:~> cat /etc/os-release
NAME="SLES"
VERSION="15-SP3"
VERSION_ID="15.3"
PRETTY_NAME="SUSE Linux Enterprise Server 15 SP3"
ID="sles"
ID_LIKE="suse"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:suse:sles:15:sp3"
DOCUMENTATION_URL="https://documentation.suse.com/"

* Link to your project (optional):

**Comment by caseydavenport** [comment]
My personal recommendation is to not run calicoctl as a pod to start with.

If that's not possible, could you share the log output from the errored container so we can see what might be happening?

**Comment by amshankaran** [comment]
Hi @caseydavenport,
We are using deployment for calicoctl. Node is going for graceful shutdown at that time calicoctl moving to Error state and getting cleaned up. There were no logs.   let me see whether I'm able to get any logs by increasing the verbosity.

**Comment by caseydavenport** [comment]
Any more information on this one?
