### ISSUE TITLE
EXTERNAL-IP - pending with MetalLB

### ISSUE THREAD

**Issue by usonline** [projectcalico/calico#5926]
HI All,
Please help me
I have a issue with metalLB

kubectl logs controller-d8df99687-4b6kr -n metallb-system
```
{"branch":"HEAD","caller":"main.go:142","commit":"v0.9.6","msg":"MetalLB controller starting version 0.9.6 (commit v0.9.6, branch HEAD)","ts":"2022-04-12T11:28:01.194086312Z","version":"0.9.6"}
I0412 11:28:31.287320       1 trace.go:205] Trace[1298498081]: "Reflector ListAndWatch" name:pkg/mod/k8s.io/client-go@v0.20.2/tools/cache/reflector.go:167 (12-Apr-2022 11:28:01.286) (total time: 30000ms):
Trace[1298498081]: [30.00071723s] [30.00071723s] END

E0412 11:28:31.287359       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.20.2/tools/cache/reflector.go:167: Failed to watch *v1.ConfigMap: failed to list *v1.ConfigMap: Get https://10.96.0.1:443/api/v1/namespaces/metallb-system/configmaps?fieldSelector=metadata.name%3Dconfig&limit=500&resourceVersion=0: dial tcp 10.96.0.1:443: i/o timeout
I0412 11:28:31.287675       1 trace.go:205] Trace[1427131847]: "Reflector ListAndWatch" name:pkg/mod/k8s.io/client-go@v0.20.2/tools/cache/reflector.go:167 (12-Apr-2022 11:28:01.286) (total time: 30001ms):
Trace[1427131847]: [30.001145161s] [30.001145161s] END

```
 kubectl logs coredns-64897985d-c5kq4 -n kube-system

```
.:53
[INFO] plugin/reload: Running configuration MD5 = db32ca3650231d74073ff4cf814959a7
CoreDNS-1.8.6
linux/amd64, go1.17.1, 13a9191
[ERROR] plugin/errors: 2 795246720698795630.7423457134295768889. HINFO: read udp 192.168.167.196:42978->192.168.0.8:53: i/o timeout
[ERROR] plugin/errors: 2 795246720698795630.7423457134295768889. HINFO: read udp 192.168.167.196:52764->192.168.0.8:53: i/o timeout
[ERROR] plugin/errors: 2 795246720698795630.7423457134295768889. HINFO: read udp 192.168.167.196:41918->192.168.0.8:53: i/o ### timeout
```

kubectl get svc -A

```

NAMESPACE     NAME            TYPE                     CLUSTER-IP         EXTERNAL-IP      PORT(S)                                 AGE
default              kubernetes   ClusterIP                10.96.0.1              <none>              443/TCP                                6d6h
default              nginx            LoadBalancer         10.110.165.104    <pending>        80:30149/TCP                        11h
kube-system    kube-dns       ClusterIP                10.96.0.10           <none>              53/UDP,53/TCP,9153/TCP     6d6h
```

**Comment by tomastigera** [comment]
What is the setup? Are you using eBPF?

**Comment by usonline** [comment]
I'm using red hat 8.5 os and firewalld and selinux disabled

**Comment by usonline** [comment]
To the best of my knowledge this seems to me to be a calico network issue
Because this setup works without any problems on ubunt server
My server configuration
red hat 8.5 os and firewalld / selinux disabled


https://projectcalico.docs.tigera.io/getting-started/kubernetes/requirements
https://projectcalico.docs.tigera.io/getting-started/kubernetes/requirements#kernel-dependencies

plz refer this url's and advice to me
my kernel version is 4.18

**Comment by caseydavenport** [comment]
Nothing here so far is suggesting this is a Calico issue, and still waiting on a response to @tomastigera's question - are you using eBPF mode or iptables mode for your Calico data plane?

We need more information about the way you installed your cluster and the steps you took to reproduce this. Please fill out the issue template when raising issues so that we can help you better.

>  dial tcp 10.96.0.1:443: i/o timeout

MetalLB is having trouble talking to the API server. This is likely one of a few things:

- Security groups or firewall rules are not properly configured to allow pod traffic.
- Not running Calico on your control plane nodes, so routing doesn't work to control plane nodes from pods.
- Something wrong with your host networking (out of Calico's control)
- Something wrong with kube-proxy (out of Calico's control)

**Comment by usonline** [comment]
Hi Caseydavenport,

I'm using iptables but we disabled firewalld

[root@k8-m ~]# kubectl get pods --all-namespaces
NAMESPACE        NAME                                       READY   STATUS    RESTARTS     AGE
kube-system      calico-kube-controllers-56fcbf9d6b-654sl   1/1     Running   1 (9d ago)   10d
kube-system      calico-node-5r5hb                          1/1     Running   1 (9d ago)   10d
kube-system      calico-node-lvckq                          1/1     Running   1 (9d ago)   10d
kube-system      coredns-64897985d-k9rr9                    1/1     Running   1 (9d ago)   10d
kube-system      coredns-64897985d-wxlrz                    1/1     Running   1 (9d ago)   10d
kube-system      etcd-k8-m                                  1/1     Running   1 (9d ago)   10d
kube-system      kube-apiserver-k8-m                        1/1     Running   1 (9d ago)   10d
kube-system      kube-controller-manager-k8-m               1/1     Running   1 (9d ago)   10d
kube-system      kube-proxy-n64bh                           1/1     Running   1 (9d ago)   10d
kube-system      kube-proxy-qphdq                           1/1     Running   1 (9d ago)   10d
kube-system      kube-scheduler-k8-m                        1/1     Running   1 (9d ago)   10d
metallb-system   controller-d8df99687-vz4k6                 1/1     Running   1 (9d ago)   10d
metallb-system   speaker-9nwsh                              1/1     Running   1 (9d ago)   10d
metallb-system   speaker-f6prw                              1/1     Running   1 (9d ago)   10d

**Comment by caseydavenport** [comment]
> MetalLB is having trouble talking to the API server. This is likely one of a few things:
> - Security groups or firewall rules are not properly configured to allow pod traffic.
> - Not running Calico on your control plane nodes, so routing doesn't work to control plane nodes from pods.
> - Something wrong with your host networking (out of Calico's control)
> - Something wrong with kube-proxy (out of Calico's control)

I'd recommend going through each of these suggestions from my previous post and making sure they are behaving properly. 

You found the links for networking requirements, which is a good start - make sure your SG / firewall rules are configured according to the documentation. 

You may need to do some packet tracing to see where packets are getting lost and why they are not making it to the API server. The tools I'd recommend for that are:

- ping (to generate traffic)
- traceroute (see the hops being taken)
- `ip route show` - to view route tables
- `iptables-save` - to view iptables
