### ISSUE TITLE
slow increase in bird cpu usage

### ISSUE THREAD

**Issue by fungusakafungus** [projectcalico/calico#5942]
On nodes with high container turnover (pods started or restarted often) cpu usage of bird rises slowly over weeks until it reaches the pod cpu limit.

## Expected Behavior
Bird CPU usage should stay below limit.

## Current Behavior
birdcl commands like `show protocol` take longer and longer, e.g. over a minute after 4 weeks:
```
# time crictl ps | grep Running.*calico-node | awk '{print $1}' | xargs -I{} crictl exec {} birdcl -s /var/run/calico/bird.ctl show protocol
BIRD v0.3.3+birdv1.6.8 ready.
name     proto    table    state  since       info
static1  Static   master   up     2022-03-21
kernel1  Kernel   master   up     2022-03-21
device1  Device   master   up     2022-03-21
direct1  Direct   master   up     2022-03-21
Mesh_10_<snip>_40 BGP      master   up     2022-03-21  Established
Mesh_10_<snip>_36 BGP      master   up     2022-03-21  Established
Mesh_10_<snip>_37 BGP      master   up     2022-03-21  Established
Mesh_10_<snip>_13 BGP      master   up     2022-03-21  Established
Mesh_10_<snip>_14 BGP      master   up     2022-03-21  Established
Mesh_10_<snip>_15 BGP      master   up     2022-03-21  Established
Mesh_10_<snip>_16 BGP      master   up     2022-03-21  Established
Mesh_10_<snip>_17 BGP      master   up     2022-03-21  Established
Mesh_10_<snip>_18 BGP      master   up     2022-03-21  Established
Mesh_10_<snip>_41 BGP      master   up     2022-03-21  Established
Mesh_10_<snip>_10 BGP      master   up     2022-03-21  Established
Mesh_10_<snip>_11 BGP      master   up     2022-03-21  Established
Mesh_10_<snip>_19 BGP      master   up     2022-03-21  Established
Mesh_10_<snip>_28 BGP      master   up     2022-04-19  Established
Mesh_10_<snip>_30 BGP      master   up     2022-03-21  Established
Mesh_10_<snip>_31 BGP      master   up     2022-03-21  Established
Mesh_10_<snip>_32 BGP      master   up     2022-03-21  Established
Mesh_10_<snip>_33 BGP      master   up     2022-03-21  Established
Mesh_10_<snip>_34 BGP      master   up     2022-04-06  Established
Mesh_10_<snip>_35 BGP      master   up     2022-03-21  Established
Mesh_10_<snip>_39 BGP      master   up     2022-04-19  Established
Mesh_10_<snip>_20 BGP      master   up     2022-03-21  Established
Mesh_10_<snip>_21 BGP      master   up     2022-03-21  Established
Mesh_10_<snip>_22 BGP      master   up     2022-04-13  Established
Mesh_10_<snip>_23 BGP      master   up     2022-04-19  Established
Mesh_10_<snip>_24 BGP      master   up     2022-03-21  Established
Mesh_10_<snip>_25 BGP      master   up     2022-03-30  Established
Mesh_10_<snip>_26 BGP      master   up     2022-03-21  Established
Mesh_10_<snip>_27 BGP      master   up     2022-03-21  Established

real  1m7.332s
user  0m0.107s
sys 0m0.051s
```

bird's internal network interface list (`birdcl dump interfaces`) increases in size with each created and removed pod:
(here I send a `dump interfaces` command to a running bird in a calico pod, then, looking at bird/calico logs, enumerate the list of interfaces between "Known network interfaces" and "Router ID" lines, see https://github.com/CZ-NIC/bird/blob/v1.6.8/nest/iface.c#L107-L110 and find out that bird still knows about ~29k interfaces that used to exist on this node)
```
# crictl ps | grep Running.*calico-node | awk '{print $1}' | xargs -I{} crictl exec {} birdcl -s /var/run/calico/bird.ctl dump interfaces
# crictl ps | grep Running.*calico-node | awk '{print $1}' | xargs -I{} crictl logs --tail 100000 {} | awk '/Known network interfaces/{s=0}/^Known network interfaces/,/^Router ID/{printf("%s ",s+=1); print}'|tail
28934 IF0: caliad4e7a218ef SHUTDOWN DOWN TDOWN MTU=0
28935 IF0: calic130efce236 SHUTDOWN DOWN TDOWN MTU=0
28936 IF0: cali5efc20f8e03 SHUTDOWN DOWN TDOWN MTU=0
28937 IF30894: cali4c6cc625ed0 DOWN LINK-UP MA BC MC MTU=1500
28938 IF0: cali4e5547e6b9c SHUTDOWN DOWN TDOWN MTU=0
28939 IF0: caliea58d1255ca SHUTDOWN DOWN TDOWN MTU=0
28940 IF0: cali7230d5921dd SHUTDOWN DOWN TDOWN MTU=0
28941 IF0: califf08dc52090 SHUTDOWN DOWN TDOWN MTU=0
28942 IF0: cali64fb00dd057 SHUTDOWN DOWN TDOWN MTU=0
28943 Router ID: 0a0c841d
```
currently, there are only 79 network interfaces:
```
# ip -o l | wc -l
79
```

bird cpu usage increases over time:
![image](https://user-images.githubusercontent.com/159878/164227325-d550398f-f157-478f-aa80-c951e1d075f6.png)

## Possible Solution
From my inexperienced look at [iface.c](https://github.com/CZ-NIC/bird/blob/v1.6.8/nest/iface.c) there doesn't seem to be any code to remove interfaces from `iface_list`. Also, I didn't investigate, why and when this list is used by bird/calico. I just rely on correlation which I think is strong.

Maybe a periodic restart/some kind of reload would make bird forget the interfaces of yore.

## Steps to Reproduce (for bugs)

I could reproduce the bug by creating/deleting 20k dummy interfaces named `caliz...` repeatedly, in batches of 100, waiting 10 sec between creation and deletion, so bird picks them up.
1. create/delete interfaces
   ```
   for j in {0..199}; do for i in {1..100}; do DEV=caliz$(printf %010i $(($j*100 + $i))); ip l add $DEV type dummy up; done; sleep 10; for i in {1..100}; do DEV=caliz$(printf %010i $(($j*100 + $i))); ip l delete $DEV; done ; sleep 5; done
   ```
2. measure the size of `dump interfaces`, it will be more than 20k:
    ```
    # crictl ps | grep Running.*calico-node | awk '{print $1}' | xargs -I{} crictl exec {} birdcl -s /var/run/calico/bird.ctl dump interfaces
    # crictl ps | grep Running.*calico-node | awk '{print $1}' | xargs -I{} crictl logs --tail 30000 {} | awk '/Known network interfaces/{s=0}/^Known network interfaces/,/^Router ID/{printf("%s ",s+=1); print}'|tail
3. Inspect the calico/bird cpu usage

## Context

bird6 experiences the same pattern of elevated cpu usage, even when we have `FELIX_IPV6SUPPORT: False`.

The z in caliz is not related to current russian military symbolics and is only there for greppability. I condemn the invasion of Ukraine.

## Your Environment
<!--- Include as many relevant details about the environment you experienced the bug in -->
* Calico version: v3.20.3 and v3.19.3
* Orchestrator version (e.g. kubernetes, mesos, rkt): k8s 1.22 and 1.21
* Operating System and version: ubuntu focal
Mostly default config as in kubespray, calico_pool_blocksize: 26, calico_advertise_cluster_ips: false, some nodes peer with routers and set `keepOriginalNextHop: true`

**Comment by fungusakafungus** [comment]
> Otherwise, this sounds like it might be a bug in BIRD itself not recognizing when an interface is removed, and will need some more digging into the BIRD code.

I think it does recognize the interface being removed, it sets a flag on it, but it doesn't remove it from the list: 
https://github.com/CZ-NIC/bird/blob/v1.6.8/nest/iface.c#L275-L276

All the deleted interfaces I see in `dump interfaces` have the flag SHUTDOWN.

probably because it's still 1998 in some parts of this file and network interfaces are rather stable.

**Comment by fungusakafungus** [comment]
> I wonder if a periodic config reload would be enough - if you make some trivial change to your BGP configuration (e.g., changing log level - this should send a signal to BIRD to reload its configuration) do you see the number of interfaces go back down?

kubespray configures most of the things via env vars, so not so easy to cause a config reload, but I had a look at https://github.com/projectcalico/calico/blob/79b442a53adb7d7f1fd62927d9322daf87dce9de/confd/etc/calico/confd/conf.d/bird.toml#L10 and tried `sv hup bird` -- that did not reduce the number of interfaces in `dump interfaces `

**Comment by florianbeer** [comment]
https://github.com/projectcalico/bird/issues/95 
I think we have the same issue, I commented over in the bird project.

**Comment by caseydavenport** [comment]
I believe this has been fixed? A few PRs went into BIRD in this area: https://github.com/projectcalico/bird/pull/104 and https://github.com/projectcalico/bird/pull/111
