### ISSUE TITLE
v3.22 release manifests do not contain CRDs anymore

### ISSUE THREAD

**Issue by itspngu** [projectcalico/calico#5950]
## Expected Behavior

We're installing Calico from the documented URLs (https://docs.projectcalico.org/vX.Y/manifests/calico.yaml) using FluxCD. We've upgraded from v3.21 to v3.22 20 days ago. Everything works :)

## Current Behavior

This morning I woke up to calico-kube-controllers crashlooping due to a missing CRD. On investigation, it appeared that the release manifests for 3.22 have been changed to not include *any* CRDs anymore. I'm assuming this change is not intended.

## Possible Solution

Based on the timeline, I suspect the breaking change was introduced with #5946 

## Steps to Reproduce (for bugs)

```
curl -sL https://docs.projectcalico.org/v3.21/manifests/calico.yaml | grep "kind: CustomResourceDefinition"
kind: CustomResourceDefinition
kind: CustomResourceDefinition
kind: CustomResourceDefinition
kind: CustomResourceDefinition
kind: CustomResourceDefinition
kind: CustomResourceDefinition
kind: CustomResourceDefinition
kind: CustomResourceDefinition
kind: CustomResourceDefinition
kind: CustomResourceDefinition
kind: CustomResourceDefinition
kind: CustomResourceDefinition
kind: CustomResourceDefinition
kind: CustomResourceDefinition
kind: CustomResourceDefinition
kind: CustomResourceDefinition
kind: CustomResourceDefinition

curl -sL https://docs.projectcalico.org/v3.22/manifests/calico.yaml | grep "kind: CustomResourceDefinition"
```

## Context

Sufficient context has been provided above.

## Your Environment

* Calico version v3.22
* Orchestrator version (e.g. kubernetes, mesos, rkt): v1.23.5
* Operating System and version: n/a
* Link to your project (optional):

**Comment by itspngu** [comment]
> @itspngu We think we've fixed this now. If you feel like having another go, it would be great if you can confirm or deny.

The curl output looks fine now:

```
$ curl -sL https://docs.projectcalico.org/v3.22/manifests/calico.yaml | grep "kind: CustomResourceDefinition" | wc -l
17

$ curl -sL https://docs.projectcalico.org/v3.21/manifests/calico.yaml | grep "kind: CustomResourceDefinition" | wc -l
17
```
I'm a little hesitant to touch anything related to calico right now, as I had to spend 2 hours identifying the issue and repairing our staging environment while devs were complaining :D (the downgrade to 3.21 was not trivial, I had to drain and replace all nodes as well as the control plane, but didn't think of grabbing logs at the time). I think it's safe to assume that the problem is fixed though.

Slightly offtopic, but do you provide "immutable" copies of the manifests somewhere? Getting them from the repo is not really an option because they seem to be generated in CI, and getting them from the release artifacts does not work in our specific case (usage of FluxCD) because Kustomize dropped support for tarballs as a source a while ago.

**Comment by neiljerram** [comment]
Thanks for looking, and apologies.  I'll let @caseydavenport answer the follow-up manifest question, as he understands the factors involved much better than me.

**Comment by itspngu** [comment]
No worries, mistakes happen everywhere, all the time. Thanks for the hard work. Just taking the chance to rethink our own deployment strategy.

**Comment by caseydavenport** [comment]
Very sorry for this one, completely on me. I'll see how we can ensure this type of mistake doesn't happen in the future.

> getting them from the release artifacts does not work in our specific case (usage of FluxCD) because Kustomize dropped support for tarballs as a source a while ago.

right now, the only place is within the release artifacts. If you need them immutable, we generally recommend that you snapshot the manifests and keep your own copies (e.g., pull them from the release tar and keep them in your own config management system). 

There is an open issue though here tracking this: https://github.com/projectcalico/calico/issues/2587

I would like to stop auto-generating the manifests, so that you can pull the manifests straight from the repo at the release commit ID and get an immutable copy. It's on my backlog.
