### ISSUE TITLE
exec format error in calico-node on ARM64 with v3.20.5

### ISSUE THREAD

**Issue by hakman** [projectcalico/calico#5963]
Calico v3.20.5 fails to start on ARM64 instances. Logs show to be related to calico-node/upgrade-ipam:
```
==== START logs for container upgrade-ipam of pod kube-system/calico-node-8npqq ====
standard_init_linux.go:228: exec user process caused: exec format error
```

## Expected Behavior
Start normally, as it used to work with v3.20.3, before upgrading (see: https://github.com/kubernetes/kops/pull/13518).

## Current Behavior

kOps daily conformance tests for ARM64 started failing since upgrading Calico to v3.20.5.
https://testgrid.k8s.io/kops-conformance#kops-aws-conformance-arm64-1-22

The AMD64 tests are still working as expected, so there may be a build issue limited to ARM64.

## Possible Solution

n/a

## Steps to Reproduce (for bugs)

1. Start calico-node on an ARM64 instance2. 
2. Check logs

## Your Environment
* Calico version: v3.20.5
* Orchestrator version (e.g. kubernetes, mesos, rkt): kOps
* Operating System and version: Ubuntu 20.04
* Link to your project (optional):

**Comment by lwr20** [comment]
Pinging @caseydavenport

**Comment by frozenprocess** [comment]
Seems like the multiarch manifest was not pushed into the repo.
https://hub.docker.com/layers/node/calico/node/v3.20.5/images/sha256-d9bebf02363b1721153a149ab873790c09e945f34b3393115b114c26030c5b4e?context=explore

**Comment by hakman** [comment]
@frozenprocess Yep, pretty much the instead of the multiarch manifest we have the same image as for AMD64.
The good news is that the individual images are there and the manifest can be manually generated.

**Comment by caseydavenport** [comment]
Yep, there was a bug in our release logic on v3.20. I just pushed a new calico/node manifest that should resolve this.

**Comment by hakman** [comment]
Thanks @caseydavenport. I can confirm that tests are now green again:
https://testgrid.k8s.io/kops-conformance#kops-aws-conformance-arm64-1-22
