### ISSUE TITLE
why the route table about IPv6 are incorrect?

### ISSUE THREAD

**Issue by pengbinbin1** [projectcalico/calico#5971]
I have a k8s cluster with 3 servers,every server has dual stack IP, node1 (192.168.188.3,2001:bb2::3)  node2 (192.168.188.4,2001:bb2::4)  node3(192.168.**166**.18,2001:**aa2**::4).  I login the node1,and curl the pod which are located on the node3 by the pod's IPv6 IP,after a period it return timeout.,but IPv4 will be ok. I check the route table on node1. why the nexthop to node3 are not the node3's IPv6 IP? it is the gateway's IPv6 IP. I have tcpdump the packet about bgp, and in the UPDATE packet,the nexthop address is node3's IPv6 IP ,but why it has been changed when i check the route table on node1?  

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Calico version
* Orchestrator version (e.g. kubernetes, mesos, rkt):
* Operating System and version:
* Link to your project (optional):

**Comment by caseydavenport** [comment]
@pengbinbin1 You'll need to provide a bit more information - for example, what your network looks like and what the routing table on your node looks like.

One guess is that the node doesn't believe that Node 3 is directly connected, so it resolves the route as having a next hop of the gateway.

**Comment by ghostloda** [comment]
@caseydavenport I have similar issue at [issues/6609](https://github.com/projectcalico/calico/issues/6609#issuecomment-1226719815) .IPv4 will be ok,but IPv6 get unreachabled.
