### ISSUE TITLE
Remove PodSecurityPolicies, replace with pod security standards.

### ISSUE THREAD

**Issue by caseydavenport** [projectcalico/calico#5972]
Breaking out the PSP from https://github.com/projectcalico/calico/issues/4570. 

We should remove these - they will start to fail in k8s v1.25, when they are planned to be removed. 

## Expected Behavior

Remove deprecated PSP API, update operator so it conditionally programs them based on k8s version.

## Current Behavior

We always program PSPs. 

## Possible Solution

- Remove from manifests
- Conditionally program in the operator.

**Comment by sftim** [comment]
PSP removal from Kubernetes was https://github.com/kubernetes/kubernetes/pull/109798
