### ISSUE TITLE
wrong link in documentation ?

### ISSUE THREAD

**Issue by parmentelat** [projectcalico/calico#6007]
## Expected Behavior

I'm trying to install kubectl-calico on a linux running intel x86_64

from the instructions here
https://projectcalico.docs.tigera.io/maintenance/clis/calicoctl/install#install-calicoctl-as-a-binary-on-a-single-host
Clicking on the 'Linux tab' as shown above gave me a link to the wrong architecture
![image](https://user-images.githubusercontent.com/4519227/166455930-5afefbcd-065c-4110-8a6b-be39cf05f92f.png)

## Current Behavior

for the record the correct link should read `calicoctl-linux-amd64` 

## Steps to Reproduce (for bugs)

It appears the bug is not always in the wat, and sometimes after changing tabs a couple times I do get the right link

## Your Environment

* Calico version
* Orchestrator version (e.g. kubernetes, mesos, rkt):
* Operating System and version:
* Link to your project (optional):

using latest chrome on a macOS

**Comment by coutinhop** [comment]
Thanks for pointing that out @parmentelat! This seems to have been fixed in master by this commit: https://github.com/projectcalico/calico/commit/27193295bc5c87c123d0b43be3e4a2f1368e23bc
I'll look into fixing that for v3.22.2 (and other releases)...

**Comment by caseydavenport** [comment]
Cherry picked it here: https://github.com/projectcalico/calico/pull/6050
