### ISSUE TITLE
Calico eBPF arm64 support

### ISSUE THREAD

**Issue by TrevorTaoARM** [projectcalico/calico#6022]
I saw a description for eBPF support in the official document:
https://projectcalico.docs.tigera.io/maintenance/ebpf/enabling-bpf
that says:
"eBPF mode only supports x86-64. (The eBPF programs are not currently built for the other platforms.)"

But I checked the calico-node pod on arm64 server with the command:
calico-node -bpf
It just shows the help msg for bpf support.

So I would like to ask if the eBPF is actually supported on the arm64 platform or not, and if we want to enable the support on arm64 platform, what should we do/add to enable the building for ebpf arm64 support from source.

**Comment by tomastigera** [comment]
Afaik eBPF works on arm64, it is included in the arm64 images. @frozenprocess probably knows better.

**Comment by frozenprocess** [comment]
You should be able to enable Calico eBPF dataplane on arm64 architecture.
**Note:** Please make sure you are using the latest release of Calico since ARM64 support was added to Calico from version 3.21.4+ 

There is also this tutorial that shows step by step how to enable eBPF dataplane on a cluster with an arm64 node. 
https://github.com/frozenprocess/Tigera-Presentations/tree/master/2021-10-15.Utah.Meetup.Multiarch.clusters.networking

**Comment by TrevorTaoARM** [comment]
@frozenprocess For e2e test, is there any guide on how to do the e2e test with eBPF-enabled setting?
I think the current e2e test is just for iptables( kube-proxy ) case for Calico.

**Comment by tomastigera** [comment]
e2e work for bpf too, the key is to set `DATAPLANE=“CalicoBPF”` and `PRODUCT="calico"`

**Comment by caseydavenport** [comment]
> e2e work for bpf too, the key is to set DATAPLANE=“CalicoBPF” and PRODUCT="calico"

These are args for our internal e2e tooling, which aren't currently public @tomastigera :grin: 

However, it should be fine to run the upstream Kubernetes e2e tests against a Calico cluster with eBPF configured as the data plane.

**Comment by lwr20** [comment]
> However, it should be fine to run the upstream Kubernetes e2e tests against a Calico cluster with eBPF configured as the data plane right?
Yes, absolutely.  Or run something like [Sonobuoy](https://github.com/vmware-tanzu/sonobuoy) or [cyclonus](https://github.com/mattfenwick/cyclonus)

**Comment by frozenprocess** [comment]
Closing this one since Calico eBPF supports arm64. https://docs.tigera.io/calico/latest/operations/ebpf/enabling-ebpf
