### ISSUE TITLE
Helm-chart deployed calico does not match calicoctl version

### ISSUE THREAD

**Issue by EugenMayer** [projectcalico/calico#6027]
I deployed calico to k8s via the helm chart, version `v3.22.2`

When i now install calicoctl on my device, it has the client version `3.22.2`. Running the tool against the cluster brings up this odd message

```
calicoctl get ippopl
Failed to get resources: Version mismatch.
Client Version:   3.22.2
Cluster Version:  v3.22.2
Use --allow-version-mismatch to override.
```

So basically `3.22.2` is not `v3.22.2`

Using https://aur.archlinux.org/packages/calicoctl on my client device.

**Comment by caseydavenport** [comment]
I believe that is a problem with the third-party arch packaging of calicoctl, which recompiled calicoctl with the wrong version metadata attached. We've seen this one before with other distributions of calicoctl that aren't owned by the Calico team.

When I run the binary that the Calico team published (https://github.com/projectcalico/calico/releases/tag/v3.22.2), I get the correct results:

```
Client Version:    v3.22.2
Git commit:        14cf6d6ea
```

**Comment by EugenMayer** [comment]
Thank you, I will write the maintainer and try to fix that. Thank you a lot for the clarification

**Comment by caseydavenport** [comment]
We could also make our checking a bit more flexible - accept either 3.22.2 or v3.22.2. Seems pretty harmless to me, and allows other package managers to do their thing and stick to their own version conventions.

**Comment by EugenMayer** [comment]
Well maybe use sem-ver could help. Most implementations allow prefixing v

https://jubianchi.github.io/semver-check/#/1.0.0/v1.0.0

The specs though speak of that as 'not right but common' https://semver.org/#is-v123-a-semantic-version.

So you might just strip the leading v and compare using semver?

**Comment by caseydavenport** [comment]
Yep, I think a fine enough fix would be to stip the `v` from both versions being compared and just look at the numerical digits.
