### ISSUE TITLE
Search bar could search preferentially for the requested version of docs

### ISSUE THREAD

**Issue by robbrockbank** [projectcalico/calico#604]
At the moment the search bar returns a list of searches across all versions.

Might be nice if the search selects the version tab associated with the version of help the user is currently looking at - so that the results are initially focussed on their current version.

**Comment by djosborne** [comment]
For example, if user is on `docs.projectcalico.org/v2.0`, search results would pop up for the `v2.0` filter.

**Comment by robbrockbank** [comment]
Yup - to at least have the v2.0 tab selected.  I think it's nice to be able to switch to a different version in the docs search too.

**Comment by caseydavenport** [comment]
I think this is fixed here: https://github.com/projectcalico/calico/pull/2354
