### ISSUE TITLE
cni/node Binaries on github are missing

### ISSUE THREAD

**Issue by nebulakid** [projectcalico/calico#6043]
`github.com/projectcalico/node` and `github.com/projectcalico/cni-plugin` does not include the same assets/tags as `github.com/projectcalico/calico`

Also the links in the release notes are therefore broken:
[v3.21 release notes](https://github.com/projectcalico/node/releases/tag/v3.21.5)
E.g. see: `calico/node` and `calico/cni` for `v.3.21.5`

## Expected Behavior
Would be nice if all binary versions are available as single download, instead through download of the large "Release archive" for each version.

**Comment by caseydavenport** [comment]
@nebulakid as of v3.21, all code and releases are now performed in the github.com/projectcalico/calico repository and the node / cni-plugin repos are deprecated as mentioned in the README: https://github.com/projectcalico/node/blob/master/README.md

All of the assets are available here: https://github.com/projectcalico/calico/releases/tag/v3.21.5
