### ISSUE TITLE
[Tigera Operator Helm Chart] can't evaluate field Release in type interface {}

### ISSUE THREAD

**Issue by nick-oconnor** [projectcalico/calico#6062]
Attempting to apply `v3.23.0` of the `tigera-operator` helm chart results in:
```
template: tigera-operator/templates/tigera-operator/01-imagepullsecret.yaml:9:23: executing "tigera-operator/templates/tigera-operator/01-imagepullsecret.yaml" at <.Release.Namespace>: can't evaluate field Release in type interface {}
```
## Expected Behavior

The `tigera-operator` chart applies cleanly.

## Current Behavior

Helm throws a templating error.

## Possible Solution

It appears that a templating bug was introduced by #5649. Adding a `$` before `.Releases.Namespace` may fix the templating error. See: https://github.com/technosophos/common-chart/issues/5#issuecomment-525116545

## Steps to Reproduce (for bugs)

1. Apply the chart while specifying a namespace.

## Context

I was attempting to upgrade an existing `v3.22.2` install to `v3.23.0` via Terraform `helm_release`. I `terraform destroyed` the previous version of the chart before attempting to install the new version. My Terraform resource for reference:
```
resource "helm_release" "tigera_operator" {
  repository   = "https://docs.projectcalico.org/charts"
  chart        = "tigera-operator"
  version      = "v3.23.0"
  name         = "calico" 
  namespace    = "kube-system"
  reset_values = true
  wait         = false
  max_history  = 1
  values = [
    <<EOF
imagePullSecrets:
  registry-creds: <redacted>
installation:
  controlPlaneReplicas: 1
EOF
  ]
}
```

## Your Environment

* Calico version: v3.22.2
* Orchestrator version (e.g. kubernetes, mesos, rkt): Vanilla k8s v1.22.9
* Operating System and version: Ubuntu 22.04 LTS
* Terraform version: v1.1.9
* Helm provider version: v2.5.1

**Comment by caseydavenport** [comment]
There was a bug in earlier versions of the helm chart that meant the `namespace` parameter of the chart was ignored (discussed in detail here: https://github.com/projectcalico/calico/issues/4812)

In v3.23, we addressed that bug, but it does have upgrade implications for users who installed an earlier version of the chart. They're called out in the release notes and described in more detail here: https://projectcalico.docs.tigera.io/maintenance/kubernetes-upgrade#upgrading-an-installation-that-was-installed-using-helm

Given all of that, a few things to check:

- You probably need to perform the steps in the linked doc manually prior to running terraform.
- `namespace    = "kube-system"` - I'd expect this to be `tigera-operator`, to match the location that the previous charts installed their resources.

I'll try to reproduce this myself, but best to double check the above as well.

**Comment by caseydavenport** [comment]
A fresh install following the docs here does work for me: https://projectcalico.docs.tigera.io/getting-started/kubernetes/helm

Obviously that's not using the terraform provider though, so might be different.

**Comment by nick-oconnor** [comment]
Thanks @caseydavenport. I've narrowed it down. It only occurs when setting `imagePullSecrets` in `values.yaml`.

**Comment by nick-oconnor** [comment]
`{{- $envAll := . }}` from [01-imagepullsecret.yaml](https://github.com/projectcalico/calico/blob/669518444870a9e1e8ae9e47db93eb5a828959bc/calico/_includes/charts/tigera-operator/templates/tigera-operator/#L1) looks suspicious.

**Comment by caseydavenport** [comment]
Believe this is the fix: https://github.com/projectcalico/calico/pull/6084

Can't access Release.Namespace from within the loop since the context is different.

**Comment by nick-oconnor** [comment]
That should work. I'm curious... looks like `$envAll` is being assigned the current env (i.e. `.`). Can you just use `$envAll.Release.Namespace`? [Here's an example I found.](https://github.com/openstack/openstack-helm/blob/6125f6e3b86131c3980aed8c9438b8419935bf74/neutron/templates/pod-rally-test.yaml#L27) Full disclosure I have no idea if that'll work here.

**Comment by nick-oconnor** [comment]
Here's an example of exactly that: https://github.com/airshipit/maas/blob/50b3d689058e4ecb4927e314124a4c2e5189bd0f/charts/maas/templates/deployment-maas-ingress.yaml#L90

**Comment by caseydavenport** [comment]
Yeah, I believe you're right that is probably why envAll was there in the first place. I don't think that particular detail makes a difference in terms of UX though.

**Comment by nick-oconnor** [comment]
Awesome! Thanks @caseydavenport for getting this fixed.

**Comment by caseydavenport** [comment]
Thanks for the report! Hopefully will have this in a patch release early next week.
