### ISSUE TITLE
Probable incorrect advice in tigera operator helm chart README

### ISSUE THREAD

**Issue by FernFerret** [projectcalico/calico#6098]
## Expected Behavior

Running the readme's advice should not cause other helm charts to be deleted in the `default` namespace.

## Current Behavior

[This line in the README.md](https://github.com/projectcalico/calico/blob/master/calico/_includes/charts/tigera-operator/README.md?plain=1#L71) advises users to (I added the `--dry-run` here to make sure someone doesn't run this):

```
kubectl delete secret -n default -l name=calico -l owner=helm --dry-run
```

## Possible Solution

The readme should say:

```
kubectl delete secret -n default -l name=calico,owner=helm
```

Without the comma, the last `-l` argument is used and all others are overwritten. This would delete any secrets in the `default` namespace with `owner=helm`, which would be any helm chart installed there.

## Steps to Reproduce (for bugs)

I can run:

```
$ kubectl get secret --all-namespaces -l name=calico,owner=helm | wc -l
       8
$ kubectl get secret --all-namespaces -l name=calico -l owner=helm | wc -l
     108
$ kubectl get secret --all-namespaces -l owner=helm -l name=calico | wc -l
       8
```

This shows that the additional `-l` arguments are being accepted, but not merged as shown with the `,`. It also shows that the comma successfully performs the desired `and` behavior.

## Context

I was just reviewing my own setup and changed the delete to a get (since I was following the upgrade advice). I was surprised to see that since I was in the wrong namespace (I'd forgotten the delete) that the get returned non-calico results.

## Your Environment

* Calico version
* Orchestrator version (e.g. kubernetes, mesos, rkt):
* Operating System and version:
* Link to your project (optional):

Calico Chart Version: `v3.23.0`

OS: `Ubuntu 20.04`

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.5", GitCommit:"c285e781331a3785a7f436042c65c5641ce8a9e9", GitTreeState:"clean", BuildDate:"2022-03-16T15:51:05Z", GoVersion:"go1.17.8", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.3", GitCommit:"816c97ab8cff8a1c72eccca1026f7820e93e0d25", GitTreeState:"clean", BuildDate:"2022-01-25T21:19:12Z", GoVersion:"go1.17.6", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by caseydavenport** [comment]
yikes yeah this is bad. PR incoming.

**Comment by caseydavenport** [comment]
PR here: https://github.com/projectcalico/calico/pull/6117
