### ISSUE TITLE
Calico Hit error connecting to datastore

### ISSUE THREAD

**Issue by ZEM-Z-h4** [projectcalico/calico#6115]
Kubernetes upgrade on a cluster is failing. The Calico Node Daemon Set is crashing on multiple worker nodes. 

Throws out following error on Calico Node during the crash:

{startup/startup.go 374: Hit error connecting to datastore - retry error=Get [https://192.168.0.1:443/api/v1/nodes/foo](https://192.168.0.1/api/v1/nodes/foo): dial tcp 192.168.0.1:443: i/o timeout\n","stream":"stdout","time"}

## Expected Behavior
I would expect the calico pods to be able to connect to the datastore.

## Current Behavior
Pods are crashing and the logs show an error connecting to the datastore.

## Steps to Reproduce (for bugs)

kubeadm init --control-plane-endpoint "IP:PORT" --upload-certs
kubeadm join (4 other nodes)
kubectl apply -f calico.yaml (official one from https://projectcalico.docs.tigera.io/manifests/calico.yaml)
Check status of pods (kubectl get pods -n kube-system)

## Context
Unable to upgrade my cluster environment.

## Your Environment

* Calico version: v3.14.0
* Orchestrator version (e.g. kubernetes, mesos, rkt): kubernetes 1.16.13
* Operating System and version: Ubuntu 20.04
* Link to your project (optional):

**Comment by caseydavenport** [comment]
> {startup/startup.go 374: Hit error connecting to datastore - retry error=Get [https://192.168.0.1:443/api/v1/nodes/foo](https://192.168.0.1/api/v1/nodes/foo): dial tcp 192.168.0.1:443: i/o timeout\n","stream":"stdout","time"}

Calico connects to the apiserver via kube-proxy. If this is failing, it likely means either:

- Calico is being given bogus configuration for the API server (unlikely, but possible)
- kube-proxy isn't functioning well
- There's a problem with node networking preventing Calico from accessing the API server

**Comment by caseydavenport** [comment]
> Calico version: v3.14.0


Calico v3.14 is _very_ old - if that's what you're using, you should upgrade to something more modern
