### ISSUE TITLE
install-calico-windows.ps1 elevating to terminating errors since 3.23 release

### ISSUE THREAD

**Issue by benjamin-baxter** [projectcalico/calico#6127]
Latest release breaks install-calico-windows.ps1 for systems using kube-system instead of calico-system
## Expected Behavior

When running install-calico-windows.ps1 the function GetCalicoNamespace will detect that calico-system is not in use and return kube-system.
## Current Behavior

When running install-calico-windows.ps1 the function GetCalicoNamespace causes a terminating error for the script and exits the powershell run.
## Possible Solution

I got around it by changing $ErrorActionPreference = "Stop" on line 362 of install-calico-windows.ps1 to silentlycontinue instead of stop.
## Steps to Reproduce (for bugs)
1.Run install-calico-windows.ps1 on a prepared windows node that is attempting to connect to a cluster that has calico-nodes running on kube-system.

## Context

Annoying change.
I am building a one click setup script for a window/linux hybrid cluster on a window 10 local.

I'm not including info dumps as I have narrowed the issue to a single line of code.

## Your Environment

*Multipass based microk8s on windows 10 host with windows 2019 server VM on hyper V using a secondary vNIC for the Vxlan
*Loosely based off of: https://microk8s.io/docs/add-a-windows-worker-node-to-microk8s
* Link to your project (optional): I'll add a open source copy of the project if i make this work reliably.

**Comment by caseydavenport** [comment]
CC @lmm

**Comment by lmm** [comment]
Thanks for the bug report, @benjamin-baxter. Sorry about that, yeah we changed the `ErrorActionPreference` in the script in v3.22. Maybe we've got a gap in our test matrix as it sounds like this doesn't work for Calico installs using `kube-system`

**Comment by benjamin-baxter** [comment]
> Thanks for the bug report, @benjamin-baxter. Sorry about that, yeah we changed the `ErrorActionPreference` in the script in v3.22. Maybe we've got a gap in our test matrix as it sounds like this doesn't work for Calico installs using `kube-system`

All good! Thanks for making a great product!
