### ISSUE TITLE
calico-kube-controller pod is restarting : : Unauthorized

### ISSUE THREAD

**Issue by cpsrujana** [projectcalico/calico#6128]
## Error
2022-05-19 13:33:46.822 [INFO][1] main.go 92: Loaded configuration from environment config=&config.Config{LogLevel:"info", WorkloadEndpointWorkers:1, ProfileWorkers:1, PolicyWorkers:1, NodeWorkers:1, Kubeconfig:"", DatastoreType:"kubernetes"}
W0519 13:33:46.828542       1 client_config.go:615] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
2022-05-19 13:33:46.831 [INFO][1] main.go 113: Ensuring Calico datastore is initialized
2022-05-19 13:33:46.856 [ERROR][1] client.go 261: Error getting cluster information config ClusterInformation="default" error=connection is unauthorized: Unauthorized
2022-05-19 13:33:46.856 [FATAL][1] main.go 118: Failed to initialize Calico datastore error=connection is unauthorized: Unauthorized

## Context
Kubernetes is installed with calico cni. All pods are up and running. System is kept idle for 7days.
We have observed that calico is restarting multiple time with the an error

[ERROR][1] client.go 261: Error getting cluster information config ClusterInformation="default" error=connection is unauthorized: Unauthorized
[FATAL][1] main.go 118: Failed to initialize Calico datastore error=connection is unauthorized: Unauthorized

## Environment
* Calico version: v3.19.2
* K8s Version: v1.21.5
* Operating System and version: Ubuntu

**Comment by caseydavenport** [comment]
> 2022-05-19 13:33:46.856 [ERROR][1] client.go 261: Error getting cluster information config ClusterInformation="default" error=connection is unauthorized: Unauthorized

I'd recommend checking your API server logs to see if they contain more information as to why the connection was deemed unauthorized.

**Comment by cpsrujana** [comment]
> > 2022-05-19 13:33:46.856 [ERROR][1] client.go 261: Error getting cluster information config ClusterInformation="default" error=connection is unauthorized: Unauthorized
> 
> I'd recommend checking your API server logs to see if they contain more information as to why the connection was deemed unauthorized.

Thanks a lot for the response. 
Below is the error in the apiserver log:

E0519 13:34:15.705018       1 claims.go:126] unexpected validation error: *errors.errorString
E0519 13:34:15.705174       1 authentication.go:63] "Unable to authenticate the request" err="[invalid bearer token, Token could not be validated.]"

Could you please provide me pointers, when this can happen. Cluster was in this state for sometime. Later calico-kube-controller pod went to up and running. 
What might have gone wrong during that time ?

**Comment by caseydavenport** [comment]
It's hard to say, Calico kube-controllers just uses the token provided to it by Kubernetes, so if we were using an invalid token it's probably because Kubernetes failed to update the token mounted into the pod or because the kubernetes client code failed to notice that the token was updated.

**Comment by cpsrujana** [comment]
> It's hard to say, Calico kube-controllers just uses the token provided to it by Kubernetes, so if we were using an invalid token it's probably because Kubernetes failed to update the token mounted into the pod or because the kubernetes client code failed to notice that the token was updated.

We have brought up this setup using kubespray and kept idle for few days. Suddenly, we observed that calico kube-controller pod is going down with this error and coming back to running after sometime.

**Comment by mgleung** [comment]
I think kubespray might provide its own version of the Calico manifests? Could you try reinstalling Calico (either the same version or a later one) with our manifests from https://projectcalico.docs.tigera.io/about/about-calico and see if that might change any instability?

**Comment by akshaysharama** [comment]
@mgleung @caseydavenport,

when the calico binary starts, it will initialize cluster information using calicoclient object.
that object will have the calico env variable and kubeconfig(if not present, it will use in cluster config). what is this in cluster config? where it is defined?

use that object, i could see it is creating by default cluster configuration
`clusterInfo, err := c.ClusterInformation().Get(ctx, globalClusterInfoName, options.GetOptions{})` with datastoreType as kubernetes.

`

if err != nil {
                        // Create the default config if it doesn't already exist.
                        if _, ok := err.(cerrors.ErrorResourceDoesNotExist); ok {
                                newClusterInfo := v3.NewClusterInformation()
                                newClusterInfo.Name = globalClusterInfoName
                                newClusterInfo.Spec.CalicoVersion = calicoVersion
                                newClusterInfo.Spec.ClusterType = clusterType
                                newClusterInfo.Spec.ClusterGUID = fmt.Sprintf("%s", hex.EncodeToString(uuid.NewV4().Bytes()))
                                datastoreReady := true
                                newClusterInfo.Spec.DatastoreReady = &datastoreReady
                                _, err = c.ClusterInformation().Create(ctx, newClusterInfo, options.SetOptions{})
                                if err != nil {
                                        if _, ok := err.(cerrors.ErrorResourceAlreadyExists); ok {
                                                log.Info("Failed to create global ClusterInformation; another node got there first.")
                                                time.Sleep(1 * time.Second)
                                                continue
                                        }
                                        log.WithError(err).WithField("ClusterInformation", newClusterInfo).Errorf("Error creating cluster information config")
                                        return err
                                }
                        } else {
                                log.WithError(err).WithField("ClusterInformation", globalClusterInfoName).Errorf("Error getting cluster information config")
                                return err
                        }
                        break
                }

`

**Comment by caseydavenport** [comment]
The key / certs / token used by kube-controllers are all injected into the container by the kubelet on the system, and then interpreted by the Kubernetes golang client when creating a connection. The go client automatically handles any rotation of those credentials once the projection into the container is updated.

**Comment by caseydavenport** [comment]
You should check the token within the pod to make sure that it's valid. We use in-cluster configuration as described here: https://github.com/kubernetes/client-go/tree/master/examples/in-cluster-client-configuration#authenticating-inside-the-cluster

Given the API server logs are complaining about the token, it might be worth verifying that the token mounted at `/var/run/secrets/kubernetes.io/serviceaccount` is actually valid, since that's the token the Calico code will use.

**Comment by song-jiang** [comment]
@cpsrujana Any updates?

**Comment by lmm** [comment]
I'm going to close this for now due to inactivity but please feel free to reopen this issue if you're still experiencing this issue and have diags to provide.

**Comment by cpsrujana** [comment]
@lmm, can you please reopen the issue? we are still debugging and facing the issue

**Comment by cpsrujana** [comment]
@caseydavenport,

Hi, i've tried checking the token validity from the path "
/var/lib/kubelet/pods/5cc9962f-818f-4ff1-9824-801963d15893/../token" 

path: where pods has mounted the /var/run/secrets/kubernetes.io/serviceaccount is mounted.

I could the see the token validity is for 1yr from the day it got created. Then, why token is invalid or unauthorized? Our deployment is running from past 48d and we are seeing 172 restarts.


`{
  "aud": [
    "https://kubernetes.default.svc.cluster.local"
  ],
  "exp": 1688132695,
  "iat": 1656596695,
  "iss": "https://kubernetes.default.svc.cluster.local",
  "kubernetes.io": {
    "namespace": "kube-system",
    "pod": {
      "name": "calico-kube-controllers-76758f8d4c-6l2dr",
      "uid": "5cc9962f-818f-4ff1-9824-801963d15893"
    },
    "serviceaccount": {
      "name": "calico-kube-controllers",
      "uid": "6d8ba93f-ceaf-47f3-a90b-02e7c1d55745"
    },
    "warnafter": 1656600302
  },
  "nbf": 1656596695,
  "sub": "system:serviceaccount:kube-system:calico-kube-controllers"
}`

**Comment by mathe-matician** [comment]
Env: EKS
K8s: v1.24
Calico: 3.25.1 via tigera-operator via terraform helm

## Background

I installed the helm chart successfully (all objects came up successfully) without terraform the other day just using `helm`. I then uninstalled Calico from the cluster and restarted all of my nodes. I'm now trying to reinstall it with terraform when I hit this error.

## Logs

@caseydavenport 
> You should check the token within the pod to make sure that it's valid.

I can't seem to check whether `serviceAccountName: calico-node` is valid since the calico-node pods continually crash. Do you have any suggestions on a path forward for this? The calico-nodes are the only objects that don't seem to start in the calico-system Namespace.

My calico-node pods throw a similar error in this issue:

```
2023-08-09 20:35:54.391 [WARNING][8] startup/startup.go 444: Connection to the datastore is unauthorized error=connection is unauthorized: Unauthorized
2023-08-09 20:35:54.391 [WARNING][8] startup/utils.go 48: Terminating
Calico node failed to start
```

This is the error log I get from the api-server:

```
time="2023-08-09T19:50:26Z" level=warning msg="access denied" client="127.0.0.1:44042" error="input token was not properly formatted: token is missing expected \"k8s-aws-v1.\" prefix" method=POST path=/authenticate
```
