### ISSUE TITLE
Calico.yaml file is not applying correctly: error

### ISSUE THREAD

**Issue by iqrazaf** [projectcalico/calico#6132]
Hi, I am configureing Multi-node Kubernetes Cluster on ubuntu in VirtualBox . While apply calico.yaml file. I got error while creating last pods. Error is attached. 
I am using this file:
```
curl https://docs.projectcalico.org/manifests/calico.yaml -O
```
uncomment " CALICO_IPV4POOL_CIDR" and its value as well (10.0.0.0/16)
while applying calico got **error:** 
--------------------------------
```
error:
configmap/calico-config unchanged
customresourcedefinition.apiextensions.k8s.io/bgpconfigurations.crd.projectcalico.org configured
customresourcedefinition.apiextensions.k8s.io/bgppeers.crd.projectcalico.org configured
customresourcedefinition.apiextensions.k8s.io/blockaffinities.crd.projectcalico.org configured
customresourcedefinition.apiextensions.k8s.io/caliconodestatuses.crd.projectcalico.org configured
customresourcedefinition.apiextensions.k8s.io/clusterinformations.crd.projectcalico.org configured
customresourcedefinition.apiextensions.k8s.io/felixconfigurations.crd.projectcalico.org configured
customresourcedefinition.apiextensions.k8s.io/globalnetworkpolicies.crd.projectcalico.org configured
customresourcedefinition.apiextensions.k8s.io/globalnetworksets.crd.projectcalico.org configured
customresourcedefinition.apiextensions.k8s.io/hostendpoints.crd.projectcalico.org configured
customresourcedefinition.apiextensions.k8s.io/ipamblocks.crd.projectcalico.org configured
customresourcedefinition.apiextensions.k8s.io/ipamconfigs.crd.projectcalico.org configured
customresourcedefinition.apiextensions.k8s.io/ipamhandles.crd.projectcalico.org configured
customresourcedefinition.apiextensions.k8s.io/ippools.crd.projectcalico.org configured
customresourcedefinition.apiextensions.k8s.io/ipreservations.crd.projectcalico.org configured
customresourcedefinition.apiextensions.k8s.io/kubecontrollersconfigurations.crd.projectcalico.org configured
customresourcedefinition.apiextensions.k8s.io/networkpolicies.crd.projectcalico.org configured
customresourcedefinition.apiextensions.k8s.io/networksets.crd.projectcalico.org configured
clusterrole.rbac.authorization.k8s.io/calico-kube-controllers unchanged
clusterrolebinding.rbac.authorization.k8s.io/calico-kube-controllers unchanged
clusterrole.rbac.authorization.k8s.io/calico-node unchanged
clusterrolebinding.rbac.authorization.k8s.io/calico-node unchanged
daemonset.apps/calico-node configured
serviceaccount/calico-node unchanged
deployment.apps/calico-kube-controllers unchanged
serviceaccount/calico-kube-controllers unchanged
error: resource mapping not found for name: "calico-kube-controllers" namespace: "kube-system" from "calico.yaml": no matches for kind "PodDisruptionBudget" in version "policy/v1"
ensure CRDs are installed first
```
-------------------------------------------------------------------------------------------
I already checked calico-kube-controllers and PodDisruptionBudget"  it exist in yaml file. 

![calico-yaml-error](https://user-images.githubusercontent.com/105370998/169610358-8d876e74-62c7-4a6d-8dec-f241006d734d.PNG)

**Comment by caseydavenport** [comment]
@iqrazaf what version of Kubenretes are you using? The PodDisruptionBudget v1 API was introduced in k8s v1.21 so requires that release at a minimum.

**Comment by caseydavenport** [comment]
Yep. You need to use v1.21 Kubernetes or later.

**Comment by lizhiqiangsjtu** [comment]
I have the same trouble. Finally, i find it is the appVersion info mistake in YAML file. I write the ’V1‘, which should be 'v1' in my project. Hope it is useful for you.

**Comment by iqrazaf** [comment]
Thank everyone. Problem solved. It was a version differences issue for Docker and Kubernetes

**Comment by sshveta** [comment]
@iqrazaf Can you please tell what solved the problem.

**Comment by iqrazaf** [comment]
> @sshveta: Can you please tell what solved the problem.
It was a version differences issue for Docker and Kubernetes

**Comment by securelyshare-venkatasai-thandra** [comment]
Can u tell exactly, i also got the same issue.

**Comment by iqrazaf** [comment]
> Can u tell exactly, i also got the same issue.

install latest version of Docker and Kubernetes and hold the Kubernetes version after installation. 

**Install Docker (All hosts)**
sudo apt-get install docker.io -y

**Update the package repository and Install K8S components (All hosts):**
sudo apt-get update
sudo apt-get install -y kubelet kubectl kubeadm
sudo apt-mark hold kubelet kubeadm kubectl
