### ISSUE TITLE
How can i change the image of calico-node ?

### ISSUE THREAD

**Issue by ruanshudong** [projectcalico/calico#6133]
Everytime i use:
kubectl edit DaemonSet -n calico-system
to change the image of calico-node, It will be restored again, it's seem that tigera-operator will restore this image ??

**Comment by caseydavenport** [comment]
The tigera-operator manages deployment of those resources - you shouldn't edit them by hand. As you discovered, they will be corrected. 

What is it you're trying to do? Why do you want to change the image?
