### ISSUE TITLE
Incorrect IPv4 detection

### ISSUE THREAD

**Issue by antoinep92** [projectcalico/calico#6141]
The main physical interface of my nodes gets a /31 ip v4 cidr from the cloud's dhcp. This seems to be confusing calico address detection. I have a cluster with 4 nodes, and calico consistently detects the correct address minus one. This in turn breaks VXLAN setup, and as a result I have no network between nodes.

Let's look at a node:
- `ip addr show eth0` gives `net 10.72.70.21/31 metric 1024 scope global dynamic eth0`
- `ip route show table local` gives `local 10.72.70.21 dev eth0 proto kernel scope host src 10.72.70.21`
- DNS A query for the node name gives `10.72.70.21`
- kubernetes correctly infers the IP: Node.status.addresses is
```
  - address: 10.72.70.21
    type: InternalIP
  - address: sf02
    type: Hostname
```
- the default detection configuration (findFirst) doesn't work for me because it picks the wrong interface. Using `canReach` or `kubernetes` picks `eth0` and the calico node is:
```
spec:
  addresses:
  - address: 10.72.70.20/31
    type: CalicoNodeIP
  - address: 10.72.70.21
    type: InternalIP
  bgp:
    ipv4Address: 10.72.70.20/31
  ipv4VXLANTunnelAddr: 172.30.144.17
```
- Moving to the calico-node pod we have (lines omitted):
```
startup/autodetection_methods.go 225: Including CIDR information from host interface. CIDR="10.72.70.21/31"
felix/int_dataplane.go 1585: Received *proto.HostMetadataUpdate update from calculation graph msg=hostname:"sf02" ipv4_addr:"10.72.70.20"
felix/vxlan_mgr.go 534: Failed to configure VXLAN tunnel device, retrying... error=Unable to find parent interface with address 10.72.70.20 ipVersion=0x4
```
- For reference here's the whole log : [calico-node.log](https://github.com/projectcalico/calico/files/8761704/calico-node.log)

So my understanding is that the CIDR is correctly autodetected, I don't find anything in the logs that would indicate if the correct IP address is detected at this point. Then the "calculation graph" finds that the IP address is actually 10.72.70.20 which is incorrect, and the subsequent errors and my lack of connectivity come from this bad address.

## Expected Behavior

Reading the [documentation](https://projectcalico.docs.tigera.io/networking/ip-autodetection#change-the-autodetection-method) about `nodeAddressAutodetection.kubernetes: NodeInternalIP`:
> Calico will select the first internal IP address listed in the Kubernetes node’s Status.Addresses field

So if kubernetes has a single `InternalIP` for a node, I expect calico to pick that.

## Current Behavior

Calico is correctly detecting the whole IP block allocated to the underlying interface, although that's not the same as "select the first internal IP address listed in the Kubernetes node". And then it somehow picks the wrong address in that block. Because of this VXLAN cannot initialize, and inter-node communication is broken.

## Possible Solution

I just started looking at calico, so I don't know the internals enough. I found a workaround though: disable IP autodetection with `nodeAddressAutodetectionV4: {}` and patch every calico node manually to set its IP. I got the network up this way and will continue evaluating calico.

But for larger clusters and dynamic IP addresses this would require to automate the node patching and in effect reimplement the `kubernetes` IP detection manually with a script that does the patching, and I guess defining the right trigger for the automatic patching is not trivial...

## Steps to Reproduce (for bugs)

I don't know what's specifically is triggering the bug in my environment. I'm guessing the fact the I get non /32 IPs, but maybe that alone is not enough.
1. Pick at least 2 nodes with /31 IP addresses assigned to the physical interface which connects them
2. Install kubernetes (kubeadm)
3. Install calico (through operator) and setup kubernetes IPv4 detection
4. If network works, wait and/or reboot

## Context

I'm trying to switch from weave to calico hoping it would be more stable and maintained. Followed the docs to install. Discussed my issue on calico's [slack](https://app.slack.com/client/T0BC4L1GD/CPEPF833L/thread/CPEPF833L-1653314448.286409) and was advised to report here.

## Your Environment

* Calico version: 3.23.1
* Orchestrator version (e.g. kubernetes, mesos, rkt): kubernetes 1.23.6 (kubeadm), containerd 1.6.4, CNI 1.1.1
* Operating System and version: linux 5.17.7 (ArchLinux)

**Comment by caseydavenport** [comment]
xref: https://github.com/projectcalico/calico/issues/6142

**Comment by antoinep92** [comment]
Thanks @caseydavenport for mentioning that. Also possible duplicate of #5851.
Although I don't think the issue is specific to the kubernetes detection mode (as other issues and mine imply). I also tested `canReach` and it has the same behavior, so I believe the root cause of the issue is bad handling of network masks and not the kubernetes/internalIP logic.
