### ISSUE TITLE
IP AutoDetectionMethod kubernetes-internal-ip seems to throw last part of IP (corresponding to subnet)

### ISSUE THREAD

**Issue by DennisGlindhart** [projectcalico/calico#6142]
When using environment IP6_AUTODETECTION_METHOD = kubernetes-internal-ip  on a node, I get the following error on all but the first node starting.

```
[INFO][10] startup/autodetection_methods.go 225: Including CIDR information from host interface. CIDR="2a00:1234:100:0:5:0:3:1/64"
[INFO][10] startup/startup.go 563: Node IPv6 changed, will check for conflicts
[WARNING][10] startup/startup.go 990: Calico node 'srvpwh-k8sworker0' is already using the IPv6 address 2a00:1234:100::.
[INFO][10] startup/startup.go 393: Clearing out-of-date IPv6 address from this node IP="2a00:1234:100::/64"
[WARNING][10] startup/utils.go 49: Terminating
```

From the logs my guess it that the logic somehow throws away the last part of the IP-address (/64 in this case). This seems like a duplicate of this https://github.com/projectcalico/calico/issues/5851 which seems to be same behaviour but for IPv4

describe node srvpwh-worker0
```
Addresses:
  InternalIP:  2a00:1234:100:0:5:0:3:0
  Hostname:    srvpwh-k8sworker0
```

describe node srvpwh-worker1
```
Addresses:
  InternalIP:  2a00:1234:100:0:5:0:3:1
  Hostname:    srvpwh-k8sworker1
```

## Your Environment
* Calico 3.23.1
* Kubernetes 1.23.4
* OpenSuse Kubic

**Comment by remram44** [comment]
Fixed by #6228
