### ISSUE TITLE
small nit: the doc of change-block-size on official

### ISSUE THREAD

**Issue by cyclinder** [projectcalico/calico#6152]
## Current Behavior

link: https://projectcalico.docs.tigera.io/networking/change-block-size
the first yaml of Installation: pec -> spec , and the format is wrong. the filed `spec` should be same level with `metadata`. 😄

## Possible Solution

Can someone tell me where the doc? I'd fix it.

## Your Environment

* Calico version
* Orchestrator version (e.g. kubernetes, mesos, rkt):
* Operating System and version:
* Link to your project (optional):

**Comment by song-jiang** [comment]
@cyclinder Good spot! The doc link is here https://github.com/projectcalico/calico/blob/master/calico/networking/change-block-size.md

**Comment by song-jiang** [comment]
Would you mind raise a PR to fix it. Thanks!
