### ISSUE TITLE
Should document + set resource requests in our calico/node manifests

### ISSUE THREAD

**Issue by fasaxc** [projectcalico/calico#617]
In scale testing on k8s for 2.1.0, I found that Felix can be starved of CPU by our pinger workloads and transient calico-CNI executions, causing high dataplane programming latency.  This was greatly improved  by adding a resource request to the calico/node container:

```
        resources:
          requests:
            cpu: 250m
```

A 250 milli-core request seemed to be enough to improve it greatly (>10x) but I saw a greater improvement with 500 milli-cores.

We should 

- [ ] document that that is required in the integration guide
- [x] update our own manifests to specify it

Note, this is different to #329, which talks about limits.  Requests give a minimum, limits cap a maximum.

**Comment by fasaxc** [comment]
Assigning to Casey to triage since it's under the k8s umbrella.  Priority-wise, this gave a massive improvement in my testing so I think it should be a ship-stopper for 2.2.0.

**Comment by caseydavenport** [comment]
`master/` and `v2.1/` manifests have been updated by #628

**Comment by djosborne** [comment]
Ping @caseydavenport this is tagged as v2.2. Seems like the only thing left is to update the integration guide? Maybe we can reassign to @tmjd for that last bit?

**Comment by caseydavenport** [comment]
SGTM

**Comment by tmjd** [comment]
With the merging of #674 I think this issue has been addressed.
