### ISSUE TITLE
calico-typha installation errors 

### ISSUE THREAD

**Issue by pingme0** [projectcalico/calico#6177]
I am trying to install Calico as Kubernetes networking plugin on a local cluster ( 1 control plane node and 1 worker node ). I am following the steps in 'Calico the hard way' section of official documentation.
The single instance of calico-typha is running and healthy, but displays errors related to the calico-typha service account.

## Expected Behavior
Clean installation logs without permission errors.

## Current Behavior

```
2022-06-02 16:57:03.227 [ERROR][7] lookup.go 61: Failed to get Typha endpoint from Kubernetes error=endpoints "calico-typha" is forbidden: User "system:serviceaccount:kube-system:calico-typha" cannot get resource "endpoints" in API group "" in the namespace "kube-system"
2022-06-02 16:57:03.227 [WARNING][7] rebalance.go 55: Failed to get number of Typhas error=<nil> numTyphas=0 thread="k8s-poll"
```

```
debian@k8s-cp:~$ kubectl get pods --all-namespaces
NAMESPACE     NAME                             READY   STATUS              RESTARTS            AGE
kube-system   calico-node-cgs65                1/1     Running             0                   5m55s
kube-system   calico-node-z595v                1/1     Running             0                   5m55s
kube-system   calico-typha-5b8669646-4r996     1/1     Running             0                   45m
kube-system   coredns-64897985d-hmvzf          0/1     ContainerCreating   0                   3d3h
kube-system   coredns-64897985d-jtbjj          0/1     ContainerCreating   0                   3d3h
kube-system   etcd-k8s-cp                      1/1     Running             10                  3d3h
kube-system   kube-apiserver-k8s-cp            1/1     Running             11                  3d3h
kube-system   kube-controller-manager-k8s-cp   1/1     Running             11                  3d3h
kube-system   kube-proxy-wnwcz                 1/1     Running             5                   3d3h
kube-system   kube-proxy-ztwhq                 1/1     Running             3 (<invalid> ago)   3d3h
kube-system   kube-scheduler-k8s-cp            1/1     Running             48                  3d3h
```

## Steps to Reproduce (for bugs)

1. Run a Kubernetes cluster ( single Master and single worker ).
2. Deploy Calico binaries and calico-typha service as described in 'Calico the hard way' ( Kubernetes API datastore configuration ).

## Your Environment

* Calico version
```
Cluster Version:   v3.20.0
Cluster Type:      typha,kdd,k8s,bgp,kubeadm
```
* Orchestrator version (e.g. kubernetes):
```
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.6", GitCommit:"ad3338546da947756e8a88aa6822e9c11e7eac22", GitTreeState:"clean", BuildDate:"2022-04-14T08:43:11Z", GoVersion:"go1.17.9", Compiler:"gc", Platform:"linux/arm64"}
```
* Operating System and version:
```
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```
* Link to your project (optional):

**Comment by lwr20** [comment]
Setting `likelihood=low` because the Hard Way documentation is a teaching tool only, not a recommended install method.

**Comment by caseydavenport** [comment]
If adding that permission fixes your issue, would love to see a PR to address the docs if you have time :heart:

**Comment by pingme0** [comment]
It's handled by someone else on the official documentation. I apologise for the delay.
Thank you very much for your support.

**Comment by AlexRITIAN** [comment]
@caseydavenport  there is still missing 'get' permission on the official documentation. [documentation URL](https://projectcalico.docs.tigera.io/getting-started/kubernetes/hardway/install-typha),

**Comment by caseydavenport** [comment]
This should fix it: https://github.com/projectcalico/calico/pull/6943
