### ISSUE TITLE
Calico Node not coming up. Kubeadm cluster

### ISSUE THREAD

**Issue by pktyagi1** [projectcalico/calico#6192]
created a kubeadm kubernetes cluster. kubectl version v1.24.1 . Facing issue in deploying calico. calico node fails to come up . Error seen in pulling the image.
## Expected Behavior
calico node should come up.

## Current Behavior
 $ kubectl get pod -n calico-system
NAME                                       READY   STATUS                  RESTARTS   AGE
calico-kube-controllers-68884f975d-qngbn   0/1     Pending                 0          11m
calico-node-46grb                          0/1     Init:ImagePullBackOff   0          11m
calico-typha-7dddb94dfb-b98s5              0/1     ImagePullBackOff        0          11m

Error in Kubectl describe calico-node

Type     Reason     Age                 From               Message
  ----     ------     ----                ----               -------
  Normal   Scheduled  16m                 default-scheduler  Successfully assigned calico-system/calico-node-46grb to kuberp-master
  Warning  Failed     15m                 kubelet            Failed to pull image "docker.io/calico/pod2daemon-flexvol:v3.23.1": rpc error: code = Unknown desc = failed to pull and unpack image "docker.io/calico/pod2daemon-flexvol:v3.23.1": failed to resolve reference "docker.io/calico/pod2daemon-flexvol:v3.23.1": failed to do request: Head "https://registry-1.docker.io/v2/calico/pod2daemon-flexvol/manifests/v3.23.1": dial tcp 34.230.238.103:443: i/o timeout
  Warning  Failed     14m                 kubelet            Failed to pull image "docker.io/calico/pod2daemon-flexvol:v3.23.1": rpc error: code = Unknown desc = failed to pull and unpack image "docker.io/calico/pod2daemon-flexvol:v3.23.1": failed to resolve reference "docker.io/calico/pod2daemon-flexvol:v3.23.1": failed to do request: Head "https://registry-1.docker.io/v2/calico/pod2daemon-flexvol/manifests/v3.23.1": dial tcp 52.21.28.242:443: i/o timeout
  Normal   Pulling    13m (x4 over 16m)   kubelet            Pulling image "docker.io/calico/pod2daemon-flexvol:v3.23.1"
  Warning  Failed     12m (x2 over 16m)   kubelet            Failed to pull image "docker.io/calico/pod2daemon-flexvol:v3.23.1": rpc error: code = Unknown desc = failed to pull and unpack image "docker.io/calico/pod2daemon-flexvol:v3.23.1": failed to resolve reference "docker.io/calico/pod2daemon-flexvol:v3.23.1": failed to do request: Head "https://registry-1.docker.io/v2/calico/pod2daemon-flexvol/manifests/v3.23.1": dial tcp 34.203.135.183:443: i/o timeout
  Warning  Failed     12m (x4 over 16m)   kubelet            Error: ErrImagePull
  Warning  Failed     12m (x6 over 16m)   kubelet            Error: ImagePullBackOff
  Normal   BackOff    93s (x48 over 16m)  kubelet            Back-off pulling image "docker.io/calico/pod2daemon-flexvol:v3.23.1"

## Your Environment
 Calico version. v3.23.1
 kubectl version: 1.24.1
Operating SystemUbuntu:20.04

Manually I am able to pull the image:
  # docker pull docker.io/calico/pod2daemon-flexvol:v3.23.1
v3.23.1: Pulling from calico/pod2daemon-flexvol
7f7fa6133bb0: Pull complete 
bba97b2469dc: Pull complete 
32d24da403c2: Pull complete 
8234f246e460: Pull complete 
23504272b9cf: Pull complete 
4f1e00f0a1da: Pull complete 
90fbf7d861b2: Pull complete

**Comment by caseydavenport** [comment]
This doesn't appear to be a Calico issue - the pod2daemon-flexvol image exists for v3.23.1, but it looks like perhaps a configuration error on your nodes that are preventing your container runtime from being able to pull the image. 

> dial tcp 34.230.238.103:443: i/o timeout

Perhaps some sort of firewall or other configuration preventing access to your container registry?

**Comment by pktyagi1** [comment]
Seems like something to do with compatiblity. Same configuration works in kubernetes version 1.21. Closing the issue for now. Thanks

**Comment by pktyagi1** [comment]
Calico(3.23)+Kubernetes(1.21) . works
