### ISSUE TITLE
Re-vamp projectcalico.org navbar

### ISSUE THREAD

**Issue by djosborne** [projectcalico/calico#62]
_From @robbrockbank on January 4, 2016 23:54_

The links from the projectcalico.org site (http://www.projectcalico.org/getting-started/) could do with a substantial re-work to better reflect the variety of options available in calico-containers.

_Copied from original issue: projectcalico/calico-containers#708_

**Comment by djosborne** [comment]
_From @caseydavenport on August 19, 2016 2:57_

@eepyaich Are you the right assignee for this?

**Comment by djosborne** [comment]
The navbar for projectcalico.org should match the new one on docs.projectcalico.org.

We will need to make the following changes:

- Merge "community" and "Contact"
- Consolidate the homepage, "Learn", and "Getting Started" on projectcalico.org

**Comment by caseydavenport** [comment]
This is labeled as P0 but has no one assigned to it. :(
