### ISSUE TITLE
Enable binary and docker image testing for arm64 platform

### ISSUE THREAD

**Issue by odidev** [projectcalico/calico#6200]
Hi Team, 

I am working on Calico. It seems that arm64 platform binaries and Docker images are not being tested in CI before release. And the Semaphore CI used in Calico doesn't provide arm64 platform support. There is a very good platform [works on arm](https://github.com/WorksOnArm) to deal with this kind of issue. 

It would be great if we release the arm64 platform binary and docker image after testing on the arm64 platform.

**Comment by TrevorTaoARM** [comment]
@odidev Did you see any issues specific to arm64 platform until now?

**Comment by odidev** [comment]
> Did you see any issues specific to arm64 platform until now? 

 

There are no specific issues we have found till now. We'd just like to see the build and test happen natively on Arm. 

 

**FYI:** 

PR for building images natively on Arm: [projectcalico/calico#5920](https://github.com/projectcalico/calico/pull/5920) 

Issue asking the same as above [projectcalico/calico#5516](https://github.com/projectcalico/calico/issues/5516) 

Maintainers of Calico say it’s a low priority.

**Comment by frozenprocess** [comment]
@odidev Calico is now being built and tested on native arm64 instances.
