### ISSUE TITLE
Test FCOS with Calico and update "System requirements" doc

### ISSUE THREAD

**Issue by b10s** [projectcalico/calico#6205]
On the [System requirements](https://projectcalico.docs.tigera.io/getting-started/bare-metal/requirements) for latest Calico the "CoreOS Container Linux stable" is mentioned.

However CoreOS is EOL few years ago and there is replacement - FCOS.

Let's use FCOS images instead of EOL CoreOS and update aforementioned documentation page to say explicitly it is FCOS.

![Selection_177](https://user-images.githubusercontent.com/4618288/174084499-8429cde4-bf57-435e-89b1-004204723e7d.png)

**Comment by caseydavenport** [comment]
Yeah, certainly removing CoreOS is something we should have done a long time ago :laughing: 

@lwr20 owns our test infrastructure so can comment on the feasibility of adding additional platforms.

**Comment by lwr20** [comment]
> However CoreOS is EOL few years ago and there is replacement - FCOS.

Its a little unclear whether FCOS is actually a CoreOS replacement.  I know Kinvolk would say that Flatcar is actually the direct descendant of CoreOS (I believe Flatcar was forked from CoreOS)

**Comment by lwr20** [comment]
It seems the only 2 kubernetes installers which use FCOS are Typhoon and OKD.  Our install infra doesn't incorporate Typhoon (yet), which leaves OKD.  We do already have Openshift in the install infra - going to look at the differences between OKD and OCP install.

**Comment by caseydavenport** [comment]
> Its a little unclear whether FCOS is actually a CoreOS replacement. I know Kinvolk would say that Flatcar is actually the direct descendant of CoreOS (I believe Flatcar was forked from CoreOS)

I was actually going to say the same thing.

I think it's worth also pointing out that we don't (and can't) test every distro that users might want, but that doesn't mean we don't expect them to work! The default stance is "it will probably work until proven otherwise" (depending on kernel version and features, but we don't need anything too special in that regard)
