### ISSUE TITLE
Pod to pod communication doesn't work with Calico and vxlan in Kubernetes 1.21

### ISSUE THREAD

**Issue by moule3053** [projectcalico/calico#6208]
## Expected Behavior

- Pod-to-pod communication should work and pods should be able to reach external networks such as hosts on the Internet
- `vxlan.calico` network interface should be there
- Routes to the pod networks on the nodes should be there

## Current Behavior

- `vxlan.calico` network interface is missing
-  Routes to the pods networks on the nodes are missing from the nodes
- pods can only reach pods on the same node, and not pods on other nodes or external networks

## Possible Solution

For the time being, updating the ippool with `ipipMode: Always` and `vxlanMode: Never` seems to resolve the issue. However, I need vxlan to work on the other clusters that I will upgrade.

## Steps to Reproduce (for bugs)

1. Upgrade cluster from Kubernetes v1.20.7 to Kubernetes v1.21.6 using Kubespray
2. Run a pod like `nettools` to test network connectivity to other pods and hosts on the Internet
3. Run `ip route` on the nodes to check the routing table

## Context

I recently upgraded a cluster from Kubernetes v1.20.7 to v1.21.6 using Kubespray. The cluster was running Calico v3.17.4 with `vxlanMode:Always`. After the upgrade, it is running Calico v3.19.2. When the upgrade was finished, I noticed that pods could only reach those on the same node, it was not possible to reach the pods on other nodes. Moreover, pods could not reach external network such as the internet. Further investigation revealed that the `vxlan.calico` network interface is missing. Plus, the route to the pod networks on other nodes were missing too.

## Your Environment

* Calico version v3.19.2
* Orchestrator version (e.g. kubernetes, mesos, rkt): Kubernetes v1.21.6
* Operating System and version: CentOS 7.9.2009

**Comment by lwr20** [comment]
> The cluster was running Calico v3.17.4 with vxlanMode:Always. After the upgrade, it is running Cilium v3.19.2.

**Comment by moule3053** [comment]
Hi @lwr20 Thanks. I think it's correct. Which part in particular do you think has a typo?

**Comment by lwr20** [comment]
> I guess Kubespray has failed to enable vxlan during the upgrade.

That would be my guess too - that somehow over the upgrade you've lost the setting.

So options now - you could set it manually?  But perhaps also talk to the kubespray team about how to set this in your kubespray config so it doesn't get lost again next time you upgrade

**Comment by moule3053** [comment]
Sure will do, thanks @lwr20.

**Comment by lwr20** [comment]
Sadly the answer to that isn't completely straightforward.

In Calico v3.22 and below, you needed to enable VXLAN in felix AND on the ippool.  You can enable VXLAN in felix either by using felixconfig or by setting the env var on the calico-node daemonset.  I'd say that setting it in felixconfig is the preferred option these days.

In Calico v3.23+, you will only need to set it on the ippool (and this is preferred).  Upgrading from v3.22 to v3.23 will remove the setting from the felixconfig, but obviously its not possible for calico to remove it from the env vars set in the calico manifest in kubernetes.

From the [v3.23 release notes](https://projectcalico.docs.tigera.io/archive/v3.23/release-notes/#general-1):
> Felix now uses the existing IP Pools to determine whether the IPIP and/or VXLAN encapsulations should be enabled. Felix now cleans up IP addresses from the tunl0 interface if IPIP is implicitly disabled. It leaves those addresses on the interface if IPIP is explicitly disabled via the default FelixConfiguration. calico #5576 (@coutinhop)

**Comment by moule3053** [comment]
Thanks for the clarification @lwr20!

**Comment by Davidrjx** [comment]
same problem between pods across nodes, unreachable ping to pod ip(192.168.24.209), then on host with the pod, "route -n" display as follows
```
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
0.0.0.0         10.246.192.1    0.0.0.0         UG    0      0        0 eth0
10.246.192.0    0.0.0.0         255.255.240.0   U     0      0        0 eth0
169.254.169.254 10.246.194.2    255.255.255.255 UGH   0      0        0 eth0
192.168.24.209  0.0.0.0         255.255.255.255 UH    0      0        0 cali6d09fa47963
```

**Comment by LaeraFelipe** [comment]
I was facing the same issue on OCI and my final solution was:

1 -  Add these iptables rules:

For control plane
```
# Clear forwarding rejections
sudo iptables -F FORWARD
sudo iptables -P FORWARD ACCEPT

# Kubernetes ports
sudo iptables -F FORWARD
sudo iptables -I INPUT 6 -m state --state NEW -p tcp --dport 6443 -j ACCEPT
sudo iptables -I INPUT 6 -m state --state NEW -p tcp --dport 2379:2380 -j ACCEPT
sudo iptables -I INPUT 6 -m state --state NEW -p tcp --dport 10250 -j ACCEPT
sudo iptables -I INPUT 6 -m state --state NEW -p tcp --dport 10257 -j ACCEPT
sudo iptables -I INPUT 6 -m state --state NEW -p tcp --dport 10259 -j ACCEPT
sudo iptables -I INPUT 6 -m state --state NEW -p tcp --dport 443 -j ACCEPT
sudo iptables -I INPUT 6 -m state --state NEW -p tcp --dport 80 -j ACCEPT

# Calico ports
sudo iptables -I INPUT 6 -m state --state NEW -p tcp --dport 179 -j ACCEPT
sudo iptables -I INPUT 6 -m state --state NEW -p udp --dport 4789 -j ACCEPT
sudo iptables -I INPUT 6 -m state --state NEW -p tcp --dport 5473 -j ACCEPT
sudo iptables -I INPUT 6 -m state --state NEW -p udp --dport 51820 -j ACCEPT
sudo iptables -I INPUT 6 -m state --state NEW -p udp --dport 51821 -j ACCEPT
sudo iptables -I INPUT 6 -m state --state NEW -p tcp --dport 2379 -j ACCEPT
sudo iptables -I INPUT 6 -m state --state NEW -p udp --dport 2379 -j ACCEPT


sudo netfilter-persistent save
```

For worker nodes
```
# Clear forwarding rejections
sudo iptables -F FORWARD
sudo iptables -P FORWARD ACCEPT

#Kubernetes ports
sudo iptables -I INPUT 6 -m state --state NEW -p tcp --dport 10250 -j ACCEPT
sudo iptables -I INPUT 6 -m state --state NEW -p tcp --dport 10256 -j ACCEPT
sudo iptables -I INPUT 6 -m state --state NEW -p tcp --dport 30000:32767 -j ACCEPT
sudo iptables -I INPUT 6 -m state --state NEW -p tcp --dport 443 -j ACCEPT
sudo iptables -I INPUT 6 -m state --state NEW -p tcp --dport 80 -j ACCEPT

# Calico ports
sudo iptables -I INPUT 6 -m state --state NEW -p tcp --dport 179 -j ACCEPT
sudo iptables -I INPUT 6 -m state --state NEW -p udp --dport 4789 -j ACCEPT
sudo iptables -I INPUT 6 -m state --state NEW -p tcp --dport 5473 -j ACCEPT
sudo iptables -I INPUT 6 -m state --state NEW -p udp --dport 51820 -j ACCEPT
sudo iptables -I INPUT 6 -m state --state NEW -p udp --dport 51821 -j ACCEPT
sudo iptables -I INPUT 6 -m state --state NEW -p tcp --dport 2379 -j ACCEPT
sudo iptables -I INPUT 6 -m state --state NEW -p udp --dport 2379 -j ACCEPT

sudo netfilter-persistent save
```
2 - Editing the ipPools configuration on calico instalation to set encapsulation as VXLAN and nodeAddressAutodetectionV4 to my CIDR. 

```
ipPools:
- allowedUses:
  - Workload
  - Tunnel
  blockSize: 26
  cidr: 192.168.0.0/16
  disableBGPExport: false
  disableNewAllocations: false
  encapsulation: VXLAN
  name: default-ipv4-ippool
  natOutgoing: Enabled
  nodeSelector: all()
linuxDataplane: Iptables
linuxPolicySetupTimeoutSeconds: 0
multiInterfaceMode: None
nodeAddressAutodetectionV4:
  cidrs:
  - 10.0.1.0/24 #change here with your CIDR
windowsDataplane: Disabled
```

3 - Restart cluster nodes.
