### ISSUE TITLE
Why iperf show that calico in ipip mode is faster than non-ipip mode?

### ISSUE THREAD

**Issue by ChenLingPeng** [projectcalico/calico#621]
I used vagrant+docker+calico+iperf3 to test calico's performance in . I found that calico in ipip mode  has higher Bandwidth then non-ipip mode. My understanding is that ipip mode has an additional process to encapsulation packet, so the test result confuse me.

here is my test command
`docker run --rm -it --net net1 networkstatic/iperf3 -c 172.17.8.101 -n 10000M -O 3`

Is it normal and if the answer is yes, can someone tell me why? 
THX

**Comment by djosborne** [comment]
You're right in that non-ipip mode should have better performance than IPIP.

A good place to look would be the MTU size for the network environment. It often has an impact on iperf testing.

**Comment by ChenLingPeng** [comment]
@tmjd I started my test follow [this tutorial](http://docs.projectcalico.org/v2.0/getting-started/docker/installation/vagrant-ubuntu/) in my MacBookPro. 
The test result is around 2.09 Gbits/sec in non-ipip mode and around 2.15 Gbits/sec in ipip mode.

I will follow @djosborne 's suggestion to modify the MTU size and re-test again.

Thanks for all the help.

**Comment by ChenLingPeng** [comment]
Setting the mtu to 1440(which is the mtu in tunl0) in iperf command makes me happy to see the result I expect! Close this since resolved.

**Comment by ChenLingPeng** [comment]
reopen this issue since the problem also exist and I can't see how to set mtu to make the bandwidth in non-ipip mode faster then ipip mode. 

here is the how to reproduce this issue in my MacbookPro:

non-ipip test:

1. `cd v2.0/getting-started/docker/installation/vagrant-ubuntu`
2. vagrant up
3. vagrant ssh calico-01 and `calicoctl node run`, `docker network create --driver calico --ipam-driver calico-ipam net1 `
4. vagrant ssh calico-02 and `calicoctl node run`
5. in calico-01, run `docker run --rm -it --net net1 --name iperf-server networkstatic/iperf3 -s` and get ip like 192.168.84.199
6. in calico-02, run `docker run --rm -it --net net1 networkstatic/iperf3 -c 192.168.84.199 -n 30000M -O 3` and repeat
7. get test result `2.11 Gbits/sec, retr 111021`, `2.11 Gbits/sec , retr 111021`

ipip mode test(after non-ipip test):
1. `calicoctl config set ipip on`
2. get ipPool resource, enable ipip and `calicoctl replace -f pool.yaml`
3. set tunl0 mtu to 1480 in two VM(because the mtu in enp0s8 is 1500)
4. in calico-01, run `docker run --rm -it --net net1 --name iperf-server networkstatic/iperf3 -s` and get ip like 192.168.84.199
5. in calico-02, run `docker run --rm -it --net net1 networkstatic/iperf3 -c 192.168.84.199 -n 30000M -O 3` and repeat
6. get test result `2.18 Gbits/sec, retr 10138`, `2.19 Gbits/sec, retr 11413`

so the performance in ipip mode is better in my test. 

My guess on this result is that the `retransmitted` in ipip mode less than non-ipip mode though I don't know why this happened.

Any idea why `retransmitted` in ipip mode is much less than normal case?

**Comment by tmjd** [comment]
@ChenLingPeng I don't know what causes the `retransmitted` but I believe whatever is causing that is the problem.  Have you tried doing the same test without calico? Using --net host? (I even destroyed and recreated my VMs and did not start calico.)  I get the same rates without calico as I do with non-IPIP so I do not believe there is a problem with non-IPIP but that IPIP does something to change the traffic which avoids some non-calico related issue.

**Comment by ChenLingPeng** [comment]
close this since not related to calico
