### ISSUE TITLE
When k8s installs calico, it overwrites the original cni plugin

### ISSUE THREAD

**Issue by vlinxh** [projectcalico/calico#6219]
After installing the cni plugin according to https://docs.projectcalico.org/manifests/calico.yaml, host-local v0.8.6 is automatically downloaded. How do I want to download the v1.1.1 version?

## Expected Behavior

use cni version 1.1.1

## Current Behavior

use Version 0.8.6

## Steps to Reproduce (for bugs)

1.After the k8s cluster is installed, apply calico.yaml and check /opt/cni/bin/host-local The version is 0.8.6
2.
3.
4.

## Your Environment

* Calico version
* Orchestrator version (e.g. kubernetes, mesos, rkt):
* Operating System and version:
* Link to your project (optional):

**Comment by lwr20** [comment]
You cannot (easily).

The host-local plugin is bundled with calico-node and we test the combination thoroughly.   What's your use-case here? 

If you really wanted to use version 1.1.1 of the host-local plugin, you could:
- submit a PR into Calico to update the version of the plugin for everyone
- build the calico-cni image yourself and use your custom image.

**Comment by lwr20** [comment]
Actually, I see that the update to 1.1.1 has already happened in the release-v3.23 branch (a possibly others) https://github.com/projectcalico/calico/pull/5944

Perhaps you just need to upgrade Calico?

**Comment by lwr20** [comment]
@vlinxh Did this work for you?  Can we close now?
