### ISSUE TITLE
Kubernetes Namespace Affinity for Pools

### ISSUE THREAD

**Issue by tmjd** [projectcalico/calico#622]
This is a feature request that allows linking a Kubernetes Namespace and Calico IP Pool.
This would cause a pod created in the namespace to use IP addresses from the linked IP Pool.

**Comment by tmjd** [comment]
Created from discussion on issue https://github.com/projectcalico/cni-plugin/issues/288

**Comment by caseydavenport** [comment]
This is available in Calico v3.3! 🙌
