### ISSUE TITLE
calicoctl v3.21.4 can not support vxlan dual stack

### ISSUE THREAD

**Issue by ArenaSu** [projectcalico/calico#6226]
## Expected Behavior

Install calico via calicoctl success when in vxlan mode.

## Current Behavior

> Error occured and message is "Failed to apply 'IPPool' resource: [error with field IPpool.VXLANMode = 'Always' (VXLANMode other than 'Never' is not supported on an IPv6 IP pool)]"

## Possible Solution

> Remove check when in vxlan and dualstack mode.
> Remove Source code: calico-3.21.4/libcalico-go/lib/validator/v3/validator.go line 895~899

## Steps to Reproduce (for bugs)

1. install k8s(v1.23.4) and calico(v3.21.4) via kubespray

## Your Environment

* Calico version: v3.21.4
* Orchestrator version (e.g. kubernetes, mesos, rkt): v1.23.4
* Operating System and version: Centos 7.9
* Link to your project (optional):

**Comment by ArenaSu** [comment]
Install dual stack calico via manifest yaml and the result is success.

**Comment by caseydavenport** [comment]
Calico v3.21 does not support IPv6 VXLAN. It's more than just validation, the code simply doesn't support it.

Calico v3.23 is the first release to support IPv6 VXLAN, as called out in the release notes: https://projectcalico.docs.tigera.io/archive/v3.23/release-notes/#ipv6-vxlan-support
