### ISSUE TITLE
Traffic shaping with Calico and k8s

### ISSUE THREAD

**Issue by sepehrjavid** [projectcalico/calico#6232]
Hello,

I have been trying to test the traffic shaping feature based on the test provided in #797 and the result is different than what is expected. I am suing k8s version 1.21.1 and the calico version 3.14. The cluster was created using kubeadm and I am using a VM for as a worker node and another VM as the controller in OpenStack
The /etc/cni/net.d/10-calico.conflist contains:
![Screenshot from 2022-06-15 11-49-49](https://user-images.githubusercontent.com/32390553/174059465-a91f96f0-c961-429b-a94b-e79335327945.png)

the result with traffic shaping enabled and setup to 1M on the iperf-server pod is:
![withTS](https://user-images.githubusercontent.com/32390553/174059596-ac851e9d-8342-40e9-9826-eda189e22983.png)

and without traffic shaping the result is:
![withoutTS](https://user-images.githubusercontent.com/32390553/174059661-32bc9bf9-5fa3-4c29-bd37-5dd96196c0d1.png)

Also bandwidth file exists in /opt/cni/bin/ path as well.

As seen in the results, the bandwidth is more than the setup threshold and I was curios to know what could be the reason.

Could you please help me resolve the problem?
Thank you so much

**Comment by sepehrjavid** [comment]
Update:

I set the threshold to 50 Mbits/sec and the first measurements seemed too far from the threshold. However, the next bandwidths were within the setup range. Any ideas why this might be happening that only the first connection is consuming way more bandwidth than the threshold?

![Screenshot from 2022-06-20 10-01-33](https://user-images.githubusercontent.com/32390553/174544336-c8b02659-d97d-4884-8644-9c661c5e4ce2.png)

**Comment by Josh-Tigera** [comment]
I noticed that you mention you're using OpenShift, and reading through the discussion on the issue you linked this comment:

https://github.com/projectcalico/calico/issues/797#issuecomment-494028690

Suggested that the bandwidth feature was originally only supported with docker as the container runtime, though I'm not sure what the state of the bandwidth feature is today with respect to various different runtimes.

Are you able to run `tc qdisc show` in your iperf-server pod to verify if the rules were installed correctly?

**Comment by optimus-kart** [comment]
Is this enabled by default now? if not is there a documentation on how to do it for AWS EKS installation of calico?
