### ISSUE TITLE
Use Vxlan mode to install dual stack k8s. Only Pod's IPv4 address can be accessed from another node's pod. Use IPv6 address will meet "connect: Network is unreachable"

### ISSUE THREAD

**Issue by hellocn9** [projectcalico/calico#6246]
Use Vxlan mode to install dual stack k8s. Only Pod's IPv4 address can be accessed from another node's pod. Use IPv6 address will meet "connect: Network is unreachable"

Calico version：3.23.1
K8S version：1.23.6
Centos7
Docker version：20.10.14

When I check calico-node‘s log, I see a lot of repeat info as below:

```
2022-06-20 09:46:55.902 [WARNING][94] felix/route_table.go 1181: Failed to access interface but it appears to be up error=netlink update operation failed ifaceNa
me="vxlan-v6.calico" ifaceRegex="^vxlan-v6.calico$" ipVersion=0x6 link=&netlink.Vxlan{LinkAttrs:netlink.LinkAttrs{Index:207, MTU:1380, TxQLen:0, Name:"vxlan-v6.c
alico", HardwareAddr:net.HardwareAddr{0x66, 0x5e, 0xc1, 0x67, 0x8d, 0x25}, Flags:0x13, RawFlags:0x11043, ParentIndex:0, MasterIndex:0, Namespace:interface {}(nil
), Alias:"", Statistics:(*netlink.LinkStatistics)(0xc00036ed80), Promisc:0, Allmulti:0, Multi:1, Xdp:(*netlink.LinkXdp)(nil), EncapType:"ether", Protinfo:(*netli
nk.Protinfo)(nil), OperState:0x0, PhysSwitchID:0, NetNsID:-1, NumTxQueues:1, NumRxQueues:1, GSOMaxSize:0x10000, GSOMaxSegs:0xffff, Vfs:[]netlink.VfInfo(nil), Gro
up:0x0, Slave:netlink.LinkSlave(nil)}, VxlanId:4096, VtepDevIndex:9, SrcAddr:net.IP{0x24, 0x9, 0x80, 0x28, 0x5c, 0xc0, 0xbb, 0xf3, 0x0, 0x0, 0x0, 0x0, 0x0, 0x6, 
0x0, 0x72}, Group:net.IP(nil), TTL:0, TOS:0, Learning:false, Proxy:false, RSC:false, L2miss:false, L3miss:false, UDPCSum:false, UDP6ZeroCSumTx:false, UDP6ZeroCSu
mRx:false, NoAge:false, GBP:false, FlowBased:false, Age:300, Limit:0, Port:4789, PortLow:0, PortHigh:0} tableIndex=0
2022-06-20 09:46:55.902 [WARNING][94] felix/route_table.go 604: Failed to sync routes to interface even after retries. Leaving it dirty, requiring a full sync. i
faceName="vxlan-v6.calico" ifaceRegex="^vxlan-v6.calico$" ipVersion=0x6 tableIndex=0
2022-06-20 09:46:55.902 [WARNING][94] felix/route_table.go 617: Some interfaces still out-of sync. ifaceRegex="^vxlan-v6.calico$" ipVersion=0x6 tableIndex=0
2022-06-20 09:46:55.903 [WARNING][94] felix/int_dataplane.go 1905: Failed to synchronize routing table, will retry...
2022-06-20 09:46:56.003 [INFO][94] felix/route_table.go 953: Deleting from expected targets cidr=2001:db8:42:8c:5187:693e:95:ecc0/122 ifaceName="vxlan-v6.calico"
 ifaceRegex="^vxlan-v6.calico$" ipVersion=0x6 tableIndex=0
2022-06-20 09:46:56.003 [INFO][94] felix/route_table.go 959: No pending target update, adding back in as an update cidr=2001:db8:42:8c:5187:693e:95:ecc0/122 ifac
eName="vxlan-v6.calico" ifaceRegex="^vxlan-v6.calico$" ipVersion=0x6 tableIndex=0
2022-06-20 09:46:56.004 [INFO][94] felix/route_table.go 953: Deleting from expected targets cidr=2001:db8:42:8c:5187:693e:95:ecc0/122 ifaceName="vxlan-v6.calico"
 ifaceRegex="^vxlan-v6.calico$" ipVersion=0x6 tableIndex=0
2022-06-20 09:46:56.004 [INFO][94] felix/route_table.go 959: No pending target update, adding back in as an update cidr=2001:db8:42:8c:5187:693e:95:ecc0/122 ifac
eName="vxlan-v6.calico" ifaceRegex="^vxlan-v6.calico$" ipVersion=0x6 tableIndex=0
2022-06-20 09:46:56.005 [WARNING][94] felix/route_table.go 722: Failed to add route error=no route to host ifaceName="vxlan-v6.calico" ifaceRegex="^vxlan-v6.cali
co$" ipVersion=0x6 tableIndex=0
2022-06-20 09:46:56.005 [WARNING][94] felix/route_table.go 1181: Failed to access interface but it appears to be up error=netlink update operation failed ifaceNa
me="vxlan-v6.calico" ifaceRegex="^vxlan-v6.calico$" ipVersion=0x6 link=&netlink.Vxlan{LinkAttrs:netlink.LinkAttrs{Index:207, MTU:1380, TxQLen:0, Name:"vxlan-v6.c
alico", HardwareAddr:net.HardwareAddr{0x66, 0x5e, 0xc1, 0x67, 0x8d, 0x25}, Flags:0x13, RawFlags:0x11043, ParentIndex:0, MasterIndex:0, Namespace:interface {}(nil
), Alias:"", Statistics:(*netlink.LinkStatistics)(0xc000de3a40), Promisc:0, Allmulti:0, Multi:1, Xdp:(*netlink.LinkXdp)(nil), EncapType:"ether", Protinfo:(*netli
nk.Protinfo)(nil), OperState:0x0, PhysSwitchID:0, NetNsID:-1, NumTxQueues:1, NumRxQueues:1, GSOMaxSize:0x10000, GSOMaxSegs:0xffff, Vfs:[]netlink.VfInfo(nil), Gro
up:0x0, Slave:netlink.LinkSlave(nil)}, VxlanId:4096, VtepDevIndex:9, SrcAddr:net.IP{0x24, 0x9, 0x80, 0x28, 0x5c, 0xc0, 0xbb, 0xf3, 0x0, 0x0, 0x0, 0x0, 0x0, 0x6, 
0x0, 0x72}, Group:net.IP(nil), TTL:0, TOS:0, Learning:false, Proxy:false, RSC:false, L2miss:false, L3miss:false, UDPCSum:false, UDP6ZeroCSumTx:false, UDP6ZeroCSu
mRx:false, NoAge:false, GBP:false, FlowBased:false, Age:300, Limit:0, Port:4789, PortLow:0, PortHigh:0} tableIndex=0
2022-06-20 09:46:56.005 [WARNING][94] felix/route_table.go 604: Failed to sync routes to interface even after retries. Leaving it dirty, requiring a full sync. i
faceName="vxlan-v6.calico" ifaceRegex="^vxlan-v6.calico$" ipVersion=0x6 tableIndex=0
2022-06-20 09:46:56.005 [WARNING][94] felix/route_table.go 617: Some interfaces still out-of sync. ifaceRegex="^vxlan-v6.calico$" ipVersion=0x6 tableIndex=0
2022-06-20 09:46:56.005 [WARNING][94] felix/int_dataplane.go 1905: Failed to synchronize routing table, will retry...
2022-06-20 09:46:56.116 [INFO][94] felix/route_table.go 953: Deleting from expected targets cidr=2001:db8:42:8c:5187:693e:95:ecc0/122 ifaceName="vxlan-v6.calico"
 ifaceRegex="^vxlan-v6.calico$" ipVersion=0x6 tableIndex=0
2022-06-20 09:46:56.116 [INFO][94] felix/route_table.go 959: No pending target update, adding back in as an update cidr=2001:db8:42:8c:5187:693e:95:ecc0/122 ifac
eName="vxlan-v6.calico" ifaceRegex="^vxlan-v6.calico$" ipVersion=0x6 tableIndex=0
2022-06-20 09:46:56.118 [INFO][94] felix/route_table.go 953: Deleting from expected targets cidr=2001:db8:42:8c:5187:693e:95:ecc0/122 ifaceName="vxlan-v6.calico"
 ifaceRegex="^vxlan-v6.calico$" ipVersion=0x6 tableIndex=0
2022-06-20 09:46:56.118 [INFO][94] felix/route_table.go 959: No pending target update, adding back in as an update cidr=2001:db8:42:8c:5187:693e:95:ecc0/122 ifac
eName="vxlan-v6.calico" ifaceRegex="^vxlan-v6.calico$" ipVersion=0x6 tableIndex=0
2022-06-20 09:46:56.118 [WARNING][94] felix/route_table.go 722: Failed to add route error=no route to host ifaceName="vxlan-v6.calico" ifaceRegex="^vxlan-v6.cali
co$" ipVersion=0x6 tableIndex=0
```

I don't know where the problem is.

Can you help me ? Thanks

**Comment by hellocn9** [comment]
@coutinhop can you help me ? thanks a lot

**Comment by coutinhop** [comment]
Hi @hellocn9,

These log messages seem relevant to me:
```
2022-06-21 03:24:12.575 [ERROR][66] felix/route_table.go 994: Failed to get link attributes error=interface not present ifaceRegex="^vxlan-v6.calico$" ipVersion=0x6 tableIndex=0
```

and

```
2022-06-21 03:24:12.691 [WARNING][66] felix/route_table.go 1181: Failed to access interface but it appears to be up error=netlink update operation failed ifaceName="vxlan-v6.calico" ifaceRegex="^vxlan-v6.calico$" ipVersion=0x6 link=&netlink.Vxlan{LinkAttrs:netlink.LinkAttrs{Index:13, MTU:1430, TxQLen:0, Name:"vxlan-v6.calico", HardwareAddr:net.HardwareAddr{0x66, 0xa4, 0x36, 0x2b, 0xc5, 0x2b}, Flags:0x13, RawFlags:0x11043, ParentIndex:0, MasterIndex:0, Namespace:interface {}(nil), Alias:"", Statistics:(*netlink.LinkStatistics)(0xc000aa0240), Promisc:0, Allmulti:0, Multi:1, Xdp:(*netlink.LinkXdp)(nil), EncapType:"ether", Protinfo:(*netlink.Protinfo)(nil), OperState:0x0, PhysSwitchID:0, NetNsID:-1, NumTxQueues:1, NumRxQueues:1, GSOMaxSize:0x10000, GSOMaxSegs:0xffff, Vfs:[]netlink.VfInfo(nil), Group:0x0, Slave:netlink.LinkSlave(nil)}, VxlanId:4096, VtepDevIndex:2, SrcAddr:net.IP{0xfd, 0x15, 0x4b, 0xa5, 0x5a, 0x2b, 0x10, 0x8, 0x59, 0xee, 0xc4, 0x2b, 0xd5, 0xc9, 0x2e, 0xb4}, Group:net.IP(nil), TTL:0, TOS:0, Learning:false, Proxy:false, RSC:false, L2miss:false, L3miss:false, UDPCSum:false, UDP6ZeroCSumTx:false, UDP6ZeroCSumRx:false, NoAge:false, GBP:false, FlowBased:false, Age:300, Limit:0, Port:4789, PortLow:0, PortHigh:0} tableIndex=0
```

It could be that the IPv6 vxlan intf was still being set up, as the `Failed to get link attributes error=interface not present` message stops after a while, but `Failed to access interface but it appears to be up error=netlink update operation failed` keeps being spammed throughout the log...

Can you expand a little bit on your set up? How did you set up dual stack calico?

Could you also send what you have for FelixConfiguration, and IP pools? Could you run `ip addr` and `ip link` on your calico-node?

I'm trying to understand what's going on with the vxlan-v6.calico interface that makes calico fail to access it...

**Comment by hellocn9** [comment]
[calico.zip](https://github.com/projectcalico/calico/files/8973624/calico.zip)
Here is calico.yaml configuration.



Follow is node 192-168-239-143 ip info

[root@192-168-239-143 kubernetes]# ip addr
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: ens33: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 00:0c:29:19:49:4d brd ff:ff:ff:ff:ff:ff
    inet 192.168.239.143/24 brd 192.168.239.255 scope global noprefixroute dynamic ens33
       valid_lft 864330sec preferred_lft 864330sec
    inet6 fd15:4ba5:5a2b:1008:59ee:c42b:d5c9:2eb4/64 scope global noprefixroute dynamic 
       valid_lft 86390sec preferred_lft 14390sec
    inet6 fe80::386d:35de:8672:c292/64 scope link noprefixroute 
       valid_lft forever preferred_lft forever
3: docker0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default 
    link/ether 02:42:66:ef:2e:8a brd ff:ff:ff:ff:ff:ff
    inet 172.17.0.1/16 brd 172.17.255.255 scope global docker0
       valid_lft forever preferred_lft forever
4: dummy0: <BROADCAST,NOARP> mtu 1500 qdisc noop state DOWN group default qlen 1000
    link/ether 22:5c:9c:1b:6f:fb brd ff:ff:ff:ff:ff:ff
5: nodelocaldns: <BROADCAST,NOARP> mtu 1500 qdisc noop state DOWN group default 
    link/ether 3a:6b:c5:eb:ad:cb brd ff:ff:ff:ff:ff:ff
    inet 169.254.25.10/32 brd 169.254.25.10 scope global nodelocaldns
       valid_lft forever preferred_lft forever
6: kube-ipvs0: <BROADCAST,NOARP> mtu 1500 qdisc noop state DOWN group default 
    link/ether 82:fd:eb:d1:fb:a9 brd ff:ff:ff:ff:ff:ff
    inet 10.96.0.3/32 scope global kube-ipvs0
       valid_lft forever preferred_lft forever
    inet 10.96.0.1/32 scope global kube-ipvs0
       valid_lft forever preferred_lft forever
    inet 10.96.83.6/32 scope global kube-ipvs0
       valid_lft forever preferred_lft forever
    inet6 2001:db8:40:1::68e1/128 scope global 
       valid_lft forever preferred_lft forever
7: cali905dcb8d5d5@if3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1430 qdisc noqueue state UP group default 
    link/ether ee:ee:ee:ee:ee:ee brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet6 fe80::ecee:eeff:feee:eeee/64 scope link 
       valid_lft forever preferred_lft forever
8: calidba5221d753@if3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1430 qdisc noqueue state UP group default 
    link/ether ee:ee:ee:ee:ee:ee brd ff:ff:ff:ff:ff:ff link-netnsid 1
    inet6 fe80::ecee:eeff:feee:eeee/64 scope link 
       valid_lft forever preferred_lft forever
9: cali7a5c11ec6eb@if3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1430 qdisc noqueue state UP group default 
    link/ether ee:ee:ee:ee:ee:ee brd ff:ff:ff:ff:ff:ff link-netnsid 2
    inet6 fe80::ecee:eeff:feee:eeee/64 scope link 
       valid_lft forever preferred_lft forever
10: vxlan.calico: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue state UNKNOWN group default 
    link/ether 66:bc:03:20:cf:64 brd ff:ff:ff:ff:ff:ff
    inet 10.224.151.128/32 scope global vxlan.calico
       valid_lft forever preferred_lft forever
    inet6 fe80::64bc:3ff:fe20:cf64/64 scope link 
       valid_lft forever preferred_lft forever
11: vxlan-v6.calico: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1430 qdisc noqueue state UNKNOWN group default 
    link/ether 66:a4:36:2b:c5:2b brd ff:ff:ff:ff:ff:ff
    inet6 2001:db8:42:35:e7c7:ad3d:96bd:6200/128 scope global 
       valid_lft forever preferred_lft forever
[root@192-168-239-143 kubernetes]# 
[root@192-168-239-143 kubernetes]# 
[root@192-168-239-143 kubernetes]# ip link
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN mode DEFAULT group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
2: ens33: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP mode DEFAULT group default qlen 1000
    link/ether 00:0c:29:19:49:4d brd ff:ff:ff:ff:ff:ff
3: docker0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN mode DEFAULT group default 
    link/ether 02:42:66:ef:2e:8a brd ff:ff:ff:ff:ff:ff
4: dummy0: <BROADCAST,NOARP> mtu 1500 qdisc noop state DOWN mode DEFAULT group default qlen 1000
    link/ether 22:5c:9c:1b:6f:fb brd ff:ff:ff:ff:ff:ff
5: nodelocaldns: <BROADCAST,NOARP> mtu 1500 qdisc noop state DOWN mode DEFAULT group default 
    link/ether 3a:6b:c5:eb:ad:cb brd ff:ff:ff:ff:ff:ff
6: kube-ipvs0: <BROADCAST,NOARP> mtu 1500 qdisc noop state DOWN mode DEFAULT group default 
    link/ether 82:fd:eb:d1:fb:a9 brd ff:ff:ff:ff:ff:ff
7: cali905dcb8d5d5@if3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1430 qdisc noqueue state UP mode DEFAULT group default 
    link/ether ee:ee:ee:ee:ee:ee brd ff:ff:ff:ff:ff:ff link-netnsid 0
8: calidba5221d753@if3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1430 qdisc noqueue state UP mode DEFAULT group default 
    link/ether ee:ee:ee:ee:ee:ee brd ff:ff:ff:ff:ff:ff link-netnsid 1
9: cali7a5c11ec6eb@if3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1430 qdisc noqueue state UP mode DEFAULT group default 
    link/ether ee:ee:ee:ee:ee:ee brd ff:ff:ff:ff:ff:ff link-netnsid 2
10: vxlan.calico: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue state UNKNOWN mode DEFAULT group default 
    link/ether 66:bc:03:20:cf:64 brd ff:ff:ff:ff:ff:ff
11: vxlan-v6.calico: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1430 qdisc noqueue state UNKNOWN mode DEFAULT group default 
    link/ether 66:a4:36:2b:c5:2b brd ff:ff:ff:ff:ff:ff

Follow is node 192-168-239-144 ip info

[root@192-168-239-144 ~]# ip addr
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: ens33: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 00:0c:29:6f:b9:a5 brd ff:ff:ff:ff:ff:ff
    inet 192.168.239.144/24 brd 192.168.239.255 scope global noprefixroute dynamic ens33
       valid_lft 865226sec preferred_lft 865226sec
    inet6 fd15:4ba5:5a2b:1008:ebc2:f878:9ff0:ade5/64 scope global noprefixroute dynamic 
       valid_lft 86395sec preferred_lft 14395sec
    inet6 fe80::e297:ea14:1749:c8f7/64 scope link noprefixroute 
       valid_lft forever preferred_lft forever
3: docker0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default 
    link/ether 02:42:42:5b:33:de brd ff:ff:ff:ff:ff:ff
    inet 172.17.0.1/16 brd 172.17.255.255 scope global docker0
       valid_lft forever preferred_lft forever
4: dummy0: <BROADCAST,NOARP> mtu 1500 qdisc noop state DOWN group default qlen 1000
    link/ether 16:95:cc:6a:97:81 brd ff:ff:ff:ff:ff:ff
5: kube-ipvs0: <BROADCAST,NOARP> mtu 1500 qdisc noop state DOWN group default 
    link/ether ce:39:79:6e:06:25 brd ff:ff:ff:ff:ff:ff
    inet 10.96.0.1/32 scope global kube-ipvs0
       valid_lft forever preferred_lft forever
    inet 10.96.83.6/32 scope global kube-ipvs0
       valid_lft forever preferred_lft forever
    inet 10.96.0.3/32 scope global kube-ipvs0
       valid_lft forever preferred_lft forever
    inet6 2001:db8:40:1::68e1/128 scope global 
       valid_lft forever preferred_lft forever
6: nodelocaldns: <BROADCAST,NOARP> mtu 1500 qdisc noop state DOWN group default 
    link/ether a6:7f:df:20:2c:ba brd ff:ff:ff:ff:ff:ff
    inet 169.254.25.10/32 brd 169.254.25.10 scope global nodelocaldns
       valid_lft forever preferred_lft forever
7: vxlan.calico: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue state UNKNOWN group default 
    link/ether 66:bd:3c:e0:1b:02 brd ff:ff:ff:ff:ff:ff
    inet 10.224.150.0/32 scope global vxlan.calico
       valid_lft forever preferred_lft forever
    inet6 fe80::64bd:3cff:fee0:1b02/64 scope link 
       valid_lft forever preferred_lft forever
8: vxlan-v6.calico: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1430 qdisc noqueue state UNKNOWN group default 
    link/ether 66:04:71:b8:3b:75 brd ff:ff:ff:ff:ff:ff
    inet6 2001:db8:42:88:291:b347:abd:eb00/128 scope global 
       valid_lft forever preferred_lft forever
11: calid8f1074fb86@if3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1430 qdisc noqueue state UP group default 
    link/ether ee:ee:ee:ee:ee:ee brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet6 fe80::ecee:eeff:feee:eeee/64 scope link 
       valid_lft forever preferred_lft forever
12: calid53a79e6f2b@if3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1430 qdisc noqueue state UP group default 
    link/ether ee:ee:ee:ee:ee:ee brd ff:ff:ff:ff:ff:ff link-netnsid 1
    inet6 fe80::ecee:eeff:feee:eeee/64 scope link 
       valid_lft forever preferred_lft forever
13: calicd9030b8d9f@if3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1430 qdisc noqueue state UP group default 
    link/ether ee:ee:ee:ee:ee:ee brd ff:ff:ff:ff:ff:ff link-netnsid 2
    inet6 fe80::ecee:eeff:feee:eeee/64 scope link 
       valid_lft forever preferred_lft forever
[root@192-168-239-144 ~]# ip link
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN mode DEFAULT group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
2: ens33: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP mode DEFAULT group default qlen 1000
    link/ether 00:0c:29:6f:b9:a5 brd ff:ff:ff:ff:ff:ff
3: docker0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN mode DEFAULT group default 
    link/ether 02:42:42:5b:33:de brd ff:ff:ff:ff:ff:ff
4: dummy0: <BROADCAST,NOARP> mtu 1500 qdisc noop state DOWN mode DEFAULT group default qlen 1000
    link/ether 16:95:cc:6a:97:81 brd ff:ff:ff:ff:ff:ff
5: kube-ipvs0: <BROADCAST,NOARP> mtu 1500 qdisc noop state DOWN mode DEFAULT group default 
    link/ether ce:39:79:6e:06:25 brd ff:ff:ff:ff:ff:ff
6: nodelocaldns: <BROADCAST,NOARP> mtu 1500 qdisc noop state DOWN mode DEFAULT group default 
    link/ether a6:7f:df:20:2c:ba brd ff:ff:ff:ff:ff:ff
7: vxlan.calico: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue state UNKNOWN mode DEFAULT group default 
    link/ether 66:bd:3c:e0:1b:02 brd ff:ff:ff:ff:ff:ff
8: vxlan-v6.calico: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1430 qdisc noqueue state UNKNOWN mode DEFAULT group default 
    link/ether 66:04:71:b8:3b:75 brd ff:ff:ff:ff:ff:ff
11: calid8f1074fb86@if3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1430 qdisc noqueue state UP mode DEFAULT group default 
    link/ether ee:ee:ee:ee:ee:ee brd ff:ff:ff:ff:ff:ff link-netnsid 0
12: calid53a79e6f2b@if3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1430 qdisc noqueue state UP mode DEFAULT group default 
    link/ether ee:ee:ee:ee:ee:ee brd ff:ff:ff:ff:ff:ff link-netnsid 1
13: calicd9030b8d9f@if3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1430 qdisc noqueue state UP mode DEFAULT group default 
    link/ether ee:ee:ee:ee:ee:ee brd ff:ff:ff:ff:ff:ff link-netnsid 2

**Comment by ArenaSu** [comment]
I meet the same problem. [https://github.com/projectcalico/calico/issues/6273#issue-1283419449]

**Comment by coutinhop** [comment]
At first I thought `state UNKNOWN` could mean trouble, but [it doesn't seem to matter and the interfaces are indeed up](https://superuser.com/questions/1463162/unknown-state-of-network-interface).

I'm trying to repro this on my side, but could you try [increasing felix's log level to debug](https://projectcalico.docs.tigera.io/maintenance/troubleshoot/component-logs#configure-felix-log-level) and posting the output here?

**Comment by coutinhop** [comment]
@hellocn9 what kernel version are you using? https://github.com/projectcalico/calico/issues/6273 was just closed as they were having trouble with 3.10, but upgrading to 5.4 seemed to get everything working. If you can, though, please get some logs with debug level and post them here first. Thanks!

**Comment by cyclinder** [comment]
Hi @coutinhop , Calico only don't support `ipip on ipv6` these days?

**Comment by caseydavenport** [comment]
@hellocn9 any update on this? Did you see @coutinhop's question? 

@cyclinder IPIP is v4 only, Wireguard is v4 only but planning to add v6 support in Calico v3.24, and VXLAN supports dual-stack.

**Comment by hellocn9** [comment]
> ey were having trouble with 3.10, but upgrading to 5.4 seemed to get everything working. If you can, though, please get some logs with debug level and post them here first. Thanks!

kernel version is  3.10.0. Also, upgrading to 4.19, it seemed to be solved.
