### ISSUE TITLE
Access to cluster external hosts fails for pods with IP from IPpool with disabled natOutgoing

### ISSUE THREAD

**Issue by wbosse** [projectcalico/calico#6254]
From pods with IP addresses from pool with natOutgoing set to false cluster internal network access is operational but access to cluster external hosts fails probably because affected traffic is not routed.
For testing the pod IP was now assigned in node OS to the default NIC. Network accesses using the pod IP as source address succeeds. In node OS the pod IP is removed now from default NIC. Afterwards the network access to external hosts succeeds also in still running pod. So the setup and application of the IP pool seems to be correct.

## Expected Behavior

Routes to networks connected to node NIC are active for new pods allocating IP address from pool with natOutgoing set to false.

## Current Behavior

Routes to networks connected to node NIC are not active for new pods allocating IP address from pool with natOutgoing set to false.

## Possible Solution

n.a.

## Steps to Reproduce (for bugs)

1. Create IP pool:
```shell
$ cat protected-ippool.yaml
apiVersion: projectcalico.org/v3
kind: IPPool
metadata:
  name: protected-ipv4-ippool
spec:
  cidr: 10.50.148.192/26
  blocksize: 32
  ipipMode: Never
  vxlanmode: Never
  natOutgoing: false
$ calicoctl apply -f protected_ippool.yaml
```
2. Create namespace for pods
```shell
$ kubectl create namespace protected-pod
$ kubectl annotate namespace protected-pod --overwrite cni.projectcalico.org/ipv4pools='["protected-ipv4-ippool"]'
```
3. start pod utilizing IP pool
```shell
$ kubectl run protected-1 --image centos:7 --namespace protected-pod
$ kubectl get pods --namespace protected-pod-o wide
NAME          READY   STATUS    RESTARTS   AGE     IP              NODE            NOMINATED NODE   READINESS GATES
protected-1   1/1     Running   0          5m44s   10.50.148.200   avk8sp-node36   <none>           <none>
```
4. network access from pod to cluster external host fails
```shell
$ kubectl exec -it pod/protected-1 --namespace protected-pod -- bash
$ ping -c 1 10.50.15.56
PING 10.50.15.56 (10.50.15.56) 56(84) bytes of data.
From 10.50.148.200 icmp_seq=1 Destination Host Unreachable

--- 10.50.15.56 ping statistics ---
1 packets transmitted, 0 received, +1 errors, 100% packet loss, time 0ms
$ exit
```
5. create/activate missing route on cluster node
```shell
$ ip address add 10.50.148.200/32 dev eth0
$ ping -c 1 10.50.15.56
PING 10.50.15.56 (10.50.15.56) 56(84) bytes of data.
64 bytes from 10.50.15.56: icmp_seq=1 ttl=64 time=0.590 ms

--- 10.50.15.56 ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 0.590/0.590/0.590/0.000 ms
$ ip address del 10.50.148.200/32 dev eth0
```
6. network access in pod succeeds now
```shell
$ kubectl exec -it pod/protected-1 --namespace protected-pod -- bash
$ ping -c 1 10.50.15.56
PING 10.50.15.56 (10.50.15.56) 56(84) bytes of data.
64 bytes from 10.50.15.56: icmp_seq=1 ttl=64 time=0.590 ms

--- 10.50.15.56 ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 0.620/0.600/0.610/0.000 ms
$ exit
```

## Context

Network access to legacy systems running on VMs hosted in DMZ from pods in a particular namespace. Firewall limits access to DMZ to a subnet of cluster nodes default network mask.

## Your Environment

* Calico version 3.21.4
* Orchestrator version (e.g. kubernetes, mesos, rkt): RKE2 with k8s 1.22.7
* Operating System and version: CentOS 7
* Link to your project (optional): public access not available

**Comment by caseydavenport** [comment]
With natOutgoing disabled, you need to make sure that your underlying network is capable of routing packets back to pod IPs directly. This means that any routing infrastructure (if you have it) needs to be told about pod IPs (e.g., via BGP or static routes).

If you have a flat L2 network between your nodes, then ARP might be the issue and perhaps that is why the temporary address + ping on the host fixed the issue - it may have populated ARP tables in your switch or remote node? 

Either way, I think this is working as expected. I'd recommend sharing a bit more information on your network structure, and digging into what state changed in your network after the successful ping - e.g., routes / arp caches.

**Comment by wbosse** [comment]
Our current solution is 

- enable ARP proxy for default NIC on all nodes deployed with applications requiring access to DMZ
  ```
  $ echo 1 >/proc/sys/net/ipv4/conf/eth0/proxy_arp
  ```
- to avoid problems with ARP caches use reasonable `cidr` & `blocksize` values for `protected-ipv4-ippool`
   - With `cidr` set to a /26 netmask & `blocksize` set to 29 the pool contains 8 blocks containing 8 IP addresses. This matches up to 4 nodes running each up to 8 concurrent requests accessing DMZ targets. 

PS: Sorry for the late response.
