### ISSUE TITLE
flag provided but not defined: -best-effort

### ISSUE THREAD

**Issue by nitinjagjivan** [projectcalico/calico#6255]
Using calico v3.23.1
Today I am facing an issue while installing it.

kubectl get po -n kube-system
NAME                                                        READY   STATUS                  RESTARTS      AGE
calico-kube-controllers-6b77fff45-djdf5                     0/1     ContainerCreating       0             49m
**calico-node-gcxmw                                           0/1     Init:CrashLoopBackOff   6 (39s ago)   6m16s**
coredns-64897985d-qtt6l                                     0/1     ContainerCreating       0             49m
coredns-64897985d-wmjnw                                     0/1     ContainerCreating       0             49m

kubectl logs -n kube-system calico-node-gcxmw -c mount-bpffs
`flag provided but not defined: -best-effort
Usage of Calico:
  -allocate-tunnel-addrs
flag provided but not defined: -best-effort
    	Configure tunnel addresses for this node
  -allocate-tunnel-addrs-run-once
    	Run allocate-tunnel-addrs in oneshot mode
  -bird-live
    	Run bird liveness checks
  -bird-ready
    	Run BIRD readiness checks
  -bird6-live
    	Run bird6 liveness checks
  -bird6-ready
    	Run BIRD6 readiness checks
  -bpf
    	Run BPF debug tool
  -confd
    	Run confd
  -confd-confdir string
    	Confd configuration directory. (default "/etc/calico/confd")
  -confd-keep-stage-file
    	Keep stage file when running confd
  -confd-run-once
    	Run confd in oneshot mode
  -felix
    	Run Felix
  -felix-live
    	Run felix liveness checks
  -felix-ready
    	Run felix readiness checks
  -hostpath-init
    	Initialize hostpaths for non-root access
  -init
    	Do privileged initialisation of a new node (mount file systems etc).
  -monitor-addresses
    	Monitor change in node IP addresses
  -monitor-token
    	Watch for Kubernetes token changes, update CNI config
  -should-install-windows-upgrade
    	Check if Windows upgrade service should be installed.
  -show-status
    	Print out node status
  -shutdown
    	Do shutdown routine.
  -startup
    	Do non-privileged start-up routine.
  -status-reporter
    	Run node status reporter
  -threshold-time duration
    	Threshold time for bird readiness (default 30s)
  -upgrade-windows
    	Run Windows upgrade service.
  -v	Display version
`

Orchestrator version (e.g. kubernetes, containerd): k8s 1.23.4
Operating System and version: CentOS 7

**Comment by fidsamurai-crelio** [comment]
@nitinjagjivan Was facing this same problem with 3.23.1 and 3.22.3.

If you're using manifests try the following -
```
# This init container mounts the necessary filesystems needed by the BPF data plane
        # i.e. bpf at /sys/fs/bpf and cgroup2 at /run/calico/cgroup. Calico-node initialisation is executed
        # in best effort fashion, i.e. no failure for errors, to not disrupt pod creation in iptable mode.
        - name: "mount-bpffs"
          image: docker.io/calico/node:v3.22.3
          command: ["calico-node", "-init"]
```

Basically remove the `-best-effort` flag from the `mount-bpffs` container spec

**Comment by nitinjagjivan** [comment]
Thanks @fidsamurai-crelio. We decided to install working v3.21 till this is fixed.

**Comment by mazdakn** [comment]
This happens because we recently added `-best-effort` flags (https://github.com/projectcalico/calico/pull/6240) and it is reflected in the manifests. However manifests for a release are live and not versioned to the 0.0.x releases.

@nitinjagjivan If you are using iptables mode (not ebpf data plane) you can safely remove that init container.

**Comment by mazdakn** [comment]
The fix is available in the coming 'v3.22.4`, `v3.23.2` and 'v3.24` releases. Once these release are available, you can safely use them since the manifests are in sync with these releases.

For the moment, you can remove the `mount-bpffs` init container safely if your are using `iptables` mode. And if you are using `ebpf` mod, you can remove the `-best-effort` flag.

**Comment by mazdakn** [comment]
btw, If you want to pin to a specific patch release manifest, you can get those from the release artefacts attached to each Github release.

**Comment by caseydavenport** [comment]
PRs in flight to remove the offending init container: https://github.com/projectcalico/calico/pull/6259

It will be added back once the next patch release goes out.

**Comment by mazdakn** [comment]
Also PR for removing v3.22 change: https://github.com/projectcalico/calico/pull/6260

**Comment by caseydavenport** [comment]
This should be fixed now as of the above two PRs ^
