### ISSUE TITLE
ARMv7 support for tigera/operator image

### ISSUE THREAD

**Issue by usma0118** [projectcalico/calico#6267]
failed to pull and unpack image "quay.io/tigera/operator:v1.25.9": no match for platform in manifest: not found

## Expected Behavior
Calico and tigera-operator should deploy and run successfully on node

## Current Behavior
pod throws ImagePullBackOff with error detail: failed to pull and unpack image "quay.io/tigera/operator:v1.25.9": no match for platform in manifest: not found

## Steps to Reproduce (for bugs)
1. Setup Ubuntu 22 on Raspberry PI 4b
2. deploy K3s
3. Install Calico
4. Install tigera via https://projectcalico.docs.tigera.io/archive/v3.22/manifests/tigera-operator.yaml

## Context
kube-system pods:
coredns-b96499967-f7c6b                   0/1     Pending
kube-vip-rrd5q                            1/1     Running 
local-path-provisioner-7b7dc8d6f5-9qht6   0/1     Pending 

## Your Environment
* Calico version v1.25.9
* Orchestrator version (e.g. kubernetes, mesos, rkt): k3s
* Operating System and version: Ubuntu 22 runnong on Rasbperry PI 4b (arm64)
* Link to your project (optional):

**Comment by caseydavenport** [comment]
```
docker manifest inspect quay.io/tigera/operator:v1.25.9
{
   "schemaVersion": 2,
   "mediaType": "application/vnd.docker.distribution.manifest.list.v2+json",
   "manifests": [
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 1580,
         "digest": "sha256:82fee701aef83ff305f6e33fd132f9e4b24463aa85015c74cb7615ff36e2ef03",
         "platform": {
            "architecture": "amd64",
            "os": "linux"
         }
      },
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 1368,
         "digest": "sha256:6446f87d0fae54fe223f1a676e47301f0b0262657c05fbba97062e1ad5373620",
         "platform": {
            "architecture": "arm64",
            "os": "linux"
         }
      }
   ]
}
```

^ I get the following when checking the supported architectures for that image. Suspect you might be using something other than AMD64 or ARM64?

**Comment by usma0118** [comment]
hmmm.. this is strange.. I have Ubuntu 22 running on Raspberry Pi 4b.
did architecture check and it returns: armv7l...

**Comment by caseydavenport** [comment]
> armv7l

Yep, the manifest doesn't support that architecture yet it seems. armv7 is a different arch than arm64. 

We'll need to add a new Dockerfile here: https://github.com/tigera/operator/tree/master/build

**Comment by frozenprocess** [comment]
Closing this ticket given Kubernetes dropped armv7 support and we are following the same.
https://github.com/kubernetes/kubernetes/pull/115742
