### ISSUE TITLE
While using calico network on EKS cluster not able to reach Kubernetes default service

### ISSUE THREAD

**Issue by SurRepo** [projectcalico/calico#6272]
While using calico network on EKS cluster not able to reach Kubernetes default service

## Expected Behavior
Kubernetes default service should be reachable from pod 

## Current Behavior
curl -kv https://kubernetes.default.svc.cluster.local
* Could not resolve host: kubernetes.default.svc.cluster.local
* Closing connection 0
curl: (6) Could not resolve host: kubernetes.default.svc.cluster.local
bash-4.4$

## Steps to Reproduce (for bugs)
1. Installed Calico network plugin 
2. Spin up the pod and we have observed IP has been assigned from calico network
3. Login to the pod shell and executed the below statement to check whether kubernetes default service is reachable or not 
4. curl -kv https://kubernetes.default.svc.cluster.local
5. Then we have got the below error and its not reaching to the Kubernetes default service 
Error : * Could not resolve host: kubernetes.default.svc.cluster.local
* Closing connection 0
curl: (6) Could not resolve host: kubernetes.default.svc.cluster.local

6. Also tried nslookup, please find below the output
 / # nslookup https://kubernetes.default.svc.cluster.local
;; connection timed out; no servers could be reached

## Context
Cluster has been created with AWS EKS console.
Has all required traffic allowed in cluster and node security group

* Calico version
v3.23.1

* Orchestrator version (e.g. kubernetes, mesos, rkt):
Eks -1.21

Please help us to resolve the issue.

**Comment by caseydavenport** [comment]
> Error : * Could not resolve host: kubernetes.default.svc.cluster.local

Sounds like your pod is unable to reach core DNS, or there is another DNS issue in the cluster.

First thing would be to share how your cluster is configured - are you using Calico for networking or the AWS VPC CNI plugin w/ Calico for policy-only? 

If you're using Calico networking, are you using IPIP or VXLAN, and have you followed the requirements here: https://projectcalico.docs.tigera.io/getting-started/kubernetes/requirements#network-requirements

For diagnosing, you should try to figure out what packet paths work:
- Can pods talk to pods on their own node?
- Can pods talk to other nodes?
- Can nodes talk to each other? Can they talk to pods on remote nodes?
- Is kube-proxy healthy on the cluster? Can you reach pod IPs directly (rather than via DNS) 

You can also try using tcpdump / traceroute / etc to see how far your pod traffic is getting before it is dropped.

**Comment by SurRepo** [comment]
Hi there thanks for the quick response.
Please find my comment below :
As per my understanding it is DNS issue.

First thing would be to share how your cluster is configured - are you using Calico for networking or the AWS VPC CNI plugin w/ Calico for policy-only?

We are using VXLAN

Can pods talk to pods on their own node?   Yes (using IP)
Can pods talk to other nodes?   Yes (Using IP)
Can nodes talk to each other? Can they talk to pods on remote nodes? Yes (Using IP)
Is kube-proxy healthy on the cluster?  -- Yes 
Can you reach pod IPs directly (rather than via DNS)   -Yes

Regards,
Surajit

**Comment by caseydavenport** [comment]
Sounds like all of those are checking out, so you'll probably want to look into tracing the packets being sent by Calico to see where they are getting dropped, or debugging core DNS since it could possible by a DNS misconfiguration on the cluster rather than a packet routing issue.

**Comment by SurRepo** [comment]
Can you please guide me where & what to check in DNS to solve this issue ?

**Comment by SurRepo** [comment]
Hi Josh,

We can see the timeout issue from Core-DNS saying plugin/error. Please find below

[devadmin@ip-10-85-132-6 cluster.conf]$ kubectl logs -f coredns-844bb8ddf7-4zbn2
[WARNING] plugin/kubernetes: starting server with unsynced Kubernetes API
.:53
[INFO] plugin/reload: Running configuration MD5 = 47d57903c0f0ba4ee0626a17181e5d94
CoreDNS-1.8.4
linux/amd64, go1.13.15, 053c4d5c
[ERROR] plugin/errors: 2 5215155408334832447.5001855525620343658. HINFO: read udp 192.168.189.131:40322->10.85.128.2:53: i/o timeout
[ERROR] plugin/errors: 2 5215155408334832447.5001855525620343658. HINFO: read udp 192.168.189.131:51913->10.85.128.2:53: i/o timeout
[ERROR] plugin/errors: 2 5215155408334832447.5001855525620343658. HINFO: read udp 192.168.189.131:57329->10.85.128.2:53: i/o timeout
[ERROR] plugin/errors: 2 5215155408334832447.5001855525620343658. HINFO: read udp 192.168.189.131:37878->10.85.128.2:53: i/o timeout
[ERROR] plugin/errors: 2 5215155408334832447.5001855525620343658. HINFO: read udp 192.168.189.131:39336->10.85.128.2:53: i/o timeout
[ERROR] plugin/errors: 2 5215155408334832447.5001855525620343658. HINFO: read udp 192.168.189.131:56759->10.85.128.2:53: i/o timeout
[ERROR] plugin/errors: 2 5215155408334832447.5001855525620343658. HINFO: read udp 192.168.189.131:53499->10.85.128.2:53: i/o timeout
[ERROR] plugin/errors: 2 5215155408334832447.5001855525620343658. HINFO: read udp 192.168.189.131:34043->10.85.128.2:53: i/o timeout
[ERROR] plugin/errors: 2 5215155408334832447.5001855525620343658. HINFO: read udp 192.168.189.131:55091->10.85.128.2:53: i/o timeout

**Comment by caseydavenport** [comment]
> [ERROR] plugin/errors: 2 5215155408334832447.5001855525620343658. HINFO: read udp 192.168.189.131:40322->10.85.128.2:53: i/o timeout

Seems to suggest CoreDNS might be having trouble communicating with an upstream DNS server?

**Comment by SurRepo** [comment]
Can you please tell/guide me how to solve this issue ?

**Comment by caseydavenport** [comment]
I can't really resolve this without more investigation on your side - you should figure out why this connection is failing. 

> udp 192.168.189.131:55091->10.85.128.2:53

- Do you have NAToutgoing enabled on your IP pools?
- Can your nodes access 10.85.128.2:53?
- Can your pods access 10.85.128.2:53? If not, where are the packets lost?

**Comment by isatfg** [comment]
@SurRepo did you manage to solve this? I seems to be having a similar issue.
