### ISSUE TITLE
Readiness probe failed: calico/node is not ready: dial unix /var/run/calico/bird.ctl: connect: connection refused

### ISSUE THREAD

**Issue by jokerZhou** [projectcalico/calico#6285]
I work on a kubernetes cluster with 2 nodes:
```
[root@master01 logs]# kubectl get node
NAME       STATUS   ROLES           AGE    VERSION
master01   Ready    control-plane   3h9m   v1.24.2
node01     Ready    <none>          29m    v1.24.2
```

and currently both calico-node pods are running, but are NOT ready. When I inspect logs of this pods the kubemaster constantly reports:

```
  Warning  Unhealthy  <invalid> (x2 over <invalid>)  kubelet            Readiness probe failed: calico/node is not ready: BIRD is not ready: Error querying BIRD: unable to connect to BIRDv4 socket: dial unix /var/run/calico/bird.ctl: connect: connection refused
```
And I also run calicoctl node status on two nodes:

ON master01
```
Calico process is running.
IPv4 BGP status
+---------------+-------------------+-------+----------+-------------+
| PEER ADDRESS  |     PEER TYPE     | STATE |  SINCE   |    INFO     |
+---------------+-------------------+-------+----------+-------------+
| 10.128.62.127 | node-to-node mesh | up    | 08:27:26 | Established |
+---------------+-------------------+-------+----------+-------------+

IPv6 BGP status
No IPv6 peers found.
ON node01
[root@node01 ~]# calicoctl node status
Calico process is running.

IPv4 BGP status
+---------------+-------------------+-------+----------+-------------+
| PEER ADDRESS  |     PEER TYPE     | STATE |  SINCE   |    INFO     |
+---------------+-------------------+-------+----------+-------------+
| 10.128.62.124 | node-to-node mesh | up    | 08:58:03 | Established |
+---------------+-------------------+-------+----------+-------------+

IPv6 BGP status
No IPv6 peers found.
```
It's OK

I try to logs container: 

https://github.com/jokerZhou/calico-report/tree/main

But I have no idea.

**Comment by caseydavenport** [comment]
BIRD appears to be running and established, so a bit surprised to see that the health check can't talk to the socket. 

Does `/var/run/calico/bird.ctl` exist within your calico/node pod?

Do you see this on node01 as well or just the control plane node?

**Comment by jokerZhou** [comment]
> BIRD appears to be running and established, so a bit surprised to see that the health check can't talk to the socket.
> 
> Does `/var/run/calico/bird.ctl` exist within your calico/node pod?
> 
> Do you see this on node01 as well or just the control plane node?

Looks like it's okay,Two nodes can  communicate, But sometime a new node cannot access each other. 
Then they Ping each other so that they can communicate.I have no idea.

**Comment by jokerZhou** [comment]
I  find out the problem,The maintainer opened the ACL of the server and only allowed the communication of the Ministry of molecular networks
