### ISSUE TITLE
Add typha and calico-kube-controllers grafana dashboard

### ISSUE THREAD

**Issue by willzhang** [projectcalico/calico#6286]
why there have no typha and calico-kube-controllers grafana dashboard?

the official docs say typha and calico-kube-controllers have metrics interface, but no grafana dashboard to see this metrics.

https://projectcalico.docs.tigera.io/maintenance/monitor/monitor-component-metrics

## Current Behavior

can not find typha and calico-kube-controllers grafana dashboard in https://grafana.com/grafana/dashboards/

## Possible Solution
give some example grafana dashboard ,it  Not too complicated， just let user see what the metircs is.

## Your Environment

1、helm install prometheus-stack

2、yaml install calico

**Comment by MPV** [comment]
Is this guide sufficient to close this issue?
https://docs.tigera.io/calico/latest/operations/monitor/monitor-component-visual

As there is a dashboard now, over at:
https://github.com/frozenprocess/calico/blob/23ae58b62765b14aa2c5952b2fc6c40155731a79/manifests/grafana-dashboards.yaml

Most recently updated at/in:
- https://github.com/projectcalico/calico/pull/8613

**Comment by caseydavenport** [comment]
Yeah, I think we can close this. I think something that's enabled by default as part of the product would be cool, but is a different ask. Thanks @MPV
