### ISSUE TITLE
Cannot upgrade to v3.23.2

### ISSUE THREAD

**Issue by muff1nman** [projectcalico/calico#6294]
With a typha based setup, upgrading to calico 3.23.2 from 3.22.1 is not possible (at least not without a degradation of the CNI).

## Expected Behavior
1. Upgrade everything except calico-node to 3.23.2
2. Cluster is healthy and calico-node 3.22.1 continues to function 

## Current Behavior
1. Upgrade everything except calico-node (crds, calico-typha, etc) to 3.23.2
2. Calico-node goes unready
3. Networking for newly created pods is not functional

## Speculation
Looking a bit into this it seems part of the problem might be that there might be some incompatible changes in libcalico-go such that typha and calico-node have different views of the world and what is valid. For example here is some log lines from calico-node 3.22.1 after the calico-typha upgrade:
```
    2022-06-28 04:19:15.280 [ERROR][133] felix/sync_proto.go 302: BUG: cannot parse key. key="/calico/resources/v3/projectcalico.org/kubernetesendpointslices/kube-applier-8t5xd"
```
This looks like a potential bug where endpoint slices are no longer being treated as namespaced, potentially fixed with the following:
```
diff --git a/libcalico-go/lib/namespace/resource.go b/libcalico-go/lib/namespace/resource.go
index ebe909024..79e1fade8 100644
--- a/libcalico-go/lib/namespace/resource.go
+++ b/libcalico-go/lib/namespace/resource.go
@@ -39,6 +39,7 @@ func IsNamespaced(kind string) bool {
        case KindKubernetesEndpointSlice:
                // KindKubernetesEndpointSlice is a special-case resource. We don't expose it over the
                // v3 API, but it is used in the felix syncer.
+               return true
        case KindKubernetesService:
                return true
        }
```
However it also looks like KubernetesServices were changed to namespaced so also are not parsed in calico-node 3.22.1 when interacting with typha 3.23.2:  https://github.com/projectcalico/calico/pull/5813/files#diff-0c1fa0f118bec26553d1dbbeb19112f956b9139f8b005d57cfd62b3cd4945c35

There may be more at play here, as I had mainly gravitated to the `BUG` log lines..

## Steps to Reproduce (for bugs)
See expected behavior above.

## Context
- Running with typha
- Upgrade from 3.22.1 to 3.23.2

P.S. Happy to dig up extra details if necessary, but figured this was worth posting sooner rather than later.

**Comment by muff1nman** [comment]
Thanks @caseydavenport . However, I'm not confident that is sufficient on its own. I had tried a patch with just that change and didn't have luck getting calico-node to stay ready (or functional).

**Comment by caseydavenport** [comment]
Gotcha, OK. I'll do some more investigation on this then.

**Comment by stevehipwell** [comment]
Is #6297 as included in v3.23.3 meant to solve this?

**Comment by juliantaylor** [comment]
note the error does not only occur for endpoint slices, e.g:
```
[ERROR][1445608] felix/sync_proto.go 302: BUG: cannot parse key. key="/calico/resources/v3/projectcalico.org/kubernetesservice/namespace/$pod-any-qa"

**Comment by caseydavenport** [comment]
Yep. I was able to reproduce this, and it seems the problem is that the new typha is sending a configuration option that the old Felix doesn't understand.

> 2022-07-21 21:57:01.389 [INFO][1637] felix/config_params.go 496: Ignoring unknown config param. raw name="FloatingIPs"

Is then followed by this log, after receiving its config from Typha:

> 2022-07-21 21:57:01.390 [WARNING][1637] felix/daemon.go 1142: Config change requires restart key="FloatingIPs" new="Disabled" updateType="add"

I would expect a similar (but inverted) situation if running an old Typha and a new Felix. I think the problem comes from us including a CRD-level default on the new FloatingIPs field, so that on upgrade of the CRD the field is automatically populated.

A workaround, as suggested by @sfudeus above, would be to order your upgrade like so:

- Update all of your CRDs, with the exception of FelixConfiguration. 
- Update all of the Calico components to the new version of the code.
- Update the FelixConfiguration CRD to the appropriate one for the new code (v3.23). 

^ It's probably safe to update all of your CRDs after updating the other components, but these steps ensure it's the smallest difference from the standard upgrade procedure.

I'll think on what a proper fix for this might look like.

**Comment by caseydavenport** [comment]
> Is https://github.com/projectcalico/calico/pull/6297 as included in v3.23.3 meant to solve this?

Yeah, this was definitely a bug but ultimately not the only upgrade related issue around this time...,

**Comment by stevehipwell** [comment]
@caseydavenport unfortunately the suggested workaround isn't an option for us, our automation makes the assumption (correctly IMHO) that CRDS need updating before components are updated. I thought the whole point of deploying components via a K8s operator is the fact that the operator can engineer around things like this so the end user doesn't have to worry about them?

On a slight tangent, is there not E2E automation specifically to catch issues like this on upgrading between versions?

**Comment by caseydavenport** [comment]
> unfortunately the suggested workaround isn't an option for us, our automation makes the assumption (correctly IMHO) that CRDS need updating before components are updated

Yep understood. You can also simply remove the "FloatingIPs" field from the CRD that you are installing, if that's an option.

>  I thought the whole point of deploying components via a K8s operator is the fact that the operator can engineer around things like this so the end user doesn't have to worry about them?

It is. In this case, we missed this upgrade issue and we don't generally manage the CRDs via the operator (for various reasons) so we don't have ordering logic. We aim to ensure there is no ordering requirement to install CRDs like the workaround above.

> On a slight tangent, is there not E2E automation specifically to catch issues like this on upgrading between versions?

I thought that we did. I will follow up with our test expert, @lwr20, to see why this wasn't detected.

**Comment by caseydavenport** [comment]
Removing the defaulting is actually all that should be needed, e.g., this PR: https://github.com/projectcalico/calico/pull/6415

**Comment by stevehipwell** [comment]
Thanks for the details and workaround @caseydavenport!

**Comment by muff1nman** [comment]
I believe this needs to be reopened as I'm finding that #6415 is not sufficient, still seeing `BUG` lines like:

```
2022-08-30 23:06:56.288 [WARNING][987185] felix/keys.go 229: (BUG) Path is a namespaced resource, but resource is global: /calico/resources/v3/projectcalico.org/kubernetesservice/sync/kube-applier
2022-08-30 23:06:56.288 [ERROR][987185] felix/sync_proto.go 302: BUG: cannot parse key. key="/calico/resources/v3/projectcalico.org/kubernetesservice/sync/kube-applier"
2022-08-30 23:06:56.295 [WARNING][987185] felix/keys.go 229: (BUG) Path is a namespaced resource, but resource is global: /calico/resources/v3/projectcalico.org/kubernetesservice/redis-testing/cluster-2
2022-08-30 23:06:56.295 [ERROR][987185] felix/sync_proto.go 302: BUG: cannot parse key. key="/calico/resources/v3/projectcalico.org/kubernetesservice/redis-testing/cluster-2"
```

**Comment by muff1nman** [comment]
Okay so the good news is that the catastrophic failure originally observed is now fixed and can confirm that was fixed by the defaulting CRD field. Also good news is that endpoint slices are not in the `BUG` log lines which I presume means they are getting reconciled. I believe `kubernetesservices` are expected to not be reconciled correctly until both components are running the same version and I believe this is harmless if I'm understanding https://github.com/projectcalico/calico/pull/5813 correctly. 

So with that I believe this can be closed, but will be proving this out shortly with some clusters.

**Comment by caseydavenport** [comment]
That sounds right to me - I'll leave this open until you get a chance to prove it, though!

**Comment by muff1nman** [comment]
Proved it out on at least one cluster, ran into what I think are unrelated  issues though. Will raise separately.
