### ISSUE TITLE
Include the release date on our release pages

### ISSUE THREAD

**Issue by neiljerram** [projectcalico/calico#630]
For example, in http://docs.projectcalico.org/v2.1/releases/.

TBD whether we just make this happen for future releases, or if it's worth also adding the dates to past releases.

**Comment by djosborne** [comment]
Let's add a note to RELEASING.md to disclose this new policy.

**Comment by djosborne** [comment]
I'm going to milestone the "do this for future releases" part of this for v2.2. 

Doing this for past releases doesn't necessarily need to be done in time for v2.2.

**Comment by djosborne** [comment]
I'm going to open a new issue for back-applying to past releases.
