### ISSUE TITLE
calico-apiserver pod won't start Error: unknown shorthand flag: 'v' in -v=5

### ISSUE THREAD

**Issue by jsalatiel** [projectcalico/calico#6319]
Following https://projectcalico.docs.tigera.io/maintenance/install-apiserver won't work.
The pod will never start. Crash loop back
The log shows:
```
Version:      v3.23.2
Build date:   2022-06-24T17:06:31+0000
Git tag ref:  v3.23.2
Git commit:   a52cb86db
Error: unknown shorthand flag: 'v' in -v=5
Usage:
   [flags]

Flags:

...


E0705 13:11:46.003843       1 apiserver.go:53] server exited unexpectedly (unknown shorthand flag: 'v' in -v=5)
```

**Comment by jsalatiel** [comment]
Manifest

**Comment by caseydavenport** [comment]
For now, you can simply remove the line with `        - -v=5`.

Looks like we'll need to fix that manifest, and perhaps investigate why the verbosity option was removed.

**Comment by cyclinder** [comment]
I'd take this one, Can I have this?
