### ISSUE TITLE
Improve documentation about failsafeInboundHostPorts

### ISSUE THREAD

**Issue by lightyou** [projectcalico/calico#6329]
In https://projectcalico.docs.tigera.io/reference/resources/felixconfig the paragraph about failsafeInboundHostPorts tells about a list of protocol/port or protocol/CIDR/port but no example of syntax with CIDR can be found.

## Expected Behavior
The message in the code when the configuration is wrong is
ports should be <protocol>:<net>:<number> or <protocol>:<number> or <number>
This precision should be added to the documentation

## Current Behavior
Have to go through the code to find how to use failsafeInboundHostPorts  with CIDR

## Possible Solution
Update the documenatation

## Steps to Reproduce (for bugs)
NA

## Context
NA

## Your Environment
Using calico in kubernetes with the need to disable failsafe rules (but total disable prevent calico-apiserver to start, so the need to ass specific failsafe rules, but his is another story ;)

**Comment by Scott-Wenzel** [comment]
Documentation on how to disable all failsafe rules needs to be improved.  Per instructions "The lists of failsafe ports can be configured via the configuration parameters FailsafeInboundHostPorts and FailsafeOutboundHostPorts described in [Configuring Felix](https://projectcalico.docs.tigera.io/reference/felix/configuration). They can be disabled by setting each configuration value to “none”."   But when I specify failsafeInboundHostPorts: none, I get [ValidationError(FelixConfiguration.spec.failsafeInboundHostPorts): invalid type for org.projectcalico.crd.v1.FelixConfiguration.spec.failsafeInboundHostPorts: got "string", expected "array",

**Comment by frozenprocess** [comment]
I've added a couple of corrections and content to address this ticket.
Please feel free to re open it if you feel like something is missing.
