### ISSUE TITLE
Typha issues after upgrading from v3.22.1 to v3.23.2

### ISSUE THREAD

**Issue by blakqq** [projectcalico/calico#6336]
Typha pods won't come up after upgrade of typha and node, and spit out the following message - Failed to perform list of current data during resync ListRoot="/calico/resources/v3/projectcalico.org/kubernetesendpointslices" error=resource does not exist

## Possible Solution

Assumption is that it _could_ be something to do with the ClusterRole RBAC rules but I've not had any luck so far.

## Steps to Reproduce (for bugs)

Upgrading from v3.22.1 to v3.23.2.

## Your Environment

* Calico version v3.23.2
* Orchestrator version (e.g. kubernetes, mesos, rkt): kubernetes (EKS)

**Comment by caseydavenport** [comment]
Yeah, I suspect it is. The EndpointSlice v1beta1 API was removed in Kubernetes v1.21 IIRC, at which point only the v1 API remained. 

You can check which version of the API is being served on your cluster with this:

```
kubectl api-resources | grep endpointslice
```

If you see a v1beta1 version present, but no v1 version present, that's the issue.

**Comment by blakqq** [comment]
> 

I don't see any versions. When I run the suggested command I receive the below;
`endpointslices                                 discovery.k8s.io               true         EndpointSlice`

When I run `kubectl describe endpointslices`, I get;
```
Name:         kubernetes
Namespace:    default
Labels:       kubernetes.io/service-name=kubernetes
Annotations:  <none>
AddressType:  IPv4
Ports:
  Name   Port  Protocol
  ----   ----  --------
  https  443   TCP
Endpoints:
  - Addresses:  <removed>
    Conditions:
      Ready:    true
    Hostname:   <unset>
    Topology:   <none>
  - Addresses:  <removed>
    Conditions:
      Ready:   true
    Hostname:  <unset>
    Topology:  <none>
Events:        <none>
```

Sorry, I'm probably doing something silly - any pointers?

**Comment by caseydavenport** [comment]
Sorry, that's my bad for giving you the wrong command from memory :sweat_smile: 

This should do the trick:

```
kubectl api-versions | grep discovery
```

Alternatively, 

```
kubectl get endpointslices -o yaml | grep apiVersion
```

^ The latter will only tell you what version is _preferred_, if your cluster supports both.

**Comment by blakqq** [comment]
@caseydavenport That's done it, definitely the issue. Thank you very much!
