### ISSUE TITLE
Calico workload communication broken when IPTables service is enabled

### ISSUE THREAD

**Issue by svallala** [projectcalico/calico#6342]
## Expected Behavior
Calico Workload communication should work when IP tables service is enabled

## Current Behavior
We were earlier using Calico v3.12.3 and things were working fine when the IP tables service is enabled. The last rule "Policy explicitly accepted packet" is configured in the cali-FORWARD chain

[root@qct-23 ~]# iptables -S cali-FORWARD
-N cali-FORWARD
-A cali-FORWARD -m comment --comment "cali:vjrMJCRpqwy5oRoX" -j MARK --set-xmark 0x0/0xe0000
-A cali-FORWARD -m comment --comment "cali:A_sPAO0mcxbT9mOV" -m mark --mark 0x0/0x10000 -j cali-from-hep-forward
-A cali-FORWARD -i cali+ -m comment --comment "cali:8ZoYfO5HKXWbB3pk" -j cali-from-wl-dispatch
-A cali-FORWARD -o cali+ -m comment --comment "cali:jdEuaPBe14V2hutn" -j cali-to-wl-dispatch
-A cali-FORWARD -m comment --comment "cali:12bc6HljsMKsmfr-" -j cali-to-hep-forward
-A cali-FORWARD -m comment --comment "cali:MH9kMp5aNICL-Olv" -m comment --comment "Policy explicitly accepted packet." -m mark --mark 0x10000/0x10000 -j ACCEPT

We upgraded to Calico v3.21.5 and pod-to-pod communication is broken when IP tables service is enabled. In the cali-FORWARD chain, don't see the last rule, instead, it is at the end of the FORWARD chain after the icmp-host-prohibited rule enforced by the IPTables service.

[root@centos-60-219 ~]# iptables -S FORWARD
-P FORWARD ACCEPT
-A FORWARD -m comment --comment "cali:wUHhoiAYhphO9Mso" -j cali-FORWARD
-A FORWARD -m comment --comment "kubernetes forwarding rules" -j KUBE-FORWARD
.
.
.
-A FORWARD -j REJECT --reject-with icmp-host-prohibited
-A FORWARD -m comment --comment "cali:S93hcgKJrXEqnTfs" -m comment --comment "Policy explicitly accepted packet." -m mark --mark 0x10000/0x10000 -j ACCEPT
-A FORWARD -m comment --comment "cali:mp77cMpurHhyjLrM" -j MARK --set-xmark 0x10000/0x10000

## Possible Solution
If we add a rule to ACCEPT packets with the mark 0x10000/0x10000 above the ICMP reject rule then things are working fine. Is this change in behavior intentional, do we explicitly enable packets with this mark?

### Your Environment
Calico: v3.21.5
Kubernetes: v1.23.1

**Comment by caseydavenport** [comment]
Yes, this change is expected and was introduced in this PR: https://github.com/projectcalico/felix/pull/2424 in order to resolve this issue: https://github.com/projectcalico/calico/issues/3901

As part of the release note for that release:

> if you have your own rules in that chain then please check that they do not drop or reject pod traffic before it reaches the ACCEPT rule.

So you probably just need to remove that reject rule.

**Comment by svallala** [comment]
@caseydavenport thanks for the response. IPTables service by default has this reject rule in its configuration to lock down the node. So with this change, out of the box, Calico pod communication will not work with IPtables service.

Removing the reject will be a security concern, to detect the pod traffic accepting packets with the specified match would be enough?

[root@centos-60-219 ~]# iptables -S ROBIN-CALICO-WL
-N ROBIN-CALICO-WL
-A ROBIN-CALICO-WL -m comment --comment "Calico workload traffic" -m mark --mark 0x10000/0x10000 -j ACCEPT

Thanks
Shravan

**Comment by lmm** [comment]
I'm going to close this issue for now since there hasn't been any activity in a while. Please feel free to reopen if you have more questions, thanks!
