### ISSUE TITLE
Cleanup Kubernetes Manifest story

### ISSUE THREAD

**Issue by ozdanborne** [projectcalico/calico#635]
Kubernetes 1.6 brings subtle changes to the API. We need to ensure our YAML's are forwards compabitle or start maintaining separate ones depending on the k8s version.

This issue is to track that work.

The following tables covers all existing install Yamls, ignoring RBAC / ABAC requirements:

| Yaml File | Description | k8s-1.5 compatibility | k8s-1.6 compatibility | Docs |
|---------------|---------------|--------------------|--------------------|---------|
| `calico.yaml` | Regular install | Yes | Yes | Need to mention dual support |
| `kubeadm/calico.yaml` | Kubeadm for 1.5| Yes | No (tolerations) | Needs confirmation of good UX | |
| `kubeadm/1.6/calico.yaml` | Kubeadm for 1.6 | No (tolerations) | Yes | Needs confirmation of good UX | Done |
| `k8s-backend/calico.yaml` | K8s backend |  | | |
| [`k8s-backend-addon-manager/calico-daemonset.yaml`](https://github.com/projectcalico/calico/blob/master/v2.0/getting-started/kubernetes/installation/hosted/k8s-backend-addon-manager/calico-daemonset.yaml) | Addon-Manager + k8s-backend | | |
| `canal.yml` | standard canal install |
| `kubeadm/canal.yml` | canal for kubeadm | Yes | No |
| `kubeadm/1.6/canal.yml` | canal for kubeadm | No | Yes |

**Comment by djosborne** [comment]
- what happens if abac is enabled and rbac roles are provided

**Comment by djosborne** [comment]
### Authorization Method
#### None
- [Question] Can we create serviceaccounts and assign them to pods even when auth=None? Can we reasonably impose the requirement that the cluster must support serviceaccounts?
  - Answer: Yes, and therefore, Yes

#### RBAC
- Podspecs need to include  `serviceAccountName: calico-xyz`
- Need to create `ServiceAccount` objects
- Need to also create `ClusterRole` and `ClusterRoleBinding` objects

#### ABAC
- Podspecs need to include `serviceAccountName: calico-xyz` 
- Need to create `ServiceAccount`
- Instruct user which json to add to their `--authorization-policy-files=$SOME_FILENAME`

### Launch Method
#### Kubectl

#### Addon-Manager
- Mostly the same, but ConfigMap is served separately so operators can launch that piece manually
- Also k8s-policy-controller is missing but maybe that's a bug?

### Tolerations
- Toleration declaration incompatible between k8s-1.5 and k8s-1.6
- Some clusters will have taints.
  - We are aware of some of the common ones, e.g. Kubeadm's required ones

### Backend
[Proposal] Give instructions to user on how to modify this.

#### existing etcd
- set `etcd_endpoints` in yaml
- set certs as necessary

#### Own Etcd (Alpha)
Needed for kubeadm
- Launch additional `etcd` pod and service
- set `etcd_endpoints` to that service IP in yaml
- [Question] Do we add cert support?

#### K8s
- Set `"policy": {"type":"k8s"}` in `cni_network_config` in `calico-config`
- [Proposal] Move that^ into a configmap field as a flag, template it into the rest of the yaml automatically?

### Networking Option
#### Flannel (Canal)
- [Todo]

#### Not Flannel
- [Todo]

### Authentication
#### None
#### TLS

Current manifests put TLS options which default empty.

## Conclusions
- [ ] add `serviceAccountName` and `serviceAccount` objects to all base calico yamls.
- [ ] Move `ClusterRole` and `ClusterRoleBinding` into a `rbac.yml`
- [ ] Create list of ABAC json policies (documentation or hosted json file)
- [ ] Move configmap into a separate yaml files
- [ ] move datastore selection into a configmap variable
  - [ ] teach other components how to template interpretation
-

Other tidbits:
- [x] Check regular calico install works for 1.6
- [ ] Add links on docs to compiled yaml (for convenience) (#636)

**Comment by djosborne** [comment]
## Proposed UX for a User

1. Configure Calico. Create your calico-config.yml
  1. What are you using for etcd?
    1. Own etcd? change `etcd_endpoints` in the configmap
    2. Roll own etcd (kubeadm)? change `etcd_endpoints` to `http://10.96.232.136:6666` and launch `calico-etcd.yml`
    3. k8s backend? change `backend` to `none`
2. Authorize Calico. 
    1. What are you using for auth?
        1. If auth=none, skip this step
        2. If using RBAC, `kubectl apply -f calico-rbac.yml`
        3. If using ABAC, add these lines to your json: xxxxxx
3. Launch calico.
  a. If using addon-manager, `mv calico.yml dest.yml`
  b. Otherwise, `kubectl apply -f calico.yml`

## Necessary Changes
- [ ] add `serviceAccountName` and `serviceAccount` objects to all base calico yamls.
- [ ] Move `ClusterRole` and `ClusterRoleBinding` into a `rbac.yml`
- [ ] Create list of ABAC json policies (documentation or hosted json file)
- [ ] Move configmap into a separate yaml files. Maintain a separate one for each deployment. For example:
  - [ ] a kubeadm-config.yml where `etcd_endpoints` is set to the etcd service ip
  - [ ] a regular config.yml where `etcd_endpoints` is set to `localhost:2379`
- [ ] move datastore selection into a configmap variable
  - [ ] teach other components how to template interpretation
- [ ] Add tolerations to all components, deprecate 1.5 yamls



Other tidbits:
- [x] Check regular calico install works for 1.6
- [ ] Add links on docs to compiled yaml (for convenience) (#636)

**Comment by caseydavenport** [comment]
@djosborne I think a lot of what you're suggesting here goes beyond just how do we support Kubernetes v1.6 (but I could be wrong).

I thought there were just two parts to this:
- Add RBAC to the kubeadm manifest
- Include a v1.6 manifest that uses the new tolerations fields rather than annotations.
