### ISSUE TITLE
Error during migration from manifest to operator : node affinity not supported for calico-node daemonset

### ISSUE THREAD

**Issue by keliansb** [projectcalico/calico#6357]
## Description
I get an error when I try to migrate Calico from manifest to an operator-managed installation following [this procedure](https://projectcalico.docs.tigera.io/maintenance/operator-migration). 
```
root@<node_name>:~# kubectl describe tigerastatus calico
Name:         calico
Namespace:
Labels:       <none>
Annotations:  <none>
API Version:  operator.tigera.io/v1
Kind:         TigeraStatus
Metadata:
  Creation Timestamp:  2022-07-11T10:02:48Z
  Generation:          1
  Managed Fields:
    API Version:  operator.tigera.io/v1
    Fields Type:  FieldsV1
    fieldsV1:
      f:spec:
      f:status:
        .:
        f:conditions:
    Manager:         operator
    Operation:       Update
    Time:            2022-07-11T10:02:53Z
  Resource Version:  281989278
  UID:               567b3b6b-d4d6-4c2b-aecc-a79211de2cba
Spec:
Status:
  Conditions:
    Last Transition Time:  2022-07-11T10:02:53Z
    Message:               node affinity not supported for calico-node daemonset. To fix it, remove the affinity on daemonset/calico-node
    Reason:                Existing Calico installation can not be managed by Tigera Operator as it is configured in a way that Operator does not currently support. Please update your existing Calico install config
    Status:                True
    Type:                  Degraded
Events:                    <none>
```

## Possible Solution

Possible solution (suggested in the message) would be to remove the affinity on the daemonset calico-node, but the following note is indicated on the procedure :
> Do not edit or delete any resources in the kube-system Namespace during the following procedure as it may interfere with the upgrade.

The following affinity is set on the daemonset calico-node :
```
affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/os
          operator: In
          values:
          - linux
```

## Steps to Reproduce (for bugs)

Use [this procedure](https://projectcalico.docs.tigera.io/maintenance/operator-migration) to migrate from manifest to an operator-managed installation.

## Your Environment

* Calico version: **3.23.2**
* Orchestrator version (e.g. kubernetes, mesos, rkt): **Kubernetes 1.21.5**
* Operating System and version: **Ubuntu 20.04 LTS**

**Comment by Josh-Tigera** [comment]
We don't support custom affinities within the operator so you'll need to remove it to make the upgrade successful. The warning message regarding not modifying resources in the kube-system Namespace during the upgrade procedure is very literal so you can modify the resource prior to the upgrade procedure safely. Give this a shot and let us know if you run into any further issues.

**Comment by caseydavenport** [comment]
@lmm is in the process of adding support for custom affinities by the way, so this limitation will go away in the near future. @lmm can comment more.

**Comment by caseydavenport** [comment]
Tracked here I believe https://github.com/tigera/operator/issues/1990

**Comment by keliansb** [comment]
In fact I opened this issue because I don't think I put any affinity on the daemonset, I think it was set by Calico during the deployment or upgrades via manifests at some point (the cluster is about a year and a half old).
Anyway, I will try to remove this affinity and start the upgrade process again, thanks @Josh-Tigera.

**Comment by keliansb** [comment]
I was able to migrate correctly after removing the affinity, thanks for your help!
