### ISSUE TITLE
Nodes are still in Not Ready state after installing calico operator

### ISSUE THREAD

**Issue by ali-alhajj98** [projectcalico/calico#6369]
I recently installed the calico operator in my cluster as a CNI but things didn't change as expected.
## Expected Behavior

Master and worker nodes should be in ready state now but they aren't.
## Steps to Reproduce (for bugs)

1. I installed calico operator as in this link [https://projectcalico.docs.tigera.io/getting-started/kubernetes/self-managed-onprem/onpremises]
2. Edited the custom-resources.yaml file to change the cidr to the one i used in the kubeadm init command.
3. Output of some commands after installing the operator without any errors:
$ kubectl get ns
NAME              STATUS   AGE
calico-system     Active   12m
default           Active   3h31m
kube-node-lease   Active   3h31m
kube-public       Active   3h31m
kube-system       Active   3h31m
tigera-operator   Active   12m

$ kubectl get all -n calico-system
NAME                   TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)    AGE
service/calico-typha   ClusterIP   10.102.239.176   <none>        5473/TCP   12m

$ kubectl get all -n tigera-operator
NAME                                  READY   STATUS    RESTARTS   AGE
pod/tigera-operator-d8cbfddcc-lwqmg   1/1     Running   0          13m
NAME                              READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/tigera-operator   1/1     1            1           13m
NAME                                        DESIRED   CURRENT   READY   AGE
replicaset.apps/tigera-operator-d8cbfddcc   1         1         1       13m

$ kubectl get all -n kube-system
NAME                                   READY   STATUS      RESTARTS   AGE
pod/coredns-f9fd979d6-9scgz            0/1     Completed   9          3h32m
pod/coredns-f9fd979d6-t7rw4            0/1     Completed   2          3h32m
pod/kube-apiserver-master-1            1/1     Running     26         3h32m
pod/kube-apiserver-master-2            1/1     Running     28         3h30m
pod/kube-apiserver-master-3            1/1     Running     29         3h30m
pod/kube-controller-manager-master-1   1/1     Running     15         3h32m
pod/kube-controller-manager-master-2   1/1     Running     12         3h30m
pod/kube-controller-manager-master-3   1/1     Running     11         3h30m
pod/kube-proxy-2pbhh                   1/1     Running     6          3h28m
pod/kube-proxy-5d88h                   1/1     Running     11         3h30m
pod/kube-proxy-6gmhg                   1/1     Running     6          3h28m
pod/kube-proxy-6vpz4                   1/1     Running     7          3h29m
pod/kube-proxy-8fnrg                   1/1     Running     6          3h29m
pod/kube-proxy-jzhr8                   1/1     Running     10         3h32m
pod/kube-proxy-mdxhk                   1/1     Running     6          3h28m
pod/kube-proxy-mfjm5                   1/1     Running     11         3h30m
pod/kube-scheduler-master-1            1/1     Running     15         3h32m
pod/kube-scheduler-master-2            1/1     Running     12         3h30m
pod/kube-scheduler-master-3            1/1     Running     11         3h30m

NAME               TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)                  AGE
service/kube-dns   ClusterIP   10.96.0.10   <none>        53/UDP,53/TCP,9153/TCP   3h32m

NAME                        DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR            AGE
daemonset.apps/kube-proxy   8         8         8       8            8           kubernetes.io/os=linux   3h32m

NAME                      READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/coredns   0/2     2            0           3h32m

NAME                                DESIRED   CURRENT   READY   AGE
replicaset.apps/coredns-f9fd979d6   2         2         0       3h32m

LOGS of tigera-operator pod:

"logger":"controller_installation","msg":"Error creating / updating resource","Request.Namespace":"","Request.Name":"default","error":"no matches for kind \"PodDisruptionBudget\" in version \"policy/v1\"","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.7/pkg/internal/controller/controller.go:253\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.7/pkg/internal/controller/controller.go:214"}
{"level":"error","ts":1657627669.905982,"logger":"controller.tigera-installation-controller","msg":"Reconciler error","name":"default","namespace":"","error":"no matches for kind \"PodDisruptionBudget\" in version \"policy/v1\"","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.7/pkg/internal/controller/controller.go:214"}
{"level":"info","ts":1657627671.7782376,"logger":"status_manager.calico","msg":"Status manager is not ready to report component statuses."}

## Your Environment

* Calico version latest as in the link provided
* Orchestrator version (e.g. kubernetes, mesos, rkt): k8s v1.19
* Operating System and version:
* Link to your project (optional):

**Comment by ali-alhajj98** [comment]
I installed flannel instead of calico and worked.

**Comment by tmjd** [comment]
I think the version of kubernetes needed to be updated to a version that supports the v1 API for PodDisruptionBudget. The current  [system requirements](https://projectcalico.docs.tigera.io/getting-started/kubernetes/requirements) for Calico 3.23 show that the latest version of Calico supports K8s 1.21-1.23.
I'm mentioning this in case others come across this issue.
