### ISSUE TITLE
Calico-node does not check vxlan.calico interface whether it is correctly configured

### ISSUE THREAD

**Issue by ArenaSu** [projectcalico/calico#6383]
## Expected Behavior

vxlan.calico interface transport pod's packet correctly.

## Current Behavior

Ping pod ip and no reply. And find vxlan.calico interface does not transport pod's packet correctly to caliXXXX via tcpdump tool.

## Possible Solution

The reason is that vxlan.calico interface was left when removing node from cluster via kube-spray. So vxlan.calico interface  was still existed after uninstalling cluster B and cluster C. And calico-node does not check vxlan.calico interface whether it is correctly configured. The vxlan.calico interface is in error state and does not transport pod's packet correctly.

My solution:
1. Remove nodes (node 4 ~9) from cluster A via kubespray.
2. Delete vxlan.calico interface on nodes (node 4 ~9)  manually.
3. Re-add nodes (node 4 ~9) to cluster A.
4. Everything is OK.

More details look up slack messages: https://calicousers.slack.com/archives/CPEPF833L/p1657876482761339

## Steps to Reproduce (for bugs)

1. Install kubernetes cluster A containing 3 nodes(1 master 2 workers) via kubespray.
2. Install kubernetes cluster B containing 2 nodes(1 master 1 workers) via kubespray.
6.  Install kubernetes cluster C containing 4 nodes(1 master 3 workers) via kubespray.
7. Uninstall cluster B and cluster C (reset cluster via kubespray ansible command).
8. Re-add nodes that belonged to cluster B and C before to cluster A.
9. Ping pods between nodes (node 1 ~3) that belonged to cluster A in the beginning and the result is ok.
10. Ping pods on nodes (node 4 ~9) that belonged to cluster B and C and the result is failed.

## Context

```
ping (on node ai-01-node1) pod ip 10.233.88.5 (on ai-01-node4) and tcpdump result:

icmp packet -> ai-01-node1 vxlan.calico [ok] -> ai-01-node4 vxlan.calico [ok] ->[failed] cali7e051bba08e (route info)

-----------
ping (on ai-01-node4) pod ip 10.233.88.5 (on ai-01-node4) and tcpdump result:

icmp packet -> cali7e051bba08e (route info)  [ok] 

```

calico-node on  ai-01-node4 has no error logs.

## Your Environment

* Calico version: v3.21.4
* Orchestrator version (e.g. kubernetes, mesos, rkt): kubernetes v1.23.4
* Operating System and version: Centos 7.9
* Link to your project (optional):

**Comment by lwr20** [comment]
There's not enough information here to diagnose this.  Perhaps come to the calico slack: https://slack.projectcalico.org/

**Comment by lwr20** [comment]
If slack's not an option, can you show me the output of `kubectl get no -o yaml`, `kubectl get ippools -o yaml` please?

Also - what's the environment?  on-prem, cloud?  Which cloud?

**Comment by ArenaSu** [comment]
> If slack's not an option, can you show me the output of `kubectl get no -o yaml` (maybe redact routeable IPs), `kubectl get ippools -o yaml` please?
> 
> Also - what's the environment? on-prem, cloud? Which cloud?

```
[root@ai-01-node1 ~]# kubectl get nodes -o wide
NAME          STATUS   ROLES                  AGE   VERSION   INTERNAL-IP    EXTERNAL-IP   OS-IMAGE                KERNEL-VERSION           CONTAINER-RUNTIME
ai-01-node1   Ready    control-plane,master   34d   v1.23.4   10.19.32.38    <none>        CentOS Linux 7 (Core)   3.10.0-1160.el7.x86_64   docker://20.10.11
ai-01-node2   Ready    <none>                 34d   v1.23.4   10.19.32.39    <none>        CentOS Linux 7 (Core)   3.10.0-1160.el7.x86_64   docker://20.10.11
ai-01-node3   Ready    <none>                 34d   v1.23.4   10.1.251.151   <none>        CentOS Linux 7 (Core)   3.10.0-1160.el7.x86_64   docker://20.10.11
ai-01-node4   Ready    <none>                 29h   v1.23.4   10.19.32.40    <none>        CentOS Linux 7 (Core)   3.10.0-1160.el7.x86_64   docker://20.10.11
ai-01-node5   Ready    <none>                 29h   v1.23.4   10.19.90.76    <none>        CentOS Linux 7 (Core)   3.10.0-1160.el7.x86_64   docker://20.10.11
ai-01-node6   Ready    <none>                 29h   v1.23.4   10.19.32.184   <none>        CentOS Linux 7 (Core)   3.10.0-1160.el7.x86_64   docker://20.10.11
ai-01-node7   Ready    <none>                 29h   v1.23.4   10.19.32.181   <none>        CentOS Linux 7 (Core)   3.10.0-1160.el7.x86_64   docker://20.10.11
ai-01-node8   Ready    <none>                 29h   v1.23.4   10.19.32.182   <none>        CentOS Linux 7 (Core)   3.10.0-1160.el7.x86_64   docker://20.10.11
ai-01-node9   Ready    <none>                 29h   v1.23.4   10.19.32.183   <none>        CentOS Linux 7 (Core)   3.10.0-1160.el7.x86_64   docker://20.10.11

# kubectl get ippools -o yaml
apiVersion: v1
items:
- apiVersion: crd.projectcalico.org/v1
  kind: IPPool
  metadata:
    annotations:
      projectcalico.org/metadata: '{"uid":"40f1bc3e-a8b7-47ee-a9b4-fe939100c335","creationTimestamp":"2022-06-10T10:31:39Z"}'
    creationTimestamp: "2022-06-10T10:31:39Z"
    generation: 1
    name: default-pool
    resourceVersion: "863"
    uid: 7ac8e6d1-2924-490a-89f9-ded158f1314a
  spec:
    allowedUses:
    - Workload
    - Tunnel
    blockSize: 24
    cidr: 10.233.64.0/18
    ipipMode: Never
    natOutgoing: true
    nodeSelector: all()
    vxlanMode: Always
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
```

**Comment by lwr20** [comment]
For anyone finding this later, as a workaround, delete the `vxlan.calico` interface.  That should cause calico to re-create it correctly.
