### ISSUE TITLE
K8s NodePort Service can only be accessed locally but not externally when using eBPF dataplane

### ISSUE THREAD

**Issue by TrevorTaoARM** [projectcalico/calico#6392]
## Expected Behavior
I enabled eBPF dataplane, and installed a k8s service with a backend Nginx pod, the yaml file is like:
apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    name: http
    nodePort: 30942
  selector:
    app: nginx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
        role: backend
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80

I can access node port service from the 2 k8s nodes(including the master) locally, which IPs are 10.169.208.204 and 10.169.208.233(the master, tainted), but when I accesses the nodePort service from other servers(10.169.208.229,...), the service can't  be accessed:
1. For node 10.169.208.204, the result is :
curl 10.169.208.204:30942
curl: (7) Failed to connect to 10.169.208.204 port 30942: Connection refused
The tcpdump result here:
![image](https://user-images.githubusercontent.com/29970645/179480676-c1ab4fff-3df6-40ec-a948-33d41de7532e.png)

2. For node 10.169.208.233, the result is:
curl 10.169.208.233:30942
curl: (7) Failed to connect to 10.169.208.233 port 30942: Connection timed out
![image](https://user-images.githubusercontent.com/29970645/179480791-f4244fdf-393c-49a8-bb3a-513bf5a86c80.png)

When I disabled the eBPF and restored the Kube-proxy, the nodePort service here can be accessed normally.

## Steps to Reproduce (for bugs)

The script to enable eBPF dataplane:
k8s_ep=$(kubectl get endpoints kubernetes -o wide | grep kubernetes | cut -d " " -f 4)
k8s_host=$(echo $k8s_ep | cut -d ":" -f 1)
k8s_port=$(echo $k8s_ep | cut -d ":" -f 2)

cat <<EOF > ${WORKDIR}/k8s_service.yaml
kind: ConfigMap
apiVersion: v1
metadata:
  name: kubernetes-services-endpoint
  namespace: kube-system
data:
  KUBERNETES_SERVICE_HOST: "__KUBERNETES_SERVICE_HOST__"
  KUBERNETES_SERVICE_PORT: "__KUBERNETES_SERVICE_PORT__"
EOF

sed -i "s/__KUBERNETES_SERVICE_HOST__/${k8s_host}/" ${WORKDIR}/k8s_service.yaml
sed -i "s/__KUBERNETES_SERVICE_PORT__/${k8s_port}/" ${WORKDIR}/k8s_service.yaml

kubectl apply -f ${WORKDIR}/k8s_service.yaml

echo "Disable kube-proxy:"
kubectl patch ds -n kube-system kube-proxy -p '{"spec":{"template":{"spec":{"nodeSelector":{"non-calico": "true"}}}}}'

echo "Enable eBPF:"
calicoctl patch felixconfiguration default --patch='{"spec": {"bpfEnabled": true}}'

echo "Enable Direct Server Return(DSR) mode: optional"
#calicoctl patch felixconfiguration default --patch='{"spec": {"bpfExternalServiceMode": "DSR"}}'
## Your Environment

* Calico version  v3.23.2, v3.23.1(also)
* * Orchestrator version (e.g. kubernetes, mesos, rkt): k8s 1.22.1
* Operating System and version:  Ubuntu 20.04, arm64
* Link to your project (optional):

`

`

**Comment by caseydavenport** [comment]
This would be one for @tomas-mazak, though I believe he's out for a few days.

**Comment by lwr20** [comment]
I think @caseydavenport should have pinged @tomastigera

**Comment by caseydavenport** [comment]
Yep you're absolutely correct. :facepalm:

**Comment by tomastigera** [comment]
I do not quite follow what is the problem. It seems like when you are trying to access the nodeport from either of the 2 k8s node, you get a failure. Or am I reading it just wrong and you mean that if you access from say `10.169.208.229` to either of the two nodes you get these 2 different errors? I think that is what you meant.

Is the actuall pod running?

What is the output from `kubectl exec calico-node-xyz -n calico-system -- calico-node -bpf nat dump` for both of the nodes?

**Comment by tomastigera** [comment]
Could you also set `BPFLogLevel` felix config to `Debug` and get us output from `tc exec bpf debug >& tc.log` on the node which you are trying to connect to? Lets try the one with the pod first. Beware: it can be a lot of output.

**Comment by TrevorTaoARM** [comment]
> `BPFLogLevel`



> I do not quite follow what is the problem. It seems like when you are trying to access the nodeport from either of the 2 k8s node, you get a failure. Or am I reading it just wrong and you mean that if you access from say `10.169.208.229` to either of the two nodes you get these 2 different errors? I think that is what you meant.
> 
> Is the actuall pod running?
> 
> What is the output from `kubectl exec calico-node-xyz -n calico-system -- calico-node -bpf nat dump` for both of the nodes?

On node 10.169.208.204(master, tainted):
# calico-node -bpf nat dump
2022-07-27 02:57:03.265 [INFO][2459138] confd/maps.go 433: Loaded map file descriptor. fd=0x9 name="/sys/fs/bpf/tc/globals/cali_v4_nat_fe3"
2022-07-27 02:57:03.265 [INFO][2459138] confd/maps.go 433: Loaded map file descriptor. fd=0xa name="/sys/fs/bpf/tc/globals/cali_v4_nat_be"
10.169.208.204 port 30942 proto 6 id 0 count 2 local 1
        0:0      192.168.26.199:80
        0:1      192.168.4.3:80
172.16.1.10 port 53 proto 6 id 3 count 2 local 2
        3:0      192.168.26.194:53
        3:1      192.168.26.195:53
172.16.1.10 port 53 proto 17 id 2 count 2 local 2
        2:0      192.168.26.194:53
        2:1      192.168.26.195:53
172.16.1.10 port 9153 proto 6 id 4 count 2 local 2
        4:0      192.168.26.194:9153
        4:1      192.168.26.195:9153
172.26.12.101 port 30942 proto 6 id 0 count 2 local 1
        0:0      192.168.26.199:80
        0:1      192.168.4.3:80
192.168.26.192 port 30942 proto 6 id 0 count 2 local 1
        0:0      192.168.26.199:80
        0:1      192.168.4.3:80
172.16.1.1 port 443 proto 6 id 1 count 1 local 0
        1:0      10.169.208.204:6443
172.16.1.147 port 80 proto 6 id 0 count 2 local 1
        0:0      192.168.26.199:80
        0:1      192.168.4.3:80
172.17.0.1 port 30942 proto 6 id 0 count 2 local 1
        0:0      192.168.26.199:80
        0:1      192.168.4.3:80
192.168.122.1 port 30942 proto 6 id 0 count 2 local 1
        0:0      192.168.26.199:80
        0:1      192.168.4.3:80
192.168.202.25 port 30942 proto 6 id 0 count 2 local 1
        0:0      192.168.26.199:80
        0:1      192.168.4.3:80
255.255.255.255 port 30942 proto 6 id 0 count 2 local 1
        0:0      192.168.26.199:80
        0:1      192.168.4.3:80

On node 10.169.210.208:
calico-node -bpf nat dump
2022-07-27 03:01:30.386 [INFO][2162491] confd/maps.go 433: Loaded map file descriptor. fd=0x9 name="/sys/fs/bpf/tc/globals/cali_v4_nat_fe3"
2022-07-27 03:01:30.387 [INFO][2162491] confd/maps.go 433: Loaded map file descriptor. fd=0xa name="/sys/fs/bpf/tc/globals/cali_v4_nat_be"
255.255.255.255 port 30942 proto 6 id 4 count 2 local 1
        4:0      192.168.4.3:80
        4:1      192.168.26.199:80
172.16.1.1 port 443 proto 6 id 0 count 1 local 0
        0:0      10.169.208.204:6443
172.16.1.10 port 53 proto 6 id 2 count 2 local 0
        2:0      192.168.26.194:53
        2:1      192.168.26.195:53
172.16.1.10 port 53 proto 17 id 1 count 2 local 0
        1:0      192.168.26.194:53
        1:1      192.168.26.195:53
172.17.0.1 port 30942 proto 6 id 4 count 2 local 1
        4:0      192.168.4.3:80
        4:1      192.168.26.199:80
192.168.4.0 port 30942 proto 6 id 4 count 2 local 1
        4:0      192.168.4.3:80
        4:1      192.168.26.199:80
10.169.210.108 port 30942 proto 6 id 4 count 2 local 1
        4:0      192.168.4.3:80
        4:1      192.168.26.199:80
172.16.1.10 port 9153 proto 6 id 3 count 2 local 0
        3:0      192.168.26.194:9153
        3:1      192.168.26.195:9153
172.16.1.147 port 80 proto 6 id 4 count 2 local 1
        4:0      192.168.4.3:80
        4:1      192.168.26.199:80
172.26.12.100 port 30942 proto 6 id 4 count 2 local 1
        4:0      192.168.4.3:80
        4:1      192.168.26.199:80
192.168.122.1 port 30942 proto 6 id 4 count 2 local 1
        4:0      192.168.4.3:80
        4:1      192.168.26.199:80

**Comment by TrevorTaoARM** [comment]
> > `BPFLogLevel`
> 
> > I do not quite follow what is the problem. It seems like when you are trying to access the nodeport from either of the 2 k8s node, you get a failure. Or am I reading it just wrong and you mean that if you access from say `10.169.208.229` to either of the two nodes you get these 2 different errors? I think that is what you meant.
> > Is the actuall pod running?
> > What is the output from `kubectl exec calico-node-xyz -n calico-system -- calico-node -bpf nat dump` for both of the nodes?
> 

Yes, I 
> On node 10.169.208.204(master, tainted): # calico-node -bpf nat dump 2022-07-27 02:57:03.265 [INFO][2459138] confd/maps.go 433: Loaded map file descriptor. fd=0x9 name="/sys/fs/bpf/tc/globals/cali_v4_nat_fe3" 2022-07-27 02:57:03.265 [INFO][2459138] confd/maps.go 433: Loaded map file descriptor. fd=0xa name="/sys/fs/bpf/tc/globals/cali_v4_nat_be" 10.169.208.204 port 30942 proto 6 id 0 count 2 local 1 0:0 192.168.26.199:80 0:1 192.168.4.3:80 172.16.1.10 port 53 proto 6 id 3 count 2 local 2 3:0 192.168.26.194:53 3:1 192.168.26.195:53 172.16.1.10 port 53 proto 17 id 2 count 2 local 2 2:0 192.168.26.194:53 2:1 192.168.26.195:53 172.16.1.10 port 9153 proto 6 id 4 count 2 local 2 4:0 192.168.26.194:9153 4:1 192.168.26.195:9153 172.26.12.101 port 30942 proto 6 id 0 count 2 local 1 0:0 192.168.26.199:80 0:1 192.168.4.3:80 192.168.26.192 port 30942 proto 6 id 0 count 2 local 1 0:0 192.168.26.199:80 0:1 192.168.4.3:80 172.16.1.1 port 443 proto 6 id 1 count 1 local 0 1:0 10.169.208.204:6443 172.16.1.147 port 80 proto 6 id 0 count 2 local 1 0:0 192.168.26.199:80 0:1 192.168.4.3:80 172.17.0.1 port 30942 proto 6 id 0 count 2 local 1 0:0 192.168.26.199:80 0:1 192.168.4.3:80 192.168.122.1 port 30942 proto 6 id 0 count 2 local 1 0:0 192.168.26.199:80 0:1 192.168.4.3:80 192.168.202.25 port 30942 proto 6 id 0 count 2 local 1 0:0 192.168.26.199:80 0:1 192.168.4.3:80 255.255.255.255 port 30942 proto 6 id 0 count 2 local 1 0:0 192.168.26.199:80 0:1 192.168.4.3:80
> 
> On node 10.169.210.208: calico-node -bpf nat dump 2022-07-27 03:01:30.386 [INFO][2162491] confd/maps.go 433: Loaded map file descriptor. fd=0x9 name="/sys/fs/bpf/tc/globals/cali_v4_nat_fe3" 2022-07-27 03:01:30.387 [INFO][2162491] confd/maps.go 433: Loaded map file descriptor. fd=0xa name="/sys/fs/bpf/tc/globals/cali_v4_nat_be" 255.255.255.255 port 30942 proto 6 id 4 count 2 local 1 4:0 192.168.4.3:80 4:1 192.168.26.199:80 172.16.1.1 port 443 proto 6 id 0 count 1 local 0 0:0 10.169.208.204:6443 172.16.1.10 port 53 proto 6 id 2 count 2 local 0 2:0 192.168.26.194:53 2:1 192.168.26.195:53 172.16.1.10 port 53 proto 17 id 1 count 2 local 0 1:0 192.168.26.194:53 1:1 192.168.26.195:53 172.17.0.1 port 30942 proto 6 id 4 count 2 local 1 4:0 192.168.4.3:80 4:1 192.168.26.199:80 192.168.4.0 port 30942 proto 6 id 4 count 2 local 1 4:0 192.168.4.3:80 4:1 192.168.26.199:80 10.169.210.108 port 30942 proto 6 id 4 count 2 local 1 4:0 192.168.4.3:80 4:1 192.168.26.199:80 172.16.1.10 port 9153 proto 6 id 3 count 2 local 0 3:0 192.168.26.194:9153 3:1 192.168.26.195:9153 172.16.1.147 port 80 proto 6 id 4 count 2 local 1 4:0 192.168.4.3:80 4:1 192.168.26.199:80 172.26.12.100 port 30942 proto 6 id 4 count 2 local 1 4:0 192.168.4.3:80 4:1 192.168.26.199:80 192.168.122.1 port 30942 proto 6 id 4 count 2 local 1 4:0 192.168.4.3:80 4:1 192.168.26.199:80

**Comment by lwr20** [comment]
pinging @tomastigera

**Comment by TrevorTaoARM** [comment]
This issue disappeared from release v3.25.0-dev.

**Comment by lwr20** [comment]
> This issue disappeared from release v3.25.0-dev(commit: c4f28c9)

@tomastigera is that expected?

**Comment by renyunkang** [comment]
How's it going? @tomastigera

**Comment by TrevorTaoARM** [comment]
> > This issue disappeared from release v3.25.0-dev(commit: [c4f28c9](https://github.com/projectcalico/calico/commit/c4f28c9666e8e5934c863b38ac162ced3f891bc6))
> 
> @tomastigera is that expected?

I still meet this issue on arm64 platform, I will do a further analysis if time is available for me in the future.

**Comment by tomastigera** [comment]
Hi @TrevorTaoARM , could you elaborate a little bit on how adding the enPxxx helps this issue?

**Comment by TrevorTaoARM** [comment]
Hi @tomastigera We found this issue on our arm servers with the eBPF dataplane used, the environment is as:
2 k8s nodes with Calico installed, eBPF dataplane enabled, 
after deploying a k8s service with 2 backend Nginx pods with the yaml(pls see at the end of this comment), we found that when we access the nodePort service by
curl http://nodeIP:nodePort, only half accesses here can succeeded. 

So I checked the ebpf trace log, it seemed that some of the accessing packets had been discarded by:
unknown ep:
		if (!(val = (struct ifstate_val *)cali_iface_lookup_elem(&ifindex))) {
			CALI_DEBUG("FIB not approved - connection to unknown ep %d not confirmed.\n", ifindex);
			return false;
		}
and I checked the ifstate map by:
[root@net-arm-n1sdp /]# calico-node -bpf ifstate dump
   30 : {flags: workload,ready, name: cali5a113a54339}
   20 : {flags: workload,ready, name: cali94be36c4e32}
   58 : {flags: workload,ready, name: califbb8ddc9eeb}
   92 : {flags: workload,ready, name: cali067623b0fb4}
   63 : {flags: workload,ready, name: cali27e5c48a008}
   26 : {flags: workload,ready, name: cali20978252779}
    8 : {flags: ready, name: vxlan.calico}
   55 : {flags: ready,workload, name: cali473574a4023}
    2 : {flags: ready, name: eth0}
   56 : {flags: workload,ready, name: cali3e9aba7e249}
   27 : {flags: workload,ready, name: cali6df34eb990c}
   57 : {flags: workload,ready, name: cali723098c7756}
   29 : {flags: workload,ready, name: cali5faddd946b7}
   24 : {flags: workload,ready, name: cali35c2dc05f32}
   72 : {flags: ready,workload, name: cali7d0bb85cc20}
   31 : {flags: workload,ready, name: cali8998e765e58}
   28 : {flags: workload,ready, name: calib894ccabde7}

but for the interface enP1p1s0f1 which is the dedicated (10G ether nic, faster than the mgmt intf)  to connect the 2 nodes were missed from the map, so if the access was NATed to the remote Nginx pod, it would be discarded; if it's NATed to the local Nginx pod, it will succeed. 

The yaml to deploy our service:
apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    name: http
    nodePort: 30942
  selector:
    app: nginx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
        role: backend
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80

**Comment by TrevorTaoARM** [comment]
@tomastigera Anyway, I think we still need verify carefully if it really solve this issue completely with more tests/checks. 
But the PR here is really against an actual issue of interface missing, so I think it should be valueful and needed.
