### ISSUE TITLE
How to re-trigger failed flannel to calico migration?

### ISSUE THREAD

**Issue by Siddharood** [projectcalico/calico#6398]
## Expected Behavior
I want to rerun failed flannel to calico migration and make sure it completes and calico nodes are running in case of failures during flannel migration job.

## Current Behavior
I have a 3 node kubernetes cluster with k8s 1.22 version with flannel setup and running fine. I did run live migration steps from flannel to calico as describes in [here]( https://projectcalico.docs.tigera.io/getting-started/kubernetes/flannel/migration-from-flannel). Cluster migrated to calico successfully. However when I tried multiple times, couple of times I encountered below scenario.

- flannel migration job is running even after 20 hours.
- flannel to calico migration was not successfull.
- two nodes out of 3 nodes(node2 and node3) were running calico node
- one node(node1) was in schedulingdisabled mode and calico node was not running on the setup.
- When I read logs from flannel migration job, it was trying to reach kube-apiserver and it was down during that time, hence it was failed.

Later after sometime when kube-api server was stable I tried re-running flannel migration job, it didn't proceed and nothing happened.

## Steps to Reproduce (for bugs)
1. Install k8s cluster of 3 nodes with flannel
2. run flannel to calico migration following the steps mentioned in [here]( https://projectcalico.docs.tigera.io/getting-started/kubernetes/flannel/migration-from-flannel)
3. bring down kube-api server on one node

## Context
When flannel to calico migration failed in middle with node scheduling disabled, cluster is not in ideal state. 

## Your Environment

* Calico version: 3.21
* Orchestrator version: kubernetes 1.22
* Operating System and version: Ubuntu 18.04
* Link to your project (optional):

Any help on this is appreciated.

**Comment by Siddharood** [comment]
Thanks for the response @lmm. I will provide logs and also take a look at the check.

**Comment by Siddharood** [comment]
@song-jiang - Any help on this appreciated.

**Comment by song-jiang** [comment]
Sorry for the late reply. Lost github notification somehow. 

> Later after sometime when kube-api server was stable I tried re-running flannel migration job, it didn't proceed and nothing happened.
1. Was flannel migration controller running when you rerun the job?
2. What is the log of flannel migration controller? Normally the log will show why it's not proceeding.

**Comment by lmm** [comment]
I'm going to close this for now due to inactivity but feel free to reopen, thanks.
