### ISSUE TITLE
Calico created microk8s cluster network does not seem to work properly/is slow with a 10Gbps Broadcom BCM57416 card

### ISSUE THREAD

**Issue by PhotoTeeborChoka** [projectcalico/calico#6410]
I am using a fully automatic Ansible based deployment to provision a microk8s multi-node cluster (that utilizes calico) inside VMs on a bare-metal server. Both VM and bare-metal based setups with this exact deployment have been working with a 1Gbps NIC, however when using a 10Gbps NIC, the pod network speeds between different nodes are extremely slow.

The podA(nodeA) to podB(nodeB) iperf output on a 10Gbps NIC:
```
Connecting to host iperf3-server-service.network-performance.svc.cluster.local, port 5201
[ 5] local 10.1.140.103 port 48002 connected to 10.152.183.205 port 5201
[ ID] Interval Transfer Bitrate Retr Cwnd
...
- - - - - - - - - - - - - - - - - - - - - - - - -
[ ID] Interval Transfer Bitrate Retr
[ 5] 0.00-30.00 sec 11.6 MBytes 3.24 Mbits/sec 3494 sender
[ 5] 0.00-30.00 sec 11.5 MBytes 3.22 Mbits/sec receiver

iperf Done.
```

This issues relates to https://github.com/canonical/microk8s/issues/3341 but I have no idea where it should be filed.

## Expected Behavior
The pods between different Kubernetes nodes should communicate with the maximum speed allowed by the network interface.

## Current Behavior
The communication between pods from different nodes is extremely low.

## Steps to Reproduce (for bugs)

1. create a microk8s multinode cluster in a HA setup i VMs with a 10Gbps card
2. run iperf to test the communication

## Context

This completely bricks the setup.

## Your Environment

* Calico version 3.22
* microk8s v1.24/stable snapd
* Ubuntu 20.04.1

**Comment by coutinhop** [comment]
Closing as it seems like a particular issue with the hardware that was being used...
