### ISSUE TITLE
Does calico network policies only log denied traffic?

### ISSUE THREAD

**Issue by ausername86** [projectcalico/calico#6418]
Hello,

I am a bit confused on the Log action for Calico network policies. Im not seeing in the calico documentation if the Log action only logs denied traffic or if it can log both denied and accepted traffic. I just see an example of logging denied traffic in the documentation. Is there a way to tell if it's accepted or denied by the "calico-packet:" log line in syslog? I don't see a DROP in any of my calico-packet log lines.

https://projectcalico.docs.tigera.io/security/calico-network-policy#apply-network-policies-in-specific-order

Thanks for the clarification.

**Comment by caseydavenport** [comment]
The log action will log packets that traverse the rule, it's not tied to accept / drop in any way and you need to use other rules in order to perform those actions.

**Comment by lmm** [comment]
Going to close this for now due to inactivity but if you have any more questions please feel free to reopen, thanks!

**Comment by sourabhgupta385** [comment]
I am also a bit puzzled about the logging. The documentation says - 

If one or more network policies apply to a pod containing egress rules, then only the egress traffic specifically allowed by those policies is allowed.

I want to log all the traffic that is denied by the Calico network policy. 

I have applied some Allow rules policy, which means rest everything is blocked. Now, how do I log that rest everything? Do I need to create a separate network policy with high order value then the one with Allow rules policy?
