### ISSUE TITLE
container is Running, but has no eth0 NIC in container, and cant's access network inside container

### ISSUE THREAD

**Issue by huangjiasingle** [projectcalico/calico#6423]
## Expected Behavior

running container

## Current Behavior

pod running on one node, it's alrady running 20 Hour, do some data process task , some time download some file from internal stroage server.  but now the container has no eth0 NIC (on the node  the calixxx NIC not exist), so down load file error.   

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Calico version
* v3.22.1
* Orchestrator version (e.g. kubernetes, mesos, rkt):
* kubernetes
* Operating System and version:
* 3.10.0-1160.59.1.el7.x86_64
* Link to your project (optional):

**Comment by caseydavenport** [comment]
Calico will only remove that device when told to do so via the container runtime. 

You should probably look into the Calico CNI logs on that node to see if a teardown was triggered for that pod at any time, and if so look into the container runtime logs to see why that might have happened.

Does the `Pod` object exist in the Kubernetes API? If so, what is its STATUS?

**Comment by lmm** [comment]
I'm going to close this for now due to inactivity, please feel free to reopen if you have more details or questions, thanks!
