### ISSUE TITLE
Calico 3.22.2 --CNI network "k8s-pod-network": error getting ClusterInformation , x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by priyapal** [projectcalico/calico#6425]
we are having issues with Calico 3.22.2 with Kubernetes version 1.21.5 , This seem to work fine in K8  v1.19.12. 

pods fail to come up and struck at ContainerCreating

Warning  FailedCreatePodSandBox  4m3s                 kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to create pod network sandbox k8sxxx): error adding pod dxxxx to CNI network "k8s-pod-network": error getting ClusterInformation: Get "https://[172.244.0.1]:443/apis/crd.projectcalico.org/v1/clusterinformations/default": x509: certificate signed by unknown authority

## Expected Behavior
Pods should be up and running with no issues

## Current Behavior
<Pods are struck in ContainerCreating stage  with the below error
Warning  FailedCreatePodSandBox  4m3s                 kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to create pod network sandbox k8s_ai-core-onboarding-8478587bf4-xz5rt_default_2bc3d9ef-9e8b-4f55-810b-ad09d879c7f5_0(61a32dc8e6b4a6d06fdc9fbbe1d783bb9462b1671a33cd1f16271bd821195936): error adding pod default_ai-core-onboarding-8478587bf4-xz5rt to CNI network "k8s-pod-network": error getting ClusterInformation: Get "https://[172.244.0.1]:443/apis/crd.projectcalico.org/v1/clusterinformations/default": x509: certificate signed by unknown authority

## Your Environment

* Calico version Issue in both 3.22.2 and also tried in latest 3.23.2
* Orchestrator version (e.g. kubernetes, mesos, rkt): 1.21.5

**Comment by coutinhop** [comment]
Hi @priyapal, k8s v1.21.5 seems to no longer be supported (EOL for v1.21.14 was 2022-06-28, v1.21.5 is older than that even: https://kubernetes.io/releases/patch-releases/#support-period). Could you try creating your cluster with a more recent k8s version?

I see that you mention that you don't have this issue with k8s v1.19.12, I wonder if it could be a more recent patch release than v1.21.5, or if you are reusing some configuration which needs to be updated when upgrading? Anyways, IMHO you should try a recent patch of a supported k8s version to see if you still hit this issue...

**Comment by priyapal** [comment]
Thanks @coutinhop ,  Strangly renaming 10-calico.conflist , make the pods to come up which makes me wonder how comes it works on this .Any insights?

**Comment by caseydavenport** [comment]
@priyapal Do you have other files in that directory? 

The container runtime looks for files in lexicographical order, so you may have inadvertently changed which config file was being used by changing the name. What did you rename it to?
