### ISSUE TITLE
can't run calicoctl version successfully without a cluster

### ISSUE THREAD

**Issue by 06kellyjac** [projectcalico/calico#6436]
## Expected Behavior

I expect calicoctl version to pass even if I have no cluster

## Current Behavior

It fails

## Possible Solution

I tried messing with `KUBERNETES_MASTER` and looked at the flags but nothing was useful

## Steps to Reproduce (for bugs)

1. Have no cluster (or maybe no calico cni deployed)
2. `calicoctl version`
3. see exit code 1

## Context

I run calicoctl version within a sandbox that has no-networking to make sure it was built correctly

**Comment by caseydavenport** [comment]
What version are you using? Look like it works fine for me with the latest v3.23.3 build:

```
$ calicoctl version
Client Version:    v3.23.3
Git commit:        3a3559be1
Unable to detect installed Calico version

$ echo $?          
0
```
