### ISSUE TITLE
Document All components supporting datastore config file

### ISSUE THREAD

**Issue by tmjd** [projectcalico/calico#646]
Document the changes from #563 

Expect to need doc updates for:

- [ ] New page that each component can link
  - "Datastore Configuration File" (potential name ??)
- [ ] calicoctl
  - [ ] UI changes
  - [ ] Split out previous calicoctl etcdv2 and k8s config info moving relevant pieces to "Datastore Cfg"
  - [ ] Update considerations
- [ ] calico/node
  - [ ] New config option
  - [ ] link to Datastore Cfg section
- [ ] CNI plugin
  - [ ] New config option
  - [ ] link to Datastore Cfg section
- [ ] ~~Policy controller~~
  - [ ] ~~New config option~~
  - [ ] ~~link to Datastore Cfg section~~
- [ ] Libnetwork plugin
  - [ ] ~~New config option~~
  - [ ] link to Datastore Cfg section
- [ ] ~~Felix~~
  - [ ] ~~New config option~~
  - [ ] ~~link to Datastore Cfg section~~

**Comment by caseydavenport** [comment]
I think we should track documentation in the original issue.
