### ISSUE TITLE
Readiness probe failed: calico/node is not ready: BIRD is not ready: BGP not established with xx.xx.xx.xx

### ISSUE THREAD

**Issue by jijilonline** [projectcalico/calico#6474]
Issue Summary

Calico Version - node:v3.3.2, K8s Version 1.17

Calico Daemsets pods are not running and gives the below error Readiness probe failed: calico/node is not ready: BIRD is not ready: BGP not established with xx.xx.xx.xx
calico-node-xjk                            1/2     Running   0        
calico-node-xnx                            1/2     Running   0       
calico-node-xq9                           1/2     Running   0     
calico-node-xrp                            1/2     Running  

**calicoctl node status** 

Calico process is running.

IPv4 BGP status
+---------------+-------------------+-------+------------+--------------------------------+
| PEER ADDRESS  |     PEER TYPE     | STATE |   SINCE    |              INFO              |
+---------------+-------------------+-------+------------+--------------------------------+
| 10.xx.xx.xx | node-to-node mesh | start | 16:43:32   | Active Socket: Host is         |
|               |                   |       |            | unreachable                    |
| | 10.xx.xx.xx  | node-to-node mesh | start | 2022-07-14 | Active Socket: Host is         |
|               |                   |       |            | unreachable               

## Steps to Reproduce (for bugs)

1. All the calico pods are throwing the error and not able to run and kube-controller pod shows the below error

2022-07-26 04:14:19.096 [ERROR][1] node_controller.go 174: Error deleting Calico node: node-01%!(EXTRA *errors.errorString=The requested CIDR (10.xx.xx.xx/26) is not within any configured pools.) error=The requested CIDR (10.xx.xx.xx/26) is not within any configured pools.
2022-07-26 04:30:59.540 [ERROR][1] ipam.go 930: Failed to release IPAM affinities for host error=The requested CIDR (10.xx.xx.xx/26) is not within any configured pools. host="node-01"

## Your Environment

* Calico version -- quay.io/calico/node:v3.3.2
* Orchestrator version (e.g. kubernetes, mesos, rkt):
* Operating System and version:
* Link to your project (optional):

**Comment by caseydavenport** [comment]
> Calico version -- quay.io/calico/node:v3.3.2

Please try again using a modern Calico and Kubernetes version. v3.3.2 is long since out of support. The latest is v3.23, which requires Kubernetes v1.21+
