### ISSUE TITLE
Warn Calico-v2.0 users to use Calico v2.1 with kubeadm-1.6

### ISSUE THREAD

**Issue by gunjan5** [projectcalico/calico#648]
We have a separate manifest for k8s 1.6 for Calico v2.1:
http://docs.projectcalico.org/v2.1/getting-started/kubernetes/installation/hosted/kubeadm/

but not for Calico v2.0

(one of the users just tripped on that)

**Comment by djosborne** [comment]
Kubeadm 1.6 was recently released. I think it's reasonable to require users to use at a minimum Calico v2.1 with this new release. So I don't feel the need to backport kubeadm-1.6 compliant manifests to Calico 2.0 and earlier releases.

Instead, let's update our 2.0 docs to explain and link to Calico 2.1 with kubeadm-1.6 compliany yamls.

**Comment by djosborne** [comment]
While we're here, it seems like the versions given to kubeadm have changed. So we should update these lines in 2.1:

```
For Kubeadm <=1.6.0-alpha with Kubernetes 1.5.x:
...
For Kubeadm >=1.6.0-beta with Kubernetes 1.6.x:
...
```

Should now just read `Kubeadm 1.6` and `Kubeadm 1.5`

**Comment by djosborne** [comment]
@tmjd fixed the Kubeadm version strings. All that's left for this issue is the original stuff: update v2.0 docs to push people to v2.1
