### ISSUE TITLE
routing broken

### ISSUE THREAD

**Issue by fungusakafungus** [projectcalico/calico#6486]
## Expected Behavior
- routes should be setup consistently and point to the one node hosting a block.
- all blockaffinities should have distinct `spec.cidr`s

## Current Behavior

sometimes, a blockaffinity is created with the same cidr as an existing one:
```
$ kubectl get blockaffinity node-15.company.com-10-148-158-64-26 node-14.company.com-10-148-158-64-26
NAME                                                      AGE
node-15.company.com-10-148-158-64-26   105s
node-14.company.com-10-148-158-64-26   8d
```

IPAMBlock object shows the correct affinity:
```
$ kubectl get ipamblock 10-148-158-64-26 -ocustom-columns=AFFINITY:spec.affinity
AFFINITY
host:node-15.company.com
```

routes(on all other nodes) point to both nodes(.12 and .13 are node-14 and node-15):
```
$ ssh node-1.company.com ip -o r | grep 10.148.158.64/26
10.148.158.64/26 proto bird \	nexthop via 10.18.132.12 dev eth0 weight 1 \	nexthop via 10.18.132.13 dev eth0 weight 1
```

**pings to pods in affected subnets time out**.

## Possible Solution
Workaround is to delete the old blockaffinity.
 
## Context
We create dev environments as namespaces, spinning up 50-150 pods at once. 
## Your Environment
* Calico version: v3.20.3
* Orchestrator version (e.g. kubernetes, mesos, rkt): k8s v1.22.11
* Operating System and version: ubuntu focal 
* Link to your project (optional):

We run with kdd and typha(2 replicas), bgp mesh, and some nodes peer with routers; each cluster is 50 nodes, blockSize: 26

We see this problem multiple times a day. Last change to the environment was calico upgrade 3.19.3 to 3.20.3, later 3.20.4, and k8s upgrade, v1.21.5 to v1.22.11.  

```
$ kubectl get felixconfiguration default -oyaml
...
spec:
  bpfEnabled: false
  bpfExternalServiceMode: Tunnel
  bpfLogLevel: ""
  ipipEnabled: false
  logSeverityScreen: Info
  reportingInterval: 0s
  vxlanEnabled: false
  wireguardEnabled: false
```

**Comment by mgleung** [comment]
Hey @fungusakafungus, if I'm understanding your problem correctly, it sounds like we've hit a fun IPAM GC issue. Could I get you to post some of the node logs to see if there's anything we can rule out from there? Might also be good to get the logs of the kube-controllers as well since they should be handling IPAM GC too.

**Comment by fungusakafungus** [comment]
will provide the logs of our next case. One interesting thing we noticed is that sometimes the routes become consistent (the blockaffinity object gets deleted) after a long time, e.g.
```
node-19.company.com-10-148-144-64-26             105d
node-35.company.com-10-148-144-64-26             99m
```
...so at least after 99 minutes

**Comment by fungusakafungus** [comment]
I noticed that ipamblock is created together with the new blockaffinity:
```
$ kubectl get ipamblock/10-148-4-64-26 blockaffinity/node-14.company.com-10-148-4-64-26 blockaffinity/node-48.company.com-10-148-4-64-26
NAME                                             AGE
ipamblock.crd.projectcalico.org/10-148-4-64-26   37m

NAME                                                                                        AGE
blockaffinity.crd.projectcalico.org/node-14.company.com-10-148-4-64-26   37m
blockaffinity.crd.projectcalico.org/node-48.company.com-10-148-4-64-26   14d
```
both are 37 minutes old.

So I checked for blockaffinities that don't have an ipamblock and found some. That doesn't sound healthy.

I checked the age of all ipamblocks and found that the bulk of them were created 14 days ago, and the rest is more recent.
14 days ago we tried to fix the(a?) routing problem by upgrading calico to v3.22.4 and downgrading back to 3.20.3 and rebooting everything, because we encountered a whole lot of https://github.com/projectcalico/calico/issues/5779 , which was worse than routing trouble.

Now I believe that we had a different routing problem before up- and downgrade, the only trace of that other problem is how it manifested on some nodes:
```
root@node-45.company:~# ip r get 10.148.155.23/32
RTNETLINK answers: Invalid argument
```

...so I think we should close here because too many things have happened to this clusters

**Comment by coutinhop** [comment]
OK, @fungusakafungus, thanks for the reply. We'll close this, please let us know if you find issues again, but I'd advise you to use a more recent calico version (v3.20.3 is from Nov 2021; unfortunately the fix for https://github.com/projectcalico/calico/issues/5779 did not make it to v3.22.4, but it should be in the next patch release; it is present in v3.23 and v3.24 though).
