### ISSUE TITLE
FelixConfiguration kubeNodePortRanges:  []numorstring.Port: readObjectStart: expect { or n, but found "

### ISSUE THREAD

**Issue by KaseiHaku** [projectcalico/calico#6508]
## Expected Behavior

no error

## Steps to Reproduce (for bugs)

```bash
kubectl create -f https://projectcalico.docs.tigera.io/manifests/tigera-operator.yaml
kubectl create -f https://projectcalico.docs.tigera.io/manifests/custom-resources.yaml
cat <<EOF | tee ~/k8s/temporary.yml
apiVersion: projectcalico.org/v3
kind: FelixConfiguration
metadata:
  name: default
spec:
  bpfLogLevel: ""
  floatingIPs: Disabled
  healthPort: 9099
  iptablesMarkMask: 0xffff0000
  kubeNodePortRanges:
    - '30000:39999'
  logSeverityScreen: Info
  reportingInterval: 0s
EOF
calicoctl create -f ~/k8s/temporary.yml
kubectl -n tigera-operator logs tigera-operator-56d4765449-bcc7t -f
```
![1659947893988](https://user-images.githubusercontent.com/34833442/183376558-60a8ae43-2872-4e81-b93e-293c3a21aae2.jpg)

## Your Environment

* Calico version: 3.23
* Orchestrator version (e.g. kubernetes, mesos, rkt): k8s v1.23.9
* Operating System and version: centos7
* Link to your project (optional):

**Comment by caseydavenport** [comment]
I found this to work fine on the latest Calico, so going to close as not reproducible. I believe it was this commit that fixed it: https://github.com/tigera/operator/commit/b1467e284afa5f39ff54bd9d8951982e0b70ddf2
