### ISSUE TITLE
Automate RC header warning

### ISSUE THREAD

**Issue by ozdanborne** [projectcalico/calico#653]
A warning message was added in #650 which pushes users towards the latest release.

This warning message will start printing on v2.1 once v2.2-rc is published. We'll need to update that code so that:
- it doesn't make this jump until we are ready
- it warns users when they're on the release candidate.

**Comment by tmjd** [comment]
Not sure what the thought was to handle this but @tomdee handled it just by not putting the new RC at the top of the versions file.  Seems like a reasonable thing to do though the RELEASING.md doc needs that info.

**Comment by djosborne** [comment]
Information has been placed in release steps. De-escalating automation of this.

**Comment by ozdanborne** [comment]
Going to close this as wontfix. Manual process doesn't cost enough time to warrant a fix
