### ISSUE TITLE
HELM - The Tigera Operator Helm chart does not support imagePullSecrets

### ISSUE THREAD

**Issue by jbehrends** [projectcalico/calico#6530]
## Expected Behavior
In an environment that does not allow internet access and a secured private registry is required to host all Calico/Tigera containers, the Helm chart should template the appropriate imagePullSecrets into the Tigera deployment or it's Service account so that the container can be pulled.

## Current Behavior
The helm chart values files does have a value for "imagePullSecrets" BUT that value is never templated into the actual deployment or service account manifests...  As a result when trying to deploy the Tigera operator, we get a not authorized error from our registry because no image pull secret is referenced. (Note, the imagepullsecret we're TRYING to reference was already defined in a different process outside of the helmchart)

## Possible Solution
The helm chart templates need to be updated so that IF Values.imagePullSecrets is defined, then render the deployment manifest with the imagePullSecrets defined.

## Steps to Reproduce (for bugs)

1. Setup an environment with a private registry that requires credentials.
2. Apply the Tigera helm chart with 
 - Values for image/tag overrides that point to the private registry for image source.
 - Values.imagePullSecrets defined with an existing and valid imagepull secret name.
4. The deployment will fail, and you will be able to run a kubectl get <DEPLYMENT NAME> -o yaml and verify there is no imagepullsecret referenced.

## Context
The Helm chart is useless in an environment that uses secured private registries.

## Your Environment

* Calico Chart version: v3.23.3 (Issue appears to exist in "master" as well.
* Orchestrator version (e.g. kubernetes, mesos, rkt): kubernetes 1.21 / Helm v3.5.3
* Operating System and version:
* Link to your project (optional):

**Comment by caseydavenport** [comment]
Newer versions of the helm chart do actually support this, starting in v3.23.1: https://github.com/projectcalico/calico/pull/6093

**Comment by jbehrends** [comment]
@caseydavenport  I just downloaded the latest 3.23.3 release and it does NOT support imagePullSecrets to deploy the actual operator it's self.

You can verify by down downloading the chart:
https://github.com/projectcalico/calico/releases/download/v3.23.3/tigera-operator-v3.23.3.tgz

There looks to be imagepullsecret references for use in the containers that operator deploys... but there are no references to an imagepullsecret for for the operator's deployment or the service account that it uses.

Please reopen this issue.

**Comment by caseydavenport** [comment]
Yep, gotcha. Looks like we still need to add this.
