### ISSUE TITLE
Why does calico DROP connections to BGP advertised serviceLoadBalancerIPs? And how can i prevent it?

### ISSUE THREAD

**Issue by tomiamao** [projectcalico/calico#6553]
I have a the following config:

```
apiVersion: projectcalico.org/v3
kind: BGPConfiguration
metadata:
  name: default
spec:
  serviceClusterIPs:
  serviceExternalIPs:
  serviceLoadBalancerIPs:
  - cidr: 172.X.X.0/13
  - cidr: 102.Y.Y.0/22
```
On the k8s data nodes, I see the following in the IP table:
```
:~$ sudo iptables -S | grep cali-cidr-block
-N cali-cidr-block
-A cali-FORWARD -m comment --comment "cali:NOSxoaGx8OIstr1z" -j cali-cidr-block
-A cali-cidr-block -d 102.Y.Y.0/22 -m comment --comment "cali:vorxMY1Fx0NtdC9K" -j DROP
-A cali-cidr-block -d 172.X.X.0/13 -m comment --comment "cali:xuGZSEbeFpyU6wOS" -j DROP
```

The effect of this is that my pods can't speak to the serviceLoadBalancerIPs for example 102.Y.Y.1

## Context

The reason I need this is for cert-manager. Currently, when cert-manager tries to connect to the nginx controller, the connection gets dropped by the iptables rules inserted by Calico. The nginx controller service IP is within the serviceLoadBalancerIPs range.

Why does calico DROP connections to BGP advertised serviceLoadBalancerIPs? And how can i prevent it?

I tried deleting the calico rules but that didn't work. 

Any help appreciated.

## Your Environment

* Calico version
* Orchestrator version (e.g. kubernetes, mesos, rkt):
* Operating System and version:
* Link to your project (optional):
```
$ calicoctl version
Client Version:    v3.22.0
Git commit:        a86e41d02
Cluster Version:   v3.22.0
Cluster Type:      k8s,bgp,kubeadm,kdd
```
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.3", GitCommit:"816c97ab8cff8a1c72eccca1026f7820e93e0d25", GitTreeState:"clean", BuildDate:"2022-01-25T21:25:17Z", GoVersion:"go1.17.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.3", GitCommit:"816c97ab8cff8a1c72eccca1026f7820e93e0d25", GitTreeState:"clean", BuildDate:"2022-01-25T21:19:12Z", GoVersion:"go1.17.6", Compiler:"gc", Platform:"linux/amd64"}
```

OS: Ubuntu 20:04

**Comment by Josh-Tigera** [comment]
Hi @tomiamao,

Could you include the steps you took to configure your nginx controller service, as well as the current config for that service? Please also include the full output of your iptables.

**Comment by caseydavenport** [comment]
The service loadbalancer IP ranges provided aren't expected to be real routable IP addresses assigned to pods. Rather, the way they are intended to work is that they are handled by NAT on the Kubernetes nodes and translated to a pod IP address before being forwarded. 

The DROP rules that you see are meant to prevent routing loops in the case that a pod is sending traffic to a LB IP that isn't allocated, and thus doesn't get DNAT'd and would instead be sent out the default gateway.

The thing to look at here would be why isn't the kube-proxy performing DNAT on traffic destined to one of your LoadBalancer IP addresses. Is the LB IP actually allocated to one of your Kubernetes services?
