### ISSUE TITLE
calico-node-sn6nh                                        0/1     CrashLoopBackOff

### ISSUE THREAD

**Issue by lenin-netizen** [projectcalico/calico#6555]
calico-node is not ready state

## Expected Behavior
calico-node should be in ready state 

## Current Behavior
logs =>> error: You must be logged in to the server (the server has asked for the client to provide credentials ( pods/log calico-node-sn6nh))
describe => 
 Normal   Started         21m                    kubelet  Started container calico-node
  Warning  Unhealthy       21m                    kubelet  Liveness probe failed: calico/node is not ready: Felix is not live: Get "http://localhost:9099/liveness": dial tcp [::1]:9099: connect: connection refused
  Warning  Unhealthy       20m (x8 over 21m)      kubelet  Readiness probe failed: calico/node is not ready: BIRD is not ready: Error querying BIRD: unable to connect to BIRDv4 socket: dial unix /var/run/bird/bird.ctl: connect: no such file or directory
  Normal   Killing         20m                    kubelet  Container calico-node failed liveness probe, will be restarted
  Warning  Unhealthy       6m46s (x40 over 21m)   kubelet  Liveness probe failed: calico/node is not ready: bird/confd is not live: exit status 1
  Warning  BackOff         102s (x54 over 17m)    kubelet  Back-off restarting failed container

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Calico version
* Orchestrator version (e.g. kubernetes, mesos, rkt):
* Operating System and version:
* Link to your project (optional):

**Comment by lenin-netizen** [comment]
kubernetes version 1.23.5
calico version                v3.23.1

**Comment by lenin-netizen** [comment]
it was working before. this is one of the master node out of 3. i have reset and join again due to system boot issue then calio-node gone to 0/1 state. please advise

kube-system      calico-node-snxx                                        0/1     Running
kube-system      kube-apiserver-asxx1                       1/1     Running
kube-system      kube-controller-manager-asxx              1/1
kube-system      kube-proxy-sqjcr                                         1/1     Running
kube-system      kube-scheduler-asxxxx1                       1/1     Running 
metallb-system   speaker-pjz64                                            0/1     CrashLoopBackOff
monitoring       stable-prometheus-node-exporter-szqfq

**Comment by caseydavenport** [comment]
Can you post the logs from one of the failed containers?

**Comment by lmm** [comment]
I'm going to close this issue due to inactivity but please feel free to reopen.
