### ISSUE TITLE
Update references to kubeadm's "--cluster-cidr' to "--pod-network-cidr"

### ISSUE THREAD

**Issue by djosborne** [projectcalico/calico#658]
Flag was changed in recent kubeadm apparently. Our k8s datastore install doc should be updated to mention the new flag name.

**Comment by djosborne** [comment]
I think kubeadm may have changed the default value as well. We should update our 1.6 manifests to use the new one. And double check that we adequately warn people about setting the value correctly in the manifest.

**Comment by tmjd** [comment]
The k8s datastore install doc seems to be updated correctly.  There is a reference to `cluster-cidr` but that is in reference to kube-controller-manager which is still the correct flag.  The reference to kubeadm in the k8s backend has already been updated with `pod-network-cidr`.

The kubeadm docs still would benefit from some docs updates around the CIDRs used.
