### ISSUE TITLE
calico.yaml cannot be downloaded

### ISSUE THREAD

**Issue by olekszhel** [projectcalico/calico#6587]
calico.yaml cannot be downloaded using URL https://docs.projectcalico.org/manifests/calico.yaml

Request URL: https://docs.projectcalico.org/manifests/calico.yaml
Request Method: GET
Status Code: 404 
Remote Address: 35.198.80.163:443

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Calico version
* Orchestrator version (e.g. kubernetes, mesos, rkt):
* Operating System and version:
* Link to your project (optional):

**Comment by lmm** [comment]
In Calico v3.24, manifest links in the docs are now just raw links to the manifests in the Calico repo.

For the manifest you want, try: https://raw.githubusercontent.com/projectcalico/calico/v3.24.0/manifests/calico.yaml

That said, I'd still expect https://docs.projectcalico.org/manifests/calico.yaml to point to the latest release version of that manifest.

**Comment by olekszhel** [comment]
thx for link, yeah, I've also just found that I can use something like that [https://raw.githubusercontent.com/projectcalico/calico/master/manifests/calico.yaml](), but it will be better to have old link in working state, because a lot of forums and some training materials are pointing to exactly that link. JFYI yesterday [https://docs.projectcalico.org/manifests/calico.yaml](url) worked fine.

**Comment by olekszhel** [comment]
Perfect! It works now! Thanks!

**Comment by mgleung** [comment]
Hey @olekszhel , sorry for the disruption. We had some docs site refactoring and it looks like we missed a couple things during those changes. I just pushed out a fix and I think that this should be working now.
