### ISSUE TITLE
Document use of link-local address as gateway

### ISSUE THREAD

**Issue by djosborne** [projectcalico/calico#66]
_From @caseydavenport on June 17, 2016 16:20_

We set up the following routes within a container to get traffic out to the host:

```
default via 169.254.1.1 dev eth0
168.254.1.1 dev eth0
```

We should document this so that it isn't confusing / surprising to users.

_Copied from original issue: projectcalico/calico-containers#1023_

**Comment by djosborne** [comment]
_From @caseydavenport on September 19, 2016 19:53_

@djosborne giving this one to you as one to consider as part of your docs work.

**Comment by caseydavenport** [comment]
This exists in the FAQ.  Where else do we think it should go?
