### ISSUE TITLE
Improve Versioning UX

### ISSUE THREAD

**Issue by ozdanborne** [projectcalico/calico#662]
## EDIT @caseydavenport: I think this is what we've decided to do for 2.4:

- [x] Report "Calico Version" in `calicoctl version`.
- [x] Report Cluster type in `calicoctl version`.
- [x] Produce a release tar archive for each Calico release, including manifests.

## Old text:

Lots of users have trouble figuring out how the Calico versioning system works. We should improve the UX. The following are some suggestions to do so:

- [ ] Link users to the "Releases" page from the landing page
- [ ] add a page to the `/releases` category which explains how the "Calico vX.Y" versioning system works. e.g.
  - Calico components are on their own github pages and are revved and released individually
  - Calico does a regular, tested and QA'd platform release using the latest release of each subcomponent
  - For each release, manifests on the docs.pc.org site are pinned for that release
- [ ] Add to component references how you can figure out what version you are on.
  - [ ] For calico/node: `docker run quay.io/calico/node:master versions` command
  - [ ] TODO: fill in with other component

**Comment by caseydavenport** [comment]
Request: We should be producing a build artifact for each release that includes all the binaries as well as the necessary Kubernetes manifests for a given release so that people can get the manifests without having to go to docs.projectcalico.org
