### ISSUE TITLE
kubeletVolumePluginPath field missing from Installation CRD

### ISSUE THREAD

**Issue by gclawes** [projectcalico/calico#6620]
[tigera-operator v1.28.0](https://github.com/tigera/operator/releases/tag/v1.28.0), which included calico v3.24.0, added CSI driver support and the `kubeletVolumePluginPath` field in the Installation CRD.  This field is missing from the calico v3.24.0 version of this CRD for v3.24.0

It looks like this was added in this commit after the v3.24.0 release: https://github.com/projectcalico/calico/commit/a6c67dfea6ec63a02204c54a28db290c2efa6a7a

## Expected Behavior

I expected CRDs to match between `calico` and `tigera-operator`.

## Context

Discovered in: https://github.com/stevehipwell/helm-charts/issues/505

## Your Environment

* Calico version v3.24.0
* Orchestrator version (e.g. kubernetes, mesos, rkt): k3s
* Operating System and version: N/A

**Comment by caseydavenport** [comment]
Yep, this was a mistake on our end in updating the CRDs. 

As you discovered, we've added a new commit to fix it but it won't be available until v3.24.1.

In the meantime you should be able to manually patch the CRD in your cluster to include the field.

**Comment by lwr20** [comment]
Since v3.24.1 is now released, closing this.
