### ISSUE TITLE
calico-kube-controllers CrashLoopBackOff due to Liveness probe failed: Error initializing datastore...

### ISSUE THREAD

**Issue by rpacogit79** [projectcalico/calico#6642]
I have upgraded from k8s 1.19 to 1.20.
During the procedure, it was required to upgrade the cluster CNI which I did from Calico v1.3.20 to 1.3.24.
However, calico-kube-controllers keeps constantly failing.
Observed error:

 Warning  Unhealthy         24m (x3 over 25m)    kubelet            Liveness probe failed: Error initializing datastore: Get "https://10.96.0.1:443/apis/crd.projectcalico.org/v1/clusterinformations/default": dial tcp 10.96.0.1:443: i/o timeout
  Warning  Unhealthy         24m (x3 over 25m)    kubelet            Readiness probe failed: Error initializing datastore: Get "https://10.96.0.1:443/apis/crd.projectcalico.org/v1/clusterinformations/default": dial tcp 10.96.0.1:443: i/o timeout
  Warning  Unhealthy         24m                  kubelet            Liveness probe errored: rpc error: code = Unknown desc = failed to exec in container: container is in CONTAINER_EXITED state
  Normal   Started           24m (x2 over 25m)    kubelet            Started container calico-kube-controllers
  Normal   Pulled            24m (x2 over 25m)    kubelet            Container image "docker.io/calico/kube-controllers:v3.24.1" already present on machine
  Normal   Created           24m (x2 over 25m)    kubelet            Created container calico-kube-controllers
  Warning  Unhealthy         24m (x4 over 25m)    kubelet            Readiness probe failed: initialized to false
  Warning  Unhealthy         15m (x11 over 25m)   kubelet            Liveness probe failed: initialized to false
  Warning  BackOff           10m (x49 over 23m)   kubelet            Back-off restarting failed container
  Warning  DNSConfigForming  39s (x111 over 25m)  kubelet            Search Line limits were exceeded, some search paths have 

How to fix this issue?

**Comment by caseydavenport** [comment]
> Warning Unhealthy 24m (x3 over 25m) kubelet Liveness probe failed: Error initializing datastore: Get "[https://10.96.0.1:443/apis/crd.projectcalico.org/v1/clusterinformations/default](https://10.96.0.1/apis/crd.projectcalico.org/v1/clusterinformations/default)": dial tcp 10.96.0.1:443: i/o timeout

kube-controllers is failing to reach the kubernetes apiserver. You should look into why it's unable to reach the apiserver.

**Comment by coutinhop** [comment]
Closing this as inactive. Feel free to reopen if you're still having issues...

**Comment by superggn** [comment]
got the same issue, calico-kube-controller kept getting this warning, finally caused a CrashLoopBack
```
  Warning  Unhealthy               50m (x3 over 50m)     kubelet            Readiness probe failed: Error initializing datastore: Get "https://10.96.0.1:443/apis/crd.projectcalico.org/v1/clusterinformations/default": dial tcp 10.96.0.1:443: i/o timeout
```

**Comment by superggn** [comment]
BTW I installed calico through the github manifest -> calico.yaml

**Comment by thelo09** [comment]
I am also getting the same error

Readiness probe failed: Error initializing datastore: Get "https://10.96.0.1:443/apis/crd.projectcalico.org/v1/clusterinformations/default": dial tcp 10.96.0.1:443: i/o timeout

**Comment by PhirakbotDiff** [comment]
Hello everyone, I have also got the same error. 

Liveness probe failed: Error initializing datastore: Get "https://10.233.0.1:443/apis/crd.projectcalico.org/v1/clusterinformations/default": dial tcp 10.233.0.1:443: connect: no route to host

Do you have a solution for the issue above?
