### ISSUE TITLE
Impossibile   to use imagePullSecrets for tigera-operator deployment via helm install

### ISSUE THREAD

**Issue by EyalZafrani** [projectcalico/calico#6655]
seems to be possible to add the imagepullsecret for all the rest of the images, but for the deployment tigera-operator not.

## Expected Behavior
add the ability to use imagePullSecrets for tigera-operator deployment 

## Current Behavior
by specify imagePullSecrets via values files, are not working for the tigera-operator pod.

## Your Environment
calico projectcalico/tigera-operator ---version v3.21.6

**Comment by caseydavenport** [comment]
A PR was merged to fix this recently and will be available in Calico v3.25.0: https://github.com/projectcalico/calico/pull/6591
