### ISSUE TITLE
Pods cannot reach services

### ISSUE THREAD

**Issue by jw-websensa** [projectcalico/calico#6664]
After updating my on-premis cluster to 1.23 and updating calico plugin to 3.24.1 I started facing issues with connecting to pods through services.

## Expected Behavior
Pods should be able to connect to other pods through services.

## Current Behavior
Currently no connection through services is working, both through DN and IP address. 
However, pods are capable of connecting with each other directly through assigned IPs.
I also noticed error on kube-proxy side:
```
proxier.go:1484] "Failed to execute iptables-restore" err="exit status 1 (iptables-restore: line 1183 failed\n)"
```

## Possible Solution
I wish I knew

## Steps to Reproduce (for bugs)
I wish I knew

## Context
-

## Your Environment
* Calico version - 3.24.1
* Orchestrator version (e.g. kubernetes, mesos, rkt): 1.23
* Operating System and version: Ubuntu 20.04 LTS on all nodes

**Comment by noahge** [comment]
i have same problem, is any solution?

**Comment by jw-websensa** [comment]
In my case solution was quite stupid - restart the nodes
