### ISSUE TITLE
Not possible to disable IPv6 VXLAN

### ISSUE THREAD

**Issue by muff1nman** [projectcalico/calico#6670]
## Expected Behavior
When upgrading from Calico 3.22 to 3.23 (7dbb81af0c4292db09abf8a416f597e6487fb1b8), ipv6 vxlan should not be enabled by default, or if it is, there should be a way to disable it.

## Current Behavior
On upgrading to Calico 3.23 and above, Calico fails to setup IPv6 VXLAN with the following messages:
```
2022-09-06 17:17:54.882 [INFO][43] felix/route_table.go 1159: Failed to access interface because it doesn't exist. error=Link not found ifaceName="vxlan-v6.calico" ifaceRegex="^vxlan-v6.calico$" ipVersion=0x6 tableIndex=0
2022-09-06 17:17:54.882 [INFO][43] felix/route_table.go 1227: Failed to get interface; it's down/gone. error=Link not found ifaceName="vxlan-v6.calico" ifaceRegex="^vxlan-v6.calico$" ipVersion=0x6 tableIndex=0
2022-09-06 17:17:54.882 [ERROR][43] felix/route_table.go 994: Failed to get link attributes error=interface not present ifaceRegex="^vxlan-v6.calico$" ipVersion=0x6 tableIndex=0
2022-09-06 17:17:54.882 [INFO][43] felix/route_table.go 587: Interface missing, will retry if it appears. ifaceName="vxlan-v6.calico" ifaceRegex="^vxlan-v6.calico$" ipVersion=0x6 tableIndex=0
```
However, no IPv6 pools were configured with IPv6 VXLAN encapsulation. Furthermore it is not possible to disable IPv6 encapsulation, as removing `vxlanEnabled` from the `default` FelixConfiguration, leads to IPv4 VXLAN encapsulation being broken. This is contrary to the documentation which states this about `vxlanEnabled`:
```
Optional, you shouldn’t need to change this setting as Felix calculates if VXLAN should be enabled based on the existing IP Pools. When set, this overrides whether Felix should create the VXLAN tunnel device for VXLAN networking.
```

## Possible Solutions
- Decouple vxlanEnabled from vxlan6Enabled ( #6671 has been commandeered to go down this route)
- ~Only have `vxlanEnabled` be a field to override the ippools to Enabled. Setting it to Never would have no effect if the ippols have vxlanMode enabled. (#6671 explores this idea)~
- Instead focus on fixing why vxlan-v6.calico interface is having issues

## Steps to Reproduce (for bugs)
Configure calico with one ipv4 pool with vxlan encapsulation, and an ipv6 ippool without.

**Comment by caseydavenport** [comment]
Interesting. The intended behavior here was that you could eventually delete the `vxlanEnabled` field from FelixConfiguration because Felix would detect this from the v4 pools instead. 

Removing the field from the deafault felixconfig shouldn't break v4 VXLAN, so I'm currently thinking that is the primary bug here.

I thought we also agreed vxlanEnabled would be v4 only and shouldn't impact v6 enablement at all... but maybe I'm misremembering. @coutinhop do you recall?

**Comment by coutinhop** [comment]
@muff1nman what do your IP pools look like? I just wanted to better understand the issue you're having, as in my understanding, this should work:
- removing vxlanEnabled from FelixConfig entirely
- have vxlanMode set to 'Always' or 'CrossSubnet' in at least one v4 IP pool
- have vxlanMode set to 'Never' on any and every v6 IP pool

When you say IIPv4 VXLAN is broken if you remove 'vxlanEnabled' from FelixConfig, what exactly is happening?

**Comment by coutinhop** [comment]
@caseydavenport Yes I remember we did talk about decoupling the 'vxlanEnabled' FelixConfig from IPv6 (with the reasoning being that it does not need any kind of override or backwards compatibility). I'm sorry I got side tracked and ended up not doing that yet. I'll try to make sure with @muff1nman that doing that would solve this issue.

**Comment by muff1nman** [comment]
Here is the working 3.22.x resources with a couple redactions:

```
apiVersion: v1
items:
- apiVersion: crd.projectcalico.org/v1
  kind: FelixConfiguration
  metadata:
    generation: 4
    name: default
  spec:
    bpfLogLevel: ""
    logSeverityScreen: Info
    reportingInterval: 0s
    vxlanEnabled: true
- apiVersion: crd.projectcalico.org/v1
  kind: IPPool
  metadata:
    name: k8s-ipv6
  spec:
    blockSize: 122
    cidr: foo:bar::/64
    disabled: false
    ipipMode: Never
    natOutgoing: false
    nodeSelector: all()
- apiVersion: crd.projectcalico.org/v1
  kind: IPPool
  metadata:
    generation: 1
    name: k8s-shared-ipv4
  spec:
    blockSize: 26
    cidr: 172.18.0.0/16
    disabled: false
    natOutgoing: true
    nodeSelector: all()
    vxlanMode: Always
kind: List
metadata:
  resourceVersion: ""
```

The following was done to attempt to turn off ipv6 vxlan (i.e. deleted the vxlanEnabled field):
```
kubectl edit felixconfiguration default --output-patch
Patch: {"spec":{"vxlanEnabled":null}}
felixconfiguration.crd.projectcalico.org/default edited
```

This resulted in all of the ipv4 vxlan being disabled (interfaces removed).

**Comment by muff1nman** [comment]
Actually I'm realizing an additional complication. The change for the felixconfiguration was done when calico-node was still 3.22.x. Because I wasn't able to upgrade calico-node to 3.23.x due to vxlan-v6 causing problems, the idea was to drop that field first with calico 3.22.x and then upgrade. That might not be possible with a lot of the recent changes in this area missing on the 3.22 branch? So potentially I might need to try backporting some of these changes to 3.22?

**Comment by muff1nman** [comment]
> Yes I remember we did talk about decoupling the 'vxlanEnabled' FelixConfig from IPv6 (with the reasoning being that it does not need any kind of override or backwards compatibility

I think that would be awesome.

**Comment by coutinhop** [comment]
@muff1nman the changes that make Felix use IP pools to determine encapsulation and add IPv6 VXLAN support went into calico v3.23. Prior to that, enabling say VXLAN in an IP pool would add 'vxlanEnabled' to the default FelixConfig (but disabling it wouldn't remove it).

So I think the best way to proceed with a v3.22 -> v3.23 upgrade is to have VXLAN enabled in the IP pool, then upgrade, then remove it from FelixConfig... Could you try that and let me know if it works?

**Comment by muff1nman** [comment]
> a v3.22 -> v3.23 upgrade is to have VXLAN enabled in the IP pool, then upgrade

@coutinhop  That was the initial attempt, but the new calico-node was not coming up correctly with the errors mentioned in the description
