### ISSUE TITLE
Calico node crash loop - failed - error: command '/bin/calico-node -shutdown' exited with 137

### ISSUE THREAD

**Issue by kart2** [projectcalico/calico#6677]
## Expected Behavior
calico version 3.20.0 installed via tigera operator and expects all calico pods should be healthy

## Current Behavior
Out of 400 pods always 3 or 2 goes to crash loop back

Events:
  Type     Reason             Age                  From               Message
  ----     ------             ----                 ----               -------
  Normal   Scheduled          25m                  default-scheduler  Successfully assigned calico-system/calico-node-9w5nz to ip-192-168-82-236.us-west-2.compute.internal
  Normal   Created            25m                  kubelet            Created container flexvol-driver
  Normal   Pulled             25m                  kubelet            Container image "quay.io/calico/pod2daemon-flexvol:v3.20.0" already present on machine
  Normal   Started            25m                  kubelet            Started container flexvol-driver
  Normal   Killing            24m                  kubelet            Container calico-node failed liveness probe, will be restarted
  Warning  FailedPreStopHook  24m                  kubelet            Exec lifecycle hook ([/bin/calico-node -shutdown]) for Container "calico-node" in Pod "calico-node-9w5nz_calico-system(5d90750c-0a3b-4ecc-baf4-72f077dc2ec1)" failed - error: command '/bin/calico-node -shutdown' exited with 137: , message: ""
  Warning  Unhealthy          24m                  kubelet            Readiness probe failed: OCI runtime exec failed: exec failed: container_linux.go:380: starting container process caused: process_linux.go:130: executing setns process caused: exit status 1: unknown
  Normal   Pulled             24m (x2 over 25m)    kubelet            Container image "quay.io/calico/node:v3.20.0" already present on machine
  Normal   Created            24m (x2 over 24m)    kubelet            Created container calico-node
  Normal   Started            24m (x2 over 24m)    kubelet            Started container calico-node
  Warning  Unhealthy          23m (x2 over 24m)    kubelet            Readiness probe errored: rpc error: code = Unknown desc = container not running (ac7e077c7669dc1ca6cff5abcc4d167a7d3fd0a848d740d46d838265f4ce26b6)
  Warning  Unhealthy          23m (x5 over 24m)    kubelet            Liveness probe failed: Get "http://localhost:9099/liveness": dial tcp 127.0.0.1:9099: connect: connection refused
  Warning  Unhealthy          5m1s (x39 over 24m)  kubelet            Readiness probe failed:
  Warning  BackOff            3s (x55 over 16m)    kubelet            Back-off restarting failed container

## Your Environment

* Calico version - v3.20.0
* Orchestrator version (e.g. kubernetes, mesos, rkt): EKS 1.20
* Operating System and version: Ubuntu

**Comment by mgleung** [comment]
@kart2 out of curiosity, do the pods in CrashLoopBackoff eventually come back up? I just want to clarify that the 2-3 pods that are in CrashLoopBackoff are a rotating set rather than the same pods being stuck.

**Comment by kart2** [comment]
@mgleung they are rotating. I have delete the node where it runs and a new node comes up with health calico node. Later i observe a failure in another node.
```NAME          DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR            AGE
calico-node   443       443       438     443          438         kubernetes.io/os=linux   20d```

**Comment by mgleung** [comment]
@kart2 , is it possible to get the logs from one of the pods that is stuck in `CrashLoopBackoff`? It sounds like they only rotate when you delete the node so hopefully we can get some logs that might help us pin down the issue.

**Comment by kart2** [comment]
Thanks for following up @mgleung . One of our service pod was taking up lot of memory and kicking out calico pod from the node. After fixing the memory constraint on pod, the issue was resovled.
