### ISSUE TITLE
calico combine with fd.io vpp?

### ISSUE THREAD

**Issue by ZYecho** [projectcalico/calico#668]
Hello,
I saw a post here https://www.projectcalico.org/celebrating-two-milestone-releases/ which said the calico grows interest to use alternate data planes include vpp. But I didn't see anything about it in version2.1, does this happen?

**Comment by djosborne** [comment]
Calico 2.1 added an abstraction layer for its dataplane which opens the door to alternate dataplane drivers. But unfortunately there hasn't been any publicly viewable progress on a VPP plugin by fd.io for it.

**Comment by ZYecho** [comment]
thanks a lot~

**Comment by tmjd** [comment]
I think this issue is answered so I'm going to close the issue.  @ZYecho if there are more questions around this feel free to reopen.
