### ISSUE TITLE
How to disable pod security policy creation from tigera-operator

### ISSUE THREAD

**Issue by mo-saeed** [projectcalico/calico#6681]
As pod security policy is deprecated, we want to clean up the whole resources related to pod security policy

- policies 
```
calico-apiserver          false          RunAsAny   RunAsAny           MustRunAs   MustRunAs   false            configMap,emptyDir,projected,secret,downwardAPI,persistentVolumeClaim,hostPath
calico-kube-controllers   false          RunAsAny   MustRunAsNonRoot   MustRunAs   MustRunAs   false            configMap,emptyDir,projected,secret,downwardAPI,persistentVolumeClaim
calico-node               true           RunAsAny   RunAsAny           MustRunAs   MustRunAs   false            configMap,emptyDir,projected,secret,downwardAPI,persistentVolumeClaim,hostPath
calico-typha              false          RunAsAny   MustRunAsNonRoot   MustRunAs   MustRunAs   false            configMap,emptyDir,projected,secret,downwardAPI,persistentVolumeClaim
```
- roles ?
- rolebindings ?

I tried to find my answer here https://projectcalico.docs.tigera.io/reference/installation/api but couldn't find it.

I would appreciate your help. Thanks a lot in advance

**Comment by caseydavenport** [comment]
If you run the latest (v1.28) release of the tigera-operator, it will conditionally program PSPs based on whether or not the cluster has API support for them (and also programs pod security standards labels on namespaces it creates)

**Comment by mo-saeed** [comment]
Hi @caseydavenport 

Thank you for your answer. we are using this https://github.com/projectcalico/calico/tree/master/charts/tigera-operator to install tigera-operator.

I disabled pod security policy from the admission of the API but still the pod security policies are created.

**Comment by mo-saeed** [comment]
Hi @caseydavenport Thank you for your reply.

Unfortunately, we can't change the version of the tigera-operator to the latest coz it's controlled by azure and right now we have version 1.23.
any other way to disable the psp in this case ?

**Comment by caseydavenport** [comment]
Afraid there is not a way to do that without an upgrade. Probably need the Azure team to upgrade the version of Calico they are installing.

**Comment by puneetloya** [comment]
@caseydavenport question about what the behavior is going to be in a upgrade kubernetes cluster from 1.24 -> 1.25 and I have an instance of tigera operator/calico instances already installed(latest version). What would the operator do in that case?

From the code and your explanation its not going to use PSPs in that case but are there going to be equivalent PSA and PSS ?

**Comment by caseydavenport** [comment]
Yes, newer versions of the operator install pod security standard annotations on all of the namespaces that it creates, so it should be a seamless upgrade.

Just make sure you upgrade the operator first, and then your kubernetes cluster, to make sure you're on a version with PSS support. You should see the annotations on the namespaces already, even if your cluster supports PSPs still.
