### ISSUE TITLE
Private container registry containers authentication required

### ISSUE THREAD

**Issue by Pacobart** [projectcalico/calico#6691]
## Expected Behavior
When pulling a container from a private repository, one should specify `imagePullSecrets`. 

## Current Behavior
This parameter is missing from the tigera-operator deployment. Therefore, the image is never pulled and errors.

## Possible Solution
Add `imagePullSecrets` to `spec` in deployment.

**Comment by caseydavenport** [comment]
As mentioned on this PR, a fix for this was already merged to master here: https://github.com/projectcalico/calico/pull/6591
