### ISSUE TITLE
node-driver-registrar missing from documentation

### ISSUE THREAD

**Issue by Re4zOon** [projectcalico/calico#6694]
Add node-driver-registrar to the documentation:
https://projectcalico.docs.tigera.io/maintenance/image-options/alternate-registry

Sadly I wasn't able to figure out where the "site" variables are stored for the template:
https://github.com/projectcalico/calico/blob/master/calico/maintenance/image-options/alternate-registry.md#how-to

**Comment by Josh-Tigera** [comment]
You're right the documentation should contain the node-driver-registrar image. For your second link that's simply the template used to generate an actual viewable webpage that shouldn't contain `{{site.prodname}}`. See here for a correctly rendered page:
https://projectcalico.docs.tigera.io/maintenance/image-options/alternate-registry

**Comment by Re4zOon** [comment]
Hi,

When will it be visible on the website?

**Comment by Josh-Tigera** [comment]
Hi @Re4zOon,

It is visible today if you look at the ["nightly" version of the docs](https://projectcalico.docs.tigera.io/master/maintenance/image-options/alternate-registry), however it won't be visible with version "Version 3.24" until the next rebuild is released which I'm not sure about the exact timing, but is currently being worked on.
