### ISSUE TITLE
Release 3.24.2 to include helm chart fixes

### ISSUE THREAD

**Issue by Pacobart** [projectcalico/calico#6709]
## Expected Behavior

We need to install the tigera-operator helm chart using a private container registry. Currently, this doesn't support a regcred. The following Pull Request added this feature. We need this added to release to consume
https://github.com/projectcalico/calico/pull/6591

**Comment by caseydavenport** [comment]
CC @mgleung - release lead. 

We'd need to backport that PR before cutting the release.

**Comment by Pacobart** [comment]
> CC @mgleung - release lead.
> 
> We'd need to backport that PR before cutting the release.

Any update to cutting a release with this functionality?

**Comment by mgleung** [comment]
@Pacobart , there's one last bug that we're waiting on that's needed in v3.24.2. My estimate is that this will be done by early next week.
