### ISSUE TITLE
Missing libnss_files causes localhost lookup issues in calico/typha:v3.24.1

### ISSUE THREAD

**Issue by wdoekes** [projectcalico/calico#6710]
In `calico/typha:v3.24.1` docker image, there are only a handful libs in /lib64.
In `calico/typha:v3.23.3` there are a bunch more.

The lack of libnss_files causes localhost to get searched, which unfortunately resulted in a * CNAME being matched, causing localhost not to be 127.0.0.1.

## Expected Behavior

`/etc/hosts` should be read by libc.

## Current Behavior

If `/etc/resolv.conf` does not contain any `options`, things are fine:
- `/etc/hosts` is read
- `libnss_dns` is called (if needed)

If `/etc/resolv.conf` does contain any `options`, things break:
- `/etc/hosts` is NOT read
- `libnss_files` is tried but is unavailable in v3.24.1
- `libnss_dns` is called

This means that we got totally the wrong answer for `localhost` because it got translated to `localhost.nodedomain.` and that was a CNAME which resolved to REMOTE_IP.

This resulted in the health check not being able to bind on that remote IP:
```
health.go 296: Health endpoint failed, trying to restart it... error=listen tcp REMOTE_IP:9098: bind: cannot assign requested address
```

## Possible Solution

Add more `libnss_*` here:
https://github.com/projectcalico/calico/blob/65368ae5cf3abd20297a8226b6d94f9f1caf4b34/typha/docker-image/Dockerfile.amd64#L46-L50

Especially everything that you've put here:
https://github.com/projectcalico/calico/blob/65368ae5cf3abd20297a8226b6d94f9f1caf4b34/typha/docker-image/nsswitch.conf
```
hosts: files mdns4_minimal [NOTFOUND=return] dns mdns4
```

Available in `registry.access.redhat.com/ubi8/ubi-minimal:8.6` are:
```
/lib64/libnss_compat.so.2
/lib64/libnss_dns.so.2
/lib64/libnss_files.so.2
/lib64/libnss_myhostname.so.2
/lib64/libnss_resolve.so.2
/lib64/libnss_systemd.so.2
```
I don't see any mdns4 or mdns4_minimal there, so you can drop those from nsswitch.conf.

## Example with no options in resolv.conf
```
[pid   106] 14:42:42.686147 openat(AT_FDCWD, "/etc/nsswitch.conf", O_RDONLY|O_CLOEXEC) = 8
[pid   106] 14:42:42.686896 openat(AT_FDCWD, "/etc/resolv.conf", O_RDONLY|O_CLOEXEC) = 8
[pid   106] 14:42:42.688016 openat(AT_FDCWD, "/etc/hosts", O_RDONLY|O_CLOEXEC) = 8
```

## Example with options in resolv.conf
```
[pid    20] 14:44:09.527134 openat(AT_FDCWD, "/etc/nsswitch.conf", O_RDONLY|O_CLOEXEC) = 9
[pid    20] 14:44:09.527487 openat(AT_FDCWD, "/etc/resolv.conf", O_RDONLY|O_CLOEXEC) = 8
[pid    20] 14:44:09.528578 connect(8, {sa_family=AF_UNIX, sun_path="/var/run/nscd/socket"}, 110 <unfinished ...>
[pid    20] 14:44:09.528728 <... connect resumed>) = -1 ENOENT (No such file or directory)
[pid    20] 14:44:09.528894 connect(8, {sa_family=AF_UNIX, sun_path="/var/run/nscd/socket"}, 110) = -1 ENOENT (No such file or directory)
[pid    20] 14:44:09.529206 openat(AT_FDCWD, "/etc/nsswitch.conf", O_RDONLY|O_CLOEXEC) = 8
[pid    20] 14:44:09.529464 openat(AT_FDCWD, "/etc/host.conf", O_RDONLY|O_CLOEXEC <unfinished ...>
[pid    20] 14:44:09.529527 <... openat resumed>) = 9
[pid    20] 14:44:09.529891 openat(AT_FDCWD, "/etc/resolv.conf", O_RDONLY|O_CLOEXEC) = 9
[pid    20] 14:44:09.530362 openat(AT_FDCWD, "/lib64/libnss_files.so.2", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
[pid    20] 14:44:09.530477 openat(AT_FDCWD, "/usr/lib64/tls/x86_64/x86_64/libnss_files.so.2", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
[pid    20] 14:44:09.530643 openat(AT_FDCWD, "/usr/lib64/tls/x86_64/libnss_files.so.2", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
[pid    20] 14:44:09.530811 openat(AT_FDCWD, "/usr/lib64/tls/x86_64/libnss_files.so.2", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
[pid    20] 14:44:09.530923 openat(AT_FDCWD, "/usr/lib64/tls/libnss_files.so.2", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
[pid    20] 14:44:09.531118 openat(AT_FDCWD, "/usr/lib64/x86_64/x86_64/libnss_files.so.2", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
[pid    20] 14:44:09.531422 openat(AT_FDCWD, "/usr/lib64/x86_64/libnss_files.so.2", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
[pid    20] 14:44:09.531631 openat(AT_FDCWD, "/usr/lib64/x86_64/libnss_files.so.2", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
[pid    20] 14:44:09.531914 openat(AT_FDCWD, "/usr/lib64/libnss_files.so.2", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
[pid    20] 14:44:09.532139 openat(AT_FDCWD, "/lib64/libnss_mdns4_minimal.so.2", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
[pid    20] 14:44:09.532312 openat(AT_FDCWD, "/lib64/libnss_dns.so.2", O_RDONLY|O_CLOEXEC) = 8
[pid    20] 14:44:09.532727 openat(AT_FDCWD, "/lib64/libresolv.so.2", O_RDONLY|O_CLOEXEC) = 8
```

## Context

Spent most of the day investigating why some hosts had localhost resolve to a remote IP while others didn't.

- Only some hosts had a domain that had a working `localhost.domain.` that resolved to something.
- Only some hosts had `options` in `/etc/resolv.conf`.

## Your Environment

* Calico version: calico/typha:v3.24.1 on amd64
* Orchestrator version: k8s
* Operating System and version: ubuntu

Cheers,
Walter Doekes
OSSO B.V.

P.S. I haven't yet seen where libc chooses between reading /etc/hosts and delegating to nss; but in my tests that appeared to depend solely on "options whatever" being present in resolv.conf.

**Comment by wdoekes** [comment]
## Reproducing

`test.sh`
```sh
#!/bin/sh
echo 'multi on' > /etc/host.conf

echo 'hosts: files mdns4_minimal [NOTFOUND=return] dns mdns4' > /etc/nsswitch.conf

domain=$(cat /etc/hostname | sed -e 's/^[^.]*\.//') && \
printf '%s\n' '127.0.0.2 localhost' "127.0.0.3 localhost.$domain" >/etc/hosts

sed -e '/^nameserver/!d' /etc/resolv.conf > /tmp/x
( cat /tmp/x; echo '# search minion.nl'; echo '# options whatever' ) > /etc/resolv.conf

cp /lib64/libnss_files* /tmp/

tail -n100 /etc/host.conf /etc/nsswitch.conf /etc/hostname /etc/hosts /etc/resolv.conf
echo

set_libnss_files() {
    if test $1 -eq 1; then cp /tmp/libnss* /lib64/
    else rm /lib64/libnss_files*; fi; }
set_options() {
    sed -e '/^options/d' /etc/resolv.conf >/tmp/x; cat /tmp/x >/etc/resolv.conf
    test $1 -eq 1 && echo 'options whatever' >>/etc/resolv.conf; }
set_search() {
    sed -e '/^search/d' /etc/resolv.conf >/tmp/x; cat /tmp/x >/etc/resolv.conf
    test $1 -eq 1 && echo 'search minion.nl' >>/etc/resolv.conf; }

for options in 0 1; do
    for search in 0 1; do
	for libnss_files in 0 1; do
	    set_libnss_files $libnss_files
	    set_options $options
	    set_search $search
	    printf '%-16s  %s\n' "$(echo $(/typhatest))" \
		"<-- opt=$options search=$search libnss_files=$libnss_files"
	done
    done
done
```
`Dockerfile`
```docker
FROM golang AS builder
RUN printf '%s\n' \
    'package main' \
    'import "fmt"' \
    'import "net"' \
    'func main() {' \
    '  addrs, _ := net.LookupHost("localhost")' \
    '  for _, a := range addrs {' \
    '    fmt.Println(a)' \
    '  }' \
    '}' > typhatest.go
RUN go build typhatest.go && mv typhatest /
RUN go version >/typhatest.golang

FROM registry.access.redhat.com/ubi8/ubi-minimal:8.6
COPY --from=builder /typhatest* /
COPY test.sh /
CMD cat /typhatest.golang && echo && sh /test.sh
```
## Output
`docker build -t tmp . && docker run --network=host -it tmp`
```
go version go1.19.1 linux/amd64

==> /etc/host.conf <==
multi on

==> /etc/nsswitch.conf <==
hosts: files mdns4_minimal [NOTFOUND=return] dns mdns4

==> /etc/hostname <==
walter-tretton.kiwi

==> /etc/hosts <==
127.0.0.2 localhost
127.0.0.3 localhost.kiwi

==> /etc/resolv.conf <==
nameserver 127.0.0.53
# search minion.nl
# options whatever

127.0.0.2         <-- opt=0 search=0 libnss_files=0
127.0.0.2         <-- opt=0 search=0 libnss_files=1
127.0.0.2         <-- opt=0 search=1 libnss_files=0
127.0.0.2         <-- opt=0 search=1 libnss_files=1
::1 127.0.0.1     <-- opt=1 search=0 libnss_files=0
127.0.0.2         <-- opt=1 search=0 libnss_files=1
127.255.255.255   <-- opt=1 search=1 libnss_files=0
127.0.0.2         <-- opt=1 search=1 libnss_files=1
```
This list here shows the different behaviours between the options mentioned: *generally it works,* but not if some system decides to search-domain AND there is no libnss_files* AND options is set.

**Comment by wdoekes** [comment]
Actually, I wonder what the point is of using nsswitch libraries if you're overwriting the configuration anyway :thinking: 

If you're using a prefabricated nsswitch, you're in fact doing: (1) prefer /etc/hosts, (2) read dns from the recursors in resolv.conf.

*Isn't that the same behaviour that CGO_ENABLED=0 would provide?*

If we rebuild `typhatest` above with `CGO_ENABLED=0`, we get this:
```
127.0.0.2         <-- opt=0 search=0 libnss_files=0
127.0.0.2         <-- opt=0 search=0 libnss_files=1
127.0.0.2         <-- opt=0 search=1 libnss_files=0
127.0.0.2         <-- opt=0 search=1 libnss_files=1
127.0.0.2         <-- opt=1 search=0 libnss_files=0
127.0.0.2         <-- opt=1 search=0 libnss_files=1
127.0.0.2         <-- opt=1 search=1 libnss_files=0
127.0.0.2         <-- opt=1 search=1 libnss_files=1
```
100% success rate from /etc/hosts. And regular dns lookups, including `search` domains still work.

**Comment by wdoekes** [comment]
... and for those who wonder about that `options whatever` changing the behaviour. Apparently that is (also) due to the modified nsswitch:
```
==> /etc/nsswitch.conf <==
hosts: files dns
...
127.0.0.2         <-- opt=0 search=0 libnss_files=0
127.0.0.2         <-- opt=0 search=0 libnss_files=1
127.0.0.2         <-- opt=0 search=1 libnss_files=0
127.0.0.2         <-- opt=0 search=1 libnss_files=1
127.0.0.1 ::1     <-- opt=1 search=0 libnss_files=0
127.0.0.2         <-- opt=1 search=0 libnss_files=1
127.255.255.255   <-- opt=1 search=1 libnss_files=0
127.0.0.2         <-- opt=1 search=1 libnss_files=1
```
On my current Ubuntu it says `files resolve dns`:
```
==> /etc/nsswitch.conf <==
hosts: files resolve dns
...
127.0.0.1 ::1     <-- opt=0 search=0 libnss_files=0
127.0.0.2         <-- opt=0 search=0 libnss_files=1
127.255.255.255   <-- opt=0 search=1 libnss_files=0
127.0.0.2         <-- opt=0 search=1 libnss_files=1
127.0.0.1 ::1     <-- opt=1 search=0 libnss_files=0
127.0.0.2         <-- opt=1 search=0 libnss_files=1
127.255.255.255   <-- opt=1 search=1 libnss_files=0
127.0.0.2         <-- opt=1 search=1 libnss_files=1
```
That leads to less erratic behaviour.

In short: _if you're touching nsswitch.conf from a docker setup, you're probably doing things wrong._

**Comment by wdoekes** [comment]
Ah, I finally see where that "options" difference comes from:

- https://github.com/golang/go/blob/81efd7b347dd6d7f12fd49c6eee0274005734c71/src/net/dnsconfig_unix.go#L78-L125 likely the setting of `unknownOpt`, along with 
- https://github.com/golang/go/blob/c3aac6c010f9293319ae5dbe0592bc7706b6a161/src/net/conf.go#L159 different behaviour based on that setting.

Apparently golang will decide at runtime whether to use libc or not for the resolving. This can be forced with `GODEBUG=netdns=go` (for golang-dns) during runtime.

I also realise what a big compatibility mess conf.go is, so I'll retract my words about using CGO_ENABLED=0 as best workaround :upside_down_face:

**Comment by snowmanstark** [comment]
@wdoekes @caseydavenport, Is there any reason that this change was not added to [Dockerfile.arm64](https://github.com/projectcalico/calico/blob/master/typha/docker-image/Dockerfile.arm64)

**Comment by wdoekes** [comment]
I guess this:

![image](https://github.com/projectcalico/calico/assets/1225014/75750334-e0b7-435c-984b-0cf8a13f52ba)

Where the breakage was introduced in Dockerfile.amd64, in 297d417c72f96de3ea4337e03a7ffe0df2b8b1ca, it was never explicitly broken in Dockerfile.arm64:

![image](https://github.com/projectcalico/calico/assets/1225014/fbecc303-e34f-447e-86ac-cee23f1b13a2)

I see no copying of /lib* in https://github.com/ossobv/calico/blob/master/typha/docker-image/Dockerfile.arm64 -- so I wouldn't know what change to add.

If you're missing libs, you should visit the ticket that generated this: bdc3dbd866dff782d44bafcf2f38e4e9f0528025

This only concerns the regression after 297d417c72f96de3ea4337e03a7ffe0df2b8b1ca.

**Comment by snowmanstark** [comment]
Thanks @wdoekes for the info. I see that there are a lot of differences between the amd64 and the other archs Dockerfiles. I think I should file an issue to have them updated.
