### ISSUE TITLE
FailedCreatePodSandBox when scheduling pods

### ISSUE THREAD

**Issue by thandrade830** [projectcalico/calico#6716]
Hi,

I'm getting errors from pods on nodes that were recently inserted into kubernetes.

Logs error:

Normal SandboxChanged  9m30s (x183 over 6h15m)  kubelet  Pod sandbox changed, it will be killed and re-created.

Warning  FailedCreatePodSandBox  2m1s kubelet  Failed to create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container "5d8c43f3b8179b87e01a6740a92bf485fe95cb16ca310e0c853ef731197f302b" network for pod "restic-2jsjf": networkPlugin cni failed to set up pod "restic-2jsjf_psc-velero" network: error getting ClusterInformation: Get "https://[10.43.0.1]:443/apis/crd.projectcalico.org/v1/clusterinformations/default": dial tcp 10.43.0.1:443: i/o timeout

* Calico version: v3.16.5
* Orchestrator version: Kubernetes: v1.19.10
* Operating System and version: SUSE Linux Enterprise Server 15 SP3

**Comment by caseydavenport** [comment]
> Calico version: v3.16.5

This is a very old version of Calico / Kubernetes. Could you please try upgrading and letting us know if you still see this?

v3.16 is no longer in support, so I'm going to close this, but please re-open if you are able to reproduce this on a modern version of Calico.
