### ISSUE TITLE
Proposal: hypercalico image

### ISSUE THREAD

**Issue by bradbeam** [projectcalico/calico#672]
I'd like to propose creating a calico container that is similar to hyperkube. Something that would contain all of the components that make up a calico release. I think this would help address the version sprawl and inconsistencies with calico versioning. For example, calico v2.1.2 really doesn't mean anything by itself, you need to reference a table to look up each individual component. I could be up to date with calico/node, but lagging behind on the policy container.

**Comment by bradbeam** [comment]
Relates to https://github.com/projectcalico/calico/issues/662

**Comment by caseydavenport** [comment]
CC @tomdee

**Comment by ozdanborne** [comment]
As per #864, a tarball containing all release artifacts can be produced by running `make release-artifact`.

That release artifact will be attached to the next release as it has been added to the release steps of #898.

Therefore, I am going to close this issue as fixed.
