### ISSUE TITLE
Flannel to calico migration is failing 

### ISSUE THREAD

**Issue by RishabhSharma-00** [projectcalico/calico#6745]
With version v0.19.0+ flannel install Daemonset kube-flannel-ds in kube-flannel. The migration job is not able to detect flannel daemonset since it is only looking in kube-system namespace.

 flannel-migration logs:
`$ kubectl logs -f flannel-migration-jgqbz -n kube-flannel
2022-09-21 07:35:51.785 [INFO][1] main.go 103: Loaded configuration from environment config=&config.Config{LogLevel:"info", WorkloadEndpointWorkers:1, ProfileWorkers:1, PolicyWorkers:1, NodeWorkers:1, Kubeconfig:"", DatastoreType:"kubernetes"}
W0921 07:35:51.786064       1 client_config.go:617] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
2022-09-21 07:35:51.786 [INFO][1] main.go 127: Ensuring Calico datastore is initialized
2022-09-21 07:35:51.796 [INFO][1] main.go 153: Calico datastore is initialized
2022-09-21 07:35:51.796 [INFO][1] main.go 176: Loaded Flannel configuration from environment flannelConfig=&flannelmigration.Config{FlannelNetwork:"", FlannelIpv6Network:"", FlannelDaemonsetName:"kube-flannel-ds", FlannelMTU:0, FlannelIPMasq:true, FlannelSubnetLen:24, FlannelIpv6SubnetLen:64, FlannelAnnotationPrefix:"flannel.alpha.coreos.com", FlannelVNI:1, FlannelPort:8472, CalicoDaemonsetName:"calico-node", CniConfigDir:"/etc/cni/net.d", PodNodeName:"c07-cnf-vm-14", FlannelSubnetEnv:"", DebugWaitBeforeExit:0, DebugWaitBeforeStart:0, DefaultIppoolSize:26, DefaultIppoolSizeV6:122}
2022-09-21 07:35:51.796 [INFO][1] main.go 207: Starting status report routine
2022-09-21 07:35:51.796 [INFO][1] main.go 501: Starting controller ControllerType="FlannelMigration"
2022-09-21 07:35:51.796 [INFO][1] migration_controller.go 155: Starting Migration controller
2022-09-21 07:35:51.799 [INFO][1] migration_controller.go 333: Daemonset kube-flannel-ds not exists, no migration process is needed.
2022-09-21 07:35:51.800 [INFO][1] migration_controller.go 144: No migration needed. Stopping migration controller.`

kubectl get po -A output-
`kubectl get po -A

> NAMESPACE      NAME                                       READY   STATUS      RESTARTS   AGE
kube-flannel   kube-flannel-ds-9ftd9                      1/1     Running     0          20m
kube-flannel   kube-flannel-ds-c66t9                      1/1     Running     0          20m
kube-flannel   kube-flannel-ds-t99vz                      1/1     Running     0          20m
kube-system    calico-kube-controllers-6799f5f4b4-7snj8   1/1     Running     0          2m45s
kube-system    coredns-6d4b75cb6d-7qvkt                   1/1     Running     0          20m
kube-system    coredns-6d4b75cb6d-kkps2                   1/1     Running     0          20m
kube-system    etcd-c07-cnf-vm-13                         1/1     Running     0          21m
kube-system    flannel-migration-w8bhv                    0/1     Completed   0          2m25s
kube-system    kube-apiserver-c07-cnf-vm-13               1/1     Running     0          21m
kube-system    kube-controller-manager-c07-cnf-vm-13      1/1     Running     0          21m
kube-system    kube-proxy-2zxcz                           1/1     Running     0          20m
kube-system    kube-proxy-z2qp2                           1/1     Running     0          20m
kube-system    kube-proxy-zx2qj                           1/1     Running     0          20m
kube-system    kube-scheduler-c07-cnf-vm-13               1/1     Running     0          21m

`
kubectl get no -A

> > kubectl get no -A -owide
> NAME            STATUS   ROLES           AGE   VERSION   INTERNAL-IP    EXTERNAL-IP   OS-IMAGE             KERNEL-VERSION      CONTAINER-RUNTIME
> c07-cnf-vm-13   Ready    control-plane   64m   v1.24.4   10.170.6.106   <none>        Ubuntu 20.04.5 LTS   5.4.0-126-generic   containerd://1.5.9
> c07-cnf-vm-14   Ready    <none>          63m   v1.24.4   10.170.6.107   <none>        Ubuntu 20.04.5 LTS   5.4.0-126-generic   containerd://1.5.9
> c07-cnf-vm-15   Ready    <none>          63m   v1.24.4   10.170.6.108   <none>        Ubuntu 20.04.5 LTS   5.4.0-126-generic   containerd://1.5.9

## Expected Behavior

Flannel to Calcio migration should be successful.

## Current Behavior

Flannel to calico migration is failing 

## Possible Solution

Migration job should not be hardcoded with kube-system namespace for detecting flannel Daemonset kube-flannel-ds.

## Steps to Reproduce (for bugs)

1. Install Flannel (https://raw.githubusercontent.com/flannel-io/flannel/v0.19.2/Documentation/kube-flannel.yml) version v0.19.2
2. Do migration from Flannel to calico with mentioned steps in Calico official document https://projectcalico.docs.tigera.io/getting-started/kubernetes/flannel/migration-from-flannel

## Context

Not able to migrate from flannel to calico.

## Your Environment

* Orchestrator version (e.g. kubernetes, mesos, rkt): kubernetes version - v1.24.4
* Operating System and version: Ubuntu 20.04.5 LTS

**Comment by abhinand5** [comment]
@RishabhSharma-00 @coutinhop @caseydavenport 

I am also facing the same problem. Is there any immediate workaround for this or should I wait for a fix?

**Comment by caseydavenport** [comment]
Fix for this is to update the configuration and add a configuration option here: https://github.com/projectcalico/calico/blob/master/kube-controllers/pkg/controllers/flannelmigration/config.go#L34

Right now I don't think there's a workaround - we'll need to make a minor code change. I would be happy to review a PR to do this.

**Comment by nisc-acooper** [comment]
Is there any progress made on this? Looking at the config.go, there appears to be no way to set the namespace to look in for the flannel daemonset.  We were just about to kick this migrator off, but doing some research, we identified this as a blocker since we are using flannel v0.20.1

It would appear the minor code change required would be to move the hard coded flannel namespace into the config map, maintaining the current hard coded value as default.   My concern is that there may be other changes on the flannel side that need to be qualified through this migration process.  Based on the current issue, it would appear this migration was never tested on a flannel install beyond 0.19

**Comment by nisc-acooper** [comment]
I have a prelim diff for what I think this needs to succeed.  I am working through local build issues (make image is failing on MacOS Monterey 12.6). https://github.com/projectcalico/calico/compare/master...nisc-acooper:calico:feature/flannel-namespace-override?expand=1

**Comment by caseydavenport** [comment]
PR https://github.com/projectcalico/calico/pull/7557
