### ISSUE TITLE
csi-node-driver ImagePullBackOff missing imagePullSecrets

### ISSUE THREAD

**Issue by DiZY-Jin** [projectcalico/calico#6750]
Im using below link to use a private registry, however it seems the imagePullSecrets is not set for the daemonSet csi-node-driver.
https://projectcalico.docs.tigera.io/maintenance/image-options/alternate-registry

Other calico pods is up and running and get imagePullSecrets  in the deployments and daemonSet.

kubernetes v1.24.4
calico version 3.24.1

**Comment by caseydavenport** [comment]
@Josh-Tigera could you take a look at this one? Sounds like perhaps we're missing logic to include pull secrets for this daemonset?

Double check we don't need docs updates in that linked doc as well.

**Comment by Josh-Tigera** [comment]
Sure yeah, likely just an oversight on my part when implementing this.
