### ISSUE TITLE
With the quick start instructions, some pods fail to run with "x509: cannot validate certificate for 10.96.0.1 because it doesn't contain any IP SANs".

### ISSUE THREAD

**Issue by mosesyyoung** [projectcalico/calico#6754]
With the quick start instructions, some pods fail to run with "x509: cannot validate certificate for 10.96.0.1 because it doesn't contain any IP SANs".

## Expected Behavior
All POD are started normally

## Current Behavior
pods calico-kube-controllers, calico-typha and coredns are failed to start to run with the error logs:
" x509: cannot validate certificate for 10.96.0.1 because it doesn't contain any IP SANs"

## Possible Solution
Change to Flannel rather than Calico for deploying, no same issues found. All POD started

## Steps to Reproduce (for bugs)
1. Install Virtual Box, Install a server with ubuntu 18.04. Install kubeadm.
Resources: 2 CPUS, 2G Memory, 2 NIC(NAT for accessing internet, Host-Only for SSH from Host)
2. Follow the quick start instruction https://projectcalico.docs.tigera.io/getting-started/kubernetes/quickstart
Install kubeadm https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/
Use kubeadm to deployment k8s with only one single host. "sudo kubeadm init --pod-network-cidr=10.244.0.0/16"
Execute commands below to create config for kubectl:
mkdir -p $HOME/.kube
sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
sudo chown $(id -u):$(id -g) $HOME/.kube/config
Execute commands below to apply calico:
wget https://raw.githubusercontent.com/projectcalico/calico/v3.24.1/manifests/tigera-operator.yaml
kubectl create -f tigera-operator.yaml
Change custom-resources.yaml: cidr: 192.168.0.0/16 -> 10.244.0.0/16
kubectl create -f custom-resources.yaml
3. Wait for a while. Many pods are started by some are failed with multiple error logs:
Warning  FailedCreatePodSandBox  2m24s (x17 over 6m23s)  kubelet            (combined from similar events): Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "13c466073c3a9aec33344dafb7610616421cf1003f71033dfed1fce151835393": plugin type="calico" failed (add): error getting ClusterInformation: Get "https://10.96.0.1:443/apis/crd.projectcalico.org/v1/clusterinformations/default": x509: cannot validate certificate for 10.96.0.1 because it doesn't contain any IP SANs
[Command_history.txt](https://github.com/projectcalico/calico/files/9631841/Command_history.txt)
[Reproduce_Steps.txt](https://github.com/projectcalico/calico/files/9631842/Reproduce_Steps.txt)

## Your Environment
* Calico version: v3.24.1
* Orchestrator version (e.g. kubernetes, mesos, rkt): v1.25.2
* Operating System and version: Ubuntu 18.04.6 LTS
* Link to your project (optional):

**Comment by mosesyyoung** [comment]
There are some findings:
1. With Containerd + Kubernetes 1.25.X + Calico 1.24.1 via "unix:///run/containerd/containerd.sock". "IP SANS" issue occurs.
2. With CRIO + Kubernetes 1.25.X + Calico 1.24.1 via "unix:///run/crio/crio.sock". "IP SANS" issue occurs.
3. With Docker CE + Kubernetes 1.23.X(Since 1.24.X, docker shim is not supported any more) + Calico 1.23.0(Since 1.24.X, some definitions can't be recognized in this case) via "unix:///var/run/dockershim.sock". No issues found.
4. With Containerd + Kubernetes 1.23.X + Calico 1.23.0 via "unix:///run/containerd/containerd.sock". "IP SANS" issue occurs.
So the work around is to use Kubernetes 1.23.X via "unix:///var/run/dockershim.sock".

**Comment by lwr20** [comment]
So its kubeadm that's configuring the certificates. Presumably the quickstart guide needs to pass some flags to kubeadm to add the correct IP SANS to the cert.

**Comment by lwr20** [comment]
Perhaps similar to https://github.com/kubernetes/kubernetes/issues/62939 ?

**Comment by lwr20** [comment]
Can you show me the output from the `kubeadm init` command?

**Comment by mosesyyoung** [comment]
Please refer to already attached file "[Command_history.txt](https://github.com/projectcalico/calico/files/9631841/Command_history.txt)" in question description to get the output from the "kubeadm init".
Actually we tired to add all IPs to any item related to SANs but still not work.

**Comment by lwr20** [comment]
I know in my kubeadm config file I have to set this parameter:
```
apiServerCertSANs:
- ${master_external_address}
- 127.0.0.1
```
Does that help in your situation?

**Comment by song-jiang** [comment]
Looks like a kubeadm configuration issue. Feel free to open it again if you need.
