### ISSUE TITLE
Put Calico Version at top of all manifests

### ISSUE THREAD

**Issue by djosborne** [projectcalico/calico#676]
- [x] Put Calico Version at top of all manifests. Users will have an easier time identifying which version of Calico they're on if it's included in the manifest they applied.

This should help address #662

We can take this a step further and:
- [x] Add a link to `docs.projectcalico.org/{{page.version}}releases#vX.Y.Z`
- [x] put a comment at the top of the manifests which (though redundant) lists all calico subcomponent versions included in the manifest
- [ ] Since (I think) you won't be able to view these comments in `kubectl get` output, we could also possibly put them in the labels section, or some other metadata field? (though consider this suggestion out of scope for this issue for now)

**Comment by fasaxc** [comment]
If we can pass it in as an environment variable then `calico/node versions` and Felix could print it out too?

**Comment by djosborne** [comment]
Fixed by #720
