### ISSUE TITLE
How to specify the image tag of calico components

### ISSUE THREAD

**Issue by zonml** [projectcalico/calico#6770]
I installed calico v3.24.1 through tigera-operato:v1.28.1.  I was trying to find how to set image tag for calico conponents like node, typha, kube-controller in below document but failed. We want to add suffix in the tag like calico/nodev3.24.1-2022-09-27 in AWS ECR(our private registry) since sometimes we only want to upgrade the base OS in calico Dockerfile instead the calico version. Can you tell me how to specify the image tag? Perhaps you would say ImageSetSpec, but it only supports digest.  We have more than one Environment, so we hope to use image with tag instead of digest(the image digest in each Env is different).

https://projectcalico.docs.tigera.io/archive/v3.23/reference/installation/api#operator.tigera.io/v1.Image

kubernetes v1.21.5
calico version 3.24.1
tigera-operato version v1.28.1

**Comment by mgleung** [comment]
@zonml I'm not sure if it's possible to switch out the images in our operator. Maybe @tmjd knows?

**Comment by zonml** [comment]
I understand your concern.  If users are using v3.24.1 operator but they specify v3.23.1 image for calico typha, kube-controller and node, this can lead to unpredictable errors.   Can you tell me how to build a corresponding operator version?  Or if there is a non-operator installation method so I can specify image tag.

**Comment by caseydavenport** [comment]
Yeah, it would be a minor code change. Essentially you would modify the config file which specifies the versions: https://github.com/tigera/operator/blob/v1.28.1/config/calico_versions.yml

And then run this command:

```
make gen-versions
```

**Comment by caseydavenport** [comment]
Going to close this for now, since it looks like you found a solution. The main benefit of digest is that you can't accidentally push a new image and have it receive the same digest.
