### ISSUE TITLE
`calicoctl endpoint remove` is documented but not implemented

### ISSUE THREAD

**Issue by djosborne** [projectcalico/calico#68]
_From @xh3b4sd on September 29, 2016 14:28_

As documented on [how to stop a calico node](https://github.com/projectcalico/calico-containers/blob/8bc12f020191232156c391b2b36c9ed7d1e218f2/docs/calicoctl/node.md#calicoctl-node-stop) it is advised to call `calicoctl endpoint remove`. This in fact results into the following.

```
core@xh3b4sd-k8svm-master ~ $ calicoctl endpoint remove
Usage:
  calicoctl endpoint show [--host=<HOSTNAME>] [--orchestrator=<ORCHESTRATOR_ID>]
    [--workload=<WORKLOAD_ID>] [--endpoint=<ENDPOINT_ID>] [--detailed]
  calicoctl endpoint <ENDPOINT_ID> profile (append|remove|set) [--host=<HOSTNAME>]
    [--orchestrator=<ORCHESTRATOR_ID>] [--workload=<WORKLOAD_ID>]  [<PROFILES>...]
  calicoctl endpoint <ENDPOINT_ID> profile show [--host=<HOSTNAME>]
    [--orchestrator=<ORCHESTRATOR_ID>] [--workload=<WORKLOAD_ID>]
```

I feel like I am doing something fundamentally wrong. Can somebody provide feedback here?

_Copied from original issue: projectcalico/calico-containers#1176_

**Comment by djosborne** [comment]
_From @matthewdupre on September 29, 2016 21:45_

That might be a typo for `calicoctl container remove`.  Could you try it and let me know if the doc works modulo that substitution?  If so I can update the doc (or you could make a PR for it if you like).

**Comment by djosborne** [comment]
_From @xh3b4sd on October 5, 2016 13:27_

I think it is a typo in the docs and `calicoctl container remove` does the trick.

**Comment by caseydavenport** [comment]
Closing - new calicoctl will fix this.
