### ISSUE TITLE
Calico trying to assign themselves with IP from Podman's net bridge.

### ISSUE THREAD

**Issue by OrvilleQ** [projectcalico/calico#6801]
Refers to [this](https://github.com/k0sproject/k0s/issues/2208) issue I opened.

There is a chance that calico will pick IP address from interface podman0 when it's in `first-found` mode.

As document said, `Certain known “local” interfaces are omitted, such as the docker bridge.` Maybe we could make podman bridge been omitted either.

**Comment by caseydavenport** [comment]
As suggested in the original issue, you can configure Calico to select or skip certain interfaces on your host - this is what I would recommend.

I'd also be happy to review a PR that adds the podman bridge name to our default list of skips.

**Comment by OrvilleQ** [comment]
Fair enough.

I'll wait for #6760 to be merged and then open the pull request. :)
