### ISSUE TITLE
Auto Host Endpoints controller gives warnings when the feature is disabled

### ISSUE THREAD

**Issue by renan** [projectcalico/calico#6809]
After upgrading from v3.21.4 to v3.24.1 on a Kubernetes v1.24.4 cluster I am getting some warnings.

I am running calico with bird backend and Kubernetes storage as done here: https://github.com/projectcalico/calico/blob/v3.24.1/manifests/calico.yaml

```
2022-10-04 10:24:19.739 [INFO][1] main.go 103: Loaded configuration from environment config=&config.Config{LogLevel:"warning", WorkloadEndpointWorkers:1, ProfileWorkers:1, PolicyWorkers:1, NodeWorkers:1, Kubeconfig:"", DatastoreType:"kubernetes"}
W1004 10:24:19.740653       1 client_config.go:617] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
I1004 10:24:19.759604       1 shared_informer.go:255] Waiting for caches to sync for nodes
2022-10-04 10:24:19.760 [WARNING][1] hostendpoints.go 96: Unexpected kind received over syncer: IPPool(default-ipv4-ippool)
2022-10-04 10:24:19.763 [WARNING][1] hostendpoints.go 96: Unexpected kind received over syncer: ClusterInformation(default)
I1004 10:24:19.859990       1 shared_informer.go:262] Caches are synced for nodes
I1004 10:24:19.860012       1 shared_informer.go:255] Waiting for caches to sync for pods
I1004 10:24:19.860024       1 shared_informer.go:262] Caches are synced for pods
```

From https://github.com/projectcalico/calico/blob/v3.24.1/kube-controllers/pkg/controllers/node/controller.go#L144-L146:
```
	// Create the Auto HostEndpoint sub-controller and register it to receive data.
	// We always launch this controller, even if auto-HEPs are disabled, since the controller
	// is responsible for cleaning up after itself in case it was previously enabled.
```

Checking if it is enabled:
```
# kubectl kubecontrollersconfigurations.crd.projectcalico.org -o yaml | grep hostEndpoint -A 1
          hostEndpoint:
            autoCreate: Disabled
```

Since it is not enabled, it is actually not doing anything, from what I understood.
Yet I believe calico components should not issue WARNING logs that are to be ignored or for features that are disabled.

## Your Environment

* Calico version: v3.24.1
* Calico backend: bird
* Calico storage: Kubernetes
* Orchestrator version: Kubernetes v1.24.4
* Operating System and version: Ubuntu 22.04

**Comment by caseydavenport** [comment]
Those warnings will appear whether or not the hep controller is enabled. I found this bug as well a little while back and submitted a patch for it here: https://github.com/projectcalico/calico/commit/62f43c08beced4f1d65c2c939ede14bcf1208dda

That will be available in v3.25.0 ^
