### ISSUE TITLE
calico iptables rules not being removed when pod is deleted

### ISSUE THREAD

**Issue by bradbehle** [projectcalico/calico#681]
It appears that even when pods aren't on a given worker node, that the iptables rules for those pods stick around?  This is on calico 2.0.2 (so calico-node v1.0.2, policy-controller v0.5.2), and looking at the iptables rules, there are rules for 150+ different cali* interfaces, but there are only 17 cali* interfaces on the system and 17 routes to cali* interfaces.  I've attached the output of "ip a | grep cali", "route -n", and "sudo iptables -nvL" to show this.  
[iptables.txt](https://github.com/projectcalico/calico/files/926695/iptables.txt)
[routes.txt](https://github.com/projectcalico/calico/files/926701/routes.txt)
       - NOTE: in routes.txt I replaced public IPs with ********
[ip_a.txt](https://github.com/projectcalico/calico/files/926696/ip_a.txt)

**Comment by lxpollitt** [comment]
@fasaxc Can you take a look at this one?

**Comment by bradbehle** [comment]
Here is the felix log as well, showing that iptables restore is being called
[current.txt](https://github.com/projectcalico/calico/files/927223/current.txt)

**Comment by fasaxc** [comment]
@bradbehle If Felix isn't cleaning up those rules then the most likely explanation is that it believes those pods should still be present on the node.  

If you're using the etcd datastore driver, please can you check if they're still in the datastore?  IIRC, `calicoctl get workloadendpoint --node=<nodename>` should do the trick.

If you're using the Kubernetes datastore driver, I think we've fixed a number of issues around pod deletion in Felix 2.1.x so it may be that the release you're using is missing some fixes.

**Comment by bradbehle** [comment]
We are currently using etcd datastore driver.
153 workload endpoints on for the node I'm looking at, but only 16 pods with cali* interfaces (and 3 pods with host networking).

~~~
behle:~$ route -n | grep cali | wc -l
16
behle:~$ kubectl get pods --all-namespaces -o wide | grep "10.176.31.237" | wc -l
19
behle:~$ /opt/bin/calicoctl get workloadendpoint --node=prod-dal10-carrier1-worker-11.alchemy.ibm.com -o wide | wc -l
153
behle:~$ 
~~~

**Comment by fasaxc** [comment]
As discussed, the workaround would be to 

- find and delete the workload endpoints for the missing pods
- release the associated IP address.

You could:

- use `ip route` and compare with `ip link` to find out which interfaces are missing and what their assigned IP was
- use 
```
./calicoctl get workloadEndpoint \
            --node=<nodename> \
            --output=go-template="{{range .}}{{range .Items}}{{if eq .Spec.InterfaceName \"<interface-name>\"}}{{println .Metadata.Workload}}{{end}}{{end}}{{end}}"
```
  to find the workload ID from an interface name
- use `calicoctl delete workloadendpoint --node=<nodename> --workload=<workloadID>`
- use `calicoctl ipam release <IP address>` to release the IP for re-use.

**Comment by bradbehle** [comment]
To summarize (after debugging this a bit over slack), we think these workload endpoints (weps) are due to kube not notifying Calico CNI plugin when pods are moved (most likely due to a worker reboot or docker restart).  This node was rebooted 5 days ago, and the kubelet log shows a lot of the following message from around the time of the reboot:
```Failed to delete pod "master-f6d9f2732cc64a2489e49d978b94a51d-3819453785-d53vw_kubx-masters(bda157de-2061-11e7-b12b-0615fa0288ad)", err: pod not found```

This behavior is supposed to be better in kubernetes 1.6.  Until then, if needed we can manually delete the weps that don't correspond to a pod running on the system using the ```calico delete workloadendpoint``` and ```calico ipam release``` commands listed above.  If creating a script to do this, we could find the pod names of all the weps on a given node using ```./calicoctl get workloadEndpoint --node=<nodename> \```   In this output the "WORKLOAD" field has the form <kube_ns>.<kube_pod_name>   We can then use kubectl get pods --all-namespaces | grep <kube_pod_name> to see if the pods are still alive, and if not, can delete the wep.

We might want to do this in order to keep the number of iptables entries in the filter table reasonable, this might improve iptables-save and iptables-restore times which might improve service startup times.

**Comment by tmjd** [comment]
@bradbehle From what you summarized it sounds like this is a K8s 1.5 issue and you have a solution for handling.  Is there anything remaining on this issue that it should remain open?

**Comment by tmjd** [comment]
I don't think there is anything left to do for this issue.  There exists #657 for adding some documentation to handle it.  @bradbehle If you feel there is more to do here please feel free to reopen or create a new issue.  Thanks.

**Comment by bradbehle** [comment]
Sorry for the delay, I agree, no more to do here right now.
