### ISSUE TITLE
bird: KRT: Received route with strange next-hop

### ISSUE THREAD

**Issue by lrc0** [projectcalico/calico#6828]
My K8S cluster lacks the default route, causing the container network to fail，so i add a ip route: 169.254.1.1 via 10.16.0.45 dev eth0
this route solved my container network, but now the calico keeping printing bird: KRT: Received route 169.254.1.1/32 with strange next-hop 10.16.0.45. 
![image](https://user-images.githubusercontent.com/29445288/194697946-17350790-4846-4f55-b0d5-221295ef1af4.png)

please help me how to stop printing this massage ~

# Your enviorment
K8S version：1.20.2
calico version: v3.18.6

**Comment by caseydavenport** [comment]
Could you share the whole route table for that node? Do you have a device route covering 10.16.0.45? If I had to guess, BIRD is emitting the warning because it can't find a route that contains 10.16.0.45.

**Comment by lrc0** [comment]
sorry for the late relpy， this problem already solved, the route should be "169.254.1.1 dev eth0" without  via 10.16.0.45 ,  because the eth0's IP aleady  10.16.0.45
