### ISSUE TITLE
windows: calico-node startup container unable to access kubeadm ConfigMap

### ISSUE THREAD

**Issue by mweibel** [projectcalico/calico#6829]
## Expected Behavior
calico-node-startup is able to fetch kubeadm ConfigMap when needed, or does not terminate startup when it's not needed.

## Current Behavior
When a new windows node boots up without any non-hostprocess pods running, the calico-node-startup container is not able to access the kubeadm configmap (see note [1]) because the Calico HNSNetwork is not yet setup. This also means felix can't continue.

[1] calico startup tries to go via internal kubeconfig instead of externally

Relevant code:
- [try fetching kubeadm config with InClusterConfig](https://github.com/projectcalico/calico/blob/release-v3.23/node/pkg/lifecycle/startup/startup.go#L132)
- [if that does not work it terminates](https://github.com/projectcalico/calico/blob/release-v3.23/node/pkg/lifecycle/startup/startup.go#L159)

InClusterConfig works in HostProcess containers because Kubernetes passes in the necessary env variables to those pods: `KUBERNETES_SERVICE_HOST` and `KUBERNETES_SERVICE_PORT`.

Error returned:
```
[ERROR][10148] startup/startup.go 158: failed to query kubeadm's config map error=Get "[https://10.96.0.1:443/api/v1/namespaces/kube-system/configmaps/kubeadm-config?timeout=2s](https://10.96.0.1/api/v1/namespaces/kube-system/configmaps/kubeadm-config?timeout=2s)": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
```

See [Slack for a discussion](https://calicousers.slack.com/archives/CF9M1U9RV/p1664978759521999).

## Possible Solution
We did a workaround in our fork of calico: https://github.com/helio/calico/commit/c81b703e345bdc745c9b1604c61f3ba645c4dbdb
This is a possible solution, however the Slack discussion suggests that maybe calico does not need to fetch those infos at all or maybe the whole startup process needs to be reconsidered for windows HostProcess. 

## Steps to Reproduce (for bugs)
1. Create a kubernetes 1.24.x cluster with windows and nightly containerd. 
2. Ensure no non-hostprocess pod is scheduled on windows nodes
3. Boot up a windows instance
4. Check logs of calico-node-startup

An example config using cluster-api and azure cloud is attached. I tried to replicate our cluster with a [template from CAPZ](https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/main/templates/cluster-template-windows.yaml). 
See [cluster-api quickstart](https://cluster-api.sigs.k8s.io/user/quick-start.html) if it's your first time using cluster-api. 
The initial value for windows nodes is set to zero replicas, to ensure necessary bits are set up before anything else.

[calico-example.zip](https://github.com/projectcalico/calico/files/9753305/calico-example.zip)

Of course also any other k8s cluster would suffice, given you can adjust the necessary bits like having the right k8s version and containerd nightly installed. 

## Context
We need to use containerd nightly because we need windows GPU support in containers. We want to use calico hostprocess since it's much simpler to manage than having to bake it into the VM image. We always scale from/to zero so boot up time is important. 

## Your Environment
* Calico version v3.23.0
* Orchestrator version (e.g. kubernetes, mesos, rkt): k8s 1.24.6 with kubeadm
* Operating System and version: windows

**Comment by lwr20** [comment]
pinging @song-jiang @coutinhop

**Comment by lwr20** [comment]
I believe @song-jiang is working on this, but no ETA yet.

**Comment by song-jiang** [comment]
Just a quick update that we are working on Calico for Windows HPC installation support and this issue should be fixed when HPC support is released. We don't have an ETA yet.
