### ISSUE TITLE
Understand why --pod-network-cidr must match Calico Pool 

### ISSUE THREAD

**Issue by lwr20** [projectcalico/calico#683]
This doc: http://docs.projectcalico.org/v2.1/getting-started/kubernetes/installation/hosted/kubeadm/
has the statement:
```
The Kubeadm flag --cluster-cidr (pre 1.6) or --pod-network-cidr (1.6+) is not utilized by Calico nor Kubernetes if using Calico for routing.
```
But I'm seeing that if the `--pod-network-cidr` flag is not set to include all calico ippools, then access from pod to a service backed by a pod on a different node does not work when a policy is in place.  Or in simple terms:  the `simple policy demo` in our docs fails intermittently at the "Allow Access using a NetworkPolicy" step.

**Comment by tmjd** [comment]
This is my bad on the docs, when I was testing I wasn't thinking and was not using DefaultDeny and therefore did not need policy.
@djosborne I just wanted to bring this to your attention.

**Comment by djosborne** [comment]
Interesting. I wonder why this is. @lwr20 you encountered this even when using Calico for routing?

**Comment by lwr20** [comment]
Yes @djosborne .  This was a kubeadm installed k8s cluster running v1.6.1 and using calico (with etcd backend) installed according to the kubeadm quickstart docs.  My cluster install script was specifying 10.244.0.0/24 as the `pod-network-cidr` - which didn't play nicely with the calico default ippool of 192.168.0.1. 

@fasaxc diagnosed the problem - he said something about kube-proxy doing DNAT for services.

Now that I've updated the installer, I see that our automated e2e tests are now starting to pass the `It should enforce policy based on PodSelector [Feature:NetworkPolicy]` test which has been failing for a while.  I think the reason this was passing intermittently before was that if the server pod happens to get scheduled on the same node as the client pod, the test passes.

**Comment by djosborne** [comment]
Text is updated thanks to @tmjd . But I want to keep this open until I understand what causes policy issues when these two values don't match

**Comment by tmjd** [comment]
@djosborne Can we remove the milestone on this issue or do you want this before 2.2 is released?  And is it still a task for me or did you want to take it over?

**Comment by caseydavenport** [comment]
When `--cluster-cidr` is specified on the kube-proxy, it will masquerade all traffic it receives that is from a source _not in that cidr_.

So, if Pods have IP addresses assigned from outside of that cluster-cidr then they will be masqueraded by the kube-proxy and dropped by Calico policy.

So, valid configurations would be:
- No `--cluster-cidr` specified at all (breaks some scenarios with multiple interfaces)
- Ensuring `--cluster-cidr` matches the configured Calico IP Pool.

**Comment by zioalex** [comment]
> When `--cluster-cidr` is specified on the kube-proxy, it will masquerade all traffic it receives that is from a source _not in that cidr_.
> 
> So, if Pods have IP addresses assigned from outside of that cluster-cidr (e.g. when Calico IPAM is selecting from a mismatched pool) then they will be masqueraded by the kube-proxy and dropped by Calico policy.
> 
> So, valid configurations would be:
> 
>     * No `--cluster-cidr` specified at all (breaks some scenarios with multiple interfaces)
> 
>     * Ensuring `--cluster-cidr` matches the configured Calico IP Pool.

@caseydavenport  This explanation should be included in the doc  and in the yaml file. I spent some hours before to understand why my calico setup works also without the cluster-cidr match.
