### ISSUE TITLE
confused about calico peerSelector mechanism

### ISSUE THREAD

**Issue by aries1998** [projectcalico/calico#6832]
From what i read the doc on tigera.io,  you can add k8s node label like "route-reflector: true" using kubectl or calicoctl .

When using kubectl , the label is added to node's label field.

When using calicoctl , the label is added to the node's annotations field.

Here's the question , when calico use peerSelector to match node , how calico decide which label to use  if you set one true and another false. 

And which method is the better way to add label  , kubectl or calicoctl?

**Comment by caseydavenport** [comment]
They will both work - labels applied to the k8s node will also be visible on the Calico "node" object.
