### ISSUE TITLE
rbac.yaml has lots of HTML in it

### ISSUE THREAD

**Issue by lwr20** [projectcalico/calico#684]
http://docs.projectcalico.org/master/getting-started/kubernetes/installation/rbac.yaml

http://docs.projectcalico.org/master/getting-started/kubernetes/installation/hosted/ says that if you're using RBAC, you should run:
`kubectl apply -f http://docs.projectcalico.org/master/getting-started/kubernetes/installation/rbac.yaml`

But that yaml file has lots of HTML in it and is rejected by kubernetes.

**Comment by djosborne** [comment]
oops, top of the yaml needs:
```
---
layout: null
---
```
