### ISSUE TITLE
Need your help for self-defined xdp program  in calico

### ISSUE THREAD

**Issue by linhil** [projectcalico/calico#6851]
I set0 a k8s cluster with calico cni in bgp ipv6 mode with linux kernel 4.20. 
I start a pod, I set a xdp program on eth0 veth with XDP_TX to relflect the packet inside the pod, and I must set the corresponding xdp program XDP_PASS on the host's calixxxx veth to forward the packet, but I set the [calico-bgp](https://projectcalico.docs.tigera.io/getting-started/kubernetes/self-managed-onprem/onpremises) in advance. I tested the performance, the performance was poor, does some one know why does the extra edp cause the poor performance?

**Comment by coutinhop** [comment]
tagging @tomastigera
