### ISSUE TITLE
ServiceAccount etcd datastore

### ISSUE THREAD

**Issue by Hanmask21** [projectcalico/calico#6853]
I am running calico node via calicotl:
`calicoctl node run -c calico.yaml --node-image=calico/node:latest`
Calico.yaml file:
apiVersion: projectcalico.org/v3
kind: CalicoAPIConfig
metadata:
spec:
  datastoreType: "etcdv3"
  etcdEndpoints: "etcdEndpoints"
 
I am waiting for calico node to start, but node is waiting for config kuber. Datastore specified by etcd:
2022-10-16 23:32:03.680 [ERROR][57] cni-config-monitor/token_watch.go 34: Failed to watch Kubernetes serviceaccount files. error=no such file or directory

**Comment by lwr20** [comment]
We're going to need much more information to be able to do anything with this report.

**Comment by Hanmask21** [comment]
@lwr20  updated description

**Comment by lwr20** [comment]
Or if you are actually trying to install a non-cluster host, you need to follow: https://projectcalico.docs.tigera.io/getting-started/bare-metal/about

**Comment by Hanmask21** [comment]
I want to set it up for a nomad, but as far as I understand it will not work

**Comment by lwr20** [comment]
Nomad isn't supported by Calico at this point.  That's not to say it can't work, but that we don't test or document how to do so at this point.

@caseydavenport wrote this comment on the subject: 
https://github.com/projectcalico/calico/issues/5335#issuecomment-1007830438

So you would need to:
- set up an etcd instance.
- Install the CNI plugin binaries and a suitable CNI plugin config file pointing it at etcd, in the place that nomad expects to find CNI config
- Run calico/node as a container on each node in your nomad cluster, pointing it at etcd.

https://raw.githubusercontent.com/projectcalico/calico/v3.24.2/manifests/calico-etcd.yaml is a kubernetes manifest for setting up calico-node to use etcd as its datastore, you can probably get hints (required environment variables, config files, etc) from that.

**Comment by caseydavenport** [comment]
I believe you can set `CALICO_MANAGE_CNI=false` in the calico/node env in order to turn off the serviceaccount management logic. That will at least get you past this particular issue.
