### ISSUE TITLE
Readiness probe failed: calico/node is not ready: BIRD is not ready: Error querying BIRD: unable to connect to BIRDv4 socket: dial unix /var/run/calico/bird.ctl: connect: connection refused

### ISSUE THREAD

**Issue by XDavidT** [projectcalico/calico#6860]
Adding a new node using RKE to my current cluster, I'm getting this message on 'events' of calico:

> Readiness probe failed: calico/node is not ready: BIRD is not ready: Error querying BIRD: unable to connect to BIRDv4 socket: dial unix /var/run/calico/bird.ctl: connect: connection refused

The pod is in 'ready' status, but this message look not good - and this cluster is for production == zero errors.
I tried to look in the issues, but didn't saw how people figure this out - I only saw block between nodes connection, but this is not my case, nodes can talk with each other easily.

## Expected Behavior
No errors

## Current Behavior
Getting this event during the pods of calico that deployed in the new node by DaemonSet:
Readiness probe failed: calico/node is not ready: BIRD is not ready: Error querying BIRD: unable to connect to BIRDv4 socket: dial unix /var/run/calico/bird.ctl: connect: connection refused

## Steps to Reproduce (for bugs)

1. Cluster build with RKE without network plugin
2. adding new calico Ds: https://gist.github.com/XDavidT/a5e1069269d522ceacbc805c4781b9e6
3. Adding a new node to the cluster

## Context
Just normal cluster built by rke up command - calico deploy with 3 nodes to test. we only made a change on **IP_AUTODETECTION_METHOD** to use our subnet and not other network cards.
then added one more node.

## Your Environment
* Calico version v3.23.1
* Orchestrator version (e.g. kubernetes, mesos, rkt): K8s (by RKE) v1.21.12
* Operating System and version: Ubuntu 18.04 & 20.04
* Link to your project (optional):--

Can someone explain me why this issue came up, and why? and what we can do to solve it?

**Comment by mgleung** [comment]
Hey @XDavidT , could I ask you to include the logs for a failing calico-node pod? I want to check if there's anything else there that would provide more details as to what's causing this.

**Comment by XDavidT** [comment]
After 1 day the error is gone without doing nothing.
