### ISSUE TITLE
Manifest does not mach website docs

### ISSUE THREAD

**Issue by Re4zOon** [projectcalico/calico#6866]
The [manifest](https://docs.projectcalico.org/manifests/tigera-operator.yaml) does not match the documentations on the [website](https://projectcalico.docs.tigera.io/maintenance/image-options/alternate-registry).
Manifest is referencing an older image, while the documentation is already updated.
They should be kept in sync as it breaks my ansible scripts and any type of hope/soul in not-really-experienced users.

## Expected Behavior
Versions match.

## Current Behavior
Versions don't match.

FYI the registrar image has been added by this PR:
https://github.com/projectcalico/calico/pull/6812

However its still not visible in the documentation.

**Comment by Josh-Tigera** [comment]
Which image are you referring to specifically? Operator 1.28.1 vs 1.28.2? I don't see a node-registrar-driver image referenced in the linked manifest at all.

**Comment by Re4zOon** [comment]
To be clear:
My ansible playbook references the website (could do with the github repos instead, but whatever), grabs the image tags, pulls/tags/uploads them to the private registry, then starts the operator.

So ansible does:
1. grab 1.28.2 (and 3.24.2)
2. pulls/tags/pushes 1.28.2 (and 3.24.2) to private registry
3. starts 1.28.1 (which starts 3.24.1) images
4. Nothing starts, as no image is available

**Comment by Josh-Tigera** [comment]
I see, thanks for the clarification.

**Comment by caseydavenport** [comment]
Yep, this was missed in the release. Here's a fix for the manifest: https://github.com/projectcalico/calico/pull/6868

The pinned manifests will need a new patch release to fix, but that will come out soon.
