### ISSUE TITLE
Tigera Operator helm deploy not updating CRDs

### ISSUE THREAD

**Issue by mstansberry** [projectcalico/calico#6880]
When upgrading from `v3.21.3` to `3.24.1`, the upgrade fails to update pods in the `calico-system` namespace. Upon further investigation it appears that the issue stems from the `spec.kubernetesProvider` attempting to use a value of `RKE2` which is not present in the existing `installations.operator.tigera.io` CRD.

## Expected Behavior
Upgrades should complete as expected, regardless of installation/upgrade mechanism.

## Current Behavior
CRDs are not updating during helm install/upgrade [by design](https://github.com/helm/helm/pull/6243), and therefore any changes made to underlying CRDs will not be applied during an upgrade. Current solution is to manually run `kubectl replace -f` using the CRD from [operator.tigera.io_installations_crd.yaml](https://github.com/projectcalico/calico/tree/master/manifests/ocp/operator.tigera.io_installations_crd.yaml) as the current [operator-crds.yaml](https://github.com/projectcalico/calico/tree/master/manifests/operator-crds.yaml) is not up-to-date.

## Possible Solution
As helm intentionally does not upgrade CRDs as part of a helm install/upgrade, the operator should perform these upgrades directly. If that is not possible, an up-to-date [operator-crds.yaml](https://github.com/projectcalico/calico/tree/master/manifests/operator-crds.yaml) should be provided to allow updating the CRDs outside of the `tigera-operator` chart.

## Steps to Reproduce (for bugs)
1. Install calico `v3.21.3` from helm chart on an RKE2 cluster
2. Apply necessary changes for [v.3.23+](https://projectcalico.docs.tigera.io/maintenance/kubernetes-upgrade#upgrade-from-calico-versions-prior-to-v3230)
3. Run `helm install calico projectcalico/tigera-operator --version v3.24.2 --namespace tigera-operator`
4. Monitor tigera-operator pod logs for errors
    ```"Installation.operator.tigera.io \"default\" is invalid: spec.kubernetesProvider: Unsupported value: \"RKE2\": supported values: \"\", \"EKS\", \"GKE\", \"AKS\", \"OpenShift\", \"DockerEnterprise\""```
5. Apply [operator.tigera.io_installations_crd.yaml](https://github.com/projectcalico/calico/tree/master/manifests/ocp/operator.tigera.io_installations_crd.yaml) manually
6. Monitor tigera-operator pod logs and pods in `calico-system` to verify upgrade is completed

## Context
While we have identified a workaround, would appreciate a long-term documented solution for future upgrades to continue allowing the use of helm while supporting required changes to CRDs.

## Your Environment
kubernetes v1.22.9
calico v3.21.3/3.24.1
ubuntu 18.04/20.04
Rancher RKE2

**Comment by caseydavenport** [comment]
Yep, I think we could do any of the following:

- Configure the operator to update its own CRDs on upgrade (I believe this is already possible, but maybe not enabled in the helm install). 
- Add a new CRD yaml file as part of the upgrade.
- Something else, perhaps?

My current preference is probably for the first option, although I think we'll need a values.yaml config option to disable that for users who don't want that behavior. Should be straightforward, and I'd be happy to review a PR to do this.

@tmjd might be able to comment more on the auto-CRD-upgrade capabilities since I believe he implemented that originally.

**Comment by EugenMayer** [comment]
For anybody i need for the work around

```bash
wget https://raw.githubusercontent.com/projectcalico/calico/v3.24.5/manifests/ocp/operator.tigera.io_installations_crd.yaml
kubectl replace -f operator.tigera.io_installations_crd.yaml
```

What i also did was

```bash
wget https://raw.githubusercontent.com/projectcalico/calico/master/manifests/operator-crds.yaml
kubectl replace -f operator-crds.yaml
```

**Comment by lwr20** [comment]
> Add a new CRD yaml file as part of the upgrade.

An attempt to improve the helm upgrade docs here:
https://github.com/projectcalico/calico/pull/7127/files

**Comment by EugenMayer** [comment]
@lwr20 IMHO that does not work and did not for me.

**Comment by lwr20** [comment]
@EugenMayer IIUC the issue in this bug is that the `operator-crds.yaml` at that location isn't being updated (and should be).  Once this bug is fixed, those instructions should be correct, or have I missed something further?

**Comment by EugenMayer** [comment]
@lwr20 i cannot tell if it was outdate, broken or anything else. It did not work, the instructions i posted in https://github.com/projectcalico/calico/issues/6880#issuecomment-1367963633 do work, since they use the current source code with the actual version relating to the helm chart.

But yes, if the only issue was it is outdated, and keeping it up to date can be automated, it is the easier way to do what i did above.

**Comment by mstansberry** [comment]
> @EugenMayer IIUC the issue in this bug is that the `operator-crds.yaml` at that location isn't being updated (and should be). Once this bug is fixed, those instructions should be correct, or have I missed something further?

Once `manifests/operator-crds.yaml` is being updated reliably, I think we can start using that as a pre-upgrade task and replace. Thanks a lot.

**Comment by caseydavenport** [comment]
This PR should fix the generation of the operator-crds.yaml manifest: https://github.com/projectcalico/calico/pull/7216

**Comment by caseydavenport** [comment]
Latest instructions explain how to replace the CRDs on upgrade: https://docs.tigera.io/calico/latest/operations/upgrading/kubernetes-upgrade#all-other-upgrades
