### ISSUE TITLE
Release `v3.24.2` Tigera Operator chart/version hasn't been updated

### ISSUE THREAD

**Issue by stevehipwell** [projectcalico/calico#6884]
## Expected Behavior

I would expect to see [v1.28.2](https://github.com/tigera/operator/releases/tag/v1.28.2) of the Tigera Operator and `v3.24.2` of the Calico CLI in the Tigera Operator Helm chart

## Current Behavior

The Tigera Operator version hasn't been updated which AFAIK means that the operator wouldn't install the correct version of Calico.

## Possible Solution

Fix the chart and update the release artifact.

## Steps to Reproduce (for bugs)

n/a

## Context

I tried to reach out about this when the release was cut but I didn't get a response.

## Your Environment

* Calico version: v3.24.0
* Orchestrator version (e.g. kubernetes, mesos, rkt): K8s
* Operating System and version: n/a
* Link to your project (optional): n/a

**Comment by stevehipwell** [comment]
CC @caseydavenport

**Comment by caseydavenport** [comment]
Yeah, unfortunately we hit a bug in our release process that resulted in v3.24.2 not including the right image tag. @mgleung is aware and is in the process of cutting v3.24.3 which will fix this. I am hopeful that this release will go out today.

First spotted here: https://github.com/projectcalico/calico/issues/6866

**Comment by mgleung** [comment]
v3.24.3 has been released and this issue should have been addressed. Please shout out if you see this happen again though.
