### ISSUE TITLE
Helm "include calicoctl pod" boolean

### ISSUE THREAD

**Issue by jcpunk** [projectcalico/calico#6886]
## Expected Behavior
When installing calico via helm, it would be handy if I could "flip a bit" to include calicoctl as a Kubernetes pod.  This would provide a clean way to bundle up a known calicoctl within the cluster and make getting started easier.

## Current Behavior
After installing the helm chart, I've got to go fetch `calicoctl`.

## Possible Solution
Add a boolean to `values.yml` that will load the "[calicoctl as a Kubernetes pod](https://projectcalico.docs.tigera.io/maintenance/clis/calicoctl/install#install-calicoctl-as-a-kubernetes-pod)" workflow

## Steps to Reproduce (for bugs)

1. Install helm chart
2. notice a lack of calicoctl
3.
4.

## Context

I'm trying to make it easier to get up and running from scratch with the calico operators

## Your Environment

* Calico version: 3.24.2
* Orchestrator version (e.g. kubernetes, mesos, rkt): 1.25.2
* Operating System and version: CentOS Stream 9
* Link to your project (optional):

**Comment by caseydavenport** [comment]
We want to move away from bundling calicoctl as a pod. There is a Calico API server that performs the same function as calicoctl as a pod and is the recommended way to interact with Calico APIs, and is installed by default when using the helm chart already. 

What is your use-case for installing calicoctl on the cluster?

**Comment by jcpunk** [comment]
Mostly for looking at the IPAM.  I can live with my current workflow.
