### ISSUE TITLE
Canal network policy does not take effect in ali-vpc mode ！

### ISSUE THREAD

**Issue by AliDev0ps** [projectcalico/calico#6894]
Does Canal network policy only work in Vxlan mode by default?

Some Pods cannot be created after uninstalling Canal !

```
 Warning  FailedCreatePodSandBox  22s (x17 over 2m39s) kubelet  (combined from similar events): Failed to create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container "2293bb" network for pod "dev-xxx-56698c8c4b-5dwml": networkPlugin cni failed to set up pod "dev-xxx" network: Unauthorized
```

**Comment by lwr20** [comment]
Its easier to help if you fill in the issue template.

> Does Canal network policy only work in Vxlan mode by default?
It depends.  Some clouds block traffic that isn't VXLAN, so in those environments, yes, it would only work in VXLAN mode.

The "unauthorised" error from the CNI plugin looks similar to issues we've seen with running old versions of Calico on new versions of kubernetes.  I think one of the new versions of kubernetes changed how tokens were issued - we had to make calico changes for that, perhaps flannel needs to make them too.

**Comment by coutinhop** [comment]
Closing this as inactive. Feel free to reopen if you're still having issues...
