### ISSUE TITLE
Switch to quay.io for calico chart?

### ISSUE THREAD

**Issue by jcpunk** [projectcalico/calico#6897]
## Expected Behavior

The charts use a consistent container repository.

## Current Behavior

The `tigera-operator` chart uses quay.io for the container image, however, the [`calico`](https://github.com/projectcalico/calico/blob/master/charts/calico/values.yaml) chart uses docker hub.  Playing about with calico in KinD had me hitting the docker hub pull limit surprisingly quickly.

## Possible Solution

Update https://github.com/projectcalico/calico/blob/master/charts/calico/values.yaml to use quay.io

## Steps to Reproduce (for bugs)

1. build and destroy a few KinD clusters using the operator
2. hit dockerhub pull limit
3.
4.

## Context

I'm building a test platform for folks to locally spin up an environment that matches our production runtime on their dev nodes.

## Your Environment

* Calico version: 3.24.2
* Orchestrator version (e.g. kubernetes, mesos, rkt): 1.25.2
* Operating System and version: CentOS Stream 9
* Link to your project (optional):

**Comment by lwr20** [comment]
So `values.yaml` can be used to set properties in the Installation resource.   https://projectcalico.docs.tigera.io/reference/installation/api

I think you could set `spec.imagePath` to point to the quay.io calico images.

**Comment by lwr20** [comment]
might be as simple as setting `spec.registry=quay.io`?

**Comment by jcpunk** [comment]
That would work! Mostly I just noticed the inconsistency between the two.

**Comment by lwr20** [comment]
@caseydavenport do we want to make quay.io the default source of calico images to avoid people hitting the docker download limits?
