### ISSUE TITLE
namespaceSelector/matchLabels/name ignored by network policy

### ISSUE THREAD

**Issue by vova3379** [projectcalico/calico#6898]
We have a strange issue in one namespace, where network policy ignores one namespace by name. Our current configuration looks like below 
`    - namespaceSelector:
        matchLabels:
          name: kube-system`
but we can not reach pods in the target namespace from pods from the kube-system namespace and getting timeout 
 `root@ubuntu:/# nc -zv 10.56.134.27 8080
nc: connect to 10.56.134.27 port 8080 (tcp) failed: Connection timed out` 
but when we add the same namespace with the namespace labels like below:
`    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: kube-system`     
all start working.

## Expected Behavior
ingress policy must work for namespaceSelector/matchLabels/name 

## Current Behavior
it doesn't work

## Possible Solution
as you can see above I've used namespace labels to mitigate this. 

## Steps to Reproduce (for bugs)
Unfortunately, I can not provide a lot here, because we see this issue only for one namespace on dev k8s eks cluster, same policy on the prod cluster works without problems and I am unsure how to debug it. 

## Context
As you can see namespaceSelector/matchLabels/name not works as expected 

## Your Environment
* Calico version: tigera-operator 3.24.0
* Orchestrator version (e.g. kubernetes, mesos, rkt): amazon EKS v1.21.14-eks-6d3986b

**Comment by lwr20** [comment]
What labels are on the kube-system namespace?

**Comment by vova3379** [comment]
Hello @lwr20 thank you for your reply, you are right and I miss that on dev k8s we don't have a needed label on the problem namespace, but on prod have. 

Some time ago recreated dev cluster and old labels were removed, so we need start using new labels for network policies. 

Thanks a lot for your help.
