### ISSUE TITLE
Traffic randomly being denied by global network policy.

### ISSUE THREAD

**Issue by ausername86** [projectcalico/calico#6905]
I am running Calico v3.23.2 on a kubernetes cluster hosted in AWS EKS. I have a global default deny policy that denies all traffic without a specific order assigned (defaulted to order infinity), and I have namespaced network policies with an order of 1 that allow ingress / egress. The logic here is with an order of 1 all my network policies are evaluated first through the chain before hitting the global default network policy to deny traffic that isn't defined in any other network policies.

I am running into issues where all the policies are applied and everything communicates correctly with no denied traffic, but randomly if a pod restarts, sometimes the traffic will start being blocked, almost like it's hitting the global default deny netpol before it can reach it's actual egress / ingress rules. This happens at random and most of the time when pods restart everything runs fine, but there have been a few instances over the last couple of weeks where this has happened and the only solution is to either delete the pod and let kubernetes bring it back, or delete all the network policies in the cluster and then re apply them. There are no changes to the network policies as far as rules go during this process. Im not really sure what's going on. But I would expect that this wouldn't happen unless there was an actual change to the network policy itself.  An example of this is there is a pod in a daemonset that will start having it's traffic denied, even though all the other pods are ok and the same net pol is applied to all of them.

Any insight / help would be greatly appreciated.

## Expected Behavior
Network policies should always correctly enforce network traffic, even if a pod restarts or a node restarts.

## Current Behavior
At random, a pod will start suddenly dropping traffic when it should be allowing traffic.

## Your Environment

* Calico version v3.23.2
* Orchestrator version (e.g. kubernetes, mesos, rkt): 1.22.5
* Operating System and version:
* Link to your project (optional):

**Comment by song-jiang** [comment]
> almost like it's hitting the global default deny netpol before it can reach it's actual egress / ingress rules

Are you sure it was the global deny policy blocking the traffic? There could be multiple reasons that traffic was not going through. 

> or delete all the network policies in the cluster and then re apply them

This is more convincing but still it is better to confirm global deny policy played a role here. Is it easier to repo? One way to debug is that when a pod hit this issue, find out the iptables rules corresponding to the deny policy and check if the rule counter increase.

**Comment by song-jiang** [comment]
Close inactive issue
