### ISSUE TITLE
Linkerd GRPC load balancing doesn't work with Calico eBPF

### ISSUE THREAD

**Issue by aagzoom** [projectcalico/calico#6908]
### What is the issue?
When I use Linkerd with Calico CNI (ebpf mode with vxlan) all GRPC requests go to one pod instead of balancing between all pods behind a Service

I see this line in the logs in broken setup:

`[     0.204913s] DEBUG ThreadId(01) outbound:accept{client.addr=172.25.229.60:42842}:proxy{addr=172.25.240.43:50051}: linkerd_cache: Caching new value key=Accept { orig_dst: OrigDstAddr(172.25.240.43:50051), protocol: () }`

And this line in correctly working setup:

`[     0.184450s] DEBUG ThreadId(01) outbound:accept{client.addr=172.27.102.88:44572}:proxy{addr=10.106.182.82:50051}: linkerd_cache: Caching new value key=Accept { orig_dst: OrigDstAddr(10.106.182.82:50051), protocol: () }`

In the first line linkerd-proxy uses Pod address (172.25.240.43:50051). In the second line linkerd-proxy uses Service address (10.106.182.82:50051).

### How can it be reproduced?

Install linkerd with Calico and try to send grpc requests to a grpc service behind a kubernetes Service.

### Logs, error output, etc

first appearance of the pod address in the client's linkerd-proxy log:

`[     0.204913s] DEBUG ThreadId(01) outbound:accept{client.addr=172.25.229.60:42842}:proxy{addr=172.25.240.43:50051}: linkerd_cache: Caching new value key=Accept { orig_dst: OrigDstAddr(172.25.240.43:50051), protocol: () }`

### output of linkerd check -o short

```
Linkerd core checks
===================

linkerd-version
---------------
‼ cli is up-to-date
    is running version 2.12.1 but the latest stable version is 2.12.2
    see https://linkerd.io/2.12/checks/#l5d-version-cli for hints

control-plane-version
---------------------
‼ control plane is up-to-date
    is running version 2.12.1 but the latest stable version is 2.12.2
    see https://linkerd.io/2.12/checks/#l5d-version-control for hints

linkerd-control-plane-proxy
---------------------------
‼ control plane proxies are up-to-date
    some proxies are not running the current version:
	* linkerd-destination-788d67674-nx9r9 (stable-2.12.1)
	* linkerd-identity-7d54bd547-lkvrw (stable-2.12.1)
	* linkerd-proxy-injector-7cf8cf457c-hjht5 (stable-2.12.1)
    see https://linkerd.io/2.12/checks/#l5d-cp-proxy-version for hints

Linkerd extensions checks
=========================

linkerd-viz
-----------
‼ viz extension proxies are up-to-date
    some proxies are not running the current version:
	* metrics-api-cbb5cdd44-tljc9 (stable-2.12.1)
	* prometheus-796c56d568-tp58f (stable-2.12.1)
	* tap-775d89cc78-spp5k (stable-2.12.1)
	* tap-injector-599fdd646b-b84wp (stable-2.12.1)
	* web-7666f68d74-qbfjs (stable-2.12.1)
    see https://linkerd.io/2.12/checks/#l5d-viz-proxy-cp-version for hints

Status check results are √
```

### Environment

    kubernetes v1.22.2
    calico version: v3.24.1
    on-prem installation
    OS Debian Linux 10
    linkerd: stable-2.12.1

### Possible solution

No response

**Comment by caseydavenport** [comment]
@aagzoom I'm not especially familiar with linkerd - are you using it as a sidecar or a per-host proxy in your system?

**Comment by aagzoom** [comment]
@caseydavenport Hello!
We are using linkerd as sidecar in our system.

**Comment by caseydavenport** [comment]
The only thing I can think of here is that linkerd itself is resolving the Service IP into a pod IP address and not performing LoadBalancing, and thus bypassing Calico's own Service LoadBalancing implementation.

I'm not sure why that would be, but the logs themselves are coming from Linkerd which is running within the client pod, and so is occurring before the packet ever makes it to Calico's eBPF programs as far as I understand.

CC @tomastigera to double check I'm not crazy.

**Comment by tomastigera** [comment]
> I see this line in the logs in broken setup:
> 
> `[ 0.204913s] DEBUG ThreadId(01) outbound:accept{client.addr=172.25.229.60:42842}:proxy{addr=172.25.240.43:50051}: linkerd_cache: Caching new value key=Accept { orig_dst: OrigDstAddr(172.25.240.43:50051), protocol: () }`
> 
> And this line in correctly working setup:
> 
> `[ 0.184450s] DEBUG ThreadId(01) outbound:accept{client.addr=172.27.102.88:44572}:proxy{addr=10.106.182.82:50051}: linkerd_cache: Caching new value key=Accept { orig_dst: OrigDstAddr(10.106.182.82:50051), protocol: () }`
> 
> In the first line linkerd-proxy uses Pod address (172.25.240.43:50051). In the second line linkerd-proxy uses Service address (10.106.182.82:50051).

What logs are these?

Note that in eBPF mode, connections within the cluster are always pod-pod onthe wire even if they are routed via a service. When the app calls `connect()` the final destination provided by the services is picked up and used. So the service resolution is done in connect time, there is no NAT for each individual packet. However, for the app that made the `connect()` call it still looks like it is connecting to a service IP.

So if these logs are not from the client, they seem OK.

**Comment by tomastigera** [comment]
Note that if the service has multiple backends, `connect()` gets loadbalances across all of them.

**Comment by tomastigera** [comment]
You can turn off the connect-time loadbalancing (ctlb) by setting `bpfConnectTimeLoadBalancingEnabled=false` in [felix](https://projectcalico.docs.tigera.io/reference/resources/felixconfig) configuration however, that could bring a host of other issues. These issues are being addres in the upcoming 3.25 release. It relates to this issue https://github.com/projectcalico/calico/issues/4509 However, you cannot torn it on/off per service. We may be able to do that in the future if the k8s kube-proxy front end code were to provide label - me not sure atm.

**Comment by nstrashevskii** [comment]
Was this problem eventually resolved in new versions of calico?

**Comment by zoftdev** [comment]
> Was this problem eventually resolved in new versions of calico?


in 3.27 you need to change 2 parameter about CTLB and HostNat as in this issue:
https://github.com/projectcalico/calico/issues/8495
