### ISSUE TITLE
Windows package of 3.24.3 NSSM folder name is wrong.

### ISSUE THREAD

**Issue by p-v-a** [projectcalico/calico#6915]
Windows package of 3.24.3 NSSM folder name is wrong.

## Expected Behavior

Clean install Calico on a windows node

## Current Behavior

An error during install due to Calico scripts expects nssm.exe being under ./nssm folder, in fact falder now called nssm-2.24-103-gdee49fc due to 3a2abe57cb9467a34353d8c5dad3e56caf09c90a.

## Steps to Reproduce (for bugs)

1. Download install-calico-windows.ps1 for 3.24.3
2. Initiate install
3. Observe the error during install

## Context

At the moment I can't proceed with Calico deployment on a windows nodes 

## Your Environment

* Calico version: 3.24.3
* Orchestrator version (e.g. kubernetes, mesos, rkt): kubernetes 1.22
* Operating System and version: Windows Server 2019
* Link to your project (optional):

**Comment by chrisjohnson00** [comment]
A workaround for this is to pin to the older release of the `calico-windows` binary.

```
.\install-calico-windows.ps1 -ReleaseBaseURL "https://github.com/projectcalico/calico/releases/download/v3.24.1/" -ReleaseFile calico-windows-v3.24.1.zip
```

**Comment by song-jiang** [comment]
@chrisjohnson00 Thanks for reporting this. Let me see what I can do to fix this.

**Comment by song-jiang** [comment]
@chrisjohnson00 Can you download the installation script and try it again? This issue is fixed. I'll be working on a better solution in the mean time.

**Comment by chrisjohnson00** [comment]
> @chrisjohnson00 Can you download the installation script and try it again? This issue is fixed. I'll be working on a better solution in the mean time.

Will do! I was testing a non related change when I ran into this, so I will rebuild and test today.

**Comment by song-jiang** [comment]
> I did not report this, just bubbled it up to your attention

Sorry my mistake. Thanks @p-v-a for reporting this issue.

**Comment by chrisjohnson00** [comment]
> > @chrisjohnson00 Can you download the installation script and try it again? This issue is fixed. I'll be working on a better solution in the mean time.
> 
> Will do! I was testing a non related change when I ran into this, so I will rebuild and test today.

Yes, it seems to be working fine now!  Thanks!!

**Comment by chrisjohnson00** [comment]
@song-jiang  - thanks for the fix!
While I have your attention.

Is there another url for `install-calico-windows.ps1` which would allow me to pin our automation to a full version?  Instead of this link which is `v3.24.x` I'd like to pin to `v.3.24.2` for example.
https://projectcalico.docs.tigera.io/archive/v3.24/scripts/install-calico-windows.ps1

**Comment by song-jiang** [comment]
I'm afraid there's no URL for v3.24.2 installation script.
If you really want to do it, maybe download v3.24.3 script and run
```
./install-calico-windows.ps1 -ReleaseBaseURL https://github.com/projectcalico/calico/releases/download/v3.24.2 -ReleaseFile calico-windows-v3.24.2.zip 

```
I haven't tried it myself and it is not recommended.

**Comment by chrisjohnson00** [comment]
> I'm afraid there's no URL for v3.24.2 installation script. If you really want to do it, maybe download v3.24.3 script and run
> 
> ```
> ./install-calico-windows.ps1 -ReleaseBaseURL https://github.com/projectcalico/calico/releases/download/v3.24.2 -ReleaseFile calico-windows-v3.24.2.zip 
> ```
> 
> I haven't tried it myself and it is not recommended.

Yes, thanks.  Those URL parameters are part of the workaround I commented about initially on this issue.
Thanks for the help and quick responses on this!!
