### ISSUE TITLE
ExecSync cmd from runtime service failed" err="rpc error: code = Unknown desc = operation timeout: context deadline exceeded

### ISSUE THREAD

**Issue by deco-zhang** [projectcalico/calico#6921]
## Steps to Reproduce (for bugs)

1.  kubernetes cluster add a new node ,  but if node running several days ,  the calico pod is error "operation timeout: context deadline exceeded"
2.  error info :
 kubelet[1301]: E1028 03:01:48.810665    1301 remote_runtime.go:394] "ExecSync cmd from runtime service failed" err="rpc error: code = Unknown desc = operation timeout: context deadline exceeded" containerID="f58ec4ccfad18d52b8d066c1ab60c484377fe862b29880cbec4c602ed1313c1f" cmd=[/bin/calico-node -bird-ready -felix-ready]
3.  calico use too many socket , if restart node will be recover ， but several days also happened error。 
4.  the calico pod can not  docker exec -it calico 
5.  please help me ，thx。

## Your Environment

* Calico version   v3.8.9
* Orchestrator version (e.g. kubernetes, mesos, rkt):  kubernetes  v1.21.8
* Operating System and version:   centos 7  kernel  5.4.221
* Link to your project (optional):

<img width="1327" alt="image" src="https://user-images.githubusercontent.com/101389472/198864956-e51cc1f8-374b-43f0-8153-c669a856aa80.png">

**Comment by deco-zhang** [comment]
docker info

Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)
  scan: Docker Scan (Docker Inc., v0.21.0)

Server:
 Containers: 28
  Running: 13
  Paused: 0
  Stopped: 15
 Images: 10
 Server Version: 20.10.6
 Storage Driver: overlay2
  Backing Filesystem: xfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 10c12954828e7c7c9b6e0ea9b0c02b01407d3ae1
 runc version: v1.1.2-0-ga916309
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.4.221-1.el7.elrepo.x86_64
 Operating System: CentOS Linux 7 (Core)
 OSType: linux
 Architecture: x86_64
 CPUs: 16
 Total Memory: 61.71GiB
 Name: k8s-prod-node-c05-10-90-2-254
 ID: A7J3:75XN:BGER:3IEC:JQT3:HVG7:7EEH:TIDR:ZBJR:HFJD:EST6:HQ6O
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

**Comment by deco-zhang** [comment]
calico log

**Comment by song-jiang** [comment]
@deco-zhang Calico v3.8.9 is very old. Maybe you should upgrade to latest version if possible?

**Comment by deco-zhang** [comment]
@song-jiang    thank you support ,  when i rollback the kernel 5.4.221 to 5.4.204   it fix .
