### ISSUE TITLE
rr crash , external network can not access k8s pod ip  immediately

### ISSUE THREAD

**Issue by timchenxiaoyu** [projectcalico/calico#6922]
rr crash , external network can not access k8s pod ip  immediately，it is dangerous ！！！

**Comment by coutinhop** [comment]
Hi @timchenxiaoyu, could you please provide more information on your issue and setup (environment, expected/current behavior, steps to reproduce, etc)?

Our docs do mention to run at least 2 route reflectors for redundancy (https://projectcalico.docs.tigera.io/networking/bgp#route-reflectors), did your have only one running or 2 of them crashed? Do you know what caused the crash?
