### ISSUE TITLE
csi-node-driver not started on ARM based EKS nodes

### ISSUE THREAD

**Issue by vw393** [projectcalico/calico#6928]
Hello,
I'm struggling to find out why csi-node-driver ignores the ARM based nodes in an AWS EKS cluster. No issues apparently with AMD based nodes.
For example, on this cluster I currently have a nodegroup with 16 m6a.large (AMD) nodes and another nodegroup with 3 tg4.large (ARM) nodes. Only the csi-node-driver pods for the AMD nodes are running:

 ➜ kubectl -n calico-system get pods | grep calico-node | wc -l
      19
 ➜ kubectl -n calico-system get pods | grep csi-node-driver | wc -l
      16 

The only error entries I find in the kubelet journal of the ARM nodes are like:
```
. . .
E1030 08:39:13.424233    1542 kubelet.go:2394] "Container runtime network not ready" networkReady="NetworkReady=false reason:NetworkPluginNotReady message:Network plugin returns error: cni plugin not initialized"
. . .
E1030 08:39:13.522523    1542 kubelet.go:2469] "Error getting node" err="node \"ip-10-20-17-22.eu-west-1.compute.internal\" not found"
. . .
E1030 08:39:13.744672    1542 nodelease.go:49] "Failed to get node when trying to set owner ref to the node lease" err="nodes \"ip-10-20-17-22.eu-west-1.compute.internal\" not found" node="ip-10-20-17-22.eu-west-1.compute.internal"
. . .
E1030 08:39:14.640804    1542 driver-call.go:262] Failed to unmarshal output for command: init, output: "", error: unexpected end of JSON input
. . .
W1030 08:39:14.735715    1542 driver-call.go:149] FlexVolume: driver call failed: executable: /usr/libexec/kubernetes/kubelet-plugins/volume/exec/nodeagent~uds/uds, args: [init], error: fork/exec /usr/libexec/kubernetes/kubelet-plugins/volume/exec/nodeagent~uds/uds: no such file or directory, output: ""
. . .
E1030 08:39:18.548625    1542 kubelet.go:2394] "Container runtime network not ready"
networkReady="NetworkReady=false reason:NetworkPluginNotReady message:Network plugin returns error: cni plugin not initialized"
E1030 08:39:18.565474    1542 pod_workers.go:951] "Error syncing pod, skipping" err="network is not ready: container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:Network plugin returns error: cni plugin not initialized" pod="kube-system/ebs-csi-node-6k8bq" podUID=bac2d254-37fc-4e60-b525-7c6ec2d5edb1
```

Something I don't understand in the errors is, uds was installed on those nodes, so I don't see why I find a no such file or directory in the kubelet logs:

```
# ls -la /usr/libexec/kubernetes/kubelet-plugins/volume/exec/nodeagent~uds/uds
-r-xr-x--- 1 root root 5086008 Oct 30 08:39 /usr/libexec/kubernetes/kubelet-plugins/volume/exec/nodeagent~uds/uds

# stat /usr/libexec/kubernetes/kubelet-plugins/volume/exec/nodeagent~uds/uds
  File: ‘/usr/libexec/kubernetes/kubelet-plugins/volume/exec/nodeagent~uds/uds’
  Size: 5086008         Blocks: 9936       IO Block: 4096   regular file
Device: 10301h/66305d   Inode: 46149166    Links: 1
Access: (0550/-r-xr-x---)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2022-10-30 08:39:36.495745363 +0000
Modify: 2022-10-30 08:39:36.495745363 +0000
Change: 2022-10-30 08:39:36.495745363 +0000
 Birth: -

# /usr/libexec/kubernetes/kubelet-plugins/volume/exec/nodeagent~uds/uds version
Version is 0.1

# /usr/libexec/kubernetes/kubelet-plugins/volume/exec/nodeagent~uds/uds init
{"status":"Success","message":"Init ok.","capabilities":{"attach":false}}
```

Any hint is highly appreciated

## Expected Behavior

I expect to see a `csi-node-driver` pod running in namespace `calico-system` also for ARM-based nodes

## Current Behavior

I see a `csi-node-driver` pod running in namespace `calico-system` only for AMD-based nodes

## Your Environment

* Calico version : 3.24.3
* Kubernetes 1.23 on EKS
* ARN nodes on amzn2 5.4.209-116.367.amzn2.aarch64

**Comment by Josh-Tigera** [comment]
You might be hitting [Issue 5356](https://github.com/projectcalico/calico/issues/5356) which is fixed by [PR 5515](https://github.com/projectcalico/calico/pull/5515) because your AMD hosts have the necessary dynamic libraries present while your ARM hosts do not. Would you be able to follow some of the troubleshooting steps in the linked issue to narrow down if you are in fact hitting that issue?

**Comment by vw393** [comment]
Please forget my request.
The binaries are statically linked, I had checked that. What I missed, is that there where some node taints left over on the ARM instances, that the csi-node-driver daemonset was observing (not the calico-node daemonset though).
