### ISSUE TITLE
Can not ping external network from extra network interface created using multus + calico

### ISSUE THREAD

**Issue by rveerama1** [projectcalico/calico#6934]
I have created a simple pod with two network interfaces (default eth0 and net1). I can ping external network via _eth0_ but not via _net1_.

## Expected Behavior

Expecting similar behavior as eth0. Should be able to ping eternal network via _net1_ interface 

## Current Behavior

Can not ping from _net1_ interface. My guess is NAT is happening on extra network interface address space.

## Steps to Reproduce (for bugs)

sudo tee /etc/sysctl.d/kubernetes.conf <<EOF
net.bridge.bridge-nf-call-ip6tables = 1
net.bridge.bridge-nf-call-iptables = 1
net.ipv4.ip_forward = 1
EOF

sudo tee /etc/modules-load.d/containerd.conf <<EOF
overlay
br_netfilter
EOF

sudo kubeadm init --pod-network-cidr=192.168.0.0/16

kubectl create -f https://projectcalico.docs.tigera.io/manifests/tigera-operator.yaml

kubectl apply -f calico/custom-resources.yaml 

custom-resources.yaml 
```
# This section includes base Calico installation configuration.
# For more information, see: https://projectcalico.docs.tigera.io/master/reference/installation/api#operator.tigera.io/v1.Installation
apiVersion: operator.tigera.io/v1
kind: Installation
metadata:
  name: default
spec:
  # Configures Calico networking.
  calicoNetwork:
    # Note: The ipPools section cannot be modified post-install.
    ipPools:
    - blockSize: 26
      cidr: 192.168.0.0/16
      encapsulation: VXLANCrossSubnet
      natOutgoing: Enabled
      nodeSelector: all()
    containerIPForwarding: Enabled
---

# This section configures the Calico API server.
# For more information, see: https://projectcalico.docs.tigera.io/master/reference/installation/api#operator.tigera.io/v1.APIServer
apiVersion: operator.tigera.io/v1
kind: APIServer 
metadata: 
  name: default 
spec: {}

```

./calicoctl get IPPool  default-ipv4-ippool -o yaml
```
apiVersion: projectcalico.org/v3
kind: IPPool
metadata:
  creationTimestamp: "2022-10-31T20:12:16Z"
  name: default-ipv4-ippool
  resourceVersion: "636"
  uid: 12762d4d-bef0-46b0-8596-003b5de867e2
spec:
  allowedUses:
  - Workload
  - Tunnel
  blockSize: 26
  cidr: 192.168.0.0/16
  ipipMode: Never
  natOutgoing: true
  nodeSelector: all()
  vxlanMode: CrossSubnet

```

kubectl apply -f https://raw.githubusercontent.com/k8snetworkplumbingwg/multus-cni/master/deployments/multus-daemonset-thick.yml

kubectl apply -f macvlan-conf.yaml 
```
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: macvlan-conf
spec:
  config: '{
      "cniVersion": "0.3.0",
      "type": "macvlan",
      "master": "eno0",
      "mode": "bridge",
      "ipam": {
        "type": "host-local",
        "subnet": "192.168.1.0/24",
        "rangeStart": "192.168.1.200",
        "rangeEnd": "192.168.1.216",
        "routes": [
          { "dst": "0.0.0.0/0" }
        ],
        "gateway": "192.168.1.1"
      }
    }'

```

kubectl apply -f samplepod.yaml 
```
apiVersion: v1
kind: Pod
metadata:
  name: samplepod
  annotations:
    k8s.v1.cni.cncf.io/networks: macvlan-conf
spec:
  containers:
  - name: samplepod
    command: ["/bin/ash", "-c", "trap : TERM INT; sleep infinity & wait"]
    image: praqma/network-multitool

```

## Your Environment

* Calico version
 $ ./calicoctl version
Client Version:    v3.24.3
Git commit:        d833a9e38
Cluster Version:   v3.24.3
Cluster Type:      typha,kdd,k8s,operator,bgp,kubeadm

* Orchestrator version (e.g. kubernetes, mesos, rkt): k8s
* Operating System and version: Ubuntu 22.04
* Link to your project (optional): Similar issue created https://github.com/k8snetworkplumbingwg/multus-cni/issues/945

**Comment by coutinhop** [comment]
Not sure on all the details of your setup, but it looks like this is happening because the `macvlan-conf` CIDR is within the calico IP pool CIDR range, which would make calico apply NAT (because it's an IP inside its pool and `natOutgoing` is enabled)... Try configuring `macvlan-conf` with a CIDR outside of 192.168.0.0/16?

**Comment by rveerama1** [comment]
@coutinhop thanks for the reply.

Tried different macvlan-conf too it didn't work.
```
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: macvlan-conf
spec:
  config: '{
      "cniVersion": "0.3.0",
      "type": "macvlan",
      "master": "ens3",
      "mode": "bridge",
      "ipam": {
        "type": "host-local",
        "subnet": "10.10.10.0/24",
        "rangeStart": "10.10.10.10",
        "rangeEnd": "10.10.10.200",
        "routes": [
          { "dst": "0.0.0.0/0" }
        ],
        "gateway": "10.10.10.1"
      }
    }'
```

**Comment by caseydavenport** [comment]
For what it's worth, Calico CNI doesn't fully support running in a multi-pod-NIC mode today. You might be able to get it to work but there are some known limitations.

This issue is the catch-all for that: https://github.com/projectcalico/calico/issues/5199

**Comment by samar08** [comment]
But the good thing is @rveerama1  you are able to atleast attach macvlan interface to the pod which I am not able to do with calico latest versions like 3.25.0 or 3.24.5. Were you able to attach macvlan interface to the pod in addition to the eth0 interface created by calico (latest version)?
