### ISSUE TITLE
BPF ifstate map exhaustion due to possible leak

### ISSUE THREAD

**Issue by brenix** [projectcalico/calico#6935]
Several of our development and production clusters have been experiencing events of network loss/instability. This appears to be due to if bpf ifstate map being exhausted, which causes the calico-node pods to log the following messages:

```
[WARNING][28344] felix/caching_map.go 246: Error while updating DP map error=argument list too long
[WARNING][28344] felix/bpf_ep_mgr.go 678: Failed to write updates to ifstate BPF map. error=multiple errors while updating dataplane (1)
```

This occurs in clusters with varying node (<100) and pod counts (<1000), but nothing extreme.

As a short-term solution, we have found that increasing the `bpfMapSizeIfState` value in the felix configuration from the default (`1000`) to something larger (e.g `3000`) restores connectivity and the warnings stop. However, given enough time we will see that even with the increased map size the issue will resurface. Once of our production clusters has more churn in pods (spawned from jobs) which tends to experience this more frequently too.

Using debugging tools such as [bpf-map](https://github.com/cilium/bpf-map), we can also see that that count of keys in the the bpf map (stored under `/sys/fs/bpf/tc/globals/cali_iface2`) continues to increase, but never decreases when workloads are removed. Dumping the data from the map also shows old interfaces that no longer exist.

Only when the calico-node pods are recycled, we eventually see that bpf map size is reduced and the logs show the pending deletions:

```
[INFO][94] felix/caching_map.go 132: Recalculated pending operations cached=2728 name="cali_v4_nat_be" pendingDels=2728 pendingUpdates=0
```

## Expected Behavior

* The bpf ifstate map should reflect what is actual state of the cluster.
* The old map entries to interfaces/workloads which no longer exist should be automatically cleaned up through some routine

## Current Behavior

* The bpf ifstate map continues to grow, without ever decreasing
* Once the number of entries (defined via `bpfMapSizeIfState`) becomes exhausted, calico-node pods begin logging warnings and cluster network becomes unstable.

## Possible Solution

Based on the behavior, it seems entries are being leaked and not cleaned up. I'd expect that some routine which is meant to do this is not working as expected. It only occurs during pod startup.

## Steps to Reproduce (for bugs)

1. Using [bpf-map](https://github.com/cilium/bpf-map) or a similar tool, get a count of keys in the ifstate map on a given node:

    ```shell
	$ sudo ./bpf-map dump /sys/fs/bpf/tc/globals/cali_iface2  | grep Key | wc -l
    22
	```

1. Create a Pod assigned to that same node (e.g using `.spec.nodeName`)
1. Get the count of keys in the ifstate map again

    ```shell
    $ sudo ./bpf-map dump /sys/fs/bpf/tc/globals/cali_iface2  | grep Key | wc -l
    23
    ```

1. Delete the pod and wait for teardown
1. Get the count of keys from the ifstate map again

    ```shell
    $ sudo ./bpf-map dump /sys/fs/bpf/tc/globals/cali_iface2  | grep Key | wc -l
    23
    ```

    As you can see, the count did not decrease. You can also see that the interface that as associated to the pod still exists in the map, but does not exist in the list of interfaces on the host:

    ```shell
    $ sudo ./bpf-map dump /sys/fs/bpf/tc/globals/cali_iface2 | grep cali199822f2
    00000000  03 00 00 00 63 61 6c 69  31 39 39 38 32 32 66 32  |....cali199822f2|

    $ ip link | grep cali199822f2
    ```
    
1. Delete the calico-node pod running on that node. The logs will show the pending deletions (in our case this is the one pod that was created and removed:

    ```
    [INFO][91] felix/caching_map.go 80: Loaded cache from dataplane. count=23 name="cali_iface"
    [INFO][91] felix/caching_map.go 132: Recalculated pending operations cached=23 name="cali_iface" pendingDels=1 pendingUpdates=0
    ```

1. Get the count of keys again

    ```
    $ sudo ./bpf-map dump /sys/fs/bpf/tc/globals/cali_iface2  | grep Key | wc -l
    22
    ```

## Your Environment

* Calico version: 3.24.3 (w/typha)
* Orchestrator version (e.g. kubernetes, mesos, rkt): kubernetes
* Operating System and version: Ubuntu 20.04 Focal

**Comment by tomastigera** [comment]
OK thank you that is very helpful!

**Comment by tomastigera** [comment]
@brenix you can try `v3.24.4-4-g95659e1167b4` which includes the backported fix

**Comment by brenix** [comment]
Oh cool, didn't realize this would be backported. I briefly tried the `v3.25.0-0.dev-440-gcc33e80eb864` image tag but didn't have much time to validate. 

Thanks for getting this out there so quickly!

**Comment by brenix** [comment]
We have had 3.24.5 deployed for a day or so now and have not experienced the issue. Thanks again!
