### ISSUE TITLE
Calico node zombie container

### ISSUE THREAD

**Issue by prometheus-tao** [projectcalico/calico#6945]
Occasionally, the calico node zombie container appears in the k8s cluster. It cannot stop and enter the container command line, and the network access is normal.
## Current Behavior

stuck all the time
1. kubectl logs calico-node-dv7s2 -n kube-system
2. kubectl exec -it calico-node-dv7s2 bash -n kube-system
## Possible Solution

1. docker ps | grep calico-node-dv7s2
3. ps -elf |grep <container_id>, found container-shim pid
4. kill <pid>
## Steps to Reproduce (for bugs)

1.
5.
6.
7.

## Your Environment

* Calico version v3.13.4
* Orchestrator version (e.g. kubernetes, mesos, rkt): v1.18.20
* Operating System and version: centos 7.9 kernel: 4.4.205-1.el7.elrepo.x86_64
* Link to your project (optional):

**Comment by caseydavenport** [comment]
Calico v3.13 is very old and no longer supported. Please upgrade to a modern version of Calico and open a new issue if you're still seeing the same behavior.

**Comment by zheng1** [comment]
Same issue in v3.20.0

**Comment by prometheus-tao** [comment]
> Same issue in v3.20.0

Then you solv this issue by some method ? @zheng1

**Comment by zheng1** [comment]
> > Same issue in v3.20.0
> 
> Then you solv this issue by some method ? @zheng1

@prometheus-tao I guess it is probably more related to the kernel. ubuntu 5.4.0-33-generic has no problem, but 5.4.0-132-generic will have the same problem.
