### ISSUE TITLE
Missing operator image `v1.27.16`, referenced in the upgrade documentation/manifest

### ISSUE THREAD

**Issue by jguedez** [projectcalico/calico#6951]
The documentation for upgrading version `3.23` ([link](https://projectcalico.docs.tigera.io/archive/v3.23/maintenance/kubernetes-upgrade#upgrading-an-installation-that-uses-the-operator)) points to image `quay.io/tigera/operator:v1.27.16`

    $ curl -s https://projectcalico.docs.tigera.io/archive/v3.23/manifests/tigera-operator.yaml | grep quay
            image: quay.io/tigera/operator:v1.27.16

However, this tag does not currently exist, also confirmed in [quay.io](https://quay.io/repository/tigera/operator):

    $ docker pull quay.io/tigera/operator:v1.27.16
    Error response from daemon: manifest for quay.io/tigera/operator:v1.27.16 not found: manifest unknown: manifest unknown

## Expected Behavior

The manifest should refer to an existing image

## Current Behavior

The manifest does not refer to an existing image

## Possible Solution

1. Add the missing image:tag
2. Update the manifest to point to an existing tag (`v1.27.15`? That seems to have been uploading recently...)

## Steps to Reproduce (for bugs)

1. Fetch the manifest
2. Confirm image is missing

## Context

This would prevent upgrades in the 3.23 series

## Your Environment

This issue is independent of the environment to be upgraded

**Comment by keliansb** [comment]
I just encountered the same problem when trying to update Calico from version 3.23.2 to version 3.23.5.
