### ISSUE TITLE
Question: When the k8s node IP changes, how to change the IP configuration of the calico node

### ISSUE THREAD

**Issue by sniperking1234** [projectcalico/calico#6954]
I modified the IP of the master node of the K8S cluster, but the route generated by calico still uses the original IP address.What configuration should I modify so that calico can generate the correct routes. calico DATASTORE_TYPE is kubernetes.

**Comment by caseydavenport** [comment]
@sniperking1234 we're going to need more information from you to answer this question.

In general you shouldn't need to change any configuration - Calico will respond to node IP changes accordingly.

But this depends on what version you're running, for one. Please fill out the issue template when raising issues - it gives us the information we need to answer them.

**Comment by sniperking1234** [comment]
I tried to modify the node ip address again, this time it was normal, so close this issue.
