### ISSUE TITLE
Overwriting the neutron_election key in etcd leaves us permanently with no leader

### ISSUE THREAD

**Issue by MatMeredith** [projectcalico/calico#696]
Scenario: write a value in to the neturon_election key in etcd and don't specify a TTL.   The current Neutron leader will abdicate because its process ID no longer matches the value in etcd, and no other process will ever take over because the key won't time out.   Even restart of Neutron does not recover from this.

Suggest the easy fix would be for the Elector to check that the key has a (sensible?) TTL associated with it when it queries it and delete it if it doesn't.

**Comment by Lukasa** [comment]
So this is fundamentally a quite low priority bug. It *can* happen, but to have it happen an entity needs to write a key without a TTL into our namespace in etcd. We generally consider etcd to be a trusted DB, so bad data in there is not really something we defend against.

However, we *can* defend against this quite easily so we *should* do it: it's just not something that has to be done right this second.

**Comment by lwr20** [comment]
@plwhite pointed out to me that this behaviour is arguably useful - if we ever need to disable the refresh that the neutron leader does, we simply write a key without a TTL into here.  

Possible scenarios that might be useful in (note that we've not tried these and do not recommend them at this point!):  
- to diagnose a bad state the system had got into 
- disable refresh during upgrade

**Comment by fasaxc** [comment]
Would be good to log a warning at least (presumably, etcd tells us that there's a ttl on the key when we read it?)

**Comment by fasaxc** [comment]
Closing as stale/arguably not a bug.
