### ISSUE TITLE
EndpointSlices Endpoint using v1beta1 not v1

### ISSUE THREAD

**Issue by siegenthalerroger** [projectcalico/calico#6990]
## Expected Behavior
Calico would use the new v1 version of EndpointSlices not v1beta1 after an upgrade to k8s 1.25.

## Current Behavior
The calico-typha pod is not coming online and running pods in other node pools are also erroring out but at least reporting themselves as running.

Log of calico-typha pod (regardless of if running with kubelet 1.24.6 or 1.25.2):
```
[INFO][7] watchercache.go 188: Failed to perform list of current data during resync ListRoot="/calico/resources/v3/projectcalico.org/kubernetesendpointslices" error=resource does not exist: KubernetesEndpointSlice with error: the server could not find the requested resource
```

K8s API resources:
```
> kubectl api-resources | grep discovery
endpointslices                                         discovery.k8s.io/v1                      true         EndpointSlice
```

## Steps to Reproduce (for bugs)
1. Update to k8s 1.25.2
2. That is all.

## Your Environment

* Calico version: 3.21.6
* Orchestrator version (e.g. kubernetes, mesos, rkt): 1.25.2 on AKS (preview), tigera 1.23.8
* Operating System and version: Ubuntu 22.04 (iirc)
* Link to your project (optional): https://github.com/Azure/AKS/issues/3315

**Comment by coutinhop** [comment]
Hi @siegenthalerroger, it seems like calico v3.21 (and v3.22 as well) still haven't had the API updated to `v`. Is it possible to move to a more recent Calico version (v3.23+)?

**Comment by siegenthalerroger** [comment]
Sadly when using AKS the tigera operator and calico are in Microsoft managed namespaces that we can't change. So we're stuck waiting for an update on their side. The issue is known by MS though so I expect it'll be fixed before k8s 1.25 is GA.

**Comment by geotransformer** [comment]
> Hi @siegenthalerroger, it seems like calico v3.21 (and v3.22 as well) still haven't had the API updated to `v`. Is it possible to move to a more recent Calico version (v3.23+)?

Hi @coutinhop Upgrade calico (v3.23+) can help on this issue ?

**Comment by caseydavenport** [comment]
Calico has already updated to use the v1 API - I think we should close this as it's an issue with an external integration pulling in an outdated version of Calico, rather than a bug in Calico itself.

**Comment by siegenthalerroger** [comment]
fwiw the calico documentation still makes no reference to 1.25 support which was one of the contributing confusing factors. https://projectcalico.docs.tigera.io/getting-started/kubernetes/requirements
