### ISSUE TITLE
window node pod can't connect to the linux.

### ISSUE THREAD

**Issue by andyzheung** [projectcalico/calico#6996]
I install the calico on windows, and deploy pod is running, but follow the demo I can't connect window pod to linux pod, and windows two windows pod also can't ping each other..
https://projectcalico.docs.tigera.io/archive/v3.22/getting-started/windows-calico/demo

![image](https://user-images.githubusercontent.com/22912347/201863437-6ab2fa64-b75f-4021-a010-f3e1920490b0.png)

1 can't connect to 6 and 5,
3 and 4 can't ping ok to each other.

**Comment by andyzheung** [comment]
Did anything configure wrong?

**Comment by andyzheung** [comment]
pod is running, but 
1、I read the calico node logs on windows:
2022-11-15 17:20:23.657 [INFO][1016] startup/ipam.go 2134: Looking up existing affinities for host host="win-35goccl4pgg"
2022-11-15 17:20:23.660 [INFO][1016] startup/ipam.go 369: Looking up existing affinities for host host="win-35goccl4pgg"
2022-11-15 17:20:23.662 [INFO][1016] startup/ipam.go 486: Trying affinity for 192.168.65.0/26 host="win-35goccl4pgg"
2022-11-15 17:20:23.665 [INFO][1016] startup/ipam.go 152: Attempting to load block cidr=192.168.65.0/26 host="win-35goccl4pgg"
2022-11-15 17:20:23.667 [INFO][1016] startup/ipam.go 229: Affinity is confirmed and block has been loaded cidr=192.168.65.0/26 host="win-35goccl4pgg"
2022-11-15 17:20:23.667 [INFO][1016] startup/ipam.go 2167: Host's block '192.168.65.0/26'  host="win-35goccl4pgg"
2022-11-15 17:20:23.674 [INFO][1016] startup/dataplane_windows.go 358: Attempting to create HNSNetwork {"Name":"Calico","Type":"Overlay","Subnets":[{"AddressPrefix":"192.168.65.0/26","GatewayAddress":"192.168.65.1","Policies":[{"Type":"VSID","VSID":4096}]}]} subnet="192.168.65.0/26"
2022-11-15 17:20:23.684 [ERROR][1016] startup/dataplane_windows.go 119: Unable to create hns network Calico subnet="192.168.65.0/26"
2022-11-15 17:20:23.684 [ERROR][1016] startup/startup.go 221: Unable to ensure network for os error=failed to create HNSNetwork Calico: failed during hnsCallRawResponse: hnsCall failed in Win32: An adapter was not found. (0x803b0006)
2022-11-15 17:20:23.684 [WARNING][1016] startup/utils.go 49: Terminating
Calico node initialisation failed, will retry...
2、describe pod:
![image](https://user-images.githubusercontent.com/22912347/201881997-7aca41ad-d425-410d-86f9-3393b2b176e9.png)
![image](https://user-images.githubusercontent.com/22912347/201882151-7ce54890-35a5-4cd0-b5ee-412a39d4a196.png)
ls
![image](https://user-images.githubusercontent.com/22912347/201882300-6b6822e7-da53-4ef7-931c-3356d35fb365.png)

**Comment by andyzheung** [comment]
1、kubectl exec -it  xxxx -- powershell
route PRINT:
![image](https://user-images.githubusercontent.com/22912347/201886901-f0105bdf-2af2-48e2-9240-976be048f77b.png)

I didn't see any calico network info, i think is not right?

**Comment by andyzheung** [comment]
kubectl exec -it xxx -- powershell
netsh interface ipv4 show interfaces 
![image](https://user-images.githubusercontent.com/22912347/201970521-8c2fea7d-51a4-4e7d-9aa7-655c2e796807.png)

**Comment by coutinhop** [comment]
pinging @song-jiang 

@andyzheung from the link you posted, you seem to be using Calico v3.22, is that right? What version kubernetes are you using? Are you using docker or containerd on the windows nodes?

I wonder if this could be related to using the no-longer supported dockershim on kubernetes v1.24 or later (https://kubernetes.io/blog/2022/02/17/dockershim-faq/)... What do your interface names look like, are they still non-ascii (as in the other issue you posted)?

**Comment by andyzheung** [comment]
> pinging @song-jiang
> 
> @andyzheung from the link you posted, you seem to be using Calico v3.22, is that right? What version kubernetes are you using? Are you using docker or containerd on the windows nodes?
------------------------------
yes, calico version is v3.22, and kubernetes version is v1.21.0. I install docker engine on windows node, windows version is windows server 2019 1809 build 17763.973.

> I wonder if this could be related to using the no-longer supported dockershim on kubernetes v1.24 or later (https://kubernetes.io/blog/2022/02/17/dockershim-faq/)... What do your interface names look like, are they still non-ascii (as in the other issue you posted)?
------------------------------
how to check the interface name?  I just follow this to change my windows config.
2、the other problem to solve:
https://github.com/kubernetes-sigs/sig-windows-tools/issues/68

I have solved this, in windows server, before you start any service includes docker, set "controll panel" -> "region" -> "administrative" -> "change system locale..." -> check the option "Use Unicode UTF-8 for worldwide language support"
then reboot

**Comment by andyzheung** [comment]
Is there any suggestion? @song-jiang

**Comment by andyzheung** [comment]
I think the root cause is the following, but i don't know how it happens?

2022-11-16 10:12:13.545 [INFO][11636] startup/startup.go 425: Early log level set to info
2022-11-16 10:12:13.549 [INFO][11636] startup/utils.go 127: Using NODENAME environment for node name win-35goccl4pgg
2022-11-16 10:12:13.549 [INFO][11636] startup/utils.go 139: Determined node name: win-35goccl4pgg
2022-11-16 10:12:13.549 [INFO][11636] startup/startup.go 94: Starting node win-35goccl4pgg with version v3.22.5
2022-11-16 10:12:13.555 [INFO][11636] startup/startup.go 106: Skipping datastore connection test
2022-11-16 10:12:13.566 [INFO][11636] startup/autodetection_methods.go 103: Using autodetected IPv4 address on interface vEthernet (Ethernet0): 10.250.8.138/24
2022-11-16 10:12:13.566 [INFO][11636] startup/startup.go 699: No AS number configured on node resource, using global value
2022-11-16 10:12:13.576 [INFO][11636] startup/startup.go 815: Selected default IP pool is '192.168.0.0/16'
2022-11-16 10:12:13.580 [INFO][11636] startup/startup.go 218: Using node name: win-35goccl4pgg
2022-11-16 10:12:13.580 [INFO][11636] startup/startup_windows.go 57: Backend networking is vxlan, ensure vxlan network.
2022-11-16 10:12:13.580 [INFO][11636] startup/ipam.go 2063: Ensure block for host win-35goccl4pgg, ipv4 attr &{3 1 windows-reserved-ipam-handle windows host rsvd} ipv6 attr <nil>
2022-11-16 10:12:13.580 [INFO][11636] startup/ipam.go 2134: Looking up existing affinities for host host="win-35goccl4pgg"
2022-11-16 10:12:13.583 [INFO][11636] startup/ipam.go 369: Looking up existing affinities for host host="win-35goccl4pgg"
2022-11-16 10:12:13.586 [INFO][11636] startup/ipam.go 486: Trying affinity for 192.168.65.0/26 host="win-35goccl4pgg"
2022-11-16 10:12:13.587 [INFO][11636] startup/ipam.go 152: Attempting to load block cidr=192.168.65.0/26 host="win-35goccl4pgg"
2022-11-16 10:12:13.589 [INFO][11636] startup/ipam.go 229: Affinity is confirmed and block has been loaded cidr=192.168.65.0/26 host="win-35goccl4pgg"
2022-11-16 10:12:13.589 [INFO][11636] startup/ipam.go 2167: Host's block '192.168.65.0/26'  host="win-35goccl4pgg"
2022-11-16 10:12:13.596 [INFO][11636] startup/dataplane_windows.go 358: Attempting to create HNSNetwork **{"Name":"Calico","Type":"Overlay","Subnets":[{"AddressPrefix":"192.168.65.0/26","GatewayAddress":"192.168.65.1","Policies":[{"Type":"VSID","VSID":4096}]}]}** subnet="192.168.65.0/26"
2022-11-16 10:12:13.605 [ERROR][11636] startup/dataplane_windows.go 119: Unable to create hns network Calico subnet="192.168.65.0/26"
2022-11-16 10:12:13.605 [ERROR][11636] startup/startup.go 221: Unable to ensure network for os error=failed to create HNSNetwork Calico: failed during **hnsCallRawResponse: **hnsCall failed in Win32: An adapter was not found**. (0x8**03b0006)
2022-11-16 10:12:13.605 [WARNING][11636] startup/utils.go 49: Terminating
Calico node initialisation failed, will retry...

**Comment by andyzheung** [comment]
struggle for it.  I update the windows server to the following version:
![image](https://user-images.githubusercontent.com/22912347/202168435-cc8acb80-bdc7-4a80-9396-d6d02ab71c79.png)

and follow this instruction:
https://projectcalico.docs.tigera.io/getting-started/windows-calico/demo
![image](https://user-images.githubusercontent.com/22912347/202168634-52a1e1fc-62f7-47ee-835a-f55ded692ff6.png)

my window pod can connect to each other.
for example:
 kubectl exec pwsh -- powershell Invoke-WebRequest -Uri http://$(kubectl get po porter -o 'jsonpath={.status.podIP}') -UseBasicParsing -TimeoutSec 5
![image](https://user-images.githubusercontent.com/22912347/202168806-eded7a02-7290-4871-bda9-464b95be18e4.png)

but windows pod can't connect to the linux pod,linux pod also can't connect to windows pod.
my ippool is changed:
![image](https://user-images.githubusercontent.com/22912347/202169256-6fa9ef1d-bdb0-4c82-9b5a-443bb6b50b9b.png)

**Comment by song-jiang** [comment]
> HNSNetwork Calico: failed during hnsCallRawResponse: hnsCall failed in Win32: An adapter was not found. (0x803b0006)
Can you share the output of 
```
Get-HnsNetwork
Get-NetAdapter
```

**Comment by andyzheung** [comment]
Get-HnsNetwork
==>
PS C:\CalicoWindows\kubernetes> Get-HnsNetwork


ActivityId             : 24303D2F-17C6-4640-AC85-0F2BF12BB127
AdditionalParams       :
CurrentEndpointCount   : 0
Extensions             : {@{Id=E7C3B2F0-F3C5-48DF-AF2B-10FED6D72E7A; IsEnabled=False; Name=Microsoft Windows 筛选平台}, @{I
                         d=E9B59CFA-2BE1-4B21-828F-B6FBDBDDC017; IsEnabled=False; Name=Microsoft Azure VFP Switch Exten
                         sion}, @{Id=EA24CD6C-D17A-4348-9190-09F0D5BE83DD; IsEnabled=True; Name=Microsoft NDIS 捕获}}
Flags                  : 0
Health                 : @{AddressNotificationMissedCount=0; AddressNotificationSequenceNumber=0; InterfaceNotification
                         MissedCount=0; InterfaceNotificationSequenceNumber=0; LastErrorCode=0; LastUpdateTime=13313076
                         2786637301; RouteNotificationMissedCount=0; RouteNotificationSequenceNumber=0}
ID                     : C3C641B1-7AC1-43B2-9824-EEDE9B5A9DF9
IPv6                   : False
LayeredOn              : 71C23E77-52BD-4416-BDE7-54FB5EE7B96A
MacPools               : {@{EndMacAddress=00-15-5D-9A-4F-FF; StartMacAddress=00-15-5D-9A-40-00}}
MaxConcurrentEndpoints : 0
Name                   : nat
NatName                : ICS3A058A10-E5D6-4AA7-857C-02B4F3F118B5
Policies               : {}
Resources              : @{AdditionalParams=; AllocationOrder=2; Allocators=System.Object[]; Health=; ID=24303D2F-17C6-
                         4640-AC85-0F2BF12BB127; PortOperationTime=0; State=1; SwitchOperationTime=0; VfpOperationTime=
                         0; parentId=FB31C29A-E133-495D-83B2-30350A7A089C}
State                  : 1
Subnets                : {@{AdditionalParams=; AddressPrefix=172.25.0.0/20; GatewayAddress=172.25.0.1; Health=; ID=24EF
                         BA5A-F98E-4522-8989-BDC95241F251; Policies=System.Object[]; State=0}}
TotalEndpoints         : 0
Type                   : nat
Version                : 38654705669

ActivityId             : F0FD1269-6018-4437-B9BA-6C6C21CB6835
AdditionalParams       :
CurrentEndpointCount   : 3
DNSServerCompartment   : 4
DrMacAddress           : 00-15-5D-74-2C-23
Extensions             : {@{Id=E7C3B2F0-F3C5-48DF-AF2B-10FED6D72E7A; IsEnabled=False; Name=Microsoft Windows 筛选平台}, @{I
                         d=E9B59CFA-2BE1-4B21-828F-B6FBDBDDC017; IsEnabled=True; Name=Microsoft Azure VFP Switch Extens
                         ion}, @{Id=EA24CD6C-D17A-4348-9190-09F0D5BE83DD; IsEnabled=True; Name=Microsoft NDIS 捕获}}
Flags                  : 0
Health                 : @{LastErrorCode=0; LastUpdateTime=133130766582917728}
ID                     : 689B6A4F-DB62-4A51-9935-978556EE22DD
IPv6                   : False
LayeredOn              : 134FBBEF-780C-417F-AFF1-89F84D14C3C5
MacPools               : {@{EndMacAddress=00-15-5D-D0-CF-FF; StartMacAddress=00-15-5D-D0-C0-00}}
ManagementIP           : 10.250.8.155
MaxConcurrentEndpoints : 3
Name                   : Calico
Policies               : {@{Type=HostRoute}}
Resources              : @{AdditionalParams=; AllocationOrder=1; Allocators=System.Object[]; Health=; ID=F0FD1269-6018-
                         4437-B9BA-6C6C21CB6835; PortOperationTime=0; State=1; SwitchOperationTime=0; VfpOperationTime=
                         0; parentId=90D5E317-9462-4BC0-8DFC-0FD5B6B0640E}
State                  : 1
Subnets                : {@{AdditionalParams=; AddressPrefix=192.168.64.0/26; GatewayAddress=192.168.64.1; Health=; ID=
                         E4FC02D1-891F-4F23-B623-F306B2179C9F; ObjectType=5; Policies=System.Object[]; State=0}}
TotalEndpoints         : 3
Type                   : Overlay
Version                : 38654705669

ActivityId             : 87B83940-1B75-443D-82F0-A017AEB812F9
AdditionalParams       :
CurrentEndpointCount   : 0
DNSServerCompartment   : 3
DrMacAddress           : 00-15-5D-74-2C-23
Extensions             : {@{Id=E7C3B2F0-F3C5-48DF-AF2B-10FED6D72E7A; IsEnabled=False; Name=Microsoft Windows 筛选平台}, @{I
                         d=E9B59CFA-2BE1-4B21-828F-B6FBDBDDC017; IsEnabled=True; Name=Microsoft Azure VFP Switch Extens
                         ion}, @{Id=EA24CD6C-D17A-4348-9190-09F0D5BE83DD; IsEnabled=True; Name=Microsoft NDIS 捕获}}
Flags                  : 0
Health                 : @{LastErrorCode=0; LastUpdateTime=133130764695781848}
ID                     : FD73A38F-A961-43CE-BF5A-93D592918DF9
IPv6                   : False
LayeredOn              : 134FBBEF-780C-417F-AFF1-89F84D14C3C5
MacPools               : {@{EndMacAddress=00-15-5D-0F-9F-FF; StartMacAddress=00-15-5D-0F-90-00}}
ManagementIP           : 10.250.8.155
MaxConcurrentEndpoints : 0
Name                   : External
Policies               : {}
Resources              : @{AdditionalParams=; AllocationOrder=1; Allocators=System.Object[]; Health=; ID=87B83940-1B75-
                         443D-82F0-A017AEB812F9; PortOperationTime=0; State=1; SwitchOperationTime=0; VfpOperationTime=
                         0; parentId=90D5E317-9462-4BC0-8DFC-0FD5B6B0640E}
State                  : 1
Subnets                : {@{AdditionalParams=; AddressPrefix=192.168.255.0/30; GatewayAddress=192.168.255.1; Health=; I
                         D=7134CA67-0264-4A6E-9440-90EA7D98CC09; ObjectType=5; Policies=System.Object[]; State=0}}
TotalEndpoints         : 0
Type                   : Overlay
Version                : 38654705669

> Get-NetAdapter
==>
PS C:\CalicoWindows\kubernetes> Get-NetAdapter

Name                      InterfaceDescription                    ifIndex Status       MacAddress             LinkSpeed
----                      --------------------                    ------- ------       ----------             ---------
vEthernet (Ethernet0)     Hyper-V Virtual Ethernet Adapter #2          22 Up           00-50-56-96-14-59         1 Gbps
vEthernet (9d940bc6dd7...                                              51 Up           0E-2A-C0-A8-40-04         1 Gbps
vEthernet (7c8fdd65cf3...                                              46 Up           0E-2A-C0-A8-40-03         1 Gbps
vEthernet (nat)           Hyper-V Virtual Ethernet Adapter             20 Up           00-15-5D-9A-45-A6        10 Gbps
vEthernet (1c8f240eca6...                                              56 Up           0E-2A-C0-A8-40-05         1 Gbps
Ethernet0                 Intel(R) 82574L Gigabit Network Conn...       4 Up           00-50-56-96-14-59         1 Gbps

**Comment by andyzheung** [comment]
> Index Status MacAddress LinkSpeed

but now I pod in windows can connect to each other, but windows and linux pod can't. like what i say above.@song-jiang

**Comment by song-jiang** [comment]
I would expect routes to Linux pods created in the `policy` field of Calico network

**Comment by andyzheung** [comment]
[log.zip](https://github.com/projectcalico/calico/files/10026711/log.zip)
@song-jiang

**Comment by andyzheung** [comment]
I add new windows-node to the kubernetes cluster:
I find two windows node can't ping each other..
![image](https://user-images.githubusercontent.com/22912347/202385229-63db7811-8d1d-4f39-86cc-605949950e51.png)

**Comment by song-jiang** [comment]
I've checked your log but not sure why you have `confd` service running. Have you set [config](https://github.com/projectcalico/calico/blob/master/node/windows-packaging/CalicoWindows/config.ps1#L16) here to be `BGP` at some stage?

**Comment by andyzheung** [comment]
> `onfd` s

1、maybe i install follow the instruction on calico website, i find the default mode is windows-bgp, but I have changed it.
![image](https://user-images.githubusercontent.com/22912347/203091530-6feb6b0f-0f01-41ae-be9e-f8d32757551a.png)

2、my k8s controller plane calico is ipipmode, and i changed it to vxlan, as i mentioned above.

**Comment by song-jiang** [comment]
Can you start with a new cluster with the correct configurations? Calico for Windows does not support changing network backends unfortunately.

**Comment by andyzheung** [comment]
> Can you start with a new cluster with the correct configurations? Calico for Windows does not support changing network backends unfortunately.
Oh, I will try to start a new cluster.
Now I just use the exist kubernetes cluster.. But if we can't changed config with the old cluster, the scene is limited，because we have existing k8s cluster.
@song-jiang

**Comment by andyzheung** [comment]
> Can you start with a new cluster with the correct configurations? Calico for Windows does not support changing network backends unfortunately.

I try to setup a new cluster use vxlan mode of calico it seem that win can connect to linux pod use this demo following:
https://projectcalico.docs.tigera.io/archive/v3.22/getting-started/windows-calico/demo
![image](https://user-images.githubusercontent.com/22912347/204085797-59489154-7f35-40db-b73e-7b6cfb59bda5.png)
![image](https://user-images.githubusercontent.com/22912347/204085820-5d771b19-a09e-4642-8dea-9a2bba97a7f7.png)

Thank you so much!!!@song-jiang 
But another question is how about the existing cluster that I use ipipmode? How to migration the existing cluster to  vxlan mode? I have a lot of app on the cluster..

**Comment by song-jiang** [comment]
Great to know your cluster is up running. 
> how about the existing cluster that I use ipipmode
If you used tigera operator to install calico, you should be able to update the [installation](https://projectcalico.docs.tigera.io/reference/installation/api) to vxlan and Calico should start a rolling upgrade. @lwr20 Could you help to confirm that is the correct way to do it?

**Comment by lwr20** [comment]
I think with recent versions of Calico, you can simply update the `ippool` (directly, NOT in the `installation`*) to use vxlan instead of IP in IP.  @coutinhop implemented that.
https://projectcalico.docs.tigera.io/networking/vxlan-ipip  

*The ippool in the Installation simply tells calico what to create _if there isn't already an ippool_ - and there will be in your cluster.

**Comment by andyzheung** [comment]
> I think with recent versions of Calico, you can simply update the `ippool` (directly, NOT in the `installation`*) to use vxlan instead of IP in IP. @coutinhop implemented that. https://projectcalico.docs.tigera.io/networking/vxlan-ipip
> 
> *The ippool in the Installation simply tells calico what to create _if there isn't already an ippool_ - and there will be in your cluster.

I use the manifest to install it ,but calico version is: 3.22 , kubernetes version is 1.21.
ttps://docs.projectcalico.org/manifests/calico.yaml
I try to modify like this, but it seems have some problem like this issue above:
https://github.com/projectcalico/calico/issues/6987#issuecomment-1313994613

**Comment by coutinhop** [comment]
@andyzheung what exactly is the issue you have when you change the encapsulation in the IP pool from IPIP to VXLAN in the running cluster?

**Comment by andyzheung** [comment]
> @andyzheung what exactly is the issue you have when you change the encapsulation in the IP pool from IPIP to VXLAN in the running cluster?
-----
II try to modify like this, but it seems have some problem like this issue above:
https://github.com/projectcalico/calico/issues/6987#issuecomment-1313994613
https://github.com/projectcalico/calico/issues/6987#issuecomment-1314868078
----
But @song-jiang  said:
https://github.com/projectcalico/calico/issues/6996#issuecomment-1317881919
https://github.com/projectcalico/calico/issues/6996#issuecomment-1321244344

So I think that my modify way is not right? so my windows node can't connect to others?
@coutinhop

**Comment by andyzheung** [comment]
If I can delete the calico manifest on existing cluster(I have many pod on it) like:
kubectl delete -f manifest.yaml?
And them use tiger operator to setup new calico? Can it solve this problem?
It seems that will cause cluster network stop for a few minites? Any other problem?

**Comment by lwr20** [comment]
> If I can delete the calico manifest on existing cluster(I have many pod on it) 

If you do that, you will need to delete and recreate all your pods, because deleting the CRDs will delete all records of the pods (e.g. their allocated IPs).  I do NOT recommend it.

**Comment by coutinhop** [comment]
@andyzheung did you manage to fix this by recreating the cluster? Will close the issue, feel free to reopen with more info if there's still anything else left to do
