### ISSUE TITLE
csi-node-driver ImagePullBackOff for csi-node-driver in the **Tigera operator** and Connection to the datastore is unauthorized error=connection is unauthorized: Unauthorized

### ISSUE THREAD

**Issue by ahmad-sharif** [projectcalico/calico#7012]
csi-node-driver ImagePullBackOff and
Connection to the datastore is unauthorized error=connection is unauthorized: Unauthorized

## Expected Behavior
Should be able to pull images from a private repository 

## Current Behavior
ImagePullSecret is missing for csi-node-driver  in the **Tigera operator** 

## Possible Solution
Add ImagePullSecret for csi-node-driver  in the **Tigera operator** 

## Steps to Reproduce (for bugs)
1. helm upgrade --install tigera-calico projectcalico/tigera-operator --version v3.24.5 --namespace calico-system -f b.yaml
2. where b.yaml contains `
installation:
  registry: registry \n
imagePullSecrets:
  docker-reg-secret: ' '`

## Context
We can not use new version of Calico if it is not fixed 

## Your Environment
* Calico version: v3.24.5
* Orchestrator version (e.g. kubernetes, mesos, rkt): 1.22 eks

**Comment by coutinhop** [comment]
Closing this as inactive (might have been fixed?). Feel free to reopen if you're still affected by it (and please provide more info if possible).
