### ISSUE TITLE
Calico performance. Many pods on one node

### ISSUE THREAD

**Issue by dmitrytretyakov** [projectcalico/calico#7029]
Hi all,

I’m trying to replace small VM workers (8 CPUs, 48G mem),  with large HW workers (88 CPUs, 768G mem) and run as many as possible pods on them.

Currently, I’m stuck on Calico:
1. Much bigger CPU consumption than just replaced_vm_count * (calico_vm_node_cpu_consumtion + 10-15%). Actually, it’s more than 2x for the same workload but balanced on a few VM nodes. The biggest consumer is Felix’s process. Attached profiles from HW nodes (running about 450 pods).
[felix-cpu-2022-11-15-1.pprof.tar.gz](https://github.com/projectcalico/calico/files/10102113/felix-cpu-2022-11-15-1.pprof.tar.gz)
[felix-cpu-2022-11-15-2.pprof.tar.gz](https://github.com/projectcalico/calico/files/10102114/felix-cpu-2022-11-15-2.pprof.tar.gz)

2. Issues with pods network interconnection on one node from time to time

Could you please advise what I can do to improve Calico performance in this case?

## Your Environment

* Calico version - 3.24.5, first it was 3.19.2 
* Orchestrator version (e.g. kubernetes, mesos, rkt): k8s 1.21.5
* Operating System and version: Ubuntu 20.04.5, 5.4.0-131-generic kernel

**Comment by mgleung** [comment]
Hey @dmitrytretyakov , is it possible to get the calico node logs your calico node pods? I think the only thing we can really do is check to see if there is anything strange happening that might affect your performance.

That being said, how many extra pods are you running on your larger instances? I would expect the CPU consumption to increase if you have a lot more pods so I'm wondering what scale of pods we are looking at here.

**Comment by dmitrytretyakov** [comment]
Hi @mgleung, sorry for the delay.
We were able to run about 740 pods on one node. Our target is 1500.
Attaching logs and profile from node at the static moment (without any deploying or removing pods) of running 740 pods:
[calico-node-logs-and-profile.tar.gz](https://github.com/projectcalico/calico/files/10142442/calico-node-logs-and-profile.tar.gz)

**Comment by dmitrytretyakov** [comment]
Maybe heapdump can shed some light on it:
```
(pprof) top10
Showing nodes accounting for 118.57MB, 77.09% of 153.81MB total
Dropped 99 nodes (cum <= 0.77MB)
Showing top 10 nodes out of 110
      flat  flat%   sum%        cum   cum%
   36.52MB 23.74% 23.74%    38.02MB 24.72%  github.com/projectcalico/calico/libcalico-go/lib/backend/syncersv1/updateprocessors.convertWorkloadEndpointV2ToV1Value
   24.02MB 15.62% 39.36%    24.52MB 15.94%  runtime.allocm
       9MB  5.85% 45.21%        9MB  5.85%  reflect.cvtBytesString
    8.50MB  5.53% 50.74%     8.50MB  5.53%  encoding/json.(*decodeState).literalStore
    8.28MB  5.39% 56.12%    12.32MB  8.01%  github.com/projectcalico/calico/felix/labelindex.(*SelectorAndNamedPortIndex).UpdateEndpointOrSet
       8MB  5.20% 61.33%        8MB  5.20%  fmt.Sprintf
       8MB  5.20% 66.53%     9.50MB  6.18%  github.com/projectcalico/calico/libcalico-go/lib/backend/syncersv1/updateprocessors.convertWorkloadEndpointV2ToV1Key
    6.71MB  4.36% 70.89%     6.71MB  4.36%  github.com/vishvananda/netlink/nl.(*NetlinkSocket).Receive
       5MB  3.25% 74.14%    23.50MB 15.28%  github.com/projectcalico/calico/libcalico-go/lib/backend/etcdv3.convertListResponse
    4.54MB  2.95% 77.09%     4.54MB  2.95%  github.com/projectcalico/calico/libcalico-go/lib/set.Boxed[...].Add
    ```
[heap.tar.gz](https://github.com/projectcalico/calico/files/10155211/heap.tar.gz)

**Comment by fasaxc** [comment]
v3.25.1 has now shipped with the fix.
