### ISSUE TITLE
CRDs for tigera-operator are not updating with helm upgrade, Migration is not possible.

### ISSUE THREAD

**Issue by Shivam0609** [projectcalico/calico#7030]
Trying to disable default `csi-node-driver` daemonset created with calico helm chart installation, By setting `kubeletVolumePluginPath=None` with helm `--set` args

Ref:  https://github.com/projectcalico/calico/blob/v3.24.5/charts/tigera-operator/crds/operator.tigera.io_installations_crd.yaml#L4253

Running version v3.24.0 of calico & migrating to v3.24.5

## Expected Behavior

When upgrading calico chart from v3.24.0 to v3.24.5, Expecting with helm upgrade all CRD's and CR's should be updated to the newer version also the default Daemonset for `csi-node-driver` should not be present.

## Current Behavior

When upgrading calico chart from v3.24.0 to v3.24.5 default Daemonset for `csi-node-driver` is still present, After checking a little bit found that CRD's are not updated with field `kubeletVolumePluginPath`  and hence helm upgrade fails with below Error

```bash
Error: UPGRADE FAILED: error validating "": error validating data: ValidationError(Installation.spec): unknown field "kubeletVolumePluginPath" in io.tigera.operator.v1.Installation.spec
```

## Possible Solution

To get CRD's and CR's updated had to remove helm release and delete CRD's and then do fresh install which is not a migration scenario which is more like delete and create a new installtion for calico

## Steps to Reproduce (for bugs)

1. Install calico version v3.24.0 using calico chart
 ```bash
helm repo add projectcalico https://docs.projectcalico.org/charts
helm repo update
helm upgrade --install calico projectcalico/tigera-operator --namespace=tigera-operator --create-namespace --version v3.24.0 --set installation.registry=quay.io --set apiServer.enabled=false
```
2. Once calico is installed MIgrate to v3.24.5, with `--set installation.kubeletVolumePluginPath=None`
```bash
(root:~) helm upgrade --install calico projectcalico/tigera-operator --namespace=tigera-operator --create-namespace --version v3.24.5 --set installation.registry=quay.io --set apiServer.enabled=false --set installation.kubeletVolumePluginPath=None
Error: UPGRADE FAILED: error validating "": error validating data: ValidationError(Installation.spec): unknown field "kubeletVolumePluginPath" in io.tigera.operator.v1.Installation.spec
```
3. Upgrade fails since CRD's and CR's are not yet updated to support the `kubeletVolumePluginPath` field

## Context

When upgrading calico chart from v3.24.0 to v3.24.5 default Daemonset for `csi-node-driver` is still present, After checking a little bit found that CRD's are not updated with field `kubeletVolumePluginPath`  and hence helm upgrade fails with below Error

```bash
Error: UPGRADE FAILED: error validating "": error validating data: ValidationError(Installation.spec): unknown field "kubeletVolumePluginPath" in io.tigera.operator.v1.Installation.spec
```

## Your Environment

* Calico version : v3.24.0 upgrading to v3.24.5
* Orchestrator version (e.g. kubernetes, mesos, rkt): k8s version 1.23
* Operating System and version: amazon-linux2 ami
* Link to your project (optional):

**Comment by aquam8** [comment]
Related to https://github.com/tigera/operator/issues/2249 I would say, I have the same problem

**Comment by caseydavenport** [comment]
yeah we 100% need to update our upgrade documentation to handle this ASAP

**Comment by Chili-Man** [comment]
@Shivam0609 I've been able to successfully do upgrades through helm  by splitting it into three helm charts: 

1. First have a crds only helm chart for calico, `calico-crds`. We basically copy and paste the existing calico helm chart's crds into the templates directory of `calico-crds` which allows upgrading of the crds through the helm chart. 
2. Next, we install the provided calico helm chart with the `--skip-crds` flag. 
3. Finally, we have a third helm chart for deploying and instances of the crds, called `calico-policies`. 

This has allowed us to do smooth upgrades with out issues so far and have it successfully deployed through flux with the helmrelease

**Comment by ArchiFleKs** [comment]
@Chili-Man +1 for the dedicated charts (I know istio did that at some point), the other solution would be maintaining a docs saying when there are CRDs upgrade to apply and publish the CRDs ready to be applied on Github. I know [kube-prometheus-stack] does this [here](https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack#from-40x-to-41x)

This makes it more easier for people to follow the CRDs release, and also to manage it independently, for example with TF like [here](https://github.com/particuleio/terraform-kubernetes-addons/blob/main/kube-prometheus-crd.tf)

**Comment by aquam8** [comment]
Thank you both @Chili-Man and @ArchiFleKs for your contributions, 2 valid solutions that would definitely help going forward.
Simplest would be the second solution, since people can still continue to use the current helm-chart with CRD.
But users concerned about upgradability would use `--skip-crds` and load the CRDs by hand or automation (terraform). They just need to be properly versioned so we can reference the YAML of the CRDS by code as suggested.

**Comment by ArchiFleKs** [comment]
@aquam8 is there a place where we can find the versionned CRDs right now ? outside of the packaged helm charts

**Comment by caseydavenport** [comment]
@ArchiFleKs you can find them here for now: https://projectcalico.docs.tigera.io/manifests/operator-crds.yaml

Or https://projectcalico.docs.tigera.io/archive/v3.24/manifests/operator-crds.yaml 

Or for recent versions, on GH: https://raw.githubusercontent.com/projectcalico/calico/v3.25.0/manifests/operator-crds.yaml

**Comment by caseydavenport** [comment]
Latest upgrade instructions properly explain to upgrade the CRDs manually https://docs.tigera.io/calico/latest/operations/upgrading/kubernetes-upgrade#all-other-upgrades
