### ISSUE TITLE
Responses from ServiceIP using BPF VXLAN tunnel are not delivered due to udp cksum error in encapsulated packet

### ISSUE THREAD

**Issue by Garagoth** [projectcalico/calico#7040]
When connecting from outside of cluster to Service IP BPF program correctly produces VXLAN packet, with both udp frames (outer and inner) having  udp checksums ok. Packet is received on node with target pod, decapsulated, delivered to pod, pod response received and encapsulated, resulting VXLAN packet has outer (first) udp header checksum sum ok, but inner one (received from pod and being encapsulated) has udp cksum error.

## Expected Behavior
Response packet delivered via vxlan, decapsulated and delivered to client.

## Current Behavior
Response packet is dropped by vmware vswitch (probably) - it leaves VM, but never leaves ESXi host.

## Possible Solution
Disabling offloading on **ens** interface causes encapsulated packet to have proper udp checksum and is delivered properly.
`ethtool -K ens192 tx-checksum-ip-generic off`
ens192 is my main (and only) interface that handles all outgoing and incoming traffic to node.
Disabling offload on **cali*** interfaces does not have any effect.
Other packets (that is, not vxlan response from bpf nat+tunnel) all seem to have proper cksums, no matter what are offload settings on ens interface, and are delivered just fine.

However, turning off offload completely, even for packets that seem to work just fine, feels wrong...

## Steps to Reproduce (for bugs)
1. Install kubernetes cluster, skip kube-proxy
2. Install calico using tigera-operator
3. Turn on eBPF
4. Ask CoreDNS from outside of cluster using service ip for anything, but be careful not to ask node that actually has CoreDNS (no vxlan in that case).
5. Never get a response. (asking directly using PodIP works just fine at the same time)
6. Turn off offloading on ensX interface on node where CoreDNS is running
7. Start getting responses!

## Context
node-A (one that got packet from my dig query, forwards it using vxlan tunnel to node-B where coredns is running in a pod):
```
[node-A]$ tcpdump -vvvvvv -nl -i ens192 port 4789
tcpdump: listening on ens192, link-type EN10MB (Ethernet), snapshot length 262144 bytes
00:01:00.856808 IP (tos 0x0, ttl 60, id 31653, offset 0, flags [none], proto UDP (17), length 129)
    10.12.4.11.4789 > 10.12.10.75.4789: [no cksum] VXLAN, flags [I] (0x08), vni 13242816
IP (tos 0x0, ttl 60, id 31653, offset 0, flags [none], proto UDP (17), length 79)
    10.7.208.109.33347 > 172.19.0.10.53: [udp sum ok] 16677+ [1au] A? google.com. ar: . OPT UDPsize=1232 [COOKIE c6ceb8ab34f26836] (51)
```
No response arrives.
node-B (coredns runs here. Response is sent, packet is visible on esxi virtual interface, never leaves vswitch and is not delivered anywhere. Looks like vmware inspects vxlan packets, maybe to check vxlan id?):
```
[node-B]$ tcpdump -vvvvv -nl -i ens192 port 4789
tcpdump: listening on ens192, link-type EN10MB (Ethernet), snapshot length 262144 bytes
00:01:00.857596 IP (tos 0x0, ttl 56, id 31653, offset 0, flags [none], proto UDP (17), length 129)
    10.12.4.11.4789 > 10.12.10.75.4789: [no cksum] VXLAN, flags [I] (0x08), vni 13242816
IP (tos 0x0, ttl 60, id 31653, offset 0, flags [none], proto UDP (17), length 79)
    10.7.208.109.33347 > 172.19.0.10.53: [udp sum ok] 16677+ [1au] A? google.com. ar: . OPT UDPsize=1232 [COOKIE c6ceb8ab34f26836] (51)
00:01:00.857799 IP (tos 0x0, ttl 64, id 50657, offset 0, flags [DF], proto UDP (17), length 155)
    10.12.10.75.4789 > 10.12.4.11.4789: [no cksum] VXLAN, flags [I] (0x08), vni 13242816
IP (tos 0x0, ttl 63, id 50657, offset 0, flags [DF], proto UDP (17), length 105)
    172.19.0.10.53 > 10.7.208.109.33347: [bad udp cksum 0x86f8 -> 0x0628!] 16677* q: A? google.com. 1/0/1 google.com. [10s] A 142.250.186.206 ar: . OPT UDPsize=1232 [COOKIE c6ceb8ab34f26836] (77)
```

## Your Environment
* Calico version: 3.24.5, operator-based, with **BGP** (for pod and service IPs) and **BPF**
* Orchestrator version: Kubernetes 1.25.3
* Operating System and version: Ubuntu 22.04.1, kernel 5.15.0-48-generic, running on VMWare.
* Link to your project (optional): n/a
* `ethtool -i ens192`:
```
driver: vmxnet3
version: 1.6.0.0-k-NAPI
firmware-version: 
expansion-rom-version: 
bus-info: 0000:0b:00.0
supports-statistics: yes
supports-test: no
supports-eeprom-access: no
supports-register-dump: yes
supports-priv-flags: no
```

Slack conversation for this issue: https://calicousers.slack.com/archives/CUKP5S64R/p1669742690097709?thread_ts=1669131160.110409&cid=CUKP5S64R

**Comment by Garagoth** [comment]
Just to let you know: setting `  featureDetectOverride: "ChecksumOffloadBroken=true"` does not fix this problem.

**Comment by lwr20** [comment]
Looks like @tomastigera has merged a fix.  I think we discussed in slack how you might get hold of a dev build to try it out.

**Comment by tomastigera** [comment]
Is this still an issue with new versions? Feel free to reopen if yes.
