### ISSUE TITLE
Host services exposed on ClusterIP VIPs

### ISSUE THREAD

**Issue by igcherkaev** [projectcalico/calico#7049]
## Expected Behavior

If there's a service on a host bound to 0.0.0.0 and some port, e.g. sshd bound to 0.0.0.0:22 listening for incoming connections, and there's a client connecting to any IP of the services CIDR advertised over BGP on port 22, such connection attempt must be blocked.

## Current Behavior

When ClusterIP (regular) services are advertised via BGP, any client outside the cluster can connect to services' IP on an arbitrary port and if host is running a service bound to 0.0.0.0 and that port, connection will be established.

Example:
```
$ calicoctl get bgpconfiguration default -o yaml
apiVersion: projectcalico.org/v3
kind: BGPConfiguration
metadata:
  creationTimestamp: "2022-08-22T18:14:24Z"
  name: default
  resourceVersion: "479077"
  uid: c329ba54-412e-4596-8992-3e1d4068d8a9
spec:
  asNumber: 64512
  logSeverityScreen: Info
  nodeToNodeMeshEnabled: false
  serviceClusterIPs:
  - cidr: 10.161.0.0/20
```
This CIDR is advertised over BGP, and it happens to be routed via a specific kubernetes node, in our case via rndkbm501. We take any IP from that CIDR regardless whether such ClusterIP service exists or not and connect to it:

```
$ telnet 10.161.0.100 22
Trying 10.161.0.100...
Connected to 10.161.0.100.
Escape character is '^]'.
SSH-2.0-OpenSSH_8.8

```
And we connect to the sshd process running on rndkbm501.

This can also be reproduced without advertising the services CIDR, too:
```
rndkbm501 ~ $ curl -v telnet://10.161.0.100:22 
*   Trying 10.161.0.100:22...
* Connected to 10.161.0.100 (10.161.0.100) port 22 (#0)
SSH-2.0-OpenSSH_8.8
^C
```

In this example there's no services with IP 10.161.0.100. But it doesn't matter. An IP of some existing service can be used to reproduce it.

## Possible Solution
This is similar to this issue: https://github.com/kubernetes/kubernetes/issues/72236

Calico could probably validate if the packet's dst IP address belongs to any existing services and validate if dst port is serviced. If not, drop such packets.

## Steps to Reproduce (for bugs)

1. Connect to any clusterIP service to a port of some process running on the host which is bound to 0.0.0.0:<port>

## Context

Security concerns.

## Your Environment

* Calico version
```
Client Version:    v3.24.5
Git commit:        f1a1611ac
Cluster Version:   v3.24.5
Cluster Type:      typha,kdd,k8s,bgp,rnd
```
* Orchestrator version (e.g. kubernetes, mesos, rkt): Upstream Kubernetes 1.22.14
* Operating System and version: `Linux rndkbm501 5.15.63-flatcar #1 SMP Mon Aug 29 18:27:27 -00 2022 x86_64 Intel(R) Xeon(R) CPU E5-2660 v2 @ 2.20GHz GenuineIntel GNU/Linux`

**Comment by tomastigera** [comment]
After some offline discussion it seems like the issue is `10.161.15.255/20` assigned to loopback device. That creates routes in the `local` table that route anything in that cidr to `lo` and thus if there is a process listening on any device, it will pick it up and reply with service IP as a source.

So far that seems to be a mis-config.

**Comment by tomastigera** [comment]
This is a repro of that case https://github.com/tomastigera/project-calico-calico/commit/a2e8686a01de8543c5c51902ecdfedaefa9e39c7

**Comment by igcherkaev** [comment]
Now after talking with @tomastigera and looking into all this, it appears to be a misconfiguration on my end... I'm closing this issue for now.

**Comment by igcherkaev** [comment]
Muchas gracias to @tomastigera
