### ISSUE TITLE
Missing toleration from 1.6 kubeadm calico manifest

### ISSUE THREAD

**Issue by lwr20** [projectcalico/calico#705]
This file:
http://docs.projectcalico.org/master/getting-started/kubernetes/installation/hosted/kubeadm/1.6/calico.yaml

seems to be missing this toleration:
```
      # Mark the pod as a critical add-on for rescheduling.
      - key: CriticalAddonsOnly
        operator: Exists
```

Without it, I was seeing that my cluster was only starting calico-node on the master...

**Comment by lwr20** [comment]
Passing to @fasaxc for review - because I don't know taints and tolerations very well and could be mistaken about this...

**Comment by fasaxc** [comment]
Blind leading the blind here but  the docs certainly say you should set both: https://kubernetes.io/docs/concepts/cluster-administration/guaranteed-scheduling-critical-addon-pods/

> Marking add-on as critical
> To be critical an add-on has to run in kube-system namespace (configurable via flag) and
>  - have the scheduler.alpha.kubernetes.io/critical-pod annotation set to empty string, and
>  - have the PodSpec’s tolerations field set to [{"key":"CriticalAddonsOnly", "operator":"Exists"}]
> The first one marks a pod a critical. The second one is required by Rescheduler algorithm.

**Comment by tmjd** [comment]
Just throwing in my 2cents here. But I wanted to point out that the 1.5 manifests have this in a manner except it existed as an annotation.  I agree with your assessments (for what its worth).

**Comment by fasaxc** [comment]
@tmjd Yes, I think the annotation form no longer works now it's a GA feature.

**Comment by djosborne** [comment]
Copying's @fasaxc 's comment, for the record (https://github.com/projectcalico/calico/pull/708#discussion_r113498604)

>Just to close the loop, there used to be two annotations, this one to mark our pod as a critical add-on and a second one for the old format of toleration. this one is still needed, but the toleration one has moved to the "real" toleration syntax.
