### ISSUE TITLE
How to alloc a new cluster ip that is  determined   like LRU in ippools  as far as possible for the newest pod

### ISSUE THREAD

**Issue by fengyeall111** [projectcalico/calico#7059]
we have the service that is like  redis shards.Thank this:
two  service: shard-one-service ,shard-two-service
```
podname                               lisnten port      cluterIP
shard-one-service pod1        4000                172.100.100.244
shard-two-service pod1        4000                172.100.100.245
```

When shard-one-service pod1 destorys,its clusterIp is freed to ippool.
At the same time,shard-two-service pod2 t may retrieve the clusterIp of shard-one-service pod1.
This may cause problem.eg: using clusterIp to generate serial number,shard-two-service pod2  have the same serial number with 
shard-one-service pod1.In fact this is not allowed.
Is there any way for calico to alloc ip using LRU strategy.,not most recently used

**Comment by caseydavenport** [comment]
> When shard-one-service pod1 destorys,its clusterIp is freed to ippool.

Service Cluster IPs aren't managed by Calico. If this is a problem with service IP allocation, then it's unlikely to be related to Calico.

> Is there any way for calico to alloc ip using LRU strategy.,not most recently used

For pod IPs, Calico allocates them based on the block assigned to the node in a least-recently-used fashion. This is already the case.

Can you please use the issue template when raising issues? We're not able to support you unless you provide the information we ask for in the template.
