### ISSUE TITLE
error converting YAML to JSON: hosted/kubernetes-datastore/1.6/calico.yaml

### ISSUE THREAD

**Issue by frnkdny** [projectcalico/calico#707]
This manifest is failing to fully be applied:  
http://docs.projectcalico.org/master/getting-started/kubernetes/installation/hosted/kubernetes-datastore/1.6/calico.yaml

kubetest-master:~$ kubectl apply -f http://docs.projectcalico.org/master/getting-started/kubernetes/installation/hosted/kubernetes-datastore/1.6/calico.yaml
configmap "calico-config" created
error: error converting YAML to JSON: yaml: line 34: did not find expected '-' indicator

**Comment by gunjan5** [comment]
Fixed in https://github.com/projectcalico/calico/pull/711
