### ISSUE TITLE
Profile resource doc really needs to state defaults

### ISSUE THREAD

**Issue by lwr20** [projectcalico/calico#709]
This doc:
http://docs.projectcalico.org/v2.1/reference/calicoctl/resources/profile

...has a column for defaults, but no actual values.  It should at least say that the default for an empty profile is allow-all.

**Comment by caseydavenport** [comment]
Especially as of this PR: https://github.com/projectcalico/calico/pull/2366

I don't think there's anything to do here - none of the fields actually have defaults, and most of them are deprecated.
