### ISSUE TITLE
tls: server chose an unconfigured cipher suite

### ISSUE THREAD

**Issue by ryanlyy** [projectcalico/calico#7097]
Hi All,

I am installing kubernetes 1.26 with calico v3.24.5. kubernetes and calico can be installed successfully but kubernetes DNS and calico controller failed to be created the error is:

```
Warning FailedCreatePodSandBox 6s kubelet Failed to create pod sandbox: rpc error: code = Unknown desc = failed to create pod network sandbox k8s_coredns-787d4945fb-kvmsm_kube-system_b21eddb2-d4e6-4049-9d9e-c4774d23fc3e_0(54a342475b83c356e71c0ebdf228d8a3b9e5c6839b0bd23e89dad598eade5d45): error adding pod kube-system_coredns-787d4945fb-kvmsm to CNI network "k8s-pod-network": plugin type="calico" failed (add): error getting ClusterInformation: Get "[https://10.96.0.1:443/apis/crd.projectcalico.org/v1/clusterinformations/default](https://10.96.0.1/apis/crd.projectcalico.org/v1/clusterinformations/default)": tls: server chose an unconfigured cipher suite
```

what is wrong with it?

Thanks for your support

**Comment by caseydavenport** [comment]
Sounds like the Calico CNI plugin is failing to establish a connection with the Kubernetes API server due to a cipher suite negotiation failure. 

This may be related to the generation of your Kubernetes API server certificate, if it's using a non-FIPS-compatible cipher suite.

**Comment by ryanlyy** [comment]
Thanks a lot for your support. how can we address it? if non-FIPS-compatiable cipher suite is not allowed by Calico. is there any description on it or how to fix it in somewhere?

Thanks

**Comment by ryanlyy** [comment]
looking at the kube-apiserver on tls-cipher-suites, I did not add this parmater in kube-apiserver manifest, then "the default Go cipher suites will be used", calico will fail if using "the default Go cipher suites will be used"? which one shall be used for calico?
Thanks,

<html><body>


--tls-cipher-suites strings
--
  | Comma-separated list of cipher suites for the server. If omitted, the default Go cipher suites will be used.Preferred  values: TLS_AES_128_GCM_SHA256, TLS_AES_256_GCM_SHA384,  TLS_CHACHA20_POLY1305_SHA256, TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA,  TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,  TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA,  TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,  TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305,  TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256,  TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA,  TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,  TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA,  TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,  TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305,  TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256,  TLS_RSA_WITH_AES_128_CBC_SHA, TLS_RSA_WITH_AES_128_GCM_SHA256,  TLS_RSA_WITH_AES_256_CBC_SHA, TLS_RSA_WITH_AES_256_GCM_SHA384.Insecure  values: TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256,  TLS_ECDHE_ECDSA_WITH_RC4_128_SHA, TLS_ECDHE_RSA_WITH_3DES_EDE_CBC_SHA,  TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256, TLS_ECDHE_RSA_WITH_RC4_128_SHA,  TLS_RSA_WITH_3DES_EDE_CBC_SHA, TLS_RSA_WITH_AES_128_CBC_SHA256,  TLS_RSA_WITH_RC4_128_SHA.


</body>
</html>

**Comment by ryanlyy** [comment]
I configured kube-apiserver with --tls-cipher-suites=TLS_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256, calico still fails with same error.

**Comment by 5StevenWu** [comment]
the  same problems      
coredns doesn't  work   ;  healthcheck  fail

OS UBUNTU2204
K8S V1.26
CALICO  V3.24.5

**Comment by durd07** [comment]
Hi Ryan,

I faced the same problem with the same OS and version with @5StevenWu.
What is your OS version? Is it an issue specific to Ubuntu 22.04?

**Comment by 5StevenWu** [comment]
> Hi Ryan,
> 
> I faced the same problem with the same OS and version with @5StevenWu. What is your OS version? Is it an issue specific to Ubuntu 22.04?

没找到解决办法 我重新部署后正常了    kubeadm reset ;  kubeadm init ;  @durd07

**Comment by ryanlyy** [comment]
@5StevenWu still the following env when you redeploy: seems I tried several times with same version still same error.
OS UBUNTU2204
K8S V1.26
CALICO V3.24.5

**Comment by zzvara** [comment]
I have the same issue with K8S 1.25.6, Calico v3.24.5, and Ubuntu 22.04.2 installed by Kubespray.

**Comment by zzvara** [comment]
> I have the same issue with K8S 1.25.6, Calico v3.24.5, and Ubuntu 22.04.2 installed by Kubespray.

For me it was a proxy issue. I noticed that from the node where the Pod sandbox shall be started, the `telnet 10.96.0.1 6443` (or whatever API endpoint I had) was automatically sent to the proxy server.
