### ISSUE TITLE
What is meaning and significance of different dataplane message type

### ISSUE THREAD

**Issue by crujzo** [projectcalico/calico#7104]
Calico prometheus monitoring exposes a metrics "**felix_int_dataplane_messages**" which gives information about different message types like: 

**1. ActiveProfileRemove
2. ActiveProfileUpdate
3. ConfigUpdate
4. Encapsulation
5. HostMetadataUpdate
6. IPAMPoolUpdate
7. InSync
8. NamespaceUpdate
9. RouteRemove
10. RouteUpdate
11. ServiceAccountUpdate
12. ServiceRemove
13. ServiceUpdate"
14. VXLANTunnelEndpointUpdate
15. WorkloadEndpointRemove
16. WorkloadEndpointUpdate**

. can any one please describe what these message types means in detail or point me to  resource where i can study it

**Comment by caseydavenport** [comment]
These are messages that Calico sends internally between it's calculation logic and the dataplane programming component. 

They're defined here: https://github.com/projectcalico/calico/blob/master/felix/proto/felixbackend.proto
