### ISSUE TITLE
Calico in eBPF mode doesn't seem to honor terminationGracePeriodSeconds and blocks outbound traffic from pods being terminated

### ISSUE THREAD

**Issue by igcherkaev** [projectcalico/calico#7110]
## Expected Behavior
Once pod is being deleted and marked as being Terminated by Kubernetes, calico should still allow traffic (only for already established connections)  from the pod back to the client and vice versa, until it's gone for good.

## Current Behavior
Traffic from pods being terminated is dropped. While tcpdump'ing it, I noticed TCP retransmits on the cali interface and the client didn't receive anything. Connection was kept open even when the pod had been long gone.

## Possible Solution

Ideally, memorize the value of terminationGracePeriodSeconds set for the pod, once endpoint is removed, calculate the moment in time when it's safe to clean up and clean up after that moment is reached. Until it's not reached, keep connection entry/nat entry and all related policies in place.

## Steps to Reproduce (for bugs)

1. Deploy a pod
2. Make a long-running request to it
3. Delete the pod
4. Even though the app handles SIGTERM properly and attempts to complete the request, generated response never gets to the client.

I can upload my calico-test docker image to reproduce this, if need be.

## Context

To achieve zero downtime deployments it is required to allow instances of the app complete in-flight requests while a new version is being rolled out and old pods are gracefully terminated. We've been receiving complaints from clients during deployments and HPA scale down events that some of their requests time out.

## Your Environment

* Calico version: `3.24.5`
* Orchestrator version (e.g. kubernetes, mesos, rkt): `Vanilla Kubernetes 1.22.14`
* Operating System and version: `Linux rndkbw503 5.15.63-flatcar #1 SMP Mon Aug 29 18:27:27 -00 2022 x86_64 Intel(R) Xeon(R) CPU E5-2660 v2 @ 2.20GHz GenuineIntel GNU/Linux`

**Comment by caseydavenport** [comment]
@tomastigera want to look at this one? 

I wouldn't have thought we would need to do anything special to handle termination grace period properly, since we key off the deleted event and I wouldn't expect us to change our programming until we receive it. But perhaps BPF mode does something I'm not aware of?

Or maybe it's something in our eBPF kube-proxy implementation?

**Comment by igcherkaev** [comment]
@caseydavenport Me neither, but we kept receiving complaints from dev and devops folks that during rollouts and/or HPA scaling down events few requests were getting timed out here and there. I didn't think it was calico to blame, but had to develop a simple app that takes several seconds before responding back to regular http clients to simulate the issue. Turned out, as soon as my test request was in and I terminated the pod, the pod was still in the grace termination period and attempted to send a response back, but it could not, such traffic wasn't let go out. @tomastigera  confirmed that as well, I think. At least he said that as soon as endpoint is removed by Kubernetes, calico updates its eBPF programs accordingly and it may block traffic from pods being terminated.

**Comment by igcherkaev** [comment]
All in all, this is a big issue in my opinion as it doesn't really allow you having zero downtime deployments with calico+ebpf.

**Comment by igcherkaev** [comment]
While reproducing it with @StevenTigera the behavior stated in the issue is achieved only when talking to the pod via the service's IP. When/if client talks to the pod directly, it works as expected/desired.

**Comment by tomastigera** [comment]
yes, we only remove the conntrack when a backend of a service disappears, we are too eager :sweat:

**Comment by igcherkaev** [comment]
New conditions: the client has to be outside the kubernetes cluster. Meaning that the whole setup must have BGP enabled allowing clients talk directly to the services in Kubernetes. If clients sit on any of the worker nodes, or kubectl port forward is used (essentially making the client "sit" on the kube-apiserver node), the problem described in this issue doesn't show itself. 

@StevenTigera tried to reproduce this issue by running curl from worker nodes and via kubectl port forward but could not. So did I and saw exactly same results.

**Comment by tomastigera** [comment]
It is enough to access say a nodeport or a load balancer from outside. Or turn of ctlb, then it would also apply to all traffic within the cluster. It does not apply to cluster local traffic when ctlb is on.

**Comment by igcherkaev** [comment]
It almost feels like @tomastigera knows what the issue is, but doesn't tell @StevenTigera so he can figure it out himself :)

**Comment by tomastigera** [comment]
TZ issue ... we discussed that just before you posted :-D

**Comment by igcherkaev** [comment]
Thank you!
