### ISSUE TITLE
after uninstall calico node alreday trigger condition by calico

### ISSUE THREAD

**Issue by chestarss** [projectcalico/calico#7112]
kubectl get node k8s-node-5
  conditions:
  - lastHeartbeatTime: "2022-12-20T02:19:40Z"
    lastTransitionTime: "2022-12-20T02:19:40Z"
    message: Calico is shutting down on this node
    reason: CalicoIsDown
    status: "True"

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Calico version
* Orchestrator version (e.g. kubernetes, mesos, rkt):
* Operating System and version:
* Link to your project (optional):

**Comment by caseydavenport** [comment]
I'm sorry, but we can't action this issue without more information. Please fill out the entire issue template.

**Comment by chestarss** [comment]
use kubectl patch remove this condition. it is works
