### ISSUE TITLE
How do I add an external server to calico？

### ISSUE THREAD

**Issue by K-free-N** [projectcalico/calico#7115]
How do I add an external server to calico？

My K8s is built on the Intranet, but I have a public network Nat mapping to the K8s entry. I want external servers to access this cluster, but calico-node init always accesses my kubernetes endpoint(which is an Intranet IP). I tried to modify the daemonset of calico-node to add the environment variables "KUBERNETES_SERVICE_HOST" and "KUBERNETES_SERVICE_PORT", but to no avail, calico configmap also tries to define "__KUBERNETES_SERVICE_HOST__ "and "__KUBERNETES_SERVICE_PORT__", but it doesn't work. I hope you can help to solve it. Thank you very much!

**Comment by lwr20** [comment]
You want to install Calico on a node that is not part of a k8s cluster?  
See: https://projectcalico.docs.tigera.io/getting-started/bare-metal/about

**Comment by K-free-N** [comment]
Thank you for your answer. The problem has been solved.
