### ISSUE TITLE
worker node calico  pod  can't  run properly 

### ISSUE THREAD

**Issue by helloxjade** [projectcalico/calico#7122]
kubectl logs calico-node-ks47p -n kube-system  -c install-cni

`2022-12-22 10:29:47.681 [ERROR][1] cni-installer/<nil> <nil>: Unable to create token for CNI kubeconfig error=Post "https://10.96.0.1:443/api/v1/namespaces/kube-system/serviceaccounts/calico-node/token": dial tcp 10.96.0.1:443: i/o timeout
2022-12-22 10:29:47.681 [FATAL][1] cni-installer/<nil> <nil>: Unable to create token for CNI kubeconfig error=Post "https://10.96.0.1:443/api/v1/namespaces/kube-system/serviceaccounts/calico-node/token": dial tcp 10.96.0.1:443: i/o timeout`

how can i  sovle this problem ！

**Comment by caseydavenport** [comment]
@helloxjade please fill out the full issue template when creating an issue - it's difficult for us to help without all of the information that it requests. Specifically information about the versions of software that you're using, and where your cluster is running.

**Comment by song-jiang** [comment]
@helloxjade I'm closing this issue. Feel free to work it again with the correct format.
