### ISSUE TITLE
CIDRNotAvailable Using Calico

### ISSUE THREAD

**Issue by antikilahdjs** [projectcalico/calico#7134]
## Expected Behavior

Hello Team, I am sorry but I am facing many errors as message "CIDRNotAvailable". I the config file to create a cluster using KK as used the kubePodsCIDR: 10.233.64.0/18 and kubeServiceCIDR: 10.233.0.0/18 as default but my network CIDR is
172.30.0.0/23. In the line "nodeCidrMaskSize" I am tried use /23 and /21 /18 but I got the same error about CIDRNotAvailable and I just wondering if someone help me to understand what am not doing correctly or If is a bug .

## Current Behavior

This is my configuration for Calico Node

network:
    plugin: calico
    calico:
      ipipMode: Never
      vxlanMode: Never
      vethMTU: 0
    kubePodsCIDR: 10.233.64.0/18
    kubeServiceCIDR: 10.233.0.0/18

## Steps to Reproduce (for bugs)

1. Just install Calico using Helm or YAML Templates

## Context

The Logs

100s        Normal    CIDRNotAvailable          node/gpu01                                                                Node gpu01 status is now: CIDRNotAvailable
9m43s       Normal    Synced                    clusterrolebinding/gpushare-device-plugin                                 ClusterRoleBinding synced successfully
9m43s       Normal    Synced                    clusterrolebinding/gpushare-schd-extender                                 ClusterRoleBinding synced successfully
9m43s       Normal    Synced                    clusterrolebinding/grafana-monitoring-kubeone-clusterrolebinding          ClusterRoleBinding synced successfully
9m43s       Normal    Synced                    clusterrolebinding/ingress-nginx                                          ClusterRoleBinding synced successfully
9m43s       Normal    Synced                    clusterrolebinding/installer-editor                                       ClusterRoleBinding synced successfully
9m43s       Normal    Synced                    clusterrolebinding/installer                                              ClusterRoleBinding synced successfully
9m43s       Normal    Synced                    clusterrolebinding/k8s-event-logger                                       ClusterRoleBinding synced successfully
9m43s       Normal    Synced                    clusterrolebinding/ks-devops                                              ClusterRoleBinding synced successfully
9m43s       Normal    Synced                    clusterrolebinding/ks-installer                                           ClusterRoleBinding synced successfully
9m43s       Normal    Synced                    clusterrolebinding/kubeadm:get-nodes                                      ClusterRoleBinding synced successfully
9m43s       Normal    Synced                    clusterrolebinding/kubeadm:kubelet-bootstrap                              ClusterRoleBinding synced successfully
9m43s       Normal    Synced                    clusterrolebinding/kubeadm:node-autoapprove-bootstrap                     ClusterRoleBinding synced successfully
9m43s       Normal    Synced                    clusterrolebinding/kubeadm:node-autoapprove-certificate-rotation          ClusterRoleBinding synced successfully
9m43s       Normal    Synced                    clusterrolebinding/kubeadm:node-proxier                                   ClusterRoleBinding synced successfully
9m43s       Normal    Synced                    clusterrolebinding/kubesphere-kube-state-metrics                          ClusterRoleBinding synced successfully
9m43s       Normal    Synced                    clusterrolebinding/kubesphere-node-exporter                               ClusterRoleBinding synced successfully
9m43s       Normal    Synced                    clusterrolebinding/kubesphere-prometheus-k8s                              ClusterRoleBinding synced successfully
9m43s       Normal    Synced                    clusterrolebinding/kubesphere-prometheus-operator                         ClusterRoleBinding synced successfully
9m43s       Normal    Synced                    clusterrolebinding/kubesphere                                             ClusterRoleBinding synced successfully
9m43s       Normal    Synced                    clusterrolebinding/kubewatch                                              ClusterRoleBinding synced successfully
9m43s       Normal    Synced                    globalrolebinding/leonardo.vera-workspace-devops                          GlobalRoleBinding synced successfully
9m43s       Normal    Synced                    clusterrolebinding/manager-rolebinding                                    ClusterRoleBinding synced successfully
9m43s       Normal    Synced                    clusterrolebinding/metallb-controller:controller                          ClusterRoleBinding synced successfully
9m43s       Normal    Synced                    clusterrolebinding/metallb-controller:speaker                             ClusterRoleBinding synced successfully
9m43s       Normal    Synced                    clusterrolebinding/metrics-server:system:auth-delegator                   ClusterRoleBinding synced successfully
9m43s       Normal    Synced                    clusterrolebinding/multus                                                 ClusterRoleBinding synced successfully
9m43s       Normal    Synced                    clusterrolebinding/notification-manager-controller-rolebinding            ClusterRoleBinding synced successfully
9m43s       Normal    Synced                    clusterrolebinding/notification-manager-proxy-rolebinding                 ClusterRoleBinding synced successfully
9m43s       Normal    Synced                    clusterrolebinding/notification-manager-tenant-sidecar-rolebinding        ClusterRoleBinding synced successfully
9m43s       Normal    Synced                    clusterrolebinding/openebs-maya-operator                                  ClusterRoleBinding synced successfully
9m43s       Normal    Synced                    clusterrolebinding/pl-cloud-connector-cluster-binding                     ClusterRoleBinding synced successfully
9m43s       Normal    Synced                    clusterrolebinding/pl-node-view-cluster-binding                           ClusterRoleBinding synced successfully
9m43s       Normal    Synced                    clusterrolebinding/pl-updater-cluster-binding                             ClusterRoleBinding synced successfully
9m43s       Normal    Synced                    clusterrolebinding/pl-vizier-metadata-cluster-binding                     ClusterRoleBinding synced successfully
9m43s       Normal    Synced                    clusterrolebinding/pl-vizier-metadata-node-view-cluster-binding           ClusterRoleBinding synced successfully
9m43s       Normal    Synced                    globalrolebinding/pre-registration                                        GlobalRoleBinding synced successfully
9m43s       Normal    Synced                    clusterrolebinding/proxy-rolebinding                                      ClusterRoleBinding synced successfully
41m         Normal    Synced                    workspacerole/role-template-create-devops                                 Synced successfully
41m         Normal    Synced                    workspacerole/role-template-create-projects                               Synced successfully
41m         Normal    Synced                    workspacerole/role-template-manage-app-repos                              Synced successfully
41m         Normal    Synced                    workspacerole/role-template-manage-app-templates                          Synced successfully
41m         Normal    Synced                    workspacerole/role-template-manage-devops                                 Synced successfully
41m         Normal    Synced                    workspacerole/role-template-manage-groups                                 Synced successfully
41m         Normal    Synced                    workspacerole/role-template-manage-members                                Synced successfully
41m         Normal    Synced                    workspacerole/role-template-manage-projects                               Synced successfully
41m         Normal    Synced                    workspacerole/role-template-manage-roles                                  Synced successfully
41m         Normal    Synced                    workspacerole/role-template-manage-workspace-settings                     Synced successfully
41m         Normal    Synced                    workspacerole/role-template-view-app-repos                                Synced successfully
41m         Normal    Synced                    workspacerole/role-template-view-app-templates                            Synced successfully
41m         Normal    Synced                    workspacerole/role-template-view-basic                                    Synced successfully
41m         Normal    Synced                    workspacerole/role-template-view-devops                                   Synced successfully
41m         Normal    Synced                    workspacerole/role-template-view-groups                                   Synced successfully
41m         Normal    Synced                    workspacerole/role-template-view-members                                  Synced successfully
41m         Normal    Synced                    workspacerole/role-template-view-projects                                 Synced successfully
41m         Normal    Synced                    workspacerole/role-template-view-roles                                    Synced successfully
41m         Normal    Synced                    workspacerole/role-template-view-workspace-settings                       Synced successfully
9m43s       Normal    Synced                    clusterrolebinding/rtspconfigupdater-role-binding                         ClusterRoleBinding synced successfully
9m43s       Normal    Synced                    clusterrolebinding/rtspserverlocator-role-binding                         ClusterRoleBinding synced successfully
34s         Normal    CIDRNotAvailable          node/xxx                                                                  Node xxx status is now: CIDRNotAvailable
4m47s       Normal    CIDRNotAvailable          node/xxx                                                                  Node xxx status is now: CIDRNotAvailable
4m16s       Normal    CIDRNotAvailable          node/xxx                                                                  Node xxx status is now: CIDRNotAvailable
5m1s        Normal    CIDRNotAvailable          node/xxx                                                                  Node xxx status is now: CIDRNotAvailable
38s         Normal    CIDRNotAvailable          node/xxx                                                                  Node xxx status is now: CIDRNotAvailable
25s         Normal    CIDRNotAvailable          node/xxx                                                                  Node xxx status is now: CIDRNotAvailable
22s         Normal    CIDRNotAvailable          node/xxx                                                                  Node xxx status is now: CIDRNotAvailable
5s          Normal    CIDRNotAvailable          node/xxx                                                                  Node xxx status is now: CIDRNotAvailable
2m12s       Normal    CIDRNotAvailable          node/xxx                                                                  Node xxx status is now: CIDRNotAvailable
2m1s        Normal    CIDRNotAvailable          node/xxx                                                                  Node xxx status is now: CIDRNotAvailable
4m56s       Normal    CIDRNotAvailable          node/xxx                                                                  Node xxx status is now: CIDRNotAvailable
21s         Normal    CIDRNotAvailable          node/xxx                                                                  Node xxx status is now: CIDRNotAvailable
30s         Normal    CIDRNotAvailable          node/xxx                                                                  Node xxx status is now: CIDRNotAvailable
2m43s       Normal    CIDRNotAvailable          node/xxx                                                                  Node xxx status is now: CIDRNotAvailable
4m52s       Normal    CIDRNotAvailable          node/xxx                                                                  Node xxx status is now: CIDRNotAvailable
4m42s       Normal    CIDRNotAvailable          node/xxx                                                                  Node xxx status is now: CIDRNotAvailable
9m43s       Normal    Synced                    clusterrolebinding/snapshot-controller-role                               ClusterRoleBinding synced successfully
41m         Normal    Synced                    workspacerole/system-workspace-admin                                      Synced successfully
41m         Normal    Synced                    workspacerole/system-workspace-regular                                    Synced successfully
41m         Normal    Synced                    workspacerole/system-workspace-self-provisioner                           Synced successfully
41m         Normal    Synced                    workspacerole/system-workspace-viewer                                     Synced successfully
9m43s       Normal    Synced                    clusterrolebinding/system:basic-user                                      ClusterRoleBinding synced successfully
9m43s       Normal    Synced                    clusterrolebinding/system:controller:attachdetach-controller              ClusterRoleBinding synced successfully
9m43s       Normal    Synced                    clusterrolebinding/system:controller:certificate-controller               ClusterRoleBinding synced successfully
9m43s       Normal    Synced                    clusterrolebinding/system:controller:clusterrole-aggregation-controller   ClusterRoleBinding synced successfully
9m43s       Normal    Synced                    clusterrolebinding/system:controller:cronjob-controller                   ClusterRoleBinding synced successfully
9m43s       Normal    Synced                    clusterrolebinding/system:controller:daemon-set-controller                ClusterRoleBinding synced successfully
9m43s       Normal    Synced                    clusterrolebinding/system:controller:deployment-controller                ClusterRoleBinding synced successfully
9m43s       Normal    Synced                    clusterrolebinding/system:controller:disruption-controller                ClusterRoleBinding synced successfully
9m43s       Normal    Synced                    clusterrolebinding/system:controller:endpoint-controller                  ClusterRoleBinding synced successfully
9m43s       Normal    Synced                    clusterrolebinding/system:controller:endpointslice-controller             ClusterRoleBinding synced successfully
9m43s       Normal    Synced                    clusterrolebinding/system:controller:endpointslicemirroring-controller    ClusterRoleBinding synced successfully
9m43s       Normal    Synced                    clusterrolebinding/system:controller:ephemeral-volume-controller          ClusterRoleBinding synced successfully
9m43s       Normal    Synced                    clusterrolebinding/system:controller:expand-controller                    ClusterRoleBinding synced successfully
9m43s       Normal    Synced                    clusterrolebinding/system:controller:generic-garbage-collector            ClusterRoleBinding synced successfully
9m43s       Normal    Synced                    clusterrolebinding/system:controller:horizontal-pod-autoscaler            ClusterRoleBinding synced successfully
9m43s       Normal    Synced                    clusterrolebinding/system:controller:job-controller                       ClusterRoleBinding synced successfully
9m43s       Normal    Synced                    clusterrolebinding/system:controller:namespace-controller                 ClusterRoleBinding synced successfully
9m43s       Normal    Synced                    clusterrolebinding/system:controller:node-controller                      ClusterRoleBinding synced successfully
9m43s       Normal    Synced                    clusterrolebinding/system:controller:persistent-volume-binder             ClusterRoleBinding synced successfully
9m43s       Normal    Synced                    clusterrolebinding/system:controller:pod-garbage-collector                ClusterRoleBinding synced successfully
9m43s       Normal    Synced                    clusterrolebinding/system:controller:pv-protection-controller             ClusterRoleBinding synced successfully
9m43s       Normal    Synced                    clusterrolebinding/system:controller:pvc-protection-controller            ClusterRoleBinding synced successfully
9m43s       Normal    Synced                    clusterrolebinding/system:controller:replicaset-controller                ClusterRoleBinding synced successfully
9m43s       Normal    Synced                    clusterrolebinding/system:controller:replication-controller               ClusterRoleBinding synced successfully
9m43s       Normal    Synced                    clusterrolebinding/system:controller:resourcequota-controller             ClusterRoleBinding synced successfully
9m43s       Normal    Synced                    clusterrolebinding/system:controller:root-ca-cert-publisher               ClusterRoleBinding synced successfully
9m43s       Normal    Synced                    clusterrolebinding/system:controller:route-controller                     ClusterRoleBinding synced successfully
9m43s       Normal    Synced                    clusterrolebinding/system:controller:service-account-controller           ClusterRoleBinding synced successfully
9m43s       Normal    Synced                    clusterrolebinding/system:controller:service-controller                   ClusterRoleBinding synced successfully
9m43s       Normal    Synced                    clusterrolebinding/system:controller:statefulset-controller               ClusterRoleBinding synced successfully
9m43s       Normal    Synced                    clusterrolebinding/system:controller:ttl-after-finished-controller        ClusterRoleBinding synced successfully
9m43s       Normal    Synced                    clusterrolebinding/system:controller:ttl-controller                       ClusterRoleBinding synced successfully
9m43s       Normal    Synced                    clusterrolebinding/system:coredns                                         ClusterRoleBinding synced successfully
9m43s       Normal    Synced                    clusterrolebinding/system:discovery                                       ClusterRoleBinding synced successfully
9m43s       Normal    Synced                    clusterrolebinding/system:kube-controller-manager                         ClusterRoleBinding synced successfully
9m43s       Normal    Synced                    clusterrolebinding/system:kube-dns                                        ClusterRoleBinding synced successfully
9m43s       Normal    Synced                    clusterrolebinding/system:kube-scheduler                                  ClusterRoleBinding synced successfully
9m43s       Normal    Synced                    clusterrolebinding/system:kubesphere-cluster-admin                        ClusterRoleBinding synced successfully
9m43s       Normal    Synced                    clusterrolebinding/system:metrics-server                                  ClusterRoleBinding synced successfully
9m43s       Normal    Synced                    clusterrolebinding/system:monitoring                                      ClusterRoleBinding synced successfully
9m43s       Normal    Synced                    clusterrolebinding/system:nginx-ingress-clusterrole-nisa-binding          ClusterRoleBinding synced successfully
9m43s       Normal    Synced                    clusterrolebinding/system:node-proxier                                    ClusterRoleBinding synced successfully
9m43s       Normal    Synced                    clusterrolebinding/system:node                                            ClusterRoleBinding synced successfully
9m43s       Normal    Synced                    clusterrolebinding/system:public-info-viewer                              ClusterRoleBinding synced successfully
9m43s       Normal    Synced                    clusterrolebinding/system:service-account-issuer-discovery                ClusterRoleBinding synced successfully
9m43s       Normal    Synced                    clusterrolebinding/system:volume-scheduler                                ClusterRoleBinding synced successfully
9m43s       Normal    Synced                    clusterrolebinding/tiller                                                 ClusterRoleBinding synced successfully
9m43s       Normal    Synced                    clusterrolebinding/wekafs-io-controller                                   ClusterRoleBinding synced successfully
9m43s       Normal    Synced                    clusterrolebinding/wekafs-io-node                                         ClusterRoleBinding synced successfully
9m43s       Normal    Synced                    clusterrolebinding/workflow-cluster-role                                  ClusterRoleBinding synced successfully
41m         Normal    Synced                    workspacerole/workspace-super-users                                       Synced successfully
41m         Normal    Synced                    workspacerole/workspace-server-dom-admin                                    Synced successfully
41m         Normal    Synced                    workspacerole/workspace-server-dom-devops-view                              Synced successfully
41m         Normal    Synced                    workspacerole/workspace-server-dom-regular                                  Synced successfully
41m         Normal    Synced                    workspacerole/workspace-server-dom-self-provisioner                         Synced successfully
41m         Normal    Synced                    workspacerole/workspace-server-dom-viewer                                   Synced successfully

## Your Environment

* Calico version v3.24.5
* Orchestrator version (e.g. kubernetes, mesos, rkt): Kubernetes
* Operating System and version: Ubuntu 20.04 LTS and RedHat 8.5
* Link to your project (optional):

**Comment by caseydavenport** [comment]
> 100s Normal CIDRNotAvailable node/gpu01 Node gpu01 status is now: CIDRNotAvailable

This log doesn't appear to be coming from Calico - looks like it's coming from your installer perhaps?
