### ISSUE TITLE
Can't reach windows pods from a master

### ISSUE THREAD

**Issue by orest-gulman** [projectcalico/calico#7139]
I have master mode on Debian and worker node on Windows Server 2022 version 21H2 (20348.1366), both are VM on Hyper-V (192.168.xx.xx/23 Network).
I've installed calico and configure BGP between master and worker node.

![image](https://user-images.githubusercontent.com/10500949/210407798-88d0a3de-3ebb-464a-94ec-6c5bcb555cf9.png)

## Expected Behavior
The master node should be able to reach pods IP (Windows).

## Current Behavior
In case of the Calico IP pool it is configured to 192.168.0.0/16 - the master node can ping windows pods but pod can NOT resolve external DNS except internal. 
![image](https://user-images.githubusercontent.com/10500949/210459901-c1763ba0-cabf-4645-88a3-84401b5c26e3.png)

In case of the Calico IP pool it is configured to 10.244.0.0/16, witch is my Kubernetes pods subnet - the master node can NOT ping windows pods but pod can resolve external DNS records using cluster DNS server (10.96.0.10).

## Configuration with 10.244.0.0/16 Calico IP pool.
master node:
![image](https://user-images.githubusercontent.com/10500949/210410944-d415ec9a-67c3-42c4-8ef6-57259a0419c0.png)
![image](https://user-images.githubusercontent.com/10500949/210411940-81c467bc-e085-44c0-a6e7-839f3763d8f1.png)worker node (Windows):
![image](https://user-images.githubusercontent.com/10500949/210409541-b7790fa8-9bc5-4912-90be-dd6927832506.png)

## Configuration with 192.168.0.0/16 Calico IP pool.
master node:
![image](https://user-images.githubusercontent.com/10500949/210411447-a7143f77-838b-48da-a895-e254a3c47b9a.png)
![image](https://user-images.githubusercontent.com/10500949/210411716-5b5e9e24-0619-434f-beb2-55bd0f18dc4d.png)
worker node (Windows):
![image](https://user-images.githubusercontent.com/10500949/210412124-8f55324f-2f45-48bb-8b3c-6faf8e2aa069.png)

**Comment by mgleung** [comment]
Hey @orest-gulman , we do not currently support Windows Server 2022 (though we are working on it). Maybe @song-jiang might be able to weigh in more though on if there is any other configuration options we could try in the meantime to debug this a little?

**Comment by orest-gulman** [comment]
Hi @mgleung 
calicoctl version
Client Version:    v3.19.1
Git commit:        6fc0db96
Cluster Version:   v3.24.5
Cluster Type:      k8s,bgp,kubeadm,kdd,win

**Comment by mgleung** [comment]
@orest-gulman , I'll need to get back to you on this, we're doing some validation on our end for Windows Server 2022 but it's possible that there might just need to be some config changes needed to make it work.

**Comment by doctorpangloss** [comment]
My on-premises microk8s-based calico cluster runs Windows 2022 workers correctly in v3.23.5 so that's maybe a red herring.

**Comment by coutinhop** [comment]
@orest-gulman how does iptables look in your nodes? Do you have any policies configured?

**Comment by orest-gulman** [comment]
> @orest-gulman how does iptables look in your nodes? Do you have any policies configured?

Hi @coutinhop, firewall it's inactive on Linux and on Windows.
Yesterday, I've install additional Windows Server 2022 worker node with latest version of Calico 3.25.0, and reset k8s cluster on Control-Plane, than I've applyed https://raw.githubusercontent.com/projectcalico/calico/v3.25.0/manifests/calico.yaml with few changes: `CALICO_IPV4POOL_CIDR`, _CALICO_IPV4POOL_IPIP: "Never"_, adding _IP_AUTODETECTION_METHOD value: "interface=eth0"_. Additionally I've applied _calicoctl ipam configure --strictaffinity=true_.
As a result BGP sessions are established, the pod 1 on Windows worker node 1 can reach pod 2 on Windows worker node 2, but they can't reach Kubernetes DNS service and also pods aren't reachable from control plane.

**Comment by doctorpangloss** [comment]
> > @orest-gulman how does iptables look in your nodes? Do you have any policies configured?
> 
> 
> 
> Hi @coutinhop, firewall it's inactive on Linux and on Windows.
> 
> Yesterday, I've install additional Windows Server 2022 worker node with latest version of Calico 3.25.0, and reset k8s cluster on Control-Plane, than I've applyed https://raw.githubusercontent.com/projectcalico/calico/v3.25.0/manifests/calico.yaml with few changes: `CALICO_IPV4POOL_CIDR`, `CALICO_IPV4POOL_IPIP: "Never"`, adding `IP_AUTODETECTION_METHOD: "interface=eth0"` . Additionally I've applied `calicoctl ipam configure --strictaffinity=true` .
> 
> As a result BGP sessions are established, the pod 1 on Windows worker node 1 can reach pod 2 on Windows worker node 2, but they can't reach Kubernetes DNS service and also pods aren't reachable from control plane.

You have to advertise service IPs in your BGP configuration, and you probably need to specify a policy. Later I will share manifests in a ticket that should be used in all bare metal BGP peered mixed platform Calico installations since 3.23.5.

**Comment by orest-gulman** [comment]
> > > @orest-gulman how does iptables look in your nodes? Do you have any policies configured?
> > 
> > 
> > Hi @coutinhop, firewall it's inactive on Linux and on Windows.
> > Yesterday, I've install additional Windows Server 2022 worker node with latest version of Calico 3.25.0, and reset k8s cluster on Control-Plane, than I've applyed https://raw.githubusercontent.com/projectcalico/calico/v3.25.0/manifests/calico.yaml with few changes: `CALICO_IPV4POOL_CIDR`, `CALICO_IPV4POOL_IPIP: "Never"`, adding `IP_AUTODETECTION_METHOD: "interface=eth0"` . Additionally I've applied `calicoctl ipam configure --strictaffinity=true` .
> > As a result BGP sessions are established, the pod 1 on Windows worker node 1 can reach pod 2 on Windows worker node 2, but they can't reach Kubernetes DNS service and also pods aren't reachable from control plane.
> 
> You have to advertise service IPs in your BGP configuration, and you probably need to specify a policy. Later I will share manifests in a ticket that should be used in all bare metal BGP peered mixed platform Calico installations since 3.23.5.

@doctorpangloss please share what you are saying
