### ISSUE TITLE
BGP doc wrongly pushes users to disable node-mesh

### ISSUE THREAD

**Issue by ozdanborne** [projectcalico/calico#714]
[Our docs state: "We generally expect the full node-to-node mesh to be disabled and explicit BGP peering to be configured.”](http://docs.projectcalico.org/master/usage/configuration/bgp#concepts)

This is [misleading users into disabling node-mesh](https://github.com/projectcalico/calico/issues/689#issuecomment-296439099).

We should clarify what a "small scale deployment" is, and find other ways to prevent users from misunderstanding.

**Comment by tmjd** [comment]
Agreed.  If you didn't create this from seeing #689 that is quite a coincidence.
That issue is someone doing exactly that when they did not need to.
