### ISSUE TITLE
Fix kubeadm section of KD hosted install

### ISSUE THREAD

**Issue by djosborne** [projectcalico/calico#716]
http://docs.projectcalico.org/master/getting-started/kubernetes/installation/hosted/kubernetes-datastore#example-kubeadm

This section seems half-baked. It should be cleaned up or removed.

**Comment by djosborne** [comment]
looking for input from @heschlie @caseydavenport

**Comment by caseydavenport** [comment]
yeah ideally this eventually all goes away when KDD has all the routing features, and we can just consolidate that doc with our kubeadm doc in its entirety.

As it is, it's bare-bones but it gives a starting place.

**Comment by djosborne** [comment]
Plan is to reword and move the kubeadm information up to section on `Calico policy with Calico networking (Beta)`, as that is really the only use case we want to support at this time.
