### ISSUE TITLE
round_trippers.go:574] Response Status: 503 Service Unavailable in 5008 milliseconds

### ISSUE THREAD

**Issue by vsudonet** [projectcalico/calico#7163]
## Expected Behavior

kubectl command return output quickly

## Current Behavior

kubectl command return output slowly because of 503 Service Unavailable when connecting to apis calico. Sometimes, it take me about 2 minutes to display output

## Steps to Reproduce (for bugs)

1. kubectl get pod --v=6
I0107 12:51:22.369045    7658 loader.go:372] Config loaded from file:  /Users/vsudo/.kube/config
I0107 12:51:22.406718    7658 round_trippers.go:553] GET https://10.12.30:6443/apis/metrics.k8s.io/v1beta1?timeout=32s 503 Service Unavailable in 33 milliseconds
I0107 12:51:22.448745    7658 request.go:1264] body was not decodable (unable to check for Status): couldn't get version/kind; json parse error: json: cannot unmarshal string into Go value of type struct { APIVersion string "json:\"apiVersion,omitempty\""; Kind string "json:\"kind,omitempty\"" }
I0107 12:51:22.448780    7658 cached_discovery.go:83] skipped caching discovery info due to the server is currently unable to handle the request
I0107 12:51:22.459790    7658 round_trippers.go:553] GET https://10.12.30.70:6443/apis/metrics.k8s.io/v1beta1?timeout=32s 503 Service Unavailable in 10 milliseconds
I0107 12:51:22.499745    7658 request.go:1264] body was not decodable (unable to check for Status): couldn't get version/kind; json parse error: json: cannot unmarshal string into Go value of type struct { APIVersion string "json:\"apiVersion,omitempty\""; Kind string "json:\"kind,omitempty\"" }
I0107 12:51:22.499762    7658 cached_discovery.go:83] skipped caching discovery info due to the server is currently unable to handle the request
I0107 12:51:22.500020    7658 shortcut.go:89] Error loading discovery information: unable to retrieve the complete list of server APIs: metrics.k8s.io/v1beta1: the server is currently unable to handle the request
I0107 12:51:22.506360    7658 round_trippers.go:553] GET https://10.12.30.70:6443/apis/metrics.k8s.io/v1beta1?timeout=32s 503 Service Unavailable in 6 milliseconds
I0107 12:51:22.548809    7658 request.go:1264] body was not decodable (unable to check for Status): couldn't get version/kind; json parse error: json: cannot unmarshal string into Go value of type struct { APIVersion string "json:\"apiVersion,omitempty\""; Kind string "json:\"kind,omitempty\"" }
I0107 12:51:22.548825    7658 cached_discovery.go:83] skipped caching discovery info due to the server is currently unable to handle the request
I0107 12:51:22.558010    7658 round_trippers.go:553] GET https://10.12.30.70:6443/api/v1/namespaces/default/pods?limit=500 200 OK in 7 milliseconds

## Your Environment

* Calico version: v3.24.3
* Orchestrator version (e.g. kubernetes, mesos, rkt): v1.25.3+k3s1
* Operating System and version: ubuntu 22
* Link to your project (optional):

**Comment by mgleung** [comment]
Hey @vsudonet , are there any other details about your cluster that might be relevant? I think that kubectl should be trying to communicate directly with the K8s API which I wouldn't expect to be changed by Calico pod networking. Have you tried running kubectl from one of the cluster nodes? Any issues with kube-proxy?

**Comment by caseydavenport** [comment]
Agreed, this doesn't look like it has anything to do with Calico. 

> I0107 12:51:22.506360 7658 round_trippers.go:553] GET https://10.12.30.70:6443/apis/metrics.k8s.io/v1beta1?timeout=32s 503 Service Unavailable in 6 milliseconds

Looks like the metrics endpoint isn't available.
