### ISSUE TITLE
externaltrafficpolicy=local on ClusterIP

### ISSUE THREAD

**Issue by oscni** [projectcalico/calico#7175]
Don't know if this is solvable in the calico project and if it does matter running eBPF or kube-proxy but here we go :)

When we announce Service IPs over BGP and setup a service with externaltrafficpolicy=local we basically get a /32 announced from each node that has that service. Traffic flows correct but the "problem" is that we need to use type NodePort (or LoadBalancer) instead of ClusterIP. So basically unnecessary config will be needed which confuses things when it feels like it doesn't have to. Is there a ways to get pass this and get calico/kubernetes to allow externaltrafficpolicy=local on a ClusterIP service?

**Comment by tomastigera** [comment]
Unfortunately that would not work now as we wanted to behave like k8s behave. However, that would not be a big code change to make it happen. Contributions are welcome! :)

**Comment by sfudeus** [comment]
Maybe `internalTrafficPolicy: Local` already fulfills what you want when only clusterIPs are involved, but currently mind https://github.com/projectcalico/calico/issues/8255.

**Comment by tomastigera** [comment]
@oscni does `internalTrafficPolicy: Local` work for you? Is part of 3.27 and current master. I am closing this issue, but feel free to reopen if need be.
