### ISSUE TITLE
Logging for felix unclear if vm has no security groups attached.

### ISSUE THREAD

**Issue by Brook-Roberts** [projectcalico/calico#718]
If a vm has no security groups associated with it, then felix does not add it and deletes the chain associated with it, giving the below log.  Rather than just saying the Endpoint is unready, it would be more helpful if it explained why it was unready i.e. no profile_ids / no security group ids are associated with this vm.

2015-07-08 16:04:39,468 [INFO][21479/227] calico.felix.endpoint 337: Endpoint<IPv6,id=EndpointId<e9798859-0afe-4cc6-a084-ad6d01f643c1>,iface=tape9798859-0a> became unready.

**Comment by fasaxc** [comment]
To be clear, the end result is that packets to the VM are dropped, which is exactly what we want.  The issue is that it's hard to tell why.

**Comment by fasaxc** [comment]
Fixed by #822
