### ISSUE TITLE
Same node no connectivity - no route to host (pod/host to pod) veth link not working?

### ISSUE THREAD

**Issue by jaimehrubiks** [projectcalico/calico#7180]
I don't think it's a bug, but maybe some incompatibility or something on my setup, I write this in case someone has any idea and could help me. I'm having an issue that happens only on some nodes. Specifically let's say that I have a 6-node cluster, freshly installed with KubeAdm, and two of the servers are experiencing this issue, let's call one of them "server A".

The issue is that I cannot communicate to the pods on this specific server. Not from other pod (on this node or other node), not from the node itself. I'm connecting directly to the pod's IP address. Seems like the veth pair is not working properly.

Example:
```
[i] ~ ❯ k get pods -o wide                                                                                                            
NAME                                      READY   STATUS    RESTARTS   AGE     IP              NODE
nginx-A                               1/1     Running   0          5h1m    10.234.164.11   A
nginx-B                            1/1     Running   0          14m     10.234.177.20   B 
ubuntu-A                          1/1     Running   0          3m53s   10.234.164.12   A 
ubuntu-B                          1/1     Running   0          3m53s   10.234.177.21   B
```
There is no way to connect to nginx-A, not from ubuntu-A nor ubuntuB, not from ssh://B itself. Message is: **curl: (7) Failed connect to 10.234.177.20:80; No route to host** when connecting from ssh://B

## Expected Behavior
I should be able to connect.

## Current Behavior
I don't have connectivity

## Steps to Reproduce
1. In my case, create a fresh cluster with kubeAdm (I use docker as CNI -tried both dockershim and cri-dockerd-)
  podSubnet: 10.234.128.0/18
  serviceSubnet: 20.234.192.0/18

2. Install calico with default configuration and these values:
```yaml
spec:
  # Configures Calico networking.
  calicoNetwork:
    # Note: The ipPools section cannot be modified post-install.
    ipPools:
    - blockSize: 26
      cidr: 10.234.128.0/18
      encapsulation: VXLANCrossSubnet
      natOutgoing: Enabled
      nodeSelector: all()
```

## Context
My servers are on-prem servers with a lot of interfaces and extra configuration, so something might be breaking the setup on this particular server.

I recently changed this, it did not work (I restarted nm and rebooted, and nmcli shows unmanaged on cali interfaces)
```
[root@A ~]# cat /etc/NetworkManager/conf.d/calico.conf
[keyfile]
unmanaged-devices=interface-name:cali*;interface-name:tunl*;interface-name:vxlan.calico;interface-name:vxlan-v6.calico;interface-name:wireguard.cali;interface-name:wg-v6.cali
```
Routes: (simplified)
```
[root@B ~]# route
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
default         gateway         0.0.0.0         UG    400    0        0 COMPSVCS
10.177.216.0    0.0.0.0         255.255.252.0   U     400    0        0 COMPSVCS (this is my main NIC, the ip of A and B are in this range)
10.234.177.0    B 255.255.255.192 UG    0      0        0 COMPSVCS
10.234.164.0    0.0.0.0         255.255.255.192 U     0      0        0 *
10.234.164.11   0.0.0.0         255.255.255.255 UH    0      0        0 calid4bdad70e06
10.234.164.12   0.0.0.0         255.255.255.255 UH    0      0        0 cali1e4d7ea28a1
link-local      0.0.0.0         255.255.0.0     U     1003   0        0 enp1s0f0
link-local      0.0.0.0         255.255.0.0     U     1004   0        0 enp1s0f1
172.17.0.0      0.0.0.0         255.255.0.0     U     0      0        0 docker0
192.168.201.0   0.0.0.0         255.255.255.0   U     0      0        0 enp1s0f0 (these are other NICs)
192.168.251.0   0.0.0.0         255.255.255.0   U     0      0        0 enp1s0f1
```

Also, the command calicoctl node status shows full connectivity. But I guess my issue is not with the BGP part of calico, is within the same node.

I cannot find anything weird in the iptables, although it's hard for me to read them. I did some "diff" on DROP iptables but couldn't find anything.

TCPdump on calid4bdad70e06 only shows ARP requests, no replies, and nothing else. Whereas in node B (ssh server to pod) it shows all the traffic properly.

SElinux is disabled

FirewallD is disabled.

kubectl port-forward nginx-A 8080:80 (and then curl localhost:8080 from my laptop) **does work**

docker run -p 8080:80 nginx works fine.

Tried using cri-dockerd instead of dockershim, same issue.

Tried using containerd instead of docker-ce, same issue

## Your Environment

* Calico version: 3.24.5
* Orchestrator version (e.g. kubernetes, mesos, rkt): 1.22
* Operating System and version: Centos 7
* Kernel: 3.10.0-1160.62.1.el7.x86_64
* iptables: v1.4.21

Thanks for your time.

**Comment by coutinhop** [comment]
@jaimehrubiks would you be able to provide some more information, such as the calico-node pods and calico-node logs (setting `logSeverityScreen` in FelixConfiguration to `debug`, if possible)?

**Comment by tomastigera** [comment]
Can reopen if more info provided.
