### ISSUE TITLE
Need more discussion of node->container / container->node comms in public cloud

### ISSUE THREAD

**Issue by robbrockbank** [projectcalico/calico#721]
Would be useful to have some diagrams explaining RPF / Policy issues when using IPIP.

Should cover the following:
-  Should use NAT-outgoing on pool
-  If sending from node to IPIP container, originating IP is NATed so that it appears from the tunl address - this ensures Reverse Path is same as outbound path.
-  You will need to include the tunl0 address in your policy decisions.  You can do this via a HostEndpoint (but see next bullet)
-  If using a HostEndpoint to configure policy for the tunl0, you must configure the tunnel IP on the endpoint - you cannot use the interface name as other hosts will not be able to see what the IP address is and include it in their policy calculations.  We may want to consider the IPIP IP allocation code scanning for HostEndpoints and updating any HostEndpoint that has an interface of tunl0.

**Comment by djosborne** [comment]
Possibly related, see new intro pages I've been working on: https://github.com/projectcalico/calico/compare/master...djosborne:seeing-is-believing
