### ISSUE TITLE
Log out more helpful error than "No more machines in cluster"

### ISSUE THREAD

**Issue by Lukasa** [projectcalico/calico#721]
Occasionally we get a very unhelpful error log, as @fasaxc describes in #458:

> For context: "No more machines in cluster" is a poor error message from python-etcd. It happens when python-etcd's retry code gets invoked, which tries the request against a different node in the cluster and then it runs out of nodes to try. The original cause of the retry (usually a connection failure or timeout) is the more interesting thing but that is lost because the retry code raises its own error.

@alexwlchan has also seen it:

> I have also been seeing the "No more machines in cluster" exception when the etcd disk is full. We can definitely provide a more useful message than that.
>
> (Scale testing, with a single node in the etcd cluster. I stuffed it full of endpoints until it ran out of space, and then this exception bubbled up.)

We should aim to log out a more useful error than this.

**Comment by eepyaich** [comment]
Can this issue be closed now, following #458?  @Lukasa @fasaxc?

**Comment by Lukasa** [comment]
No, this issue was opened as the more specific version of #458 in order to close #458. This still needs fixing.

**Comment by fasaxc** [comment]
I think this may have been addressed by python-etcd 0.4.1.  We should check that before investing more effort.

**Comment by fasaxc** [comment]
Could be resolved under move to etcd v3 API #952

**Comment by fasaxc** [comment]
I think we now get EtcdConnectionFailed exceptions with the original cause exception wrapped inside.
