### ISSUE TITLE
Pass Calico Version as processable variable in Install Manifests 

### ISSUE THREAD

**Issue by ozdanborne** [projectcalico/calico#722]
As per [ @fasaxc 's comment](https://github.com/projectcalico/calico/issues/676#issuecomment-293632855):
>If we can pass it in as an environment variable then calico/node versions and Felix could print it out too

**Comment by caseydavenport** [comment]
I think this falls into a larger discussion about releases and versioning.  I don't think passing an environment variable through is the right option here.
