### ISSUE TITLE
Quick question: How does Calico select NIC (Network Interface Card) to transfer POD-to-POD traffic

### ISSUE THREAD

**Issue by earthlovepython** [projectcalico/calico#7221]
Environment
=========================
Calico version:  3.25
K8S version: 1.24.8
Operating System and version: CentOS 7.9
K8S cluster: 3 nodes (1 controller node; 2 worker nodes). Each node has 3 NIC (NetworkInterfaceCard)  
K8S K8S podSubnet (defined in kubeadm-cluster-config-v1beta2.yml): 10.32.0.0/16

Hardware
=========================
3 NICs:  enp0s3 /  enp0s8 /  enp0s9 
enp0s3: access internet
enp0s8 (172.25.11.0/24 subnet) : K8s management traffic go this NetworkInterfaceCard
enp0s9 (172.26.11.0/24 subnet): reserved for NFS server traffic. 

How I installed Calico
=========================
Simply follow suite https://projectcalico.docs.tigera.io/getting-started/kubernetes/quickstart . I just did:
kubectl create -f https://raw.githubusercontent.com/projectcalico/calico/v3.25.0/manifests/tigera-operator.yaml
kubectl create -f https://raw.githubusercontent.com/projectcalico/calico/v3.25.0/manifests/custom-resources.yaml

Observed behavior on k8s controller node while run "ip route"
=========================
10.32.105.0/26 via 172.26.11.93 dev enp0s9 proto 80 onlink
10.32.144.64/26 via 172.26.11.92 dev enp0s9 proto 80 onlink
About output shows that POD traffic go thru enp0s9 (not enp0s8 which is used for K8S management traffic).
I also setup another different K8S cluster with 2 NICs. This time, Calico select "enp0s8" to transfer POD-to-POD traffic. 
I checked all Calico related operator configuration. No place to define which NIC used for POD-to-POD traffic
Can you please tell me how Calico select NIC to transfer POD-to-POD traffic? And how to configure it manually? 

Thanks

**Comment by Josh-Tigera** [comment]
The default method is to simply use the first-found interface. You can override this or change the setting by following the documentation here: https://unified-docs.tigera.io/calico/3.25/networking/ipam/ip-autodetection#change-the-autodetection-method

**Comment by earthlovepython** [comment]
Thanks. It works. 
This is great function. It can split "k8s management traffic" and "pod-to-pod traffic" in different NIC.
