### ISSUE TITLE
Separation of BGP peering per IPPool or subnet

### ISSUE THREAD

**Issue by sysarch-repo** [projectcalico/calico#7253]
Hello, this is a query rather than a bug report:

I have configured an IPPool, added the external IP address to the default BGP configuration:
```
  serviceExternalIPs:
  - cidr: 192.168.56.0/24
```

I have then created a BGPPeer and the route advertisement works as expected, e.g. on the BGP peer I see:
```
B>* 192.168.56.0/24 [20/0]   via 10.10.30.85, eth1, weight 1, 03:06:31
  *                          via 10.10.30.105, eth1, weight 1, 03:06:31
  *                          via 10.10.30.110, eth1, weight 1, 03:06:31
  *                          via 10.10.30.140, eth1, weight 1, 03:06:31
  *                          via 10.10.30.141, eth1, weight 1, 03:06:31
  *                          via 10.10.30.174, eth1, weight 1, 03:06:31
  *                          via 10.10.30.184, eth1, weight 1, 03:06:31
B>* 192.168.56.101/32 [20/0] via 10.10.30.85, eth1, weight 1, 02:35:25
  *                          via 10.10.30.110, eth1, weight 1, 02:35:25
```

Now I would like to add additional IPPools / externalIP subnets with separate BGP sessions a separate BGP peer for each of the subnets (network separation). Is this possible by Calico configuration?

The only thing I can think of is defining node specific BGP configs and BGP peers. To achieve redundancy (2 nodes min) and to advertize 3 different subnets I would need 2 x 3 = 6 K8S nodes. 

**Is there any better way to assign the subnets to be advertized to their individual BGP peers / sessions?**

Thanks a lot!

**Comment by caseydavenport** [comment]
Could you share a little bit more about what it is you're trying to achieve?

IPPools have a nodeSelector field which allows you to limit their use to particular nodes. It sounds like that might be what you are looking for?

ExternalIPs do not have that same behavior though, and for good reason - because they are  a services concept, which aren't bound to a single set of nodes.

**Comment by sysarch-repo** [comment]
@caseydavenport, thanks for your comments!
I am trying to set up BGP peering from a Kubernetes cluster via Calico to 3 different TOR BGP peers. Each BGP peer has a dedicated role: OAM, signaling, data replication. The associated K8S services on the K8S cluster utilize external IPs for OAM, signaling and data replication tasks. What I am trying to achieve - advertize the routes to the OAM external IP range to the OAM BGP peer only, the routes to the signaling IP address range to the signaling BGP peer only, and the routes to the data replication IP address range to the data replication BGP peer only. I do not know how to do it, i.e. I assume the routes to all 3 IP address ranges are advertized to all 3 BGP peers and this is not preferred. I see the following options.
- I use prefix advertisement and configure the BGP peers to consider only the routes with the community ID associated with the role of the BGP peer (PAM; signaling, data replication).
- set up a node-specific BGP peering, i.e. 2 nodes will advertize OAM routes to the OAM BGP peer, 2 nodes the routes to the signaling BGP peer and 2 nodes the data replication routes to the data replication BGP peer. As you are saying, this will limit the use of routes to particular nodes and utilize 6 nodes - not really optimal, so unless there is another way to split the BGP peering I will probably have to ask the BGP peer provider to configure community tags and filter the BGP routes.
I can paste a network diagram id needed. Thoughts?

**Comment by caseydavenport** [comment]
Sounds like it might be a case for BGP advertisement filtering, which is something we've had on the back of the roadmap for a while.

@coutinhop is this something that might be covered by the filtering work you're looking at?

**Comment by sysarch-repo** [comment]
@coutinhop 
Hi, I had a look at [Supported way to customize BGP export filters](https://github.com/projectcalico/calico/issues/1604) and while that ticket disables the route advertisement for an IPPool, I would need a whitelist for CIDRs to be advertised to a specific BGP peer. With this, each BGP peer could only receive the routes for the network it is dedicated to and the community-based filtering would no longer be needed at the BGP peer. Some operators do not like receiving advertisements for routes that are not associated with the network the BGP peer is associated with. Thoughts?

**Comment by coutinhop** [comment]
Hi @sysarch-repo and @caseydavenport! Yes, this use case sounds exactly it would be solved by the new BGPFilter added to BGPPeers in https://github.com/projectcalico/calico/pull/7271, which has merged to master and is slated to go into Calico v3.26.

**Comment by sysarch-repo** [comment]
@coutinhop , @caseydavenport thanks for your support! Much appreciated. I am closing the ticket.
