### ISSUE TITLE
"calico-etcd.yaml": Secret in version "v1" cannot be handled as a Secret

### ISSUE THREAD

**Issue by ayunwSky** [projectcalico/calico#7257]
kubernetes version: v1.26.0
calico version: v3.25.0

When I install calico in kubernetes with calico-etcd.yaml,download yaml with `curl -O https://docs.projectcalico.org/manifests/calico-etcd.yaml`.

Then I changed the secret in calico-etcd.yaml.   Convert the etcd-key.  pem、etcd. pem and etcd-ca certificate files into base64 encoding files and fill them in calico-etcd.yaml.   However, application calico-etcd.  yaml found an error, as follows:

```
# kubectl apply -f calico-etcd.yaml
poddisruptionbudget.policy/calico-kube-controllers configured
serviceaccount/calico-kube-controllers unchanged
serviceaccount/calico-node unchanged
configmap/calico-config unchanged
clusterrole.rbac.authorization.k8s.io/calico-kube-controllers unchanged
clusterrole.rbac.authorization.k8s.io/calico-node unchanged
clusterrolebinding.rbac.authorization.k8s.io/calico-kube-controllers unchanged
clusterrolebinding.rbac.authorization.k8s.io/calico-node unchanged
daemonset.apps/calico-node configured
deployment.apps/calico-kube-controllers unchanged
Error from server (BadRequest): error when creating "calico-etcd.yaml": Secret in version "v1" cannot be handled as a Secret: illegal base64 data at input byte 1332
```

I use command `cat etcd.pem | base64 -w 0` to convert,how can i resolve it?

**Comment by MichalFupso** [comment]
Hi @ayunwSky, would you please be able to share your updated calico-etcd.yaml with us (with placeholders for your secrets)? You can also verify if they were encoded properly with `echo "your string" | base64 -d`

**Comment by ayunwSky** [comment]
@MichalFupso Thanks for your reply.
I used another method to solve the problem. Create secret directly from the command line as
```
kubectl create secret generic calico-etcd-secrets -n kube-system \
--from-file=etcd-cert=/data/install-kubernetes/certs/certs/etcd.pem \
--from-file=etcd-key=/data/install-kubernetes/certs/certs/etcd-key.pem \
--from-file=etcd-ca=/data/install-kubernetes/certs/certs/Kubernetes-CA.pem
```

I am using command `echo "your string" | base64 -d` certificate file after the resolution transcoding, found that it is garbled. However, garbled code should be a normal phenomenon, because the certificate used normally in my current production environment is also garbled after transcoding.
