### ISSUE TITLE
Vagrant coreos configs use very old coreos version

### ISSUE THREAD

**Issue by lwr20** [projectcalico/calico#726]
Running through this doc: http://docs.projectcalico.org/v2.2/getting-started/kubernetes/installation/vagrant/

Seen in output:
```
==> k8s-node-01: A newer version of the box 'coreos-stable' is available! You currently
==> k8s-node-01: have version '1185.3.0'. The latest is version '1353.7.0'. Run
==> k8s-node-01: `vagrant box update` to update.
```

**Comment by djosborne** [comment]
That is just the boxes downloaded to your local machine. The Vagrantfile pulls an image from `update_channel='stable'` only if one isn't available locally. So it's up to you to run that command and proceed.
