### ISSUE TITLE
Can we install calico on k3s cluster as default CNI in unencapsulated mode ? i.e without VXLAN or ipip encapsulation.

### ISSUE THREAD

**Issue by samar08** [projectcalico/calico#7262]
Can we install calico on k3s cluster as default CNI in unencapsulated mode ? i.e without VXLAN or ipip encapsulation.
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Calico version
* Orchestrator version (e.g. kubernetes, mesos, rkt):
* Operating System and version:
* Link to your project (optional):

**Comment by caseydavenport** [comment]
Yep, that should definitely be possible - are you seeing that it doens't work?
