### ISSUE TITLE
calico can not spread external BGP route in cluster

### ISSUE THREAD

**Issue by jary-287** [projectcalico/calico#7270]
Calico node can not spread external route when it leaned a route from external EBGP neighbor.
## Expected Behavior

The node should spread the route which id learned from a EBGP neighbor  to other neighbor.

## Current Behavior

Calico node can not spread external route when it leaned a route from external EBGP neighbor.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Calico version 3.24.3
* Orchestrator version (e.g. kubernetes, mesos, rkt): k8s v1.24.4
* Operating System and version: ubuntu 20.04 LTS
* Link to your project (optional):

**Comment by coutinhop** [comment]
Hey @jary-287 can you provide some more details of your setup so that we can try to investigate/reproduce? Are you missing the route from an ebgp neighbor outside the cluster inside the cluster? Or to a 2nd outside neighbor? Could you provide details of the cluster's BGP configureation and peers, and maybe the external bgp neighbors as well? Thanks!

**Comment by jary-287** [comment]
> Hey @jary-287 can you provide some more details of your setup so that we can try to investigate/reproduce? Are you missing the route from an ebgp neighbor outside the cluster inside the cluster? Or to a 2nd outside neighbor? Could you provide details of the cluster's BGP configureation and peers, and maybe the external bgp neighbors as well? Thanks!

This is the first time I've used issue and thank you for your. reply.

**Comment by jary-287** [comment]
> Hey @jary-287 can you provide some more details of your setup so that we can try to investigate/reproduce? Are you missing the route from an ebgp neighbor outside the cluster inside the cluster? Or to a 2nd outside neighbor? Could you provide details of the cluster's BGP configureation and peers, and maybe the external bgp neighbors as well? Thanks!

Hey, this is the first time I've used issue and thank you for your reply. I will show some details for my problem.
First, my lab is shown below.
<img width="604" alt="image" src="https://user-images.githubusercontent.com/59545791/217123622-918a58a2-7663-4ba7-bbf5-8117e63d44d9.png">
The neighbor information:
1.Node1 have neighbor with all nodes.
![image](https://user-images.githubusercontent.com/59545791/217123813-5034644c-25df-46d9-8140-dc2a63f496fe.png)
2.frr node have establish EBGP neighbor with node1 and have the best route.
![image](https://user-images.githubusercontent.com/59545791/217124057-f1be4647-50c4-4b52-b19f-15d196c51cbf.png)

problem
1.Just as I expected，node1 have learned 1.1.1.1, but it should be  learned by master and node2, but it does not.
2.I have find the answer with google, it seems that calico not support import the external route but I can not find it in calico document.

**Comment by mazdakn** [comment]
@jary-287 What's the BGP configuration of Calico?
