### ISSUE TITLE
[Feature Request] Implement a way to enable RFC 5549 support in BIRD

### ISSUE THREAD

**Issue by lhog** [projectcalico/calico#7284]
## Expected Behavior

[RFC 5549](https://datatracker.ietf.org/doc/rfc5549/) defines the method used for BGP to advertise IPv4 prefixes with IPv6 next hops. This is handy to enable peering on so-called unnumbered interfaces, i.e. interfaces having only a auto-configured link-local IPv6 addresses. Most of the top-of-rack switch vendors implement RFC 5549 as it enables establishing BGP peering configuration with a very generic statement like: `neighbor interface ethXX remote-as <number>|internal|external`, so this statement can be made a template and applied wide in the fabric on all BGP enabled interfaces with minimal changes (usually only interface name will change).

With RFC 5549 in place you don't even need to have IPv4 addressing on peer-to-peer links between servers and switch(es), which also makes configuration management much easier.

BIRD has a support for RFC 5549 configuration too See: https://bird.network.cz/?get_doc&v=20&f=bird-6.html#ss6.3
> interface string
    Define interface we should use for link-local BGP IPv6 sessions. Interface can also be specified as a part of neighbor address (e.g., neighbor fe80::1234%eth0 as 65000;). The option may also be used for non link-local sessions when it is necessary to explicitly specify an interface, but only for direct (not multihop) sessions.

However Calico `BGPPeer` resource only expects `IPv4:port` or `IPv6:port` as a valid value of `peerIP`.

As an idea it's possible to extend `peerIP` to support the BGP peer defined as interface name or interface name wildcard or introduce a new field say `peerInterface`. Obviously the updated fields semantics will need to be fed back to BIRD as configuration.

## Current Behavior

Unnumbered BGP is not possible.

## Possible Solution

Manual configuration

## Context

Reduce operation / configuration complexity.

## Your Environment

* Calico version
* Orchestrator version (e.g. kubernetes, mesos, rkt):
* Operating System and version:
* Link to your project (optional):

**Comment by caseydavenport** [comment]
Anything BIRD supports we should be able to add support for, but we just need to agree on what the configuration model would look like.

**Comment by lhog** [comment]
I've never contributed to Calico, but happy to give it a try.

**Comment by caseydavenport** [comment]
Let's start with figuring out what the configuration model on the BGPPeer resource would need to look like.

Once we have that, I believe @coutinhop may have recently made a similar change to add a new config option, so might be able to help with the nitty-gritty details.

**Comment by lhog** [comment]
Two main implementation possibilities are outlined in the original comment, I think both options have their pros and cons.
Extending `BGPPeer`:
+) Probably easier to implement and integrate
+) Lesser documentation effort
+) No need to detect and resolve a conflict when both `BGPPeer` and `peerInterface` are set up.
-) `BGPPeer` doesn't quite a fit for interface name

Introducing `peerInterface` (or alike) - opposite of the above.

If I were to pick one of them I'd probably go with extending of `BGPPeer`.

**Comment by caseydavenport** [comment]
I think it would be a good idea to get @nelljerram to look at the UX you've proposed.

Would also like to poke @mgleung to add this to his radar in terms of Calico roadmap.

**Comment by mgleung** [comment]
bumping this for @nelljerram to get some thoughts on the proposed UX of extending `BGPPeer`

**Comment by lhog** [comment]
> Can you confirm that that's correct understanding, and that Linux supports all that?

Confirmed, you got it 100% right.

> Next, I'm wondering exactly what BIRD does with an interface <interface> configuration? I'm presuming - given your preamble about the Cisco-style config - that there isn't any an explicit peer address with this (even IPv6 link-local), is that right? It tells BIRD that there should or can be sessions through that interface, and that once there are sessions, it can set the interface's IPv6 link-local address as the next hop when exporting. But how does BIRD know what sessions to initiate via that interface?

Right. The IPv6 link-local addresses are autogenerated by Linux OS on all eligible network interfaces.
The BGP session is established on a point to point Ethernet link between a server and top of rack switch, both acting as BGP speakers. The standard process known as IPv6 neighbor discovery is responsible for populating neighbor tables on such links. The `interface string` enables the process of automatic session set up.

**Comment by lhog** [comment]
This is way too slow.

**Comment by kavana-14** [comment]
$ bird --version
BIRD version v0.3.3+birdv1.6.8

$ k3s --version
k3s version v1.29.6+k3s1 (83ae095a)
go version go1.21.11

OS: ubuntu 22.04

With calico-bird we are also observing as below:

1. bird without enable-ipv6 is not distributing ipv6 routes through BGP and
2. bird with enable-ipv6 is not distributing ipv4 routes through BGP
Can one address family redistributing routes for both ipv4 and ipv6?

I'm working on kubernetes networking, with Calico cni plugin. I want to configure the BIRD that is available in the ProjectCalico repo. But both ipv4 and v6 are not supported. If I enable ipv6 it won't parse ipv4 address or vice versa.

https://github.com/projectcalico/bird.git //where the repo was cloned
installation step:
./configure
make
make install

bird.conf:
protocol static {
        route 10.0.0.0/24 via 55.55.55.44;
        route 10.10.0.0/16 blackhole;
        route 10.20.0.0/20 unreachable;
        route 10.30.50.0/28 prohibit;
        route 20.20.20.0/24 via 2001:1::2;
}

 protocol static {
        ipv6 { export all; };
        route 2001:db8:1::/48 via 5555::6666;
        route 2001:db8:2::/48 blackhole;
        route 2001:db8:3::/48 prohibit;
        route 2001:db8:4::/48 unreachable;
}

$ ./bird -d -c ./bird.conf
bird: ./bird.conf:27:11 This is an IPv4 router, therefore IPv6 addresses are not supported

I'm expecting it should work fine for both ipv4 and v6 addresses.
