### ISSUE TITLE
if we use calico-IPAM for ip address management of the pods do we have to use whereabouts ipam for assigning unique ip addresses for the additional network interfaces like macvlan or ipvlan attached to the pods?

### ISSUE THREAD

**Issue by samarhpe** [projectcalico/calico#7288]
if we use calico-IPAM for ip address management of the pods do we have to use whereabouts ipam for assigning unique ip addresses for the additional network interfaces like macvlan or ipvlan attached to the pods?
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Calico version
* Orchestrator version (e.g. kubernetes, mesos, rkt):
* Operating System and version:
* Link to your project (optional):

**Comment by tomastigera** [comment]
some hints on incompatibility https://github.com/projectcalico/calico/issues/5672
