### ISSUE TITLE
Running a Cluster (MicroK8s) on  Wireguard

### ISSUE THREAD

**Issue by mlankenau** [projectcalico/calico#7292]
More a question than an issue:

Is it possible to run calico on top of a wireguard network? I understand that calico can
have encrypted connections between nodes, but we have a scenario, where nodes are in
a private network and cannot be accessed by the rest of the cluster.

Any idea or pointer to more information on how to run calico on top of a wireguard VPN would be highly appreciated.

**Comment by mazdakn** [comment]
@frozenprocess do you know of any resource about running Calico on top of wireguard?

**Comment by mazdakn** [comment]
@mlankenau have you tried it? any issue that we can help with?

**Comment by mazdakn** [comment]
Closing the issue due to inactivity. @mlankenau feel free to re-open if you have an update.

**Comment by amandakcc** [comment]
I’m doing this with WireGuard + RHEL9.2 + microk8s. A few points to note. Please tell me if I made mistakes on that.

1. Using wg-quick down wg0, which deletes the interface wg0, will disrupt the Kubernetes API and kubectl will need around one minute to come back to existence, and the pod statuses will be blown to Unknown everywhere. So manually managing ip route is desirable.
2. WireGuard settings precedes Calico configuration. So setting AllowedIPs in peers to 0.0.0.0/0 will route in-cluster traffic to wg0 interface and the cluster will just fail. So it’s necessary to exclude the pod CIDR and service CIDR (which includes K8S API) from the AllowedIPs range, and you may need a calculator for that. https://www.procustodibus.com/blog/2021/03/wireguard-allowedips-calculator/
