### ISSUE TITLE
Unable to set an ippool as default for pods

### ISSUE THREAD

**Issue by rshiva777** [projectcalico/calico#7299]
I have two calico IPPool added to my kubernetes cluster, both are enabled

NAME                  CIDR            NAT    IPIPMODE   VXLANMODE   DISABLED   DISABLEBGPEXPORT   SELECTOR
default-ipv4-ippool   100.96.0.0/11   true   Always     Never       false      false              all()
new-ipv4-ippool       192.0.0.0/16    true   Always     Never       false      false              all()

When ever i try to create a pod, it is automatically picking the IP from any of the above pools, not the specific pool. However i can enable an annotation at pod level to pick a particular IPPool for IP allocation.

What i am trying is to enable an default IPPool, so all the pods will get the IPs allocated from the default pool
For specific set of applications, i will enable the annoatation of the IPPool of the non-default one to allocate the ips

## Expected Behavior

What i am trying is to enable an default IPPool, so all the pods will get the IPs allocated from the default pool
For specific set of applications, i will enable the annoatation of the IPPool of the non-default one to allocate the ips

## Current Behavior

When ever i try to create a pod, it is automatically picking the IP from any of the above pools, not the specific pool. However i can enable an annotation at pod level to pick a particular IPPool for IP allocation.

## Your Environment

* Calico version: v3.22.1
* Orchestrator version (e.g. kubernetes, mesos, rkt): kubernetes
* Operating System and version: ubuntu
* Link to your project (optional):

**Comment by caseydavenport** [comment]
One thing you can do is adjust the nodeSelector on the second IP pool so that it doesn't select any nodes in your cluster - an IP pool will only be used by default if it selects the node.

You can then use annotations on specific pods to use the second pool.

**Comment by rshiva777** [comment]
Hello @caseydavenport ,

Yes, we can add nodeselector on the second IPpool, but again this ip will be picked by the pods only when they deploy on the selected nodes

Why i am trying to achieve is,

1. I want a first ippool, where all the pods deployed will pick ip from the default ippool (first pool)
2. I want a second ippool, where pods with specific annotations added to pick ip from the second ippool

Lets say both are ippools are enabled, so without mentioning of any annotation to the pod we are not sure which ip is picked by the pod (either from first ippool or second ippool)

**Comment by rshiva777** [comment]
With reference to the below comment,

My cluster has 2 ipools and I have deploy a sample nginx application with 5 replicas.

```
test@localhost:~/calico$ kubectl get po -n aqaduct1 -o wide
NAME                       READY   STATUS    RESTARTS   AGE   IP                NODE                                NOMINATED NODE   READINESS GATES
nginx04-7bbb87f87b-dmj2l   1/1     Running   0          19s   192.168.0.135     gks-rat-stg-4-md-0-cfc98465-wvct5   <none>           <none>
nginx04-7bbb87f87b-g95fx   1/1     Running   0          19s   100.127.113.192   gks-rat-stg-4-md-0-cfc98465-h6mz4   <none>           <none>
nginx04-7bbb87f87b-gmrwf   1/1     Running   0          19s   192.168.0.68      gks-rat-stg-4-md-0-cfc98465-m66vz   <none>           <none>
nginx04-7bbb87f87b-snhx8   1/1     Running   0          19s   192.168.0.3       gks-rat-stg-4-md-0-cfc98465-9lshl   <none>           <none>
nginx04-7bbb87f87b-tnfvx   1/1     Running   0          19s   192.168.0.196     gks-rat-stg-4-md-0-cfc98465-wvsb7   <none>           <none>
```

See, out of 5 pods 4 ips are taken from 1st ippool (default pool) and  1 replica ip is taken from second pool (newly created). I want them to take ip from the default pool itself unless specified any annotations

**Comment by rshiva777** [comment]
Thanks for the suggestion @caseydavenport 

CLosing the issue
