### ISSUE TITLE
Access to pod from external system in same VNET of Kubernetes cluster 

### ISSUE THREAD

**Issue by carlosmkb** [projectcalico/calico#730]
Hi,
I have a Kubernetes cluster with calico and created an ippool with pods address CIDR.
With this configuration I can access to external systems from the pods, but cannot access directly to pods (10.244.x.x) from an external system in the same vnet.
There is any solution for this requirement?

**Comment by tmjd** [comment]
This might help http://docs.projectcalico.org/v2.1/usage/external-connectivity#inbound-connectivity

**Comment by carlosmkb** [comment]
Following that documentation, now I'm trying to create a global BGP peering to the external host, but the creation fails:
"Failed to create 'bgpPeer' resource: operation Create is not supported on BGPPeer(global, ip=10.250.10.100)"

**Comment by tmjd** [comment]
Are you following http://docs.projectcalico.org/v2.1/usage/configuration/bgp?

Could you add the full bgpPeer configuration you were trying to use?

**Comment by carlosmkb** [comment]
cat << EOF | calicoctl create -f -
apiVersion: v1
kind: bgpPeer
metadata:
  peerIP: 10.250.10.100
  scope: global
EOF

**Comment by tmjd** [comment]
I think you have to include
```
spec:
  asNumber: <AS_Number>
```
You can retrieve it with `calicoctl config get asNumber`
And your BGP configuration on your external host needs to be configured with the same AS number.

**Comment by tmjd** [comment]
@carlosmkb Were you able to get direct access to your pods setup?

**Comment by tmjd** [comment]
I'm going to close this issue for now.  @carlosmkb if you are still having trouble with this feel free to reopen this issue or create a new one.
