### ISSUE TITLE
failed to fetch https://projectcalico.docs.tigera.io/charts/index.yaml : 404 Not Found

### ISSUE THREAD

**Issue by CecileRobertMichon** [projectcalico/calico#7300]
As of a few hours ago, the Helm chart repo is unreachable, causing all `helm repo add` commands in CI to fail:

```
helm repo add projectcalico https://projectcalico.docs.tigera.io/charts
Error: looks like "https://projectcalico.docs.tigera.io/charts" is not a valid chart repository or cannot be reached: failed to fetch https://projectcalico.docs.tigera.io/charts/index.yaml : 404 Not Found
```

Also posted in Slack: https://calicousers.slack.com/archives/CPTH1KS00/p1675839419742799

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Calico version
* Orchestrator version (e.g. kubernetes, mesos, rkt):
* Operating System and version:
* Link to your project (optional):

**Comment by uristernik** [comment]
Experiencing this too ☝️

**Comment by uristernik** [comment]
@CecileRobertMichon They changed the domain of the docs and the hosted repo -> https://docs.tigera.io/calico/3.25/getting-started/kubernetes/helm

Pull from https://docs.tigera.io/calico/charts

**Comment by edumgui** [comment]
Thanks to FluxCD notifications we know that this started to happen today at ~1 am UTC.

> helmrepository/projectcalico.system
failed to fetch Helm repository index: failed to cache index to temporary file: failed to fetch https://projectcalico.docs.tigera.io/charts/index.yaml : 404 Not Found
summary
flux resources

It's solved by replacing `https://projectcalico.docs.tigera.io/charts` with `https://docs.tigera.io/calico/charts` as @uristernik suggested before.

But I was not able to find any notification about that change.

**Comment by mboersma** [comment]
It wasn’t possible to make a redirect? Where was this announced?
This is seriously disappointing and has cost us a lot of downtime.

**Comment by senser-adi** [comment]
In a similar issue i was pulling `https://docs.projectcalico.org/manifests/calico.yaml` and it stopped working as well. 
Changing this to `https://docs.tigera.io/manifests/calico.yaml` is not working..
Any idea?
Thanks!

**Comment by edumgui** [comment]
> In a similar issue i was pulling `https://docs.projectcalico.org/manifests/calico.yaml` and it stopped working as well. Changing this to `https://docs.tigera.io/manifests/calico.yaml` is not working.. Any idea? Thanks!

Are you looking for `https://raw.githubusercontent.com/projectcalico/calico/v3.25.0/manifests/tigera-operator.yaml`?

Extracted from doc https://docs.tigera.io/calico/3.25/getting-started/kubernetes/quickstart#install-calico

**Comment by mboersma** [comment]
In the [Slack channel](https://calicousers.slack.com/archives/CPTH1KS00) we're told a redirect is now in place, and it does seem to be working for us.

**Comment by ctauchen** [comment]
Sorry for the disruption, folks! We've moved to the new docs site, and it wasn't entirely seamless.

For charts, both of these locations work:

https://projectcalico.docs.tigera.io/charts/index.yaml (old site)
https://docs.tigera.io/calico/charts/index.yaml (new site)

Both are proxies for the same location, so can be used interchangeably.

Other Calico manifests continue to be hosted at raw.githubusercontent.com, so those locations remain the same.

All the current locations can be found in the docs themselves: https://docs.tigera.io/calico/

If you find anything else not working right, let me know and I'll make sure it gets sorted out. Thanks!

**Comment by caseydavenport** [comment]
Going to leave this one open for the rest of the week as we tidy up anything we broke as part of the documentation move. It sounds like most redirects have been restored now, so please shout if there is something you expect to be working that is not!

**Comment by r-eid** [comment]
There is no redirect for https://docs.projectcalico.org/manifests/calico.yaml yet.
