### ISSUE TITLE
Should calico csi-driver run on every node ? What about tolerations for it ?

### ISSUE THREAD

**Issue by hajdukda** [projectcalico/calico#7344]
Hi,

Im using operator deployment and it seems this daemonset is missing our tolerations. How can we configure operator to deploy that ds everywhere ?

**Comment by caseydavenport** [comment]
I believe @coutinhop has a fix that should be coming in an upcoming release, but he can speak more to that!

**Comment by hajdukda** [comment]
Any plans to backport it ?

**Comment by Josh-Tigera** [comment]
I believe this is the change you're interested in: https://github.com/tigera/operator/pull/2331

Feel free to have a look and let me know if it didn't quite cover what you're looking for.

We don't typically backport enhancements to maintenance releases of existing branches but you can pick it up in release v3.26

**Comment by hajdukda** [comment]
> I believe this is the change you're interested in: [tigera/operator#2331](https://github.com/tigera/operator/pull/2331)
> 
> Feel free to have a look and let me know if it didn't quite cover what you're looking for.
> 
> We don't typically backport enhancements to maintenance releases of existing branches but you can pick it up in release v3.26

Do I understand docs correctly that this component is only really important if I want to make use of Istio ? If it would be a case its a critical DS and its not installed by operator everywhere - it would be super bad for anyone working on 3.24-3.25 ?

**Comment by Josh-Tigera** [comment]
Yes that's right.

**Comment by caseydavenport** [comment]
@Josh-Tigera can this be closed? Do we support tolerations for this now?

**Comment by Josh-Tigera** [comment]
Yeah I think we can close this as both the code and docs are merged, they just haven't made it into any releases yet.
[Code PR](https://github.com/tigera/operator/pull/2331/files#diff-eee11695119388fa68e2cc77b3020163dc1320ae34c9d2ec057d0cb31b6ab8cc)
[Docs PR](https://github.com/tigera/docs/pull/256)
