### ISSUE TITLE
According to the kubernetes official demo test network strategy failed

### ISSUE THREAD

**Issue by AbelHugh** [projectcalico/calico#7362]
kubernetes version:1.24.4
calico version: v3.24.1
ipipmode: crosssubnet

As shown in the figure below, I follow the official kubernetes network isolation example step by step

document address：
https://kubernetes.io/docs/tasks/administer-cluster/declare-network-policy/

Until the end, even if --labels="access=true" is added, it is still inaccessible
![219536226-76d99ed5-a070-4344-a8f7-5cfa263d9d38](https://user-images.githubusercontent.com/71317399/219539251-6d402457-65b4-48ca-8254-e2b83e66873d.png)

ippool:
![image](https://user-images.githubusercontent.com/71317399/219538356-ef4e97d5-0bc5-4df5-8cb1-1b8e8dc484b0.png)

**Comment by Josh-Tigera** [comment]
So just to verify, you can successfully communicate between your pods prior to creating the `access-nginx` policy?

Can you do a `describe` or `get -o yaml` on both `access-nginx` and your nginx pod?
