### ISSUE TITLE
Is there a way to configure typha tolerations?

### ISSUE THREAD

**Issue by deepalakshmic** [projectcalico/calico#7363]
## Expected Behavior
I am trying to add below configuration in calico values.yaml

installation:
  kubernetesProvider: "EKS"
  registry: ${AWS_ACCOUNT_ID}.dkr.ecr.${ECR_REGION}.amazonaws.com/nuix-platform-ext/${AWS_ACCOUNT_ALIAS}
  typhaDeployment:
    spec:
      template:
        spec:
          nodeSelector:
            role: support
          tolerations:
            - key: CriticalAddonsOnly
              operator: Exists

tolerations:
nodeSelector:
  role: support

## Current Behavior
Terraform helm_release throws error - Error: error validating "": error validating data: ValidationError(Installation.spec): unknown field "typhaDeployment" in io.tigera.operator.v1.Installation.spec

## Context
Trying to modify tolerations and node selector for calico-typha pods as it get scheduled on node-groups where it should not be scheduling the pod. This affects in scaling down the node group.

## Your Environment
* Calico version - 3.25.0
* Orchestrator version (e.g. kubernetes, mesos, rkt): 1.23
* Operating System and version:linux
* Link to your project (optional):

**Comment by caseydavenport** [comment]
You should be able to adjust tolerations for Typha using the TyphaDeployment section within the Installation API: https://docs.tigera.io/calico/3.25/reference/installation/api#operator.tigera.io/v1.TyphaDeployment

**Comment by mgleung** [comment]
Closing this since it seems to be resolved. Please shout out if any other issues occur and we can reopen this thread.
