### ISSUE TITLE
BFD: failureDetectionMode

### ISSUE THREAD

**Issue by zeysh** [projectcalico/calico#7366]
## Expected Behavior
Hello,

Do you have plan to add `failureDetectionMode` feature in BGPPeer crd for non enterprise version?

Refs: 

- https://github.com/tigera/operator/blob/master/pkg/crds/enterprise/crd.projectcalico.org_bgppeers.yaml#L54
- https://github.com/tigera/operator/blob/master/pkg/crds/calico/crd.projectcalico.org_bgppeers.yaml

## Current Behavior

`failureDetectionMode` not available in non enterprise version crd.

## Possible Solution

Implement `failureDetectionMode` in non entreprise version.

Many thanks.

**Comment by mgleung** [comment]
I think for organizational purposes, I'm going to close this issue out and track everything against #7086 but please shout out if we need to reopen this.
