### ISSUE TITLE
Ring-topology network with calico

### ISSUE THREAD

**Issue by hans-fischer** [projectcalico/calico#7377]
Dear Calico-Community,

as far as I know you can only assign one NIC to be used by calico.
Its possible to use auto-detection, but this results in one NIC of the node used.

I would realy like to build a 3 node cluster with each having a 40gbit x2 network card. Connected to each other with a DAC Calble. So I don't need to power a switch and gain more resitance to failure by removing the switch as singel point of failure.

Hardware: ConnectX-3 CX354A (realy affordable, 8x PCIe 3.0)

Each card has 2 ports and is represented by two nic-interfaces.
With the help of static IPs and static routing it's easy to establish a reliable connecting between these 3 nodes.

Do you guys see a way to configure calico in a way so it just use the host-routing to reach hosts in the host-network? Or any other way - I currently dont know about - to reach my goal?

Calico-Version: v3.25.0 (helm)

Thank you very much
Hans Fischer

**Comment by mgleung** [comment]
Maybe @caseydavenport or @fasaxc might know? I believe that this works in OpenStack because of Neutron but I'm not sure if we have anything in Calico that allows this.

**Comment by fasaxc** [comment]
Yes, you can do this kind of thing:
* Add a loopback IP to your nodes; i.e. a stable IP that is on neither interface.  Assign that to `lo`
* Set up Calico (and kubernetes) to use the loopback IP as the node IP
* Use BGP peerings over the per-interface IP addresses.

**Comment by fasaxc** [comment]
When creating your BGP peers, use `sourceAddress: None`, then BIRD will choose the per-interface address for the peering.  You can use a link-local IP or whatever you like for the addresses.  It's important to have a stable IP for each node or you don't get HA because the IP of a given interface becomes invalid when that interface goes down.
