### ISSUE TITLE
feature request: Hardware addresses that support pods have an same prefix

### ISSUE THREAD

**Issue by cyclinder** [projectcalico/calico#7396]
## Expected Behavior

Support custom mac address to the pod, For example, add a field to the CNI configuration file: `mac_prefix`:

```shell
root@controller:~# cat /etc/cni/net.d/10-calico.conflist
{
  "name": "calico",
  "cniVersion":"0.3.1",
  "plugins":[
    {
      "datastore_type": "kubernetes",
      "nodename": "controller",
      "type": "calico",
      "log_level": "info",
      "log_file_path": "/var/log/calico/cni/cni.log",
      "mac_prefix": "1a:3b",    # <======
      "ipam": {
        "type": "calico-ipam",
        "assign_ipv6": "true",
        "ipv6_pools": ["fd85:ee78:d8a6:8607::1:0000/112"],
        "ipv4_pools": ["10.233.64.0/18"],
        "assign_ipv4": "true"
      },
      "policy": {
        "type": "k8s"
      },
      "kubernetes": {
        "kubeconfig": "/etc/cni/net.d/calico-kubeconfig"
      }
    },
    {
      "type":"portmap",
      "capabilities": {
        "portMappings": true
      }
    },
    {
      "type":"bandwidth",
      "capabilities": {
        "bandwidth": true
      }
    }
  ]
}
```

This is a global configuration, When a Pod is created, the mac addresses of all Pods will have the same prefix：`0a:1b`. The complete mac address is stitched together from two parts: `mac_prefix` + `hexcode(ip)`. For example:

```
root@controller:~# kubectl get po -o wide
NAME                                        READY   STATUS      RESTARTS      AGE    IP               NODE         NOMINATED NODE   READINESS GATES
test-794b96cd5b-d92pp                       1/1     Running     0             132m   10.233.119.208   controller   <none>           <none>
root@controller:~# kubectl exec -it test-794b96cd5b-d92pp -- ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: tunl0@NONE: <NOARP> mtu 1480 qdisc noop state DOWN qlen 1000
    link/ipip 0.0.0.0 brd 0.0.0.0
3: ip_vti0@NONE: <NOARP> mtu 1480 qdisc noop state DOWN qlen 1000
    link/ipip 0.0.0.0 brd 0.0.0.0
5: eth0@if386536: <BROADCAST,MULTICAST,UP,LOWER_UP,M-DOWN> mtu 1430 qdisc noqueue state UP
    link/ether 1a:3b:0a:e9:77:d0 brd ff:ff:ff:ff:ff:ff
    inet 10.233.119.208/32 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fd85:ee78:d8a6:8607::1:3110/128 scope global
       valid_lft forever preferred_lft forever
    inet6 fe80::39:6ff:fe1a:d64b/64 scope link
       valid_lft forever preferred_lft forever
```

Also，You can also do this via annotations：

```shell
apiVersion: v1
kind: Pod
metadata:
  annotations:
    cni.projectcalico.org/macPrefix: "1a:3b"
```
Note:  annotations have a higher priority than the global configuration in `cni-conf`. By default, this feature is disabled, Users can decide to enable or disable it according to their needs.

I have implemented this in my local environment, and if you guys think it makes sense, I am willing to open a PR for it :)

Thanks!

## Current Behavior

feature request: Support custom mac address

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Calico version
* Orchestrator version (e.g. kubernetes, mesos, rkt):
* Operating System and version:
* Link to your project (optional):

**Comment by caseydavenport** [comment]
Could you explain your use-case a bit more? Curious what the motivation is.

Also, related PR: https://github.com/projectcalico/calico/pull/6249

**Comment by cyclinder** [comment]
Thanks for the response!

This motivation comes from our users, who hope every deployment to have the same hw address prefix. for example:

- deploy1 with hw prefix: `0a:1b`

||IP|HW addr|
|---|---|---|
|Pod1|10.233.0.1|0a:1b:0a:e9:00:01|
|Pod2|10.233.0.2|0a:1b:0a:e9:00:02|

- deploy2 with hw prefix: `0a:1c`

||IP|HW addr|
|---|---|---|
|Pod1|10.233.10.1|0a:1c:0a:e9:0a:01|
|Pod2|10.233.10.2|0a:1c:0a:e9:0a:02|

Users can sort applications by HW address prefix for easy management. 

I notice that https://github.com/projectcalico/calico/pull/6249, I think it's two different things from what I need. But it is possible to implement my needs based on it. 

Here are some thoughts: 

```
     cni.projectcalico.org/hwAddr
```

- If it is a full hw address, the same logic as now
- If it is a hw address prefix, the complete mac address is stitched together from two parts: mac_prefix + hexcode(ip)

**Comment by mazdakn** [comment]
@cyclinder can you please elaborate a bit more how setting mac address based on IP address helps with ease of management?
The original change to support setting container mac address was based on licensing application, but I am not sure about this use case.

**Comment by mazdakn** [comment]
Thanks for explanation, now I understand the use case. In that case, they should be able to set `cni.projectcalico.org/hwAddr` annotation with the correct prefix, right? there should be no need for Calico to generate it, IMO.

**Comment by cyclinder** [comment]
@mazdakn  Yes, They only need to set a Mac address prefix via annotations, and the complete Mac address is spliced from this prefix and the pod's IP.

**Comment by mazdakn** [comment]
My question is that why should it be generated based on pod's IP? if the only important factor is the prefix, then it can also be generated from the prefix and some random number, right?

**Comment by cyclinder** [comment]
Yes, Pod's IP-based reasons are an IPv4 address that can be perfectly converted to a MAC address suffix(4 bytes), but an ipv6 address not.  I think it is not so important if it is based on IP. it can be generated from some random number, which looks simpler.

**Comment by cyclinder** [comment]
So the conclusion here is mac prefix + a randomly generated string as mac suffix?

**Comment by mazdakn** [comment]
More specifically, I mean this can be generated outside of `Calico`, and then be set for each pod with the available annotation. WDYT?

**Comment by cyclinder** [comment]
If that's the case, then we need to set up two annotations for the pod?  The first is to specify the MAC prefix via `cni.projectcalico.org/hwAddr`, and the second is to specify a random MAC suffix by the user. 

If so, I think two annotations are a bit difficult to use. As a user, I'd prefer one annotation to the thing.

**Comment by mazdakn** [comment]
No, this can be set by the same `cni.projectcalico.org/hwAddr`. It's possible to use a script or a program to generate the MAC, and assign it to a pod via the annotation. I just don't see why `calico` should generate it.

**Comment by cyclinder** [comment]
Do mac prefixes and suffixes use the same annotations `cni.projectcalico.org/hwAddr`?  This only works if set separately for pods, but mac Prefix is deployment level, and different pods of the same deployment cannot use the same MAC address, right?

Also, why don't you like calico to generate it？ Is there some reason for this?

**Comment by mazdakn** [comment]
Ok, got your point. In that case, it make sense to generate it based on pod IP.

**Comment by mazdakn** [comment]
I'll review the PR soon then.

**Comment by cyclinder** [comment]
I didn't test this feature in Felix, I compiled this binary separately before and then let it work after the calico call, which is no problem.

Maybe it needs to test in Felix?  If yes, I can test it next week, busy with work in recent days....

**Comment by mazdakn** [comment]
@cyclinder the main thing here is that the application you described cannot be done by Felix, as workload's packets MAC address are replaced by node's ones.
