### ISSUE TITLE
kubectl set env does not effact the calico-node containers

### ISSUE THREAD

**Issue by devops00x** [projectcalico/calico#7397]
Set CALICO_DATA_PROTECTION_MODE to true using:
`kubectl set env daemonset/calico-node CALICO_DATA_PROTECTION_MODE=true -c calico-node -n calico-system`
## Expected Behavior
The env is set and I can list it using:
`kubectl set env daemonset/calico-node  -c calico-node -n calico-system  --list`

## Current Behavior
One of pods from the calico-node daemonset restartes. The env variable is not set on any of the pods.
I tried for other objects than the calico-node daemonset and `kubectl set env` works as expacted.

## Possible Solution
Either setting env using kubectl or any other way to add this env rathar than editing the calico-node daemonset manifest or setting env by `kubect exec` command?

## Steps to Reproduce (for bugs)
1. `kubectl set env daemonset/calico-node CALICO_DATA_PROTECTION_MODE=true -c calico-node -n calico-system`
2. `kubectl set env daemonset/calico-node  -c calico-node -n calico-system  --list`

## Context
Trying to block sending anonymised data out from my Azure Kubernetes Cluster (AKS).

## Your Environment

* Calico version: cni, calico-node, and flexvol version: v3.24.0
* Orchestrator version (e.g. kubernetes, mesos, rkt): AKS v1.25.4
* Operating System and version: Linux - Ubuntu 20.4

**Comment by caseydavenport** [comment]
This is actually working as expected. 

The environment is controller by the operator, and reconciled when any changes are made: https://github.com/tigera/operator/blob/master/pkg/render/node.go#L1173

I'm not familiar with CALICO_DATA_PROTECTION_MODE though, what does that do?

**Comment by devops00x** [comment]
Still doesn't work for me. 
I want to block Calico from sending anonymised log data out of my AKS cluster. It is a better way to do that?

**Comment by caseydavenport** [comment]
https://docs.tigera.io/calico/3.25/reference/resources/felixconfig

> usageReportingEnabled | Reports anonymous Calico version number and cluster size to projectcalico.org. Logs warnings returned by the usage server. For example, if a significant security vulnerability has been discovered in the version of Calico being used.
-- | --

Yep, we have a config option for that.
