### ISSUE TITLE
projectcalico.org "documentation" link returns 404 instead of the introduction page

### ISSUE THREAD

**Issue by gunjan5** [projectcalico/calico#74]
Go to: https://www.projectcalico.org/ 
click on `Documentation`
bam: 404

it should point to `http://docs.projectcalico.org/master/introduction/`
It points to `http://docs.projectcalico.org/en/latest/index.html` right now.

**Comment by djosborne** [comment]
Good catch.

Fixed.

@gunjan5 Can you confirm and merge?

**Comment by gunjan5** [comment]
works!
