### ISSUE TITLE
Canal: Update flannel to more recent version

### ISSUE THREAD

**Issue by laibe** [projectcalico/calico#7400]
The flannel version used in canal is more than one year old (`v0.16.3`). Is there any reason for not updating to a more recent version?

https://github.com/projectcalico/calico/blob/460e6dafc6e7b90e3ffdd6cd7379e508e70371a9/manifests/canal.yaml#L4796 

Latest Flannel: [`v0.21.2` ](https://github.com/flannel-io/flannel/releases/tag/v0.21.2)

**Comment by mazdakn** [comment]
@laibe I don't think there is any reason behind it. Please create a PR for it, so we can review and merge it.
