### ISSUE TITLE
feature request: natively support LoadBalancer resources

### ISSUE THREAD

**Issue by doctorpangloss** [projectcalico/calico#7402]
Calico should provide a LoadBalancer resource controller.

This would resolve conflicts with `metallb` and `kube-vip` BGP functionality.

## Expected Behavior
Declaring a LoadBalancer service with Calico-specific annotations works.

"MVP":
The internal IP field is interpreted as a BGP-advertised VIP with VRRP based failover. Annotations or Calico resources specify a node selector corresponding to the VRRP group Calico should build. Calico daemonset runs keepalived to fulfill this request. The external IP field is interpreted as a WAN IP that other infrastructure routes to this VIP.

Expanded scope:
A `FirewallPeer` resource: Calico reconciles with a network firewall

## Current Behavior
Users who want real load balancing will need hardware vendor or cloud loadbalancers, since `metallb` and `kube-vip` cannot coexist with Calico BGP without caveats.

## Possible Solution
I am not a networking expert: could a subset of `kube-vip`, `metallb` or `keepalived` features work? For example, could `keepalived` be run as a daemon?

## Context
On-premises Calico deployments with high availability need real load balancing, including load balancing of the control plane. Calico does not have the infrastructure to do this, and the various projects that touch BGP (frr or hns) conflict with each other.

**Comment by RefluxMeds** [comment]
Any progress on this topic?

**Comment by RefluxMeds** [comment]
@tomastigera repeating my comment for visibility. Does Calico team have native support for LoadBalancer IPs in roadmap?
Thanks!

**Comment by caseydavenport** [comment]
@RefluxMeds I'm not aware of this being on the core team's roadmap, but I'd be happy to work through a design here with anyone interested in contributing such a feature. I think the first thing would be to lay in concrete terms what the goals and use-cases are.

**Comment by doctorpangloss** [comment]
Goal: effortlessly and idiomatically support LoadBalancer services.

Concrete goals:

##### MVP

Creates a service that functionally behaves the same as a ClusterIP service with external IPs set today. This would concretely require:

 - Use Calico BGP
 - A `Service` with type `LoadBalancer`, `spec.allocateLoadBalancerNodePorts: false` and `spec.loadBalancerClass: "calico"`.
 - Optionally, an annotation that specifies which IPPool to use for the `externalIPs` assigned to the service; or, a dedicated `IPPool` with `loadBalancerCIDRs: ...` for IPAM

This leaves routing from the broader network to the external IP up to the user.

##### Better Routing

The next, high value concrete goal would be where Calico configures other networking infrastructure to implement the LoadBalancer faithfully.

It only makes sense to talk about on premises networks, because cloud environments already do all of this, you would never use Calico load balancing. Among on premises networks, there are only really two kinds: people who have public IPs, and people who don't. I would assume that the vast majority of metallb users are very artisanal, they have 1 public IP they do not control, and they have completely different needs than someone who has a block of static IPs and knows how to use them.

### Case 1: Better routing for artisanal users

A `FirewallPeer` resource that assumes a single host or routing appliance (potentially clustered) manages the connectivity for the cluster to the outside world. This would allow load balancing to be delegated directly to this appliance by creating firewall rules.

### Case 2: Better routing for enterprise users

I'm not really sure!

Knowing how networking infrastructure is actually automated, you would probably want CRDs that specify Python snippets to implement your bespoke network configuration on triggered events. This would allow Calico to delegate the implementation details of the operator behavior like creating, modifying and delete LoadBalancers to the end user in a way that would be high value and get important learnings from the ecosystem.

**Comment by caseydavenport** [comment]
Thanks @doctorpangloss 

> The next, high value concrete goal would be where Calico configures other networking infrastructure to implement the LoadBalancer faithfully.

If I understand correctly, Calico already supports this today using BGP peering to an external device to advertise LoadBalancer IP addresses as documented here: https://docs.tigera.io/calico/latest/networking/configuring/advertise-service-ips#advertise-service-load-balancer-ip-addresses

What Calico doesn't do is _allocate_ LoadBalancer IP addresses - for that, it relies on a third-party controller (e.g., MetalLB controller).

> A FirewallPeer resource that assumes a single host or routing appliance (potentially clustered) manages the connectivity for the cluster to the outside world. This would allow load balancing to be delegated directly to this appliance by creating firewall rules.

How would this differ from the existing BGPPeer resource, which is today used to peer Calico with external routers.

> you would probably want CRDs that specify Python snippets to implement your bespoke network configuration on triggered events

This sounds well out of scope for Calico, I don't think we want to be in the business of configuring external firewall devices or exposing third-party device configuration through our API.

**Comment by caseydavenport** [comment]
> Does Calico team have native support for LoadBalancer IPs in roadmap?

@RefluxMeds could you clarify your understanding of what "native support for LoadBalancerIPs" means in your use-case?

**Comment by RefluxMeds** [comment]
Hi @caseydavenport,
The equivalent of what is supported by MetalLB controller component. That is allocating LoadBalancer service IP addresses.

**Comment by caseydavenport** [comment]
Got it. I am not fundamentally against such a change to Calico (a new component to allocate LoadBalancer service IP addresses). But it's a hard sell to invest resources into a new component that is functionally equivalent to one that is available off the shelf already.

**Comment by caseydavenport** [comment]
@MichalFupso has just merged a PR that does this, so will be coming in v3.30!

**Comment by doka380** [comment]
Hi @caseydavenport , just for planning purposes - when 3.30 is planned to be released? Thank you.

**Comment by caseydavenport** [comment]
Code freeze for v3.30 is expected in a month, and then likely released a month after that.
