### ISSUE TITLE
calico-node is not coming in Running state

### ISSUE THREAD

**Issue by shnigam2** [projectcalico/calico#7414]
calico-node pod showing below errors is logs 
```
felix/daemon.go 245: Failed to get config from datastore error=Get "[https://172.20.0.1:443/apis/crd.projectcalico.org/v1/clusterinformations/default](https://172.20.0.1/apis/crd.projectcalico.org/v1/clusterinformations/default)": dial tcp 172.20.0.1:443: i/o timeout
```

## Expected Behavior
calico-node should be in running state 1/1 for each nodes

## Current Behavior
Due to Readiness probe failing, calico-node is not coming in Running state. Readiness/Livelinessprobe failure errors:-
```
 Warning  Unhealthy  5m26s (x8 over 6m22s)  kubelet            Readiness probe failed: calico/node is not ready: felix is not ready: Get "http://localhost:9099/readiness": dial tcp 127.0.0.1:9099: connect: connection refused
  Warning  Unhealthy  76s (x26 over 6m6s)    kubelet            Liveness probe failed: calico/node is not ready: Felix is not live: Get "http://localhost:9099/liveness": dial tcp 127.0.0.1:9099: connect: connection refused

```

## Possible Solution
Need to fix connectivity for getting felix to be in running state, as of now nothing is listening on 9099 port on nodes.

## Steps to Reproduce (for bugs)
<Production is impacted we have this issue as of now.

1.
2.
3.
4.

## Context
Production EKS cluster is down

## Your Environment

* Calico version 3.20.5
* Orchestrator version (e.g. kubernetes, mesos, rkt): 1.22.9
* Operating System and version: 
```
AME="Amazon Linux"
VERSION="2"
ID="amzn"
ID_LIKE="centos rhel fedora"
VERSION_ID="2"
PRETTY_NAME="Amazon Linux 2"
ANSI_COLOR="0;33"
CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2"
HOME_URL="https://amazonlinux.com/"
```
* Link to your project (optional):

**Comment by gaopeiliang** [comment]
```
dial tcp 172.20.0.1:443: i/o timeout
```

here  is  apiserver service IP address ?  to be sure  kube-proxy work first

**Comment by tomastigera** [comment]
Wha tis your cluster environtment? Aws EKS or you installed the cluster yourself in aws?
