### ISSUE TITLE
the node local docker network is not wrok when the calico opened ebpf

### ISSUE THREAD

**Issue by xxoxx** [projectcalico/calico#7420]
# the node local docker network is not wrok when the calico opened ebpf
## Current Behavior

nodes in the network cannot connect to containers port in the local docker

## Steps to Reproduce (for bugs)

1.install k8s （version:1.26.2）（1 master-node, 2 worker-node）by kubeadm
2. install calico：   kubectl apply -f https://projectcalico.docs.tigera.io/archive/v3.25.0/manifests/calico.yaml
3. open ebpf: calicoctl patch felixconfiguration default --patch='{"spec": {"bpfEnabled": true}}' && calicoctl patch felixconfiguration default --patch='{"spec": {"bpfExternalServiceMode": "DSR"}}'
4. master node run a docker : docker run -itd --name nginx1 -p 18080:80 nginx
5. other node:curl http://masterip:18080   (not connect)
6. when i close ebpf: calicoctl patch felixconfiguration default --patch='{"spec": {"bpfEnabled": false}}'
7. other node:curl http://masterip:18080   (works good)

I want to be able to connect the docker network normally in ebpf mode !
Please confirm that this is a bug or my configuration is not configured correctly

## Your Environment

* Calico version：3.25.0
* k8s:1.26.2
* Operating System and version: debian11 Linux debian-242 5.10.0-21-amd64

**Comment by tomastigera** [comment]
How is the networking for docker done on the master node? Could be an issue with a policy on host endpoint. Could you provide some more info? Like devices, routing etc. on the master node?

**Comment by xxoxx** [comment]
my docker is installed by default: apt-get install docker-ce docker-ce-cli containerd.io
docker version: 23.0.1

route:
"""
root@debian-241:~# route -n
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
0.0.0.0         192.168.3.210   0.0.0.0         UG    0      0        0 enp1s0
10.244.17.0     0.0.0.0         255.255.255.192 U     0      0        0 *
10.244.99.0     192.168.3.242   255.255.255.192 UG    0      0        0 tunl0
10.244.160.192  192.168.3.243   255.255.255.192 UG    0      0        0 tunl0
172.17.0.0      0.0.0.0         255.255.0.0     U     0      0        0 docker0
192.168.3.0     0.0.0.0         255.255.255.0   U     0      0        0 enp1s0
"""

And I tryed use cilium in ebpf mode, but used cilium ,the docker network is  works good.

**Comment by tomastigera** [comment]
It is a bug on our side, sorry for that. You can make it work by setting `bpfHostConntrackBypass: false` in felix configuration `kubectl edit felixconfiguration default` for now.
