### ISSUE TITLE
None default IPPool  that differs from cluster pod CIDR do not assign to nodes

### ISSUE THREAD

**Issue by msergg** [projectcalico/calico#7440]
None default IPPool  that differs from cluster pod CIDR do not assign to nodes

## Expected Behavior

1. Create cluster control plane with default pool 
2. Create new additional ippools that depeneds on node locations, and disable default ippool
3. according to https://docs.tigera.io/calico/3.25/networking/ipam/assign-ip-addresses-topology#create-an-ip-pool-specific-nodes and use feature `nodeSelector: zone == "west"`
4. Install some new nodes with three different location
5. New nodes get address from IpPool defined by IPPool definition

`
apiVersion: crd.projectcalico.org/v1
kind: IPPool
metadata:
  name: pool-a
spec:
  cidr: 10.144.4.0/22
  ipipMode: Never
  natOutgoing: false
  disabled: false
  nodeSelector: topology.kubernetes.io/zone == 'a'
---
apiVersion: crd.projectcalico.org/v1
kind: IPPool
metadata:
  name: pool-b
spec:
  cidr: 10.144.8.0/22
  ipipMode: Never
  natOutgoing: false
  disabled: false
  nodeSelector: topology.kubernetes.io/zone == 'b'
---
apiVersion: crd.projectcalico.org/v1
kind: IPPool
metadata:
  name: pool-c
spec:
  cidr: 10.144.12.0/22
  ipipMode: Never
  natOutgoing: false
  disabled: false
  nodeSelector:  topology.kubernetes.io/zone == 'c'
`

## Current Behavior
1. New nodes creating with disabled or deleted default IPPool(== clusterPodCIDR) 
2. New pods are not getting new ip address and `got error the given pool does not exist, or is not enabled`
`Failed to create pod sandbox: rpc error: code = Unknown desc = failed to...for sandbox "81d00561cac9193c20135a8d41afc0d0cd21a10fa1d04f58b77620312a64390d": plugin type="calico" failed (add): the given pool (10.239.56.0/21) does not exist, or is not enabled`

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Context
Try to use different ipPoolls for specific az on on-premise cluster ot correctly configure bgp sessions and separate nodes by specific pod network

## Your Environment
kubernetes v1.24.6
calico version: v3.23.3
kubespray version 2.20.0

    calico_ipip_mode: 'Never'  
    calico_vxlan_mode: 'Never'
    calico_network_backend: 'bird'

**Comment by caseydavenport** [comment]
>  the given pool (10.239.56.0/21) does not exist, or is not enabled

This seems to be telling the truth. That CIDR isn't one of the two you listed.

What does the CNI config on your host look like? Does it have any IP pools specified?

What about the annotations on the pod - is it requesting this particular IP pool?

**Comment by mgleung** [comment]
Closing this since it seems to have gone stale. Please shout out if we need to reopen this.
