### ISSUE TITLE
Ingress deny preventing access to GCP Metadata Server

### ISSUE THREAD

**Issue by nick-jones** [projectcalico/calico#7458]
Apologies in advance, as I suspect this is very much expected behaviour (or PEBCAK). But my knowledge in this space is somewhat lacking, so I'd appreciate confirmation if that is indeed the case.

I've defined a minimal policy which I believe should allow all egress, and prevent any ingress to a particular namespace:

```yaml
apiVersion: crd.projectcalico.org/v1
kind: NetworkPolicy
metadata:
  name: default
  namespace: test
spec:
  types:
    - Egress
    - Ingress
  egress:
    - action: Allow
  ingress:
    - action: Deny
```

I can egress out as expected:

```
/ # curl http://httpstat.us/200
200 OK
```

However, attempting to curl the [VM Metadata Server](https://cloud.google.com/compute/docs/metadata/overview) relating to the node that is running the pod I'm testing on hangs:

```
/ # curl --verbose -m 10 http://169.254.169.254
*   Trying 169.254.169.254:80...
* Connection timed out after 10000 milliseconds
* Closing connection 0
curl: (28) Connection timed out after 10000 milliseconds
/ # 
```

If I modify the network policy to _allow_ ingress, this works as expected;

```diff
diff --git a/netpol.yaml b/netpol.yaml
index b1b02f8..bb9157c 100644
--- a/netpol.yaml
+++ b/netpol.yaml
@@ -10,4 +10,4 @@ spec:
   egress:
     - action: Allow
   ingress:
-    - action: Deny
+    - action: Allow
```

```
$ kubectl --namespace=test apply -f netpol.yaml
networkpolicy.crd.projectcalico.org/default configured
```

```
/ # curl --verbose -m 10 http://169.254.169.254
*   Trying 169.254.169.254:80...
* Connected to 169.254.169.254 (169.254.169.254) port 80 (#0)
> GET / HTTP/1.1
> Host: 169.254.169.254
> User-Agent: curl/7.88.1
> Accept: */*
> 
< HTTP/1.1 200 OK
< Metadata-Flavor: Google
< Content-Type: application/text
< Date: Sun, 12 Mar 2023 18:50:26 GMT
< Server: Metadata Server for VM
< Content-Length: 17
< X-XSS-Protection: 0
< X-Frame-Options: SAMEORIGIN
< 
computeMetadata/
* Connection #0 to host 169.254.169.254 left intact
```

Watching `iptables-save` I believe this rule is resulting in the traffic being dropped:

```
[17:816] -A cali-pi-test/default -m comment --comment "cali:eF_MkEUljdcnPBCb" -m comment --comment "Policy test/default ingress" -j DROP
```

If I use `action: Log` I see the following type of thing in the system log:

```
Mar 12 18:53:26 gke-cluster-2-default-pool-fe48597f-1w59 kernel: calico-packet: IN=eth0 OUT=calieb336116cde MAC=42:01:0a:80:00:07:42:01:0a:80:00:01:08:00 SRC=169.254.169.254 DST=10.44.0.5 LEN=48 TOS=0x00 PREC=0x00 TTL=63 ID=0 PROTO=TCP SPT=80 DPT=41010 WINDOW=65535 RES=0x00 ACK SYN URGP=0 
Mar 12 18:53:27 gke-cluster-2-default-pool-fe48597f-1w59 kernel: calico-packet: IN=eth0 OUT=calieb336116cde MAC=42:01:0a:80:00:07:42:01:0a:80:00:01:08:00 SRC=169.254.169.254 DST=10.44.0.5 LEN=48 TOS=0x00 PREC=0x00 TTL=63 ID=0 PROTO=TCP SPT=80 DPT=41010 WINDOW=65535 RES=0x00 ACK SYN URGP=0 
Mar 12 18:53:27 gke-cluster-2-default-pool-fe48597f-1w59 kernel: calico-packet: IN=eth0 OUT=calieb336116cde MAC=42:01:0a:80:00:07:42:01:0a:80:00:01:08:00 SRC=169.254.169.254 DST=10.44.0.5 LEN=48 TOS=0x00 PREC=0x00 TTL=63 ID=0 PROTO=TCP SPT=80 DPT=41010 WINDOW=65535 RES=0x00 ACK SYN URGP=0 
```

## Expected Behavior

As it stands, I _want_ to be able to access the Metadata Server whilst also blocking ingress from other namespaces, etc.

My naive understanding is that curling `169.254.169.254` with an ingress deny type policy should work, since traffic is outward from the pod. I understand that `169.254.169.254` is a link local address, so I suspect this may have implications.

## Current Behavior

Request hangs / traffic is blocked.

## Possible Solution

I can trivially permit _ingress_ from `169.254.169.254` specifically - which seems to work fine. But if this is the solution, it would certainly be helpful for me to understand why this is necessary (so I can leave a comment to that effect :-)

Alternatively there is quite possibly some configuration I've missed!

## Steps to Reproduce (for bugs)

To check this in GKE:

```
$ gcloud container clusters create cluster-2 --enable-network-policy --region=<region>
$ # wait for cluster to be healthy, check calico is up and running:
$ kubectl get nodes -l projectcalico.org/ds-ready=true
NAME                                       STATUS   ROLES    AGE   VERSION
gke-cluster-2-default-pool-fe48597f-1w59   Ready    <none>   52m   v1.24.9-gke.3200
gke-cluster-2-default-pool-fe48597f-75mh   Ready    <none>   52m   v1.24.9-gke.3200
gke-cluster-2-default-pool-fe48597f-bbxl   Ready    <none>   52m   v1.24.9-gke.3200
```

Apply a policy such as:

```yaml
apiVersion: crd.projectcalico.org/v1
kind: NetworkPolicy
metadata:
  name: default
  namespace: test
spec:
  types:
    - Egress
    - Ingress
  egress:
    - action: Allow
  ingress:
    - action: Deny
```

Create a pod, exec a shell, and attempt to curl `169.254.169.254`

## Context

Traffic to the Metadata Server being dropped can cause issues when accessing GCP cloud resources from within GKE. As I understand, it is common to look to _block_ access to the Metadata Server for various security associated reasons, but we have certain things relying on access, so at least for now we cannot block traffic.

## Your Environment

* Calico version: v3.23.5
* Orchestrator version (e.g. kubernetes, mesos, rkt): kubernetes
* Operating System and version: Google Container-Optimized OS / `Linux gke-cluster-2-default-pool-fe48597f-1w59 5.10.161+ #1 SMP Thu Jan 5 22:49:42 UTC 2023 x86_64 AMD EPYC 7B12 AuthenticAMD GNU/Linux`
* Link to your project (optional):

**Comment by caseydavenport** [comment]
Interesting. I don't recall specifically how the GCP metadata IP address works, but what you're describing sounds like it might be bypassing `conntrack` for some reason. 

Calico's policy works on connections - when a pod initiates a connection, normally a conntrack entry is created which allows the response traffic back regardless of the ingress policy. However, if there is an exception on the host for a certain IP, it might be bypassing that behavior, in which case your ingress rules would need to explicitly allow the return traffic.

I'd check the rules on your host for the metadata IP and see if there are any that include `NOTRACK` to skip conntracking. That might explain it.

**Comment by nick-jones** [comment]
Many thanks for the explanation. It looks like your suspicion is correct. I've created a GKE cluster without calico in the mix, and I see the following on the host node:

```
$ sudo iptables -L -n -t raw
Chain PREROUTING (policy ACCEPT)
target     prot opt source               destination         
CT         tcp  --  169.254.169.254      0.0.0.0/0            tcp spt:80 NOTRACK
CT         tcp  --  0.0.0.0/0            169.254.169.254      tcp dpt:80 NOTRACK
CT         tcp  --  127.0.0.1            0.0.0.0/0            tcp spt:10248 NOTRACK
CT         tcp  --  127.0.0.1            0.0.0.0/0            tcp dpt:10248 NOTRACK

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination         
CT         tcp  --  0.0.0.0/0            169.254.169.254      tcp dpt:80 NOTRACK
CT         tcp  --  0.0.0.0/0            127.0.0.1            tcp dpt:10248 NOTRACK
CT         tcp  --  0.0.0.0/0            127.0.0.1            tcp spt:10248 NOTRACK
```

So I guess they're added when the node is provisioned by Google. (I've confirmed they are present when a GKE cluster is created with calico enabled.)
