### ISSUE TITLE
calico node readiness prob failed after setting gnp

### ISSUE THREAD

**Issue by mak241265** [projectcalico/calico#7459]
Hello everyone..
I have 2 node kubernetes cluster (one master and one worker) iam trying to use heps and gnp to protect my nodes instead of using ufw..i follow the calico official documents and create heps by paching kubecontrollersconfiguration and then i deleted the default profile(projectcalico-default-allow) on heps because in doc it is said the profiles are deprecated and i also need to have fully controlled on my nodes...
after removing the profiles i started to create the gnp..i follow the below link:
https://docs.tigera.io/calico/3.25/network-policy/hosts/kubernetes-nodes

so i created two gnps named ingress-k8s-masters,ingress-k8s-workers after that i saw that calico node and typha started to fail on readiness...i think more rules need to be set on gnp,,am i right??
please consider all pods on all namespaces were ready and running before setting gnp
 
one thing that keep my mind busy is what is the purpose of projectcalico-default-allow profiles when there is failsafe inbout/outbound...as far as i understood projectcalico-default-allow profiles set inbound/outbound for any traffic which does not make any sense

## Current Behavior

calico-system      calico-node-9gfwg                          0/1     CrashLoopBackOff

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Calico version v3.25.0
* Orchestrator version (e.g. kubernetes, mesos, rkt):  v1.26.1
* Operating System and version: ubuntu 22.04
* Link to your project (optional):

**Comment by sridhartigera** [comment]
@mak241265 Any chance the nodes have source-dest check enabled?

**Comment by mgleung** [comment]
It looks like this issue has gone stale so I'm going to close this. If anyone wants to still discuss about this issue, please shout out and we can reopen it.
