### ISSUE TITLE
Clarification on Kubernetes 1.25 Upgrade

### ISSUE THREAD

**Issue by cmukai-cisco** [projectcalico/calico#7470]
## Expected Behavior

I have currently deployed Calico 3.22.0 using Helm on a Kubernetes cluster running version 1.24. I want to upgrade my cluster to 1.25. Prior to upgrading Kubernetes I updated Calico to version 3.25.0. I am expecting all Calico PSPs to be removed.

## Current Behavior

I see two Calico PSPs, calico-node and calico-typha.

## Possible Solution

Am I supposed to upgrade Kubernetes to 1.25 before upgrading Calico? Can I just delete the PSPs and RBAC after upgrading to Kubernetes 1.25?

## Steps to Reproduce (for bugs)

1. Create a Kubernetes 1.24 cluster.
2. Deploy Calico 3.22.0.
3. Upgrade Calico to 3.25.0.

## Context

Some guidance for upgrading to Kubernetes 1.25 would be helpful.

## Your Environment

* Calico version 3.25
* Orchestrator version (e.g. kubernetes, mesos, rkt): Kubernetes 1.24
* Operating System and version: Amazon Linux 2 (kernel: Linux 5.10.165-143.735.amzn2.x86_64)
* Link to your project (optional):

**Comment by MichalFupso** [comment]
Hi @cmukai-cisco, when you update Kubernetes from version 1.24 to version 1.25 the operator will pick that up and remove the PSPs automatically.

**Comment by cmukai-cisco** [comment]
So far in my upgrade testing I have discovered that once 1.25 is installed any PSPs left behind cannot be deleted because the API is gone. Because of this I tried to delete all PSPs prior to upgrading. Since I installed everything using Helm I tried to uninstall Calico prior to upgrading the cluster and then reinstalling it after the upgrade. When I did this the calico-kube-controllers pod was hung in the terminating state. I had to force deletion of the pod and manually delete the container on the host. I then upgraded the cluster and then installed Calico 3.25.0. I noticed that the calico-kube-controllers deployment was not present. I tested the cluster by deploying a few Spark jobs and everything seems to be working. Is calico-kube-controllers no longer present in 3.25.0? If it is supposed to be deployed then why does my cluster appear to be working?

**Comment by caseydavenport** [comment]
The operator will install PSPs so long as the Kubernetes API server it is talking to supports PSPs. It also configures pod security standards annotations on the namespaces it creates.

It will never delete them, because any API server that is missing the PSP API will simply fail any requests to attempt a PSP (since it doesn't even know what PSPs are at that point).

**Comment by brianrowlett** [comment]
Is it possible to upgrade without uninstalling Calico?
Can I just delete the pod security policies prior to upgrading to Kubernetes 1.25 and they will not be recreated?

Calico version: 3.25.1
Orchestrator version (e.g. kubernetes, mesos, rkt): EKS 1.24
Operating System and version: Amazon Linux 2 (5.10.167-147.601.amzn2.x86_64)

**Comment by caseydavenport** [comment]
> Can I just delete the pod security policies prior to upgrading to Kubernetes 1.25 and they will not be recreated?

If you upgrade, the PSPs should be removed automatically be the uplevel version of Kubernetes doesn't support them, no?

You shouldn't need to uninstall Calico.

**Comment by cmukai-cisco** [comment]
Based on my testing I observed that while I am on version 1.24 the tigera-operator will recreate calico PSPs immediately after I delete them. Once I upgrade to 1.25 the PSP API is no longer available so they "disappear". I assume that what is happening is that the PSP records in etcd are left behind and are no longer accessible since the API is gone.

**Comment by EnriqueHormilla** [comment]
Just for add info about the process:


I updated my EKS cluster **from 1.24 to 1.25.** 
After update the controlPlane, tigera-operator still try to find _PodSecurityPolicy_ objets and throw errors like these:
```
{"level":"info","ts":16817291.05884,"logger":"controller_installation","msg":"Failed to update object.","Name":"calico-typha","Namespace":"","Kind":"PodSecurityPolicy","key":"/calico-typha"}
{"level":"error","ts":168241.0588584,"logger":"controller_installation","msg":"Error creating / updating resource","Request.Namespace":"","Request.Name":"default","reason":"ResourceUpdateError","error":"the server could not find the requested resource","stacktrace":"github.com/tigera/operator/pkg/controller/status.(*statusManager).SetDegraded\n\t/go/src/github.com/tigera/operator/pkg/controller/status/status.go:406\ngithub.com/tigera/operator/pkg/controller/installation.(*ReconcileInstallation).Reconcile\n\t/go/src/github.com/tigera/operator/pkg/controller/installation/core_controller.go:1358\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.0/pkg/internal/controller/controller.go:121\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.0/pkg/internal/controller/controller.go:320\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.0/pkg/internal/controller/controller.go:273\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.0/pkg/internal/controller/controller.go:234"}
```

But after the upgrade node groups, tigera operator detected the change and know that in the cluster can´t use  PodSecurityPolicies:
```
{"level":"info","ts":1682417867.9316103,"logger":"setup","msg":"Checking if PodSecurityPolicies are supported by the cluster","supported":false}
```

In my case everything works as expected.

**Comment by caseydavenport** [comment]
@EnriqueHormilla thanks for reporting back! Glad to hear everything worked out.
