### ISSUE TITLE
The calico-node is in the CrashLoopBackOff state

### ISSUE THREAD

**Issue by helloxubo** [projectcalico/calico#7474]
k8s version : 1.26.2
calico version: v3.25.0

![图片](https://user-images.githubusercontent.com/38270190/225827543-f519fbb0-429e-449b-9cc6-fc6ea9aa7934.png)
![图片](https://user-images.githubusercontent.com/38270190/225829288-cce2d374-b1fd-4004-9eb3-8cf2aade6782.png)

kube-apiserver logs
`{
  "kind": "Event",
  "apiVersion": "audit.k8s.io/v1",
  "level": "RequestResponse",
  "auditID": "16a01547-1f8b-4656-8075-85ff4a2b4f0f",
  "stage": "ResponseStarted",
  "requestURI": "/api/v1/namespaces/kube-system/serviceaccounts/calico-node/token",
  "verb": "create",
  "user": {},
  "sourceIPs": [
    "192.168.14.23"
  ],
  "userAgent": "install/v0.0.0 (linux/amd64) kubernetes/$Format",
  "objectRef": {
    "resource": "serviceaccounts",
    "namespace": "kube-system",
    "name": "calico-node",
    "apiVersion": "v1",
    "subresource": "token"
  },
  "responseStatus": {
    "metadata": {},
    "status": "Failure",
    "message": "Unauthorized",
    "reason": "Unauthorized",
    "code": 401
  },
  "responseObject": {
    "kind": "Status",
    "apiVersion": "v1",
    "metadata": {},
    "status": "Failure",
    "message": "Unauthorized",
    "reason": "Unauthorized",
    "code": 401
  },
  "requestReceivedTimestamp": "2023-03-17T06:10:40.036757Z",
  "stageTimestamp": "2023-03-17T06:10:40.037844Z"
}`

Can you help me,thinks!

**Comment by helloxubo** [comment]
I create calico with the file https://github.com/projectcalico/calico/blob/d521de4a1c44076b95769e4781b5577aae4bcc38/manifests/calico.yaml

**Comment by helloxubo** [comment]
@tomastigera Thinks, I have solved it.The problem is caused by the k8s upgrade.

**Comment by helloSuperxu** [comment]
@helloxubo 

Hello, I have encountered the same problem. Could you please tell me how you resolved it? My WeChat and QQ number is 280950204

**Comment by helloSuperxu** [comment]
@helloxubo "I have been solving this problem for a long time, but I still haven't been able to solve it. I hope to receive your reply as soon as possible."

**Comment by helloxubo** [comment]
@helloSuperxu  hello, I have contacted you through wechat.
