### ISSUE TITLE
Docker sunset of free Teams

### ISSUE THREAD

**Issue by DaspawnW** [projectcalico/calico#7478]
As you are maybe already aware https://github.com/docker/hub-feedback/issues/2314 GitHub will sunset free Teams. This change will lead to frozen public images if the owner doesn't apply to the OpenSource Program or buys the Team. (That's at least my interpretation, but as it's currently a manner of hours until this changes it's also not put into stones).

Is there any plan how Calico will handle this? Alternatives could be for example github, google, quay or ecr.

Thank you in advance,
Best regards,
Björn

**Comment by coutinhop** [comment]
@mgleung has checked and Calico was not/will not be affected by the sunset. Closing this, thanks @DaspawnW once again!
