### ISSUE TITLE
Calico HostEndpoints GlobalNetworkPolicy selector

### ISSUE THREAD

**Issue by kfox1111** [projectcalico/calico#7488]
There doesn't seem to be a way to write a selector in GlobalNetworkPolicy object so that it only targets HostEndpoints rather then both HostEndpoints and WorkloadEndpoints. Is this a lack of feature or just a documentation issue?

**Comment by sridhartigera** [comment]
@kfox1111 you can use labels when creating hostEndPoints and the same labels can be used as selectors in GlobalNetworkPolicy.  Please refer to https://docs.tigera.io/calico/latest/network-policy/hosts/protect-hosts-tutorial
