### ISSUE TITLE
Troubleshoot calico in K8S cluster - Is it possible to upgrade calico in an exisiting K8S cluster?

### ISSUE THREAD

**Issue by eliassal** [projectcalico/calico#7499]
Can you please let me know how can I troubleshoot calico in an exisiting K8S cluster? Also, I need to know if it is possible to upgrade calico in an existing K8S cluster?

## Current Behavior
I have setup a K8S 3-nodes cluster on 3 ubuntu VMs on-prem amd it works fine until I hit ani issue using storage. After debugging and troubleshooting, I was told to check calico config/networking if there is any issue. Can you please tell me how can I do that for calico.

I used, 1 month ago this calico file during setup

https://raw.githubusercontent.com/projectcalico/calico/master/manifests/calico.yaml

## Context
In one of calico pods log in my environment I see from time to time this message:

> error 2023-03-24 13:08:04.803 [INFO][88] confd/watchercache.go 125: Watch error received from Upstream ListRoot="/calico/ipam/v2/host/kubernetes" error=too old resource version: 677 (1772591)

## Your Environment

* Calico version : as indicated above I used https://raw.githubusercontent.com/projectcalico/calico/master/manifests/calico.yaml
* Orchestrator version:  kubernetes 1.26
* Operating System and version: ubuntu 22.04
* Link to your project (optional):all details are at this stackoverflow link   
* https://stackoverflow.com/questions/75815752/unable-to-attach-or-mount-volumes-unmounted-volumes-container-stuck-in-contai

**Comment by mgleung** [comment]
Hey @eliassal , it should be be possible to upgrade Calico in an existing cluster. The issue that you're hitting seems to come from trying to update a really old version of Calico to our most recent version of Calico which might have issues. Do you know what the version of Calico you are trying to upgrade from is?

**Comment by eliassal** [comment]
Hi mgleung, "

> Do you know what the version of Calico you are trying to upgrade from is

", as I said, I used 
`kubectl apply -f https://raw.githubusercontent.com/projectcalico/calico/master/manifests/calico.yaml`
can you please tell me how to discover which version it was?

**Comment by mgleung** [comment]
@eliassal in order to figure out the version you were trying to upgrade from, you'll probably need the manifest that installed the system prior to applying the master manifest.

**Comment by caseydavenport** [comment]
> kubectl apply -f https://raw.githubusercontent.com/projectcalico/calico/master/manifests/calico.yaml

This is the master version, which means it's in-development and is not stable. But also, that's the new version, not the old version.
