### ISSUE TITLE
Need doc to support users upgrading from KDD on 2.1

### ISSUE THREAD

**Issue by lwr20** [projectcalico/calico#750]
Users who have installed according to this doc:
http://docs.projectcalico.org/v2.1/getting-started/kubernetes/installation/hosted/k8s-backend/

Need to continue to be supported when they upgrade to calico 2.2.  

The 2.2 KDD docs have manifests which enable BGP routing and don't mention the scenario from the 2.1 docs, leading to confusion about support.

Options:
- Continue to maintain a policy-only manifest, OR
- Document that the KDD manifest now enables BGP networking by default and include instructions for how to disable it for policy-only

**Comment by tomdee** [comment]
@robbrockbank This is probably related to the other bugs I just assigned you
