### ISSUE TITLE
Missing fix in https://github.com/projectcalico/containernetworking-plugins cause new udp connections to delete conntrack table entries

### ISSUE THREAD

**Issue by MaxFedotov** [projectcalico/calico#7517]
Hello,

we recently found a problem with host port udp connections when using calico - when a new connection arrives, all other connections experience a huge delay. In short, we tracked down this issue to this commit in https://github.com/containernetworking/plugins/pull/705, which is missing in https://github.com/projectcalico/containernetworking-plugins. 

After building a new version of portmap plugin with the provided fix the issue was gone. Is it possible to merge this commit and update https://github.com/projectcalico/containernetworking-plugins?

Thanks.

**Comment by MichalFupso** [comment]
Hi @MaxFedotov, we cherry-picked the change https://github.com/projectcalico/containernetworking-plugins/pull/15. I will go into 3.26 release later this month
