### ISSUE TITLE
Calico v3.25.1: tls: protocol version not supported

### ISSUE THREAD

**Issue by stephan2012** [projectcalico/calico#7520]
Calico v3.25.1 calico-kube-controllers fails with TLS error which did not show with v3.25.0. Our Kubernetes API servers are configured to serve TLS v1.3 only.

Reverting to v3.25.0 brings the Pod network back, i.e., `calico-kube-controllers` and `calico-node` start as expected.

## Expected Behavior

v3.25.1 should work just as v3.25.0.

## Current Behavior

Logs:

```text
2023-03-31 14:04:24.468 [INFO][1] main.go 107: Loaded configuration from environment config=&config.Config{LogLevel:"info", WorkloadEndpointWorkers:1, ProfileWorkers:1, PolicyWorkers:1, NodeWorkers:1, Kubeconfig:"", DatastoreType:"kubernetes"}
W0331 14:04:24.470238       1 client_config.go:617] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
2023-03-31 14:04:24.470 [INFO][1] main.go 131: Ensuring Calico datastore is initialized
2023-03-31 14:04:24.472 [ERROR][1] client.go 290: Error getting cluster information config ClusterInformation="default" error=Get "https://172.31.0.1:443/apis/crd.projectcalico.org/v1/clusterinformations/default": remote error: tls: protocol version not supported
2023-03-31 14:04:24.472 [INFO][1] main.go 138: Failed to initialize datastore error=Get "https://172.31.0.1:443/apis/crd.projectcalico.org/v1/clusterinformations/default": remote error: tls: protocol version not supported
2023-03-31 14:04:29.475 [ERROR][1] client.go 290: Error getting cluster information config ClusterInformation="default" error=Get "https://172.31.0.1:443/apis/crd.projectcalico.org/v1/clusterinformations/default": remote error: tls: protocol version not supported
```

## Possible Solution

Any changes related to TLS, maybe through a dependency?

## Steps to Reproduce (for bugs)

1. Possibly: Disable TLS v1.2 in the control plane
2. Deploy Calico v3.25.1 

Kuberetes API server configuration:

```yaml
spec:
  containers:
  - command:
    - kube-apiserver
    - […]
    - --tls-cipher-suites=TLS_AES_128_GCM_SHA256,TLS_AES_256_GCM_SHA384,TLS_CHACHA20_POLY1305_SHA256
    - --tls-min-version=VersionTLS13
```

## Context

Nothing special. Just a regular bugfix update.

## Your Environment

* Calico version `v3.25.1`
* Orchestrator version (e.g. kubernetes, mesos, rkt): Kubernetes v1.24.12 (`kubeadm`)
* Operating System and version: Ubuntu Server 22.04.2 LTS, Linux kernel 5.19.0-38-generic
* Link to your project (optional):

**Comment by gentoo9ball** [comment]
Is there any update on this issue?

**Comment by itay47** [comment]
I also get this error when I deploy a fresh cluster using kubespray v2.22.1.
if I use tls_min_version: "VersionTLS13" (kubespray configuration) to set the cluster to work with TLS1.3 only, I get this error and deployment stops.
if I use tls_min_version: "VersionTLS12" - all is good.
tried TLS1.3 combination with and without any ciphers - fails with the same error.
TLS1.3 only with the ciphers we chose worked great with calico v3.23.3.

**Comment by Macgregorian** [comment]
Getting the same results with Kubespray v2.22.1 and TLS1.3

**Comment by cstisa** [comment]
Hello all,

I have the same issue

Any updates on this ? 

Best Regards

**Comment by iaacautomation** [comment]
Same error when upgrading to v2.24.0 using minimum TLSversion1.3

**Comment by caseydavenport** [comment]
I'm told this is related to the version of Golang that we've compiled these versions with and that it should be resolved in an upcoming release.

**Comment by sridhartigera** [comment]
TLS 1.3 is supported from v3.25.2. In 3.25.1, we were building a single image which is FIPS complaint resulting in an error when using TLS 1.3. Starting v3.25.2, we are building separate images for FIPS and non-FIPS. Hence TLS 1.3 is supported on non-FIPS installs. @stephan2012 can you try v3.25.2 or the latest calico(v3.27.0) and let us know how it goes?

**Comment by stephan2012** [comment]
> TLS 1.3 is supported from v3.25.2. In 3.25.1, we were building a single image which is FIPS complaint resulting in an error when using TLS 1.3. Starting v3.25.2, we are building separate images for FIPS and non-FIPS. Hence TLS 1.3 is supported on non-FIPS installs.

I'm curious: Does FIPS compliance disallow TLS v1.3?

> @stephan2012 can you try v3.25.2 or the latest calico(v3.27.0) and let us know how it goes?

Looks like v3.26.4 is good!

**Comment by fasaxc** [comment]
> I'm curious: Does FIPS compliance disallow TLS v1.3?

It did.  When a new TLS version comes out, it has to be approved.

As of start of 2024, FIPS _requires_ support for TLS v1.3.

**Comment by sridhartigera** [comment]
Thanks for confirming. Closing this issue.
