### ISSUE TITLE
Calico version 3.23.2, due to verification issues enabled on the network card

### ISSUE THREAD

**Issue by opencmit2** [projectcalico/calico#7528]
In Calico version 3.23.2, due to the network card enabling verification, PODs on two node nodes in the same network segment cannot communicate with each other.
1. When network card verification is enabled, the PODs of two node nodes cannot communicate normally in the same network segment.
2. Through the packet capture tool, no information was obtained from the vxlan to the local network card.
3. The network card of H3C's server
4. After turning off the network card verification, the following，verything returns to normal ，why??
![image](https://user-images.githubusercontent.com/112474703/229772256-c6604099-56ea-4e00-b064-0e4021a55db3.png)

**Comment by coutinhop** [comment]
@opencmit2 could you share some more details about your issue? What does your cluster look like, can you share the yamls for your IPPools and FelixConfig?
On another note, calico v3.23.2 was released June last year, could you try a more up-to-date release? (The most recent v3.23 patch would be v3.23.5, but I'd recommend moving to a more recent version if you can)

**Comment by WVenus** [comment]
@coutinhop Here is the configuration file for installing CALICO. The listenPort value in BGPConfiguration is 12020, and I'm not sure whether this configuration has an impact.
[calico-3.23.2-ipv6-vxlan.txt](https://github.com/projectcalico/calico/files/11165515/calico-3.23.2-ipv6-vxlan.txt)
[calico-bgpport.txt](https://github.com/projectcalico/calico/files/11165516/calico-bgpport.txt)
[calico-node.txt](https://github.com/projectcalico/calico/files/11165560/calico-node.txt)

**Comment by WVenus** [comment]
apiVersion: crd.projectcalico.org/v1
kind: IPPool
metadata:
  generation: 1
  name: default-ipv4-ippool
spec:
  allowedUses:
  - Workload
  - Tunnel
  blockSize: 26
  cidr: 197.166.0.0/16
  ipipMode: Never
  natOutgoing: true
  nodeSelector: all()
  vxlanMode: Always

**Comment by opencmit2** [comment]
> @opencmit2 could you share some more details about your issue? What does your cluster look like, can you share the yamls for your IPPools and FelixConfig? On another note, calico v3.23.2 was released June last year, could you try a more up-to-date release? (The most recent v3.23 patch would be v3.23.5, but I'd recommend moving to a more recent version if you can)

>
[calico-node.txt](https://github.com/projectcalico/calico/files/11169331/calico-node.txt)
[calico-bgpport (1).txt](https://github.com/projectcalico/calico/files/11169332/calico-bgpport.1.txt)
[calico-bgpport.txt](https://github.com/projectcalico/calico/files/11169333/calico-bgpport.txt)



apiVersion: projectcalico.org/v3
items:
- apiVersion: projectcalico.org/v3
  kind: IPPool
  metadata:
    creationTimestamp: "2023-02-07T02:11:48Z"
    name: default-ipv4-ippool
    resourceVersion: "108793"
    uid: b263cdf2-94b7-4066-abe9-667d4c60b525
  spec:
    allowedUses:
    - Workload
    - Tunnel
    blockSize: 26
    cidr: 197.166.0.0/16
    ipipMode: Never
    natOutgoing: true
    nodeSelector: all()
    vxlanMode: Always
- apiVersion: projectcalico.org/v3
  kind: IPPool
  metadata:
    creationTimestamp: "2023-02-07T02:11:48Z"
    name: default-ipv6-ippool
    resourceVersion: "108796"
    uid: c2982278-47cc-4de4-95fd-6145ed9ec702
  spec:
    allowedUses:
    - Workload
    - Tunnel
    blockSize: 122
    cidr: fdf3:8f2d:d955::/48
    ipipMode: Never
    nodeSelector: all()
    vxlanMode: Never
kind: IPPoolList
metadata:
  resourceVersion: "14608699"

**Comment by opencmit2** [comment]
> @opencmit2 could you share some more details about your issue? What does your cluster look like, can you share the yamls for your IPPools and FelixConfig? On another note, calico v3.23.2 was released June last year, could you try a more up-to-date release? (The most recent v3.23 patch would be v3.23.5, but I'd recommend moving to a more recent version if you can)

@coutinhop 
[calico-node.txt](https://github.com/projectcalico/calico/files/11169360/calico-node.txt)
[calico-bgpport (1).txt](https://github.com/projectcalico/calico/files/11169361/calico-bgpport.1.txt)
[calico-bgpport.txt](https://github.com/projectcalico/calico/files/11169362/calico-bgpport.txt)

`apiVersion: projectcalico.org/v3
items:
- apiVersion: projectcalico.org/v3
  kind: IPPool
  metadata:
    creationTimestamp: "2023-02-07T02:11:48Z"
    name: default-ipv4-ippool
    resourceVersion: "108793"
    uid: b263cdf2-94b7-4066-abe9-667d4c60b525
  spec:
    allowedUses:
    - Workload
    - Tunnel
    blockSize: 26
    cidr: 197.166.0.0/16
    ipipMode: Never
    natOutgoing: true
    nodeSelector: all()
    vxlanMode: Always
- apiVersion: projectcalico.org/v3
  kind: IPPool
  metadata:
    creationTimestamp: "2023-02-07T02:11:48Z"
    name: default-ipv6-ippool
    resourceVersion: "108796"
    uid: c2982278-47cc-4de4-95fd-6145ed9ec702
  spec:
    allowedUses:
    - Workload
    - Tunnel
    blockSize: 122
    cidr: fdf3:8f2d:d955::/48
    ipipMode: Never
    nodeSelector: all()
    vxlanMode: Never
kind: IPPoolList
metadata:
  resourceVersion: "14608699"
`
`apiVersion: projectcalico.org/v3
items:
- apiVersion: projectcalico.org/v3
  kind: FelixConfiguration
  metadata:
    creationTimestamp: "2023-02-07T02:11:48Z"
    name: default
    resourceVersion: "108800"
    uid: 825ef260-7b93-4813-879b-a0165e58780e
  spec:
    bpfLogLevel: ""
    floatingIPs: Disabled
    logSeverityScreen: Info
    reportingInterval: 0s
kind: FelixConfigurationList
metadata:
  resourceVersion: "14608608"`

**Comment by opencmit2** [comment]
@coutinhop 
`apiVersion: projectcalico.org/v3
items:
- apiVersion: projectcalico.org/v3
  kind: IPPool
  metadata:
    creationTimestamp: "2023-02-07T02:11:48Z"
    name: default-ipv4-ippool
    resourceVersion: "108793"
    uid: b263cdf2-94b7-4066-abe9-667d4c60b525
  spec:
    allowedUses:
    - Workload
    - Tunnel
    blockSize: 26
    cidr: 197.166.0.0/16
    ipipMode: Never
    natOutgoing: true
    nodeSelector: all()
    vxlanMode: Always
- apiVersion: projectcalico.org/v3
  kind: IPPool
  metadata:
    creationTimestamp: "2023-02-07T02:11:48Z"
    name: default-ipv6-ippool
    resourceVersion: "108796"
    uid: c2982278-47cc-4de4-95fd-6145ed9ec702
  spec:
    allowedUses:
    - Workload
    - Tunnel
    blockSize: 122
    cidr: fdf3:8f2d:d955::/48
    ipipMode: Never
    nodeSelector: all()
    vxlanMode: Never
kind: IPPoolList
metadata:
  resourceVersion: "14608699"
`
`apiVersion: projectcalico.org/v3
items:
- apiVersion: projectcalico.org/v3
  kind: FelixConfiguration
  metadata:
    creationTimestamp: "2023-02-07T02:11:48Z"
    name: default
    resourceVersion: "108800"
    uid: 825ef260-7b93-4813-879b-a0165e58780e
  spec:
    bpfLogLevel: ""
    floatingIPs: Disabled
    logSeverityScreen: Info
    reportingInterval: 0s
kind: FelixConfigurationList
metadata:
  resourceVersion: "14608608"`

**Comment by coutinhop** [comment]
@opencmit2 IPPools and FelixConfig look fine at a first glance, could you share more info on your setup? (fill out the template, as in, do you use a cloud service or bare metal nodes, what versions of kubernetes, etc)

Could you also share calico-node logs (possibly setting the `logSeverityScreen` to `Debug` in the FelixConfig before doing so)?

**Comment by coutinhop** [comment]
Closing this as inactive, feel free to reopen if you're still facing this issue (please send more info if you do).
