### ISSUE TITLE
Calico pod disk io read bytes is very high

### ISSUE THREAD

**Issue by prometheus-tao** [projectcalico/calico#7539]
The pod calico-node-xxxx disk io read bytes is high 120MB/S  of prometheus metrics a few minutes, Metrics name is container_fs_reads_bytes_total, Then pod readinessProbe healthcheck is failure occur unavaliable trigger alert
## Expected Behavior

disk io read bytes is ~5KB/S
## Current Behavior

disk io read bytes is ~120MB/S
## Possible Solution

auto recovery
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Context

The pod cannot running and ready status a few mintues
## Your Environment

* Calico version v3.13.4
* Orchestrator version (e.g. kubernetes, mesos, rkt): kubernetes v1.18.20
* Operating System and version:  CentOS Linux 7 5.4.210-1.el7.elrepo.x86_64
* Link to your project (optional):

Calico container env list: 

- env:
    - name: CALICO_DISABLE_FILE_LOGGING
      value: "true"
    - name: CALICO_IPV4POOL_CIDR
      value: xx.xx.xx.0/18
    - name: CALICO_IPV4POOL_IPIP
      value: "off"
    - name: CLUSTER_TYPE
      value: k8s,bgp
    - name: DATASTORE_TYPE
      value: kubernetes
    - name: FELIX_DEFAULTENDPOINTTOHOSTACTION
      value: ACCEPT
    - name: FELIX_HEALTHENABLED
      value: "true"
    - name: FELIX_IPINIPENABLED
      value: "false"
    - name: FELIX_IPV6SUPPORT
      value: "false"
    - name: FELIX_LOGSEVERITYSCREEN
      value: info
    - name: IP
      value: autodetect
    - name: WAIT_FOR_DATASTORE
      value: "true"

**Comment by mgleung** [comment]
Hi @prometheus-tao , I noticed that the version that you're using is pretty old and there have been many performance fixes that have gone in since 3.13. Could I ask you to try a newer version of Calico and see if your issue persists?

**Comment by prometheus-tao** [comment]
@mgleung thanks, I try to deploy upgrade newer version on test cluster.

**Comment by prometheus-tao** [comment]
@sridhartigera Not yet, I have something do work recently, I try to it next week. thanks!

**Comment by mgleung** [comment]
@prometheus-tao any updates on this?
