### ISSUE TITLE
After adding new workers, cluster services are not accessible from the new ones, like coredns

### ISSUE THREAD

**Issue by dpeer6** [projectcalico/calico#7545]
Hi,

Before adding new workers, we installed/migrated to calico-typha from calico by applying it's manifest.
We were about to have more worker nodes then 50, as recomeded.

We added new workers to the cluster, without any issues, all daemonsets seemed to loaded just fine, no errors.
When we scheduled PODs on the new added nodes, we saw that they fail to communicate with cluster services, like our "kube-dns" ClusterIP service... but not just... any other services fails to communicated to cluster services & direct POD IP addresses.

## Expected Behavior
On existing nodes, the communication to cluster services/PODs works as expected.

## Current Behavior
On the new nodes, all out tests using "telnet 10.96.0.10 53", nslookup, at the host level and from debug PODs...all fails.
We tested different services with the same results.

We enforced IP_AUTODETECTION_METHOD on the daemonset, with the same results.

## Possible Solution
Not sure, spent more then 2 days to debug at the system/OS level.

## Steps to Reproduce (for bugs)
On-prem Kuberenetes vanilla **1.24.9**
Calico-Typha **3.25.1** replicate count of 3

## Context
Currently, only new worker nodes are effected.

## Your Environment
On-prem **Kuberenetes** vanilla, version: **1.24.9**
Ubuntu **22.04**
Calico-Typha **3.25.1** replicate count of 3

Worker and control plane nodes CIDR:
10.155.2.0/23,10.155.6.0/23

POD CIDR:
10.250.0.0/16

At the problematic node level:
Runing: calicoctl node checksystem:
Checking kernel version...
		5.15.0-69-generic   					OK
Checking kernel modules...
		ipt_ipvs            					OK
		ipt_REJECT          					OK
		xt_rpfilter         					OK
		ipt_set             					OK
		nf_conntrack_netlink					OK
		xt_set              					OK
		ip6_tables          					OK
		ip_tables           					OK
		xt_bpf              					OK
		ipt_rpfilter        					OK
		vfio-pci            					OK
		xt_conntrack        					OK
		xt_icmp             					OK
		xt_icmp6            					OK
		xt_mark             					OK
		xt_u32              					OK
		ip_set              					OK
		xt_addrtype         					OK
		xt_multiport        					OK

calicoctl node status, show that all "node-to-node mesh" are up

What could be the issue or the mis configuration?

Many thanks in advance!

**Comment by dpeer6** [comment]
Some more information:
kubectl get ippools -o yaml
apiVersion: v1
items:
- apiVersion: crd.projectcalico.org/v1
  kind: IPPool
  metadata:
    annotations:
      projectcalico.org/metadata: '{"uid":"ed2d4a91-6e70-47b7-8765-de7fa12a7de1","creationTimestamp":"2023-02-04T21:03:50Z"}'
    creationTimestamp: "2023-02-04T21:03:50Z"
    generation: 1
    name: default-ipv4-ippool
    resourceVersion: "245332292"
    uid: e3134cc1-fa7f-4a6c-bfc6-1f1292702e22
  spec:
    allowedUses:
    - Workload
    - Tunnel
    blockSize: 26
    cidr: 10.250.0.0/16
    ipipMode: Always
    natOutgoing: true
    nodeSelector: all()
    vxlanMode: Never
kind: List
metadata:
  resourceVersion: ""

**Comment by caseydavenport** [comment]
@dpeer6 thanks for the update! There are definitely bugs in checksum offloading that we've seen before in various kernel / NIC combinations.

I'm going to close this for now since I don't think this is a Calico issue, but please do keep it up-to-date if you discover anything new.

**Comment by dpeer6** [comment]
The root cause was the Broadcom firmware, once downgraded, all works as expected.

**Comment by xnum** [comment]
This exactly happened to me and resolved by turning off all offloadings with this command `for if in bond0 enp24s0f0np0 enp24s0f1np1; do ethtool -K $if rx off tx off sg off tso off ufo off gso off gro off lro off; done`

Packets are sent and received as usual and can be captured by tcpdump. So I don't even think it's such a low-level issue.

Our NIC is `Mellanox Technologies MCX4421A-ACQN ConnectX-4 Lx EN OCP,2x25G`

However, after upgrading firmware, the card's 802.3ad function is fucked up.

It's OEM card with a special PSID and not easy to reflash it. So still finding a way to make it perfect.

**Comment by jonahbohlmann** [comment]
@dpeer6 we have the same network card and 100% the same issue.
Do you remember which version you had and which version you downgraded to? That would help us a lot.
