### ISSUE TITLE
How to adjust the 179 port of bird in the Calico service deployed through Helm?

### ISSUE THREAD

**Issue by 46797536** [projectcalico/calico#7551]
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Calico version
* Orchestrator version (e.g. kubernetes, mesos, rkt):
* Operating System and version:
* Link to your project (optional):

**Comment by MichalFupso** [comment]
Hi @46797536, you can change the listenPort described in the BGP documentation https://docs.tigera.io/calico/latest/reference/resources/bgpconfig
