### ISSUE TITLE
Windows quickstart results in failing kubelet

### ISSUE THREAD

**Issue by riverar** [projectcalico/calico#7552]
After running through the Windows [Quickstart documentation](https://docs.tigera.io/calico/latest/getting-started/kubernetes/windows-calico/quickstart), attempting to launch the kubelet results in errors. The quickstart just doesn't seem to work out of the box on Windows.

```
E0413 13:08:10.312301   26404 run.go:74] "command failed" err="failed to parse kubelet flag: unknown flag: --logtostderr"
```

```
E0413 13:04:30.849556   66952 run.go:74] "command failed" err="failed to validate kubelet configuration, error: [invalid configuration: enforceNodeAllocatable (--enforce-node-allocatable) is not supported unless cgroupsPerQOS (--cgroups-per-qos) is set to true, invalid configuration: EnforceNodeAllocatable (--enforce-node-allocatable) [pods] is not supported on Windows], path: &TypeMeta{Kind:,APIVersion:,}"
```

## Expected Behavior
Kubelet to start after performing Quickstart steps.

## Current Behavior
Kubelet doesn't start after performing Quickstart steps.

## Steps to Reproduce (for bugs)
1. `C:\install-calico-windows.ps1 -KubeVersion 1.26.3 -CalicoBackend "vxlan"`
2. Start Kubelet service
3. Observe error(s) in kubelet.err.log

## Context
Attempting to stand up a Windows node to join existing microk8s-based Linux cluster.

## Your Environment
* Calico version: 3.25.1
* Orchestrator version (e.g. kubernetes, mesos, rkt): 1.26.3
* Operating System and version: Windows Server 2022 20348.1668
* Link to your project (optional): N/A

**Comment by Josh-Tigera** [comment]
I know the `--logtostderr` was cleaned up by [this](https://github.com/projectcalico/calico/pull/7294) but I'm not familiar with the other one. Perhaps @coutinhop could chime in if he's ever seen that before.

**Comment by kkbruce** [comment]
```
Invoke-WebRequest https://github.com/projectcalico/calico/releases/download/v3.25.1/install-calico-windows.ps1 -OutFile c:\install-calico-windows.ps1
c:\install-calico-windows.ps1 -KubeVersion 1.26.4
...
C:\CalicoWindows\kubernetes\install-kube-services.ps1
```

In a similar scenario, I used the BGP path, and after executing the script, I could see the Kubelet service constantly restarting. After querying, I obtained the following logs:

```
E0510 09:40:05.213985    3568 run.go:74] "command failed" err="failed to parse kubelet flag: unknown flag: --logtostderr"
Flag --resolv-conf has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Flag --enable-debugging-handlers has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Flag --cluster-dns has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Flag --cluster-domain has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Flag --hairpin-mode has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Flag --cgroups-per-qos has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
```

How can I solve it?

**Comment by davhdavh** [comment]
yes, it is still present in https://docs.tigera.io/calico/3.26/scripts/PrepareNode.ps1
/reopen
