### ISSUE TITLE
calico IP-in-IP tunnel device uses incorrect MTU in GCE

### ISSUE THREAD

**Issue by Symmetric** [projectcalico/calico#756]
Copied over from calico-docker (https://github.com/Metaswitch/calico-docker/issues/415)

The tunl0 device uses MTU 1480 unconditionally. In GCE, the network MTU is 1460, so the correct MTU for the tunl0 device is 1440 in this environment.

With the incorrect value of 1480, packets are dropped after encapsulation, but before being transmitted on the VM's external interface. One might expect the kernel to generate an ICMP "fragmentation required" in this case, but that does not happen.

This issue is exacerbated by the kernel's TSO/GSO function, which can coalesce outbound packets into a single jumbo frame (to be segmented by the NIC) to improve transmission rates. This feature (enabled by default on most kernels, including GCE's Ubuntu and CoreOS images) can cause a burst of small packets (e.g. those produced by a traffic generator) to be glued into a single MTU-sized packet, which since the MTU is incorrect, will also be dropped after encapsulation.

Cheapest fix would be to pick an arbitrary number <= 1440 and use that as the tunl0 MTU in all cases. Could alternatively try to determine the value dynamically by inspecting the interfaces on the machine -- but that could be tricky. pMTU detection is available in the kernel, but this seems to be discouraged for security reasons.

**Comment by fasaxc** [comment]
Fixed by #755
