### ISSUE TITLE
calico-kube-controllers-789dc4c76b-779wx stuck in container creating phase

### ISSUE THREAD

**Issue by NareshChinnusamy** [projectcalico/calico#7581]
## Summary
- I'm trying to set up the Kubernetes k8s cluster manually with Calico as the CNI part.
- I have referred to the Kubernetes official docs for bridge network setup and docker installation and Kubernetes tool setup.
- Then with the help of [Quickstart for Calico on Kubernetes](https://docs.tigera.io/calico/latest/getting-started/kubernetes/quickstart)  I have setup the calico CNI pods under the calico-system namespace.
- The cluster is updated to READY state. But when I look into the particular calico-system  namespace, I have got the following status
 ```bash
calico-kube-controllers-789dc4c76b-779wx   0/1     ContainerCreating   0          15m
calico-node-b2c8b                          1/1     Running             0          15m
calico-typha-549dc6597-jfkpt               1/1     Running             0          15m
csi-node-driver-nmsmx                      0/2     ContainerCreating   0          15m
```
- When I look into **container creating** pods using describe commands, I got these responses below for both the pods.
```bash
Events:
  Type     Reason                  Age                 From               Message
  ----     ------                  ----                ----               -------
  Warning  FailedScheduling        16m                 default-scheduler  0/1 nodes are available: 1 node(s) had untolerated taint {node.kubernetes.io/not-ready: }. preemption: 0/1 nodes are available: 1 Preemption is not helpful for scheduling..
  Normal   Scheduled               16m                 default-scheduler  Successfully assigned calico-system/calico-kube-controllers-789dc4c76b-779wx to kali
  Warning  FailedCreatePodSandBox  16m                 kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "454652cdd673c537f7a88fe5263a84e863658755afaa2ed44834845c33590820": plugin type="calico" failed (add): failed to find plugin "calico" in path [/usr/lib/cni]
  Normal   SandboxChanged          69s (x71 over 16m)  kubelet            Pod sandbox changed, it will be killed and re-created.
```
- But the calico is installed in the **/opt/cni/bin** directory path.

## Expected Behavior
- I expect it to update the status to running format.

## Your Environment
* Calico version: Latest
* Orchestrator version  Kubernetes :v1.27.1
* Operating System and version: Kali Linux
* Running environment: Linode Shared Public VM.

**Comment by gaopeiliang** [comment]
just  about CNI  workdir .....  keep kubelet and calico CNI same ..  

check  kubelet CNI workdir config , 

`/opt/cni/bin`  is default CNI bin workdir

**Comment by NareshChinnusamy** [comment]
I got the Issue fixed and resolved. @gaopeiliang  Thank you for your support.

**Comment by faisalchishtii** [comment]
@NareshChinnusamy Could you please elaborate on how you resolved the issue?

**Comment by NareshChinnusamy** [comment]
When I run the manifest for calico CNI driver setup. The CNI executables
are created inside the /opt/cni/bin/ folder.

But the kubelet service is looking for CNI executables in the /usr/lib/cni
folder. So the calcio pods are still in the container creating phase.

We had to perform the following steps to get them running.

- mkdir -p /usr/lib/cni

- cp -r /opt/cni/bin/* /usr/lib/cni

- systemctl restart kubelet.service

- kubectl get pods -n calico-system - to check all the cni pods are in
running status.
