### ISSUE TITLE
Sporadic errors after applying deny-all NetworkPolicy

### ISSUE THREAD

**Issue by ikyrycho** [projectcalico/calico#7588]
After applying `deny-all-from-other-namespace` NetworkPolicy `kubectl get all` command starts returning errors due to timeout.

## Expected Behavior
NetworkPolicy shouldn't cause timeout issue and resource should be returned instantly (~20 ms) and without retry.

## Current Behavior
On multi-node (2 nodes) clusters, error is returned in `kubectl get all -v6` command:
```
I0425 09:59:57.519260  891760 round_trippers.go:553] GET https://x.y.z.v.sslip.io/k8s/clusters/c-m-j8557b5x/apis/projectcalico.org/v3?timeout=32s 200 OK in 49 milliseconds


I0425 10:00:02.512669  891760 round_trippers.go:553] GET https://x.y.z.v.sslip.io/k8s/clusters/c-m-j8557b5x/apis/subresources.kubevirt.io/v1?timeout=32s 503 Service Unavailable in 5042 milliseconds
I0425 10:00:02.513001  893961 request.go:1188] Response Body: error trying to reach service: context deadline exceeded

I0425 10:00:02.513022  891760 request.go:1387] body was not decodable (unable to check for Status): Object 'Kind' is missing in 'error trying to reach service: context deadline exceeded
'
E0425 10:00:02.513078  891760 memcache.go:287] couldn't get resource list for subresources.kubevirt.io/v1: the server is currently unable to handle the request
I0425 10:00:02.530983  891760 round_trippers.go:553] GET https://x.y.z.v.sslip.io/k8s/clusters/c-m-j8557b5x/apis/subresources.kubevirt.io/v1?timeout=32s 200 OK in 13 milliseconds
I0425 10:00:02.670791  891760 round_trippers.go:553] GET https://x.y.z.v.sslip.io/k8s/clusters/c-m-j8557b5x/api/v1/namespaces/kubevirt/pods?limit=500 200 OK in 19 milliseconds
```

## Steps to Reproduce (for bugs)
1. Install Kubevirt/CDI (https://kubevirt.io/user-guide/operations/installation/)
2. Apply K8s (not Calico's) NetworkPolicy
```
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  namespace: kubevirt
  name: kubevirt-deny-from-other-namespaces
spec:
  podSelector:
    matchLabels:
  ingress:
    - from:
        - podSelector: {}
```
3. Perform `kubectl get all` command after ~1 minute.

## Context
Issue is happening on multinode clusters and couldn't be reproduced on single-node cluster. It is a sporadic issue that has reproducibility rate of ~50% and happens with other dependencies (prometheus/CDI). Issue only appears for resources for which there's a corresponding `NetworkPolicy` is created. Issue is not reproducible if `canal` CNI is used instead of `calico`.

Overall this issue causes API slowdown due to retries and when all retries are used it prevents `kubectl` from showing all resources. 

There are several similar issues that are advising to disable `VXLAN` on calico's interfaces on nodes and add `ChecksumOffloadBroken=true` to `FelixConfiguration`, but none of them helps with issue.

## Your Environment
* Calico version 
Calico operator: docker.io/rancher/mirrored-calico-operator:v1.29.0
Calico: docker.io/rancher/mirrored-calico-kube-controllers:v3.25.0
* Orchestrator version (e.g. kubernetes, mesos, rkt):
Client Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.0", GitCommit:"1b4df30b3cdfeaba6024e81e559a6cd09a089d65", GitTreeState:"clean", BuildDate:"2023-04-11T17:10:18Z", GoVersion:"go1.20.3", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v5.0.1
Server Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.2+rke2r1", GitCommit:"fc04e732bb3e7198d2fa44efa5457c7c6f8c0f5b", GitTreeState:"clean", BuildDate:"2023-03-01T00:08:27Z", GoVersion:"go1.19.6 X:boringcrypto", Compiler:"gc", Platform:"linux/amd64"}
* Operating System and version:
PRETTY_NAME="Ubuntu 22.04.2 LTS"
Kernel: 5.16.0-051600-generic

**Comment by mgleung** [comment]
Hi @ikyrycho , I'm not entirely sure what kubevirt is doing, but is there any other information about your use case that you can share? I wouldn't expect the k8s API to become unreachable if a namespace unrelated to the k8s API is cordoned off, especially since calls from `kubectl` should be directed straight to the k8s API and should not be subject to network policy constraints. What are you using kubevirt for and what is deployed in that namespace in your cluster?

**Comment by ikyrycho** [comment]
Hi, @mgleung as mentioned in bug report - this issue happens not only with kubevirt, but with other apps as well, so it shouldn't be kubevirt-specific issue. Each app is the only application deployed in corresponding namespace.
Kubevirt purpose is to run Virtual Machines on K8s cluster and that's our main use-case, however this issue occurs after deployment and before we ran any kind of VM on cluster.

**Comment by mgleung** [comment]
@ikyrycho sorry, I only mentioned kubevirt because it was mentioned as the resources in your logs that you were trying to reach and as a part of the reproduction steps. Could you also check the network connection between nodes in your cluster? The fact that this does not happen for single node clusters seems to hint at connectivity issues between nodes that may be exacerbated by the restrictions imposed by network policy.

**Comment by ikyrycho** [comment]
@mgleung I don't think that this is connectivity issue - both servers are in same rack and connected to the same switch + issue is reproducible on another cluster in different rack, so it is unlikely that issue is caused by broken hardware.

Quick test of my cluster (ping/traceroute) didn't showed any issues - if you have some tools that you want me to run, let me know.
