### ISSUE TITLE
Configuration of default / initial IPPools in multi-ippool environment is impossible

### ISSUE THREAD

**Issue by Garagoth** [projectcalico/calico#7590]
(Original Slack threads: https://calicousers.slack.com/archives/CPTH1KS00/p1670605688948369?thread_ts=1670603496.145829&cid=CPTH1KS00, https://calicousers.slack.com/archives/CPEPF833L/p1680615833691429)

I am having setup where pod network is different in each of three datacenters.
pooldc1, pooldc2, pooldc3, which are subset of pod network for the cluster.

## Current Behavior
IPPool setup is impossible to make it right in first go.
`kubectl apply` with `Installation.spec.calicoNetwork.ipPools: []` prohibits ANY ip allocation, even when I add my three ippools later using calicoctl.
Leaving ipPools field empty (or non-existant) causes Calico to create default ip pool (with address range equal to kubernetes pod network that was setup using kubeadm, confirmed here: https://calicousers.slack.com/archives/CPEPF833L/p1680617216547649?thread_ts=1680615833.691429&cid=CPEPF833L) which is incorrect and prohibits creation of my pools (overlap issues), in the same time assigning IPs from that pool to all new pods, requiring then to be deleted before pool is deleted. Madness!

Might be similar to #7440 ?

## Expected Behavior
Way to create IPPools in `Installation` together with node selector, and more then one, as Calico permits that later.
Or, make it work when Installation has empty array passed intentionally, refusing to allocate any IPs until proper IPPool resources are created later.

## Possible Solution
See above.

## Your Environment
* Calico version: 3.25.1, initially reported for 3.24.5
* Orchestrator version (e.g. kubernetes, mesos, rkt): Kubernetes 1.25.3
* Operating System and version: Ubuntu 22.04

**Comment by Garagoth** [comment]
Hi, sorry to bother, but is there any solution/progress regarding this? I would really love to get rid of some magic while setting up nodes :-)

**Comment by caseydavenport** [comment]
@Garagoth sorry for not spotting this one!

We have changed the way the tigera/operator works in v3.28 actually. You can now declare multiple IP pools via the Installation object.

I believe you should also be able to now properly set `ipPools: []` and manage your pools via calicoctl as well. 

Please try this out on v3.28 and see if the new logic solves your issues.

**Comment by Garagoth** [comment]
Hi!
Documentation for `Installation.spec.calicoNetwork.ipPools` still says:
> At most one IP pool of each address family may be specified. If omitted, a single pool will be configured if needed.

Documentation error?
I will test this this week (I need to create new cluster, will take a moment) anyway.

**Comment by caseydavenport** [comment]
Yeah, that's a documentation bug for sure. :facepalm:
