### ISSUE TITLE
[windows/cni] calico vxlan mode, no access to external network in pod

### ISSUE THREAD

**Issue by danyang-intel** [projectcalico/calico#7594]
Hi team, 
I am seeking for your support for the windows calico CNI. 
Our on-prem k8s cluster is composed by 2 servers in different subnet, 
1 master : ubuntu18.4 vm
1 worker:  windows 2019 physical host
k8s version: 1.20.2 (We have to stay on this version for some other reason)
calico cni: 3.21 (the latest version supporting k8s 1.20), vxlan mode
calico cni is installed by referring https://docs.tigera.io/archive/v3.21/getting-started/windows-calico/quickstart

## Expected Behavior
The windows pod could access external network

## Current Behavior
1. windows pod could connects pod in same namespace with cluster ip, no matter the destination pod on linux host or windows host. 
The testing mentioned in https://docs.tigera.io/archive/v3.21/getting-started/windows-calico/demo are passed. 
**2. windows pod ping/curl external ip does not works**
PS C:\> curl 10.xxxxx  # host out of k8s cluster
curl : The remote name could not be resolved: 'xxxxx.xxx.com'
At line:1 char:1
+ curl 10.xxxxx
+ ~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebExc
   eption
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand

PS C:\> ping 192.168.226.131   # pod in same namespace on linux node
Pinging 192.168.226.131 with 32 bytes of data:
Reply from 192.168.226.131: bytes=32 time=31ms TTL=63
Reply from 192.168.226.131: bytes=32 time=31ms TTL=63
Ping statistics for 192.168.226.131:
    Packets: Sent = 2, Received = 2, Lost = 0 (0% loss),
Approximate round trip times in milli-seconds:
    Minimum = 31ms, Maximum = 31ms, Average = 31ms

> kubectl get po -n calico-demo -o wide
NAME      READY   STATUS    RESTARTS   AGE   IP                NODE                NOMINATED NODE   READINESS GATES
busybox   1/1     Running   0          24h   192.168.226.131  linuxxxx   <none>           <none>
nginx     1/1     Running   0          24h   192.168.226.130  linuxxxx     <none>           <none>
porter    1/1     Running   0          10h   192.168.6.125     winxxx        <none>           <none>
pwsh      1/1     Running   0          10h   192.168.6.124     winxxx        <none>           <none>

PS C:\> ipconfig /all   #windows pod
Windows IP Configuration
   Host Name . . . . . . . . . . . . : pwsh
   Primary Dns Suffix  . . . . . . . :
   Node Type . . . . . . . . . . . . : Hybrid
   IP Routing Enabled. . . . . . . . : No
   WINS Proxy Enabled. . . . . . . . : No
   DNS Suffix Search List. . . . . . : calico-demo.svc.cluster.local
                                       svc.cluster.local
                                       cluster.local
Ethernet adapter vEthernet (eaacad6229008132087d395068908eeba7a1174db6ee52a3a210ba927a773690_Calico):
   Connection-specific DNS Suffix  . : calico-demo.svc.cluster.local
   Description . . . . . . . . . . . : Hyper-V Virtual Ethernet Adapter #4
   Physical Address. . . . . . . . . : 0E-2A-C0-A8-06-7C
   DHCP Enabled. . . . . . . . . . . : No
   Autoconfiguration Enabled . . . . : Yes
   Link-local IPv6 Address . . . . . : fe80::11bc:c10a:a447:d24a%45(Preferred)
   IPv4 Address. . . . . . . . . . . : 192.168.6.124(Preferred)
   Subnet Mask . . . . . . . . . . . : 255.255.255.192
   Default Gateway . . . . . . . . . : 192.168.6.65
   DNS Servers . . . . . . . . . . . : 10.96.0.10
   NetBIOS over Tcpip. . . . . . . . : Disabled
   Connection-specific DNS Suffix Search List :
                                       calico-demo.svc.cluster.local
                                       svc.cluster.local
                                       cluster.local

PS C:\> ping 192.168.6.65  (gateway)
Pinging 192.168.6.65 with 32 bytes of data:
Request timed out.
Request timed out.
Request timed out.
Ping statistics for 192.168.6.65:
    Packets: Sent = 3, Received = 0, Lost = 3 (100% loss),

**3. pod on linux node could access the same external ip.**

## Steps to Reproduce (for bugs)
1 linux k8s controller node & 1 windows worker in diff subnet
calico CNI, vxlan mode
apiVersion: projectcalico.org/v3
items:
- apiVersion: projectcalico.org/v3
  kind: IPPool
  metadata:
    name: default-ipv4-ippool
  spec:
    allowedUses:
    - Workload
    - Tunnel
    blockSize: 26
    cidr: 192.168.0.0/16
    ipipMode: Never
    natOutgoing: true
    nodeSelector: all()
    vxlanMode: Always
kind: IPPoolList

## Your Environment
Calico CNI config is the default one.

There might be some clues:
1. windows pod cannot access its gateway and I see the warning in felix log
2023-04-24 18:56:16.988 [WARNING][18804] felix/l3_route_resolver.go 583: Unable to create route for IP; the node it belongs to was not recorded in IPAM IP=192.168.6.64
2023-04-24 18:56:16.988 [WARNING][18804] felix/l3_route_resolver.go 583: Unable to create route for IP; the node it belongs to was not recorded in IPAM IP=192.168.6.65
2023-04-24 18:56:16.988 [INFO][18804] felix/watchersyncer.go 209: Received InSync event from one of the watcher caches
2023-04-24 18:56:16.988 [WARNING][18804] felix/l3_route_resolver.go 583: Unable to create route for IP; the node it belongs to was not recorded in IPAM IP=192.168.6.66
2023-04-24 18:56:16.988 [WARNING][18804] felix/l3_route_resolver.go 583: Unable to create route for IP; the node it belongs to was not recorded in IPAM IP=192.168.6.127

2. kube-proxy loops, but I saw this mentioned in other windows CNI related issues and it happens even when the network works. 

3. anything wrong with connection to kubedns/coredns?
coredns-74ff55c5b-7tlpc                     1/1     Running   0          40d   **10.244.7.2**      linuxxxxx   <none>           <none>
coredns-74ff55c5b-vskns                     1/1     Running   0          40d   10.244.7.3       linuxxxxx      <none>           <none>

PS C:\> Resolve-DnsName -Name kubernetes.default.svc.cluster.local -Server 10.244.7.2    # in windows pod
Resolve-DnsName : kubernetes.default.svc.cluster.local : This operation returned because the timeout period expired
At line:1 char:1
+ Resolve-DnsName -Name kubernetes.default.svc.cluster.local -Server 10 ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationTimeout: (kubernetes.default.svc.cluster.local:String) [Resolve-DnsName], Win32
   Exception
    + FullyQualifiedErrorId : ERROR_TIMEOUT,Microsoft.DnsClient.Commands.ResolveDnsName

**Comment by danyang-intel** [comment]
Logs: 
[calico_logs.zip](https://github.com/projectcalico/calico/files/11328990/calico_logs.zip)
[kubelog.zip](https://github.com/projectcalico/calico/files/11328991/kubelog.zip)

**Comment by coutinhop** [comment]
Hi @danyang-intel, could you provide some more info? You say you're using Windows Server 2019, what's the specific build number, could you tell us? Also, would it be possible to try using a more recent version of Calico (and consequently kubernetes as well)? Finally, the logs you posted don't show anything wrong, could you post any NetworkPolicies (and/or GlobalNetworkPolicies) you may have?

**Comment by danyang-intel** [comment]
@coutinhop , Thanks for your help and time.
The is the echo to your questions
1. windows version meets Calico's requirement
> [System.Environment]::OSVersion.Version
Major  Minor  Build  Revision
-----  -----  -----  --------
10     0      17763  0

2. We have to stay on k8s v1.20 because of an feature gate, which is deprecated in later versions.
    And Calico 3.21 is the latest version compatible with k8s v1.20.  
    Do you think latest Calico version support k8s 1.20? If yes, we will try.

3. We don't set any network policy, here is calico's config. It's almost the default one.
{
  "name": "Calico",
  "windows_use_single_network": true,

  "cniVersion": "0.3.1",
  "type": "calico",
  "mode": "vxlan",

  "vxlan_mac_prefix":  "0E-2A",
  "vxlan_vni": 4096,

  "policy": {
    "type": "k8s"
  },

  "log_level": "info",

  "capabilities": {"dns": true},

  "DNS":  {
    "Nameservers":  ["10.96.0.10"],
    "Search":  [
      "svc.cluster.local"
    ]
  },

  "nodename_file": "C:\\CalicoWindows\\libs\\calico\\..\\..\\nodename",

  "datastore_type": "kubernetes",

  "etcd_endpoints": "",
  "etcd_key_file": "",
  "etcd_cert_file": "",
  "etcd_ca_cert_file": "",

  "kubernetes": {
    "kubeconfig": "C:\\CalicoWindows\\calico-kube-config"
  },

  "ipam": {
    "type": "calico-ipam",
    "subnet": "usePodCidr"
  },

  "policies":  [
    {
      "Name":  "EndpointPolicy",
      "Value":  {
        "Type":  "OutBoundNAT",
        "ExceptionList":  [
          "10.96.0.0/12"
        ]
      }
    },
    {
      "Name":  "EndpointPolicy",
      "Value":  {
        "Type":  "ROUTE",
        "DestinationPrefix":  "10.96.0.0/12",
        "NeedEncap":  true
      }
    }
  ]
}

PS, dose calico bgp mode support windows k8s cluster with cross subnet nodes? 
Thank you again.

**Comment by coutinhop** [comment]
Hi @danyang-intel, could you please post the output to `kubectl get felixconfig` (or `calicoctl get felixconfig` if you use `calicoctl`)?

Also, how does `ip route` look on your linux pod, and the equivalent (is it `route print`? I forget now) in your windows pod look?

I'm not sure I fully follow your question 2, when you say 'calico bgp mode', do you mean no encapsulation (as in, VXLAN 'Never')? You will definitely need to configure routes correctly yourself to achieve cross subnet connectivity, but I believe it can work.

**Comment by tomastigera** [comment]
@danyang-intel any update?

**Comment by danyang-intel** [comment]
Hi Pedro and Tomas, 
Thank you for the help and reply. 
Let's archive this since we changed direction and the testing env no longer exists. 
I'll try your suggestion in future if there is chance. Thank you again.

**Comment by nadenf** [comment]
@danyang-intel  .. May want to see if this [issue](https://github.com/projectcalico/calico/issues/7832) is related as I had the same error messages.
