### ISSUE TITLE
Istio integration is broken in Calico v3.25+

### ISSUE THREAD

**Issue by frozenprocess** [projectcalico/calico#7604]
Dikastes requires libresolv.so.2, but it is missing from the image.
```
calico@dev-advocacy:~/calico/app-policy/bin$ ldd dikastes-amd64 
	linux-vdso.so.1 (0x00007ffe486e9000)
	libresolv.so.2 => /lib/x86_64-linux-gnu/libresolv.so.2 (0x00007fb552338000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fb552333000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fb552000000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fb552367000)
```

## Expected Behavior

Dikastes container should run.
## Current Behavior

```
kubectl logs database-5cd7d86449-ql7jx -c dikastes
/dikastes: error while loading shared libraries: libresolv.so.2: cannot open shared object file: No such file or directory
```
## Possible Solution

Adding the library to the image -> https://github.com/projectcalico/calico/pull/7602 https://github.com/projectcalico/calico/pull/7603
## Steps to Reproduce (for bugs)

1. Install calico
2. enable istio
3. deploy a workload

## Context

https://docs.tigera.io/calico/latest/network-policy/istio/enforce-policy-istio <- following this tutorial

## Your Environment

* Calico version v3.25.1
* Orchestrator version (e.g. kubernetes, mesos, rkt): k3s, Kubernetes 1.26.3
* Operating System and version: ubuntu 22.04
* Link to your project (optional):

**Comment by mgleung** [comment]
I think this should be fixed by https://github.com/projectcalico/calico/pull/7602, https://github.com/projectcalico/calico/pull/7617 and https://github.com/projectcalico/calico/pull/7603 so I'm going to close this issue.
