### ISSUE TITLE
Readiness probe failed: calico/node is not ready: BIRD is not ready: Error querying BIRD: unable to connect to BIRDv4 socket: dial unix /var/run/calico/bird.ctl: connect: connection refused

### ISSUE THREAD

**Issue by 664182893** [projectcalico/calico#7614]
When I created a k8s cluster in binary mode and deployed cni through the calico plug-in, I found that Pods could not communicate with each other. Then I went to calico's pod events and found the following
![issue1](https://user-images.githubusercontent.com/59825005/235337295-8a4b6eb0-c57f-4dd2-8345-7d9f109c8df9.png)
  Meanwhile, the configuration of my calico ds is as follows
![issue2](https://user-images.githubusercontent.com/59825005/235337488-299e97c4-0e8e-420c-bac8-dbc87d896dc1.png)
  however,i can't find any useful messages in "calico-node-……" pod;
  I have collected some information to help me locate the problem. Now I find that the docker0 network card of my virtual machine is in down state, and the restart of docker still does not work after deleting the network card.
  How can I solve this problem now? Thanks in advance
## Expected Behavior
My Pods can access each other and this warnning could be solved
## Steps to Reproduce (for bugs)

1. i bulid this k8s cluster in binary mode which is base on https://blog.csdn.net/weixin_49497353/article/details/128900261;
2. calico's yaml ->[calicoyaml.docx](https://github.com/projectcalico/calico/files/11360688/calicoyaml.docx)
3.
4.

## Your Environment
  calico version:3.23.5
  k8s version: 1.21.14

  docker version: 20.10.17
  centos 7.6

**Comment by Josh-Tigera** [comment]
Hi @664182893 I'm unfortunately not able to read Mandarin so I can't look at the blog page you linked, but since it's not our official documentation could you instead try setting up your cluster according to our official documentation at https://docs.tigera.io/calico/latest/about/?

**Comment by yyeexxhhh** [comment]
Use compiled  calico-node of  binary build images , will have the same problem!

**Comment by yyeexxhhh** [comment]
maybe is that issue https://github.com/projectcalico/calico/pull/7556

**Comment by hackerain** [comment]
In my case, this is because the other node's(192.168.0.118) bird is not running, recreating the pod will fix it.

![image](https://github.com/projectcalico/calico/assets/2007096/9d0c6ecb-3dd9-4fb0-831a-05fa7530d701)

**Comment by mazdakn** [comment]
@664182893 can you please try one of our official tutorials (https://docs.tigera.io/) and check if you still have any issue.

**Comment by armaneshaghi** [comment]
I get this error when following official tutorial https://docs.tigera.io/calico/latest/getting-started/kubernetes/self-managed-onprem/onpremises  . I have IP_AUTDETECTION_METHOD='tailscale*'

**Comment by caseydavenport** [comment]
> From inside the calico node, i can see there is an attempt to speak to the wrong interface:

I don't see any evidence in that output that it's attempting to use the wrong address. What makes you think that?

**Comment by sridhartigera** [comment]
Closing this issue. Feel free to reopen if you have more information.
