### ISSUE TITLE
Calico-typha pods always fail to evict while eks upgrade

### ISSUE THREAD

**Issue by mk2134226** [projectcalico/calico#7639]
Eveytime i perform eks upgrade calico-typha pods alwayas fail to evict.
I only use calico for network policy so i dont care even if its down , i found no way to delete PDB  as well
Even if i delete the pod , calico still schedule itself on SchedulingDisabled Node

whats the fix

**Comment by coutinhop** [comment]
@mk2134226 could you provide more info? Versions of what you're using and possibly steps to reproduce your setup and problem would help us try to figure this out...

**Comment by caseydavenport** [comment]
I believe Typha's tolerations are very lenient by default. You might need to adjust the tolerations passed to Typha so that it doesn't get scheduled on nodes that are terminating.

**Comment by AniketK-Crest** [comment]
> You might need to adjust the tolerations passed to Typha so that it doesn't get scheduled on nodes that are terminating.

Can you please describe how?

**Comment by caseydavenport** [comment]
You can configure Typha's tolerations using the Installation API (if you installed with the tigera operator) as referred to here: https://docs.tigera.io/calico/latest/reference/installation/api#operator.tigera.io/v1.TyphaDeployment

It allows overriding the default tolerations (which I believe tolerate all taints IIRC) - you can instead set custom tolerations. For example: https://github.com/projectcalico/calico/issues/8371
