### ISSUE TITLE
calico/kube-controllers:v3.25.1 docker image appears to contain stale binary

### ISSUE THREAD

**Issue by dilyevsky** [projectcalico/calico#7644]
## Expected Behavior / Current Behavior

When testing official 3.25.1 patch release with https://github.com/projectcalico/calico/pull/7503 bugfix we've observed the issue persisted. However our private build made from the same tag 3.25.1 did not exhibit the same issue. I've dug in some more and it appears the binary packaged in `docker.io/calico/kube-controllers:v3.25.1` contains code that I removed in https://github.com/projectcalico/calico/pull/7503:

```shell
> strings usr/bin/kube-controllers |grep OnKubernetesPodDeleted
OnKubernetesPodDeleted
github.com/projectcalico/calico/kube-controllers/pkg/controllers/node.(*ipamController).OnKubernetesPodDeleted
github.com/projectcalico/calico/kube-controllers/pkg/controllers/node.(*ipamController).OnKubernetesPodDeleted

> strings usr/bin/kube-controllers |grep OnKubernetesPodUpdated
OnKubernetesPodUpdated
github.com/projectcalico/calico/kube-controllers/pkg/controllers/node.(*ipamController).OnKubernetesPodUpdated
github.com/projectcalico/calico/kube-controllers/pkg/controllers/node.(*ipamController).OnKubernetesPodUpdated
```

If you look at the changeset https://github.com/projectcalico/calico/pull/7503 these methods are removed and https://github.com/projectcalico/calico/commit/c5750290c174f4d3a97ab19c881f86ab06c948e1 is currently tagged with https://github.com/projectcalico/calico/commits/v3.25.1 but somehow the code still appears in the docker image.

Given the above I'm suspecting something went wrong with the build process. Perhaps the tag was moved after the patch release build completed? cc @caseydavenport 

## Possible Solution

Not really sure. Perhaps rerun the build pipeline and make sure the commands bellow no longer show dead/removed code.

## Steps to Reproduce (for bugs)

```
docker pull docker.io/calico/kube-controllers:v3.25.1
docker save docker.io/calico/kube-controllers:v3.25.1 > controllers:v3.25.1.tar
tar xvf controllers:v3.25.1.tar
tar xvf 02290465887351b0d11d806f4607fa4beb6e71424a2a691cb81f7bc984acef03/layer.tar
strings usr/bin/kube-controllers |grep OnKubernetesPodUpdated
OnKubernetesPodUpdated
github.com/projectcalico/calico/kube-controllers/pkg/controllers/node.(*ipamController).OnKubernetesPodUpdated
github.com/projectcalico/calico/kube-controllers/pkg/controllers/node.(*ipamController).OnKubernetesPodUpdated
# above output shouldn't appear
```

## Your Environment

Linux / amd64

**Comment by caseydavenport** [comment]
@danudey if we haven't already we should make sure the release notes properly call this out (and remove any release notes for commits that got pushed to v3.25.2)
