### ISSUE TITLE
IPIP Tunl0 Ip Can Not Transfer Large Than 1372 Bytes Data In Kubernetes

### ISSUE THREAD

**Issue by fengmingm** [projectcalico/calico#7651]
IPIP Tunl0 Ip Can Not Transfer Large Than 1372 Bytes Data In Kubernetes

## Current Behavior
Recently, I encountered a strange thing: there are multiple nodes in the Kubernetes cluster, node A host and its Pod can not access node B Pod  web API if  return data large than 1372 bytes, but Node A Pod access same replicaset Pods in other nodes is OK， and when node and pod are not in node A, request node B Pod  API are all successfully.

## Context
When checking the network,  ping command  transfer 65507 bytes icmp packet also return < 1ms，telnet pod port is ok.

When access the node B Pod API from node A, returns more than 1372 bytes, the captured packet will display misordering and retransmission.

It is successfully for node A to use ssh to connect node B's tunl0 ip address.  But node B cannot use ssh to connect to node A's tunl0 ip address, Like when the API returns more than 1372 bytes, it will be hanging.

In addition, it is normal for A or B to access and be accessed by other nodes.  calico's mtu reads k8s configmap, so it is globally consistent.

## Your Environment
* Calico version：3.8.5
* Orchestrator version：Kubernetes v17.9
* Operating System and version:  Centos7.6, kernel 4.19.12

**Comment by MichalFupso** [comment]
Hi @fengmingm, Calico v3.8.5 is fairly old now, I would recommend updating to a more recent version of Calico to see if the issue persists as there's been a lot of updates since.

**Comment by gaopeiliang** [comment]
what's value MTU of tunl0,  host out interface and pod veth ?  

Try set an small mtu with container veth (nsenter container;  ip link set mtu vv)

https://github.com/projectcalico/calico/issues/7146  maybe help ...

**Comment by fengmingm** [comment]
THX all, I try to restart calico node 

> what's value MTU of tunl0, host out interface and pod veth ?
> 
> Try set an small mtu with container veth (nsenter container; ip link set mtu vv)
> 
> #7146 maybe help ...

**Comment by fengmingm** [comment]
Thanks all, I tried to restart calico pod and docker services but still had problems. Finally, I restarted host and recovered.
