### ISSUE TITLE
calico does not work with minikube

### ISSUE THREAD

**Issue by amirensit** [projectcalico/calico#7652]
Hello.
I followed this sample to install calico with minikube. It seems it does not work.
[calico minikube tutorial](https://docs.tigera.io/calico/latest/getting-started/kubernetes/minikube).
`kubectl get pods -l k8s-app=calico-node -A` returns this 0/1 running:

`kube-system   calico-node-pz2pf   0/1     Running   1 (15m ago)   57m`

Any idea ?

**Comment by mazdakn** [comment]
@amirensit please fill in the template so we get a better understanding of your issue.
For example, it would be helpful to understand what's going wrong by checking the output of  `describe` command. This is the command:
`kubectl describe pod calico-node-pz2pf -n kubesystem`

**Comment by coutinhop** [comment]
Closing issue as it's inactive since May. Feel free to reopen with more info if you're still facing it.
