### ISSUE TITLE
tigera operator shows "Unable to find kind "PodDistruptionBudgets in Policy/v1" and coredns pods with error" plugin type="calico" failed (add): stat /var/lib/calico/nodename: no such file or directory: check that the calico/node container is running and has mounted /var/lib/calico/"

### ISSUE THREAD

**Issue by SaurabhGIT77** [projectcalico/calico#7655]
Trying to configure Calico as networking provider in a 2 node Kubernetes cluster

Following this: 

https://docs.tigera.io/calico/latest/getting-started/kubernetes/quickstart   (Modifying Few sections like the source of image to be used for the tigera operator "v1.29.0" )

Also modified the CIDR section in the custom resource definition YAML with the one obtained from the network team (Free Subnet)

## Expected Behavior
Calico  Pods should spin up after running the tigera operator.

## Current Behavior
After spinning up the tigera operator using the YAML file  +  using the custom resources YAML with modifying the POD CIDR.

Unable to spin up Calico pods as there are errors on the tigera-operator pod and Coredns pods

Installed "calicoctl"  , "calico" and "calico-ipam" binaries.

Installed the Network CNI and configurations under "/etc/cni/net.d/"

Error on CoreDNS pods:

  Warning  FailedCreatePodSandBox  3m37s (x40876 over 6d4h)  kubelet  (combined from similar events): Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "66f9a2d2e14c2ddc3e9f61fb68a200b8bf59de8ed49435f50b09505658cdb918": plugin type="calico" failed (add): stat /var/lib/calico/nodename: no such file or directory: check that the calico/node container is running and has mounted /var/lib/calico/

Error on Tigera-operator pod:

{"level":"error","ts":1684167211.0066028,"logger":"controller_installation","msg":"Error creating / updating resource","Request.Namespace":"","Request.Name":"default","reason":"ResourceUpdateError","error":"no matches for kind \"PodDisruptionBudget\" in version \"policy/v1\"","stacktrace":"github.com/tigera/operator/pkg/controller/status.(*statusManager).SetDegraded\n\t/go/src/github.com/tigera/operator/pkg/controller/status/status.go:406\ngithub.com/tigera/operator/pkg/controller/installation.(*ReconcileInstallation).Reconcile\n\t/go/src/github.com/tigera/operator/pkg/controller/installation/core_controller.go:1348\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.0/pkg/internal/controller/controller.go:121\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.0/pkg/internal/controller/controller.go:320\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.0/pkg/internal/controller/controller.go:273\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.0/pkg/internal/controller/controller.go:234"}
{"level":"error","ts":1684167211.0067344,"msg":"Reconciler error","controller":"tigera-installation-controller","object":{"name":"default"},"namespace":"","name":"default","reconcileID":"6fb5e655-56b0-4aaf-8a2c-c6a3a3621888","error":"no matches for kind \"PodDisruptionBudget\" in version \"policy/v1\"","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.0/pkg/internal/controller/controller.go:326\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.0/pkg/internal/controller/controller.go:273\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.0/pkg/internal/controller/controller.go:234"}

## Possible Solution

Kubernetes Version used:   v1.20
Tigera-operator:  v1.29.0
Containerd:  containerd.io 1.6.6

tried installing the "PodDisruptionBudget" and "PDB" manually via YAML files under "policy/v1beta1" ----> no luck
When trying to create "PodDisruptionBudget" and "PDB" manually via YAML under "policy/v1" ----> No luck

We have a limitation to use the kubernetes version == v1.20  because of a critical job scheduling tool by IBM as it only supports on version v1.20

So upgrading the kubernetes version is bit far from the only solutions

## Steps to Reproduce (for bugs)

1) Follow the steps from below:
https://docs.tigera.io/calico/latest/getting-started/kubernetes/quickstart
2) modify the below YAML by replacing the image repository to artifactory and using a Registry Secret to pull images

https://raw.githubusercontent.com/projectcalico/calico/v3.25.1/manifests/tigera-operator.yaml

3) Modify CIDR to the one reserved for Pod networking (it does not collide with the base system)

https://raw.githubusercontent.com/projectcalico/calico/v3.25.1/manifests/custom-resources.yaml

## Your Environment
Kubernetes Version used:   v1.20
Tigera-operator:  v1.29.0
Containerd:  containerd.io 1.6.6
OS: Red hat Linux 7.9

I have already provided errors for this, i cannot provide you the link to the project as im facing this issue in my organisation.

Any logs i can try to attach but please do let me know how to overcome this issue.

**Comment by caseydavenport** [comment]
I suspect this is because you're using k8s v1.20. You'll need to downgrade Calico to a version that is compatible with k8s v1.20

**Comment by SaurabhGIT77** [comment]
@caseydavenport 
Will it be possible to know which version can best suit version v1.20
Im unable to find YAMLS for version say example calico v3.16 (ive read that this can best suit with v1.20 of kubernetes)

**Comment by caseydavenport** [comment]
@SaurabhGIT77 the requirements page for each release discusses the ideal versions.

For example, v3.20 supports v1.19->v1.21: https://docs.tigera.io/archive/v3.20/getting-started/kubernetes/requirements#kubernetes-requirements

**Comment by SaurabhGIT77** [comment]
@caseydavenport 
Many Thanks for supporting and your valuable inputs.

probably one last question, its mentioned that “if your host comes with firewalld or other iptables tool it should be disabled to avoid unexpected behavior” 

but i have enabled all the important cluster ports along with calico ports with firewalld itself

How can i overcome this?

also to ask you, the POD CIDR subnet i have chosen again is from my networks team

do i need to take any additional steps with them or acquring a free subnet is enough??


again thanks very much :)

**Comment by SaurabhGIT77** [comment]
@caseydavenport 
The link is very helpfull, i remember i came across this link

but still there are no supporting YAMLs there

because previously calico was installed with “calico.yaml” now in the recent releases we have “tigera-operator”  and “custom-resource”
