### ISSUE TITLE
Network policies only take effect when pods are assigned to the same node

### ISSUE THREAD

**Issue by AbelHugh** [projectcalico/calico#7658]
I configured it according to the network policy demonstrated in the official document, and found that sometimes it takes effect and sometimes it does not. After investigation, I finally found that this example only takes effect when busybox and nginx are assigned to the same node, and it does not take effect if they are not on the same node.

url: https://kubernetes.io/docs/tasks/administer-cluster/declare-network-policy/

As shown in the figure, the first part is completely done according to the demonstration of the official document, just to keep the busybox container without '--rm', which can be seen through the command 'kubectl get pod, node -o wide', the first part busybox and nginx are always on the 'worker-130' node, and the expected result is correct. However, in the second part, I forcibly dispatched nginx to 'worker-131' and immediately lost the connection.

![image](https://github.com/kubernetes/kubernetes/assets/71317399/12d5c07a-ec8a-4f07-b20a-a8c096683d49)

### What did you expect to happen?

Network policies should not only take effect when the test container and the container under test are on the same node.

### How can we reproduce it (as minimally and precisely as possible)?

There are screenshots above

### Kubernetes version

1.24.4

### OS version

Ubuntu 20.04.5

### Install tools

kubeadm

### Container runtime (CRI) and version (if applicable)

runtime: containerd 1.6.16

### Related plugins (CNI, CSI, ...) and versions (if applicable)

cni: calico 3.24.1
IPpool：
![image](https://github.com/projectcalico/calico/assets/71317399/b8eeb169-53fa-46f5-9ef2-409e98eefc08)
![image](https://github.com/projectcalico/calico/assets/71317399/0623028b-ba89-404b-8a1c-31267f41e5e0)

**Comment by coutinhop** [comment]
@AbelHugh I will try to recreate a similar setup and reproduce, but could you send some more details? Do you have any firewall running? Are your nodes bare-metal, or are you using some kind of containers for your setup (e.g. KIND)? Could you share the output of `ip route` on your nodes? Also logs from calico-node pods could be helpful...

Finally, is there a specific reason you need IPIP mode 'CrossSubnet'? Would it be possible to change it to 'Always' and try again?

**Comment by coutinhop** [comment]
We haven't managed to reproduce the issue on our end, closing it as it's inactive since May. Feel free to reopen with more info if you're still facing it.
