### ISSUE TITLE
Windows Pod cannot access elasticsearch url in local network

### ISSUE THREAD

**Issue by Sameer-Italiya** [projectcalico/calico#7660]
On-Premises elasticsearch is running in Ubuntu 18.04 and requires to communication windows pod from the k8s cluster to the local network elasticsearch server.   

**Expected Behavior**
Windows pod to linux pod communication should work
Windows pod to all host communication should work
Windows pod to local network elasticsearch communication should work by default without any services or calico network policy

**Current Behavior**
Windows pod to windows pod communication working
Windows pod to linux pod communication not working
Windows pod to windows host communication not working
Windows pod to local network elasticsearch communication not working

PS C:\inetpub\wwwroot> curl.exe -u elastic:'xxxxxx' -k -XGET https://xx.xxx.xxx.xx:9200/_cluster/health?pretty=true
curl: (28) Failed to connect to xx.xxx.xxx.xx port 9200 after 21034 ms: Couldn't connect to server

**Possible Solution**
If windows pod communicates with the host network then Elasticsearch starts communicating from windows pod

**Steps to Reproduce (for bugs)**

1. Containerd installation in Ubuntu from https://docs.docker.com/engine/install/ubuntu/
2. Kubernetes Installation from https://v1-24.docs.kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/
3. Kubernetes Cluster created from https://v1-24.docs.kubernetes.io/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm/
4. Containerd installation in Windows from https://github.com/containerd/containerd/blob/main/docs/getting-started.md
5. Calico for Linux quickstart from https://docs.tigera.io/calico/latest/getting-started/kubernetes/quickstart
6. Calico for Windows quickstart from https://docs.tigera.io/calico/latest/getting-started/kubernetes/windows-calico/quickstart

**Context**
I want to Windows pod should communicate with other pods of Windows and Linux. Windows pod should communicate with Windows and Linux hosts. Windows pod should communicate with Local Network

**Your Environment**
Kubernetes Version = v1.24.13
One Master Node = Ubuntu 18.04
Two Worker Node = Windows Server 2019 (OS Build 17763.4377)
Containerd = 1.6.21 (Both Ubuntu & Windows)
Calico = v3.25.1 (Both Ubuntu & Windows)

**Comment by Sameer-Italiya** [comment]
vxlan encapsulation is used while setup calico in both Ubuntu and Windows

#kubectl get felixconfig -o yaml
apiVersion: v1
items:
- apiVersion: projectcalico.org/v3
  kind: FelixConfiguration
  metadata:
    creationTimestamp: "2023-05-11T09:54:42Z"
    generation: 1
    name: default
    resourceVersion: "1378"
    uid: fca38bd4-3f81-4c1a-8a85-8ce5b05cd20b
  spec:
    bpfLogLevel: ""
    floatingIPs: Disabled
    healthPort: 9099
    logSeverityScreen: Info
    reportingInterval: 0s
kind: List
metadata:
  resourceVersion: ""

# kubectl get ippool -o yaml
apiVersion: v1
items:
- apiVersion: projectcalico.org/v3
  kind: IPPool
  metadata:
    creationTimestamp: "2023-05-11T10:00:06Z"
    name: default-ipv4-ippool
    resourceVersion: "1376"
    uid: ca687a4e-bc3a-4014-b2ae-95bf81a7fab0
  spec:
    allowedUses:
    - Workload
    - Tunnel
    blockSize: 26
    cidr: 192.168.110.0/24
    ipipMode: Never
    natOutgoing: true
    nodeSelector: all()
    vxlanMode: CrossSubnet
kind: List
metadata:
  resourceVersion: ""

For Windows install follow the manual guide by following quickstart https://docs.tigera.io/calico/latest/getting-started/kubernetes/windows-calico/quickstart

**Comment by coutinhop** [comment]
@Sameer-Italiya sorry for the delay. vxlanMode 'CrossSubnet' is not supported on windows: https://docs.tigera.io/calico/latest/getting-started/kubernetes/windows-calico/limitations

Could you change it to 'Always' and verify if it fixes it?

**Comment by Sameer-Italiya** [comment]
It looks like SNAT not working in the Windows worker node. From the Ubuntu master node SNAT working fine.

**Comment by Sameer-Italiya** [comment]
Does hyper-V require enabling in the windows worker node?

**Comment by Sameer-Italiya** [comment]
@coutinhop can we have an update?

**Comment by coutinhop** [comment]
@Sameer-Italiya how exactly did you proceed when changing the VXLAN encapsulation from 'CrossSubnet' to 'Always'? Did you by any chance not restart (or delete and recreate) pods by any chance? I'm not 100% sure, but I think that may be required. (worst case, it may be needed to restart the windows nodes themselves, or remove them and add them to the cluster)

Could you try those, in case you haven't already? Please let me know how it goes.

**Comment by Sameer-Italiya** [comment]
@coutinhop I have destroy the whole cluster and recreate it. After that while installation of calico in the custom-resource.yml file changed encapsulation to VXLAN.

**Comment by Sameer-Italiya** [comment]
@coutinhop any more information required from your end?

**Comment by coutinhop** [comment]
@Sameer-Italiya how exactly did you install Calico, could you provide more details? Did you follow the quickstart guides?

I'm not sure about Hyper-V, let me defer that to @song-jiang 

(also, could this be related to this issue? https://github.com/projectcalico/calico/issues/6324)

**Comment by Sameer-Italiya** [comment]
@coutinhop 

Yes by following the quickstart guide install the calico

**Comment by coutinhop** [comment]
@Sameer-Italiya so do you still see the issue after starting the cluster from scratch with VXLAN 'Always'?
