### ISSUE TITLE
In the manifest 3.24.6. specified image 3.24.5

### ISSUE THREAD

**Issue by SlavaNosulych** [projectcalico/calico#7667]
Hi guys, can you fix the image tag in the last manifest?
## Expected Behavior
[The last manifest](https://raw.githubusercontent.com/projectcalico/calico/v3.24.6/manifests/apiserver.yaml) should have v3.24.6 image, currently image: calico/apiserver:v3.24.5:
https://raw.githubusercontent.com/projectcalico/calico/v3.24.6/manifests/apiserver.yaml
Thanks

**Comment by caseydavenport** [comment]
I don't think we can modify the live manifest, but we can cut a new release to fix the images properly.

CC @danudey - we should figure out what happened such that this manifest wasn't updated.

**Comment by danudey** [comment]
Hi @SlavaNosulych,

Apologies for this, an issue during our release process caused these files not to be updated before the release was tagged and built.

If you need updated manifests, you can find them in the updated release archive on the releases page: https://github.com/projectcalico/calico/releases/tag/v3.24.6.

**Comment by ClearSeve** [comment]
no wonder
