### ISSUE TITLE
Felix dies if ipset gets too big

### ISSUE THREAD

**Issue by fasaxc** [projectcalico/calico#768]
An ipset can hold many entries (maybe ~65k, by default) but we don't put a limit on how many entries we'll try to put in one.  If the the ipset restore call fails due to the number of entries being exceeded then felix dies with 

```
<snip>
add felix-tmp-v4-prof-000 1.1.68.108
add felix-tmp-v4-prof-000 1.1.68.107
add felix-tmp-v4-prof-000 1.1.68.106
add felix-tmp-v4-prof-000 1.1.68.105
add felix-tmp-v4-prof-000 1.1.68.104
add felix-tmp-v4-prof-000 1.1.68.103
add felix-tmp-v4-prof-000 1.1.68.102
add felix-tmp-v4-prof-000 1.0.50.108
add felix-tmp-v4-prof-000 1.1.68.100
swap felix-v4-prof-000 felix-tmp-v4-prof-000
destroy felix-tmp-v4-prof-000
COMMIT


TrackedAsyncResult ('ipsets.py:100:_update_active_ipset', 'IpsetManager(IPv4) (processing 6a605efe775a)', 'TagIpset(prof-000)', 'replace_members') was leaked with exception FailedSystemCall('ipset', 'restore').  Dying.
```

I'm not sure if the limit can be raised (so that we can dynamically choose to increase it once we're getting close) or if it's a hard limit (in which case we should isolate the failure to the single ipset and log an error).

**Comment by plwhite** [comment]
Each ipset has a maximum size specified when it is created (default 64K on the box I was running on). We can easily enough notice when we are about to exceed this value and rather than exploding increase it. You can't actually increase it dynamically, but you can create a new ipset with a different maximum size then do an atomic swap.

**Comment by fasaxc** [comment]
We could add `call_silent(["ipset", "destroy", self.temp_set_name])` to the start of `replace_members()` and then make sure we create the temp set with an appropriate size before we populate it and swap it into place.
