### ISSUE TITLE
Calico-Node frequent restart due to extended startup time in high BGP peer environment

### ISSUE THREAD

**Issue by pf2rich** [projectcalico/calico#7681]
### Bug Description
In our Kubernetes (k8s) cluster, we have over 2000 BGP peers. This has resulted in a significant increase in startup time for Calico-Node. The issue arises from confd's synchronization of a large amount of data from Typha. Calico-Node waits for the data synchronization to complete before generating the configuration files for Bird. However, the default health check interval for Calico-Node is only around 1 minute, while our Calico-Node takes 3-5 minutes to start under these conditions. Consequently, Calico-Node restarts frequently and fails to start correctly.

### Expected Behavior
We expect to address the extended startup time of Calico-Node in our environment, enabling it to start within a reasonable timeframe without frequent restarts.

### Steps to Reproduce
Deploy Calico-Node in a k8s cluster with over 2000 BGP peers.
Observe the startup time of Calico-Node.
Current Behavior
Calico-Node experiences an extended startup time of 3-5 minutes in our environment due to the synchronization of a large amount of data from Typha. This duration exceeds the default health check interval, resulting in frequent restarts and failed startup attempts.

### Environment Information
Calico version: v3.21.4
Kubernetes version: 1.22
Number of nodes: 1000

### Proposed Solution
We suggest the following possible solutions:

Optimize the data synchronization process between confd and Typha to reduce the synchronization time, thereby reducing Calico-Node's startup time.

**Comment by tomastigera** [comment]
@pf2rich Hi, there were several improvement on these fronts, namely perf improvements of [typha](https://docs.tigera.io/calico/3.25/release-notes/?gclid=CjwKCAjwvdajBhBEEiwAeMh1U1qCUYBPsmrblPbQRvEQouSpDPc-DC_gyXvrFDpIztkpbJ2oNhLy8xoCb3MQAvD_BwE#v3.25.0). Could you try upgrading to 3.25?

**Comment by mazdakn** [comment]
@pf2rich beside @tomastigera's suggestion, you should also switch from Calico BGP mesh topology to route reflectors for a 1000-node cluster.
