### ISSUE TITLE
Vulnerability issues with golang-jwt/v4 and go-restful/v3

### ISSUE THREAD

**Issue by vmwmk** [projectcalico/calico#7702]
github.com/emicklei/go-restful/v3 module prior to v3.10.0 is vulnerable to Authentication Bypass by Primary Weakness. There is an inconsistency in how go-restful parses URL paths. This inconsistency could lead to several security check bypass in a complex system.

github.com/golang-jwt/jwt/v4 module prior to v4.4.3 is vulnerable to Denial of Service (DoS). In case one of the RegisteredClaims params is empty it can lead to panic.

**Comment by mazdakn** [comment]
@Behnam-Shobiri fyi.
I did a quick search, and could not find these modules in our code, but I might be wrong.

**Comment by Behnam-Shobiri** [comment]
Thanks for reporting the vulnerabilities to us @vmwmk. 
I did not find any CVEs for the libraries that you mentioned in [NVD](https://nvd.nist.gov/vuln/search). We can fix/backport the libraries that have CVEs; however, there should be a  CVE ID associated with it (CVE-*). Feel free to let me know if any of the mentioned vulnerabilities have a CVE ID. 

If the mentioned vulnerabilities are from a private database, I would encourage you to ask them or the affected libraries to issue an actual CVE. Also, both mentioned libraries are indirect dependencies and relate to `k8s.io/apiserver`. Therefore, it's K8s that needs to update the libraries (afterward, we can bump the version of K8s libraries) and not Calico.
