### ISSUE TITLE
Same subnet bird route issue

### ISSUE THREAD

**Issue by gongzixiangyuan** [projectcalico/calico#7706]
Hello, all.

All the nodes of the cluster are in the same subnet, why is the next hop of the bird route the gateway instead of the node IP? And, after restarting bird, the routing is normal。

birdv1.6.3

[root@master1 log]# ip r | grep bird
172.18.123.0/26 via **x.x.0.1** dev eth0 proto bird 
172.18.136.0/26 via x.x.0.1 dev eth0 proto bird 
blackhole 172.18.137.64/26 proto bird 
172.18.180.0/26 via x.x.0.1 dev eth0 proto bird 
172.18.215.0/26 via x.x.0.1 dev eth0 proto bird

**Comment by coutinhop** [comment]
Hi @gongzixiangyuan, could you share some more details of your setup (kubernetes version, calico version, type of cluster, number of nodes, network topology)? Also, BGP logs might help if you could post them here (https://docs.tigera.io/calico/latest/operations/troubleshoot/component-logs#configure-bgp-agent-log-level)

Thanks!
