### ISSUE TITLE
BIRD failed to come up and calico-node is stuck in NotReady state

### ISSUE THREAD

**Issue by ajayudayagiri-hpe** [projectcalico/calico#7712]
During a 3-node cluster deployment calico.yaml is ran, calico-node pods are created on all nodes and one replica of calico-kube-controllers pod is created. These pods will take a minute to come up and be Ready. 

However, in one of the deployment we observed calico-node pod is not ready for almost 20 hours. There are no errors in calico-node pod or calico-kube-controllers log, but the pod is in NotReady state because readiness probe is continuously failing.

`Warning  Unhealthy  83s (x1234 over 7h22m)  kubelet  Readiness probe failed: calico/node is not ready: BIRD is not ready: Error querying BIRD: unable to connect to BIRDv4 socket: dial unix /var/run/calico/bird.ctl: connect: resource temporarily unavailable` 

Usually, in these kind of scenarios the Liveness probe is expected to fail which will restart the pod. As liveness is passing in this scenario the pod was stuck at NotReady state for almost 20 hrs after which bird automatically recovered. 

## Expected Behavior
Readiness probe passes once the bird is up and pod goes into Ready state. 
In case bird does not come up or BGP peers are not established successfully, both readiness and liveness probe should fail. 

## Current Behavior
Readiness probe continuously fails as bird failed to come up. But Liveness probe is passing here. 

When the calico-node pod is in NotReady state, the calicoctl node status for the NotReady node shows `Hold Timer Expired` error. Also, any birdcl commands (`birdcl show status`) inside NotReady calico-node pod gives no response while it works on other calico-node pods. This clearly states bird is not up successfully on NotReady node. 

The `strace` of the bird process on the NotReady node shows following result and it is stuck there..

```
user@node3:/admin# strace -p 22213
strace: Process 22213 attached
write(2, "bird: ", 6
```

As per the calico code - The liveness probe check only validates if the bird service is up - [Link](https://github.com/projectcalico/calico/blob/master/node/pkg/health/health.go#L138)
The readiness probe validates BGP peers if they are successfully established - [Link](https://github.com/projectcalico/calico/blob/master/node/pkg/health/health.go#L154)

## Possible Solution
The Liveness check should be robust enough to verify if BGP is successfully established between nodes and should fail in case of issues. 

## Context

The node network got into bad state and deployment of the cluster failed. 

## Your Environment

* Calico version - v3.24.5
* Kubernetes version - v1.22.17
* Operating System and version - Ubuntu 18.04.6 LTS

**Comment by mazdakn** [comment]
@ajayudayagiri-hpe can you also attach the logs from `calico-node` from the node that's failing. It would help to understand what's failing.

**Comment by ajayudayagiri-hpe** [comment]
@mazdakn - We have gone through logs and found no unusual errors/warnings in it. There are no logs available with us to provide as of now, we are trying to reproduce the issue, can provide once issue is identified again.

**Comment by mazdakn** [comment]
Ok, no worries. Let us know when you have more logs.

**Comment by sridhartigera** [comment]
@ajayudayagiri-hpe Did you get a chance to reproduce this issue? If so, can you please send us the logs.
