### ISSUE TITLE
Tigera-operator hostPath

### ISSUE THREAD

**Issue by stepan111** [projectcalico/calico#7719]
Hello, I have calico installed with tigera-operator in my EKS cluster. Operator itself deployed with helm chart. Now we run some security scanners and found that tigera-operator configured with host-path volume. I checked helm chart template and seems there are no way to configure this setting through values.yaml.  Can you please confirm if mounting hostPath into tigera-operator pods is required.
 Thanks

## Your Environment

* Calico version - 3.24.1
* Orchestrator version (e.g. kubernetes, mesos, rkt): EKS 1.23

**Comment by stepan111** [comment]
I understand that Calico Cloud and Calico Opensource are different projects,but still I found this document - https://docs.tigera.io/calico-cloud/operations/comms/pod-security-policy . 
And here it mention that tigera-operator not requires hostPath volume. 

Thanks in advance

**Comment by caseydavenport** [comment]
The tigera-operator reads MTU information populated by calico/node from that hostPath, that is all.

I believe the operator will continue to function without that hostpath, but MTU auto-detection might not work as expected, meaning you may need to explicitly configure your MTU in the `Installation`.

**Comment by stepan111** [comment]
Thanks you @caseydavenport. 
Do you know if can configure hostPath for operator somehow ? 
I checked and it seems that there are no option for this ( here are volume mount - https://github.com/projectcalico/calico/blob/e40707c5d30c353a78bed67a8c6596656b183121/charts/tigera-operator/templates/tigera-operator/02-tigera-operator.yaml#L68 ).  So I would need to clone chart and manage it by myself, right?

**Comment by stepan111** [comment]
Description why it requires hostPath is enough for me right now. @caseydavenport  Thanks for your assistance
