### ISSUE TITLE
Continuous repeated CIDRNotAvailable event for one node in cluster.

### ISSUE THREAD

**Issue by tjf** [projectcalico/calico#7722]
I have a small three-node cluster running k3s and Calico.  I use the BGP peering functionality and it works spectacularly.  Strangely, the last node I added to my cluster is showing a CIDRNotAvailable in the output of 'kubectl describe node' and I can't determine why.

## Expected Behavior
I expect this error to not occur :-)

## Current Behavior
While the node is working fine -- all network functionality, pod scheduling, service routing, etc -- it is constantly logging CIDRNotAvailable events.  I can't find any mention in the k3s logs of any network issues that could be causing this.

```
Events:
  Type    Reason            Age                      From           Message
  ----    ------            ----                     ----           -------
  Normal  CIDRNotAvailable  107s (x1025 over 3d14h)  cidrAllocator  Node node1 status is now: CIDRNotAvailable
```

## Possible Solution
I'd love a pointer for where to look to continue my troubleshooting.

## Your Environment
* Calico version 3.25.1
* Orchestrator version (e.g. kubernetes, mesos, rkt): k3s 1.26
* Operating System and version: Debian 11

**Comment by tjf** [comment]
Hi Casey, thanks for the reply.  I wasn't sure if this was a k3s or a Calico thing, but figured I'd start here.

As this is a k3s cluster, all of the individual daemons are wrapped up together in the k3s binary.  I did verify that all of the nodes are started with the same env vars and other configs, though.  

The odd part is that aside from the error event, everything appears to be working just fine.  

I appreciate your reply -- I'll go check in with the k3s folks now.  Thanks again!

**Comment by caseydavenport** [comment]
Yeah, some networking implementations rely on Kubenretes itself allocating CIDRs to nodes, and so in that case you'd tell Kubernetes the CIDR range to use and it distributes subnets to each node. That's probably what k3s is doing by deafult, and from the sounds of it the range given to the cluster isn't large enough to be subdivided more than into two parts (guessing it's a /25?)

Calico doesn't typically follow this pattern, so generally you'll just turn off CIDR allocation when using Calico (unless for some reason you want Calico to adhere to those allocations, but that's more niche).

**Comment by tjf** [comment]
Nah, cluster CIDR is a /23, with block size of 26, so there's enough to go around.  All 3 nodes have workloads scheduled and running fine on them.

> Calico doesn't typically follow this pattern, so generally you'll just turn off CIDR allocation when using Calico

This is interesting -- maybe I need to disable something that's on by default then?  I do have this resource, for what it's worth.  I'm sure I likely have something misconfigured somewhere, like you said, a wrong netmask or whatever.

```
$ k get ippool default-ipv4-ippool -o yaml
apiVersion: projectcalico.org/v3
kind: IPPool
metadata:
  creationTimestamp: "2023-05-24T00:58:57Z"
  name: default-ipv4-ippool
  resourceVersion: "10250"
  uid: 7e4cb9d3-3fc0-4adc-afdc-2f962625e04d
spec:
  allowedUses:
  - Workload
  - Tunnel
  blockSize: 26
  cidr: 192.168.20.0/23
  ipipMode: Never
  natOutgoing: true
  nodeSelector: all()
  vxlanMode: CrossSubnet

```

**Comment by tjf** [comment]
Hmm, another update -- I just noticed that the affected node (node1) does not have anything listed in the spec.podCIDR of the node resource, and the other 2 show the /24's of that /23 (ie, one has 192.168.20.0/24, the other has 192.168.21.0/24.. both of which would compose the entire /23 block provided to k3s and leave nothing left for node1 (which was the last node created, as unintuitive as that sounds)

I'm starting to think I have conflicting IP assignment technologies going on here -- Calico (or something) is certainly respecting that `blockSize: 26` (or it's a coincidence) as I see /26 routes in the routing table.  However, does kube-controller-manager typically split --cluster-cidr into classful-bounded subnets? (in this case, /24's)

**Comment by tjf** [comment]
Aha, I think I may have it figured out.  According to this comment: https://github.com/k3s-io/k3s/issues/697#issuecomment-576463182..

> There's an extra --node-cidr-mask-size option that can be passed to kube-controller-manager, which defaults to 24. It looks like we can pass this in as--kube-controller-manager-arg=node-cidr-mask-size=22

So this would make sense why it's splitting up my /23 into two /24's and throwing the error (as there isn't another /24 to assign to that node) -- However, from what you're saying above, I should have this disabled at this layer anyway, as Calico is handling it.

**Comment by caseydavenport** [comment]
> anything listed in the spec.podCIDR of the node resource, and the other 2 show the /24's of that /23

Doh, yeah I meant /23 instead of /25, got my directionality wrong! You can only fit two /24s within that /23, so the third node is left hanging. Anyway, sounds like you figured it out!

As for Calico, yeah you can either disable this node CIDR allocation entirely, or you can tweak the numbers so that there's enough room in the CIDR for all of your nodes to get a subnet. Either way doesn't matter - Calico is going to ignore whatever is written into `spec.podCIDR` anyway!
