### ISSUE TITLE
UFW blocks certain packets from Calico

### ISSUE THREAD

**Issue by ausias-armesto** [projectcalico/calico#7727]
While looking at the `ufw` logs I can see that there are certain requests that are being blocked and they belong to Calico. I've tried many ufw rules but cannot manage to get the right one that enables that traffic so it is not shown anymore in the logs.

## Expected Behavior
I would expect not having any blocker in logs. I've tried with many `ufw` rules but I suppose that there is some conflict between Calico rules and the firewall.

## Current Behavior
At the application level I don't appreciate any problem, the apps in Kubernetes are working fine and they don't show any message error, but I don't feel confident seeing some packets being blocked in `ufw`

## Possible Solution
I've been able to configure `ufw` rules step by step until I don't see any other packets blocked, but those packets which come from virtual interfaces starting with `cali` and having and attribute `MARK` cannot be unblocked.

## Your Environment
This is my current setup
- Kubernetes cluster 1.24.6 on metal servers with Debian 10
- Kubernetes distribution is Kubespray with Calico configured to use Iptables
- Calico image version `quay.io/calico/node:v3.23.3`
- Only 1 worker node (`server-01`) has public IP and acts as a NAT gateway while the other worker nodes only have private IPv4
- There are some iptables rules that forward traffic from worker nodes to the `server-01` allowing those worker nodes to have access to internet.
- The worker nodes private IP have the range `10.0.0.0/16`
- The Kubernetes pod subnet range is `10.2.0.0/16`
- The Kubernetes service subnet range is `10.1.0.0/16`
- The ufw firewall configuration is the following

```
root@server-01 /home/debian # ufw status numbered
Status: active

     To                         Action      From
     --                         ------      ----
[ 1] 22/tcp                     ALLOW IN    10.0.0.0/16                (log) # Allow ssh connections from within the subnet
[ 2] 80/tcp                     ALLOW IN    Anywhere                   (log) # Allow external HTTP connections
[ 3] 443/tcp                    ALLOW IN    Anywhere                   (log) # Allow external HTTPS connections
[ 6] Anywhere                   ALLOW FWD   10.0.0.0/16                (log) # Allow forward subnet NATed traffic
[ 7] Anywhere                   ALLOW IN    10.0.0.0/16                (log) # Allow server subnet internal communication
[ 8] Anywhere                   ALLOW IN    10.2.0.0/16/udp            (log) # Allow Kubernetes pods communication through UDP
[ 9] Anywhere                   ALLOW IN    10.2.0.0/16/tcp            (log) # Allow Kubernetes pods communication through TCP
[10] Anywhere                   ALLOW FWD   10.2.0.0/16                (log) # Allow Kubernetes pods forward traffic between subnets
[11] Anywhere on any            ALLOW FWD   10.2.0.0/16 on any         (log) # Allow Kubernetes pods forward traffic between subnets
```
- The ufw logs are these:
```
Jun  1 00:19:40 server-01 kernel: [4939271.395479] [UFW BLOCK] IN=calidca318939f1 OUT= MAC=ee:ee:ee:ee:ee:ee:72:24:e2:58:04:64:08:00 SRC=10.2.173.226 DST=10.1.7.90 LEN=40 TOS=0x00 PREC=0x00 TTL=64 ID=0 DF PROTO=TCP SPT=45126 DPT=3300 WINDOW=0 RES=0x00 RST URGP=0 MARK=0x32240000 
Jun  1 00:19:40 server-01 kernel: [4939271.395910] [UFW BLOCK] IN=calidca318939f1 OUT= MAC=ee:ee:ee:ee:ee:ee:72:24:e2:58:04:64:08:00 SRC=10.2.173.226 DST=10.1.78.204 LEN=40 TOS=0x00 PREC=0x00 TTL=64 ID=0 DF PROTO=TCP SPT=37816 DPT=3300 WINDOW=0 RES=0x00 RST URGP=0 MARK=0x32240000 
Jun  1 00:19:40 server-01 kernel: [4939271.397560] [UFW BLOCK] IN=calidca318939f1 OUT= MAC=ee:ee:ee:ee:ee:ee:72:24:e2:58:04:64:08:00 SRC=10.2.173.226 DST=10.1.7.90 LEN=40 TOS=0x00 PREC=0x00 TTL=64 ID=0 DF PROTO=TCP SPT=45138 DPT=3300 WINDOW=0 RES=0x00 RST URGP=0 MARK=0x32240000 
Jun  1 00:19:41 server-01 kernel: [4939271.813207] [UFW BLOCK] IN=calidca318939f1 OUT= MAC=ee:ee:ee:ee:ee:ee:72:24:e2:58:04:64:08:00 SRC=10.2.173.226 DST=10.1.7.90 LEN=40 TOS=0x00 PREC=0x00 TTL=64 ID=0 DF PROTO=TCP SPT=45202 DPT=3300 WINDOW=0 RES=0x00 RST URGP=0 MARK=0x32240000 
Jun  1 00:19:41 server-01 kernel: [4939271.813539] [UFW BLOCK] IN=calidca318939f1 OUT= MAC=ee:ee:ee:ee:ee:ee:72:24:e2:58:04:64:08:00 SRC=10.2.173.226 DST=10.1.7.90 LEN=40 TOS=0x00 PREC=0x00 TTL=64 ID=0 DF PROTO=TCP SPT=45202 DPT=3300 WINDOW=0 RES=0x00 RST URGP=0 MARK=0x32240000 
Jun  1 00:19:41 server-01 kernel: [4939271.813804] [UFW BLOCK] IN=calidca318939f1 OUT= MAC=ee:ee:ee:ee:ee:ee:72:24:e2:58:04:64:08:00 SRC=10.2.173.226 DST=10.1.78.204 LEN=40 TOS=0x00 PREC=0x00 TTL=64 ID=0 DF PROTO=TCP SPT=37900 DPT=3300 WINDOW=0 RES=0x00 RST URGP=0 MARK=0x32240000 
Jun  1 00:19:41 server-01 kernel: [4939272.533437] [UFW BLOCK] IN=calidca318939f1 OUT= MAC=ee:ee:ee:ee:ee:ee:72:24:e2:58:04:64:08:00 SRC=10.2.173.226 DST=10.1.7.90 LEN=40 TOS=0x00 PREC=0x00 TTL=64 ID=0 DF PROTO=TCP SPT=45412 DPT=3300 WINDOW=0 RES=0x00 RST URGP=0 MARK=0x32240000 

```

**Comment by MichalFupso** [comment]
Hi @ausias-armesto, it might be possible that ufw it conflicting with another tools that set firewall rules. Is the output of `iptables -S -v` as you would expect?

**Comment by ausias-armesto** [comment]
Definitely the issue should be there, a conflict between Calico and UFW Iptables rules. That command (`iptables- S -v`) provides 760 lines, I wouldn't be able to determine if any of those lines is not expected.

**Comment by otto-joe** [comment]
I am also seeing a similar issue where certain pod-to-pod traffic is getting blocked very intermittently. The applications appear to be handling it, but likewise to @ausias-armesto, I'm weary of it.

**Comment by willzhang** [comment]
same here,:
```
root@node1:~# kubectl get nodes -o wide
NAME    STATUS   ROLES           AGE   VERSION    INTERNAL-IP     EXTERNAL-IP   OS-IMAGE             KERNEL-VERSION      CONTAINER-RUNTIME
node1   Ready    control-plane   80m   v1.25.11   192.168.72.40   <none>        Ubuntu 22.04.2 LTS   5.15.0-76-generic   containerd://1.6.23
```
environment:
```
root@node1:~# cat /etc/os-release 
PRETTY_NAME="Ubuntu 22.04.2 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.2 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
root@node1:~# uname -sr
Linux 5.15.0-76-generic
root@node1:~# 
```
i have just one node, but enable ufw dns resolve will failed
```
root@node1:~# ufw status
Status: inactive
root@node1:~# 
root@node1:~# kubectl exec -i -t dnsutils -- nslookup kubernetes.default
Server:         10.96.0.10
Address:        10.96.0.10#53

Name:   kubernetes.default.svc.cluster.local
Address: 10.96.0.1

root@node1:~# 
root@node1:~# 
root@node1:~# ufw enable 
Command may disrupt existing ssh connections. Proceed with operation (y|n)? y
Firewall is active and enabled on system startup
root@node1:~# 
root@node1:~# 
root@node1:~# kubectl exec -i -t dnsutils -- nslookup kubernetes.default
;; connection timed out; no servers could be reached

command terminated with exit code 1
root@node1:~# 
```

**Comment by vincepower** [comment]
> Why can UFW affect the internal traffic communication of Calico on the same node？

All network traffic ultimately passes through the Linux kernel and the iptables rules set in it. So if UFW sets a rule that applies to all traffic then the kernel would respect that.

Calico and UFW are not aware of each other, so they don't coordinate to ensure they don't conflict. That is why Calico recommends host endpoints and other security policies instead of UFW and firewalld.

https://docs.tigera.io/calico/latest/reference/resources/hostendpoint
