### ISSUE TITLE
Quickstart documentation is incorrect

### ISSUE THREAD

**Issue by rbjorklin** [projectcalico/calico#7737]
## Expected Behavior

The quickstart guide provides working instructions.

## Current Behavior

Looking at the [Getting Started guide in the section for kubernetes requirements](https://docs.tigera.io/calico/latest/getting-started/kubernetes/requirements#kubernetes-requirements) it says Calico is tested with k8s 1.24 and newer. In the section immediately after that it says to provide the `--network-plugin=cni` flag to the kubelet however this _cannot_ work as that flag was removed in 1.24 as per: https://github.com/kubernetes/kubernetes/pull/106907

What is the correct way of providing this configuration in a world with k8s 1.24 or newer And with something like containerd?

**Comment by lwr20** [comment]
I think the quickstart doc is correct, and has the exact commands you need in it.https://docs.tigera.io/calico/latest/getting-started/kubernetes/quickstart

**Comment by lwr20** [comment]
@ctauchen A docs bug for you

**Comment by caseydavenport** [comment]
@lwr20 @ctauchen I don't see a linked fix - is this one closeable?

**Comment by ctauchen** [comment]
Fixed with https://github.com/tigera/docs/pull/790
