### ISSUE TITLE
CoreDNS [ERROR] plugin/errors: 2 . Unable to reach internet from inside the pod

### ISSUE THREAD

**Issue by parshva-shah-dsw** [projectcalico/calico#7742]
K8s :- V1.26.1
OS : - RHEL 8.7
VM is hosted using Azure cloud provider.

![image](https://github.com/projectcalico/calico/assets/117802398/4f54287c-3c84-41ca-a7dc-a00891245a4c)

Core dns logs :-
CoreDNS-1.9.3
linux/amd64, go1.18.2, 45b0a11
[ERROR] plugin/errors: 2 2568389657905608835.8295431261288812352. HINFO: read udp 192.168.54.66:34391->168.63.129.16:53: read: no route to host
[ERROR] plugin/errors: 2 2568389657905608835.8295431261288812352. HINFO: read udp 192.168.54.66:34275->168.63.129.16:53: read: no route to host
[ERROR] plugin/errors: 2 2568389657905608835.8295431261288812352. HINFO: read udp 192.168.54.66:59435->168.63.129.16:53: read: no route to host

Unable to reach internet from inside the pod. nslookup fails with below error

<img width="269" alt="image" src="https://github.com/projectcalico/calico/assets/117802398/a9e16b9e-093d-4320-8b2d-6441ffc96694">

**Comment by tomastigera** [comment]
This looks like a configuration issue. Your pod has a private address. Do you have some sort of NAT setup? Do your nodes have public IPs? If yes, you can try to place your DNS pods in a nat-outgoing ippool.

**Comment by DineshRajj** [comment]
> K8s :- V1.26.1 OS : - RHEL 8.7 VM is hosted using Azure cloud provider.
> 
> ![image](https://user-images.githubusercontent.com/117802398/243564304-4f54287c-3c84-41ca-a7dc-a00891245a4c.png)
> 
> Core dns logs :- CoreDNS-1.9.3 linux/amd64, go1.18.2, 45b0a11 [ERROR] plugin/errors: 2 2568389657905608835.8295431261288812352. HINFO: read udp 192.168.54.66:34391->168.63.129.16:53: read: no route to host [ERROR] plugin/errors: 2 2568389657905608835.8295431261288812352. HINFO: read udp 192.168.54.66:34275->168.63.129.16:53: read: no route to host [ERROR] plugin/errors: 2 2568389657905608835.8295431261288812352. HINFO: read udp 192.168.54.66:59435->168.63.129.16:53: read: no route to host
> 
> Unable to reach internet from inside the pod. nslookup fails with below error
> 
> <img alt="image" width="269" src="https://user-images.githubusercontent.com/117802398/243563255-a9e16b9e-093d-4320-8b2d-6441ffc96694.png">

Facing the same issue with RHEL 9 in a VM hosted in VM.  @parshva-shah-dsw  where you able to solve it

**Comment by parshva-shah-dsw** [comment]
@DineshRajj flushing ip tables rules and installing flannel cni worked for us in RHEL 8. not sure with RHEL 9 the same resolution will work or not

**Comment by DineshRajj** [comment]
> @DineshRajj flushing ip tables rules and installing flannel cni worked for us in RHEL 8. not sure with RHEL 9 the same resolution will work or not
Thanks for the reply
Sure will try with flannel.  Please help me with flannel CNI version and also if you have any document to follow you can share here

**Comment by YKI2KOR** [comment]
> @DineshRajj flushing ip tables rules and installing flannel cni worked for us in RHEL 8. not sure with RHEL 9 the same resolution will work or not

@parshva-shah-dsw Could you please help me with deck or reference link to setup custom k8s setup using Azure VMs(RHEL 9).
