### ISSUE TITLE
Calico v3.26.0 failing k8s conformance tests on Azure

### ISSUE THREAD

**Issue by CecileRobertMichon** [projectcalico/calico#7751]
Opened a PR to bump Calico to v3.26.0 in Cluster API Provider Azure after the release came out (https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/3603), however the conformance jobs are failing on the PR (jobs show passed but it actually failed 17 tests, this is a separate issue we're looking into): https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-api-provider-azure/3603/pull-cluster-api-provider-azure-conformance/1664348179514003456

Calico is installed via Helm chart using the Tigera operator.

All the calico pod logs can be found in artifacts:
https://gcsweb.k8s.io/gcs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-api-provider-azure/3603/pull-cluster-api-provider-azure-conformance/1664348179514003456/artifacts/clusters/capz-conf-3k0hpv/calico-apiserver/
https://gcsweb.k8s.io/gcs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-api-provider-azure/3603/pull-cluster-api-provider-azure-conformance/1664348179514003456/artifacts/clusters/capz-conf-3k0hpv/calico-system/
https://gcsweb.k8s.io/gcs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-api-provider-azure/3603/pull-cluster-api-provider-azure-conformance/1664348179514003456/artifacts/clusters/capz-conf-3k0hpv/tigera-operator/

Nothing changed aside from Calico version.

**Comment by caseydavenport** [comment]
From what I can see the errors appear to be due to pods stuck terminating, which suggests something going on with the CNI plugin perhaps. Unfortunately I don't see the CNI plugin logs in that output (nor do I see the `kubectl describe pod` output for the "stuck pods" (which would also potentially shine light onto why it is stuck).

Any possibility of getting that information?

**Comment by CecileRobertMichon** [comment]
@caseydavenport I don't have the describe for the pods that were created as part of conformance unfortunately since they get deleted before the log collection occurs but I do have pod describe logs for all the kube-system pods [here](https://gcsweb.k8s.io/gcs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-api-provider-azure/3603/pull-cluster-api-provider-azure-conformance/1664348179514003456/artifacts/clusters/capz-conf-3k0hpv/kube-system/) and the  [kubelet logs](https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-api-provider-azure/3603/pull-cluster-api-provider-azure-conformance/1664348179514003456/artifacts/clusters/capz-conf-3k0hpv/machines/capz-conf-3k0hpv-md-0-55d48c58fxj99pb-tv977/kubelet.log) for the nodes if that helps.

What do you mean by CNI plugin logs? is that a pod log or on the VM? is it https://[storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-api-provider-azure/3603/pull-cluster-api-provider-azure-conformance/1664348179514003456/artifacts/clusters/capz-conf-3k0hpv/calico-system/calico-node-dwjks/calico-node.log](https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-api-provider-azure/3603/pull-cluster-api-provider-azure-conformance/1664348179514003456/artifacts/clusters/capz-conf-3k0hpv/calico-system/calico-node-dwjks/calico-node.log) ?

**Comment by caseydavenport** [comment]
The CNI plugin logs would be on the host, likely at `/var/log/calico/cni.log`

**Comment by CecileRobertMichon** [comment]
I tried to collect logs from `/var/log/calico/cni.log` however that file is empty on the cluster VMs: https://[storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-api-provider-azure/3603/pull-cluster-api-provider-azure-conformance/1666918655864082432/artifacts/clusters/capz-conf-axvzeg/machines/capz-conf-axvzeg-md-0-6cbb46ff7dx5qgfw-fqhck/cni.log](https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-api-provider-azure/3603/pull-cluster-api-provider-azure-conformance/1666918655864082432/artifacts/clusters/capz-conf-axvzeg/machines/capz-conf-axvzeg-md-0-6cbb46ff7dx5qgfw-fqhck/cni.log)

Which tells me something is probably wrong with CNI plugin? I can try to check a healthy Calico install too to sanity check that this file exists on Azure VMs running Calico CNI. Note that we're using Calico in VXLAN mode if that matters.

**Comment by CecileRobertMichon** [comment]
@caseydavenport @jsturtevant was able to get logs:

- Control plane node: https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-api-provider-azure/3603/pull-cluster-api-provider-azure-conformance/1668292743819956224/artifacts/clusters/capz-conf-bx649b/machines/capz-conf-bx649b-control-plane-sfn8w/cni.log)
- 1st worker node: https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-api-provider-azure/3603/pull-cluster-api-provider-azure-conformance/1668292743819956224/artifacts/clusters/capz-conf-bx649b/machines/capz-conf-bx649b-md-0-5d84cbcb6dxplc8w-9b4h2/cni.log)
- 2nd worker node (empty for some reason): https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-api-provider-azure/3603/pull-cluster-api-provider-azure-conformance/1666918655864082432/artifacts/clusters/capz-conf-axvzeg/machines/capz-conf-axvzeg-md-0-6cbb46ff7dx5qgfw-zs8hb/cni.log)

**Comment by CecileRobertMichon** [comment]
@caseydavenport any thing jump out to you from the logs? not sure where to look next

**Comment by CecileRobertMichon** [comment]
Looking into this a bit more, it seems that the reason conformance tests are failing is because various tests are timing out when waiting for pods to delete. E.g.:

```
{Jun  8 23:23:56.369: Pods left unterminated after stop:
update-demo-nautilus-9slht
update-demo-nautilus-rvp9c
```

I was able repro locally. Created two deployments (using this yaml https://github.com/Azure-Samples/azure-voting-app-redis/blob/master/azure-vote-all-in-one-redis.yaml). I then deleted the deployments:

```
➜  cluster-api-provider-azure git:(calico-v3.26.0) ✗ k get deploy -A
NAMESPACE          NAME                       READY   UP-TO-DATE   AVAILABLE   AGE
calico-apiserver   calico-apiserver           2/2     2            2           11m
calico-system      calico-kube-controllers    1/1     1            1           13m
calico-system      calico-typha               2/2     2            2           13m
default            azure-vote-back            1/1     1            1           3m22s
default            azure-vote-front           1/1     1            1           3m22s
kube-system        cloud-controller-manager   1/1     1            1           13m
kube-system        coredns                    2/2     2            2           13m
kube-system        csi-azuredisk-controller   1/1     1            1           11m
tigera-operator    tigera-operator            1/1     1            1           13m
➜  cluster-api-provider-azure git:(calico-v3.26.0) ✗ k delete deploy azure-vote-back             
deployment.apps "azure-vote-back" deleted
➜  cluster-api-provider-azure git:(calico-v3.26.0) ✗ k delete deploy azure-vote-front                
deployment.apps "azure-vote-front" deleted
➜  cluster-api-provider-azure git:(calico-v3.26.0) ✗ k get deploy -A                 
NAMESPACE          NAME                       READY   UP-TO-DATE   AVAILABLE   AGE
calico-apiserver   calico-apiserver           2/2     2            2           12m
calico-system      calico-kube-controllers    1/1     1            1           13m
calico-system      calico-typha               2/2     2            2           13m
kube-system        cloud-controller-manager   1/1     1            1           13m
kube-system        coredns                    2/2     2            2           14m
kube-system        csi-azuredisk-controller   1/1     1            1           11m
tigera-operator    tigera-operator            1/1     1            1           13m
```

However, the pods never get deleted, and when I try deleting the pods individually, new pods get spun up, even though the deployments no longer exist:

```
➜  cluster-api-provider-azure git:(calico-v3.26.0) ✗ k get pods    
NAME                                READY   STATUS    RESTARTS   AGE
azure-vote-back-7fdc94f44b-nm7t4    1/1     Running   0          29m
azure-vote-front-565bd4fbb5-jrht6   1/1     Running   0          34m
➜  cluster-api-provider-azure git:(calico-v3.26.0) ✗ k delete po azure-vote-back-7fdc94f44b-nm7t4                      
pod "azure-vote-back-7fdc94f44b-nm7t4" deleted
➜  cluster-api-provider-azure git:(calico-v3.26.0) ✗ k get pods                                   
NAME                                READY   STATUS    RESTARTS   AGE
azure-vote-back-7fdc94f44b-r5wmv    1/1     Running   0          3s
azure-vote-front-565bd4fbb5-jrht6   1/1     Running   0          34m
```

This doesn't happen when Calico v3.25 is installed on the cluster but I'm having trouble seeing what Calico has to do with it.

**Comment by AndrewSav** [comment]
@CecileRobertMichon sorry, just a random person here. Deployments manage Replica Sets which manage pods. If there is no Deployment, but when you delete a pod it's span back up, there must be something (such as Replica Set) that does it. Things to check:

- Are you sure that Deployment is gone completely after you deleted it? If you try to list it again is it listed?
- What about Replica Set?
- If there is no Replica Set, examine the Kubernetes Audit Log to see what is creating the new pods when you delete the old ones, for diagnostics purposes

This of course does not answer what Calico has to do with any of this, but hopefully will get us more info to get to the bottom of this.

**Comment by CecileRobertMichon** [comment]
@AndrewSav thanks for the questions/pointers, that was helpful.

I got another repro to answer your questions:

```
➜  cluster-api-provider-azure git:(calico-v3.26.0) k get deploy 
NAME               READY   UP-TO-DATE   AVAILABLE   AGE
azure-vote-back    1/1     1            1           2m12s
azure-vote-front   1/1     1            1           2m12s
➜  cluster-api-provider-azure git:(calico-v3.26.0) k get pods    
NAME                               READY   STATUS    RESTARTS   AGE
azure-vote-back-c5c6d84-8zjxd      1/1     Running   0          2m14s
azure-vote-front-55fc499bf-x78pd   1/1     Running   0          2m14s
➜  cluster-api-provider-azure git:(calico-v3.26.0) k get rs  
NAME                         DESIRED   CURRENT   READY   AGE
azure-vote-back-c5c6d84      1         1         1       2m22s
azure-vote-front-55fc499bf   1         1         1       2m22s
➜  cluster-api-provider-azure git:(calico-v3.26.0) k delete deploy azure-vote-front
deployment.apps "azure-vote-front" deleted
➜  cluster-api-provider-azure git:(calico-v3.26.0) k get deploy                    
NAME              READY   UP-TO-DATE   AVAILABLE   AGE
azure-vote-back   1/1     1            1           2m37s
➜  cluster-api-provider-azure git:(calico-v3.26.0) k get rs      
NAME                         DESIRED   CURRENT   READY   AGE
azure-vote-back-c5c6d84      1         1         1       2m41s
azure-vote-front-55fc499bf   1         1         1       2m41s
➜  cluster-api-provider-azure git:(calico-v3.26.0) k get pods
NAME                               READY   STATUS    RESTARTS   AGE
azure-vote-back-c5c6d84-8zjxd      1/1     Running   0          2m44s
azure-vote-front-55fc499bf-x78pd   1/1     Running   0          2m44s
``` 

> Are you sure that Deployment is gone completely after you deleted it? If you try to list it again is it listed?

Yes

```
k get deploy azure-vote-front  
Error from server (NotFound): deployments.apps "azure-vote-front" not found
``` 

> What about Replica Set?

The replica set still exists. Looks like that's the issue. Why it's not getting deleted when the deployment gets deleted I don't know.

> Check the ownerReferences field of the pod, what is it?

pod is owned by replica set, replica set is owned by deployment that no longer exists.

Pod: 

```
apiVersion: v1
kind: Pod
metadata:
  annotations:
    cni.projectcalico.org/containerID: 95ede545456bf9086e88835b1e65349c66e9b40e691373d393f49b65cf31aed2
    cni.projectcalico.org/podIP: 192.168.118.131/32
    cni.projectcalico.org/podIPs: 192.168.118.131/32
  creationTimestamp: "2023-06-20T15:15:17Z"
  generateName: azure-vote-front-55fc499bf-
  labels:
    app: azure-vote-front
    pod-template-hash: 55fc499bf
  name: azure-vote-front-55fc499bf-x78pd
  namespace: default
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: azure-vote-front-55fc499bf
    uid: 5d9dedd0-09fc-48a4-8a91-711c2c0edeab
  resourceVersion: "1800"
  uid: 67a36a18-cd1b-4c5d-bce2-a7bcc7a300f7
```

Replica Set:
```
apiVersion: apps/v1
  kind: ReplicaSet
  metadata:
    annotations:
      deployment.kubernetes.io/desired-replicas: "1"
      deployment.kubernetes.io/max-replicas: "2"
      deployment.kubernetes.io/revision: "1"
    creationTimestamp: "2023-06-20T15:15:17Z"
    generation: 1
    labels:
      app: azure-vote-front
      pod-template-hash: 55fc499bf
    name: azure-vote-front-55fc499bf
    namespace: default
    ownerReferences:
    - apiVersion: apps/v1
      blockOwnerDeletion: true
      controller: true
      kind: Deployment
      name: azure-vote-front
      uid: 75fc9a13-a51a-4989-9f1e-7ec91d76707b
    resourceVersion: "1816"
    uid: 5d9dedd0-09fc-48a4-8a91-711c2c0edeab
```

Just to confirm, I ran the exact same steps with an identical Azure cluster with Calico 3.25 installed, deleting the deployment triggers the replica set to get deleted as well as expected (and pods get terminated).

**Comment by CecileRobertMichon** [comment]
I think I found the issue

```
I0620 15:32:48.724912       1 shared_informer.go:273] Waiting for caches to sync for garbage collector
E0620 15:33:18.725865       1 shared_informer.go:276] unable to sync caches for garbage collector
E0620 15:33:18.725897       1 garbagecollector.go:250] timed out waiting for dependency graph builder sync during GC sync (attempt 38)
I0620 15:33:18.829609       1 shared_informer.go:273] Waiting for caches to sync for garbage collector
W0620 15:33:41.597907       1 reflector.go:424] vendor/k8s.io/client-go/metadata/metadatainformer/informer.go:90: failed to list *v1.PartialObjectMetadata: connection is unauthorized: bgpfilters.crd.projectcalico.org is forbidden: User "system:serviceaccount:calico-apiserver:calico-apiserver" cannot list resource "bgpfilters" in API group "crd.projectcalico.org" at the cluster scope
E0620 15:33:41.597994       1 reflector.go:140] vendor/k8s.io/client-go/metadata/metadatainformer/informer.go:90: Failed to watch *v1.PartialObjectMetadata: failed to list *v1.PartialObjectMetadata: connection is unauthorized: bgpfilters.crd.projectcalico.org is forbidden: User "system:serviceaccount:calico-apiserver:calico-apiserver" cannot list resource "bgpfilters" in API group "crd.projectcalico.org" at the cluster scope
E0620 15:33:48.830629       1 shared_informer.go:276] unable to sync caches for garbage collector
E0620 15:33:48.830657       1 garbagecollector.go:250] timed out waiting for dependency graph builder sync during GC sync (attempt 39)
```

`bgpfilters.crd.projectcalico.org is forbidden: User "system:serviceaccount:calico-apiserver:calico-apiserver" cannot list resource "bgpfilters" in API group "crd.projectcalico.org" at the cluster scope`

@AndrewSav @caseydavenport

**Comment by AndrewSav** [comment]
Interesting. For one reason or another I did not have the `bgpfilters` CRD after upgrade to 3.26.0, I had to create them manually from the yaml.

**Comment by CecileRobertMichon** [comment]
It might be worth noting I'm using Helm to install Calico v3.26 via the operator on a brand new k8s cluster in the repros above

**Comment by AndrewSav** [comment]
It appears that this bit is controlled by <https://github.com/tigera/operator>. When you have an `APIServer` object, the operator creates [ClusterRole](https://github.com/tigera/operator/blob/v1.30.0/pkg/render/apiserver.go#L539) called `calico-crds` and a [ClusterRoleBinding](https://github.com/tigera/operator/blob/v1.30.0/pkg/render/apiserver.go#L553) called `calico-apiserver-access-calico-crds`. The binding binds the role to [calico-apiserver](https://github.com/tigera/operator/blob/master/pkg/render/apiserver.go#L91) ServiceAccount. Can you check if you have those objects in place?

The role should have [bgpfilters](https://github.com/tigera/operator/blob/v1.30.0/pkg/render/apiserver.go#L1197) in the list, which is intended to allow the access you see denied in the logs.

**Comment by CecileRobertMichon** [comment]
@AndrewSav thank you for all the help here, much appreciated.

I've tested with Calico v3.26.1 and can confirm it fixes the issue.

/close

**Comment by caseydavenport** [comment]
Apologies for my delay here - I've been on PTO for the last two weeks. That said, I'm glad you managed to figure it out! Thanks for the help @AndrewSav!

@CecileRobertMichon - I just wanted to double check - is there any thing that needs to be done on the Calico side for this?

**Comment by AndrewSav** [comment]
@caseydavenport apologies for hijacking unrelated issue, wanted to find out what is the best way to proceed. I'm also having an issue after kubernetes and calico upgrade, and I suspect it is not calico issue, but I'm not sure. What happens, after a node is provisioned if a pod is scheduled on the node before the calico pod initialises the pod get the IP of `127.0.0.1` then when calico does initialise the IP remains `127.0.0.1` and the pod gets stuck. The only way to fix it is to delete the pod.

I'm a bit apprehensive opening an new issue here because I'm not sure if it is calico issue. Since all the components are a newer version, it can be anything. In particular, I suspect it may be cri-o which I'm using as the container runtime. The did changes around cni lately which could unintentionally break things. Do you think it worth opening an issue in this repo, or what is my best shot?

**Comment by caseydavenport** [comment]
@AndrewSav let's open a new issue and I'd be happy to discuss in more detail  :)
