### ISSUE TITLE
Update K8s manifests with rolling upgrade for calico/node Daemonset

### ISSUE THREAD

**Issue by tmjd** [projectcalico/calico#777]
With the rolling upgrade capability of Daemonsets in kubernetes 1.6 we can enable that in our manifests and change our Upgrade story for calico/node.

**Comment by caseydavenport** [comment]
We should document how to do this, but I'm not entirely sure we want to enable the rolling-update in our checked-in manifests across the board - it should be a deliberate action on the users behalf to trigger this behavior.

**Comment by caseydavenport** [comment]
Let's do this in the next release. DaemonSet rolling-update support has been around long enough that I think it's safe, and is the desired behavior for most users.

**Comment by caseydavenport** [comment]
Closing in favor of https://github.com/projectcalico/calico/issues/1272
