### ISSUE TITLE
single node k8s, must calico open port 2379 and 6443, can‘t not deny

### ISSUE THREAD

**Issue by Niceies** [projectcalico/calico#7785]
I want to shield ports 6443 and 2379 from being exposed to the outside world, so I use GlobalNetworkPolicy to set the port settings of the corresponding network card, but I found that it did not take effect, and the other ports are blocked normally.
## Expected Behavior
6443 and 2379 port not can be accessed

## Current Behavior
it‘s still can access

## Possible Solution
it is must open even if is a single node

## Steps to Reproduce (for bugs)
1. use this config
- apiVersion: projectcalico.org/v3
  kind: GlobalNetworkPolicy
  metadata:
    name: allow-external-ingress
  spec:
    applyOnForward: true
    ingress:
    - action: Allow
      destination:
        ports:
        - 162
        - 514
        - 515
        - 30594
        - 4488
        - 8443
        - 80
        - 19666
        - 5044
        - 22
        - 443
      protocol: TCP
      source:
        selector: network-ip-list == 'external-wl' && enabled == 'true'
    - action: Allow
      destination:
        ports:
        - 162
        - 514
        - 515
        - 5044
      protocol: UDP
      source:
        selector: network-ip-list == 'external-wl' && enabled == 'true'
    - action: Deny
      destination:
        ports:
        - 6443
      http:
        paths:
        - path: /version.*
      protocol: TCP
      source:
        selector: network-ip-list == 'external-wl' && enabled == 'true'	
    - action: Allow
      destination: {}
      protocol: ICMP
      source:
        selector: network-ip-list == 'external-wl' && enabled == 'true'
    order: 10
    preDNAT: true
    selector: host-endpoint == 'data'
    types:
    - Ingress
2. access https://<ip>:6443/version still success
3. namp scan 2379 port and 6443 port still listen

## Your Environment
k8s: v1.23.13
calico: v3.24.5

**Comment by MichalFupso** [comment]
Hi @Niceies, would you please be able to reformat the code to be readable. In your config I don't see any deny rules for the port 2379, is this the whole file? Have you tried using `- prefix: '/version'` instead of `path: /version.*` in your deny rule
