### ISSUE TITLE
CALICO_NETWORKING_BACKEND none creates noisy log output

### ISSUE THREAD

**Issue by tobiasgiese** [projectcalico/calico#7819]
With calico v3.26.1 there is an issue with `CALICO_NETWORKING_BACKEND: none`.
Using no network backend creates alot of log output. Every second the following lines will be printed:

```
W0627 10:59:35.128237     457 feature_gate.go:241] Setting GA feature gate ServiceInternalTrafficPolicy=true. It will be removed in a future release.
2023-06-27 10:59:35.132 [INFO][457] monitor-addresses/startup.go 432: Early log level set to info
2023-06-27 10:59:35.132 [INFO][457] monitor-addresses/startup.go 315: Skipped monitoring node IP changes when CALICO_NETWORKING_BACKEND=none
```

With the latest `master` (i.e., v3.27.0-dev) this issue does not occur.

Reproducable with `kind`:

1. Create a v1.26 kind cluster

```
❯ kind create cluster --image kindest/node:v1.26.4@sha256:f4c0d87be03d6bea69f5e5dc0adb678bb498a190ee5c38422bf751541cebe92e
```

2. Apply calico v3.26.1 with backend type `none`

```
❯ curl https://raw.githubusercontent.com/projectcalico/calico/v3.26.1/manifests/calico.yaml | sed -r 's/(calico_backend:) "bird"/\1 "none"/' | kubectl apply -f -
```

3. Wait for calico-node Pods running and see the log output

```
❯ kubectl -n kube-system logs calico-node-l7mv4 --tail 9
Defaulted container "calico-node" out of: calico-node, upgrade-ipam (init), install-cni (init), mount-bpffs (init)
W0627 11:06:02.068549     650 feature_gate.go:241] Setting GA feature gate ServiceInternalTrafficPolicy=true. It will be removed in a future release.
2023-06-27 11:06:02.072 [INFO][650] monitor-addresses/startup.go 432: Early log level set to info
2023-06-27 11:06:02.072 [INFO][650] monitor-addresses/startup.go 315: Skipped monitoring node IP changes when CALICO_NETWORKING_BACKEND=none
W0627 11:06:03.114813     666 feature_gate.go:241] Setting GA feature gate ServiceInternalTrafficPolicy=true. It will be removed in a future release.
2023-06-27 11:06:03.119 [INFO][666] monitor-addresses/startup.go 432: Early log level set to info
2023-06-27 11:06:03.119 [INFO][666] monitor-addresses/startup.go 315: Skipped monitoring node IP changes when CALICO_NETWORKING_BACKEND=none
W0627 11:06:04.159043     680 feature_gate.go:241] Setting GA feature gate ServiceInternalTrafficPolicy=true. It will be removed in a future release.
2023-06-27 11:06:04.163 [INFO][680] monitor-addresses/startup.go 432: Early log level set to info
2023-06-27 11:06:04.163 [INFO][680] monitor-addresses/startup.go 315: Skipped monitoring node IP changes when CALICO_NETWORKING_BACKEND=none
```

Setting `CALICO_STARTUP_LOGLEVEL` or `FELIX_LOGSEVERITYSCREEN` to `error` does not fix the issue.

## Your Environment

* Calico version v3.26.1
* Orchestrator version (e.g. kubernetes, mesos, rkt): kind v1.26.4
* Operating System and version:
* Link to your project (optional):

<sub>Tobias Giese <tobias.giese@mercedes-benz.com>, Mercedes-Benz Tech Innovation GmbH, [legal info/Impressum](https://github.com/mercedes-benz/foss/blob/master/LEGAL_IMPRINT.md)</sub>

**Comment by caseydavenport** [comment]
Looks like that spammy log was removed in this commit: https://github.com/projectcalico/calico/commit/08f2765dada2398423c1e3567b2f7a15302a1f22

Seems like a reasonable enough cherry-pick if anyone wants to have a go

**Comment by tobiasgiese** [comment]
@caseydavenport only this CP creates a nil pointer because `configureASNumber`

https://github.com/projectcalico/calico/blob/8234b36dcb0c484427c016c8cd58126577a02bd2/node/pkg/lifecycle/startup/startup.go#L188-L189

needs `node.Spec.BGP.ASNumber`

https://github.com/projectcalico/calico/blob/8234b36dcb0c484427c016c8cd58126577a02bd2/node/pkg/lifecycle/startup/startup.go#L702

```
calico-node-ghflt calico-node W0628 07:25:57.491768       9 feature_gate.go:241] Setting GA feature gate ServiceInternalTrafficPolicy=true. It will be removed in a future release.
calico-node-ghflt calico-node panic: runtime error: invalid memory address or nil pointer dereference
calico-node-ghflt calico-node [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x19e7718]
calico-node-ghflt calico-node 
calico-node-ghflt calico-node goroutine 1 [running]:
calico-node-ghflt calico-node github.com/projectcalico/calico/node/pkg/lifecycle/startup.configureASNumber(0xc0000e8000)
calico-node-ghflt calico-node 	/go/src/github.com/projectcalico/calico/node/pkg/lifecycle/startup/startup.go:705 +0x58
calico-node-ghflt calico-node github.com/projectcalico/calico/node/pkg/lifecycle/startup.Run()
calico-node-ghflt calico-node 	/go/src/github.com/projectcalico/calico/node/pkg/lifecycle/startup/startup.go:187 +0x8e5
calico-node-ghflt calico-node main.main()
calico-node-ghflt calico-node 	/go/src/github.com/projectcalico/calico/node/cmd/calico-node/main.go:146 +0x732
calico-node-ghflt calico-node Calico node failed to start
```

Btw, this is also an issue with the latest `v3.27.0-0.dev` and `master`

**Comment by tobiasgiese** [comment]
@caseydavenport if created a PR that fixes this nil pointer

**Comment by caseydavenport** [comment]
@tobiasgiese good catch! I just gave that PR a look over and gave some suggestions - LMK what you think.

**Comment by tobiasgiese** [comment]
@caseydavenport adjusted the PR according your suggestions and it's working as expected.

**Comment by tobiasgiese** [comment]
@caseydavenport created PR https://github.com/projectcalico/calico/pull/7824 to cherry-pick both commits.

**Comment by mindw** [comment]
Any news on when this gets released? or at least if there is a workaround till it is?
Tx!

**Comment by tobiasgiese** [comment]
@mindw seems like v3.26.3 has been released last week
https://github.com/projectcalico/calico/releases/tag/v3.26.3
