### ISSUE TITLE
OpenShift Integration

### ISSUE THREAD

**Issue by ozdanborne** [projectcalico/calico#782]
The following work is needed to enhance Calico's integration with OpenShift:

- [x] Support connecting to an etcd instance stood up outside of OpenShift. (https://github.com/openshift/openshift-ansible/pull/4267)
- [ ] Integrate with etcd playbook roles to set up an additional etcd instance for use only by Calico.
- [ ] Convert from systemd units of Calico-node to Hosted Install
- [ ] Support host protection

Add documentation covering (mostly just the above):

- [x] Basic landing page for OpenShift users explaining how to get started with openshift-ansible ( #816 )
- [x] Advanced doc on connecting to an etcd instance stood up outside of OpenShift
- [ ] Demos?
- [ ] Document IPv6 with Calico and OpenShift

**Comment by djosborne** [comment]
Help wanted for the above issues. Please ping me on [Calico Users Slack](calicousers.slack.com) @ozdanborne and reach out in the #openshift channel

cc: @VincentS

**Comment by kprabhak** [comment]
Regd demo's, probably leverage the existing Calico demo's, and also OpenShift examples (https://github.com/openshift/origin/tree/master/examples)

**Comment by kprabhak** [comment]
Another:
- Update openshift-ansible calico playbook to use client certs (potentially byoc) in addition to etcd server certs during install
