### ISSUE TITLE
The CustomResourceDefinition "installations.operator.tigera.io" is invalid: metadata.annotations: Too long: must have at most 262144 bytes

### ISSUE THREAD

**Issue by bluven** [projectcalico/calico#7826]
## Expected Behavior
tigera-operator can work.

## Current Behavior
```
kubectl apply -f tigera-operator.yaml 
namespace/tigera-operator unchanged
customresourcedefinition.apiextensions.k8s.io/bgpconfigurations.crd.projectcalico.org configured
customresourcedefinition.apiextensions.k8s.io/bgpfilters.crd.projectcalico.org configured
customresourcedefinition.apiextensions.k8s.io/bgppeers.crd.projectcalico.org configured
customresourcedefinition.apiextensions.k8s.io/blockaffinities.crd.projectcalico.org configured
customresourcedefinition.apiextensions.k8s.io/caliconodestatuses.crd.projectcalico.org configured
customresourcedefinition.apiextensions.k8s.io/clusterinformations.crd.projectcalico.org configured
customresourcedefinition.apiextensions.k8s.io/felixconfigurations.crd.projectcalico.org configured
customresourcedefinition.apiextensions.k8s.io/globalnetworkpolicies.crd.projectcalico.org configured
customresourcedefinition.apiextensions.k8s.io/globalnetworksets.crd.projectcalico.org configured
customresourcedefinition.apiextensions.k8s.io/hostendpoints.crd.projectcalico.org configured
customresourcedefinition.apiextensions.k8s.io/ipamblocks.crd.projectcalico.org configured
customresourcedefinition.apiextensions.k8s.io/ipamconfigs.crd.projectcalico.org configured
customresourcedefinition.apiextensions.k8s.io/ipamhandles.crd.projectcalico.org configured
customresourcedefinition.apiextensions.k8s.io/ippools.crd.projectcalico.org configured
customresourcedefinition.apiextensions.k8s.io/ipreservations.crd.projectcalico.org configured
customresourcedefinition.apiextensions.k8s.io/kubecontrollersconfigurations.crd.projectcalico.org configured
customresourcedefinition.apiextensions.k8s.io/networkpolicies.crd.projectcalico.org configured
customresourcedefinition.apiextensions.k8s.io/networksets.crd.projectcalico.org configured
customresourcedefinition.apiextensions.k8s.io/apiservers.operator.tigera.io configured
customresourcedefinition.apiextensions.k8s.io/imagesets.operator.tigera.io configured
customresourcedefinition.apiextensions.k8s.io/tigerastatuses.operator.tigera.io configured
serviceaccount/tigera-operator configured
clusterrole.rbac.authorization.k8s.io/tigera-operator unchanged
clusterrolebinding.rbac.authorization.k8s.io/tigera-operator unchanged
deployment.apps/tigera-operator configured
The CustomResourceDefinition "installations.operator.tigera.io" is invalid: metadata.annotations: Too long: must have at most 262144 bytes
```
## Steps to Reproduce (for bugs)
1. Install kubernetes v1.22.5
2. kubectl create -f https://raw.githubusercontent.com/projectcalico/calico/v3.26.1/manifests/tigera-operator.yaml

That's all.

## Your Environment

* Calico version: v3.26.1
* Orchestrator version (e.g. kubernetes, mesos, rkt): kubernetes v1.22.5
* Operating System and version:   centos 7 
   ```
   uname -a
   Linux beijing 3.10.0-1160.el7.x86_64 #1 SMP Mon Oct 19 16:18:59 UTC 2020 x86_64 
   ```

**Comment by bluven** [comment]
I made a stupid mistake by using 'kubectl apply' rather than 'kubectl create'

**Comment by bluepresleycom** [comment]
I wonder if this should be considered a "bug"? What's the intent? 

What I mean is, I know where the confusion is coming from. After Kubernetes is installed manually with `kubeadm init` the success message pops up and gives two steps, the second of which is:

```
You should now deploy a pod network to the cluster.
Run "kubectl apply -f [podnetwork].yaml" with one of the options listed at:
  https://kubernetes.io/docs/concepts/cluster-administration/addons/
```

There are suble difference between kubectl create and apply, one of which is that apply allows for easily updating through another 'kubectl apply -f' iteretion. 'kubectl create -f' does not. Doing so throws an error, and the resources have to be destroyed before they can be recreated. This can be disruptive in a production environment, and I don't think that is the intent? Shouldn't the Calico operators be created with apply? What do we do in a production setting when the operators have to be updated?

The fact that create vs apply accepts different metadata annotation lengths is an interesting issue itself. I didn't know that. I'll run that by the k8s project, I'm curious to know more.

**Comment by asrivastava-github** [comment]
Agree with @bluepresleycom regarding production deployment. This (k delete/create) is not something we would prefer in production. Should we expect 3.26.4 with the fix, please.

**Comment by caseydavenport** [comment]
> There are suble difference between kubectl create and apply, one of which is that apply allows for easily updating through another 'kubectl apply -f' iteretion. 'kubectl create -f' does not

If you use `kubectl create`, you want to use `kubectl replace` on upgrade (not delete / create). 

Apply is the wrong verb for our CRDs. `apply` is not the same thing as `update`, and as far as I'm aware the nuanced merging behavior that it carries with it isn't appropriate for our CRDs which should be updated wholesale to exactly the new version.

Happy to be convinced otherwise though, just haven't heard of a use case yet.

**Comment by caseydavenport** [comment]
This is at its core just a bug in how kubectl apply is implemented. It wasn't design to handle large resources.

**Comment by yuvipanda** [comment]
You can use `--server-side` to `kubectl apply` to get around this now btw.
