### ISSUE TITLE
gatekeeper and calico

### ISSUE THREAD

**Issue by caduceus4** [projectcalico/calico#7827]
I would like to create a gatekeeper constraint that disallows pod creation if a partcular globalnetworkpolicy does not exist for a namespace.

With k8s native network policys, I can import

data.kubernetes.networkpolicies 

in my rego code and I can then read and parse the network policies. What can I import or otherwise use to read/inspect/use the calico network policies (global as well)? Thanks

**Comment by mazdakn** [comment]
@caduceus4 global network policy is a global resource and is not namespaced. IIUC, you want to read the list of global network policies in your code, right?
