### ISSUE TITLE
What's the use of calico CSI?

### ISSUE THREAD

**Issue by bluven** [projectcalico/calico#7831]
I deployed calico with tigera operator  and I found there were some csi-node-driver pods, I couldn't find any documents about this compoent, what is the use of it?

**Comment by mehmetyazicioglu** [comment]
https://docs.tigera.io/calico/latest/getting-started/kubernetes/hardway/istio-integration 

"Calico uses a Container Storage Interface (CSI) driver to enable secure connectivity between Felix and the Dikastes container running in each pod. It mounts a shared volume into which Felix inserts a Unix Domain Socket."

I also found this 

https://docs.tigera.io/calico/latest/network-policy/istio/app-layer-policy
