### ISSUE TITLE
Default IP Autodetection method should select real interfaces

### ISSUE THREAD

**Issue by nadenf** [projectcalico/calico#7832]
The default IP Autodetection method as described [here](https://docs.tigera.io/calico/latest/networking/ipam/ip-autodetection#manually-configure-ip-address-and-subnet-for-a-node) is to select the first valid IP address. 

However if you have Tailscale or similar virtual interfaces they can be selected even if under almost all conditions they would not be a sensible choice.

## Expected Behavior
Rather than go through a [painful](https://github.com/rancher/rke2/issues/4320#) triage adventure it would be better if Calico could either (a) select a real interface i.e. network card or (b) select the interface associated with the InternalIP address that Kubernetes has selected.

## Current Behavior
Pods will run and have connectivity with each other but if say Tailscale is selected will not be able to access outside world.

## Possible Solution
If you look at ethtool for Tailscale it should be obvious it's not real:
```
Settings for tailscale0:
	Supported ports: [  ]
	Supported link modes:   Not reported
	Supported pause frame use: No
	Supports auto-negotiation: No
	Supported FEC modes: Not reported
	Advertised link modes:  Not reported
	Advertised pause frame use: No
	Advertised auto-negotiation: No
	Advertised FEC modes: Not reported
	Speed: Unknown!
	Duplex: Full
	Auto-negotiation: off
	Port: Twisted Pair
	PHYAD: 0
	Transceiver: internal
	MDI-X: Unknown
        Current message level: 0x00000000 (0)
	Link detected: yes 
```

## Steps to Reproduce (for bugs)
1. Install Tailscale and/or multiple network cards (one that has weird routing and should not be used)
2. Install Calico using VXLAN mode on RKE2/similar and have it select the Tailscale interface (you may need to rename others)
3. Add two nodes.
4. Launch pod that is pinned to second node.
5. Pod will be able to access other pods on first node but not access internet.

## Your Environment
* Calico version: v3.25.0
* Orchestrator version (e.g. kubernetes, mesos, rkt): RKE2 v1.25.11+rke2r1
* Operating System and version: Linux Ubuntu 22.04
* Link to your project (optional):

**Comment by mazdakn** [comment]
@nadenf It is possible to configure [auto detection](https://docs.tigera.io/calico/latest/networking/ipam/ip-autodetection#autodetection-methods) functionality. You can use a regex to include or exclude an interface from auto detection.

**Comment by nadenf** [comment]
@mazdakn .. Fully aware. But just close if it's not an issue. 

It's just incredibly frustrating and time consuming when you install Calico and it fails to work out of the box.

**Comment by coutinhop** [comment]
@nadenf @mazdakn it looks like this would be a simple fix, we just need to add patterns for the virtual interface types to the default exclude list: https://github.com/projectcalico/calico/blob/master/node/pkg/lifecycle/startup/autodetection/autodetection_linux.go#L18

@nadenf since this is implemented as a list of interface regexes to be excluded, we'd need to know what the virtual interfaces you had trouble with look like, could you please share that info? As a side note, contributor PRs are also always welcome, if you feel like gettting your hands dirty :smile:

**Comment by nadenf** [comment]
@coutinhop  .. Thanks so much for that. Didn't realise you were already excluding interfaces.

I will submit a PR for including just Tailscale to keep it simple.
