### ISSUE TITLE
netpol w namespaceSelector blocks NLB access, no solution 

### ISSUE THREAD

**Issue by darkn3rd** [projectcalico/calico#7834]
Using Calico for network policies will block traffic from an external load balancer (NLB) when using `namespaceSelector`.  There doesn't seem to be a viable solution path for allowing traffic from the external load balancer (NLB) and from the desired namespace, e.g. `client`.

## Expected Behavior

I expected to be able to filter in a namespace using `namespaceSelector` and also receive traffic from external load balancer (NLB).  I expected to be able to filter in traffic using the client source IP address using `ipBlock.cidr`, or find any solution where I can filter in only the desired namespace, `client` and traffic from the load balancer (NLB).  

## Current Behavior

* If I use only `namespaceSelector`, all traffic is blocked from the external load balancer (NLB).   
* If I also add `ipBlock.cidr`, to filter in client source IP, this will not work, even if service is set with `spec.externalTrafficPolicy: Local`.  Traffic from the external load balancer (NLB) is blocked.
* If `ipBlock.cidr` to include the full VPC subnet range, traffic from the external load balancer (NLB) will work, but then all namespaces will be able to reach the service, including unauthorized namespaces that are not `client`.

There doesn't seem to be a way to allow traffic from the load balancer and from a single namespace.

## Possible Solution

If the client source IP is supported with network policies, then both `namespaceSelector` and the external load balancer (NLB) can be supported.  If there is a way to fetch the private IP addresses used by NLB and support this automatically within the network policy, then this would work as well. 

## Steps to Reproduce (for bugs)

0. Setup
   ```bash
   export AWS_PROFILE="my-aws-profile" # CHANGEME
   export EKS_CLUSTER_NAME="my-unique-cluster-name" # CHANGEME
   export EKS_REGION="us-west-2"
   export EKS_VERSION="1.26"
   export KUBECONFIG="$HOME/.kube/$EKS_REGION.$EKS_CLUSTER_NAME.yaml"
   export ACCOUNT_ID=$(aws sts get-caller-identity --query "Account" --output text)

   export POLICY_NAME_ALBC="${EKS_CLUSTER_NAME}_AWSLoadBalancerControllerIAMPolicy"
   export POLICY_ARN_ALBC="arn:aws:iam::$ACCOUNT_ID:policy/$POLICY_NAME_ALBC"
   export ROLE_NAME_ALBC="${EKS_CLUSTER_NAME}_AmazonEKSLoadBalancerControllerRole"
   ```
1. Provision EKS Cluster:
   ```bash
   eksctl create cluster --version $EKS_VERSION --region $EKS_REGION \
     --name $EKS_CLUSTER_NAME --nodes 3
   eksctl utils associate-iam-oidc-provider --cluster $EKS_CLUSTER_NAME \
     --region $EKS_REGION --approve  
   ```
2. AWS LB Controller Policy
   ```bash
   VER="v2.5.2"
   PREFIX="https://raw.githubusercontent.com"
   HTTP_PATH="kubernetes-sigs/aws-load-balancer-controller/$VER/docs/install"
   
   curl --remote-name --silent --location $PREFIX/$HTTP_PATH/iam_policy.json
   aws iam create-policy \
    --policy-name $POLICY_NAME_ALBC \
    --policy-document file://iam_policy.json
   ```
3. IAM-Role-for-Service-Account
   ```bash
   eksctl create iamserviceaccount --cluster $EKS_CLUSTER_NAME --region $EKS_REGION \
     --namespace "kube-system" --name "aws-load-balancer-controller" \
     --role-name $ROLE_NAME_ALBC \
     --attach-policy-arn $POLICY_ARN_ALBC --approve
   ```
4. Install AWS LB Controller
   ```bash
   helm repo add "eks" "https://aws.github.io/eks-charts" && helm repo update
   helm install aws-load-balancer-controller eks/aws-load-balancer-controller \
    --namespace "kube-system" \
    --set clusterName=$EKS_CLUSTER_NAME \
    --set serviceAccount.create=false \
    --set serviceAccount.name=aws-load-balancer-controller
   ```
5. Install Calico
   ```bash
   kubectl create namespace tigera-operator
   helm install calico projectcalico/tigera-operator --version v3.26.1 \
     --namespace tigera-operator --set installation.kubernetesProvider=EKS
   ```
6. Kublet Race Condition workaround w VPC-CNI + Calico
   ```
   cat << EOF > append.yaml
   - apiGroups:
       - ""
     resources:
       - pods
     verbs:
       - patch
   EOF
   
   kubectl apply -f <(cat <(kubectl get clusterrole aws-node -o yaml) append.yaml)
   kubectl set env daemonset aws-node --namespace kube-system ANNOTATE_POD_IP=true
   kubectl delete pod --selector app.kubernetes.io/name=calico-kube-controllers --namespace calico-system
   ```
7. Install Application
   ```bash
   kubectl create namespace server
   kubectl create deployment httpd --image=httpd --replicas=3 \
     --port=80 --namespace=server
   cat <<EOF | kubectl apply --namespace server -f -
   apiVersion: v1
   kind: Service
   metadata:
     name: httpd
     annotations:
       service.beta.kubernetes.io/aws-load-balancer-type: external
       service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
       service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
   spec:
     externalTrafficPolicy: Local
     ports:
       - port: 80
         targetPort: 80
         protocol: TCP
     type: LoadBalancer
     selector:
       app: httpd
   EOF
   ```
8. Install Policy
   ```bash
   MY_IP_ADDRESS=$(curl --silent ifconfig.me)
   kubectl apply --namespace server --filename - <<EOF
   apiVersion: networking.k8s.io/v1
   kind: NetworkPolicy
   metadata:
     name: allow
     namespace: server
   spec:
     podSelector: {}
     ingress:
       - from:
           - podSelector: {}
       - from:
           - ipBlock:
               cidr: "$MY_IP_ADDRESS/32"
       - from:
           - namespaceSelector:
               matchLabels:
                 kubernetes.io/metadata.name: client
   EOF
   ```
9. Test from NLB endpoint, expect this to work
   ```bash
   export MY_LB=$(kubectl get service httpd --namespace "server" \
     --output jsonpath='{.status.loadBalancer.ingress[0].hostname}')
   curl --silent --include $MY_LB  
   ```
10. Test from approved namespace `client`, expect this to work
     ```bash
     kubectl create namespace client
     kubectl run curl -ti --namespace client --image=curlimages/curl -- sh
     # inside container
     curl httpd.server
     ```
 11. Test from `unapproved` namespace, expect this to be blocked
     ```bash
     kubectl create namespace unapproved
     kubectl run curl -ti --namespace unapproved --image=curlimages/curl -- sh
     # inside container
     curl httpd.server
     ```

## Context

The above example is a minimal example for steps to reproduce.  The final solution will be a distributed graph database called https://dgraph.io/.

These are two use cases:

1. Secure stateful graph db server, so that only permitted clients (designated by namespace) and select client source IP addresses can reach private database.  This is typical OPD scenario.
2. Secure tenant graph db servers, so that each tenant can never communicate to other tenants.  Each tenant has its own namespace.  Allow select administrative or operational clients to access the tenant databases in their perspective namespace; allow customer traffic to reach their tenant database.  The tenants will allow all outside traffic, and will use tokens to secure access from the customer, but should block other private access of other tenants namespaces within the Kubernetes cluster. This is PaaS oriented solution.  

## Your Environment

* Calico version: `v3.26.1`
* Orchestrator version: EKS `v1.26.5-eks-c12679a`
* Operating System and version: n/a 
* Link to your project (optional): n/a

**Comment by caseydavenport** [comment]
>  If there is a way to fetch the private IP addresses used by NLB and support this automatically within the network policy, then this would work as well.

yeah, it sounds like fundamentally the problem is that the NLB address isn't well-known, and so in order to make sure you include it in your policy you need to write policy that is too broad?

if you could narrow your CIDR rule to just include the NLB's IP address, then you'd probably be OK with the current model. Does that sound right?

**Comment by mgleung** [comment]
Closing this since it seems to have gone stale. Please shout out if this needs to be reopened.
