### ISSUE TITLE
Where is `remove-calico-policy.sh` ? is it deprecated？

### ISSUE THREAD

**Issue by joeyleeeeeee97** [projectcalico/calico#7835]
not in https://github.com/tigera/docs, and is removed in https://github.com/projectcalico/calico/commit/5826e2ff33fd336040d599f7263404cdc43856ff

## Expected Behavior

a up to date clean up script

## Current Behavior

can't find effective scripts for cleanup.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Calico version master branch
* Orchestrator version (e.g. kubernetes, mesos, rkt):
* Operating System and version:
* Link to your project (optional):

**Comment by caseydavenport** [comment]
This may have been an accidental casualty of the docs move. @ctauchen might know better if there are plans to add that back, but guessing it was just an accident.

@joeyleeeeeee97 That said, that script is not really maintained and is probably long out of date - where did you see a reference to it?

**Comment by ctauchen** [comment]
I see that the `hack` directory was included in the docs site files. But it wasn't part of the published documentation. The content there seems well out of date.

@caseydavenport Perhaps we could consider restoring this in projectcalico? If we wanted to publish any of this on the docs site, we'd need to make revisions first.

**Comment by joeyleeeeeee97** [comment]
@caseydavenport , I am deploying calico in my EKS, after uninstall it, I saw `left calico iptable ruls` on the machine.
In that case the network is broken, can't access any.

After manually run the script,  this issue is fixed.

**Comment by joeyleeeeeee97** [comment]
@ctauchen @caseydavenport Hi, I have few questions about calico's left iptable rules:

1. what it does? I am only using it to enable wireguard, I am not applying any network policy.
2. Is this ever cleaned? if yes when and how could we ensure clean up happened.

Thanks!

**Comment by caseydavenport** [comment]
yeah, it was never meant to be part of the published documentation - it's really meant for developers rather than end-users.

**Comment by caseydavenport** [comment]
Action here is still to remove this from the documentation and move it back to the projectcalico/calico repository.

**Comment by joeyleeeeeee97** [comment]
@caseydavenport we should maintain this script, sometimes uninstalling calico will leave uncleaned iptables, very tricky.

**Comment by caseydavenport** [comment]
The script isn't supported or maintained, so should be removed. It was never intended as a supported way of uninstalling Calico, even when it was first introduced.

When uninstalling Calico (or any CNI plugin really), you should reboot your nodes to ensure transient state is cleaned (including iptables, routes, ipsets, interface state and configuration, etc).
