### ISSUE TITLE
Felix could be smarter with its RTNETLINK parsing

### ISSUE THREAD

**Issue by plwhite** [projectcalico/calico#784]
Felix detects interfaces coming up using the netlink interface. It doesn't parse every flag in the message, but instead just tries to program the interface and route every time anything changes.

We could optimise this by being smarter and only programming interfaces when they are in a state for that to be worthwhile. We have to be a little careful, since if an interface flaps (as we have seen on some misbehaving VMs) Felix is doing the right thing of applying the route again when it comes back; that behaviour must not be broken.

This is a performance optimisation because we seem to see quite a lot of CPU usage under load. It's not clear that we need to do this, but raising the issue so it can be considered.

@fasaxc Please be aware of this issue.

**Comment by plwhite** [comment]
I'm increasing the priority of this. It appears that this takes Felix from "happily handles 150 creates per second at 50% CPU" to "cannot handle 150 creates per second". Hence I think we should definitely spend a day or so fixing this.

**Comment by neiljerram** [comment]
Observations so far...

For an individual VM being launched, I see 7 RTM_NEWLINK messages for its TAP interface, with the following IFF flags.

- 1002 - not UP, not RUNNING
- 1002 - same again
- 1003 - UP, not RUNNING
- 11043 - UP, RUNNING, + whatever 10000 means
- 11043 - again
- 11043 - again
- 11043 - again

For reference, the individual flag values, that are relevant here, are:

- 1 - UP
- 2 - has a broadcast address
- 40 - RUNNING
- 1000 - multicast-capable
- 10000 - unknown

So one partial win would be to only trigger Felix processing when UP and RUNNING are both set.  However, that still leaves us with 4 occurrences of the 11043 state.

Thoughts?

**Comment by neiljerram** [comment]
If it helps, note that the 4 occurrences of the 11043 state happen very quickly.  For the last VM that I launched, the first 3 occurrences happened so quickly that UpdateSplitter didn't get to run until there were 3 copies of the on_interface_update message on its queue.

It appears, though, that the UpdateSplitter or LocalEndpoint receivers don't usefully coalesce their processing of the on_interface_update message - so it probably doesn't help that those netlink occurrences happen so quickly after each other, as the code currently stands.

**Comment by neiljerram** [comment]
I've posted a fix for this at #792
