### ISSUE TITLE
make gateway ip (169.254.1.1) configurable

### ISSUE THREAD

**Issue by bdurgaprakash** [projectcalico/calico#7840]
Calico is using the 169.254.1.1 as default route and its hardcoded same IP in below locations.

[calico/felix/dataplane/linux/bpf_ep_mgr.go at master · projectcalico/calico · GitHub](https://github.com/projectcalico/calico/blob/master/felix/dataplane/linux/bpf_ep_mgr.go#L2554)
[calico/felix/dataplane/linux/bpf_ep_mgr.go at master · projectcalico/calico · GitHub](https://github.com/projectcalico/calico/blob/master/felix/dataplane/linux/bpf_ep_mgr.go#L1781)
[calico/felix/dataplane/linux/bpf_ep_mgr.go at master · projectcalico/calico · GitHub](https://github.com/projectcalico/calico/blob/master/felix/dataplane/linux/bpf_ep_mgr.go#L2526)
[calico/felix/dataplane/linux/bpf_ep_mgr.go at master · projectcalico/calico · GitHub](https://github.com/projectcalico/calico/blob/master/felix/dataplane/linux/bpf_ep_mgr.go#L3066)

It would be great if we make it configurable ?

**Comment by sridhartigera** [comment]
@fasaxc @tomastigera Thoughts on this please.

**Comment by mazdakn** [comment]
@bdurgaprakash can you tell us about the application and why would the ability to change this address help?

**Comment by bdurgaprakash** [comment]
@mazdakn 

In our k8s cluster with multiple racks. For each rack our backend private ip config is 169.254.racknumber.nodenumber. 
For 1st rack it will 169.254.1.x 
For 2nd rack it will 169.254.2.x and so on.
As calico gw ip is 169.254.1.1 might conflict with out backed private ip.

if we can config this other than 169.254.1.1 would helps us with uniform backend network config.

**Comment by fasaxc** [comment]
I don't think there's actually a conflict.  Neither host nor pod actually has that IP assigned; it's a virtual IP that's implemented using an ARP trick.  Pod ARPs for 169.254.1.1 and the host responds via proxy ARP but the host doesn't actually have the IP assigned.

**Comment by ischorr** [comment]
@fasaxc What if a process in the pod wants to talk to the 169.254.1.1 host IP?  That would be an issue, no?
