### ISSUE TITLE
k8s cluster certs expiration, after renew certs，pod cannot create/delete

### ISSUE THREAD

**Issue by Tendrun101** [projectcalico/calico#7846]
when our k8s cluster certs expiration, we renewed all certs. After that we found we cannot create/delete pod.

## Current Behavior

we can found some "unauthorized "error logs in kubelet.log
```
E0802 10:17:24.172893 1237970 kubelet.go:1787] failed to "KillPodSandbox" for "f059f451-d193-41a8-82fe-9a99ec45c827" with KillPodSandboxError: "rpc error: code = Unknown desc = failed to destroy network for sandbox \"714dec02fa2dca5076e25cd82762611b52f1dffe6f4c6849be5c90f391133b28\": plugin type=\"calico\" failed (delete): error getting ClusterInformation: connection is unauthorized: Unauthorized"
E0802 10:17:24.172934 1237970 pod_workers.go:965] "Error syncing pod, skipping" err="failed to \"KillPodSandbox\" for \"f059f451-d193-41a8-82fe-9a99ec45c827\" with KillPodSandboxError: \"rpc error: code = Unknown desc = failed to destroy network for sandbox \\\"714dec02fa2dca5076e25cd82762611b52f1dffe6f4c6849be5c90f391133b28\\\": plugin type=\\\"calico\\\" failed (delete): error getting ClusterInformation: connection is unauthorized: Unauthorized\"" pod="default/ttt-75bbfc76c5-rmf6c" podUID=f059f451-d193-41a8-82fe-9a99ec45c827
E0802 10:17:29.189768 1237970 remote_runtime.go:248] "StopPodSandbox from runtime service failed" err="rpc error: code = Unknown desc = failed to destroy network for sandbox \"d6f149c56c82e098461f25fc6f4392f07fb8ef8d518bf01aa317e7207a6dc229\": plugin type=\"calico\" failed (delete): error getting ClusterInformation: connection is unauthorized: Unauthorized" podSandboxID="d6f149c56c82e098461f25fc6f4392f07fb8ef8d518bf01aa317e7207a6dc229"
E0802 10:17:29.189955 1237970 kuberuntime_manager.go:999] "Failed to stop sandbox" podSandboxID={Type:containerd ID:d6f149c56c82e098461f25fc6f4392f07fb8ef8d518bf01aa317e7207a6dc229}
E0802 10:17:29.190278 1237970 kubelet.go:1787] failed to "KillPodSandbox" for "01ed2019-7db4-4842-9fd8-a5c028148128" with KillPodSandboxError: "rpc error: code = Unknown desc = failed to destroy network for sandbox \"d6f149c56c82e098461f25fc6f4392f07fb8ef8d518bf01aa317e7207a6dc229\": plugin type=\"calico\" failed (delete): error getting ClusterInformation: connection is unauthorized: Unauthorized"

``` 

## Possible Solution

we think this error may have some thing to do with ''/etc/cni/net.d/calico-kubeconfig''.  So we recreate calico-node pod, pod can be deleted/created.

## Context

Is it a bug or Is it a good way to handle this scenario  ?

## Your Environment

* Calico version v3.18
* Orchestrator version (e.g. kubernetes, mesos, rkt): 1.24.10
* Operating System and version: centos 7.9
* Link to your project (optional):

**Comment by MichalFupso** [comment]
Hi @Tendrun101, are you updating your certificates manually? Kubernetes dynamic certificate reload is currently not supported for all components and certificates, after the update you should restart the control plane pods.

**Comment by Tendrun101** [comment]
> Hi @Tendrun101, are you updating your certificates manually? Kubernetes dynamic certificate reload is currently not supported for all components and certificates, after the update you should restart the control plane pods.
yes，I updated my certificates manually also restarted kube-apiserver, kube-controller-manager, kube-scheduler and etcd pod.

**Comment by matiasdm2020** [comment]
> > Hi [@Tendrun101](https://github.com/Tendrun101), are you updating your certificates manually? Kubernetes dynamic certificate reload is currently not supported for all components and certificates, after the update you should restart the control plane pods.
> 
> yes，I updated my certificates manually also restarted kube-apiserver, kube-controller-manager, kube-scheduler and etcd pod.

How did you solved it?

**Comment by lethargosapatheia** [comment]
The question is: how do you actually restart the control plane nodes without restarting the node itself? kubectl delete is being ignored. It conventionally says that the pod has been restarted, when it clearly hasn't (if you check the pods using crictl/docker, you'll see that the containers are still there). So how do you nomally do it?
