### ISSUE TITLE
when calico set clusterCIDRs，calico watch endpoints resource will cause high network data

### ISSUE THREAD

**Issue by w313062006** [projectcalico/calico#7847]
when calico default bgpconfiguration use cluster cidrs, calico confd will build routegenerator, routegenerator will open endpoints informer to watch endpoints events.
according to https://kubernetes.io/blog/2020/09/02/scaling-kubernetes-networking-with-endpointslices/
k8s recommend use endpointslices resource replace endpoints resource, because watch endpoints will cause high network data if k8s service has thousands Pods.

https://github.com/projectcalico/calico/blob/38a92dfcc791717d2506040c8c24e1d11777c396/confd/pkg/backends/calico/client.go#L242C10-L242C10

## Current Behavior

when svc endpoints change, 10+ Gb apiserver network data will happen (our cluster has 2K nodes and not use typha)

## Possible Solution

1, use endpointslices replace endpoints
2, when set clusterCIDRs, why calico need watch endpoints? can I bypass this logic?
3, use typha will solve or mitigate this question？

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Calico version   3.23
* Orchestrator version (e.g. kubernetes, mesos, rkt): 1.23
* Operating System and version:  debian 10
* Link to your project (optional):

**Comment by mazdakn** [comment]
@w313062006 yeah, we don't use `endpointslices` for this resource atm, and using `typha` should fix the issue. Anyway I am going to create an internal ticket to consider the optimisation in future.

**Comment by fasaxc** [comment]
> our cluster has 2K nodes and not use typha

I think this your problem.  Typha is designed to solve exactly this problem.  I suggest using the operator to deploy calico, it automates creation of TLS certs for Typha and it auto-scales Typha for your cluster size.
