### ISSUE TITLE
Necessity of Default gateway in Calico

### ISSUE THREAD

**Issue by cpsrujana** [projectcalico/calico#7866]
Calico pods are not coming up, in absence of default gateway on the interface which is used to bringup the Kubernetes.
Why we need a default gateway. Can we remove the dependency on the default gateway while bringing up the calico pods?

Could you please provide me the links or information regarding the same.

**Comment by mazdakn** [comment]
@cpsrujana please fill in the template with the necessary information so we can help you.
generally speaking, Calico does not require default gateway, but it needs to use some images, so if the images are not available locally, it would need to download those. Anyway, we cannot exactly tell what's going wrong on your cluster without more information.

**Comment by caseydavenport** [comment]
> Why we need a default gateway. Can we remove the dependency on the default gateway while bringing up the calico pods?

Calico needs a default gateway on the host in order for proxy_arp to function, which enables the host to respond to ARP requests from the containers it is hosting.
