### ISSUE TITLE
Example: kubeadm calico manifest points to a broken link

### ISSUE THREAD

**Issue by frnkdny** [projectcalico/calico#787]
Example: kubeadm calico manifest points to a broken link

kubectl apply -f `http://docs.projectcalico.org/v2.2/getting-started/kubernetes/installation/hosted/kubernetes-datastore/calico.yaml`

taken from here: 
http://docs.projectcalico.org/v2.2/getting-started/kubernetes/installation/hosted/kubernetes-datastore/#example-kubeadm

see also: https://github.com/projectcalico/calico/issues/716

**Comment by caseydavenport** [comment]
Wow this is bad.

Part of this issue should be ensuring _all_ of our manifest links are correct.

**Comment by djosborne** [comment]
I will fix this as part of 716
