### ISSUE TITLE
calico-node unable to start if one AZ subnet is down

### ISSUE THREAD

**Issue by pfragoso** [projectcalico/calico#7884]
On a test cluster when doing some testing for resilience purposes we found out that if we disable an AWS AZ subnet to mimic a failure, calico is unable to start a node on a working AWS AZ.

The cluster runs on 3 AWS AZ and when disabling one of the subnets we are unable to scale the cluster on the working remaining 2 AWS AZs until the failed AZ becomes operational again.

## Expected Behavior
A newer fresh node on a working AZ should be able to start the calico stack.

## Current Behavior
Unable to start the network stack on a fresh node until the node that's on the failed AZ becomes operational again.
Errors:

`2023-07-26 19:12:07.526 [ERROR][60] cni-config-monitor/token_watch.go 106: Unable to create token for CNI kubeconfig error=Post "https://172.20.0.1:443/api/v1/namespaces/calico-system/serviceaccounts/calico-cni-plugin/token": dial tcp 172.20.0.1:443: i/o timeout
2023-07-26 19:12:07.526 [ERROR][60] cni-config-monitor/token_watch.go 130: Failed to update CNI token, retrying... error=Post "https://172.20.0.1:443/api/v1/namespaces/calico-system/serviceaccounts/calico-cni-plugin/token": dial tcp 172.20.0.1:443: i/o timeout
2023-07-26 19:12:07.539 [ERROR][57] felix/daemon.go 249: Failed to get config from datastore error=Get "https://172.20.0.1:443/apis/crd.projectcalico.org/v1/clusterinformations/default": dial tcp 172.20.0.1:443: i/o timeout
2023-07-26 19:12:07.564 [ERROR][63] status-reporter/discovery.go 199: Unable to get Typha service endpoints from Kubernetes. error=Get "https://172.20.0.1:443/api/v1/namespaces/calico-system/endpoints/calico-typha": dial tcp 172.20.0.1:443: i/o timeout
2023-07-26 19:12:07.564 [FATAL][63] status-reporter/startsyncerclient.go 49: Typha discovery enabled but discovery failed. error=Get "https://172.20.0.1:443/api/v1/namespaces/calico-system/endpoints/calico-typha": dial tcp 172.20.0.1:443: i/o timeout`

pod events
`Normal   Scheduled  22m   default-scheduler  Successfully assigned calico-system/calico-node-psn77 to ip-10-138-11-236.eu-west-2.compute.internal
  Normal   Pulled     22m   kubelet            Container image "quay.io/calico/pod2daemon-flexvol:v3.26.0" already present on machine
  Normal   Created    22m   kubelet            Created container flexvol-driver
  Normal   Started    22m   kubelet            Started container flexvol-driver
  Normal   Pulled     22m   kubelet            Container image "quay.io/calico/cni:v3.26.0" already present on machine
  Normal   Created    22m   kubelet            Created container install-cni
  Normal   Started    22m   kubelet            Started container install-cni
  Warning  Unhealthy  22m   kubelet            Readiness probe failed: calico/node is not ready: felix is not ready: Get "http://localhost:9099/readiness": dial tcp 127.0.0.1:9099: connect: connection refused
W0726 19:10:03.593464      18 feature_gate.go:241] Setting GA feature gate ServiceInternalTrafficPolicy=true. It will be removed in a future release.
  Warning  Unhealthy  22m  kubelet  Readiness probe failed: calico/node is not ready: felix is not ready: Get "http://localhost:9099/readiness": dial tcp 127.0.0.1:9099: connect: connection refused
W0726 19:10:04.585214      31 feature_gate.go:241] Setting GA feature gate ServiceInternalTrafficPolicy=true. It will be removed in a future release.
  Warning  Unhealthy  21m  kubelet  Readiness probe failed: calico/node is not ready: felix is not ready: Get "http://localhost:9099/readiness": dial tcp 127.0.0.1:9099: connect: connection refused
W0726 19:10:11.000953      45 feature_gate.go:241] Setting GA feature gate ServiceInternalTrafficPolicy=true. It will be removed in a future release.
  Warning  Unhealthy  21m  kubelet  Readiness probe failed: calico/node is not ready: felix is not ready: Get "http://localhost:9099/readiness": dial tcp 127.0.0.1:9099: connect: connection refused
W0726 19:10:21.005574      59 feature_gate.go:241] Setting GA feature gate ServiceInternalTrafficPolicy=true. It will be removed in a future release.
  Normal   Killing    21m  kubelet  Container calico-node failed liveness probe, will be restarted
  Warning  Unhealthy  21m  kubelet  Readiness probe failed: calico/node is not ready: felix is not ready: Get "http://localhost:9099/readiness": dial tcp 127.0.0.1:9099: connect: connection refused
W0726 19:10:31.006689      72 feature_gate.go:241] Setting GA feature gate ServiceInternalTrafficPolicy=true. It will be removed in a future release.
  Warning  Unhealthy  21m  kubelet  Readiness probe failed: calico/node is not ready: felix is not ready: Get "http://localhost:9099/readiness": dial tcp 127.0.0.1:9099: connect: connection refused
W0726 19:10:31.083874      98 feature_gate.go:241] Setting GA feature gate ServiceInternalTrafficPolicy=true. It will be removed in a future release.
  Normal   Pulled     21m (x2 over 22m)  kubelet  Container image "quay.io/calico/node:v3.26.0" already present on machine
  Normal   Started    21m (x2 over 22m)  kubelet  Started container calico-node
  Normal   Created    21m (x2 over 22m)  kubelet  Created container calico-node
  Warning  Unhealthy  21m                kubelet  Readiness probe failed: calico/node is not ready: felix is not ready: Get "http://localhost:9099/readiness": dial tcp 127.0.0.1:9099: connect: connection refused
W0726 19:10:36.641655      17 feature_gate.go:241] Setting GA feature gate ServiceInternalTrafficPolicy=true. It will be removed in a future release.
  Warning  Unhealthy  21m  kubelet  Readiness probe failed: calico/node is not ready: felix is not ready: Get "http://localhost:9099/readiness": dial tcp 127.0.0.1:9099: connect: connection refused
W0726 19:10:37.673517      31 feature_gate.go:241] Setting GA feature gate ServiceInternalTrafficPolicy=true. It will be removed in a future release.
  Warning  Unhealthy  21m (x4 over 22m)   kubelet  Liveness probe failed: Get "http://localhost:9099/liveness": dial tcp 127.0.0.1:9099: connect: connection refused
  Warning  Unhealthy  17m (x35 over 21m)  kubelet  (combined from similar events): Readiness probe failed: calico/node is not ready: felix is not ready: readiness probe reporting 503
W0726 19:15:01.002831     478 feature_gate.go:241] Setting GA feature gate ServiceInternalTrafficPolicy=true. It will be removed in a future release.`

## Steps to Reproduce (for bugs)
1. Assuming you are running an EKS cluster on multi-AZ (subnet). Using AWS FIS create an experiment to fully disable a subnet for a period of time (30 min for example)
2. Add a newer node to the cluster on an operational AZ

## Your Environment
* Calico version: 2.36.1
* Orchestrator version (e.g. kubernetes, mesos, rkt): EKS 1.27
* Operating System and version: EKS ami

**Comment by caseydavenport** [comment]
> Failed to get config from datastore error=Get "https://172.20.0.1:443/apis/crd.projectcalico.org/v1/clusterinformations/default": dial tcp 172.20.0.1:443: i/o timeout 2023-07-26 19:12:07.564 

The error seems to be a problem accessing the API server - is the network functioning between the node that Calico is running on and the EKS API server?

Is kube-proxy functioning on those node? This feels likely to be a node networking issue in some capacity.
