### ISSUE TITLE
Felix has broken code to handle configuration changes

### ISSUE THREAD

**Issue by plwhite** [projectcalico/calico#789]
In fetcd.py, there is the following comment.

        # Configuration keys.  If these change, by default, we'll die and
        # let the init daemon restart us.

But the comment does not match the code. Specifically, below that line the code to handle config parameters changing doesn't exit, but instead just does a (useless) resync.

Trivial fix, but needs to be properly tested.

**Comment by fasaxc** [comment]
@plwhite the resync triggers a re-read of the config and then we spot that it had changed and die.  Bad comment only or have you seen it fail to restart?

**Comment by plwhite** [comment]
Yes, agreed. Comment is just misleading.
