### ISSUE TITLE
upgrade calico from 3.23 to 3.26 doesn't work

### ISSUE THREAD

**Issue by kombiwagon** [projectcalico/calico#7890]
Hi,
I have installed calicoVersion: v3.23.1 on kubernetes: 1.24.8. 
My installation way is: Tigera Calico operator and custom resource definitions.
I was trying upgrade calico version to 3.26 in this way: https://docs.tigera.io/calico/latest/operations/upgrading/kubernetes-upgrade#upgrading-an-installation-that-uses-the-operator and the result is below:
###############
namespace/tigera-operator replaced
customresourcedefinition.apiextensions.k8s.io/bgpconfigurations.crd.projectcalico.org replaced
customresourcedefinition.apiextensions.k8s.io/bgppeers.crd.projectcalico.org replaced
customresourcedefinition.apiextensions.k8s.io/blockaffinities.crd.projectcalico.org replaced
customresourcedefinition.apiextensions.k8s.io/caliconodestatuses.crd.projectcalico.org replaced
customresourcedefinition.apiextensions.k8s.io/clusterinformations.crd.projectcalico.org replaced
customresourcedefinition.apiextensions.k8s.io/felixconfigurations.crd.projectcalico.org replaced
customresourcedefinition.apiextensions.k8s.io/globalnetworkpolicies.crd.projectcalico.org replaced
customresourcedefinition.apiextensions.k8s.io/globalnetworksets.crd.projectcalico.org replaced
customresourcedefinition.apiextensions.k8s.io/hostendpoints.crd.projectcalico.org replaced
customresourcedefinition.apiextensions.k8s.io/ipamblocks.crd.projectcalico.org replaced
customresourcedefinition.apiextensions.k8s.io/ipamconfigs.crd.projectcalico.org replaced
customresourcedefinition.apiextensions.k8s.io/ipamhandles.crd.projectcalico.org replaced
customresourcedefinition.apiextensions.k8s.io/ippools.crd.projectcalico.org replaced
customresourcedefinition.apiextensions.k8s.io/ipreservations.crd.projectcalico.org replaced
customresourcedefinition.apiextensions.k8s.io/kubecontrollersconfigurations.crd.projectcalico.org replaced
customresourcedefinition.apiextensions.k8s.io/networkpolicies.crd.projectcalico.org replaced
customresourcedefinition.apiextensions.k8s.io/networksets.crd.projectcalico.org replaced
customresourcedefinition.apiextensions.k8s.io/apiservers.operator.tigera.io replaced
customresourcedefinition.apiextensions.k8s.io/imagesets.operator.tigera.io replaced
customresourcedefinition.apiextensions.k8s.io/installations.operator.tigera.io replaced
customresourcedefinition.apiextensions.k8s.io/tigerastatuses.operator.tigera.io replaced
serviceaccount/tigera-operator replaced
clusterrole.rbac.authorization.k8s.io/tigera-operator replaced
clusterrolebinding.rbac.authorization.k8s.io/tigera-operator replaced
deployment.apps/tigera-operator replaced
Error from server (NotFound): error when replacing "tigera-operator.yaml": customresourcedefinitions.apiextensions.k8s.io "bgpfilters.crd.projectcalico.org" not foundkd
################
It seems on the first glance that everything is ok but my 'calico-node' pods didn't update to new version and customresourcedefinition also.
what am i doing wrong ? It seems that I've done exactly what documentation says. Maybe I shoud delete all customresourcedefinition handly and recreate again but i afraid it is not safety

**Comment by paulcosma** [comment]
I've run into the same issue when upgrading from v3.25.1 to v3.26.1

I've deleted the operator and installed again
kubectl delete -f https://raw.githubusercontent.com/projectcalico/calico/v3.26.1/manifests/tigera-operator.yaml
kubectl create -f https://raw.githubusercontent.com/projectcalico/calico/v3.26.1/manifests/tigera-operator.yaml

I've created the manifest and installed calico after that as per https://docs.tigera.io/calico/latest/getting-started/kubernetes/self-managed-onprem/onpremises

**Comment by caseydavenport** [comment]
> Error from server (NotFound): error when replacing "tigera-operator.yaml": customresourcedefinitions.apiextensions.k8s.io "bgpfilters.crd.projectcalico.org" not foundkd

`replace` won't work for resources that weren't present in the previous version, in this case `BGPFilter` was introduced in v3.26 and didn't exist in v3.25

Probably need to `kubectl create` that particular resource.

**Comment by sorrison** [comment]
I've just found this bug after following the docs at https://docs.tigera.io/calico/latest/operations/upgrading/kubernetes-upgrade#upgrading-an-installation-that-uses-the-operator

Is there some more detailed instructions on how to do this somewhere that I'm missing?

**Comment by raghav19** [comment]
The right way is to use the CRD install step given at https://docs.tigera.io/calico/latest/operations/upgrading/kubernetes-upgrade#all-other-upgrades using server side apply. Seems to be a docs bug for operator upgrade step.
