### ISSUE TITLE
Bird and bgpd port conflict

### ISSUE THREAD

**Issue by iamejboy** [projectcalico/calico#7893]
if bgpd bound to port 179 during startup, bird will fail to start

## Expected Behavior

bgpd should not pick up port 179

bgpd should not pick a port similar to other processes especially bird or vice versa

## Current Behavior

During installation, I noticed the node status to "Error: No listening socket"
```
+---------------+-------------------+-------+----------+----------------------------+
| PEER ADDRESS  |     PEER TYPE     | STATE |  SINCE   |            INFO            |
+---------------+-------------------+-------+----------+----------------------------+
| 10.5.4.136 | node-to-node mesh | down  | 06:44:51 | Error: No listening socket |
| 10.5.4.135 | node-to-node mesh | down  | 06:44:51 | Error: No listening socket |
| 10.5.4.138 | node-to-node mesh | down  | 06:44:51 | Error: No listening socket |
+---------------+-------------------+-------+----------+----------------------------+

# netstat -nutap | grep 179
tcp        0      0 0.0.0.0:179             0.0.0.0:*               LISTEN      1522/bgpd
```

## Possible Solution

Workaround if happened, make bird listen to other port
apiVersion: projectcalico.org/v3
```
kind: BGPConfiguration
metadata:
  name: default
spec:
  listenPort: 178
```

## Steps to Reproduce (for bugs)

Calico installation

## Your Environment

* Calico version 3.26(latest)
* Orchestrator version (e.g. kubernetes, mesos, rkt): kubernetes
* Operating System and version: FCOS38
* Link to your project (optional):

**Comment by caseydavenport** [comment]
This is working as expected - BIRD is a BGP daemon and so defaults to the default BGP port.

As you discovered, there is a configuration option to change this if you need.

https://docs.tigera.io/calico/latest/reference/resources/bgpconfig
