### ISSUE TITLE
calico-node pod readiness-probe times out. Value discrepancy between operator and generated manifests

### ISSUE THREAD

**Issue by Josh-Tigera** [projectcalico/calico#7895]
A community user reported that some of their calico-node pods were not reaching "Ready". Investigation and debugging led us to discover that the `/bin/calico-node -bird-ready -felix-ready` command was timing out with the operator-set timeout value of 5s. When instructed to use the annotation that prevents the operator from reverting changes to managed resources and increasing the calico-node readiness probe timeout value to 10s all calico-node pods reached ready state. Given this it seems that 10s would be a more appropriate value, and the discrepancy between what the operator is setting (https://github.com/tigera/operator/blob/feature-mt/pkg/render/node.go#L1752) and what our generated manifests show (https://github.com/projectcalico/calico/blob/master/manifests/calico.yaml#L4909) should be investigated and reconciled.

## Expected Behavior

-calico-node pods reach ready state
-operator-set value for readiness probe timeout value equals readiness probe timeout value from generated manifests

## Current Behavior

-calico-node pods readiness probe times out
-operator-set value for readiness probe is 5s, generated manifests readiness probe timeout value is 10s

## Possible Solution

-Change operator-set readiness probe timeout value to 10s to agree with generated manifest values

## Steps to Reproduce (for bugs)

Unsure. Only some of the user's calico-node pods were timing out and they indicated there was nothing specifically unique about those nodes that would cause a significantly longer processing delay. It's possible that 5s is simply too aggressive a timeout value, but  that could be verified when the discrepancy between manifest and operator-set values is looked at.

## Context

Occurred during upgrade from v3.24.1 to v3.26.1

## Your Environment

* Calico version: v3.24.1 upgrading to v3.26.1
* Orchestrator version (e.g. kubernetes, mesos, rkt): k3s
* Operating System and version:
* Link to your project (optional):

**Comment by MichalFupso** [comment]
Changes have been delivered to 3.25 https://github.com/tigera/operator/pull/2827

**Comment by mimmus** [comment]
Probably same issue (with same version 3.24.1).
As I'm unable to upgrade soon, how can I set readinessProbe timeout to 10s, when tigera-operator is active?
