### ISSUE TITLE
Pod to Host networking is broken when workers have multiple network interfaces

### ISSUE THREAD

**Issue by satishpasumarthi** [projectcalico/calico#7899]
I've setup a kubeadm cluster with calico CNI (v3.25). I have two worker nodes (worker A and worker B) where each node has multiple network cards (4). I launched a pod (say podA) from workerA. 

## Expected Behavior
- podA should be able to ping workerA
- workerA should be able to ping podA

## Current Behavior
- podA can ping controller
- podA can ping workerB
- controller can ping podA
- podA **cannot** ping workerA
- workerA **cannot** ping podA
- podA is able to connect to internet.

## Steps to Reproduce (for bugs)
1. Setup a kubeadm cluster with 2 worker nodes. Worker node should have multiple network cards.
2. Submit a job (pod) onto one worker and try to ping the pod from the host.

## Your Environment

* Calico version 3.25
* Orchestrator version (e.g. kubernetes, mesos, rkt): kubeadm v1.27
* Operating System and version: Ubuntu 20.04

**Comment by csantanapr** [comment]
Hi @hasonhai I work with @satishpasumarthi 
We are already using `IP_AUTODETECTION_METHOD:            can-reach=xxx.xxx.xxx.xxx` 
We updated to v3.26.1 
And we still have the problem that kubelet can't reach the pod IP on the same host, other hosts can reach the Pod IP

**Comment by satishpasumarthi** [comment]
In AWS, for multi NIC instances there is a route table assigned with each NIC. The above issue was resolved after
 adding `ip r add throw <POD_CIDR> table <ROUTE_TABLE>` for route table of the NIC.

**Comment by xiaosuiba** [comment]
> In AWS, for multi NIC instances there is a route table assigned with each NIC. The above issue was resolved after adding `ip r add throw <POD_CIDR> table <ROUTE_TABLE>` for route table of the NIC.

Thanks for your instructions, we have the same problem and your reply saved my day!
