### ISSUE TITLE
Struggling to find networking view of how Pod CIDR is carved up and routed

### ISSUE THREAD

**Issue by engelr1974** [projectcalico/calico#791]
Infrastructure Admins are asking for diagrams of how Calico is assigning sections of the Pod CIDR block across hosts, and how Pod-to-Pod networking is accomplished.  I'm not finding the type of view they are asking for on http://docs.projectcalico.org/ or in more general searches either.

## Expected Behavior
These Admins have pointed out some diagrams they are seeing for Flannel, and asking to see a similar view of Calico:  https://image.slidesharecdn.com/dockernetworking201-141219121503-conversion-gate02/95/tutorial-on-using-coreos-flannel-for-docker-networking-5-638.jpg?cb=1426786746 

## Current Behavior
I see some material along these lines at the following location:  http://docs.projectcalico.org/v1.6/reference/without-docker-networking/docker-container-lifecycle
However, they don't show the flow of the request to the level of detail I am being asked for.

**Comment by ozdanborne** [comment]
@engelr1974 It's still a work in progress, but I think this covers what you are looking for: 
https://github.com/projectcalico/calico/pull/760/files

**Comment by engelr1974** [comment]
Yes, I agree that is on the right path to making the container networking clearer, and I'll grab a download of that diagram for now, while this continues to be matured.  Thanks.
