### ISSUE TITLE
Calico network does not work properly when vSwitch (of the Hyper-V host of the VM host) is not enabled with Promiscuous mode

### ISSUE THREAD

**Issue by hasonhai** [projectcalico/calico#7915]
## Expected Behavior

Our Kubernetes setup running on top of a group of VMs that provided by a group of Hyper-V hosts.
We installed Calico with the default setting: https://[raw.githubusercontent.com/projectcalico/calico/v3.26.1/manifests/calico.yaml](https://raw.githubusercontent.com/projectcalico/calico/v3.26.1/manifests/calico.yaml)
Our VM run RHEL7 with iptables-legacy.
The Kubernetes cluster is installed by KubeADM. 

After completing the setup, we found that the network between pod to pod is not working correctly. Only pods on the same VM host can communicate to each others. Pods between VM hosts are not able to talk to each others. However, our VMs can connect to each others and work normally. After debugging, we found that the packages were dropped at the vSwitch. We have to enable the vSwitch to Promiscuous mode to let the packages passing through.

My question is:
* Is it mandatory to have Promiscuous Mode enabled in the vSwitch to have the Calico network working?
* Why do we need "Promiscuous Mode"?
* Is there a way to avoid using Promiscuous mode in the vSwitch? My company policy is very strict for using promiscuous mode.

Sorry if the questions are unclear. I'm not really good at computer networking so I don't know if my explanation make the questions more confusing.   

## Current Behavior

Network between pod-to-pod does not work if the vSwitch is not enabled with Promiscuous Mode

## Possible Solution

Enabling Promiscuous Mode

## Your Environment

* Calico version: v3.26.1
* Orchestrator version (e.g. kubernetes, mesos, rkt): Kubernetes v1.24.13
* Operating System and version: RHEL7, Kernel 3.10.0-1160.95.1.el7.x86_64
* Link to your project (optional):

**Comment by mazdakn** [comment]
Calico routes pod's traffic from a node to another. By enabling promiscuous mode, you are basically changing vSwitch to a pure layer 2 switch that passes all traffic to all ports, which is not the way it's supposed to be.

You can fix this by one of this approaches:
- Enable an overlay (ipip,vxlan) in Calico: https://docs.tigera.io/calico/next/networking/configuring/vxlan-ipip
- Enable mesh BGP between your nodes: https://docs.tigera.io/calico/next/networking/configuring/bgp#common-bgp-topologies
- Any other way in your tools to make sure pod cidrs are reachable from each node.

**Comment by mazdakn** [comment]
Feel free to re-open if you think you question is not answered.

**Comment by mazdakn** [comment]
Perfect. Thanks @hasonhai for the update.
