### ISSUE TITLE
The Pod network connection fails due to the use of traffic shaping plugin 

### ISSUE THREAD

**Issue by haoyann** [projectcalico/calico#7917]
## Expected Behavior

Use traffic shaping plugin pod network is normal.

## Current Behavior

Use traffic shaping

Pod Config
```
    kubernetes.io/egress-bandwidth: 1M
    kubernetes.io/ingress-bandwidth: 1M
```
Node Config
```
{
  "name": "k8s-pod-network",
  "cniVersion": "0.3.1",
  "plugins": [
    {
      "type": "calico",
      "log_level": "info",
      "log_file_path": "/var/log/calico/cni/cni.log",
      "datastore_type": "kubernetes",
      "nodename": "szth-205-68-70.linux.17usoft.com",
      "mtu": 0,
      "ipam": {
          "type": "calico-ipam"
      },
      "policy": {
          "type": "k8s"
      },
      "kubernetes": {
          "kubeconfig": "/etc/cni/net.d/calico-kubeconfig"
      }
    },
    {
      "type": "portmap",
      "snat": true,
      "capabilities": {"portMappings": true}
    },
    {
      "type": "bandwidth",
      "capabilities": {"bandwidth": true}
    }
  ]

```

The network is normal at the beginning of the pod, but the network is abnormal after running for a period of time.

WorkloadEndpoint

```
- apiVersion: projectcalico.org/v3
  kind: WorkloadEndpoint
  metadata:
    creationTimestamp: "2023-08-10T08:46:13Z"
    generateName: offline.stress12-5b97ff44f9-
    labels:
      pod-template-hash: 5b97ff44f9
      projectcalico.org/namespace: offline
      projectcalico.org/orchestrator: k8s
      projectcalico.org/serviceaccount: default
      service.name: offline.stress12
      tche.aos.io/pod-type: offline
    name: szth--205--68--70.linux.17usoft.com-k8s-offline.stress12--5b97ff44f9--xrfvj-eth0
    namespace: offline
    resourceVersion: "737263614"
    uid: c33deadf-78aa-4939-a363-f61817691810
  spec:
    containerID: e067fc9775b0fba7e7cbd8326f1a88e175bd5f207dc5d0755b91f9d66d761ce0
    endpoint: eth0
    interfaceName: calib9cb277d6c8
    ipNetworks:
    - 10.204.206.129/32
    node: szth-205-68-70.linux.17usoft.com
    orchestrator: k8s
    pod: offline.stress12-5b97ff44f9-xrfvj
    profiles:
    - kns.offline
    - ksa.offline.default
    serviceAccountName: default
```

This is the tc rule
<img width="630" alt="image" src="https://github.com/projectcalico/calico/assets/43994656/2e097ddd-7e12-4c29-9e2e-f20fc01898b9">

ifconfig

<img width="531" alt="image" src="https://github.com/projectcalico/calico/assets/43994656/f44d39e0-7287-446b-ab28-ac781dde8962">

arp
<img width="466" alt="image" src="https://github.com/projectcalico/calico/assets/43994656/7c678727-26e5-4b08-920a-1538c854de52">

It was found that the arp table of the pod network was lost. 
Why is this happening? hope to get help.
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Calico version v3.22.1 
* Orchestrator version (e.g. kubernetes, mesos, rkt): kubernetes v1.22.7
* Operating System and version: CentOS Linux 7 5.10.109-1.el7.x86_64 
* Link to your project (optional):

**Comment by tomastigera** [comment]
> The network is normal at the beginning of the pod, but the network is abnormal after running for a period of time.

Do you have nay more insights into what might happen between normal and abnormal? Afaict there should be no conflict between calico and qdisc.
