### ISSUE TITLE
Reduce default k8s vagrant demo cluster to 1 master, 1 node

### ISSUE THREAD

**Issue by ozdanborne** [projectcalico/calico#792]
There's no need to launch 2 nodes so long as we can schedule pods by default on the master.

Can we ensure there are no taints on the master and then scale down to 1 node by default?

**Comment by caseydavenport** [comment]
@ozdanborne IIRC this was chosen because some of our demos required the extra node, and the master didn't have enough capacity for master components and real workloads.  

Worth a shot though - I could definitely be misremembering.

**Comment by ozdanborne** [comment]
I'd wonder why we couldn't just increase mem and cpu on the two boxes instead of spreading it across 3 then...

**Comment by caseydavenport** [comment]
Yeah, not really sure tbh.

**Comment by caseydavenport** [comment]
We've removed the vagrant demo in favor of the kubeadm quickstart.
