### ISSUE TITLE
Issue while installation of calico 3.26 on with kubadm v1.27.0

### ISSUE THREAD

**Issue by jinaloo7** [projectcalico/calico#7925]
Hi all i am facing an issue with calico install with kubeadm.
I am trying to use only IPv6 mode by using public IP to assign node and private ip to assign pods.the calico nodes are getting up and running but dns pods are not and stays in pending state only.let me share the logs below.any help would be appreciated thank you.
I am running kubernetes 1.27

> ubuntu@xyz:~$ kubectl describe node xyz
> Name:               xyz
> Roles:              control-plane
> Labels:             beta.kubernetes.io/arch=amd64
>                     beta.kubernetes.io/os=linux
>                     kubernetes.io/arch=amd64
>                     kubernetes.io/hostname=xyz
>                     kubernetes.io/os=linux
>                     node-role.kubernetes.io/control-plane=
>                     node.kubernetes.io/exclude-from-external-load-balancers=
> Annotations:        kubeadm.alpha.kubernetes.io/cri-socket: unix:///var/run/containerd/containerd.sock
>                     node.alpha.kubernetes.io/ttl: 0
>                     volumes.kubernetes.io/controller-managed-attach-detach: true
> CreationTimestamp:  Mon, 07 Aug 2023 04:37:27 -0400
> Taints:             node.kubernetes.io/not-ready:NoSchedule
> Unschedulable:      false
> Lease:
>   HolderIdentity:  xyz
>   AcquireTime:     <unset>
>   RenewTime:       Mon, 07 Aug 2023 11:57:34 -0400
> Conditions:
>   Type             Status  LastHeartbeatTime                 LastTransitionTime                Reason                       Message
>   ----             ------  -----------------                 ------------------                ------                       -------
>   MemoryPressure   False   Mon, 07 Aug 2023 11:56:23 -0400   Mon, 07 Aug 2023 04:37:26 -0400   KubeletHasSufficientMemory   kubelet has sufficient memory available
>   DiskPressure     False   Mon, 07 Aug 2023 11:56:23 -0400   Mon, 07 Aug 2023 04:37:26 -0400   KubeletHasNoDiskPressure     kubelet has no disk pressure
>   PIDPressure      False   Mon, 07 Aug 2023 11:56:23 -0400   Mon, 07 Aug 2023 04:37:26 -0400   KubeletHasSufficientPID      kubelet has sufficient PID available
>   Ready            False   Mon, 07 Aug 2023 11:56:23 -0400   Mon, 07 Aug 2023 04:37:26 -0400   KubeletNotReady              container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:Network plugin returns error: cni plugin not initialized
> Addresses:
>   InternalIP:  (Public IPv6)
>   Hostname:    xyz
> Capacity:
>   cpu:                4
>   ephemeral-storage:  489629688Ki
>   hugepages-1Gi:      0
>   hugepages-2Mi:      0
>   memory:             32837976Ki
>   pods:               110
> Allocatable:
>   cpu:                4
>   ephemeral-storage:  451242719714
>   hugepages-1Gi:      0
>   hugepages-2Mi:      0
>   memory:             32735576Ki
>   pods:               110
> System Info:
>   Machine ID:                 2bf8e6335cf748618ed406bb495d80ed
>   System UUID:                00000000-0000-0000-0000-3CECEF4A432E
>   Boot ID:                    5c5dd4d6-4299-4898-ae17-f3665c0a81fe
>   Kernel Version:             4.15.0-213-generic
>   OS Image:                   Ubuntu 18.04.6 LTS
>   Operating System:           linux
>   Architecture:               amd64
>   Container Runtime Version:  containerd://1.6.12
>   Kubelet Version:            v1.27.4
>   Kube-Proxy Version:         v1.27.4
> PodCIDR:                      fc00:32c0:1008:c3::/64
> PodCIDRs:                     fc00:32c0:1008:c3::/64
> Non-terminated Pods:          (6 in total)
>   Namespace                   Name                               CPU Requests  CPU Limits  Memory Requests  Memory Limits  Age
>   ---------                   ----                               ------------  ----------  ---------------  -------------  ---
>   kube-system                 etcd-xyz                          100m (2%)     0 (0%)      100Mi (0%)       0 (0%)         7h20m
>   kube-system                 kube-apiserver-xyz                250m (6%)     0 (0%)      0 (0%)           0 (0%)         7h20m
>   kube-system                 kube-controller-manager-xyz        200m (5%)     0 (0%)      0 (0%)           0 (0%)         7h20m
>   kube-system                 kube-proxy-5ggj4                   0 (0%)        0 (0%)      0 (0%)           0 (0%)         7h19m
>   kube-system                 kube-scheduler-xyz               100m (2%)     0 (0%)      0 (0%)           0 (0%)         7h20m
>   tigera-operator             tigera-operator-5f4668786-fff7w    0 (0%)        0 (0%)      0 (0%)           0 (0%)         6h49m
> Allocated resources:
>   (Total limits may be over 100 percent, i.e., overcommitted.)
>   Resource           Requests    Limits
>   --------           --------    ------
>   cpu                650m (16%)  0 (0%)
>   memory             100Mi (0%)  0 (0%)
>   ephemeral-storage  0 (0%)      0 (0%)
>   hugepages-1Gi      0 (0%)      0 (0%)
>   hugepages-2Mi      0 (0%)      0 (0%)
> Events:              <none>
> ubuntu@cn3:~$ 

I am seeing this taint which blocks from scheduling pods Taints:             [node.kubernetes.io/not-ready:NoSchedule](http://node.kubernetes.io/not-ready:NoSchedule) I try to untainted that and it is showing untainted for a second and than again gets tainted.Meanwhile the pods are going into container-creating state but could not able to get properly running and throws the following error.

> cat custom-resources.yaml
> # This section includes base Calico installation configuration.
> # For more information, see: https://projectcalico.docs.tigera.io/master/reference/installation/api#operator.tigera.io/v1.Installation
> apiVersion: operator.tigera.io/v1
> kind: Installation
> metadata:
>  name: default
> spec:
>  # Configures Calico networking.
>  calicoNetwork:
>   # Note: The ipPools section cannot be modified post-install.
>   ipPools:
>   - blockSize: 122
>    cidr: fc00:32c0:1008:c3::/64
>    encapsulation: None
>    natOutgoing: Enabled
>    nodeSelector: all()
> 
> ---
> 
> # This section configures the Calico API server.
> # For more information, see: https://projectcalico.docs.tigera.io/master/reference/installation/api#operator.tigera.io/v1.APIServer
> apiVersion: operator.tigera.io/v1
> kind: APIServer
> metadata:
>  name: default
> spec: {}
>

**Comment by mgleung** [comment]
Hey @jinaloo7 , could you perhaps post the logs from you calico-node pods as well? Based on what you've mentioned about the DNS pods staying in "pending" state, I think that it's likely that either the calico-node pods are erroring or not starting. If the calico-node pods aren't available, could you post the operator pod logs so we can see what's holding that up?
