### ISSUE TITLE
Typha, Apiserver and controller unstable after upgrading to calico 3.25.1

### ISSUE THREAD

**Issue by bbharat3** [projectcalico/calico#7938]
We are upgrading calico from 3.23.3 to 3.25.1
After the upgrade, we observed that the pods for typha, calico-kube-controller and apiserver are continuously terminating and replaced with new pods. However the same is not observed in 3.25.0.

## Expected Behavior
It should stable like 3.25.0

## Current Behavior
we observed that the pods for typha, calico-kube-controller and apiserver are continuously terminating and replaced with new pods in calico 3.25.1

## Possible Solution
Don't know yet.

## Steps to Reproduce (for bugs)
1. upgrade to calico 3.25.1 (inline or direct upgrade)

## Context
We are upgrading  calico as a part of EKS upgrade to 1.26

**Comment by mazdakn** [comment]
Could be related to https://github.com/projectcalico/calico/issues/7748

**Comment by coutinhop** [comment]
@bbharat3 can you post more details, like logs and `kubectl describe` for the crashlooping pods?
