### ISSUE TITLE
update to tigera status conflicted in logs

### ISSUE THREAD

**Issue by ankit-arora-369** [projectcalico/calico#7947]
We upgraded Calico v3.25.0 from 3.23.3 in one of our test ENV and we are seeing the below logs in tigera-operator pods:

"{"level":"info","ts":1692560484.9176748,"logger":"status_manager","msg":"update to tigera status conflicted, retrying","reason":"Operation cannot be fulfilled on tigerastatuses.operator.tigera.io \"calico\": the object has been modified; please apply your changes to the latest version and try again"}"

Does that me anything is wrong and we should be worried about?

## Expected Behavior
We should not be seeing these logs if everything is working fine.

## Current Behavior
Functionality of Calico looks fine and pods are also getting the IPs. We have disable CSI as we didn't need it.

## Possible Solution
If it's okay to get these logs then we should not print them as it's confusing.

## Steps to Reproduce (for bugs)
1. Upgrade to version 3.25.0
2.
3.
4.

## Context
I just want to confirm that it's not an issue in the current running setup.

## Your Environment
* Calico version : 3.25.0
* Orchestrator version (e.g. kubernetes, mesos, rkt): EKS v1.23
* Operating System and version: Amazon Linux 2
* Link to your project (optional):

**Comment by tomastigera** [comment]
The operation got retried and so long as they're not seeing this continuously, its all fine. Does the issue persist?

**Comment by caseydavenport** [comment]
Yeah, this is normal so long as it isn't clogging your logs up. It just means two things tried to update the same object at the same time, and one will need to retry. (note it's at "info" log level and not at "error" level).

This PR downgrades the log level: https://github.com/tigera/operator/pull/2902
