### ISSUE TITLE
Improve Calico-IPAM Docs

### ISSUE THREAD

**Issue by ozdanborne** [projectcalico/calico#795]
(Condensing the information from #63 into a new issue.)

Need a doc that explains, for Calico IPAM:
- the philosophy behind its behavior
- why one would use it
- what it does
- how it does it. Specifically:
   - How the IPAM module assigns blocks and pools

**Comment by caseydavenport** [comment]
https://docs.projectcalico.org/v3.10/networking/get-started-ip-addresses
