### ISSUE TITLE
Encrypt in-cluster pod traffic Documentation - AKS 

### ISSUE THREAD

**Issue by cloud-az** [projectcalico/calico#7965]
Which CNI pluggings are supported for "_Inter-node pod_" and "_Inter-node, host-network_" traffic encryption with WireGuard in AKS?
## Expected Behavior

Only Azure CNI.

## Current Behavior
[Documentation](https://docs.tigera.io/calico/latest/network-policy/encrypt-cluster-pod-traffic) of "Encrypt in-cluster pod traffic" does not specify which CNIs are supported for AKS in the latest version (3.26).

**Comment by cloud-az** [comment]
@caseydavenport I am stuck, could you please provide information here?

**Comment by caseydavenport** [comment]
@cloud-az sorry for the long delay here. Why is your expectation that only the Azure CNI plugin is supported?

based on that documentation, it seems clear to me which options aren't supported:

```
Encrypted same-node pod traffic
GKE
Using your own custom keys to encrypt traffic
```

This seems to clearly show that we should expect all Calico modes to support Wireguard on AKS.

**Comment by cloud-az** [comment]
The reason for I am asking is that in your documentation for version 1.25: https://docs.tigera.io/calico/3.25/network-policy/encrypt-cluster-pod-traffic we see only **Azure CNI** is supported. But now it is not specified which version CNI is supported

**Comment by caseydavenport** [comment]
I just checked with the team on this one. This is the PR that changed it: https://github.com/projectcalico/calico/pull/7081/

The doc is in flux, but the expectation is that any platform using Calico CNI will work for inter-node pod encryption. Inter-node host encryption should only be used for the Azure CNI plugin, though.

**Comment by cloud-az** [comment]
Thank you!
"_The expectation is that any platform using **Calico CNI** will work for inter-node pod encryption_".

Can you please clarify if there is support for _inter-node pod_ or _inter-node host_ encryption when using Calico as an **extension** with either '**Azure CNI Overlay**' or '**Kubenet**' in Azure Kubernetes Service?

**Comment by caseydavenport** [comment]
For Azure CNI overlay, you can expect Wireguard to work - you will want to enable the inter-node host encryption when doing so.

For Kubenet, AKS actually uses Calico under the covers. However, it uses host-local IPAM and I am not 100% sure that wireguard is compatible with that.
