### ISSUE TITLE
Windows: EC2 platform detection not working with IMDSv2

### ISSUE THREAD

**Issue by davidgiga1993** [projectcalico/calico#7969]
When installing calico on windows (on EC2) it doesn't detect the platform type correctly.
[The detection](https://github.com/projectcalico/calico/blob/master/node/windows-packaging/CalicoWindows/libs/calico/calico.psm1#L480C68-L480C99) doesn't handle the IMDSv2 endpoint correctly.

## Expected Behavior
```
Get-PlatformType
ec2
```

## Current Behavior
```
Get-PlatformType
bare-metal
```

## Possible Solution
```
$token = Invoke-RestMethod -Headers @{"X-aws-ec2-metadata-token-ttl-seconds" = "21600"} -Method PUT -Uri http://169.254.169.254/latest/api/token -ErrorAction Ignore
Invoke-RestMethod -Headers @{"X-aws-ec2-metadata-token" = $token} -uri http://169.254.169.254/latest/meta-data/local-hostname -ErrorAction Ignore
```

## Steps to Reproduce (for bugs)
1. Install calico on a windows node
2. The ec2 metadata endpoint will not work afterwards, since the platform type has been detected as `bare-metal` instead of `ec2`

## Context
Manual route fixing required to make the ec2 metadata endpoint work again.

## Your Environment
* Calico version 3.26.1
* Orchestrator version (e.g. kubernetes, mesos, rkt): k8s v1.27.4
* Operating System and version: Windows Server Core 2022

**Comment by mazdakn** [comment]
pinging @coutinhop
