### ISSUE TITLE
Calico upgrade failed on kubernetes 1.28.1

### ISSUE THREAD

**Issue by urbaman** [projectcalico/calico#7971]
Upgraded calico as per this guide:
https://docs.tigera.io/calico/latest/operations/upgrading/kubernetes-upgrade#upgrading-an-installation-that-uses-the-operator

The pods are failing with a lot of permission problems:

```
NAME                                       READY   STATUS                  RESTARTS        AGE
calico-kube-controllers-7ddc4f45bc-w82fs   0/1     CrashLoopBackOff        9 (5s ago)      23m
calico-node-5kjps                          0/1     Init:CrashLoopBackOff   8 (35s ago)     16m
calico-node-6jdng                          0/1     Init:CrashLoopBackOff   8 (31s ago)     16m
calico-node-9vj84                          0/1     Init:CrashLoopBackOff   8 (28s ago)     16m
calico-node-ndhk4                          0/1     Init:CrashLoopBackOff   8 (25s ago)     16m
calico-node-qbhtt                          0/1     Init:CrashLoopBackOff   8 (32s ago)     16m
calico-node-xfpdh                          0/1     Init:CrashLoopBackOff   8 (17s ago)     16m
```

calico-kube-controllers-7ddc4f45bc-w82fs logs:

`[ERROR][1] client.go 295: Error getting cluster information config ClusterInformation="default" error=connection is unauthorized: clusterinformations.crd.projectcalico.org "default" is forbidden: User "system:serviceaccount:kube-system:calico-kube-controllers" cannot get resource "clusterinformations" in API group "crd.projectcalico.org" at the cluster scope
`
## Expected Behavior

The pods should start flawlessly

## Current Behavior

See logs above

## Steps to Reproduce (for bugs)
1. Upgrade from 1.35.1 to 1.36.1 on kubernetes 1.28.1
2.
3.
4.

## Your Environment

* Calico version 1.35.1 to 1.36.1
* Orchestrator version (e.g. kubernetes, mesos, rkt): kubernetes (kubeadm)
* Operating System and version: Ubuntu 22.04

**Comment by tomastigera** [comment]
Do you have a bit more logs, expecially from calico-nodes? I suppose the versions are 1.25.1 and 1.26.1

**Comment by tomastigera** [comment]
Could you also provide your Installation and tigera-operator logs? Perhaps RBAC is not applied correctly.

**Comment by caseydavenport** [comment]
> Upgrade from 1.35.1 to 1.36.1

What versions are we talking about here? There's no Calico version or tigera/operator version with those numbers.

**Comment by gioguanuo** [comment]
Hello ,
I have an issue with kubernetes 1.28 on virtual box machines equipped with Debian 12.
Installing a cluster with one master and two workers, the two workers perfectly identical, the same installation procedure.
After installing Calico compatible with K8s 1.28 one worker node is ready the second one not ready.
After remove Calico all go in right way.
Some suggest?
Thank you in advance

**Comment by caseydavenport** [comment]
@gioguanuo please open a new issue, sounds unrelated to this one. We'll also need more detailed information about the issues you were encountering, like `kubectl describe` output for the nodes in question.

**Comment by rsoika** [comment]
@gioguanuo , I installed also kubernetes 1.28 on Debian 12 a few days ago without problems. 
You may take a look at [my cloud project](https://github.com/imixs/imixs-cloud/) describing my setup for small clusters. See [this setup guide](https://github.com/imixs/imixs-cloud/blob/master/doc/SETUP.md) and also this [install script for Debian 12](https://github.com/imixs/imixs-cloud/blob/master/scripts/setup_debian.sh). Maybe this helps you.

**Comment by gioguanuo** [comment]
Thank you very much and sorry I haven't time to inform you. Solved many days ago
