### ISSUE TITLE
The pods on Kubernetes cannot access the pod IP addresses on other's nodes.

### ISSUE THREAD

**Issue by opencmit2** [projectcalico/calico#7991]
When I deploy Calico in Kubernetes, the cluster network works fine when I use the ipip mode. However, when I use the vxlan network, some pods on certain nodes cannot ping each other. I want to know ,what problem with me???

when i use  calico vxlan mode
server A pod A ping serverA pod B's ip  ok
server A pod A  ping serverB pod B's  ip  fault

when i use  calico ipip mode
server A pod A ping serverA pod B's ip  ok
server A pod A  ping serverB pod B 's ip  ok

**Comment by brownz11** [comment]
What Kernel and OS are you running?

This sounds like you may be running into https://docs.rke2.io/known_issues#calico-with-vxlan-encapsulation

Can try an quick fix via https://github.com/rancher/rke2/issues/1541#issuecomment-895297008

**Comment by mazdakn** [comment]
@opencmit2 please fill in the issue template fully so we can understand your cluster better.
