### ISSUE TITLE
libbpf: failed to find valid kernel BTF  (Debian 12)

### ISSUE THREAD

**Issue by alexdev-wb** [projectcalico/calico#8001]
Unable to start calico with eBPF dataplane

## Current Behavior
calico-node pod failed to load bpf prog:
```
libbpf: failed to find valid kernel BTF
libbpf: Error loading vmlinux BTF: -3
libbpf: failed to load object '/usr/lib/calico/bpf/from_wep_fib_no_log_co-re.o'
```

Distro bpftool able to dump BTF, whereas calico-node bpftool isn't:

```
kubectl -n calico-system exec -i -t calico-node-<pod> -- bash
# bpftool btf dump file /sys/kernel/btf/vmlinux format c
libbpf: failed to get EHDR from /sys/kernel/btf/vmlinux
Error: failed to load BTF from /sys/kernel/btf/vmlinux: Unknown error -4001
```

## Possible Solution
bpftool upgrade?..

## Steps to Reproduce (for bugs)
1. Debian 12 system, kernel 6.1.0-9-amd64
2. k8s cluster with kubeadm
3. follow steps to install calico cni with eBPF dataplane

## Your Environment
* Calico 3.26.1
* kubernetes 1.28.1
* Debian 12 (amd64)

**Comment by onesb23** [comment]
eBPF works in Calico version v3.27.0-0.dev

**Comment by tomastigera** [comment]
We upgraded libbpf recently https://github.com/tigera/calico-private/pull/6576
