### ISSUE TITLE
Auto accept service vip pkg in cali-INPUT chain when use ipvs mode 

### ISSUE THREAD

**Issue by gaopeiliang** [projectcalico/calico#8002]
calico use "cali-INPUT" chain do some forward-check , and accept pkg ignore INPUT extra action ....

```
-A INPUT -m comment --comment "cali:Cz_u1IQiXIMmKD4c" -j cali-INPUT


-A cali-INPUT -m comment --comment "cali:PCzw3ez-xOEOzWX3" -j MARK --set-xmark 0x0/0xfff00000
-A cali-INPUT -m comment --comment "cali:OvwuhxZpZ9lZuukt" -j cali-forward-check
-A cali-INPUT -m comment --comment "cali:Y9AhoSSYyNjemCQ3" -m mark ! --mark 0x0/0xfff00000 -j RETURN

#  calio-forward-check Not Mark Pkg will return to INPUT action
||||  -A cali-forward-check -m comment --comment "cali:Pbldlb4FaULvpdD8" -m conntrack --ctstate RELATED,ESTABLISHED -j RETURN
||||  -A cali-forward-check -p tcp -m comment --comment "cali:ZD-6UxuUtGW-xtzg" -m comment --comment "To kubernetes NodePort service" -m multiport --dports 30000:32767 -m set --match-set cali40this-host dst -g cali-set-endpoint-mark
||||  -A cali-forward-check -p udp -m comment --comment "cali:CbPfUajQ2bFVnDq4" -m comment --comment "To kubernetes NodePort service" -m multiport --dports 30000:32767 -m set --match-set cali40this-host dst -g cali-set-endpoint-mark
||||  -A cali-forward-check -m comment --comment "cali:jmhU0ODogX-Zfe5g" -m comment --comment "To kubernetes service" -m set ! --match-set cali40this-host dst -j cali-set-endpoint-mark

-A cali-INPUT -i cali+ -m comment --comment "cali:F9ISwbGfetOR8orJ" -g cali-wl-to-host
-A cali-INPUT -m comment --comment "cali:gXI_QBzPL6XebJdy" -m mark --mark 0x10000/0x10000 -j ACCEPT
-A cali-INPUT -m comment --comment "cali:W7rZsWy-ibBq3gZZ" -j MARK --set-xmark 0x0/0xf0000
-A cali-INPUT -m comment --comment "cali:iGq3sTKq8XgLhSBI" -j cali-from-host-endpoint
-A cali-INPUT -m comment --comment "cali:BgHaZXbljayrc2Z5" -m comment --comment "Host endpoint policy accepted packet." -m mark --mark 0x10000/0x10000 -j ACCEPT

```

sometimes firewall should like this , default DROP, and ACCEPT with special chain

```
INPUT -P DROP

-A INPUT -j cali-INPUT

LIMIT_ACCESS_1024 -P DROP
-A INPUT --dports 1024 -j LIMIT_ACCESS_1024


LIMIT_ACCESS_53 -P DROP
-A INPUT --dports 53 -j LIMIT_ACCESS_53
```

Pod workload connect to VIP well when we use kube-proxy IPTABLES mode,  because this pkg should to forward chain and Never hit INPUT -> cali-INPUT

But when we use IPVS mode , it will connect failed,  because IPVS made pkg to INPUT -> LB -> OUTPUT ,  it will hit INPUT ,  cali-INPUT chain will not accept,  other chain not accept also ,, it will be drop .... 

we should always add an special chain to accept this case ,  and sometimes change some rule will drop this case in mistake .......  crying.....

```
-A INPUT --dports 53 --dst SERVICE_VIP_CIDR -j ACCEPT

```

so calio-forward-check chain maybe mark this case pkg , check , accept , like "Kubernetes Node Port"
```
-A cali-forward-check  -m comment --comment "cali:ZD-6UxuUtGW-xtzg" -m comment --comment "To kubernetes IPVS service VIP" --dst SERVICE_VIP_CIDR  -g cali-set-endpoint-mark

```

## Expected Behavior
auto accept service vip package when use ipvs mode

## Possible Solution
```
-A cali-forward-check  -m comment --comment "cali:ZD-6UxuUtGW-xtzg" -m comment --comment "To kubernetes IPVS service VIP" --dst SERVICE_VIP_CIDR  -g cali-set-endpoint-mark

or add SERVICE_VIP_CIDR  to ipset cali40this-host,   hit this rule 

-A cali-forward-check -m comment --comment "cali:jmhU0ODogX-Zfe5g" -m comment --comment "To kubernetes service" -m set ! --match-set cali40this-host dst -j cali-set-endpoint-mark
```

## Steps to Reproduce (for bugs)
1.  start local cache dns server on port 53
2.  add rule allow special IP accept port 53
3.  turn kube-proxy iptables mode to ipvs
4.  Pod connect coredns VIP 53 will failed 

## Your Environment

* Calico version 3.21
* Orchestrator version (e.g. kubernetes, mesos, rkt):  kubernetes
* Operating System and version: Linux
* Link to your project (optional):is

**Comment by tomastigera** [comment]
I am not entirely sure if I understand correctly, but it feels like you want to insert your own rules that should play well with calico. Have a look at the config options that allow to change some default behaviour or our rules https://docs.tigera.io/calico/latest/reference/resources/felixconfig

`iptablesFilterAllowAction`, `iptablesMangleAllowAction`, `defaultEndpointToHostAction` etc.

**Comment by gaopeiliang** [comment]
I think should focuse on it has different action of filter "k8s service packet" when use iptable mode with ipvs mode ,  when turn iptables to ipvs someday,,  it will break conn of service ....

**Comment by caseydavenport** [comment]
II'm not sure I fully understand, but based on what I do understand I don't think we should add special-case code for this. You might be able to add the rule you want using HostEndpoints and GlobalNetworkPolicy?

You're talking about a pod -> IPVS VIP -> local Node. If anything, this might fall under the responsibility of the IPVS kube-proxy implementation.

**Comment by gaopeiliang** [comment]
![图片](https://github.com/projectcalico/calico/assets/11383058/c01b0280-3ebc-4a90-951b-e13a5450fb6d)
