### ISSUE TITLE
If the interface is down/up, can the route be restored?

### ISSUE THREAD

**Issue by gongzixiangyuan** [projectcalico/calico#8003]
## Expected Behavior

After interface up, route is restored

## Current Behavior

The route is gone forever

## Possible Solution

When cni writes routing, can it be persisted?

## Steps to Reproduce (for bugs)

[root@master3 ~]# ifconfig
eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 172.18.136.63  netmask 255.255.255.255  broadcast 0.0.0.0
        inet6 fe80::862:45ff:feaf:e7d1  prefixlen 64  scopeid 0x20<link>
        ether 0a:62:45:af:e7:d1  txqueuelen 0  (Ethernet)
        RX packets 10145076  bytes 582753536 (555.7 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 5299689  bytes 321105070 (306.2 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1000  (Local Loopback)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

[root@master3 ~]# 
[root@master3 ~]# ip r
default via 169.254.1.1 dev eth0 
169.254.1.1 dev eth0 scope link 
[root@master3 ~]# 
[root@master3 ~]# **ifconfig eth0 down**
[root@master3 ~]# 
[root@master3 ~]# **ip r**
[root@master3 ~]# 
[root@master3 ~]# **ifconfig eth0 up**
[root@master3 ~]# 
[root@master3 ~]# ifconfig
eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 172.18.136.63  netmask 255.255.255.255  broadcast 0.0.0.0
        inet6 fe80::862:45ff:feaf:e7d1  prefixlen 64  scopeid 0x20<link>
        ether 0a:62:45:af:e7:d1  txqueuelen 0  (Ethernet)
        RX packets 10145163  bytes 582758878 (555.7 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 5299734  bytes 321107916 (306.2 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1000  (Local Loopback)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

[root@master3 ~]# 
[root@master3 ~]# **ip r**  # The route is lost after the interface down/up
[root@master3 ~]# 

## Your Environment

* Calico version
* Orchestrator version (e.g. kubernetes, mesos, rkt):
* Operating System and version:
* Link to your project (optional):

Calico version 3.23

**Comment by coutinhop** [comment]
@gongzixiangyuan could you help us understand your use case better? what does your cluster look like? why would you need to to `ifconfig eth0 down` on a node? without some more context, I can only say that restarting calico-node *should* program routes, but I'm a little lost with just the info you provided, sorry

**Comment by gongzixiangyuan** [comment]
> @gongzixiangyuan could you help us understand your use case better? what does your cluster look like? why would you need to to `ifconfig eth0 down` on a node? without some more context, I can only say that restarting calico-node _should_ program routes, but I'm a little lost with just the info you provided, sorry

I executed ifconfig eth0 down in the container, not on the node. It can be regarded as a reliability test in a certain scenario.

**Comment by mazdakn** [comment]
@fasaxc can you please check this?

**Comment by fasaxc** [comment]
This is working as designed, we don't touch the routes inside the container after set-up.  Non-privileged containers can't change their routing or bring interfaces down/up like this; privileged containers can, but if a privileged container breaks its own routing then that's its own fault.  veths can't just "go down" on their own as far as I know, they're not real interfaces that have a wire that can be removed.

That said, it would be nice to maintain routes to prevent this kind of issue.  To do that, I think the best bet would be for calico CNI to implement the CNI [CHECK](https://github.com/containernetworking/cni/blob/main/SPEC.md#check-check-containers-networking-is-as-expected) verb to do the periodic check that the container is set up correctly.

**Comment by gongzixiangyuan** [comment]
> This is working as designed, we don't touch the routes inside the container after set-up. Non-privileged containers can't change their routing or bring interfaces down/up like this; privileged containers can, but if a privileged container breaks its own routing then that's its own fault. veths can't just "go down" on their own as far as I know, they're not real interfaces that have a wire that can be removed.
> 
> That said, it would be nice to maintain routes to prevent this kind of issue. To do that, I think the best bet would be for calico CNI to implement the CNI [CHECK](https://github.com/containernetworking/cni/blob/main/SPEC.md#check-check-containers-networking-is-as-expected) verb to do the periodic check that the container is set up correctly.
> 
> FWIW, the overall design of systems like Kubernetes is that we don't aim to deal with every possible corner case such as this. Your app should have a health check configured, then, if something disrupts its networking (say a cosmic ray disabled the veth), the health check fails and the pod gets restarted and the problem is solved.

**Comment by gongzixiangyuan** [comment]
> This is working as designed, we don't touch the routes inside the container after set-up. Non-privileged containers can't change their routing or bring interfaces down/up like this; privileged containers can, but if a privileged container breaks its own routing then that's its own fault. veths can't just "go down" on their own as far as I know, they're not real interfaces that have a wire that can be removed.
> 
> That said, it would be nice to maintain routes to prevent this kind of issue. To do that, I think the best bet would be for calico CNI to implement the CNI [CHECK](https://github.com/containernetworking/cni/blob/main/SPEC.md#check-check-containers-networking-is-as-expected) verb to do the periodic check that the container is set up correctly.
> 
> FWIW, the overall design of systems like Kubernetes is that we don't aim to deal with every possible corner case such as this. Your app should have a health check configured, then, if something disrupts its networking (say a cosmic ray disabled the veth), the health check fails and the pod gets restarted and the problem is solved.

Thank you very much for your reply !
