### ISSUE TITLE
kubernetes v1.28.1 and calico 3.26 network cannot reach

### ISSUE THREAD

**Issue by dlarmor** [projectcalico/calico#8007]
according to [Quickstart for Calico on Kubernetes] step by step apply tigera-operator.yaml and custom-resources.yaml ,
## Steps to Reproduce (for bugs)

1. run a busybox on master
<img width="771" alt="image" src="https://github.com/projectcalico/calico/assets/24198244/d2506b1a-56cf-4558-bcb0-dfaf19f47e40">

2. try connect to pod on master 
<img width="858" alt="image" src="https://github.com/projectcalico/calico/assets/24198244/eb5204e0-bcfa-4309-af85-00d09ce9274e">

4. run a busybox on worker
5. 
<img width="1290" alt="image" src="https://github.com/projectcalico/calico/assets/24198244/db3a4b26-cd2b-4c27-9122-0615d0d441fb">
fail to connect to mysql
<img width="489" alt="image" src="https://github.com/projectcalico/calico/assets/24198244/55f24801-fd11-4df8-b796-9d1330a016eb">

6.
info busybox on master
<img width="990" alt="image" src="https://github.com/projectcalico/calico/assets/24198244/b856aaa3-a2cf-40a6-aa26-5d0784753e62">
info busybox2 on worker
<img width="768" alt="image" src="https://github.com/projectcalico/calico/assets/24198244/9fe0cd06-604d-4bf3-a27f-f0e69ed0679b">

## Your Environment

* Calico version 3.26
* Orchestrator version (e.g. kubernetes, mesos, rkt): k8s v1.28.1
* Operating System and version: 
* 
<img width="1078" alt="image" src="https://github.com/projectcalico/calico/assets/24198244/55019047-765d-455f-a1d8-748a209a0ef3">

* Link to your project (optional):

**Comment by brownz11** [comment]
You've left out what OS/Kernel you're on. Workers not being able to do DNS lookups and not being able to talk to pods on other nodes sounds a lot like

https://docs.rke2.io/known_issues#calico-with-vxlan-encapsulation

**Comment by mazdakn** [comment]
@dlarmor is your issue solved or still dealing with it?

**Comment by dlarmor** [comment]
> @dlarmor is your issue solved or still dealing with it?

emm. I gave up and didn't try for a long time.
