### ISSUE TITLE
Migration from Flannel failing with "Can not find pod with label in map[k8s-app:canal]"

### ISSUE THREAD

**Issue by jmboby** [projectcalico/calico#8018]
The migration is failing due to our canal pods being labelled differently, could we add the ability to configure the label instead of it being hardcoded? 
https://github.com/projectcalico/calico/blob/master/kube-controllers/pkg/controllers/flannelmigration/migration_controller.go#L68C2-L68C16

## Expected Behavior
The migration controller should detect our existing canal pods and start the migration

## Current Behavior
The migration controller goes into a Crashloop with this error: 
Stopping Migration controller. error=Failed to execute command in pod. Can not find pod with label in map[k8s-app:canal] on node ....

## Possible Solution
Could we fix this in the same way you made flannel namespace configurable?
https://github.com/projectcalico/calico/pull/7557

## Steps to Reproduce (for bugs)
1. Create the migration controller job, sa, configmap and rbac - "kubectl apply -f migration-job.yaml"
2. Check migration controller logs - "kubectl logs -n kube-system -l k8s-app=flannel-migration-controller"

## Context
We are trying to migrate from Flannel to Calico as per your doco - https://docs.tigera.io/calico/latest/getting-started/kubernetes/flannel/migration-from-flannel#view-migration-logs

## Your Environment
* Calico version: v3.26.1
 https://raw.githubusercontent.com/projectcalico/calico/v3.26.1/manifests/flannel-migration/migration-job.yaml
* Orchestrator version: K8s v1.23
* Operating System and version: N/A

**Comment by caseydavenport** [comment]
Yep, seems reasonable as a fix to make this configurable.

As a workaround, would just adding the expected label to your daemonset also work?

**Comment by jmboby** [comment]
Yes after looking into further I can just add the expected label to our daemonset. Originally I thought this would have caused a clash with a second canal daemonset running on the same cluster but this is not the case, it should work fine.

Let's close this one off, no need to add the extra feature.
