### ISSUE TITLE
Calico-Node is in CrashLoopBackOff status, And Calico-node shutting down in Node

### ISSUE THREAD

**Issue by dolgae03** [projectcalico/calico#8023]
I have 3 nodes in my Kubernetes cluster, and calico node deployed as CNI. However, 1 Master Node and 1 Worker Node worked well. But 1 calico-node in Worker Node is in CrashBackoff Status.   

## Expected Behavior

In my Cluster in Local VM Machine, and AWS EC2, Calico node depolyed well.
and I expected to deploy well in my Server because, i used sample deployment method in Calico website

## Current Behavior

`kubectl get pod -A`
![image](https://github.com/projectcalico/calico/assets/109707681/fa4e96f0-45ff-4f0f-8528-9c2c912b9128)

This is the current status. As you see the calico-node and calico-typha is in CrashBackOff.

`kubectl get node ubuntu`
![image](https://github.com/projectcalico/calico/assets/109707681/cc3e8ac5-c20d-4f00-8596-22946ae6d6b4)

`kubectl exec calico-node-qmhps -n calico-system -- /bin/calico-node -felix-ready`
![image](https://github.com/projectcalico/calico/assets/109707681/aebef2cb-d185-40b2-8ca3-bc6416b7c0e4)

`kubectl describe node ubuntu`
![image](https://github.com/projectcalico/calico/assets/109707681/b5de3773-0b2d-43e1-8a52-d47aee89f0a7)

`kubectl describe pod calico-node-qmhps -n calico-system `
> Events:
> Type Reason Age From Message
> 
> Normal Scheduled 5m31s default-scheduler Successfully assigned calico-system/calico-node-qmhps to ubuntu
> Normal Pulled 5m30s kubelet Container image "docker.io/calico/pod2daemon-flexvol:v3.26.1" already present on machine
> Normal Created 5m30s kubelet Created container flexvol-driver
> Normal Started 5m30s kubelet Started container flexvol-driver
> Normal Pulled 5m29s kubelet Container image "docker.io/calico/cni:v3.26.1" already present on machine
> Normal Created 5m29s kubelet Created container install-cni
> Normal Started 5m29s kubelet Started container install-cni
> Warning Unhealthy 5m27s kubelet Readiness probe failed: calico/node is not ready: BIRD is not ready: Error querying BIRD: unable to connect to BIRDv4 socket: dial unix /var/run/calico/bird.ctl: connect: connection refused
> W0908 13:07:14.483764 61 feature_gate.go:241] Setting GA feature gate ServiceInternalTrafficPolicy=true. It will be removed in a future release.
> Warning Unhealthy 5m26s kubelet Readiness probe failed: calico/node is not ready: BIRD is not ready: Error querying BIRD: unable to connect to BIRDv4 socket: dial unix /var/run/calico/bird.ctl: connect: connection refused
> W0908 13:07:15.487428 371 feature_gate.go:241] Setting GA feature gate ServiceInternalTrafficPolicy=true. It will be removed in a future release.
> Warning Unhealthy 4m55s (x3 over 5m15s) kubelet Readiness probe failed: command "/bin/calico-node -bird-ready -felix-ready" timed out
> Normal Created 4m50s (x2 over 5m28s) kubelet Created container calico-node
> Normal Started 4m50s (x2 over 5m28s) kubelet Started container calico-node
> Normal Pulled 4m50s (x2 over 5m28s) kubelet Container image "docker.io/calico/node:v3.26.1" already present on machine
> Warning Unhealthy 4m50s (x3 over 5m10s) kubelet Liveness probe failed: Get "http://localhost:9099/liveness": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
> Normal Killing 4m50s kubelet Container calico-node failed liveness probe, will be restarted
> Warning Unhealthy 4m50s kubelet Readiness probe failed: 2023-09-08 13:07:51.192 [INFO][523] confd/health.go 180: Number of node(s) with BGP peering established = 2
> W0908 13:07:51.187693 523 feature_gate.go:241] Setting GA feature gate ServiceInternalTrafficPolicy=true. It will be removed in a future release.
> Warning Unhealthy 4m50s kubelet Readiness probe errored: rpc error: code = NotFound desc = failed to exec in container: failed to create exec "10f418b975084fd2b587cab91d3df175b0e08003ab1d756cfc9a3645ddd3d804": task 5c55e7e8fa6a9d841758e8866f23382c50d290d1b651efd3a72618434e9d62a3 not found: not found
> Warning Unhealthy 4m50s kubelet Readiness probe failed: calico/node is not ready: BIRD is not ready: Error querying BIRD: unable to connect to BIRDv4 socket: dial unix /var/run/calico/bird.ctl: connect: connection refused
> W0908 13:07:51.554603 23 feature_gate.go:241] Setting GA feature gate ServiceInternalTrafficPolicy=true. It will be removed in a future release.
> Warning Unhealthy 4m49s kubelet Readiness probe failed: calico/node is not ready: BIRD is not ready: Error querying BIRD: unable to connect to BIRDv4 socket: dial unix /var/run/calico/bird.ctl: connect: connection refused
> W0908 13:07:52.589282 85 feature_gate.go:241] Setting GA feature gate ServiceInternalTrafficPolicy=true. It will be removed in a future release.
> Warning BackOff 30s (x7 over 90s) kubelet Back-off restarting failed container calico-node in pod calico-node-qmhps_calico-system(eaa1e1ba-190f-4fe7-83e6-343dc8cd2dae)

## Possible Solution

I tried the method in this site(Change Readness time), Howerver it doesn't work for me.
I also tried to reset and init cluster again, But it doesn't works for me.

## Steps to Reproduce (for bugs)

I tried to reproduce this bug on the AWS or some where. Howerver It is impossible to reproduce.
Howerver, Here is the Process that i used to install K8s and Calico
```bash
sudo swapoff -a

cat <<EOF | sudo tee /etc/modules-load.d/k8s.conf
overlay
br_netfilter
EOF

sudo modprobe overlay
sudo modprobe br_netfilter

cat <<EOF | sudo tee /etc/sysctl.d/k8s.conf
net.bridge.bridge-nf-call-iptables  = 1
net.bridge.bridge-nf-call-ip6tables = 1
net.ipv4.ip_forward                 = 1
EOF

sudo sysctl --system
```

```bash
sudo apt-get update
sudo apt-get install ca-certificates curl gnupg

sudo install -m 0755 -d /etc/apt/keyrings
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
sudo chmod a+r /etc/apt/keyrings/docker.gpg

echo \
  "deb [arch="$(dpkg --print-architecture)" signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
  "$(. /etc/os-release && echo "$VERSION_CODENAME")" stable" | \
  sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

sudo apt-get update

sudo apt-get install containerd.io

sudo containerd config default | sudo tee /etc/containerd/config.toml
sudo sed -i 's/SystemdCgroup \= false/SystemdCgroup \= true/g' /etc/containerd/config.toml
sudo sed -i 's%sandbox_image \= "registry.k8s.io/pause:3.6"%sandbox_image \= "registry.k8s.io/pause:3.9"%g' /etc/containerd/config.toml

sudo systemctl daemon-reload
sudo systemctl restart containerd
```

```bash
DOWNLOAD_DIR="/usr/local/bin"
sudo mkdir -p "$DOWNLOAD_DIR"

CRICTL_VERSION="v1.25.0"
ARCH="amd64"
curl -L "https://github.com/kubernetes-sigs/cri-tools/releases/download/${CRICTL_VERSION}/crictl-${CRICTL_VERSION}-linux-${ARCH}.tar.gz" | sudo tar -C $DOWNLOAD_DIR -xz

#RELEASE="$(curl -sSL https://dl.k8s.io/release/stable.txt)"
RELEASE="v1.27.4"
ARCH="amd64"
cd $DOWNLOAD_DIR
sudo curl -L --remote-name-all https://dl.k8s.io/release/${RELEASE}/bin/linux/${ARCH}/{kubeadm,kubelet,kubectl}
sudo chmod +x {kubeadm,kubelet,kubectl}

RELEASE_VERSION="v0.4.0"
curl -sSL "https://raw.githubusercontent.com/kubernetes/release/${RELEASE_VERSION}/cmd/kubepkg/templates/latest/deb/kubelet/lib/systemd/system/kubelet.service" | sed "s:/usr/bin:${DOWNLOAD_DIR}:g" | sudo tee /etc/systemd/system/kubelet.service
sudo mkdir -p /etc/systemd/system/kubelet.service.d
curl -sSL "https://raw.githubusercontent.com/kubernetes/release/${RELEASE_VERSION}/cmd/kubepkg/templates/latest/deb/kubeadm/10-kubeadm.conf" | sed "s:/usr/bin:${DOWNLOAD_DIR}:g" | sudo tee /etc/systemd/system/kubelet.service.d/10-kubeadm.conf

sudo systemctl enable --now kubelet
```

```bash
sudo apt install socat conntrack
sudo kubeadm init --pod-network-cidr=192.168.0.0/16 
```

```bash
kubectl taint nodes --all node-role.kubernetes.io/control-plane-
```

```bash
kubectl create -f https://raw.githubusercontent.com/projectcalico/calico/v3.26.1/manifests/tigera-operator.yaml
kubectl create -f https://raw.githubusercontent.com/projectcalico/calico/v3.26.1/manifests/custom-resources.yaml
```

## Your Environment

For some reason, I can give exact IP address for you. But it is public ip and in one subnet.
* Operating System and version:
![image](https://github.com/projectcalico/calico/assets/109707681/70179cc7-0638-4e99-acaf-e7746eea588c)
![image](https://github.com/projectcalico/calico/assets/109707681/9b79188b-044d-4783-bc40-c4422a23abf6)
The Node doesn't work is third node from above.

* Calico version : v3.6.21
* Orchestrator version (e.g. kubernetes, mesos, rkt):
Client Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.4", GitCommit:"fa3d7990104d7c1f16943a67f11b154b71f6a132", GitTreeState:"clean", BuildDate:"2023-07-19T12:20:54Z", GoVersion:"go1.20.6", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v5.0.1
Server Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.5", GitCommit:"93e0d7146fb9c3e9f68aa41b2b4265b2fcdb0a4c", GitTreeState:"clean", BuildDate:"2023-08-24T00:42:11Z", GoVersion:"go1.20.7", Compiler:"gc", Platform:"linux/amd64"}

**Comment by coutinhop** [comment]
@dolgae03 I assume there's a typo on the calico version? (v3.6 would be extremely old). Could you send calico-node logs, preferably by enabling debug with `kubectl patch felixconfiguration default --type merge --patch='{"spec":{"logSeverityScreen":"Debug"}}'` first? Thanks

**Comment by dolgae03** [comment]
Sorry, Calico version is typo. Version is 3.26.1. Do you means `kubectl get logs -n calico-system calico-node-xxxxx` ?

**Comment by dolgae03** [comment]
> @dolgae03 I assume there's a typo on the calico version? (v3.6 would be extremely old). Could you send calico-node logs, preferably by enabling debug with `kubectl patch felixconfiguration default --type merge --patch='{"spec":{"logSeverityScreen":"Debug"}}'` first? Thanks

Sorry, Calico version is typo. Version is 3.26.1. Do you means `kubectl get logs -n calico-system calico-node-xxxxx `?

**Comment by coutinhop** [comment]
@dolgae03 yes `kubectl get logs -n calico-system calico-node-xxxxx` would be the command

**Comment by dolgae03** [comment]
@coutinhop Here is the log file, and some ip and node name has changed. If you have any logs or system info, let me know. Thank you for your help.

ubuntu => Worker Node(Problem Node
Node B => Control Plane
Node C => Worker Node
[a.txt](https://github.com/projectcalico/calico/files/12686501/a.txt)

**Comment by urbaman** [comment]
Hi,

I did have the very same problem these days.

Kubeadm (both 1.28.2 and 1.27.6 version)
Calico 3.26.1
All nodes Ubuntu 22.04 (3x masters, 3x workers)

The workers are those having problems. The only different thing in the nodes is I run containerd with the nvidia container runtime to get GPU access with the Nvidia driver plugin on those.

Getting the nodes back to runc containred runtime settled the calico instability, and got the GPU working with the Nvidia operator instead.

**Comment by urbaman** [comment]
Addendum: going deeper in confronting my installation of the Nvidia driver plugin and the Nvidia operator, is that thay automated the containerd Nvidia runtime installation and settings.

It turns out that I missed setting `SystemCgroup = True` in the nvidia runtime setting and it probably was the problem, so it's something you could verify in your implementation.

**Comment by dolgae03** [comment]
> Addendum: going deeper in confronting my installation of the Nvidia driver plugin and the Nvidia operator, I found out that thay automated the containerd Nvidia runtime installation and settings.
> 
> It turns out that I missed setting `SystemCgroup = True` in the nvidia runtime setting and it probably was the problem, so it's something you could verify in your implementation.

@urbaman Thank you for your advise. However, I think SystemCgroup got correct value. Here is the config.toml of containerd. If you think it is wrong, Tell me.
[ubuntu_config.txt](https://github.com/projectcalico/calico/files/12714947/ubuntu_config.txt)

**Comment by urbaman** [comment]
Is it the very same in all of the three nodes, both the working one and the failing one?

In my basic installation, I do have "runc" in here

```
[plugins."io.containerd.grpc.v1.cri".containerd.default_runtime]

         base_runtime_spec = "runc"
```

**Comment by dolgae03** [comment]
> Is it the very same in all of the three nodes, both the working one and the failing one?
> 
> In my basic installation, I do have "runc" in here
> 
> ```
> [plugins."io.containerd.grpc.v1.cri".containerd.default_runtime]
> 
>          base_runtime_spec = "runc"
> ```

@urbaman The file of config of node B  is below, But it works normally,
[config.txt](https://github.com/projectcalico/calico/files/12719436/config.txt)

**Comment by dolgae03** [comment]
> @coutinhop Here is the log file, and some ip and node name has changed. If you have any logs or system info, let me know. Thank you for your help.
> 
> ubuntu => Worker Node(Problem Node Node B => Control Plane Node C => Worker Node [a.txt](https://github.com/projectcalico/calico/files/12686501/a.txt)

@coutinhop May i ask to check this log file? Thank you for your time.

**Comment by coutinhop** [comment]
> > @coutinhop Here is the log file, and some ip and node name has changed. If you have any logs or system info, let me know. Thank you for your help.
> > ubuntu => Worker Node(Problem Node Node B => Control Plane Node C => Worker Node [a.txt](https://github.com/projectcalico/calico/files/12686501/a.txt)
> 
> @coutinhop May i ask to check this log file? Thank you for your time.

@dolgae03 sorry for the delay... I don't see anything that points to a cause in the log you posted, could you double check that it is from the problem node, and that the crashloopbackoff is happening during that time? One thing I'm missing from the logs is this message which shows up after calico-node starts up:
```
2023-11-14 18:02:06.377 [INFO][75212] felix/health.go 336: Overall health status changed: live=true ready=true
+---------------------------+---------+----------------+-----------------+--------+                           
|         COMPONENT         | TIMEOUT |    LIVENESS    |    READINESS    | DETAIL |                           
+---------------------------+---------+----------------+-----------------+--------+                           
| CalculationGraph          | 30s     | reporting live | reporting ready |        |                           
| CloudWatchReporter        | 20s     | reporting live | reporting ready |        |                           
| DNSReporter               | 20s     | reporting live | reporting ready |        |                           
| FelixStartup              | -       | reporting live | reporting ready |        |                           
| InternalDataplaneMainLoop | 1m30s   | reporting live | reporting ready |        |                           
| L7Reporter                | 20s     | reporting live | reporting ready |        |                           
+---------------------------+---------+----------------+-----------------+--------+                           
```

So it seems like felix is failing to report as live and ready, which makes k8s restart the pod, but I'm still not sure exactly why that is happening

**Comment by bhuntley** [comment]
I was also running into this problem between calico and the nvidia container runtime on my K8s cluster, running on Ubuntu 22.04.  I had configured my /etc/containerd/config.toml using an online guide that used a sed command to set SystemdCgroup = true.  Setting the value in this way of course only sets it under the [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc.options] unless you had manually added to [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.nvidia.options] previously.

Once I had added SystemdCgroup = true under [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.nvidia.options], the problem resolves and calico is pods are staying Running.

Interestingly, this is the third GPU K8s cluster I have configured - One of the previous deployments on Ubuntu 20.04, and another one on Ubuntu 22.04 but using the current runtime from ~6 months ago.  I did not run into this issue on either of those clusters.

**Comment by srankmeng** [comment]
I face to this problem, the calico-node cannot start on worker nodes. Then I add `InitConfiguration` on `kubeadm-config.yaml` like this, it's work.

``` 
apiVersion: kubeadm.k8s.io/v1beta3
kind: ClusterConfiguration
kubernetesVersion: stable
controlPlaneEndpoint: "<CONTROLPLANE_IP>:6443"
...
...
networking:
  podSubnet: "10.244.0.0/16"
---
apiVersion: kubeadm.k8s.io/v1beta3
kind: InitConfiguration
localAPIEndpoint:
  advertiseAddress: <CONTROLPLANE_IP>
  bindPort: 6443
```

**Comment by dolgae03** [comment]
> I face to this problem, the calico-node cannot start on worker nodes. Then I add `InitConfiguration` on `kubeadm-config.yaml` like this, it's work.
> 
> ```
> apiVersion: kubeadm.k8s.io/v1beta3
> kind: ClusterConfiguration
> kubernetesVersion: stable
> controlPlaneEndpoint: "<CONTROLPLANE_IP>:6443"
> ...
> ...
> networking:
>   podSubnet: "10.244.0.0/16"
> ---
> apiVersion: kubeadm.k8s.io/v1beta3
> kind: InitConfiguration
> localAPIEndpoint:
>   advertiseAddress: <CONTROLPLANE_IP>
>   bindPort: 6443
> ```

Thank you for giving attention about this issue. Finaly, It was Firewall issue.

**Comment by abhijith-zupaloop** [comment]
@dolgae03 I am also facing the same issue. Could you please guide me. I guess the issue is with firewall in my case. 

```
Defaulted container "calico-node" out of: calico-node, flexvol-driver (init), install-cni (init)
Error from server: Get "https://10.80.0.4:10250/containerLogs/calico-system/calico-node-wd8vh/calico-node?follow=true": dial tcp 10.80.0.4:10250: i/o timeout
```
I get the above error when i check the logs

![image](https://github.com/user-attachments/assets/e4fda799-83d9-47ea-88ea-92fb2149aff5)
The issue is with the GPU worker node. CPU workers are fine

**Comment by dolgae03** [comment]
@abhijith-zupaloop I'm not sure it's in same issue, For me Not only port policy, but also another forwarding policy of firewall was problem. Here is some commend you need to consider, I hope it give you some hints to solve your problem. The problem really depends on each env.

```
sudo iptables -P INPUT ACCEPT
sudo iptables -P OUTPUT ACCEPT
sudo iptables -P FORWARD ACCEPT

sudo iptables -t nat -P PREROUTING ACCEPT 
sudo iptables -t nat -P INPUT ACCEPT 
sudo iptables -t nat -P OUTPUT ACCEPT 
sudo iptables -t nat -P POSTROUTING ACCEPT 

sudo iptables -t mangle -P PREROUTING ACCEPT 
sudo iptables -t mangle -P INPUT ACCEPT 
sudo iptables -t mangle -P FORWARD ACCEPT
sudo iptables -t mangle -P OUTPUT ACCEPT 
sudo iptables -t mangle -P POSTROUTING ACCEPT 

#아래의 chain flush 이전에 각각의 정보들 확인(flush 해도 이후에 재부팅시 복구됨)
sudo iptables -L
sudo iptables -t nat -L
sudo iptables -t mangle -L

#### 해당 명령어는 Flush이므로(모든 Chain을 삭제) 모두 ACCEPT으로 된 것이 확인된 후에 실행이 필요함.
sudo iptables -F
sudo iptables -t nat -F
sudo iptables -t mangle -F
```

**Comment by dolgae03** [comment]
I meant YOU NEED TO FLUSH ALL FIREWALL, not only port policy.

**Comment by abhijith-zupaloop** [comment]
@dolgae03 
I have followed the above steps , yet getting the same issue

![image](https://github.com/user-attachments/assets/fb6c7c74-bf9c-4ffd-9e9e-accc48c82949)

**Comment by abhijith-zupaloop** [comment]
I have opened the Ports based on [this ](https://kubernetes.io/docs/reference/networking/ports-and-protocols/)
