### ISSUE TITLE
Update UBI_VERSION to 8.8

### ISSUE THREAD

**Issue by wedaly** [projectcalico/calico#8050]
The image registry.access.redhat.com/ubi8/ubi-minimal:8.7 has several CVEs that are appearing in security scanner results:
[ubi-8.7-cves.txt](https://github.com/projectcalico/calico/files/12718158/ubi-8.7-cves.txt)

Creating this issue to track updating UBI_VERSION from 8.7 to 8.8 to address these.

**Comment by mgleung** [comment]
This will be fixed with https://github.com/projectcalico/calico/pull/7664

**Comment by Behnam-Shobiri** [comment]
Thanks for reporting the CVEs @wedaly. We update our releases as much as possible. Generally, our latest n-1 release gets the CVE updates (currently it would be 3.25 and 3.26). Both versions are already using scratch-based images that use libraries from UBI 8.8. See 3.26: https://github.com/projectcalico/calico/blob/release-v3.26/metadata.mk#L18
3.25: https://github.com/projectcalico/calico/blob/release-v3.26/metadata.mk#L18 

As @mgleung mentioned, the main branch will also be updated, but please note that there is no release based on the main branch.

**Comment by Behnam-Shobiri** [comment]
Thanks again for reporting this @wedaly. The fix was merged and I just created a PR to update UBI to 8.9 (released yesterday; see https://github.com/projectcalico/calico/pull/8237 and backports). Please feel free to open other issues if you see any other issues.
