### ISSUE TITLE
Kubernetes addon-manager compliant manifests for 2.x

### ISSUE THREAD

**Issue by lachie83** [projectcalico/calico#806]
Any chance you can publish kubernetes addon-manager compliant manifest for 2.1 and 2.2 like what's been done here -- https://github.com/projectcalico/calico/tree/master/v2.0/getting-started/kubernetes/installation/hosted/k8s-backend-addon-manager

**Comment by lachie83** [comment]
It's probably easy enough simply to add the annotations without having it upstream

**Comment by lxpollitt** [comment]
@caseydavenport @tomdee What's your view on this? Is it something we want upstream as generally useful without leading to combinatorial explosion of manifests?
