### ISSUE TITLE
Using calico as overlay network in GKE clusters

### ISSUE THREAD

**Issue by poojapatil010677** [projectcalico/calico#8061]
In GKE seems like calico can be installed only for network policies. I was looking into installing calico for it's overlay network support but could not find any documentation how that can be accomplished. Is it possible to use calico for it's overlay capabilities on GKE? Using VPC-native which is default in GKE can lead to IP exhaustion so looking to this option.

**Comment by tomastigera** [comment]
Unfortunately, the answer is "No, Google don't allow it"

**Comment by lwr20** [comment]
IIUC, Google consider the pod-network to be part of what they're managing for you when you use their managed kubernetes, so they lock it down tight.
