### ISSUE TITLE
Adding label at calico-apiserver and calico-system namespace

### ISSUE THREAD

**Issue by Pavaningithub** [projectcalico/calico#8075]
Currently I'm installing calico using calico operator helm chart (version v3.26.1)
I would like to add label `istio.io/rev: prod-stable` to `calico-system` and `calico-apiserver` namespaces. These namespaces are created automatically by the operator and I did not find any way to add labels or annotations to namespaces.

## Expected Behavior

I would like to know a method to set labels or annotations to namespaces.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Calico version
* Orchestrator version (e.g. kubernetes, mesos, rkt):
* Operating System and version:
* Link to your project (optional):

**Comment by caseydavenport** [comment]
Today, you can still label those namespaces post-creation using standard means. e.g.,

```
kubectl label namespace calico-system istio.io/rev=prod-stable
```

I believe you should also be able to pre-create these namespaces before installing Calico, although I haven't tried this myself. If you do, I would expect the tigera/operator to assume ownership of the namespace and apply its own configuration to it, but leave your custom labeling intact.
