### ISSUE TITLE
When is the release for supporting k8s 1.28

### ISSUE THREAD

**Issue by lubronzhan** [projectcalico/calico#8076]
Just curious do we have timeline of releasing, maybe 3.27, for k8s 1.28 support.

Thanks

**Comment by lubronzhan** [comment]
Hi @mazdakn from the slack I learnt from @frozenprocess calico will support K8s 1.28 in Calico 3.27. We just look for some official claim from calico documents that some version of calico can support k8s 1.28

**Comment by frozenprocess** [comment]
I believe 3.26 is tested with 1.28 and with the next release (3.27) we are going to highlight the fact that our e2e tests have been successful on Kunernetes 1.28 
@lwr20

**Comment by lubronzhan** [comment]
Thanks @frozenprocess I talked to @lwr20 [here](https://calicousers.slack.com/archives/C0BCA117T/p1697821629120459?thread_ts=1697627796.295359&cid=C0BCA117T) 
There is a [ongoing PR](https://github.com/tigera/docs/pull/1018) to claim support k8s 1.28 with 3.26. But now it's kind of blocked because of people are discussing we should strictly follow k8s n-1 skew support policy

**Comment by lwr20** [comment]
https://github.com/tigera/docs/pull/1018 is now merged :)

**Comment by lubronzhan** [comment]
Nice! Thank you. I can close this since 3.25 and 3.26 now supports k8s 1.28 https://github.com/tigera/docs/pull/1018
