### ISSUE TITLE
csi-node-driver using default serviceAccount

### ISSUE THREAD

**Issue by jonathanrobinson96** [projectcalico/calico#8077]
As part of enhancing the security posture of our clusters we are moving away from using default service accounts. I've noticed that the csi-node-driver is a resource that uses a default service account however, doesn't seem to use the service account allocated to it when I change the daemonset config. Is there a reason for this? / a way around this? I am using calico via the tigera-operator helm chart.

## Expected Behavior

If I change the service account in the daemonset config this change should propagate across the csi-node-driver pods.
```  template:
      metadata:
        creationTimestamp: null
        labels:
          app.kubernetes.io/name: csi-node-driver
          k8s-app: csi-node-driver
          name: csi-node-driver
      spec:
        serviceAccountName: csi-node-driver
        containers:
```
## Current Behavior

1/8 of the csi-node-driver pods terminates and starts up, still using the default service account.

## Steps to Reproduce (for bugs)

1. Install calico via tigera-operator helm chart
2. create a service account for csi-node-driver
3. Edit csi-node-driver daemonset to use created service account

## Your Environment

* tigera-operator chart version: v3.26.1
* tigera/operator image version: v1.30.4
* kubernetes version v1.25.12 (EKS)

**Comment by sridhartigera** [comment]
@jonathanrobinson96 The csi-node-driver daemonset is managed by the operator. Hence any change to the daemonset will be overwritten by the operator. At present, we dont have a way around this. This needs to be an enhancement as the serviceaccount needs to trickle down using the operator config.

**Comment by caseydavenport** [comment]
Looks like right now we use a dedicated serviceaccount if PSP is enabled on the cluster: https://github.com/tigera/operator/blob/master/pkg/render/csi.go#L397

Should probably just always use one. The reasoning here is that CSI driver doesn't actually perform any API access so it shouldn't need any RBAC resources, but we can just as easily create a non-deafult SA with no permissions in order to satisfy policies like this.

**Comment by jonathanrobinson96** [comment]
Any updates on this issue?

**Comment by caseydavenport** [comment]
Here's a PR: https://github.com/tigera/operator/pull/3399
