### ISSUE TITLE
Reporter is not ready. name="InternalDataplaneMainLoop"

### ISSUE THREAD

**Issue by xfyan0408** [projectcalico/calico#8078]
Reporter is not ready. name="InternalDataplaneMainLoop"

## Expected Behavior
run correctly!

## Current Behavior
I added this, 
```
            - name: FELIX_LOGSEVERITYSCREEN
              value: "debug"
```
when I run `kubectl logs calico-node-kl227 -n kube-system` it had the following log:
 felix/health.go 266: Reporter is not ready. name="InternalDataplaneMainLoop"
![image](https://github.com/projectcalico/calico/assets/76023357/418773f8-c62f-47e8-a47e-339c5d339646)

and my server memory increasely quickly:
![image](https://github.com/projectcalico/calico/assets/76023357/3463b221-6781-413d-9b33-6ce718159c9a)
![image](https://github.com/projectcalico/calico/assets/76023357/a03a7d67-6012-463f-8792-ed5971d8828b)

## Possible Solution
update os version? I ran it correctly in ubuntu20. I do not know why.

## Your Environment

* Calico version 3.25
* Orchestrator version (e.g. kubernetes, mesos, rkt): k8s 1.26.5
* Operating System and version: ubuntu16

**Comment by coutinhop** [comment]
@xfyan0408 could you post the full calico logs (with debug enabled preferably), so we can have more info to try to pinpoint a root cause for this failure? thanks!

**Comment by jvaibhav123-a11y** [comment]
We are facing same issue. what was the fix for this issue?

**Comment by Z-ALIVE** [comment]
Any update on this I am facing the same issue and I am stuck..
