### ISSUE TITLE
pod can not access host in host network

### ISSUE THREAD

**Issue by jeffery9** [projectcalico/calico#808]
kubernetes 1.6.3 installed use kubeadm, and installed calico network

## Expected Behavior

container in pod can access host in host network

## Current Behavior

container can ping tunl0 of host,
container can ping docker0 of host

## Steps to Reproduce (for bugs)

1.  install kubernetes 1.6.3 use kubeadm
2.  install calico network  use `kubectl apply -f  http://docs.projectcalico.org/v2.2/getting-started/kubernetes/installation/hosted/kubeadm/1.6/calico.yaml `
3.  install Yaml `https://raw.githubusercontent.com/jeffery9/kubernetes-odoo/master/odoo.yaml`, change DB_PORT_5432_TCP_ADDR to the host in host network
4.  view pod's log, found that  pod can not access DB_Host in host network
5,  attach to pod to test networking........

ping pod host's ip is ok
ping pod ip is ok
ping master's host ip, not ok

## Your Environment

* Calico version    2.2
* Orchestrator version (e.g. kubernetes, mesos, rkt): kubernetes 1.6.3
* Operating System and version: ubuntu 16.04
* Link to your project (optional):

**Comment by jeffery9** [comment]
after enable NAT for pod network, it worked

**Comment by tmjd** [comment]
Yes what you found is a known issue, see https://github.com/projectcalico/calicoctl/issues/1562.  You also found the current workaround.
I'm going to close this issue since it is already being tracked through that calicoctl issue.
