### ISSUE TITLE
calico-node and calico-kube-controllers readiness probe failures on longevity clusters

### ISSUE THREAD

**Issue by ajayudayagiri-hpe** [projectcalico/calico#8097]
We are observing readiness probe failures with following event from both calico-node and calico-kube-controllers pods on any longevity(more than 10 days) cluster. This issue is not observed on a newly created cluster. 

 `LAST SEEN   TYPE      REASON           OBJECT                                         MESSAGE
5m11s       Warning   Unhealthy        pod/calico-kube-controllers-5fb7d84d57-jgs8c   Readiness probe failed:
91s         Warning   Unhealthy        pod/calico-node-l5bqm                          Readiness probe failed: calico/node is not ready: BIRD is not ready: Error executing command: read unix @->/var/run/calico/bird.ctl: i/o timeout`

## Expected Behavior
Readiness probe should not fail on longevity

## Current Behavior
Currently on any single/multi-node cluster we are observing this readiness probe failure issues on calico-node and calico-kube-controllers pods. At specific time of Readiness probe failure, we checked pod logs and no red flags are observed. 

## Possible Solution
Enhance readiness probe check logic to ensure stability of cluster

## Steps to Reproduce (for bugs)
We see this behaviour on all dev/qa/prod clusters irrespective of size of cluster.  

## Context
If calico-node pod health is down, any other pod schedule/de-schedule is impacted. 

## Your Environment
* Calico version - 3.24
* Kubernetes version - 1.22.17
* Operating System and version: Ubuntu 18.04

**Comment by caseydavenport** [comment]
The readiness probe is just a symptom of something else going wrong, it's not causing problems itself.

It would be good to see a full `kubectl describe pod` output as well as `kubectl logs` output from the affected pods.

**Comment by ajayudayagiri-hpe** [comment]
@caseydavenport - I will get back with `kubectl describe` output and `kubectl logs` of calico-node and calico-kube-controller pods.

**Comment by caseydavenport** [comment]
@ajayudayagiri-hpe any progress here?

**Comment by ajayudayagiri-hpe** [comment]
@caseydavenport - we have updated calico_backend to vxlan, readiness probe failures on calico-node pod are not seen. 

However, will have to wait for few more days of longevity to see if calico-kube-controllers readiness probe failures will happen.

**Comment by mazdakn** [comment]
@ajayudayagiri-hpe is your issue solved now?

**Comment by mazdakn** [comment]
Closing this issue. @ajayudayagiri-hpe feel free to re-open this if you still have the same issue.

**Comment by thelo09** [comment]
hi @mazdakn , I am having the same issue

![Screenshot from 2024-02-25 00-10-54](https://github.com/projectcalico/calico/assets/137653186/b7385a18-4efd-4826-bdc4-acd688834ac4)
Logs of calico kube controller
