### ISSUE TITLE
Improve Style Theme 

### ISSUE THREAD

**Issue by djosborne** [projectcalico/calico#81]
The docs site could use improvements to its theme that accomplishes the following:
- Adhere to html best practices (screen width, spacing, etc.)
- Giv Calico a unique, appealing look
- Easy to use properly

**Comment by djosborne** [comment]
I'll propose [twitter bootstrap](http://getbootstrap.com/). 

- It handles screen-size scaling across mobile, tablet, and desktop.
- It has good documentation with examples of how to use it.
- It can be skinned with CSS overrides to change the themeing

**Comment by robbrockbank** [comment]
Can we reduce the height of the top section - it's currently a 1/3 of the page height which is really just wasted space.

I don't think we need the heading + sub heading - just use the heading.   E.g. "Introduction" and "Background information on Calico" -- just bin the latter wordier one.

**Comment by djosborne** [comment]
Fixed by #554 :tada:
