### ISSUE TITLE
How to install patch-releases of components using Helm?

### ISSUE THREAD

**Issue by michaldobisek** [projectcalico/calico#8100]
I am using Helm tigera operator chart (v3.26.1) to install the calico. 

It successfully figures out how to get the images (like `calico/node` or `calico/pod2daemon-flexvol`) v3.26.1 from my repo.

However I can't figure out is how to tell it to use the patch-versions (like `v3.26.1-69-g92752fc266f3`). The documentation ([reference/installation](https://docs.tigera.io/calico/latest/reference/installation/api#operator.tigera.io/v1.Installation)) tells me that images are loaded from

`Image format:<registry><imagePath>/<imagePrefix><imageName>:<image-tag>`

and there are ways how to specify `<registry>`, `<imagePath>` or `<imagePrefix>`, but there is no mention of how to specify custom <image-tag>.

Could you please advice how to do that?

**Comment by michaldobisek** [comment]
With some more research I realised that when I use the Tigera Operator Helm, then the image names and version to use seem to be hard-coded inside the tigera/operator image.

Using 
`docker run quay.io/tigera/operator:v1.30.7-0-g8cbb161896a4 --print-images=list`
one can list these images and version.

However it's still not clear to me if/how is there any way to utilize the images with the patch-tags (e.g. `v3.26.1-69-g92752fc266f3`) in this case.

**Comment by caseydavenport** [comment]
The patch tags are pre-release developer versions, not intended for general availability.

**Comment by caseydavenport** [comment]
> However I can't figure out is how to tell it to use the patch-versions (like v3.26.1-69-g92752fc266f3). The documentation ([reference/installation](https://docs.tigera.io/calico/latest/reference/installation/api#operator.tigera.io/v1.Installation)) tells me that images are loaded from

To close this off, those are development versions and not officially released. You can build the helm chart yourself and/or modify the images, but that's not a supported flow and is just a developer workflow.
