### ISSUE TITLE
Run calico cni on docker desktop kubernetes

### ISSUE THREAD

**Issue by cveld** [projectcalico/calico#8102]
In order to explore network policies I require a CNI within kubernetes that runs on docker desktop.

I have tried to install calico through the following command:
`kubectl apply -f https://docs.projectcalico.org/manifests/calico.yaml`

## Expected Behavior

Calico up and running, able to apply network policies.

## Current Behavior

I get the error:
`Error: failed to start container "mount-bpffs": Error response from daemon: path /sys/fs is mounted on /sys but it is not a shared mount`

## Your Environment

* Calico version: 3.26.1
* Orchestrator version (e.g. kubernetes, mesos, rkt): docker desktop kubernetes windows v4.23.0
* Operating System and version: Windows 11 Enterprise    Version	10.0.22621 Build 22621

**Comment by caseydavenport** [comment]
I'm not too surprised it's not working on Docker desktop, as it's not a platform we test on or expect to be used in production. You'll need to make sure the correct kernel, mounts, etc are in use. Docker desktop isn't one of our supported platforms so I'm afraid we can't provide too much help here, other than suggesting to investigate how to configure the necessary mounts in a Docker Desktop environment - ultimately Docker Desktop is using a VM under the covers, to ensuring that VM meets Calico's requirements is necessary.
