### ISSUE TITLE
BIRD is not ready: connection refused

### ISSUE THREAD

**Issue by SlothPivot** [projectcalico/calico#8111]
Calico CNI running on 3 nodes: 1 Master node and 2 Worker nodes.
Seems to be running without any issues on the worker nodes, but gives the following error on a master node:
![image](https://github.com/projectcalico/calico/assets/77167734/d243f0ce-8960-4a95-98ee-d3bd7bdbe99d)
![image](https://github.com/projectcalico/calico/assets/77167734/0e7c072e-fdb3-4168-89f0-33d60b75c7a4)

This is a testing environment, so I would disable BGP all-together, but since I'm quite new to K8s and Calico CNI, don't really understand how to do that and should I even do that.

Deleting the pod or daemonset restart did not solve the issue.
Not sure what could be the consequences if I just leave it that way, because everything seems to be working for now, except the calico-node. But I would want to get to the root of the issue.
![image](https://github.com/projectcalico/calico/assets/77167734/5c0fda57-a01a-4748-bab3-33908ea71544)

**Comment by MichalFupso** [comment]
Hi @SlothPivot, are you able to share more about how you installed calico and what version are you using. Also if you have not done so, one of the network requirements for BGP is to allow TCP 179 on your host and firewall.

**Comment by SlothPivot** [comment]
@MichalFupso Kubernetes v1.28.1-00; Calico v3.26.1
The BGP ports were opened on the standard ufw firewalls.
I've noticed that if I delete all the pods, sometimes one random Calico node doesn't get configuration files (bird.cfg and bird6.cfg) and sometimes all of them do.

**Comment by mazdakn** [comment]
@SlothPivot the output suggest something prevents creating the BIRD's config file. Can you share the `calico-node` logs files? The log file should include the reason for the issue.

Also you can disable BGP if you have overlay encapsulation enabled. This link shows both options: https://docs.tigera.io/calico/latest/networking/configuring/
