### ISSUE TITLE
If there are multiple ippools, how do I prioritize them?

### ISSUE THREAD

**Issue by An-zhe** [projectcalico/calico#8120]
i.e.  
i have three ippool for kubernetes ,   ippools as below:
default-ippool
ippoo-internal
ippool-external  

And  , for some services , we   configure the  kubernetes deployment  annotations  for ippool-internal and ipoool-external  ,  But in addition, we need all the others services to be able to use the default ippool by default without configure annotations.

Can we set the priority for ippools ?

    
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Calico version
* Orchestrator version (e.g. kubernetes, mesos, rkt):
* Operating System and version:
* Link to your project (optional):

**Comment by An-zhe** [comment]
Hi @coutinhop  , Thanks for your reply ,What I mean is, if there are two same  ippools  and I don't set annotations,   How does Calico assign IP addresses to pods,   are they randomly assigned between these two IPpools? Can it specify priority?

**Comment by caseydavenport** [comment]
There's no priority between IP pools, and no clearly expressible priority given. It depends on several factors, including which IPs might already be assigned on that node. 

If you want to be able to deterministically select a pool for a given pod / node, you will need to use the IP pool selectors

**Comment by caseydavenport** [comment]
> And , for some services , we configure the kubernetes deployment annotations for ippool-internal and ipoool-external , But in addition, we need all the others services to be able to use the default ippool by default without configure annotations.

I would give `ippool-internal` and `ippool-external` node selectors that match no nodes - this way, they won't be used _except_ by pods that have the annotations. Then, any pod that doesn't have an annotation will use the default IP pool, since it's the only one that selects nodes.

**Comment by An-zhe** [comment]
Thanks @caseydavenport

**Comment by An-zhe** [comment]
Thanks
