### ISSUE TITLE
Impact of a cni daemonset rolling restart?

### ISSUE THREAD

**Issue by bh-tt** [projectcalico/calico#8131]
We recently moved some more stateful applications (e.g. databases) to our k8s cluster, and we were wondering about the possible impact of a CNI restart (mostly in the context of a patch/minor version upgrade).

If my understanding of the CNI is correct then the daemonset pod need only be running when a pod is created or deleted in order to add/remove a pod IP from the network, and a daemonset pod restart should have no impact on the networking of existing pods?

Additionally, how do networkpolicies factor into this? I assume a change in a networkpolicy requires the daemonset pod to be up in order to process the change?

I could not find information related to this in the calico docs, althoug the CNI spec suggests the above is correct.

## Your Environment

* Calico version 3.26.3
* Orchestrator version (e.g. kubernetes, mesos, rkt): kubernetes 1.28.2
* Operating System and version: 
* Link to your project (optional):

**Comment by sridhartigera** [comment]
@bh-tt You are right. Rolling update of the daemonset should have no impact on the networking of the existing pods. In order to process any change in the networkpolicy, the pods should be up and running.
