### ISSUE TITLE
Route missing when kubernetes node removed and add again

### ISSUE THREAD

**Issue by crliu3227** [projectcalico/calico#8135]
## Current Behavior
kubernetes node removed，some pods still running on the removed node,  at this point calico-kube-controller will not cleanup node  due to this ips, logs:
![image](https://github.com/projectcalico/calico/assets/33312307/da4f434d-7d7c-4619-8d03-1c16f8ca041a)
when kubelet restart, the node will register in k8s apiserver again with the same node name, but at this time old pods not cleared before can't be connected by other k8s nodes, other k8s nodes don;t apply route to the node in vxlan node.
If I delete all old pods manually,  new pod running on this node connection will be setted.

## Excepet Behavior
Calico can handle old pods when node add again

## Your Environment

* Calico version: v3.24.1 vxlan
* Orchestrator version: kubernetes 1.24.3

**Comment by coutinhop** [comment]
@crliu3227 I don't think that is supposed to be supported. You should use `kubectl drain <node_name>` before removing the node... (unless I misunderstood what you meant, please feel free to clarify)
