### ISSUE TITLE
Support for BGP Unnumbered Interfaces/BGP Flowspec

### ISSUE THREAD

**Issue by shamalco** [projectcalico/calico#814]
I can't find any documentation about Calico support for BGP Unnumbered Interfaces or BGP Flowspec, Is there current support. If not can we add it to the roadmap with Extended Next-hop Encoding. I think its a useful feature for deployment in Data Centers.

**Comment by tmjd** [comment]
I am unaware of support for those (though I do not really know what they are TBH).
@robbrockbank or @kprabhak do either of you know if we support these?

I marked this as 'kind/support' for the time being but we can change it to feature request if it is confirmed that those are not supported.

**Comment by kprabhak** [comment]
Regd BGP unnumbered, I know of some existing deployments with Bird that accomplish this with some templating around Bird, in combination with a ToR switch which also has this capabilities. So this can be accomplished with some additional Calico/Bird templating work.

Alternatively, if one uses one of the alternative bgp back-ends to Calico, like GoBGP, these might also support Unnumbered BGP as described here: https://github.com/osrg/gobgp/blob/master/docs/sources/unnumbered-bgp.md

I'm not up to speed with the latest on Flowspec implementation status in Bird or GoBGP, perhaps @robbrockbank or (once he's back from vacation) @liljenstolpe might be able to comment. At least GoBGP seems to indicate that it supports Flowspec, per this link:  https://github.com/osrg/gobgp/blob/master/docs/sources/flowspec.md

**Comment by shamalco** [comment]
Thanks @kprabhak for the clarification. I think I switch backends to GoBGP and test BGP unnumbered and flow spec with it.
