### ISSUE TITLE
Calico has  etcd as datastore, AllowSpoofedSourcePrefixes doesn't take effect

### ISSUE THREAD

**Issue by clairelz-zhang** [projectcalico/calico#8144]
## Expected Behavior
I set environment variable FELIX_WORKLOADSOURCESPOOFING=Any when starting calico-node. I was using calico in etcd mode,  and I create pods with annotations "cni.projectcalico.org/allowedSourcePrefixes: '["0.0.0.0/0"]'". I was expecting there's iptable chain 
cali-rpf-skip added to skip rpf.
But there is no chain added.

## Steps to Reproduce (for bugs)
1. install calico node in etcd mode and set the enviromentment variables FELIX_WORKLOADSOURCESPOOFING=Any
2. create a pod with annotations cni.projectcalico.org/allowedSourcePrefixes: '["0.0.0.0/0"]'
3.check the iptables raw table to see if cali-rpf-skip chain like that '-A cali-rpf-skip -i cali63f339361b8 -m comment --comment "cali:w9ZtHJTJ8TNOC4wL" -j ACCEPT'  added to to skip rpffilter with the interface of the pod added.

## Your Environment
* Calico version 3.26.3
* Orchestrator version (e.g. kubernetes, mesos, rkt): k8s 1.23

**Comment by matthewdupre** [comment]
etcd mode is not recommended - could you please try KDD and let us know if that works?  It'll narrow down what's wrong significantly.

**Comment by fm9282** [comment]
It looks calico etcd mode does not handel this annotations(cni.projectcalico.org/allowedSourcePrefixes), so I try to add the following lines for calico cni in file cni-plugin/pkg/k8s/k8s.go, it works.


```
func CmdAddK8s(...) 
...
	// add allowedSourcePrefixes to workload endpoint
	var sourcePrefixes []string
	if annotation, ok := annot["cni.projectcalico.org/allowedSourcePrefixes"]; ok && annotation != "" {
		// Parse Annotation data
		var requestedSourcePrefixes []string
		err := json.Unmarshal([]byte(annotation), &requestedSourcePrefixes)
		if err != nil {
			return nil, fmt.Errorf("failed to parse '%s' as JSON: %s", annotation, err)
		}

		// Filter out any invalid entries and normalize the CIDRs.
		for _, prefix := range requestedSourcePrefixes {
			if _, n, err := cnet.ParseCIDR(prefix); err != nil {
				return nil, fmt.Errorf("failed to parse '%s' as a CIDR: %s", prefix, err)
			} else {
				sourcePrefixes = append(sourcePrefixes, n.String())
			}
		}
		endpoint.Spec.AllowSpoofedSourcePrefixes = sourcePrefixes
		logger.WithField("endpoint", endpoint).Info("Added allowedSourcePrefixes to endpoint")
	}
```

**Comment by matthewdupre** [comment]
@fm9282 thanks for looking - could you please raise a PR and let me know?

**Comment by fm9282** [comment]
Sure, I will submit a PR later.
