### ISSUE TITLE
log metrics felix_log_errors maybe error count

### ISSUE THREAD

**Issue by gaopeiliang** [projectcalico/calico#8147]
```
rate(felix_log_errors) > 0  always , but we can not find any error about it .... 
```

we should see source code !

```
https://github.com/projectcalico/calico/blob/master/libcalico-go/lib/logutils/logutils.go#L496
func (h *BackgroundHook) Fire(entry *log.Entry) (err error) {

        ........

	for _, dest := range h.destinations {
		if ql.Level > dest.Level {
			continue
		}
		if waitGroup != nil {
			// Thread safety: we must call add before we send the wait group over the
			// channel (or the background thread could be scheduled immediately and
			// call Done() before we call Add()).  Since we don't know if the send
			// will succeed that leads to the need to call Done() on the 'default:'
			// branch below to correctly pair Add()/Done() calls.
			waitGroup.Add(1)
		}

		if ok := dest.Send(ql); !ok {
			// Background thread isn't keeping up.  Drop the log and count how many
			// we've dropped.
			if waitGroup != nil {
				waitGroup.Done()
			}
			
			// #######################################################
			// ###  here  dest.counter == felix_log_errors
			// ###  it maybe h.counter == felix_logs_dropped like annotation said distribute log error not I/O writer error
			
			// Increment the number of dropped logs
			dest.counter.Inc()
		}
	}
        ........
}


```

## Steps to Reproduce (for bugs)

1.   it is difficult to reproduce,  I meet onlyone  thousand of instance ....

2.   maybe IOLoopWrite grotinue have block case .... 

## Your Environment
* Calico version  3.21
* Orchestrator version (e.g. kubernetes, mesos, rkt):  kubernetes
* Operating System and version:  Linux 4.19

**Comment by coutinhop** [comment]
@gaopeiliang I'm sorry but I don't understand the issue you're facing. Could you share some more details please?

**Comment by gaopeiliang** [comment]
> @gaopeiliang I'm sorry but I don't understand the issue you're facing. Could you share some more details please?

just code maybe mistake ....

send to different log writer error, should add metrics felix_logs_dropped , not felix_log_errors

**Comment by mazdakn** [comment]
@gaopeiliang unfortunately it's hard for me to follow the issue, and understand it. Please follow the template, and be more clear about what you are stating.
