### ISSUE TITLE
error switching to ns: operation not permitted!

### ISSUE THREAD

**Issue by hamidrezakhosroabadi** [projectcalico/calico#8150]
## Expected Behavior
When i create a pod in Kubernetes, Calico should give an IP address to my pod.

## Current Behavior
Calico can not respond to Kubelet cni commands like add and delete and returns following error:

Oct 23 10:09:05 node37 kubelet[26109]: E1023 10:09:05.734268   26109 pod_workers.go:1294] "Error syncing pod, skipping" err="failed to \"CreatePodSandbox\" for \"my-pod_default(b6789ec1-5c7d-4185-9b2b-c1f06230f828)\" with CreatePodSandboxError: \"Failed to create sandbox for pod \\\"my-pod_default(b6789ec1-5c7d-4185-9b2b-c1f06230f828)\\\": rpc error: code = Unknown desc = failed to setup network for sandbox \\\"68e1f16b51104511ac0710fb3a93910d661c7b36dbf1dd1542a5c3b87b69d273\\\": plugin type=\\\"calico\\\" failed (add): error switching to ns /var/run/netns/cni-fa368223-e47d-d5aa-807e-2426b9a61c1a: Error switching to ns /var/run/netns/cni-fa368223-e47d-d5aa-807e-2426b9a61c1a: operation not permitted\"" pod="default/my-pod" podUID=b6789ec1-5c7d-4185-9b2b-c1f06230f828

## Context

This issue only exists on one of my nodes and was happened accidentally.
Also I can exec command to created netns with ip netns exec command.

## Your Environment

* Calico version: v3.25.1
* Orchestrator version (e.g. kubernetes, mesos, rkt): Kubernetes 1.27
* Operating System and version: Debian Bookworm
* Link to your project (optional):

**Comment by coutinhop** [comment]
@hamidrezakhosroabadi could you share some details about your setup? Did you use tigera-operator? How does your installation, ip pools, felixconfiguration look? Any particular bits that can help us reproduce this?

**Comment by bzsuni** [comment]
@hamidrezakhosroabadi 
so have you resolved this issue?
