### ISSUE TITLE
Usage doc needed: How to use labels to select external host IPs

### ISSUE THREAD

**Issue by tmjd** [projectcalico/calico#818]
Regularly it is asked how to define IPs that can be referenced with labels.  This can be done by defining a host endpoint (with one per IP address or multiple IPs in a host endpoint) with a label and then selecting that label.

It would be good to have a Usage doc explaining this.

**Comment by ozdanborne** [comment]
I'd love to see this done generically as it is very applicable to Mesos as well.

**Comment by caseydavenport** [comment]
In v3.1 we have GlobalNetworkSets to do this, so I'm going to close this.

**Comment by tmjd** [comment]
I still think a simple usage doc or FAQ saying that is what GlobalNetworkSets are for would be nice. The name GlobalNetworkSets does not convey necessarily that using them is how to select external IPs.

**Comment by caseydavenport** [comment]
Could be, though it's fairly well explained here: https://docs.projectcalico.org/v3.1/reference/calicoctl/resources/globalnetworkset
