### ISSUE TITLE
failed to create pod: host side routes for interface has already exists

### ISSUE THREAD

**Issue by cyclinder** [projectcalico/calico#8180]
## Expected Behavior

If there is already a route on the node for the same interface, we can ignore the error,

## Current Behavior

```
Warning  FailedCreatePodSandBox  86s               kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "3c8b059ce4c4cd7ae47eb9ebc8d1937afae2d0e23ec32cd3f4b9c464ab5d358d": plugin type="calico" failed (add): error adding host side routes for interface: calid29a1cadef5, error: route (Ifindex: 131, Dst: 172.25.136.1/32, Scope: link) already exists for an interface other than 'calid29a1cadef5': route (Ifindex: 12, Dst: 172.25.136.1/32, Scope: link, Iface: calif6cb5368383)
```

## Steps to Reproduce (for bugs)

We create 1000 pods at the same time (10 deployments, 10 replicas each), and I found some pods can't be created.

## Your Environment

* Calico version
* Orchestrator version (e.g. kubernetes, mesos, rkt):
* Operating System and version:
* Link to your project (optional):

**Comment by caseydavenport** [comment]
> If there is already a route on the node for the same interface, we can ignore the error,

I believe we already ignore the error if the route is targeting the same interface.

This can occur for a few reasons, IP exhaustion / borrowing being one of them.

**Comment by zeroooooop** [comment]
> > If there is already a route on the node for the same interface, we can ignore the error,
> 
> I believe we already ignore the error if the route is targeting the same interface.
> 
> This can occur for a few reasons, IP exhaustion / borrowing being one of them.

We have also encountered the same issue where we created nearly 3500 pods, and then experienced the same problem. However, after some time, these pods were successfully created again. What could be the possible reasons for this?

**Comment by caseydavenport** [comment]
This can happen if your IP address space is limited and IPs are reused rapidly across your cluster - either due to a large number of pods being created, or due to small IP pools or IPAM block sizes in your cluster.

If can also happen if you pod IP space conflicts with other addresses in your network. Usually though if it's a transient issue it's probably to do with a non-optimal IP pool configuration for your cluster's needs.

**Comment by emoxam** [comment]
calicoctl ipam show
+----------+----------------+-----------+------------+--------------+
| GROUPING |      CIDR      | IPS TOTAL | IPS IN USE |   IPS FREE   |
+----------+----------------+-----------+------------+--------------+
| IP Pool  | 192.168.0.0/16 |     65536 | 36 (0%)    | 65500 (100%) |
| IP Pool  | 10.0.0.0/16    |     65536 | 0 (0%)     | 65536 (100%) |
+----------+----------------+-----------+------------+--------------+

(combined from similar events): Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "9752a5e5b89ef0585650d6d5ede47406b6950a924969db74a5383063fb0c04b7": plugin type="calico" failed (add): error adding host side routes for interface: cali26600bacb30, error: route (Ifindex: 4813, Dst: 192.168.112.226/32, Scope: link) already exists for an interface other than 'cali26600bacb30': route (Ifindex: 27, Dst: 192.168.112.226/32, Scope: link, Iface: calif29ce899aab)

Why is this happens ?

calicoctl version
Client Version:    v3.23.3
Git commit:        3a3559be1
Cluster Version:   v3.23.3
Cluster Type:      k8s,bgp,kubeadm,kdd
