### ISSUE TITLE
Calico problems with kubernetes 1.28 in a virtualbox three node with Debian 12

### ISSUE THREAD

**Issue by gioguanuo** [projectcalico/calico#8186]
Hello ,
I have an issue with kubernetes 1.28 on virtual box machines equipped with Debian 12.
Installing a cluster with one master and two workers, the two workers perfectly identical, the same installation procedure.
After installing Calico compatible with K8s 1.28 one worker node is ready the second one not ready. From second node, not ready node, cannot ping the master node. 
After remove Calico all go in right way.
Some suggest?
Thank you in advance

**Comment by MichalFupso** [comment]
Hi @gioguanuo, can you please share how and what version of Calico did you install? Also can you please share calico node logs?

**Comment by gioguanuo** [comment]
Hello,
I have solved the problem. I will share with you the solution in the next days and thank you to each person that try to help me.
For Michal the version of Calico was the last, on a Debian 12 installation
Thank you once again

**Comment by pholophus** [comment]
how did you solve it?
