### ISSUE TITLE
How does Calico prevent the same IP block from being allocated to a host

### ISSUE THREAD

**Issue by smallemployees** [projectcalico/calico#8211]
## Expected Behavior

How does Calico prevent IP conflicts
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Calico version
* Orchestrator version (e.g. kubernetes, mesos, rkt):
* Operating System and version:
* Link to your project (optional):

**Comment by MichalFupso** [comment]
When Calico creates an IP block, there is also a BlockAffinity resource created. BlockAffinity is block resource for an IPAM block. You can see more in our documentation https://docs.tigera.io/calico/latest/reference/resources/blockaffinity#blockaffinity
