### ISSUE TITLE
Include Updated CRD Definitions for Calico Operator Helm Chart

### ISSUE THREAD

**Issue by justdan96** [projectcalico/calico#8214]
The following PR was merged to `master` back in June but the updated CRD definitions have yet to make it into the latest Calico Opperator Helm charts: https://github.com/projectcalico/calico/pull/7818
When can we expect the updated CRD manifests to make it into a 3.26.x release? We need to implement PTSC for the Calico APIServer but until the APIServer CRD is updated we are unable to do this. 

## Expected Behavior

Make some changes to the `values.yaml` for the Helm chart to add Pod Topology Spread Constraints for the Calico APIServer, have the calico-apiserver deployment change.

## Current Behavior

The deployment will fail as the current CRDs do not include support for setting `apiServer.apiServerDeployment.spec.template.spec.topologySpreadConstraints`.

## Possible Solution

Bring in https://github.com/projectcalico/calico/pull/7818 for the next chart release.

## Steps to Reproduce (for bugs)

1. Use latest Helm chart.
2. Try to set `apiServer.apiServerDeployment.spec.template.spec.topologySpreadConstraints`.
3. Watch the deployment fail.

## Context

We are using the latest version of the Calico Operator Helm chart.

## Your Environment

Calico Operator 3.26.3.

**Comment by coutinhop** [comment]
@justdan96 https://github.com/projectcalico/calico/pull/7818 will be released in Calico v3.27.0, which is coming soon. Let me ping @matthewdupre @caseydavenport to ask whether we should consider cherry-picking this to other release branches.

**Comment by justdan96** [comment]
If they make it into the 3.27.0 release then that should be acceptable for us, thank you for replying so quickly.

**Comment by matthewdupre** [comment]
@coutinhop I think it's worth cherry-picking to 3.26

**Comment by caseydavenport** [comment]
@coutinhop did this end up getting picked?

**Comment by caseydavenport** [comment]
Cool, I think with https://github.com/projectcalico/calico/pull/8281 we can close this now.
