### ISSUE TITLE
Calico host policy support for nat table

### ISSUE THREAD

**Issue by rtheis** [projectcalico/calico#823]
Feature Request: Update the Calico policy resource (http://docs.projectcalico.org/v2.2/reference/calicoctl/resources/policy) to support host policies in the nat table.

## Expected Behavior
Administrators would like to use Calico policies to protect their hosts that cannot be bypassed when workloads are created. This is effectively what happens when using Calico with Kubernetes.  That is, Kubernetes services of type `LoadBalancer` and `NodePort` result in nat table rules that effectively bypass Calico host policies.  This is due to DNAT of these services which makes it difficult for an administrator to create and manage policies to protect their hosts while opening holes for Kubernetes services based on their described policy.

Specific use cases:
* Block a Kubernetes service via the nodes' public interface
* Block the Kubernetes node port range on the public interface
* Allow Kubernetes service access from a source CIDR.

## Current Behavior
The Calico policy resource supports host policies in the filter table only.

## Possible Solution
The basic idea is to apply Calico host policy to the beginning of the nat table PREROUTING chain in order to capture destination IP and port before DNAT in order to mark applicable connections to be dropped in the filter table.

For example:
```
iptables -t nat -N CALICO-FW-NAT
iptables -t nat -I PREROUTING -j RETURN -m mark --mark 0x8000/0x8000
iptables -t nat -I PREROUTING -j CALICO-FW-NAT
iptables -t nat -I CALICO-FW-NAT -p tcp -m multiport --dport 30000:32767 -j KUBE-MARK-DROP
iptables -t nat -I CALICO-FW-NAT -p udp -m multiport --dport 30000:32767 -j KUBE-MARK-DROP
```

## Context
See expected behavior.

## Your Environment
* Calico version: v2.1.5
* Orchestrator version (e.g. kubernetes, mesos, rkt): Kubernetes v1.5.6
* Operating System and version: Ubuntu 16.04.2

**Comment by neiljerram** [comment]
Draft doc for proposed new 'preDNAT' policy flag: https://github.com/projectcalico/calico/pull/910

**Comment by neiljerram** [comment]
libcalico-go change to add 'preDNAT' flag to Policy resource: https://github.com/projectcalico/libcalico-go/pull/475

**Comment by neiljerram** [comment]
New feature will be available in Calico 2.4

**Comment by rtheis** [comment]
@neiljerram this looks great.  I can't wait to try it out in Calico 2.4.

**Comment by rtheis** [comment]
I tested the Calico v2.4 RC2 support for pre-DNAT policies and found that the support passed all my tests and appeared to meet all of our use cases.  Thank you and great work!

**Comment by neiljerram** [comment]
Thanks @rtheis - feedback very much appreciated!
