### ISSUE TITLE
calico-apiserver & calic-systems namespace labelling

### ISSUE THREAD

**Issue by elsnepal** [projectcalico/calico#8244]
# Summary

While using tigera operator helm chart, `calico-apiserver` & `calico-system` namespace are created as part of bundle. I dont see any way to label those namespaces. 

It looked like it should be possible as per doc: https://docs.tigera.io/calico/latest/reference/installation/api#operator.tigera.io/v1.APIServer, however it throws back as unknown field.

Is it possible to add feature to allow label namespaces?

# Version 

3.26.1

**Comment by matthewdupre** [comment]
This isn't possible today - you can add labels to the API server Deployment (here: https://docs.tigera.io/calico/latest/reference/installation/api#operator.tigera.io/v1.APIServerDeploymentPodTemplateSpec), but there's no support for adding them to the namespace itself.  The metadata field in the APIServer section of the doc you linked refers to the APIServer custom resource's metadata - not anything it creates.

Is there a particular use case you have for labeling these namespaces?

**Comment by sridhartigera** [comment]
Feel free to reopen if there is any update.

**Comment by akamac** [comment]
We do have a use case for this: we are filtering by namespace labels which namespaces we want to monitor in dev cluster.
