### ISSUE TITLE
CALICO-IPAM not using NODENAME nor FELIX_FELIXHOSTNAME

### ISSUE THREAD

**Issue by frederic-loui** [projectcalico/calico#826]
When a pod is created on a cluster with minions having multiple interface. Calico/Felix does not use NODENAME / FELIX_FELIXHOSTNAME but still use "get_host_by_name()" in order to write the key in etcd.

## Expected Behavior

In etcd the key written should be in the form:
/calico/ipam/v2/host/<NODENAME>/ipv4/block/192.168.3.128-26
Now it is still in the form:
/calico/ipam/v2/host/<sys.gethostbyname()>/ipv4/block/192.168.3.128-26

calico/felix should use NODENAME or FELIX_FELIXHOSTNAME when precised.

## Current Behavior

The result is that only /32 route to pod is advertised and not the right /26
host-local tested and calico-ipam node tested.

## Possible Solution

calico/felix should use NODENAME or FELIX_FELIXHOSTNAME when precised.

## Steps to Reproduce (for bugs)

1. fired up a k8s cluster with multiple interface
2. use IP address for NODENAME or FELX_FELIXNODENAME in cni config an systemd calico config
3. establish BGP
4. ls --recursively etcd database you'll see different /26 allocation s 

## Context

Only /32 pod route were advertised into the cluster. Not the /26.

## Your Environment

* Calico version: 2.2
* Orchestrator version (e.g. kubernetes, mesos, rkt): kubernetes 1.6.4
* Operating System and version: Ubuntu 16.04

**Comment by caseydavenport** [comment]
Hm.  It's not Felix that writes those values into etcd, rather it's the calico-ipam CNI plugin.  What does your CNI config look like? Does it have a `hostname` or `nodename` specified?

**Comment by frederic-loui** [comment]
Thanks for the clarification/precision.
When my workers start I use the environment variable: NODENAME=10.1.0.2 and in doubt also set HOSTNAME=10.1.0.2. etcd reflect everything but when I fire up a pod the hostname()=kube2-2 is written into etcd insteadd of 10.1.0.2. I've corrected my CNI config file and removed    "nodename": "10.1.0.2" and used the hostname as NODENAME. (i.e NODENAME=kube2-2) that fixed the issue. But I feel that this is not the right behaviour. If NODENAME is precised, calico-ipam should use it and write into etcd NODENAME value and not use gethostbyname() function.

My CNI config:

{
    "name": "calico-k8s-network",
    "nodename": "10.1.0.2"
    "cniVersion": "0.1.0",
    "type": "calico",
    "etcd_endpoints": "https://172.16.1.1:2379",
    "etcd_ca_cert_file": "/var/lib/kubernetes/ca.pem",
    "etcd_cert_file": "/var/lib/kubernetes/kubernetes.pem",
    "etcd_key_file": "/var/lib/kubernetes/kubernetes-key.pem",
    "log_level": "info",
    "ipam": {
        "type": "calico-ipam",
        "assign_ipv4": "true",
        "assign_ipv6": "false",
        "ipv4_pools": ["192.168.2.0/24"]
    },
    "policy": {
        "type": "k8s"
    },
    "kubernetes": {
        "kubeconfig": "/var/lib/kubelet/kubeconfig"
    }
}
