### ISSUE TITLE
 etcd-snapshot fails on k3s server

### ISSUE THREAD

**Issue by MalikaML** [projectcalico/calico#8275]
## Environmental Info:
K3s Version: k3s version v1.26.3+k3s1
go version go1.19.7
Operating System: Debian GNU/Linux 12
Cluster configuration: 1 master node and 3 worker nodes

## Current Behavior
When executing the `sudo k3s etcd-snapshot save` command, an error message is returned:
`FATA[0000] etcd database not found in /var/lib/rancher/k3s/server`

To install k3sup on my system, I used these commands: (k3s version: v1.27.6+k3s1)
```
curl -sLS https://get.k3sup.dev | sh
sudo install k3sup /usr/local/bin/
```
To add the master node, I used this command : (k3s version: v1.26.3+k3s1)
`k3sup install \
 --ip <ipv4-master-1> \
 --user root \
 --k3s-version <latest-version> \
 --local-path config.yaml \
 --context <cluster-name> \
 --tls-san <ipv4-virtual-ip> \
 --k3s-extra-args='--disable servicelb --flannel-backend=none
--cluster-cidr=10.45.0.0/16
--service-cidr=10.46.0.0/16 --disable-network-policy
--disable traefik
--node-ip=<ipv4-master-1>'
`
## Expected Behavior
The k3s etcd-snapshot save command should create an etcd snapshot without encountering errors.

## Additional context / logs:
If I run the command` ls /var/lib/rancher/k3s/server/db/` it displays these files:
`etcd   snapshots   state.db   state;db-shm   state.db-wal` (so it means I have an etcd database to snapshot, right?)

And if run the command `ls /var/lib/rancher/k3s/server/` it displays these files: 
`agent-token   cred   db   etc   kine.sock   manifests   node-token   static   tls   token`

**Comment by MalikaML** [comment]
@brandond, can you please help me out with this ? Thank you

**Comment by brandond** [comment]
I'd be glad to if you open it in the k3s-io/k3s repo, and not in a completely unrelated project?

**Comment by coutinhop** [comment]
This definitely looks like one for github.com/k3s-io/k3s and not the Calico repo, closing it here, @MalikaML please do open an issue in the k3s repo

**Comment by MalikaML** [comment]
My bad! didn't pay attention at all. Will open an issue in the k3s repo, thank you
