### ISSUE TITLE
Clarify which section IPAM manipulation annotations should be placed in

### ISSUE THREAD

**Issue by tmjd** [projectcalico/calico#828]
The docs at http://docs.projectcalico.org/v2.2/reference/cni-plugin/configuration#ipam-manipulation-with-kubernetes-annotations lists annotations but not a full example using the annotation.  This has been a problem a couple times because annotations are not restricted to the metadata section.

## Expected Behavior
Have a full example of a pod or deployment manifest with IPAM manipulation.

## Current Behavior
Only have 2 lines with annotation and then the annotation value.

## Possible Solution
Docs updated

## Context
https://github.com/projectcalico/calicoctl/issues/1652

**Comment by ozdanborne** [comment]
I don't know that we need to add a full example, but we should definitely clear up which metadata section the annotation needs to go in.

**Comment by tmjd** [comment]
True a full example probably isn't necessary.  We should add some wording and maybe we could add some kind of example too.  If an example would be too much text then maybe we can add something that is collapsed by default or a we could link to an example.

**Comment by caseydavenport** [comment]
I think it says now that it needs to be applied to the pod metadata.
