### ISSUE TITLE
Pod (dnsutils) cannot resolve internal cluster domain (eg., kubernetes.deafult)  and external host (eg., github.com)

### ISSUE THREAD

**Issue by MingCHEN-Github** [projectcalico/calico#8284]
## Expected Behavior
The dnsutils pod can resolve the domain of "kubernetes.default" by running the command of  `nslookup kubernetes.default`  and resolve the the host of `github.com` inside the pod

## Current Behavior
1.  Following  [k8s dns-debugging-resolution](https://kubernetes.io/docs/tasks/administer-cluster/dns-debugging-resolution/) , and running a `dnsutils` pod in k8s cluster with calico as the network add-on.
2.  Go into the `dnsutils` pod by running `kubectl exec -i -t dnsutils -- /bin/bash`

> root@dnsutils:/# cat /etc/resolv.conf 
search default.svc.cluster.local svc.cluster.local cluster.local openstacklocal 
nameserver 10.96.0.10
options ndots:5
root@dnsutils:/# 
root@dnsutils:/# nslookup kubernetes.default
;; connection timed out; no servers could be reached
root@dnsutils:/# host github.com
;; connection timed out; no servers could be reached
root@dnsutils:/# 

## Possible Solution

Since I am not familiar with Calico and my focus is more on k8s scheduling and pod placement,
I am not sure if there are some _**additional configurations needed for k8s cluster**_ when using the default Calico config as the networking add-on.

## Steps to Reproduce (for bugs)

1. The setup of k8s cluster with Calico :
  (1) After running [common.sh](https://github.com/MingCHEN-Github/kubeadm-scripts/blob/main/scripts/common.sh) in every node (master node and worker nodes) and [master.sh](https://github.com/MingCHEN-Github/kubeadm-scripts/blob/main/scripts/master.sh) in the master node, a ready K8s cluster will be set-up.
(2) the set-ups related to calico are in [master.sh](https://github.com/MingCHEN-Github/kubeadm-scripts/blob/main/scripts/master.sh)
>kubectl create -f https://raw.githubusercontent.com/projectcalico/calico/v3.26.1/manifests/tigera-operator.yaml
curl https://raw.githubusercontent.com/projectcalico/calico/v3.26.1/manifests/custom-resources.yaml -O

2. some coredns related services, pods, and endpoints seem running well:
<img width="1090" alt="image" src="https://github.com/projectcalico/calico/assets/5981694/79b4f20c-4262-408d-84e8-3e6ebc206746">

<img width="967" alt="image" src="https://github.com/projectcalico/calico/assets/5981694/11291229-0aba-4aff-bcd4-9727302863f1">

## Your Environment

* Calico version : 3.26.1
* Orchestrator version (e.g. kubernetes, mesos, rkt): Kubernetes v.1.27.4
* Operating System and version: Ubuntu 22.04 (Linux version 5.15.0-69-generic (buildd@lcy02-amd64-080) (gcc (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0, GNU ld (GNU Binutils for Ubuntu) 2.38) )
* Link to your project (optional):

**Comment by gaopeiliang** [comment]
check kube-proxy  is it work correctly ....

**Comment by johnny550** [comment]
I'll advise a few debugging tips
- adding the log plugin to the config map of your coredns pods
- ensure queries reach the coredns pods, first action item can help with that
- do you have any unexpected network policies?
- the search param in your resolv.conf has the right value? What is the dnspolicy of the pods from which you send queries?

**Comment by lwr20** [comment]
Since you've posted this in the Calico repo, perhaps checking your Calico setup is happy is a good idea?  
Can you show us the output of `kubectl get tigerastatus` please?  And `kubectl get po -n calico-system`.  

If those show issues, could you also get logs from the tigera operator and any unhappy calico-node pods.  The commands will look something like:
`kubectl logs -n tigera-operator tigera-operator-xxxx`
`kubectl logs -n calico-system calico-node-yyyy`

**Comment by lwr20** [comment]
> I am not sure if there are some additional configurations needed for k8s cluster when using the default Calico config as the networking add-on.

It depends on the underlying network setup.  Usually the answer to this is "no", but it can depend on whether your nodes have >1 network interface card, etc.  If you want a more detailed answer, you'll have to describe your nodes and the network between them in much more detail.

**Comment by MingCHEN-Github** [comment]
The issue is resolved with the assistance of @lwr20 .  
To be short, edit the `default-ipv4-ippool`  by running
`kubectl edit ippool default-ipv4-ippool `and change `vxlanMode: CrossSubnet` to `vxlanMode: Always`

For details, the troubleshooting and messages can be checked at Calico slack channel: https://calicousers.slack.com/archives/C0BCA117T/p1701687704681769

**Comment by MingCHEN-Github** [comment]
> I'll advise a few debugging tips
> 
> * adding the log plugin to the config map of your coredns pods
> * ensure queries reach the coredns pods, first action item can help with that
> * do you have any unexpected network policies?
> * the search param in your resolv.conf has the right value? What is the dnspolicy of the pods from which you send queries?

@johnny550 Thanks for your reply. I've tried these and still cannot resolve my issue. I resolved the issue by editing the` default-ipv4-ippool` by running
`kubectl edit ippool default-ipv4-ippool` and change `vxlanMode: CrossSubnet` to `vxlanMode: Always`
