### ISSUE TITLE
calico How to fix the POD IP not to change after restarting

### ISSUE THREAD

**Issue by shudingchao** [projectcalico/calico#8287]
Can calico support fixed POD IP? I want to know if there is a way, such as starting multiple PODs through StatefulSet or deployment, and fixing their IPs so that they cannot change after restarting.

**Comment by gongzixiangyuan** [comment]
cni.projectcalico.org/ipAddrs 
https://docs.tigera.io/calico/latest/reference/configure-cni-plugins

Is this what you need?

**Comment by shudingchao** [comment]
> cni.projectcalico.org/ipAddrs https://docs.tigera.io/calico/latest/reference/configure-cni-plugins
> 
> 这是你需要的吗？

这个是针对单个POD，我通过StatefulSet四个副本，重启之后IP就发生变化了
