### ISSUE TITLE
Calico for windows AutoCreateServiceAccountTokenSecret param handling is inconsistent

### ISSUE THREAD

**Issue by p-v-a** [projectcalico/calico#8290]
It looks like there is inconsistency in how AutoCreateServiceAccountTokenSecret is handled in install-calico-windows.ps1 script
According to params it should be string, at least it gets [default value of 'yes'](https://github.com/projectcalico/calico/blob/fb4f398a30c4aeadc4cedd47466f8d6f49284a4e/node/windows-packaging/install-calico-windows.ps1#L31)

Later in the code it gets checked as [boolean](https://github.com/projectcalico/calico/blob/fb4f398a30c4aeadc4cedd47466f8d6f49284a4e/node/windows-packaging/install-calico-windows.ps1#L269C27)

## Expected Behavior
```
/install-calico-windows.ps1 -DownloadOnly 'yes' -KubeVersion 1.25.9 -ServiceCidr 10.0.0.0/16 -DNSServerIPs 10.0.0.10 -CalicoBackend vxlan -AutoCreateServiceAccountTokenSecret 'No' -Datastore 'kubernetes'
```
and 

```
/install-calico-windows.ps1 -DownloadOnly 'yes' -KubeVersion 1.25.9 -ServiceCidr 10.0.0.0/16 -DNSServerIPs 10.0.0.10 -CalicoBackend vxlan -AutoCreateServiceAccountTokenSecret 'Yes' -Datastore 'kubernetes'
```

should be threaded differently, according to parameter value

## Current Behavior
Currently there is no difference between Yes or Now, because code checks parameter as boolean, so it always evaluate true.
One can set parameter to $true or $false, and then it works as expected
```
/install-calico-windows.ps1 -DownloadOnly 'yes' -KubeVersion 1.25.9 -ServiceCidr 10.0.0.0/16 -DNSServerIPs 10.0.0.10 -CalicoBackend vxlan -AutoCreateServiceAccountTokenSecret $false -Datastore 'kubernetes'
```

## Possible Solution
Solution would be to treat parameter same way as [DownloadOnly is threaded](https://github.com/projectcalico/calico/blob/fb4f398a30c4aeadc4cedd47466f8d6f49284a4e/node/windows-packaging/install-calico-windows.ps1#L536-L538)

## Steps to Reproduce (for bugs)
Commands in Expected Behaviour reproduces bug reliably.

## Your Environment
* Calico version 3.26.4
* Orchestrator version (e.g. kubernetes, mesos, rkt): kubernetes

**Comment by coutinhop** [comment]
Thanks @p-v-a for spotting this! It definitely is inconsistent at best, we'll fix this. As a side note, Calico v3.27.0 is releasing soon, and will make Calico for Windows installation and operations much easier, getting rid of the `install-calico-windows.ps1` script. We'll fix the script as it will still be supported for a while, but just a heads up that it will be deprecated in the future. Stay tuned and check it out when it releases!
