### ISSUE TITLE
Route entry lost

### ISSUE THREAD

**Issue by jumpsre** [projectcalico/calico#8291]
I have 3 master nodes where maser03 restarts due to hardware failure. After master03 is started, it is found that a routing table to master01 and master02 is lost, the function of this route is mainly coredns, may I ask why this route is lost?

## Your Environment

* Calico version: v3.14.1-4
* Orchestrator version (e.g. kubernetes, mesos, rkt): kubernetes v1.20.1-20
* Operating System and version:  ubuntu 18.04.4
* Link to your project (optional):

**Comment by mazdakn** [comment]
@jumpsre can you share the content of main route table and also point which ones are being lost?
