### ISSUE TITLE
calico-apiserver exits with exit code 0 occasionally 

### ISSUE THREAD

**Issue by jakubbujny** [projectcalico/calico#8292]
In unknown/random moments calico-apiserver exits with exit code 0 (k8s terminated reason: completed) causing container to restart.

## Expected Behavior
API server should be stable all the time

## Current Behavior
API server exits randomly with exit code 0

## Possible Solution
Unknown

## Steps to Reproduce (for bugs)
Unknown

## Context
None

## Your Environment
EKS 1.28
api server image: docker.io/calico/apiserver:v3.26.1
Tigera operator Helm chart version: 3.26.1

Last logs seen:
```
time="2023-12-07T13:20:24Z" level=info msg="Main client watcher loop"
time="2023-12-07T13:25:30Z" level=info msg="Process backend watcher done event in main client"
time="2023-12-07T13:25:30Z" level=info msg="Terminating main client watcher loop"
```

We have 2 instances of apiserver running, it often happens they restart both in the same moment but it's not the rule.

How can we debug this?

**Comment by tomastigera** [comment]
Do you have any more logs from the apiserver?

**Comment by OlehKyrtsun** [comment]
> Hi, was there any resolution to this issue? We are also seeing sporadic restarts of calico apiserver version 3.26.1.
> 
> Thank you, Ed

Any luck figuring out what's going on?

**Comment by zoezhangmattr** [comment]
got the same issue in 3.29.1 version., is this closed due to resolved? what is the solution?
