### ISSUE TITLE
Document hostname vs FQDN confusion

### ISSUE THREAD

**Issue by ozdanborne** [projectcalico/calico#83]
_From @fasaxc on September 8, 2016 9:44_

As per https://github.com/projectcalico/felix/issues/1027, felix and OpenStack can disagree on the hostname.  This was awkward to track down, maybe we can enhance the docs or add some heuristics to felix to spot the situation.

_Copied from original issue: projectcalico/felix#1096_

**Comment by tmjd** [comment]
This can also happen with felix (calico/node) and the CNI config and I found it difficult to identify the problem until I thought to check `calicoctl get nodes` and saw the duplicate entries.  #1093 is a report due to the same misconfiguration.

**Comment by caseydavenport** [comment]
We've fixed this.
