### ISSUE TITLE
Some nodes have vxlan-v6.calico IPV6 addresses that can be accessed, while others cannot

### ISSUE THREAD

**Issue by htxxy1015** [projectcalico/calico#8316]
## Possible Solution

The K8S cluster has 11 nodes, among which 3 nodes have vxlan v6 calico ipv6 addresses. ping6 access is normal, and the remaining 8 nodes occasionally get stuck during ping6, about 10 seconds later. Then ping6 the pod ipv6 address of this node. When capturing packets, see the prompt 2409:8057:5a00: 24:3001: d440 (vxlan v6 calico ipv6 address)>ht-gateway-66d74bd876-fsznv: ICMP6, destination unreachable

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Calico version 3.26.1
* Orchestrator version (e.g. kubernetes, mesos, rkt):k8s-1.23
* Operating System and version:Linux app-worker02 4.19.91-25.2.an7.x86_64 #1 SMP Wed Jan 5 16:35:24 CST 2022 x86_64 x86_64 x86_64 GNU/Linux
* Link to your project (optional):

**Comment by caseydavenport** [comment]
Have you checked the calico/node logs on those nodes to see if there are any errors?

**Comment by htxxy1015** [comment]
> Have you checked the calico/node logs on those nodes to see if there are any errors?
Yes, no issues were found with the logs of the calico node. I use the address ping6 vxlan v6 calico, sometimes it can be accessed normally, sometimes it is abnormal, and packet loss may occur. But the addresses of vxlan-v6.calico on three node nodes have always been normal without packet loss. How can we troubleshoot this situation

**Comment by caseydavenport** [comment]
I think the first places to look would be:

- the vxlan devices on each node to see if they are configured correctly.
- the Node annotations to see if Calico has assigned an IPv6 tunnel address to the node.
- trying to trace the packets that are being dropped to see _where_ they are dropped (is it iptables? routing? locally or on the remote node?)

Sharing the full calico/node logs might also help me to debug in case I spot anything out of the ordinary.

**Comment by htxxy1015** [comment]
> I think the first places to look would be:
> 
> * the vxlan devices on each node to see if they are configured correctly.
> * the Node annotations to see if Calico has assigned an IPv6 tunnel address to the node.
> * trying to trace the packets that are being dropped to see _where_ they are dropped (is it iptables? routing? locally or on the remote node?)
> 
> Sharing the full calico/node logs might also help me to debug in case I spot anything out of the ordinary.


1、The IP address of vxlan-v6.calico on node A is 2409:8057:5a00:: 24:3001:d440. There is a pod on node A with IP 2409:8057:5a00:: 24:3001:d443, and a pod on node B with IP 2409:8057:5a00:: 24:3001:f6c6. On node B, ping6 2409:8057:5a00:: 24:3001:d443, and capture packets in node A's pod. When ping6 fails, it prompts In IP6 2409:8057:5a00: 24:3001: d440>mtex gateway fd9ff475c wxpht: ICMP6, Destination unreachable.

2、There seems to be an access issue with IPv6 between vxlan v6. calico and pod

3、And when executing ip -6 neighbor on node A, there may be a route failed, but after a while, it is actually normal again. Has Calico affected the neighbor table

4、Is it that a certain IPV6 parameter value of the operating system has reached the online level

**Comment by htxxy1015** [comment]
> I think the first places to look would be:
> 
> * the vxlan devices on each node to see if they are configured correctly.
> * the Node annotations to see if Calico has assigned an IPv6 tunnel address to the node.
> * trying to trace the packets that are being dropped to see _where_ they are dropped (is it iptables? routing? locally or on the remote node?)
> 
> Sharing the full calico/node logs might also help me to debug in case I spot anything out of the ordinary.

1、The IP address of vxlan-v6.calico on node A is 2409:8057:5a00:: 24:3001:d440. There is a pod on node A with IP 2409:8057:5a00:: 24:3001:d443, and a pod on node B with IP 2409:8057:5a00:: 24:3001:f6c6. On node B, ping6 2409:8057:5a00:: 24:3001:d443, and capture packets in node A's pod. When ping6 fails, it prompts In IP6 2409:8057:5a00: 24:3001: d440>ht-test-fd9ff475c wxpht: ICMP6, Destination unreachable.

2、There seems to be an access issue with IPv6 between vxlan v6. calico and pod

3、And when executing ip -6 neighbor on node A, there may be a route failed, but after a while, it is actually normal again. Has Calico affected the neighbor table

4、Is it that a certain IPV6 parameter value of the operating system has reached the online level

**Comment by zhangzujian** [comment]
> > I think the first places to look would be:
> > 
> > * the vxlan devices on each node to see if they are configured correctly.
> > * the Node annotations to see if Calico has assigned an IPv6 tunnel address to the node.
> > * trying to trace the packets that are being dropped to see _where_ they are dropped (is it iptables? routing? locally or on the remote node?)
> > 
> > Sharing the full calico/node logs might also help me to debug in case I spot anything out of the ordinary.
> 
> 1、The IP address of vxlan-v6.calico on node A is 2409:8057:5a00:: 24:3001:d440. There is a pod on node A with IP 2409:8057:5a00:: 24:3001:d443, and a pod on node B with IP 2409:8057:5a00:: 24:3001:f6c6. On node B, ping6 2409:8057:5a00:: 24:3001:d443, and capture packets in node A's pod. When ping6 fails, it prompts In IP6 2409:8057:5a00: 24:3001: d440>ht-test-fd9ff475c wxpht: ICMP6, Destination unreachable.
> 
> 2、There seems to be an access issue with IPv6 between vxlan v6. calico and pod
> 
> 3、And when executing ip -6 neighbor on node A, there may be a route failed, but after a while, it is actually normal again. Has Calico affected the neighbor table
> 
> 4、Is it that a certain IPV6 parameter value of the operating system has reached the online level

You can try to set sysctl variable: `sysctl net.ipv6.route.max_size=16384`.

**Comment by htxxy1015** [comment]
1、Below are the calico node logs but I have not found any errors on my end：
2024-01-24 07:17:19.730 [INFO][89] monitor-addresses/autodetection_methods.go 103: Using autodetected IPv4 address on interface ens192: 10.110.206.71/24
2024-01-24 07:17:19.732 [INFO][89] monitor-addresses/autodetection_methods.go 103: Using autodetected IPv6 address on interface ens192: 2409:8062:5a10:300:1000:0:1:200c/116
2024-01-24 07:17:28.668 [INFO][88] felix/summary.go 100: Summarising 10 dataplane reconciliation loops over 1m5.3s: avg=6ms longest=27ms ()
2024-01-24 07:18:15.529 [INFO][88] felix/vxlan_resolver.go 328: VTEP information has not changed, skipping duplicate update node="k8s-master03"
2024-01-24 07:18:15.530 [INFO][88] felix/vxlan_resolver.go 328: VTEP information has not changed, skipping duplicate update node="k8s-master03"
2024-01-24 07:18:15.530 [INFO][88] felix/vxlan_resolver.go 328: VTEP information has not changed, skipping duplicate update node="k8s-master03"
2024-01-24 07:18:19.651 [INFO][88] felix/vxlan_resolver.go 328: VTEP information has not changed, skipping duplicate update node="k8s-master01"
2024-01-24 07:18:19.652 [INFO][88] felix/vxlan_resolver.go 328: VTEP information has not changed, skipping duplicate update node="k8s-master01"
2024-01-24 07:18:19.652 [INFO][88] felix/vxlan_resolver.go 328: VTEP information has not changed, skipping duplicate update node="k8s-master01"
2024-01-24 07:18:19.734 [INFO][89] monitor-addresses/autodetection_methods.go 103: Using autodetected IPv4 address on interface ens192: 192.168.1.71/24
2024-01-24 07:18:19.736 [INFO][89] monitor-addresses/autodetection_methods.go 103: Using autodetected IPv6 address on interface ens192: 2409:8062:4a13:300:1000:0:1:200c/116

2、I have try to set sysctl variable: sysctl net.ipv6.route.max_size=16384,But it didn't solve the problem

3、I executed ip -6 neigh | grep 2409:8062 on the problematic machine：
     1）2409:8062:4a13:300:1000:0:1:200d dev ens192 lladdr 00:50:56:a9:b9:5a router DELAY
          2409:8062:4a13:300:1000:0:1:2018 dev ens192 lladdr 00:50:56:a9:71:9c REACHABLE
         2409:8062:4a13:300:1000:0:1:2010 dev ens192 lladdr 00:50:56:a9:ae:9a router PROBE
         2409:8062:4a13:300:1000:0:1:200c dev ens192 lladdr 00:50:56:a9:32:a2 router REACHABLE
         2409:8062:4a13:300:1000:0:1:2013 dev ens192 lladdr 00:50:56:a9:12:ea router STALE
         2409:8062:4a13:300:1000:0:1:200f dev ens192  router FAILED
         2409:8062:4a13:300:1000:0:1:200b dev ens192  router FAILED
         2409:8062:4a13:300:1000:0:1:2016 dev ens192 lladdr 00:50:56:a9:3f:60 router DELAY
         2409:8062:4a13:300:1000:0:1:200e dev ens192  router FAILED
         2409:8062:4a13:300:1000:0:1:2011 dev ens192  router FAILED
         2409:8062:4a13:300:1000:0:1:2002 dev ens192 lladdr 00:50:56:a9:9e:aa REACHABLE
     
    2）2409:8062:4a13:300:1000:0:1:200d dev ens192 lladdr 00:50:56:a9:b9:5a router STALE
2409:8062:4a13:300:1000:0:1:2018 dev ens192 lladdr 00:50:56:a9:71:9c REACHABLE
2409:8062:4a13:300:1000:0:1:2010 dev ens192 lladdr 00:50:56:a9:ae:9a router REACHABLE
2409:8062:4a13:300:1000:0:1:200c dev ens192 lladdr 00:50:56:a9:32:a2 router DELAY
2409:8062:4a13:300:1000:0:1:2013 dev ens192  router FAILED
2409:8062:4a13:300:1000:0:1:200f dev ens192 lladdr 00:50:56:a9:35:f7 router REACHABLE
2409:8062:4a13:300:1000:0:1:200b dev ens192 lladdr 00:50:56:a9:4f:6a router REACHABLE
2409:8062:4a13:300:1000:0:1:2016 dev ens192 lladdr 00:50:56:a9:3f:60 router REACHABLE
2409:8062:4a13:300:1000:0:1:200e dev ens192 lladdr 00:50:56:a9:58:7e router REACHABLE
2409:8062:4a13:300:1000:0:1:2011 dev ens192 lladdr 00:50:56:a9:27:37 router REACHABLE
2409:8062:4a13:300:1000:0:1:2002 dev ens192 lladdr 00:50:56:a9:9e:aa REACHABLE

2409:8062:4a13:300:1000:0:1:2011 from route faild to router REACHABLE


@zhangzujian @caseydavenport

**Comment by caseydavenport** [comment]
@htxxy1015 did you make any progress on this?
