### ISSUE TITLE
Remove "calicoctl as a pod"

### ISSUE THREAD

**Issue by caseydavenport** [projectcalico/calico#8322]
calicoctl was always meant as a CLI tool.

The "calicoctl as a pod" deployment method was a stopgap before we had an API server, but now we do!

We should remove the documentation and manifests that support calicoctl as a pod - it results in lots of confusing behaviors since calicoctl isn't meant to run containerized and some commands require access to host resources that result in confusing results in this mode.

e.g.,

- https://github.com/projectcalico/calico/issues/7538

**Comment by lwr20** [comment]
Isn't calicoctl-as-a-pod also useful to cover the GitOps problem where the calico apiserver isn't up yet?

**Comment by caseydavenport** [comment]
I think the problem you're referring to is that using a GitOps approach to both install Calico itself, as well as install Calico API resources like GlobalNetworkPolicy, has an ordering dependency - namely, that Calico must be installed (with the API server enabled) before the tooling can install the GNP.

The better way to handle that is by splitting your configuration, such that Calico resources are only installed by your config management after Calico itself is installed and ready.
