### ISSUE TITLE
 Missing changelog file for v3.27.0

### ISSUE THREAD

**Issue by xoxys** [projectcalico/calico#8342]
Same issue again, see https://github.com/projectcalico/calico/issues/8236. You might want to check your release process.

**Comment by caseydavenport** [comment]
CC @danudey

**Comment by caseydavenport** [comment]
https://github.com/projectcalico/calico/pull/8343

**Comment by xoxys** [comment]
Thanks!

**Comment by danudey** [comment]
@xoxys The release notes have been added to the `release-v3.27` branch [in the standard location](https://github.com/projectcalico/calico/blob/release-v3.27/release-notes/v3.27.0-release-notes.md).
