### ISSUE TITLE
Calico fail on installation: pod stuck at container creating with calico:v3.26.1 on Kubernetes V:1.28.1

### ISSUE THREAD

**Issue by dareth-koh** [projectcalico/calico#8344]
Fresh installation with almalinux8 

```
node/kub-master    Ready    control-plane   5d1h   v1.28.2   10.0.1.2      <none>        AlmaLinux 8.9 (Midnight Oncilla)   4.18.0-513.9.1.el8_9.x86_64   containerd://1.6.25
node/kub-worker1   Ready    <none>          5d1h   v1.28.2   10.0.1.3      <none>        AlmaLinux 8.9 (Midnight Oncilla)   4.18.0-513.9.1.el8_9.x86_64   containerd://1.6.25
node/kub-worker2   Ready    <none>          5d1h   v1.28.2   10.0.1.4      <none>        AlmaLinux 8.9 (Midnight Oncilla)   4.18.0-513.9.1.el8_9.x86_64   containerd://1.6.25
```

```
NAMESPACE     NAME                                           READY   STATUS                  RESTARTS       AGE    IP         NODE          NOMINATED NODE   READINESS GATES
NAMESPACE     NAME                                           READY   STATUS                  RESTARTS       AGE    IP         NODE          NOMINATED NODE   READINESS GATES
kube-system   pod/calico-kube-controllers-7ddc4f45bc-8bx8z   0/1     ContainerCreating       0              80m    <none>     kub-worker1   <none>           <none>
kube-system   pod/calico-node-5j8cn                          0/1     Init:CrashLoopBackOff   18 (55s ago)   80m    10.0.1.4   kub-worker2   <none>           <none>
kube-system   pod/calico-node-rg45d                          1/1     Running                 0              80m    10.0.1.2   kub-master    <none>           <none>
kube-system   pod/calico-node-zfkb5                          0/1     Init:CrashLoopBackOff   18 (63s ago)   80m    10.0.1.3   kub-worker1   <none>           <none>
kube-system   pod/coredns-5dd5756b68-h7xtt                   0/1     ContainerCreating       0              5d1h   <none>     kub-worker2   <none>           <none>
kube-system   pod/coredns-5dd5756b68-svqhg                   0/1     ContainerCreating       0              5d1h   <none>     kub-worker2   <none>           <none>
```

# kubectl config view

```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: DATA+OMITTED
    server: https://10.0.1.2:6443
  name: kubernetes
contexts:
- context:
    cluster: kubernetes
    user: kubernetes-admin
  name: kubernetes-admin@kubernetes
current-context: kubernetes-admin@kubernetes
kind: Config
preferences: {}
users:
- name: kubernetes-admin
  user:
    client-certificate-data: DATA+OMITTED
    client-key-data: DATA+OMITTED
```

# kubectl describe service kubernetes

```
Name:              kubernetes
Namespace:         default
Labels:            component=apiserver
                   provider=kubernetes
Annotations:       <none>
Selector:          <none>
Type:              ClusterIP
IP Family Policy:  SingleStack
IP Families:       IPv4
IP:                10.96.0.1
IPs:               10.96.0.1
Port:              https  443/TCP
TargetPort:        6443/TCP
Endpoints:         10.0.1.2:6443
Session Affinity:  None
Events:            <none>
```

# more /etc/hosts

```
127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4
::1         localhost localhost.localdomain localhost6 localhost6.localdomain6
10.0.1.2        kub-master
10.0.1.3        kub-worker1
10.0.1.4        kub-worker2
10.0.1.5        kub-worker3
```

ifconfig

```
docker0: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
        inet 172.17.0.1  netmask 255.255.0.0  broadcast 172.17.255.255

ens33: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 10.0.1.2  netmask 255.255.255.0  broadcast 10.0.1.255

ens34: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.152.230  netmask 255.255.255.0  broadcast 192.168.152.255
```

-------------------------------------------------------------------------------
]# kubectl  logs calico-node-5j8cn  -n kube-system --follow

```
Defaulted container "calico-node" out of: calico-node, upgrade-ipam (init), install-cni (init), mount-bpffs (init)
Error from server (BadRequest): container "calico-node" in pod "calico-node-5j8cn" is waiting to start: PodInitializing

# kubectl  logs calico-node-5j8cn -c upgrade-ipam -n kube-system
2023-12-16 01:12:15.525 [INFO][1] ipam_plugin.go 79: migrating from host-local to calico-ipam...
2023-12-16 01:12:15.528 [INFO][1] migrate.go 66: checking host-local IPAM data dir dir existence...
2023-12-16 01:12:15.528 [INFO][1] migrate.go 68: host-local IPAM data dir dir not found; no migration necessary, successfully exiting...
2023-12-16 01:12:15.528 [INFO][1] ipam_plugin.go 109: migration from host-local to calico-ipam complete node="kub-worker2"

2023-12-16 02:35:48.663 [INFO][1] cni-installer/<nil> <nil>: /host/secondary-bin-dir is not writeable, skipping
W1216 02:35:48.663342       1 client_config.go:618] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
2023-12-16 02:36:18.710 [ERROR][1] cni-installer/<nil> <nil>: Unable to create token for CNI kubeconfig error=Post "https://10.96.0.1:443/api/v1/namespaces/kube-system/serviceaccounts/calico-cni-plugin/token": dial tcp 10.96.0.1:443: i/o timeout
2023-12-16 02:36:18.710 [FATAL][1] cni-installer/<nil> <nil>: Unable to create token for CNI kubeconfig error=Post "https://10.96.0.1:443/api/v1/namespaces/kube-system/serviceaccounts/calico-cni-plugin/token": dial tcp 10.96.0.1:443: i/o timeout
```

# kubectl  logs calico-node-5j8cn -c mount-bpffs -n kube-system

```
Error from server (BadRequest): container "mount-bpffs" in pod "calico-node-5j8cn" is waiting to start: PodInitializing
```

-------------------------------------------------------------------------------------------------

## Steps to Reproduce (for bugs)
1. kubectl create -f https://docs.projectcalico.org/manifests/calico.yaml

#more /etc/redhat-release
AlmaLinux release 8.9 (Midnight Oncilla)

#uname -a
Linux kub-master 4.18.0-513.9.1.el8_9.x86_64 

Please share some light how i can proceed as i had tried this method and i got the same errors.
```
kubectl create -f https://raw.githubusercontent.com/projectcalico/calico/v3.26.4/manifests/tigera-operator.yaml
kubectl create -f  https://raw.githubusercontent.com/projectcalico/calico/v3.26.4/manifests/custom-resources.yaml
```

**Comment by caseydavenport** [comment]
> 2023-12-16 02:36:18.710 [FATAL][1] cni-installer/<nil> <nil>: Unable to create token for CNI kubeconfig error=Post "https://10.96.0.1:443/api/v1/namespaces/kube-system/serviceaccounts/calico-cni-plugin/token": dial tcp 10.96.0.1:443: i/o timeout


Looks like the cni-installer container within the calico/node pod is unable to access the API server using the Service IP - this is likely either a problem with kube-proxy or with node-to-node networking preventing processes on that host from accessing the API server.

is kube-proxy running and healthy on the cluster?

**Comment by dareth-koh** [comment]
Hello @caseydavenport, kube proxies are running properly. 

kube-system   etcd-kub-master                            1/1     Running                 9 (5m4s ago)    7d23h
kube-system   kube-apiserver-kub-master                  1/1     Running                 9 (5m4s ago)    7d23h
kube-system   kube-controller-manager-kub-master         1/1     Running                 9 (5m4s ago)    7d23h
kube-system   kube-proxy-6tm8f                           1/1     Running                 7 (5m1s ago)    7d23h
kube-system   kube-proxy-9hrn7                           1/1     Running                 7 (4m46s ago)   7d23h
kube-system   kube-proxy-9j7fd                           1/1     Running                 9 (5m4s ago)    7d23h
kube-system   kube-scheduler-kub-master                  1/1     Running                 9 (5m4s ago)    7d23h
 

I1219 00:15:48.378389       1 server_others.go:69] "Using iptables proxy"
I1219 00:15:48.549947       1 node.go:141] Successfully retrieved node IP: 10.0.1.3
I1219 00:15:48.564654       1 conntrack.go:100] "Set sysctl" entry="net/netfilter/nf_conntrack_max" value=131072
I1219 00:15:48.565169       1 conntrack.go:52] "Setting nf_conntrack_max" nfConntrackMax=131072
I1219 00:15:48.587229       1 conntrack.go:83] "Setting conntrack hashsize" conntrackHashsize=32768
I1219 00:15:48.649749       1 conntrack.go:100] "Set sysctl" entry="net/netfilter/nf_conntrack_tcp_timeout_close_wait" value=3600
I1219 00:15:49.095772       1 server.go:632] "kube-proxy running in dual-stack mode" primary ipFamily="IPv4"
I1219 00:15:49.132273       1 server_others.go:152] "Using iptables Proxier"
I1219 00:15:49.132592       1 server_others.go:421] "Detect-local-mode set to ClusterCIDR, but no cluster CIDR for family" ipFamily="IPv6"
I1219 00:15:49.132661       1 server_others.go:438] "Defaulting to no-op detect-local"
I1219 00:15:49.133278       1 proxier.go:251] "Setting route_localnet=1 to allow node-ports on localhost; to change this either disable iptables.localhostNodePorts (--iptables-localhost-nodeports) or set nodePortAddresses (--nodeport-addresses) to filter loopback addresses"
I1219 00:15:49.137994       1 server.go:846] "Version info" version="v1.28.4"
I1219 00:15:49.138028       1 server.go:848] "Golang settings" GOGC="" GOMAXPROCS="" GOTRACEBACK=""
I1219 00:15:49.150238       1 config.go:188] "Starting service config controller"
I1219 00:15:49.156838       1 shared_informer.go:311] Waiting for caches to sync for service config
I1219 00:15:49.157564       1 config.go:97] "Starting endpoint slice config controller"
I1219 00:15:49.157828       1 shared_informer.go:311] Waiting for caches to sync for endpoint slice config
I1219 00:15:49.164309       1 config.go:315] "Starting node config controller"
I1219 00:15:49.193202       1 shared_informer.go:311] Waiting for caches to sync for node config
I1219 00:15:49.271256       1 shared_informer.go:318] Caches are synced for endpoint slice config
I1219 00:15:49.271690       1 shared_informer.go:318] Caches are synced for service config
I1219 00:15:49.301729       1 shared_informer.go:318] Caches are synced for node config


# curl -v localhost:10249/proxyMode
*   Trying ::1...
* TCP_NODELAY set
* connect to ::1 port 10249 failed: Connection refused
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 10249 (#0)
> GET /proxyMode HTTP/1.1
> Host: localhost:10249
> User-Agent: curl/7.61.1
> Accept: */*
>
< HTTP/1.1 200 OK
< Content-Type: text/plain; charset=utf-8
< X-Content-Type-Options: nosniff
< Date: Tue, 19 Dec 2023 00:26:18 GMT
< Content-Length: 8
<
* Connection #0 to host localhost left intact

**Comment by dareth-koh** [comment]
# ./calicoctl node status
Calico process is running.

IPv4 BGP status
No IPv4 peers found.

IPv6 BGP status
No IPv6 peers found.

# ./calicoctl node checksystem
Checking kernel version...
                4.18.0-513.9.1.el8_9.x86_64                                     OK
Checking kernel modules...
                xt_set                                                  OK
                ipt_ipvs                                                OK
                xt_bpf                                                  OK
                ipt_REJECT                                              OK
                ipt_rpfilter                                            OK
                xt_addrtype                                             OK
WARNING: Unable to detect the xt_icmp6 module as Loaded/Builtin module or lsmod
                xt_icmp6                                                FAIL
                xt_mark                                                 OK
                ip_set                                                  OK
                vfio-pci                                                OK
                xt_multiport                                            OK
                ip_tables                                               OK
                nf_conntrack_netlink                                    OK
                ipt_set                                                 OK
                xt_conntrack                                            OK
WARNING: Unable to detect the xt_icmp module as Loaded/Builtin module or lsmod
                xt_icmp                                                 FAIL
                xt_u32                                                  OK
                ip6_tables                                              OK
                xt_rpfilter                                             OK

**Comment by caseydavenport** [comment]
@dareth-koh what happens if you run this command from one of your host machines?

```
curk -k https://10.96.0.1:443/api/v1/namespaces/kube-system
```

**Comment by dareth-koh** [comment]
@caseydavenport 
i get no responses from the worker nodes.
NAMESPACE     NAME                                       READY   STATUS                  RESTARTS         AGE   IP         NODE          NOMINATED NODE   READINESS GATES
kube-system   calico-kube-controllers-7ddc4f45bc-8bx8z   0/1     ContainerCreating       0                16d   <none>     kub-worker1   <none>           <none>
kube-system   calico-node-5j8cn                          0/1     Init:CrashLoopBackOff   10 (3m7s ago)    16d   10.0.1.4   kub-worker2   <none>           <none>
kube-system   calico-node-rg45d                          1/1     Running                 2 (25m ago)      16d   10.0.1.2   kub-master    <none>           <none>
kube-system   calico-node-zfkb5                          0/1     Init:CrashLoopBackOff   10 (2m42s ago)   16d   10.0.1.3   kub-worker1   <none>           <none>
kube-system   coredns-5dd5756b68-h7xtt                   0/1     ContainerCreating       0                21d   <none>     kub-worker2   <none>           <none>
kube-system   coredns-5dd5756b68-svqhg                   0/1     ContainerCreating       0                21d   <none>     kub-worker2   <none>           <none>
kube-system   etcd-kub-master                            1/1     Running                 10 (25m ago)     21d   10.0.1.2   kub-master    <none>           <none>
kube-system   kube-apiserver-kub-master                  1/1     Running                 10 (25m ago)     21d   10.0.1.2   kub-master    <none>           <none>
kube-system   kube-controller-manager-kub-master         1/1     Running                 10 (25m ago)     21d   10.0.1.2   kub-master    <none>           <none>
kube-system   kube-proxy-6tm8f                           1/1     Running                 8 (24m ago)      21d   10.0.1.3   kub-worker1   <none>           <none>
kube-system   kube-proxy-9hrn7                           1/1     Running                 8 (24m ago)      21d   10.0.1.4   kub-worker2   <none>           <none>
kube-system   kube-proxy-9j7fd                           1/1     Running                 10 (25m ago)     21d   10.0.1.2   kub-master    <none>           <none>
kube-system   kube-scheduler-kub-master                  1/1     Running                 10 (25m ago)     21d   10.0.1.2   kub-master    <none>           <none>

**Comment by dareth-koh** [comment]
i had installed calicoctl to check the nodes and here's the output

[root@kub-master bin]# calicoctl node checksystem
Checking kernel version...
                4.18.0-513.9.1.el8_9.x86_64                                     OK
Checking kernel modules...
                vfio-pci                                                OK
                ipt_set                                                 OK
WARNING: Unable to detect the xt_icmp6 module as Loaded/Builtin module or lsmod
                xt_icmp6                                                FAIL
                xt_mark                                                 OK
                xt_multiport                                            OK
                ip_set                                                  OK
                ip6_tables                                              OK
                ipt_ipvs                                                OK
                xt_u32                                                  OK
                xt_addrtype                                             OK
                xt_set                                                  OK
                ip_tables                                               OK
                ipt_REJECT                                              OK
                nf_conntrack_netlink                                    OK
                ipt_rpfilter                                            OK
                xt_conntrack                                            OK
                xt_bpf                                                  OK
                xt_rpfilter                                             OK
WARNING: Unable to detect the xt_icmp module as Loaded/Builtin module or lsmod
                xt_icmp                                                 FAIL
System doesn't meet one or more minimum systems requirements to run Calico




[root@kub-master bin]# calicoctl ipam check --allow-version-mismatch
Checking IPAM for inconsistencies...

Loading all IPAM blocks...
Found 1 IPAM blocks.
 IPAM block 192.168.73.128/26 affinity=host:kub-master:
IPAM blocks record 1 allocations.

Loading all IPAM pools...
  192.168.0.0/16
Found 1 active IP pools.

Loading all nodes.
Found 1 node tunnel IPs.

Loading all workload endpoints.
Found 0 workload IPs.
Workloads and nodes are using 1 IPs.

Looking for top (up to 20) nodes by allocations...
  kub-master has 1 allocations
Node with most allocations has 1; median is 1

Scanning for IPs that are allocated but not actually in use...
Found 0 IPs that are allocated in IPAM but not actually in use.
Scanning for IPs that are in use by a workload or node but not allocated in IPAM...
Found 0 in-use IPs that are not in active IP pools.
Found 0 in-use IPs that are in active IP pools but have no corresponding IPAM allocation.

Check complete; found 0 problems.


[root@kub-master bin]# calicoctl ipam show --allow-version-mismatch
+----------+----------------+-----------+------------+--------------+
| GROUPING |      CIDR      | IPS TOTAL | IPS IN USE |   IPS FREE   |
+----------+----------------+-----------+------------+--------------+
| IP Pool  | 192.168.0.0/16 |     65536 | 1 (0%)     | 65535 (100%) |
+----------+----------------+-----------+------------+--------------+

**Comment by caseydavenport** [comment]
> i get no responses from the worker nodes.

This pretty much confirms that this isn't a problem with Calico, rather it's an issue with your Service implementation _or_ your node-to-node network.

You probably want to trace those requests and see where the packets are getting to, using tools like `tcpdump`, `iptables-save -c`, etc.

What do these commands show:

- `iptables-save -c | grep DROP`
- `iptables-save -c | grep 10.96.0.1`

**Comment by dareth-koh** [comment]
i dont find anything amiss in the iptables

 iptables-save -c | grep ACCEPT
:INPUT ACCEPT [0:0]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [0:0]
[0:0] -A FORWARD -o docker0 -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
[0:0] -A FORWARD -i docker0 ! -o docker0 -j ACCEPT
[0:0] -A FORWARD -i docker0 -o docker0 -j ACCEPT
[2:169] -A FORWARD -m comment --comment "cali:S93hcgKJrXEqnTfs" -m comment --comment "Policy explicitly accepted packet." -m mark --mark 0x10000/0x10000 -j ACCEPT
[0:0] -A LIBVIRT_INP -i virbr0 -p udp -m udp --dport 53 -j ACCEPT
[0:0] -A LIBVIRT_INP -i virbr0 -p tcp -m tcp --dport 53 -j ACCEPT
[0:0] -A LIBVIRT_INP -i virbr0 -p udp -m udp --dport 67 -j ACCEPT
[0:0] -A LIBVIRT_INP -i virbr0 -p tcp -m tcp --dport 67 -j ACCEPT
[0:0] -A LIBVIRT_OUT -o virbr0 -p udp -m udp --dport 53 -j ACCEPT
[0:0] -A LIBVIRT_OUT -o virbr0 -p tcp -m tcp --dport 53 -j ACCEPT
[0:0] -A LIBVIRT_OUT -o virbr0 -p udp -m udp --dport 68 -j ACCEPT
[0:0] -A LIBVIRT_OUT -o virbr0 -p tcp -m tcp --dport 68 -j ACCEPT
[0:0] -A LIBVIRT_FWO -s 192.168.122.0/24 -i virbr0 -j ACCEPT
[0:0] -A LIBVIRT_FWI -d 192.168.122.0/24 -o virbr0 -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
[0:0] -A LIBVIRT_FWX -i virbr0 -o virbr0 -j ACCEPT
[0:0] -A KUBE-FORWARD -m comment --comment "kubernetes forwarding rules" -m mark --mark 0x4000/0x4000 -j ACCEPT
[0:0] -A KUBE-FORWARD -m comment --comment "kubernetes forwarding conntrack rule" -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
[0:0] -A cali-INPUT -p ipv4 -m comment --comment "cali:PajejrV4aFdkZojI" -m comment --comment "Allow IPIP packets from Calico hosts" -m set --match-set cali40all-hosts-net src -m addrtype --dst-type LOCAL -j ACCEPT
[0:0] -A cali-INPUT -m comment --comment "cali:6McIeIDvPdL6PE1T" -m mark --mark 0x10000/0x10000 -j ACCEPT
[0:0] -A cali-INPUT -m comment --comment "cali:q-Vz2ZT9iGE331LL" -m comment --comment "Host endpoint policy accepted packet." -m mark --mark 0x10000/0x10000 -j ACCEPT
[3:180] -A cali-wl-to-host -m comment --comment "cali:nSZbcOoG1xPONxb8" -m comment --comment "Configured DefaultEndpointToHostAction" -j ACCEPT
[0:0] -A cali-OUTPUT -m comment --comment "cali:Mq1_rAdXXH3YkrzW" -m mark --mark 0x10000/0x10000 -j ACCEPT
[0:0] -A cali-OUTPUT -p ipv4 -m comment --comment "cali:AnEsmO6bDZbQntWW" -m comment --comment "Allow IPIP packets to other Calico hosts" -m set --match-set cali40all-hosts-net dst -m addrtype --src-type LOCAL -j ACCEPT
[0:0] -A cali-OUTPUT -m comment --comment "cali:OgU2f8BVEAZ_fwkq" -m comment --comment "Host endpoint policy accepted packet." -m mark --mark 0x10000/0x10000 -j ACCEPT
[1:160] -A cali-tw-cali3a55abf4daa -m comment --comment "cali:fixPap2tBT5VtrAp" -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
[2640:212962] -A cali-fw-cali3a55abf4daa -m comment --comment "cali:9ga_z8plqB3dB251" -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
[2661:214322] -A cali-fw-cali24a739b15d8 -m comment --comment "cali:90RfLjoNw4hgashw" -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
[1:159] -A cali-tw-cali24a739b15d8 -m comment --comment "cali:D-D823K_e3L7kifU" -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
:PREROUTING ACCEPT [0:0]
:INPUT ACCEPT [0:0]
:POSTROUTING ACCEPT [0:0]
:OUTPUT ACCEPT [0:0]
:PREROUTING ACCEPT [0:0]
:INPUT ACCEPT [0:0]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [0:0]
:POSTROUTING ACCEPT [0:0]
[527018:337455035] -A cali-PREROUTING -m comment --comment "cali:6BJqBjBC7crtA-7-" -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
[0:0] -A cali-PREROUTING -m comment --comment "cali:KX7AGNd6rMcDUai6" -m mark --mark 0x10000/0x10000 -j ACCEPT
[0:0] -A cali-PREROUTING -m comment --comment "cali:Cg96MgVuoPm7UMRo" -m comment --comment "Host endpoint policy accepted packet." -m mark --mark 0x10000/0x10000 -j ACCEPT
:PREROUTING ACCEPT [0:0]
:OUTPUT ACCEPT [0:0]
[0:0] -A cali-PREROUTING -m comment --comment "cali:lV4V2MPoMBf0hl9T" -m mark --mark 0x10000/0x10000 -j ACCEPT
[0:0] -A cali-OUTPUT -m comment --comment "cali:pN0F5zD0b8yf9W1Z" -m mark --mark 0x10000/0x10000 -j ACCEPT


# ip r
default via 192.168.152.2 dev ens34 proto dhcp src 192.168.152.230 metric 101
10.0.1.0/24 dev ens33 proto kernel scope link src 10.0.1.2 metric 100
172.17.0.0/16 dev docker0 proto kernel scope link src 172.17.0.1 linkdown
blackhole 192.168.73.128/26 proto bird
192.168.73.130 dev cali3a55abf4daa scope link
192.168.73.131 dev cali24a739b15d8 scope link
192.168.122.0/24 dev virbr0 proto kernel scope link src 192.168.122.1 linkdown
192.168.152.0/24 dev ens34 proto kernel scope link src 192.168.152.230 metric 101

could it be some associations with virbr0?

**Comment by caseydavenport** [comment]
@dareth-koh what IP range are you using for your node IP addresses? And what CIDR have you allocated for your pod IPs?

Double check that your node CIDR, your pod CIDR, and your Service CIDR do not overlap at all - that will cause routing issues.

**Comment by dareth-koh** [comment]
Hi @caseydavenport ,  i heard of such issues occurred when setup the cni. Hence, my interface ip is 10. 0.1.x (no gateway and just internal connectivity with /24 subnet), api server is 10.0.1.2 and cluster CIDR is 192.168.0.0. 

I'm wits end as i had it running previously with the exact same ip configuration except newer kubernetes version and calico. 
This is so strange. :(

**Comment by caseydavenport** [comment]
> default via 192.168.152.2 dev ens34 proto dhcp src 192.168.152.230 metric 101

I asked because this route seems to suggest your node's default routing is configured to use a gateway in the 192.168.0.0/16 CIDR.

```
192.168.122.0/24 dev virbr0 proto kernel scope link src 192.168.122.1 linkdown
192.168.152.0/24 dev ens34 proto kernel scope link src 192.168.152.230 metric 101
```

These routes are also overlapping with Calico's routes, but as far as I can tell aren't programmed by Calico itself. So I suspect there is a conflict going on.
