### ISSUE TITLE
Calico Node ipv4 cache of "dead" node.

### ISSUE THREAD

**Issue by brunomiguel-teixeira** [projectcalico/calico#8346]
When using Calico only as Network Policy provider (unsure if other configurations have same problem), we are hitting ipv4 conflicts in cache due to Cluster scaling up/down.

What happens is that when a k8s clusters scales up, sometimes the node receives an ipv4 from a **freshly** previous deleted node. This means that calico agent enters a crashloop backoff state with the following message: `"Calico node 'aks-xxxxxx01' is already using the IPv4 address 10.140.x.xx."` 

## Expected Behavior
* When K8s Node is deleted (or rebuilt), Calico should free the ipv4 lease.
* Or when in conflict, if it detects the lease belongs to a node about to pruned, free the lease.

## Current Behavior
* ipv4 leases get attached/cached in to be deleted k8s node resources (the instance/vm no longer exists)

## Possible Solution
* When in conflict, if it detects the lease belongs to a node about to pruned, free the lease.

## Steps to Reproduce (for bugs)
1. Downscale AKS.
2. (Within next few minutes) scale up AKS. Most time the nodes will reuse previous ipv4 address.
3. Calico in the new AKS Node will remain in crashloop state with previous error message since the ipv4 is "still allocated" to an already new VM with different k8s node resource.

## Your Environment
* Managed Kubernetes (AKS). Still occurs in releases up to 1.27
* Azure managed Calico as Network Policy Provider
* Calico Node v3.24.6

P.S: I am unsure if this is a "Calico" issue, or a more general problem from the autoscaler and its reconciliation with Cloud Nodes since the while the VM itself is deleted, the Kubernetes Node resources takes ~10 minutes to be pruned.

**Comment by caseydavenport** [comment]
@brunomiguel-teixeira have you run `kubectl delete node` to delete the old nodes from the Kubernetes API?

**Comment by caseydavenport** [comment]
>  the Kubernetes Node resources takes ~10 minutes to be pruned.

Ah, I see that the node is still around. That is likely the problem here, as Calico can only know what the API server tells it.
