### ISSUE TITLE
Calico IP mode startup health check error, but checking the routing, port 179 status, and node communication are all normal. How can I solve this problem

### ISSUE THREAD

**Issue by smallemployees** [projectcalico/calico#8373]
## Expected Behavior

I want to know how to troubleshoot

## Current Behavior

Why did the health check of a node suddenly report an error

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Calico version  v3.4.9
* Orchestrator version (e.g. kubernetes, mesos, rkt):
* Operating System and version:
* Link to your project (optional):

**Comment by caseydavenport** [comment]
Please fill out the issue template when raising issues. As it is, there is not enough information to help you here.

I will say - Calico v3.4.9 is very very old and no longer supported. Before you raise any other issues, make sure you are on a modern version of Calico. v3.27.0 was just released.
