### ISSUE TITLE
calico-node logs spammed with "bird: KIF: Ignore kube-ipvs0 that is not UP"

### ISSUE THREAD

**Issue by lbogdan** [projectcalico/calico#8378]
## Expected Behavior

`calico-node` pods logs are not spammed with useless messages.

## Current Behavior

`calico-node` pods logs are spammed with **a lot** (~40 lines every 2 seconds) of "bird: KIF: Ignore kube-ipvs0 that is not UP":

```
$ date && kubectl -n kube-system logs -c calico-node --tail 20 --timestamps calico-n
ode-6vjmw
Tue Dec 26 07:55:13 PM UTC 2023
2023-12-26T19:55:12.277185490Z bird: KIF: Ignore kube-ipvs0 that is not UP
2023-12-26T19:55:12.277185490Z bird: KIF: Ignore kube-ipvs0 that is not UP
2023-12-26T19:55:12.277185490Z bird: KIF: Ignore kube-ipvs0 that is not UP
2023-12-26T19:55:12.277185490Z bird: KIF: Ignore kube-ipvs0 that is not UP
2023-12-26T19:55:12.277185490Z bird: KIF: Ignore kube-ipvs0 that is not UP
2023-12-26T19:55:12.277185490Z bird: KIF: Ignore kube-ipvs0 that is not UP
2023-12-26T19:55:12.277185490Z bird: KIF: Ignore kube-ipvs0 that is not UP
2023-12-26T19:55:12.277185490Z bird: KIF: Ignore kube-ipvs0 that is not UP
2023-12-26T19:55:12.277210778Z bird: KIF: Ignore kube-ipvs0 that is not UP
2023-12-26T19:55:12.277210778Z bird: KIF: Ignore kube-ipvs0 that is not UP
2023-12-26T19:55:12.277210778Z bird: KIF: Ignore kube-ipvs0 that is not UP
2023-12-26T19:55:12.277210778Z bird: KIF: Ignore kube-ipvs0 that is not UP
2023-12-26T19:55:12.277210778Z bird: KIF: Ignore kube-ipvs0 that is not UP
2023-12-26T19:55:12.277210778Z bird: KIF: Ignore kube-ipvs0 that is not UP
2023-12-26T19:55:12.277210778Z bird: KIF: Ignore kube-ipvs0 that is not UP
2023-12-26T19:55:12.277210778Z bird: KIF: Ignore kube-ipvs0 that is not UP
2023-12-26T19:55:12.277210778Z bird: KIF: Ignore kube-ipvs0 that is not UP
2023-12-26T19:55:12.277210778Z bird: KIF: Ignore kube-ipvs0 that is not UP
2023-12-26T19:55:12.277210778Z bird: KIF: Ignore kube-ipvs0 that is not UP
2023-12-26T19:55:12.277210778Z bird: KIF: Ignore kube-ipvs0 that is not UP
```

## Steps to Reproduce (for bugs)

1. Install `calico` into a `1.28.5` Kubernetes cluster using the manifest:

```
curl https://raw.githubusercontent.com/projectcalico/calico/v3.27.0/manifests/calico.yaml -O
```

Note that `kube-proxy` is configured into [`ipvs` mode](https://kubernetes.io/docs/reference/networking/virtual-ips/#proxy-mode-ipvs), and is the component that creates the `kube-ipvs0` interface in the first place, interface which is supposed to be down, as per [this comment](https://github.com/kubernetes/kubernetes/issues/107662#issuecomment-1017894646):

> kube-ipvs0 should be down and noarp.

2. Look at any of the `calico-node` pods logs.

## Context

Massively spamming logs with useless messages is bad for obvious reasons.

## Your Environment

* Calico version: `3.27.0` (`docker.io/calico/node:v3.27.0` image)
* Orchestrator version (e.g. kubernetes, mesos, rkt): kubernetes `1.28.5`
* Operating System and version: Ubuntu `22.04.3` LTS, kernel version `6.2.0-39-generic`
* Link to your project (optional): N/A

Looking at the `bird` configuration file `/etc/calico/confd/config/bird.cfg` inside a `calico-node` pod, it looks like the `kube-ipvs0` interface should be ignored, specifically mentioning `kube-proxy` in `ipvs` mode

```
# cat /etc/calico/confd/config/bird.cfg
[...]
protocol direct {
  debug { states };
  interface -"cali*", -"kube-ipvs*", "*"; # Exclude cali* and kube-ipvs* but
                                          # include everything else.  In
                                          # IPVS-mode, kube-proxy creates a
                                          # kube-ipvs0 interface. We exclude
                                          # kube-ipvs0 because this interface
                                          # gets an address for every in use
                                          # cluster IP. We use static routes
                                          # for when we legitimately want to
                                          # export cluster IPs.
}
[...]
```

so it's quite weird that `bird` still complains about that interface.

**Comment by ivanovpavel1983** [comment]
same problem...

**Comment by Atomique** [comment]
Upgraded to v3.27 today with these steps from the docs having the same issue: https://docs.tigera.io/calico/latest/operations/upgrading/kubernetes-upgrade#upgrading-an-installation-that-uses-the-operator

**Comment by lbogdan** [comment]
I can take a look at this, @caseydavenport can you please point me to the exact source code `bird` is compiled from? I see there's a `bird` mirror at https://github.com/projectcalico/bird/, and judging by the version in the `calico-node:v3.27.0` image (`BIRD version v0.3.3+birdv1.6.8`), I would guess it's https://github.com/projectcalico/bird/tree/v0.3.3 ? Although that branch looks 5 years old, so I'm not sure.

**Comment by caseydavenport** [comment]
@lbogdan thanks!

The BIRD_IMAGE is overridden by the build process using the version taken from `metadata.mk` here: https://github.com/projectcalico/calico/blob/master/metadata.mk#L28-L29

I think we stopped cutting formal releases of our BIRD fork and instead pin to commit builds instead.

**Comment by lbogdan** [comment]
Thanks a lot!

Found the commit that introduced this: https://github.com/projectcalico/bird/commit/3d15998f2410ff7043dbaa96879e2d9a11b1c3dc .

**Comment by lbogdan** [comment]
@caseydavenport Any reason `bird` is ran with `-d` (debug) here https://github.com/projectcalico/calico/blob/a684f90bec0bc99ccade9424d2312ac641ffd3dd/node/filesystem/etc/service/available/bird/run#L3 ?

**Comment by lbogdan** [comment]
Ok, so I managed to hack around it by replacing that `-d` with `-f` (`runit` expects `bird` to run in the foreground) in `/etc/service/available/bird/run` in the `calico-node` image.

Just FYI, I also published a "fixed" image at `docker.io/lbogdan:calico-node:3.27.0-0` built from the following `Dockerfile`:

```dockerfile
FROM calico/node:v3.27.0

RUN sed -i s/-d/-f/ /etc/service/available/bird/run
```

> [!CAUTION]
> People annoyed by this that want to fix it until a new Calico release should probably **NOT** use this image (especially in production), but build their own.

**Comment by lbogdan** [comment]
@caseydavenport Would the above be a suitable approach? If so, I could open a PR.

**Comment by caseydavenport** [comment]
@lbogdan great sleuthing! Agree with your assesment. From what I can tell, the other instances of ignored interfaces do so silent without any DEBUG level logging, so we probably just want to remove the log line from the BIRD code itself and keep the `-d` flag - WDYT?

**Comment by lbogdan** [comment]
It would be nice if `bird`'s log level was configurable, but I guess that'd be a bit more involved.

Which branch should one use to create a `projectcalico/bird` PR? I see the default branch there is `feature-ipinip`.

**Comment by caseydavenport** [comment]
> It would be nice if bird's log level was configurable (and set to INFO by default), but I guess that'd be a bit more involved.

Yeah I agree. If that's something you'd be interested in taking on I'm all for it, though I'd be happy with simply removing the log for now since as you say it's more involved.

`feature-ipinip` is the correct branch :+1:

**Comment by lbogdan** [comment]
@caseydavenport This should be reopened until `bird` version is updated in `calico/metadata.mk`.

**Comment by nelljerram** [comment]
@lbogdan Thanks for the work you're already doing on this!  Regarding the question of the BIRD logging level being configurable...  I could be wrong, or the existing implementation might not be working as intended, but I believe that the BIRD logging level already should be configurable.  My understanding is that it works as follows.

1. The `-d` option, when we run BIRD, only enables the possibility of debug-level messages.  It doesn't necessarily mean that debug-level messages *will* be emitted.

2. There's a `logSeverityScreen` field in the [BGPConfiguration resource](https://docs.tigera.io/calico/latest/reference/resources/bgpconfig) which controls both the logging from confd (our component that generates and maintains the BIRD config) and the logging from BIRD itself.  When `logSeverityScreen` is `debug`, the BIRD config includes `debug all;`.  When `logSeverityScreen` is `info`, the BIRD config includes `debug { states };`.  For other `logSeverityScreen` values there is no `debug ...` directive in the BIRD config.

If my reasoning is correct, it implies that you must have had `logSeverityScreen: Debug` in order to see those kube-ipvs0 messages.  Was that the case?

**Comment by lbogdan** [comment]
> Was that the case?

@nelljerram No, from my experimentation, the existence (or not) of the `debug` statements in the `bird` configuration file didn't have any effect in regard to this specific debug message. I get the log messages from a default `calico` install from `https://raw.githubusercontent.com/projectcalico/calico/v3.27.0/manifests/calico.yaml`.

Looking at the code, it indeed looks like it's not influenced by any configuration settings.

**Comment by nelljerram** [comment]
Interesting, thanks.  It seems we have misunderstood what our existing mechanism does.  I don't think it's a high priority, given that you've already fixed the most important spam case, but if you feel like digging into this further that would be welcome.

**Comment by lbogdan** [comment]
From [`bird`'s documentation](https://bird.network.cz/?get_doc&v=20&f=bird-3.html#ss3.1), it looks like the `log` statement can be used to control this, from the configuration file:

> **log "filename" [limit "backup"] | syslog [name name] | stderr all|{ list of classes }**
>
>Set logging of messages having the given class (either all or { error|trace [, ...] } etc.) into selected destination - a file specified as a filename string (with optional log rotation information), syslog (with optional name argument), or the stderr output.
>
>Classes are: info, warning, error and fatal for messages about local problems, debug for debugging messages, trace when you want to know what happens in the network, remote for messages about misbehavior of remote machines, auth about authentication failures, bug for internal BIRD bugs.
>
>Logging directly to file supports basic log rotation -- there is an optional log file limit and a backup filename, when log file reaches the limit, the current log file is renamed to the backup filename and a new log file is created.
>
>You may specify more than one log line to establish logging to multiple destinations. Default: log everything to the system log, or to the debug output if debugging is enabled by -d/-D command-line option.
