### ISSUE TITLE
In the case of Calico and Keepalived using the same network card, there may be occasional loss of IPv6 routing when Keepalived switches to VIP

### ISSUE THREAD

**Issue by smallemployees** [projectcalico/calico#8398]
## Expected Behavior

I want to know why there is a situation of IPv6 routing loss
## Current Behavior

IPv6 routing loss
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Calico version  v3.15.5
* Orchestrator version (e.g. kubernetes, mesos, rkt):
* Operating System and version:
* Link to your project (optional):

**Comment by caseydavenport** [comment]
> Calico version v3.15.5

This is a very old version of Calico that's no longer in support - please reproduce on a more modern version. v3.27.0 is the latest at the moment.

Also, for future issues please fill out the issue template - we're not able to assist without all of the necessary context.
