### ISSUE TITLE
[ERROR][9] startup/startup.go 193: Unable to set node resource configuration error=update conflict: Node(k8s02)

### ISSUE THREAD

**Issue by jibingjie2** [projectcalico/calico#8408]
My server shut down abnormally due to high load and entered emergency mode after I started up. I executed the following command
xfs_ Repair - v - L/dev/dm-0
reboot
After starting up normally, the calico node encountered this error message

###  calico-node log:
W0114 03:48:00.336299       9 feature_gate.go:241] Setting GA feature gate ServiceInternalTrafficPolicy=true. It will be removed in a future release.
2024-01-14 03:48:00.429 [ERROR][9] startup/startup.go 193: Unable to set node resource configuration error=update conflict: Node(k8s02)
Calico node failed to start
### calico-kube-controllers log
[calico-kube-controllers.log](https://github.com/projectcalico/calico/files/13930248/calico-kube-controllers.log)

**Comment by caseydavenport** [comment]
> startup/startup.go 193: Unable to set node resource configuration error=update conflict: Node(k8s02)

Your node is trying to talk to the Kubernetes API server and hitting a conflict with another API user. Does this happen consistently or does it resolve itself after a couple of tries?

**Comment by jibingjie2** [comment]
> > startup/startup.go 193: Unable to set node resource configuration error=update conflict: Node(k8s02)
> 
> Your node is trying to talk to the Kubernetes API server and hitting a conflict with another API user. Does this happen consistently or does it resolve itself after a couple of tries?

It is a continuous occurrence, and during the troubleshooting process, it was found that a node in the ETCD cluster crashed, causing data inconsistency. When the ETCD cluster was restored, this issue was also resolved
