### ISSUE TITLE
eBPF mode fails to enable on Raspberry Pi 5

### ISSUE THREAD

**Issue by sholdee** [projectcalico/calico#8428]
## Expected Behavior
eBPF mode loads on Raspberry Pi 5 with supported kernel.

## Current Behavior
BPF and Cgroup2 filesystems are mounted, but eBPF mode fails to enable and Calico falls back to iptables dataplane:

```
ethan@k3s-master-0:~ $ sudo kubectl logs calico-node-cdlws -n calico-system | grep ERROR
Defaulted container "calico-node" out of: calico-node, flexvol-driver (init), mount-bpffs (init), install-cni (init)
2024-01-20 03:42:47.036 [ERROR][51] felix/daemon.go 376: BPF dataplane mode enabled but not supported by the kernel.  Disabling BPF mode.

ethan@k3s-master-0:~ $ sudo kubectl logs calico-node-cdlws -n calico-system -c mount-bpffs
2024-01-20 03:42:42.300 [INFO][1] init/startup.go 445: Early log level set to info
2024-01-20 03:42:42.300 [INFO][1] init/calico-init_linux.go 57: Checking if BPF filesystem is mounted.
2024-01-20 03:42:42.300 [INFO][1] init/calico-init_linux.go 69: BPF filesystem is mounted.
2024-01-20 03:42:42.300 [INFO][1] init/calico-init_linux.go 92: Checking if cgroup2 filesystem is mounted.
2024-01-20 03:42:42.301 [INFO][1] init/calico-init_linux.go 110: Cgroup2 filesystem is mounted.

ethan@k3s-master-0:~ $ cat /proc/version
Linux version 6.1.0-rpi7-rpi-2712 (debian-kernel@lists.debian.org) (gcc-12 (Debian 12.2.0-14) 12.2.0, GNU ld (GNU Binutils for Debian) 2.40) #1 SMP PREEMPT Debian 1:6.1.63-1+rpt1 (2023-11-24)

[root@k3s-master-0 /]# calico-node -v
v3.27.0
```

## Steps to Reproduce (for bugs)
1. Enable eBPF dataplane on Raspberry Pi 5 (possibly other versions as well?)

## Context
Calico has been working great for me on Pi 5, except for eBPF mode. I tested cilium in the same environment and eBPF loads as expected.

## Your Environment
* Calico version: v3.27.0
* Orchestrator version (e.g. kubernetes, mesos, rkt):  v1.28.5+k3s1
* Operating System and version: Raspberry Pi OS Lite 64-bit, Debian Bookworm

**Comment by tomastigera** [comment]
@sholdee could you try this image? It is based on current master and should contain some extra logging `thruby/calico-node:master-arm64`

**Comment by sholdee** [comment]
> @sholdee could you try this image? It is based on current master and should contain some extra logging `thruby/calico-node:master-arm64`

`2024-01-31 06:01:10.515 [ERROR][64] felix/daemon.go 376: BPF dataplane mode enabled but not supported by the kernel.  Disabling BPF mode. error=BPF syscall support is not available on this platform`
[calico-node-debug-jan31](https://gist.github.com/sholdee/7ba2be111530c463bd61b49bccc01585)

```bash
root@k3s-test:~# grep BPF /boot/config-$(uname -r)
CONFIG_BPF=y
CONFIG_HAVE_EBPF_JIT=y
CONFIG_ARCH_WANT_DEFAULT_BPF_JIT=y
# BPF subsystem
CONFIG_BPF_SYSCALL=y
CONFIG_BPF_JIT=y
# CONFIG_BPF_JIT_ALWAYS_ON is not set
CONFIG_BPF_JIT_DEFAULT_ON=y
CONFIG_BPF_UNPRIV_DEFAULT_OFF=y
# CONFIG_BPF_PRELOAD is not set
# CONFIG_BPF_LSM is not set
# end of BPF subsystem
CONFIG_CGROUP_BPF=y
CONFIG_NETFILTER_XT_MATCH_BPF=m
# CONFIG_BPFILTER is not set
CONFIG_NET_CLS_BPF=y
# CONFIG_NET_ACT_BPF is not set
# CONFIG_BPF_STREAM_PARSER is not set
CONFIG_LWTUNNEL_BPF=y
CONFIG_BPF_LIRC_MODE2=y
CONFIG_BPF_EVENTS=y
# CONFIG_TEST_BPF is not set
```
```bash
root@k3s-test:~# cat /proc/kallsyms | grep bpf > kallsyms-bpf
```
[kallsyms-bpf](https://gist.github.com/sholdee/53aa9a358c423bf6e39e09efba09e6fe)

**Comment by tomastigera** [comment]
@sholdee I believe it is a bug/regression in the build system and an issue on your side.

**Comment by tomastigera** [comment]
@sholdee could you try this `thruby/calico-node:master-arm64-fix` which is build with the fixed build system to verify that it is all we need to fix your issue? :pray: :crossed_fingers:

**Comment by sholdee** [comment]
> @sholdee could you try this `thruby/calico-node:master-arm64-fix` which is build with the fixed build system to verify that it is all we need to fix your issue? 🙏 🤞

Seems good with new image: [calico-node-bpf-debug-logs.log](https://gist.github.com/sholdee/bff92932ed7948980c9ca2dd1d9ce2a3)

`calico-node -bpf` dump commands are giving me outputs now.

Thank you!
