### ISSUE TITLE
KubeControllersConfiguration example uses unknown field 'spec.etcdv3CompactionPeriod'

### ISSUE THREAD

**Issue by sebhoss** [projectcalico/calico#8432]
## Expected Behavior

I tried applying the example configuration from https://docs.tigera.io/calico/latest/reference/resources/kubecontrollersconfig to a cluster running with Calico 3.27 and calico-apiserver 3.27. My expectation was that it would apply without warnings/errors.

## Current Behavior

The response was `Warning: unknown field "spec.etcdv3CompactionPeriod"`

## Possible Solution

I'm guessing that the documentation must be updated to remove the field or the apiserver must be updated to allow setting this field.

## Steps to Reproduce (for bugs)

1. Deploy Calico
2. Apply sample config from https://docs.tigera.io/calico/latest/reference/resources/kubecontrollersconfig
3. See warning in kubectl output

## Context

I'm trying to manage all aspects of calico in a declarative way and would like to avoid any warnings/errors.

## Your Environment

* Calico version: 3.27
* Orchestrator version (e.g. kubernetes, mesos, rkt): kubernetes
* Operating System and version: Ubuntu 20.04
* Link to your project (optional): Company on-premise cluster

**Comment by caseydavenport** [comment]
Yep, this looks like a documentation bug - think that field just needs to be removed.

**Comment by sebhoss** [comment]
Ok thanks - created https://github.com/tigera/docs/pull/1266 for that
