### ISSUE TITLE
TCP massive retransmission between tunnel interface to kubernetes pod ip

### ISSUE THREAD

**Issue by ray1888** [projectcalico/calico#8448]
there is a lot of tcp retranmission between calico tunnel interface to kubernetes service pod 

## Expected Behavior
there is no retransmission  between calico tunnel interface to kubernetes service pod 

## Current Behavior
![image](https://github.com/projectcalico/calico/assets/19427008/80a998c0-3824-4e85-822c-194ebd03d080)

tcp dump file as below 
[service.zip](https://github.com/projectcalico/calico/files/14049417/service.zip)

## Possible Solution
not solution 

## Steps to Reproduce (for bugs)

1.  install apisix 
2.   config upstream service 
3.  user login to reverse proxy, then tcp dump to the service pod ip 
     ``` 
        tcpdump -i any host ￥service_pod_ip and port $service_pod_port -A
     ```

## Context

background: we trying to test api gateway on our premise kubernetes cluster, but higress has said that our base inter connection has problem, so we need to solve this problem first. (related issue: https://github.com/alibaba/higress/issues/795)

## Your Environment

* Calico version- v3.14.1
* Orchestrator version (e.g. kubernetes, mesos, rkt): kuberntes v1.23.17
* Operating System and version: CentOS Linux  7 (kernel: 5.4.245-1.el7.elrepo.x86_64)
* Link to your project (optional):

**Comment by caseydavenport** [comment]
> Calico version- v3.14.1

Please upgrade to a modern Calico version - v3.14 is very old and is no longer supported. If you can reproduce this on v3.27 or similar, please let me know and I will re-open this issue.
