### ISSUE TITLE
Block IMDS traffic access not working as expected

### ISSUE THREAD

**Issue by esierra-stratio** [projectcalico/calico#8479]
The provided kubernetes `NetworkPolicy` and calico `GlobalNetworkPolicy` manifests aim to block traffic to the Instance Metadata Service (IMDS) on ports 80 and 443. However, there seems to be an issue where traffic to port 80 is not being blocked as expected.

```bash
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-all-egress
  namespace: kube-system
spec:
  egress:
  - {}
  podSelector: {}
  policyTypes:
  - Egress
```

```bash
---
apiVersion: crd.projectcalico.org/v1
kind: GlobalNetworkPolicy
metadata:
  name: deny-all-traffic-to-imds
spec:
  types:
    - Egress
  egress:
    - action: Log
      metadata: {}
      protocol: TCP
      destination:
        ports:
          - 80
          - 443
        nets:
          - 169.254.169.254/32
    - action: Deny
      metadata: {}
      protocol: TCP
      destination:
        ports:
          - 80
          - 443
        nets:
          - 169.254.169.254/32
  selector: all()
```

The security policies in place seem to be partially effective, as access to IMDS on port 443 is blocked, but there is an issue with the request on port 80 resulting in a 400 Bad Request error as shown below:

```bash
$ kubectl exec -it curl-pod -n kube-system -- curl http://169.254.169.254:80 -i
HTTP/1.1 400 Bad Request
Content-Type: application/json; charset=utf-8
Date: Fri, 02 Feb 2024 09:52:21 GMT
Content-Length: 89

{"error":"invalid_request","error_description":"Required metadata header not specified"}
```
```bash
kubectl exec -it curl-pod -n kube-system -- curl https://169.254.169.254:443 -i
curl: (28) Failed to connect to 169.254.169.254 port 443 after 129490 ms: Couldn't connect to server
command terminated with exit code 28
```

## Expected Behavior
Restrict access to IMDS on both ports.

## Current Behavior
Restricting IMDS traffic access exclusively to port 443

## Possible Solution
N/A

## Steps to Reproduce (for bugs)
1. Kubernetes cluster in Azure version v1.28.0
2. Install helm chart tigera-operator v3.26.1
3. Apply the provided manifests above

## Context
Attempting to restrict IMDS traffic access to mitigate security risks

## Your Environment
* Calico version 3.26.1
* Orchestrator version (e.g. kubernetes, mesos, rkt): kubernetes 1.28.0

**Comment by coutinhop** [comment]
Hi @esierra-stratio, this is you on slack, isn't it? https://calicousers.slack.com/archives/CPEPQE8CS/p1707219329533299

For the record, both policies do not have an `order` field and are thus both using the default value (infinity, meaning they'd come last after any other plain k8s network policy you might have, for example). As they're tied in ordering, the tie-breaker would be alphabetic ordering based on policy name, meaning the "allow" policy would be applied before the "deny".

In the thread, the solution was to to block destination `127.0.0.1:2579` because of Azure DNAT behavior:
```
- apiVersion: crd.projectcalico.org/v1
  kind: GlobalNetworkPolicy
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"crd.projectcalico.org/v1","kind":"GlobalNetworkPolicy","metadata":{"annotations":{},"name":"deny-all-traffic-to-localhost"},"spec":{"egress":[{"action":"Deny","destination":{"nets":["127.0.0.1/32"],"ports":[2579]},"protocol":"TCP"}],"order":0,"selector":"all()","types":["Egress"]}}
    creationTimestamp: "2024-02-06T15:40:55Z"
    generation: 1
    name: deny-all-traffic-to-localhost
    resourceVersion: "124250"
    uid: d03ceb7d-4355-4b09-824b-a049398ba55d
  spec:
    egress:
    - action: Deny
      destination:
        nets:
        - 127.0.0.1/32
        ports:
        - 2579
      protocol: TCP
    order: 0
    selector: all()
    types:
    - Egress
```
