### ISSUE TITLE
Uninstallation Failure: Calico Module Leaves Remaining Jobs Blocking Deletion

### ISSUE THREAD

**Issue by rohan-vivek** [projectcalico/calico#8490]
## Expected Behavior
The expected behavior is that the Calico module should uninstall successfully without encountering any errors or interference from leftover jobs.

## Current Behavior
During the uninstallation process of the Calico module using Terraform, a job named `tigera-operator-uninstall` is created, which prevents the module from being deleted successfully. This job interferes with the uninstallation process and causes it to fail with the error message:
```
Error: warning: Hook pre-delete tigera-operator/templates/tigera-operator/00-uninstall.yaml failed: 1 error occurred:
	* jobs.batch "tigera-operator-uninstall" already exists
```

## Possible Solution
Manually deleting the tigera-operator-uninstall job via the CLI in parallel with the destruction process resolves the issue. However, a more automated solution within the Terraform module itself would be ideal.

## Steps to Reproduce (for bugs)

1. Install the Calico module using Terraform.
2. Attempt to uninstall the Calico module using Terraform.
3. Observe the creation of the tigera-operator-uninstall job.
4. Note the error message indicating the job already exists, preventing uninstallation.

## Context
This issue is affecting users trying to manage their Kubernetes clusters using Terraform and Calico. It prevents the successful uninstallation of the Calico module, causing frustration and hindering the management of their infrastructure.

## Your Environment

* Calico version: v3.27.0
* Orchestrator version: Kubernetes 1.29
* Operating System and version: Ubuntu 22.04.3 LTS (GitHub Runner)
* Link to your project (optional):

**Comment by coutinhop** [comment]
@caseydavenport I think you're familiar with this, could you take a look?

**Comment by caseydavenport** [comment]
I would have expected a successful uninstall to remove the Job afterwards, so perhaps the original `helm uninstall` is failing in some way.

**Comment by pawcykca** [comment]
I noticed below error that could be a root cause why this job fails:
```
2024/02/29 12:13:48 [INFO] Version: v1.32.5
2024/02/29 12:13:48 [INFO] Go Version: go1.21.6 X:boringcrypto
2024/02/29 12:13:48 [INFO] Go OS/Arch: linux/amd64
2024/02/29 12:13:48 [INFO] preDelete hook exiting
2024/02/29 12:13:48 [ERROR] installations.operator.tigera.io "default" is forbidden: User "system:serviceaccount:kube-system:tigera-operator" cannot delete resource "installations" in API group "operator.tigera.io" at the cluster scopeFailed to complete pre-delete hook
Stream closed EOF for kube-system/tigera-operator-uninstall-29xqh (cleanup-job)
```

**Comment by caseydavenport** [comment]
Yeah, that seems likely to be the root cause. I believe there was a PR to fix this but it hasn't been released yet: https://github.com/projectcalico/calico/pull/8413
