### ISSUE TITLE
Chain INPUT default policy: DROP

### ISSUE THREAD

**Issue by fayvori** [projectcalico/calico#8492]
Hi there ! Is there a way to set default chain INPUT policy to DROP ?

## Expected Behavior

```
# root@kind-control-plane:/# iptables -nL | head
Chain INPUT (policy DROP)
target     prot opt source               destination
KUBE-PROXY-FIREWALL  all  --  0.0.0.0/0            0.0.0.0/0            ctstate NEW /* kubernetes load balancer firewall */
KUBE-NODEPORTS  all  --  0.0.0.0/0            0.0.0.0/0            /* kubernetes health check service ports */
...
```

## Current Behavior

```
# root@kind-control-plane:/# iptables -nL | head
Chain INPUT (policy ACCEPT)
target     prot opt source               destination
KUBE-PROXY-FIREWALL  all  --  0.0.0.0/0            0.0.0.0/0            ctstate NEW /* kubernetes load balancer firewall */
KUBE-NODEPORTS  all  --  0.0.0.0/0            0.0.0.0/0            /* kubernetes health check service ports */
...
```

## Steps to Reproduce (for bugs)

1. Install calico or tigera-operator
2. ssh on the node and execute `iptables -nL`

## Context

We have a trigger that fires when vm default chain INPUT policy != "DROP". Right now it's solved using ansible playbooks

## Environment

* Calico version: v3.27.0
* Orchestrator version (e.g. kubernetes, mesos, rkt): kind, kubernetes:v1.26.13
* Operating System and version: Arch Linux x86_64

**Comment by fasaxc** [comment]
I don't think we have a way to set that, to close all timing windows it needs to be set before your NICs are brought up, which means it has to be outside of Calico, which only starts after k8s is already running.
