### ISSUE TITLE
CalicoPlugin imports order in networking_calico

### ISSUE THREAD

**Issue by sp3c1k** [projectcalico/calico#8494]
Hello, 

I would like to ask if there is a specific reason why `l3_db` is imported before `Ml2Plugin` in https://github.com/projectcalico/calico/blob/master/networking-calico/networking_calico/plugins/calico/plugin.py#L15-L17

We use the calico plugin in OpenStack Neutron Server as a core plugin and what we encountered with the current state of the imports is that description for security group rules was not returned in the response from the api. 
After digging through the code with debugger I got to a point where if I import `Ml2Plugin` before `l3_db` the description starts working as intended in OpenStack. 

When importing `Ml2Plugin` - `l3_db` gets imported too, from this stack:
https://github.com/openstack/neutron/blob/master/neutron/plugins/ml2/plugin.py#L149
-> https://github.com/openstack/neutron/blob/master/neutron/plugins/ml2/rpc.py#L35
-> https://github.com/openstack/neutron/blob/master/neutron/db/l3_hamode_db.py#L52
-> https://github.com/openstack/neutron/blob/master/neutron/db/l3_dvr_db.py#L47

The description in neutron is handled by [standardattrdescription_db](https://github.com/openstack/neutron/blob/master/neutron/db/standardattrdescription_db.py) and this function https://github.com/openstack/neutron/blob/master/neutron/db/standardattrdescription_db.py#L24-L25 returns all the resources that should be extended with description. 
As seen in https://github.com/openstack/neutron-lib/blob/493609c019bed6fb60a62f2c032381ce19648208/neutron_lib/db/standard_attr.py#L223-L233 the `get_standard_attr_resource_model_map` function iterates over `HasStandardAttributes.__subclasses__()`. 

When `l3_db` is imported first, during the import of standardattrdescription only the following resources gets extended by the description:
```
ports
subnets
subnetpools
networks
routers
floatingips
```
Then, when the `l3_db` would get imported in `Ml2Plugin` again, it is already imported in the runtime, so it is skipped/only referenced. 

When we switch the imports and import `Ml2Plugin` first, we get this list of resources extended by standardattrdescription:

![image-2](https://github.com/projectcalico/calico/assets/57964340/6effa9cd-a15e-4bc1-ae59-df0303467818)

Description is then correctly returned in the api response for security group rules.

If we use `core_plugin = neutron.plugins.ml2.plugin.Ml2Plugin` instead of `core_plugin = calico` in `neutron.conf` according to https://docs.tigera.io/calico/latest/networking/openstack/configuration, the description is returned correctly as well. 

## Expected Behavior

When using CalicoPlugin in OpenStack Neutron as core_plugin, security group rules should return description in api responses as it is often used by other 3rd party tools and users to get more context for the rules. 

## Current Behavior

When using CalicoPlugin in OpenStack Neutron as core_plugin, security groups rules does not return description in api responses. 

## Possible Solution

Change the order of imports in https://github.com/projectcalico/calico/blob/master/networking-calico/networking_calico/plugins/calico/plugin.py#L15-L17

## Steps to Reproduce (for bugs)

1. use `core_plugin = calico` in `neutron.conf` for OpenStack Neutron 
2. create a security group and security group rule with description
3. get/show the rule - it should be without description or `description: None`

## Your Environment

* networking_calico version:  3.26
* Openstack: Yoga release
* Operating System and version:  Ubuntu 22.04

**Comment by coutinhop** [comment]
Thanks for the detailed report @sp3c1k! I'm not sure but I believe the sole reason for the import order is alphabetical. I don't see any issues changing the import order (we should definitely add a comment explicitly stating the reason). @nelljerram, I think you're more familiar with this area, could you shed a light?
