### ISSUE TITLE
To work with Istio, need option to disable ebpf in pod network namespace 

### ISSUE THREAD

**Issue by zoftdev** [projectcalico/calico#8495]
When pod calling to service clusterip:port,EBPF modify destination to pod.ip:pod.port
So the envoy will not trigger correct rule, or discard request in some situation.

Cilium has option to disable Ebpf in pod network to make it work with Istio: https://github.com/istio/istio/issues/27619

## Expected Behavior
- Istio Envoy should see pod calling to serviceip:service.port

## Current Behavior
- Istio Envoy see that pod going to pod.ip:pod.port 

## Possible Solution
- disable ebpf

## Steps to Reproduce (for bugs)
```
        - install calico with Ebpf  , Istio
	- set Istio parameter : outboundTrafficPolicy:  REGISTRY_ONLY
	- inside injected pod: curl  svcip:svcport -H 'host: svcname.nsname.svc'
	- got return 502 / connection reset  

```
 
## Your Environment
- Istio 1.20.0  , outboundTrafficPolicy:  REGISTRY_ONLY
- calico 3.26.4 , enable ebpf dataplance
- rhel 8.9
- kernel 4.18.0

**Comment by tomastigera** [comment]
@zoftdev calico has similar options with similar functionality - disabling the socket level load balancing in pods. It was always possible to disable it and our docs mention it the section about [service mesh](https://docs.tigera.io/calico/latest/operations/ebpf/use-cases-ebpf#-building-a-service-mesh-control-plane) in eBPF.

However, 3.27 introduced some new/better options (already gated in 3.26 https://github.com/projectcalico/calico/issues/4509#issuecomment-1306318160) but proper documentation slipped :sweat: Please, see the referenced docs PR :arrow_up: for details for now.
