### ISSUE TITLE
calico breaks essential network connectivity on Windows 2022 10.0.20348.2322 and 10.0.20348.2582. 10.0.20348.1970 (aka September 2023 update) and earlier works

### ISSUE THREAD

**Issue by doctorpangloss** [projectcalico/calico#8529]
## Expected Behavior
When calico becomes active on Windows 2022 [10.0.20348.2322](https://support.microsoft.com/en-au/topic/september-12-2023-kb5030216-os-build-20348-1970-34d4aff3-fd05-4270-b288-4ab6379c7f81), the node's primary vEthernet interface (the physical network interface) becomes inaccessible due to a failure for BGP peers to connect to it.

On [10.0.20348.1970](https://support.microsoft.com/en-au/topic/september-12-2023-kb5030216-os-build-20348-1970-34d4aff3-fd05-4270-b288-4ab6379c7f81), 10.0.20348.1547, 10.0.20348.1906 and 10.0.20348.1787, it is still accessible.

The node is still accessible on its Calico network interface.

This affects pod-to-pod and physical-to-pod, physical-to-service networking catastrophically. Apparently in mesh-to-mesh with Windows nodes, the bug under 10.0.20348.2322 affects all IP blocks and services' reachability, even ones that have nothing to do with the problematic 10.0.20348.2322 node.

For people encountering a similar issue, this will uninstall the problematic update:
```
dism /online /remove-package /PackageName:Package_for_RollupFix~31bf3856ad364e35~amd64~~20348.2322.1.271 /Quiet /NoRestart
shutdown /t 0 /r
```

| Property                                      | A                     | B                     | C         | C*        |
|-----------------------------------------------|-----------------------|-----------------------|--------------------------|-------------------------|
| **Version**                                   | 10.0.20348.1970       | 10.0.20348.1726       | 10.0.20348.2322          | 10.0.20348.1726         |
| **Calico Internal IP**                        | 10.3.71.2             | 10.3.174.194          | 10.3.5.194               | 10.3.5.194              |
| **Physical IP**                               | 10.2.0.67             | 10.2.0.61             | 10.2.0.60                | 10.2.0.60               |
| **Ping Calico Internal**                      | works                 | works                 | works                    | works                   |
| **Ping Physical**                             | works                 | works                 | intermittently fails     | works                   |
| **Get-BGPPeer from 10.0.20348.1787 ConnectivityStatus** | Connected           | Connected             | Connecting               | Connected               |

*Indicates the host had the fix I specified applied to it remotely.

| Version          | Status |
|------------------|--------|
| 10.0.20348.1547  | works  |
| 10.0.20348.1607  | works  |
| 10.0.20348.1726  | works  |
| 10.0.20348.1787  | works  |
| 10.0.20348.1906  | works  |
| 10.0.20348.1970  | works  |
| 10.0.20348.2322  | fails  |

## Current Behavior
calico nodes with 10.0.20348.2322 cause catastrophic issues on the network

## Possible Solution
The workaround is to remove that update.

## Steps to Reproduce (for bugs)
1. Update Windows 2022 to the latest version in Windows Update.
2. Observe other Calico nodes cannot peer with it via BGP.
3. If you are using a ToR such as VyOS, it apparently can peer with it, and it receives glitchy routes and all sorts of problems occur.

## Context
This wrecked a demo and kind of ruined a few days of my life.

## Your Environment

* Calico version 3.26.4 (attempted to update to resolve this)
* Orchestrator version (e.g. kubernetes, mesos, rkt): kubernetes 1.26.2
* Operating System and version: Windows 2022 10.0.20348.2322

**Comment by coutinhop** [comment]
Thanks for the detailed report @doctorpangloss! I'll attempt a repro and investigate

**Comment by coutinhop** [comment]
@doctorpangloss I'm having trouble reproducing due to not having access to a Windows box. I've tried spinning up VMs on AWS and Azure but didn't manage to get the update (I'm trying to get it directly with `Get-WindowsUpdate -Install -KBArticleID KB5034770`, but on Azure I get an 'access denied' error, on aws the KBArticleID doesn't seem to be there).

Could you help me out by posting calico logs? I see you're using BGP, the just released v3.27.2 version has fixes to confd on Windows so you should be able to use the operator install for windows if you want to.

Thanks!

**Comment by doctorpangloss** [comment]
this is a real issue. I am sorry it is hard to get Windows 2022 up and running on the vendors, I use physical nodes.

**Comment by coutinhop** [comment]
@doctorpangloss apologies, I've reopened the issue. Yes, I've been having trouble reproducing this issue on the cloud providers we normally use, and have no access to a physical windows node at the moment. I'm trying to get this update available in a windows VM currently

**Comment by doctorpangloss** [comment]
I appreciate it, it is very tricky to deal with this stuff. But without a doubt, the update breaks BGP on Windows.

**Comment by avin3sh** [comment]
Calico networking on VXLAN started breaking for us after installing the July 2024—KB5040437 (OS Build 20348.2582) CU on our Windows Server 2022 worker.

When scheduling workload on node, some pods appeared to be coming up normally but majority of the pods had Pod networking breaking. `ping 1.1.1.1` returned `General failure`, for example. The pods could be exec'ed into, though but weren't reachable via Pod DNS or Service DNS name.

This particular issue was opened in context of Calico BGP with February CU, so I might just create a new issue, but Calico Windows appear to be needing some love after recent monthly patches seem to be causing catastrophic network failure 🥺

**Comment by coutinhop** [comment]
@avin3sh I see you filed https://github.com/projectcalico/calico/issues/9019 (that's caused by a Windows containers issue in another Windows update version, I did link them in there), sorry but there's not much we can do to prevent upstream issues from breaking Calico...

@doctorpangloss I still haven´t been able to reproduce this to investigate, but will give it another go this week, did you have a chance to collect additional logs (since you're using v3.26, the logs would require logging into the Windows host to look at `c:/CalicoWindows/logs)?

**Comment by alexandra-branco** [comment]
I had exactly this problem with Calico (`v3.27.2`) on Physical Windows Nodes (Kubernetes `v1.30.5`). With the latest Windows Update (`KB5044281`), the problem seems to have been resolved.

**Microsoft October 8, 2024 - KB5044281 (OS Build 20348.2762)**

> [Containers (known issue)] Fixed: Container networking on Kubernetes might not work as you expect. Containers fail to reach external networks or communicate between pods. It might affect you when you use Calico to set up container networking on development or production instances. If affected, containers will not connect to the internet. The host’s firewall also blocks network traffic. When you ping external addresses, like ‘microsoft.com,’ you might get a general failure error message.
