### ISSUE TITLE
calicoctl has silent failure if passed in config file does not exist

### ISSUE THREAD

**Issue by tmjd** [projectcalico/calico#853]
When attempting to pass in a config file to `calicoctl node run` I had misnamed the file and could not understand why the configuration in my file was being ignored.  There is no indication that a passed in file does not exist.

## Expected Behavior

If a file is passed with `--config` to calicoctl and the file does not exist then an error message will be printed.  I think it would also be good to just exit in that case too but can understand not exiting to keep the current behavior.

## Current Behavior

Passing in a non-existent file to calicoctl `--config` flag produces no message or error.

## Possible Solution

If a non-default value is received from the `--config` option and the file does not exist then print an error message.

## Steps to Reproduce (for bugs)
1. Use calicoctl where the non-default values do not access the datastore
2. Run `calicoctl get node --config non-existent-file.yaml
3. See no indication that file does not exist.

## Context
See summary

## Your Environment
* Calicoctl version v1.3.0

**Comment by bcreane** [comment]
Migrated a copy of this issue to projectcalico/calicoctl
