### ISSUE TITLE
Incompatibility with Calico eBPF Mode When Transitioning from kube-proxy + IPVS Mode

### ISSUE THREAD

**Issue by pf2rich** [projectcalico/calico#8530]
Issue Description:
When attempting to switch from kube-proxy + IPVS mode to Calico eBPF mode with Calico version 3.26.4 and Kubernetes version 1.22.0, the host becomes instantly inaccessible. Any attempt to access 127.0.0.1 on the host results in the error message "ping: sendmsg: Operation not permitted."

However, switching from kube-proxy + iptables mode to Calico eBPF mode does not exhibit any issues.

Query:
Is the current implementation of Calico eBPF mode incompatible with transitioning from kube-proxy + IPVS mode?

Your prompt attention to this matter would be appreciated.

**Comment by pf2rich** [comment]
`// Check if current felix ipvs config is correct when felix gets a kube-ipvs0 interface update.
// If KubeIPVSInterface is UP and felix ipvs support is disabled (kube-proxy switched from iptables to ipvs mode),
// or if KubeIPVSInterface is DOWN and felix ipvs support is enabled (kube-proxy switched from ipvs to iptables mode),
// restart felix to pick up correct ipvs support mode.
func (d *InternalDataplane) checkIPVSConfigOnStateUpdate(state ifacemonitor.State) {
	ipvsIfacePresent := state != ifacemonitor.StateNotPresent
	ipvsSupportEnabled := d.config.RulesConfig.KubeIPVSSupportEnabled
	if ipvsSupportEnabled != ipvsIfacePresent {
		log.WithFields(log.Fields{
			"ipvsIfaceState": state,
			"ipvsSupport":    ipvsSupportEnabled,
		}).Info("kube-proxy mode changed. Restart felix.")
		d.config.ConfigChangedRestartCallback()
	}
}`
When kube-proxy uses ipvs mode, that is, when kube-ipvs0 exists, switching to ebpf mode will cause felix to restart indefinitely.

**Comment by pf2rich** [comment]
If I remove the kube-ipvs0 interface, the calico-node pod can be ready

**Comment by sridhartigera** [comment]
@pf2rich We don't support moving to eBPF mode from IPVS. For now the path forward is to move to kube-proxy iptables mode and then switch to eBPF.
