### ISSUE TITLE
Images not available for release

### ISSUE THREAD

**Issue by cwrau** [projectcalico/calico#8531]
## Expected Behavior
The images referenced in https://github.com/projectcalico/calico/blob/release-v3.27/manifests/calico.yaml, and in general the `release-v3.$kubeMinor`, should exist.

## Current Behavior
On February 16, at around 8pm CEST, the referenced images in that branch were changed but didn't exist.

## Possible Solution
Build images first, update manifest later.

## Context
Lots of our clusters had a single node, thankfully just one, disconnected from the CNI.

## Your Environment
We're installing calico with flux, gitrepository and kustomization by referencing the above mentioned yaml.

**Comment by fasaxc** [comment]
Agree, we should push images first but it's pretty crazy to deploy whatever gets pushed to that URL into prod with no delay!  If you're going to automate that much , you should do an automated canary deployment and only roll out if the new version works correctly for you.
