### ISSUE TITLE
 The proper use of multiple IP Pools？

### ISSUE THREAD

**Issue by promacanthus** [projectcalico/calico#8539]
1. If creating hundreds of IPPools in a kubernetes cluster, is there any thing wrong?
2. What is the proper way to use multiple IPPools effectively?

**Comment by caseydavenport** [comment]
> What is the proper way to use multiple IPPools effectively?

This depends on what your needs are. In general, I'd recommend against using multiple IP pools unless you have a specific use-case that requires them. A single pool is just simpler to manage if you don't need more.

> If creating hundreds of IPPools in a kubernetes cluster, is there any thing wrong?

Hundreds of IP pools can strain the system, especially if they are small. There have been a number of issues over the years related to systems running with several hundred IP pools - most have been fixed though. It's not necessarily a problem, but I'd generally recommend against doing this unless it's absolutely needed. Usually there's a better way.
