### ISSUE TITLE
Mesos Vagrant Demo uses rsync with windows

### ISSUE THREAD

**Issue by ozdanborne** [projectcalico/calico#856]
Conversation from Slack:

>samding [2:03 PM] 
I am trying mesos demo :`http://docs.projectcalico.org/v2.2/getting-started/mesos/vagrant/` on windows7, during the starting, it asks "rsync" and says "rsync" could not be found on your PATH. Make sure that rsyncis properly installed on your system and available on the PATH",  is this `rsync` `Acrosync`? Thx. (edited)

>ozdanborne [2:07 PM] 
@samding sounds like you are hitting this: https://github.com/projectcalico/calico/blob/master/v2.2/getting-started/mesos/vagrant/Vagrantfile#L92-L94 

>can you try editing that line from `/home/vagrant/sync` to just `/vagrant` and see  if that works?

>as per: https://github.com/CentOS/sig-cloud-instance-build/pull/34/

>samding [7:24 AM] 
@ozdanborne Thanks! After changing it started.

**Comment by caseydavenport** [comment]
@ozdanborne what do we need to do to fix this?

**Comment by caseydavenport** [comment]
Closing as stale.
