### ISSUE TITLE
calico is deployed using calico-etcd.yaml, CRD is not supported, how should I change the bgp default port 179 to another port

### ISSUE THREAD

**Issue by qq3200341** [projectcalico/calico#8566]
calico is deployed using calico-etcd.yaml, CRD is not supported, how should I change the bgp default port 179 to another port

**Comment by caseydavenport** [comment]
For one, I'd recommend using the operator install which allows configuration using `kubectl`. 

Otherwise, you can perform all of the same steps using `calicoctl` instead to modify BGPConfiguration.

**Comment by qq3200341** [comment]
So i you use calico-etcd.yaml deployment i can't change the bgp default port, right?

**Comment by qq3200341** [comment]
So if i use calico-etcd.yaml deployment i can't change the bgp default port, right? @caseydavenport

**Comment by caseydavenport** [comment]
With `calico-etcd.yaml`, you can change the BGP default port using `calicoctl` to interact with projectcalico.org/v3 resources instead of `kubectl`.

**Comment by qq3200341** [comment]
Sorry, I don't know much about calico, can you give a specific example?Here is my own attempt:

```shell
kubectl-calico create -f calico-bgpport.yaml 
Failed to create 'BGPConfiguration' resource: [resource does not exist: BGPConfiguration(default) with error: the server could not find the requested resource (post BGPConfigurations.crd.projectcalico.org)]
``` 
calico-bgpport.yaml:
```shell
apiVersion: projectcalico.org/v3
kind: BGPConfiguration
metadata:
  name: default
spec:
  listenPort: 1179
```

**Comment by caseydavenport** [comment]
Check out these docs:

- https://docs.tigera.io/calico/latest/reference/calicoctl/overview
- https://docs.tigera.io/calico/latest/operations/calicoctl/install
