### ISSUE TITLE
REMOTESUBNETROUTE VFP rule does not exist when no container is running on the Windows worker

### ISSUE THREAD

**Issue by avin3sh** [projectcalico/calico#8569]
## Expected Behavior

`REMOTESUBNETROUTE` rule is required in VXLAN Overlay mode for inter-node connectivity. Without this rule a worker node where Calico and kube-proxy are running is unable to reach out to any service VIP.

## Current Behavior

It looks like when the worker node does not have any containers running on it, there is no `REMOTESUBNETROUTE` VFP rule present - this causes failures when the node is trying to connect to another service on the same cluster. This is inspite `REMOTESUBNETROUTE` policy being present as per HNS.

## Steps to Reproduce (for bugs)

1. Setup on-prem Windows worker with Calico, without hostprocess container, and Windows Server 2022
2. Run a pod on a Linux worker
3. Try connecting to the pod on Linux worker from Windows worker, ensure there is no container running on the Windows worker
4. Request times out / packet drops

**Comment by coutinhop** [comment]
@avin3sh could you please enable debug logging (by setting `logSeverityScreen` to `Debug` in the default FelixConfiguration) and post logs from the windows nodes? (they should be located in `C:/CalicoWindows/logs`)

**Comment by caseydavenport** [comment]
@avin3sh any update? Otherwise will close due to inactivity.

**Comment by avin3sh** [comment]
Apologies for the radio silence. Please give me another week of time and I will revert with detailed logs.

**Comment by avin3sh** [comment]
I tried reproducing this with more recent v3.27 but couldn't. I will try an upgrade to v3.27 first.
