### ISSUE TITLE
Non-calico node how to access the calico network?

### ISSUE THREAD

**Issue by JinsYin** [projectcalico/calico#858]
Non-calico node how to access calico network?

**Comment by tmjd** [comment]
Check out the "Inbound connectivity" section in http://docs.projectcalico.org/v2.3/usage/external-connectivity

If you are just doing some testing a simple way to get connectivity is to run calico/node, configured to connect to the datastore being used, on a non-calico node.  That would cause the routes to be distributed to that host and then it would be able to access the workloads.

**Comment by tmjd** [comment]
@JinsYin I hope the link or my suggestion helped.  If you are still having issues with getting access please feel free to reopen this or ask questions in Slack at  http://slack.projectcalico.org/ or in IRC on freenode at #calico.
