### ISSUE TITLE
Distinguish pods by cali interface name

### ISSUE THREAD

**Issue by stralex7** [projectcalico/calico#8598]
Is there a simple way to map between a pod information in K8s and on host cali interface name on the e.g. worker host?

The process we use as of today:
- get a container pid from any container of the pod
- "ip netns indentify <pid>" returns cni-<uid> NS name in return
- ip l | grep ns_name

## Expected Behavior
A clear way to map an information obtained from K8s to identify cali interface name or cni-namespace.

## Current Behavior
It is not clear how names of interfaces and namespaces are generated and used.

## Possible Solution
N/A

## Steps to Reproduce (for bugs)
ip link show
cali6b54e6eda63@if6: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 2090 qdisc noqueue state UP mode DEFAULT group default 
    link/ether ee:ee:ee:ee:ee:ee brd ff:ff:ff:ff:ff:ff link-netns cni-2a3d98a7-78bd-e747-40c9-eddaad083109

**Comment by caseydavenport** [comment]
@stralex7 you can use `calicoctl` to query the WorkloadEndpoint from Calico's perspective.

For example:

```
calicoctl get weps -n calico-apiserver
```

Returns something like this:

```
NAMESPACE          WORKLOAD                            NODE           NETWORKS                                                   INTERFACE         
calico-apiserver   calico-apiserver-57589b6747-bqcdn   kind-worker3   192.168.195.194/32,fd00:10:244:0:58fd:b191:5c13:9cc1/128   cali470c2d79457   
calico-apiserver   calico-apiserver-57589b6747-nrm2f   kind-worker2   192.168.110.131/32,fd00:10:244:0:1cc0:b1ac:ad47:e7c2/128   cali0fe72600521 
```

Alternatively, you can use the pod's IP and then do a route lookup on the node to find the target interface:

```
ip route get <pod IP>
```

**Comment by stralex7** [comment]
@caseydavenport Thank you a lot for a calicoctl hint. But 'ip r get' is such an elegant solution and feels like an obvious thing now. Thanks again!
