### ISSUE TITLE
The k8s node lost network (drop all the packets) after the calico-node pod is manually restarted

### ISSUE THREAD

**Issue by drummerglen** [projectcalico/calico#8646]
Hi guys,

I was testing calico's ebpf mode in recent days, I found that when I manually killed the calico-node pod for reliability test, the node's network was lost and it could not respond to any external connections. 

I have to login the node through external console (just like vmrc or ibmc) and use `tc-s qdisc show dev` to find that the number of drop packets is increasing. Only by restarting the node can the node network be restored to normal. 

I have searched for a long time in calico official documentation, google and github. Have not found the answer when, this question is very tricky, if it happens in the production environment it will be a disaster!

please feel free to give advice! Orz

## Expected Behavior

k8s node work normally after restart calico-node pod

## Current Behavior

k8s node work normally after restart calico-node pod

## Possible Solution

No

## Steps to Reproduce (for bugs)

**1.Make sure calico has enabled eBPF mode. Here is the felixconfiguration**
<img width="967" alt="image" src="https://github.com/projectcalico/calico/assets/42017338/a1e146ff-fde3-424c-bc06-e2895f4bcb7a">

**2. Make sure all the daemonsets of calico-node work normally and the pod could see the client's real source ip**
<img width="909" alt="image" src="https://github.com/projectcalico/calico/assets/42017338/328baab7-ec60-44db-acad-d4f126d23f20">
<img width="451" alt="image" src="https://github.com/projectcalico/calico/assets/42017338/f3e9106f-f09e-4770-a5c6-8cb0f2311f7e">

**3.Kill calico-node pod manually and node lost network**
Obviously nodes become NotReady after a while.
<img width="1306" alt="image" src="https://github.com/projectcalico/calico/assets/42017338/cfac0d3e-2513-4188-bbdc-a52bcf29b76e">

**4.Check the node network connectivity and eBPF qdisc clsact status**
Using command `ping %gateway%` and `tc -s qdisc show dev ens160`.
It can not transmit any icmp packet and the number of drops growing rapidly.
<img width="725" alt="image" src="https://github.com/projectcalico/calico/assets/42017338/f8144d3c-c3ac-4f59-b869-6f11368b4e68">
<img width="595" alt="image" src="https://github.com/projectcalico/calico/assets/42017338/eab6d33f-a326-4f48-bb39-ac391675813a">
<img width="597" alt="image" src="https://github.com/projectcalico/calico/assets/42017338/57de94b1-1a3e-43d0-868b-93839477dc90">
<img width="596" alt="image" src="https://github.com/projectcalico/calico/assets/42017338/447b4d02-6467-4da1-9229-b12e93e069d6">

## Context

Just lab env, but if it happens in the production environment it will be a disaster!

## Your Environment

* Calico version: 3.24.5
* Orchestrator version (e.g. kubernetes, mesos, rkt): v1.25.9 on-prem kubeadm kubernetes cluster with one master and two worker node
* Operating System and version: Ubuntu 20.04.6
* Link to your project (optional): None

**Comment by tomastigera** [comment]
You mean, when the pod starts again, you still do not have connectivity. Or the pod does not even come up again? That is certainly unexpected behaviour, however, you are using a pretty old calico version (but even with that one should work as expected in this scenario). Please, upgrade to a more recent version of calico. I'd recommend 3.27.2 as many issues were fixed since 3.24. 3.28 is about to be released. Feel free to reopen this issue if you can repro with a recent version.

**Comment by drummerglen** [comment]
@tomastigera That's awesome. The issue was resolved by updating to 3.27.3
