### ISSUE TITLE
reference on calico main 

### ISSUE THREAD

**Issue by v1k0d3n** [projectcalico/calico#865]
this has probably already been caught and considered, but i noticed that the [Integrate with an Orchestrator](http://www.projectcalico.org/getting-started/docker/) reference on the main [Calico Project Page](http://www.projectcalico.org/getting-started/docker/) forwarded me to a dead link on [GitHub](https://github.com/projectcalico/calico-docker/blob/master/docs/Orchestrators.md). 

I'm assuming that you want to forward users to [Calico on Docker](https://github.com/projectcalico/calico-docker/blob/master/README.md)? At least this is what I was after...I think. :smile:

**Comment by alexwlchan** [comment]
Thanks for the spot! :-)

Pinging @robbrockbank, who manages the website

**Comment by robbrockbank** [comment]
Yup was just looking at it! :-)

We're in the middle of reworking the docs a little - in particular the old Orchestrator guide referred to our calico-docker integration using powerstrip - this is in the process of being retired in preference to dockers native use libnetwork.  We will be re-instating the guide soon (there is an issue open for it) - but yup we didn't spot the link from the projectcalico.org site, so thanks for that.

**Comment by v1k0d3n** [comment]
no worries. i figured it was already caught and addressed, but i wanted to make sure that you guys were aware...just in case. sometimes tracking everything is tough.

so is the [Calico on Docker](https://github.com/projectcalico/calico-docker/blob/master/README.md) guide ultimately where you're going to point users instead of the previous reference?

**Comment by robbrockbank** [comment]
I think pointing there would be a good solution until the next docs rework - I'll update in just a mo.

**Comment by robbrockbank** [comment]
Main link updated.  I'll update the calico-docker specific issue, to make sure we don't miss this when we add a new orchestrators guide.
