### ISSUE TITLE
After calico-node is started, the node continues to be in NetworkUnavailable state

### ISSUE THREAD

**Issue by gongzixiangyuan** [projectcalico/calico#8651]
## Expected Behavior
After calico-node starts, NetworkUnavailable returns to false

## Current Behavior
1. After calico-node is stopped, NetworkUnavailable is set to false
2. When calico-node started, calling the apiserer timed out, and no update was successful after 30 seconds. calico-node swallowed the exception and stopped updating.
3. Container network pod cannot be deployed on the node

## Possible Solution
```go
if os.Getenv("CALICO_NETWORKING_BACKEND") != "none" {
		if clientset != nil {
			err := utils.SetNodeNetworkUnavailableCondition(*clientset, k8sNodeName, false, 30*time.Second)
			if err != nil {
				log.WithError(err).Error("Unable to set NetworkUnavailable to False")
                                // FIXME: Is it more appropriate to call utils.Terminate() here ?
			}
		}
	}
``` 

## Steps to Reproduce (for bugs)
1. Stop calico-node
2. Constructing apiserver exception when starting calico-node

## Your Environment

* Calico version 3.25.2

**Comment by caseydavenport** [comment]
Yeah, seems like we need to restart if we fail to update the condition after a certain amount of time.

**Comment by gongzixiangyuan** [comment]
> Yeah, seems like we need to restart if we fail to update the condition after a certain amount of time.

Thank you very much for your reply

**Comment by cyclinder** [comment]
Let's call `utils.Terminate()` here, calico-node can exit with code 1, so it will be restarted. I can help with this.
