### ISSUE TITLE
Restrict traffic from host-network pods to IMDS

### ISSUE THREAD

**Issue by laiminhtrung1997** [projectcalico/calico#8708]
Dear everyone,

I'm seeking guidance on how to block access to IMDS (Instance Metadata Service) for all host-network pods, while allowing specific other host-network pods to access it. I've attempted to deploy HostEndpoint and GlobalNetworkPolicy, but Calico simply blocks access to IMDS for all host-network pods without allowing me to configure exceptions for specific ones. Could you please assist me in resolving this situation? Your help would be greatly appreciated. Thank you.

Best regards,
Trung Lai

**Comment by caseydavenport** [comment]
> for all host-network pods, while allowing specific other host-network pods to access it

Unfortunately, there is no good way to distinguish one host networked pod from another host networked pod today. They share the same network namespace, interfaces, ip address, etc.

**Comment by caseydavenport** [comment]
Do you need to run these pods with `hostNetwork: true`?

**Comment by laiminhtrung1997** [comment]
Yes, these pods have to be configured with hostNetwork.
I want to do more restrictions on the IMDS, so I configured the EC2 with IMDSv2 and set the hop limit as 1. It means only the host-network pod can access IMDS. Unfortunately, I have only one pod that must be configured with hostNetwork and must access IMDS to do its jobs. More specifically, the pod is adot-collector.
