### ISSUE TITLE
Improve checkConflictingNodes() processing to avoid excessive queries on startup

### ISSUE THREAD

**Issue by robbrockbank** [projectcalico/calico#871]
During calico/node startup, the startup script performs a check for conflicting IP addresses configured across the cluster of nodes.

For large deployments this can take lead to a large number of queries if all nodes are restarting at the same time.

We should either just remove this check completely (it's not strictly required), perform a lazy validation, add a validation function in calicoctl (which you run anywhere once), or only perform this validation when the node IP addresses change.

**Comment by caseydavenport** [comment]
After discussing with @robbrockbank, we think the following is a good solution:

1) Only perform the IP validation check when startup.go thinks the IP address has changed.
2) Add an option to disable the IP validation check entirely (e.g. `DISABLE_NODE_IP_CHECK=true`)

**Comment by robbrockbank** [comment]
Key thing to add is that it is the Nodes().List() operation that is heavy-weight so that is the operation that should be avoided unless necessary.

**Comment by heschlie** [comment]
Resolved in #915
