### ISSUE TITLE
The iptables rule for calico networkpolicy

### ISSUE THREAD

**Issue by smallemployees** [projectcalico/calico#8723]
## Expected Behavior

Find specific rules to block pods
## Current Behavior

Pod cannot communicate across hosts, and SVC cannot access Pod. How can I find the reason through rules
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Calico version
* Orchestrator version (e.g. kubernetes, mesos, rkt):
* Operating System and version:
* Link to your project (optional):

**Comment by frozenprocess** [comment]
[Here](https://github.com/frozenprocess/Tigera-Presentations/tree/master/2023-03-30.container-and-Kubernetes-security-policy-design/04.best-practices-for-securing-a-Kubernetes-environment) is a tutorial on the subject that allows you to use IPtable log commands to achieve traffic visibility.
We also got couple of videos in our YouTube channel around the same subject. https://youtu.be/P0LV8mV7lD8?t=510
