### ISSUE TITLE
Calico Controller not running due to dial tcp 10.96.0.1:443: i/o timeout

### ISSUE THREAD

**Issue by AnushaTRC** [projectcalico/calico#8767]
We set up the k8s cluster in Redhat 8.9 with below versions.
Kubernetes 1.27
Containerd 1.6
Calico 3.25.1
But the calico controller and coredns pods fail to start due to the below issue.

**Pod Logs:**

kubectl logs calico-kube-controllers-674fff74c8-tf4vg -n kube-system

2024-04-26 19:48:51.630 [INFO][1] main.go 107: Loaded configuration from environment config=&config.Config{LogLevel:"info", WorkloadEndpointWorkers:1, ProfileWorkers:1, PolicyWorkers:1, NodeWorkers:1, Kubeconfig:"", DatastoreType:"kubernetes"}
W0426 19:48:51.631240       1 client_config.go:617] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
2024-04-26 19:48:51.631 [INFO][1] main.go 131: Ensuring Calico datastore is initialized
2024-04-26 19:49:21.632 [ERROR][1] client.go 290: Error getting cluster information config ClusterInformation="default" error=Get "
[https://10.96.0.1:443/apis/crd.projectcalico.org/v1/clusterinformations/default":](https://10.96.0.1/apis/crd.projectcalico.org/v1/clusterinformations/default%22:)
dial tcp 10.96.0.1:443: i/o timeout
2024-04-26 19:49:21.632 [INFO][1] main.go 138: Failed to initialize datastore error=Get "
[https://10.96.0.1:443/apis/crd.projectcalico.org/v1/clusterinformations/default":](https://10.96.0.1/apis/crd.projectcalico.org/v1/clusterinformations/default%22:)
dial tcp 10.96.0.1:443: i/o timeout

Please let me know if any additional information is required and help us to resolve this.

**Comment by fs2016l** [comment]
I have the same question

**Comment by fs2016l** [comment]
Warning  FailedCreatePodSandBox  114m                 kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container "3d6733531c3caf74141893557e9d697f5ba909a3a08874087ed6892142153048" network for pod "calico-kube-controllers-7b84757b95-576fg": networkPlugin cni failed to set up pod "calico-kube-controllers-7b84757b95-576fg_kube-system" network: plugin type="calico" failed (add): error creating calico client: stat /etc/cni/net.d/calico-kubeconfig: no such file or directory
  
Warning  Unhealthy               113m (x7 over 114m)  kubelet            Readiness probe failed: Error initializing datastore: Get "https://10.96.0.1:443/apis/crd.projectcalico.org/v1/clusterinformations/default": dial tcp 10.96.0.1:443: connect: no route to host

**Comment by fs2016l** [comment]
我发现在k8s集群启动后,手动添加10.96.0.1:443防火墙,可以正常运行,但是我已经提前开放了所有ip的443端口防火墙,我不理解这是为什么,似乎有什么东西覆盖了之前的防火墙

**Comment by tomastigera** [comment]
> dial tcp 10.96.0.1:443: connect: no route to host

Is kube-proxy running? Do you have port 443 allowed in your environment (how does the env look like) Calico has 443 in failsafe ports so calico would not block 443. But would fail to start if it wasn't already allowed.

**Comment by fs2016l** [comment]
The 443 port on the firewall is open, and everything works fine when I temporarily add the 443 port using iptables. However, when I restart the server, the iptables rule I added should be ineffective, but to my confusion, it still works normally.

---- Replied Message ----
| From | Tomas ***@***.***> |
| Date | 04/30/2024 07:50 |
| To | projectcalico/calico ***@***.***> |
| Cc | fs2016l ***@***.***>,
Comment ***@***.***> |
| Subject | Re: [projectcalico/calico] Calico Controller not running due to dial tcp 10.96.0.1:443: i/o timeout (Issue #8767) |

dial tcp 10.96.0.1:443: connect: no route to host

Is kube-proxy running? Do you have port 443 allowed in your environment (how does the env look like) Calico has 443 in failsafe ports so calico would not block 443. But would fail to start if it wasn't already allowed.

**Comment by tomastigera** [comment]
> However, when I restart the server, the iptables rule I added should be ineffective, but to my confusion, it still works normally.

That is out of scope for calico I am affraid.

**Comment by Catherine-monk** [comment]
I also encountered the same problem. How did you resolve it?
2024-07-01 06:40:09.354 [ERROR][1] client.go 295: Error getting cluster information config ClusterInformation="default" error=Get "https://10.233.0.1:443/apis/crd.projectcalico.org/v1/clusterinformations/default": dial tcp 10.233.0.1:443: connect: connection refused
2024-07-01 06:40:09.355 [INFO][1] main.go 138: Failed to initialize datastore error=Get "https://10.233.0.1:443/apis/crd.projectcalico.org/v1/clusterinformations/default": dial tcp 10.233.0.1:443: connect: connection refused
2024-07-01 06:40:26.688 [ERROR][1] client.go 295: Error getting cluster information config ClusterInformation="default" error=Get "https://10.233.0.1:443/apis/crd.projectcalico.org/v1/clusterinformations/default": net/http: TLS handshake timeout

**Comment by fs2016l** [comment]
我怀疑是k8s的iptables与linux的冲突了,两个办法解决,第一个办法关闭防火墙,第二个办法重新添加iptables规则:iptables -A OUTPUT -p tcp -d 10.96.0.1 --dport 443 -j ACCEPT
iptables -A OUTPUT -p tcp -d 10.96.0.1 --dport 53 -j ACCEPT 你可以试一下,有任何问题可以重新联系我
| |
fs2016l
|
|
***@***.***
|


---- Replied Message ----
| From | ***@***.***> |
| Date | 07/1/2024 17:12 |
| To | ***@***.***> |
| Cc | ***@***.***> ,
***@***.***> |
| Subject | Re: [projectcalico/calico] Calico Controller not running due to dial tcp 10.96.0.1:443: i/o timeout (Issue #8767) |

I also encountered the same problem. How did you resolve it?
2024-07-01 06:40:09.354 [ERROR][1] client.go 295: Error getting cluster information config ClusterInformation="default" error=Get "https://10.233.0.1:443/apis/crd.projectcalico.org/v1/clusterinformations/default": dial tcp 10.233.0.1:443: connect: connection refused
2024-07-01 06:40:09.355 [INFO][1] main.go 138: Failed to initialize datastore error=Get "https://10.233.0.1:443/apis/crd.projectcalico.org/v1/clusterinformations/default": dial tcp 10.233.0.1:443: connect: connection refused
2024-07-01 06:40:26.688 [ERROR][1] client.go 295: Error getting cluster information config ClusterInformation="default" error=Get "https://10.233.0.1:443/apis/crd.projectcalico.org/v1/clusterinformations/default": net/http: TLS handshake timeout

**Comment by liweis** [comment]
> 我怀疑是k8s的iptables与linux的冲突了,两个办法解决,第一个办法关闭防火墙,第二个办法重新添加iptables规则:iptables -A OUTPUT -p tcp -d 10.96.0.1 --dport 443 -j ACCEPT iptables -A OUTPUT -p tcp -d 10.96.0.1 --dport 53 -j ACCEPT 你可以试一下,有任何问题可以重新联系我 | | fs2016l | | ***@***.*** |
> […](#)
> ---- Replied Message ---- | From | ***@***.***> | | Date | 07/1/2024 17:12 | | To | ***@***.***> | | Cc | ***@***.***> , ***@***.***> | | Subject | Re: [projectcalico/calico] Calico Controller not running due to dial tcp 10.96.0.1:443: i/o timeout (Issue #8767) | I also encountered the same problem. How did you resolve it? 2024-07-01 06:40:09.354 [ERROR][1] client.go 295: Error getting cluster information config ClusterInformation="default" error=Get "https://10.233.0.1:443/apis/crd.projectcalico.org/v1/clusterinformations/default": dial tcp 10.233.0.1:443: connect: connection refused 2024-07-01 06:40:09.355 [INFO][1] main.go 138: Failed to initialize datastore error=Get "https://10.233.0.1:443/apis/crd.projectcalico.org/v1/clusterinformations/default": dial tcp 10.233.0.1:443: connect: connection refused 2024-07-01 06:40:26.688 [ERROR][1] client.go 295: Error getting cluster information config ClusterInformation="default" error=Get "https://10.233.0.1:443/apis/crd.projectcalico.org/v1/clusterinformations/default": net/http: TLS handshake timeout — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***>

Hi I still face this issue after add these two iptables rule, do you have other suggestions?

![image](https://github.com/user-attachments/assets/bcb48eb6-c7ae-4780-b6ba-c164103eda2f)

**Comment by fs2016l** [comment]
> > 我怀疑是k8s的iptables与linux的冲突了，有两个办法解决，第一个办法关闭防火墙，第二个办法重新添加iptables规则：iptables -A OUTPUT -p tcp -d 10.96.0.1 --dport 443 - j ACCEPT iptables -A OUTPUT -p tcp -d 10.96.0.1 --dport 53 -j ACCEPT 你可以试一下，有任何问题可以重新联系我 | | FS2016l | | _**@**_ .*** | 
> > […](#)  
> > ---- 回复消息 ---- |来自| _**@**_。_**> | |日期| 2024/07/1 17:12 | |至| _**@**_。**_ > | |抄送| _**@**_。_**>，_**@**_。**_ > | |主题 |回复：[projectcalico/calico] Calico Controller 因拨号 tcp 10.96.0.1:443: i/o 超时而未运行（问题#8767）| 我也遇到了同样的问题。你是怎么解决的？ 2024-07-01 06:40:09.354 [ERROR][1] client.go 295：获取集群信息配置时出错 ClusterInformation="default" error=Get " https://10.233.0.1:443/apis/crd.projectcalico.org/v1/clusterinformations/default “：拨号 tcp 10.233.0.1:443：连接：被拒绝连接 2024-07-01 06：40：09.355 [INFO ][1] main.go 138：无法初始化数据存储错误=获取“ https://10.233.0.1:443/apis/crd.projectcalico.org/v1/clusterinformations/default ”：拨号 tcp 10.233.0.1:443：连接：连接被拒绝 2024-07-01 06：40：26.688 [错误][1] client.go 295：获取集群信息配置时错误 ClusterInformation="default" error=Get " [https://10.233.0.1:443/apis/crd. projectcalico.org/v1/ clusterinformations/default](https://10.233.0.1:443/apis/crd.projectcalico.org/v1/clusterinformations/default) “：net/http：TLS 握手超时 — 直接回复此电子邮件、在 GitHub 上查看或取消订阅。您收到此邮件是因为您发表了评论。消息 ID：_**@**_ . ***>
> 
> @fs2016l您好，添加这两个 iptables 规则后我仍然遇到这个问题，您还有其他建议吗？
> 
> ![图像](https://private-user-images.githubusercontent.com/3294154/381492967-bcb48eb6-c7ae-4780-b6ba-c164103eda2f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAyODY4NjEsIm5iZiI6MTczMDI4NjU2MSwicGF0aCI6Ii8zMjk0MTU0LzM4MTQ5Mjk2Ny1iY2I0OGViNi1jN2FlLTQ3ODAtYjZiYS1jMTY0MTAzZWRhMmYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAzMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMzBUMTEwOTIxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ODUwOTVlMTU4OTEzZTkxODVjNTY5NWRlYjRlZjA4MDA4ZWVhNmE2NjhmOTFlODQ5YWQ3MDNmMDI0ODVlYTFiYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.5LkSABXsC9SwSRudhYfN9aAx2cOttgiLXsQIsFZYK4U)

我非常确信关闭防火墙可以解决问题

**Comment by fs2016l** [comment]
@liweis 我非常相信关闭防火墙可以解决问题

**Comment by liweis** [comment]
> @liweis 我非常相信关闭防火墙可以解决问题,如果你使用的是基于docker部署,可以尝试重启docker服务试试, 10.233.0.1:443你的是这个端口不通,你要改一下把10.96.0.1改成10.233.0.1

@fs2016l The issue I met happened when I install calico using operator, and the error message is :
![image](https://github.com/user-attachments/assets/10a60489-5ab1-4059-9f50-329044eecc93)
So I added two rules in iptables and restarted the docker service as well, but no luck...

**Comment by wt-1611** [comment]
我也遇到了这个问题，我看了kube-proxy日志发现了问题：

**Comment by wt-1611** [comment]
我也出现了相同的问题，但我看kube-proxy日志发现了问题
```bash
I0211 03:12:25.996562       1 proxier.go:653] "Failed to load kernel module with modprobe, you can ignore this message when kube-proxy is running inside container without mounting /lib/modules" moduleName="ip_vs"
I0211 03:12:25.997818       1 proxier.go:653] "Failed to load kernel module with modprobe, you can ignore this message when kube-proxy is running inside container without mounting /lib/modules" moduleName="ip_vs_rr"
I0211 03:12:25.999040       1 proxier.go:653] "Failed to load kernel module with modprobe, you can ignore this message when kube-proxy is running inside container without mounting /lib/modules" moduleName="ip_vs_wrr"
I0211 03:12:26.000270       1 proxier.go:653] "Failed to load kernel module with modprobe, you can ignore this message when kube-proxy is running inside container without mounting /lib/modules" moduleName="ip_vs_sh"
E0211 03:12:26.001289       1 server_others.go:107] "Can't use the IPVS proxier" err="IPVS proxier will not be used because the following required kernel modules are not loaded: [ip_vs_wrr ip_vs_sh ip_vs ip_vs_rr]"
I0211 03:12:26.008823       1 node.go:163] Successfully retrieved node IP: 192.168.3.103
I0211 03:12:26.008904       1 server_others.go:138] "Detected node IP" address="192.168.3.103"
I0211 03:12:26.023677       1 server_others.go:206] "Using iptables Proxier"
I0211 03:12:26.023697       1 server_others.go:213] "kube-proxy running in dual-stack mode" ipFamily=IPv4
I0211 03:12:26.023702       1 server_others.go:214] "Creating dualStackProxier for iptables"
I0211 03:12:26.023709       1 server_others.go:491] "Detect-local-mode set to ClusterCIDR, but no IPv6 cluster CIDR defined, , defaulting to no-op detect-local for IPv6"
I0211 03:12:26.023861       1 server.go:656] "Version info" version="v1.23.10"
I0211 03:12:26.024656       1 conntrack.go:52] "Setting nf_conntrack_max" nf_conntrack_max=131072
I0211 03:12:26.025171       1 config.go:317] "Starting service config controller"
I0211 03:12:26.025192       1 shared_informer.go:240] Waiting for caches to sync for service config
I0211 03:12:26.025240       1 config.go:226] "Starting endpoint slice config controller"
I0211 03:12:26.025251       1 shared_informer.go:240] Waiting for caches to sync for endpoint slice config
I0211 03:12:26.126866       1 shared_informer.go:247] Caches are synced for endpoint slice config
I0211 03:12:26.126918       1 shared_informer.go:247] Caches are synced for service config

```
