### ISSUE TITLE
k8s 1.29 使用 calicao v3.27.3 calico-kube-controllers 无法成功运行

### ISSUE THREAD

**Issue by fs2016l** [projectcalico/calico#8770]
Normal Scheduled 114m default-scheduler Successfully assigned kube-system/calico-kube-controllers-7b84757b95-576fg to y3
Warning FailedCreatePodSandBox 114m kubelet Failed to create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container "3d6733531c3caf74141893557e9d697f5ba909a3a08874087ed6892142153048" network for pod "calico-kube-controllers-7b84757b95-576fg": networkPlugin cni failed to set up pod "calico-kube-controllers-7b84757b95-576fg_kube-system" network: plugin type="calico" failed (add): error creating calico client: stat /etc/cni/net.d/calico-kubeconfig: no such file or directory
Warning FailedCreatePodSandBox 114m kubelet Failed to create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container "80e85e2e540352d3d3f488bed5e59b6639294764e97573dfc98897ce7b5dd4a1" network for pod "calico-kube-controllers-7b84757b95-576fg": networkPlugin cni failed to set up pod "calico-kube-controllers-7b84757b95-576fg_kube-system" network: plugin type="calico" failed (add): error creating calico client: stat /etc/cni/net.d/calico-kubeconfig: no such file or directory
Normal SandboxChanged 114m (x3 over 114m) kubelet Pod sandbox changed, it will be killed and re-created.
Warning Unhealthy 113m (x7 over 114m) kubelet Readiness probe failed: Error initializing datastore: Get "[https://10.96.0.1:443/apis/crd.projectcalico.org/v1/clusterinformations/default](https://10.96.0.1/apis/crd.projectcalico.org/v1/clusterinformations/default)": dial tcp 10.96.0.1:443: connect: no route to host
Normal Pulled 113m (x2 over 114m) kubelet Container image "calico/kube-controllers:v3.27.3" already present on machine
Normal Started 113m (x2 over 114m) kubelet Started container calico-kube-controllers
Normal Created 113m (x2 over 114m) kubelet Created container calico-kube-controllers
Warning Unhealthy 113m (x2 over 114m) kubelet Readiness probe failed: initialized to false
Warning Unhealthy 99m (x31 over 114m) kubelet Liveness probe failed: Error initializing datastore: Get "[https://10.96.0.1:443/apis/crd.projectcalico.org/v1/clusterinformations/default](https://10.96.0.1/apis/crd.projectcalico.org/v1/clusterinformations/default)": dial tcp 10.96.0.1:443: connect: no route to host
Warning BackOff 89m (x82 over 110m) kubelet Back-off restarting failed container calico-kube-controllers in pod calico-kube-controllers-7b84757b95-576fg_kube-system(2c51d34d-8381-4968-8240-6ba7a469dbdf)
Normal SandboxChanged 85m (x2 over 85m) kubelet Pod sandbox changed, it will be killed and re-created.
Warning Unhealthy 85m kubelet Readiness probe failed: initialized to false
Normal Pulled 84m (x2 over 85m) kubelet Container image "calico/kube-controllers:v3.27.3" already present on machine
Normal Created 84m (x2 over 85m) kubelet Created container calico-kube-controllers
Normal Started 84m (x2 over 85m) kubelet Started container calico-kube-controllers
Warning Unhealthy 83m (x9 over 85m) kubelet Readiness probe failed: Error initializing datastore: Get "[https://10.96.0.1:443/apis/crd.projectcalico.org/v1/clusterinformations/default](https://10.96.0.1/apis/crd.projectcalico.org/v1/clusterinformations/default)": dial tcp 10.96.0.1:443: connect: no route to host
Warning Unhealthy 70m (x26 over 85m) kubelet Liveness probe failed: Error initializing datastore: Get "[https://10.96.0.1:443/apis/crd.projectcalico.org/v1/clusterinformations/default](https://10.96.0.1/apis/crd.projectcalico.org/v1/clusterinformations/default)": dial tcp 10.96.0.1:443: connect: no route to host
Warning BackOff 50m (x123 over 84m) kubelet Back-off restarting failed container calico-kube-controllers in pod calico-kube-controllers-7b84757b95-576fg_kube-system(2c51d34d-8381-4968-8240-6ba7a469dbdf)
Normal SandboxChanged 46m (x2 over 47m) kubelet Pod sandbox changed, it will be killed and re-created.
Normal Pulled 46m kubelet Container image "calico/kube-controllers:v3.27.3" already present on machine
Normal Created 46m kubelet Created container calico-kube-controllers
Normal Started 46m kubelet Started container calico-kube-controllers
Warning Unhealthy 46m kubelet Readiness probe failed: initialized to false
Normal SandboxChanged 44m (x2 over 46m) kubelet Pod sandbox changed, it will be killed and re-created.
Normal Pulled 43m (x2 over 44m) kubelet Container image "calico/kube-controllers:v3.27.3" already present on machine
Normal Created 43m (x2 over 44m) kubelet Created container calico-kube-controllers
Warning Unhealthy 43m (x6 over 44m) kubelet Liveness probe failed: Error initializing datastore: Get "[https://10.96.0.1:443/apis/crd.projectcalico.org/v1/clusterinformations/default](https://10.96.0.1/apis/crd.projectcalico.org/v1/clusterinformations/default)": dial tcp 10.96.0.1:443: connect: no route to host
Normal Killing 43m kubelet Container calico-kube-controllers failed liveness probe, will be restarted
Warning Unhealthy 43m kubelet Readiness probe failed: OCI runtime exec failed: exec failed: cannot exec in a stopped container: unknown
Normal Started 43m (x2 over 44m) kubelet Started container calico-kube-controllers
Warning Unhealthy 43m (x2 over 44m) kubelet Readiness probe failed: initialized to false
Warning Unhealthy 16m (x60 over 44m) kubelet Readiness probe failed: Error initializing datastore: Get "[https://10.96.0.1:443/apis/crd.projectcalico.org/v1/clusterinformations/default](https://10.96.0.1/apis/crd.projectcalico.org/v1/clusterinformations/default)": dial tcp 10.96.0.1:443: connect: no route to host
Warning BackOff 58s (x157 over 42m) kubelet Back-off restarting failed container calico-kube-controllers in pod calico-kube-controllers-7b84757b95-576fg_kube-system(2c51d34d-8381-4968-8240-6ba7a469dbdf)

**Comment by fs2016l** [comment]
Warning FailedCreatePodSandBox 114m kubelet Failed to create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container "3d6733531c3caf74141893557e9d697f5ba909a3a08874087ed6892142153048" network for pod "calico-kube-controllers-7b84757b95-576fg": networkPlugin cni failed to set up pod "calico-kube-controllers-7b84757b95-576fg_kube-system" network: plugin type="calico" failed (add): error creating calico client: stat /etc/cni/net.d/calico-kubeconfig: no such file or directory
Warning FailedCreatePodSandBox 114m kubelet Failed to create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container "80e85e2e540352d3d3f488bed5e59b6639294764e97573dfc98897ce7b5dd4a1" network for pod "calico-kube-controllers-7b84757b95-576fg": networkPlugin cni failed to set up pod "calico-kube-controllers-7b84757b95-576fg_kube-system" network: plugin type="calico" failed (add): error creating calico client: stat /etc/cni/net.d/calico-kubeconfig: no such file or directory

Warning Unhealthy 83m (x9 over 85m) kubelet Readiness probe failed: Error initializing datastore: Get "[https://10.96.0.1:443/apis/crd.projectcalico.org/v1/clusterinformations/default](https://10.96.0.1/apis/crd.projectcalico.org/v1/clusterinformations/default)": dial tcp 10.96.0.1:443: connect: no route to host
Warning Unhealthy 70m (x26 over 85m) kubelet Liveness probe failed: Error initializing datastore: Get "[https://10.96.0.1:443/apis/crd.projectcalico.org/v1/clusterinformations/default](https://10.96.0.1/apis/crd.projectcalico.org/v1/clusterinformations/default)": dial tcp 10.96.0.1:443: connect: no route to host

**Comment by fs2016l** [comment]
我已经放开了防火墙的443端口,但是这没有效果
当我关闭整个防火墙时,他才能成功运行
这个问题该如何解决呢

**Comment by tomastigera** [comment]
@fs2016l I assume [you comment](https://github.com/projectcalico/calico/issues/8764#issuecomment-2080704557) relates more to this question. Why/what sort of a firewall do you need? Does it block 443? Calico is in a sense a firewall. Isn't one solution blocking the use of another solution?

**Comment by cyclinder** [comment]
Kubernetes requires the firewall to be disabled. This is don't related to calico.

**Comment by fs2016l** [comment]
The 443 port on the firewall is open, and everything works fine when I temporarily add the 443 port using iptables. However, when I restart the server, the iptables rule I added should be ineffective, but to my confusion, it still works normally.

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年04月30日 14:57 |
| 收件人 | projectcalico/calico ***@***.***> |
| 抄送人 | fs2016l ***@***.***>,
Mention ***@***.***> |
| 主题 | Re: [projectcalico/calico] k8s 1.29 使用 calicao v3.27.3 calico-kube-controllers 无法成功运行 (Issue #8770) |

Kubernetes requires the firewall to be disabled. This is don't related to calico.

**Comment by fs2016l** [comment]
As for how to open a firewall, it is based on security considerations.

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年04月30日 14:57 |
| 收件人 | projectcalico/calico ***@***.***> |
| 抄送人 | fs2016l ***@***.***>,
Mention ***@***.***> |
| 主题 | Re: [projectcalico/calico] k8s 1.29 使用 calicao v3.27.3 calico-kube-controllers 无法成功运行 (Issue #8770) |

Kubernetes requires the firewall to be disabled. This is don't related to calico.

**Comment by kunaljha5** [comment]
I was able to get ride of the above problem with below steps 

**OS**: RHEL 9
**Kubernetes Version**: 1.29.3 
**Automation**: Kubespray

Steps to fix problem above

1. uninstall firewalld on VM's
```
sudo systemctl stop firewalld
sudo systemctl disable firewalld
sudo dnf remove firewalld
```
2. Since i was using kubespray i had to reset the config
```
source kubespray-venv/bin/activate
cd kubespray
cluster_name="cluster-01"
ansible-playbook -i ../${cluster_name}/hosts.yml \
  --user=<ur-system-user> \
  --become \
  --become-user=root reset.yml \
  --private-key ../<private.pem>
```
3. Then started with setup of the kubernetes cluster using kubespray
```
cd kubespray && \
cluster_name="cluster-01"
ansible-playbook -i ../${cluster_name}/hosts.yml \
  -e @../${cluster_name}/cluster-config.yml \
  --user=<ur-system-user> \
  --become \
  --become-user=root cluster.yml \
  --private-key ../<private.pem>
```
this time it worked perfectly

**Comment by fs2016l** [comment]
Yes, disabling the firewall can certainly work well, but what if we don't disable it?

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年05月02日 16:55 |
| 收件人 | projectcalico/calico ***@***.***> |
| 抄送人 | fs2016l ***@***.***>,
Mention ***@***.***> |
| 主题 | Re: [projectcalico/calico] k8s 1.29 使用 calicao v3.27.3 calico-kube-controllers 无法成功运行 (Issue #8770) |

I was able to get ride of the above problem with below steps

OS: RHEL 9
Kubernetes Version: 1.29.3
Automation: Kubespray

Steps to fix problem above

uninstall firewalld on VM's
sudo systemctl stop firewalld
sudo systemctl disable firewalld
sudo dnf remove firewalld

Since i was using kubespray i had to reset the config
source kubespray-venv/bin/activate
cd kubespray
cluster_name="cluster-01"
ansible-playbook -i ../${cluster_name}/hosts.yml \
  --user=<ur-system-user> \
  --become \
  --become-user=root reset.yml \
  --private-key ../<private.pem>

Then started with setup of the kubernetes cluster using kubespray
cd kubespray && \
cluster_name="cluster-01"
ansible-playbook -i ../${cluster_name}/hosts.yml \
  -e @../${cluster_name}/cluster-config.yml \
  --user=<ur-system-user> \
  --become \
  --become-user=root cluster.yml \
  --private-key ../<private.pem>


this time it worked perfectly

**Comment by tomastigera** [comment]
@fs2016l if you are blocking the traffic using another firewall, calico (or other similar products) cannot work correctly.
