### ISSUE TITLE
Calico Multiple Network Card Selection Problem

### ISSUE THREAD

**Issue by smallemployees** [projectcalico/calico#8783]
## Expected Behavior

I currently have two network segments, one using eth0 and the other using eth1, but there are also eth0 network cards present. How can I make Calico choose the correct network card
## Current Behavior

Incorrect selection of network card leads to communication failure between pods
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Calico version
v1.23.2
* Orchestrator version (e.g. kubernetes, mesos, rkt):
* Operating System and version:
* Link to your project (optional):

**Comment by coutinhop** [comment]
This would be achieved by disabling IP address autodetection and then setting each of your nodes to the IP from the interface you want it to use (e.g.: eth0 or eth1): https://docs.tigera.io/calico/latest/networking/ipam/ip-autodetection#manually-configure-ip-address-and-subnet-for-a-node
