### ISSUE TITLE
The "node-driver-registrar" binary has x86 architecture in a ppc64le Calico/node-driver-registrar image.

### ISSUE THREAD

**Issue by iv1111** [projectcalico/calico#8784]
Hello.

Our team has noticed that in the `ppc64le` version of the `Calico/node-driver-registrar:v3.27.0` image which one can pull like this: 

`docker pull --platform linux/ppc64le calico/node-driver-registrar:v3.27.0`

there is an x86 executable located inside the image filesystem under: 

`/usr/local/bin/node-driver-registrar`

which we cannot run on our `ppc64le` machine that hosts the docker installation.

This issue is related to https://github.com/projectcalico/calico/pull/7315 and note that on `s390x` architecture, the problem **persists** even though the patch in afore-mentioned PR has been merged long ago.

**Comment by iv1111** [comment]
FYI @tumberino @caseydavenport @huoqifeng

**Comment by Michael-Baylis** [comment]
The s390x problem still exists,  I have tried at v3.26.0 and v3.28.1.

exec /usr/local/bin/node-driver-registrar: exec format error

**Comment by sulaweyo** [comment]
We are running into the same issue on s390. Tried v3.29.0 as well but same output
`exec /usr/bin/node-driver-registrar: exec format error`

**Comment by caseydavenport** [comment]
Sorry for this... here's a PR to fix it: https://github.com/projectcalico/calico/pull/9594
