### ISSUE TITLE
Calico nodes failed on kubernetes cluster

### ISSUE THREAD

**Issue by ariyaee1367** [projectcalico/calico#8852]
i install kuberernetes cluster with kubespray 2.24 On the enf of installation , i have calico failed error . All cacilo nodes faied with bellow error : Here is logs for my calico node pod : 

```
kubectl logs calico-node-c68kd -n kube-system Defaulted container "calico-node" out of: calico-node, upgrade-ipam (init), install-cni (init), flexvol-driver (init) W0522 19:37:15.581786 9 feature_gate.go:241] Setting GA feature gate ServiceInternalTrafficPolicy=true. It will be removed in a future release. 
```

Calico node failed to start And also here is describe calico node pods :

Events: Type Reason Age From Message

```
Warning BackOff 14m (x8204 over 28h) kubelet Back-off restarting failed container calico-node in pod calico-node-c68kd_kube-system(428e7f55-89bc-4834-8d42-a4a4645147ad)
```

Have you any idea for resolve this issue ?

We deploy kubernetes cluster with kubespray but we have calico node pods error .

**Comment by tomastigera** [comment]
The warning about the feature gate is benign. What calico version? Do you have more logs? There is not much we can diagnose.
