### ISSUE TITLE
Failed to read from server connection=&discovery.Typha

### ISSUE THREAD

**Issue by nhattien147** [projectcalico/calico#8861]
I have a issue right below with calico-node in AKS
All the calico pod still running fine but sometimes have some issue below

**Error message:** 

```
2024-05-26 13:55:01.598 [ERROR][82] status-reporter/sync_client.go 387: Failed to read from server connection=&discovery.Typha{Addr:"10.193.224.11:5473", IP:"10.193.224.11", NodeName:(*string)(0xc00080cf20)} error=read tcp 10.193.224.16:35830->10.193.224.11:5473: i/o timeout myID=0x1 serverConnID=0x11 type="node-status"

2024-05-26 13:55:00.715 [ERROR][80] felix/sync_client.go 387: Failed to read from server connection=&discovery.Typha{Addr:"10.193.224.11:5473", IP:"10.193.224.11", NodeName:(*string)(0xc0003083e0)} error=read tcp 10.193.224.16:35844->10.193.224.11:5473: i/o timeout myID=0x1 serverConnID=0x12 type=""
```

## Your Environment

* Calico version: 3.26.3
* Orchestrator version (e.g. kubernetes, mesos, rkt): AKS
* Operating System and version: 1.29. 2

Here're the logs collect from typha pod and calico-node pod with the related IP 10.193.224.16 and 10.193.224.11:

[calico- typha ip.11.log](https://github.com/projectcalico/calico/files/15464951/calico-.typha.ip.11.log)
[calico-node ip .11.log](https://github.com/projectcalico/calico/files/15464953/calico-node.ip.11.log)
[calico- typha ip.16.log](https://github.com/projectcalico/calico/files/15464952/calico-.typha.ip.16.log)
[calico-node ip.16.log](https://github.com/projectcalico/calico/files/15464954/calico-node.ip.16.log)

**Comment by nhattien147** [comment]
@fasaxc @caseydavenport 
sorry for ping like this but i need help

**Comment by caseydavenport** [comment]
@nhattien147 Looks like a problem with calico/node being unable to talk to Typha - double check that your network meets Calico's requirements and that the necessary ports are open in the host's firewall: https://docs.tigera.io/calico/latest/getting-started/kubernetes/requirements#network-requirements

**Comment by nhattien147** [comment]
> @nhattien147 Looks like a problem with calico/node being unable to talk to Typha - double check that your network meets Calico's requirements and that the necessary ports are open in the host's firewall: https://docs.tigera.io/calico/latest/getting-started/kubernetes/requirements#network-requirements

thank for your insight, i will check and get back to you ASAP

**Comment by nhattien147** [comment]
> @nhattien147 Looks like a problem with calico/node being unable to talk to Typha - double check that your network meets Calico's requirements and that the necessary ports are open in the host's firewall: https://docs.tigera.io/calico/latest/getting-started/kubernetes/requirements#network-requirements



> @nhattien147 Looks like a problem with calico/node being unable to talk to Typha - double check that your network meets Calico's requirements and that the necessary ports are open in the host's firewall: https://docs.tigera.io/calico/latest/getting-started/kubernetes/requirements#network-requirements

@caseydavenport Hello, I forgot to mention that this issue occurs intermittently, so I don't think it's related to the firewall or network requests.

**Comment by lwr20** [comment]
> this issue occurs intermittently
Sounds like there's something wrong with the networking between your nodes?  calico-node and typha have to run in the host's network (because that's all there is before they set up the pod-network).   Calico can't help you with your node network :)

**Comment by nhattien147** [comment]
> > this issue occurs intermittently
> 
> Sounds like there's something wrong with the networking between your nodes? calico-node and typha have to run in the host's network (because that's all there is before they set up the pod-network). Calico can't help you with your node network :)

Hi @lwr20, thanks for your response, Everything is working normally even though we are not doing anything.
Not sure when the issue will happen again.

**Comment by lwr20** [comment]
Shall we close this for now then?  Since:
- we don't have a clear repro
- we don't think its a calico issue

**Comment by nhattien147** [comment]
> Shall we close this for now then? Since:
> 
> * we don't have a clear repro
> * we don't think its a calico issue

Sure
We can close right now
I will reopen if needed
