### ISSUE TITLE
calico-node pods being recreated every few seconds

### ISSUE THREAD

**Issue by maximemoreillon** [projectcalico/calico#8864]
Hello,

I am currently experiencing a strange behavior with Calico v 3.25.1 running on a 4 node Microk8s v1.30 cluster. The `calico-node` pods of each node keep being terminated and recreated after at most 30 seconds:

```
NAME                                       READY   STATUS     RESTARTS        AGE
calico-kube-controllers-749f88db4d-rctkf   1/1     Running    0               4h28m
calico-node-2fxmj                          0/1     Init:0/2   0               3s
calico-node-8p84q                          0/1     Init:0/2   0               2s
calico-node-bl6hq                          0/1     Init:1/2   0               3s
calico-node-g2gsx                          0/1     Running    0               7s
```

The nodes report network unavailability:

```
  Type                 Status  LastHeartbeatTime                 LastTransitionTime                Reason                       Message
  ----                 ------  -----------------                 ------------------                ------                       -------
  NetworkUnavailable   True    Thu, 30 May 2024 13:36:08 +0900   Thu, 30 May 2024 13:36:08 +0900   CalicoIsDown                 Calico is shutting down on this node
  MemoryPressure       False   Thu, 30 May 2024 13:33:10 +0900   Thu, 30 May 2024 02:36:59 +0900   KubeletHasSufficientMemory   kubelet has sufficient memory available
  DiskPressure         False   Thu, 30 May 2024 13:33:10 +0900   Thu, 30 May 2024 02:36:59 +0900   KubeletHasNoDiskPressure     kubelet has no disk pressure
  PIDPressure          False   Thu, 30 May 2024 13:33:10 +0900   Thu, 30 May 2024 02:36:59 +0900   KubeletHasSufficientPID      kubelet has sufficient PID available
  Ready                True    Thu, 30 May 2024 13:33:10 +0900   Thu, 30 May 2024 02:36:59 +0900   KubeletReady                 kubelet is posting ready status
```

## Expected Behavior
`calico-node` pods should be running continuously

## Current Behavior
`calico-node` pods get terminated and recreated after less than 30 seconds. The pods do not seem to error or enter a `CrashLoopBackOff` state.

Oddly enough, there does not seem to be any impact on applications running in the cluster.

Here are some logs from the pods for the the brief time they are running,:

```
2024-05-30 04:38:58.037 [INFO][76] felix/int_dataplane.go 1726: Received interface addresses update msg=&intdataplane.ifaceAddrsUpdate{Name:"calico_tmp_A", Addrs:set.Set[string](nil)}
2024-05-30 04:38:58.037 [INFO][76] felix/hostip_mgr.go 84: Interface addrs changed. update=&intdataplane.ifaceAddrsUpdate{Name:"calico_tmp_A", Addrs:set.Set[string](nil)}
2024-05-30 04:38:58.284 [INFO][76] felix/health.go 306: Overall health status changed: live=true ready=true
+---------------------------+---------+----------------+-----------------+--------+
|         COMPONENT         | TIMEOUT |    LIVENESS    |    READINESS    | DETAIL |
+---------------------------+---------+----------------+-----------------+--------+
| CalculationGraph          | 30s     | reporting live | reporting ready |        |
| FelixStartup              | 0s      | reporting live | reporting ready |        |
| InternalDataplaneMainLoop | 1m30s   | reporting live | reporting ready |        |
+---------------------------+---------+----------------+-----------------+--------+
```

```
2024-05-30 00:20:53.039 [INFO][25] tunnel-ip-allocator/node.go 99: Error updating Node resource error=Operation cannot be fulfilled on nodes "haspc": the object has been modified; please apply your changes to the latest version and try again

2024-05-30 00:20:53.039 [INFO][25] tunnel-ip-allocator/allocateip.go 686: Error updating node haspc: %!s(<nil>). Retrying. type="wireguardTunnelAddress"
```

```
2024-05-30 04:45:24.920 [INFO][31] tunnel-ip-allocator/config_params.go 647: Parsed value for FeatureDetectOverride: map[ChecksumOffloadBroken:true] (from environment variable)
2024-05-30 04:45:24.920 [INFO][31] tunnel-ip-allocator/config_params.go 611: Parsing value for DefaultEndpointToHostAction: ACCEPT (from environment variable)
2024-05-30 04:45:24.920 [INFO][31] tunnel-ip-allocator/config_params.go 647: Parsed value for DefaultEndpointToHostAction: ACCEPT (from environment variable)
2024-05-30 04:45:24.920 [INFO][31] tunnel-ip-allocator/config_params.go 611: Parsing value for IpInIpMtu: 0 (from environment variable)
2024-05-30 04:45:24.920 [INFO][31] tunnel-ip-allocator/config_params.go 647: Parsed value for IpInIpMtu: 0 (from environment variable)
2024-05-30 04:45:24.920 [INFO][31] tunnel-ip-allocator/config_params.go 611: Parsing value for Ipv6Support: false (from environment variable)
2024-05-30 04:45:24.920 [INFO][31] tunnel-ip-allocator/config_params.go 647: Parsed value for Ipv6Support: false (from environment variable)
2024-05-30 04:45:25.088 [INFO][31] tunnel-ip-allocator/allocateip.go 340: Current address is still valid, do nothing currentAddr="10.1.217.229" type="vxlanTunnelAddress"
CALICO_NETWORKING_BACKEND is vxlan - no need to run a BGP daemon
Calico node started successfully
```

I will post more as soon as I can catch something interesting

On the other hand, I don't see any error in the logs of the `calico-kube-controllers` pod

## Possible Solution

I managed to get the pods running by having each Kubernetes node leave and re-join the cluster but after a week, the problem is back.

## Unfruitful attemps

Those attempts did not succeed in solving the problem:

- restarting the calico-node daemonset
- restarting the calico-kube-controller deployment
- restarting the nodes
- updating calico as described [here](https://microk8s.io/docs/change-cidr)

## Steps to Reproduce (for bugs)
I had no such issues when using Microk8s v1.24. From there, my changes to the cluster include:

- Incremental update Microk8s v1.24 to v1.30
- Installing Longhorn v1.61
- Adding `10.1.0.0/16,10.152.183.0/24,*.svc,*.cluster.local` to the NO_PROXY environment variable for Longhorn to work
- Enabled hugepages on each node

## Your Environment

* Calico version: 3.25.1
* Orchestrator version: Microk8s v1.30 (i.e. Kuberntes v1.30) with DNS addon enabled
* Operating System and version: 4 x Ubuntu server 22.04 LTS running on physical machines

Additionally:

Kubelet configuration (`/var/snap/microk8s/current/args/kubelet`):

```
--cluster-dns=10.152.183.10
--cluster-domain=cluster.local
...
```

Kube-APIserver configuration (`/var/snap/microk8s/current/args/kube-apiserver`):

```
...
--service-cluster-ip-range=10.152.183.0/24
...
```

The cluster runs on-premise, behind a corporate proxy. Environment variables are set accordingly in `/etc/environment` of each node, as per recommended [here](https://microk8s.io/docs/install-proxy)

```
HTTP_PROXY=http://172.16.105.13:8118
HTTPS_PROXY=http://172.16.105.13:8118
NO_PROXY=localhost,127.0.0.1,172.16.98.148,172.16.98.150,172.16.99.29,172.16.106.87,november,haspc,20khaa520,24khaa344,10.1.0.0/16,10.152.183.0/24,*.svc,*.cluster.local
```

Similarily, containerd environment variables are set in `/var/snap/microk8s/current/args/containerd-env`:

```
HTTPS_PROXY=http://172.16.105.13:8118
NO_PROXY=10.1.0.0/16,10.152.183.0/24,172.16.0.0/12,127.0.0.1,localhost
```

Probably unrelated, but Longhorn v1.6.1 is installed in the cluster using Helm.

I've got a similar cluster, composed of AWS EC2s that dot not require proxy settings and have no problems there.

Is there special proxy-related configuration needed by Calico to run properly?

**Comment by maximemoreillon** [comment]
I brought one node for maintenance today for maintenance today and the `calico-node` pods started running properly.
Bringing the node back up immediately triggered the recreation cycle mentioned in this issue.
I have no idea what makes this node special for the time being and also don't know if this would happen if any other node was taken down.

**Comment by maximemoreillon** [comment]
I found a deployment whose pod had been stuck `pending` state for a couple months.
Deleting it immediately solved the problems with `calico-node` pods.
As I didn't imagine those issues to be linked, I didn't check why the aforementioned pod was in `pending` state and am now unable to recreate the issue.
For anyone experiencing the same issue, check your pods and deal with any that is in `pending` state

**Comment by CasparChou** [comment]
@maximemoreillon Thank you so much! I spent hours searching for the cause even reinstall the whole calico still not working.  just deleting the pending pod immediately resolved the issue...
