### ISSUE TITLE
calico-policy-only.yaml in cluster with existing flannel does not work from version 3.26

### ISSUE THREAD

**Issue by JosefRypacek** [projectcalico/calico#8866]
## Context
I'm trying to install Calico into Kubernetes cluster with existing Flannel overlay network and pods.
I suppose the `calico-policy-only.yaml` file is the one manifest I should use. I was successful to to setup it this way for Calico <= 3.25, but it does not work with newer versions.

Am I doing something wrong? Should I use different manifest or is there a bug?

## Expected Behavior
It should work.

## Current Behavior
Calico pods, DNS pods and other pods on flannel network does not have network access.
Below is one error message from events.
```
kube-system                      8m39s                    Warning   FailedCreatePodSandBox    Pod/kube-dns-autoscaler-568cfc9fc5-tmsl5                          
Failed to create pod sandbox: rpc error: code = Unknown desc = failed to create pod network sandbox k8s_kube-dns-autoscaler-568cfc9fc5-tmsl5_kube-system_6285919b-c434-4ced-be73-f23e6cb14e33_0(b0e3a8aaa54fbec7c434847ac80eed1611bc216446ddbc14916a901c957b5017): 
error adding pod kube-system_kube-dns-autoscaler-568cfc9fc5-tmsl5 to CNI network "k8s-pod-network": plugin type="calico" failed (add): error getting ClusterInformation: connection is unauthorized: clusterinformations.crd.projectcalico.org "default" is forbidden: User "system:serviceaccount:kube-system:calico-cni-plugin" cannot get resource "clusterinformations" in API group "crd.projectcalico.org" at the cluster scope
```

I verified RBAC are set correctly.
```
kubectl auth can-i create serviceaccounts/calico-cni-plugin -n kube-system --subresource token --as "system:serviceaccount:kube-system:calico-node"
yes
```

I've just found that if I add some additonal changes from [this PR](https://github.com/projectcalico/calico/pull/7106/files#diff-a13e3dc70d98c53fce0f3a76fa93787186a8d68d182bc2ae231f45afd5d6b365) to the `calico-policy-only.yaml` file, I'm able to make my setup work.

To make it work I had to add following. It seems that I had to modify both ClusterRoles, but not sure which resources / verbs are actually required.
```
### add into calico-node ClusterRole
- calico-node

### add into calico-cni-plugin ClusterRole
  - apiGroups: ["crd.projectcalico.org"]
    resources:
      - blockaffinities
      - ipamblocks
      - ipamhandles
      - clusterinformations
      - ippools
      - ipreservations
      - ipamconfigs
    verbs:
      - get
      - list
      - create
      - update
      - delete
```

## Your Environment
* Calico version 3.26.4 and 3.27.3
* Kubernetes version 1.27.10

**Comment by MichalFupso** [comment]
Hi @JosefRypacek , 
Do you have any special purpose for using flannel for networking, calico comes with native networking without the need to use flannel. You can see what networking option would suit you best in our [documentation](https://docs.tigera.io/calico/latest/networking/determine-best-networking) as well as [migration guide](https://docs.tigera.io/calico/latest/getting-started/kubernetes/flannel/migration-from-flannel) from flannel to calico 

For using calico policy only mode with flannel, it is not possible to install calico on a cluster that already has flannel installed. We provide a way to install flannel as well as calico in policy only mode in one manifest. Please see [docs](https://docs.tigera.io/calico/latest/getting-started/kubernetes/flannel/install-for-flannel) for more details

**Comment by JosefRypacek** [comment]
Thanks, I've seen other networking options and recommendation, but I'm trying to use OCI cloud - OKE Kubernetes cluster which comes with Flannel networking out of the box. I may investigate other options, but as `calico-policy-only.yaml` worked in version <= 3.25, I would like to keep this way for now.

I actually followed this OCI documentation: https://docs.oracle.com/en-us/iaas/Content/ContEng/Tasks/contengsettingupcalico.htm#manualcalicoinstall

After my modification to `ClusterRole`s it works as expected. I can probably also use `canal.yaml` file and remove flannel pods from there, but I thought `calico-policy-only.yaml` is the better way.

**Can you please recommend which way is better (or less bad) to install Calico for policy only into Cluster with existing Flannel overlay network and pods?**

**Comment by aaaaaaaalex** [comment]
Hiya @JosefRypacek,

Thanks for the extra info. 

So, while it sounds like Oracle has configured Flannel in this scenario to be compatible with Calico, keep in mind that we haven't tested it nor do we support OCI officially, so we can't confidently advocate its use, or make any guarantees that everything is working as intended. For further support in this configuration, you would need to ask Oracle support.

Officially, we can currently only advocate the use of Flannel+Calico as shown in the docs and `canal.yaml` file.
The YAML shown on Oracle docs, on the other hand, was not originally intended for use on that stack, and has not been used in our installation docs for a few years now.

Right now I believe we do not have any official method for installing policy-only Calico on a cluster with a pre-existing Flannel overlay. Part of the reason for this is that some configurations of Flannel are completely incompatible with how Calico enforces policy, e.g, Flannel bridges break Calico policy between pods on the same node.

**Comment by JosefRypacek** [comment]
Thanks for the info. I'll keep it in mind and be sure to test compatibility and required features until there is some better way.

I have compared `canal.yaml` and `calico-policy-only.yaml` and have one more question. 
**Is there any benefit using Typha for Canal (Calico for policies and Flannel for networking) in this configuration?** I read the documentation related to workload and number of nodes, but it's not obvious how much it's important when not using Calico networking. I was a little bit surprised when I saw Typha enabled in `calico-policy-only.yaml`.

**Comment by mazdakn** [comment]
Using Typha is also beneficial in policy mode as well. Typha proxies node's accesses to API servers, and helps with scalability of a cluster. Even in policy mode, Calico nodes need to process many updates about workloads, policies, etc. 

In the end, it's up to users to enable or disable Typha. However, we recommend using it.
