### ISSUE TITLE
Cannot get ip on stage ContainerCreating，with stage Entrypoint in Dockerfile

### ISSUE THREAD

**Issue by hailong226** [projectcalico/calico#887]

**Comment by tmjd** [comment]
It would help if you filled in the information requested in the "New Issue" template that is provided when creating an issue.  Please fill in as much information as you can from the template in your next message (you can see the template by selecting "New Issue" and copying the template).

I am guessing that you are attempting to start a pod and it is unable to get an IP on Kubernetes.
You should check the kubelet logs to see if there is a CNI error.  You should also check the logs from calico-node and calico-policy-controller to ensure they are operating as expected.

With the information you provide by filling in the template and information you find in the logs it should help us identify your issue.
