### ISSUE TITLE
External IP is taken as InternalIP

### ISSUE THREAD

**Issue by melardev** [projectcalico/calico#8873]
## Expected Behavior
An external IP should not be an `InternalIP`.

## Current Behavior
Calico assigned an internal `10.108.0.11` as CalicoNodeIP, and an external IP `142.250.200.142` as InternalIP.
![image](https://github.com/projectcalico/calico/assets/18094815/e9b8c194-6588-4055-870d-8710c2a6962d)

## Possible Solution
Add IP logic to parse IPs, private IPs have specific reserved ranges, anything that falls in it like `10.108...` is private IP, and anything that
falls outside is an external IP.

## Steps to Reproduce (for bugs)
It is hard to reproduce. My cluster contains nodes in Hetzner and DigitalOcean.

The nodes in Hetzner are correctly parsed, the nodes in DigitalOcean are not.
Example Node in Hetzner:
![image](https://github.com/projectcalico/calico/assets/18094815/4ebdc52f-977b-435b-a948-3d27b6d0566f)

Example Node in DigitalOcean:
![image](https://github.com/projectcalico/calico/assets/18094815/29918da7-1e08-47fe-8fd6-930fd176e713)

## Context
This was a big issue for me, because that `CalicoNodeIP` (so the internal IP) was used for BGP KEEPALIVE packets being sent from my other nodes, but that internal IP is unreachable because other nodes are in a different LAN network and so the packets failed and triggered many network errors and there was also network flood (probably it sends more probes when they fail?) . Because of this my cloud provider ended up blocking my server completely.

If they were using the right address (the external one) BGP would have succeded and from what I see in a Wireshark capture, they are less intrusive.

## Your Environment
Calico v3.26.3
Linux Machines

**Comment by caseydavenport** [comment]
Calico isn't responsible for detecting IP addresses of type `InternalIP` or `ExternalIP` - those are pulled directly from the Kubernetes node objects, so I suspect this issue isn't really Calico related. 

The CalicoNodeIP is the only one that is set by Calico itself, and can be controlled according to these docs: https://docs.tigera.io/calico-cloud/networking/ipam/ip-autodetection#big-picture

**Comment by matthewdupre** [comment]
@melardev Did you try using the autodetection settings to control the CalicoNodeIP?
