### ISSUE TITLE
Cluster install guide - what does "install on your cluster" mean?

### ISSUE THREAD

**Issue by suityou01** [projectcalico/calico#8877]
In the installation guide for a cluster the following text is given

1. Install the operator on your cluster. See [here](https://docs.tigera.io/calico/latest/getting-started/kubernetes/self-managed-onprem/onpremises#install-calico) 

I have a 2 node cluster running in RPi. Should I run this command on just the control plane node, or each node in the custer?

Please advise.

**Comment by aaaaaaaalex** [comment]
You should only need to run the command once, as `apply` just applies the given _resource_ to the k8s datastore, which is the same for the whole cluster. It can be done from any node or machine with a valid kubeconfig file which points to your cluster's K8s API :)
