### ISSUE TITLE
Document host protection + IPIP

### ISSUE THREAD

**Issue by fasaxc** [projectcalico/calico#888]
If you're using host protection with IPIP for workloads, you need to adjust the policy to allow IPIP packets.  We should document that somewhere.

In general, it'd be good to have a worked example of setting up host protection with k8s, say.

**Comment by tmjd** [comment]
There is now the k8s worked example on the Host Protection Overview page.  It does not specifically call out the policy needed to allow IPIP, do we need that? if so I think probably just a note to that page would satisfy this issue.

**Comment by ozdanborne** [comment]
ping @fasaxc would you be comfortable closing out this issue if we added a note on enabling IPIP to this doc? https://docs.projectcalico.org/master/getting-started/bare-metal/bare-metal

Can you clarify what the IPIP rule is supposed to apply to (all workloads? Only hostendpoints?)

**Comment by fasaxc** [comment]
Agree, note on that page sounds like the way to go.

**Comment by ozdanborne** [comment]
@fasaxc can you make this adjustment yourself, or clarify what the IPIP rule is supposed to look so that @emanic can resolve it?
