### ISSUE TITLE
eBPF not issuing TCP RST on unknown connections

### ISSUE THREAD

**Issue by sfudeus** [projectcalico/calico#8882]
## Expected Behavior

When a node receives a packet for an unknown TCP connection on the host IP or to a closed port, it should by default reject that connection by issuing a packet with the TCP RST bit set. There may be situations where it should be silently dropped, in default it should behave transparently. 

This behaviour should be identical between the eBPF mode and the iptables mode.

## Current Behavior

When sending a TCP packet to a port on the hostIP of a node running calico on eBPF mode, for unknown connections, there is no reply sent, the packet is silently dropped and the client will resume retries until timeout. This happens both for unknown connections against closed ports and open ports. New connections against closed ports are properly rejected.

When sending such an unknown TCP packet to a node running calico on iptables mode, there is an immediate TCP RST packet and the client can immediately terminate (and potentially reestablish a connection). 

## Possible Solution

Even in eBPF mode, a packet with RST bit set should be sent for any connection not in conntrack. 

## Steps to Reproduce (for bugs)

* Send a TCP packet without proper prior handshake to a nodeIP of a node which is eBPF enabled, regardless if the port is open or not. 
* Observe that you won't get a reply. 

Trivial python script to trigger this:
```
#!/usr/bin/env python3

from scapy.all import *
import argparse

def main():
    parser = argparse.ArgumentParser("rst-test")
    parser.add_argument("dest_host", help="the destination host to test against")
    parser.add_argument("dest_port", help="the destination port to test against", type=int)
    args = parser.parse_args()

    packet = IP(dst=args.dest_host) / TCP(sport=13337, dport=args.dest_port, seq=1337, ack=1336, flags="PA") / Raw(load="test")

    response = sr1(packet, timeout=10)

    if response:
        if response.haslayer(TCP) and response.getlayer(TCP).flags & 0x04:
            print("Received RST packet")
        else:
            print("Did not receive RST packet")
    else:
        print("No response received")

if __name__ == "__main__":
    main()
```

## Context

We are running the apiservers on an anycast IP in the hostNetwork, announced via BGP. When one master node goes down and withdraws its announcement, ECMP routing will route the traffic to a remaining control plane node. With that, such a remaining node will see traffic for unknown TCP connections, right after the ECMP change. 

In our case, on eBPF-enabled clusters, kubelets' connections to the apiserver start to hang until a timeout is reached, partially causing nodes to be ejected as not-ready anymore. We identified that this happens because the kubelet don't notice that their connection to the apiserver broke, they keep on resending packets, because they never see a TCP reset. 

On the non-eBPF clusters, this scenario is not an issue at all. After the ECMP change, kubelet will see a TCP reset, and establish a new TCP connection immediately. 

## Remarks 

This might be related to #8854 or at least affected by a fix for this. From the user perspective, it is a different thing. 

## Your Environment
* Calico version 3.27.4/3.28.0
* Orchestrator version (e.g. kubernetes, mesos, rkt): kubernetes v1.28.9
* Operating System and version: FlatCar beta 3874.1.0 with kernel 6.6.21-flatcar

**Comment by tomastigera** [comment]
Yeah, this is a known issue for many years :crying_cat_face: It wasn't addressed yet as with nodeports, the idea is that the node itself will respond - seems like that does not work for you. With other services advertised via bgp, that does not work and it is related to https://github.com/projectcalico/calico/issues/5039. Also the #8854 might be at play. Let's say we will prioritize the work higher.

**Comment by tomastigera** [comment]
We do issue ICMP error when there is a service but that service does not have a backend.

**Comment by tomastigera** [comment]
Relates to https://github.com/projectcalico/calico/issues/7983 I am not even sure iptables mode (vanilla k8s would respond with RST - hence I treat it as kind/Enhancement)

**Comment by sfudeus** [comment]
An additional factor here is that I wouldn't even expect eBPF to interfere here, since we are plainly working with hostIP, not pods or calico interfaces involved at all. It is pure host2host communication, with IP addresses not managed via calico or K8s. And, as mentioned, in non-ebpf mode, it behaves as expected.

**Comment by tomastigera** [comment]
Well calico ebpf interferes on any host device that is included in the dataiface regexp. But my expectation would be that node IPs would just work :thinking: Would you see any conntracks in Linux or dropped packets in ebpf counters etc?

**Comment by sfudeus** [comment]
All ebpf drop counters stay 0. And I didn't see anything special in conntrack. 
But I digged a bit into the iptables rules. 

In a cluster without eBPF, as far as I understand we pass 
INPUT->cali-INPUT->cali-from-host-endpoint->cali-fh-any-interface-at-all->cali-failsafe-in
and at least for this, we have a failsafe rule which causes the accept (end then ending in a reset because there is no connection). 

In the eBPF case, we see directly the following in the INPUT chain: 
  373 49106 DROP       all  --  *      *       0.0.0.0/0            0.0.0.0/0            /* cali:XQL0mC-L6wldZdgN */ /* Drop packets from unknown flows. */ mark match 0x5000000/0x5000000
  
Observing the counter, this triggers for my unrelated packet and causes the drop. So this at least should be the reason for the differing behaviour. Anything we can do about this?

**Comment by tomastigera** [comment]
@sfudeus great investigation. Interestingly, this rule should be only hit by when (a) we see a mid-flow TCP packet for which we do not have a conntrack entry in ebpf  (the connection predates enabling ebpf) and (b) linux does not have an entry for an existing flow neither - so it may be some spoofed packet and thus it should be dropped. :thinking: I will try to investigate.

**Comment by sfudeus** [comment]
@tomastigera that does fit, because in my scenario we do have such a mid-flow packet, because it was rerouted due to ECMP when 1 potential (and original) destination was removed. I understand the concern about spoofing, but I'd say there only is a risk if such a packet would break an existing connection state. In this case, it would only be about "revealing" that no matching connections exists. And that response would be sent to the "original" IP, not the spoofer. And not sure inhowfar this would require sequence numbers to match sufficiently. 
And, at least in my case, now sure how generic this is: If someone would be able to inject an invalid packet into the hostNetwork at this level, we'd have a problem anyway. A spoofed packet from outside should have been rejected with invalid source IP already before being routed into that network.

**Comment by tomastigera** [comment]
Hmmm it is an interesting one. I agree. Let me think about how to achieve the desired behaviour.

I think we just need to pass these packets through policy anyway and not just rely on iptables and conntrack. Because when contrack exists, we know that it was allowed, to we let it through. But if conntrack does not exist, it is already too late to police the packet and thus we need to drop it. The question is what to do with such a packet if it would be now denied by policy but iptables conntrack exists. I think it is fine to deny, however, at the startup (switch from iptables to ebpf) we could break existing connections and that is what we do not want to in the first place. And we cannot quite just send RST from ebpf because what if there was a conntrack in the kernel! With newer kernels, we could query linux conntrack. Or we may just allow the packet and mark it with "drop it if conntrack does not exist because denied by policy" :thinking: @fasaxc WDYT?

**Comment by tomastigera** [comment]
@sfudeus could you try this image if it would work for you? `thruby/node:3-28-tcp-reject-1`

**Comment by sfudeus** [comment]
calico-node didn't come up ready on 3 of 8 nodes with internal dataplane main loop timeout:
```
│ calico-node 2024-06-25 13:47:17.147 [INFO][53] felix/health.go 336: Overall health status changed: live=false ready=false                                                                                                                                                                                                │
│ calico-node +---------------------------+---------+----------------+-----------------+--------+                                                                                                                                                                                                                          │
│ calico-node |         COMPONENT         | TIMEOUT |    LIVENESS    |    READINESS    | DETAIL |                                                                                                                                                                                                                          │
│ calico-node +---------------------------+---------+----------------+-----------------+--------+                                                                                                                                                                                                                          │
│ calico-node | BPFEndpointManager        | -       | -              | reporting ready |        |                                                                                                                                                                                                                          │
│ calico-node | CalculationGraph          | 30s     | reporting live | reporting ready |        |                                                                                                                                                                                                                          │
│ calico-node | FelixStartup              | -       | reporting live | reporting ready |        |                                                                                                                                                                                                                          │
│ calico-node | InternalDataplaneMainLoop | 1m30s   | timed out      | timed out       |        |                                                                                                                                                                                                                          │
│ calico-node +---------------------------+---------+----------------+-----------------+--------+                                                                                                                                                                                                                          │
│ calico-node 2024-06-25 13:47:17.149 [WARNING][53] felix/health.go 286: Reporter is not live: timed out. name="InternalDataplaneMainLoop"                                                                                                                                                                                 │
│ calico-node 2024-06-25 13:47:17.149 [INFO][53] felix/health.go 294: Reporter is not ready: timed out. name="InternalDataplaneMainLoop"                                                                                                                                                                                   │
│ calico-node 2024-06-25 13:47:27.122 [WARNING][53] felix/health.go 286: Reporter is not live: timed out. name="InternalDataplaneMainLoop"                                                                                                                                                                                 │
│ calico-node 2024-06-25 13:47:27.122 [INFO][53] felix/health.go 294: Reporter is not ready: timed out. name="InternalDataplaneMainLoop"                                                                                                                                                                                   │
│ calico-node 2024-06-25 13:47:27.128 [WARNING][53] felix/health.go 286: Reporter is not live: timed out. name="InternalDataplaneMainLoop"                                                                                                                                                                                 │

```

With loglevel set to info, nothing special visible in the logs AFAICS. 

Initially, it is reporting live, but not ready. Later, it is reporting timeouts for both liveness and readiness (as in the excerpt above). I could not identify a pattern which hosts would come up and which not. 

But regarding the original issue: All 3 masters came up fine with the new calico-node and I properly received my tcp-rst when sending out-of-line packets. So it seems this might be solved.

**Comment by fasaxc** [comment]
@sfudeus what's the load like on your hosts?  Do they have a lot of pods, is CPU maxed out?  (That timeout suggests either a concurrency bug and Felix has locked up, or your nodes have a very high workload and Felix is struggling.)

**Comment by sfudeus** [comment]
@fasaxc nodes were only minimally loaded. This was on a bare metal sandbox cluster without real load. Theoretically there could have been CPU throttling on pod-level because of CPU limits involved, but I don't remember seeing anything specifically there. I can retry and report back if there is something.

**Comment by tomastigera** [comment]
This is a newer image `thruby/node:3-28-tcp-reject-2` that came up well for me. Hard to say with the log excerpt anything beyond that there is a loop timeout indeed.

**Comment by sfudeus** [comment]
As discussed in Slack, it came up good in a cluster after reboot and now even in the other cluster where I originally had seen issues. Strange, since these cluster get rebooted roughly once a week anyway. 
For now, I cannot reproduce any issues with `thruby/node:3-28-tcp-reject-2`. It ran well in a cluster over the weekend and I upgraded one from 3.28.0 again this morning and observed no readiness issues. 
And I still can confirm that the original issue is fixed for me with this as well.
