### ISSUE TITLE
Helm chart does not have proper updates from operator repo for operator types

### ISSUE THREAD

**Issue by tmjd** [projectcalico/calico#8883]
## Expected Behavior

The helm chart and manifest should have updates pulled from the [operator repo](https://github.com/tigera/operator/) before each release.

## Current Behavior

Master and Calico v3.28 are not updated with the proper definitions for the operator types. A specific example looking at the v3.28 release, is `csi-node-driver` is the [only allowed container name for the csiNodeDriverDaemonSet](https://github.com/projectcalico/calico/blob/release-v3.28/charts/tigera-operator/crds/operator.tigera.io_installations_crd.yaml#L6869) but `csi-node-driver-registrar` and `csi-node-driver` should also be allowed (based on the [CRD in the operator repo](https://github.com/tigera/operator/blob/release-v1.34/pkg/crds/operator/operator.tigera.io_installations.yaml#L5526)). See https://github.com/tigera/operator/issues/3356 for context.

## Possible Solution

Ensure the release process properly pulls in updates from the operator repo before creating new releases. It will also be good to pull in updates to the master branch periodically or anytime creating new releases.

## Steps to Reproduce (for bugs)

This is an issue with getting the manifests/helm chart updated properly for releases, so no steps necessary to reproduce.

## Context

https://github.com/tigera/operator/issues/3356

## Your Environment

Not Applicable

**Comment by mashiofu-cafex** [comment]
Originated from https://github.com/projectcalico/calico/issues/8853 which is now closed to monitor this issue

**Comment by muckelba** [comment]
We've stumbled across the same problem. I've tried to use the original yaml from the operator repo, but that's not perfect yaml:
```sh
kubectl apply --server-side --force-conflicts -f https://github.com/tigera/operator/blob/master/pkg/crds/operator/operator.tigera.io_installations.yaml
error: error parsing https://github.com/tigera/operator/blob/master/pkg/crds/operator/operator.tigera.io_installations.yaml: error converting YAML to JSON: yaml: line 212: mapping values are not allowed in this context
```

**Comment by TomBillietKlarrio** [comment]
Any updates on this? Just stumbled upon it too.

**Comment by mashiofu-cafex** [comment]
Any update on this effort?

**Comment by caseydavenport** [comment]
There's a makefile helper to do this: https://github.com/projectcalico/calico/blob/bb0c3b99e9b746c7e93fd7c7cc468c6eb494dd46/Makefile#L65-L70

This PR will add a CI check for it: https://github.com/projectcalico/calico/pull/9377
