### ISSUE TITLE
Unauthorised logo error

### ISSUE THREAD

**Issue by ForcemCS** [projectcalico/calico#8903]
I'm using helm to deploy consul and I'm getting the following message,I'm not sure if this is a problem with the web plugin (calico) or something else,If it's a problem with the web plugin, what should I do to fix it
```
Warning  FailedCreatePodSandBox  9m8s (x546 over 18m)  kubelet            (combined from similar events): Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "bbb2fb13957bed5e7ea18e921ed670d5a6ebd534242211f2bf3e90ff9d8576a8": plugin type="consul-cni" name="consul-cni" failed (add): error retrieving pod: Unauthorized
```

**Comment by caseydavenport** [comment]
@ForcemCS please see this (recently closed) issue. In particular, this comment: https://github.com/projectcalico/calico/issues/8368#issuecomment-2120873448

It outlines a few debugging steps and actions to take if seeing this error.
