### ISSUE TITLE
eBPF dataplane problem with link aggregation (bond)

### ISSUE THREAD

**Issue by pedrocrc** [projectcalico/calico#8917]
## Expected Behavior

After activating eBPF dataplane, all communications are ok

## Current Behavior

After activating eBPF dataplane, the pods deployed on some nodes can't communicate with services (Cluster IPs). The problem was detected to happen on nodes whose network is based on link aggregation.

## Steps to Reproduce (for bugs)

1. Enable eBPF dataplane by disabling kube-proxy and patching Tigera installation, and enabling DSR.

## Context

I've enabled the eBPF dataplane on my staging environment successfully. However, when doing so on my production environment, this problem happened. My staging environment consists only of virtual machines that act as nodes, but my production environment has both VMs and bare-metal nodes. The problem only happened at the bare-metal nodes.

All the nodes (VMs and bare-metal) have Ubuntu 22.04 LTS OS installed, and their network were configured through Netplan.

The bare-metal nodes are physical servers, and each of them have 2 NICs that are teamed together with a link aggregation. The Netplan configuration of the bare-metal nodes is as follows (not working):
```yaml
# This is the network config written by 'subiquity'
network:
  ethernets:
    eno1: {}
    eno2: {}
  version: 2
  bonds:
    bond0:
      interfaces:
      - eno1
      - eno2
      parameters:
        lacp-rate: slow
        mode: 802.3ad
        transmit-hash-policy: layer2
      addresses:
      - #ommited
      nameservers:
        addresses:
        - #ommited
        - #ommited
        search:
        - #ommited
      routes:
      - to: default
        via: #ommited
```

Before enabling eBPF dataplane, I had been using calico with IPTables and kube-proxy, and all worked well. The problem started at the moment I enabled the eBPF dataplane.

After that, I've changed the configuration of the bare-metal servers to only use one interface, and all worked well. So I'm sure that the problem is some incompatibility of eBPF dataplane and the link aggregation. Configuration after changing that (working):
```yaml
network:
  ethernets:
    eno1: {}
    eno2:
      addresses:
      - #ommited
      nameservers:
        addresses:
        - #ommited
        - #ommited
        search:
        - #ommited
      routes:
      - to: default
        via: #ommited
```

Important facts:
* my environment doesn't have NAT Outgoing, because I use BGP peering with my switches
* the only change that made the communication fail or not was implementing eBPF dataplane at the bare-metal nodes when using link aggregation. Link aggregation works well with calico and IPTables, and eBPF works well without link aggregation
* because I only have bare-metal at my production environment, I'm not able to conduct much testing at this environment

Calico installation:
```yaml
apiVersion: operator.tigera.io/v1
kind: Installation
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: #ommited
  creationTimestamp: #ommited
  finalizers:
  - tigera.io/operator-cleanup
  - operator.tigera.io/installation-controller
  generation: #ommited
  name: default
  resourceVersion: #ommited
  uid: #ommited
spec:
  calicoNetwork:
    bgp: Enabled
    hostPorts: Disabled
    ipPools:
    - allowedUses:
      - Workload
      - Tunnel
      blockSize: #ommited
      cidr: #ommited
      disableBGPExport: false
      encapsulation: None
      name: default-ipv4-ippool
      natOutgoing: Disabled
      nodeSelector: all()
    linuxDataplane: BPF
    linuxPolicySetupTimeoutSeconds: 0
    mtu: 0
    multiInterfaceMode: None
    nodeAddressAutodetectionV4:
      interface: #ommited
    windowsDataplane: Disabled
  cni:
    ipam:
      type: Calico
    type: Calico
  componentResources:
  - componentName: Node
    resourceRequirements:
      requests:
        cpu: 250m
  controlPlaneReplicas: 2
  flexVolumePath: None
  kubeletVolumePluginPath: /var/lib/kubelet
  logging:
    cni:
      logFileMaxAgeDays: 30
      logFileMaxCount: 10
      logFileMaxSize: 100Mi
      logSeverity: Info
  nodeUpdateStrategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
  nonPrivileged: Disabled
  typhaMetricsPort: 9093
  variant: Calico
```

Felix configuration:
```yaml
apiVersion: crd.projectcalico.org/v1
kind: FelixConfiguration
metadata:
  annotations:
    operator.tigera.io/bpfEnabled: "true"
    projectcalico.org/metadata: #ommited
  creationTimestamp: #ommited
  generation: #ommited
  name: default
  resourceVersion: #ommited
  uid: #ommited
spec:
  bpfConnectTimeLoadBalancing: TCP
  bpfEnabled: true
  bpfExternalServiceMode: DSR
  bpfHostNetworkedNATWithoutCTLB: Enabled
  bpfLogLevel: ""
  floatingIPs: Disabled
  healthPort: 9099
  logSeverityScreen: Info
  policySyncPathPrefix: /var/run/nodeagent
  prometheusMetricsEnabled: true
  reportingInterval: 0s
  vxlanVNI: 4096
```

## Your Environment

* Calico version: 3.28
* Orchestrator version (e.g. kubernetes, mesos, rkt): Kubernetes 1.28.9
* Operating System and version: Ubuntu 22.04 LTS

**Comment by tomastigera** [comment]
Hey @pedrocrc there is a few ways how to handle that.

1. you can remove enoX from `bpfDataIfacePattern` in `felixconfiguratio` and replace it with `bond0`  https://docs.tigera.io/calico/latest/reference/resources/felixconfig
2. you may also just try to set `bpfEnforceRPF` to `Loose` as that test is most likely failing since the programs are attached to enoX instead of bond0
3. [This](https://github.com/projectcalico/calico/pull/8914) should fix the issue for you and we would appreciate if you tested it. It should go out in the next 3.28 path release, but you can try image `calico/node:release-v3.28` which carries that change.

Pls let us know if any of these worked for you.

**Comment by pedrocrc** [comment]
Hello @tomastigera 
Thanks for the help.
I've included the following configuration at my FelixConfiguration, and it worked:
```yaml
bpfDataIfacePattern: >-
    ^((en|wl|ww|sl|ib)[Popsx].*|(eth|wlan|wwan|bond).*|tunl0$|vxlan.calico$|vxlan-v6.calico$|wireguard.cali$|wg-v6.cali$)
```

I've got this regex from https://github.com/sridhartigera/calico/blob/de4ba77dd49ccbb11ad01fb6dbc085987723b21b/felix/config/config_params.go#L182
