### ISSUE TITLE
error="open /host/opt/cni/bin/portmap: text file busy" 

### ISSUE THREAD

**Issue by geotransformer** [projectcalico/calico#8932]
## Expected Behavior

Calico pod should be able to up and running

## Steps to Reproduce (for bugs)

1.  Upgrade the system os 
2. root partition switch over, and install the kubernetes with backup etcd on the new root partition
3. Install kubeadm and run kubeadm init with existing etcd
4. Calico pod crash loop

## Context

master-1:~$ kubectl logs calico-node-pvc2n -n kube-system -c install-cni -p
time="2024-06-20T07:51:02Z" level=info msg="Running as a Kubernetes pod" source="install.go:140"
time="2024-06-20T07:51:02Z" level=info msg="Installed /host/opt/cni/bin/bandwidth"
time="2024-06-20T07:51:02Z" level=info msg="Installed /host/opt/cni/bin/calico"
time="2024-06-20T07:51:02Z" level=info msg="Installed /host/opt/cni/bin/calico-ipam"
time="2024-06-20T07:51:02Z" level=info msg="Installed /host/opt/cni/bin/flannel"
time="2024-06-20T07:51:02Z" level=info msg="Installed /host/opt/cni/bin/host-local"
time="2024-06-20T07:51:02Z" level=info msg="Installed /host/opt/cni/bin/install"
time="2024-06-20T07:51:02Z" level=info msg="Installed /host/opt/cni/bin/loopback"
time="2024-06-20T07:51:02Z" level=error msg="Failed to install /host/opt/cni/bin/portmap" error="open /host/opt/cni/bin/portmap: text file busy" 

## Your Environment

* Calico version 3.24
* Orchestrator version (e.g. kubernetes, mesos, rkt): Kubernetes
* Operating System and version:Ubuntu 20.04
* Link to your project (optional):

**Comment by coutinhop** [comment]
> `error="open /host/opt/cni/bin/portmap: text file busy"`

@geotransformer could you run `lsof /opt/cni/bin/portmap` on your **host** to check what's preventing that file from being overwritten by the `install-cni` initContainer?

**Comment by sridhartigera** [comment]
@geotransformer Closing this issue. Feel free to reopen if you have more information.
