### ISSUE TITLE
kube-controllers: pprof is enabled on /metrics server port.

### ISSUE THREAD

**Issue by xinfengliu** [projectcalico/calico#8936]
In `kube-controllers/cmd/kube-controllers/main.go`, there's an import `_ "net/http/pprof"`, this causes `/debug/pprof` emerges in any started http server such as server for serving  `/metrics` (default at port 9094) even if `DebugProfilePort` is not set.

## Expected Behavior

`/debug/pprof` is not enabled on Calico `kube-controllers`'s `/metrics` server port
## Current Behavior

`/debug/pprof` is enabled on Calico `kube-controllers`'s `/metrics` server port 

## Possible Solution

Not sure if `import _ "net/http/pprof"` is necessary, I see currently if `DebugProfilePort` is not zero, `github.com/pkg/profile` is used to write profile data to local disk.

## Steps to Reproduce (for bugs)

1. Deploy Calico and `/metrics` is enabled in `kube-controllers`  (this is default).
2. Access `http://<calico-kube-controllers IP>:9094/debug/pprof`

## Context

Exposing `pprof` by default outside the host OS is considered a security issue by organizations which have high security requirements. 

## Your Environment

* Calico version v3.27.0
* Orchestrator version (e.g. kubernetes, mesos, rkt): kubernetes
* Operating System and version: Rocky Linux 8.6
* Link to your project (optional):

**Comment by caseydavenport** [comment]
Thanks @xinfengliu - should be fixed by this PR: https://github.com/projectcalico/calico/pull/8967
