### ISSUE TITLE
EtcdClusterIdChanged should be a warning, not a traceback

### ISSUE THREAD

**Issue by nbartos** [projectcalico/calico#896]
Currently when the etcd cluster id changes, there's a traceback as such:

```
Nov 13 03:52:55.383873 10.20.0.21 err calico-felix[4245]: client@791 Unexpected request failure, re-raising.
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/etcd/client.py", line 765, in api_execute
  File "/usr/lib64/python2.7/site-packages/etcd/client.py", line 817, in _check_cluster_id
EtcdClusterIdChanged: The UUID of the cluster changed from 2d286babfee3aa0 to 6e35ac9bbec4972.
```

To me it doesn't feel like this should require a trace, just a regular warning log message.

**Comment by fasaxc** [comment]
Sounds reasonable.

That said, I think you're the only person who thinks it's normal to nuke their etcd cluster every 5 minutes ;-)

**Comment by nbartos** [comment]
Perhaps, but I stand by my assertion that Tracebacks should only be for coding errors or things that actually require a trace for debugging.

**Comment by fasaxc** [comment]
That exception is logged by python-etcd, not by felix.  @nbartos Please can you raise upstream?

Agree there should just be a special-case for that expected exception.

**Comment by nbartos** [comment]
Upstream pull created:  https://github.com/jplana/python-etcd/pull/144
