### ISSUE TITLE
STs seem to be broken on newer docker releases

### ISSUE THREAD

**Issue by fasaxc** [projectcalico/calico#896]
I tried to run `cd calico_node; make st` on my dev machine.  I see errors in the console from docker.

## Expected Behavior
Clean ST run.

## Current Behavior
```
docker exec -it host1 sh -c 'docker network create --driver calico --ipam-driver calico-ipam  testnet1'
  # Return code: 1
  # Error response from daemon: legacy plugin: plugin not found
  # 
```
## Possible Solution

Looks like a change to the docker API has broken the STs?

## Steps to Reproduce (for bugs)

1. `cd calico_node`
2. `make st ST_TO_RUN=tests/st/policy/test_profile.py`

## Context
This is blocking development of STs for the feature I'm working on.

## Your Environment

* Calico version: master de0528c845e75998a02ff00923592f63819c5fbf
* Orchestrator version (e.g. kubernetes, mesos, rkt):

```
$ docker version
Client:
 Version:      17.05.0-ce
 API version:  1.29
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:10:54 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.05.0-ce
 API version:  1.29 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:10:54 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

* Operating System and version: 
Ubuntu 16.04
```
$ uname -a 
Linux smc-ubuntu 4.4.0-78-generic #99-Ubuntu SMP Thu Apr 27 15:29:09 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```
* Link to your project (optional):

**Comment by ozdanborne** [comment]
@fasaxc do you recall if this is still an issue?

**Comment by fasaxc** [comment]
ISTR that others didn't have he same problem
