### ISSUE TITLE
How to manually import calico images to local

### ISSUE THREAD

**Issue by huanghaiqing1** [projectcalico/calico#8978]
My site can't use docker pull to get calico images to local(Rocky os 8 latest) by internet for setup k8s. Here I download the full package: release-v3.28.0.tgz to local and try pull these images to local and make tag for configure network of k8s. Is there any related  README about how to import these images?

Events:
  Type     Reason          Age                   From     Message
  ----     ------          ----                  ----     -------
  Normal   BackOff         90m (x1514 over 17h)  kubelet  Back-off pulling image "docker.io/calico/pod2daemon-flexvol:v3.28.0"
  Warning  Failed          85m (x112 over 16h)   kubelet  (combined from similar events): Failed to pull image "docker.io/calico/pod2daemon-flexvol:v3.28.0": rpc error: code = DeadlineExceeded desc = failed to pull and unpack image "docker.io/calico/pod2daemon-flexvol:v3.28.0": failed to copy: httpReadSeeker: failed open: failed to do request: Get "https://production.cloudflare.docker.com/registry-v2/docker/registry/v2/blobs/sha256/58/587b28ecfc62e2a60919e6a39f9b25be37c77da99d8c84252716fa3a49a171b9/data?verify=1720067032-UAyJpzOYNBEiBGCv%!F(MISSING)%!F(MISSING)OTJ4WQV2o%!D(MISSING)": dial tcp 199.59.149.208:443: i/o timeout
  Warning  FailedMount     13m                   kubelet  MountVolume.SetUp failed for volume "tigera-ca-bundle" : object "calico-system"/"tigera-ca-bundle" not registered
  Warning  FailedMount     13m                   kubelet  MountVolume.SetUp failed for volume "node-certs" : object "calico-system"/"node-certs" not registered
  Normal   SandboxChanged  13m                   kubelet  Pod sandbox changed, it will be killed and re-created.
  Warning  Failed          12m                   kubelet  Failed to pull image "docker.io/calico/pod2daemon-flexvol:v3.28.0": failed to pull and unpack image "docker.io/calico/pod2daemon-flexvol:v3.28.0": failed to copy: httpReadSeeker: failed open: failed to do request: Get "https://production.cloudflare.docker.com/registry-v2/docker/registry/v2/blobs/sha256/58/587b28ecfc62e2a60919e6a39f9b25be37c77da99d8c84252716fa3a49a171b9/data?verify=1720071385-TNktrfBxfbLLAVBL4OwGapHhZlY%3D": dial tcp 31.13.85.169:443: i/o timeout
  Warning  Failed          11m (x2 over 11m)     kubelet  Failed to pull image "docker.io/calico/pod2daemon-flexvol:v3.28.0": failed to pull and unpack image "docker.io/calico/pod2daemon-flexvol:v3.28.0": mkdir /var/lib/containerd/io.containerd.content.v1.content/ingest/bdda3d115b639779fe247e7698875486c900c20a8dad8acfddecb8fd2ba47918: no space left on device
  Warning  Failed          10m (x5 over 12m)     kubelet  Error: ImagePullBackOff
  Normal   Pulling         10m (x4 over 13m)     kubelet  Pulling image "docker.io/calico/pod2daemon-flexvol:v3.28.0"
  Warning  Failed          9m34s (x4 over 12m)   kubelet  Error: ErrImagePull
  Warning  Failed          9m34s                 kubelet  Failed to pull image "docker.io/calico/pod2daemon-flexvol:v3.28.0": failed to pull and unpack image "docker.io/calico/pod2daemon-flexvol:v3.28.0": failed to copy: httpReadSeeker: failed open: failed to do request: Get "https://production.cloudflare.docker.com/registry-v2/docker/registry/v2/blobs/sha256/58/587b28ecfc62e2a60919e6a39f9b25be37c77da99d8c84252716fa3a49a171b9/data?verify=1720071572-3YHRF4mXlSw0wK4N8Alanu4iomo%3D": dial tcp 159.106.121.75:443: i/o timeout
  Normal   BackOff         3m32s (x25 over 12m)  kubelet  Back-off pulling image "docker.io/calico/pod2daemon-flexvol:v3.28.0"

**Comment by caseydavenport** [comment]
Probably would suggest starting with this document and reporting back if that's not sufficient: https://docs.tigera.io/calico/latest/operations/image-options/alternate-registry

**Comment by coutinhop** [comment]
> Probably would suggest starting with this document and reporting back if that's not sufficient: https://docs.tigera.io/calico/latest/operations/image-options/alternate-registry

To add a bit, you'll probably need to build the images locally  (or import the tars) + push them to your private registry, then use the latter half of that doc to configure Calico to use your images

**Comment by huanghaiqing1** [comment]
Hello, Thanks for your information. And I'm a biginner for k8s and calico. Based on the KB your provided, I download the tar-ball: release-v3.28.0 and import the calico images to local private docker registry hub. Here I choose k8s master server also as my private docker registry. Based on that KB, I can define a variable: REGISTRY as "localhost:5000". And replace quay.io with $REGISTRY in tigera-operator.yaml and also add below part in the end of tiger-operator.yaml. Then go on calico deployment on k8s master server. Is the process ok? --- apiVersion: operator.tigera.io/v1 kind: Installation metadata: name: default spec: variant: Calico imagePullSecrets: - name: tigera-pull-secret registry: $REGISTRY On Jul 17, 2024, at 12:27 AM, Pedro Coutinho ***@***.***> wrote: Probably would suggest starting with this document and reporting back if that's not sufficient: https://docs.tigera.io/calico/latest/operations/image-options/alternate-registry To add a bit, you'll probably need to build the images locally (or import the tars) + push them to your private registry, then use the latter half of that doc to configure Calico to use your images — Reply to this email directly, view it on GitHub , or unsubscribe . You are receiving this because you authored the thread. Message ID: ***@***.***>

**Comment by huanghaiqing1** [comment]
When I follow the process in your recommended KB, it throws below warning during deploy tigera-operator.yaml. What should I set in my tigera-operator.yaml? On Jul 17, 2024, at 10:35 AM, 黄海庆 ***@***.***> wrote: Hello, Thanks for your information. And I'm a biginner for k8s and calico. Based on the KB your provided, I download the tar-ball: release-v3.28.0 and import the calico images to local private docker registry hub. Here I choose k8s master server also as my private docker registry. Based on that KB, I can define a variable: REGISTRY as "localhost:5000". And replace quay.io with $REGISTRY in tigera-operator.yaml and also add below part in the end of tiger-operator.yaml. Then go on calico deployment on k8s master server. Is the process ok? --- apiVersion: operator.tigera.io/v1 kind: Installation metadata: name: default spec: variant: Calico imagePullSecrets: - name: tigera-pull-secret registry: $REGISTRY <Screenshot 2024-07-17 103144.png><Screenshot 2024-07-17 103222.png> On Jul 17, 2024, at 12:27 AM, Pedro Coutinho ***@***.***> wrote: Probably would suggest starting with this document and reporting back if that's not sufficient: https://docs.tigera.io/calico/latest/operations/image-options/alternate-registry To add a bit, you'll probably need to build the images locally (or import the tars) + push them to your private registry, then use the latter half of that doc to configure Calico to use your images — Reply to this email directly, view it on GitHub , or unsubscribe . You are receiving this because you authored the thread. Message ID: ***@***.***>

**Comment by tomastigera** [comment]
https://docs.tigera.io/calico/latest/operations/image-options/alternate-registry#run-the-operator-using-images-from-your-registry
