### ISSUE TITLE
Latest felix not programming all iptables rules in calico-docker

### ISSUE THREAD

**Issue by robbrockbank** [projectcalico/calico#900]
I'm hitting a problem in calico-docker with the latest felix.  I initially had a problem with the installation (we needed to fix up our container image to include the yajl2 libraries) but have resolved that.

I'm running a 2 host test with a single workload on each host and a single profile used by both workloads.  Connectivity between the workloads is fine with calico@1.2.1, but broken with the latest master.

Looking at the iptables on a working (calico 1.2.1) and non-working (calico master) system reveals a large number of missing iptable entries.  No felix error logs.

I've gathered diagnostics from both hosts on the working and non-working system.  In all cases I've set log level to DEBUG.

Diagnostics can be downloaded as follows:

Host 1 (working system):  https://transfer.sh/O4KhO/diags-181115-024426.tar.gz
Host 2 (working system):  https://transfer.sh/mnqq1/diags-181115-024516.tar.gz

Host 1 (Non-working system): https://transfer.sh/blY0Q/diags-181115-024848.tar.gz
Host 2 (Non-working system): https://transfer.sh/NcPre/diags-181115-024920.tar.gz

**Comment by plwhite** [comment]
First thing that comes to mind is that we have added extra log files, and your diags job is not picking them up. That'll be what happens when we have different log collection jobs in different places (there's a driver log).

**Comment by alexwlchan** [comment]
I've had a brief dig into this, but couldn't find anything quickly. The only major change since v1.2.1 is Shaun's PR for concurrent resync. I suspect the problem is probably buried in there, although there aren't any obvious changes to the ipsets code.

**Comment by plwhite** [comment]
OK - I had a quick look but have stopped now. A few odd things.

- The Felix process is refreshing data every few seconds, which is odd. It might be that the refresh timer is firing too often?
- The driver logs added in this version are missing. Those would tell us what is going on from the etcd point of view.
- Looks like we do not have debug logs, just INFO level.

Net of this is that I think we probably do have a bug, but we should get debug logs and driver logs as well as felix logs to figure out why this is so broken in your environment.

**Comment by robbrockbank** [comment]
I'll update our log collection today and gather more logs and update the issue.

**Comment by robbrockbank** [comment]
oops sorry closed by mistake!

**Comment by robbrockbank** [comment]
Hmm, actually the logging might be a little more tricky in calico-docker land.  We currently have our processes log to stdout and use svlogd handle log file rotation.

So, what happens if the felix log level is set to write to stdout only?  What happens to the driver logs?

**Comment by robbrockbank** [comment]
I can see driver logs in the trace:

2015-11-18 02:46:08,759 [INFO][50/140139390368432] calico.etcddriver.driver 329: Sent config message to Felix.

Or should I be looking for something else?

**Comment by robbrockbank** [comment]
I think this might be related to #903.

If I stop and restart felix on both of my hosts, everything fixes itself - so this would appear to be an issue with notifications from etcd maybe?

**Comment by robbrockbank** [comment]
I've turned on debug tracing before Felix started.  Both of these are for a non-working system using the latest Felix.  Half way through you will see I forced a stop/start of felix, at which point everything kicks into life.  Diags were collected after the restart.

Host 1: https://transfer.sh/1738MK/diags-181115-201857.tar.gz
Host 2: https://transfer.sh/Vz5YD/diags-181115-202008.tar.gz

**Comment by fasaxc** [comment]
@robbrockbank the driver has its own logging config params.  It can log to stdout too; I think that will mix the logs in one stream for you to collect.

**Comment by fasaxc** [comment]
@plwhite and I had a look though the diags for bad host 1.  It appears that Felix is receiving no updates at all from etcd.  @robbrockbank are you sure that you're not writing to one etcd cluster and reading from another :-P ?  That would explain #903 too.

**Comment by robbrockbank** [comment]
We only have a single etcd instance running.  The only difference between the working and non-working scenarios is which version of calico we are baking into our ST.  So whilst it could be some kind of configuration issue, it is suspect that it was working before.

**Comment by fasaxc** [comment]
@robbrockbank You said on Slack that you thought this was some sort of timing window, which you only see when running docker-in-docker.
