### ISSUE TITLE
Which release has the latest features 3.28.0 or 3.24.7 for new installations?

### ISSUE THREAD

**Issue by Muthukumar-Subramaniam** [projectcalico/calico#9000]
My concern here is for the new installations, should we choose 3.28.0 or the current release marked as latest.
Just getting condused on the major release number 3.28.
For example, if we go with 3.27.4 for new installations as its marked latest, does it have bug fixes for 3.28.0?
Currently test clusters are running with 3.28.0.
Further testing for new installations should we go with 3.27.4?
Automation uses the manifest file from the calico project where we update the latest version.
https://raw.githubusercontent.com/projectcalico/calico/v3.28.0/manifests/tigera-operator.yaml

For newer installation for testing should we go with 3.27.4?

This issue is continuation of https://github.com/projectcalico/calico/issues/8999

I was unable to reopen the above issue, hence opened this new issue to get a clear picture on this.
Please assist us on this query.

**Comment by caseydavenport** [comment]
Calico follows semantic versioning (pretty closely) for its releases, which would put v3.28.0 as having more features than v3.27.4.

GitHub labels the most recently published chronologically release as "latest".

ref: https://semver.org/

**Comment by Muthukumar-Subramaniam** [comment]
Hi @caseydavenport,

Thank you for your clear information on this.
Hope they could adapt this as a feature in GitHub itself.
Something like latest release marking, for each bug fix patch versions of manjor.minor releases for Semantic Versioning.
