### ISSUE TITLE
Remove ETCD_AUTHORITY entirely

### ISSUE THREAD

**Issue by caseydavenport** [projectcalico/calico#901]
Remove ETCD_AUTHORITY from all Calico code.

It’s been deprecated for many releases now (in favor of ETCD_ENDPOINTS, which is what is documented)

**Comment by matthewdupre** [comment]
I approve, but we should mention we're doing it in slack and the release notes.

**Comment by caseydavenport** [comment]
@gunjan5 has this been done in v3.0 alpha?

**Comment by gunjan5** [comment]
It's in a PR https://github.com/projectcalico/libcalico-go/pull/634 which is awaiting final approval

**Comment by gunjan5** [comment]
Ok the PR is merged
