### ISSUE TITLE
Pods with hostNetwork: true can't access CoreDNS with 3.28.0

### ISSUE THREAD

**Issue by Don-ONeill** [projectcalico/calico#9015]
## Expected Behavior

Pods are getting assigned a IP in the VPC and should be able to use the CoreDNS service object IP to resolve DNS queries 

## Current Behavior

We dont see any queries reaching CoreDNS. Pods without the hostNetwork setting have no issue

## Possible Solution

We didnt have this problem with any version before 3.28.0

## Steps to Reproduce (for bugs)

1. Using Terraform to to deploy EKS 1.30 on AWSAmazon EKS 1.30
2. Before the node groups are deployed, we install using this method
3. kubectl create -f https://raw.githubusercontent.com/projectcalico/calico/v${var.calico_version}/manifests/tigera-operator.yaml
4. Then we apply this manifest

`kind: Installation
apiVersion: operator.tigera.io/v1
metadata:
  name: default
spec:
  kubernetesProvider: EKS
  cni:
    type: Calico
  calicoNetwork:
    bgp: Enabled
    hostPorts: Enabled
    ipPools:
    - cidr: "10.174.200.0/21"
      encapsulation: VXLAN`

## Context
Everything else seems to be working ok except for this issue. 

## Your Environment

* 3.28.0
* EKS on 1.30
* Amazon Linux

**Comment by caseydavenport** [comment]
@Don-ONeill I believe there is a known regression related to double-masquerade and VXLAN checksum offloading that can cause this problem. 

You may want to try disabling VXLAN checksum offloading on your instances and see if it improves your symptoms. 

You can do that with the following command:

```
kubectl patch felixconfiguration default --type="merge" -p='{"spec":{"FeatureDetectOverride":"ChecksumOffloadBroken=true"}'
```

https://www.tigera.io/blog/what-is-new-in-calico-3-28/

**Comment by Don-ONeill** [comment]
that fixed the problem, thank you..
