### ISSUE TITLE
Operator uninstall job runs when upgrade from 3.26 to 3.27+ version with ArgoCD

### ISSUE THREAD

**Issue by dmarquez-splunk** [projectcalico/calico#9033]
When upgrading operator helm from 3.26 to 3.27+ with argoCD we are seeing that the uninstall job is being executed and failing, leaving calico in a strange state. My suspicion is that the pre-delete helm hook isn't being respected since argoCD is managing the resources lifecycle and not helm. The helm plugin is using `helm template` with `kubectl apply` which I also suspect might be the reason for the helm hooks not being respected. You can see more documentation on the argocd helm implementation [here](https://argo-cd.readthedocs.io/en/stable/user-guide/helm/#hook-tips)

## Expected Behavior
Uninstall Job should not run when using operator with helm and Argocd on upgrades.

## Current Behavior
Uninstall Job is run when upgrading operator from 3.26 -> 3.27+ with helm and ArgoCD.

## Possible Solution
1. Make uninstall job optional via values.yaml
2. Allow for more annotations on the job so that we can add argocd hooks that can accomplish similar functionality as the helm hook (though I haven't tested this for correctness)

## Steps to Reproduce (for bugs)
1. Deploy operator with helm 3.26 via ArgoCD
2. Update the helm version to 3.27+ and sync the application via ArgoCD

## Context
This is impacts upgrades from 3.26 -> 3.27+ and I am worried that any other subsequent upgrades will result in the same behavior moving forward.

**Comment by caseydavenport** [comment]
Will think about how to resolve this one.

My first thought is that this is just a bug in ArgoCD and that it would be worth raising an issue against them.

That doesn't mean we can't come up with a workaround on our side, but really feels like Argo should fix this.

**Comment by dmarquez-splunk** [comment]
I worked around this issue by adding the `--no-hooks` flag to the `helm template` command to avoid it from generating the job's manifest. Not ideal but an alternative solution can be to optionally opt out of the resource by adding and additional boolean variable to the helm chart's values.yaml file and adding a check in the uninstall template.
