### ISSUE TITLE
Sort out Kubernetes versioning for manifests

### ISSUE THREAD

**Issue by caseydavenport** [projectcalico/calico#906]
We currently ship both k8s v1.5 manifests and k8s v1.6 manifests for each of the following:
- kubeadm
- kubernetes-datastore/policy-only
- kubernetes-datastore/calico-networking

Which is necessary because of incompatible API changes between the two k8s versions (change in tolerations).

We now have Kubernetes v1.7, which adds support for hostport and again requires an incompatible change to the manifests.

How can we organize our docs and manifests so that there isn't an overwhelming number of options, but we still support the necessary deployments?

It's related to, but not the same as, which Kubernetes versions do we say Calico is compatible with.

**Comment by bcreane** [comment]
@caseydavenport : the buck stops here.
