### ISSUE TITLE
Operator helm chart doesn't work when using kubernetesServiceEndpoint

### ISSUE THREAD

**Issue by abasitt** [projectcalico/calico#9061]
If I try to use kubernetesServiceEndpoint in the helm chart, I get below error. I am using k3s helm controller.

+ helm_v3 install --namespace tigera-operator --version v3.28.0 calico calico/tigera-operator --values /config/values-01_HelmChart.yaml
Error: INSTALLATION FAILED: 1 error occurred:
        * ConfigMap in version "v1" cannot be handled as a ConfigMap: json: cannot unmarshal number into Go struct field ConfigMap.data of type string
 

## Steps to Reproduce (for bugs)
helm install with kubernetesServiceEndpoint, specially when using https://github.com/k3s-io/helm-controller

## Your Environment
* Calico version: 3.28.0
* Orchestrator version k3s

**Comment by caseydavenport** [comment]
@abasitt could you provide your values.yaml file?

**Comment by abasitt** [comment]
Thank you @caseydavenport for looking in to this. 
My helmcharts that doesn't work. 
https://github.com/abasitt/home-ops/blob/main/ansible/neo_pg/playbooks/templates/custom-calico-helmchart.yaml.j2

It works when i remove the kubernetesServiceEndpoint. e.g. below is the working one.
https://github.com/abasitt/home-ops/blob/main/ansible/neo/playbooks/templates/custom-calico-helmchart.yaml.j2

**Comment by abasitt** [comment]
The full error.
```

set +v -x
+ [[ true != \t\r\u\e ]]
+ [[ '' == \1 ]]
+ [[ '' == \v\2 ]]
+ shopt -s nullglob
+ [[ -f /config/ca-file.pem ]]
+ [[ -f /tmp/ca-file.pem ]]
+ [[ -n '' ]]
+ helm_content_decode
+ set -e
+ ENC_CHART_PATH=/chart/calico.tgz.base64
+ CHART_PATH=/tmp/calico.tgz
+ [[ ! -f /chart/calico.tgz.base64 ]]
+ return
+ [[ install != \d\e\l\e\t\e ]]
+ helm_repo_init
+ grep -q -e 'https\?://'
+ [[ helm_v3 == \h\e\l\m\_\v\3 ]]
+ [[ calico/tigera-operator == stable/* ]]
+ [[ -n https://projectcalico.docs.tigera.io/charts ]]
+ [[ -f /auth/username ]]
+ [[ -f /auth/tls.crt ]]
+ helm_v3 repo add calico https://projectcalico.docs.tigera.io/charts
"calico" has been added to your repositories
+ helm_v3 repo update
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "calico" chart repository
Update Complete. ⎈Happy Helming!⎈
+ helm_update install --namespace tigera-operator --version v3.28.0
+ [[ helm_v3 == \h\e\l\m\_\v\3 ]]
++ helm_v3 ls --all -f '^calico$' --namespace tigera-operator --output json
++ ++ tr '[:upper:]' '[:lower:]'
jq -r '"\(.[0].chart),\(.[0].status)"'
+ LINE=tigera-operator-v3.28.0,failed
+ IFS=,
+ read -r INSTALLED_VERSION STATUS _
+ VALUES=
+ for VALUES_FILE in /config/*.yaml
+ VALUES=' --values /config/values-01_HelmChart.yaml'
+ [[ install = \d\e\l\e\t\e ]]
+ [[ tigera-operator-v3.28.0 =~ ^(|null)$ ]]
+ [[ failed =~ ^(pending-install|pending-upgrade|pending-rollback)$ ]]
+ [[ failed == \d\e\p\l\o\y\e\d ]]
+ [[ failed =~ ^(deleted|failed|null|unknown)$ ]]
+ [[ reinstall == \r\e\i\n\s\t\a\l\l ]]
+ [[ helm_v3 == \h\e\l\m\_\v\3 ]]
+ echo 'Uninstalling failed helm_v3 chart'
+ helm_v3 uninstall calico --namespace tigera-operator --wait
release "calico" uninstalled
Deleted
+ echo Deleted
+ echo 'Installing helm_v3 chart'
+ helm_v3 install --namespace tigera-operator --version v3.28.0 calico calico/tigera-operator --values /config/values-01_HelmChart.yaml
Error: INSTALLATION FAILED: 1 error occurred:
        * ConfigMap in version "v1" cannot be handled as a ConfigMap: json: cannot unmarshal number into Go struct field ConfigMap.data of type string
```

**Comment by j-rda** [comment]
I just got this error message too setting my endpoint to the hostname of my load balancer.
k8s 1.30.4, cri-o, operator 3.28.0.
I initialized my first CP, then installed the helm chart... error message but tigera-operator is running and the other calico pods.
I joined CPs and then 5 workers. everything looks to be working so far.

**Comment by caseydavenport** [comment]
I believe this was fixed in this PR: https://github.com/projectcalico/calico/pull/9067

Backported here: https://github.com/projectcalico/calico/pull/9068

So, will be in v3.28.2 when it is released. Thanks all.

**Comment by abasitt** [comment]
Thank you
