### ISSUE TITLE
Error Pulling image "quay.io/tigera/operator:v1.34.3" while upgrading to latest version v3.28.1

### ISSUE THREAD

**Issue by Muthukumar-Subramaniam** [projectcalico/calico#9076]
Hi projectcalico team,

Seems like the image trying to be fetched is not available yet in the quay.io image repository .
Please check and fix the issue, either wrong image name specified in the manifest or the tag is not yet updated in the quay.io image repository ..

Please find the below logs .

[root@prod-k8s-cp1 ~]# curl https://raw.githubusercontent.com/projectcalico/calico/v3.28.1/manifests/tigera-operator.yaml | grep "quay.io/tigera/operator:v1.34.3"
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 1724k  100 1724k    0     0  3641k      0 --:--:-- --:--:-- --:--:-- 3637k
          image: quay.io/tigera/operator:v1.34.3
[root@prod-k8s-cp1 ~]#

------------------------------------------------------
Events:
  Type     Reason     Age                  From               Message
  ----     ------     ----                 ----               -------
  Normal   Scheduled  2m36s                default-scheduler  Successfully assigned tigera-operator/tigera-operator-77f994b5bb-zwckp to prod-k8s-n2
  Normal   Pulling    66s (x4 over 2m35s)  kubelet            Pulling image "quay.io/tigera/operator:v1.34.3"
  Warning  Failed     65s (x4 over 2m34s)  kubelet            Failed to pull image "quay.io/tigera/operator:v1.34.3": rpc error: code = NotFound desc = failed to pull and unpack image "quay.io/tigera/operator:v1.34.3": failed to resolve reference "quay.io/tigera/operator:v1.34.3": quay.io/tigera/operator:v1.34.3: not found
  Warning  Failed     65s (x4 over 2m34s)  kubelet            Error: ErrImagePull
  Warning  Failed     54s (x6 over 2m34s)  kubelet            Error: ImagePullBackOff
  Normal   BackOff    42s (x7 over 2m34s)  kubelet            Back-off pulling image "quay.io/tigera/operator:v1.34.3"

<img width="821" alt="Screenshot-2024-07-31-091831" src="https://github.com/user-attachments/assets/cbad49e5-5c4e-40ba-a71f-4b2d8c7aa7db">

Thanks & Regards,
Muthukumar Subramaniam

**Comment by RemcodM** [comment]
We're experiencing the same problem. But the reason the image seems to be missing is because version 1.34.3 of the Tigera Operator is not even released yet? It is not listed on https://github.com/tigera/operator/releases.

I suspected earlier today that the release might have been a little bit late, but several hours hours later, this release is still not available. Maybe the Helm chart references the wrong operator version?

**Comment by caseydavenport** [comment]
CC @danudey 

Sorry about this - please continue to use the previous release for now. There was a gap between publishing the chart and publishing the operator release. Should be resolved today, thank you for your patience. :pray:

**Comment by Muthukumar-Subramaniam** [comment]
This issue was fixed 2 weeks ago.

Thanks & Regards,
Muthukumar Subramaniam
