### ISSUE TITLE
vxlanTunnelMACAddr not published in Node resource spec

### ISSUE THREAD

**Issue by mgrove36** [projectcalico/calico#9086]
## Expected Behavior

A `vxlanTunnelMACAddr` key-value pair should be present in the `spec` section of the `Node` resource created by Calico when a `calico/node` instance is started.

## Current Behavior

No `vxlanTunnelMACAddr` key-value pair is present. `calicoctl get node master -o yaml` gives:

```yaml
apiVersion: projectcalico.org/v3
kind: Node
metadata:
  annotations:
    projectcalico.org/kube-labels: '{"beta.kubernetes.io/arch":"amd64","beta.kubernetes.io/os":"linux","kubernetes.io/arch":"amd64","kubernetes.io/hostname":"master","kubernetes.io/os":"linux","node-role.kubernetes.io/control-plane":"","node.kubernetes.io/exclude-from-external-load-balancers":""}'
  creationTimestamp: "2024-07-12T08:26:13Z"
  labels:
    beta.kubernetes.io/arch: amd64
    beta.kubernetes.io/os: linux
    kubernetes.io/arch: amd64
    kubernetes.io/hostname: master
    kubernetes.io/os: linux
    node-role.kubernetes.io/control-plane: ""
    node.kubernetes.io/exclude-from-external-load-balancers: ""
  name: master
  resourceVersion: "140164"
  uid: c777xxxx9fb9
spec:
  addresses:
  - address: 192.168.124.153/24
    type: CalicoNodeIP
  - address: 192.168.124.153
    type: InternalIP
  bgp:
    ipv4Address: 192.168.124.153/24
  ipv4VXLANTunnelAddr: 10.100.219.64
  orchRefs:
  - nodeName: master
    orchestrator: k8s
status: {}
```

## Steps to Reproduce (for bugs)

1. Deploy a new k8s cluster with kubeadm, using cri-dockerd and a Pod IP range of 10.100.0.0/16
2. Install Calico using [the instructions from the documentation](https://docs.tigera.io/calico/latest/getting-started/kubernetes/self-managed-onprem/onpremises), in `VXLANCrossSubnet` mode.
3. Get a node resource with `calicoctl get node node_name -o yaml`

## Context

[The reference for the Node resource](https://docs.tigera.io/calico/latest/reference/resources/node) states that `vxlanTunnelMACAddr` should be populated by the system - and not added manually - so I would expect it to be present whenever Calico is running with VXLAN.

## Your Environment

* Calico version: 
  * Client Version:    v3.28.0
  * Git commit:        413e6f559
  * Cluster Version:   v3.28.0
  * Cluster Type:      typha,kdd,k8s,operator,bgp,kubeadm
* Kubernetes version:
  * Client Version: v1.30.2
  * Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
  * Server Version: v1.30.2
* Operating System and version:
  * All nodes are Debian 12 with kernel 6.1.0 (`Linux master 6.1.0-23-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.99-1 (2024-07-15) x86_64 GNU/Linux`)

**Comment by cyclinder** [comment]
Hi @mgrove36, Thanks for the report.

Do you change the tunnel mode? Do you use the VXLANCrossSubnet mode when you install the calico?

**Comment by mgrove36** [comment]
Hey 👋
It was installed in `VXLANCrossSubnet` mode, and presented the issue. Switching to the VXLAN Always mode gave the same issue

**Comment by cyclinder** [comment]
Did you find anything suspicious in the calico-node logs? I will try to reproduce it.

**Comment by mgrove36** [comment]
Thanks. `calico-node` logs show it is correctly receiving the MACs via `proto.VXLANTunnelEndpointUpdate update from calculation graph` but that when initially loading the configuration (`felix/daemon.go 391: Successfully loaded configuration.`) `VXLANTunnelMACAddr` and `VXLANTunnelMACAddrV6` are both empty strings.

**Comment by mgrove36** [comment]
And the API resources themselves never seem to publish the MACs at all

**Comment by caseydavenport** [comment]
Hm, that field should be set from the `"projectcalico.org/VXLANTunnelMACAddr"` annotation on the underlying Kubernetes Node object - do you see that it is present if you use `kubectl` to get the node?

**Comment by mgrove36** [comment]
Nope, it's not set

**Comment by mgrove36** [comment]
Has anyone been able to replicate this?

**Comment by caseydavenport** [comment]
I can confirm that I also do not see the MAC address annotation. 

However, my VXLAN network seems to be functioning just fine. I believe this is because the MAC address is deterministically calculated when that annotation isn't present: https://github.com/projectcalico/calico/blob/05f32eaa0682e008cc7c4e3d0ccd10665e139603/felix/calc/vxlan_resolver.go#L359-L363

So, I think this is working as intended but the reference documentation isn't correct.

**Comment by mgrove36** [comment]
Makes sense, thanks for verifying. VXLAN works fine for me too - it was just that annotation missing. Is it worth updating the implementation so the annotation is published via the API server? This would be the same functionality that Flannel provides

**Comment by caseydavenport** [comment]
I'd rather just update the documentation to say that field is deprecated and kept around for legacy reasons (which I believe is the case). Unless there's a reason we want to have it written into the API?

**Comment by mgrove36** [comment]
Don't think so, was just a suggestion. Sounds good to me :)

**Comment by caseydavenport** [comment]
My colleagues just reminded me that this field is indeed used specifically to handle migration from flannel->Calico, in order to maintain the use of the existing tunnel MAC to avoid network disruptions.

**Comment by mgrove36** [comment]
Ah, makes sense!
