### ISSUE TITLE
Calico-node pods is listed as 0/1

### ISSUE THREAD

**Issue by denis-akimov** [projectcalico/calico#9087]
I have 2 nodes in my baremetal kubernetes cluster. I installed calico and the calico-node pods are not starting. They are in running status but the number of running containers is listed as 0/1

![image](https://github.com/user-attachments/assets/1d1e5923-be98-4701-8054-544c7dd254bd)

## Expected Behavior

All calico-node pods is listed as 1/1
## Current Behavior

Calico-node pods is listed as 0/1
## Steps to Reproduce (for bugs)

1. Install kubelet kubeadm kubectl
2. Run kubeadm init --pod-network-cidr=10.244.0.0/16
3. Add another node to cluster
4. Install calico with manifest: kubectl apply -f https://raw.githubusercontent.com/projectcalico/calico/v3.28.1/manifests/calico.yaml
5. Make sure the pods show 0/1

Here are the events that can be obtained using the command kubectl describe po calico-node-7tp6l -n kube-system
![image](https://github.com/user-attachments/assets/be7c97eb-6962-48f9-8942-ebee30f485d8)

Here are the logs from kubectl logs calico-node-7tp6l -n kube-system
![image](https://github.com/user-attachments/assets/80268bb4-2c0b-4cd4-bab0-8766d66e0507)

## Your Environment

* Calico version 3.28.1
* Orchestrator version (e.g. kubernetes, mesos, rkt): kubeadm 1.30.3
* Operating System and version: Ubuntu 20.04.3

**Comment by caseydavenport** [comment]
Sounds like BGP is failing to establish.

Please first double check that you have met the network requirements for BGP listed here: https://docs.tigera.io/calico/latest/getting-started/kubernetes/requirements#network-requirements

Specifically, your firewall rules / security group needs to allow TCP port 179.

**Comment by sridhartigera** [comment]
@denis-akimov Any update on this?
