### ISSUE TITLE
slow pod-to-pod communication after migrating to a new infrastructure

### ISSUE THREAD

**Issue by jonahbohlmann** [projectcalico/calico#9097]
I have 3 Kubernetes clusters (3 cp, 3 w) installed via Kubespray, hosted on a Proxmox cluster (3 nodes). Recently, I migrated to a new Proxmox cluster with a 10G network (before, it was 1G). 
Since the migration, the pod-to-pod network has been slow/unusable on all three clusters.

## Expected Behavior
Network speed for pod-to-pod should be > 1G (better around 10G)

## Current Behavior
Since the migration to new servers with Broadcom BCM57412 NetXtreme-E 10Gb RDMA Ethernet, the pod-to-pod network speed has decreased from 900Mbit/s to around 6-7Mbit/s.

On the old hardware, the speed is still around 900 Mbit/s.

## Possible Solution
N/A

## Steps to Reproduce (for bugs)
N/A

## Context
The Migration was actually:
- stop K8S VMs
- backup from old proxmox env
- restore in new proxmox env
- change node IPs with kubespray
- Start the cluster again

MTU was checked and is 1500 everywhere (with exception of the pod with 1430).

Resources / issues:
- https://github.com/projectcalico/calico/issues/7545
- https://github.com/projectcalico/calico/issues/6410
- https://github.com/kubernetes/kubernetes/issues/117162
- https://serverfault.com/a/1106199
- https://github.com/projectcalico/calico/issues/4743

Calico settings in kubespray:
```yaml
calico_ipip_mode_ipv6: Never
calico_vxlan_mode_ipv6: Always
calico_endpoint_to_host_action: "ACCEPT"
calico_iptables_backend: "NFT"
calico_network_backend: vxlan
```

## Your Environment
* Calico version: 3.26.4
* Orchestrator version (e.g. kubernetes, mesos, rkt): k8s 1.28.10
* Operating System and version: Oracle Linux 8
* K8S installed via kubespray 2.24.2

**Comment by jonahbohlmann** [comment]
We updated the firmware of the network cards (Broadcom BCM57412 NetXtreme-E 10Gb RDMA Ethernet) from V216 and V218 to 230.1.116.0. This solved the issue.

With the old version, we had around 6-7 Mbit/s. Now, we have 2.5Gbit/s. Maybe this could be improved by optimizing MTU, but 2.5Gbit/s is more than enough for us for now.

Thanks!

**Comment by DeprecatedLuke** [comment]
Issue is also present on: cb:00.0 Ethernet controller: Broadcom Inc. and subsidiaries BCM57416 NetXtreme-E Dual-Media 10G RDMA Ethernet Controller (rev 01)
