### ISSUE TITLE
Worker Nodes cannot communicate with API Server

### ISSUE THREAD

**Issue by 4ndr3asd** [projectcalico/calico#9110]
## Expected Behavior
After setting up Cloud Infrastructure with Terraform and configuring MicroK8s with Ansible, it should work with calico fine and without errors.

## Current Behavior
After setting up Cloud Infrastructure with Terraform and configuring MicroK8s it with Ansible, Calico starts on each node calico-pods but only on the master node the pod gets to the state `running` . On both worker nodes the pods are looping in killing and creating. If I use `kubectl describe pod calico-node-v8x6l -n kube-system` I get following output:
```
  Type     Reason     Age                From               Message
  ----     ------     ----               ----               -------
  Normal   Scheduled  52s                default-scheduler  Successfully assigned kube-system/calico-node-v8x6l to worker-node-1
  Normal   Pulled     52s                kubelet            Container image "docker.io/calico/cni:v3.25.1" already present on machine
  Normal   Created    52s                kubelet            Created container upgrade-ipam
  Normal   Started    52s                kubelet            Started container upgrade-ipam
  Normal   Pulled     21s (x2 over 52s)  kubelet            Container image "docker.io/calico/cni:v3.25.1" already present on machine
  Normal   Created    21s (x2 over 52s)  kubelet            Created container install-cni
  Normal   Started    21s (x2 over 52s)  kubelet            Started container install-cni
  Normal   Pulled     20s                kubelet            Container image "docker.io/calico/node:v3.25.1" already present on machine
  Normal   Created    20s                kubelet            Created container calico-node
  Normal   Started    20s                kubelet            Started container calico-node
  Warning  Unhealthy  2s (x4 over 19s)   kubelet            Readiness probe failed: calico/node is not ready: felix is not ready: Get "http://localhost:9099/readiness": dial tcp [::1]:9099: connect: connection refused
  Warning  Unhealthy  2s                 kubelet            Liveness probe failed: calico/node is not ready: Felix is not live: Get "http://localhost:9099/liveness": dial tcp [::1]:9099: connect: connection refused
```
If I do `kubectl logs calico-node-v8x6l -n kube-system` for example then I get:
```
Defaulted container "calico-node" out of: calico-node, upgrade-ipam (init), install-cni (init)
Error from server: Get "https://188.245.103.211:10250/containerLogs/kube-system/calico-node-v8x6l/calico-node": dial tcp 188.245.103.211:10250: i/o timeout
```

Those Problems are only on Worker Nodes, if I do the same commands on the calico node which is located on the master node I get logs and no errors at all.

## Possible Solution
I don't know what's going on so I can't tell what a solution could be.

## Steps to Reproduce (for bugs)
1. Create 3 Servers in Hetzner Cloud (2 worker and 1 master all with arm64, 4VCPUs and 8GB RAM)
2. Configure MicroK8s on nodes with Ansible
3. Watch Calico Nodes failing

## Context
After using Raspberry Pi I wanted to switch to cloud based clusters, and after spinning up those Hetzner Servers and installing microk8s the goal was to configure load balancer and firewall.

## Your Environment
* Calico version: 3.25.1 (Standard with microK8s)
* Orchestrator version (e.g. kubernetes, mesos, rkt): kubernetes client v1.29.2, kubernetes server v1.30.1
* Operating System and version: Servers run with Debian 12

**Comment by 4ndr3asd** [comment]
@mazdakn I didn't tried the newer versions, because this Calico Version is included in my microk8s installation. With v1.29 od microk8s it get s automatically installed and if I understand it correct there is no possibility to upgrade to a later version, because the installation is with Ansible Commands. 

I install the cluster with some Ansible Commands, that configure the standard environment with calico, coredns, docker and more.
If BGP is the standard, then yes I use BGP in my cluster, is there a way to check that?

**Comment by caseydavenport** [comment]
> Error from server: Get "https://188.245.103.211:10250/containerLogs/kube-system/calico-node-v8x6l/calico-node": dial tcp 188.245.103.211:10250: i/o timeout

This error seems to suggest an issue with Kubernetes itself being able to communicate with the node in order to get logs, not necessarily an issue with Calico (which isn't involved in node->node communication like this).

I'd probably start by verifying that your network enables all nodes to communicate with each other - is there a firewall / security group in your cluster? Does it allow the necessary traffic?

**Comment by 4ndr3asd** [comment]
@caseydavenport Yes I got one firewall rule in Hetzner Cloud, but its configured for incoming traffic, not inside the cluster.

I think with Security Group you mean SecurityContext and the installation of microk8s isn't with any security rules at all only some modifications with `mode`, but here the code for your understanding.
`- name: Install alternative packagemanagement system snapd
  ansible.builtin.apt:
    name: "{{ item }}"
    state: "present"
    force_apt_get: "yes"
  with_items:
    - snapd

- name: Cgroup enable in kernal
  ansible.builtin.replace:
    path: /boot/firmware/cmdline.txt
    regexp: '^([\w](?!.*\b{{ item }}\b).*)$'
    replace: '\1 {{ item }}'
  with_items:
    - "cgroup_memory=1"
    - "cgroup_enable=memory"
  when: ansible_default_ipv4.address | ipaddr('ip-adress-range')

- name: Disable swap
  ansible.builtin.service:
    name: dphys-swapfile
    state: stopped
    enabled: false
  when: ansible_default_ipv4.address | ipaddr('192.168.177.0/24')

- name: Install microk8s
  community.general.snap:
    classic: yes
    name:
      - microk8s

- name: Add all users into the microk8s group
  ansible.builtin.user:
    name: "{{ ansible_ssh_user }}"
    groups: microk8s
    append: true

- name: Add kubectl alias
  ansible.builtin.lineinfile:
    create: true
    mode: "644"
    path: /etc/profile.d/00-aliases.sh
    line: "alias kubectl='microk8s kubectl'"
    state: present
    insertafter: EOF

- name: Unconditionally reboot the machine with all defaults
  become: true
  ansible.builtin.reboot:`

**Comment by caseydavenport** [comment]
> but its configured for incoming traffic, not inside the cluster.

You may need to add rules to your firewall to allow the necessary in-cluster communications between nodes, if it doesn't already allow them. Here's a reference: https://docs.tigera.io/calico/latest/getting-started/kubernetes/requirements#network-requirements

**Comment by 4ndr3asd** [comment]
I fixed it with some Firewall Rules. I got one for traffic from outside but forgot the traffic inside the cluster between single nodes. Some internal firewall rules fixed the problem. Thank you for your help an the link.
