### ISSUE TITLE
Missing documentation of RBAC requirements

### ISSUE THREAD

**Issue by MikeSpreitzer** [projectcalico/calico#912]
## Expected Behavior

http://docs.projectcalico.org/v2.3/getting-started/kubernetes/installation/#requirements makes a vague statement that some RBAC configuration must be done, and someone who proceeds to http://docs.projectcalico.org/v2.3/getting-started/kubernetes/installation/integration gets no further guidance.  That reader should get sufficient guidance. 

## Current Behavior

See above.

## Possible Solution

The smallest fix would be to update that vague remark in http://docs.projectcalico.org/v2.3/getting-started/kubernetes/installation/integration to include a reference to http://docs.projectcalico.org/v2.3/getting-started/kubernetes/installation/hosted/#rbac

## Steps to Reproduce (for bugs)

1.  Visit http://docs.projectcalico.org/v2.3/getting-started/kubernetes/installation/
2.  Visit http://docs.projectcalico.org/v2.3/getting-started/kubernetes/installation/integration
3.  Note that you have not bee told what RBAC stuff you need to add

## Context

I am trying to update some Ansible plays that add Calico (itself using etcd directly) to Kubernetes in the manner discussed in http://docs.projectcalico.org/v2.3/getting-started/kubernetes/installation/integration

## Your Environment

* Calico version v2.0 through v2.3
* Orchestrator version (e.g. kubernetes, mesos, rkt): Kubernetes 1.6
* Operating System and version: Ubuntu 16.04
* Link to your project (optional): Sorry, not public

**Comment by tmjd** [comment]
I think with #913 merged there is nothing left to do on this issue so I'm closing it.  If there is still more that needs to be done please let us know and we can reopen it.
