### ISSUE TITLE
how to  change a pod's bandwidth dynamically？

### ISSUE THREAD

**Issue by chenm0520** [projectcalico/calico#9145]
we can set a pod's bandwidth with a annotation `kubernetes.io/ingress-bandwidth` in k8s,but if the annotation  change, it cannot to be effective  right now,is there any solution in calico to make the change take effect right now without kill the pod?

**Comment by caseydavenport** [comment]
Right now, Calico doesn't offer anything beyond the kubernetes annotation for this, so you would need to restart the pod.
