### ISSUE TITLE
Calico cannot obtain IPv6 address, unable to complete initialization

### ISSUE THREAD

**Issue by smallemployees** [projectcalico/calico#9184]
## Expected Behavior

Why not consider instantiating IPv4 separately

## Current Behavior

Calico node cannot start

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Calico version 3.23.4
* Orchestrator version (e.g. kubernetes, mesos, rkt):
* Operating System and version:
* Link to your project (optional):

**Comment by lwr20** [comment]
Can you fill in the Issue template correctly please?  There's not enough information here to help you.  

One thing you did provide was the calico version (3.23.4).  That version is **very** old now - released 20 Oct 2022.  You should upgrade to a version that's still supported (3.28.x).

FWIW, we have automated tests for IPv4 only, IPv6 only and dual-stack clusters (on the supported releases), and we do NOT see anything like this issue in there.  You will need to provide more information about your problem if we're going to be able to help.

If you're new to Calico and struggle to provide useful debugging information, consider joining the Calico Slack https://slack.projectcalico.org/ and we can try to assist there.
