### ISSUE TITLE
Install CNI loopback plugin

### ISSUE THREAD

**Issue by caseydavenport** [projectcalico/calico#92]
Kubernetes depends on the loopback plugin being installed. See here: kubernetes/kubernetes#30681

Calico itself doesn't need this, but Kubernetes fails without it. Should the self-hosted manifests support installing this binary?

In the meantime, users need to make sure they are installing a CNI release from here: https://github.com/containernetworking/cni/releases

**Comment by djosborne** [comment]
ping @caseydavenport can you triage this accordingly

**Comment by caseydavenport** [comment]
Yep.  This isn't a v2.0.0-beta blocker.  Leaving as is.

**Comment by caseydavenport** [comment]
Fixed in `calico/cni:v1.5.2`

**Comment by heschlie** [comment]
Resolved in this PR https://github.com/projectcalico/calico-cni/pull/211
