### ISSUE TITLE
Readiness probe failed: calico/node is not ready: BIRD is not ready: Error querying BIRD: unable to connect to BIRDv4 socket: dial unix /var/run/calico/bird.ctl: connect: connection refused

### ISSUE THREAD

**Issue by emoxam** [projectcalico/calico#9201]
I've got cluster
k get nodes
```
NAME            STATUS     ROLES           AGE     VERSION
kube-master     Ready      control-plane   2y12d   v1.24.4
kube-worker-1   Ready      <none>          2y12d   v1.24.4
kube-worker-2   Ready      <none>          2y12d   v1.24.4
```
on master node
calicoctl version
```
Client Version:    v3.23.3
Git commit:        3a3559be1
Cluster Version:   v3.23.3
Cluster Type:      k8s,bgp,kubeadm,kdd
```

And i want to add a new node
without this command i can't do that ()maybe it is important

`kubectl create clusterrolebinding kubeadm:kubelet-bootstrap --clusterrole=system:node-bootstrapper --group=system:bootstrappers:kubeadm:default-node-token`

k get clusterrolebinding | grep kubelet-bootstrap
```
kubeadm:kubelet-bootstrap                              ClusterRole/system:node-bootstrapper                                               30m
kubelet-bootstrap                                      ClusterRole/system:node-bootstrapper                                               2y4d
```

than i added a new node, approved certificates
`kubectl certificate approve csr-hl2bx`
so i can see pod logs

but calico-node-w68dv stucked in

`Readiness probe failed: calico/node is not ready: BIRD is not ready: Error querying BIRD: unable to connect to BIRDv4 socket: dial unix /var/run/calico/bird.ctl: connect: connection refused`

What should i do to fix it? Help me to fix it please.

here's a output of
kubectl logs -n kube-system calico-node-5qjvf
https://pastebin.com/RrbY1rR0

**Comment by emoxam** [comment]
here's a output of
kubectl logs -n kube-system calico-node-5qjvf
https://pastebin.com/RrbY1rR0

**Comment by caseydavenport** [comment]
> Cluster Version:   v3.23.3

This Calico version is very old and no longer in support. I'd recommend upgrading to a newer Calico + Kubernetes version.
