### ISSUE TITLE
Running calico as root user 

### ISSUE THREAD

**Issue by LyKos4** [projectcalico/calico#9209]
Are there security dangers in running the calico pods' containers as root user in a kubernetes cluster?
If so, what are they?  (Please describe scenario) 
Also, are all pods affected? Either they are accessible with bash/sh or not?

Is there a  way to run calico pods with a non-privileged user with no problems?

**Comment by frozenprocess** [comment]
@LyKos4 This sounds like a thing to ask on [Slack](https://calicousers.slack.com/) or the [discussion board](https://github.com/orgs/projectcalico/discussions).

**Comment by caseydavenport** [comment]
https://github.com/orgs/projectcalico/discussions/9212
