### ISSUE TITLE
 failed (add): error getting ClusterInformation: connection is unauthorized: Unauthorized

### ISSUE THREAD

**Issue by 13567436138** [projectcalico/calico#9215]
## Current Behavior

```
  Warning  FailedCreatePodSandBox  33s               kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "b6385006e8b3eedeaa1fd60e3e69afc9fb758a27666c93708a9211b3c988ab34": plugin type="calico" failed (add): error getting ClusterInformation: connection is unauthorized: Unauthorized
```
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Calico version  v3.26,1
* Orchestrator version (e.g. kubernetes, mesos, rkt): k8s 1.31.0
* Operating System and version: ubuntu2404
* Link to your project (optional):

**Comment by sridhartigera** [comment]
can you give more information on this?

**Comment by oniubi** [comment]
me too

**Comment by caseydavenport** [comment]
There's not enough information to go on here. We've fixed a number of issues related to this in recent releases - I recommend trying a newer version.
