### ISSUE TITLE
bad network performance with calico in kubernetes cluster

### ISSUE THREAD

**Issue by haveatry** [projectcalico/calico#922]
I tried to verify the network performance with qperf tool in one kubernetes cluster. The kubernetes cluster is set up with kubeadm, and the pod network add-on is calico. The calico related pods is create via the [yaml file](http://docs.projectcalico.org/v2.3/getting-started/kubernetes/installation/hosted/kubeadm/1.6/calico.yaml). The master node is installed in one VM, 3 working nodes are all physical machines, and the network dev info is as the following for the 3 working nodes.

[root@docker01 ~]# ethtool bond0
Settings for bond0:
	Supported ports: [ ]
	Supported link modes:   Not reported
	Supported pause frame use: No
	Supports auto-negotiation: No
	Advertised link modes:  Not reported
	Advertised pause frame use: No
	Advertised auto-negotiation: No
	**Speed: 20000Mb/s**
	Duplex: Full
	Port: Other
	PHYAD: 0
	Transceiver: internal
	Auto-negotiation: off
	Link detected: yes

The following table shows the summary of my test result. My question is why the max bandwidth for the  first and third test could only reach around 180MB/sec.  Is there any config could be changed to adjust it performance? Furthermore, why the access from one node to pod in another node could only reach 182 MB/sec, while the access from one pod to another node could reach 827MB/sec?

access type | max bandwidth
-- | --
pod to pod in another node | 179 MB/sec
pod to pod in the same node | 4.96GB/sec
node to pod in another node | 182 MB/sec
pod to another node | 827 MB/sec
node to node | 1.78 GB/sec

**The following is the test result for the pod to pod access, the max bandwidth is 171 MB/Sec.**
[root@docker01 /]# qperf -oo  msg_size:1:2M:*2  10.244.180.4 tcp_bw tcp_lat
tcp_bw:
    bw  =  2.26 MB/sec
tcp_bw:
    bw  =  4.08 MB/sec
tcp_bw:
    bw  =  7.93 MB/sec
tcp_bw:
    bw  =  14.7 MB/sec
tcp_bw:
    bw  =  24.3 MB/sec
tcp_bw:
    bw  =  39.5 MB/sec
tcp_bw:
    bw  =  59.9 MB/sec
tcp_bw:
    bw  =  89.4 MB/sec
tcp_bw:
    bw  =  109 MB/sec
tcp_bw:
    bw  =  132 MB/sec
tcp_bw:
    bw  =  153 MB/sec
tcp_bw:
    bw  =  167 MB/sec
tcp_bw:
    bw  =  169 MB/sec
tcp_bw:
    bw  =  170 MB/sec
tcp_bw:
    bw  =  171 MB/sec
tcp_bw:
    bw  =  152 MB/sec
tcp_bw:
    bw  =  171 MB/sec
tcp_bw:
    bw  =  164 MB/sec
tcp_bw:
    bw  =  126 MB/sec
tcp_bw:
    bw  =  163 MB/sec
tcp_bw:
    bw  =  153 MB/sec
tcp_bw:
    bw  =  153 MB/sec
tcp_lat:
    latency  =  56.8 us
tcp_lat:
    latency  =  56.4 us
tcp_lat:
    latency  =  56.3 us
tcp_lat:
    latency  =  57.2 us
tcp_lat:
    latency  =  57.1 us
tcp_lat:
    latency  =  57.9 us
tcp_lat:
    latency  =  57.1 us
tcp_lat:
    latency  =  57.6 us
tcp_lat:
    latency  =  60 us
tcp_lat:
    latency  =  58.6 us
tcp_lat:
    latency  =  68.7 us
tcp_lat:
    latency  =  84.2 us
tcp_lat:
    latency  =  111 us
tcp_lat:
    latency  =  136 us
tcp_lat:
    latency  =  204 us
tcp_lat:
    latency  =  389 us
tcp_lat:
    latency  =  601 us
tcp_lat:
    latency  =  1.17 ms
tcp_lat:
    latency  =  2.08 ms
tcp_lat:
    latency  =  3.39 ms
tcp_lat:
    latency  =  6.78 ms
tcp_lat:
    latency  =  13.4 ms

**The following is the test result for pod to pod access in the same node, the max bandwidth is 4.96GB/sec.**
[root@clusterhealthy bin]# qperf -oo  msg_size:1:2M:*2  10.244.243.133 tcp_bw tcp_lat
tcp_bw:
    bw  =  2.08 MB/sec
tcp_bw:
    bw  =  4.57 MB/sec
tcp_bw:
    bw  =  9.01 MB/sec
tcp_bw:
    bw  =  18.7 MB/sec
tcp_bw:
    bw  =  32.2 MB/sec
tcp_bw:
    bw  =  51.4 MB/sec
tcp_bw:
    bw  =  90.4 MB/sec
tcp_bw:
    bw  =  125 MB/sec
tcp_bw:
    bw  =  239 MB/sec
tcp_bw:
    bw  =  147 MB/sec
tcp_bw:
    bw  =  157 MB/sec
tcp_bw:
    bw  =  199 MB/sec
tcp_bw:
    bw  =  497 MB/sec
tcp_bw:
    bw  =  779 MB/sec
tcp_bw:
    bw  =  1.63 GB/sec
tcp_bw:
    bw  =  2.83 GB/sec
tcp_bw:
    bw  =  3.7 GB/sec
tcp_bw:
    bw  =  4.21 GB/sec
tcp_bw:
    bw  =  4.68 GB/sec
tcp_bw:
    bw  =  4.96 GB/sec
tcp_bw:
    bw  =  4.59 GB/sec
tcp_bw:
    bw  =  3.77 GB/sec
tcp_lat:
    latency  =  14 us
tcp_lat:
    latency  =  14.2 us
tcp_lat:
    latency  =  12.2 us
tcp_lat:
    latency  =  13.2 us
tcp_lat:
    latency  =  11.7 us
tcp_lat:
    latency  =  10.7 us
tcp_lat:
    latency  =  13.1 us
tcp_lat:
    latency  =  10.7 us
tcp_lat:
    latency  =  12.3 us
tcp_lat:
    latency  =  12.1 us
tcp_lat:
    latency  =  13.3 us
tcp_lat:
    latency  =  16.5 us
tcp_lat:
    latency  =  19.5 us
tcp_lat:
    latency  =  22 us
tcp_lat:
    latency  =  26.2 us
tcp_lat:
    latency  =  27.8 us
tcp_lat:
    latency  =  29.3 us
tcp_lat:
    latency  =  44.8 us
tcp_lat:
    latency  =  110 us
tcp_lat:
    latency  =  185 us
tcp_lat:
    latency  =  319 us
tcp_lat:
    latency  =  660 us

**The test result for the access from one node to one pod in another node, the max bandwidth is 182MB/Sec**
[root@docker01 ~]# qperf -oo  msg_size:1:2M:*2  10.244.180.4 tcp_bw tcp_lat
tcp_bw:
    bw  =  2.01 MB/sec
tcp_bw:
    bw  =  4.12 MB/sec
tcp_bw:
    bw  =  7.9 MB/sec
tcp_bw:
    bw  =  15 MB/sec
tcp_bw:
    bw  =  24.8 MB/sec
tcp_bw:
    bw  =  42.4 MB/sec
tcp_bw:
    bw  =  70.6 MB/sec
tcp_bw:
    bw  =  107 MB/sec
tcp_bw:
    bw  =  140 MB/sec
tcp_bw:
    bw  =  154 MB/sec
tcp_bw:
    bw  =  176 MB/sec
tcp_bw:
    bw  =  182 MB/sec
tcp_bw:
    bw  =  179 MB/sec
tcp_bw:
    bw  =  181 MB/sec
tcp_bw:
    bw  =  180 MB/sec
tcp_bw:
    bw  =  178 MB/sec
tcp_bw:
    bw  =  154 MB/sec
tcp_bw:
    bw  =  181 MB/sec
tcp_bw:
    bw  =  168 MB/sec
tcp_bw:
    bw  =  169 MB/sec
tcp_bw:
    bw  =  169 MB/sec
tcp_bw:
    bw  =  156 MB/sec
tcp_lat:
    latency  =  76.9 us
tcp_lat:
    latency  =  81.6 us
tcp_lat:
    latency  =  80.3 us
tcp_lat:
    latency  =  75.8 us
tcp_lat:
    latency  =  78.5 us
tcp_lat:
    latency  =  73.8 us
tcp_lat:
    latency  =  81.9 us
tcp_lat:
    latency  =  82.2 us
tcp_lat:
    latency  =  81.1 us
tcp_lat:
    latency  =  83.7 us
tcp_lat:
    latency  =  83.3 us
tcp_lat:
    latency  =  85.2 us
tcp_lat:
    latency  =  100 us
tcp_lat:
    latency  =  111 us
tcp_lat:
    latency  =  156 us
tcp_lat:
    latency  =  300 us
tcp_lat:
    latency  =  515 us
tcp_lat:
    latency  =  861 us
tcp_lat:
    latency  =  1.5 ms
tcp_lat:
    latency  =  3.09 ms
tcp_lat:
    latency  =  6.19 ms
tcp_lat:
    latency  =  19.2 ms

**The following is the test result for the access from one node to another node.**
[root@docker01 ~]# qperf -oo  msg_size:1:2M:*2  172.16.3.26 tcp_bw tcp_lat
tcp_bw:
    bw  =  2.35 MB/sec
tcp_bw:
    bw  =  4.58 MB/sec
tcp_bw:
    bw  =  8.5 MB/sec
tcp_bw:
    bw  =  16.6 MB/sec
tcp_bw:
    bw  =  32.6 MB/sec
tcp_bw:
    bw  =  52.6 MB/sec
tcp_bw:
    bw  =  102 MB/sec
tcp_bw:
    bw  =  203 MB/sec
tcp_bw:
    bw  =  352 MB/sec
tcp_bw:
    bw  =  600 MB/sec
tcp_bw:
    bw  =  974 MB/sec
tcp_bw:
    bw  =  1.38 GB/sec
tcp_bw:
    bw  =  1.55 GB/sec
tcp_bw:
    bw  =  1.78 GB/sec
tcp_bw:
    bw  =  1.78 GB/sec
tcp_bw:
    bw  =  1.77 GB/sec
tcp_bw:
    bw  =  1.72 GB/sec
tcp_bw:
    bw  =  1.73 GB/sec
tcp_bw:
    bw  =  1.71 GB/sec
tcp_bw:
    bw  =  1.76 GB/sec
tcp_bw:
    bw  =  1.68 GB/sec
tcp_bw:
    bw  =  1.67 GB/sec
tcp_lat:
    latency  =  40.4 us
tcp_lat:
    latency  =  40.3 us
tcp_lat:
    latency  =  40.8 us
tcp_lat:
    latency  =  39.8 us
tcp_lat:
    latency  =  41.3 us
tcp_lat:
    latency  =  41.2 us
tcp_lat:
    latency  =  40.6 us
tcp_lat:
    latency  =  41.7 us
tcp_lat:
    latency  =  41.5 us
tcp_lat:
    latency  =  43.4 us
tcp_lat:
    latency  =  45.4 us
tcp_lat:
    latency  =  56.7 us
tcp_lat:
    latency  =  65.2 us
tcp_lat:
    latency  =  72.2 us
tcp_lat:
    latency  =  89.1 us
tcp_lat:
    latency  =  102 us
tcp_lat:
    latency  =  207 us
tcp_lat:
    latency  =  352 us
tcp_lat:
    latency  =  552 us
tcp_lat:
    latency  =  823 us
tcp_lat:
    latency  =  1.4 ms
tcp_lat:
    latency  =  1.92 ms

The following is the test result for the access from one pod to another node, the max bandwidth is 827Mb/Sec.
[root@docker01 /]# qperf -oo  msg_size:1:2M:*2  172.16.3.26 tcp_bw tcp_lat                                                                                  
tcp_bw:
    bw  =  2.44 MB/sec
tcp_bw:
    bw  =  4.35 MB/sec
tcp_bw:
    bw  =  8.8 MB/sec
tcp_bw:
    bw  =  15.3 MB/sec
tcp_bw:
    bw  =  28.6 MB/sec
tcp_bw:
    bw  =  44.7 MB/sec
tcp_bw:
    bw  =  72.5 MB/sec
tcp_bw:
    bw  =  117 MB/sec
tcp_bw:
    bw  =  161 MB/sec
tcp_bw:
    bw  =  208 MB/sec
tcp_bw:
    bw  =  250 MB/sec
tcp_bw:
    bw  =  358 MB/sec
tcp_bw:
    bw  =  660 MB/sec
tcp_bw:
    bw  =  727 MB/sec
tcp_bw:
    bw  =  748 MB/sec
tcp_bw:
    bw  =  712 MB/sec
tcp_bw:
    bw  =  817 MB/sec
tcp_bw:
    bw  =  827 MB/sec
tcp_bw:
    bw  =  730 MB/sec
tcp_bw:
    bw  =  782 MB/sec
tcp_bw:
    bw  =  783 MB/sec
tcp_bw:
    bw  =  800 MB/sec
tcp_lat:
    latency  =  47.5 us
tcp_lat:
    latency  =  47.2 us
tcp_lat:
    latency  =  45.8 us
tcp_lat:
    latency  =  47.1 us
tcp_lat:
    latency  =  46.8 us
tcp_lat:
    latency  =  47.7 us
tcp_lat:
    latency  =  48.3 us
tcp_lat:
    latency  =  47.5 us
tcp_lat:
    latency  =  49.8 us
tcp_lat:
    latency  =  48.1 us
tcp_lat:
    latency  =  51.9 us
tcp_lat:
    latency  =  71.5 us
tcp_lat:
    latency  =  78.6 us
tcp_lat:
    latency  =  84.5 us
tcp_lat:
    latency  =  93.8 us
tcp_lat:
    latency  =  108 us
tcp_lat:
    latency  =  225 us
tcp_lat:
    latency  =  380 us
tcp_lat:
    latency  =  638 us

[root@docker16 calico]# kubectl get pods --all-namespaces -o wide 
NAMESPACE     NAME                                       READY     STATUS    RESTARTS   AGE       IP               NODE
default       iperf-server-controller-g6x15              1/1       Running   0          23h       10.244.243.131   docker03
kube-system   calico-etcd-r60lq                          1/1       Running   0          1d        172.16.3.93      docker16
kube-system   calico-node-4k6pn                          2/2       Running   0          1d        172.16.3.93      docker16
kube-system   calico-node-h12wt                          2/2       Running   0          1d        172.16.3.26      docker02
kube-system   calico-node-lzhkh                          2/2       Running   1          1d        172.16.3.25      docker01
kube-system   calico-node-rrn0f                          2/2       Running   1          1d        172.16.3.27      docker03
kube-system   calico-policy-controller-441498130-vpnvv   1/1       Running   0          6h        172.16.3.25      docker01
kube-system   clusterhealthy                             1/1       Running   0          5h        10.244.243.132   docker03
kube-system   dns-monitor-6xtsw                          1/1       Running   0          23h       10.244.180.3     docker02
kube-system   docker01                                   1/1       Running   0          5h        10.244.159.197   docker01
kube-system   docker02                                   1/1       Running   0          5h        10.244.180.4     docker02
kube-system   docker03                                   1/1       Running   0          5h        10.244.243.133   docker03
kube-system   docker16                                   1/1       Running   0          5h        10.244.22.197    docker16
kube-system   kube-apiserver-docker16                    1/1       Running   0          1d        172.16.3.93      docker16
kube-system   kube-controller-manager-docker16           1/1       Running   0          1d        172.16.3.93      docker16
kube-system   kube-dns-1033415403-mmt9j                  3/3       Running   0          1d        10.244.22.195    docker16
kube-system   kube-proxy-649hd                           1/1       Running   0          1d        172.16.3.25      docker01
kube-system   kube-proxy-dc62m                           1/1       Running   0          1d        172.16.3.27      docker03
kube-system   kube-proxy-m3rnl                           1/1       Running   0          1d        172.16.3.93      docker16
kube-system   kube-proxy-tnqch                           1/1       Running   0          1d        172.16.3.26      docker02
kube-system   kube-scheduler-docker16                    1/1       Running   0          1d        172.16.3.93      docker16

[root@docker16 calico]# kubectl get nodes
NAME       STATUS    AGE       VERSION
docker01   Ready     1d        v1.7.0
docker02   Ready     1d        v1.7.0
docker03   Ready     1d        v1.7.0
docker16   Ready     1d        v1.7.0

**Comment by ozdanborne** [comment]
A likely reason is that for kubeadm clusters, IP-in-IP encapsulation is enabled by default. If you are in an environment where you can connnect without encapsulation, you could try rerunning the test without IPIP enabled by changing `always` to `off` for the following field in your `calico.yaml`:

```
- name: CALICO_IPV4POOL_IPIP
  value: "always"
```

Note - this setting only applies to the default pool of new clusters. If you are rerunning the tests on a cluster that already has calico installed, you will need to edit the existing Calico pool - the reverse of what is described here: http://docs.projectcalico.org/v2.2/usage/configuration/ip-in-ip

**Comment by haveatry** [comment]
@ozdanborne Thanks for your information. I have rerun the tests as your suggestion. The result looks good now.
