### ISSUE TITLE
How can I renew the calico apiserver cert?

### ISSUE THREAD

**Issue by ryangrahamnc** [projectcalico/calico#9228]
I'm getting this error in my calico-node pods:
`
2024-09-13 02:27:05.909 [WARNING][161478] confd/sync_client.go 158: error connecting to typha endpoint (2 of 2) 192.168.2.22:5473 connID=0x0 error=x509: certificate has expired or is not yet valid: current time 2024-09-13T02:27:05Z is after 2024-08-29T01:41:00Z type="bgp"
`

And if I restart a node, the node's pods no longer get network access. They dont seem to be able to talk on any kube services either. This includes any pods on the kube master after I restarted the master. I've tried `curl google.com` and `curl http://some-other-service:80/`, and everything times out. But the host still has network access, pods boot up properly, and i can exec into pods and view their logs. I just don't have network access once I'm inside the pod.

I've looked at my `calico-apiserver-certs` secret, and checked the tls.crt info with `openssl x509 -in ./the.crt -noout -enddate` and got `notAfter=Aug 29 01:48:02 2024 GMT`. Since the two dates are minutes apart and the pods are having tls connection errors in the logs when talking to calico services, I suspect the expired cert is the problem.

Is there an easy command for renewing this cert? And/or a guide for how to manually handle renewing it? Google didnt turn up anything, but theres a chance I'm not using the best search terms.

## Your Environment
```
$ k get apiservers.operator.tigera.io 
NAME      AGE
default   2y110d
```
```
$ k get secrets -n calico-apiserver        
NAME                     TYPE     DATA   AGE
calico-apiserver-certs   Opaque   2      2y110d
```
```
$ k get ippools.crd.projectcalico.org default-ipv4-ippool -o yaml
apiVersion: crd.projectcalico.org/v1
kind: IPPool
metadata: *snip*
spec:
  allowedUses:
  - Workload
  - Tunnel
  blockSize: 26
  cidr: 10.0.0.0/16
  ipipMode: Always
  natOutgoing: true
  nodeSelector: all()
  vxlanMode: Never

```

* Calico version: v3.23.1
* kubernetes: Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.1", GitCommit:"3ddd0f45aa91e2f30c70734b175631bec5b5825a", GitTreeState:"clean", BuildDate:"2022-05-24T12:18:48Z", GoVersion:"go1.18.2", Compiler:"gc", Platform:"linux/amd64"}
* OS: 22.04.1-Ubuntu

**Comment by ryangrahamnc** [comment]
I tried deleting the secret, but it wouldnt recreate. Idk, maybe it was a different secret I had to delete. Maybe one in the tigera namespace. In retrospect, I should have checked that.

I got everything working by completely removing calico and reinstalling.

For others who stumble on this and want to try the calico reinstall route, I was able to start my uninstall by following the install steps in reverse and using `delete` instead of `create`. The finalizers will hang, unfortunately, so there's manual work that needs to be done.
The namespaces to delete are `calico-apiserver`, `calico-system`, and `tigera-operator`.
A helpful command to see whats still around is:
`kubectl api-resources --verbs=list --namespaced -o name | xargs -n 1 kubectl get -n calico-system` (and do the same for the other namespaces). For me, a serviceaccount that wouldnt delete was causing my last bits of hanging.
There's definitely something wrong with my install now (for instance I now have a `ippools.projectcalico.org` AND a `ippools.crd.projectcalico.org`). But its working now, and I dont want to deal with that crap. Next time kube breaks, I think it'll be fastest to reinstall kube from scratch, and deal with finding all my yamls and re-setting up all my namespaces/deployments.

**Comment by caseydavenport** [comment]
> There's definitely something wrong with my install now (for instance I now have a ippools.projectcalico.org AND a ippools.crd.projectcalico.org).

This part is actually expected. See https://github.com/projectcalico/calico/issues/6412

> Maybe one in the tigera namespace. 

Yes, I should have clarified that this is the correct one to delete to trigger generation of a new certificate.

**Comment by FredNass** [comment]
I just went through this messy path. Deleting the secrets and rolling out/restarting the calico components didn't help, nor did restarting rke2-{server,agent}. I finally fixed the issue by stopping chronyd and setting the nodes to a date before the certificate expiration (date -s '2024-12-20 12:00:00'). I then restarted rke2-{server,agent}, waited 5-10 minutes, then restarted chronyd to force the time update, and finally restarted rke2-{server,agent} again which resolved the issue.

Still, the tls.crt in 'typha-certs' secret (namespace 'calico-system') was not renewed and still show a date in the past.

I wasn't able to get this certificate to regenerate by deleting the 'typha-certs' secret and restarting the calico and tigera-operator components.

Can someone please explain how one can force the renewal of this certificate?

**Comment by zengqingfu1442** [comment]
> I tried deleting the secret, but it wouldnt recreate. Idk, maybe it was a different secret I had to delete. Maybe one in the tigera namespace. In retrospect, I should have checked that.
> 
> I got everything working by completely removing calico and reinstalling.
> 
> For others who stumble on this and want to try the calico reinstall route, I was able to start my uninstall by following the install steps in reverse and using `delete` instead of `create`. The finalizers will hang, unfortunately, so there's manual work that needs to be done. The namespaces to delete are `calico-apiserver`, `calico-system`, and `tigera-operator`. A helpful command to see whats still around is: `kubectl api-resources --verbs=list --namespaced -o name | xargs -n 1 kubectl get -n calico-system` (and do the same for the other namespaces). For me, a serviceaccount that wouldnt delete was causing my last bits of hanging. There's definitely something wrong with my install now (for instance I now have a `ippools.projectcalico.org` AND a `ippools.crd.projectcalico.org`). But its working now, and I dont want to deal with that crap. Next time kube breaks, I think it'll be fastest to reinstall kube from scratch, and deal with finding all my yamls and re-setting up all my namespaces/deployments.

How did you completely removing calico? I cannot delete calico completely after the calico apiserver certificate has expired.
