### ISSUE TITLE
Update docs to use v1 NetworkPolicy API

### ISSUE THREAD

**Issue by caseydavenport** [projectcalico/calico#923]
## Expected Behavior

Should use v1 NetworkPolicy API (see https://github.com/projectcalico/calico/pull/914#discussion_r128005756)

## Current Behavior

Uses v1beta1 API.

## Context

Let's do this once k8s 1.8 is launched. 

## Your Environment

* Calico version
* Orchestrator version (e.g. kubernetes, mesos, rkt):
* Operating System and version:
* Link to your project (optional):

**Comment by vCloudernBeer** [comment]
Do we want to do this after k8s 1.8 is out?  Currently in rev 1.7 the apiVersion is changed from **extensions/v1beta1** to **networking.k8s.io/v1**

I am new to Project Calico and would like to work on documentation changes before driving in to the code.

**Comment by caseydavenport** [comment]
@vCloudernBeer awesome, welcome!

I think it would be good to address this in Calico v2.6, which is the next release and is scheduled to more-or-less coincide with k8s v1.8.0, so I think this is a good one to work on.

CC @emanic

**Comment by vCloudernBeer** [comment]
The documents that needs to be changed is under this tree - https://github.com/projectcalico/calico? I am still trying to understand the tree structure for this project. :) 

Also, should I use slack or IRC to ask questions regarding this issue?

**Comment by emanic** [comment]
CONTRIBUTING_DOCS.md describes the existing doc organizational structure. If you want to contribute to the upcoming release v2.6, you should work in the `master` directory. Thanks @vCloudernBeer !

**Comment by vCloudernBeer** [comment]
Ah, Got it.  thanks so much.

**Comment by tmjd** [comment]
@vCloudernBeer Slack is how most of us interact and there is a bridge to the irc channel in slack. In slack there is a dedicated #calico-dev channel which might be the most appropriate place for discussions.

**Comment by tmjd** [comment]
Since I'm suggesting slack I should probably include a link, slack.projectcalico.org.

**Comment by vCloudernBeer** [comment]
@tmjd Got it. Joined. Have a nice weekend.
