### ISSUE TITLE
Windows Pods IPs Unreachable

### ISSUE THREAD

**Issue by vincent-guillemette-fr** [projectcalico/calico#9272]
Hello Calico, 

Following tutorials found on MicroK8s, I set up a cluster including : 
- 1 Linux Control Plane,
- 1 Windows Worker. 

Linux workloads work like a charm, but when I deploy pods on the Windows node, its IP cannot be reached at all. 

## Expected Behavior
To be able to ping Windows Pods from: 
- Linux Host, 
- Windows Host, 
- Linux Pod. 

## Current Behavior
Can only ping Pod from itself. 

Would you be so kind to help me troubleshoot this behavior ?

**Comment by coutinhop** [comment]
@vincent-guillemette-fr could you please post details about your setup? Calico version, k8s version, Linux distro and version, Windows version, etc...

Taking a (rather wild, from the limited info) guess at what might be wrong, this could be this Windows containers bug https://github.com/microsoft/Windows-Containers/issues/516

Please take a look at this known issue https://github.com/projectcalico/calico/issues/9019 (Windows build 20348.2582 and up seems to break networking), there is a fix on this comment: https://github.com/projectcalico/calico/issues/9019#issuecomment-2341458640

**Comment by vincent-guillemette-fr** [comment]
@coutinhop 
Thank you for helping us. 
I'm afraid I'm a bit confused about all the components of the cluster and the information relevant to each one of them.  

It's resolved, but we applied two fixes at a time, so I don't know which one, if not both, solved the connectivity issue: 
- The bug you referred to : https://github.com/microsoft/Windows-Containers/issues/516, 
- The Network Adapter switch mentioned here: https://ranchermanager.docs.rancher.com/how-to-guides/new-user-guides/kubernetes-clusters-in-rancher-setup/use-windows-clusters#rancher-on-vmware-vsphere-with-esxi-67u2-and-above.

**Comment by vincent-guillemette-fr** [comment]
We rolled back the network adapter switch and can then confirm we were affected by the bug you mentioned. 
Thank you again !
