### ISSUE TITLE
Constant ReadTimeoutError from etcd.client in Felix logs

### ISSUE THREAD

**Issue by dragonde** [projectcalico/calico#930]
I get constant errors like in calico/felix logs:

2015-12-03 10:52:19,597 [ERROR][30/1] etcd.client 776: Request to server http://10.131.121.96:2379 failed: ReadTimeoutError("HTTPConnectionPool(host='10.131.121.96', port=2379): Read timed out.",)

However the etcd is up and working:

curl  http://10.131.121.96:2379/version
{"etcdserver":"2.2.2","etcdcluster":"2.2.0"}

**Comment by fasaxc** [comment]
The errors are benign. Simply over zealous logging in python-etcd.

They've been fixed already in python-etcd but I'm not sure if they've released the fix yet.

**Comment by fasaxc** [comment]
Fixed upstream in https://github.com/jplana/python-etcd/pull/135 and released in python-etcd 0.4.3.
