### ISSUE TITLE
node is not ready felix is not ready

### ISSUE THREAD

**Issue by zlluye** [projectcalico/calico#9337]
system version: centos7.9
k8s version: 1.24
calico version: 3.20.1

I have a standalone Kubernetes cluster that has been running for 2 years. Recently, after a reboot, I found that calico-node is unable to start normally. The error message is as follows. 
why  does the  hostip_mgr.go  recognize the lo IP as 127.0.0.0?  None of my device have 127.0.0.0 ip address
<img width="1694" alt="image" src="https://github.com/user-attachments/assets/b95c7370-9839-4ede-8147-d2bd578bacc7">
<img width="1705" alt="image" src="https://github.com/user-attachments/assets/714a9314-afaa-49f2-8313-705994fdaa7c">

**Comment by mazdakn** [comment]
@zlluye Calico version v3.20 is very old. Please upgrade to a newer and supported version like v3.28.
