### ISSUE TITLE
The performance of pod-to-pod communication across nodes significantly decreases when using Always mode compared to CrossSubnet mode for IP pools in VXLAN.

### ISSUE THREAD

**Issue by ayewwww** [projectcalico/calico#9341]
## Expected Behavior

The communication rate between pods across nodes must reach gigabit levels.
![image](https://github.com/user-attachments/assets/26abda54-e462-465f-b18e-eb290b3fe3fa)

## Current Behavior

![image](https://github.com/user-attachments/assets/3bd12151-e6fc-4aff-aa6b-f79678194a69)

## Steps to Reproduce (for bugs)

1. 
![image](https://github.com/user-attachments/assets/c5b0a958-93d8-4150-9459-dc7ba2f7a701)

2.
![image](https://github.com/user-attachments/assets/88e97536-3f5c-42ff-b954-e76cd5dbb0d3)

3.
![image](https://github.com/user-attachments/assets/eb2f7241-cc84-436e-aca7-973b28d8368b)
![image](https://github.com/user-attachments/assets/3ebb2334-334d-48e9-8074-d0e7ea1b024c)

4.

## Your Environment

* Calico version
* Calico dataplane (iptables, windows etc.)
* Orchestrator version (e.g. kubernetes, mesos, rkt):
* Operating System and version:
* Link to your project (optional):

**Comment by ayewwww** [comment]
node1: 10.0.102.61/24, node2: 10.0.102.62/24

**Comment by ayewwww** [comment]
![image](https://github.com/user-attachments/assets/3d8b1ad4-59ba-4160-a7ba-b5bedad57e02)
![image](https://github.com/user-attachments/assets/5df35793-af73-497b-a861-254fa71d2859)
When using VXLAN in "always" mode, the performance loss is too severe.

**Comment by MichalFupso** [comment]
Hi @ayewwww, can you please share more about your environment, what version and installation of Calico are you using? Have you made any changes to the Calico Network mtu spec?

**Comment by ayewwww** [comment]
> 你好@ayewwww，您能否分享更多关于您的环境的信息，您使用的是哪个版本的 Calico？您对 Calico Network mtu 规范做过任何更改吗？

calico version3.26.4，kernel5.10，no modifications have been made to the Calico MTU

**Comment by ayewwww** [comment]
> Hi @ayewwww, can you please share more about your environment, what version and installation of Calico are you using? Have you made any changes to the Calico Network mtu spec?

![image](https://github.com/user-attachments/assets/448f1aec-821b-469c-8a5b-69d299fc08c6)

**Comment by caseydavenport** [comment]
This sounds most likely to be an MTU tuning issue - the VXLAN device's MTU is set to 1450, what is your default interface's MTU?

You may need to adjust the VXLAN MTU in FelixConfiguration as described in this document: https://docs.tigera.io/calico/latest/networking/configuring/mtu

**Comment by ayewwww** [comment]
> This sounds most likely to be an MTU tuning issue - the VXLAN device's MTU is set to 1450, what is your default interface's MTU?
> 
> You may need to adjust the VXLAN MTU in FelixConfiguration as described in this document: https://docs.tigera.io/calico/latest/networking/configuring/mtu

The MTU has not been changed; the default is 1450.

**Comment by caseydavenport** [comment]
If your default interface's MTU is 1450, then your VXLAN tunnel device MTU needs to be 50 bytes less than that - 1400 - else you will get fragementation, leading to substantial performance degradation.

**Comment by ayewwww** [comment]
> If your default interface's MTU is 1450, then your VXLAN tunnel device MTU needs to be 50 bytes less than that - 1400 - else you will get fragementation, leading to substantial performance degradation.

I don’t think it’s the main reason. After I changed the mtu of the VXLAN tunnel to 1400, the bandwidth is still low.
![image](https://github.com/user-attachments/assets/41135d50-68c7-404c-89ef-d7874fb1acf0)
Then, I tested the UDP bandwidth of several groups of physical networks, and the bandwidth was also very low. I guess this is the main reason.

**Comment by ayewwww** [comment]
> > If your default interface's MTU is 1450, then your VXLAN tunnel device MTU needs to be 50 bytes less than that - 1400 - else you will get fragementation, leading to substantial performance degradation.
> 
> I don’t think it’s the main reason. After I changed the mtu of the VXLAN tunnel to 1400, the bandwidth is still low. ![image](https://private-user-images.githubusercontent.com/59998764/385694954-41135d50-68c7-404c-89ef-d7874fb1acf0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE0OTEyNjYsIm5iZiI6MTczMTQ5MDk2NiwicGF0aCI6Ii81OTk5ODc2NC8zODU2OTQ5NTQtNDExMzVkNTAtNjhjNy00MDRjLTg5ZWYtZDc4NzRmYjFhY2YwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTEzVDA5NDI0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY1OGZkMzNiYjI4M2RkMTIwNjk3MDE2Mzc0NTYxNzgzNjlhNzM0NDRjZmViZGRhOTEyYmE5N2Q3ODE3ZGMzYTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.8QQbyny7Oy5v9EZiguzPcrdND5VanKOaa8I_RpLORA8) Then, I tested the UDP bandwidth of several groups of physical networks, and the bandwidth was also very low. I guess this is the main reason.

The cross-node bandwidth of pod VXLAN is close to the UDP bandwidth of the physical network. I guess this is the bottleneck
