### ISSUE TITLE
Suggested manifest for flannel-migration is unusable

### ISSUE THREAD

**Issue by dimastty** [projectcalico/calico#9358]
https://docs.tigera.io/calico/latest/getting-started/kubernetes/flannel/migration-from-flannel
suggests that manifest 
https://raw.githubusercontent.com/projectcalico/calico/v3.28.2/manifests/flannel-migration/migration-job.yaml
should be applied.
However,  container image in that manifest turned out to be 
`          image: calico/flannel-migration-controller:master`
which is incompatible with CRD defined in the v3.28.2/manifests/flannel-migration/calico.yaml
User "system:serviceaccount:kube-system:flannel-migration-controller" cannot create resource "tiers" in API group "crd.projectcalico.org" at the cluster scope

**Comment by caseydavenport** [comment]
@dimastty yep, this is unfortunately a known issue with that release. 

You should be able to modify the image to v3.28.2 in order to get the correct code. 

@lwr20 have we fixed the root cause of this do you know?

**Comment by caseydavenport** [comment]
We did fix the root cause of this in this PR: https://github.com/projectcalico/calico/pull/9263

And cherry-picked it to supported branches. Just pending a new release. In the meantime, you can update the image version in the shipped manifest.
