### ISSUE TITLE
Improve ST tests for multiple CIDRs

### ISSUE THREAD

**Issue by fasaxc** [projectcalico/calico#936]
The tests for multiple CIDRs could do with beefing up as per @lwr20's suggestion:

Tests we might like to add:
Rules with:

- [ ] CIDRs other than /32
- [ ] the same CIDR twice
- [ ] overlapping CIDRs
- [ ] Evil CIDRs: (to check libcalico-go's validation is plumbed through OK)
- [ ] 0/0
- [ ] a couple of invalid CIDRs:
- [ ] /33+
- [ ] too many octets

**Comment by caseydavenport** [comment]
@fasaxc @lwr20 does this still apply? What sorts of CIDRs are we referring to here?

I think the validation aspects of this are covered in libcalico-go tests. Please close if you think there's nothing meaningful left to do here. If there is some important coverage we're missing then could you add a bit more detail to what sorts of tests we'd actually want to write?

**Comment by lwr20** [comment]
Fairly sure this refers to the tests now living in projectcalico/node.

While these validation tests may be covered in libcalico-go, `Evil CIDRs: (to check libcalico-go's validation is plumbed through OK)` sounds like it would still be a useful check to have in the node tests.

**Comment by caseydavenport** [comment]
I'm going to close this since the validation aspect is covered in existing tests in libcalico, and the plumbing through of libcalico into other repositories is also covered in each of those repos.
