### ISSUE TITLE
How to modify the Calico Node environment variables in an operator deployment.

### ISSUE THREAD

**Issue by ayewwww** [projectcalico/calico#9369]
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Calico version
* Calico dataplane (iptables, windows etc.)
* Orchestrator version (e.g. kubernetes, mesos, rkt):
* Operating System and version:
* Link to your project (optional):

**Comment by caseydavenport** [comment]
Please fill out the issue template for future issues.

Directly modifying the calico/node environment variables is not supported in the operator install, but it is likely that what you are trying to do is possible via the operator API. Hard to know without more info though!
