### ISSUE TITLE
Blocking ICMP via calicoctl doesn't block ICMPv6

### ISSUE THREAD

**Issue by Brook-Roberts** [projectcalico/calico#938]
Using a docker setup with two hosts, connected with IPv6 networking.

Ran command: "calicoctl profile groupF rule add inbound deny icmp"

This blocks protocol ICMP in iptables, and in ip6tables.

Expected behaviour is probably that ICMPv6 is blocked in ip6tables (and if not, there should probably be an option in calicoctl for specifically blocking ICMPv6).

**Comment by alexwlchan** [comment]
Should this be filed against the calico-docker repo instead? Sounds like it’s a calicoctl problem, not a Felix problem.

**Comment by fasaxc** [comment]
Investigated some more.  The Felix code is expecting "icmpv6" as the protocol but that's the wrong value for the kernel so it wouldn't work even if calicoctl was setting that.

**Comment by fasaxc** [comment]
Blocked on merge of #942, which reworks the relevant code substantially.

**Comment by fasaxc** [comment]
Given that we've also had issues with /etc/protocols being missing ipip, for example, I think the right fix is probably to introduce a mapping dict that maps our etcd values to the protocol numbers (depending on the IP version).

```
{
    (4, icmp): 1,

    (6, icmp): 58,
    (6, icmpv6): 58,
    (6, ipv6-icmp): 58,

  ...
}
```

**Comment by fasaxc** [comment]
Ah, the kernel has its own guaranteed whitelist, which is baked in so that's where the icmpv6/ipv6-icmp conflict comes from.

**Comment by fasaxc** [comment]
Now blocked on discussion with calicoctl team to decide where we make the fix.

**Comment by fasaxc** [comment]
Fixed in calicoctl.
