### ISSUE TITLE
calico-apiserver manifests are missing permissions for 'tiers'

### ISSUE THREAD

**Issue by sebhoss** [projectcalico/calico#9481]
The manifest at https://github.com/projectcalico/calico/blob/master/manifests/apiserver.yaml and its released siblings do not allow the calico-apiserver to create resources of type 'tiers' resulting in the following error upon start:

```shell
time="2024-11-15T07:20:58Z" level=info msg="Unable to initialize adminnetworkpolicy Tier" func=github.com/projectcalico/calico/libcalico-go/lib/clientv3.client.EnsureInitialized file="/go/src/github.com/projectcalico/calico/libcalico-go/lib/clientv3/client.go:258" error="connection is unauthorized: tiers.crd.projectcalico.org is forbidden: User \"system:serviceaccount:calico-apiserver:calico-apiserver\" cannot create resource \"tiers\" in API group \"crd.projectcalico.org\" at the cluster scope"
E1115 07:20:58.943546       1 resource.go:106] Failed initializing client: "connection is unauthorized: tiers.crd.projectcalico.org is forbidden: User \"system:serviceaccount:calico-apiserver:calico-apiserver\" cannot create resource \"tiers\" in API group \"crd.projectcalico.org\" at the cluster scope"
```

## Expected Behavior

calico-apiserver should start fine

## Current Behavior

calico-apiserver cannot start

## Possible Solution

Do the same change as https://github.com/projectcalico/calico/commit/48746c1e3bb54011ed9cc671053ff0ffc2a9a686 for calico-apiserver

## Steps to Reproduce (for bugs)

1. Install calico-apiserver from https://github.com/projectcalico/calico/blob/master/manifests/apiserver.yaml
2. View logs of calico-apiserver

**Comment by mazdakn** [comment]
@sebhoss Thanks for reporting this and also providing the fix.

**Comment by mazdakn** [comment]
The fix will be available in v3.29.1 patch release.

**Comment by sinawic** [comment]
@mazdakn 
hi
i am still getting the same error in `quay.io/calico/cni:v3.29.1`

**Comment by krishnakc1** [comment]
> [@mazdakn](https://github.com/mazdakn) hi i am still getting the same error in `quay.io/calico/cni:v3.29.1`
> 
> ```
> 2025-02-04 14:06:31.320 [WARNING][1] kube-controllers/client.go 417: Unauthorized to create tier adminnetworkpolicy. error=connection is unauthorized: tiers.crd.projectcalico.org is forbidden: User "system:serviceaccount:kube-system:calico-kube-controllers" cannot create resource "tiers" in API group "crd.projectcalico.org" at the cluster scope
> ```

+1. I see too but it is displayed as warning in v3.29.1

**Comment by Searge** [comment]
+1 have the same error:

```bash
❯ k get daemonset -n kube-system calico-node -o jsonpath='{.spec.template.spec.containers[?(@.name=="calico-node")].image}'
quay.io/calico/node:v3.29.1
```

**Comment by caseydavenport** [comment]
It was a manifest fix - have you updated the ClusterRole as well as the image?
