### ISSUE TITLE
rc tag names are wrong.

### ISSUE THREAD

**Issue by matthewdupre** [projectcalico/calico#950]
Readthedocs requires pre-release tag names to obey a certain (PEP440) format.  Ours don't, so our stable track doesn't follow the right versions.

For example, 1.3.0 pre-release 5 should be tagged as 1.3.0b5 (or a5).

http://docs.readthedocs.org/en/latest/versions.html

**Comment by fasaxc** [comment]
@matthewdupre if you understand the issue, why can't you just fix it?

**Comment by matthewdupre** [comment]
We've now created properly numbered releases that follow all the bad ones.  We need to make sure we continue to use the right format (X.Y.ZbN) in future, but readthedocs should now be back on track.
