### ISSUE TITLE
Application photo shows Calico VXLAN network card packet loss, how can I troubleshoot

### ISSUE THREAD

**Issue by smallemployees** [projectcalico/calico#9511]
## Expected Behavior

Application photo shows Calico VXLAN network card packet loss, how can I troubleshoot
## Current Behavior

After running the application for a period of time, ping packet loss exceeds 20%, but restarting the application can restore it
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Calico version  v2.23.2
* Calico dataplane (iptables, windows etc.)
* Orchestrator version (e.g. kubernetes, mesos, rkt):
* Operating System and version:
* Link to your project (optional):

**Comment by sridhartigera** [comment]
calico 3.23.2 is old. Can you try with latest version?
