### ISSUE TITLE
Classic Calico-Installation  (kubectl apply) should have a smaller footprint 

### ISSUE THREAD

**Issue by erkules** [projectcalico/calico#9517]
In CAPI there is a way to deploy K8s-objects using ConfigMaps (via ClusterRessourceSets).
The K8s-obejects to deploy Calico are above that 1MB limit for storing Objects in etcd.

~~~
$ du -sh tigera-operator.yaml 
1,6M    tigera-operator.yaml
~~~

Cilium uses not so much:

~~~
$ du -sh cilium.yaml 
64K     cilium.yaml
~~~

It would be nice to have a smaller footprint to deploy calico via ClusterRessourceSets in CAPI.

**Comment by caseydavenport** [comment]
This PR removes all of the CRD content from tigera-operator.yaml: https://github.com/projectcalico/calico/pull/9518
