### ISSUE TITLE
[v3.28.2 -> v3.29.1] tigera-operator: Pods fail to start due to missing default Tier resource

### ISSUE THREAD

**Issue by SB-MFJ** [projectcalico/calico#9520]
## Expected Behavior

Updating to 3.29.x should create the default Tier resource and update CRD's.

## Current Behavior

attempting to update the tigera-operator installation from 3.28.2 to 3.29.1 pods spin up with

```
Failed to initialize datastore error=resource does not exist: Tier(default) with error: the server could not find the requested resource (post Tiers.crd.projectcalico.org)
```

I tried looking for what the [default level 1,000,000](https://docs.tigera.io/calico/latest/network-policy/policy-tiers/tiered-policy#the-default-tier) to manually create it but was not able to find it and I'm not seeing that CRD under `crd.projectcalico.org` after updating to 3.29.1.

## Steps to Reproduce (for bugs)

We manage things in terragrunt/tofu, this is all the installation values we specify:

```terraform
# terragrunt.hcl
# ...
inputs = {
  openid_url = dependency.k8_cluster.outputs.openid_url
  openid_arn = dependency.k8_cluster.outputs.openid_arn

  chart_version = "3.28.2"
}
```

```terraform
# main.tf
provider "helm" {
  kubernetes {
    config_path = "~/.kube/config"
  }
}

locals {
  namespace_tigera = "tigera-operator"
}

resource "kubernetes_namespace" "namespace_tigera" {
  metadata {
    labels = {
      "kubernetes.io/metadata.name" = local.namespace_tigera
      name = local.namespace_tigera
      "pod-security.kubernetes.io/enforce" = "privileged"
    }

    name = local.namespace_tigera
  }
}

resource "helm_release" "tigera-operator" {
  name       = "tigera-operator"
  namespace  = kubernetes_namespace.namespace_tigera.metadata[0].name
  repository = "https://projectcalico.docs.tigera.io/charts"
  chart      = "tigera-operator"
  version    = var.chart_version

  # https://projectcalico.docs.tigera.io/reference/installation/api#operator.tigera.io/v1.InstallationSpec
  values = [<<-VALUES
  installation:
    kubernetesProvider: EKS
    calicoNetwork:
      bgp: Disabled
      linuxDataplane: Iptables
    cni:
      ipam:
        type: AmazonVPC
      type: AmazonVPC
    flexVolumePath: None
    nodeUpdateStrategy:
      rollingUpdate:
        maxUnavailable: 1
      type: RollingUpdate
    variant: Calico
  VALUES
  ]
}
```

## Context

Cannot update, need calico for outside k8s comms.

## Your Environment

* Calico version
  * 3.28.2
* Calico dataplane (iptables, windows etc.)
  * linux Iptables
* Orchestrator version (e.g. kubernetes, mesos, rkt):
  * kubernetes
* Operating System and version:

```
terragrunt version v0.69.0
OpenTofu v1.8.5
on darwin_arm64
+ provider registry.opentofu.org/hashicorp/aws v5.77.0
+ provider registry.opentofu.org/hashicorp/helm v2.16.1
+ provider registry.opentofu.org/hashicorp/kubernetes v2.33.0
```

**Comment by caseydavenport** [comment]
Thanks for raising this. Will look into the cause - it sounds like the Tier CRD isn't being created. You should be able to create it yourself if you'd like to make progress by applying this YAML file (highlighting specifically the Tier CRD within) https://github.com/projectcalico/calico/blob/v3.29.1/manifests/operator-crds.yaml#L21036-L21098

**Comment by caseydavenport** [comment]
It's a bit odd - the Tier CRD is present within the helm chart source: https://github.com/projectcalico/calico/tree/v3.29.1/libcalico-go/config/crd

**Comment by SB-MFJ** [comment]
Good call, I likely glazed over it since we're on 3.28.
Will report back after our maintenance.

**Comment by SB-MFJ** [comment]
That did it. Sorry folks my bad!
