### ISSUE TITLE
Run with PyPy by default

### ISSUE THREAD

**Issue by thedrow** [projectcalico/calico#954]
Since this project can be used in companies where network throughput is important we need to be able to juice as much power as possible from calico.
PyPy runs 10x times faster than Calico. It seems that every dependency you have is either pure python or CFFI based. Therefore, I see no reason why this project shouldn't be targeted to PyPy by default.
We can ship our containers with it as well so there's no issue of whether PyPy is available on the system or not.
What do you guys think?

**Comment by Lukasa** [comment]
@thedrow The Felix component of Calico, at the very least, has supported PyPy in some form for more than a year. However, there are some unfortunate interactions with gevent that make it very hard to productise that support: gevent does not play nicely with PyPy. Support for PyPy has come out recently, but it's not really there yet and IIRC @fasaxc has had to disable PyPy from the continuous integration server.

However, you're welcome to try using PyPy to see how it goes for you!

**Comment by thedrow** [comment]
That's a shame.
I think we should keep this open until gevent works well with PyPy.

**Comment by lxpollitt** [comment]
@thedrow Note that Calico's Python code is control plane only and is not involved in any data plane paths, so there shouldn't be any impact on network throughput.  When you say "juice as much power as possible from calico" is it network throughput you are mostly focussed on, or are there other elements of Calico's performance that are high priority for you too?

**Comment by thedrow** [comment]
network and some control aspects. Sometimes fast orchestration means you're able to boot containers more quickly and hook them up to the relevant components of the system. That means that autoscaling is more responsive and it can be the difference between an outage and an operational system.
This is why people are trying to minimize the size of their containers so bad. They want to be able to pull them as quickly as possible.

**Comment by fasaxc** [comment]
@thedrow We scale tested with PyPy but it didn't show the benefits we'd hoped.

* It did run faster (maybe 1-2x but not 10x).  Some of our code is not suited to PyPy, in particular, we make heavy use of the logging module, which is slow in PyPy.
* It was a lot less predictable, with long pauses (maybe for GC or gevent scheduling issues?) and performance seemed to degrade over time.
* It used a *lot* more RAM, maybe 10x.

@Lukasa is right that we had to disable PyPy UT support for now because there's a gevent/pypy incompatibility tracked by #955.

**Comment by thedrow** [comment]
Have you tried switching it with logbook? It's a much better logging library.
Also if the logging module is slow on PyPy they would consider this to be a bug. Have you considered filing an issue? Higher memory usage could be related to gevent not releasing some of it's memory. Have we run calico with valgrind? If the high memory usage stems from PyPy itself then they will also probably consider this a bug.
It's easy to debug GC issues. Just set PYPY_GC_DEBUG to 1 to see large collections or 2 to see all collections. vmprof will indicate if the pauses are greenlet related.
See http://doc.pypy.org/en/latest/gc_info.html and https://vmprof.readthedocs.org/en/latest/

**Comment by fasaxc** [comment]
@thedrow thanks for the tips.  We haven't tried logbook but it looks interesting.

What sort of container startup rates are you aiming for?  We've done a lot of work in the upcoming 1.3 release to improve our performance under heavy churn.

**Comment by thedrow** [comment]
It depends on how large is the traffic spike. We need to be able to boot as quickly as possible.

**Comment by fasaxc** [comment]
@thedrow sure, but what order of magnitude?  1/s 10/s 100/s 1000/s?

**Comment by thedrow** [comment]
Between 10/s and 100/s. An autoscaling event with 1000 containers that need to boot as soon as possible is Facebook/Google scale. The question is if we want to be able to support that as well.

**Comment by fasaxc** [comment]
Our scale is somewhere between 100 and 1000/s right now in 1.3-pre but he bottleneck isn't felix so I'm going to close this because we already meet the scale goal without PyPy (and PyPy has other drawbacks, such as large occupancy and sketchy gevent support).
