### ISSUE TITLE
The `birdcl show status` command doesn't print GR state

### ISSUE THREAD

**Issue by promacanthus** [projectcalico/calico#9550]
## Expected Behavior

From the source code, there is an example output from bird:

https://github.com/projectcalico/calico/blob/release-v3.27/node/pkg/health/bird/bird.go#L72

```
	// The following is sample output from BIRD
	//
	// 0001 BIRD v0.3.2+birdv1.6.3 ready.
	// 1000-BIRD v0.3.2+birdv1.6.3
	// 1011-Router ID is 172.18.0.4
	// 	 Current server time is 2018-04-03 22:59:51
	// 	 Last reboot on 2018-04-03 22:59:26
	// 	 Last reconfiguration on 2018-04-03 22:59:26
	// 0024-Graceful restart recovery in progress
	// 	   Waiting for 1 protocols to recover
	// 	   Wait timer is 215/240
	// 0013 Daemon is up and running
```

In the line that starts with 0024, we can see the graceful restart state.

## Current Behavior

Run the following command:

```
kubectl -n kube-system exec calico-node-xxx -- birdcl show status

Defaulted container "calico-node" out of: calico-node, upgrade-ipam (init), install-cni (init), mount-bpffs (init)
BIRD v0.3.3+birdv1.6.8 ready.
BIRD v0.3.3+birdv1.6.8
Router ID is 10.112.77.12
Current server time is 2024-12-03 07:25:49
Last reboot on 2024-11-14 19:47:51
Last reconfiguration on 2024-11-27 12:34:51
Daemon is up and running
```

The graceful restart state is missing from the output.

## Context

We want to check the BGP connection state and graceful restart state at each calico-node.

Run 'birdcl show protocols' command and the output matches our expectation.

```
Defaulted container "calico-node" out of: calico-node, upgrade-ipam (init), install-cni (init), mount-bpffs (init)
BIRD v0.3.3+birdv1.6.8 ready.
name     proto    table    state  since       info
static1  Static   master   up     2024-11-14
kernel1  Kernel   master   up     2024-11-14
device1  Device   master   up     2024-11-14
direct1  Direct   master   up     2024-11-14
Node_10_x_x_x BGP      master   up     2024-11-14  Established
Node_10_x_x_x BGP      master   up     2024-11-14  Established
```

When running 'birdcl show status' command, the graceful restart state is not displayed in the output.

Have we missed any required configurations for calico-node?

## Your Environment

* Calico version: `v3.27.2`
* Calico dataplane (iptables, windows etc.): `iptables`
* Orchestrator version (e.g. kubernetes, mesos, rkt): `kubernetes`
* Operating System and version: `Linux  5.10.134-16.3.an8.x86_64 GNU/Linux`

**Comment by mazdakn** [comment]
@promacanthus I believe that line is added when a graceful restart is in progress, otherwise it's not included. Is it missing for you during a GR?

**Comment by promacanthus** [comment]
> @promacanthus I believe that line is added when a graceful restart is in progress, otherwise it's not included. Is it missing for you during a GR?

I'm not sure if this line is missed during a graceful restart.

Maybe there is someting misunderstanding about the graceful restart.

How can I trigger  a graceful restart, for example deleting the Calico pod?  When the Calico pod is terminating, I cannot run `birdcl show status` to check the BIRD status.

---
I also want to know how to verify if the GR state is preserved on the BIRD side.
