### ISSUE TITLE
calico-node can't running with the segfault

### ISSUE THREAD

**Issue by cyclinder** [projectcalico/calico#9562]
## Expected Behavior

Calico running well

## Current Behavior

![Uploading image.png…]()

*  contained logs: 
```
12.05 11:16:18 global containerd[1193542]: time="2024-12-05T11:16:18.207483076+08:00" level=debug msg="received exit event container_id:\"f53d890f75b347bc05c84ba0668556119d09354bc2fb47c33e59626a20f5818a\"  id:\"f53d890f75b347bc05c84ba0668556119d09354bc2fb47c33e59626a20f5818a\"  pid:1224399  exit_status:139  exited_at:{seconds:1733368578  nanos:207273523}"
```

* demsg:

```
[   34.571651] start_runit[17224]: segfault at 563ffe4fa320 ip 00007f3e7cab1ead sp 00007fffad0185a8 error 4 in libc-2.28.so[7f3e7ca8d000+1cd000]
[   34.571658] Code: 00 00 0f 18 4e 40 0f 18 8e 40 10 00 00 0f 18 8e 40 20 00 00 0f 18 8e 40 30 00 00 0f 10 06 0f 10 4e 10 0f 10 56 20 0f 10 5e 30 <0f> 10 a6 00 10 00 00 0f 10 ae 10 10 00 00 0f 10 b6 20 10 00 00 0f
[   56.180195] start_runit[17954]: segfault at 557292dad320 ip 00007f9783966ead sp 00007ffceafd7ec8 error 4 in libc-2.28.so[7f9783942000+1cd000]
[   56.180201] Code: 00 00 0f 18 4e 40 0f 18 8e 40 10 00 00 0f 18 8e 40 20 00 00 0f 18 8e 40 30 00 00 0f 10 06 0f 10 4e 10 0f 10 56 20 0f 10 5e 30 <0f> 10 a6 00 10 00 00 0f 10 ae 10 10 00 00 0f 10 b6 20 10 00 00 0f
```

* ldd version:

```
~# ldd --version
ldd ( GNU libc ) 2.28
```

*uname -a

![Uploading image.png…]()

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Calico version
* Calico dataplane (iptables, windows etc.)
* Orchestrator version (e.g. kubernetes, mesos, rkt):
* Operating System and version:
* Link to your project (optional):

**Comment by caseydavenport** [comment]
@cyclinder hm, your images are dead links for me.

Do you have Calico logs for when this is happening?

**Comment by caseydavenport** [comment]
Also any additional information - e.g., is this BPF / iptables / nftables mode? kernel version? other environmental information - would all be useful!

**Comment by cyclinder** [comment]
Thanks @caseydavenport, calico has not shown any logs when this is happening, but this issue has been resolved. This should be a hardware problem, after we changed the brand of the network card on the host to intel, calico worked fine.

**Comment by caseydavenport** [comment]
@cyclinder glad it's working now! I think I'm going to close this then since it seems network card related and there's not much action we can take at the moment.
