### ISSUE TITLE
Docs don't mention that HostEndpoints don't work in a KDD system

### ISSUE THREAD

**Issue by lwr20** [projectcalico/calico#957]
I set up a system using KDD.  

I attempted to configure host end points on it using calicoctl (following http://docs.projectcalico.org/v2.4/getting-started/bare-metal/bare-metal ) .  

calicoctl said that it had "Successfully applied 1 'hostEndpoint' resource(s)" but `calicoctl get hep` persistently showed no host endpoints. 

Turns out that KDD doesn't support hostEndpoints.  Would have been nice if 
1) the doc above had said this and 
2) that calicoctl had told me that it wouldn't work.

This is made worse by the new PreDNAT policies feature in 2.4 - because they don't work in KDD either.

**Comment by robbrockbank** [comment]
@lwr20 :  Does `calicoctl` really not report that it isn't valid to Create?

With the master build of calicoctl (which shouldn't be any different from the latest RC), I get:

```
$ dist/calicoctl-darwin-amd64 create -f -
apiVersion: v1
kind: hostEndpoint
metadata:
  name: eth1
  node: node1
spec:
  interfaceName: eth1
Failed to create 'hostEndpoint' resource: operation Create is not supported on HostEndpoint(node=node1, name=eth1)
```

I think create/apply/update/delete for the HostEndpoints should all fail.

Docs def. need updating though.

**Comment by lwr20** [comment]
I'm certain it didn't report that it wasn't valid to create.  I was using the amd64 version though, not the darwin version.

**Comment by caseydavenport** [comment]
@lwr20 did you by chance have calicoctl accidentally pointing at an etcd cluster?  If so it would have succeeded, but done nothing.

**Comment by lwr20** [comment]
Pretty sure it was configured correctly.  Before trying to add a host endpoint, I'd done `calicoctl get wep` - and it was showing the endpoints I expected to see.

**Comment by robbrockbank** [comment]
@lwr20 : the only other thing I can think of is that it was an older version of calicoctl.  We recently (2.3 though I think) tightened up "silent" failures to apply configuration.  Given I couldn't report - could you perhaps repro this for sanity?
