### ISSUE TITLE
Make KDD manifest work with kubeadm

### ISSUE THREAD

**Issue by caseydavenport** [projectcalico/calico#963]
The KDD manifests work with kubeadm, but currently require changing the default IP Pool to match the one kubeadm sets (or vice-versa).

We document it, but its [hidden away on the KDD page](http://docs.projectcalico.org/v2.3/getting-started/kubernetes/installation/hosted/kubernetes-datastore/).

Would be good to at [least point to it from the kubeadm doc](http://docs.projectcalico.org/v2.3/getting-started/kubernetes/installation/hosted/kubeadm/)

## Expected Behavior

KDD should work with kubeadm out-of-the-box, or we should at least document how to do it in the kubeadm doc.

## Current Behavior

Hard to find the _minimal_ docs for running KDD with kubeadm.

**Comment by heschlie** [comment]
It looks like there are some notes about it in the Requirements / Limitations part of the kubeadm page now. Though I recall talking about possibly updating our manifests with a CIDR that matches what kubeadm uses, was this something we're still interested in?

**Comment by caseydavenport** [comment]
> Though I recall talking about possibly updating our manifests with a CIDR that matches what kubeadm uses

kubeadm actually doesn't have a default CIDR, I was just looking into this :)

> It looks like there are some notes about it in the Requirements / Limitations part of the kubeadm page now

I don't see any notes about KDD there.  I think to close this issue we should at least document how to run KDD in the kubeadm doc.
