### ISSUE TITLE
Calico clobbers the whole forwarding mark even though we only need 1 bit

### ISSUE THREAD

**Issue by fasaxc** [projectcalico/calico#964]
We use the kernel's forwarding mark to return values between our iptables chains (where we need to distinguish between returning with our without a match).  We only need 1 bit to do that but, right now, we clobber the whole mark value rather than masking it off.

This conflicts with Kubernetes kube-proxy, which also uses the whole mark.  Both apps need to be changed to play nicely with each other.

**Comment by fasaxc** [comment]
I suggested adding configuration to kube-proxy to set its mask size: https://github.com/kubernetes/kubernetes/issues/19983 and to default to something that would work out-of-the-box for Calico.

**Comment by matthewdupre** [comment]
Kubernetes issue is fixed for 1.2.  By default it uses only bit 14 (chosen by fair dice roll, guaranteed to be random).
