### ISSUE TITLE
Large ARP Traffic Generated After Node Shutdown in Full Mesh BGP Mode

### ISSUE THREAD

**Issue by kangxiaoning** [projectcalico/calico#9652]
There is a cluster with 250 nodes using IP-in-IP and a full mesh BGP topology. When 50 nodes in the cluster were shut down but not removed from the Kubernetes cluster, a large number of ARP requests were generated in the network, putting significant pressure on the switches. The ARP traffic only decreased after the 50 shut-down nodes were removed from the cluster. What is the reason for this behavior?

**Comment by caseydavenport** [comment]
@kangxiaoning Calico doesn't really do anything special with respect to L2 / ARP between nodes.

That said, I suspect what is happening is that something (possibly Calico) is attempting to make network calls to those shutdown node IP addresses. The network calls require resolution of the node MAC addresses, which results in the ARP traffic.

Removing the nodes from your cluster tells the rest of the cluster that they don't exist any more, which means components (likely calico/node, if in full-mesh BGP) will stop attempting to connect to those nodes. 

One way to avoid this might be to use a non-full-mesh topology, or something like Calico VXLAN that doesn't use a node mesh.

**Comment by kangxiaoning** [comment]
If the behavior causing the ARP traffic is identified, would it be possible to reduce the ARP traffic through configuration parameters, such as probing every 10 seconds in the first minute and then every 5 minutes thereafter?

**Comment by caseydavenport** [comment]
> For new clusters, we are also considering avoiding the use of a full-mesh BGP topology.

Yeah, this probably makes sense. Either using a RR, ToR, or switching to Calico's VXLAN mode that doens't use BGP at all, would all resolve this. 

https://github.com/projectcalico/calico/blob/ff2669e2251e755a26826bc96e95740b7d78f831/confd/etc/calico/confd/templates/bird.cfg.template#L150

BIRD doesn't give us very nuanced control of the connect retry behavior - we could increase it, but that would make convergence slower in the mainline working case, so I don't think that would be right.
