### ISSUE TITLE
How to pass gobgp parameters

### ISSUE THREAD

**Issue by shamalco** [projectcalico/calico#966]
I am trying to configure bgp unnumbered on Calico using a gobgp backend. I been trying to figure out how to pass gobgp configuration parameters to the calico-node, but I can't find a method. The parameters I am trying to pass are the following:

(I am following the following GoBGP document(https://github.com/osrg/gobgp/blob/master/docs/sources/unnumbered-bgp.md)) 

```
[global.config]
  as = 64512
  router-id = "192.168.255.1"

[[neighbors]]
  [neighbors.config]
    neighbor-interface = "eth0"
```

The most important parameter I need to pass is (neighbors)

I am using the Calico self hosted manifest with k8s, how can I pass these values in the .yaml file?

**Comment by tmjd** [comment]
Have you seen this document? http://docs.projectcalico.org/v2.3/usage/configuration/bgp
It has information on configuring BGP in Calico.  Note that the yaml listed there must be applied with the calicoctl command. 

You could modify a Calico self hosted manifest and add a one time job that runs calicoctl (the calico/ctl container) and applies your desired configuration.

**Comment by shamalco** [comment]
Yes I have seen it. But its doesn't help what I am trying to do.

I am try to configure BGP unnumbered using Calico. To do so I need to configure the following:

```[[neighbors]]
  [neighbors.config]
    neighbor-interface = "eth0"```

The other value are supported such AS, etc.. But I want to pass the GoBGP neighbors parameter to the gobgp backend through Calico. How can I do that, is there a way to do that? I can't find anything in the documentation.

**Comment by tmjd** [comment]
@robbrockbank Can you help here?

**Comment by robbrockbank** [comment]
Hi @shamalco:  At the moment we do not have a mechanism for passing in additional GoBGP parameters.  Padding out the configuration model is something that is on my radar though but haven't actually pinned down any details yet.

**Comment by tmjd** [comment]
@robbrockbank Is there an issue that is tracking that already, I couldn't find one? If so could you link it here please?  If not could you create one and then link it?  Or we could leave this issue to track it but we should remove the support label and change it to feature request.

**Comment by robbrockbank** [comment]
Raised issue #28 in bgp-daemon.
Also applies to bird too.

**Comment by tmjd** [comment]
Thanks @robbrockbank.  @shamalco I'm going to close this issue since it is not currently possible what you are trying to do.  Please follow the issue linked above to keep track of the progress of the feature and please feel free to give your input on it too.
