### ISSUE TITLE
safe_decode_json doesn't catch JSONDecodeError

### ISSUE THREAD

**Issue by fasaxc** [projectcalico/calico#966]
I believe that's another error that could be raised there.

* [ ] Check that JSONDecodeError can be thrown
* [ ] Catch it

**Comment by alexwlchan** [comment]
You can throw a JSONDecodeError here, but [the exception is new in Python 3.5](https://docs.python.org/3.5/library/json.html?highlight=jsondecodeerror#json.JSONDecodeError). 

Here's a minimal example:

```python
import json

json_decoder = json.JSONDecoder()
json_decoder.decode(r'not really json')
```

When run under Python 2.7:

```
$ python2.7 safejson.py
Traceback (most recent call last):
  File "safejson.py", line 4, in <module>
    json_decoder.decode(r'not really json')
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
```

and then Python 3.5:

```
$ python3.5 safejson.py
Traceback (most recent call last):
  File "safejson.py", line 4, in <module>
    json_decoder.decode(r'not really json')
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

Earlier versions of Python 3 will also throw a ValueError.

**Comment by alexwlchan** [comment]
Note additionally that because the exception doesn’t exist in Python 3.4 or earlier, trying to catch it will cause another error.

Example:

```python
# saferjson.py
import json

json_decoder = json.JSONDecoder()
try:
    json_decoder.decode('not really json')
except json.JSONDecodeError:
    print("Something went wrong!")
```

On Python 2.7:

```
$ python2.7 caughtjson.py
Traceback (most recent call last):
  File "caughtjson.py", line 6, in <module>
    except json.JSONDecodeError:
AttributeError: 'module' object has no attribute 'JSONDecodeError'
```

and Python 3.5:

```
$ python3.5 caughtjson.py
Something went wrong!
```

**Comment by alexwlchan** [comment]
(Earlier comments scrubbed because they were only half-thought out.)

1. You can raise a JSONDecodeError if you pass bad JSON into `JSONDecoder.decode()`, but [the exception is new in Python 3.5](https://docs.python.org/3.5/library/json.html?highlight=jsondecodeerror#json.JSONDecodeError).

2. Since JSONDecodeError subclasses from ValueError, it can be caught with an `except ValueError` statement. This means that `safe_json_decode` is already catching the error.

Minimal example:

```python
# unsafejson.py
import json

json_decoder = json.JSONDecoder()
try:
    json_decoder.decode('not really json')
except ValueError:
    print("Something went wrong!")
```

And run in different versions of Python:

```
$ python2.7 unsafejson.py
Something went wrong!

$ python3.5 unsafejson.py
Something went wrong!
```

So I don’t think we need to do anything here.

**Comment by fasaxc** [comment]
Thanks for the analysis.  Closing.
