### ISSUE TITLE
"Error response from daemon" error when creating docker network

### ISSUE THREAD

**Issue by sjkeerthi** [projectcalico/calico#968]
While following the below doc
https://github.com/projectcalico/calico-containers/blob/master/docs/calico-with-docker/docker-network-plugin/README.md

While performing non cloud network

docker network create --driver calico --subnet=192.168.57.0/24 net1
Error response from daemon: error getting pools config from store during init: store for address space GlobalDefault not found

**Comment by fasaxc** [comment]
@sjkeerthi please can you run `calicoctl diags` to collect diagnostics and post the output?

**Comment by robbrockbank** [comment]
Hi @sjkeerthi. Could you let me know which version of docker you are using as well.  Thanks.

**Comment by sjkeerthi** [comment]
docker info
Containers: 2
Images: 17
Server Version: 1.9.1
Storage Driver: devicemapper
 Pool Name: docker-253:0-23731-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 107.4 GB
 Backing Filesystem: 
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 299.8 MB
 Data Space Total: 107.4 GB
 Data Space Available: 17.37 GB
 Metadata Space Used: 1.044 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.146 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.107-RHEL7 (2015-10-14)
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.10.0-327.el7.x86_64
Operating System: CentOS Linux 7 (Core)
CPUs: 1
Total Memory: 1.797 GiB
Name: Docker-Calico
ID: 2W5N:L4TV:67GZ:6QND:D5PV:N72S:BW2V:D4W5:DSRH:SZ2F:IIOK:PBF3
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled

**Comment by robbrockbank** [comment]
Hi @sjkeerthi 

The Docker info does not have a cluster store specified for the Docker daemon.  You will need to stop your Docker Daemon and restart it specifying the `--cluster-store` option pointing at your etcd data store.  See the link I posted above for the syntax of the cluster store option.

Let me know if you have difficulty getting this working.

Rob

**Comment by fasaxc** [comment]
Looks like this was a misconfiguration of docker.  @sjkeerthi please re-open if adding `--cluster-store` doesn't solve your issue.
