### ISSUE TITLE
Expand Calico's failsafe ports, for a k8s hosted install

### ISSUE THREAD

**Issue by neiljerram** [projectcalico/calico#968]
When Calico is installed using manifests into a k8s cluster, using its own etcd database, it makes sense to configure failsafe port lists so that the base system will continue working if host endpoints are defined without any additional policy.  (Notwithstanding the excellent advice at http://docs.projectcalico.org/master/getting-started/bare-metal/bare-metal#creating-basic-connectivity-and-calico-policy.)

Specifically:
- In this kind of install, Calico's etcd will be using a different port number from the etcd standard ones.  That port number should be allowed.
- In this kind of install, Calico's etcd will run as a k8s service, so its port number needs to be allowed both inbound and outbound.
- The BGP port number should be allowed as a failsafe, both inbound and outbound.

## Expected Behavior
If a host endpoint is defined, it should still work to run `calicoctl` from a cluster node.

## Current Behavior
If a host endpoint is defined, `calicoctl` times out after failing to connect to the calico-etcd service.

**Comment by neiljerram** [comment]
In general there are 2 things we can do here:

1. Expand Felix's hardcoded defaults for the failsafe ports.  That would obviously then affect all deployments.

2. Add environment settings to particular manifests, so as to add failsafe ports for those particular deployments.

**Comment by neiljerram** [comment]
Felix's current hardcoded defaults are:
```
	FailsafeInboundHostPorts  []ProtoPort `config:"port-list;tcp:22,udp:68;die-on-fail"`
	FailsafeOutboundHostPorts []ProtoPort `config:"port-list;tcp:2379,tcp:2380,tcp:4001,tcp:7001,udp:53,udp:67;die-on-fail"`
```

ISTM there is a good case for adding 179 (bgp) to these defaults, in both directions.

For the etcd port number in a k8s install, I suspect using manifest settings is better.  The current defaults already make sense for a deployment in which the etcd nodes are distinct from the workload hosts.

CC @fasaxc @song-jiang  WDYT?

**Comment by fasaxc** [comment]
Yes, that makes sense to me.  Needs to be a manifest setting, it's going to be different for each type of deployment.

**Comment by caseydavenport** [comment]
Looks to me like this has been addressed, so closing this. Reopen if I missed something!
