### ISSUE TITLE
No Binarys binaries.projectcalico.org 403 Forbidden

### ISSUE THREAD

**Issue by sjkeerthi** [projectcalico/calico#972]
Hi All,

When I try to access the latest release as per the below url 
403 Forbidden
nginx/1.4.6 (Ubuntu)

http://binaries.projectcalico.org/rpm_juno_testing
http://binaries.projectcalico.org/rpm_kilo_testing
http://binaries.projectcalico.org/rpm_testing

**Comment by fasaxc** [comment]
@sjkeerthi I don't think you can access those directories in a browser, they're designed to be accessed by YUM, which will access the files beneath those directories directly.

Please re-open if YUM cannot access the binaries when using those URLs as a repo source.
