### ISSUE TITLE
Calico for containers(Kubernetes) not freeing endpoints if minion rebooted

### ISSUE THREAD

**Issue by Nagodar** [projectcalico/calico#978]
Hi,

   I have found that if you reboot kubernetes minions (or restart docker service for example) the endpoints are not freed up.
```
root@kubcalico01:/var/log# calicoctl endpoint show
+-------------+-----------------+---------------------+---------------------+
|   Hostname  | Orchestrator ID | Number of Workloads | Number of Endpoints |
+-------------+-----------------+---------------------+---------------------+
| kubcalico02 |       cni       |          76         |          76         |
| kubcalico03 |       cni       |          25         |          25         |
+-------------+-----------------+---------------------+---------------------+
root@kubcalico01:/var/log# kubectl get pods --all-namespaces
NAMESPACE     NAME                                READY     STATUS    RESTARTS   AGE
default       kube-proxy-192.168.1.88             1/1       Running   2          17h
default       kube-proxy-192.168.1.89             1/1       Running   2          17h
kube-system   elasticsearch-logging-v1-gj3et      1/1       Running   0          15h
kube-system   elasticsearch-logging-v1-md56b      1/1       Running   0          15h
kube-system   fluentd-192.168.1.88                1/1       Running   1          15h
kube-system   fluentd-192.168.1.89                1/1       Running   1          15h
kube-system   kibana-logging-v1-00x2g             1/1       Running   0          15h
kube-system   kube-dns-v11-h6a05                  4/4       Running   1          16h
kube-system   kube-dns-v11-rtt4u                  4/4       Running   0          16h
kube-system   kube-registry-v0-8pa7e              1/1       Running   0          16h
kube-system   kube-ui-v5-sz0d0                    1/1       Running   0          16h
kube-system   kubernetes-dashboard-v0.1.0-bvgu9   1/1       Running   0          16h
```
Using cni, kubernetes 1.1.7, calico for containers 1.0.0, ubuntu 15.10

**Comment by caseydavenport** [comment]
Hi @Nagodar - I believe you're hitting this upstream Kubernetes issue: https://github.com/kubernetes/kubernetes/issues/14940

Essentially, the Kubelet isn't telling the network plugin that the old pods have been destroyed, and thus Calico doesn't know to delete those endpoints.

This is something that we'd like to fix and contribute back to the Kubernetes project.

**Comment by Nagodar** [comment]
How can I free this ip's/endpoints? I've tried with:
root@kubcalico01:/var/log# calicoctl ipam release 172.16.0.11
Address successfully released

but I continue viewing it in the enpoints:
| kubcalico03 |       cni       | ef5dca199f3edc1c5849d3bde12238597b33017d23cf5434d08df0e6b806af12 | b775fd94cf3911e591565254001e5957 |  172.16.0.11/32 | c2:55:62:e4:07:fe | calico-k8s-network | active |

thanks,

**Comment by caseydavenport** [comment]
@Nagodar `calicoctl ipam release` will release the IP allocation in Calico's IPAM so that it can be used again, but it won't delete the endpoint object itself.

Unfortunately, there isn't a really convenient way to free those endpoints at the moment.

You can try the ```calicoctl container remove <container ID>``` command, but this needs to be run on the host on which the pod was running.

Alternatively, you can use `etcdctl` to remove the endpoints directly from etcd.

```
# List all the endpoints on a given host.
etcdctl ls --recursive /calico/v1/host/<hostname>/workload/cni
```
```
# Remove the endpoints that you no longer want.
etcdctl rm /calico/v1/host/<hostname>/workload/cni/<workload_id>/endpoint/<endpoint_id>
```

**Comment by caseydavenport** [comment]
I'm going to close this one, since we've got a few different issues tracking this. (https://github.com/projectcalico/calico-containers/issues/1034)

This issue tracks adding this function to calicoctl: https://github.com/tigera/libcalico-go/issues/67
