### ISSUE TITLE
Calico-Kubernetes install instructions don't tell users to modify etcd-endpoints in policy-controller.yaml

### ISSUE THREAD

**Issue by djosborne** [projectcalico/calico#98]
Kubernetes install instructions say to download a manifest and run it, but the manifest needs to be filled in by the user before they launch it. We need to instruct the user to replace <etcd_endpoints> with their etcd location

See section [3. Deploy the Calico network policy controller](http://docs.projectcalico.org/master/getting-started/kubernetes/installation#deploy-the-calico-network-policy-controller)

**Comment by caseydavenport** [comment]
You can tackle this one, @djosborne :)

**Comment by djosborne** [comment]
Well that's embarrassing. It does say to modify it. I just glazed over it..
