### ISSUE TITLE
No way to configure log level for confd

### ISSUE THREAD

**Issue by caseydavenport** [projectcalico/calico#985]
## Expected Behavior

Should be able to configure confd log level.  I think it currently defaults to debug.

## Current Behavior

No configuration option.

## Possible Solution

Perhaps should just use the CALICO_BGP_LOGSEVERITYSCREEN variable.

## Context

Split out from here: https://github.com/projectcalico/calicoctl/issues/1633

**Comment by javefang** [comment]
This is currently generating about 9.6GB of logs daily from the 11 nodes that we have. I can see the "--log-level=debug" flag has been removed in the confd service definition. Can we cherry-pick that change back into the v2.6.2?

**Comment by javefang** [comment]
This is currently generating about 20GB of logs daily from the 11 nodes that we have. I can see the "--log-level=debug" flag has been removed in the confd service definition. Can we cherry-pick that change back into the v2.6.2?

**Comment by caseydavenport** [comment]
Yep, as you've spotted this is fixed in v3.0.0-beta1. We should also fix in v2.6.x.

**Comment by caseydavenport** [comment]
This is fixed in v3.0, and we've adjusted to info level in the soon-to-be-released v2.6.4, so I'm going to close this.
