### ISSUE TITLE
A question for enabling/porting Calico on ARM64 platform

### ISSUE THREAD

**Issue by TrevorTaoARM** [projectcalico/calico#992]
Dear Calico authors:
Now I am working on enabling/porting Calico on ARM64(aarch64) platform. For the calico_node, as you know it depends on a lot of components, such as bird, felix, calicoctl, calico-bgp-daemon, kube-policy-controller, typha and so on, which are given and used in the form of either docker images and/or binaries. 
But for the arm64 version of those components, they are not available from the official Calico docker hub repo and the release URL of github.com/projectcalico. 
So I have to build all those components from src for arm64 version. The question here is:
1. Where should I put those docker images and binaries of arm64 which are available for public access and acceptable to Calico community if I add the arm64 support for Calico to the community? 
   If I put them to my personal repo(still is public, now it is trevortaonb) on docker hub, is it acceptable to the community?or a certain repo of an open source org would be acceptable?
2. Since the lack of the arm64 binaries of those components of Calico, I would like to put them together and add them to a single docker image, like xxx/calico-components-aarch64:2.4.0, which would greatly facilitate the availability of those binaries.  Is this way acceptable?
3. If possible, could we add the corresponding arm64 binaries to the github/projectcalico/xxx/releases/download when we issue the x86 ones, which would greatly facilitate the work for arm64 porting.

Thank you very much,
Trevor Tao

**Comment by leonlcw92** [comment]
I spent two days install calico in arm64 .

**Comment by caseydavenport** [comment]
@TrevorTaoARM sorry for missing the questions in this issue.

> Where should I put those docker images and binaries of arm64 which are available for public access and acceptable to Calico community 

Ideally what I'd like to see is the arm binaries to be built as part of the upstream Calico release processes, so whenever a new Calico release is produced the arm64 binaries are produced with it.

You've found our go-build repo, which contains some of our common build infra: https://github.com/projectcalico/go-build/pull/13

Let's start by getting that PR merged once @fasaxc is back from vacation.

Once that's in, it will be a matter of updating the individual repos in question to support arm64 in their build + test workflow. Here's an example of that for ppc64le: https://github.com/projectcalico/kube-controllers/pull/138

> Since the lack of the arm64 binaries of those components of Calico, I would like to put them together and add them to a single docker image, like xxx/calico-components-aarch64:2.4.0, which would greatly facilitate the availability of those binaries. Is this way acceptable?

I'd like the packaging to mirror what we do for say amd64.  So, there would be a `calico/ctl-arm64` and a `calico/node-arm64` etc. 

> If possible, could we add the corresponding arm64 binaries to the github/projectcalico/xxx/releases/download when we issue the x86 ones, which would greatly facilitate the work for arm64 porting.

+1 - let's get the binaries produced and added to the standard releases.

**Comment by tmjd** [comment]
It looks like the 2 PRs @caseydavenport referenced have been merged.  Is there anything left to do for this issue?  Should it be closed?

**Comment by caseydavenport** [comment]
I think there is still ongoing work for multi-arch, including ARM, but I don't see a reason to keep this issue open any more.

**Comment by kfox1111** [comment]
What is the status? Are there images somewhere yet?
