### ISSUE TITLE
Is Calico support IP encryption on a network?

### ISSUE THREAD

**Issue by sharminakteranee** [projectcalico/calico#997]
On the same calico network, all of the ip-addresses of containers are directly connected to each other. Is there any way to encrypt the ip-addresses of the network?

**Comment by fasaxc** [comment]
> all of the ip-addresses of containers are directly connected to each other

This isn't quite true; we use routing to provide connectivity but we also provide security policy which decides who can talk to who.

If you need to encrypt your traffic, Calico should work just fine over an IPSEC network; we have a customer that is experimenting with this approach.  I don't think even IPSEC encrypts the IP address itself though.  What is your use case for encrypting the IP address?

Short of using onion routing, I can't see a good way to make that work, IP addresses need to be public or there's no way for routing to work!

**Comment by sharminakteranee** [comment]
I want to encrypt all of my container ip addresses, as I don't want to share all of my apps with all users on the same network. Just like openVswitch can, but the problem is network configuration have to be created for each nodes. On the otherhand, it is easy to create network on calico.

**Comment by fasaxc** [comment]
Are you worried about containers "snooping" the network?  Calico prevents that, there's no L2 broadcast domain.

**Comment by sharminakteranee** [comment]
In digital ocean, there is no internal network system like GCE or AWS. For that, I have to think about this ip encryption

**Comment by fasaxc** [comment]
Yes, the DO network is essentially public.  We strongly recommend deploying Calico over, say IPSEC in that environment, otherwise your etcd will be public!

**Comment by sharminakteranee** [comment]
Any suggestions for Calico with IPSEC?? I mean, by which process it can work with IPSEC.

**Comment by fasaxc** [comment]
If you configure IPSEC between your hosts, Calico should "just work"  Calico only requires an IP fabric underneath, which IPSEC provides.
