### ISSUE TITLE
The manifests in the v2.4.0 release artifact reference the rc1 for calico-node and the docs.

### ISSUE THREAD

**Issue by tmjd** [projectcalico/calico#997]
## Expected Behavior
The artifacts should reference/use the v2.4.0 versions.

## Current Behavior
The manifests in the v2.4.0 release artifact reference the rc1 for calico-node and the docs.

## Possible Solution
Either fix the artifact (which feels counter productive to the purpose of the artifact) or do a new release (v2.4.1) and ensure the artifact is correct.

## Steps to Reproduce (for bugs)
1.  Download Artifact
2.  Extract contents
3.  Look in manifests

## Context
v2.4.0 release of projectalico/calio

**Comment by caseydavenport** [comment]
Good spot - I've updated the release archive.

This was because the Makefile doesn't ensure a clean build, and the old artifacts were still laying around and thus got picked up in the build.

**Comment by tmjd** [comment]
Thanks @bradbeam for pointing it out to me. :+1:
